import type { Blueprint, Phrase, VocabSeed } from "./types";

/**
 * A second authored vocabulary expansion for the dedicated Words route.
 *
 * The tuples below are the curriculum: no runtime prompt, random word source,
 * seed expansion or generated translation is involved. Helpers only keep the
 * article and part-of-speech metadata consistent across four hundred entries.
 */
const focus = "Advanced, high-utility vocabulary for learners who already know everyday English or German and want more precise real-world expression.";

const adjective = (de: string, en: string): VocabSeed => ({ de, lookup: de, fallbackEn: en, tip: "adjective" });
const adverb = (de: string, en: string): VocabSeed => ({ de, lookup: de, fallbackEn: en, tip: "adverb" });
const verb = (de: string, en: string): VocabSeed => ({ de, lookup: de.replace(/^sich /, ""), fallbackEn: en, tip: "verb" });
const verbPhrase = (de: string, lookup: string, en: string): VocabSeed => ({ de, lookup, fallbackEn: en, tip: "verb phrase" });
const noun = (article: "der" | "die" | "das", de: string, en: string): VocabSeed => ({ de: `${article} ${de}`, lookup: de, fallbackEn: en, tip: "noun", article });

// The sixth argument arrived with the sentence packs: these started as word
// lists with a lesson name, and the sentences that teach the words in use are
// passed alongside the seeds. Packs not yet deepened simply omit it.
const pack = (label: string, level: string, theme: string, description: string, seeds: VocabSeed[], phrases: Phrase[] = []): Blueprint => ({
  label,
  level,
  theme,
  description,
  focus,
  seeds,
  dialogues: [],
  phrases,
});

export const advancedWordPartBlueprints2: Record<string, Blueprint> = {
  part421: pack("Part 421", "B2-C1", "Feelings and inner states", "Precise words for emotions, reactions and states of mind that come up in honest conversations.", [
    adjective("fassungslos", "stunned and speechless"),
    adjective("bestürzt", "dismayed"),
    adjective("verblüfft", "astonished"),
    adjective("verwirrt", "confused"),
    adjective("beunruhigt", "alarmed, worried"),
    adjective("überwältigt", "overwhelmed emotionally"),
    adjective("angespannt", "tense"),
    adjective("beleidigt", "offended"),
    adjective("verzweifelt", "desperate"),
    adjective("hoffnungsvoll", "hopeful"),
    adjective("zuversichtlich", "optimistic, confident"),
    adjective("unsicher", "unsure, insecure"),
    adjective("verunsichert", "unsettled, made unsure"),
    adjective("entschlossen", "determined"),
    adjective("unentschlossen", "undecided"),
    adjective("betroffen", "personally affected"),
    adjective("besorgt", "concerned"),
    adjective("schuldig", "guilty"),
    adjective("reumütig", "remorseful"),
    adjective("einsam", "lonely"),
    adjective("ausgelassen", "high-spirited"),
    adjective("niedergeschlagen", "downhearted"),
    adjective("aufgewühlt", "emotionally shaken"),
    adjective("entmutigt", "discouraged"),
    adjective("unterfordert", "not challenged enough"),
    adjective("gelangweilt", "bored"),
    adjective("fasziniert", "fascinated"),
    adjective("begeistert", "thrilled, enthusiastic"),
    adjective("gerührt", "touched emotionally"),
    adjective("ängstlich", "anxious, fearful"),
    adjective("schockiert", "shocked"),
    adjective("unwohl", "uneasy, unwell"),
    adjective("zufrieden", "satisfied, content"),
    adjective("unruhig", "restless"),
    adjective("bekümmert", "troubled, sorrowful"),
    adjective("gefasst", "composed after a shock"),
    adjective("ratlos", "at a loss"),
    adjective("sprachlos", "lost for words"),
    adjective("beklommen", "apprehensive, uneasy"),
    adjective("ernüchtert", "disillusioned, sobered"),
  ], [
    { de: "Fassungslos standen die Anwohner vor den Trümmern.", en: "The residents stood stunned in front of the rubble.", use: "The adjective fronts (Fassungslos standen ...) — stance and feeling in one image; die Anwohner = those living adjacent." },
    { de: "Bestürzt reagierte auch der Bürgermeister.", en: "The mayor, too, reacted with dismay.", use: "Fronted participle again, and auch AFTER the verb scopes over the subject: the mayor too, not only others." },
    { de: "Verblüfft stellte sie fest, dass ihr Plan aufging.", en: "To her astonishment, she found that her plan was working out.", use: "feststellen splits; ein Plan geht auf = a plan comes off — the arithmetic image of things dividing evenly." },
    { de: "Ich bin eher verwirrt als überzeugt.", en: "I am more confused than convinced.", use: "eher X als Y = more X than Y — the measured self-report; both participles work as plain adjectives." },
    { de: "Beunruhigt hat mich weniger der Fehler als die Reaktion darauf.", en: "What alarmed me was not so much the mistake as the reaction to it.", use: "weniger X als Y weighs two causes; darauf = to it, pointing back at der Fehler." },
    { de: "Von der Anteilnahme waren die Eltern sichtlich überwältigt.", en: "The parents were visibly overwhelmed by the sympathy.", use: "überwältigt von + Dativ; sichtlich = visibly — the observer's word, not the feeler's." },
    { de: "Vor dem Elfmeter war das ganze Stadion angespannt.", en: "Before the penalty, the whole stadium was tense.", use: "angespannt — tightened like a muscle; das ganze Stadion stands for everyone in it, the container for the crowd." },
    { de: "Er war beleidigt, ließ es sich aber nicht anmerken.", en: "He was offended but didn't let it show.", use: "sich (Dativ) etwas anmerken lassen = to let something show on you — the es is the feeling being hidden." },
    { de: "Verzweifelt suchte sie nach einem Ausweg, den es nicht gab.", en: "Desperately she searched for a way out that did not exist.", use: "suchen nach + Dativ; den es nicht gab — es gibt in the past inside a relative clause, the exit already missing." },
    { de: "Trotz der Prognose blieb sie zuversichtlich.", en: "Despite the prognosis, she remained confident.", use: "trotz + Genitiv; zuversichtlich — confidence pointed at the future, where selbstsicher points at oneself." },
    { de: "Unsicher war er nur beim freien Sprechen.", en: "He was only insecure when speaking freely.", use: "beim freien Sprechen — bei + nominalised infinitive with its adjective; the insecurity gets one precise location." },
    { de: "Die vielen Änderungen haben die Belegschaft verunsichert.", en: "All the changes have unsettled the workforce.", use: "verunsichern = to MAKE insecure — the ver- prefix turns the state into something done to people." },
    { de: "Entschlossen trat sie ans Mikrofon.", en: "She stepped up to the microphone with determination.", use: "One fronted participle paints the manner; ans Mikrofon treten — an + Akkusativ for stepping up to." },
    { de: "Wer unentschlossen wirkt, wird übergangen.", en: "Come across as undecided and you get passed over.", use: "übergangen werden = to be passed over — übergehen with a person as object; wirken for the fatal impression." },
    { de: "Von der Kürzung sind vor allem Familien betroffen.", en: "Families are the ones most affected by the cut.", use: "betroffen sein von = to be affected by; vor allem = above all, marking who bears it." },
    { de: "Besorgt fragte die Nachbarin, ob alles in Ordnung sei.", en: "The neighbour asked with concern whether everything was all right.", use: "ob-clause with Konjunktiv I sei — reported question; the fronted Besorgt gives the tone before the words." },
    { de: "Reumütig brachte er das geliehene Buch zurück.", en: "He returned the borrowed book, full of remorse.", use: "zurückbringen splits; das geliehene Buch — the participle attribute says the whole backstory in one word." },
    { de: "Ausgelassen feierten die Fans bis in den Morgen.", en: "The fans celebrated exuberantly into the morning.", use: "ausgelassen = let-loose, exuberant; bis in den Morgen — bis + in + Akkusativ stretches the night." },
    { de: "Nach der Absage war sie tagelang niedergeschlagen.", en: "After the rejection she was downhearted for days.", use: "niedergeschlagen — struck down, the German image for low spirits; tagelang, the -lang duration adverb again." },
    { de: "Der Brief hat ihn sichtlich aufgewühlt.", en: "The letter visibly shook him.", use: "aufwühlen = to churn up — water first, feelings second; the perfect with haben keeps the churner in view." },
    { de: "Unterfordert zu sein ermüdet auf Dauer genauso wie überfordert zu sein.", en: "Being underchallenged is, in the long run, as tiring as being overwhelmed.", use: "Two zu-infinitive subjects mirror the pack's pair unterfordert/überfordert; auf Dauer = in the long run." },
  ]),

  part422: pack("Part 422", "B2-C1", "Handling information precisely", "Useful actions for researching, organising, transforming and presenting information.", [
    verb("erfassen", "to capture, comprehend"),
    verb("bewirken", "to bring about"),
    verb("herbeiführen", "to cause deliberately"),
    verb("veranlassen", "to prompt, arrange for"),
    verb("ausüben", "to exercise, practise"),
    verb("anwenden", "to apply a method"),
    verb("einsetzen", "to deploy, use"),
    verb("entnehmen", "to take from, infer"),
    verb("festlegen", "to specify, set"),
    verb("feststellen", "to establish, determine"),
    verb("ermitteln", "to ascertain"),
    verb("nachverfolgen", "to track over time"),
    verb("aufdecken", "to uncover"),
    verb("enthüllen", "to reveal publicly"),
    verb("erforschen", "to research, explore"),
    verb("ordnen", "to put in order"),
    verb("bündeln", "to bundle, consolidate"),
    verb("zusammensetzen", "to assemble from parts"),
    verb("vereinheitlichen", "to standardise"),
    verb("kennzeichnen", "to label, mark"),
    verb("hervorbringen", "to produce, give rise to"),
    verb("bearbeiten", "to edit, process"),
    verb("abrufen", "to retrieve"),
    verb("umwandeln", "to convert"),
    verb("ablegen", "to file, store"),
    verb("aufzeichnen", "to record data"),
    verb("auslesen", "to read out data"),
    verb("verknüpfen", "to link together"),
    verb("abgleichen", "to cross-check"),
    verb("filtern", "to filter"),
    verb("verdichten", "to condense"),
    verb("aufbereiten", "to prepare for use"),
    verb("bereitstellen", "to provide, make available"),
    verb("nachbilden", "to recreate, model"),
    verb("abbilden", "to represent, map"),
    verb("registrieren", "to register, detect"),
    verb("übertragen", "to transmit, transfer"),
    verb("einscannen", "to scan in"),
    verb("archivieren", "to archive"),
    verb("protokollieren", "to log, document formally"),
  ], [
    { de: "Die Kamera erfasst jede Bewegung im Flur.", en: "The camera captures every movement in the corridor.", use: "erfassen = to capture/register — sensors erfassen; also to grasp mentally. One verb, both worlds." },
    { de: "Die Kampagne hat kaum etwas bewirkt.", en: "The campaign achieved next to nothing.", use: "bewirken = to bring about as an effect; kaum etwas = hardly anything, softer than nichts." },
    { de: "Die Entscheidung wurde bewusst herbeigeführt, nicht abgewartet.", en: "The decision was deliberately brought about, not waited for.", use: "herbeiführen = to engineer an outcome — the deliberate cousin of bewirken; the participle pair carries the contrast." },
    { de: "Wer hat die Überprüfung veranlasst?", en: "Who arranged for the review?", use: "veranlassen = to cause to happen through an instruction — the question asked when something official suddenly moves." },
    { de: "Das Amt übt hier lediglich eine Kontrollfunktion aus.", en: "The office merely exercises a supervisory function here.", use: "ausüben splits; Funktion/Amt/Druck ausüben — the verb for wielding roles and pressure." },
    { de: "Die Methode lässt sich auch auf kleinere Projekte anwenden.", en: "The method can also be applied to smaller projects.", use: "anwenden auf + Akkusativ; sich lassen keeps it impersonal — no one has to be doing the applying." },
    { de: "Dem Bericht ist zu entnehmen, dass die Kosten steigen.", en: "It can be gathered from the report that costs are rising.", use: "Dem X ist zu entnehmen, dass — the formal frame for 'the document says'; the source stands in the dative." },
    { de: "Die Ursache konnte bis heute nicht ermittelt werden.", en: "To this day, the cause has not been established.", use: "ermitteln = to determine by investigation — police and reports share this verb; bis heute = to this day." },
    { de: "Jede Änderung wird protokolliert und lässt sich später nachverfolgen.", en: "Every change is logged and can be traced later.", use: "protokollieren then nachverfolgen — the audit-trail pair; both keep the bureaucratic register." },
    { de: "Die Prüfung deckte gravierende Mängel auf.", en: "The audit uncovered serious defects.", use: "aufdecken splits — the investigative verb; gravierend = grave, the adjective auditors reach for." },
    { de: "Erst Jahre später wurde enthüllt, wer die Berichte geschrieben hatte.", en: "Only years later was it revealed who had written the reports.", use: "enthüllen = to unveil publicly — bigger stage than aufdecken; the passive plus indirect question carries the mystery." },
    { de: "Ordnen Sie die Belege nach Datum, nicht nach Betrag.", en: "Sort the receipts by date, not by amount.", use: "ordnen nach + Dativ = to order by; the repeated nach keeps the correction parallel." },
    { de: "Die Anfragen werden gebündelt und einmal pro Woche beantwortet.", en: "The queries are bundled and answered once a week.", use: "bündeln = to gather into one bundle — the office's favourite efficiency verb; two passives share werden." },
    { de: "Aus Einzelteilen dreier Studien wurde ein neues Gesamtbild zusammengesetzt.", en: "From pieces of three studies, a new overall picture was assembled.", use: "zusammensetzen aus = to assemble from; dreier — the rare bare genitive of drei, formal but alive." },
    { de: "Die Formulare wurden vereinheitlicht, es gibt jetzt nur noch eines.", en: "The forms have been standardised; there is only one now.", use: "vereinheitlichen — to make einheitlich; nur noch eines = only one left, the count after the cull." },
    { de: "Kennzeichnen Sie Änderungen farblich, sonst übersieht sie jeder.", en: "Mark changes in colour, otherwise everyone will miss them.", use: "farblich = by colour, the -lich adverb; übersehen — to overlook, stress on the SE, not to be split." },
    { de: "Alte Aufnahmen wurden digitalisiert und ins neue Archiv übertragen.", en: "Old recordings were digitised and transferred into the new archive.", use: "übertragen in + Akkusativ = to transfer into; the prefix über- stays put — no splitting." },
    { de: "Die Daten werden nachts abgeglichen, Abweichungen morgens gemeldet.", en: "The data is cross-checked overnight; deviations are reported in the morning.", use: "abgleichen = to reconcile two copies; nachts/morgens — the -s time adverbs frame the routine." },
    { de: "Filtern Sie die Liste zuerst nach Region, dann nach Größe.", en: "Filter the list first by region, then by size.", use: "filtern nach — same government as ordnen nach; zuerst ... dann sequences the clicks." },
    { de: "Auf einer Seite verdichtet, überzeugt der Bericht mehr als auf vierzig.", en: "Condensed to one page, the report is more convincing than at forty.", use: "A fronted participle phrase (Auf einer Seite verdichtet) sets the condition; verdichten — to compress prose like gas." },
    { de: "Die Rohdaten müssen erst aufbereitet werden, vorher sagen sie nichts.", en: "The raw data has to be processed first; before that, it tells you nothing.", use: "aufbereiten = to prepare for use — water, data and coal all get aufbereitet; vorher points back at erst." },
  ]),

  part423: pack("Part 423", "B2-C1", "Phrasal and separable verbs", "Common verb combinations whose real meaning is difficult to guess from their individual parts.", [
    verb("hinauslaufen", "to amount to, come down to"),
    verbPhrase("in Kauf nehmen", "Kauf nehmen", "to accept as a drawback"),
    verbPhrase("in Frage kommen", "Frage kommen", "to be a possibility"),
    verbPhrase("in Gang setzen", "Gang setzen", "to set in motion"),
    verb("anlegen", "to create, put on, invest"),
    verbPhrase("sich durchringen", "durchringen", "to bring oneself to do something"),
    verbPhrase("sich aufraffen", "aufraffen", "to summon the energy"),
    verbPhrase("sich raushalten", "raushalten", "to stay out of it"),
    verbPhrase("sich abfinden", "abfinden", "to come to terms with"),
    verb("verlassen", "to leave, rely on"),
    verb("beziehen", "to obtain, refer to"),
    verb("zurückgreifen", "to fall back on"),
    verb("absehen", "to foresee, refrain from"),
    verbPhrase("bestehen aus", "bestehen aus", "to consist of"),
    verbPhrase("sich eignen", "eignen", "to be suitable"),
    verb("eingehen", "to address, enter into"),
    verb("ankommen", "to depend on, arrive"),
    verb("hinauszögern", "to delay, drag out"),
    verb("übersehen", "to overlook"),
    verb("missachten", "to disregard"),
    verb("einsehen", "to realise, accept"),
    verb("nachsehen", "to check, look up"),
    verb("vorausplanen", "to plan ahead"),
    verb("nachprüfen", "to verify"),
    verb("zurückblicken", "to look back"),
    verb("vorwegnehmen", "to anticipate, pre-empt"),
    verb("zurückweisen", "to reject, turn away"),
    verb("aufweisen", "to exhibit, show"),
    verb("hindeuten", "to indicate, point to"),
    verb("hinweisen", "to point out"),
    verb("auskommen", "to manage, get along"),
    verb("auftreten", "to occur, appear"),
    verb("vorliegen", "to be present, available"),
    verb("zusammentreffen", "to coincide, meet"),
    verb("übereinstimmen", "to correspond, agree"),
    verb("unterbringen", "to accommodate, place"),
    verb("vorsorgen", "to make provision in advance"),
    verb("gegensteuern", "to take countermeasures"),
    verbPhrase("sich herausreden", "herausreden", "to talk one's way out of it"),
    verbPhrase("sich etwas vornehmen", "vornehmen", "to resolve to do something"),
  ], [
    { de: "Auf genau diese Frage läuft die ganze Debatte hinaus.", en: "This is exactly the question the whole debate comes down to.", use: "hinauslaufen auf + Akkusativ = to come down to; fronting auf genau diese Frage lands the destination first." },
    { de: "Die längere Anfahrt nehmen wir in Kauf.", en: "The longer commute is a price we are willing to pay.", use: "in Kauf nehmen = to accept as part of the bargain — the Kauf is figurative; the object fronts naturally." },
    { de: "Für die Leitung kommen nur zwei Kandidaten in Frage.", en: "Only two candidates are in the running for the leadership.", use: "in Frage kommen = to be a possibility; für names the role. Nicht in Frage kommen is the hard no." },
    { de: "Wer hat die Umstrukturierung eigentlich in Gang gesetzt?", en: "Who actually set the restructuring in motion?", use: "in Gang setzen — machinery language for processes; eigentlich again marks the question nobody can answer." },
    { de: "Sie konnte sich nicht durchringen, das Haus zu verkaufen.", en: "She could not bring herself to sell the house.", use: "sich durchringen + zu-infinitive — wringing oneself through to a decision; the struggle is in the ringen." },
    { de: "Raff dich auf, der Kurs fängt gleich an.", en: "Get yourself moving — the class is about to start.", use: "sich aufraffen = to summon the energy to get up; the du-imperative raff dich auf is pure everyday German." },
    { de: "Aus dem Streit der Nachbarn halte ich mich raus.", en: "I am staying out of the neighbours' quarrel.", use: "sich raushalten aus = to keep out of; raus- is the spoken heraus-. The aus-phrase fronts for topic." },
    { de: "Mit der Absage habe ich mich längst abgefunden.", en: "I came to terms with the rejection long ago.", use: "sich abfinden mit = to make peace with what will not change; längst = long since." },
    { de: "Die Zahlen bezieht das Amt direkt von den Krankenkassen.", en: "The office obtains the figures directly from the health insurers.", use: "beziehen von = to source from — also newspapers and pensions are bezogen; the object fronts again." },
    { de: "Im Notfall greifen wir auf die Rücklagen zurück.", en: "In an emergency, we fall back on the reserves.", use: "zurückgreifen auf + Akkusativ — reaching back for what was set aside; im Notfall = if the worst comes." },
    { de: "Von einer Anzeige hat sie abgesehen.", en: "She refrained from pressing charges.", use: "absehen von + Dativ = to refrain from; the other absehen (foresee) needs an object like das Ende." },
    { de: "Das Prüfungskomitee besteht aus fünf Mitgliedern.", en: "The examining committee consists of five members.", use: "bestehen aus + Dativ = to consist of; bestehen auf would be to insist — the preposition decides the meaning." },
    { de: "Der Raum eignet sich kaum für Besprechungen, es hallt zu sehr.", en: "The room is hardly suitable for meetings — it echoes too much.", use: "sich eignen für = to be suited to; es hallt — the impersonal es for room acoustics." },
    { de: "Zögern Sie die Entscheidung nicht weiter hinaus.", en: "Do not put the decision off any longer.", use: "hinauszögern splits in the imperative: zögern Sie ... hinaus; weiter = any further." },
    { de: "Wer Warnhinweise missachtet, handelt auf eigene Gefahr.", en: "Ignore the warnings and you act at your own risk.", use: "missachten = to disregard deliberately; auf eigene Gefahr — the sign-post phrase for transferred risk." },
    { de: "Irgendwann sah er ein, dass die Kritik berechtigt war.", en: "At some point he came to accept that the criticism was justified.", use: "einsehen = to see and admit — insight plus surrender in one verb; irgendwann = at some unnamed point." },
    { de: "Planen Sie voraus, aber prüfen Sie monatlich nach.", en: "Plan ahead, but check up on it monthly.", use: "vorausplanen and nachprüfen — the prefix pair voraus/nach turns one verb pair into a management principle." },
    { de: "Wer zurückblickt, sollte daraus etwas mitnehmen, sonst lohnt es nicht.", en: "If you look back, you should take something from it — otherwise it is not worth doing.", use: "zurückblicken = to look back; etwas mitnehmen aus — to take a lesson away, the seminar phrase." },
    { de: "Gute Moderation nimmt die Einwände vorweg.", en: "Good moderation anticipates the objections.", use: "vorwegnehmen = to pre-empt — saying it before the critic can; nimmt ... vorweg splits." },
    { de: "Der Verband wies die Vorwürfe umgehend zurück.", en: "The association immediately rejected the accusations.", use: "zurückweisen = to reject firmly — the press-release verb; umgehend from part429's family, without delay." },
    { de: "Vieles deutet auf einen technischen Defekt hin, ganz sicher ist es nicht.", en: "A lot points to a technical fault, but it is not certain.", use: "hindeuten auf again, now with vieles as subject — the evidence talks, nobody commits." },
  ]),

  part424: pack("Part 424", "C1", "Law, rights and disputes", "Practical vocabulary for news, contracts, police matters and understanding legal rights.", [
    noun("die", "Straftat", "criminal offence"),
    noun("die", "Ordnungswidrigkeit", "administrative offence"),
    noun("der", "Prozess", "court case, trial"),
    noun("der", "Zeuge", "witness"),
    noun("die", "Aussage", "statement, testimony"),
    noun("das", "Geständnis", "confession"),
    noun("der", "Verdacht", "suspicion"),
    noun("die", "Ermittlung", "investigation"),
    noun("die", "Anklage", "prosecution, charge"),
    noun("die", "Verteidigung", "legal defence"),
    noun("die", "Staatsanwaltschaft", "public prosecution service"),
    noun("die", "Haftstrafe", "prison sentence"),
    noun("die", "Geldstrafe", "financial penalty"),
    noun("die", "Bewährung", "probation"),
    noun("die", "Auflage", "legal condition, requirement"),
    noun("der", "Schadenersatz", "compensation for damages"),
    noun("die", "Regelung", "legal provision, arrangement"),
    noun("das", "Gesetz", "law, statute"),
    noun("der", "Gesetzentwurf", "draft law, bill"),
    noun("die", "Verfassung", "constitution"),
    noun("die", "Menschenwürde", "human dignity"),
    noun("die", "Gleichberechtigung", "equal rights"),
    noun("die", "Privatsphäre", "privacy"),
    noun("die", "Unschuldsvermutung", "presumption of innocence"),
    noun("die", "Verjährung", "statutory limitation"),
    noun("die", "Einigung", "settlement, agreement"),
    noun("die", "Rechtslage", "legal position"),
    noun("das", "Datenschutzrecht", "data protection law"),
    noun("der", "Haftbefehl", "arrest warrant"),
    noun("die", "Durchsuchung", "search by authorities"),
    noun("die", "Vorladung", "official summons"),
    noun("der", "Freispruch", "acquittal"),
    noun("der", "Schuldspruch", "guilty verdict"),
    noun("das", "Rechtsmittel", "legal remedy, appeal"),
    noun("die", "Schlichtung", "mediation, conciliation"),
    noun("der", "Tatbestand", "elements of an offence"),
    noun("der", "Rechtsbeistand", "legal counsel"),
    noun("das", "Beweismittel", "item of evidence"),
    noun("die", "Zeugenaussage", "witness testimony"),
    noun("der", "Verfahrensfehler", "procedural error"),
  ], [
    { de: "Falschparken ist eine Ordnungswidrigkeit, Fahrerflucht eine Straftat.", en: "Parking illegally is an administrative offence; hit-and-run is a crime.", use: "The second clause drops ist — parallel verdicts, one verb. The pair teaches the legal line German draws between the two." },
    { de: "Der Zeuge verweigerte die Aussage.", en: "The witness refused to testify.", use: "die Aussage verweigern is the fixed courtroom phrase — a noun where English uses the verb testify." },
    { de: "Ohne sein Geständnis wäre die Anklage kaum zu halten gewesen.", en: "Without his confession, the charges would hardly have held up.", use: "wäre ... zu halten gewesen stacks Konjunktiv II, sein + zu-infinitive and the past — peak formal German, worth reading twice." },
    { de: "Die Ermittlung wurde eingestellt, weil sich der Verdacht nicht erhärten ließ.", en: "The investigation was dropped because the suspicion could not be substantiated.", use: "ein Verfahren einstellen = to drop/discontinue proceedings — nothing to do with adjusting settings; sich erhärten lassen = to firm up." },
    { de: "Die Staatsanwaltschaft hat Anklage erhoben.", en: "The public prosecutor's office has filed charges.", use: "Anklage erheben — no article, fixed legal collocation; erheben also serves Klage (civil suit) and Einspruch (objection)." },
    { de: "Die Haftstrafe wurde zur Bewährung ausgesetzt.", en: "The prison sentence was suspended on probation.", use: "zur Bewährung aussetzen is THE formula of German sentencing — aussetzen here = to suspend, not to expose." },
    { de: "Statt einer Geldstrafe bekam er eine Auflage: hundert Stunden gemeinnützige Arbeit.", en: "Instead of a fine, he was given a condition: a hundred hours of community service.", use: "statt + Genitiv (statt einer Geldstrafe); the colon then spells the Auflage out. gemeinnützig = for the public good." },
    { de: "Auf Schadenersatz hat nur Anspruch, wer den Schaden auch nachweisen kann.", en: "Only those who can actually prove the damage are entitled to compensation.", use: "Anspruch haben auf + Akkusativ = to be entitled to; the wer-clause is postponed to the end for weight." },
    { de: "Der Gesetzentwurf scheiterte schon im Ausschuss.", en: "The bill already died in committee.", use: "scheitern = to fail definitively; schon marks how early. im Ausschuss — committee stage, where German bills quietly end." },
    { de: "Die Verfassung schützt die Menschenwürde an erster Stelle.", en: "The constitution protects human dignity first and foremost.", use: "an erster Stelle = in first place/foremost — an echo of Article 1, which every German pupil meets: Die Würde des Menschen ist unantastbar." },
    { de: "Die Gleichberechtigung steht seit 1949 im Grundgesetz, im Alltag steht sie oft nur auf dem Papier.", en: "Equal rights have been in the constitution since 1949; in everyday life they often exist only on paper.", use: "stehen twice with different force: im Gesetz stehen = to be written there; auf dem Papier stehen = to exist only nominally." },
    { de: "Die Unschuldsvermutung gilt bis zum rechtskräftigen Urteil.", en: "The presumption of innocence applies until the verdict is final.", use: "rechtskräftig = legally final (no appeal left) — the adjective carries what English needs a whole phrase for." },
    { de: "Nach zwanzig Jahren tritt bei den meisten Delikten Verjährung ein.", en: "After twenty years, most offences become time-barred.", use: "Verjährung tritt ein — limitation SETS IN; eintreten is the verb German law gives to states that begin by themselves." },
    { de: "Am Ende einigten sich beide Seiten außergerichtlich.", en: "In the end, the two sides settled out of court.", use: "sich einigen = to reach agreement; außergerichtlich packs 'out of court' into one adverb." },
    { de: "Die Rechtslage ist eindeutig, die Beweislage nicht.", en: "The legal position is clear; the evidence is not.", use: "-lage builds situation nouns: Rechtslage, Beweislage, Wetterlage. The clipped second clause lands the punch." },
    { de: "Der Haftbefehl wurde noch am selben Abend vollstreckt.", en: "The arrest warrant was executed that same evening.", use: "vollstrecken = to execute (a warrant, a judgment) — enforcement vocabulary; noch am selben Abend = that very evening." },
    { de: "Bei der Durchsuchung wurde das entscheidende Beweismittel gefunden.", en: "The decisive piece of evidence was found during the search.", use: "bei + Dativ noun = during/in the course of; das Beweismittel is countable where English 'evidence' is not." },
    { de: "Wer einer Vorladung nicht folgt, riskiert eine Geldstrafe.", en: "If you ignore an official summons, you risk a fine.", use: "einer Vorladung folgen — folgen takes the dative; here it means to comply, not to walk behind." },
    { de: "Auf den Freispruch in erster Instanz folgte der Schuldspruch in der zweiten.", en: "The acquittal at first instance was followed by a conviction at the second.", use: "in erster Instanz / in der zweiten — the court hierarchy; auf X folgt Y carries the reversal." },
    { de: "Gegen das Urteil ist kein Rechtsmittel mehr zulässig.", en: "No further appeal against the verdict is admissible.", use: "ein Rechtsmittel gegen + Akkusativ; kein ... mehr = no further. zulässig = admissible, the gatekeeping adjective of procedure." },
    { de: "Der Tatbestand des Betrugs setzt eine Täuschung voraus.", en: "Fraud, as defined in law, requires an act of deception.", use: "voraussetzen = to presuppose/require as an element; der Tatbestand + Genitiv names the offence being dissected." },
    { de: "Ein einziger Verfahrensfehler kann das ganze Urteil kippen.", en: "A single procedural error can overturn the entire verdict.", use: "kippen used transitively = to topple/overturn — colloquial force inside legal talk, which is exactly how lawyers speak." },
  ]),

  part425: pack("Part 425", "B2-C1", "Education, research and language", "Words needed to discuss learning, academic work, language and evidence with confidence.", [
    noun("die", "Betonung", "word stress, emphasis"),
    noun("die", "Silbe", "syllable"),
    noun("die", "Wortart", "part of speech"),
    noun("der", "Satzbau", "sentence structure"),
    noun("die", "Zeichensetzung", "punctuation"),
    noun("das", "Synonym", "word with the same meaning"),
    noun("das", "Gegenteil", "the opposite, the reverse"),
    noun("die", "Definition", "meaning statement"),
    noun("die", "Zusammenfassung", "summary"),
    noun("die", "Literatur", "academic literature"),
    noun("die", "Umfrage", "survey"),
    noun("die", "Methode", "method"),
    noun("die", "Analyse", "analysis"),
    noun("die", "Veröffentlichung", "publication"),
    noun("die", "Fachzeitschrift", "academic journal"),
    noun("die", "Begutachtung", "assessment, peer review"),
    noun("der", "Lehrplan", "curriculum"),
    noun("die", "Bewertung", "assessment, evaluation"),
    noun("die", "Qualifikation", "qualification"),
    noun("die", "Fortbildung", "professional development course"),
    noun("das", "Seminar", "seminar class"),
    noun("die", "Vorlesung", "university lecture"),
    noun("das", "Stipendium", "scholarship"),
    noun("das", "Lernziel", "learning objective"),
    noun("das", "Lernergebnis", "learning outcome"),
    noun("die", "Forschungsfrage", "research question"),
    noun("die", "Datenerhebung", "data collection"),
    noun("die", "Ausarbeitung", "written assignment"),
    noun("die", "Dissertation", "doctoral thesis"),
    noun("die", "Abhandlung", "academic treatise"),
    noun("das", "Nachschlagewerk", "reference work"),
    noun("der", "Fachbegriff", "technical term"),
    noun("das", "Sprachniveau", "language proficiency level"),
    noun("der", "Sprachgebrauch", "language usage"),
    noun("der", "Lehrstoff", "course material"),
    noun("die", "Vorkenntnis", "prior knowledge"),
    noun("die", "Prüfungsordnung", "examination regulations"),
    noun("die", "Quellenangabe", "source citation"),
    noun("die", "Fachliteratur", "specialist literature"),
    noun("der", "Fachbereich", "academic department, subject area"),
  ], [
    { de: "Die Betonung liegt auf der zweiten Silbe.", en: "The stress falls on the second syllable.", use: "die Betonung liegt auf + Dativ — the fixed frame for stress placement; the pack's first two words in one sentence." },
    { de: "Zu welcher Wortart gehört denn nun eigentlich das Wort selbst?", en: "So which part of speech does the word itself actually belong to?", use: "gehören zu = to belong to a category; denn nun eigentlich stacks three particles of mild exasperation." },
    { de: "Der deutsche Satzbau stellt das Verb an die zweite Stelle.", en: "German sentence structure puts the verb in second position.", use: "an die zweite Stelle stellen — Akkusativ for the placing; the sentence performs the rule it states." },
    { de: "In der Zeichensetzung unterscheiden sich die beiden Sprachen deutlich.", en: "The two languages differ markedly in their punctuation.", use: "sich unterscheiden in + Dativ names the field of the difference; deutlich = markedly." },
    { de: "Kaum ein Synonym deckt sich vollständig mit dem Gegenteil seines Gegenteils.", en: "Hardly any synonym is a perfect match for the opposite of its opposite.", use: "sich decken mit again — the near-match problem every learner meets; kaum ein = hardly any." },
    { de: "Eine gute Definition grenzt den Begriff nach beiden Seiten ab.", en: "A good definition delimits the term in both directions.", use: "abgrenzen nach — the definitional fencing verb; nach beiden Seiten = towards both sides." },
    { de: "Schreiben Sie zuerst die Zusammenfassung, sie zwingt zur Klarheit.", en: "Write the summary first — it forces you to be clear.", use: "zwingen zu + Dativ noun (zur Klarheit) — compulsion towards a state, no infinitive needed." },
    { de: "Die Umfrage wurde in drei Sprachen durchgeführt.", en: "The survey was conducted in three languages.", use: "eine Umfrage durchführen — surveys are CARRIED THROUGH in German; the passive hides the pollsters." },
    { de: "Erst die Analyse trennt Beobachtung von Deutung.", en: "Only analysis separates observation from interpretation.", use: "trennen von + Dativ; Erst + subject once more — the thing that finally does the job." },
    { de: "Die Veröffentlichung verzögert sich um ein halbes Jahr.", en: "Publication is delayed by half a year.", use: "sich verzögern um + Akkusativ measures the delay; um marks the size of the shift." },
    { de: "Die Fachzeitschrift nimmt nur jeden zehnten eingereichten Artikel an.", en: "The journal accepts only one in ten submitted articles.", use: "jeder zehnte = one in ten; eingereicht — the participle attribute doing a relative clause's work." },
    { de: "Vor der Begutachtung werden die Namen der Autoren entfernt.", en: "Before peer review, the authors' names are removed.", use: "The anonymising step in one passive sentence — vor + Dativ for the stage, werden ... entfernt for the deed." },
    { de: "Der neue Lehrplan lässt den Schulen mehr Freiheit.", en: "The new curriculum gives schools more freedom.", use: "jemandem etwas lassen = to leave someone something — the freedom is left, not granted." },
    { de: "Ohne das Stipendium hätte sie das Studium abbrechen müssen.", en: "Without the scholarship, she would have had to drop out.", use: "hätte ... müssen — Konjunktiv II past with a modal: the double infinitive abbrechen müssen stays at the end." },
    { de: "Formulieren Sie Lernziele so, dass sich ihr Erreichen prüfen lässt.", en: "Word learning objectives so that their achievement can be tested.", use: "ihr Erreichen — the nominalised infinitive with a possessive; so, dass + sich lassen builds testability in." },
    { de: "Zwischen Lernziel und Lernergebnis liegt der Unterricht.", en: "Between the learning objective and the learning outcome lies the teaching.", use: "zwischen X und Y liegt Z — geometry applied to pedagogy; the verb liegen again for abstract position." },
    { de: "Eine gute Forschungsfrage ist eng genug für eine Antwort.", en: "A good research question is narrow enough to be answerable.", use: "eng genug für — genug follows its adjective; the für-phrase names what the narrowness buys." },
    { de: "Die Dissertation baut auf einer früheren Abhandlung auf.", en: "The doctoral thesis builds on an earlier treatise.", use: "aufbauen auf + Dativ = to build on — the auf appears twice, once as prefix, once as preposition." },
    { de: "Jeder Fachbegriff wird beim ersten Auftreten erklärt.", en: "Every technical term is explained at its first occurrence.", use: "beim ersten Auftreten — bei + nominalised auftreten; the style rule stated in its own style." },
    { de: "Ihr Sprachniveau liegt deutlich über dem verlangten.", en: "Her language level is well above the required one.", use: "über dem verlangten — the participle stands for the elided Niveau; liegen über + Dativ for exceeding." },
    { de: "Ohne Quellenangabe ist das schönste Zitat wertlos.", en: "Without a source citation, the finest quotation is worthless.", use: "ohne + noun as bare condition once more; der Superlativ das schönste concedes beauty before dismissing it." },
  ]),

  part426: pack("Part 426", "B2-C1", "Business and markets", "High-value vocabulary for work, commerce, finance and understanding business news.", [
    noun("die", "Zielgruppe", "target audience"),
    noun("der", "Marktanteil", "market share"),
    noun("der", "Vertrieb", "sales and distribution"),
    noun("die", "Lieferkette", "supply chain"),
    noun("der", "Bestand", "stock, inventory"),
    noun("der", "Mitbewerber", "business competitor"),
    noun("der", "Auftrag", "order, assignment"),
    noun("der", "Lieferant", "supplier"),
    noun("der", "Hersteller", "manufacturer"),
    noun("der", "Dienstleister", "service provider"),
    noun("die", "Dienstleistung", "service offered"),
    noun("die", "Marke", "brand"),
    noun("der", "Ruf", "reputation"),
    noun("die", "Strategie", "business strategy"),
    noun("die", "Investition", "investment"),
    noun("die", "Marge", "profit margin"),
    noun("die", "Kosten", "costs"),
    noun("der", "Aufwand", "effort, expenditure"),
    noun("der", "Ertrag", "return, revenue"),
    noun("die", "Bilanz", "balance sheet"),
    noun("der", "Cashflow", "cash flow"),
    noun("die", "Liquidität", "liquidity"),
    noun("die", "Insolvenz", "insolvency"),
    noun("die", "Übernahme", "corporate takeover"),
    noun("die", "Fusion", "company merger"),
    noun("die", "Partnerschaft", "business partnership"),
    noun("die", "Beteiligung", "stake, participation"),
    noun("der", "Anteil", "share, proportion"),
    noun("der", "Kurs", "market price, rate"),
    noun("die", "Ausschüttung", "payout, distribution"),
    noun("das", "Wachstum", "growth"),
    noun("der", "Rückgang", "decline"),
    noun("die", "Schwankung", "fluctuation"),
    noun("das", "Geschäftsjahr", "financial year"),
    noun("das", "Geschäftsmodell", "business model"),
    noun("die", "Wertschöpfung", "value creation"),
    noun("die", "Preispolitik", "pricing policy"),
    noun("die", "Kundschaft", "customer base"),
    noun("das", "Umsatzziel", "sales target"),
    noun("das", "Fremdkapital", "borrowed capital"),
  ], [
    { de: "Wer ist die Zielgruppe, und was liest sie wirklich?", en: "Who is the target audience, and what do they actually read?", use: "The marketing double question; sie agrees with die Zielgruppe — singular, though it names many people." },
    { de: "Der Marktanteil wächst, die Marge schrumpft.", en: "Market share is growing; the margin is shrinking.", use: "Four words a side, no connector — the classic trade-off stated as a bare parallel." },
    { de: "Der Vertrieb verspricht Termine, die die Lieferkette nicht halten kann.", en: "Sales promises delivery dates the supply chain cannot keep.", use: "die die — relative pronoun straight after its article twin; Termine halten = to keep dates." },
    { de: "Der Bestand reicht noch für zwei Wochen.", en: "Stock will last another two weeks.", use: "reichen für + time span = to last for; noch adds the countdown feel." },
    { de: "Unser größter Mitbewerber ist inzwischen unser wichtigster Lieferant.", en: "Our biggest competitor is by now our most important supplier.", use: "Two superlatives on one subject — the awkward modern supply relationship in a single sentence." },
    { de: "Der Auftrag ging an den Hersteller mit dem besten Ruf, nicht mit dem besten Preis.", en: "The order went to the manufacturer with the best reputation, not the best price.", use: "an + Akkusativ for where orders GO; the repeated mit dem besten sharpens the correction." },
    { de: "Als Dienstleister lebt man von Empfehlungen.", en: "As a service provider, you live on recommendations.", use: "leben von + Dativ = to live off; als + role sets the perspective for the whole rule." },
    { de: "Die Marke ist mehr wert als alle Maschinen zusammen.", en: "The brand is worth more than all the machines put together.", use: "mehr wert sein als — wert with sein takes no case drama; zusammen = combined." },
    { de: "Ohne Strategie ist jede Investition eine Wette.", en: "Without a strategy, every investment is a bet.", use: "The bare-ohne frame delivering a business aphorism; eine Wette — the noun does the judging." },
    { de: "Der Aufwand ist gestiegen, der Ertrag nicht.", en: "The effort has gone up; the return has not.", use: "The elliptical second clause once more — nicht negates the elided ist gestiegen." },
    { de: "Die Bilanz sieht besser aus, als das Geschäft tatsächlich läuft.", en: "The balance sheet looks better than the business is actually doing.", use: "als + clause after a comparative; das Geschäft läuft — business RUNS in German idiom." },
    { de: "Am Cashflow erkennt man früher als an der Bilanz, ob es brennt.", en: "Cash flow shows you earlier than the balance sheet whether the house is on fire.", use: "erkennen an + Dativ = to tell by; ob es brennt — the fire idiom for trouble, impersonal es." },
    { de: "Die Liquidität ist gesichert, von Gewinn redet aber niemand mehr.", en: "Liquidity is secure — but nobody is talking about profit any more.", use: "reden von + Dativ; the fronted von Gewinn marks what has quietly left the conversation." },
    { de: "Kurz vor der Insolvenz kam das Übernahmeangebot.", en: "Shortly before the insolvency came the takeover bid.", use: "kurz vor + Dativ; the verb-subject inversion after the fronted time phrase gives it headline rhythm." },
    { de: "Nach der Fusion blieb von der kleineren Firma nur der Name.", en: "After the merger, all that remained of the smaller company was the name.", use: "bleiben von + Dativ = to be left of; nur der Name — the quiet obituary of an acquisition." },
    { de: "Die Beteiligung liegt knapp unter der Schwelle, ab der man mitreden darf.", en: "The stake is just below the threshold at which you get a say.", use: "ab der — the relative clause built on ab + Dativ; mitreden dürfen = to be allowed a say." },
    { de: "Der Kurs schwankt stärker als das Geschäft dahinter.", en: "The share price fluctuates more than the business behind it.", use: "dahinter = behind it — the pronoun-adverb pointing at the company underneath the ticker." },
    { de: "Wachstum um jeden Preis rächt sich im nächsten Abschwung.", en: "Growth at any price takes its revenge in the next downturn.", use: "um jeden Preis = at any price; sich rächen — the mistake itself comes back for revenge, reflexively." },
    { de: "Das Geschäftsjahr endet hier im März, nicht im Dezember.", en: "The financial year here ends in March, not December.", use: "The plain corporate fact with the nicht-correction — and a reminder that Geschäftsjahr and Kalenderjahr differ." },
    { de: "Erklären Sie mir das Geschäftsmodell in einem Satz.", en: "Explain the business model to me in one sentence.", use: "The investor's classic demand; in einem Satz = in a single sentence, the compression test." },
    { de: "Die Preispolitik entscheidet, welche Kundschaft man anzieht.", en: "Pricing decides which customers you attract.", use: "die Kundschaft — the customer base as a singular collective; anziehen = to attract, same verb as putting clothes on." },
  ]),

  part427: pack("Part 427", "B2-C1", "Media and culture", "Vocabulary for following news, discussing films and judging how stories are presented.", [
    noun("die", "Berichterstattung", "news coverage"),
    noun("die", "Schlagzeile", "headline"),
    noun("der", "Leitartikel", "editorial article"),
    noun("der", "Kommentar", "opinion commentary"),
    noun("die", "Rezension", "published review"),
    noun("die", "Kritik", "critique, criticism"),
    noun("die", "Handlung", "plot, storyline"),
    noun("die", "Figur", "fictional character"),
    noun("die", "Besetzung", "cast"),
    noun("die", "Regie", "direction of a production"),
    noun("das", "Drehbuch", "screenplay"),
    noun("die", "Kulisse", "set, backdrop"),
    noun("die", "Sendezeit", "broadcasting time"),
    noun("der", "Kulturteil", "arts and culture section"),
    noun("das", "Publikum", "audience"),
    noun("das", "Feuilleton", "arts and culture pages"),
    noun("die", "Debatte", "public debate"),
    noun("die", "Darstellung", "portrayal, depiction"),
    noun("die", "Botschaft", "underlying message"),
    noun("die", "Pressekonferenz", "press conference"),
    noun("die", "Perspektive", "point of view"),
    noun("der", "Kontext", "context"),
    noun("die", "Überschrift", "title, heading"),
    noun("die", "Bildunterschrift", "image caption"),
    noun("die", "Desinformation", "deliberate misinformation"),
    noun("die", "Zensur", "censorship"),
    noun("die", "Pressefreiheit", "freedom of the press"),
    noun("die", "Urheberschaft", "authorship"),
    noun("das", "Werk", "creative work"),
    noun("die", "Aufführung", "live performance"),
    noun("die", "Dokumentation", "documentary programme"),
    noun("die", "Reportage", "feature report"),
    noun("die", "Nachrichtensendung", "news programme"),
    noun("der", "Meinungsbeitrag", "opinion piece"),
    noun("die", "Ausstrahlung", "broadcast, airing"),
    noun("die", "Leserschaft", "readership"),
    noun("die", "Zuschauerquote", "audience rating"),
    noun("die", "Redaktion", "editorial team"),
    noun("die", "Chefredaktion", "editorial leadership"),
    noun("die", "Pressemitteilung", "press release"),
  ], [
    { de: "Die Berichterstattung war schneller als die Ermittlungen.", en: "The news coverage was faster than the investigation.", use: "The comparative als between two nominalised processes — a very German way to describe a scandal." },
    { de: "Die Schlagzeile verspricht mehr, als der Artikel hält.", en: "The headline promises more than the article delivers.", use: "mehr, als + clause; halten = to keep (a promise) — the verb binds headline and article into a contract." },
    { de: "Im Leitartikel bezieht die Zeitung klar Stellung.", en: "In its editorial, the paper takes a clear position.", use: "Stellung beziehen = to take a stand — military ground-taking borrowed by opinion pages." },
    { de: "Der Kommentar ist als solcher gekennzeichnet, die Nachricht bleibt neutral.", en: "The commentary is labelled as such; the news itself stays neutral.", use: "als solcher = as such, agreeing with der Kommentar; the separation German media law actually requires." },
    { de: "Die Rezension verriss den Film, das Publikum liebte ihn.", en: "The review tore the film apart; audiences loved it.", use: "verreißen = to pan/savage — the critic's verb; the flat second clause delivers the verdict that matters." },
    { de: "Kritik an der Regierung ist keine Majestätsbeleidigung.", en: "Criticising the government is not lèse-majesté.", use: "Kritik an + Dativ; Majestätsbeleidigung survives as the ironic word for treating criticism as a crime." },
    { de: "Die Handlung ist dünn, die Figuren tragen den Film.", en: "The plot is thin; the characters carry the film.", use: "tragen = to carry (the weight of a work) — the reviewer's stock verb for what holds a piece together." },
    { de: "Die Besetzung der Hauptrolle war ein Glücksgriff.", en: "The casting of the lead was a stroke of luck.", use: "der Glücksgriff = the lucky pick — greifen frozen into a noun of fortunate choosing." },
    { de: "Regie und Drehbuch stammen aus einer Hand.", en: "Direction and screenplay come from the same person.", use: "aus einer Hand = from one hand — single authorship; stammen aus for origin." },
    { de: "Hinter den Kulissen war der Streit längst entschieden.", en: "Behind the scenes, the dispute had long been settled.", use: "hinter den Kulissen — the stage-set idiom for what the audience never sees; längst entschieden, stative." },
    { de: "Zur besten Sendezeit läuft ausgerechnet eine Wiederholung.", en: "In the prime slot, of all things, a repeat is running.", use: "ausgerechnet = of all things — the particle of indignant disbelief; zur besten Sendezeit = prime time." },
    { de: "Das Feuilleton lobte ausgerechnet die Szene, die das Publikum langweilte.", en: "The arts pages praised precisely the scene that bored the audience.", use: "ausgerechnet again, now aimed at a noun — the gap between critics and crowds in one sentence." },
    { de: "Die Debatte drehte sich bald nur noch um die Person, nicht um das Werk.", en: "Before long, the debate was only about the person, no longer about the work.", use: "sich drehen um = to revolve around; nur noch marks the narrowing." },
    { de: "Die Darstellung der Ereignisse weicht vom Polizeibericht ab.", en: "The portrayal of events differs from the police report.", use: "abweichen von + Dativ — deviation measured against a reference document; the noun Darstellung stays neutral." },
    { de: "Die eigentliche Botschaft steht zwischen den Zeilen.", en: "The real message is between the lines.", use: "zwischen den Zeilen stehen — the fixed reading-idiom; eigentlich as adjective = the actual one." },
    { de: "Auf der Pressekonferenz waren Fragen unerwünscht.", en: "At the press conference, questions were unwelcome.", use: "unerwünscht = unwanted — the polite word for forbidden; auf + Konferenz, not an." },
    { de: "Ohne Kontext ist das Zitat eine Waffe.", en: "Without context, a quotation is a weapon.", use: "The bare-ohne aphorism frame, aimed at media literacy this time." },
    { de: "Die Bildunterschrift behauptet, was das Foto nicht zeigt.", en: "The caption claims what the photo does not show.", use: "A was-clause as object of behaupten — the caption-photo gap, the oldest trick in the misinformation drawer." },
    { de: "Desinformation braucht keine Lügen, ein schiefer Zusammenhang genügt.", en: "Disinformation needs no lies; a skewed context is enough.", use: "schief = crooked/skewed, here applied to framing; genügen closes the argument in one word." },
    { de: "Zensur beginnt selten mit Verboten, meist mit Angst.", en: "Censorship rarely begins with bans — usually it begins with fear.", use: "selten ... meist ... — two frequency adverbs carry the whole argument; the verb appears once." },
    { de: "Ohne Pressefreiheit erfährt der Wähler nur, was er erfahren soll.", en: "Without press freedom, voters only learn what they are meant to learn.", use: "erfahren twice — once free, once steered by sollen; the repetition is the point." },
    { de: "Die Zuschauerquote misst Aufmerksamkeit, nicht Qualität.", en: "Ratings measure attention, not quality.", use: "The X, nicht Y correction after the verb once more — the media-studies axiom in six words." },
  ]),

  part428: pack("Part 428", "B2-C1", "Materials and sensory detail", "Precise everyday descriptions for texture, shape, taste, atmosphere and physical properties.", [
    adjective("rau", "rough-textured"),
    adjective("matt", "matte, not shiny"),
    adjective("glänzend", "shiny, glossy"),
    adjective("durchsichtig", "transparent, see-through"),
    adjective("undurchsichtig", "opaque"),
    adjective("lichtdurchlässig", "translucent"),
    adjective("wasserdicht", "waterproof"),
    adjective("feuerfest", "fireproof"),
    adjective("hitzebeständig", "heat-resistant"),
    adjective("bruchsicher", "shatterproof"),
    adjective("biegsam", "flexible, bendable"),
    adjective("elastisch", "stretchy, elastic"),
    adjective("fest", "firm, solid"),
    adjective("locker", "loose"),
    adjective("dicht", "dense, tightly sealed"),
    adjective("porös", "porous"),
    adjective("hohl", "hollow"),
    adjective("massiv", "solid, massive"),
    adjective("flach", "flat, shallow"),
    adjective("steil", "steep"),
    adjective("schief", "crooked, slanted"),
    adjective("gewölbt", "curved, arched"),
    adjective("spitz", "pointed, sharp-tipped"),
    adjective("stumpf", "blunt, dull"),
    adjective("geruchsneutral", "odourless"),
    adjective("duftend", "fragrant"),
    adjective("muffig", "musty"),
    adjective("stechend", "pungent, piercing"),
    adjective("bitter", "bitter-tasting"),
    adjective("säuerlich", "slightly sour"),
    adjective("würzig", "spicy, savoury"),
    adjective("fade", "bland"),
    adjective("knusprig", "crispy, crunchy"),
    adjective("cremig", "creamy"),
    adjective("körnig", "grainy"),
    adjective("klebrig", "sticky"),
    adjective("feucht", "damp, moist"),
    adjective("frostig", "frosty"),
    adjective("schwül", "humid and muggy"),
    adjective("zugig", "draughty"),
  ], [
    { de: "Die Wand ist noch rau, sie wird erst morgen verputzt.", en: "The wall is still rough; it will not be plastered until tomorrow.", use: "erst morgen = not until tomorrow; verputzen — the builder's verb for plastering, in the passive." },
    { de: "Matt oder glänzend? Für den Flur empfehle ich matt.", en: "Matte or gloss? For the hallway I recommend matte.", use: "The paint-shop question verbatim; the adjectives stand bare because the noun (Farbe) is understood." },
    { de: "Der Vorhang ist lichtdurchlässig, aber nicht durchsichtig.", en: "The curtain lets light through, but you cannot see through it.", use: "lichtdurchlässig against durchsichtig — translucent versus transparent, the pack's finest distinction." },
    { de: "Wasserdicht heißt nicht dampfdicht, sonst würde die Jacke von innen nass.", en: "Waterproof does not mean vapour-proof, or the jacket would get wet from the inside.", use: "The X heißt nicht Y frame with a würde-consequence — outdoor-shop physics in one line." },
    { de: "Die Schale ist feuerfest, der Griff leider nicht.", en: "The dish is fireproof; the handle, unfortunately, is not.", use: "The clipped second clause with leider — product-review German at its most typical." },
    { de: "Hitzebeständig bis zweihundert Grad, sagt der Hersteller.", en: "Heat-resistant up to two hundred degrees, says the manufacturer.", use: "bis + number for the rated limit; sagt der Hersteller trails with the scepticism built in." },
    { de: "Das neue Display gilt als bruchsicher, getestet hat das noch niemand.", en: "The new display is said to be shatterproof — nobody has tested that yet.", use: "gelten als once more; getestet hat das noch niemand — the fronted participle carries the doubt." },
    { de: "Der Draht ist biegsam genug für enge Kurven.", en: "The wire is flexible enough for tight bends.", use: "genug after the adjective again; für names the task the flexibility must survive." },
    { de: "Der Bund ist elastisch und trägt nicht auf.", en: "The waistband is stretchy and does not add bulk.", use: "auftragen (intransitive) = to add bulk under clothing — a tailor's verb learners rarely meet in books." },
    { de: "Der Knoten muss fest sein, aber nicht zu fest.", en: "The knot needs to be tight, but not too tight.", use: "fest ... zu fest — the adjective against its own excess; zu marks the tipping point." },
    { de: "Lass die Schraube lieber etwas locker.", en: "Better leave the screw a little loose.", use: "lieber in an imperative = better/rather; etwas before an adjective = a little." },
    { de: "Das Fenster schließt nicht dicht, es zieht.", en: "The window does not seal properly — there is a draught.", use: "dicht schließen = to close tight; es zieht — the impersonal draught, the complaint behind zugig." },
    { de: "Klopf mal dagegen: Klingt es hohl oder massiv?", en: "Knock on it: does it sound hollow or solid?", use: "The DIY test as dialogue; dagegen = against it, and the oder-question offers the two pack adjectives." },
    { de: "Der Einstieg ins Becken ist flach, dahinter wird es steil.", en: "The entry into the pool is shallow; beyond that it gets steep.", use: "flach and steil around dahinter — the swimming-pool warning as a geometry lesson." },
    { de: "Das Bild hängt schief, einen Zentimeter nach links.", en: "The picture is hanging crooked — one centimetre to the left.", use: "schief hängen; the bare measurement phrase (einen Zentimeter nach links) gives the correction without a verb." },
    { de: "Die Decke ist leicht gewölbt, das täuscht beim Messen.", en: "The ceiling is slightly arched, which is deceptive when measuring.", use: "das täuscht — the das picks up the whole fact; beim Messen, bei + nominalised verb once more." },
    { de: "Vorsicht, die Kanten sind spitz, die Klingen längst stumpf.", en: "Careful — the corners are sharp, though the blades have long gone blunt.", use: "spitz for points, stumpf for edges that lost their bite; längst = long since." },
    { de: "Das Waschmittel ist geruchsneutral, die Seife duftend.", en: "The detergent is unscented; the soap is fragrant.", use: "geruchsneutral against duftend — absence and presence of smell, one clause each." },
    { de: "Im Keller riecht es muffig, wir müssen besser lüften.", en: "The cellar smells musty; we need to air it better.", use: "es riecht + adjective — the impersonal smell report; muffig is damp-cloth mustiness specifically." },
    { de: "Ein stechender Geruch lag in der Luft.", en: "A pungent smell hung in the air.", use: "in der Luft liegen = to hang in the air — for smells and tension alike; stechend, piercing like a sting." },
    { de: "Die Soße ist mir zu säuerlich, ihm zu fade.", en: "The sauce is too sour for me and too bland for him.", use: "jemandem zu + adjective — the dative names whose taste sets the limit; two verdicts, no verb repeated." },
    { de: "Außen knusprig, innen cremig: So muss das sein.", en: "Crispy outside, creamy inside: that is how it should be.", use: "außen/innen with two textures and no verb; So muss das sein — the formula of satisfied approval." },
  ]),

  part429: pack("Part 429", "B2-C1", "Connectors and natural flow", "Words and short chunks that make longer explanations sound coherent and natural.", [
    adverb("dementsprechend", "accordingly, in line with that"),
    adverb("andernfalls", "otherwise, if not"),
    adverb("ebenfalls", "likewise, also"),
    adverb("ebenso", "likewise, similarly"),
    adverb("zugleich", "at the same time"),
    adverb("zunächst", "initially, first of all"),
    adverb("bislang", "up to this point"),
    adverb("künftig", "in future"),
    adverb("umgehend", "without delay"),
    adverb("teilweise", "partly"),
    adverb("nahezu", "almost, virtually"),
    adverb("lediglich", "merely, only"),
    adverb("ausschließlich", "exclusively"),
    adverb("üblicherweise", "usually, as a rule"),
    adverb("möglicherweise", "possibly"),
    adverb("zumindest", "at least"),
    adverb("vorgeblich", "supposedly, ostensibly"),
    adverb("entsprechend", "correspondingly"),
    adverb("unabhängig davon", "regardless of that"),
    adverb("unterdessen", "in the meantime"),
    adverb("andernorts", "elsewhere"),
    adverb("nacheinander", "one after another"),
    adverb("miteinander", "with one another"),
    adverb("demgegenüber", "set against that"),
    adverb("des Weiteren", "further to this"),
    adverb("indessen", "meanwhile, however"),
    adverb("mithin", "therefore, thus"),
    adverb("ohnehin", "anyway, regardless"),
    adverb("in erster Linie", "primarily"),
    adverb("wohlgemerkt", "mind you, notably"),
    adverb("unterm Strich", "all things considered"),
    adverb("auf Dauer", "in the long run"),
    adverb("unter Umständen", "under certain circumstances"),
    adverb("im Gegensatz dazu", "in contrast to that"),
    adverb("in der Regel", "as a general rule"),
    adverb("im Großen und Ganzen", "by and large"),
    adverb("letzten Endes", "ultimately"),
    adverb("auf Anhieb", "on the first attempt"),
    adverb("nach wie vor", "still, as before"),
    adverb("nicht zuletzt", "not least"),
  ], [
    { de: "Die Nachfrage ist gestiegen, dementsprechend knapp ist die Ware.", en: "Demand has risen; the goods are correspondingly scarce.", use: "dementsprechend grades the adjective that follows it — the effect sized to its cause." },
    { de: "Zahlen Sie bis Freitag, andernfalls geht die Mahnung raus.", en: "Pay by Friday, otherwise the reminder goes out.", use: "andernfalls — the formal otherwise of payment letters; rausgehen, spoken register inside a threat." },
    { de: "Der Flug war günstig, das Hotel ebenfalls.", en: "The flight was cheap, and so was the hotel.", use: "ebenfalls carries the elided war günstig — likewise, with no verb repeated." },
    { de: "Sie spricht Polnisch und versteht ebenso Tschechisch.", en: "She speaks Polish and understands Czech just as well.", use: "ebenso = just as much — it compares the degree, where ebenfalls merely adds another item." },
    { de: "Das Medikament wirkt schnell und zugleich lange.", en: "The drug works fast and lasts long at the same time.", use: "zugleich joins two qualities usually traded off — simultaneity as the selling point." },
    { de: "Zunächst klang alles harmlos, bislang ist es das auch geblieben.", en: "At first it all sounded harmless, and so far it has stayed that way.", use: "zunächst and bislang bracket the timeline; es das geblieben — das stands for harmlos." },
    { de: "Künftig gilt die neue Regelung, umgehend gemeldet werden muss aber schon jetzt.", en: "The new rule applies from now on — but immediate reporting is required already today.", use: "künftig against schon jetzt; the fronted passive infinitive (gemeldet werden muss) is peak notice-board German." },
    { de: "Der Schaden ist teilweise gedeckt, lediglich der Eigenanteil bleibt offen.", en: "The damage is partly covered; only the excess remains outstanding.", use: "teilweise measures the coverage, lediglich shrinks what is left — two quantifiers doing the accounting." },
    { de: "Der Rabatt gilt ausschließlich für Neukunden.", en: "The discount applies exclusively to new customers.", use: "ausschließlich — exclusivity as an adverb; für + Akkusativ names the favoured group." },
    { de: "Üblicherweise dauert die Bearbeitung eine Woche, momentan eher drei.", en: "Processing usually takes a week — at the moment, more like three.", use: "üblicherweise sets the norm, eher drei corrects it; eher = more like, the honest estimate." },
    { de: "Möglicherweise reicht schon ein Anruf, zumindest einen Versuch ist es wert.", en: "Possibly a phone call is all it takes; at least it is worth a try.", use: "einen Versuch wert sein — worth an attempt, accusative; zumindest salvages the minimum." },
    { de: "Vorgeblich ging es um Sicherheit, tatsächlich um Kontrolle.", en: "Ostensibly it was about safety; in reality, about control.", use: "vorgeblich against tatsächlich — the stated versus the real purpose, es geht um shared by both." },
    { de: "Unabhängig davon, wie das Spiel ausgeht, steigt die Mannschaft ab.", en: "Regardless of how the game ends, the team is going down.", use: "unabhängig davon, wie ... — the concession frame with an indirect question inside; absteigen, football's relegation verb." },
    { de: "Unterdessen wartet die Kundschaft, andernorts längst beliefert wird sie dort schneller.", en: "Meanwhile the customers wait — elsewhere, where deliveries long since arrive, they are served faster.", use: "unterdessen and andernorts in one breath — time and place adverbs doing the work of two clauses." },
    { de: "Tragen Sie die Termine nacheinander ein, nicht alle auf einmal.", en: "Enter the appointments one after another, not all at once.", use: "nacheinander against auf einmal — sequence versus bulk; eintragen splits in the imperative." },
    { de: "Die Abteilungen reden wieder miteinander, das allein ist ein Fortschritt.", en: "The departments are talking to each other again — that alone is progress.", use: "miteinander reden = to talk WITH one another; das allein fronts the minimal win." },
    { de: "Des Weiteren behalten wir uns rechtliche Schritte vor.", en: "Furthermore, we reserve the right to take legal action.", use: "sich (Dativ) etwas vorbehalten = to reserve the right; Des Weiteren opens the second paragraph of every stern letter." },
    { de: "Der Beschluss ist gefallen, mithin gibt es nichts mehr zu verhandeln.", en: "The decision has been made; hence there is nothing left to negotiate.", use: "mithin — the jurist's therefore; ein Beschluss fällt, decisions FALL in German." },
    { de: "In erster Linie geht es um Vertrauen, erst dann um Geld.", en: "First and foremost this is about trust, and only then about money.", use: "in erster Linie ... erst dann — the ranking frame; es geht um distributes over both." },
    { de: "Wohlgemerkt: Niemand hat den Vorschlag abgelehnt, beschlossen ist er aber auch nicht.", en: "Mind you, nobody rejected the proposal — but it has not been adopted either.", use: "Wohlgemerkt: — the raised finger before a precision; aber auch nicht closes the trapdoor on both sides." },
    { de: "Unterm Strich hat sich der Umzug gelohnt.", en: "All things considered, the move was worth it.", use: "unterm Strich = below the line, where the sum lands; sich lohnen — the verb of things paying off." },
    { de: "Nach wie vor fehlt eine Antwort, nicht zuletzt auf die Kostenfrage.", en: "There is still no answer — not least to the question of costs.", use: "nach wie vor = as before, still; nicht zuletzt singles out the weightiest item while pretending not to." },
  ]),

  part430: pack("Part 430", "C1", "Cause, influence and outcomes", "Verbs for explaining why something happened and how one factor changes another.", [
    verb("hemmen", "to inhibit"),
    verb("begünstigen", "to favour, facilitate"),
    verb("erschweren", "to make more difficult"),
    verb("erleichtern", "to make easier"),
    verb("prägen", "to shape, leave a mark on"),
    verb("bestimmen", "to determine, define"),
    verb("lenken", "to direct, steer"),
    verb("steuern", "to control, manage"),
    verb("begrenzen", "to limit"),
    verb("einschränken", "to restrict"),
    verb("kompensieren", "to compensate for"),
    verb("unterstützen", "to support, assist"),
    verb("entlasten", "to relieve a burden"),
    verb("belasten", "to burden, strain"),
    verb("überfordern", "to overtax, overwhelm"),
    verb("unterschreiten", "to fall below"),
    verb("überschreiten", "to exceed"),
    verb("verfehlen", "to miss a target"),
    verb("erfüllen", "to fulfil, meet"),
    verb("beruhen", "to be based on"),
    verbPhrase("zurückzuführen sein", "zurückzuführen sein", "to be attributable to"),
    verbPhrase("führen zu", "führen zu", "to lead to"),
    verbPhrase("beitragen zu", "beitragen zu", "to contribute to"),
    verb("resultieren", "to result"),
    verb("entstehen", "to arise, come into being"),
    verb("hervorrufen", "to evoke, cause"),
    verbPhrase("nach sich ziehen", "nach sich ziehen", "to entail, bring about"),
    verb("darstellen", "to constitute, portray"),
    verb("betreffen", "to concern, affect"),
    verb("mindern", "to reduce, diminish"),
    verb("steigern", "to increase, enhance"),
    verb("verzerren", "to distort"),
    verb("verlagern", "to shift, relocate"),
    verb("verknappen", "to make scarce"),
    verb("freisetzen", "to release, set free"),
    verb("verteilen", "to distribute"),
    verb("umverteilen", "to redistribute"),
    verb("schützen", "to protect"),
    verb("schädigen", "to damage, harm"),
    verb("vorantreiben", "to drive forward"),
  ], [
    { de: "Angst hemmt das Lernen mehr, als es jeder Zeitdruck je könnte.", en: "Fear inhibits learning more than any deadline ever could.", use: "als + clause with könnte at the end; es stands in for das Lernen hemmen — the whole action, pronominalised." },
    { de: "Das milde Klima begünstigt den Anbau, die Bürokratie erschwert ihn.", en: "The mild climate favours farming; the red tape makes it harder.", use: "begünstigen and erschweren mirror each other around the comma; ihn picks up den Anbau." },
    { de: "Die neue Regel sollte alles erleichtern, eingetreten ist das Gegenteil.", en: "The new rule was supposed to make everything easier; what happened was the opposite.", use: "sollte = was supposed to; eingetreten ist das Gegenteil inverts to front the participle — the outcome lands first." },
    { de: "Die Jahre im Ausland haben ihn stärker geprägt als das Studium selbst.", en: "His years abroad shaped him more than the degree itself did.", use: "prägen = to leave a lasting stamp; selbst AFTER the noun means 'itself' — before it, it would mean 'even'." },
    { de: "Wer die Begriffe bestimmt, lenkt die Debatte.", en: "Whoever defines the terms steers the debate.", use: "bestimmen and lenken in one maxim; the wer-clause is the subject and the main verb follows straight after the comma." },
    { de: "Ein Projekt lässt sich steuern, ein Gerücht nicht.", en: "A project can be managed; a rumour cannot.", use: "sich steuern lassen = can be controlled; the clipped second half (ein Gerücht nicht) relies on the first for its verb." },
    { de: "Das Budget begrenzt das Mögliche, nicht das Nötige.", en: "The budget limits what is possible, not what is necessary.", use: "das Mögliche, das Nötige — adjectives nominalised into abstract nouns with das; German prose leans on this constantly." },
    { de: "Die neuen Vorgaben schränken den Spielraum der Kommunen erheblich ein.", en: "The new requirements considerably restrict the municipalities' room for manoeuvre.", use: "einschränken splits: schränken ... ein — the prefix waits at the very end, past the adverb erheblich." },
    { de: "Der höhere Lohn kompensiert die längere Anfahrt nur zum Teil.", en: "The higher pay only partly compensates for the longer commute.", use: "kompensieren takes a direct object — no für, unlike English compensate FOR; zum Teil = in part." },
    { de: "Das neue System soll die Mitarbeiter entlasten, nicht zusätzlich belasten.", en: "The new system is meant to take pressure off the staff, not add to it.", use: "entlasten and belasten share one object across the correction; zusätzlich = additionally, stacking the burden." },
    { de: "Wer ständig alles kontrollieren will, überfordert sich selbst.", en: "If you try to control everything all the time, you end up overtaxing yourself.", use: "überfordern never splits; sich selbst doubles down — you overtax YOURSELF, nobody else does it to you." },
    { de: "Die Einnahmen unterschritten die Erwartungen, die Kosten überschritten sie.", en: "Revenue fell short of expectations; costs exceeded them.", use: "unterschreiten and überschreiten are exact opposites with one shared object — sie = die Erwartungen." },
    { de: "Das Ziel wurde nicht verfehlt, es wurde nur später erfüllt.", en: "The target was not missed — it was just met later.", use: "verfehlen = to miss (a target); erfüllen = to meet it. Both in the processual passive with wurde." },
    { de: "Der Erfolg beruht auf Vertrauen, und Vertrauen beruht auf Zeit.", en: "Success rests on trust, and trust rests on time.", use: "beruhen auf + Dativ, chained: the object of the first clause becomes the subject of the second — a classic step figure." },
    { de: "Die Verspätung ist auf einen einzigen Fehler zurückzuführen.", en: "The delay is attributable to a single mistake.", use: "sein + zurückzuführen auf = is attributable to — the fixed passive-like frame of German reports." },
    { de: "Kleine Ursachen führen mitunter zu großen Wirkungen.", en: "Small causes sometimes lead to large effects.", use: "führen zu + Dativ; mitunter = now and then, a formal cousin of manchmal that lifts the register." },
    { de: "Jeder trägt dazu bei, ob er will oder nicht.", en: "Everyone contributes, whether they want to or not.", use: "beitragen zu splits around dazu; ob er will oder nicht = whether he wants to or not — the verb-final ob-clause." },
    { de: "Aus dem Missverständnis resultierte ein monatelanger Streit.", en: "A months-long dispute resulted from the misunderstanding.", use: "resultieren aus + Dativ — the OUTCOME is the subject, the source hides in the aus-phrase; monatelang again builds duration." },
    { de: "Wo Druck entsteht, entsteht auch Widerstand.", en: "Where pressure arises, resistance arises too.", use: "entstehen = to come into being; the doubled verb and bare nouns give the sentence the shape of a law." },
    { de: "Die Kampagne rief mehr Widerstand hervor, als sie Zustimmung erzeugte.", en: "The campaign provoked more resistance than it generated support.", use: "hervorrufen splits (rief ... hervor); the als-clause weighs the two effects against each other." },
    { de: "Eine solche Entscheidung zieht immer Folgekosten nach sich.", en: "A decision like that always entails follow-on costs.", use: "etwas nach sich ziehen = to entail — the sich belongs to the subject; Folgekosten = the costs that follow from it." },
    { de: "Der Bericht stellt die Lage schlimmer dar, als sie ist.", en: "The report portrays the situation as worse than it is.", use: "darstellen splits; schlimmer ..., als sie ist compares against reality — no wie here, als after a comparative." },
  ]),
};
