import type { Blueprint, Phrase, VocabSeed } from "./types";

/**
 * A second authored vocabulary expansion for the dedicated Words route.
 *
 * The tuples below are the curriculum: no runtime prompt, random word source,
 * seed expansion or generated translation is involved. Helpers only keep the
 * article and part-of-speech metadata consistent across four hundred entries.
 */
const focus = "Advanced, high-utility vocabulary for learners who already know everyday English or German and want more precise real-world expression.";

const adjective = (de: string, en: string): VocabSeed => ({ de, lookup: de, fallbackEn: en, tip: "adjective" });
const adverb = (de: string, en: string): VocabSeed => ({ de, lookup: de, fallbackEn: en, tip: "adverb" });
const verb = (de: string, en: string): VocabSeed => ({ de, lookup: de.replace(/^sich /, ""), fallbackEn: en, tip: "verb" });
const verbPhrase = (de: string, lookup: string, en: string): VocabSeed => ({ de, lookup, fallbackEn: en, tip: "verb phrase" });
const noun = (article: "der" | "die" | "das", de: string, en: string): VocabSeed => ({ de: `${article} ${de}`, lookup: de, fallbackEn: en, tip: "noun", article });

// The sixth argument arrived with the sentence packs: these started as word
// lists with a lesson name, and the sentences that teach the words in use are
// passed alongside the seeds. Packs not yet deepened simply omit it.
const pack = (label: string, level: string, theme: string, description: string, seeds: VocabSeed[], phrases: Phrase[] = []): Blueprint => ({
  label,
  level,
  theme,
  description,
  focus,
  seeds,
  dialogues: [],
  phrases,
});

export const advancedWordPartBlueprints2: Record<string, Blueprint> = {
  part421: pack("Part 421", "B2-C1", "Feelings and inner states", "Precise words for emotions, reactions and states of mind that come up in honest conversations.", [
    adjective("fassungslos", "stunned and speechless"),
    adjective("bestürzt", "dismayed"),
    adjective("verblüfft", "astonished"),
    adjective("verwirrt", "confused"),
    adjective("beunruhigt", "alarmed, worried"),
    adjective("überwältigt", "overwhelmed emotionally"),
    adjective("angespannt", "tense"),
    adjective("beleidigt", "offended"),
    adjective("verzweifelt", "desperate"),
    adjective("hoffnungsvoll", "hopeful"),
    adjective("zuversichtlich", "optimistic, confident"),
    adjective("unsicher", "unsure, insecure"),
    adjective("verunsichert", "unsettled, made unsure"),
    adjective("entschlossen", "determined"),
    adjective("unentschlossen", "undecided"),
    adjective("betroffen", "personally affected"),
    adjective("besorgt", "concerned"),
    adjective("schuldig", "guilty"),
    adjective("reumütig", "remorseful"),
    adjective("einsam", "lonely"),
    adjective("ausgelassen", "high-spirited"),
    adjective("niedergeschlagen", "downhearted"),
    adjective("aufgewühlt", "emotionally shaken"),
    adjective("entmutigt", "discouraged"),
    adjective("unterfordert", "not challenged enough"),
    adjective("gelangweilt", "bored"),
    adjective("fasziniert", "fascinated"),
    adjective("begeistert", "thrilled, enthusiastic"),
    adjective("gerührt", "touched emotionally"),
    adjective("ängstlich", "anxious, fearful"),
    adjective("schockiert", "shocked"),
    adjective("unwohl", "uneasy, unwell"),
    adjective("zufrieden", "satisfied, content"),
    adjective("unruhig", "restless"),
    adjective("bekümmert", "troubled, sorrowful"),
    adjective("gefasst", "composed after a shock"),
    adjective("ratlos", "at a loss"),
    adjective("sprachlos", "lost for words"),
    adjective("beklommen", "apprehensive, uneasy"),
    adjective("ernüchtert", "disillusioned, sobered"),
  ]),

  part422: pack("Part 422", "B2-C1", "Handling information precisely", "Useful actions for researching, organising, transforming and presenting information.", [
    verb("erfassen", "to capture, comprehend"),
    verb("bewirken", "to bring about"),
    verb("herbeiführen", "to cause deliberately"),
    verb("veranlassen", "to prompt, arrange for"),
    verb("ausüben", "to exercise, practise"),
    verb("anwenden", "to apply a method"),
    verb("einsetzen", "to deploy, use"),
    verb("entnehmen", "to take from, infer"),
    verb("festlegen", "to specify, set"),
    verb("feststellen", "to establish, determine"),
    verb("ermitteln", "to ascertain"),
    verb("nachverfolgen", "to track over time"),
    verb("aufdecken", "to uncover"),
    verb("enthüllen", "to reveal publicly"),
    verb("erforschen", "to research, explore"),
    verb("ordnen", "to put in order"),
    verb("bündeln", "to bundle, consolidate"),
    verb("zusammensetzen", "to assemble from parts"),
    verb("vereinheitlichen", "to standardise"),
    verb("kennzeichnen", "to label, mark"),
    verb("hervorbringen", "to produce, give rise to"),
    verb("bearbeiten", "to edit, process"),
    verb("abrufen", "to retrieve"),
    verb("umwandeln", "to convert"),
    verb("ablegen", "to file, store"),
    verb("aufzeichnen", "to record data"),
    verb("auslesen", "to read out data"),
    verb("verknüpfen", "to link together"),
    verb("abgleichen", "to cross-check"),
    verb("filtern", "to filter"),
    verb("verdichten", "to condense"),
    verb("aufbereiten", "to prepare for use"),
    verb("bereitstellen", "to provide, make available"),
    verb("nachbilden", "to recreate, model"),
    verb("abbilden", "to represent, map"),
    verb("registrieren", "to register, detect"),
    verb("übertragen", "to transmit, transfer"),
    verb("einscannen", "to scan in"),
    verb("archivieren", "to archive"),
    verb("protokollieren", "to log, document formally"),
  ]),

  part423: pack("Part 423", "B2-C1", "Phrasal and separable verbs", "Common verb combinations whose real meaning is difficult to guess from their individual parts.", [
    verb("hinauslaufen", "to amount to, come down to"),
    verbPhrase("in Kauf nehmen", "Kauf nehmen", "to accept as a drawback"),
    verbPhrase("in Frage kommen", "Frage kommen", "to be a possibility"),
    verbPhrase("in Gang setzen", "Gang setzen", "to set in motion"),
    verb("anlegen", "to create, put on, invest"),
    verbPhrase("sich durchringen", "durchringen", "to bring oneself to do something"),
    verbPhrase("sich aufraffen", "aufraffen", "to summon the energy"),
    verbPhrase("sich raushalten", "raushalten", "to stay out of it"),
    verbPhrase("sich abfinden", "abfinden", "to come to terms with"),
    verb("verlassen", "to leave, rely on"),
    verb("beziehen", "to obtain, refer to"),
    verb("zurückgreifen", "to fall back on"),
    verb("absehen", "to foresee, refrain from"),
    verbPhrase("bestehen aus", "bestehen aus", "to consist of"),
    verbPhrase("sich eignen", "eignen", "to be suitable"),
    verb("eingehen", "to address, enter into"),
    verb("ankommen", "to depend on, arrive"),
    verb("hinauszögern", "to delay, drag out"),
    verb("übersehen", "to overlook"),
    verb("missachten", "to disregard"),
    verb("einsehen", "to realise, accept"),
    verb("nachsehen", "to check, look up"),
    verb("vorausplanen", "to plan ahead"),
    verb("nachprüfen", "to verify"),
    verb("zurückblicken", "to look back"),
    verb("vorwegnehmen", "to anticipate, pre-empt"),
    verb("zurückweisen", "to reject, turn away"),
    verb("aufweisen", "to exhibit, show"),
    verb("hindeuten", "to indicate, point to"),
    verb("hinweisen", "to point out"),
    verb("auskommen", "to manage, get along"),
    verb("auftreten", "to occur, appear"),
    verb("vorliegen", "to be present, available"),
    verb("zusammentreffen", "to coincide, meet"),
    verb("übereinstimmen", "to correspond, agree"),
    verb("unterbringen", "to accommodate, place"),
    verb("vorsorgen", "to make provision in advance"),
    verb("gegensteuern", "to take countermeasures"),
    verbPhrase("sich herausreden", "herausreden", "to talk one's way out of it"),
    verbPhrase("sich etwas vornehmen", "vornehmen", "to resolve to do something"),
  ]),

  part424: pack("Part 424", "C1", "Law, rights and disputes", "Practical vocabulary for news, contracts, police matters and understanding legal rights.", [
    noun("die", "Straftat", "criminal offence"),
    noun("die", "Ordnungswidrigkeit", "administrative offence"),
    noun("der", "Prozess", "court case, trial"),
    noun("der", "Zeuge", "witness"),
    noun("die", "Aussage", "statement, testimony"),
    noun("das", "Geständnis", "confession"),
    noun("der", "Verdacht", "suspicion"),
    noun("die", "Ermittlung", "investigation"),
    noun("die", "Anklage", "prosecution, charge"),
    noun("die", "Verteidigung", "legal defence"),
    noun("die", "Staatsanwaltschaft", "public prosecution service"),
    noun("die", "Haftstrafe", "prison sentence"),
    noun("die", "Geldstrafe", "financial penalty"),
    noun("die", "Bewährung", "probation"),
    noun("die", "Auflage", "legal condition, requirement"),
    noun("der", "Schadenersatz", "compensation for damages"),
    noun("die", "Regelung", "legal provision, arrangement"),
    noun("das", "Gesetz", "law, statute"),
    noun("der", "Gesetzentwurf", "draft law, bill"),
    noun("die", "Verfassung", "constitution"),
    noun("die", "Menschenwürde", "human dignity"),
    noun("die", "Gleichberechtigung", "equal rights"),
    noun("die", "Privatsphäre", "privacy"),
    noun("die", "Unschuldsvermutung", "presumption of innocence"),
    noun("die", "Verjährung", "statutory limitation"),
    noun("die", "Einigung", "settlement, agreement"),
    noun("die", "Rechtslage", "legal position"),
    noun("das", "Datenschutzrecht", "data protection law"),
    noun("der", "Haftbefehl", "arrest warrant"),
    noun("die", "Durchsuchung", "search by authorities"),
    noun("die", "Vorladung", "official summons"),
    noun("der", "Freispruch", "acquittal"),
    noun("der", "Schuldspruch", "guilty verdict"),
    noun("das", "Rechtsmittel", "legal remedy, appeal"),
    noun("die", "Schlichtung", "mediation, conciliation"),
    noun("der", "Tatbestand", "elements of an offence"),
    noun("der", "Rechtsbeistand", "legal counsel"),
    noun("das", "Beweismittel", "item of evidence"),
    noun("die", "Zeugenaussage", "witness testimony"),
    noun("der", "Verfahrensfehler", "procedural error"),
  ], [
    { de: "Falschparken ist eine Ordnungswidrigkeit, Fahrerflucht eine Straftat.", en: "Parking illegally is an administrative offence; hit-and-run is a crime.", use: "The second clause drops ist — parallel verdicts, one verb. The pair teaches the legal line German draws between the two." },
    { de: "Der Zeuge verweigerte die Aussage.", en: "The witness refused to testify.", use: "die Aussage verweigern is the fixed courtroom phrase — a noun where English uses the verb testify." },
    { de: "Ohne sein Geständnis wäre die Anklage kaum zu halten gewesen.", en: "Without his confession, the charges would hardly have held up.", use: "wäre ... zu halten gewesen stacks Konjunktiv II, sein + zu-infinitive and the past — peak formal German, worth reading twice." },
    { de: "Die Ermittlung wurde eingestellt, weil sich der Verdacht nicht erhärten ließ.", en: "The investigation was dropped because the suspicion could not be substantiated.", use: "ein Verfahren einstellen = to drop/discontinue proceedings — nothing to do with adjusting settings; sich erhärten lassen = to firm up." },
    { de: "Die Staatsanwaltschaft hat Anklage erhoben.", en: "The public prosecutor's office has filed charges.", use: "Anklage erheben — no article, fixed legal collocation; erheben also serves Klage (civil suit) and Einspruch (objection)." },
    { de: "Die Haftstrafe wurde zur Bewährung ausgesetzt.", en: "The prison sentence was suspended on probation.", use: "zur Bewährung aussetzen is THE formula of German sentencing — aussetzen here = to suspend, not to expose." },
    { de: "Statt einer Geldstrafe bekam er eine Auflage: hundert Stunden gemeinnützige Arbeit.", en: "Instead of a fine, he was given a condition: a hundred hours of community service.", use: "statt + Genitiv (statt einer Geldstrafe); the colon then spells the Auflage out. gemeinnützig = for the public good." },
    { de: "Auf Schadenersatz hat nur Anspruch, wer den Schaden auch nachweisen kann.", en: "Only those who can actually prove the damage are entitled to compensation.", use: "Anspruch haben auf + Akkusativ = to be entitled to; the wer-clause is postponed to the end for weight." },
    { de: "Der Gesetzentwurf scheiterte schon im Ausschuss.", en: "The bill already died in committee.", use: "scheitern = to fail definitively; schon marks how early. im Ausschuss — committee stage, where German bills quietly end." },
    { de: "Die Verfassung schützt die Menschenwürde an erster Stelle.", en: "The constitution protects human dignity first and foremost.", use: "an erster Stelle = in first place/foremost — an echo of Article 1, which every German pupil meets: Die Würde des Menschen ist unantastbar." },
    { de: "Die Gleichberechtigung steht seit 1949 im Grundgesetz, im Alltag steht sie oft nur auf dem Papier.", en: "Equal rights have been in the constitution since 1949; in everyday life they often exist only on paper.", use: "stehen twice with different force: im Gesetz stehen = to be written there; auf dem Papier stehen = to exist only nominally." },
    { de: "Die Unschuldsvermutung gilt bis zum rechtskräftigen Urteil.", en: "The presumption of innocence applies until the verdict is final.", use: "rechtskräftig = legally final (no appeal left) — the adjective carries what English needs a whole phrase for." },
    { de: "Nach zwanzig Jahren tritt bei den meisten Delikten Verjährung ein.", en: "After twenty years, most offences become time-barred.", use: "Verjährung tritt ein — limitation SETS IN; eintreten is the verb German law gives to states that begin by themselves." },
    { de: "Am Ende einigten sich beide Seiten außergerichtlich.", en: "In the end, the two sides settled out of court.", use: "sich einigen = to reach agreement; außergerichtlich packs 'out of court' into one adverb." },
    { de: "Die Rechtslage ist eindeutig, die Beweislage nicht.", en: "The legal position is clear; the evidence is not.", use: "-lage builds situation nouns: Rechtslage, Beweislage, Wetterlage. The clipped second clause lands the punch." },
    { de: "Der Haftbefehl wurde noch am selben Abend vollstreckt.", en: "The arrest warrant was executed that same evening.", use: "vollstrecken = to execute (a warrant, a judgment) — enforcement vocabulary; noch am selben Abend = that very evening." },
    { de: "Bei der Durchsuchung wurde das entscheidende Beweismittel gefunden.", en: "The decisive piece of evidence was found during the search.", use: "bei + Dativ noun = during/in the course of; das Beweismittel is countable where English 'evidence' is not." },
    { de: "Wer einer Vorladung nicht folgt, riskiert eine Geldstrafe.", en: "If you ignore an official summons, you risk a fine.", use: "einer Vorladung folgen — folgen takes the dative; here it means to comply, not to walk behind." },
    { de: "Auf den Freispruch in erster Instanz folgte der Schuldspruch in der zweiten.", en: "The acquittal at first instance was followed by a conviction at the second.", use: "in erster Instanz / in der zweiten — the court hierarchy; auf X folgt Y carries the reversal." },
    { de: "Gegen das Urteil ist kein Rechtsmittel mehr zulässig.", en: "No further appeal against the verdict is admissible.", use: "ein Rechtsmittel gegen + Akkusativ; kein ... mehr = no further. zulässig = admissible, the gatekeeping adjective of procedure." },
    { de: "Der Tatbestand des Betrugs setzt eine Täuschung voraus.", en: "Fraud, as defined in law, requires an act of deception.", use: "voraussetzen = to presuppose/require as an element; der Tatbestand + Genitiv names the offence being dissected." },
    { de: "Ein einziger Verfahrensfehler kann das ganze Urteil kippen.", en: "A single procedural error can overturn the entire verdict.", use: "kippen used transitively = to topple/overturn — colloquial force inside legal talk, which is exactly how lawyers speak." },
  ]),

  part425: pack("Part 425", "B2-C1", "Education, research and language", "Words needed to discuss learning, academic work, language and evidence with confidence.", [
    noun("die", "Betonung", "word stress, emphasis"),
    noun("die", "Silbe", "syllable"),
    noun("die", "Wortart", "part of speech"),
    noun("der", "Satzbau", "sentence structure"),
    noun("die", "Zeichensetzung", "punctuation"),
    noun("das", "Synonym", "word with the same meaning"),
    noun("das", "Gegenteil", "the opposite, the reverse"),
    noun("die", "Definition", "meaning statement"),
    noun("die", "Zusammenfassung", "summary"),
    noun("die", "Literatur", "academic literature"),
    noun("die", "Umfrage", "survey"),
    noun("die", "Methode", "method"),
    noun("die", "Analyse", "analysis"),
    noun("die", "Veröffentlichung", "publication"),
    noun("die", "Fachzeitschrift", "academic journal"),
    noun("die", "Begutachtung", "assessment, peer review"),
    noun("der", "Lehrplan", "curriculum"),
    noun("die", "Bewertung", "assessment, evaluation"),
    noun("die", "Qualifikation", "qualification"),
    noun("die", "Fortbildung", "professional development course"),
    noun("das", "Seminar", "seminar class"),
    noun("die", "Vorlesung", "university lecture"),
    noun("das", "Stipendium", "scholarship"),
    noun("das", "Lernziel", "learning objective"),
    noun("das", "Lernergebnis", "learning outcome"),
    noun("die", "Forschungsfrage", "research question"),
    noun("die", "Datenerhebung", "data collection"),
    noun("die", "Ausarbeitung", "written assignment"),
    noun("die", "Dissertation", "doctoral thesis"),
    noun("die", "Abhandlung", "academic treatise"),
    noun("das", "Nachschlagewerk", "reference work"),
    noun("der", "Fachbegriff", "technical term"),
    noun("das", "Sprachniveau", "language proficiency level"),
    noun("der", "Sprachgebrauch", "language usage"),
    noun("der", "Lehrstoff", "course material"),
    noun("die", "Vorkenntnis", "prior knowledge"),
    noun("die", "Prüfungsordnung", "examination regulations"),
    noun("die", "Quellenangabe", "source citation"),
    noun("die", "Fachliteratur", "specialist literature"),
    noun("der", "Fachbereich", "academic department, subject area"),
  ]),

  part426: pack("Part 426", "B2-C1", "Business and markets", "High-value vocabulary for work, commerce, finance and understanding business news.", [
    noun("die", "Zielgruppe", "target audience"),
    noun("der", "Marktanteil", "market share"),
    noun("der", "Vertrieb", "sales and distribution"),
    noun("die", "Lieferkette", "supply chain"),
    noun("der", "Bestand", "stock, inventory"),
    noun("der", "Mitbewerber", "business competitor"),
    noun("der", "Auftrag", "order, assignment"),
    noun("der", "Lieferant", "supplier"),
    noun("der", "Hersteller", "manufacturer"),
    noun("der", "Dienstleister", "service provider"),
    noun("die", "Dienstleistung", "service offered"),
    noun("die", "Marke", "brand"),
    noun("der", "Ruf", "reputation"),
    noun("die", "Strategie", "business strategy"),
    noun("die", "Investition", "investment"),
    noun("die", "Marge", "profit margin"),
    noun("die", "Kosten", "costs"),
    noun("der", "Aufwand", "effort, expenditure"),
    noun("der", "Ertrag", "return, revenue"),
    noun("die", "Bilanz", "balance sheet"),
    noun("der", "Cashflow", "cash flow"),
    noun("die", "Liquidität", "liquidity"),
    noun("die", "Insolvenz", "insolvency"),
    noun("die", "Übernahme", "corporate takeover"),
    noun("die", "Fusion", "company merger"),
    noun("die", "Partnerschaft", "business partnership"),
    noun("die", "Beteiligung", "stake, participation"),
    noun("der", "Anteil", "share, proportion"),
    noun("der", "Kurs", "market price, rate"),
    noun("die", "Ausschüttung", "payout, distribution"),
    noun("das", "Wachstum", "growth"),
    noun("der", "Rückgang", "decline"),
    noun("die", "Schwankung", "fluctuation"),
    noun("das", "Geschäftsjahr", "financial year"),
    noun("das", "Geschäftsmodell", "business model"),
    noun("die", "Wertschöpfung", "value creation"),
    noun("die", "Preispolitik", "pricing policy"),
    noun("die", "Kundschaft", "customer base"),
    noun("das", "Umsatzziel", "sales target"),
    noun("das", "Fremdkapital", "borrowed capital"),
  ]),

  part427: pack("Part 427", "B2-C1", "Media and culture", "Vocabulary for following news, discussing films and judging how stories are presented.", [
    noun("die", "Berichterstattung", "news coverage"),
    noun("die", "Schlagzeile", "headline"),
    noun("der", "Leitartikel", "editorial article"),
    noun("der", "Kommentar", "opinion commentary"),
    noun("die", "Rezension", "published review"),
    noun("die", "Kritik", "critique, criticism"),
    noun("die", "Handlung", "plot, storyline"),
    noun("die", "Figur", "fictional character"),
    noun("die", "Besetzung", "cast"),
    noun("die", "Regie", "direction of a production"),
    noun("das", "Drehbuch", "screenplay"),
    noun("die", "Kulisse", "set, backdrop"),
    noun("die", "Sendezeit", "broadcasting time"),
    noun("der", "Kulturteil", "arts and culture section"),
    noun("das", "Publikum", "audience"),
    noun("das", "Feuilleton", "arts and culture pages"),
    noun("die", "Debatte", "public debate"),
    noun("die", "Darstellung", "portrayal, depiction"),
    noun("die", "Botschaft", "underlying message"),
    noun("die", "Pressekonferenz", "press conference"),
    noun("die", "Perspektive", "point of view"),
    noun("der", "Kontext", "context"),
    noun("die", "Überschrift", "title, heading"),
    noun("die", "Bildunterschrift", "image caption"),
    noun("die", "Desinformation", "deliberate misinformation"),
    noun("die", "Zensur", "censorship"),
    noun("die", "Pressefreiheit", "freedom of the press"),
    noun("die", "Urheberschaft", "authorship"),
    noun("das", "Werk", "creative work"),
    noun("die", "Aufführung", "live performance"),
    noun("die", "Dokumentation", "documentary programme"),
    noun("die", "Reportage", "feature report"),
    noun("die", "Nachrichtensendung", "news programme"),
    noun("der", "Meinungsbeitrag", "opinion piece"),
    noun("die", "Ausstrahlung", "broadcast, airing"),
    noun("die", "Leserschaft", "readership"),
    noun("die", "Zuschauerquote", "audience rating"),
    noun("die", "Redaktion", "editorial team"),
    noun("die", "Chefredaktion", "editorial leadership"),
    noun("die", "Pressemitteilung", "press release"),
  ]),

  part428: pack("Part 428", "B2-C1", "Materials and sensory detail", "Precise everyday descriptions for texture, shape, taste, atmosphere and physical properties.", [
    adjective("rau", "rough-textured"),
    adjective("matt", "matte, not shiny"),
    adjective("glänzend", "shiny, glossy"),
    adjective("durchsichtig", "transparent, see-through"),
    adjective("undurchsichtig", "opaque"),
    adjective("lichtdurchlässig", "translucent"),
    adjective("wasserdicht", "waterproof"),
    adjective("feuerfest", "fireproof"),
    adjective("hitzebeständig", "heat-resistant"),
    adjective("bruchsicher", "shatterproof"),
    adjective("biegsam", "flexible, bendable"),
    adjective("elastisch", "stretchy, elastic"),
    adjective("fest", "firm, solid"),
    adjective("locker", "loose"),
    adjective("dicht", "dense, tightly sealed"),
    adjective("porös", "porous"),
    adjective("hohl", "hollow"),
    adjective("massiv", "solid, massive"),
    adjective("flach", "flat, shallow"),
    adjective("steil", "steep"),
    adjective("schief", "crooked, slanted"),
    adjective("gewölbt", "curved, arched"),
    adjective("spitz", "pointed, sharp-tipped"),
    adjective("stumpf", "blunt, dull"),
    adjective("geruchsneutral", "odourless"),
    adjective("duftend", "fragrant"),
    adjective("muffig", "musty"),
    adjective("stechend", "pungent, piercing"),
    adjective("bitter", "bitter-tasting"),
    adjective("säuerlich", "slightly sour"),
    adjective("würzig", "spicy, savoury"),
    adjective("fade", "bland"),
    adjective("knusprig", "crispy, crunchy"),
    adjective("cremig", "creamy"),
    adjective("körnig", "grainy"),
    adjective("klebrig", "sticky"),
    adjective("feucht", "damp, moist"),
    adjective("frostig", "frosty"),
    adjective("schwül", "humid and muggy"),
    adjective("zugig", "draughty"),
  ]),

  part429: pack("Part 429", "B2-C1", "Connectors and natural flow", "Words and short chunks that make longer explanations sound coherent and natural.", [
    adverb("dementsprechend", "accordingly, in line with that"),
    adverb("andernfalls", "otherwise, if not"),
    adverb("ebenfalls", "likewise, also"),
    adverb("ebenso", "likewise, similarly"),
    adverb("zugleich", "at the same time"),
    adverb("zunächst", "initially, first of all"),
    adverb("bislang", "up to this point"),
    adverb("künftig", "in future"),
    adverb("umgehend", "without delay"),
    adverb("teilweise", "partly"),
    adverb("nahezu", "almost, virtually"),
    adverb("lediglich", "merely, only"),
    adverb("ausschließlich", "exclusively"),
    adverb("üblicherweise", "usually, as a rule"),
    adverb("möglicherweise", "possibly"),
    adverb("zumindest", "at least"),
    adverb("vorgeblich", "supposedly, ostensibly"),
    adverb("entsprechend", "correspondingly"),
    adverb("unabhängig davon", "regardless of that"),
    adverb("unterdessen", "in the meantime"),
    adverb("andernorts", "elsewhere"),
    adverb("nacheinander", "one after another"),
    adverb("miteinander", "with one another"),
    adverb("demgegenüber", "set against that"),
    adverb("des Weiteren", "further to this"),
    adverb("indessen", "meanwhile, however"),
    adverb("mithin", "therefore, thus"),
    adverb("ohnehin", "anyway, regardless"),
    adverb("in erster Linie", "primarily"),
    adverb("wohlgemerkt", "mind you, notably"),
    adverb("unterm Strich", "all things considered"),
    adverb("auf Dauer", "in the long run"),
    adverb("unter Umständen", "under certain circumstances"),
    adverb("im Gegensatz dazu", "in contrast to that"),
    adverb("in der Regel", "as a general rule"),
    adverb("im Großen und Ganzen", "by and large"),
    adverb("letzten Endes", "ultimately"),
    adverb("auf Anhieb", "on the first attempt"),
    adverb("nach wie vor", "still, as before"),
    adverb("nicht zuletzt", "not least"),
  ]),

  part430: pack("Part 430", "C1", "Cause, influence and outcomes", "Verbs for explaining why something happened and how one factor changes another.", [
    verb("hemmen", "to inhibit"),
    verb("begünstigen", "to favour, facilitate"),
    verb("erschweren", "to make more difficult"),
    verb("erleichtern", "to make easier"),
    verb("prägen", "to shape, leave a mark on"),
    verb("bestimmen", "to determine, define"),
    verb("lenken", "to direct, steer"),
    verb("steuern", "to control, manage"),
    verb("begrenzen", "to limit"),
    verb("einschränken", "to restrict"),
    verb("kompensieren", "to compensate for"),
    verb("unterstützen", "to support, assist"),
    verb("entlasten", "to relieve a burden"),
    verb("belasten", "to burden, strain"),
    verb("überfordern", "to overtax, overwhelm"),
    verb("unterschreiten", "to fall below"),
    verb("überschreiten", "to exceed"),
    verb("verfehlen", "to miss a target"),
    verb("erfüllen", "to fulfil, meet"),
    verb("beruhen", "to be based on"),
    verbPhrase("zurückzuführen sein", "zurückzuführen sein", "to be attributable to"),
    verbPhrase("führen zu", "führen zu", "to lead to"),
    verbPhrase("beitragen zu", "beitragen zu", "to contribute to"),
    verb("resultieren", "to result"),
    verb("entstehen", "to arise, come into being"),
    verb("hervorrufen", "to evoke, cause"),
    verbPhrase("nach sich ziehen", "nach sich ziehen", "to entail, bring about"),
    verb("darstellen", "to constitute, portray"),
    verb("betreffen", "to concern, affect"),
    verb("mindern", "to reduce, diminish"),
    verb("steigern", "to increase, enhance"),
    verb("verzerren", "to distort"),
    verb("verlagern", "to shift, relocate"),
    verb("verknappen", "to make scarce"),
    verb("freisetzen", "to release, set free"),
    verb("verteilen", "to distribute"),
    verb("umverteilen", "to redistribute"),
    verb("schützen", "to protect"),
    verb("schädigen", "to damage, harm"),
    verb("vorantreiben", "to drive forward"),
  ], [
    { de: "Angst hemmt das Lernen mehr, als es jeder Zeitdruck je könnte.", en: "Fear inhibits learning more than any deadline ever could.", use: "als + clause with könnte at the end; es stands in for das Lernen hemmen — the whole action, pronominalised." },
    { de: "Das milde Klima begünstigt den Anbau, die Bürokratie erschwert ihn.", en: "The mild climate favours farming; the red tape makes it harder.", use: "begünstigen and erschweren mirror each other around the comma; ihn picks up den Anbau." },
    { de: "Die neue Regel sollte alles erleichtern, eingetreten ist das Gegenteil.", en: "The new rule was supposed to make everything easier; what happened was the opposite.", use: "sollte = was supposed to; eingetreten ist das Gegenteil inverts to front the participle — the outcome lands first." },
    { de: "Die Jahre im Ausland haben ihn stärker geprägt als das Studium selbst.", en: "His years abroad shaped him more than the degree itself did.", use: "prägen = to leave a lasting stamp; selbst AFTER the noun means 'itself' — before it, it would mean 'even'." },
    { de: "Wer die Begriffe bestimmt, lenkt die Debatte.", en: "Whoever defines the terms steers the debate.", use: "bestimmen and lenken in one maxim; the wer-clause is the subject and the main verb follows straight after the comma." },
    { de: "Ein Projekt lässt sich steuern, ein Gerücht nicht.", en: "A project can be managed; a rumour cannot.", use: "sich steuern lassen = can be controlled; the clipped second half (ein Gerücht nicht) relies on the first for its verb." },
    { de: "Das Budget begrenzt das Mögliche, nicht das Nötige.", en: "The budget limits what is possible, not what is necessary.", use: "das Mögliche, das Nötige — adjectives nominalised into abstract nouns with das; German prose leans on this constantly." },
    { de: "Die neuen Vorgaben schränken den Spielraum der Kommunen erheblich ein.", en: "The new requirements considerably restrict the municipalities' room for manoeuvre.", use: "einschränken splits: schränken ... ein — the prefix waits at the very end, past the adverb erheblich." },
    { de: "Der höhere Lohn kompensiert die längere Anfahrt nur zum Teil.", en: "The higher pay only partly compensates for the longer commute.", use: "kompensieren takes a direct object — no für, unlike English compensate FOR; zum Teil = in part." },
    { de: "Das neue System soll die Mitarbeiter entlasten, nicht zusätzlich belasten.", en: "The new system is meant to take pressure off the staff, not add to it.", use: "entlasten and belasten share one object across the correction; zusätzlich = additionally, stacking the burden." },
    { de: "Wer ständig alles kontrollieren will, überfordert sich selbst.", en: "If you try to control everything all the time, you end up overtaxing yourself.", use: "überfordern never splits; sich selbst doubles down — you overtax YOURSELF, nobody else does it to you." },
    { de: "Die Einnahmen unterschritten die Erwartungen, die Kosten überschritten sie.", en: "Revenue fell short of expectations; costs exceeded them.", use: "unterschreiten and überschreiten are exact opposites with one shared object — sie = die Erwartungen." },
    { de: "Das Ziel wurde nicht verfehlt, es wurde nur später erfüllt.", en: "The target was not missed — it was just met later.", use: "verfehlen = to miss (a target); erfüllen = to meet it. Both in the processual passive with wurde." },
    { de: "Der Erfolg beruht auf Vertrauen, und Vertrauen beruht auf Zeit.", en: "Success rests on trust, and trust rests on time.", use: "beruhen auf + Dativ, chained: the object of the first clause becomes the subject of the second — a classic step figure." },
    { de: "Die Verspätung ist auf einen einzigen Fehler zurückzuführen.", en: "The delay is attributable to a single mistake.", use: "sein + zurückzuführen auf = is attributable to — the fixed passive-like frame of German reports." },
    { de: "Kleine Ursachen führen mitunter zu großen Wirkungen.", en: "Small causes sometimes lead to large effects.", use: "führen zu + Dativ; mitunter = now and then, a formal cousin of manchmal that lifts the register." },
    { de: "Jeder trägt dazu bei, ob er will oder nicht.", en: "Everyone contributes, whether they want to or not.", use: "beitragen zu splits around dazu; ob er will oder nicht = whether he wants to or not — the verb-final ob-clause." },
    { de: "Aus dem Missverständnis resultierte ein monatelanger Streit.", en: "A months-long dispute resulted from the misunderstanding.", use: "resultieren aus + Dativ — the OUTCOME is the subject, the source hides in the aus-phrase; monatelang again builds duration." },
    { de: "Wo Druck entsteht, entsteht auch Widerstand.", en: "Where pressure arises, resistance arises too.", use: "entstehen = to come into being; the doubled verb and bare nouns give the sentence the shape of a law." },
    { de: "Die Kampagne rief mehr Widerstand hervor, als sie Zustimmung erzeugte.", en: "The campaign provoked more resistance than it generated support.", use: "hervorrufen splits (rief ... hervor); the als-clause weighs the two effects against each other." },
    { de: "Eine solche Entscheidung zieht immer Folgekosten nach sich.", en: "A decision like that always entails follow-on costs.", use: "etwas nach sich ziehen = to entail — the sich belongs to the subject; Folgekosten = the costs that follow from it." },
    { de: "Der Bericht stellt die Lage schlimmer dar, als sie ist.", en: "The report portrays the situation as worse than it is.", use: "darstellen splits; schlimmer ..., als sie ist compares against reality — no wie here, als after a comparative." },
  ]),
};
