import type { Blueprint } from "./types";

/**
 * Vocabulary-only depth for learners who already know the everyday basics.
 *
 * These entries are deliberately authored rather than generated. Each card
 * has one useful German headword and one natural English meaning so the same
 * catalogue remains useful in either learning direction. Keep new packs
 * append-only after release: word progress is global by lemma, while the pack
 * order is the curriculum order used by the word ladder.
 */
const focus = "High-utility upper-intermediate and advanced vocabulary for dedicated word sittings, with exact German-English meanings in both learning directions.";

export const advancedWordPartBlueprints: Record<string, Blueprint> = {
  part411: {
    label: "Part 411",
    level: "B2-C1",
    theme: "Nuanced descriptions",
    description: "Precise adjectives and adverbs for describing quality, scale, certainty and change without relying on very basic words.",
    focus,
    seeds: [
      { de: "subtil", lookup: "subtil", fallbackEn: "subtle", tip: "adjective" },
      { de: "vage", lookup: "vage", fallbackEn: "vague", tip: "adjective" },
      { de: "unkompliziert", lookup: "unkompliziert", fallbackEn: "straightforward", tip: "adjective" },
      { de: "überwältigend", lookup: "überwältigend", fallbackEn: "overwhelming", tip: "adjective" },
      { de: "widerwillig", lookup: "widerwillig", fallbackEn: "reluctant", tip: "adjective" },
      { de: "eifrig", lookup: "eifrig", fallbackEn: "eager", tip: "adjective" },
      { de: "vernünftig", lookup: "vernünftig", fallbackEn: "reasonable", tip: "adjective" },
      { de: "unvernünftig", lookup: "unvernünftig", fallbackEn: "unreasonable", tip: "adjective" },
      { de: "irreführend", lookup: "irreführend", fallbackEn: "misleading", tip: "adjective" },
      { de: "voreingenommen", lookup: "voreingenommen", fallbackEn: "prejudiced, biased", tip: "adjective" },
      { de: "zerbrechlich", lookup: "zerbrechlich", fallbackEn: "fragile", tip: "adjective" },
      { de: "langlebig", lookup: "langlebig", fallbackEn: "durable", tip: "adjective" },
      { de: "reichlich", lookup: "reichlich", fallbackEn: "abundant", tip: "adjective" },
      { de: "präzise", lookup: "präzise", fallbackEn: "precise", tip: "adjective" },
      { de: "absichtlich", lookup: "absichtlich", fallbackEn: "intentional", tip: "adjective" },
      { de: "unangebracht", lookup: "unangebracht", fallbackEn: "out of place, inappropriate", tip: "adjective" },
      { de: "überzeugend", lookup: "überzeugend", fallbackEn: "convincing", tip: "adjective" },
      { de: "vernachlässigbar", lookup: "vernachlässigbar", fallbackEn: "too small to matter", tip: "adjective" },
      { de: "beträchtlich", lookup: "beträchtlich", fallbackEn: "substantial, considerable", tip: "adjective" },
      { de: "einheitlich", lookup: "einheitlich", fallbackEn: "uniform", tip: "adjective" },
      { de: "willkürlich", lookup: "willkürlich", fallbackEn: "arbitrary", tip: "adjective" },
      { de: "inhärent", lookup: "inhärent", fallbackEn: "inherent", tip: "adjective" },
      { de: "beispiellos", lookup: "beispiellos", fallbackEn: "unprecedented", tip: "adjective" },
      { de: "nachteilig", lookup: "nachteilig", fallbackEn: "detrimental", tip: "adjective" },
      { de: "vorteilhaft", lookup: "vorteilhaft", fallbackEn: "advantageous", tip: "adjective" },
      { de: "außergewöhnlich", lookup: "außergewöhnlich", fallbackEn: "exceptional", tip: "adjective" },
      { de: "übermäßig", lookup: "übermäßig", fallbackEn: "excessive", tip: "adjective" },
      { de: "mäßig", lookup: "mäßig", fallbackEn: "moderate", tip: "adjective" },
      { de: "aufeinanderfolgend", lookup: "aufeinanderfolgend", fallbackEn: "consecutive", tip: "adjective" },
      { de: "gleichzeitig", lookup: "gleichzeitig", fallbackEn: "simultaneous", tip: "adjective" },
      { de: "naheliegend", lookup: "naheliegend", fallbackEn: "obvious, natural", tip: "adjective" },
      { de: "praktisch", lookup: "praktisch", fallbackEn: "practical", tip: "adjective", use: "As an adjective it means practical; in some contexts it can also mean virtually or almost." },
      { de: "unverkennbar", lookup: "unverkennbar", fallbackEn: "unmistakable", tip: "adjective" },
      { de: "unauffällig", lookup: "unauffällig", fallbackEn: "unobtrusive, inconspicuous", tip: "adjective" },
      { de: "zwingend", lookup: "zwingend", fallbackEn: "compelling", tip: "adjective" },
      { de: "maßgeblich", lookup: "maßgeblich", fallbackEn: "decisive", tip: "adjective" },
      { de: "zweckmäßig", lookup: "zweckmäßig", fallbackEn: "fit for purpose", tip: "adjective" },
      { de: "unbestreitbar", lookup: "unbestreitbar", fallbackEn: "undeniable", tip: "adjective" },
      { de: "vorwiegend", lookup: "vorwiegend", fallbackEn: "mainly, predominantly", tip: "adverb" },
      { de: "unmissverständlich", lookup: "unmissverständlich", fallbackEn: "unequivocal", tip: "adjective" },
    ],
    dialogues: [],
    phrases: [],
  },
  part412: {
    label: "Part 412",
    level: "B2-C1",
    theme: "Character and social behaviour",
    description: "Useful words for describing how people behave, relate to others and come across in real life.",
    focus,
    seeds: [
      { de: "rücksichtslos", lookup: "rücksichtslos", fallbackEn: "inconsiderate", tip: "adjective" },
      { de: "durchsetzungsfähig", lookup: "durchsetzungsfähig", fallbackEn: "assertive", tip: "adjective" },
      { de: "kontaktfreudig", lookup: "kontaktfreudig", fallbackEn: "outgoing", tip: "adjective" },
      { de: "aufgeschlossen", lookup: "aufgeschlossen", fallbackEn: "open-minded", tip: "adjective" },
      { de: "engstirnig", lookup: "engstirnig", fallbackEn: "narrow-minded", tip: "adjective" },
      { de: "vertrauenswürdig", lookup: "vertrauenswürdig", fallbackEn: "trustworthy", tip: "adjective" },
      { de: "heuchlerisch", lookup: "heuchlerisch", fallbackEn: "hypocritical", tip: "adjective" },
      { de: "geduldig", lookup: "geduldig", fallbackEn: "patient with people", tip: "adjective" },
      { de: "ungeduldig", lookup: "ungeduldig", fallbackEn: "impatient", tip: "adjective" },
      { de: "großzügig", lookup: "großzügig", fallbackEn: "generous", tip: "adjective" },
      { de: "geizig", lookup: "geizig", fallbackEn: "stingy", tip: "adjective" },
      { de: "bescheiden", lookup: "bescheiden", fallbackEn: "modest, humble", tip: "adjective" },
      { de: "herablassend", lookup: "herablassend", fallbackEn: "condescending", tip: "adjective" },
      { de: "neidisch", lookup: "neidisch", fallbackEn: "envious", tip: "adjective" },
      { de: "hilfsbereit", lookup: "hilfsbereit", fallbackEn: "helpful", tip: "adjective" },
      { de: "abweisend", lookup: "abweisend", fallbackEn: "dismissive", tip: "adjective" },
      { de: "feindselig", lookup: "feindselig", fallbackEn: "hostile", tip: "adjective" },
      { de: "nahbar", lookup: "nahbar", fallbackEn: "approachable", tip: "adjective" },
      { de: "verlässlich", lookup: "verlässlich", fallbackEn: "dependable", tip: "adjective" },
      { de: "einfallsreich", lookup: "einfallsreich", fallbackEn: "resourceful", tip: "adjective" },
      { de: "nachlässig", lookup: "nachlässig", fallbackEn: "careless", tip: "adjective" },
      { de: "vorsichtig", lookup: "vorsichtig", fallbackEn: "cautious", tip: "adjective" },
      { de: "leichtgläubig", lookup: "leichtgläubig", fallbackEn: "gullible", tip: "adjective" },
      { de: "skeptisch", lookup: "skeptisch", fallbackEn: "sceptical", tip: "adjective" },
      { de: "selbstsicher", lookup: "selbstsicher", fallbackEn: "confident, self-assured", tip: "adjective" },
      { de: "beschämt", lookup: "beschämt", fallbackEn: "ashamed", tip: "adjective" },
      { de: "dankbar", lookup: "dankbar", fallbackEn: "grateful", tip: "adjective" },
      { de: "gewissenhaft", lookup: "gewissenhaft", fallbackEn: "conscientious", tip: "adjective" },
      { de: "unberechenbar", lookup: "unberechenbar", fallbackEn: "unpredictable", tip: "adjective" },
      { de: "schlagfertig", lookup: "schlagfertig", fallbackEn: "quick-witted", tip: "adjective" },
      { de: "taktvoll", lookup: "taktvoll", fallbackEn: "tactful", tip: "adjective" },
      { de: "untreu", lookup: "untreu", fallbackEn: "unfaithful", tip: "adjective" },
      { de: "treu", lookup: "treu", fallbackEn: "loyal", tip: "adjective" },
      { de: "mitfühlend", lookup: "mitfühlend", fallbackEn: "compassionate", tip: "adjective" },
      { de: "unhöflich", lookup: "unhöflich", fallbackEn: "rude", tip: "adjective" },
      { de: "gelassen", lookup: "gelassen", fallbackEn: "composed", tip: "adjective" },
      { de: "ehrgeizig", lookup: "ehrgeizig", fallbackEn: "ambitious", tip: "adjective" },
      { de: "anmaßend", lookup: "anmaßend", fallbackEn: "presumptuous", tip: "adjective" },
      { de: "verschlossen", lookup: "verschlossen", fallbackEn: "guarded", tip: "adjective" },
      { de: "verständnisvoll", lookup: "verständnisvoll", fallbackEn: "understanding", tip: "adjective" },
    ],
    dialogues: [],
    phrases: [],
  },
  part413: {
    label: "Part 413",
    level: "B2-C1",
    theme: "Communication and discussion",
    description: "Verbs for explaining a point, reacting to an argument and managing a difficult conversation precisely.",
    focus,
    seeds: [
      { de: "anerkennen", lookup: "anerkennen", fallbackEn: "to acknowledge", tip: "verb" },
      { de: "klarstellen", lookup: "klarstellen", fallbackEn: "to make clear", tip: "verb" },
      { de: "näher ausführen", lookup: "ausführen", fallbackEn: "to elaborate", tip: "verb" },
      { de: "umformulieren", lookup: "umformulieren", fallbackEn: "to rephrase", tip: "verb" },
      { de: "entmutigen", lookup: "entmutigen", fallbackEn: "to discourage", tip: "verb" },
      { de: "beruhigen", lookup: "beruhigen", fallbackEn: "to reassure", tip: "verb" },
      { de: "warnen", lookup: "warnen", fallbackEn: "to warn", tip: "verb" },
      { de: "benachrichtigen", lookup: "benachrichtigen", fallbackEn: "to notify", tip: "verb" },
      { de: "erwähnen", lookup: "erwähnen", fallbackEn: "to mention", tip: "verb" },
      { de: "auslassen", lookup: "auslassen", fallbackEn: "to omit", tip: "verb" },
      { de: "herunterspielen", lookup: "herunterspielen", fallbackEn: "to downplay", tip: "verb" },
      { de: "irreführen", lookup: "irreführen", fallbackEn: "to mislead", tip: "verb" },
      { de: "offenlegen", lookup: "offenlegen", fallbackEn: "to disclose", tip: "verb" },
      { de: "zurückhalten", lookup: "zurückhalten", fallbackEn: "to hold back, withhold", tip: "verb" },
      { de: "widersprechen", lookup: "widersprechen", fallbackEn: "to contradict", tip: "verb" },
      { de: "kritisieren", lookup: "kritisieren", fallbackEn: "to criticise", tip: "verb" },
      { de: "beschuldigen", lookup: "beschuldigen", fallbackEn: "to accuse", tip: "verb" },
      { de: "jemandem die Schuld geben", lookup: "Schuld geben", fallbackEn: "to blame", tip: "verb phrase" },
      { de: "einwenden", lookup: "einwenden", fallbackEn: "to object", tip: "verb" },
      { de: "anfordern", lookup: "anfordern", fallbackEn: "to request", tip: "verb" },
      { de: "sich erkundigen", lookup: "erkundigen", fallbackEn: "to enquire", tip: "verb" },
      { de: "umschreiben", lookup: "umschreiben", fallbackEn: "to express in other words", tip: "verb" },
      { de: "verkünden", lookup: "verkünden", fallbackEn: "to proclaim", tip: "verb" },
      { de: "behaupten", lookup: "behaupten", fallbackEn: "to assert, claim", tip: "verb" },
      { de: "erwidern", lookup: "erwidern", fallbackEn: "to retort", tip: "verb" },
      { de: "vermitteln", lookup: "vermitteln", fallbackEn: "to convey", tip: "verb" },
      { de: "ansprechen", lookup: "ansprechen", fallbackEn: "to raise a topic", tip: "verb" },
      { de: "bekräftigen", lookup: "bekräftigen", fallbackEn: "to reaffirm", tip: "verb" },
      { de: "preisgeben", lookup: "preisgeben", fallbackEn: "to divulge", tip: "verb" },
      { de: "ankündigen", lookup: "ankündigen", fallbackEn: "to announce", tip: "verb" },
      { de: "schildern", lookup: "schildern", fallbackEn: "to recount", tip: "verb" },
      { de: "formulieren", lookup: "formulieren", fallbackEn: "to formulate", tip: "verb" },
      { de: "zustimmen", lookup: "zustimmen", fallbackEn: "to agree", tip: "verb" },
      { de: "bezeugen", lookup: "bezeugen", fallbackEn: "to attest", tip: "verb" },
      { de: "nachfragen", lookup: "nachfragen", fallbackEn: "to ask a follow-up question", tip: "verb" },
      { de: "ergänzen", lookup: "ergänzen", fallbackEn: "to supplement", tip: "verb" },
      { de: "entgegnen", lookup: "entgegnen", fallbackEn: "to counter", tip: "verb" },
      { de: "abraten", lookup: "abraten", fallbackEn: "to advise against", tip: "verb" },
      { de: "einlenken", lookup: "einlenken", fallbackEn: "to concede", tip: "verb" },
      { de: "aufgreifen", lookup: "aufgreifen", fallbackEn: "to pick up on a point", tip: "verb" },
    ],
    dialogues: [],
    phrases: [],
  },
  part414: {
    label: "Part 414",
    level: "B2-C1",
    theme: "Work and organisation",
    description: "High-value verbs for projects, administration and decisions at work or in formal everyday life.",
    focus,
    seeds: [
      { de: "priorisieren", lookup: "priorisieren", fallbackEn: "to prioritise", tip: "verb" },
      { de: "delegieren", lookup: "delegieren", fallbackEn: "to delegate", tip: "verb" },
      { de: "koordinieren", lookup: "koordinieren", fallbackEn: "to coordinate", tip: "verb" },
      { de: "beaufsichtigen", lookup: "beaufsichtigen", fallbackEn: "to supervise", tip: "verb" },
      { de: "anwerben", lookup: "anwerben", fallbackEn: "to recruit", tip: "verb" },
      { de: "befördern", lookup: "befördern", fallbackEn: "to promote", tip: "verb" },
      { de: "einhalten", lookup: "einhalten", fallbackEn: "to comply with", tip: "verb", use: "Used for rules, deadlines, promises and agreements that must be observed." },
      { de: "genehmigen", lookup: "genehmigen", fallbackEn: "to approve", tip: "verb" },
      { de: "einplanen", lookup: "einplanen", fallbackEn: "to schedule", tip: "verb" },
      { de: "schätzen", lookup: "schätzen", fallbackEn: "to estimate", tip: "verb" },
      { de: "prognostizieren", lookup: "prognostizieren", fallbackEn: "to forecast", tip: "verb" },
      { de: "budgetieren", lookup: "budgetieren", fallbackEn: "to budget", tip: "verb" },
      { de: "in Rechnung stellen", lookup: "Rechnung stellen", fallbackEn: "to invoice", tip: "verb phrase" },
      { de: "überarbeiten", lookup: "überarbeiten", fallbackEn: "to revise", tip: "verb" },
      { de: "Korrektur lesen", lookup: "Korrektur lesen", fallbackEn: "to proofread", tip: "verb phrase" },
      { de: "bevollmächtigen", lookup: "bevollmächtigen", fallbackEn: "to authorise", tip: "verb" },
      { de: "durchsetzen", lookup: "durchsetzen", fallbackEn: "to enforce", tip: "verb" },
      { de: "gegen etwas verstoßen", lookup: "verstoßen", fallbackEn: "to violate", tip: "verb" },
      { de: "begleichen", lookup: "begleichen", fallbackEn: "to settle a payment", tip: "verb" },
      { de: "einführen", lookup: "einführen", fallbackEn: "to launch, introduce", tip: "verb" },
      { de: "zurückziehen", lookup: "zurückziehen", fallbackEn: "to withdraw", tip: "verb" },
      { de: "beibehalten", lookup: "beibehalten", fallbackEn: "to retain", tip: "verb" },
      { de: "auslagern", lookup: "auslagern", fallbackEn: "to outsource", tip: "verb" },
      { de: "optimieren", lookup: "optimieren", fallbackEn: "to optimise", tip: "verb" },
      { de: "einen Fehler beheben", lookup: "Fehler beheben", fallbackEn: "to troubleshoot", tip: "verb phrase" },
      { de: "aufrüsten", lookup: "aufrüsten", fallbackEn: "to upgrade", tip: "verb" },
      { de: "herabstufen", lookup: "herabstufen", fallbackEn: "to downgrade", tip: "verb" },
      { de: "abwickeln", lookup: "abwickeln", fallbackEn: "to process, handle", tip: "verb" },
      { de: "beschaffen", lookup: "beschaffen", fallbackEn: "to procure", tip: "verb" },
      { de: "freigeben", lookup: "freigeben", fallbackEn: "to release for use", tip: "verb" },
      { de: "einarbeiten", lookup: "einarbeiten", fallbackEn: "to onboard, train", tip: "verb" },
      { de: "befristen", lookup: "befristen", fallbackEn: "to make fixed-term", tip: "verb" },
      { de: "vermerken", lookup: "vermerken", fallbackEn: "to note on record", tip: "verb" },
      { de: "abrechnen", lookup: "abrechnen", fallbackEn: "to bill", tip: "verb" },
      { de: "bilanzieren", lookup: "bilanzieren", fallbackEn: "to take stock", tip: "verb" },
      { de: "entwerfen", lookup: "entwerfen", fallbackEn: "to draft", tip: "verb" },
      { de: "ausarbeiten", lookup: "ausarbeiten", fallbackEn: "to work out in detail", tip: "verb" },
      { de: "verwalten", lookup: "verwalten", fallbackEn: "to administer", tip: "verb" },
      { de: "zuordnen", lookup: "zuordnen", fallbackEn: "to assign", tip: "verb" },
      { de: "vereinbaren", lookup: "vereinbaren", fallbackEn: "to arrange, agree", tip: "verb" },
    ],
    dialogues: [],
    phrases: [],
  },
  part415: {
    label: "Part 415",
    level: "B2-C1",
    theme: "Change, difficulty and recovery",
    description: "Verbs for saying how situations develop, go wrong, improve or are brought back under control.",
    focus,
    seeds: [
      { de: "sich verschlechtern", lookup: "verschlechtern", fallbackEn: "to deteriorate", tip: "verb" },
      { de: "schwanken", lookup: "schwanken", fallbackEn: "to fluctuate", tip: "verb" },
      { de: "stabilisieren", lookup: "stabilisieren", fallbackEn: "to stabilise", tip: "verb" },
      { de: "beschleunigen", lookup: "beschleunigen", fallbackEn: "to accelerate", tip: "verb" },
      { de: "verlangsamen", lookup: "verlangsamen", fallbackEn: "to slow down", tip: "verb" },
      { de: "zusammenbrechen", lookup: "zusammenbrechen", fallbackEn: "to collapse", tip: "verb" },
      { de: "hervorgehen", lookup: "hervorgehen", fallbackEn: "to emerge", tip: "verb" },
      { de: "verschwinden", lookup: "verschwinden", fallbackEn: "to vanish", tip: "verb" },
      { de: "anhalten", lookup: "anhalten", fallbackEn: "to continue, persist", tip: "verb" },
      { de: "auslösen", lookup: "auslösen", fallbackEn: "to trigger", tip: "verb" },
      { de: "lindern", lookup: "lindern", fallbackEn: "to alleviate", tip: "verb" },
      { de: "überwinden", lookup: "überwinden", fallbackEn: "to overcome", tip: "verb" },
      { de: "angehen", lookup: "angehen", fallbackEn: "to tackle", tip: "verb" },
      { de: "sich mit etwas befassen", lookup: "befassen", fallbackEn: "to address, deal with", tip: "verb" },
      { de: "gefährden", lookup: "gefährden", fallbackEn: "to jeopardise", tip: "verb" },
      { de: "verwandeln", lookup: "verwandeln", fallbackEn: "to transform", tip: "verb" },
      { de: "wiederherstellen", lookup: "wiederherstellen", fallbackEn: "to restore", tip: "verb" },
      { de: "bewahren", lookup: "bewahren", fallbackEn: "to preserve", tip: "verb" },
      { de: "erneuern", lookup: "erneuern", fallbackEn: "to renew", tip: "verb" },
      { de: "verwerfen", lookup: "verwerfen", fallbackEn: "to discard", tip: "verb" },
      { de: "nach hinten losgehen", lookup: "nach hinten losgehen", fallbackEn: "to backfire", tip: "verb phrase" },
      { de: "zurechtkommen", lookup: "zurechtkommen", fallbackEn: "to cope", tip: "verb" },
      { de: "aufblühen", lookup: "aufblühen", fallbackEn: "to thrive", tip: "verb" },
      { de: "zurückgehen", lookup: "zurückgehen", fallbackEn: "to decrease, decline", tip: "verb" },
      { de: "schrumpfen", lookup: "schrumpfen", fallbackEn: "to shrink", tip: "verb" },
      { de: "stagnieren", lookup: "stagnieren", fallbackEn: "to stagnate", tip: "verb" },
      { de: "abweichen", lookup: "abweichen", fallbackEn: "to deviate", tip: "verb" },
      { de: "nachlassen", lookup: "nachlassen", fallbackEn: "to subside", tip: "verb" },
      { de: "ausgleichen", lookup: "ausgleichen", fallbackEn: "to offset", tip: "verb" },
      { de: "eindämmen", lookup: "eindämmen", fallbackEn: "to contain, limit", tip: "verb" },
      { de: "beheben", lookup: "beheben", fallbackEn: "to remedy", tip: "verb" },
      { de: "mit etwas umgehen", lookup: "umgehen", fallbackEn: "to handle, deal with", tip: "verb" },
      { de: "abfedern", lookup: "abfedern", fallbackEn: "to cushion, mitigate", tip: "verb" },
      { de: "entschärfen", lookup: "entschärfen", fallbackEn: "to defuse", tip: "verb" },
      { de: "ausarten", lookup: "ausarten", fallbackEn: "to get out of hand", tip: "verb" },
      { de: "fortbestehen", lookup: "fortbestehen", fallbackEn: "to persist", tip: "verb" },
      { de: "ausweichen", lookup: "ausweichen", fallbackEn: "to evade", tip: "verb" },
      { de: "voranschreiten", lookup: "voranschreiten", fallbackEn: "to advance", tip: "verb" },
      { de: "überdauern", lookup: "überdauern", fallbackEn: "to outlast", tip: "verb" },
      { de: "aufholen", lookup: "aufholen", fallbackEn: "to catch up", tip: "verb" },
    ],
    dialogues: [],
    phrases: [],
  },
  part416: {
    label: "Part 416",
    level: "C1",
    theme: "Reasoning and evidence",
    description: "Core concepts for understanding nuanced explanations, evidence, analysis and disagreement.",
    focus,
    seeds: [
      { de: "das Fachwissen", lookup: "Fachwissen", fallbackEn: "expertise", tip: "noun", article: "das" },
      { de: "die Voreingenommenheit", lookup: "Voreingenommenheit", fallbackEn: "bias", tip: "noun", article: "die" },
      { de: "der Blickwinkel", lookup: "Blickwinkel", fallbackEn: "perspective", tip: "noun", article: "der" },
      { de: "der Ausblick", lookup: "Ausblick", fallbackEn: "outlook", tip: "noun", article: "der" },
      { de: "der Rahmen", lookup: "Rahmen", fallbackEn: "framework", tip: "noun", article: "der" },
      { de: "das Muster", lookup: "Muster", fallbackEn: "pattern", tip: "noun", article: "das" },
      { de: "die Einordnung", lookup: "Einordnung", fallbackEn: "contextual classification", tip: "noun", article: "die" },
      { de: "das Merkmal", lookup: "Merkmal", fallbackEn: "characteristic", tip: "noun", article: "das" },
      { de: "der Faktor", lookup: "Faktor", fallbackEn: "factor", tip: "noun", article: "der" },
      { de: "das Kriterium", lookup: "Kriterium", fallbackEn: "criterion", tip: "noun", article: "das" },
      { de: "die Schätzung", lookup: "Schätzung", fallbackEn: "estimate", tip: "noun", article: "die" },
      { de: "die Prognose", lookup: "Prognose", fallbackEn: "forecast", tip: "noun", article: "die" },
      { de: "die Gewissheit", lookup: "Gewissheit", fallbackEn: "certainty", tip: "noun", article: "die" },
      { de: "das Gegenargument", lookup: "Gegenargument", fallbackEn: "counterargument", tip: "noun", article: "das" },
      { de: "die Folgerung", lookup: "Folgerung", fallbackEn: "inference", tip: "noun", article: "die" },
      { de: "die Auslegung", lookup: "Auslegung", fallbackEn: "interpretation of a rule or text", tip: "noun", article: "die" },
      { de: "der Irrglaube", lookup: "Irrglaube", fallbackEn: "misconception", tip: "noun", article: "der" },
      { de: "die Abgrenzung", lookup: "Abgrenzung", fallbackEn: "distinction", tip: "noun", article: "die" },
      { de: "die Verallgemeinerung", lookup: "Verallgemeinerung", fallbackEn: "generalisation", tip: "noun", article: "die" },
      { de: "die Mehrdeutigkeit", lookup: "Mehrdeutigkeit", fallbackEn: "ambiguity", tip: "noun", article: "die" },
      { de: "der Konsens", lookup: "Konsens", fallbackEn: "consensus", tip: "noun", article: "der" },
      { de: "die Kontroverse", lookup: "Kontroverse", fallbackEn: "controversy", tip: "noun", article: "die" },
      { de: "der Anhaltspunkt", lookup: "Anhaltspunkt", fallbackEn: "clue", tip: "noun", article: "der" },
      { de: "der Überblick", lookup: "Überblick", fallbackEn: "overview", tip: "noun", article: "der" },
      { de: "der Schwerpunkt", lookup: "Schwerpunkt", fallbackEn: "focus", tip: "noun", article: "der" },
      { de: "die Grundlage", lookup: "Grundlage", fallbackEn: "basis", tip: "noun", article: "die" },
      { de: "die Widerlegung", lookup: "Widerlegung", fallbackEn: "refutation", tip: "noun", article: "die" },
      { de: "die Einschätzung", lookup: "Einschätzung", fallbackEn: "assessment", tip: "noun", article: "die" },
      { de: "die Vermutung", lookup: "Vermutung", fallbackEn: "supposition", tip: "noun", article: "die" },
      { de: "die Denkweise", lookup: "Denkweise", fallbackEn: "mindset", tip: "noun", article: "die" },
      { de: "der Sachverhalt", lookup: "Sachverhalt", fallbackEn: "set of facts", tip: "noun", article: "der" },
      { de: "die Glaubwürdigkeit", lookup: "Glaubwürdigkeit", fallbackEn: "credibility", tip: "noun", article: "die" },
      { de: "die Stichhaltigkeit", lookup: "Stichhaltigkeit", fallbackEn: "soundness", tip: "noun", article: "die" },
      { de: "die Unsicherheit", lookup: "Unsicherheit", fallbackEn: "uncertainty", tip: "noun", article: "die" },
      { de: "der Denkfehler", lookup: "Denkfehler", fallbackEn: "reasoning error", tip: "noun", article: "der" },
      { de: "das Gegenbeispiel", lookup: "Gegenbeispiel", fallbackEn: "counterexample", tip: "noun", article: "das" },
      { de: "der Grundsatz", lookup: "Grundsatz", fallbackEn: "principle", tip: "noun", article: "der" },
      { de: "die Schlüssigkeit", lookup: "Schlüssigkeit", fallbackEn: "coherence", tip: "noun", article: "die" },
      { de: "der Gedankengang", lookup: "Gedankengang", fallbackEn: "train of thought", tip: "noun", article: "der" },
      { de: "die Beweisführung", lookup: "Beweisführung", fallbackEn: "line of argument", tip: "noun", article: "die" },
    ],
    dialogues: [],
    phrases: [],
  },
  part417: {
    label: "Part 417",
    level: "C1",
    theme: "Money and public life",
    description: "Vocabulary used in news, employment, personal finance and discussions about society.",
    focus,
    seeds: [
      { de: "die Einnahme", lookup: "Einnahme", fallbackEn: "revenue", tip: "noun", article: "die" },
      { de: "die Ausgabe", lookup: "Ausgabe", fallbackEn: "expenditure", tip: "noun", article: "die" },
      { de: "die Verschuldung", lookup: "Verschuldung", fallbackEn: "indebtedness", tip: "noun", article: "die" },
      { de: "das Darlehen", lookup: "Darlehen", fallbackEn: "formal loan", tip: "noun", article: "das" },
      { de: "das Wirtschaftswachstum", lookup: "Wirtschaftswachstum", fallbackEn: "economic growth", tip: "noun", article: "das" },
      { de: "die Rezession", lookup: "Rezession", fallbackEn: "recession", tip: "noun", article: "die" },
      { de: "der Überschuss", lookup: "Überschuss", fallbackEn: "surplus", tip: "noun", article: "der" },
      { de: "die Nachfrage", lookup: "Nachfrage", fallbackEn: "demand", tip: "noun", article: "die" },
      { de: "der Lohn", lookup: "Lohn", fallbackEn: "wage", tip: "noun", article: "der" },
      { de: "das Gehalt", lookup: "Gehalt", fallbackEn: "salary", tip: "noun", article: "das" },
      { de: "der Zuschuss", lookup: "Zuschuss", fallbackEn: "grant", tip: "noun", article: "der" },
      { de: "die Sozialleistung", lookup: "Sozialleistung", fallbackEn: "welfare benefit", tip: "noun", article: "die" },
      { de: "die Versicherung", lookup: "Versicherung", fallbackEn: "insurance", tip: "noun", article: "die" },
      { de: "die Hypothek", lookup: "Hypothek", fallbackEn: "mortgage", tip: "noun", article: "die" },
      { de: "die Rückerstattung", lookup: "Rückerstattung", fallbackEn: "reimbursement, refund", tip: "noun", article: "die" },
      { de: "das Abonnement", lookup: "Abonnement", fallbackEn: "formal subscription", tip: "noun", article: "das" },
      { de: "die Vertragsklausel", lookup: "Vertragsklausel", fallbackEn: "contract clause", tip: "noun", article: "die" },
      { de: "die Richtlinie", lookup: "Richtlinie", fallbackEn: "guideline, policy", tip: "noun", article: "die" },
      { de: "die Behörde", lookup: "Behörde", fallbackEn: "government agency", tip: "noun", article: "die" },
      { de: "der Stadtrat", lookup: "Stadtrat", fallbackEn: "city council", tip: "noun", article: "der" },
      { de: "die Bürgerinitiative", lookup: "Bürgerinitiative", fallbackEn: "citizens' initiative", tip: "noun", article: "die" },
      { de: "die Wohltätigkeitsorganisation", lookup: "Wohltätigkeitsorganisation", fallbackEn: "charity", tip: "noun", article: "die" },
      { de: "die Arbeitslosigkeit", lookup: "Arbeitslosigkeit", fallbackEn: "unemployment", tip: "noun", article: "die" },
      { de: "die Lebenshaltungskosten", lookup: "Lebenshaltungskosten", fallbackEn: "cost of living", tip: "plural noun", article: "die" },
      { de: "die Kaufkraft", lookup: "Kaufkraft", fallbackEn: "purchasing power", tip: "noun", article: "die" },
      { de: "das Vermögen", lookup: "Vermögen", fallbackEn: "wealth, assets", tip: "noun", article: "das" },
      { de: "der Haushalt", lookup: "Haushalt", fallbackEn: "household budget", tip: "noun", article: "der" },
      { de: "die Förderung", lookup: "Förderung", fallbackEn: "funding, support", tip: "noun", article: "die" },
      { de: "das Haushaltsdefizit", lookup: "Haushaltsdefizit", fallbackEn: "budget deficit", tip: "noun", article: "das" },
      { de: "der Mindestlohn", lookup: "Mindestlohn", fallbackEn: "minimum wage", tip: "noun", article: "der" },
      { de: "der Tarifvertrag", lookup: "Tarifvertrag", fallbackEn: "collective agreement", tip: "noun", article: "der" },
      { de: "die Gewerkschaft", lookup: "Gewerkschaft", fallbackEn: "trade union", tip: "noun", article: "die" },
      { de: "der Wettbewerb", lookup: "Wettbewerb", fallbackEn: "competition", tip: "noun", article: "der" },
      { de: "das Monopol", lookup: "Monopol", fallbackEn: "monopoly", tip: "noun", article: "das" },
      { de: "die Konjunktur", lookup: "Konjunktur", fallbackEn: "economic cycle", tip: "noun", article: "die" },
      { de: "der Wohlstand", lookup: "Wohlstand", fallbackEn: "prosperity", tip: "noun", article: "der" },
      { de: "die Subvention", lookup: "Subvention", fallbackEn: "subsidy", tip: "noun", article: "die" },
      { de: "der Verbraucher", lookup: "Verbraucher", fallbackEn: "consumer", tip: "noun", article: "der" },
      { de: "das Eigentum", lookup: "Eigentum", fallbackEn: "property, ownership", tip: "noun", article: "das" },
      { de: "der Steuerzahler", lookup: "Steuerzahler", fallbackEn: "taxpayer", tip: "noun", article: "der" },
    ],
    dialogues: [],
    phrases: [],
  },
  part418: {
    label: "Part 418",
    level: "C1",
    theme: "Technology and information",
    description: "Modern digital vocabulary for understanding devices, software, online services and information quality.",
    focus,
    seeds: [
      { de: "der Datenschutz", lookup: "Datenschutz", fallbackEn: "data protection, privacy", tip: "noun", article: "der" },
      { de: "die Einwilligung", lookup: "Einwilligung", fallbackEn: "informed consent, permission", tip: "noun", article: "die" },
      { de: "die Verschlüsselung", lookup: "Verschlüsselung", fallbackEn: "encryption", tip: "noun", article: "die" },
      { de: "die Benutzeroberfläche", lookup: "Benutzeroberfläche", fallbackEn: "user interface", tip: "noun", article: "die" },
      { de: "die Aktualisierung", lookup: "Aktualisierung", fallbackEn: "update", tip: "noun", article: "die" },
      { de: "der Speicherplatz", lookup: "Speicherplatz", fallbackEn: "storage space", tip: "noun", article: "der" },
      { de: "die Bandbreite", lookup: "Bandbreite", fallbackEn: "bandwidth", tip: "noun", article: "die" },
      { de: "die Verzögerung", lookup: "Verzögerung", fallbackEn: "latency, delay", tip: "noun", article: "die" },
      { de: "der Serverausfall", lookup: "Serverausfall", fallbackEn: "server outage", tip: "noun", article: "der" },
      { de: "die Schadsoftware", lookup: "Schadsoftware", fallbackEn: "malware", tip: "noun", article: "die" },
      { de: "die Zugangsdaten", lookup: "Zugangsdaten", fallbackEn: "login credentials", tip: "plural noun", article: "die" },
      { de: "die Berechtigung", lookup: "Berechtigung", fallbackEn: "permission", tip: "noun", article: "die" },
      { de: "die Benachrichtigung", lookup: "Benachrichtigung", fallbackEn: "notification", tip: "noun", article: "die" },
      { de: "der Anhang", lookup: "Anhang", fallbackEn: "email attachment, appendix", tip: "noun", article: "der" },
      { de: "der Suchverlauf", lookup: "Suchverlauf", fallbackEn: "search history", tip: "noun", article: "der" },
      { de: "der Browserverlauf", lookup: "Browserverlauf", fallbackEn: "browsing history", tip: "noun", article: "der" },
      { de: "der Zwischenspeicher", lookup: "Zwischenspeicher", fallbackEn: "cache", tip: "noun", article: "der" },
      { de: "die Datenbank", lookup: "Datenbank", fallbackEn: "database", tip: "noun", article: "die" },
      { de: "der Quellcode", lookup: "Quellcode", fallbackEn: "source code", tip: "noun", article: "der" },
      { de: "die Schnittstelle", lookup: "Schnittstelle", fallbackEn: "interface", tip: "noun", article: "die" },
      { de: "das Netzwerk", lookup: "Netzwerk", fallbackEn: "computer network", tip: "noun", article: "das" },
      { de: "die Verbindung", lookup: "Verbindung", fallbackEn: "connection", tip: "noun", article: "die" },
      { de: "die Auflösung", lookup: "Auflösung", fallbackEn: "resolution", tip: "noun", article: "die" },
      { de: "die Bildfrequenz", lookup: "Bildfrequenz", fallbackEn: "frame rate", tip: "noun", article: "die" },
      { de: "die Ladezeit", lookup: "Ladezeit", fallbackEn: "loading time", tip: "noun", article: "die" },
      { de: "das Dateiformat", lookup: "Dateiformat", fallbackEn: "file format", tip: "noun", article: "das" },
      { de: "die Kompatibilität", lookup: "Kompatibilität", fallbackEn: "compatibility", tip: "noun", article: "die" },
      { de: "die Barrierefreiheit", lookup: "Barrierefreiheit", fallbackEn: "accessibility", tip: "noun", article: "die" },
      { de: "die Nutzungsbedingungen", lookup: "Nutzungsbedingungen", fallbackEn: "terms of service", tip: "plural noun", article: "die" },
      { de: "das Urheberrecht", lookup: "Urheberrecht", fallbackEn: "copyright", tip: "noun", article: "das" },
      { de: "die Fehlinformation", lookup: "Fehlinformation", fallbackEn: "misinformation", tip: "noun", article: "die" },
      { de: "die Suchmaschine", lookup: "Suchmaschine", fallbackEn: "search engine", tip: "noun", article: "die" },
      { de: "das Endgerät", lookup: "Endgerät", fallbackEn: "end-user device", tip: "noun", article: "das" },
      { de: "das Eingabefeld", lookup: "Eingabefeld", fallbackEn: "input field", tip: "noun", article: "das" },
      { de: "die Sicherheitslücke", lookup: "Sicherheitslücke", fallbackEn: "security vulnerability", tip: "noun", article: "die" },
      { de: "der Datenverkehr", lookup: "Datenverkehr", fallbackEn: "data traffic", tip: "noun", article: "der" },
      { de: "die Voreinstellung", lookup: "Voreinstellung", fallbackEn: "default setting", tip: "noun", article: "die" },
      { de: "die Bildschirmfreigabe", lookup: "Bildschirmfreigabe", fallbackEn: "screen sharing", tip: "noun", article: "die" },
      { de: "die Spracherkennung", lookup: "Spracherkennung", fallbackEn: "speech recognition", tip: "noun", article: "die" },
      { de: "die Datenverarbeitung", lookup: "Datenverarbeitung", fallbackEn: "data processing", tip: "noun", article: "die" },
    ],
    dialogues: [],
    phrases: [],
  },
  part419: {
    label: "Part 419",
    level: "B2-C1",
    theme: "Health and wellbeing",
    description: "Specific words for explaining symptoms, treatment, recovery and how the body feels.",
    focus,
    seeds: [
      { de: "die Behandlung", lookup: "Behandlung", fallbackEn: "medical treatment", tip: "noun", article: "die" },
      { de: "die Erkrankung", lookup: "Erkrankung", fallbackEn: "medical condition", tip: "noun", article: "die" },
      { de: "der Ausbruch", lookup: "Ausbruch", fallbackEn: "outbreak", tip: "noun", article: "der" },
      { de: "die Infektion", lookup: "Infektion", fallbackEn: "infection", tip: "noun", article: "die" },
      { de: "die Immunität", lookup: "Immunität", fallbackEn: "immunity", tip: "noun", article: "die" },
      { de: "die Mangelerscheinung", lookup: "Mangelerscheinung", fallbackEn: "deficiency symptom", tip: "noun", article: "die" },
      { de: "die Entzündung", lookup: "Entzündung", fallbackEn: "inflammation", tip: "noun", article: "die" },
      { de: "die Verletzung", lookup: "Verletzung", fallbackEn: "injury", tip: "noun", article: "die" },
      { de: "die Schwellung", lookup: "Schwellung", fallbackEn: "swelling", tip: "noun", article: "die" },
      { de: "die Prellung", lookup: "Prellung", fallbackEn: "contusion", tip: "noun", article: "die" },
      { de: "die Verstauchung", lookup: "Verstauchung", fallbackEn: "sprain", tip: "noun", article: "die" },
      { de: "der Schwindel", lookup: "Schwindel", fallbackEn: "dizziness", tip: "noun", article: "der" },
      { de: "die Übelkeit", lookup: "Übelkeit", fallbackEn: "nausea", tip: "noun", article: "die" },
      { de: "die Erschöpfung", lookup: "Erschöpfung", fallbackEn: "exhaustion", tip: "noun", article: "die" },
      { de: "fiebrig", lookup: "fiebrig", fallbackEn: "feverish", tip: "adjective" },
      { de: "chronisch", lookup: "chronisch", fallbackEn: "chronic", tip: "adjective" },
      { de: "harmlos", lookup: "harmlos", fallbackEn: "harmless", tip: "adjective" },
      { de: "lebensbedrohlich", lookup: "lebensbedrohlich", fallbackEn: "life-threatening", tip: "adjective" },
      { de: "behandeln", lookup: "behandeln", fallbackEn: "to treat", tip: "verb" },
      { de: "therapieren", lookup: "therapieren", fallbackEn: "to treat with therapy", tip: "verb" },
      { de: "vorbeugen", lookup: "vorbeugen", fallbackEn: "to take preventive action", tip: "verb" },
      { de: "benommen", lookup: "benommen", fallbackEn: "dazed", tip: "adjective" },
      { de: "entzündet", lookup: "entzündet", fallbackEn: "inflamed", tip: "adjective" },
      { de: "geschwollen", lookup: "geschwollen", fallbackEn: "swollen", tip: "adjective" },
      { de: "steif", lookup: "steif", fallbackEn: "stiff", tip: "adjective" },
      { de: "pochen", lookup: "pochen", fallbackEn: "to throb", tip: "verb" },
      { de: "zerrissen", lookup: "zerrissen", fallbackEn: "torn", tip: "adjective" },
      { de: "heilbar", lookup: "heilbar", fallbackEn: "treatable, curable", tip: "adjective" },
      { de: "die Müdigkeit", lookup: "Müdigkeit", fallbackEn: "tiredness", tip: "noun", article: "die" },
      { de: "die Anspannung", lookup: "Anspannung", fallbackEn: "tension", tip: "noun", article: "die" },
      { de: "das Wohlbefinden", lookup: "Wohlbefinden", fallbackEn: "wellbeing", tip: "noun", article: "das" },
      { de: "die Migräne", lookup: "Migräne", fallbackEn: "migraine", tip: "noun", article: "die" },
      { de: "die Dehydrierung", lookup: "Dehydrierung", fallbackEn: "dehydration", tip: "noun", article: "die" },
      { de: "die Narbe", lookup: "Narbe", fallbackEn: "scar", tip: "noun", article: "die" },
      { de: "der Bluterguss", lookup: "Bluterguss", fallbackEn: "bruise", tip: "noun", article: "der" },
      { de: "der Krampf", lookup: "Krampf", fallbackEn: "cramp", tip: "noun", article: "der" },
      { de: "das Sodbrennen", lookup: "Sodbrennen", fallbackEn: "heartburn", tip: "noun", article: "das" },
      { de: "die Verdauung", lookup: "Verdauung", fallbackEn: "digestion", tip: "noun", article: "die" },
      { de: "die Atemnot", lookup: "Atemnot", fallbackEn: "shortness of breath", tip: "noun", article: "die" },
      { de: "die Heiserkeit", lookup: "Heiserkeit", fallbackEn: "hoarseness", tip: "noun", article: "die" },
    ],
    dialogues: [],
    phrases: [],
  },
  part420: {
    label: "Part 420",
    level: "C1",
    theme: "Environment and science",
    description: "Useful vocabulary for climate, energy, research and explanations of the physical world.",
    focus,
    seeds: [
      { de: "die Verschmutzung", lookup: "Verschmutzung", fallbackEn: "pollution", tip: "noun", article: "die" },
      { de: "der Abfall", lookup: "Abfall", fallbackEn: "waste", tip: "noun", article: "der" },
      { de: "der Rohstoff", lookup: "Rohstoff", fallbackEn: "raw material", tip: "noun", article: "der" },
      { de: "der Lebensraum", lookup: "Lebensraum", fallbackEn: "habitat", tip: "noun", article: "der" },
      { de: "die Tierart", lookup: "Tierart", fallbackEn: "animal species", tip: "noun", article: "die" },
      { de: "die Dürre", lookup: "Dürre", fallbackEn: "drought", tip: "noun", article: "die" },
      { de: "die Überschwemmung", lookup: "Überschwemmung", fallbackEn: "flood", tip: "noun", article: "die" },
      { de: "der Waldbrand", lookup: "Waldbrand", fallbackEn: "wildfire", tip: "noun", article: "der" },
      { de: "erneuerbar", lookup: "erneuerbar", fallbackEn: "renewable", tip: "adjective" },
      { de: "die Artenvielfalt", lookup: "Artenvielfalt", fallbackEn: "biodiversity", tip: "noun", article: "die" },
      { de: "das Treibhausgas", lookup: "Treibhausgas", fallbackEn: "greenhouse gas", tip: "noun", article: "das" },
      { de: "der Meeresspiegel", lookup: "Meeresspiegel", fallbackEn: "sea level", tip: "noun", article: "der" },
      { de: "der Energieverbrauch", lookup: "Energieverbrauch", fallbackEn: "energy consumption", tip: "noun", article: "der" },
      { de: "das Stromnetz", lookup: "Stromnetz", fallbackEn: "power grid", tip: "noun", article: "das" },
      { de: "der Wassermangel", lookup: "Wassermangel", fallbackEn: "water scarcity", tip: "noun", article: "der" },
      { de: "die Bodenerosion", lookup: "Bodenerosion", fallbackEn: "soil erosion", tip: "noun", article: "die" },
      { de: "die Abholzung", lookup: "Abholzung", fallbackEn: "deforestation", tip: "noun", article: "die" },
      { de: "die Wiederaufforstung", lookup: "Wiederaufforstung", fallbackEn: "reforestation", tip: "noun", article: "die" },
      { de: "die Kreislaufwirtschaft", lookup: "Kreislaufwirtschaft", fallbackEn: "circular economy", tip: "noun", article: "die" },
      { de: "die Recyclinganlage", lookup: "Recyclinganlage", fallbackEn: "recycling facility", tip: "noun", article: "die" },
      { de: "der Messwert", lookup: "Messwert", fallbackEn: "measurement reading", tip: "noun", article: "der" },
      { de: "der Datensatz", lookup: "Datensatz", fallbackEn: "dataset", tip: "noun", article: "der" },
      { de: "der Durchschnitt", lookup: "Durchschnitt", fallbackEn: "average", tip: "noun", article: "der" },
      { de: "die Abweichung", lookup: "Abweichung", fallbackEn: "deviation", tip: "noun", article: "die" },
      { de: "die Theorie", lookup: "Theorie", fallbackEn: "theory", tip: "noun", article: "die" },
      { de: "die Entdeckung", lookup: "Entdeckung", fallbackEn: "discovery", tip: "noun", article: "die" },
      { de: "der Bestandteil", lookup: "Bestandteil", fallbackEn: "component", tip: "noun", article: "der" },
      { de: "das Teilchen", lookup: "Teilchen", fallbackEn: "particle", tip: "noun", article: "das" },
      { de: "die Strahlung", lookup: "Strahlung", fallbackEn: "radiation", tip: "noun", article: "die" },
      { de: "die Schwerkraft", lookup: "Schwerkraft", fallbackEn: "gravity", tip: "noun", article: "die" },
      { de: "der Temperaturanstieg", lookup: "Temperaturanstieg", fallbackEn: "rise in temperature", tip: "noun", article: "der" },
      { de: "das Ökosystem", lookup: "Ökosystem", fallbackEn: "ecosystem", tip: "noun", article: "das" },
      { de: "das Grundwasser", lookup: "Grundwasser", fallbackEn: "groundwater", tip: "noun", article: "das" },
      { de: "die Luftqualität", lookup: "Luftqualität", fallbackEn: "air quality", tip: "noun", article: "die" },
      { de: "die Messung", lookup: "Messung", fallbackEn: "measurement", tip: "noun", article: "die" },
      { de: "die Erwärmung", lookup: "Erwärmung", fallbackEn: "warming", tip: "noun", article: "die" },
      { de: "der Ausstoß", lookup: "Ausstoß", fallbackEn: "emissions, output", tip: "noun", article: "der" },
      { de: "das Vorkommen", lookup: "Vorkommen", fallbackEn: "occurrence, deposit", tip: "noun", article: "das" },
      { de: "die Energiequelle", lookup: "Energiequelle", fallbackEn: "energy source", tip: "noun", article: "die" },
      { de: "die Naturkatastrophe", lookup: "Naturkatastrophe", fallbackEn: "natural disaster", tip: "noun", article: "die" },
    ],
    dialogues: [],
    phrases: [],
  },
};
