import { Blueprint } from "./types";

/**
 * Plain-B2 vocabulary (not B2-C1, not C1). The word ladder's rung 4 — the
 * band strictly between B1's mass and the B2-C1/C1 tier above it — sat at
 * 178 words next to 1,303 at B1 and 660 at B2-C1, because every earlier
 * advanced batch (this project's part401-410 included) reached straight
 * for B2-C1/C1 register. These eight packs fill that specific gap: solid
 * upper-intermediate vocabulary a confident B2 learner would actually use,
 * not academic or rare.
 */
export const b2ExpansionPartBlueprints: Record<string, Blueprint> = {
  part432: {
    label: "Part 432", level: "B2", theme: "Practical problem-solving and troubleshooting",
    description: "Verbs and phrases for figuring out what is wrong, working through it, and fixing it.",
    focus: "Plain-B2 vocabulary for the word ladder's middle-upper rung, taught in vocabulary sittings.",
    seeds: [
      { de: "die Ursache", lookup: "Ursache", fallbackEn: "cause, root cause", tip: "noun", article: "die" },
      { de: "die Störung", lookup: "Störung", fallbackEn: "malfunction, disruption, glitch", tip: "noun", article: "die", use: "technical fault or an interruption, not mere annoyance" },
      { de: "die Fehlerquelle", lookup: "Fehlerquelle", fallbackEn: "source of the error, error source", tip: "noun", article: "die" },
      { de: "der Lösungsansatz", lookup: "Lösungsansatz", fallbackEn: "approach, solution approach", tip: "noun", article: "der", use: "ein möglicher Lösungsansatz für das Problem" },
      { de: "der Engpass", lookup: "Engpass", fallbackEn: "bottleneck, shortage", tip: "noun", article: "der" },
      { de: "die Schwachstelle", lookup: "Schwachstelle", fallbackEn: "weak point, vulnerability, flaw", tip: "noun", article: "die" },
      { de: "der Anhaltspunkt", lookup: "Anhaltspunkt", fallbackEn: "clue, lead", tip: "noun", article: "der", use: "something concrete to go on while investigating" },
      { de: "die Übergangslösung", lookup: "Übergangslösung", fallbackEn: "interim solution, stopgap, workaround", tip: "noun", article: "die" },
      { de: "die Panne", lookup: "Panne", fallbackEn: "breakdown, mishap, glitch", tip: "noun", article: "die" },
      { de: "der Defekt", lookup: "Defekt", fallbackEn: "defect, fault", tip: "noun", article: "der" },
      { de: "beheben", lookup: "beheben", fallbackEn: "to fix, to remedy", tip: "verb", use: "eine Störung/einen Fehler beheben" },
      { de: "feststellen", lookup: "feststellen", fallbackEn: "to determine, to ascertain, to find out", tip: "verb" },
      { de: "überprüfen", lookup: "überprüfen", fallbackEn: "to check, to verify", tip: "verb" },
      { de: "ermitteln", lookup: "ermitteln", fallbackEn: "to determine, to find out, to investigate", tip: "verb" },
      { de: "eingrenzen", lookup: "eingrenzen", fallbackEn: "to narrow down", tip: "verb" },
      { de: "beseitigen", lookup: "beseitigen", fallbackEn: "to eliminate, to remove, to get rid of", tip: "verb" },
      { de: "nachvollziehen", lookup: "nachvollziehen", fallbackEn: "to trace, to retrace, to reproduce", tip: "verb", use: "den Fehler nachvollziehen = reproduce/retrace it" },
      { de: "diagnostizieren", lookup: "diagnostizieren", fallbackEn: "to diagnose", tip: "verb" },
      { de: "fehlerhaft", lookup: "fehlerhaft", fallbackEn: "faulty, defective", tip: "adjective" },
      { de: "unzureichend", lookup: "unzureichend", fallbackEn: "insufficient, inadequate", tip: "adjective" },
      { de: "provisorisch", lookup: "provisorisch", fallbackEn: "provisional, temporary, makeshift", tip: "adjective" },
      { de: "aufschlussreich", lookup: "aufschlussreich", fallbackEn: "informative, revealing, insightful", tip: "adjective" },
      { de: "widersprüchlich", lookup: "widersprüchlich", fallbackEn: "contradictory, inconsistent", tip: "adjective" },
      { de: "funktionsfähig", lookup: "funktionsfähig", fallbackEn: "functional, in working order", tip: "adjective" },
      { de: "vergeblich", lookup: "vergeblich", fallbackEn: "in vain, to no avail", tip: "adverb" },
      { de: "zwangsläufig", lookup: "zwangsläufig", fallbackEn: "inevitably, as a result", tip: "adverb" },
      { de: "notdürftig", lookup: "notdürftig", fallbackEn: "barely adequately, as a makeshift", tip: "adverb", use: "etwas notdürftig reparieren = patch it up" },
      { de: "gezielt", lookup: "gezielt", fallbackEn: "in a targeted way, purposefully, specifically", tip: "adverb" },
      { de: "auf den Grund gehen", lookup: "Grund", fallbackEn: "to get to the bottom of", tip: "verb phrase", use: "+ dative: einer Sache auf den Grund gehen" },
      { de: "in Angriff nehmen", lookup: "Angriff", fallbackEn: "to tackle, to take on", tip: "verb phrase", use: "etwas in Angriff nehmen" },
      { de: "Abhilfe schaffen", lookup: "Abhilfe", fallbackEn: "to provide a remedy, to fix the problem", tip: "verb phrase" },
      { de: "ausfindig machen", lookup: "ausfindig", fallbackEn: "to locate, to track down", tip: "verb phrase" },
      { de: "sich einen Überblick verschaffen", lookup: "verschaffen", fallbackEn: "to get an overview, to get a handle on the situation", tip: "verb phrase", use: "sich (Dat.) einen Überblick verschaffen" },
      { de: "zurückführen auf", lookup: "zurückführen", fallbackEn: "to trace back to, to attribute to", tip: "verb phrase", use: "+ accusative: etwas auf etwas zurückführen" },
      { de: "sich erweisen als", lookup: "erweisen", fallbackEn: "to turn out to be, to prove to be", tip: "verb phrase" },
      { de: "instand setzen", lookup: "instand", fallbackEn: "to repair, to restore to working order", tip: "verb phrase" },
      { de: "systematisch vorgehen", lookup: "vorgehen", fallbackEn: "to proceed systematically, to take a methodical approach", tip: "verb phrase" },
      { de: "auf die Spur kommen", lookup: "Spur", fallbackEn: "to get on the track of, to figure out", tip: "verb phrase", use: "+ dative: einer Sache auf die Spur kommen" },
    ],
    dialogues: [],
    phrases: [],
  },
  part433: {
    label: "Part 433", level: "B2", theme: "Time, planning and priorities",
    description: "Vocabulary for scheduling, deadlines, procrastination and deciding what matters most.",
    focus: "Plain-B2 vocabulary for the word ladder's middle-upper rung, taught in vocabulary sittings.",
    seeds: [
      { de: "der Zeitplan", lookup: "Zeitplan", fallbackEn: "schedule, timetable", tip: "noun", article: "der" },
      { de: "die Frist", lookup: "Frist", fallbackEn: "deadline, time limit", tip: "noun", article: "die", use: "a time limit, e.g. eine Frist einhalten" },
      { de: "die Nebensache", lookup: "Nebensache", fallbackEn: "minor matter, side issue", tip: "noun", article: "die" },
      { de: "die Priorität", lookup: "Priorität", fallbackEn: "priority", tip: "noun", article: "die" },
      { de: "die Ablenkung", lookup: "Ablenkung", fallbackEn: "distraction", tip: "noun", article: "die" },
      { de: "die Verzögerung", lookup: "Verzögerung", fallbackEn: "delay", tip: "noun", article: "die" },
      { de: "der Zeitrahmen", lookup: "Zeitrahmen", fallbackEn: "timeframe, time frame", tip: "noun", article: "der" },
      { de: "der Terminkalender", lookup: "Terminkalender", fallbackEn: "appointment calendar, schedule", tip: "noun", article: "der" },
      { de: "der Puffer", lookup: "Puffer", fallbackEn: "buffer, cushion (of time)", tip: "noun", article: "der", use: "time buffer, e.g. einen Puffer einplanen" },
      { de: "die Dringlichkeit", lookup: "Dringlichkeit", fallbackEn: "urgency", tip: "noun", article: "die" },
      { de: "der Stichtag", lookup: "Stichtag", fallbackEn: "deadline, cutoff date", tip: "noun", article: "der", use: "a fixed cutoff date, unlike Frist (a period)" },
      { de: "der Zeitfresser", lookup: "Zeitfresser", fallbackEn: "time waster, time sink", tip: "noun", article: "der" },
      { de: "der Rückstand", lookup: "Rückstand", fallbackEn: "backlog, being behind schedule", tip: "noun", article: "der", use: "im Rückstand sein = to be behind schedule" },
      { de: "der Meilenstein", lookup: "Meilenstein", fallbackEn: "milestone", tip: "noun", article: "der" },
      { de: "zeitaufwendig", lookup: "zeitaufwendig", fallbackEn: "time-consuming", tip: "adjective" },
      { de: "überfällig", lookup: "überfällig", fallbackEn: "overdue", tip: "adjective" },
      { de: "vorrangig", lookup: "vorrangig", fallbackEn: "top-priority, of primary importance", tip: "adjective" },
      { de: "kurzfristig", lookup: "kurzfristig", fallbackEn: "short-term, at short notice", tip: "adjective" },
      { de: "termingerecht", lookup: "termingerecht", fallbackEn: "on schedule, as agreed", tip: "adjective", use: "finished/delivered exactly as scheduled" },
      { de: "vollgepackt", lookup: "vollgepackt", fallbackEn: "jam-packed, fully booked", tip: "adjective", use: "e.g. ein vollgepackter Terminkalender" },
      { de: "zeitkritisch", lookup: "zeitkritisch", fallbackEn: "time-critical", tip: "adjective" },
      { de: "vorab", lookup: "vorab", fallbackEn: "in advance, beforehand", tip: "adverb" },
      { de: "kurzerhand", lookup: "kurzerhand", fallbackEn: "without further ado, on the spot", tip: "adverb", use: "decide or act on the spot, without much deliberation" },
      { de: "zwischenzeitlich", lookup: "zwischenzeitlich", fallbackEn: "in the meantime, meanwhile", tip: "adverb" },
      { de: "planmäßig", lookup: "planmäßig", fallbackEn: "as planned, on schedule", tip: "adverb" },
      { de: "aufschieben", lookup: "aufschieben", fallbackEn: "to postpone, to procrastinate", tip: "verb" },
      { de: "priorisieren", lookup: "priorisieren", fallbackEn: "to prioritise", tip: "verb" },
      { de: "delegieren", lookup: "delegieren", fallbackEn: "to delegate", tip: "verb" },
      { de: "sich vornehmen", lookup: "vornehmen", fallbackEn: "to plan to do, to resolve to do", tip: "verb", use: "sich etwas vornehmen = to resolve to do sth" },
      { de: "straffen", lookup: "straffen", fallbackEn: "to tighten, to streamline (a schedule)", tip: "verb" },
      { de: "sich verzetteln", lookup: "verzetteln", fallbackEn: "to get bogged down, to lose focus in details", tip: "verb", use: "lose focus by getting lost in small details" },
      { de: "trödeln", lookup: "trödeln", fallbackEn: "to dawdle, to dilly-dally", tip: "verb" },
      { de: "vertagen", lookup: "vertagen", fallbackEn: "to postpone, to adjourn", tip: "verb", use: "postpone formally, e.g. a meeting or decision" },
      { de: "eine Frist einhalten", lookup: "einhalten", fallbackEn: "to meet a deadline", tip: "verb phrase" },
      { de: "Zeit totschlagen", lookup: "totschlagen", fallbackEn: "to kill time", tip: "verb phrase", use: "idiomatic, e.g. while waiting" },
      { de: "unter Zeitdruck stehen", lookup: "Zeitdruck", fallbackEn: "to be under time pressure", tip: "verb phrase" },
      { de: "Zeit für etwas einplanen", lookup: "einplanen", fallbackEn: "to schedule time for something, to allow time for something", tip: "verb phrase" },
      { de: "den Überblick behalten", lookup: "Überblick", fallbackEn: "to keep track, to maintain an overview", tip: "verb phrase" },
    ],
    dialogues: [],
    phrases: [],
  },
  part434: {
    label: "Part 434", level: "B2", theme: "Comparing, evaluating and choosing",
    description: "Words for weighing options, trade-offs, and explaining why one thing beats another.",
    focus: "Plain-B2 vocabulary for the word ladder's middle-upper rung, taught in vocabulary sittings.",
    seeds: [
      { de: "die Bewertung", lookup: "Bewertung", fallbackEn: "evaluation, assessment, rating", tip: "noun", article: "die" },
      { de: "der Vorzug", lookup: "Vorzug", fallbackEn: "advantage, preference", tip: "noun", article: "der", use: "einer Sache den Vorzug geben = to give sth preference" },
      { de: "die Übereinstimmung", lookup: "Übereinstimmung", fallbackEn: "agreement, match, correspondence", tip: "noun", article: "die" },
      { de: "der Pluspunkt", lookup: "Pluspunkt", fallbackEn: "point in favour, upside", tip: "noun", article: "der", use: "ein Pluspunkt für etwas sein" },
      { de: "das Manko", lookup: "Manko", fallbackEn: "shortcoming, drawback", tip: "noun", article: "das", use: "das größte Manko an etwas" },
      { de: "die Alternative", lookup: "Alternative", fallbackEn: "alternative, option", tip: "noun", article: "die" },
      { de: "das Kriterium", lookup: "Kriterium", fallbackEn: "criterion", tip: "noun", article: "das" },
      { de: "der Kompromiss", lookup: "Kompromiss", fallbackEn: "compromise", tip: "noun", article: "der" },
      { de: "der Favorit", lookup: "Favorit", fallbackEn: "favourite, front-runner", tip: "noun", article: "der" },
      { de: "der Maßstab", lookup: "Maßstab", fallbackEn: "benchmark, yardstick, standard", tip: "noun", article: "der", use: "einen Maßstab anlegen" },
      { de: "die Rangfolge", lookup: "Rangfolge", fallbackEn: "ranking, order of priority", tip: "noun", article: "die" },
      { de: "die Gewichtung", lookup: "Gewichtung", fallbackEn: "weighting, relative importance", tip: "noun", article: "die", use: "Kriterien unterschiedlich gewichten" },
      { de: "der Gesichtspunkt", lookup: "Gesichtspunkt", fallbackEn: "point of view, aspect, consideration", tip: "noun", article: "der", use: "unter diesem Gesichtspunkt" },
      { de: "überlegen", lookup: "überlegen", fallbackEn: "superior", tip: "adjective", use: "with dative: jmdm. überlegen sein" },
      { de: "unterlegen", lookup: "unterlegen", fallbackEn: "inferior", tip: "adjective", use: "with dative: jmdm. unterlegen sein" },
      { de: "gleichwertig", lookup: "gleichwertig", fallbackEn: "equivalent, of equal value", tip: "adjective" },
      { de: "vergleichbar", lookup: "vergleichbar", fallbackEn: "comparable", tip: "adjective" },
      { de: "ausschlaggebend", lookup: "ausschlaggebend", fallbackEn: "decisive, deciding", tip: "adjective", use: "das ausschlaggebende Argument" },
      { de: "vorteilhaft", lookup: "vorteilhaft", fallbackEn: "advantageous, favorable", tip: "adjective", use: "eine vorteilhafte Option/Lösung; vorteilhafter als..." },
      { de: "empfehlenswert", lookup: "empfehlenswert", fallbackEn: "recommendable, advisable", tip: "adjective" },
      { de: "naheliegend", lookup: "naheliegend", fallbackEn: "obvious, the natural choice", tip: "adjective" },
      { de: "zweitrangig", lookup: "zweitrangig", fallbackEn: "secondary, of lesser importance", tip: "adjective" },
      { de: "eher", lookup: "eher", fallbackEn: "rather, more likely", tip: "adverb" },
      { de: "vielmehr", lookup: "vielmehr", fallbackEn: "rather, on the contrary", tip: "adverb" },
      { de: "verhältnismäßig", lookup: "verhältnismäßig", fallbackEn: "relatively, comparatively", tip: "adverb" },
      { de: "tendenziell", lookup: "tendenziell", fallbackEn: "tending to, on the whole", tip: "adverb" },
      { de: "abwägen", lookup: "abwägen", fallbackEn: "to weigh up", tip: "verb", use: "often Vor- und Nachteile abwägen" },
      { de: "gegenüberstellen", lookup: "gegenüberstellen", fallbackEn: "to compare side by side, juxtapose", tip: "verb", use: "separable verb" },
      { de: "bevorzugen", lookup: "bevorzugen", fallbackEn: "to prefer", tip: "verb" },
      { de: "übertreffen", lookup: "übertreffen", fallbackEn: "to surpass, outdo", tip: "verb" },
      { de: "überwiegen", lookup: "überwiegen", fallbackEn: "to outweigh, predominate", tip: "verb", use: "Vorteile überwiegen die Nachteile" },
      { de: "differenzieren", lookup: "differenzieren", fallbackEn: "to differentiate, distinguish", tip: "verb" },
      { de: "einordnen", lookup: "einordnen", fallbackEn: "to classify, rank, put into context", tip: "verb" },
      { de: "in Betracht ziehen", lookup: "Betracht", fallbackEn: "to take into consideration", tip: "verb phrase" },
      { de: "in die engere Wahl kommen", lookup: "Wahl", fallbackEn: "to make the shortlist, become a top contender", tip: "verb phrase" },
      { de: "den Ausschlag geben", lookup: "Ausschlag", fallbackEn: "to be the deciding factor, to tip the scales", tip: "verb phrase" },
      { de: "sich entscheiden für", lookup: "entscheiden", fallbackEn: "to decide on, opt for", tip: "verb phrase" },
      { de: "gut abschneiden", lookup: "abschneiden", fallbackEn: "to do well, come out ahead", tip: "verb phrase", use: "bei einem Vergleich/Test gut abschneiden" },
    ],
    dialogues: [],
    phrases: [],
  },
  part435: {
    label: "Part 435", level: "B2", theme: "Everyday risk, caution and safety",
    description: "Talking about likelihood, danger, precautions and playing it safe in daily life.",
    focus: "Plain-B2 vocabulary for the word ladder's middle-upper rung, taught in vocabulary sittings.",
    seeds: [
      { de: "die Vorsichtsmaßnahme", lookup: "Vorsichtsmaßnahme", fallbackEn: "precaution, precautionary measure", tip: "noun", article: "die" },
      { de: "die Gefahrenquelle", lookup: "Gefahrenquelle", fallbackEn: "source of danger, hazard", tip: "noun", article: "die" },
      { de: "der Leichtsinn", lookup: "Leichtsinn", fallbackEn: "recklessness, carelessness", tip: "noun", article: "der" },
      { de: "das Wagnis", lookup: "Wagnis", fallbackEn: "risky undertaking, venture, gamble", tip: "noun", article: "das" },
      { de: "die Umsicht", lookup: "Umsicht", fallbackEn: "prudence, circumspection", tip: "noun", article: "die" },
      { de: "der Warnhinweis", lookup: "Warnhinweis", fallbackEn: "warning, warning notice", tip: "noun", article: "der" },
      { de: "die Notlage", lookup: "Notlage", fallbackEn: "emergency, predicament, plight", tip: "noun", article: "die" },
      { de: "die Haftung", lookup: "Haftung", fallbackEn: "liability", tip: "noun", article: "die" },
      { de: "der Ernstfall", lookup: "Ernstfall", fallbackEn: "(case of) emergency", tip: "noun", article: "der", use: "e.g. im Ernstfall = if it actually happens" },
      { de: "das Bedenken", lookup: "Bedenken", fallbackEn: "reservation, doubt, misgiving", tip: "noun", article: "das", use: "often plural: Bedenken haben gegen etwas" },
      { de: "die Schutzmaßnahme", lookup: "Schutzmaßnahme", fallbackEn: "protective measure, safeguard", tip: "noun", article: "die" },
      { de: "die Absicherung", lookup: "Absicherung", fallbackEn: "safeguard, protection", tip: "noun", article: "die" },
      { de: "riskant", lookup: "riskant", fallbackEn: "risky", tip: "adjective" },
      { de: "achtsam", lookup: "achtsam", fallbackEn: "careful, mindful, attentive", tip: "adjective" },
      { de: "nachlässig", lookup: "nachlässig", fallbackEn: "careless, negligent", tip: "adjective" },
      { de: "unbedacht", lookup: "unbedacht", fallbackEn: "thoughtless, rash, ill-considered", tip: "adjective" },
      { de: "rücksichtsvoll", lookup: "rücksichtsvoll", fallbackEn: "considerate, careful of others", tip: "adjective" },
      { de: "rücksichtslos", lookup: "rücksichtslos", fallbackEn: "reckless, inconsiderate", tip: "adjective" },
      { de: "trügerisch", lookup: "trügerisch", fallbackEn: "deceptive, illusory, misleading", tip: "adjective", use: "e.g. trügerische Sicherheit = false sense of security" },
      { de: "brenzlig", lookup: "brenzlig", fallbackEn: "dicey, precarious", tip: "adjective", use: "informal, e.g. eine brenzlige Situation" },
      { de: "heikel", lookup: "heikel", fallbackEn: "tricky, delicate, precarious", tip: "adjective" },
      { de: "absehbar", lookup: "absehbar", fallbackEn: "foreseeable", tip: "adjective" },
      { de: "unabsehbar", lookup: "unabsehbar", fallbackEn: "unforeseeable", tip: "adjective", use: "e.g. unabsehbare Folgen" },
      { de: "vermeidbar", lookup: "vermeidbar", fallbackEn: "avoidable", tip: "adjective" },
      { de: "sicherheitshalber", lookup: "sicherheitshalber", fallbackEn: "to be safe, as a precaution", tip: "adverb" },
      { de: "vorsichtshalber", lookup: "vorsichtshalber", fallbackEn: "as a precaution, just in case", tip: "adverb", use: "close synonym of sicherheitshalber" },
      { de: "notfalls", lookup: "notfalls", fallbackEn: "if necessary, as a last resort", tip: "adverb" },
      { de: "höchstwahrscheinlich", lookup: "höchstwahrscheinlich", fallbackEn: "most likely, in all probability", tip: "adverb" },
      { de: "keinesfalls", lookup: "keinesfalls", fallbackEn: "under no circumstances, on no account", tip: "adverb" },
      { de: "im schlimmsten Fall", lookup: "Fall", fallbackEn: "in the worst case (scenario)", tip: "adverb" },
      { de: "gefährden", lookup: "gefährden", fallbackEn: "to endanger, jeopardize", tip: "verb" },
      { de: "riskieren", lookup: "riskieren", fallbackEn: "to risk", tip: "verb" },
      { de: "vorbeugen", lookup: "vorbeugen", fallbackEn: "to prevent, take preventive action against", tip: "verb", use: "+ Dativ, e.g. einer Krankheit vorbeugen" },
      { de: "abschätzen", lookup: "abschätzen", fallbackEn: "to estimate, to gauge (a risk)", tip: "verb" },
      { de: "Vorkehrungen treffen", lookup: "Vorkehrung", fallbackEn: "to take precautions", tip: "verb phrase" },
      { de: "auf Nummer sicher gehen", lookup: "auf Nummer sicher gehen", fallbackEn: "to play it safe, be on the safe side", tip: "verb phrase", use: "idiomatic, informal" },
      { de: "sich in Acht nehmen vor", lookup: "Acht", fallbackEn: "to watch out for, be wary of, beware of", tip: "verb phrase" },
      { de: "rechnen mit", lookup: "rechnen", fallbackEn: "to reckon with, expect, anticipate", tip: "verb phrase", use: "e.g. mit Verzögerungen rechnen" },
    ],
    dialogues: [],
    phrases: [],
  },
  part436: {
    label: "Part 436", level: "B2", theme: "Weather, nature and everyday environment",
    description: "Precise, everyday words for weather, seasons, landscape and the natural world around you.",
    focus: "Plain-B2 vocabulary for the word ladder's middle-upper rung, taught in vocabulary sittings.",
    seeds: [
      { de: "der Niederschlag", lookup: "Niederschlag", fallbackEn: "precipitation, rainfall", tip: "noun", article: "der", use: "covers rain, snow, and hail collectively" },
      { de: "die Feuchtigkeit", lookup: "Feuchtigkeit", fallbackEn: "humidity, moisture", tip: "noun", article: "die" },
      { de: "schwül", lookup: "schwül", fallbackEn: "humid, muggy", tip: "adjective" },
      { de: "der Wolkenbruch", lookup: "Wolkenbruch", fallbackEn: "cloudburst, downpour", tip: "noun", article: "der" },
      { de: "stürmisch", lookup: "stürmisch", fallbackEn: "stormy, turbulent", tip: "adjective" },
      { de: "die Sichtweite", lookup: "Sichtweite", fallbackEn: "visibility, visual range", tip: "noun", article: "die", use: "used in weather and traffic reports" },
      { de: "frostig", lookup: "frostig", fallbackEn: "frosty, bitterly cold", tip: "adjective" },
      { de: "das Tauwetter", lookup: "Tauwetter", fallbackEn: "thaw", tip: "noun", article: "das" },
      { de: "verdunsten", lookup: "verdunsten", fallbackEn: "to evaporate", tip: "verb" },
      { de: "der Hagel", lookup: "Hagel", fallbackEn: "hail", tip: "noun", article: "der" },
      { de: "nieseln", lookup: "nieseln", fallbackEn: "to drizzle", tip: "verb" },
      { de: "die Windböe", lookup: "Windböe", fallbackEn: "gust of wind, gust", tip: "noun", article: "die" },
      { de: "auffrischen", lookup: "auffrischen", fallbackEn: "to pick up, freshen (wind)", tip: "verb", use: "der Wind frischt auf" },
      { de: "abflauen", lookup: "abflauen", fallbackEn: "to die down, subside, ease off", tip: "verb", use: "der Sturm flaut ab" },
      { de: "sich zuziehen", lookup: "zuziehen", fallbackEn: "to cloud over", tip: "verb", use: "der Himmel zieht sich zu" },
      { de: "aufklaren", lookup: "aufklaren", fallbackEn: "to clear up (weather)", tip: "verb", use: "es klart auf" },
      { de: "umschlagen", lookup: "umschlagen", fallbackEn: "to change abruptly, turn (weather)", tip: "verb", use: "das Wetter schlägt um" },
      { de: "der Wetterumschwung", lookup: "Wetterumschwung", fallbackEn: "sudden change in weather, weather shift", tip: "noun", article: "der" },
      { de: "unbeständig", lookup: "unbeständig", fallbackEn: "unsettled, changeable", tip: "adjective" },
      { de: "Wurzeln schlagen", lookup: "Wurzel", fallbackEn: "to take root", tip: "verb phrase", use: "used literally (plants) and figuratively" },
      { de: "die Dämmerung", lookup: "Dämmerung", fallbackEn: "dusk, twilight", tip: "noun", article: "die" },
      { de: "die Anhöhe", lookup: "Anhöhe", fallbackEn: "rise, elevation, hillock", tip: "noun", article: "die" },
      { de: "der Abhang", lookup: "Abhang", fallbackEn: "slope, incline", tip: "noun", article: "der" },
      { de: "das Ufer", lookup: "Ufer", fallbackEn: "shore, bank", tip: "noun", article: "das" },
      { de: "die Ebbe", lookup: "Ebbe", fallbackEn: "low tide, ebb tide", tip: "noun", article: "die" },
      { de: "die Flut", lookup: "Flut", fallbackEn: "high tide, flood tide", tip: "noun", article: "die" },
      { de: "das Dickicht", lookup: "Dickicht", fallbackEn: "thicket", tip: "noun", article: "das" },
      { de: "die Lichtung", lookup: "Lichtung", fallbackEn: "clearing (in a forest)", tip: "noun", article: "die" },
      { de: "fruchtbar", lookup: "fruchtbar", fallbackEn: "fertile", tip: "adjective" },
      { de: "karg", lookup: "karg", fallbackEn: "barren, sparse", tip: "adjective" },
      { de: "der Lebensraum", lookup: "Lebensraum", fallbackEn: "habitat", tip: "noun", article: "der" },
      { de: "aussterben", lookup: "aussterben", fallbackEn: "to become extinct, die out", tip: "verb" },
      { de: "verwildern", lookup: "verwildern", fallbackEn: "to become overgrown, run wild", tip: "verb" },
      { de: "die Mülltrennung", lookup: "Mülltrennung", fallbackEn: "waste separation, sorting recyclables", tip: "noun", article: "die" },
      { de: "entsorgen", lookup: "entsorgen", fallbackEn: "to dispose of", tip: "verb" },
      { de: "der Feinstaub", lookup: "Feinstaub", fallbackEn: "particulate matter, fine dust", tip: "noun", article: "der" },
      { de: "die Dürre", lookup: "Dürre", fallbackEn: "drought", tip: "noun", article: "die" },
      { de: "vereinzelt", lookup: "vereinzelt", fallbackEn: "scattered, isolated (showers etc.)", tip: "adverb", use: "vereinzelt Regen = scattered showers" },
    ],
    dialogues: [],
    phrases: [],
  },
  part437: {
    label: "Part 437", level: "B2", theme: "Quantities, precision and approximation",
    description: "How to be exact or deliberately vague about amounts, degree and extent in normal speech.",
    focus: "Plain-B2 vocabulary for the word ladder's middle-upper rung, taught in vocabulary sittings.",
    seeds: [
      { de: "der Umfang", lookup: "Umfang", fallbackEn: "extent, scope, size", tip: "noun", article: "der", use: "e.g. der Umfang eines Projekts" },
      { de: "das Ausmaß", lookup: "Ausmaß", fallbackEn: "extent, magnitude, scale", tip: "noun", article: "das" },
      { de: "der Anteil", lookup: "Anteil", fallbackEn: "share, proportion, portion", tip: "noun", article: "der" },
      { de: "die Quote", lookup: "Quote", fallbackEn: "rate, quota", tip: "noun", article: "die", use: "a set/target rate, unlike Anteil (actual share)" },
      { de: "die Spanne", lookup: "Spanne", fallbackEn: "range, margin, spread", tip: "noun", article: "die" },
      { de: "der Spielraum", lookup: "Spielraum", fallbackEn: "leeway, room for manoeuvre, latitude", tip: "noun", article: "der", use: "e.g. finanzieller Spielraum" },
      { de: "die Abweichung", lookup: "Abweichung", fallbackEn: "deviation, discrepancy", tip: "noun", article: "die" },
      { de: "der Richtwert", lookup: "Richtwert", fallbackEn: "guideline value, benchmark figure", tip: "noun", article: "der" },
      { de: "die Obergrenze", lookup: "Obergrenze", fallbackEn: "upper limit, ceiling, cap", tip: "noun", article: "die" },
      { de: "der Grenzwert", lookup: "Grenzwert", fallbackEn: "threshold value, limit", tip: "noun", article: "der", use: "often technical/legal, e.g. pollution limit" },
      { de: "die Toleranz", lookup: "Toleranz", fallbackEn: "tolerance, margin of error", tip: "noun", article: "die" },
      { de: "die Größenordnung", lookup: "Größenordnung", fallbackEn: "order of magnitude, scale", tip: "noun", article: "die", use: "in dieser Größenordnung = in this range" },
      { de: "der Bruchteil", lookup: "Bruchteil", fallbackEn: "fraction, tiny amount", tip: "noun", article: "der" },
      { de: "annähernd", lookup: "annähernd", fallbackEn: "approximately, nearly", tip: "adverb" },
      { de: "exakt", lookup: "exakt", fallbackEn: "exact, precise", tip: "adjective" },
      { de: "präzise", lookup: "präzise", fallbackEn: "precise, accurate", tip: "adjective" },
      { de: "geringfügig", lookup: "geringfügig", fallbackEn: "slight, minor, marginal", tip: "adjective" },
      { de: "erheblich", lookup: "erheblich", fallbackEn: "considerable, substantial, significant", tip: "adjective" },
      { de: "spürbar", lookup: "spürbar", fallbackEn: "noticeable, appreciable", tip: "adjective" },
      { de: "pauschal", lookup: "pauschal", fallbackEn: "flat-rate, blanket, across-the-board", tip: "adjective", use: "a rough overall figure, not itemized" },
      { de: "zahlreich", lookup: "zahlreich", fallbackEn: "numerous", tip: "adjective" },
      { de: "unzählig", lookup: "unzählig", fallbackEn: "countless, innumerable", tip: "adjective" },
      { de: "rund", lookup: "rund", fallbackEn: "roughly, about", tip: "adverb", use: "rund 50 Euro = about 50 euros" },
      { de: "knapp", lookup: "knapp", fallbackEn: "just under, barely", tip: "adverb", use: "knapp 100 Leute = just under 100 people" },
      { de: "reichlich", lookup: "reichlich", fallbackEn: "a good bit over, ample", tip: "adverb", use: "reichlich 100 = a good 100, somewhat more than 100" },
      { de: "mindestens", lookup: "mindestens", fallbackEn: "at least, no less than", tip: "adverb", use: "a numeric floor, e.g. mindestens 100 Euro" },
      { de: "höchstens", lookup: "höchstens", fallbackEn: "at most, maximum", tip: "adverb" },
      { de: "größtenteils", lookup: "größtenteils", fallbackEn: "for the most part, mostly", tip: "adverb" },
      { de: "weitgehend", lookup: "weitgehend", fallbackEn: "largely, to a great extent", tip: "adverb" },
      { de: "vergleichsweise", lookup: "vergleichsweise", fallbackEn: "comparatively, relatively", tip: "adverb" },
      { de: "schätzen", lookup: "schätzen", fallbackEn: "to estimate, gauge (a quantity)", tip: "verb" },
      { de: "überschlagen", lookup: "überschlagen", fallbackEn: "to roughly calculate, estimate", tip: "verb", use: "a quick mental estimate, not exact" },
      { de: "veranschlagen", lookup: "veranschlagen", fallbackEn: "to estimate, budget for (cost or time)", tip: "verb" },
      { de: "beziffern", lookup: "beziffern", fallbackEn: "to put a figure on, quantify", tip: "verb" },
      { de: "überschreiten", lookup: "überschreiten", fallbackEn: "to exceed, go over (a limit)", tip: "verb" },
      { de: "unterschreiten", lookup: "unterschreiten", fallbackEn: "to fall below, come in under (a threshold)", tip: "verb" },
      { de: "sich auf etwas belaufen", lookup: "belaufen", fallbackEn: "to amount to, total (a sum)", tip: "verb phrase" },
      { de: "ins Gewicht fallen", lookup: "Gewicht", fallbackEn: "to carry weight, be significant (in the total)", tip: "verb phrase" },
    ],
    dialogues: [],
    phrases: [],
  },
  part438: {
    label: "Part 438", level: "B2", theme: "Habits, routines and changing your lifestyle",
    description: "Vocabulary for describing habits, starting or quitting something, and moderation.",
    focus: "Plain-B2 vocabulary for the word ladder's middle-upper rung, taught in vocabulary sittings.",
    seeds: [
      { de: "die Angewohnheit", lookup: "Angewohnheit", fallbackEn: "habit", tip: "noun", article: "die", use: "often a personal or slightly negative habit" },
      { de: "der Tagesablauf", lookup: "Tagesablauf", fallbackEn: "daily routine, daily schedule", tip: "noun", article: "der" },
      { de: "die Regelmäßigkeit", lookup: "Regelmäßigkeit", fallbackEn: "regularity", tip: "noun", article: "die" },
      { de: "die Willenskraft", lookup: "Willenskraft", fallbackEn: "willpower", tip: "noun", article: "die" },
      { de: "der Rückfall", lookup: "Rückfall", fallbackEn: "relapse, lapse", tip: "noun", article: "der", use: "e.g. einen Rückfall haben after quitting something" },
      { de: "die Abhängigkeit", lookup: "Abhängigkeit", fallbackEn: "dependency, addiction", tip: "noun", article: "die" },
      { de: "die Mäßigung", lookup: "Mäßigung", fallbackEn: "moderation, temperance", tip: "noun", article: "die" },
      { de: "die Selbstdisziplin", lookup: "Selbstdisziplin", fallbackEn: "self-discipline", tip: "noun", article: "die" },
      { de: "der Vorsatz", lookup: "Vorsatz", fallbackEn: "resolution, intention", tip: "noun", article: "der", use: "esp. Neujahrsvorsatz, New Year's resolution" },
      { de: "die Umstellung", lookup: "Umstellung", fallbackEn: "changeover, adjustment", tip: "noun", article: "die" },
      { de: "die Beständigkeit", lookup: "Beständigkeit", fallbackEn: "consistency, steadiness", tip: "noun", article: "die" },
      { de: "die Selbstbeherrschung", lookup: "Selbstbeherrschung", fallbackEn: "self-control", tip: "noun", article: "die" },
      { de: "der Ansporn", lookup: "Ansporn", fallbackEn: "incentive, motivating drive", tip: "noun", article: "der" },
      { de: "die Achtsamkeit", lookup: "Achtsamkeit", fallbackEn: "mindfulness", tip: "noun", article: "die" },
      { de: "diszipliniert", lookup: "diszipliniert", fallbackEn: "disciplined", tip: "adjective" },
      { de: "maßvoll", lookup: "maßvoll", fallbackEn: "moderate, temperate", tip: "adjective" },
      { de: "exzessiv", lookup: "exzessiv", fallbackEn: "to excess, immoderate", tip: "adjective", use: "esp. of behaviour/consumption, e.g. exzessiv feiern" },
      { de: "konsequent", lookup: "konsequent", fallbackEn: "consistent, disciplined about following through", tip: "adjective" },
      { de: "eingefahren", lookup: "eingefahren", fallbackEn: "entrenched, ingrained", tip: "adjective", use: "esp. eingefahrene Gewohnheiten, ingrained habits" },
      { de: "zwanghaft", lookup: "zwanghaft", fallbackEn: "compulsive", tip: "adjective" },
      { de: "willensstark", lookup: "willensstark", fallbackEn: "strong-willed", tip: "adjective" },
      { de: "allmählich", lookup: "allmählich", fallbackEn: "gradually", tip: "adverb" },
      { de: "schrittweise", lookup: "schrittweise", fallbackEn: "step by step, incrementally", tip: "adverb" },
      { de: "bewusst", lookup: "bewusst", fallbackEn: "consciously, deliberately", tip: "adverb" },
      { de: "unbewusst", lookup: "unbewusst", fallbackEn: "unconsciously", tip: "adverb" },
      { de: "sich abgewöhnen", lookup: "abgewöhnen", fallbackEn: "to give up, break oneself of (a habit)", tip: "verb", use: "sich (Dat.) etwas abgewöhnen" },
      { de: "sich angewöhnen", lookup: "angewöhnen", fallbackEn: "to get into the habit of, take up", tip: "verb", use: "sich (Dat.) etwas angewöhnen" },
      { de: "durchhalten", lookup: "durchhalten", fallbackEn: "to stick with it, persevere, hold out", tip: "verb" },
      { de: "einschränken", lookup: "einschränken", fallbackEn: "to cut back on, restrict, limit", tip: "verb" },
      { de: "umstellen", lookup: "umstellen", fallbackEn: "to switch over, change", tip: "verb", use: "e.g. die Ernährung umstellen, to change one's diet" },
      { de: "beibehalten", lookup: "beibehalten", fallbackEn: "to maintain, keep up, stick to", tip: "verb" },
      { de: "nachlassen", lookup: "nachlassen", fallbackEn: "to wane, taper off, ease up", tip: "verb" },
      { de: "sich verkneifen", lookup: "verkneifen", fallbackEn: "to refrain from, deny oneself (something)", tip: "verb" },
      { de: "Maß halten", lookup: "Maß", fallbackEn: "to practice moderation, exercise restraint", tip: "verb phrase" },
      { de: "in den Griff bekommen", lookup: "Griff", fallbackEn: "to get a handle on, bring under control", tip: "verb phrase" },
      { de: "am Ball bleiben", lookup: "Ball", fallbackEn: "to stay on track, keep at it", tip: "verb phrase" },
      { de: "den inneren Schweinehund überwinden", lookup: "Schweinehund", fallbackEn: "to overcome one's inner laziness, push past reluctance", tip: "verb phrase" },
      { de: "klein anfangen", lookup: "anfangen", fallbackEn: "to start small", tip: "verb phrase" },
    ],
    dialogues: [],
    phrases: [],
  },
  part439: {
    label: "Part 439", level: "B2", theme: "Giving and responding to feedback",
    description: "Praise, criticism, suggestions and how to react to them gracefully in everyday German.",
    focus: "Plain-B2 vocabulary for the word ladder's middle-upper rung, taught in vocabulary sittings.",
    seeds: [
      { de: "das Lob", lookup: "Lob", fallbackEn: "praise", tip: "noun", article: "das" },
      { de: "die Kritik", lookup: "Kritik", fallbackEn: "criticism", tip: "noun", article: "die" },
      { de: "die Rückmeldung", lookup: "Rückmeldung", fallbackEn: "feedback, response", tip: "noun", article: "die", use: "neutral term, common in professional/work contexts" },
      { de: "der Verbesserungsvorschlag", lookup: "Verbesserungsvorschlag", fallbackEn: "suggestion for improvement", tip: "noun", article: "der" },
      { de: "der Tadel", lookup: "Tadel", fallbackEn: "reprimand, rebuke", tip: "noun", article: "der", use: "formal; often paired as 'Lob und Tadel'" },
      { de: "die Anerkennung", lookup: "Anerkennung", fallbackEn: "recognition, appreciation", tip: "noun", article: "die" },
      { de: "der Einwand", lookup: "Einwand", fallbackEn: "objection", tip: "noun", article: "der" },
      { de: "der Kritikpunkt", lookup: "Kritikpunkt", fallbackEn: "point of criticism", tip: "noun", article: "der", use: "often used in the plural when listing feedback" },
      { de: "die Anmerkung", lookup: "Anmerkung", fallbackEn: "remark, comment, note", tip: "noun", article: "die" },
      { de: "die Selbstkritik", lookup: "Selbstkritik", fallbackEn: "self-criticism", tip: "noun", article: "die" },
      { de: "der Ratschlag", lookup: "Ratschlag", fallbackEn: "piece of advice, recommendation", tip: "noun", article: "der" },
      { de: "die Anregung", lookup: "Anregung", fallbackEn: "suggestion, food for thought", tip: "noun", article: "die", use: "softer, less concrete than 'Verbesserungsvorschlag'" },
      { de: "konstruktiv", lookup: "konstruktiv", fallbackEn: "constructive", tip: "adjective" },
      { de: "sachlich", lookup: "sachlich", fallbackEn: "factual, objective, matter-of-fact", tip: "adjective" },
      { de: "wohlwollend", lookup: "wohlwollend", fallbackEn: "benevolent, favorable, well-meaning", tip: "adjective" },
      { de: "taktvoll", lookup: "taktvoll", fallbackEn: "tactful", tip: "adjective" },
      { de: "berechtigt", lookup: "berechtigt", fallbackEn: "justified, warranted", tip: "adjective" },
      { de: "überzogen", lookup: "überzogen", fallbackEn: "exaggerated, excessive, over the top", tip: "adjective" },
      { de: "nachvollziehbar", lookup: "nachvollziehbar", fallbackEn: "understandable, comprehensible", tip: "adjective" },
      { de: "kritikfähig", lookup: "kritikfähig", fallbackEn: "able to take criticism, receptive to feedback", tip: "adjective" },
      { de: "differenziert", lookup: "differenziert", fallbackEn: "nuanced, differentiated", tip: "adjective" },
      { de: "gelassen", lookup: "gelassen", fallbackEn: "calmly, with composure", tip: "adverb", use: "describes how one reacts to criticism, e.g. 'gelassen reagieren'" },
      { de: "ungefragt", lookup: "ungefragt", fallbackEn: "unsolicited, without being asked", tip: "adverb", use: "often describes advice or criticism nobody asked for" },
      { de: "ehrlich gesagt", lookup: "ehrlich", fallbackEn: "honestly, to be honest", tip: "adverb", use: "used to soften or introduce frank feedback" },
      { de: "loben", lookup: "loben", fallbackEn: "to praise", tip: "verb" },
      { de: "kritisieren", lookup: "kritisieren", fallbackEn: "to criticise", tip: "verb" },
      { de: "bemängeln", lookup: "bemängeln", fallbackEn: "to find fault with, to pick holes in", tip: "verb", use: "criticise a specific flaw, e.g. quality — kritisieren is the general word" },
      { de: "würdigen", lookup: "würdigen", fallbackEn: "to acknowledge, honour, pay tribute to", tip: "verb", use: "to honour or appreciate, often in a speech" },
      { de: "anerkennen", lookup: "anerkennen", fallbackEn: "to acknowledge, recognise, credit", tip: "verb", use: "to formally accept something as valid or deserved" },
      { de: "tadeln", lookup: "tadeln", fallbackEn: "to reprimand, rebuke, tell off", tip: "verb" },
      { de: "beanstanden", lookup: "beanstanden", fallbackEn: "to object to, complain about, flag", tip: "verb", use: "formally object to something specific" },
      { de: "hervorheben", lookup: "hervorheben", fallbackEn: "to highlight, emphasize, point out", tip: "verb" },
      { de: "Kritik einstecken", lookup: "einstecken", fallbackEn: "to take criticism, to handle being criticised", tip: "verb phrase" },
      { de: "sich zu Herzen nehmen", lookup: "Herz", fallbackEn: "to take to heart", tip: "verb phrase" },
      { de: "Stellung nehmen zu", lookup: "Stellung", fallbackEn: "to comment on, take a position on", tip: "verb phrase" },
      { de: "sich rechtfertigen", lookup: "rechtfertigen", fallbackEn: "to justify oneself, defend oneself", tip: "verb phrase" },
      { de: "gut ankommen", lookup: "ankommen", fallbackEn: "to go over well, be well received", tip: "verb phrase" },
      { de: "Feedback geben", lookup: "Feedback", fallbackEn: "to give feedback", tip: "verb phrase" },
    ],
    dialogues: [],
    phrases: [],
  },
};
