import { Blueprint } from "./types";

export const GERMAN_SPECIAL_CHARACTERS = ["Ä", "ä", "É", "é", "Ö", "ö", "Ü", "ü", "ß"];

export const VOCAB_MILESTONES = [
  {
    value: 500,
    label: "Survival",
    level: "A1",
    detail: "Order food, greet people, introduce yourself",
    color: "#71717a",
  },
  {
    value: 1500,
    label: "Daily Life",
    level: "A2",
    detail: "Handle shops, transport, simple conversations",
    color: "#60a5fa",
  },
  {
    value: 3000,
    label: "Getting By",
    level: "B1",
    detail: "Understand most of what people say to you",
    color: "#34d399",
  },
  {
    value: 5000,
    label: "Confident",
    level: "B1+",
    detail: "Hold real conversations without freezing",
    color: "#58e6d9",
  },
  {
    value: 8000,
    label: "Fluent",
    level: "B2",
    detail: "Watch TV, read news, work in German",
    color: "#a78bfa",
  },
  {
    value: 12000,
    label: "Advanced",
    level: "C1",
    detail: "Nuance, humour, complex topics feel natural",
    color: "#f59e0b",
  },
  {
    value: 16000,
    label: "Mastery",
    level: "C2",
    detail: "Near-native range across all registers",
    color: "#f97316",
  },
];

export const REMOTE_GERMAN_WORD_LIST_URLS = [
  "https://raw.githubusercontent.com/hermitdave/FrequencyWords/master/content/2016/de/de_50k.txt",
  "https://raw.githubusercontent.com/Jonny-exe/German-Words-Library/master/German-words-5000-words.json",
];

export const REMOTE_CATALOG_MAX_STORED = 2500;

export const allPartBlueprints: Record<string, Blueprint> = {
  part1: {
    label: "Part 1", level: "A1", theme: "Starter basics",
    description: "Core first words, simple sentences, and survival phrases.",
    focus: "Learn articles, present tense basics, and everyday self-introduction.",
    seeds: [
      { de: "das Haus",           lookup: "Haus",     fallbackEn: "house",             tip: "noun",    article: "das" },
      { de: "der Apfel",          lookup: "Apfel",    fallbackEn: "apple",             tip: "noun",    article: "der" },
      { de: "die Stadt",          lookup: "Stadt",    fallbackEn: "city",              tip: "noun",    article: "die" },
      { de: "gehen",              lookup: "gehen",    fallbackEn: "to go",             tip: "verb" },
      { de: "sprechen",           lookup: "sprechen", fallbackEn: "to speak",          tip: "verb" },
      { de: "heute",              lookup: "heute",    fallbackEn: "today",             tip: "adverb" },
      { de: "morgen",             lookup: "morgen",   fallbackEn: "tomorrow / morning",tip: "adverb" },
      { de: "lernen",             lookup: "lernen",   fallbackEn: "to learn",          tip: "verb" },
    ],
    dialogues: [
      { title: "Cafe", lines: [
        { speaker: "A", de: "Hallo! Was möchtest du?",         en: "Hi! What would you like?",       fr: "Salut ! Qu'est-ce que tu veux ?" },
        { speaker: "B", de: "Ich möchte einen Kaffee, bitte.", en: "I would like a coffee, please.", fr: "Je voudrais un café, s'il te plaît." },
        { speaker: "A", de: "Sonst noch etwas?",                en: "Anything else?",                 fr: "Autre chose ?" },
        { speaker: "B", de: "Nein, danke.",                     en: "No, thanks.",                    fr: "Non, merci." },
      ]},
      { title: "Introductions", lines: [
        { speaker: "A", de: "Wie heißt du?",         en: "What is your name?",   fr: "Comment t'appelles-tu ?" },
        { speaker: "B", de: "Ich heiße Alex.",        en: "My name is Alex.",     fr: "Je m'appelle Alex." },
        { speaker: "A", de: "Woher kommst du?",        en: "Where are you from?",  fr: "D'où viens-tu ?" },
        { speaker: "B", de: "Ich komme aus England.",  en: "I come from England.", fr: "Je viens d'Angleterre." },
      ]},
    ],
    phrases: [
      { de: "Wie geht es dir?",              en: "How are you?",            use: "Casual greeting",         fr: "Comment vas-tu ?" },
      { de: "Ich verstehe nicht.",           en: "I do not understand.",    use: "Useful when confused",    fr: "Je ne comprends pas." },
      { de: "Können Sie das wiederholen?",  en: "Can you repeat that?",    use: "Helpful in conversation", fr: "Pouvez-vous répéter ?" },
      { de: "Ich komme aus England.",        en: "I come from England.",    use: "Basic introduction",      fr: "Je viens d'Angleterre." },
    ],
  },
  part2: {
    label: "Part 2", level: "A1", theme: "Travel and daily tasks",
    description: "Useful German for moving around, buying things, and asking for help.",
    focus: "Practice location questions, simple needs, and polite travel language.",
    seeds: [
      { de: "der Bahnhof",  lookup: "Bahnhof",    fallbackEn: "train station", tip: "noun",   article: "der" },
      { de: "die Rechnung", lookup: "Rechnung",   fallbackEn: "bill",          tip: "noun",   article: "die" },
      { de: "das Fenster",  lookup: "Fenster",    fallbackEn: "window",        tip: "noun",   article: "das" },
      { de: "kaufen",       lookup: "kaufen",     fallbackEn: "to buy",        tip: "verb" },
      { de: "brauchen",     lookup: "brauchen",   fallbackEn: "to need",       tip: "verb" },
      { de: "vielleicht",   lookup: "vielleicht", fallbackEn: "maybe",         tip: "adverb" },
      { de: "später",      lookup: "später",    fallbackEn: "later",         tip: "adverb" },
      { de: "die Frage",    lookup: "Frage",      fallbackEn: "question",      tip: "noun",   article: "die" },
    ],
    dialogues: [
      { title: "At the Station", lines: [
        { speaker: "A", de: "Entschuldigung, wo ist der Bahnhof?", en: "Excuse me, where is the station?", fr: "Excusez-moi, où est la gare ?" },
        { speaker: "B", de: "Geradeaus und dann links.",            en: "Straight ahead and then left.",    fr: "Tout droit et puis à gauche." },
        { speaker: "A", de: "Danke schön.",                        en: "Thank you very much.",             fr: "Merci beaucoup." },
        { speaker: "B", de: "Gern geschehen.",                      en: "You are welcome.",                 fr: "Je vous en prie." },
      ]},
      { title: "In a Shop", lines: [
        { speaker: "A", de: "Kann ich Ihnen helfen?",               en: "Can I help you?",                  fr: "Puis-je vous aider ?" },
        { speaker: "B", de: "Ja, ich suche Wasser.",                en: "Yes, I am looking for water.",     fr: "Oui, je cherche de l'eau." },
        { speaker: "A", de: "Dort hinten, neben der Kasse.",        en: "Back there, next to the checkout.", fr: "Là-bas, à côté de la caisse." },
        { speaker: "B", de: "Perfekt, danke.",                      en: "Perfect, thanks.",                 fr: "Parfait, merci." },
      ]},
    ],
    phrases: [
      { de: "Wo ist die Toilette?",         en: "Where is the toilet?",       use: "Travel essential",     fr: "Où sont les toilettes ?" },
      { de: "Ich hätte gern ein Ticket.",  en: "I would like a ticket.",      use: "Transport and travel", fr: "Je voudrais un billet." },
      { de: "Was kostet das?",              en: "How much does that cost?",    use: "Shopping phrase",      fr: "Combien ça coûte ?" },
      { de: "Kann ich mit Karte zahlen?",   en: "Can I pay by card?",          use: "Very useful in stores", fr: "Puis-je payer par carte ?" },
    ],
  },
  part3: {
    label: "Part 3", level: "A1-A2", theme: "Home and routine",
    description: "Talk about your room, your day, and simple routines with more confidence.",
    focus: "Build sentence patterns around daily life and everyday objects.",
    seeds: [
      { de: "das Bett",   lookup: "Bett",   fallbackEn: "bed",     tip: "noun",    article: "das" },
      { de: "die Arbeit", lookup: "Arbeit", fallbackEn: "work",    tip: "noun",    article: "die" },
      { de: "der Morgen", lookup: "Morgen", fallbackEn: "morning", tip: "noun",    article: "der" },
      { de: "lernen",     lookup: "lernen", fallbackEn: "to study",tip: "verb" },
      { de: "kochen",     lookup: "kochen", fallbackEn: "to cook", tip: "verb" },
      { de: "früh",      lookup: "früh",  fallbackEn: "early",   tip: "adjective" },
      { de: "oft",        lookup: "oft",    fallbackEn: "often",   tip: "adverb" },
      { de: "müde",      lookup: "müde",  fallbackEn: "tired",   tip: "adjective" },
    ],
    dialogues: [
      { title: "Morning Routine", lines: [
        { speaker: "A", de: "Wann stehst du auf?",          en: "When do you get up?",       fr: "Quand te lèves-tu ?" },
        { speaker: "B", de: "Ich stehe um sieben Uhr auf.", en: "I get up at seven o'clock.", fr: "Je me lève à sept heures." },
        { speaker: "A", de: "Trinkst du Kaffee?",           en: "Do you drink coffee?",      fr: "Bois-tu du café ?" },
        { speaker: "B", de: "Ja, jeden Morgen.",            en: "Yes, every morning.",       fr: "Oui, tous les matins." },
      ]},
    ],
    phrases: [
      { de: "Ich bin heute beschäftigt.", en: "I am busy today.",         use: "Daily routine",          fr: "Je suis occupé aujourd'hui." },
      { de: "Ich muss arbeiten.",          en: "I have to work.",          use: "Useful for plans",       fr: "Je dois travailler." },
      { de: "Ich mache Frühstück.",      en: "I am making breakfast.",   use: "Home routine",           fr: "Je prépare le petit-déjeuner." },
      { de: "Ich gehe jetzt nach Hause.",  en: "I am going home now.",     use: "Common everyday phrase", fr: "Je rentre à la maison maintenant." },
    ],
  },
  part4: {
    label: "Part 4", level: "A2", theme: "Plans and conversation",
    description: "Talk about tomorrow, making plans, and giving basic opinions.",
    focus: "Stretch into longer answers with time expressions and common conversational verbs.",
    seeds: [
      { de: "der Termin",     lookup: "Termin",     fallbackEn: "appointment", tip: "noun",    article: "der" },
      { de: "die Idee",       lookup: "Idee",       fallbackEn: "idea",        tip: "noun",    article: "die" },
      { de: "das Wochenende", lookup: "Wochenende", fallbackEn: "weekend",     tip: "noun",    article: "das" },
      { de: "treffen",        lookup: "treffen",    fallbackEn: "to meet",     tip: "verb" },
      { de: "planen",         lookup: "planen",     fallbackEn: "to plan",     tip: "verb" },
      { de: "zusammen",       lookup: "zusammen",   fallbackEn: "together",    tip: "adverb" },
      { de: "naechste Woche", lookup: "Woche",      fallbackEn: "next week",   tip: "phrase" },
      { de: "klingen",        lookup: "klingen",    fallbackEn: "to sound",    tip: "verb" },
    ],
    dialogues: [
      { title: "Making Plans", lines: [
        { speaker: "A", de: "Hast du morgen Zeit?",       en: "Do you have time tomorrow?", fr: "As-tu le temps demain ?" },
        { speaker: "B", de: "Ja, am Nachmittag.",         en: "Yes, in the afternoon.",     fr: "Oui, l'après-midi." },
        { speaker: "A", de: "Wollen wir uns treffen?",    en: "Do you want to meet?",       fr: "Tu veux qu'on se voie ?" },
        { speaker: "B", de: "Ja, das klingt gut.",        en: "Yes, that sounds good.",     fr: "Oui, ça a l'air bien." },
      ]},
    ],
    phrases: [
      { de: "Hast du später Zeit?",         en: "Do you have time later?",    use: "Making plans",        fr: "As-tu le temps plus tard ?" },
      { de: "Das ist eine gute Idee.",        en: "That is a good idea.",       use: "Reacting positively", fr: "C'est une bonne idée." },
      { de: "Ich bin naechste Woche frei.",   en: "I am free next week.",       use: "Scheduling",          fr: "Je suis libre la semaine prochaine." },
      { de: "Lass uns anfangen.",             en: "Let us start.",              use: "Useful group phrase", fr: "Commençons." },
    ],
  },
  part5: {
    label: "Part 5", level: "A1-A2", theme: "Food and cafe",
    description: "Food, drink, and ordering language.",
    focus: "Useful nouns and verbs for cafes, restaurants, and simple shopping.",
    seeds: [
      { de: "das Brot",        lookup: "Brot",        fallbackEn: "bread",   tip: "noun",    article: "das" },
      { de: "der Kaffee",      lookup: "Kaffee",      fallbackEn: "coffee",  tip: "noun",    article: "der" },
      { de: "der Tee",         lookup: "Tee",         fallbackEn: "tea",     tip: "noun",    article: "der" },
      { de: "die Milch",       lookup: "Milch",       fallbackEn: "milk",    tip: "noun",    article: "die" },
      { de: "bestellen",       lookup: "bestellen",   fallbackEn: "to order",tip: "verb" },
      { de: "hungrig",         lookup: "hungrig",     fallbackEn: "hungry",  tip: "adjective" },
    ],
    dialogues: [
      { title: "At a Cafe", lines: [
        { speaker: "A", de: "Möchtest du Kaffee oder Tee?",   en: "Do you want coffee or tea?",   fr: "Veux-tu du café ou du thé ?" },
        { speaker: "B", de: "Ich nehme einen Kaffee, bitte.",  en: "I will take a coffee, please.", fr: "Je prends un café, s'il te plaît." },
        { speaker: "A", de: "Möchtest du auch Brot?",         en: "Do you want bread as well?",    fr: "Veux-tu aussi du pain ?" },
        { speaker: "B", de: "Ja, ich bin hungrig.",            en: "Yes, I am hungry.",            fr: "Oui, j'ai faim." },
      ]},
    ],
    phrases: [
      { de: "Ich möchte einen Kaffee bestellen.", en: "I would like to order a coffee.", use: "Ordering food", fr: "Je voudrais commander un café." },
      { de: "Haben Sie die Speisekarte?",          en: "Do you have the menu?",           use: "Cafe phrase",   fr: "Avez-vous la carte ?" },
    ],
  },
  part6: {
    label: "Part 6", level: "A1-A2", theme: "Directions and movement",
    description: "Direction, travel, and movement language.",
    focus: "Orientation, transport, and movement for real-world situations.",
    seeds: [
      { de: "die Straße",  lookup: "Straße",  fallbackEn: "street",           tip: "noun",    article: "die" },
      { de: "das Ticket",   lookup: "Ticket",   fallbackEn: "ticket",           tip: "noun",    article: "das" },
      { de: "links",        lookup: "links",    fallbackEn: "left",             tip: "adverb" },
      { de: "rechts",       lookup: "rechts",   fallbackEn: "right",            tip: "adverb" },
      { de: "fahren",       lookup: "fahren",   fallbackEn: "to drive / travel",tip: "verb" },
      { de: "warten",       lookup: "warten",   fallbackEn: "to wait",          tip: "verb" },
    ],
    dialogues: [
      { title: "Asking Directions", lines: [
        { speaker: "A", de: "Gehe ich hier links oder rechts?",          en: "Do I go left or right here?",     fr: "Je vais à gauche ou à droite ici ?" },
        { speaker: "B", de: "Hier rechts und dann geradeaus.",           en: "Right here and then straight on.", fr: "À droite ici et puis tout droit." },
      ]},
    ],
    phrases: [
      { de: "Ich gehe nach links.",         en: "I am going left.",             use: "Direction phrase",       fr: "Je vais à gauche." },
      { de: "Der Zug ist schnell.",         en: "The train is fast.",           use: "Transport description",  fr: "Le train est rapide." },
    ],
  },
  part7: {
    label: "Part 7", level: "A1-A2", theme: "People and family",
    description: "Family and people vocabulary.",
    focus: "Build simple introductions, family descriptions, and people-based phrases.",
    seeds: [
      { de: "die Familie",  lookup: "Familie",   fallbackEn: "family",        tip: "noun",    article: "die" },
      { de: "der Freund",   lookup: "Freund",    fallbackEn: "friend",        tip: "noun",    article: "der" },
      { de: "die Freundin", lookup: "Freundin",  fallbackEn: "female friend", tip: "noun",    article: "die" },
      { de: "das Kind",     lookup: "Kind",      fallbackEn: "child",         tip: "noun",    article: "das" },
      { de: "helfen",       lookup: "helfen",    fallbackEn: "to help",       tip: "verb" },
      { de: "freundlich",   lookup: "freundlich",fallbackEn: "friendly",      tip: "adjective" },
    ],
    dialogues: [],
    phrases: [],
  },
  part8: {
    label: "Part 8", level: "A2", theme: "Core verbs",
    description: "High-use verbs that show up everywhere.",
    focus: "Build control over essential verbs for everyday speech.",
    seeds: [
      { de: "sein",    lookup: "sein",    fallbackEn: "to be",   tip: "verb" },
      { de: "haben",   lookup: "haben",   fallbackEn: "to have", tip: "verb" },
      { de: "machen",  lookup: "machen",  fallbackEn: "to make", tip: "verb" },
      { de: "geben",   lookup: "geben",   fallbackEn: "to give", tip: "verb" },
      { de: "nehmen",  lookup: "nehmen",  fallbackEn: "to take", tip: "verb" },
      { de: "wissen",  lookup: "wissen",  fallbackEn: "to know", tip: "verb" },
    ],
    dialogues: [],
    phrases: [],
  },
  part9: {
    label: "Part 9", level: "A2", theme: "Home and daily errands",
    description: "Useful German for home routines, shops, and everyday practical tasks.",
    focus: "Push beyond the starter deck with common verbs, places, and task language.",
    seeds: [
      { de: "wohnen",         lookup: "wohnen",         fallbackEn: "to live",             tip: "verb" },
      { de: "bleiben",        lookup: "bleiben",        fallbackEn: "to stay",             tip: "verb" },
      { de: "die Küche",      lookup: "Küche",          fallbackEn: "kitchen",             tip: "noun", article: "die" },
      { de: "das Geschäft",   lookup: "Geschäft",       fallbackEn: "shop",                tip: "noun", article: "das" },
      { de: "öffnen",        lookup: "öffnen",        fallbackEn: "to open",             tip: "verb" },
    ],
    dialogues: [],
    phrases: [],
  },
  part10: {
    label: "Part 10", level: "A2-B1", theme: "Work and study",
    description: "Common German for tasks, schedules, learning, and office life.",
    focus: "Learn useful nouns and verbs for work, meetings, and planning.",
    seeds: [
      { de: "arbeiten",       lookup: "arbeiten",       fallbackEn: "to work",             tip: "verb" },
      { de: "erklären",      lookup: "erklären",      fallbackEn: "to explain",          tip: "verb" },
      { de: "der Plan",       lookup: "Plan",           fallbackEn: "plan",                tip: "noun", article: "der" },
      { de: "der Computer",   lookup: "Computer",       fallbackEn: "computer",            tip: "noun", article: "der" },
      { de: "wichtig",        lookup: "wichtig",        fallbackEn: "important",           tip: "adjective" },
    ],
    dialogues: [],
    phrases: [],
  },
  part11: {
    label: "Part 11", level: "B1", theme: "Opinions and media",
    description: "Talk about what you think, read, watch, and enjoy.",
    focus: "Move into opinion language and natural everyday commentary.",
    seeds: [
      { de: "finden",         lookup: "finden",         fallbackEn: "to find / think",      tip: "verb" },
      { de: "glauben",        lookup: "glauben",        fallbackEn: "to believe",           tip: "verb" },
      { de: "die Nachricht",  lookup: "Nachricht",      fallbackEn: "message / news item",  tip: "noun", article: "die" },
      { de: "der Film",       lookup: "Film",           fallbackEn: "film",                 tip: "noun", article: "der" },
      { de: "interessant",    lookup: "interessant",    fallbackEn: "interesting",          tip: "adjective" },
    ],
    dialogues: [],
    phrases: [],
  },
  part12: {
    label: "Part 12", level: "B1", theme: "Travel and problems",
    description: "Handle delays, problems, requests, and travel situations more naturally.",
    focus: "Build practical confidence for unexpected situations.",
    seeds: [
      { de: "vergessen",      lookup: "vergessen",      fallbackEn: "to forget",           tip: "verb" },
      { de: "verlieren",      lookup: "verlieren",      fallbackEn: "to lose",             tip: "verb" },
      { de: "das Problem",    lookup: "Problem",        fallbackEn: "problem",             tip: "noun", article: "das" },
      { de: "die Hilfe",      lookup: "Hilfe",          fallbackEn: "help",                tip: "noun", article: "die" },
      { de: "spät",          lookup: "spät",          fallbackEn: "late",                tip: "adjective" },
    ],
    dialogues: [],
    phrases: [],
  },
};

export const verbConjugations: Record<string, Record<string, string>> = {
  sein:     { ich: "bin",    du: "bist",    er: "ist",    wir: "sind",    ihr: "seid",    sie: "sind" },
  haben:    { ich: "habe",   du: "hast",    er: "hat",    wir: "haben",   ihr: "habt",    sie: "haben" },
  gehen:    { ich: "gehe",   du: "gehst",   er: "geht",   wir: "gehen",   ihr: "geht",    sie: "gehen" },
  sprechen: { ich: "spreche",du: "sprichst",er: "spricht",wir: "sprechen",ihr: "sprecht", sie: "sprechen" },
  lernen:   { ich: "lerne",  du: "lernst",  er: "lernt",  wir: "lernen",  ihr: "lernt",   sie: "lernen" },
  kochen:   { ich: "koche",  du: "kochst",  er: "kocht",  wir: "kochen",  ihr: "kocht",   sie: "kochen" },
  kaufen:   { ich: "kaufe",  du: "kaufst",  er: "kauft",  wir: "kaufen",  ihr: "kauft",   sie: "kaufen" },
  brauchen: { ich: "brauche",du: "brauchst",er: "braucht",wir: "brauchen",ihr: "braucht", sie: "brauchen" },
  treffen:  { ich: "treffe", du: "triffst", er: "trifft", wir: "treffen", ihr: "trefft",  sie: "treffen" },
  planen:   { ich: "plane",  du: "planst",  er: "plant",  wir: "planen",  ihr: "plant",   sie: "planen" },
  helfen:   { ich: "helfe",  du: "hilfst",  er: "hilft",  wir: "helfen",  ihr: "helft",   sie: "helfen" },
  fahren:   { ich: "fahre",  du: "fährst", er: "fährt", wir: "fahren",  ihr: "fahrt",   sie: "fahren" },
  warten:   { ich: "warte",  du: "wartest", er: "wartet", wir: "warten",  ihr: "wartet",  sie: "warten" },
  machen:   { ich: "mache",  du: "machst",  er: "macht",  wir: "machen",  ihr: "macht",   sie: "machen" },
  geben:    { ich: "gebe",   du: "gibst",   er: "gibt",   wir: "geben",   ihr: "gebt",    sie: "geben" },
  nehmen:   { ich: "nehme",  du: "nimmst",  er: "nimmt",  wir: "nehmen",  ihr: "nehmt",   sie: "nehmen" },
  wissen:   { ich: "weiss",  du: "weisst",  er: "weiss",  wir: "wissen",  ihr: "wisst",   sie: "wissen" },
};

export const separableVerbs = [
  { verb: "aufstehen",  example: "Ich stehe früh auf.",          en: "to get up" },
  { verb: "anrufen",    example: "Ich rufe dich später an.",     en: "to call" },
  { verb: "einkaufen",  example: "Wir kaufen heute ein.",         en: "to shop" },
  { verb: "mitbringen", example: "Kannst du Brot mitbringen?",    en: "to bring along" },
];

export const entryFallbacks: Record<string, any> = {
  haus:       { word: "Haus",       pos: "noun",      glosses: ["house", "home"],              formsCount: 2, examples: ["Das Haus ist groß."],              exampleTranslations: ["The house is big."], exampleTranslationsFr: ["La maison est grande."] },
  apfel:      { word: "Apfel",      pos: "noun",      glosses: ["apple"],                      formsCount: 2, examples: ["Ich esse einen Apfel."],           exampleTranslations: ["I am eating an apple."], exampleTranslationsFr: ["Je mange une pomme."] },
  stadt:      { word: "Stadt",      pos: "noun",      glosses: ["city", "town"],               formsCount: 2, examples: ["Die Stadt ist schön."],            exampleTranslations: ["The city is beautiful."], exampleTranslationsFr: ["La ville est belle."] },
  gehen:      { word: "gehen",      pos: "verb",      glosses: ["to go", "to walk"],           formsCount: 4, examples: ["Wir gehen nach Hause."],           exampleTranslations: ["We are going home."], exampleTranslationsFr: ["Nous rentrons à la maison."] },
  sprechen:   { word: "sprechen",   pos: "verb",      glosses: ["to speak"],                   formsCount: 4, examples: ["Sie spricht Deutsch."],            exampleTranslations: ["She speaks German."], exampleTranslationsFr: ["Elle parle allemand."] },
  heute:      { word: "heute",      pos: "adverb",    glosses: ["today"],                      formsCount: 0, examples: ["Heute lerne ich Deutsch."],        exampleTranslations: ["Today I am learning German."], exampleTranslationsFr: ["Aujourd'hui j'apprends l'allemand."] },
  morgen:     { word: "morgen",     pos: "adverb",    glosses: ["tomorrow", "in the morning"], formsCount: 0, examples: ["Morgen habe ich Zeit."],           exampleTranslations: ["Tomorrow I have time."], exampleTranslationsFr: ["Demain j'ai le temps."] },
  lernen:     { word: "lernen",     pos: "verb",      glosses: ["to learn", "to study"],       formsCount: 4, examples: ["Ich lerne jeden Tag."],            exampleTranslations: ["I learn every day."], exampleTranslationsFr: ["J'apprends tous les jours."] },
  bahnhof:    { word: "Bahnhof",    pos: "noun",      glosses: ["station", "railway station"], formsCount: 2, examples: ["Der Bahnhof ist dort."],           exampleTranslations: ["The station is over there."], exampleTranslationsFr: ["La gare est là-bas."] },
  rechnung:   { word: "Rechnung",   pos: "noun",      glosses: ["bill", "invoice"],            formsCount: 2, examples: ["Die Rechnung, bitte."],            exampleTranslations: ["The bill, please."], exampleTranslationsFr: ["L'addition, s'il vous plaît."] },
  fenster:    { word: "Fenster",    pos: "noun",      glosses: ["window"],                     formsCount: 2, examples: ["Das Fenster ist offen."],          exampleTranslations: ["The window is open."], exampleTranslationsFr: ["La fenêtre est ouverte."] },
  kaufen:     { word: "kaufen",     pos: "verb",      glosses: ["to buy"],                     formsCount: 4, examples: ["Wir kaufen Wasser."],              exampleTranslations: ["We are buying water."], exampleTranslationsFr: ["Nous achetons de l'eau."] },
  brauchen:   { word: "brauchen",   pos: "verb",      glosses: ["to need"],                    formsCount: 4, examples: ["Ich brauche Hilfe."],              exampleTranslations: ["I need help."], exampleTranslationsFr: ["J'ai besoin d'aide."] },
  vielleicht: { word: "vielleicht", pos: "adverb",    glosses: ["maybe", "perhaps"],           formsCount: 0, examples: ["Vielleicht komme ich später."],    exampleTranslations: ["Maybe I will come later."], exampleTranslationsFr: ["Peut-être que je viendrai plus tard."] },
  später:    { word: "später",     pos: "adverb",    glosses: ["later"],                      formsCount: 0, examples: ["Wir sehen uns später."],           exampleTranslations: ["See you later."], exampleTranslationsFr: ["On se voit plus tard."] },
  frage:      { word: "Frage",      pos: "noun",      glosses: ["question"],                   formsCount: 2, examples: ["Ich habe eine Frage."],            exampleTranslations: ["I have a question."], exampleTranslationsFr: ["J'ai une question."] },
  bett:       { word: "Bett",       pos: "noun",      glosses: ["bed"],                        formsCount: 2, examples: ["Das Bett ist bequem."],            exampleTranslations: ["The bed is comfortable."], exampleTranslationsFr: ["Le lit est confortable."] },
  arbeit:     { word: "Arbeit",     pos: "noun",      glosses: ["work", "job"],                formsCount: 2, examples: ["Die Arbeit ist wichtig."],         exampleTranslations: ["Work is important."], exampleTranslationsFr: ["Le travail est important."] },
  kochen:     { word: "kochen",     pos: "verb",      glosses: ["to cook"],                    formsCount: 4, examples: ["Ich koche am Abend."],             exampleTranslations: ["I cook in the evening."], exampleTranslationsFr: ["Je cuisine le soir."] },
  früh:      { word: "früh",       pos: "adjective", glosses: ["early"],                      formsCount: 1, examples: ["Ich stehe früh auf."],             exampleTranslations: ["I get up early."], exampleTranslationsFr: ["Je me lève tôt."] },
  oft:        { word: "oft",        pos: "adverb",    glosses: ["often"],                      formsCount: 0, examples: ["Wir üben oft."],                  exampleTranslations: ["We practise often."], exampleTranslationsFr: ["Nous nous entraînons souvent."] },
  müde:      { word: "müde",       pos: "adjective", glosses: ["tired"],                      formsCount: 1, examples: ["Ich bin müde."],                  exampleTranslations: ["I am tired."], exampleTranslationsFr: ["Je suis fatigué."] },
  termin:     { word: "Termin",     pos: "noun",      glosses: ["appointment", "meeting time"],formsCount: 2, examples: ["Ich habe einen Termin."],          exampleTranslations: ["I have an appointment."], exampleTranslationsFr: ["J'ai un rendez-vous."] },
  idee:       { word: "Idee",       pos: "noun",      glosses: ["idea"],                       formsCount: 2, examples: ["Das ist eine gute Idee."],         exampleTranslations: ["That is a good idea."], exampleTranslationsFr: ["C'est une bonne idée."] },
  wochenende: { word: "Wochenende", pos: "noun",      glosses: ["weekend"],                    formsCount: 2, examples: ["Am Wochenende habe ich Zeit."],    exampleTranslations: ["I have time at the weekend."], exampleTranslationsFr: ["Le week-end j'ai le temps."] },
  treffen:    { word: "treffen",    pos: "verb",      glosses: ["to meet", "to hit"],          formsCount: 4, examples: ["Wir treffen uns morgen."],         exampleTranslations: ["We are meeting tomorrow."], exampleTranslationsFr: ["Nous nous retrouvons demain."] },
  planen:     { word: "planen",     pos: "verb",      glosses: ["to plan"],                    formsCount: 4, examples: ["Ich plane einen Ausflug."],        exampleTranslations: ["I am planning a trip."], exampleTranslationsFr: ["Je prévois une excursion."] },
  zusammen:   { word: "zusammen",   pos: "adverb",    glosses: ["together"],                   formsCount: 0, examples: ["Wir lernen zusammen."],            exampleTranslations: ["We are learning together."], exampleTranslationsFr: ["Nous apprenons ensemble."] },
  woche:      { word: "Woche",      pos: "noun",      glosses: ["week"],                       formsCount: 2, examples: ["Nächste Woche habe ich Zeit."],    exampleTranslations: ["I have time next week."], exampleTranslationsFr: ["La semaine prochaine j'ai le temps."] },
  klingen:    { word: "klingen",    pos: "verb",      glosses: ["to sound"],                   formsCount: 4, examples: ["Das klingt gut."],                 exampleTranslations: ["That sounds good."], exampleTranslationsFr: ["Ça a l'air bien."] },
  brot:       { word: "Brot",       pos: "noun",      glosses: ["bread"],                      formsCount: 2, examples: ["Das Brot ist frisch."],            exampleTranslations: ["The bread is fresh."], exampleTranslationsFr: ["Le pain est frais."] },
  kaffee:     { word: "Kaffee",     pos: "noun",      glosses: ["coffee"],                     formsCount: 2, examples: ["Der Kaffee ist heiß."],            exampleTranslations: ["The coffee is hot."], exampleTranslationsFr: ["Le café est chaud."] },
  tee:        { word: "Tee",        pos: "noun",      glosses: ["tea"],                        formsCount: 2, examples: ["Ich trinke Tee."],                 exampleTranslations: ["I am drinking tea."], exampleTranslationsFr: ["Je bois du thé."] },
  milch:      { word: "Milch",      pos: "noun",      glosses: ["milk"],                       formsCount: 2, examples: ["Die Milch ist kalt."],             exampleTranslations: ["The milk is cold."], exampleTranslationsFr: ["Le lait est froid."] },
  bestellen:  { word: "bestellen",  pos: "verb",      glosses: ["to order"],                   formsCount: 4, examples: ["Ich möchte bestellen."],           exampleTranslations: ["I would like to order."], exampleTranslationsFr: ["Je voudrais commander."] },
  hungrig:    { word: "hungrig",    pos: "adjective", glosses: ["hungry"],                     formsCount: 1, examples: ["Ich bin hungrig."],                exampleTranslations: ["I am hungry."], exampleTranslationsFr: ["J'ai faim."] },
  strasse:    { word: "Straße",     pos: "noun",      glosses: ["street", "road"],             formsCount: 2, examples: ["Die Straße ist lang."],            exampleTranslations: ["The street is long."], exampleTranslationsFr: ["La rue est longue."] },
  ticket:     { word: "Ticket",     pos: "noun",      glosses: ["ticket"],                     formsCount: 2, examples: ["Ich brauche ein Ticket."],         exampleTranslations: ["I need a ticket."], exampleTranslationsFr: ["J'ai besoin d'un billet."] },
  links:      { word: "links",      pos: "adverb",    glosses: ["left"],                       formsCount: 0, examples: ["Gehe hier links."],               exampleTranslations: ["Turn left here."], exampleTranslationsFr: ["Tourne à gauche ici."] },
  rechts:     { word: "rechts",     pos: "adverb",    glosses: ["right"],                      formsCount: 0, examples: ["Dann rechts."],                  exampleTranslations: ["Then right."], exampleTranslationsFr: ["Puis à droite."] },
  fahren:     { word: "fahren",     pos: "verb",      glosses: ["to drive", "to travel"],      formsCount: 4, examples: ["Wir fahren nach Berlin."],         exampleTranslations: ["We are travelling to Berlin."], exampleTranslationsFr: ["Nous allons à Berlin."] },
  warten:     { word: "warten",     pos: "verb",      glosses: ["to wait"],                    formsCount: 4, examples: ["Ich warte hier."],                 exampleTranslations: ["I am waiting here."], exampleTranslationsFr: ["J'attends ici."] },
  familie:    { word: "Familie",    pos: "noun",      glosses: ["family"],                     formsCount: 2, examples: ["Meine Familie ist klein."],        exampleTranslations: ["My family is small."], exampleTranslationsFr: ["Ma famille est petite."] },
  freund:     { word: "Freund",     pos: "noun",      glosses: ["friend"],                     formsCount: 2, examples: ["Mein Freund ist nett."],           exampleTranslations: ["My friend is nice."], exampleTranslationsFr: ["Mon ami est gentil."] },
  freundin:   { word: "Freundin",   pos: "noun",      glosses: ["female friend", "girlfriend"],formsCount: 2, examples: ["Meine Freundin ist freundlich."],  exampleTranslations: ["My friend is friendly."], exampleTranslationsFr: ["Mon amie est gentille."] },
  kind:       { word: "Kind",       pos: "noun",      glosses: ["child"],                      formsCount: 2, examples: ["Das Kind spielt."],               exampleTranslations: ["The child is playing."], exampleTranslationsFr: ["L'enfant joue."] },
  helfen:     { word: "helfen",     pos: "verb",      glosses: ["to help"],                    formsCount: 4, examples: ["Kannst du mir helfen?"],           exampleTranslations: ["Can you help me?"], exampleTranslationsFr: ["Peux-tu m'aider ?"] },
  freundlich: { word: "freundlich", pos: "adjective", glosses: ["friendly"],                   formsCount: 1, examples: ["Er ist freundlich."],              exampleTranslations: ["He is friendly."], exampleTranslationsFr: ["Il est gentil."] },
  sein:       { word: "sein",       pos: "verb",      glosses: ["to be"],                      formsCount: 6, examples: ["Ich bin hier."],                  exampleTranslations: ["I am here."], exampleTranslationsFr: ["Je suis ici."] },
  haben:      { word: "haben",      pos: "verb",      glosses: ["to have"],                    formsCount: 6, examples: ["Ich habe Zeit."],                  exampleTranslations: ["I have time."], exampleTranslationsFr: ["J'ai le temps."] },
  machen:     { word: "machen",     pos: "verb",      glosses: ["to make", "to do"],           formsCount: 4, examples: ["Wir machen das zusammen."],        exampleTranslations: ["We are doing that together."], exampleTranslationsFr: ["Nous faisons ça ensemble."] },
  geben:      { word: "geben",      pos: "verb",      glosses: ["to give"],                    formsCount: 4, examples: ["Kannst du mir das geben?"],        exampleTranslations: ["Can you give me that?"], exampleTranslationsFr: ["Peux-tu me donner ça ?"] },
  nehmen:     { word: "nehmen",     pos: "verb",      glosses: ["to take"],                    formsCount: 4, examples: ["Ich nehme einen Kaffee."],         exampleTranslations: ["I will take a coffee."], exampleTranslationsFr: ["Je prends un café."] },
  wissen:     { word: "wissen",     pos: "verb",      glosses: ["to know"],                    formsCount: 6, examples: ["Ich weiß es nicht."],              exampleTranslations: ["I do not know."], exampleTranslationsFr: ["Je ne sais pas."] },
  // Part 9 — Home and daily errands
  wohnen:     { word: "wohnen",     pos: "verb",      glosses: ["to live", "to reside"],       formsCount: 4, examples: ["Ich wohne in Berlin."],           exampleTranslations: ["I live in Berlin."], exampleTranslationsFr: ["J'habite à Berlin."] },
  bleiben:    { word: "bleiben",    pos: "verb",      glosses: ["to stay", "to remain"],       formsCount: 4, examples: ["Wir bleiben zu Hause."],           exampleTranslations: ["We are staying home."], exampleTranslationsFr: ["Nous restons à la maison."] },
  küche:      { word: "Küche",      pos: "noun",      glosses: ["kitchen"],                    formsCount: 2, examples: ["Die Küche ist klein."],           exampleTranslations: ["The kitchen is small."], exampleTranslationsFr: ["La cuisine est petite."] },
  geschäft:   { word: "Geschäft",   pos: "noun",      glosses: ["shop", "store", "business"],  formsCount: 2, examples: ["Das Geschäft ist geschlossen."],   exampleTranslations: ["The shop is closed."], exampleTranslationsFr: ["Le magasin est fermé."] },
  öffnen:     { word: "öffnen",     pos: "verb",      glosses: ["to open"],                    formsCount: 4, examples: ["Ich öffne das Fenster."],          exampleTranslations: ["I open the window."], exampleTranslationsFr: ["J'ouvre la fenêtre."] },
  // Part 10 — Work and study
  arbeiten:   { word: "arbeiten",   pos: "verb",      glosses: ["to work"],                    formsCount: 4, examples: ["Ich arbeite heute."],            exampleTranslations: ["I am working today."], exampleTranslationsFr: ["Je travaille aujourd'hui."] },
  erklären:   { word: "erklären",   pos: "verb",      glosses: ["to explain"],                 formsCount: 4, examples: ["Kannst du das erklären?"],         exampleTranslations: ["Can you explain that?"], exampleTranslationsFr: ["Peux-tu expliquer ça ?"] },
  plan:       { word: "Plan",       pos: "noun",      glosses: ["plan"],                       formsCount: 2, examples: ["Der Plan ist gut."],             exampleTranslations: ["The plan is good."], exampleTranslationsFr: ["Le plan est bon."] },
  computer:   { word: "Computer",   pos: "noun",      glosses: ["computer"],                   formsCount: 2, examples: ["Der Computer ist neu."],          exampleTranslations: ["The computer is new."], exampleTranslationsFr: ["L'ordinateur est neuf."] },
  wichtig:    { word: "wichtig",    pos: "adjective", glosses: ["important"],                  formsCount: 0, examples: ["Das ist sehr wichtig."],         exampleTranslations: ["That is very important."], exampleTranslationsFr: ["C'est très important."] },
  // Part 11 — Opinions and media
  finden:     { word: "finden",     pos: "verb",      glosses: ["to find", "to think"],        formsCount: 4, examples: ["Ich finde das gut."],            exampleTranslations: ["I think that is good."], exampleTranslationsFr: ["Je trouve ça bien."] },
  glauben:    { word: "glauben",    pos: "verb",      glosses: ["to believe", "to think"],     formsCount: 4, examples: ["Ich glaube dir."],               exampleTranslations: ["I believe you."], exampleTranslationsFr: ["Je te crois."] },
  nachricht:  { word: "Nachricht",  pos: "noun",      glosses: ["message", "news"],            formsCount: 2, examples: ["Ich habe eine Nachricht."],       exampleTranslations: ["I have a message."], exampleTranslationsFr: ["J'ai un message."] },
  film:       { word: "Film",       pos: "noun",      glosses: ["film", "movie"],              formsCount: 2, examples: ["Der Film ist spannend."],         exampleTranslations: ["The film is exciting."], exampleTranslationsFr: ["Le film est passionnant."] },
  interessant:{ word: "interessant",pos: "adjective", glosses: ["interesting"],                formsCount: 0, examples: ["Das Buch ist interessant."],      exampleTranslations: ["The book is interesting."], exampleTranslationsFr: ["Le livre est intéressant."] },
  // Part 12 — Travel and problems
  vergessen:  { word: "vergessen",  pos: "verb",      glosses: ["to forget"],                  formsCount: 4, examples: ["Ich habe es vergessen."],        exampleTranslations: ["I forgot it."], exampleTranslationsFr: ["Je l'ai oublié."] },
  verlieren:  { word: "verlieren",  pos: "verb",      glosses: ["to lose"],                    formsCount: 4, examples: ["Ich verliere nie."],             exampleTranslations: ["I never lose."], exampleTranslationsFr: ["Je ne perds jamais."] },
  problem:    { word: "Problem",    pos: "noun",      glosses: ["problem"],                    formsCount: 2, examples: ["Das ist kein Problem."],         exampleTranslations: ["That is no problem."], exampleTranslationsFr: ["Ce n'est pas un problème."] },
  hilfe:      { word: "Hilfe",      pos: "noun",      glosses: ["help"],                       formsCount: 2, examples: ["Ich brauche Hilfe."],            exampleTranslations: ["I need help."], exampleTranslationsFr: ["J'ai besoin d'aide."] },
  spät:       { word: "spät",       pos: "adjective", glosses: ["late"],                       formsCount: 0, examples: ["Es ist schon spät."],            exampleTranslations: ["It is already late."], exampleTranslationsFr: ["Il est déjà tard."] },
};
