import { Blueprint } from "./types";

export const GERMAN_SPECIAL_CHARACTERS = ["Ä", "ä", "É", "é", "Ö", "ö", "Ü", "ü", "ß"];

export const VOCAB_MILESTONES = [
  {
    value: 500,
    label: "Survival",
    level: "A1",
    detail: "Order food, greet people, introduce yourself",
    color: "#71717a",
  },
  {
    value: 1500,
    label: "Daily Life",
    level: "A2",
    detail: "Handle shops, transport, simple conversations",
    color: "#60a5fa",
  },
  {
    value: 3000,
    label: "Getting By",
    level: "B1",
    detail: "Understand most of what people say to you",
    color: "#34d399",
  },
  {
    value: 5000,
    label: "Confident",
    level: "B1+",
    detail: "Hold real conversations without freezing",
    color: "#58e6d9",
  },
  {
    value: 8000,
    label: "Fluent",
    level: "B2",
    detail: "Watch TV, read news, work in German",
    color: "#a78bfa",
  },
  {
    value: 12000,
    label: "Advanced",
    level: "C1",
    detail: "Nuance, humour, complex topics feel natural",
    color: "#f59e0b",
  },
  {
    value: 16000,
    label: "Mastery",
    level: "C2",
    detail: "Near-native range across all registers",
    color: "#f97316",
  },
];

export const REMOTE_GERMAN_WORD_LIST_URLS = [
  "https://raw.githubusercontent.com/hermitdave/FrequencyWords/master/content/2016/de/de_50k.txt",
  "https://raw.githubusercontent.com/Jonny-exe/German-Words-Library/master/German-words-5000-words.json",
];

export const REMOTE_CATALOG_MAX_STORED = 2500;

export const allPartBlueprints: Record<string, Blueprint> = {
  part1: {
    label: "Part 1", level: "A1", theme: "Starter basics",
    description: "Core first words, simple sentences, and survival phrases.",
    focus: "Learn articles, present tense basics, and everyday self-introduction.",
    seeds: [
      { de: "das Haus",           lookup: "Haus",     fallbackEn: "house",             tip: "noun",    article: "das" },
      { de: "der Apfel",          lookup: "Apfel",    fallbackEn: "apple",             tip: "noun",    article: "der" },
      { de: "die Stadt",          lookup: "Stadt",    fallbackEn: "city",              tip: "noun",    article: "die" },
      { de: "gehen",              lookup: "gehen",    fallbackEn: "to go",             tip: "verb" },
      { de: "sprechen",           lookup: "sprechen", fallbackEn: "to speak",          tip: "verb" },
      { de: "heute",              lookup: "heute",    fallbackEn: "today",             tip: "adverb" },
      { de: "morgen",             lookup: "morgen",   fallbackEn: "tomorrow",tip: "adverb" },
      { de: "lernen",             lookup: "lernen",   fallbackEn: "to learn",          tip: "verb" },
    ],
    dialogues: [
      { title: "Cafe", lines: [
        { speaker: "A", de: "Hallo! Was möchtest du?",         en: "Hi! What would you like?",       fr: "Salut ! Qu'est-ce que tu veux ?" },
        { speaker: "B", de: "Ich möchte einen Kaffee, bitte.", en: "I would like a coffee, please.", fr: "Je voudrais un café, s'il te plaît." },
        { speaker: "A", de: "Sonst noch etwas?",                en: "Anything else?",                 fr: "Autre chose ?" },
        { speaker: "B", de: "Nein, danke.",                     en: "No, thanks.",                    fr: "Non, merci." },
      ]},
      { title: "Introductions", lines: [
        { speaker: "A", de: "Wie heißt du?",         en: "What is your name?",   fr: "Comment t'appelles-tu ?" },
        { speaker: "B", de: "Ich heiße Alex.",        en: "My name is Alex.",     fr: "Je m'appelle Alex." },
        { speaker: "A", de: "Woher kommst du?",        en: "Where are you from?",  fr: "D'où viens-tu ?" },
        { speaker: "B", de: "Ich komme aus England.",  en: "I come from England.", fr: "Je viens d'Angleterre." },
      ]},
    ],
    phrases: [
      { de: "Wie geht es dir?",              en: "How are you?",            use: "Casual greeting",         fr: "Comment vas-tu ?" },
      { de: "Ich verstehe nicht.",           en: "I do not understand.",    use: "Useful when confused",    fr: "Je ne comprends pas." },
      { de: "Können Sie das wiederholen?",  en: "Can you repeat that?",    use: "Helpful in conversation", fr: "Pouvez-vous répéter ?" },
      { de: "Ich komme aus England.",        en: "I come from England.",    use: "Basic introduction",      fr: "Je viens d'Angleterre." },
    ],
  },
  part2: {
    label: "Part 2", level: "A1", theme: "Travel and daily tasks",
    description: "Useful German for moving around, buying things, and asking for help.",
    focus: "Practice location questions, simple needs, and polite travel language.",
    seeds: [
      { de: "der Bahnhof",  lookup: "Bahnhof",    fallbackEn: "train station", tip: "noun",   article: "der" },
      { de: "die Rechnung", lookup: "Rechnung",   fallbackEn: "bill",          tip: "noun",   article: "die" },
      { de: "das Fenster",  lookup: "Fenster",    fallbackEn: "window",        tip: "noun",   article: "das" },
      { de: "kaufen",       lookup: "kaufen",     fallbackEn: "to buy",        tip: "verb" },
      { de: "brauchen",     lookup: "brauchen",   fallbackEn: "to need",       tip: "verb" },
      { de: "vielleicht",   lookup: "vielleicht", fallbackEn: "maybe",         tip: "adverb" },
      { de: "später",      lookup: "später",    fallbackEn: "later",         tip: "adverb" },
      { de: "die Frage",    lookup: "Frage",      fallbackEn: "question",      tip: "noun",   article: "die" },
    ],
    dialogues: [
      { title: "At the Station", lines: [
        { speaker: "A", de: "Entschuldigung, wo ist der Bahnhof?", en: "Excuse me, where is the station?", fr: "Excusez-moi, où est la gare ?" },
        { speaker: "B", de: "Geradeaus und dann links.",            en: "Straight ahead and then left.",    fr: "Tout droit et puis à gauche." },
        { speaker: "A", de: "Danke schön.",                        en: "Thank you very much.",             fr: "Merci beaucoup." },
        { speaker: "B", de: "Gern geschehen.",                      en: "You are welcome.",                 fr: "Je vous en prie." },
      ]},
      { title: "In a Shop", lines: [
        { speaker: "A", de: "Kann ich Ihnen helfen?",               en: "Can I help you?",                  fr: "Puis-je vous aider ?" },
        { speaker: "B", de: "Ja, ich suche Wasser.",                en: "Yes, I am looking for water.",     fr: "Oui, je cherche de l'eau." },
        { speaker: "A", de: "Dort hinten, neben der Kasse.",        en: "Back there, next to the checkout.", fr: "Là-bas, à côté de la caisse." },
        { speaker: "B", de: "Perfekt, danke.",                      en: "Perfect, thanks.",                 fr: "Parfait, merci." },
      ]},
    ],
    phrases: [
      { de: "Wo ist die Toilette?",         en: "Where is the toilet?",       use: "Travel essential",     fr: "Où sont les toilettes ?" },
      { de: "Ich hätte gern ein Ticket.",  en: "I would like a ticket.",      use: "Transport and travel", fr: "Je voudrais un billet." },
      { de: "Was kostet das?",              en: "How much does that cost?",    use: "Shopping phrase",      fr: "Combien ça coûte ?" },
      { de: "Kann ich mit Karte zahlen?",   en: "Can I pay by card?",          use: "Very useful in stores", fr: "Puis-je payer par carte ?" },
    ],
  },
  part3: {
    label: "Part 3", level: "A1-A2", theme: "Home and routine",
    description: "Talk about your room, your day, and simple routines with more confidence.",
    focus: "Build sentence patterns around daily life and everyday objects.",
    seeds: [
      { de: "das Bett",   lookup: "Bett",   fallbackEn: "bed",     tip: "noun",    article: "das" },
      { de: "die Arbeit", lookup: "Arbeit", fallbackEn: "work",    tip: "noun",    article: "die" },
      { de: "der Morgen", lookup: "Morgen", fallbackEn: "morning", tip: "noun",    article: "der" },
      { de: "lernen",     lookup: "lernen", fallbackEn: "to study",tip: "verb" },
      { de: "kochen",     lookup: "kochen", fallbackEn: "to cook", tip: "verb" },
      { de: "früh",      lookup: "früh",  fallbackEn: "early",   tip: "adjective" },
      { de: "oft",        lookup: "oft",    fallbackEn: "often",   tip: "adverb" },
      { de: "müde",      lookup: "müde",  fallbackEn: "tired",   tip: "adjective" },
    ],
    dialogues: [
      { title: "Morning Routine", lines: [
        { speaker: "A", de: "Wann stehst du auf?",          en: "When do you get up?",       fr: "Quand te lèves-tu ?" },
        { speaker: "B", de: "Ich stehe um sieben Uhr auf.", en: "I get up at seven o'clock.", fr: "Je me lève à sept heures." },
        { speaker: "A", de: "Trinkst du Kaffee?",           en: "Do you drink coffee?",      fr: "Bois-tu du café ?" },
        { speaker: "B", de: "Ja, jeden Morgen.",            en: "Yes, every morning.",       fr: "Oui, tous les matins." },
      ]},
    ],
    phrases: [
      { de: "Ich bin heute beschäftigt.", en: "I am busy today.",         use: "Daily routine",          fr: "Je suis occupé aujourd'hui." },
      { de: "Ich muss arbeiten.",          en: "I have to work.",          use: "Useful for plans",       fr: "Je dois travailler." },
      { de: "Ich mache Frühstück.",      en: "I am making breakfast.",   use: "Home routine",           fr: "Je prépare le petit-déjeuner." },
      { de: "Ich gehe jetzt nach Hause.",  en: "I am going home now.",     use: "Common everyday phrase", fr: "Je rentre à la maison maintenant." },
    ],
  },
  part4: {
    label: "Part 4", level: "A2", theme: "Plans and conversation",
    description: "Talk about tomorrow, making plans, and giving basic opinions.",
    focus: "Stretch into longer answers with time expressions and common conversational verbs.",
    seeds: [
      { de: "der Termin",     lookup: "Termin",     fallbackEn: "appointment", tip: "noun",    article: "der" },
      { de: "die Idee",       lookup: "Idee",       fallbackEn: "idea",        tip: "noun",    article: "die" },
      { de: "das Wochenende", lookup: "Wochenende", fallbackEn: "weekend",     tip: "noun",    article: "das" },
      { de: "treffen",        lookup: "treffen",    fallbackEn: "to meet",     tip: "verb" },
      { de: "planen",         lookup: "planen",     fallbackEn: "to plan",     tip: "verb" },
      { de: "zusammen",       lookup: "zusammen",   fallbackEn: "together",    tip: "adverb" },
      { de: "nächste Woche", lookup: "Woche",      fallbackEn: "next week",   tip: "phrase" },
      { de: "klingen",        lookup: "klingen",    fallbackEn: "to sound",    tip: "verb" },
    ],
    dialogues: [
      { title: "Making Plans", lines: [
        { speaker: "A", de: "Hast du morgen Zeit?",       en: "Do you have time tomorrow?", fr: "As-tu le temps demain ?" },
        { speaker: "B", de: "Ja, am Nachmittag.",         en: "Yes, in the afternoon.",     fr: "Oui, l'après-midi." },
        { speaker: "A", de: "Wollen wir uns treffen?",    en: "Do you want to meet?",       fr: "Tu veux qu'on se voie ?" },
        { speaker: "B", de: "Ja, das klingt gut.",        en: "Yes, that sounds good.",     fr: "Oui, ça a l'air bien." },
      ]},
    ],
    phrases: [
      { de: "Hast du später Zeit?",         en: "Do you have time later?",    use: "Making plans",        fr: "As-tu le temps plus tard ?" },
      { de: "Das ist eine gute Idee.",        en: "That is a good idea.",       use: "Reacting positively", fr: "C'est une bonne idée." },
      { de: "Ich bin nächste Woche frei.",   en: "I am free next week.",       use: "Scheduling",          fr: "Je suis libre la semaine prochaine." },
      { de: "Lass uns anfangen.",             en: "Let us start.",              use: "Useful group phrase", fr: "Commençons." },
    ],
  },
  part5: {
    label: "Part 5", level: "A1-A2", theme: "Food and cafe",
    description: "Food, drink, and ordering language.",
    focus: "Useful nouns and verbs for cafes, restaurants, and simple shopping.",
    seeds: [
      { de: "das Brot",        lookup: "Brot",        fallbackEn: "bread",   tip: "noun",    article: "das" },
      { de: "der Kaffee",      lookup: "Kaffee",      fallbackEn: "coffee",  tip: "noun",    article: "der" },
      { de: "der Tee",         lookup: "Tee",         fallbackEn: "tea",     tip: "noun",    article: "der" },
      { de: "die Milch",       lookup: "Milch",       fallbackEn: "milk",    tip: "noun",    article: "die" },
      { de: "bestellen",       lookup: "bestellen",   fallbackEn: "to order",tip: "verb" },
      { de: "hungrig",         lookup: "hungrig",     fallbackEn: "hungry",  tip: "adjective" },
    ],
    dialogues: [
      { title: "At a Cafe", lines: [
        { speaker: "A", de: "Möchtest du Kaffee oder Tee?",   en: "Do you want coffee or tea?",   fr: "Veux-tu du café ou du thé ?" },
        { speaker: "B", de: "Ich nehme einen Kaffee, bitte.",  en: "I will take a coffee, please.", fr: "Je prends un café, s'il te plaît." },
        { speaker: "A", de: "Möchtest du auch Brot?",         en: "Do you want bread as well?",    fr: "Veux-tu aussi du pain ?" },
        { speaker: "B", de: "Ja, ich bin hungrig.",            en: "Yes, I am hungry.",            fr: "Oui, j'ai faim." },
      ]},
    ],
    phrases: [
      { de: "Ich möchte einen Kaffee bestellen.", en: "I would like to order a coffee.", use: "Ordering food", fr: "Je voudrais commander un café." },
      { de: "Haben Sie die Speisekarte?",          en: "Do you have the menu?",           use: "Cafe phrase",   fr: "Avez-vous la carte ?" },
    ],
  },
  part6: {
    label: "Part 6", level: "A1-A2", theme: "Directions and movement",
    description: "Direction, travel, and movement language.",
    focus: "Orientation, transport, and movement for real-world situations.",
    seeds: [
      { de: "die Straße",  lookup: "Straße",  fallbackEn: "street",           tip: "noun",    article: "die" },
      { de: "das Ticket",   lookup: "Ticket",   fallbackEn: "ticket",           tip: "noun",    article: "das" },
      { de: "links",        lookup: "links",    fallbackEn: "left",             tip: "adverb" },
      { de: "rechts",       lookup: "rechts",   fallbackEn: "right",            tip: "adverb" },
      { de: "fahren",       lookup: "fahren",   fallbackEn: "to drive",tip: "verb" },
      { de: "warten",       lookup: "warten",   fallbackEn: "to wait",          tip: "verb" },
    ],
    dialogues: [
      { title: "Asking Directions", lines: [
        { speaker: "A", de: "Gehe ich hier links oder rechts?",          en: "Do I go left or right here?",     fr: "Je vais à gauche ou à droite ici ?" },
        { speaker: "B", de: "Hier rechts und dann geradeaus.",           en: "Right here and then straight on.", fr: "À droite ici et puis tout droit." },
      ]},
    ],
    phrases: [
      { de: "Ich gehe nach links.",         en: "I am going left.",             use: "Direction phrase",       fr: "Je vais à gauche." },
      { de: "Der Zug ist schnell.",         en: "The train is fast.",           use: "Transport description",  fr: "Le train est rapide." },
    ],
  },
  part7: {
    label: "Part 7", level: "A1-A2", theme: "People and family",
    description: "Family and people vocabulary.",
    focus: "Build simple introductions, family descriptions, and people-based phrases.",
    seeds: [
      { de: "die Familie",  lookup: "Familie",   fallbackEn: "family",        tip: "noun",    article: "die" },
      { de: "der Freund",   lookup: "Freund",    fallbackEn: "friend",        tip: "noun",    article: "der" },
      { de: "die Freundin", lookup: "Freundin",  fallbackEn: "female friend", tip: "noun",    article: "die" },
      { de: "das Kind",     lookup: "Kind",      fallbackEn: "child",         tip: "noun",    article: "das" },
      { de: "helfen",       lookup: "helfen",    fallbackEn: "to help",       tip: "verb" },
      { de: "freundlich",   lookup: "freundlich",fallbackEn: "friendly",      tip: "adjective" },
    ],
    dialogues: [],
    phrases: [],
  },
  part8: {
    label: "Part 8", level: "A2", theme: "Core verbs",
    description: "High-use verbs that show up everywhere.",
    focus: "Build control over essential verbs for everyday speech.",
    seeds: [
      { de: "sein",    lookup: "sein",    fallbackEn: "to be",   tip: "verb" },
      { de: "haben",   lookup: "haben",   fallbackEn: "to have", tip: "verb" },
      { de: "machen",  lookup: "machen",  fallbackEn: "to make", tip: "verb" },
      { de: "geben",   lookup: "geben",   fallbackEn: "to give", tip: "verb" },
      { de: "nehmen",  lookup: "nehmen",  fallbackEn: "to take", tip: "verb" },
      { de: "wissen",  lookup: "wissen",  fallbackEn: "to know", tip: "verb" },
    ],
    dialogues: [],
    phrases: [],
  },
  part9: {
    label: "Part 9", level: "A2", theme: "Home and daily errands",
    description: "Useful German for home routines, shops, and everyday practical tasks.",
    focus: "Push beyond the starter deck with common verbs, places, and task language.",
    seeds: [
      { de: "wohnen",         lookup: "wohnen",         fallbackEn: "to live",             tip: "verb" },
      { de: "bleiben",        lookup: "bleiben",        fallbackEn: "to stay",             tip: "verb" },
      { de: "die Küche",      lookup: "Küche",          fallbackEn: "kitchen",             tip: "noun", article: "die" },
      { de: "das Geschäft",   lookup: "Geschäft",       fallbackEn: "shop",                tip: "noun", article: "das" },
      { de: "öffnen",        lookup: "öffnen",        fallbackEn: "to open",             tip: "verb" },
    ],
    dialogues: [],
    phrases: [],
  },
  part10: {
    label: "Part 10", level: "A2-B1", theme: "Work and study",
    description: "Common German for tasks, schedules, learning, and office life.",
    focus: "Learn useful nouns and verbs for work, meetings, and planning.",
    seeds: [
      { de: "arbeiten",       lookup: "arbeiten",       fallbackEn: "to work",             tip: "verb" },
      { de: "erklären",      lookup: "erklären",      fallbackEn: "to explain",          tip: "verb" },
      { de: "der Plan",       lookup: "Plan",           fallbackEn: "plan",                tip: "noun", article: "der" },
      { de: "der Computer",   lookup: "Computer",       fallbackEn: "computer",            tip: "noun", article: "der" },
      { de: "wichtig",        lookup: "wichtig",        fallbackEn: "important",           tip: "adjective" },
    ],
    dialogues: [],
    phrases: [],
  },
  part11: {
    label: "Part 11", level: "B1", theme: "Opinions and media",
    description: "Talk about what you think, read, watch, and enjoy.",
    focus: "Move into opinion language and natural everyday commentary.",
    seeds: [
      { de: "finden",         lookup: "finden",         fallbackEn: "to find",      tip: "verb" },
      { de: "glauben",        lookup: "glauben",        fallbackEn: "to believe",           tip: "verb" },
      { de: "die Nachricht",  lookup: "Nachricht",      fallbackEn: "message",  tip: "noun", article: "die" },
      { de: "der Film",       lookup: "Film",           fallbackEn: "film",                 tip: "noun", article: "der" },
      { de: "interessant",    lookup: "interessant",    fallbackEn: "interesting",          tip: "adjective" },
    ],
    dialogues: [],
    phrases: [],
  },
  part12: {
    label: "Part 12", level: "B1", theme: "Travel and problems",
    description: "Handle delays, problems, requests, and travel situations more naturally.",
    focus: "Build practical confidence for unexpected situations.",
    seeds: [
      { de: "vergessen",      lookup: "vergessen",      fallbackEn: "to forget",           tip: "verb" },
      { de: "verlieren",      lookup: "verlieren",      fallbackEn: "to lose",             tip: "verb" },
      { de: "das Problem",    lookup: "Problem",        fallbackEn: "problem",             tip: "noun", article: "das" },
      { de: "die Hilfe",      lookup: "Hilfe",          fallbackEn: "help",                tip: "noun", article: "die" },
      { de: "spät",          lookup: "spät",          fallbackEn: "late",                tip: "adjective" },
    ],
    dialogues: [],
    phrases: [],
  },
  part13: {
    label: "Part 13", level: "A2-B1", theme: "Gaming & FPS callouts",
    description: "Real callouts and voice-comm slang for shooters like Call of Duty — positions, status, and how German gamers actually talk.",
    focus: "Communicate fast in-game: call positions, status, and team plays with authentic gamer slang (English verbs get German endings: er campt, er pusht).",
    seeds: [
      { de: "der Gegner",    lookup: "Gegner",    fallbackEn: "opponent", tip: "noun", article: "der" },
      { de: "der Feind",     lookup: "Feind",     fallbackEn: "enemy",            tip: "noun", article: "der" },
      { de: "die Deckung",   lookup: "Deckung",   fallbackEn: "cover",            tip: "noun", article: "die" },
      { de: "die Granate",   lookup: "Granate",   fallbackEn: "grenade",          tip: "noun", article: "die" },
      { de: "die Munition",  lookup: "Munition",  fallbackEn: "ammo",             tip: "noun", article: "die" },
      { de: "der Schaden",   lookup: "Schaden",   fallbackEn: "damage",           tip: "noun", article: "der" },
      { de: "die Runde",     lookup: "Runde",     fallbackEn: "round",            tip: "noun", article: "die" },
      { de: "nachladen",     lookup: "nachladen", fallbackEn: "to reload",        tip: "verb" },
      { de: "campen",        lookup: "campen",    fallbackEn: "to camp",          tip: "verb" },
      { de: "pushen",        lookup: "pushen",    fallbackEn: "to push",          tip: "verb" },
      { de: "rushen",        lookup: "rushen",    fallbackEn: "to rush",          tip: "verb" },
      { de: "flankieren",    lookup: "flankieren",fallbackEn: "to flank",         tip: "verb" },
      { de: "heilen",        lookup: "heilen",    fallbackEn: "to heal",          tip: "verb" },
      { de: "zielen",        lookup: "zielen",    fallbackEn: "to aim",           tip: "verb" },
    ],
    dialogues: [
      { title: "Kontakt!", lines: [
        { speaker: "A", de: "Drei Gegner in der Mitte!",            en: "Three enemies in the middle!",       fr: "Trois ennemis au milieu !" },
        { speaker: "B", de: "Ich pushe von links.",                 en: "I'm pushing from the left.",          fr: "Je push par la gauche." },
        { speaker: "A", de: "Vorsicht, einer campt in der Ecke.",   en: "Careful, one's camping in the corner.", fr: "Attention, il y en a un qui camp dans le coin." },
        { speaker: "B", de: "Hab ihn. Netter Frag, oder?",          en: "Got him. Nice frag, right?",          fr: "Je l'ai. Joli frag, non ?" },
      ]},
      { title: "Clutch", lines: [
        { speaker: "A", de: "Ich bin der Letzte, zwei gegen einen.", en: "I'm the last one, two versus one.",   fr: "Je suis le dernier, deux contre un." },
        { speaker: "B", de: "Bleib ruhig, du schaffst das.",         en: "Stay calm, you can do it.",           fr: "Reste calme, tu vas y arriver." },
        { speaker: "A", de: "Einen hab ich... und der Zweite ist down!", en: "Got one... and the second one's down!", fr: "J'en ai un... et le deuxième est à terre !" },
        { speaker: "B", de: "Was für ein Clutch! Du bist komplett cracked.", en: "What a clutch! You're completely cracked.", fr: "Quel clutch ! T'es complètement cracked." },
      ]},
      { title: "Low HP", lines: [
        { speaker: "A", de: "Ich bin low, muss kurz heilen.",        en: "I'm low, need to heal quickly.",      fr: "Je suis low, je dois me soigner vite." },
        { speaker: "B", de: "Geh in Deckung, ich gebe dir Feuerschutz.", en: "Get to cover, I'll cover you.",   fr: "Mets-toi à couvert, je te couvre." },
        { speaker: "A", de: "Danke, bin wieder voll.",               en: "Thanks, I'm full again.",             fr: "Merci, je suis de nouveau full." },
        { speaker: "B", de: "Gut, lass uns zusammen pushen.",        en: "Good, let's push together.",          fr: "Bien, on push ensemble." },
      ]},
    ],
    phrases: [
      { de: "Er ist oben.",                          en: "He's upstairs.",                  use: "Position callout",  fr: "Il est en haut." },
      { de: "Er ist unten.",                         en: "He's downstairs.",                use: "Position callout",  fr: "Il est en bas." },
      { de: "Feind im Schlafzimmer!",                en: "Enemy in the bedroom!",           use: "Position callout",  fr: "Ennemi dans la chambre !" },
      { de: "Sniper auf dem Dach!",                  en: "Sniper on the roof!",             use: "Position callout",  fr: "Sniper sur le toit !" },
      { de: "Hinter dir!",                           en: "Behind you!",                     use: "Warning",           fr: "Derrière toi !" },
      { de: "Er flankiert uns von rechts.",          en: "He's flanking us from the right.", use: "Position callout", fr: "Il nous contourne par la droite." },
      { de: "Ich lade nach, gib mir Deckung.",       en: "I'm reloading, cover me.",        use: "Status callout",    fr: "Je recharge, couvre-moi." },
      { de: "Ich bin low HP.",                       en: "I'm low HP.",                     use: "Status callout",    fr: "Je suis low HP." },
      { de: "Ich bin one-shot.",                     en: "One more hit and I'm dead.",      use: "Status callout",    fr: "Un coup et je suis mort." },
      { de: "Ich bin down, revive mich!",            en: "I'm down, revive me!",            use: "Status callout",    fr: "Je suis à terre, relève-moi !" },
      { de: "Ich hab keine Munition mehr.",          en: "I'm out of ammo.",                use: "Status callout",    fr: "Je n'ai plus de munitions." },
      { de: "Lass uns rushen!",                      en: "Let's rush!",                     use: "Team play",         fr: "On rush !" },
      { de: "Wirf eine Granate rein!",               en: "Throw a grenade in!",             use: "Team play",         fr: "Balance une grenade !" },
      { de: "Ich pushe Mitte.",                      en: "I'm pushing mid.",                use: "Team play",         fr: "Je push au milieu." },
      { de: "Bleibt zusammen!",                      en: "Stay together!",                  use: "Team play",         fr: "Restez groupés !" },
      { de: "Noch einer übrig.",                     en: "One left.",                       use: "Enemy info",        fr: "Il en reste un." },
      { de: "Letzter ist low, hol ihn dir!",         en: "Last one's low, go get him!",     use: "Enemy info",        fr: "Le dernier est low, va le chercher !" },
      { de: "Vorsicht, Camper in der Ecke.",         en: "Watch out, camper in the corner.", use: "Enemy info",       fr: "Attention, un campeur dans le coin." },
      { de: "gg, gut gespielt Leute.",               en: "gg, good game guys.",             use: "Slang",             fr: "gg, bien joué les gars." },
      { de: "Was für ein Aim, digga!",               en: "What aim, bro!",                  use: "Slang",             fr: "Quel aim, frérot !" },
      { de: "Skill-Diff, ganz klar.",                en: "Skill diff, clearly.",            use: "Slang",             fr: "Skill diff, clairement." },
      { de: "Mein Bad, mein Fehler.",                en: "My bad, my mistake.",             use: "Slang",             fr: "Désolé, ma faute." },
      { de: "Kein Stress, nächste Runde holen wir's.", en: "No stress, we'll get it next round.", use: "Slang",       fr: "Pas de stress, on l'aura au prochain round." },
      { de: "Er carried das ganze Team.",            en: "He's carrying the whole team.",   use: "Slang",             fr: "Il carry toute l'équipe." },
    ],
  },
  part14: {
    label: "Part 14", level: "A2-B1", theme: "Everyday slang & youth talk",
    description: "How younger Germans actually talk day to day — native slang (krass, geil, Bock, das ist mir Wurst) plus the anglicised Gen-Z words (cringe, lost, geghostet, flexen).",
    focus: "Sound natural and casual: react, give opinions, and chat like a native, with French slang side by side.",
    seeds: [
      { de: "krass",         lookup: "krass",     fallbackEn: "insane",  tip: "adjective" },
      { de: "geil",          lookup: "geil",      fallbackEn: "awesome",       tip: "adjective" },
      { de: "mega",          lookup: "mega",      fallbackEn: "super",          tip: "adverb" },
      { de: "nervig",        lookup: "nervig",    fallbackEn: "annoying",              tip: "adjective" },
      { de: "verpeilt",      lookup: "verpeilt",  fallbackEn: "scatterbrained",        tip: "adjective" },
      { de: "der Bock",      lookup: "Bock",      fallbackEn: "the urge",  tip: "noun", article: "der" },
      { de: "die Kohle",     lookup: "Kohle",     fallbackEn: "cash",  tip: "noun", article: "die" },
      { de: "die Klamotten", lookup: "Klamotten", fallbackEn: "clothes",       tip: "noun", article: "die" },
      { de: "der Quatsch",   lookup: "Quatsch",   fallbackEn: "nonsense",              tip: "noun", article: "der" },
      { de: "der Hammer",    lookup: "Hammer",    fallbackEn: "awesome thing", tip: "noun", article: "der" },
      { de: "chillen",       lookup: "chillen",   fallbackEn: "to chill",              tip: "verb" },
      { de: "labern",        lookup: "labern",    fallbackEn: "to ramble",   tip: "verb" },
      { de: "pennen",        lookup: "pennen",    fallbackEn: "to sleep",      tip: "verb" },
      { de: "flexen",        lookup: "flexen",    fallbackEn: "to show off",    tip: "verb" },
      { de: "abhängen",      lookup: "abhängen",  fallbackEn: "to hang out",           tip: "verb" },
      { de: "Alter",         lookup: "Alter",     fallbackEn: "dude",    tip: "phrase" },
    ],
    dialogues: [
      { title: "Was geht?", lines: [
        { speaker: "A", de: "Ey, was geht?",                       en: "Hey, what's up?",                  fr: "Hé, ça dit quoi ?" },
        { speaker: "B", de: "Nicht viel, chill nur. Und bei dir?",  en: "Not much, just chilling. And you?", fr: "Pas grand-chose, je chill. Et toi ?" },
        { speaker: "A", de: "Läuft. Hast du Bock auf Kino?",        en: "Going well. You up for the cinema?", fr: "Ça roule. T'as envie d'aller au ciné ?" },
        { speaker: "B", de: "Auf jeden! Klingt geil.",              en: "Definitely! Sounds awesome.",       fr: "Grave ! Ça a l'air stylé." },
      ]},
      { title: "Krasse Story", lines: [
        { speaker: "A", de: "Alter, das war so krass gestern.",     en: "Dude, that was so insane yesterday.", fr: "Mec, c'était trop ouf hier." },
        { speaker: "B", de: "Erzähl, was ist passiert?",           en: "Tell me, what happened?",            fr: "Raconte, qu'est-ce qui s'est passé ?" },
        { speaker: "A", de: "Lange Story, aber war der Hammer.",    en: "Long story, but it was awesome.",    fr: "Longue histoire, mais c'était le feu." },
        { speaker: "B", de: "Hör auf zu labern, sag schon!",       en: "Stop rambling, just say it!",        fr: "Arrête de blablater, dis-le !" },
      ]},
      { title: "Kein Bock", lines: [
        { speaker: "A", de: "Kommst du heute Abend?",              en: "Are you coming tonight?",            fr: "Tu viens ce soir ?" },
        { speaker: "B", de: "Ne, hab keinen Bock, bin müde.",      en: "Nah, not in the mood, I'm tired.",   fr: "Nan, j'ai pas envie, je suis crevé." },
        { speaker: "A", de: "Komm schon, sei kein Spielverderber.", en: "Come on, don't be a spoilsport.",   fr: "Allez, fais pas ton rabat-joie." },
        { speaker: "B", de: "Okay okay, aber nicht lange.",        en: "Okay okay, but not for long.",       fr: "Ok ok, mais pas longtemps." },
      ]},
    ],
    phrases: [
      { de: "Was geht ab?",                  en: "What's up?",                     use: "Greeting",   fr: "Quoi de neuf ?" },
      { de: "Alles klar bei dir?",           en: "You all good?",                  use: "Greeting",   fr: "Tout va bien ?" },
      { de: "Läuft bei dir!",                en: "Things are going well for you!", use: "Reaction",   fr: "Ça roule pour toi !" },
      { de: "Auf jeden Fall!",               en: "Definitely!",                    use: "Reaction",   fr: "Carrément !" },
      { de: "Voll mein Ding.",               en: "Totally my thing.",              use: "Opinion",    fr: "Trop mon truc." },
      { de: "Das ist mega geil!",            en: "That's super awesome!",          use: "Opinion",    fr: "C'est trop stylé !" },
      { de: "Das ist voll der Hammer.",      en: "That's totally awesome.",        use: "Opinion",    fr: "C'est vraiment le feu." },
      { de: "Das ist mir Wurst.",            en: "I couldn't care less.",          use: "Opinion",    fr: "Je m'en fiche." },
      { de: "Das ist totaler Quatsch.",      en: "That's total nonsense.",         use: "Opinion",    fr: "C'est n'importe quoi." },
      { de: "Mach keinen Stress.",             en: "Don't make a fuss.",             use: "Reaction",   fr: "Te prends pas la tête." },
      { de: "Das ist so cringe.",            en: "That's so cringe.",              use: "Gen-Z",      fr: "C'est trop cringe." },
      { de: "Ich bin voll lost.",            en: "I'm totally clueless.",          use: "Feeling",    fr: "Je suis complètement perdu." },
      { de: "Ich hab null Bock.",            en: "I'm not in the mood at all.",    use: "Feeling",    fr: "J'ai zéro envie." },
      { de: "Ich bin total fertig.",         en: "I'm totally exhausted.",         use: "Feeling",    fr: "Je suis crevé." },
      { de: "Das nervt total.",              en: "That's so annoying.",            use: "Feeling",    fr: "Ça soûle grave." },
      { de: "Ich schwör, das ist echt.",     en: "I swear, it's real.",            use: "Emphasis",   fr: "Je te jure, c'est vrai." },
      { de: "Ich hab keine Kohle mehr.",     en: "I'm out of cash.",               use: "Money",      fr: "J'ai plus de thune." },
      { de: "Geile Klamotten, Alter!",       en: "Cool clothes, dude!",            use: "Compliment", fr: "Belles fringues, mec !" },
      { de: "Lass uns abhängen.",            en: "Let's hang out.",                use: "Plans",      fr: "On traîne ensemble ?" },
      { de: "Der ist voll der Ehrenmann.",   en: "He's a total stand-up guy.",     use: "Slang",      fr: "C'est un vrai gars bien." },
      { de: "Sheesh, das ist krass!",        en: "Sheesh, that's insane!",         use: "Gen-Z",      fr: "Sheesh, c'est ouf !" },
      { de: "Hör auf zu flexen.",            en: "Stop showing off.",              use: "Gen-Z",      fr: "Arrête de frimer." },
      { de: "Das ist voll random.",          en: "That's totally random.",         use: "Gen-Z",      fr: "C'est trop random." },
      { de: "Er hat mich geghostet.",        en: "He ghosted me.",                 use: "Gen-Z",      fr: "Il m'a ghosté." },
    ],
  },
  part15: {
    label: "Part 15", level: "A2-B1", theme: "Texting & chat shorthand",
    description: "The abbreviations Germans actually type in WhatsApp and DMs — hdl, lg, kA, vllt — plus the borrowed omg/lol, shown in real text messages.",
    focus: "Recognise German chat shorthand in context so messages make sense.",
    seeds: [
      { de: "die Nachricht", lookup: "Nachricht", fallbackEn: "message",   tip: "noun", article: "die" },
      { de: "texten",        lookup: "texten",    fallbackEn: "to text",    tip: "verb" },
      { de: "antworten",     lookup: "antworten", fallbackEn: "to reply",   tip: "verb" },
      { de: "schreiben",     lookup: "schreiben", fallbackEn: "to write",   tip: "verb" },
    ],
    dialogues: [
      { title: "WhatsApp", lines: [
        { speaker: "A", de: "Hey, wmd grade?",            en: "Hey, what you doing rn? (was machst du)", fr: "Hé, tu fais quoi là ?" },
        { speaker: "B", de: "kA, chill nur. Du?",         en: "Idk, just chilling. You? (keine Ahnung)", fr: "Aucune idée, je chill. Toi ?" },
        { speaker: "A", de: "Vllt Kino später?",          en: "Maybe cinema later? (vielleicht)",        fr: "Ciné plus tard peut-être ?" },
        { speaker: "B", de: "Jo, klingt gut. Lg!",        en: "Yeah, sounds good. Cheers! (liebe Grüße)", fr: "Ouais, ça marche. Bises !" },
      ]},
      { title: "Gute Nacht", lines: [
        { speaker: "A", de: "Ich geh pennen, gn8.",       en: "I'm off to sleep, gn. (gute Nacht)",      fr: "Je vais dormir, bonne nuit." },
        { speaker: "B", de: "Ok, schlaf gut. Hdl!",       en: "Ok, sleep well. Love ya! (hab dich lieb)", fr: "Ok, dors bien. Je t'aime fort !" },
        { speaker: "A", de: "Hdgdl, bis morgen.",         en: "Love ya loads, see you tomorrow.",        fr: "Je t'aime trop, à demain." },
        { speaker: "B", de: "Bb, träum süß.",             en: "Bye, sweet dreams. (bis bald)",           fr: "Ciao, fais de beaux rêves." },
      ]},
    ],
    phrases: [
      { de: "kA, frag jemand anderen.",   en: "No idea, ask someone else. (keine Ahnung)",      use: "Texting", fr: "Aucune idée, demande à quelqu'un d'autre." },
      { de: "Vllt komme ich später.",     en: "Maybe I'll come later. (vielleicht)",            use: "Texting", fr: "Je viendrai peut-être plus tard." },
      { de: "Kp, ist mir egal.",          en: "No prob, I don't mind. (kein Problem)",          use: "Texting", fr: "Pas de souci, ça m'est égal." },
      { de: "Bin gleich da, mom.",        en: "Almost there, one sec. (Moment)",                use: "Texting", fr: "J'arrive, deux secondes." },
      { de: "Lg und bis bald!",           en: "Cheers and see you soon! (liebe Grüße)",         use: "Texting", fr: "Bises et à bientôt !" },
      { de: "Sry, war beschäftigt.",      en: "Sorry, was busy.",                               use: "Texting", fr: "Désolé, j'étais occupé." },
      { de: "Iwie keine Lust heute.",     en: "Somehow not feeling it today. (irgendwie)",      use: "Texting", fr: "Pas trop la motiv aujourd'hui." },
      { de: "Hdl, mein Schatz.",          en: "Love ya, sweetheart. (hab dich lieb)",           use: "Texting", fr: "Je t'aime, mon cœur." },
      { de: "Mfg, dein Chef.",            en: "Best regards, your boss. (mit freundlichen Grüßen)", use: "Texting", fr: "Cordialement, ton patron." },
      { de: "Omg, das ist ja krass!",     en: "Omg, that's insane!",                            use: "Texting", fr: "Omg, c'est ouf !" },
      { de: "Lol, du bist witzig.",       en: "Lol, you're funny.",                             use: "Texting", fr: "Mdr, t'es marrant." },
      { de: "Wmd am we?",                 en: "What you up to on the weekend? (was machst du am Wochenende)", use: "Texting", fr: "Tu fais quoi ce week-end ?" },
      { de: "Kb, bin müde.",             en: "Can't be bothered, I'm tired. (kein Bock)",      use: "Texting", fr: "Pas envie, je suis fatigué." },
      { de: "Eig wollte ich schlafen.",   en: "Actually I wanted to sleep. (eigentlich)",       use: "Texting", fr: "En fait je voulais dormir." },
      { de: "Evtl bin ich später on.",   en: "Maybe I'll be on later. (eventuell)",            use: "Texting", fr: "Je serai peut-être en ligne plus tard." },
      { de: "MMn ist das fair.",          en: "In my opinion that's fair. (meiner Meinung nach)", use: "Texting", fr: "À mon avis c'est juste." },
      { de: "Lernen wir zsm?",            en: "Shall we study together? (zusammen)",            use: "Texting", fr: "On révise ensemble ?" },
      { de: "Akla, bis gleich!",          en: "All good, see you in a bit! (alles klar)",       use: "Texting", fr: "Ça marche, à tout de suite !" },
      { de: "Morgen bzw. übermorgen.",   en: "Tomorrow, or rather the day after. (beziehungsweise) / Tomorrow or the day after.", use: "Written German too", fr: "Demain, ou plutôt après-demain." },
      { de: "Bring was mit, z.B. Chips.", en: "Bring something, e.g. chips. (zum Beispiel) / Bring something, for example chips.", use: "Written German too", fr: "Apporte un truc, par ex. des chips." },
      { de: "Ca. zehn Minuten noch.",     en: "About ten minutes left. (circa) / Around ten minutes left. / Roughly ten minutes left.", use: "Written German too", fr: "Encore environ dix minutes." },
      { de: "Bücher, Stifte usw.",       en: "Books, pens and so on. (und so weiter) / Books, pens, etc.", use: "Written German too", fr: "Des livres, des stylos, etc." },
    ],
  },
  part16: {
    label: "Part 16", level: "A2", theme: "Regional greetings & expressions",
    description: "Hellos and goodbyes across the German-speaking world — Moin in the north, Servus and Grüß Gott in the south, Grüezi in Switzerland.",
    focus: "Recognise and use regional greetings so you fit in from Hamburg to Vienna.",
    seeds: [
      { de: "das Brötchen",   lookup: "Brötchen",   fallbackEn: "bread roll",        tip: "noun", article: "das" },
      { de: "der Feierabend", lookup: "Feierabend", fallbackEn: "after-work time",   tip: "noun", article: "der" },
      { de: "lecker",         lookup: "lecker",     fallbackEn: "tasty",             tip: "adjective" },
      { de: "gemütlich",      lookup: "gemütlich",  fallbackEn: "cosy",              tip: "adjective" },
    ],
    dialogues: [
      { title: "Im Norden", lines: [
        { speaker: "A", de: "Moin! Na, alles klar?",        en: "Hi! So, all good? (northern 'Moin')",   fr: "Salut ! Alors, ça va ?" },
        { speaker: "B", de: "Moin Moin! Jo, läuft.",        en: "Hi there! Yeah, all good.",             fr: "Salut salut ! Ouais, ça roule." },
        { speaker: "A", de: "Schönes Wetter heute, ne?",    en: "Nice weather today, eh?",               fr: "Beau temps aujourd'hui, non ?" },
        { speaker: "B", de: "Auf jeden. Mach's gut!",       en: "Definitely. Take care!",                fr: "Carrément. Prends soin de toi !" },
      ]},
      { title: "Im Süden", lines: [
        { speaker: "A", de: "Servus! Wie geht's dir?",      en: "Hi! How are you? (Bavarian/Austrian)",  fr: "Salut ! Comment ça va ?" },
        { speaker: "B", de: "Grüß dich! Passt scho.",       en: "Hello! All good. (southern 'passt schon')", fr: "Coucou ! Ça va nickel." },
        { speaker: "A", de: "Gehen wir was essen?",         en: "Shall we go eat?",                      fr: "On va manger ?" },
        { speaker: "B", de: "Ja freilich! Pfiat di nachher.", en: "Yes of course! See you later. (Bavarian)", fr: "Oui bien sûr ! À tout à l'heure." },
      ]},
    ],
    phrases: [
      { de: "Moin, na alles gut?",          en: "Hi, all good? (North German, any time of day)", use: "Greeting", fr: "Salut, tout va bien ?" },
      { de: "Servus, lange nicht gesehen!", en: "Hi, long time no see! (South/Austria)",         use: "Greeting", fr: "Salut, ça fait longtemps !" },
      { de: "Grüß Gott, schön Sie zu sehen.", en: "Hello, nice to see you. (formal, South)",     use: "Greeting", fr: "Bonjour, ravi de vous voir." },
      { de: "Grüezi, wie gaht's?",          en: "Hello, how are you? (Swiss German)",            use: "Greeting", fr: "Bonjour, comment ça va ? (suisse)" },
      { de: "Tach auch!",                   en: "Hi there! (casual 'Tag')",                      use: "Greeting", fr: "Salut !" },
      { de: "Gude, alles fit?",             en: "Hi, all good? (Hessian 'Gude')",                use: "Greeting", fr: "Salut, ça va ?" },
      { de: "Na, wie läuft's?",             en: "Hey, how's it going?",                          use: "Greeting", fr: "Alors, ça roule ?" },
      { de: "Mach's gut, bis bald.",        en: "Take care, see you soon.",                      use: "Farewell", fr: "Prends soin de toi, à bientôt." },
      { de: "Tschüss, schönen Tag noch!",   en: "Bye, have a nice day!",                         use: "Farewell", fr: "Salut, bonne journée !" },
      { de: "Pfiat di, bis später.",        en: "Bye, see you later. (Bavarian)",                use: "Farewell", fr: "Ciao, à plus tard." },
      { de: "Schönen Feierabend!",          en: "Enjoy your evening off! (after work)",          use: "Farewell", fr: "Bonne soirée (après le travail) !" },
      { de: "Komm gut heim!",               en: "Get home safe!",                                use: "Farewell", fr: "Rentre bien !" },
    ],
  },
  part17: {
    label: "Part 17", level: "B1", theme: "Banter & friendly trash talk",
    description: "Playful insults and teasing the way German mates rib each other — all in good fun, nothing genuinely nasty.",
    focus: "Give and take friendly banter without crossing the line.",
    seeds: [
      { de: "der Vollpfosten", lookup: "Vollpfosten", fallbackEn: "idiot",   tip: "noun", article: "der" },
      { de: "die Pfeife",      lookup: "Pfeife",      fallbackEn: "doofus",  tip: "noun", article: "die" },
      { de: "der Lauch",       lookup: "Lauch",       fallbackEn: "weakling",  tip: "noun", article: "der" },
      { de: "bescheuert",      lookup: "bescheuert",  fallbackEn: "daft",      tip: "adjective" },
      { de: "peinlich",        lookup: "peinlich",    fallbackEn: "embarrassing",      tip: "adjective" },
      { de: "lahm",            lookup: "lahm",        fallbackEn: "lame",              tip: "adjective" },
    ],
    dialogues: [
      { title: "Zockernacht", lines: [
        { speaker: "A", de: "Du Lauch, schon wieder verloren?",  en: "You weakling, lost again? (playful)", fr: "Espèce de faible, encore perdu ?" },
        { speaker: "B", de: "Halt die Klappe, du hast nur Glück.", en: "Shut it, you just got lucky.",      fr: "Tais-toi, t'as juste eu de la chance." },
        { speaker: "A", de: "Glück? Ich bin einfach besser, digga.", en: "Luck? I'm just better, bro.",     fr: "De la chance ? Je suis juste meilleur, frérot." },
        { speaker: "B", de: "Träum weiter, Vollpfosten.",        en: "Keep dreaming, you doofus.",          fr: "Continue de rêver, abruti." },
      ]},
    ],
    phrases: [
      { de: "Du Vollpfosten!",                 en: "You idiot! (playful)",                  use: "Banter", fr: "Espèce d'idiot !" },
      { de: "Spinnst du?",                     en: "Are you crazy?",                        use: "Banter", fr: "Ça va pas la tête ?" },
      { de: "Du hast doch einen Vogel.",       en: "You're nuts. (lit. you have a bird)",   use: "Banter", fr: "T'es complètement taré." },
      { de: "Halt die Klappe!",                en: "Shut up! (between mates)",              use: "Banter", fr: "Ferme-la !" },
      { de: "Träum weiter!",                   en: "Keep dreaming!",                        use: "Banter", fr: "Continue de rêver !" },
      { de: "Du bist so ein Honk.",            en: "You're such a dummy.",                  use: "Banter", fr: "T'es trop bête." },
      { de: "Mach dich nicht lächerlich.",     en: "Don't be ridiculous.",                  use: "Banter", fr: "Te rends pas ridicule." },
      { de: "Du nervst, ehrlich.",             en: "You're annoying, honestly.",            use: "Banter", fr: "Tu soûles, sérieux." },
      { de: "Ganz schwach, Alter.",            en: "Real weak, dude.",                      use: "Banter", fr: "Trop faible, mec." },
      { de: "Das war ja mal peinlich.",        en: "Well that was embarrassing.",           use: "Banter", fr: "Ça c'était la honte." },
      { de: "Du Lauch, streng dich an!",       en: "You weakling, try harder! (Gen-Z)",     use: "Banter", fr: "Espèce de faible, force un peu !" },
      { de: "Lass den Quatsch, Mann.",         en: "Cut it out, man.",                      use: "Banter", fr: "Arrête tes bêtises, mec." },
      { de: "Du hast nicht alle Tassen im Schrank.", en: "You're not all there. (idiom: not all cups in the cupboard)", use: "Banter", fr: "Tu n'as pas toute ta tête." },
      { de: "Komm, hör auf zu heulen.",        en: "Come on, stop whining.",                use: "Banter", fr: "Allez, arrête de pleurnicher." },
    ],
  },
  part18: {
    label: "Part 18", level: "B1", theme: "Dating, flirting & social",
    description: "Modern dating and social language — matching, crushes, flirting, and where things stand.",
    focus: "Navigate dating apps, flirting, and relationship talk in natural German.",
    seeds: [
      { de: "der Schwarm", lookup: "Schwarm", fallbackEn: "crush",             tip: "noun", article: "der" },
      { de: "das Date",    lookup: "Date",    fallbackEn: "date",              tip: "noun", article: "das" },
      { de: "der Korb",    lookup: "Korb",    fallbackEn: "rejection", tip: "noun", article: "der" },
      { de: "flirten",     lookup: "flirten", fallbackEn: "to flirt",          tip: "verb" },
      { de: "daten",       lookup: "daten",   fallbackEn: "to date",           tip: "verb" },
      { de: "verliebt",    lookup: "verliebt", fallbackEn: "in love",          tip: "adjective" },
      { de: "süß",         lookup: "süß",     fallbackEn: "cute",      tip: "adjective" },
    ],
    dialogues: [
      { title: "Match", lines: [
        { speaker: "A", de: "Wir haben auf Tinder gematcht!", en: "We matched on Tinder!",          fr: "On a matché sur Tinder !" },
        { speaker: "B", de: "Krass, schreib ihr doch.",       en: "Nice, message her then.",         fr: "Cool, écris-lui alors." },
        { speaker: "A", de: "Und wenn sie mich ghostet?",     en: "And what if she ghosts me?",      fr: "Et si elle me ghost ?" },
        { speaker: "B", de: "Dann ist sie's nicht wert, Bro.", en: "Then she's not worth it, bro.",  fr: "Alors elle n'en vaut pas la peine, frérot." },
      ]},
      { title: "Verliebt", lines: [
        { speaker: "A", de: "Ich glaub, ich bin verliebt.",   en: "I think I'm in love.",            fr: "Je crois que je suis amoureux." },
        { speaker: "B", de: "In wen denn? Erzähl!",           en: "With who? Tell me!",              fr: "En qui ? Raconte !" },
        { speaker: "A", de: "Mein Schwarm aus der Uni.",      en: "My crush from uni.",              fr: "Mon crush de la fac." },
        { speaker: "B", de: "Süß! Frag sie doch aus.",        en: "Cute! Ask her out then.",         fr: "Trop mignon ! Invite-la." },
      ]},
    ],
    phrases: [
      { de: "Bist du Single?",             en: "Are you single?",                       use: "Dating", fr: "T'es célibataire ?" },
      { de: "Hast du Insta?",              en: "You got Insta?",                        use: "Dating", fr: "T'as Insta ?" },
      { de: "Ich steh auf dich.",          en: "I'm into you.",                         use: "Dating", fr: "Je craque pour toi." },
      { de: "Du siehst echt gut aus.",     en: "You look really good.",                 use: "Dating", fr: "Tu es vraiment beau." },
      { de: "Lust auf einen Kaffee?",      en: "Wanna get a coffee?",                   use: "Dating", fr: "Ça te dit un café ?" },
      { de: "Er hat mir einen Korb gegeben.", en: "He turned me down. (idiom: gave a basket)", use: "Dating", fr: "Il m'a rejeté." },
      { de: "Wir sind nur Freunde.",       en: "We're just friends.",                   use: "Dating", fr: "On est juste amis." },
      { de: "Es ist kompliziert.",         en: "It's complicated.",                     use: "Dating", fr: "C'est compliqué." },
      { de: "Sie flirtet voll mit dir.",   en: "She's totally flirting with you.",      use: "Dating", fr: "Elle te drague à fond." },
      { de: "Ich date gerade jemanden.",   en: "I'm dating someone right now.",         use: "Dating", fr: "Je vois quelqu'un en ce moment." },
      { de: "Willst du mit mir ausgehen?", en: "Do you want to go out with me?",        use: "Dating", fr: "Tu veux sortir avec moi ?" },
      { de: "Wir sind jetzt zusammen.",    en: "We're together now.",                   use: "Dating", fr: "On est ensemble maintenant." },
      { de: "Er ist genau mein Typ.",      en: "He's exactly my type.",                 use: "Dating", fr: "C'est tout à fait mon genre." },
      { de: "Lass uns was trinken gehen.", en: "Let's go for a drink.",                 use: "Dating", fr: "On va boire un verre ?" },
    ],
  },
  part19: {
    label: "Part 19", level: "A2-B1", theme: "Loadouts & gunsmith talk",
    description: "Building a class in shooters like Call of Duty — attachments, unlocks, camo grinds, and the meta, the way German gamers actually say it (heavy Denglisch: das Loadout, generft, die Meta).",
    focus: "Talk weapons and loadouts naturally: attach, unlock, level up, grind, and argue about the meta.",
    seeds: [
      { de: "die Waffe",           lookup: "Waffe",           fallbackEn: "weapon",        tip: "noun", article: "die" },
      { de: "der Aufsatz",         lookup: "Aufsatz",         fallbackEn: "attachment",    tip: "noun", article: "der" },
      { de: "der Schalldämpfer",  lookup: "Schalldämpfer",  fallbackEn: "suppressor",    tip: "noun", article: "der" },
      { de: "das Visier",          lookup: "Visier",          fallbackEn: "sight",         tip: "noun", article: "das" },
      { de: "das Magazin",         lookup: "Magazin",         fallbackEn: "magazine",      tip: "noun", article: "das" },
      { de: "der Lauf",            lookup: "Lauf",            fallbackEn: "barrel",        tip: "noun", article: "der" },
      { de: "der Griff",           lookup: "Griff",           fallbackEn: "grip",          tip: "noun", article: "der" },
      { de: "der Rückstoß",      lookup: "Rückstoß",      fallbackEn: "recoil",        tip: "noun", article: "der" },
      { de: "die Reichweite",      lookup: "Reichweite",      fallbackEn: "range",         tip: "noun", article: "die" },
      { de: "die Tarnung",         lookup: "Tarnung",         fallbackEn: "camo",          tip: "noun", article: "die" },
      { de: "die Klasse",          lookup: "Klasse",          fallbackEn: "class",         tip: "noun", article: "die" },
      { de: "freischalten",        lookup: "freischalten",    fallbackEn: "to unlock",     tip: "verb" },
      { de: "aufleveln",           lookup: "aufleveln",       fallbackEn: "to level up",   tip: "verb" },
      { de: "ausrüsten",          lookup: "ausrüsten",      fallbackEn: "to equip",      tip: "verb" },
      { de: "grinden",             lookup: "grinden",         fallbackEn: "to grind",      tip: "verb" },
    ],
    dialogues: [
      { title: "Klasse bauen", lines: [
        { speaker: "A", de: "Warte kurz, ich baue noch meine Klasse.",        en: "Hang on, I'm still building my class.",         fr: "Attends, je finis de faire ma classe." },
        { speaker: "B", de: "Welche Aufsätze nimmst du?",                     en: "Which attachments are you taking?",             fr: "Tu prends quels accessoires ?" },
        { speaker: "A", de: "Schalldämpfer, langer Lauf und das Rotpunkt.",  en: "Suppressor, long barrel and the red dot.",      fr: "Silencieux, canon long et le point rouge." },
        { speaker: "B", de: "Nice, damit ist die Waffe ein Laser.",           en: "Nice, the gun's a laser with that.",            fr: "Nice, avec ça l'arme est un laser." },
      ]},
      { title: "Meta-Talk", lines: [
        { speaker: "A", de: "Die MP wurde generft, oder?",                    en: "The SMG got nerfed, right?",                    fr: "La mitraillette a été nerf, non ?" },
        { speaker: "B", de: "Ja, aber das Sturmgewehr ist jetzt Meta.",       en: "Yeah, but the assault rifle is meta now.",      fr: "Ouais, mais le fusil d'assaut est méta maintenant." },
        { speaker: "A", de: "Dann level ich das heute hoch.",                 en: "Then I'll level that up today.",                fr: "Alors je vais le monter aujourd'hui." },
        { speaker: "B", de: "Viel Spaß beim Grinden, digga.",                en: "Have fun grinding, bro.",                       fr: "Bon grind, frérot." },
      ]},
    ],
    phrases: [
      { de: "Ich baue mir ein neues Loadout.",             en: "I'm building a new loadout.",              use: "Gunsmith",  fr: "Je me fais un nouveau loadout." },
      { de: "Welche Aufsätze hast du auf der Waffe?",     en: "Which attachments do you have on the gun?", use: "Gunsmith", fr: "T'as quels accessoires sur l'arme ?" },
      { de: "Pack einen Schalldämpfer drauf.",            en: "Put a suppressor on it.",                  use: "Gunsmith",  fr: "Mets un silencieux dessus." },
      { de: "Nimm das erweiterte Magazin.",                en: "Take the extended magazine.",              use: "Gunsmith",  fr: "Prends le chargeur étendu." },
      { de: "Der lange Lauf gibt mehr Reichweite.",        en: "The long barrel gives more range.",        use: "Gunsmith",  fr: "Le canon long donne plus de portée." },
      { de: "Ohne Griff ist der Rückstoß übel.",         en: "Without a grip the recoil is nasty.",      use: "Gunsmith",  fr: "Sans poignée, le recul est horrible." },
      { de: "Ich muss das Visier noch freischalten.",      en: "I still have to unlock the sight.",        use: "Unlocks",   fr: "Je dois encore débloquer la lunette." },
      { de: "Ich level die Waffe hoch.",                   en: "I'm leveling the weapon up.",              use: "Unlocks",   fr: "Je monte l'arme en niveau." },
      { de: "Ich grinde gerade die Tarnung.",              en: "I'm grinding the camo right now.",         use: "Unlocks",   fr: "Je grind le camo en ce moment." },
      { de: "Noch zwei Level bis zum nächsten Aufsatz.",  en: "Two more levels until the next attachment.", use: "Unlocks", fr: "Encore deux niveaux avant le prochain accessoire." },
      { de: "Die Waffe ist komplett ausgelevelt.",         en: "The weapon is fully leveled.",             use: "Unlocks",   fr: "L'arme est full niveau." },
      { de: "Das ist gerade die Meta-Waffe.",              en: "That's the meta weapon right now.",        use: "Meta",      fr: "C'est l'arme méta en ce moment." },
      { de: "Die wurde letztes Update generft.",           en: "It got nerfed last update.",               use: "Meta",      fr: "Elle a été nerf à la dernière màj." },
      { de: "Die Pistole wurde gebufft.",                  en: "The pistol got buffed.",                   use: "Meta",      fr: "Le pistolet a été buff." },
      { de: "Die Waffe ist ein Laser.",                    en: "The gun is a laser. (no recoil)",          use: "Meta",      fr: "L'arme est un laser." },
      { de: "Welchen Perk nutzt du?",                      en: "Which perk do you use?",                   use: "Loadout",   fr: "Tu utilises quel atout ?" },
      { de: "Mein Loadout ist komplett.",                  en: "My loadout is complete.",                  use: "Loadout",   fr: "Mon loadout est complet." },
      { de: "Rüste die Granate aus.",                     en: "Equip the grenade.",                       use: "Loadout",   fr: "Équipe la grenade." },
    ],
  },
  part20: {
    label: "Part 20", level: "B1", theme: "Flirting & intimacy (18+)",
    description: "Adult flirting, desire, staying over — and the consent language that matters most. Everything here uses du: this is strictly informal territory.",
    focus: "Flirt like an adult, say what you want, hear what they want, and check in — clearly and confidently.",
    seeds: [
      { de: "flirten",            lookup: "flirten",       fallbackEn: "to flirt",        tip: "verb" },
      { de: "küssen",            lookup: "küssen",       fallbackEn: "to kiss",         tip: "verb" },
      { de: "der Kuss",           lookup: "Kuss",          fallbackEn: "kiss",            tip: "noun", article: "der" },
      { de: "berühren",          lookup: "berühren",     fallbackEn: "to touch",        tip: "verb" },
      { de: "verführen",         lookup: "verführen",    fallbackEn: "to seduce",       tip: "verb" },
      { de: "begehren",           lookup: "begehren",      fallbackEn: "to desire",       tip: "verb" },
      { de: "heiß",              lookup: "heiß",         fallbackEn: "hot",             tip: "adjective" },
      { de: "zärtlich",          lookup: "zärtlich",     fallbackEn: "tender",          tip: "adjective" },
      { de: "leidenschaftlich",   lookup: "leidenschaftlich", fallbackEn: "passionate",  tip: "adjective" },
      { de: "übernachten",       lookup: "übernachten",  fallbackEn: "to stay the night", tip: "verb" },
      { de: "die Zustimmung",     lookup: "Zustimmung",    fallbackEn: "consent",         tip: "noun", article: "die" },
      { de: "die Grenze",         lookup: "Grenze",        fallbackEn: "boundary",        tip: "noun", article: "die" },
    ],
    dialogues: [
      { title: "Später am Abend", lines: [
        { speaker: "A", de: "Willst du noch mit zu mir?",         en: "Do you want to come back to mine?",       fr: "Tu veux venir chez moi ?" },
        { speaker: "B", de: "Ja, sehr gern.",                     en: "Yes, I'd love to.",                        fr: "Oui, avec plaisir." },
        { speaker: "A", de: "Ich will dich küssen. Okay?",       en: "I want to kiss you. Okay?",                fr: "J'ai envie de t'embrasser. D'accord ?" },
        { speaker: "B", de: "Worauf wartest du noch?",            en: "What are you waiting for?",                fr: "Qu'est-ce que tu attends ?" },
      ]},
      { title: "Am Morgen danach", lines: [
        { speaker: "A", de: "Guten Morgen, du.",                  en: "Good morning, you.",                       fr: "Bonjour, toi." },
        { speaker: "B", de: "Letzte Nacht war unglaublich.",      en: "Last night was incredible.",               fr: "Cette nuit était incroyable." },
        { speaker: "A", de: "Bleibst du zum Frühstück?",         en: "Are you staying for breakfast?",           fr: "Tu restes pour le petit-déjeuner ?" },
        { speaker: "B", de: "Ich bleibe das ganze Wochenende.",   en: "I'm staying the whole weekend.",           fr: "Je reste tout le week-end." },
      ]},
    ],
    phrases: [
      { de: "Du machst mich verrückt.",          en: "You drive me crazy.",                       use: "Flirting",  fr: "Tu me rends fou." },
      { de: "Ich will dich.",                     en: "I want you.",                               use: "Desire",    fr: "J'ai envie de toi." },
      { de: "Ich will dich küssen.",             en: "I want to kiss you.",                       use: "Desire",    fr: "J'ai envie de t'embrasser." },
      { de: "Küss mich.",                        en: "Kiss me.",                                  use: "Desire",    fr: "Embrasse-moi." },
      { de: "Du bist so heiß.",                  en: "You're so hot.",                            use: "Flirting",  fr: "T'es trop sexy." },
      { de: "Ich kann nicht aufhören, an dich zu denken.", en: "I can't stop thinking about you.", use: "Flirting",  fr: "Je n'arrête pas de penser à toi." },
      { de: "Willst du mit zu mir?",              en: "Do you want to come back to mine?",         use: "Making a move", fr: "Tu veux venir chez moi ?" },
      { de: "Bleibst du heute Nacht?",            en: "Are you staying tonight?",                  use: "Making a move", fr: "Tu restes cette nuit ?" },
      { de: "Fass mich an.",                      en: "Touch me.",                                 use: "Desire",    fr: "Touche-moi." },
      { de: "Ich will dich verführen.",          en: "I want to seduce you.",                     use: "Desire",    fr: "Je veux te séduire." },
      { de: "Willst du das auch?",                en: "Do you want this too?",                     use: "Consent — always check", fr: "Tu en as envie aussi ?" },
      { de: "Ist das okay für dich?",            en: "Is this okay for you?",                     use: "Consent — always check", fr: "C'est bon pour toi ?" },
      { de: "Sag mir, was du magst.",             en: "Tell me what you like.",                    use: "Consent",   fr: "Dis-moi ce que tu aimes." },
      { de: "Sag mir, wenn ich aufhören soll.",   en: "Tell me if I should stop.",                 use: "Consent",   fr: "Dis-moi si je dois arrêter." },
      { de: "Langsamer.",                         en: "Slower.",                                   use: "In the moment", fr: "Plus doucement." },
      { de: "Hör auf.",                          en: "Stop.",                                     use: "Boundaries — respected instantly", fr: "Arrête." },
      { de: "Nicht heute Nacht.",                 en: "Not tonight.",                              use: "Boundaries", fr: "Pas ce soir." },
      { de: "Hast du ein Kondom?",                en: "Do you have a condom?",                     use: "Practical — just ask", fr: "Tu as un préservatif ?" },
      { de: "Das war schön.",                    en: "That was nice.",                            use: "Afterwards", fr: "C'était bien." },
      { de: "Letzte Nacht war unglaublich.",      en: "Last night was incredible.",                use: "Afterwards", fr: "Cette nuit était incroyable." },
      { de: "Hast du Lust?",                      en: "Are you in the mood?",                      use: "Euphemistic — the classic soft opener", fr: "T'as envie ?" },
      { de: "Ich will mit dir schlafen.",         en: "I want to sleep with you.",                 use: "Neutral & direct — the standard way to say it", fr: "Je veux coucher avec toi." },
      { de: "Zieh dich aus.",                     en: "Take your clothes off.",                    use: "Direct — in the moment, once things are clearly on", fr: "Déshabille-toi." },
      { de: "Ich will dich nackt sehen.",         en: "I want to see you naked.",                  use: "Direct", fr: "Je veux te voir nu." },
      { de: "Das fühlt sich so gut an.",         en: "That feels so good.",                       use: "In the moment", fr: "C'est trop bon." },
      { de: "Genau da.",                          en: "Right there.",                              use: "In the moment", fr: "Juste là." },
      { de: "Mach weiter.",                       en: "Keep going.",                               use: "In the moment", fr: "Continue." },
      { de: "Fester, bitte.",                     en: "Harder, please.",                           use: "In the moment — fester is the idiomatic word here", fr: "Plus fort." },
      { de: "Ich komme.",                         en: "I'm coming.",                               use: "In the moment — means exactly what you think", fr: "Je jouis." },
      { de: "Ich will dich ficken.",              en: "I want to fuck you.",                       use: "Very crude — only with a partner you KNOW wants this register", fr: "Je veux te baiser." },
      { de: "Fick mich.",                         en: "Fuck me.",                                  use: "Very crude — in the moment, only when clearly welcome", fr: "Baise-moi." },
      { de: "Wir haben miteinander geschlafen.",  en: "We slept together.",                        use: "Telling someone about it — neutral, not crude", fr: "On a couché ensemble." },
    ],
  },
};

export const verbConjugations: Record<string, Record<string, string>> = {
  sein:     { ich: "bin",    du: "bist",    er: "ist",    wir: "sind",    ihr: "seid",    sie: "sind" },
  haben:    { ich: "habe",   du: "hast",    er: "hat",    wir: "haben",   ihr: "habt",    sie: "haben" },
  gehen:    { ich: "gehe",   du: "gehst",   er: "geht",   wir: "gehen",   ihr: "geht",    sie: "gehen" },
  sprechen: { ich: "spreche",du: "sprichst",er: "spricht",wir: "sprechen",ihr: "sprecht", sie: "sprechen" },
  lernen:   { ich: "lerne",  du: "lernst",  er: "lernt",  wir: "lernen",  ihr: "lernt",   sie: "lernen" },
  kochen:   { ich: "koche",  du: "kochst",  er: "kocht",  wir: "kochen",  ihr: "kocht",   sie: "kochen" },
  kaufen:   { ich: "kaufe",  du: "kaufst",  er: "kauft",  wir: "kaufen",  ihr: "kauft",   sie: "kaufen" },
  brauchen: { ich: "brauche",du: "brauchst",er: "braucht",wir: "brauchen",ihr: "braucht", sie: "brauchen" },
  treffen:  { ich: "treffe", du: "triffst", er: "trifft", wir: "treffen", ihr: "trefft",  sie: "treffen" },
  planen:   { ich: "plane",  du: "planst",  er: "plant",  wir: "planen",  ihr: "plant",   sie: "planen" },
  helfen:   { ich: "helfe",  du: "hilfst",  er: "hilft",  wir: "helfen",  ihr: "helft",   sie: "helfen" },
  fahren:   { ich: "fahre",  du: "fährst", er: "fährt", wir: "fahren",  ihr: "fahrt",   sie: "fahren" },
  warten:   { ich: "warte",  du: "wartest", er: "wartet", wir: "warten",  ihr: "wartet",  sie: "warten" },
  machen:   { ich: "mache",  du: "machst",  er: "macht",  wir: "machen",  ihr: "macht",   sie: "machen" },
  geben:    { ich: "gebe",   du: "gibst",   er: "gibt",   wir: "geben",   ihr: "gebt",    sie: "geben" },
  nehmen:   { ich: "nehme",  du: "nimmst",  er: "nimmt",  wir: "nehmen",  ihr: "nehmt",   sie: "nehmen" },
  wissen:   { ich: "weiß",  du: "weißt",  er: "weiß",  wir: "wissen",  ihr: "wisst",   sie: "wissen" },
};

export const separableVerbs = [
  { verb: "aufstehen",  example: "Ich stehe früh auf.",          en: "to get up" },
  { verb: "anrufen",    example: "Ich rufe dich später an.",     en: "to call" },
  { verb: "einkaufen",  example: "Wir kaufen heute ein.",         en: "to shop" },
  { verb: "mitbringen", example: "Kannst du Brot mitbringen?",    en: "to bring along" },
];

export const entryFallbacks: Record<string, any> = {
  haus:       { word: "Haus",       pos: "noun",      glosses: ["house", "home"],              formsCount: 2, examples: ["Das Haus ist groß."],              exampleTranslations: ["The house is big."], exampleTranslationsFr: ["La maison est grande."] },
  apfel:      { word: "Apfel",      pos: "noun",      glosses: ["apple"],                      formsCount: 2, examples: ["Ich esse einen Apfel."],           exampleTranslations: ["I am eating an apple."], exampleTranslationsFr: ["Je mange une pomme."] },
  stadt:      { word: "Stadt",      pos: "noun",      glosses: ["city", "town"],               formsCount: 2, examples: ["Die Stadt ist schön."],            exampleTranslations: ["The city is beautiful."], exampleTranslationsFr: ["La ville est belle."] },
  gehen:      { word: "gehen",      pos: "verb",      glosses: ["to go", "to walk"],           formsCount: 4, examples: ["Wir gehen nach Hause."],           exampleTranslations: ["We are going home."], exampleTranslationsFr: ["Nous rentrons à la maison."] },
  sprechen:   { word: "sprechen",   pos: "verb",      glosses: ["to speak"],                   formsCount: 4, examples: ["Sie spricht Deutsch."],            exampleTranslations: ["She speaks German."], exampleTranslationsFr: ["Elle parle allemand."] },
  heute:      { word: "heute",      pos: "adverb",    glosses: ["today"],                      formsCount: 0, examples: ["Heute lerne ich Deutsch."],        exampleTranslations: ["Today I am learning German."], exampleTranslationsFr: ["Aujourd'hui j'apprends l'allemand."] },
  morgen:     { word: "morgen",     pos: "adverb",    glosses: ["tomorrow", "in the morning"], formsCount: 0, examples: ["Morgen habe ich Zeit."],           exampleTranslations: ["Tomorrow I have time."], exampleTranslationsFr: ["Demain j'ai le temps."] },
  lernen:     { word: "lernen",     pos: "verb",      glosses: ["to learn", "to study"],       formsCount: 4, examples: ["Ich lerne jeden Tag."],            exampleTranslations: ["I learn every day."], exampleTranslationsFr: ["J'apprends tous les jours."] },
  bahnhof:    { word: "Bahnhof",    pos: "noun",      glosses: ["station", "railway station"], formsCount: 2, examples: ["Der Bahnhof ist dort."],           exampleTranslations: ["The station is over there."], exampleTranslationsFr: ["La gare est là-bas."] },
  rechnung:   { word: "Rechnung",   pos: "noun",      glosses: ["bill", "invoice"],            formsCount: 2, examples: ["Die Rechnung, bitte."],            exampleTranslations: ["The bill, please."], exampleTranslationsFr: ["L'addition, s'il vous plaît."] },
  fenster:    { word: "Fenster",    pos: "noun",      glosses: ["window"],                     formsCount: 2, examples: ["Das Fenster ist offen."],          exampleTranslations: ["The window is open."], exampleTranslationsFr: ["La fenêtre est ouverte."] },
  kaufen:     { word: "kaufen",     pos: "verb",      glosses: ["to buy"],                     formsCount: 4, examples: ["Wir kaufen Wasser."],              exampleTranslations: ["We are buying water."], exampleTranslationsFr: ["Nous achetons de l'eau."] },
  brauchen:   { word: "brauchen",   pos: "verb",      glosses: ["to need"],                    formsCount: 4, examples: ["Ich brauche Hilfe."],              exampleTranslations: ["I need help."], exampleTranslationsFr: ["J'ai besoin d'aide."] },
  vielleicht: { word: "vielleicht", pos: "adverb",    glosses: ["maybe", "perhaps"],           formsCount: 0, examples: ["Vielleicht komme ich später."],    exampleTranslations: ["Maybe I will come later."], exampleTranslationsFr: ["Peut-être que je viendrai plus tard."] },
  später:    { word: "später",     pos: "adverb",    glosses: ["later"],                      formsCount: 0, examples: ["Wir sehen uns später."],           exampleTranslations: ["See you later."], exampleTranslationsFr: ["On se voit plus tard."] },
  frage:      { word: "Frage",      pos: "noun",      glosses: ["question"],                   formsCount: 2, examples: ["Ich habe eine Frage."],            exampleTranslations: ["I have a question."], exampleTranslationsFr: ["J'ai une question."] },
  bett:       { word: "Bett",       pos: "noun",      glosses: ["bed"],                        formsCount: 2, examples: ["Das Bett ist bequem."],            exampleTranslations: ["The bed is comfortable."], exampleTranslationsFr: ["Le lit est confortable."] },
  arbeit:     { word: "Arbeit",     pos: "noun",      glosses: ["work", "job"],                formsCount: 2, examples: ["Die Arbeit ist wichtig."],         exampleTranslations: ["Work is important."], exampleTranslationsFr: ["Le travail est important."] },
  kochen:     { word: "kochen",     pos: "verb",      glosses: ["to cook"],                    formsCount: 4, examples: ["Ich koche am Abend."],             exampleTranslations: ["I cook in the evening."], exampleTranslationsFr: ["Je cuisine le soir."] },
  früh:      { word: "früh",       pos: "adjective", glosses: ["early"],                      formsCount: 1, examples: ["Ich stehe früh auf."],             exampleTranslations: ["I get up early."], exampleTranslationsFr: ["Je me lève tôt."] },
  oft:        { word: "oft",        pos: "adverb",    glosses: ["often"],                      formsCount: 0, examples: ["Wir üben oft."],                  exampleTranslations: ["We practise often."], exampleTranslationsFr: ["Nous nous entraînons souvent."] },
  müde:      { word: "müde",       pos: "adjective", glosses: ["tired"],                      formsCount: 1, examples: ["Ich bin müde."],                  exampleTranslations: ["I am tired."], exampleTranslationsFr: ["Je suis fatigué."] },
  termin:     { word: "Termin",     pos: "noun",      glosses: ["appointment", "meeting time"],formsCount: 2, examples: ["Ich habe einen Termin."],          exampleTranslations: ["I have an appointment."], exampleTranslationsFr: ["J'ai un rendez-vous."] },
  idee:       { word: "Idee",       pos: "noun",      glosses: ["idea"],                       formsCount: 2, examples: ["Das ist eine gute Idee."],         exampleTranslations: ["That is a good idea."], exampleTranslationsFr: ["C'est une bonne idée."] },
  wochenende: { word: "Wochenende", pos: "noun",      glosses: ["weekend"],                    formsCount: 2, examples: ["Am Wochenende habe ich Zeit."],    exampleTranslations: ["I have time at the weekend."], exampleTranslationsFr: ["Le week-end j'ai le temps."] },
  treffen:    { word: "treffen",    pos: "verb",      glosses: ["to meet", "to hit"],          formsCount: 4, examples: ["Wir treffen uns morgen."],         exampleTranslations: ["We are meeting tomorrow."], exampleTranslationsFr: ["Nous nous retrouvons demain."] },
  planen:     { word: "planen",     pos: "verb",      glosses: ["to plan"],                    formsCount: 4, examples: ["Ich plane einen Ausflug."],        exampleTranslations: ["I am planning a trip."], exampleTranslationsFr: ["Je prévois une excursion."] },
  zusammen:   { word: "zusammen",   pos: "adverb",    glosses: ["together"],                   formsCount: 0, examples: ["Wir lernen zusammen."],            exampleTranslations: ["We are learning together."], exampleTranslationsFr: ["Nous apprenons ensemble."] },
  woche:      { word: "Woche",      pos: "noun",      glosses: ["week"],                       formsCount: 2, examples: ["Nächste Woche habe ich Zeit."],    exampleTranslations: ["I have time next week."], exampleTranslationsFr: ["La semaine prochaine j'ai le temps."] },
  klingen:    { word: "klingen",    pos: "verb",      glosses: ["to sound"],                   formsCount: 4, examples: ["Das klingt gut."],                 exampleTranslations: ["That sounds good."], exampleTranslationsFr: ["Ça a l'air bien."] },
  brot:       { word: "Brot",       pos: "noun",      glosses: ["bread"],                      formsCount: 2, examples: ["Das Brot ist frisch."],            exampleTranslations: ["The bread is fresh."], exampleTranslationsFr: ["Le pain est frais."] },
  kaffee:     { word: "Kaffee",     pos: "noun",      glosses: ["coffee"],                     formsCount: 2, examples: ["Der Kaffee ist heiß."],            exampleTranslations: ["The coffee is hot."], exampleTranslationsFr: ["Le café est chaud."] },
  tee:        { word: "Tee",        pos: "noun",      glosses: ["tea"],                        formsCount: 2, examples: ["Ich trinke Tee."],                 exampleTranslations: ["I am drinking tea."], exampleTranslationsFr: ["Je bois du thé."] },
  milch:      { word: "Milch",      pos: "noun",      glosses: ["milk"],                       formsCount: 2, examples: ["Die Milch ist kalt."],             exampleTranslations: ["The milk is cold."], exampleTranslationsFr: ["Le lait est froid."] },
  bestellen:  { word: "bestellen",  pos: "verb",      glosses: ["to order"],                   formsCount: 4, examples: ["Ich möchte bestellen."],           exampleTranslations: ["I would like to order."], exampleTranslationsFr: ["Je voudrais commander."] },
  hungrig:    { word: "hungrig",    pos: "adjective", glosses: ["hungry"],                     formsCount: 1, examples: ["Ich bin hungrig."],                exampleTranslations: ["I am hungry."], exampleTranslationsFr: ["J'ai faim."] },
  strasse:    { word: "Straße",     pos: "noun",      glosses: ["street", "road"],             formsCount: 2, examples: ["Die Straße ist lang."],            exampleTranslations: ["The street is long."], exampleTranslationsFr: ["La rue est longue."] },
  ticket:     { word: "Ticket",     pos: "noun",      glosses: ["ticket"],                     formsCount: 2, examples: ["Ich brauche ein Ticket."],         exampleTranslations: ["I need a ticket."], exampleTranslationsFr: ["J'ai besoin d'un billet."] },
  links:      { word: "links",      pos: "adverb",    glosses: ["left"],                       formsCount: 0, examples: ["Gehe hier links."],               exampleTranslations: ["Turn left here."], exampleTranslationsFr: ["Tourne à gauche ici."] },
  rechts:     { word: "rechts",     pos: "adverb",    glosses: ["right"],                      formsCount: 0, examples: ["Dann rechts."],                  exampleTranslations: ["Then right."], exampleTranslationsFr: ["Puis à droite."] },
  fahren:     { word: "fahren",     pos: "verb",      glosses: ["to drive", "to travel"],      formsCount: 4, examples: ["Wir fahren nach Berlin."],         exampleTranslations: ["We are travelling to Berlin."], exampleTranslationsFr: ["Nous allons à Berlin."] },
  warten:     { word: "warten",     pos: "verb",      glosses: ["to wait"],                    formsCount: 4, examples: ["Ich warte hier."],                 exampleTranslations: ["I am waiting here."], exampleTranslationsFr: ["J'attends ici."] },
  familie:    { word: "Familie",    pos: "noun",      glosses: ["family"],                     formsCount: 2, examples: ["Meine Familie ist klein."],        exampleTranslations: ["My family is small."], exampleTranslationsFr: ["Ma famille est petite."] },
  freund:     { word: "Freund",     pos: "noun",      glosses: ["friend"],                     formsCount: 2, examples: ["Mein Freund ist nett."],           exampleTranslations: ["My friend is nice."], exampleTranslationsFr: ["Mon ami est gentil."] },
  freundin:   { word: "Freundin",   pos: "noun",      glosses: ["female friend", "girlfriend"],formsCount: 2, examples: ["Meine Freundin ist freundlich."],  exampleTranslations: ["My friend is friendly."], exampleTranslationsFr: ["Mon amie est gentille."] },
  kind:       { word: "Kind",       pos: "noun",      glosses: ["child"],                      formsCount: 2, examples: ["Das Kind spielt."],               exampleTranslations: ["The child is playing."], exampleTranslationsFr: ["L'enfant joue."] },
  helfen:     { word: "helfen",     pos: "verb",      glosses: ["to help"],                    formsCount: 4, examples: ["Kannst du mir helfen?"],           exampleTranslations: ["Can you help me?"], exampleTranslationsFr: ["Peux-tu m'aider ?"] },
  freundlich: { word: "freundlich", pos: "adjective", glosses: ["friendly"],                   formsCount: 1, examples: ["Er ist freundlich."],              exampleTranslations: ["He is friendly."], exampleTranslationsFr: ["Il est gentil."] },
  sein:       { word: "sein",       pos: "verb",      glosses: ["to be"],                      formsCount: 6, examples: ["Ich bin hier."],                  exampleTranslations: ["I am here."], exampleTranslationsFr: ["Je suis ici."] },
  haben:      { word: "haben",      pos: "verb",      glosses: ["to have"],                    formsCount: 6, examples: ["Ich habe Zeit."],                  exampleTranslations: ["I have time."], exampleTranslationsFr: ["J'ai le temps."] },
  machen:     { word: "machen",     pos: "verb",      glosses: ["to make", "to do"],           formsCount: 4, examples: ["Wir machen das zusammen."],        exampleTranslations: ["We are doing that together."], exampleTranslationsFr: ["Nous faisons ça ensemble."] },
  geben:      { word: "geben",      pos: "verb",      glosses: ["to give"],                    formsCount: 4, examples: ["Kannst du mir das geben?"],        exampleTranslations: ["Can you give me that?"], exampleTranslationsFr: ["Peux-tu me donner ça ?"] },
  nehmen:     { word: "nehmen",     pos: "verb",      glosses: ["to take"],                    formsCount: 4, examples: ["Ich nehme einen Kaffee."],         exampleTranslations: ["I will take a coffee."], exampleTranslationsFr: ["Je prends un café."] },
  wissen:     { word: "wissen",     pos: "verb",      glosses: ["to know"],                    formsCount: 6, examples: ["Ich weiß es nicht."],              exampleTranslations: ["I do not know."], exampleTranslationsFr: ["Je ne sais pas."] },
  // Part 9 — Home and daily errands
  wohnen:     { word: "wohnen",     pos: "verb",      glosses: ["to live", "to reside"],       formsCount: 4, examples: ["Ich wohne in Berlin."],           exampleTranslations: ["I live in Berlin."], exampleTranslationsFr: ["J'habite à Berlin."] },
  bleiben:    { word: "bleiben",    pos: "verb",      glosses: ["to stay", "to remain"],       formsCount: 4, examples: ["Wir bleiben zu Hause."],           exampleTranslations: ["We are staying home."], exampleTranslationsFr: ["Nous restons à la maison."] },
  küche:      { word: "Küche",      pos: "noun",      glosses: ["kitchen"],                    formsCount: 2, examples: ["Die Küche ist klein."],           exampleTranslations: ["The kitchen is small."], exampleTranslationsFr: ["La cuisine est petite."] },
  geschäft:   { word: "Geschäft",   pos: "noun",      glosses: ["shop", "store", "business"],  formsCount: 2, examples: ["Das Geschäft ist geschlossen."],   exampleTranslations: ["The shop is closed."], exampleTranslationsFr: ["Le magasin est fermé."] },
  öffnen:     { word: "öffnen",     pos: "verb",      glosses: ["to open"],                    formsCount: 4, examples: ["Ich öffne das Fenster."],          exampleTranslations: ["I open the window."], exampleTranslationsFr: ["J'ouvre la fenêtre."] },
  // Part 10 — Work and study
  arbeiten:   { word: "arbeiten",   pos: "verb",      glosses: ["to work"],                    formsCount: 4, examples: ["Ich arbeite heute."],            exampleTranslations: ["I am working today."], exampleTranslationsFr: ["Je travaille aujourd'hui."] },
  erklären:   { word: "erklären",   pos: "verb",      glosses: ["to explain"],                 formsCount: 4, examples: ["Kannst du das erklären?"],         exampleTranslations: ["Can you explain that?"], exampleTranslationsFr: ["Peux-tu expliquer ça ?"] },
  plan:       { word: "Plan",       pos: "noun",      glosses: ["plan"],                       formsCount: 2, examples: ["Der Plan ist gut."],             exampleTranslations: ["The plan is good."], exampleTranslationsFr: ["Le plan est bon."] },
  computer:   { word: "Computer",   pos: "noun",      glosses: ["computer"],                   formsCount: 2, examples: ["Der Computer ist neu."],          exampleTranslations: ["The computer is new."], exampleTranslationsFr: ["L'ordinateur est neuf."] },
  wichtig:    { word: "wichtig",    pos: "adjective", glosses: ["important"],                  formsCount: 0, examples: ["Das ist sehr wichtig."],         exampleTranslations: ["That is very important."], exampleTranslationsFr: ["C'est très important."] },
  // Part 11 — Opinions and media
  finden:     { word: "finden",     pos: "verb",      glosses: ["to find", "to think"],        formsCount: 4, examples: ["Ich finde das gut."],            exampleTranslations: ["I think that is good."], exampleTranslationsFr: ["Je trouve ça bien."] },
  glauben:    { word: "glauben",    pos: "verb",      glosses: ["to believe", "to think"],     formsCount: 4, examples: ["Ich glaube dir."],               exampleTranslations: ["I believe you."], exampleTranslationsFr: ["Je te crois."] },
  nachricht:  { word: "Nachricht",  pos: "noun",      glosses: ["message", "news"],            formsCount: 2, examples: ["Ich habe eine Nachricht."],       exampleTranslations: ["I have a message."], exampleTranslationsFr: ["J'ai un message."] },
  film:       { word: "Film",       pos: "noun",      glosses: ["film", "movie"],              formsCount: 2, examples: ["Der Film ist spannend."],         exampleTranslations: ["The film is exciting."], exampleTranslationsFr: ["Le film est passionnant."] },
  interessant:{ word: "interessant",pos: "adjective", glosses: ["interesting"],                formsCount: 0, examples: ["Das Buch ist interessant."],      exampleTranslations: ["The book is interesting."], exampleTranslationsFr: ["Le livre est intéressant."] },
  // Part 12 — Travel and problems
  vergessen:  { word: "vergessen",  pos: "verb",      glosses: ["to forget"],                  formsCount: 4, examples: ["Ich habe es vergessen."],        exampleTranslations: ["I forgot it."], exampleTranslationsFr: ["Je l'ai oublié."] },
  verlieren:  { word: "verlieren",  pos: "verb",      glosses: ["to lose"],                    formsCount: 4, examples: ["Ich verliere nie."],             exampleTranslations: ["I never lose."], exampleTranslationsFr: ["Je ne perds jamais."] },
  problem:    { word: "Problem",    pos: "noun",      glosses: ["problem"],                    formsCount: 2, examples: ["Das ist kein Problem."],         exampleTranslations: ["That is no problem."], exampleTranslationsFr: ["Ce n'est pas un problème."] },
  hilfe:      { word: "Hilfe",      pos: "noun",      glosses: ["help"],                       formsCount: 2, examples: ["Ich brauche Hilfe."],            exampleTranslations: ["I need help."], exampleTranslationsFr: ["J'ai besoin d'aide."] },
  spät:       { word: "spät",       pos: "adjective", glosses: ["late"],                       formsCount: 0, examples: ["Es ist schon spät."],            exampleTranslations: ["It is already late."], exampleTranslationsFr: ["Il est déjà tard."] },
};
