import { lebenInDeutschlandCourse } from "@/lib/lebenInDeutschlandCourse";
import type { CountryLevel, CountryQuestion } from "@/lib/countryStudies";

/**
 * Der Übungspool für "Leben in Deutschland".
 *
 * Gebaut wie der Life-in-the-UK-Pool und aus demselben Grund von den Quizfragen
 * in den Lektionen getrennt: Die dort schließen eine Lektion ab, während der
 * Stoff noch auf dem Bildschirm steht. Diese hier werden immer wieder gezogen,
 * in beliebiger Reihenfolge, lange nachdem die Lektion gelesen wurde.
 *
 * Keine Frage aus den Lektionen taucht hier ein zweites Mal auf. Nichts darf
 * doppelt verwendet werden — also prüft
 * check-de-questions, dass sich kein Fragetext zwischen Kurs und Pool
 * wiederholt.
 *
 * Jede Frage trägt die id der Lektion, die sie unterrichtet. Das Kapitel kommt
 * aus der Lektion, nicht aus einem zweiten Verzeichnis, das jemand von Hand
 * pflegen müsste.
 *
 * Die Schwierigkeit ist gesetzt, nicht berechnet. "leicht" heißt: Die Antwort
 * steht so in der Lektion. "mittel" heißt: Ein bestimmter Name, ein Datum oder
 * eine Zahl muss erinnert werden. "schwer" heißt: Zwei Fakten müssen zusammen
 * gehalten werden, oder die Frage zielt auf eine bekannte Verwechslung —
 * 9. November gegen 3. Oktober, 1949 gegen 1990, Bundestag gegen Bundesrat.
 *
 * Nichts davon ist aus dem amtlichen Fragenkatalog abgeschrieben. Die
 * Sachverhalte sind öffentlich; die Formulierungen sind unsere.
 */

export const DE_QUESTIONS: CountryQuestion[] = [
  // ── Grundgesetz und Grundrechte ────────────────────────────────────────
  { id: "gr-1", lesson: "de-grundrechte", level: "easy",
    q: "Wie heißt die Verfassung der Bundesrepublik Deutschland?",
    options: [
      "Bundesverfassung",
      "Grundgesetz",
      "Reichsverfassung",
      "Staatsvertrag",
    ], answer: 1,
    explanation: "Sie heißt Grundgesetz. Der Name war 1949 als Provisorium gedacht — bis zur Wiedervereinigung wollte man sich das Wort „Verfassung“ aufheben." },
  { id: "gr-2", lesson: "de-grundrechte", level: "medium",
    q: "Seit wann gilt das Grundgesetz?",
    options: [
      "Seit dem 8. Mai 1945",
      "Seit dem 23. Mai 1949",
      "Seit dem 7. Oktober 1949",
      "Seit dem 3. Oktober 1990",
    ], answer: 1,
    explanation: "23. Mai 1949. Der 7. Oktober 1949 ist die Gründung der DDR, der 3. Oktober 1990 die Wiedervereinigung." },
  { id: "gr-3", lesson: "de-grundrechte", level: "easy",
    q: "Welches Recht gehört zu den Grundrechten im Grundgesetz?",
    options: [
      "Das Recht auf ein eigenes Auto",
      "Die Meinungsfreiheit",
      "Das Recht auf einen Arbeitsplatz beim Staat",
      "Das Recht auf ein Studium ohne Abschluss",
    ], answer: 1,
    explanation: "Die Meinungsfreiheit steht in Artikel 5. Die anderen drei sind keine Grundrechte." },
  { id: "gr-4", lesson: "de-grundrechte", level: "medium",
    q: "Was sagt Artikel 3 des Grundgesetzes?",
    options: [
      "Die Würde des Menschen ist unantastbar",
      "Alle Menschen sind vor dem Gesetz gleich",
      "Jeder hat das Recht auf Leben",
      "Die Kunst ist frei",
    ], answer: 1,
    explanation: "Artikel 3 ist der Gleichheitssatz. Die Menschenwürde steht in Artikel 1, die Kunstfreiheit in Artikel 5." },
  { id: "gr-5", lesson: "de-grundrechte", level: "hard",
    q: "Welche Aussage über die Meinungsfreiheit in Deutschland ist richtig?",
    options: [
      "Man darf alles sagen, ohne jede Grenze",
      "Sie endet dort, wo Volksverhetzung oder Beleidigung beginnt",
      "Sie gilt nur für deutsche Staatsangehörige",
      "Sie gilt nur in privaten Gesprächen",
    ], answer: 1,
    explanation: "Meinungsfreiheit ist weit, aber nicht grenzenlos: Volksverhetzung, Beleidigung und Holocaustleugnung sind Straftaten." },
  { id: "gr-6", lesson: "de-grundrechte", level: "hard",
    q: "Wie viele Fragen umfasst der Einbürgerungstest, und wie viele davon betreffen das Bundesland?",
    options: [
      "30 Fragen, davon 3 zum Bundesland",
      "33 Fragen, davon 3 zum Bundesland",
      "33 Fragen, davon 10 zum Bundesland",
      "25 Fragen, davon 5 zum Bundesland",
    ], answer: 1,
    explanation: "33 Fragen insgesamt: 30 aus dem bundesweiten Katalog und 3 zum Bundesland, in dem der Test geschrieben wird." },

  // ── Demokratie und Rechtsstaat ─────────────────────────────────────────
  { id: "dem-1", lesson: "de-demokratie", level: "easy",
    q: "Von wem geht in Deutschland alle Staatsgewalt aus?",
    options: [
      "Vom Bundespräsidenten",
      "Vom Volk",
      "Von den Parteien",
      "Von den Bundesländern",
    ], answer: 1,
    explanation: "Artikel 20: „Alle Staatsgewalt geht vom Volke aus.“ Ausgeübt wird sie durch Wahlen und durch die drei Gewalten." },
  { id: "dem-2", lesson: "de-demokratie", level: "medium",
    q: "Welche Staatsform hat Deutschland?",
    options: [
      "Monarchie",
      "Republik",
      "Diktatur",
      "Kaiserreich",
    ], answer: 1,
    explanation: "Eine Republik: Das Staatsoberhaupt wird gewählt, es gibt keinen König und keinen Kaiser." },
  { id: "dem-3", lesson: "de-demokratie", level: "medium",
    q: "Was gehört zur Exekutive?",
    options: [
      "Der Bundestag",
      "Die Polizei",
      "Das Bundesverfassungsgericht",
      "Der Bundesrat",
    ], answer: 1,
    explanation: "Die Polizei führt Gesetze aus und gehört damit zur Exekutive. Bundestag und Bundesrat sind Legislative, die Gerichte Judikative." },
  { id: "dem-4", lesson: "de-demokratie", level: "easy",
    q: "Was bedeutet „Rechtsstaat“?",
    options: [
      "Der Staat kann tun, was er für richtig hält",
      "Auch der Staat ist an Gesetze gebunden",
      "Nur Juristen dürfen Politik machen",
      "Es gibt besonders viele Gesetze",
    ], answer: 1,
    explanation: "Im Rechtsstaat gilt das Gesetz auch für den Staat selbst — und gegen jede staatliche Entscheidung kann man klagen." },
  { id: "dem-5", lesson: "de-demokratie", level: "hard",
    q: "Was bedeutet „wehrhafte Demokratie“?",
    options: [
      "Deutschland hat eine starke Armee",
      "Die Demokratie schützt sich vor denen, die sie abschaffen wollen",
      "Bürger dürfen sich mit Waffen verteidigen",
      "Der Staat wehrt sich gegen Kritik",
    ], answer: 1,
    explanation: "Verfassungsfeindliche Parteien können verboten werden, und der Kern der Verfassung ist unabänderlich. Mit der Armee hat der Begriff nichts zu tun." },
  { id: "dem-6", lesson: "de-demokratie", level: "hard",
    q: "Warum sind die Gewalten in Deutschland getrennt?",
    options: [
      "Damit die Arbeit schneller geht",
      "Damit keine Stelle allein über alles bestimmen kann",
      "Weil es die EU vorschreibt",
      "Weil es in der Weimarer Verfassung so stand",
    ], answer: 1,
    explanation: "Machtkontrolle ist der Zweck: Was die eine Gewalt beschließt, führt die zweite aus und überprüft die dritte." },

  // ── Bundestag und Gesetzgebung ─────────────────────────────────────────
  { id: "bt-1", lesson: "de-bundestag", level: "easy",
    q: "Welches Verfassungsorgan wird in Deutschland direkt vom Volk gewählt?",
    options: [
      "Der Bundesrat",
      "Der Bundestag",
      "Die Bundesregierung",
      "Das Bundesverfassungsgericht",
    ], answer: 1,
    explanation: "Nur der Bundestag wird direkt gewählt. Alle anderen Organe gehen mittelbar aus Wahlen hervor." },
  { id: "bt-2", lesson: "de-bundestag", level: "medium",
    q: "Was ist eine Fraktion im Bundestag?",
    options: [
      "Ein Ausschuss für Finanzfragen",
      "Der Zusammenschluss der Abgeordneten einer Partei",
      "Die Regierungsmannschaft des Kanzlers",
      "Eine Gruppe von Ministerien",
    ], answer: 1,
    explanation: "Abgeordnete derselben Partei schließen sich zur Fraktion zusammen. Fraktionen bestimmen den Arbeitsalltag des Parlaments." },
  { id: "bt-3", lesson: "de-bundestag", level: "medium",
    q: "Wer darf einen Gesetzentwurf in den Bundestag einbringen?",
    options: [
      "Nur die Bundesregierung",
      "Bundesregierung, Bundestag oder Bundesrat",
      "Nur der Bundespräsident",
      "Jeder Bürger direkt",
    ], answer: 1,
    explanation: "Drei Wege führen zu einem Gesetzentwurf: aus der Regierung, aus der Mitte des Bundestages oder aus dem Bundesrat." },
  { id: "bt-4", lesson: "de-bundestag", level: "hard",
    q: "Was versteht man unter dem Budgetrecht des Bundestages?",
    options: [
      "Das Recht, die Steuern selbst einzuziehen",
      "Das Recht, über den Haushalt des Bundes zu entscheiden",
      "Das Recht der Abgeordneten auf ein Gehalt",
      "Das Recht, Kredite privat aufzunehmen",
    ], answer: 1,
    explanation: "Das Parlament entscheidet, wofür der Staat Geld ausgibt. Deshalb gilt das Budgetrecht als Königsrecht des Bundestages." },
  { id: "bt-5", lesson: "de-bundestag", level: "hard",
    q: "Wie viele Stimmen hat ein Bundesland im Bundesrat?",
    options: [
      "Jedes Land hat genau eine Stimme",
      "Je nach Einwohnerzahl drei bis sechs Stimmen",
      "Jedes Land hat zehn Stimmen",
      "Die Zahl wechselt jedes Jahr",
    ], answer: 1,
    explanation: "Drei bis sechs Stimmen, gestaffelt nach Einwohnerzahl — und ein Land muss seine Stimmen einheitlich abgeben." },
  { id: "bt-6", lesson: "de-bundestag", level: "medium",
    q: "Was ist ein Untersuchungsausschuss?",
    options: [
      "Ein Gericht für Abgeordnete",
      "Ein Gremium des Bundestages, das Vorgänge aufklärt und die Regierung kontrolliert",
      "Eine Behörde zur Prüfung von Gesetzen",
      "Der Ausschuss, der den Haushalt aufstellt",
    ], answer: 1,
    explanation: "Er gehört zur Kontrollfunktion des Parlaments: Der Bundestag klärt damit auf, was die Regierung lieber unerwähnt ließe." },

  // ── Bundesregierung und Bundespräsident ────────────────────────────────
  { id: "reg-1", lesson: "de-regierung", level: "easy",
    q: "Wer leitet die Bundesregierung?",
    options: [
      "Der Bundespräsident",
      "Der Bundeskanzler",
      "Der Bundestagspräsident",
      "Der Präsident des Bundesrates",
    ], answer: 1,
    explanation: "Der Bundeskanzler führt die Regierung und bestimmt die Richtlinien der Politik. Der Bundespräsident regiert nicht." },
  { id: "reg-2", lesson: "de-regierung", level: "medium",
    q: "Wer wählt den Bundespräsidenten?",
    options: [
      "Der Bundestag allein",
      "Die Bundesversammlung",
      "Das Volk direkt",
      "Der Bundesrat",
    ], answer: 1,
    explanation: "Die Bundesversammlung — zur Hälfte Bundestagsabgeordnete, zur Hälfte Vertreter der Länder. Sie tritt nur zu diesem Zweck zusammen." },
  { id: "reg-3", lesson: "de-regierung", level: "medium",
    q: "Was bedeutet Richtlinienkompetenz?",
    options: [
      "Der Kanzler bestimmt die Grundlinien der Politik",
      "Der Bundespräsident gibt die Gesetze vor",
      "Die Ministerien schreiben eigene Richtlinien",
      "Der Bundesrat gibt den Ländern Richtlinien",
    ], answer: 0,
    explanation: "Der Kanzler setzt die Leitlinien; innerhalb dieser Linien führt jeder Minister sein Haus eigenständig." },
  { id: "reg-4", lesson: "de-regierung", level: "hard",
    q: "Wer ernennt die Bundesminister?",
    options: [
      "Der Bundestag durch Wahl",
      "Der Bundespräsident auf Vorschlag des Kanzlers",
      "Der Kanzler allein, ohne weitere Beteiligung",
      "Der Bundesrat",
    ], answer: 1,
    explanation: "Vorschlagen darf der Kanzler, ernennen muss der Bundespräsident. Zwei Schritte, die gern zu einem verkürzt werden." },
  { id: "reg-5", lesson: "de-regierung", level: "hard",
    q: "Wie oft darf eine Person das Amt des Bundespräsidenten ausüben?",
    options: [
      "Nur einmal",
      "Höchstens zweimal",
      "Beliebig oft",
      "Bis zum 70. Lebensjahr",
    ], answer: 1,
    explanation: "Zwei Amtszeiten zu je fünf Jahren, also höchstens zehn Jahre. Für den Kanzler gibt es keine solche Grenze." },
  { id: "reg-6", lesson: "de-regierung", level: "easy",
    q: "Wie nennt man Kanzler und Minister zusammen?",
    options: [
      "Bundesversammlung",
      "Bundesregierung oder Kabinett",
      "Bundesrat",
      "Bundestag",
    ], answer: 1,
    explanation: "Bundeskanzler und Bundesminister bilden gemeinsam die Bundesregierung, umgangssprachlich das Kabinett." },

  // ── Wahlen und Parteien ────────────────────────────────────────────────
  { id: "wa-1", lesson: "de-wahlen", level: "easy",
    q: "Wie oft findet in Deutschland regulär eine Bundestagswahl statt?",
    options: [
      "Alle zwei Jahre",
      "Alle vier Jahre",
      "Alle fünf Jahre",
      "Alle sechs Jahre",
    ], answer: 1,
    explanation: "Alle vier Jahre. Das Europäische Parlament wird alle fünf Jahre gewählt — daher die häufige Verwechslung." },
  { id: "wa-2", lesson: "de-wahlen", level: "medium",
    q: "Was bedeutet „freie Wahl“?",
    options: [
      "Die Wahl kostet nichts",
      "Niemand darf zu einer bestimmten Entscheidung gezwungen werden",
      "Jeder kann sich aussuchen, wann er wählt",
      "Man kann mehrere Stimmen abgeben",
    ], answer: 1,
    explanation: "Frei heißt: ohne Druck und ohne Zwang. Weder Staat noch Arbeitgeber noch Familie dürfen eine Stimme vorschreiben." },
  { id: "wa-3", lesson: "de-wahlen", level: "medium",
    q: "Was ist die Fünf-Prozent-Hürde?",
    options: [
      "Eine Partei braucht mindestens fünf Prozent der Zweitstimmen, um in den Bundestag zu kommen",
      "Fünf Prozent der Wähler müssen zur Wahl gehen",
      "Ein Kandidat braucht fünf Prozent im Wahlkreis",
      "Fünf Prozent der Sitze bleiben immer frei",
    ], answer: 0,
    explanation: "Sie hält Kleinstparteien draußen und soll das Parlament arbeitsfähig halten — eine Lehre aus der zersplitterten Weimarer Republik." },
  { id: "wa-4", lesson: "de-wahlen", level: "hard",
    q: "Wofür wird die Erststimme bei der Bundestagswahl verwendet?",
    options: [
      "Für die Wahl einer Partei",
      "Für die Wahl eines Kandidaten im eigenen Wahlkreis",
      "Für die Wahl des Bundeskanzlers",
      "Für die Wahl des Bundespräsidenten",
    ], answer: 1,
    explanation: "Die Erststimme gilt einer Person im Wahlkreis, die Zweitstimme einer Partei. Kanzler und Präsident wählt das Volk gar nicht." },
  { id: "wa-5", lesson: "de-wahlen", level: "hard",
    q: "Wer darf in Deutschland bei Kommunalwahlen häufig mitwählen, ohne die deutsche Staatsangehörigkeit zu haben?",
    options: [
      "Niemand",
      "Bürger anderer EU-Staaten, die hier wohnen",
      "Alle Personen mit Aufenthaltstitel",
      "Nur Personen aus Nachbarländern",
    ], answer: 1,
    explanation: "EU-Bürger dürfen dort wählen, wo sie leben — bei Kommunal- und Europawahlen. Für die Bundestagswahl braucht es den deutschen Pass." },
  { id: "wa-6", lesson: "de-wahlen", level: "easy",
    q: "Was ist die Opposition im Bundestag?",
    options: [
      "Die Parteien, die nicht die Regierung stellen",
      "Die Minister ohne eigenes Ministerium",
      "Die Abgeordneten des Bundesrates",
      "Die Verwaltung des Parlaments",
    ], answer: 0,
    explanation: "Sie kontrolliert die Regierung, stellt Alternativen zur Debatte und ist damit ein fester Bestandteil der Demokratie." },

  // ── Föderalismus und Bundesländer ──────────────────────────────────────
  { id: "fo-1", lesson: "de-foederalismus", level: "easy",
    q: "Wie heißt das Parlament eines Bundeslandes in den meisten Ländern?",
    options: [
      "Bundestag",
      "Landtag",
      "Gemeinderat",
      "Bundesrat",
    ], answer: 1,
    explanation: "Landtag. In Hamburg und Bremen heißt es Bürgerschaft, in Berlin Abgeordnetenhaus." },
  { id: "fo-2", lesson: "de-foederalismus", level: "medium",
    q: "Wie heißt der Regierungschef eines Flächenlandes?",
    options: [
      "Bürgermeister",
      "Ministerpräsident",
      "Landeskanzler",
      "Landrat",
    ], answer: 1,
    explanation: "Ministerpräsident. In den Stadtstaaten heißt das Amt Regierender Bürgermeister, Erster Bürgermeister oder Präsident des Senats." },
  { id: "fo-3", lesson: "de-foederalismus", level: "medium",
    q: "Wofür ist der Bund und nicht das Bundesland zuständig?",
    options: [
      "Für die Schulen",
      "Für die Außenpolitik",
      "Für die Landespolizei",
      "Für die Bauordnung",
    ], answer: 1,
    explanation: "Außenpolitik, Verteidigung, Staatsangehörigkeit und Währung sind Bundessache. Schule, Polizei und Bauordnung sind Ländersache." },
  { id: "fo-4", lesson: "de-foederalismus", level: "hard",
    q: "Welche Aussage über die Landesverfassungen ist richtig?",
    options: [
      "Es gibt keine, es gilt nur das Grundgesetz",
      "Jedes Land hat eine eigene, die dem Grundgesetz nicht widersprechen darf",
      "Sie stehen über dem Grundgesetz",
      "Nur die alten Bundesländer haben eine",
    ], answer: 1,
    explanation: "Jedes Land hat eine eigene Verfassung — aber Bundesrecht bricht Landesrecht, und dem Grundgesetz darf keine widersprechen." },
  { id: "fo-5", lesson: "de-foederalismus", level: "hard",
    q: "Was entscheidet die Gemeinde selbst?",
    options: [
      "Die Höhe der Einkommensteuer",
      "Bebauungspläne, Kitas und die örtliche Müllabfuhr",
      "Die Schulpflicht",
      "Die Staatsangehörigkeit",
    ], answer: 1,
    explanation: "Die kommunale Selbstverwaltung regelt, was direkt vor Ort anfällt. Steuersätze, Schulpflicht und Staatsangehörigkeit liegen höher." },
  { id: "fo-6", lesson: "de-foederalismus", level: "easy",
    q: "Wie viele Flächenländer hat Deutschland?",
    options: [
      "11",
      "13",
      "16",
      "3",
    ], answer: 1,
    explanation: "13 Flächenländer plus die drei Stadtstaaten Berlin, Hamburg und Bremen ergeben 16 Bundesländer." },

  // ── Rechtssystem und Gerichte ──────────────────────────────────────────
  { id: "re-1", lesson: "de-recht", level: "easy",
    q: "An welches Gericht wendest du dich bei einem Streit über eine Kündigung?",
    options: [
      "An das Verwaltungsgericht",
      "An das Arbeitsgericht",
      "An das Finanzgericht",
      "An das Sozialgericht",
    ], answer: 1,
    explanation: "Arbeitsgerichte entscheiden über Streit zwischen Arbeitgeber und Arbeitnehmer, Kündigungen eingeschlossen." },
  { id: "re-2", lesson: "de-recht", level: "medium",
    q: "Wer klagt im Strafverfahren gegen einen Angeklagten?",
    options: [
      "Der Richter",
      "Die Staatsanwaltschaft",
      "Die Polizei",
      "Der Verteidiger",
    ], answer: 1,
    explanation: "Die Staatsanwaltschaft erhebt Anklage. Der Richter entscheidet, die Polizei ermittelt, der Verteidiger vertritt den Angeklagten." },
  { id: "re-3", lesson: "de-recht", level: "medium",
    q: "Was bedeutet die Unabhängigkeit der Richter?",
    options: [
      "Richter dürfen selbst Gesetze machen",
      "Richter sind nur an das Gesetz gebunden und erhalten keine Weisungen",
      "Richter müssen nicht begründen, wie sie entscheiden",
      "Richter werden vom Volk gewählt",
    ], answer: 1,
    explanation: "Kein Minister und kein Vorgesetzter darf einem Richter vorschreiben, wie er zu entscheiden hat. Gebunden ist er allein an das Gesetz." },
  { id: "re-4", lesson: "de-recht", level: "hard",
    q: "Wann kann eine Person Verfassungsbeschwerde erheben?",
    options: [
      "Sofort, bevor sie andere Gerichte anruft",
      "Wenn sie sich in Grundrechten verletzt sieht und der übrige Rechtsweg ausgeschöpft ist",
      "Nur wenn der Bundestag zustimmt",
      "Nur als Gruppe von mindestens 100 Personen",
    ], answer: 1,
    explanation: "Zuerst der normale Rechtsweg, dann Karlsruhe. Die Verfassungsbeschwerde ist der letzte Schritt, nicht der erste." },
  { id: "re-5", lesson: "de-recht", level: "hard",
    q: "Was gilt, wenn jemand in Deutschland eine Straftat begeht, die zur Tatzeit noch nicht strafbar war?",
    options: [
      "Er wird nachträglich bestraft",
      "Er kann dafür nicht bestraft werden",
      "Das Gericht entscheidet frei",
      "Die Strafe wird halbiert",
    ], answer: 1,
    explanation: "Keine Strafe ohne Gesetz: Bestraft werden kann nur, was zum Zeitpunkt der Tat bereits unter Strafe stand." },
  { id: "re-6", lesson: "de-recht", level: "easy",
    q: "Wer bekommt in Deutschland einen Verteidiger, wenn er sich keinen leisten kann?",
    options: [
      "Niemand, ein Anwalt muss selbst bezahlt werden",
      "Jeder Angeklagte — der Staat hilft bei den Kosten",
      "Nur deutsche Staatsangehörige",
      "Nur bei schweren Verbrechen und nur auf eigene Kosten",
    ], answer: 1,
    explanation: "Das Recht auf Verteidigung darf nicht am Geld scheitern; deshalb gibt es Pflichtverteidigung und Prozesskostenhilfe." },

  // ── Sozialstaat und Sozialversicherung ─────────────────────────────────
  { id: "so-1", lesson: "de-sozialstaat", level: "easy",
    q: "Welche Versicherung zahlt, wenn jemand seine Arbeit verliert?",
    options: [
      "Die Rentenversicherung",
      "Die Arbeitslosenversicherung",
      "Die Pflegeversicherung",
      "Die Unfallversicherung",
    ], answer: 1,
    explanation: "Die Arbeitslosenversicherung zahlt Arbeitslosengeld und finanziert Vermittlung und Weiterbildung." },
  { id: "so-2", lesson: "de-sozialstaat", level: "medium",
    q: "Seit wann gibt es in Deutschland die Pflegeversicherung?",
    options: [
      "Seit 1949",
      "Seit 1995",
      "Seit 2005",
      "Seit 2015",
    ], answer: 1,
    explanation: "1995 kam sie als fünfte und jüngste Säule der Sozialversicherung hinzu." },
  { id: "so-3", lesson: "de-sozialstaat", level: "medium",
    q: "Wer zahlt Kindergeld, und wovon hängt es ab?",
    options: [
      "Der Arbeitgeber, abhängig vom Gehalt",
      "Der Staat, unabhängig vom Einkommen der Eltern",
      "Die Krankenkasse, abhängig von den Beiträgen",
      "Die Gemeinde, abhängig vom Wohnort",
    ], answer: 1,
    explanation: "Kindergeld gibt es für jedes Kind, ohne Rücksicht auf das Einkommen der Eltern." },
  { id: "so-4", lesson: "de-sozialstaat", level: "hard",
    q: "Wie werden die Beiträge zur gesetzlichen Krankenversicherung berechnet?",
    options: [
      "Nach dem Alter der versicherten Person",
      "Nach dem Einkommen",
      "Nach der Anzahl der Arztbesuche",
      "Für alle gleich hoch",
    ], answer: 1,
    explanation: "Nach dem Einkommen — das ist das Solidarprinzip. In der privaten Versicherung zählen dagegen Alter und Gesundheitszustand." },
  { id: "so-5", lesson: "de-sozialstaat", level: "hard",
    q: "Was ist das Elterngeld?",
    options: [
      "Ein Zuschuss zur Miete für Familien",
      "Ein Ersatz für einen Teil des Einkommens nach der Geburt eines Kindes",
      "Das monatliche Geld für jedes Kind",
      "Eine einmalige Zahlung zur Geburt",
    ], answer: 1,
    explanation: "Elterngeld ersetzt Einkommen, wenn Eltern nach der Geburt zu Hause bleiben. Kindergeld dagegen ist die laufende Zahlung pro Kind." },
  { id: "so-6", lesson: "de-sozialstaat", level: "easy",
    q: "Welche Behörde ist für Arbeitslosengeld und Arbeitsvermittlung zuständig?",
    options: [
      "Das Finanzamt",
      "Die Bundesagentur für Arbeit",
      "Das Bürgeramt",
      "Die Krankenkasse",
    ], answer: 1,
    explanation: "Die Bundesagentur für Arbeit mit ihren Agenturen und Jobcentern vor Ort." },

  // ── Kaiserreich und Weimarer Republik ──────────────────────────────────
  { id: "kai-1", lesson: "de-kaiserreich", level: "medium",
    q: "Wer war der erste Reichskanzler des Deutschen Kaiserreichs?",
    options: [
      "Wilhelm II.",
      "Otto von Bismarck",
      "Friedrich Ebert",
      "Konrad Adenauer",
    ], answer: 1,
    explanation: "Bismarck ab 1871. Ebert wurde 1919 erster Reichspräsident, Adenauer 1949 erster Bundeskanzler." },
  { id: "kai-2", lesson: "de-kaiserreich", level: "easy",
    q: "Wann endete der Erste Weltkrieg?",
    options: [
      "1914",
      "1918",
      "1933",
      "1945",
    ], answer: 1,
    explanation: "1918. Im selben Jahr dankte der Kaiser ab und die Republik wurde ausgerufen." },
  { id: "kai-3", lesson: "de-kaiserreich", level: "medium",
    q: "Was war der Versailler Vertrag?",
    options: [
      "Der Vertrag zur Gründung des Kaiserreichs",
      "Der Friedensvertrag nach dem Ersten Weltkrieg",
      "Der Vertrag über die Wiedervereinigung",
      "Der Gründungsvertrag der EU",
    ], answer: 1,
    explanation: "1919 geschlossen. Er verpflichtete Deutschland zu Reparationen und Gebietsabtretungen und belastete die junge Republik schwer." },
  { id: "kai-4", lesson: "de-kaiserreich", level: "hard",
    q: "Welche Neuerung brachte die Weimarer Republik für Frauen?",
    options: [
      "Das Recht auf eigenes Vermögen",
      "Das Wahlrecht",
      "Das Recht zu studieren",
      "Den Mutterschutz",
    ], answer: 1,
    explanation: "1919 durften Frauen erstmals wählen und gewählt werden — die wohl wichtigste demokratische Neuerung dieser Jahre." },
  { id: "kai-5", lesson: "de-kaiserreich", level: "hard",
    q: "Welche Schwäche der Weimarer Republik beantwortet das Grundgesetz mit der Fünf-Prozent-Hürde?",
    options: [
      "Die hohe Arbeitslosigkeit",
      "Die Zersplitterung des Parlaments in viele kleine Parteien",
      "Die Reparationszahlungen",
      "Die Macht des Reichspräsidenten",
    ], answer: 1,
    explanation: "Viele Kleinstparteien machten stabile Mehrheiten unmöglich. Die Hürde soll genau das verhindern." },
  { id: "kai-6", lesson: "de-kaiserreich", level: "medium",
    q: "Wofür ist Bismarck neben der Reichsgründung bekannt?",
    options: [
      "Für die Einführung der ersten Sozialversicherungen",
      "Für die Einführung des Frauenwahlrechts",
      "Für die Gründung der Bundeswehr",
      "Für die Einführung des Euro",
    ], answer: 0,
    explanation: "Kranken-, Unfall- und Rentenversicherung entstanden in den 1880er Jahren — der deutsche Sozialstaat ist älter als die Demokratie." },

  // ── Nationalsozialismus 1933–1945 ──────────────────────────────────────
  { id: "ns-1", lesson: "de-ns-zeit", level: "easy",
    q: "Wann kamen die Nationalsozialisten in Deutschland an die Macht?",
    options: [
      "1918",
      "1933",
      "1939",
      "1945",
    ], answer: 1,
    explanation: "Am 30. Januar 1933 wurde Hitler Reichskanzler. 1939 begann der Krieg, 1945 endete er." },
  { id: "ns-2", lesson: "de-ns-zeit", level: "medium",
    q: "Was bewirkte das Ermächtigungsgesetz von 1933?",
    options: [
      "Es gab dem Parlament mehr Rechte",
      "Es erlaubte der Regierung, Gesetze ohne das Parlament zu erlassen",
      "Es führte das Frauenwahlrecht ein",
      "Es begrenzte die Macht des Reichskanzlers",
    ], answer: 1,
    explanation: "Damit war die Gewaltenteilung beseitigt — der entscheidende Schritt von der Demokratie zur Diktatur." },
  { id: "ns-3", lesson: "de-ns-zeit", level: "medium",
    q: "Welches Merkmal kennzeichnete den NS-Staat?",
    options: [
      "Mehrere Parteien im Wettbewerb",
      "Nur eine erlaubte Partei",
      "Unabhängige Gerichte",
      "Freie Presse",
    ], answer: 1,
    explanation: "Ab Sommer 1933 war die NSDAP die einzige zugelassene Partei. Freie Presse und unabhängige Gerichte gab es nicht mehr." },
  { id: "ns-4", lesson: "de-ns-zeit", level: "hard",
    q: "Was geschah am 20. Juli 1944?",
    options: [
      "Der Krieg endete",
      "Ein Attentat auf Hitler scheiterte",
      "Die Nürnberger Gesetze wurden erlassen",
      "Die Mauer wurde gebaut",
    ], answer: 1,
    explanation: "Stauffenbergs Attentat scheiterte; die Beteiligten wurden hingerichtet. Der Tag steht für den militärischen Widerstand." },
  { id: "ns-5", lesson: "de-ns-zeit", level: "hard",
    q: "Wann endete der Zweite Weltkrieg in Europa?",
    options: [
      "Am 1. September 1939",
      "Am 8. Mai 1945",
      "Am 9. November 1945",
      "Am 23. Mai 1949",
    ], answer: 1,
    explanation: "Mit der bedingungslosen Kapitulation am 8. Mai 1945. Der 1. September 1939 war der Kriegsbeginn." },
  { id: "ns-6", lesson: "de-ns-zeit", level: "medium",
    q: "Was waren die Nürnberger Gesetze von 1935?",
    options: [
      "Gesetze zum Schutz von Arbeitnehmern",
      "Rassistische Gesetze, die jüdischen Deutschen ihre Bürgerrechte nahmen",
      "Die Verfassung des NS-Staates",
      "Die Urteile gegen NS-Verbrecher",
    ], answer: 1,
    explanation: "Sie entrechteten jüdische Deutsche systematisch. Die Nürnberger *Prozesse* nach 1945 sind etwas völlig anderes." },

  // ── Holocaust und Verantwortung ────────────────────────────────────────
  { id: "ver-1", lesson: "de-verantwortung", level: "easy",
    q: "Wie viele Juden wurden im Nationalsozialismus ermordet?",
    options: [
      "Etwa 600.000",
      "Etwa sechs Millionen",
      "Etwa 60.000",
      "Etwa 16 Millionen",
    ], answer: 1,
    explanation: "Etwa sechs Millionen europäische Juden. Ermordet wurden außerdem Sinti und Roma, Menschen mit Behinderung und viele andere Gruppen." },
  { id: "ver-2", lesson: "de-verantwortung", level: "medium",
    q: "Welche Gruppen wurden im Nationalsozialismus neben den Juden verfolgt?",
    options: [
      "Nur politische Gegner",
      "Sinti und Roma, Menschen mit Behinderung, politische Gegner und weitere Gruppen",
      "Ausschließlich Kriegsgefangene",
      "Niemand sonst",
    ], answer: 1,
    explanation: "Die Verfolgung traf viele Gruppen — nach rassistischen, politischen und weltanschaulichen Kriterien." },
  { id: "ver-3", lesson: "de-verantwortung", level: "medium",
    q: "Was ist in Deutschland strafbar?",
    options: [
      "Die Regierung zu kritisieren",
      "Den Holocaust öffentlich zu leugnen",
      "An einer Demonstration teilzunehmen",
      "Eine Partei zu gründen",
    ], answer: 1,
    explanation: "Holocaustleugnung ist Volksverhetzung und strafbar. Regierungskritik, Demonstrationen und Parteigründungen sind dagegen Grundrechte." },
  { id: "ver-4", lesson: "de-verantwortung", level: "hard",
    q: "Was war das Besondere an den Nürnberger Prozessen?",
    options: [
      "Sie fanden vor einem deutschen Gericht statt",
      "Erstmals wurden Staatsführer persönlich für Kriegsverbrechen zur Verantwortung gezogen",
      "Alle Angeklagten wurden freigesprochen",
      "Sie führten zur Gründung der Bundesrepublik",
    ], answer: 1,
    explanation: "1945/46 klagten die Alliierten führende Nationalsozialisten an — die Geburtsstunde des modernen Völkerstrafrechts." },
  { id: "ver-5", lesson: "de-verantwortung", level: "hard",
    q: "Was ist am 27. Januar in Deutschland?",
    options: [
      "Der Tag der Deutschen Einheit",
      "Der Gedenktag für die Opfer des Nationalsozialismus",
      "Der Tag des Grundgesetzes",
      "Der Tag der Arbeit",
    ], answer: 1,
    explanation: "Am 27. Januar 1945 wurde Auschwitz befreit. Seitdem ist der Tag deutschlandweiter Gedenktag." },
  { id: "ver-6", lesson: "de-verantwortung", level: "medium",
    q: "Wie verhält sich Deutschland heute zu seiner NS-Vergangenheit?",
    options: [
      "Sie wird nicht mehr thematisiert",
      "Sie wird in Gedenkstätten, Schulen und Gedenktagen bewusst wachgehalten",
      "Sie ist nur in Fachbüchern nachzulesen",
      "Sie darf nicht öffentlich besprochen werden",
    ], answer: 1,
    explanation: "Erinnerungskultur ist Teil des Selbstverständnisses: Gedenkstätten, Unterricht, Gedenktage und eine besondere Verantwortung gegenüber Israel." },

  // ── Nachkriegszeit und Teilung ─────────────────────────────────────────
  { id: "tei-1", lesson: "de-teilung", level: "easy",
    q: "Wann wurde die Bundesrepublik Deutschland gegründet?",
    options: [
      "1945",
      "1949",
      "1961",
      "1990",
    ], answer: 1,
    explanation: "1949, mit dem Inkrafttreten des Grundgesetzes am 23. Mai. Im selben Jahr entstand im Osten die DDR." },
  { id: "tei-2", lesson: "de-teilung", level: "medium",
    q: "Wann wurde die DDR gegründet?",
    options: [
      "Am 23. Mai 1949",
      "Am 7. Oktober 1949",
      "Am 13. August 1961",
      "Am 3. Oktober 1990",
    ], answer: 1,
    explanation: "7. Oktober 1949, rund viereinhalb Monate nach der Bundesrepublik." },
  { id: "tei-3", lesson: "de-teilung", level: "medium",
    q: "Was war das „Wirtschaftswunder“?",
    options: [
      "Der schnelle wirtschaftliche Aufschwung der Bundesrepublik in den 1950er Jahren",
      "Die Einführung des Euro",
      "Der Wiederaufbau der DDR",
      "Die Entdeckung von Rohstoffen",
    ], answer: 0,
    explanation: "Nach der Zerstörung wuchs die westdeutsche Wirtschaft rasant; Vollbeschäftigung und steigender Wohlstand prägten das Jahrzehnt." },
  { id: "tei-4", lesson: "de-teilung", level: "hard",
    q: "Warum kamen ab 1955 „Gastarbeiter“ nach Westdeutschland?",
    options: [
      "Weil Arbeitskräfte fehlten",
      "Weil die Bevölkerung zu groß geworden war",
      "Weil die DDR sie schickte",
      "Weil die Alliierten es verlangten",
    ], answer: 0,
    explanation: "Die wachsende Wirtschaft brauchte Arbeitskräfte. Angeworben wurde in Italien, Spanien, Griechenland, der Türkei und weiteren Ländern." },
  { id: "tei-5", lesson: "de-teilung", level: "hard",
    q: "Was war der Marshallplan?",
    options: [
      "Ein Plan zur Teilung Deutschlands",
      "Ein amerikanisches Hilfsprogramm für den Wiederaufbau",
      "Der Plan für die Berliner Mauer",
      "Ein Abkommen über Reparationen",
    ], answer: 1,
    explanation: "Ab 1948 halfen die USA westeuropäischen Staaten mit Krediten und Warenlieferungen beim Wiederaufbau." },
  { id: "tei-6", lesson: "de-teilung", level: "medium",
    q: "Welche Wirtschaftsordnung galt in der Bundesrepublik?",
    options: [
      "Die Planwirtschaft",
      "Die soziale Marktwirtschaft",
      "Die reine freie Marktwirtschaft ohne Regeln",
      "Die Staatswirtschaft",
    ], answer: 1,
    explanation: "Soziale Marktwirtschaft: freier Wettbewerb, aber mit sozialem Ausgleich. Die DDR hatte dagegen Planwirtschaft." },

  // ── Leben in der DDR ───────────────────────────────────────────────────
  { id: "ddr-1", lesson: "de-ddr", level: "easy",
    q: "Welche Partei bestimmte in der DDR die Politik?",
    options: [
      "Die CDU",
      "Die SED",
      "Die SPD",
      "Die FDP",
    ], answer: 1,
    explanation: "Die Sozialistische Einheitspartei Deutschlands hatte den Führungsanspruch. Andere Parteien existierten nur ohne echte Macht." },
  { id: "ddr-2", lesson: "de-ddr", level: "medium",
    q: "Wie hieß das Parlament der DDR?",
    options: [
      "Bundestag",
      "Volkskammer",
      "Landtag",
      "Reichstag",
    ], answer: 1,
    explanation: "Die Volkskammer. Frei gewählt wurde sie erst ein einziges Mal, im März 1990." },
  { id: "ddr-3", lesson: "de-ddr", level: "medium",
    q: "Was geschah am 17. Juni 1953 in der DDR?",
    options: [
      "Die Mauer wurde gebaut",
      "Ein Aufstand wurde mit sowjetischen Panzern niedergeschlagen",
      "Die DDR wurde gegründet",
      "Die ersten freien Wahlen fanden statt",
    ], answer: 1,
    explanation: "Aus Streiks gegen höhere Arbeitsnormen wurde ein Aufstand gegen die Regierung. Bis 1990 war der 17. Juni westdeutscher Nationalfeiertag." },
  { id: "ddr-4", lesson: "de-ddr", level: "hard",
    q: "Warum wurde die Berliner Mauer gebaut?",
    options: [
      "Um Angriffe aus dem Westen abzuwehren",
      "Um die eigene Bevölkerung an der Flucht zu hindern",
      "Um die Stadt vor Hochwasser zu schützen",
      "Weil die Alliierten es verlangten",
    ], answer: 1,
    explanation: "Immer mehr Menschen verließen die DDR. Die Mauer hielt niemanden draußen, sondern die eigenen Bürger drinnen." },
  { id: "ddr-5", lesson: "de-ddr", level: "hard",
    q: "Was können Betroffene heute mit ihrer Stasi-Akte tun?",
    options: [
      "Nichts, die Akten sind vernichtet",
      "Sie können Einsicht beantragen und ihre Akte lesen",
      "Nur Historiker dürfen sie einsehen",
      "Sie sind bis 2050 gesperrt",
    ], answer: 1,
    explanation: "Wer überwacht wurde, darf die eigene Akte lesen. Die Aufarbeitung gehört zum Umgang mit der SED-Diktatur." },
  { id: "ddr-6", lesson: "de-ddr", level: "medium",
    q: "Wie wurde in der DDR gewählt?",
    options: [
      "Frei zwischen mehreren Parteien",
      "Mit einer Einheitsliste, ohne echte Auswahl",
      "Gar nicht",
      "Nur in den Städten",
    ], answer: 1,
    explanation: "Es gab Wahlen, aber keine Alternativen: Die Einheitsliste stand fest, echte Auswahl gab es nicht." },

  // ── Mauerfall und Wiedervereinigung ────────────────────────────────────
  { id: "wv-1", lesson: "de-wiedervereinigung", level: "easy",
    q: "Welcher Ruf prägte die Montagsdemonstrationen 1989?",
    options: [
      "„Freiheit für alle“",
      "„Wir sind das Volk“",
      "„Nie wieder Krieg“",
      "„Einigkeit und Recht“",
    ], answer: 1,
    explanation: "„Wir sind das Volk“ — wörtlich der Gedanke aus Artikel 20 des Grundgesetzes, den die DDR nur behauptete." },
  { id: "wv-2", lesson: "de-wiedervereinigung", level: "medium",
    q: "In welcher Stadt waren die Montagsdemonstrationen 1989 besonders bedeutsam?",
    options: [
      "Dresden",
      "Leipzig",
      "Rostock",
      "Erfurt",
    ], answer: 1,
    explanation: "In Leipzig, ausgehend von den Friedensgebeten in der Nikolaikirche, wuchsen die Demonstrationen auf Hunderttausende an." },
  { id: "wv-3", lesson: "de-wiedervereinigung", level: "medium",
    q: "Wer war zur Zeit der Wiedervereinigung Bundeskanzler?",
    options: [
      "Willy Brandt",
      "Helmut Kohl",
      "Helmut Schmidt",
      "Gerhard Schröder",
    ], answer: 1,
    explanation: "Helmut Kohl, Bundeskanzler von 1982 bis 1998, gilt deshalb als „Kanzler der Einheit“." },
  { id: "wv-4", lesson: "de-wiedervereinigung", level: "hard",
    q: "Was regelte der Zwei-plus-Vier-Vertrag?",
    options: [
      "Die Aufteilung Berlins in vier Sektoren",
      "Die volle Souveränität des vereinten Deutschlands und die Bestätigung seiner Grenzen",
      "Den Beitritt zur NATO",
      "Die Einführung des Euro",
    ], answer: 1,
    explanation: "Die beiden deutschen Staaten und die vier Siegermächte einigten sich 1990 darauf — die außenpolitische Voraussetzung der Einheit." },
  { id: "wv-5", lesson: "de-wiedervereinigung", level: "hard",
    q: "Wann zogen Bundestag und Bundesregierung nach Berlin um?",
    options: [
      "1990",
      "1999",
      "2005",
      "Sie sind in Bonn geblieben",
    ], answer: 1,
    explanation: "1999. Berlin war schon 1990 wieder Hauptstadt, der Umzug von Parlament und Regierung folgte neun Jahre später." },
  { id: "wv-6", lesson: "de-wiedervereinigung", level: "medium",
    q: "Wie kam die staatliche Einheit 1990 zustande?",
    options: [
      "Durch einen Krieg",
      "Durch den Beitritt der DDR zur Bundesrepublik",
      "Durch eine Entscheidung der Vereinten Nationen",
      "Durch eine Volksabstimmung in beiden Staaten",
    ], answer: 1,
    explanation: "Die DDR trat der Bundesrepublik bei; das Grundgesetz galt fortan für ganz Deutschland." },

  // ── Deutschland in Europa und der Welt ─────────────────────────────────
  { id: "eu-1", lesson: "de-europa", level: "easy",
    q: "Wie viele Mitgliedstaaten hat die Europäische Union heute?",
    options: [
      "15",
      "27",
      "31",
      "50",
    ], answer: 1,
    explanation: "27 — seit dem Austritt des Vereinigten Königreichs im Jahr 2020." },
  { id: "eu-2", lesson: "de-europa", level: "medium",
    q: "Welche Währung galt in Deutschland vor dem Euro?",
    options: [
      "Der Schilling",
      "Die D-Mark",
      "Der Franken",
      "Die Reichsmark",
    ], answer: 1,
    explanation: "Die Deutsche Mark, eingeführt 1948 und 2002 vom Euro-Bargeld abgelöst." },
  { id: "eu-3", lesson: "de-europa", level: "medium",
    q: "Was bedeutet Freizügigkeit in der EU?",
    options: [
      "Waren sind zollfrei",
      "EU-Bürger dürfen in jedem Mitgliedstaat leben und arbeiten",
      "Man darf überall Auto fahren",
      "Es gibt keine Steuern zwischen den Ländern",
    ], answer: 1,
    explanation: "Personenfreizügigkeit: leben und arbeiten, wo man möchte — eine der Grundfreiheiten des Binnenmarktes." },
  { id: "eu-4", lesson: "de-europa", level: "hard",
    q: "Wie oft wird das Europäische Parlament gewählt?",
    options: [
      "Alle vier Jahre",
      "Alle fünf Jahre",
      "Alle sechs Jahre",
      "Alle zwei Jahre",
    ], answer: 1,
    explanation: "Alle fünf Jahre, direkt von den Bürgerinnen und Bürgern. Der Bundestag wird dagegen alle vier Jahre gewählt." },
  { id: "eu-5", lesson: "de-europa", level: "hard",
    q: "Welche Organisation ist ein Verteidigungsbündnis?",
    options: [
      "Die Europäische Union",
      "Die NATO",
      "Der Europarat",
      "Die Vereinten Nationen",
    ], answer: 1,
    explanation: "Die NATO ist das Verteidigungsbündnis. Die EU ist ein politischer und wirtschaftlicher Zusammenschluss, der Europarat kümmert sich um Menschenrechte." },
  { id: "eu-6", lesson: "de-europa", level: "medium",
    q: "Was bedeutet es, dass die Bundeswehr eine „Parlamentsarmee“ ist?",
    options: [
      "Abgeordnete dienen als Soldaten",
      "Über Auslandseinsätze entscheidet der Bundestag",
      "Die Armee untersteht dem Bundespräsidenten",
      "Soldaten dürfen nicht wählen",
    ], answer: 1,
    explanation: "Kein Auslandseinsatz ohne Zustimmung des Bundestages — die Kontrolle liegt beim Parlament, nicht allein bei der Regierung." },

  // ── Geografie, Städte und Symbole ──────────────────────────────────────
  { id: "geo-1", lesson: "de-geografie", level: "easy",
    q: "Wie heißt die Hauptstadt Deutschlands?",
    options: [
      "Bonn",
      "Berlin",
      "München",
      "Hamburg",
    ], answer: 1,
    explanation: "Berlin — seit 1990 wieder Hauptstadt, seit 1999 auch Sitz von Parlament und Regierung. Bonn war es bis dahin." },
  { id: "geo-2", lesson: "de-geografie", level: "medium",
    q: "Welche Stadt ist nach Berlin die zweitgrößte Deutschlands?",
    options: [
      "München",
      "Hamburg",
      "Köln",
      "Frankfurt am Main",
    ], answer: 1,
    explanation: "Hamburg, gefolgt von München und Köln." },
  { id: "geo-3", lesson: "de-geografie", level: "medium",
    q: "An welche zwei Meere grenzt Deutschland?",
    options: [
      "Nordsee und Ostsee",
      "Nordsee und Mittelmeer",
      "Ostsee und Schwarzes Meer",
      "Atlantik und Nordsee",
    ], answer: 0,
    explanation: "Im Nordwesten die Nordsee, im Nordosten die Ostsee." },
  { id: "geo-4", lesson: "de-geografie", level: "hard",
    q: "Welcher große deutsche Fluss fließt nach Osten ins Schwarze Meer?",
    options: [
      "Der Rhein",
      "Die Donau",
      "Die Elbe",
      "Die Weser",
    ], answer: 1,
    explanation: "Die Donau ist der einzige große Fluss Deutschlands, der nach Osten fließt. Rhein, Elbe und Weser münden in die Nordsee." },
  { id: "geo-5", lesson: "de-geografie", level: "hard",
    q: "Wie heißt das Wappentier der Bundesrepublik Deutschland?",
    options: [
      "Der Löwe",
      "Der Bundesadler",
      "Der Bär",
      "Das Pferd",
    ], answer: 1,
    explanation: "Der Bundesadler. Der Bär ist das Wappentier Berlins, nicht des Bundes." },
  { id: "geo-6", lesson: "de-geografie", level: "medium",
    q: "Wie viele Menschen leben ungefähr in Deutschland?",
    options: [
      "Etwa 50 Millionen",
      "Etwa 84 Millionen",
      "Etwa 120 Millionen",
      "Etwa 30 Millionen",
    ], answer: 1,
    explanation: "Rund 84 Millionen — damit ist Deutschland der bevölkerungsreichste Staat der Europäischen Union." },

  // ── Religion und Weltanschauung ────────────────────────────────────────
  { id: "rel-1", lesson: "de-religion", level: "easy",
    q: "Welche zwei christlichen Kirchen sind in Deutschland am größten?",
    options: [
      "Die orthodoxe und die anglikanische",
      "Die katholische und die evangelische",
      "Die evangelische und die orthodoxe",
      "Die katholische und die anglikanische",
    ], answer: 1,
    explanation: "Die katholische und die evangelische Kirche. Etwa die Hälfte der Bevölkerung gehört heute gar keiner Religionsgemeinschaft an." },
  { id: "rel-2", lesson: "de-religion", level: "medium",
    q: "Darf man in Deutschland aus der Kirche austreten?",
    options: [
      "Nein, die Mitgliedschaft ist lebenslang",
      "Ja, jederzeit",
      "Nur mit Zustimmung der Gemeinde",
      "Nur einmal im Leben",
    ], answer: 1,
    explanation: "Der Austritt ist jederzeit möglich; danach entfällt auch die Kirchensteuer. Religionsfreiheit schließt die Freiheit ein, keiner Religion anzugehören." },
  { id: "rel-3", lesson: "de-religion", level: "medium",
    q: "Wie ist der Staat in Deutschland gegenüber Religionen eingestellt?",
    options: [
      "Er bevorzugt die christlichen Kirchen",
      "Er ist weltanschaulich neutral",
      "Er lehnt Religion ab",
      "Er schreibt eine Staatsreligion vor",
    ], answer: 1,
    explanation: "Weltanschauliche Neutralität: Der Staat hat keine eigene Religion und bevorzugt keine Gemeinschaft." },
  { id: "rel-4", lesson: "de-religion", level: "hard",
    q: "Wer zahlt Kirchensteuer?",
    options: [
      "Alle Steuerzahler",
      "Nur Mitglieder einer steuererhebenden Religionsgemeinschaft",
      "Nur Selbstständige",
      "Niemand, das ist abgeschafft",
    ], answer: 1,
    explanation: "Nur Mitglieder. Wer austritt oder keiner Gemeinschaft angehört, zahlt sie nicht." },
  { id: "rel-5", lesson: "de-religion", level: "hard",
    q: "Was gilt für religiöse Gemeinschaften in Deutschland?",
    options: [
      "Sie dürfen eigene Gerichte mit verbindlichen Urteilen einrichten",
      "Sie müssen sich an die staatlichen Gesetze halten",
      "Sie stehen über dem staatlichen Recht",
      "Sie brauchen eine Erlaubnis des Bundespräsidenten",
    ], answer: 1,
    explanation: "Religionsausübung ist frei, aber das staatliche Recht gilt für alle. Parallele Rechtsprechung mit verbindlicher Wirkung gibt es nicht." },
  { id: "rel-6", lesson: "de-religion", level: "medium",
    q: "Welches Fach können Schüler wählen, die nicht am Religionsunterricht teilnehmen?",
    options: [
      "Sport",
      "Ethik oder Philosophie",
      "Eine zweite Fremdsprache",
      "Gar keins",
    ], answer: 1,
    explanation: "Als Alternative wird meist Ethik oder Philosophie angeboten. Die Teilnahme am Religionsunterricht ist freiwillig." },

  // ── Familie und Zusammenleben ──────────────────────────────────────────
  { id: "fam-1", lesson: "de-familie", level: "easy",
    q: "Ab welchem Alter darf man in Deutschland heiraten?",
    options: [
      "Ab 16 Jahren",
      "Ab 18 Jahren",
      "Ab 21 Jahren",
      "Es gibt keine Altersgrenze",
    ], answer: 1,
    explanation: "Ab der Volljährigkeit mit 18. Ehen mit Minderjährigen werden in Deutschland nicht anerkannt." },
  { id: "fam-2", lesson: "de-familie", level: "medium",
    q: "Wo wird in Deutschland rechtsgültig geheiratet?",
    options: [
      "In der Kirche",
      "Beim Standesamt",
      "Beim Notar",
      "Beim Familiengericht",
    ], answer: 1,
    explanation: "Nur die standesamtliche Eheschließung ist rechtsgültig. Eine religiöse Zeremonie kann hinzukommen, ersetzt sie aber nicht." },
  { id: "fam-3", lesson: "de-familie", level: "medium",
    q: "Was gilt in Deutschland vor einer Scheidung in der Regel?",
    options: [
      "Eine Wartezeit von einem Monat",
      "Ein Trennungsjahr",
      "Die Zustimmung beider Familien",
      "Eine Genehmigung der Kirche",
    ], answer: 1,
    explanation: "Meist muss ein Trennungsjahr vergangen sein. Über die Scheidung entscheidet das Familiengericht." },
  { id: "fam-4", lesson: "de-familie", level: "hard",
    q: "Seit wann dürfen in Deutschland auch gleichgeschlechtliche Paare heiraten?",
    options: [
      "Seit 2001",
      "Seit 2017",
      "Seit 1990",
      "Das ist nicht möglich",
    ], answer: 1,
    explanation: "Seit 2017 steht die Ehe allen Paaren offen. Zuvor gab es seit 2001 die eingetragene Lebenspartnerschaft." },
  { id: "fam-5", lesson: "de-familie", level: "hard",
    q: "Welche Behörde hilft, wenn das Wohl eines Kindes gefährdet ist?",
    options: [
      "Das Ordnungsamt",
      "Das Jugendamt",
      "Das Standesamt",
      "Das Einwohnermeldeamt",
    ], answer: 1,
    explanation: "Das Jugendamt unterstützt Familien und schützt Kinder vor Gewalt und Vernachlässigung." },
  { id: "fam-6", lesson: "de-familie", level: "medium",
    q: "Eine Frau wird von ihrem Ehemann geschlagen. Was gilt in Deutschland?",
    options: [
      "Das ist Privatsache der Familie",
      "Das ist eine Straftat, und sie kann Hilfe und Schutz bekommen",
      "Nur bei schweren Verletzungen greift der Staat ein",
      "Sie muss zuerst die Scheidung einreichen",
    ], answer: 1,
    explanation: "Gewalt in der Ehe ist eine Straftat. Die Polizei kann den Täter der Wohnung verweisen; Frauenhäuser und das Hilfetelefon helfen sofort." },

  // ── Bildung und Ausbildung ─────────────────────────────────────────────
  { id: "bil-1", lesson: "de-bildung", level: "easy",
    q: "Ab welchem Alter beginnt in Deutschland üblicherweise die Schulpflicht?",
    options: [
      "Mit vier Jahren",
      "Mit sechs Jahren",
      "Mit acht Jahren",
      "Mit zehn Jahren",
    ], answer: 1,
    explanation: "In der Regel mit sechs Jahren, und sie dauert mindestens neun Schuljahre." },
  { id: "bil-2", lesson: "de-bildung", level: "medium",
    q: "Wie lange dauert die Grundschule in den meisten Bundesländern?",
    options: [
      "Zwei Jahre",
      "Vier Jahre",
      "Sechs Jahre",
      "Acht Jahre",
    ], answer: 1,
    explanation: "Meist vier Jahre; in Berlin und Brandenburg sind es sechs. Auch das ist Ländersache." },
  { id: "bil-3", lesson: "de-bildung", level: "medium",
    q: "Was ist BAföG?",
    options: [
      "Eine Prüfung am Ende der Schule",
      "Eine staatliche Unterstützung für Schüler und Studierende",
      "Ein Zuschuss für Auszubildende vom Betrieb",
      "Eine Gebühr für das Studium",
    ], answer: 1,
    explanation: "Staatliche Ausbildungsförderung für alle, deren Eltern die Ausbildung nicht finanzieren können." },
  { id: "bil-4", lesson: "de-bildung", level: "hard",
    q: "Wer nimmt am Ende einer dualen Ausbildung die Abschlussprüfung ab?",
    options: [
      "Die Berufsschule allein",
      "Die Industrie- und Handelskammer oder die Handwerkskammer",
      "Das Kultusministerium",
      "Der Ausbildungsbetrieb selbst",
    ], answer: 1,
    explanation: "Die Kammern prüfen — deshalb ist der Abschluss bundesweit vergleichbar und nicht vom einzelnen Betrieb abhängig." },
  { id: "bil-5", lesson: "de-bildung", level: "hard",
    q: "Du hast im Ausland einen Beruf erlernt. Was kannst du in Deutschland tun?",
    options: [
      "Nichts, der Abschluss gilt hier nicht",
      "Du kannst deinen Abschluss anerkennen lassen",
      "Du musst die Ausbildung komplett wiederholen",
      "Du darfst nur als Hilfskraft arbeiten",
    ], answer: 1,
    explanation: "Es gibt ein Anerkennungsverfahren. Gerade in Pflege, Handwerk und technischen Berufen ist es der Schlüssel zum Arbeitsmarkt." },
  { id: "bil-6", lesson: "de-bildung", level: "medium",
    q: "Ab wann haben Kinder in Deutschland einen Anspruch auf einen Kita-Platz?",
    options: [
      "Ab der Geburt",
      "Ab dem ersten Geburtstag",
      "Ab drei Jahren",
      "Es gibt keinen Anspruch",
    ], answer: 1,
    explanation: "Ab dem vollendeten ersten Lebensjahr besteht ein Rechtsanspruch auf einen Betreuungsplatz." },

  // ── Arbeit und Beruf ───────────────────────────────────────────────────
  { id: "arb-1", lesson: "de-arbeit", level: "easy",
    q: "Wie viele Urlaubstage stehen bei einer Fünf-Tage-Woche mindestens zu?",
    options: [
      "10 Tage",
      "20 Tage",
      "30 Tage",
      "Es gibt kein Minimum",
    ], answer: 1,
    explanation: "Das gesetzliche Minimum sind 20 Arbeitstage im Jahr. Viele Verträge und Tarifverträge geben mehr." },
  { id: "arb-2", lesson: "de-arbeit", level: "medium",
    q: "In welcher Form muss eine Kündigung erfolgen?",
    options: [
      "Mündlich genügt",
      "Schriftlich",
      "Per E-Mail",
      "Per Telefonanruf",
    ], answer: 1,
    explanation: "Nur schriftlich mit eigenhändiger Unterschrift. Eine mündliche Kündigung oder eine E-Mail ist unwirksam." },
  { id: "arb-3", lesson: "de-arbeit", level: "medium",
    q: "Was ist Schwarzarbeit?",
    options: [
      "Arbeit in der Nachtschicht",
      "Arbeit ohne Anmeldung und ohne Sozialabgaben",
      "Arbeit im Ausland",
      "Ehrenamtliche Arbeit",
    ], answer: 1,
    explanation: "Sie ist strafbar — und wer so arbeitet, hat weder Kranken- noch Rentenversicherung noch Kündigungsschutz." },
  { id: "arb-4", lesson: "de-arbeit", level: "hard",
    q: "Was ist ein Tarifvertrag?",
    options: [
      "Ein Vertrag zwischen Arbeitnehmer und Arbeitgeber",
      "Eine Vereinbarung zwischen Gewerkschaft und Arbeitgeberseite über Löhne und Arbeitsbedingungen",
      "Der Vertrag über die Sozialversicherung",
      "Ein Vertrag über Stromtarife",
    ], answer: 1,
    explanation: "Gewerkschaften und Arbeitgeberverbände handeln ihn kollektiv aus. Der einzelne Arbeitsvertrag steht davon getrennt." },
  { id: "arb-5", lesson: "de-arbeit", level: "hard",
    q: "Darf ein Arbeitgeber jemandem kündigen, weil er sich an einem Streik beteiligt hat?",
    options: [
      "Ja, jederzeit",
      "Nein, das Streikrecht ist geschützt",
      "Nur bei längeren Streiks",
      "Nur in kleinen Betrieben",
    ], answer: 1,
    explanation: "Wer sich an einem gewerkschaftlich getragenen Streik beteiligt, darf dafür nicht gekündigt werden." },
  { id: "arb-6", lesson: "de-arbeit", level: "medium",
    q: "Was bleibt vom Bruttolohn nach Abzug von Steuern und Sozialabgaben?",
    options: [
      "Der Tariflohn",
      "Der Nettolohn",
      "Der Mindestlohn",
      "Der Grundlohn",
    ], answer: 1,
    explanation: "Das Netto ist der Betrag, der auf dem Konto ankommt. Brutto ist der Lohn vor allen Abzügen." },

  // ── Wohnen und Alltag ──────────────────────────────────────────────────
  { id: "all-1", lesson: "de-alltag", level: "easy",
    q: "Was gehört in Deutschland in die Biotonne?",
    options: [
      "Verpackungen aus Plastik",
      "Küchen- und Gartenabfälle",
      "Altpapier",
      "Glasflaschen",
    ], answer: 1,
    explanation: "Mülltrennung ist Pflicht: Bioabfall, Papier, Verpackungen, Restmüll und Glas nach Farben getrennt." },
  { id: "all-2", lesson: "de-alltag", level: "medium",
    q: "Was ist Pfand?",
    options: [
      "Eine Steuer auf Getränke",
      "Ein Betrag, den man beim Kauf zahlt und bei Rückgabe der Flasche zurückbekommt",
      "Die Gebühr für die Mülltonne",
      "Ein Rabatt beim Einkauf",
    ], answer: 1,
    explanation: "Auf viele Flaschen und Dosen wird Pfand erhoben. Bei der Rückgabe im Laden bekommt man das Geld zurück." },
  { id: "all-3", lesson: "de-alltag", level: "medium",
    q: "Darf ein Vermieter die Wohnung betreten, wann er möchte?",
    options: [
      "Ja, ihm gehört die Wohnung",
      "Nein, nur nach Ankündigung und mit einem berechtigten Grund",
      "Ja, wenn er einen Schlüssel hat",
      "Nur zusammen mit der Polizei",
    ], answer: 1,
    explanation: "Die Wohnung ist geschützt. Ohne Ankündigung und triftigen Grund darf auch der Eigentümer nicht hinein." },
  { id: "all-4", lesson: "de-alltag", level: "hard",
    q: "Wann musst du ein Ticket für Bus oder Bahn haben?",
    options: [
      "Erst wenn kontrolliert wird",
      "Vor dem Einsteigen",
      "Am Ende der Fahrt",
      "Nur zu Stoßzeiten",
    ], answer: 1,
    explanation: "Das gültige Ticket braucht man vor dem Einsteigen. Fahren ohne Fahrschein kostet ein erhöhtes Beförderungsentgelt." },
  { id: "all-5", lesson: "de-alltag", level: "hard",
    q: "Welche Behörde ist für Aufenthaltstitel und Einbürgerung zuständig?",
    options: [
      "Das Finanzamt",
      "Die Ausländerbehörde",
      "Das Standesamt",
      "Die Agentur für Arbeit",
    ], answer: 1,
    explanation: "Die Ausländerbehörde. Das Bürgeramt macht die Meldung, das Finanzamt die Steuer, das Standesamt Heirat und Geburt." },
  { id: "all-6", lesson: "de-alltag", level: "medium",
    q: "Was solltest du tun, bevor du einen Miet- oder Handyvertrag unterschreibst?",
    options: [
      "Sofort unterschreiben, um das Angebot zu sichern",
      "Ihn lesen und bei Unklarheiten nachfragen oder dich beraten lassen",
      "Nur den Preis prüfen",
      "Ihn von einem Nachbarn unterschreiben lassen",
    ], answer: 1,
    explanation: "Eine Unterschrift bindet. Die Verbraucherzentrale und Mietervereine beraten günstig, wenn etwas unklar ist." },

  // ── Gesundheit und Versicherungen ──────────────────────────────────────
  { id: "ges-1", lesson: "de-gesundheit", level: "easy",
    q: "Welche Nummer wählst du in Deutschland, wenn du die Polizei brauchst?",
    options: [
      "112",
      "110",
      "116117",
      "911",
    ], answer: 1,
    explanation: "110 für die Polizei, 112 für Notarzt und Feuerwehr. Beide sind kostenlos." },
  { id: "ges-2", lesson: "de-gesundheit", level: "medium",
    q: "Wer ist in Deutschland krankenversichert?",
    options: [
      "Nur Berufstätige",
      "Alle Menschen — die Krankenversicherung ist Pflicht",
      "Nur deutsche Staatsangehörige",
      "Nur wer sich freiwillig versichert",
    ], answer: 1,
    explanation: "Versicherungspflicht für alle: gesetzlich oder privat, aber niemand bleibt ohne Versicherung." },
  { id: "ges-3", lesson: "de-gesundheit", level: "medium",
    q: "Welche Versicherung zahlt Schäden, die du anderen zufügst?",
    options: [
      "Die Hausratversicherung",
      "Die Haftpflichtversicherung",
      "Die Unfallversicherung",
      "Die Rentenversicherung",
    ], answer: 1,
    explanation: "Die private Haftpflicht ist freiwillig, aber dringend zu empfehlen — sie deckt Schäden an fremdem Eigentum und an Personen." },
  { id: "ges-4", lesson: "de-gesundheit", level: "hard",
    q: "Welche Versicherung ist für jedes Auto gesetzlich vorgeschrieben?",
    options: [
      "Die Vollkaskoversicherung",
      "Die Kfz-Haftpflichtversicherung",
      "Die Rechtsschutzversicherung",
      "Die Hausratversicherung",
    ], answer: 1,
    explanation: "Ohne Kfz-Haftpflicht darf kein Fahrzeug bewegt werden. Kasko ist dagegen freiwillig." },
  { id: "ges-5", lesson: "de-gesundheit", level: "hard",
    q: "An wen wendest du dich außerhalb der Sprechzeiten bei einem Problem, das kein Notfall ist?",
    options: [
      "An die 110",
      "An den ärztlichen Bereitschaftsdienst unter 116117",
      "An das Gesundheitsamt",
      "An die Krankenkasse",
    ], answer: 1,
    explanation: "116117 ist der ärztliche Bereitschaftsdienst. Die 112 bleibt echten Notfällen vorbehalten." },
  { id: "ges-6", lesson: "de-gesundheit", level: "medium",
    q: "Was musst du beim Arztbesuch dabeihaben?",
    options: [
      "Den Personalausweis",
      "Die Gesundheitskarte der Krankenkasse",
      "Den Arbeitsvertrag",
      "Die Steuernummer",
    ], answer: 1,
    explanation: "Ohne Gesundheitskarte kann die Praxis die Behandlung nicht abrechnen — dann musst du unter Umständen selbst zahlen." },

  // ── Kultur, Feste und Medien ───────────────────────────────────────────
  { id: "kul-1", lesson: "de-kultur", level: "easy",
    q: "An welchen Tagen ist in Deutschland Weihnachten gesetzlicher Feiertag?",
    options: [
      "Am 24. und 25. Dezember",
      "Am 25. und 26. Dezember",
      "Nur am 24. Dezember",
      "Vom 24. bis 31. Dezember",
    ], answer: 1,
    explanation: "Der 25. und 26. Dezember sind gesetzliche Feiertage. Heiligabend am 24. ist ein normaler Arbeitstag, meist mit verkürzten Zeiten." },
  { id: "kul-2", lesson: "de-kultur", level: "medium",
    q: "Wie finanziert sich der öffentlich-rechtliche Rundfunk in Deutschland?",
    options: [
      "Aus Steuern",
      "Über den Rundfunkbeitrag der Haushalte",
      "Allein durch Werbung",
      "Durch Spenden",
    ], answer: 1,
    explanation: "Jeder Haushalt zahlt den Rundfunkbeitrag. Diese Finanzierung soll ARD und ZDF unabhängig von Regierung und Werbekunden halten." },
  { id: "kul-3", lesson: "de-kultur", level: "medium",
    q: "Welcher deutsche Dichter schrieb den „Faust“?",
    options: [
      "Friedrich Schiller",
      "Johann Wolfgang von Goethe",
      "Thomas Mann",
      "Heinrich Heine",
    ], answer: 1,
    explanation: "Goethe. Schiller schrieb unter anderem „Wilhelm Tell“ und „Die Räuber“." },
  { id: "kul-4", lesson: "de-kultur", level: "hard",
    q: "Wofür ist Johannes Gutenberg bekannt?",
    options: [
      "Für die Entdeckung der Radioaktivität",
      "Für den Buchdruck mit beweglichen Lettern",
      "Für den Bau des ersten Automobils",
      "Für die Relativitätstheorie",
    ], answer: 1,
    explanation: "Gutenberg druckte im 15. Jahrhundert mit beweglichen Lettern. Carl Benz baute das Auto, Einstein entwickelte die Relativitätstheorie." },
  { id: "kul-5", lesson: "de-kultur", level: "hard",
    q: "Was ist ein Ehrenamt?",
    options: [
      "Ein besonders gut bezahltes Amt",
      "Eine freiwillige, unbezahlte Tätigkeit für die Allgemeinheit",
      "Ein politisches Wahlamt",
      "Ein Ehrentitel für Verdienste",
    ], answer: 1,
    explanation: "Millionen Menschen engagieren sich unbezahlt in Vereinen, bei der Feuerwehr oder in der Nachbarschaftshilfe." },
  { id: "kul-6", lesson: "de-kultur", level: "medium",
    q: "In welcher Stadt findet das Oktoberfest statt?",
    options: [
      "In Köln",
      "In München",
      "In Stuttgart",
      "In Berlin",
    ], answer: 1,
    explanation: "In München. Karneval wird dagegen vor allem im Rheinland gefeiert, etwa in Köln und Düsseldorf." },
];

/** Die drei Themenbereiche, in der Reihenfolge, in der der Kurs sie lehrt. */
export function deChapters(): string[] {
  const seen: string[] = [];
  for (const lesson of lebenInDeutschlandCourse.lessons ?? []) {
    if (!seen.includes(lesson.section)) seen.push(lesson.section);
  }
  return seen;
}

export function deCategories(): { id: string; title: string; chapter: string; count: number }[] {
  const lessons = lebenInDeutschlandCourse.lessons ?? [];
  return lessons.map((lesson) => ({
    id: lesson.id,
    title: lesson.title,
    chapter: lesson.section,
    count: DE_QUESTIONS.filter((question) => question.lesson === lesson.id).length,
  }));
}

export function deQuestionsForLesson(lessonId: string): CountryQuestion[] {
  return DE_QUESTIONS.filter((question) => question.lesson === lessonId);
}

export function deQuestionsForChapter(chapter: string): CountryQuestion[] {
  const lessonIds = new Set(
    (lebenInDeutschlandCourse.lessons ?? []).filter((lesson) => lesson.section === chapter).map((lesson) => lesson.id)
  );
  return DE_QUESTIONS.filter((question) => lessonIds.has(question.lesson));
}

export function deQuestionById(id: string): CountryQuestion | undefined {
  return DE_QUESTIONS.find((question) => question.id === id);
}

export function deLessonTitle(lessonId: string): string {
  return (lebenInDeutschlandCourse.lessons ?? []).find((lesson) => lesson.id === lessonId)?.title ?? lessonId;
}

/** Die drei Stufen, in der Reihenfolge, in der die Übungsansicht sie anbietet. */
export const DE_LEVELS: CountryLevel[] = ["easy", "medium", "hard"];
