import bundledWordBank from "@/lib/bundledWordBank.json";

/**
 * German gloss for a visible English word — the learn-English mirror of
 * germanWordGloss. A German speaker hovering "goal" in an English sentence
 * should see "das Ziel" the same way an English speaker hovering "Ziel" sees
 * "goal".
 *
 * The lookup is entirely offline and precision-first: only the PRIMARY
 * English sense of each bank entry is inverted ("control, head" keys only
 * "control" — keying the secondary sense would label the everyday noun
 * "head" with a niche verb), plus a curated set of function words and
 * contractions the bank does not carry. Unknown words stay unlabelled
 * instead of guessing.
 */

type WordBankEntry = {
  de?: string;
  en?: string;
  lookup?: string;
  tip?: string;
};

const stripEnglishPunctuation = (value: string) => String(value ?? "")
  .normalize("NFC")
  .replace(/^[\s.,!?;:()[\]{}"'„“‚‘«»…–—-]+|[\s.,!?;:()[\]{}"'„“‚‘«»…–—-]+$/gu, "");

const wordKey = (value: string) => stripEnglishPunctuation(value).toLocaleLowerCase("en-GB");

/** The primary sense of a gloss: text before the first alternative separator,
 *  minus a leading particle and any bracketed qualifier. Returns "" when the
 *  primary sense is not a single word — a single hovered token cannot mean a
 *  whole phrase. */
const primarySenseKey = (gloss: string): string => {
  const first = String(gloss ?? "")
    .split(/\s*(?:,|\/|\bor\b)\s*/)[0]
    .replace(/\([^)]*\)/g, " ")
    .replace(/^(?:to|a|an|the)\s+/i, "")
    .trim();
  if (!first || /\s/.test(first)) return "";
  return wordKey(first);
};

// Curated function words, forms of be/have, and common contractions — the
// highest-frequency words a German learner of English actually hovers, none
// of which the word bank carries as entries.
const CORE_ENGLISH_GLOSSES: Array<[string, string]> = [
  ["i", "ich"],
  ["you", "du / ihr / Sie"],
  ["he", "er"],
  ["she", "sie"],
  ["it", "es"],
  ["we", "wir"],
  ["they", "sie"],
  ["the", "der / die / das"],
  ["a", "ein / eine"],
  ["an", "ein / eine"],
  ["and", "und"],
  ["or", "oder"],
  ["but", "aber"],
  ["not", "nicht"],
  ["no", "nein / kein"],
  ["yes", "ja"],
  ["is", "ist"],
  ["are", "sind / bist / seid"],
  ["am", "bin"],
  ["was", "war"],
  ["were", "waren / warst / wart"],
  ["be", "sein"],
  ["been", "gewesen"],
  ["being", "seiend / gerade"],
  ["have", "haben"],
  ["has", "hat"],
  ["had", "hatte / gehabt"],
  ["do", "tun / machen"],
  ["does", "tut / macht"],
  ["did", "tat / machte"],
  ["will", "werden (Zukunft)"],
  ["would", "würde"],
  ["can", "können"],
  ["could", "könnte / konnte"],
  ["should", "sollte"],
  ["must", "müssen"],
  ["may", "dürfen / können"],
  ["might", "könnte vielleicht"],
  ["of", "von"],
  ["to", "zu / nach"],
  ["in", "in"],
  ["on", "auf / an"],
  ["at", "an / bei / um"],
  ["for", "für"],
  ["with", "mit"],
  ["from", "von / aus"],
  ["by", "von / bei / mit"],
  ["about", "über / ungefähr"],
  ["this", "dieser / diese / dieses"],
  ["that", "das / dass / jener"],
  ["these", "diese"],
  ["those", "jene / diese"],
  ["there", "dort / da"],
  ["here", "hier"],
  ["my", "mein / meine"],
  ["your", "dein / euer / Ihr"],
  ["his", "sein / seine"],
  ["her", "ihr / ihre / sie"],
  ["our", "unser / unsere"],
  ["their", "ihr / ihre"],
  ["me", "mich / mir"],
  ["him", "ihn / ihm"],
  ["us", "uns"],
  ["them", "sie / ihnen"],
  ["what", "was"],
  ["who", "wer"],
  ["how", "wie"],
  ["when", "wann / wenn / als"],
  ["where", "wo"],
  ["why", "warum"],
  ["because", "weil"],
  ["if", "wenn / ob"],
  ["so", "also / so"],
  ["very", "sehr"],
  ["too", "zu / auch"],
  ["also", "auch"],
  ["just", "gerade / einfach / nur"],
  ["now", "jetzt"],
  ["then", "dann / damals"],
  ["still", "noch / immer noch"],
  ["already", "schon / bereits"],
  ["again", "wieder / noch einmal"],
  ["always", "immer"],
  ["never", "nie / niemals"],
  ["often", "oft"],
  ["sometimes", "manchmal"],
  ["today", "heute"],
  ["tomorrow", "morgen"],
  ["yesterday", "gestern"],
  ["before", "vor / bevor"],
  ["after", "nach / nachdem"],
  ["than", "als"],
  ["as", "als / wie"],
  ["up", "hoch / nach oben / Verbpartikel"],
  ["down", "runter / nach unten / Verbpartikel"],
  ["out", "draußen / heraus / Verbpartikel"],
  ["off", "aus / weg / Verbpartikel"],
  ["back", "zurück / Rücken"],
  ["away", "weg"],
  ["over", "über / vorbei"],
  ["under", "unter"],
  ["around", "um ... herum / ungefähr"],
  ["through", "durch"],
  ["together", "zusammen"],
  ["one", "eins / ein / eine"],
  ["two", "zwei"],
  ["three", "drei"],
  ["four", "vier"],
  ["five", "fünf"],
  ["six", "sechs"],
  ["seven", "sieben"],
  ["eight", "acht"],
  ["nine", "neun"],
  ["ten", "zehn"],
  ["all", "alle / alles"],
  ["both", "beide"],
  ["each", "jeder / jede / jedes"],
  ["every", "jeder / jede / jedes"],
  ["some", "einige / etwas"],
  ["any", "irgendein / etwas / jeder"],
  ["many", "viele"],
  ["much", "viel"],
  ["more", "mehr"],
  ["most", "die meisten / am meisten"],
  ["few", "wenige"],
  ["little", "wenig / klein"],
  ["enough", "genug"],
  ["other", "andere / anderer"],
  ["another", "noch ein / eine andere"],
  ["something", "etwas"],
  ["anything", "irgendetwas / etwas"],
  ["nothing", "nichts"],
  ["everything", "alles"],
  ["someone", "jemand"],
  ["anyone", "irgendjemand / jemand"],
  ["everyone", "alle / jeder"],
  ["got", "bekam / habe ... bekommen / habe"],
  ["getting", "bekommen / werden"],
  ["going", "gehen / fahren / werden"],
  ["doing", "tun / machen"],
  ["yet", "noch / schon / jedoch"],
  ["well", "gut / nun"],
  ["without", "ohne"],
  ["sorry", "Entschuldigung / leid"],
  ["bit", "bisschen / Stück"],
  ["exactly", "genau"],
  ["said", "sagte / gesagt"],
  ["sure", "sicher"],
  ["left", "links / übrig / verließ"],
  ["shall", "werden / sollen"],
  ["okay", "okay / in Ordnung"],
  ["ok", "okay / in Ordnung"],
  ["into", "in / hinein"],
  ["even", "sogar / gerade"],
  ["which", "welcher / welche / welches"],
  ["goes", "geht / fährt"],
  ["told", "sagte / erzählte"],
  ["almost", "fast / beinahe"],
  ["whole", "ganz / gesamte"],
  ["fine", "gut / in Ordnung / fein"],
  ["lot", "viel / Menge"],
  ["once", "einmal / sobald"],
  ["honestly", "ehrlich gesagt"],
  ["eleven", "elf"],
  ["twelve", "zwölf"],
  ["thirteen", "dreizehn"],
  ["fourteen", "vierzehn"],
  ["fifteen", "fünfzehn"],
  ["sixteen", "sechzehn"],
  ["seventeen", "siebzehn"],
  ["eighteen", "achtzehn"],
  ["nineteen", "neunzehn"],
  ["twenty", "zwanzig"],
  ["thirty", "dreißig"],
  ["hundred", "hundert"],
  ["best", "am besten / beste"],
  ["anymore", "nicht mehr"],
  ["oh", "oh"],
  ["same", "gleich / derselbe"],
  ["quite", "ziemlich / ganz"],
  ["straight", "gerade / direkt"],
  ["quickly", "schnell"],
  ["gone", "weg / gegangen"],
  ["myself", "ich selbst / mich selbst"],
  ["yourself", "du selbst / dich selbst"],
  ["else", "sonst / andere"],
  ["until", "bis"],
  ["till", "bis"],
  ["longer", "länger"],
  ["eat", "essen"],
  ["since", "seit / da"],
  ["otherwise", "sonst / andernfalls"],
  ["outside", "draußen / außerhalb"],
  ["lost", "verloren / verirrte"],
  ["tonight", "heute Abend / heute Nacht"],
  ["front", "vorn / Vorderseite"],
  ["twice", "zweimal"],
  ["thought", "dachte / Gedanke"],
  ["usually", "normalerweise"],
  ["watch", "ansehen / beobachten / Uhr"],
  ["made", "gemacht / hergestellt"],
  ["flat", "flach / Wohnung"],
  ["great", "großartig / groß"],
  ["short", "kurz"],
  ["sleep", "schlafen / Schlaf"],
  ["anyway", "sowieso / jedenfalls"],
  ["properly", "richtig / ordnungsgemäß"],
  ["soon", "bald"],
  ["worth", "wert"],
  ["pretty", "hübsch / ziemlich"],
  ["rather", "eher / ziemlich"],
  ["sit", "sitzen"],
  ["tax", "Steuer"],
  ["children", "Kinder"],
  ["top", "oben / Oberseite"],
  ["went", "ging / fuhr"],
  ["maybe", "vielleicht"],
  ["afraid", "ängstlich / leider"],
  ["box", "Kiste / Karton"],
  ["finally", "endlich / schließlich"],
  ["whether", "ob"],
  ["either", "entweder / auch"],
  ["email", "E-Mail"],
  ["hang", "hängen"],
  ["hardly", "kaum"],
  ["hello", "hallo"],
  ["listen", "zuhören"],
  ["meant", "meinte / bedeutete"],
  ["saw", "sah / Säge"],
  ["alone", "allein"],
  ["along", "entlang / mit"],
  ["between", "zwischen"],
  ["came", "kam"],
  ["differently", "anders"],
  ["slowly", "langsam"],
  ["touch", "berühren"],
  ["nobody", "niemand"],
  ["pick", "auswählen / pflücken"],
  ["lovely", "wunderschön / nett"],
  ["ring", "Ring / klingeln"],
  ["totally", "völlig"],
  ["while", "während / Weile"],
  ["bread", "Brot"],
  ["return", "zurückkehren / Rückgabe"],
  ["ahead", "vorn / voraus"],
  ["behind", "hinter"],
  ["cost", "kosten / Kosten"],
  ["seen", "gesehen"],
  ["sort", "Art / sortieren"],
  ["supposed", "angeblich / soll"],
  ["absolutely", "absolut / unbedingt"],
  ["against", "gegen"],
  ["broken", "kaputt / gebrochen"],
  ["emergency", "Notfall"],
  ["online", "online"],
  ["pass", "bestehen / vorbeigehen / Pass"],
  ["safe", "sicher / Tresor"],
  ["walk", "gehen / Spaziergang"],
  ["yeah", "ja"],
  ["afterwards", "danach"],
  ["beforehand", "vorher"],
  ["cash", "Bargeld"],
  ["milk", "Milch"],
  ["nearly", "fast / beinahe"],
  ["per", "pro / je"],
  ["seriously", "ernsthaft"],
  ["cancelled", "abgesagt / storniert"],
  ["contract", "Vertrag"],
  ["deal", "Abmachung / Geschäft"],
  ["ever", "jemals"],
  ["instead", "stattdessen"],
  ["passport", "Reisepass"],
  ["unfortunately", "leider"],
  ["barely", "kaum"],
  ["company", "Firma / Gesellschaft"],
  ["mine", "meins / Mine"],
  ["stuck", "fest / steckengeblieben"],
  ["due", "fällig / wegen"],
  ["extra", "zusätzlich / extra"],
  ["glad", "froh"],
  ["less", "weniger"],
  ["shut", "geschlossen / schließen"],
  ["sick", "krank"],
  ["wash", "waschen / Wäsche"],
  ["within", "innerhalb"],
  ["busy", "beschäftigt"],
  ["cheaper", "günstiger"],
  ["definitely", "definitiv / auf jeden Fall"],
  ["fifty", "fünfzig"],
  ["floor", "Boden / Etage"],
  ["hey", "hallo / hey"],
  ["hurt", "verletzt / tut weh"],
  ["its", "sein / ihr (für Sachen)"],
  ["note", "Notiz / beachten"],
  ["taken", "genommen / besetzt"],
  ["excuse", "Entschuldigung / entschuldigen"],
  ["finish", "beenden / Ende"],
  ["finished", "fertig / beendet"],
  ["jacket", "Jacke"],
  ["ago", "vor"],
  ["alright", "in Ordnung"],
  ["deposit", "Kaution / Anzahlung"],
  ["forgot", "vergaß / vergessen"],
  ["genuinely", "wirklich / aufrichtig"],
  ["inside", "drinnen / innerhalb"],
  ["proper", "richtig / ordentlich"],
  ["sec", "Sekunde"],
  ["sofa", "Sofa"],
  ["stand", "stehen / Stand"],
  ["bike", "Fahrrad"],
  ["germany", "Deutschland"],
  ["heard", "gehört"],
  ["immediately", "sofort"],
  ["main", "Haupt- / wichtigste"],
  ["post", "Post / Beitrag"],
  ["probably", "wahrscheinlich"],
  ["receipt", "Kassenbon / Beleg"],
  ["simply", "einfach"],
  ["asleep", "eingeschlafen / schlafend"],
  ["cancel", "absagen / stornieren"],
  ["dead", "tot"],
  ["fault", "Schuld / Fehler"],
  ["least", "am wenigsten / mindestens"],
  ["luckily", "zum Glück"],
  ["parcel", "Paket"],
  ["somewhere", "irgendwo"],
  ["stuff", "Sachen / Zeug"],
  ["switch", "Schalter / wechseln"],
  ["washing", "Waschen / Wäsche"],
  ["dinner", "Abendessen"],
  ["forgotten", "vergessen"],
  ["id", "Ausweis / Identifikation"],
  ["pack", "packen / Packung"],
  ["paid", "bezahlt"],
  ["replacement", "Ersatz"],
  ["town", "Stadt"],
  ["worse", "schlimmer"],
  ["bin", "Mülleimer / Behälter"],
  ["earlier", "früher"],
  ["fever", "Fieber"],
  ["forever", "für immer"],
  ["able", "fähig / in der Lage"],
  ["bathroom", "Badezimmer / Toilette"],
  ["battery", "Batterie / Akku"],
  ["forty", "vierzig"],
  ["fridge", "Kühlschrank"],
  ["hi", "hallo"],
  ["nursery", "Kinderzimmer / Kita"],
  ["piece", "Stück"],
  ["prescription", "Rezept / Verschreibung"],
  ["queue", "Warteschlange"],
  ["salary", "Gehalt"],
  ["shelf", "Regalbrett / Regal"],
  ["tried", "versucht"],
  ["trust", "vertrauen / Vertrauen"],
  ["briefly", "kurz"],
  ["charge", "berechnen / aufladen / Gebühr"],
  ["chat", "plaudern / Chat"],
  ["club", "Verein / Club"],
  ["noise", "Geräusch / Lärm"],
  ["o'clock", "Uhr"],
  ["onto", "auf / hinauf"],
  ["pool", "Schwimmbecken / Pool"],
  ["roughly", "ungefähr"],
  ["simple", "einfach"],
  ["took", "nahm / brachte"],
  ["whatever", "was auch immer / egal"],
  ["bought", "gekauft"],
  ["chest", "Brust / Truhe"],
  ["data", "Daten"],
  ["during", "während"],
  ["faster", "schneller"],
  ["itself", "selbst"],
  ["owe", "schulden"],
  ["separately", "getrennt"],
  ["split", "teilen / gespalten"],
  ["tight", "eng / fest"],
  ["travel", "reisen / Reise"],
  ["across", "über / auf der anderen Seite"],
  ["anywhere", "irgendwo / überall"],
  ["colour", "Farbe"],
  ["crazy", "verrückt"],
  ["depends", "kommt darauf an"],
  ["flowers", "Blumen"],
  ["handover", "Übergabe"],
  ["kids", "Kinder"],
  ["repair", "reparieren / Reparatur"],
  ["sense", "Sinn / Gefühl"],
  ["smoke", "Rauch / rauchen"],
  ["stairwell", "Treppenhaus"],
  ["tall", "groß (Körpergröße)"],
  ["tea", "Tee"],
  ["tyres", "Reifen"],
  ["awake", "wach"],
  ["barbecue", "Grillen / Grill"],
  ["bottle", "Flasche"],
  ["charger", "Ladegerät"],
  ["cheese", "Käse"],
  ["drop", "fallen lassen / Tropfen"],
  ["eighty", "achtzig"],
  ["everywhere", "überall"],
  ["join", "mitmachen / beitreten"],
  ["midnight", "Mitternacht"],
  ["packed", "gepackt / voll"],
  ["road", "Straße"],
  ["screw", "Schraube / schrauben"],
  ["smaller", "kleiner"],
  ["i'm", "ich bin"],
  ["i've", "ich habe"],
  ["i'll", "ich werde"],
  ["i'd", "ich würde / ich hätte"],
  ["it's", "es ist"],
  ["that's", "das ist"],
  ["there's", "da ist / es gibt"],
  ["you're", "du bist / ihr seid / Sie sind"],
  ["you've", "du hast / ihr habt / Sie haben"],
  ["you'll", "du wirst / ihr werdet / Sie werden"],
  ["we're", "wir sind"],
  ["we've", "wir haben"],
  ["we'll", "wir werden"],
  ["we'd", "wir würden / wir hatten"],
  ["you'd", "du würdest / ihr würdet / Sie würden"],
  ["they're", "sie sind"],
  ["they've", "sie haben"],
  ["they'll", "sie werden"],
  ["he's", "er ist / er hat"],
  ["she's", "sie ist / sie hat"],
  ["he'll", "er wird"],
  ["she'll", "sie wird"],
  ["it'll", "es wird"],
  ["don't", "… nicht (mit do)"],
  ["doesn't", "… nicht (mit does)"],
  ["didn't", "… nicht (Vergangenheit)"],
  ["can't", "kann nicht"],
  ["couldn't", "konnte nicht / könnte nicht"],
  ["won't", "wird nicht / will nicht"],
  ["wouldn't", "würde nicht"],
  ["shouldn't", "sollte nicht"],
  ["isn't", "ist nicht"],
  ["aren't", "sind nicht"],
  ["wasn't", "war nicht"],
  ["weren't", "waren nicht"],
  ["haven't", "habe nicht / haben nicht"],
  ["hasn't", "hat nicht"],
  ["hadn't", "hatte nicht"],
  ["what's", "was ist / was hat"],
  ["where's", "wo ist"],
  ["who's", "wer ist / wer hat"],
  ["how's", "wie ist / wie geht es"],
  ["here's", "hier ist"],
  ["everything's", "alles ist / alles hat"],
  ["one's", "jemandes / man"],
  ["something's", "etwas ist / etwas hat"],
  ["let's", "lass uns / lasst uns"],
];

const glossAlternatives = new Map<string, string[]>();

const addGloss = (key: string, german: string) => {
  if (!key || !german) return;
  const list = glossAlternatives.get(key);
  if (!list) glossAlternatives.set(key, [german]);
  else if (list.length < 3 && !list.includes(german)) list.push(german);
};

for (const [key, german] of CORE_ENGLISH_GLOSSES) addGloss(key, german);
// A curated entry is complete in itself — bank inversions must not append
// noun senses onto function words ("will" must stay the future marker, not
// grow "der Wille").
const curatedKeys = new Set(CORE_ENGLISH_GLOSSES.map(([key]) => key));

for (const rawEntry of bundledWordBank as WordBankEntry[]) {
  const german = String(rawEntry.de ?? "").trim();
  if (!german) continue;
  const key = primarySenseKey(rawEntry.en ?? "");
  if (curatedKeys.has(key)) continue;
  addGloss(key, german);
}

/** Inflection bases worth retrying: plural, -ing and -ed forms. Every
 *  plausible base is tried — a miss just falls through to null. */
const lookupKeys = (key: string): string[] => {
  const keys = [key];
  if (key.length > 4 && key.endsWith("ies")) keys.push(`${key.slice(0, -3)}y`);
  if (key.length > 4 && /(?:ches|shes|sses|xes|zes)$/.test(key)) keys.push(key.slice(0, -2));
  if (key.length > 3 && key.endsWith("s") && !/(?:ss|us|is)$/.test(key)) keys.push(key.slice(0, -1));
  for (const [suffix, minLength] of [["ing", 5], ["ed", 5]] as const) {
    if (key.length < minLength || !key.endsWith(suffix)) continue;
    const base = key.slice(0, -suffix.length);
    keys.push(base, `${base}e`);
    if (base.length > 2 && base[base.length - 1] === base[base.length - 2]) {
      keys.push(base.slice(0, -1));
    }
  }
  return keys;
};

/**
 * Returns a short German gloss for a visible English word, or null when the
 * word is not confidently covered.
 */
export function englishWordGloss(word: string): string | null {
  const key = wordKey(word);
  if (!key) return null;
  for (const candidate of lookupKeys(key)) {
    const list = glossAlternatives.get(candidate);
    if (list?.length) return list.join(" / ");
  }
  return null;
}
