import type { CountryQuestion } from "@/lib/countryStudies";

/**
 * La colección de práctica del curso «Vivir en España».
 *
 * Construida como las británica, alemana, francesa, polaca e italiana, y
 * separada de los exámenes que cierran cada lección por la misma razón:
 * aquellos llegan con el texto todavía en pantalla, y estas vuelven en orden
 * desordenado mucho después de haber leído.
 *
 * Ninguna pregunta de una lección reaparece aquí. Nada sirve dos veces —
 * check-es-questions compara los dos conjuntos y detiene la compilación si se
 * solapan.
 *
 * Cada pregunta lleva el identificador de la lección que la enseña. El
 * capítulo se deduce de la lección, no de una segunda lista llevada a mano.
 *
 * NO SON LAS PREGUNTAS DEL CCSE. El Instituto Cervantes publica un manual de
 * 300 preguntas y esas son suyas: estas están escritas para este curso. Se
 * comparte el temario, no el texto.
 *
 * LA DIFICULTAD se asigna, no se calcula. «easy»: la respuesta está en la
 * lección de forma explícita. «medium»: hay que recordar un nombre, una fecha
 * o una cifra. «hard»: hay que juntar dos hechos, o la pregunta apunta a una
 * confusión frecuente — el Congreso y el Senado, el jefe del Estado y el del
 * Gobierno, la Constitución de 1812 y la de 1978.
 */

export const ES_QUESTIONS: CountryQuestion[] = [
  // ── Símbolos nacionales ────────────────────────────────────────────────
  { id: "sim-1", lesson: "es-simbolos", level: "easy",
    q: "¿Qué artículo de la Constitución describe la bandera?",
    options: ["El artículo 1", "El artículo 3", "El artículo 4", "El artículo 11"],
    answer: 2,
    explanation: "El artículo 4. El 3 se ocupa de las lenguas y el 11 de la nacionalidad: los tres están en el título preliminar y se confunden con facilidad." },
  { id: "sim-2", lesson: "es-simbolos", level: "medium",
    q: "¿En el reinado de quién se adoptaron el rojo y el amarillo?",
    options: ["De Felipe II", "De Carlos III", "De Fernando VII", "De Alfonso XIII"],
    answer: 1,
    explanation: "Carlos III convocó en 1785 un concurso para dotar a la Armada de un pabellón distinguible. De la marina pasó al ejército y, ya en el siglo XIX, a bandera nacional." },
  { id: "sim-3", lesson: "es-simbolos", level: "medium",
    q: "¿Por qué se eligieron el rojo y el amarillo para el pabellón?",
    options: [
      "Por ser los colores de la Casa Real",
      "Para que la escuadra se distinguiera desde lejos en el mar",
      "Por recordar el oro de América",
      "Por imitar a la bandera francesa",
    ],
    answer: 1,
    explanation: "Casi todas las flotas europeas usaban fondos blancos con escudos y de lejos se confundían. El rojo y el amarillo se ven a mucha distancia: la razón fue práctica antes que simbólica." },
  { id: "sim-4", lesson: "es-simbolos", level: "medium",
    q: "¿Qué reino representa la granada situada al pie del escudo?",
    options: ["Navarra", "Aragón", "Granada", "León"],
    answer: 2,
    explanation: "La granada recuerda el reino nazarí incorporado en 1492, el último de la Península. Navarra aporta las cadenas y Aragón los cuatro palos." },
  { id: "sim-5", lesson: "es-simbolos", level: "hard",
    q: "¿Qué lema llevan las columnas de Hércules del escudo?",
    options: ["PLUS ULTRA", "NON PLUS ULTRA", "UNA GRANDE Y LIBRE", "TANTO MONTA"],
    answer: 0,
    explanation: "Plus ultra, más allá. Antes del descubrimiento de América el lema era el contrario, non plus ultra: nada más allá del estrecho. Se le quitó la negación." },
  { id: "sim-6", lesson: "es-simbolos", level: "easy",
    q: "¿Cómo se llama el himno nacional español?",
    options: ["Himno de Riego", "Marcha Real", "La Marsellesa", "Cara al sol"],
    answer: 1,
    explanation: "La Marcha Real. El Himno de Riego fue el himno de la Segunda República, entre 1931 y 1939." },
  { id: "sim-7", lesson: "es-simbolos", level: "medium",
    q: "¿Desde qué año está documentado el himno español?",
    options: ["Desde 1492", "Desde 1761", "Desde 1812", "Desde 1978"],
    answer: 1,
    explanation: "Aparece en 1761 como Marcha Granadera, lo que lo convierte en uno de los himnos más antiguos de Europa." },
  { id: "sim-8", lesson: "es-simbolos", level: "medium",
    q: "¿Qué se celebra el 6 de diciembre?",
    options: [
      "La Fiesta Nacional",
      "El Día de la Constitución",
      "La proclamación del rey",
      "El Día de la Hispanidad",
    ],
    answer: 1,
    explanation: "El Día de la Constitución, por el referéndum de 1978. La Fiesta Nacional es el 12 de octubre, y el Día de la Hispanidad es otro nombre para esa misma fecha." },
  { id: "sim-9", lesson: "es-simbolos", level: "hard",
    q: "¿Qué se conmemora el 2 de mayo en la Comunidad de Madrid?",
    options: [
      "La entrada de los Reyes Católicos en Granada",
      "El levantamiento de 1808 contra las tropas de Napoleón",
      "La proclamación de la Segunda República",
      "La aprobación del Estatuto de Autonomía",
    ],
    answer: 1,
    explanation: "El levantamiento del pueblo de Madrid en 1808, que abre la Guerra de la Independencia. Es fiesta de la comunidad, no nacional." },
  { id: "sim-10", lesson: "es-simbolos", level: "medium",
    q: "¿Qué lengua declara oficial del Estado el artículo 3?",
    options: ["El castellano", "El español y el catalán", "Todas las lenguas de España por igual", "No lo dice ningún artículo"],
    answer: 0,
    explanation: "El castellano es la lengua española oficial del Estado, y el mismo artículo añade que las demás lenguas españolas serán también oficiales en sus respectivas comunidades." },
  { id: "sim-11", lesson: "es-simbolos", level: "hard",
    q: "¿Cuál es la diferencia entre la bandera con escudo y la bandera sin escudo?",
    options: [
      "La de los edificios oficiales lleva escudo; la de uso común normalmente no",
      "La del escudo solo puede usarla la Casa Real",
      "La sin escudo está prohibida",
      "Son banderas de dos épocas distintas",
    ],
    answer: 0,
    explanation: "Ambas son correctas. La versión oficial, la de organismos y actos del Estado, incorpora el escudo; la que se cuelga de un balcón o se ve en un estadio suele ser la lisa." },
  { id: "sim-12", lesson: "es-simbolos", level: "medium",
    q: "¿Qué figuras ocupan los dos primeros cuarteles del escudo?",
    options: ["Un águila y una cruz", "Un castillo y un león", "Dos columnas", "Una granada y unas cadenas"],
    answer: 1,
    explanation: "El castillo de Castilla y el león de León. Las cadenas son de Navarra, la granada del reino de Granada y las columnas enmarcan el conjunto." },
  { id: "sim-13", lesson: "es-simbolos", level: "hard",
    q: "¿Qué reino representan las cadenas del escudo?",
    options: ["Castilla", "Aragón", "Navarra", "Portugal"],
    answer: 2,
    explanation: "Las cadenas son el emblema de Navarra. Aragón aporta los cuatro palos rojos sobre fondo dorado, y Portugal nunca formó parte del escudo." },

  // ── La Constitución de 1978 ────────────────────────────────────────────
  { id: "con-1", lesson: "es-constitucion", level: "easy",
    q: "¿Cuántos artículos tiene la Constitución española?",
    options: ["Noventa y nueve", "Ciento sesenta y nueve", "Doscientos", "Trescientos"],
    answer: 1,
    explanation: "Ciento sesenta y nueve, repartidos en un título preliminar y diez títulos, más las disposiciones finales. Es un texto largo para los estándares europeos." },
  { id: "con-2", lesson: "es-constitucion", level: "medium",
    q: "¿Cuándo entró en vigor la Constitución?",
    options: [
      "El 6 de diciembre de 1978",
      "El 27 de diciembre de 1978",
      "El 29 de diciembre de 1978",
      "El 1 de enero de 1979",
    ],
    answer: 2,
    explanation: "El 29 de diciembre, el día de su publicación en el Boletín Oficial del Estado. El 6 fue el referéndum y el 27 la sanción del rey." },
  { id: "con-3", lesson: "es-constitucion", level: "medium",
    q: "¿Cómo se conoce a los siete diputados que redactaron el borrador?",
    options: [
      "Los constituyentes",
      "Los padres de la Constitución",
      "La comisión de notables",
      "El consejo de redacción",
    ],
    answer: 1,
    explanation: "Se les llama los padres de la Constitución. Pertenecían a partidos distintos, lo que era el punto: el texto se escribió para que ninguna fuerza quedara fuera." },
  { id: "con-4", lesson: "es-constitucion", level: "hard",
    q: "¿Qué palabra resume el método con el que se redactó la Constitución?",
    options: ["Imposición", "Consenso", "Plebiscito", "Codificación"],
    answer: 1,
    explanation: "Consenso. Algunos artículos son deliberadamente amplios porque se acordó la frase precisamente por admitir más de una lectura: era el precio de que nadie quedara excluido." },
  { id: "con-5", lesson: "es-constitucion", level: "medium",
    q: "¿Qué título de la Constitución trata de la organización territorial del Estado?",
    options: ["El título preliminar", "El título I", "El título VI", "El título VIII"],
    answer: 3,
    explanation: "El título VIII. De él nacen las comunidades autónomas, y por eso al modelo se le llama a veces Estado del título VIII." },
  { id: "con-6", lesson: "es-constitucion", level: "medium",
    q: "¿Qué artículos forman el título preliminar?",
    options: ["Del 1 al 9", "Del 1 al 14", "Del 10 al 55", "Del 1 al 29"],
    answer: 0,
    explanation: "Del 1 al 9: qué es España, dónde reside la soberanía, las lenguas, la bandera, la capital. Del 10 al 55 va el título I, sobre derechos y deberes." },
  { id: "con-7", lesson: "es-constitucion", level: "hard",
    q: "¿Qué dos afirmaciones contiene el artículo 2?",
    options: [
      "La unidad de la Nación y el derecho a la autonomía de nacionalidades y regiones",
      "La soberanía popular y la monarquía parlamentaria",
      "La oficialidad del castellano y de las demás lenguas",
      "La igualdad ante la ley y la prohibición de discriminación",
    ],
    answer: 0,
    explanation: "Las dos mitades se acordaron juntas y ninguna se entiende sin la otra. Sobre ellas se construyó después todo el Estado autonómico." },
  { id: "con-8", lesson: "es-constitucion", level: "medium",
    q: "¿Qué artículo se reformó en 2011?",
    options: ["El artículo 13", "El artículo 135", "El artículo 2", "El artículo 168"],
    answer: 1,
    explanation: "El 135, sobre estabilidad presupuestaria, en plena crisis de deuda. La otra reforma, la de 1992, tocó el artículo 13." },
  { id: "con-9", lesson: "es-constitucion", level: "hard",
    q: "¿Por qué se reformó la Constitución en 1992?",
    options: [
      "Para permitir el voto de extranjeros en las elecciones municipales tras Maastricht",
      "Para introducir el euro",
      "Para reformar el Senado",
      "Para ampliar las competencias autonómicas",
    ],
    answer: 0,
    explanation: "El Tratado de Maastricht obligaba a reconocer el sufragio pasivo en las municipales a los ciudadanos comunitarios, y hubo que añadir dos palabras al artículo 13." },
  { id: "con-10", lesson: "es-constitucion", level: "medium",
    q: "¿Qué procedimiento de reforma obliga a disolver las Cortes y convocar elecciones?",
    options: ["El del artículo 167", "El del artículo 168", "El del artículo 92", "Ninguno lo exige"],
    answer: 1,
    explanation: "El procedimiento agravado del artículo 168, que además exige dos tercios de ambas cámaras antes y después, y un referéndum obligatorio al final." },
  { id: "con-11", lesson: "es-constitucion", level: "hard",
    q: "¿Qué partes de la Constitución protege el procedimiento agravado?",
    options: [
      "Solo el título de la Corona",
      "El título preliminar, los derechos fundamentales de la sección primera y el título de la Corona",
      "Todo el texto por igual",
      "Solo el título VIII",
    ],
    answer: 1,
    explanation: "Son las tres partes que el constituyente quiso poner casi fuera de alcance. Todo lo demás se reforma por el procedimiento ordinario, con tres quintos de cada cámara." },
  { id: "con-12", lesson: "es-constitucion", level: "easy",
    q: "¿Quién sancionó la Constitución en diciembre de 1978?",
    options: ["El presidente del Gobierno", "El rey", "El presidente de las Cortes", "El Tribunal Constitucional"],
    answer: 1,
    explanation: "El rey la sancionó el 27 de diciembre, después de que las Cortes la aprobaran y el pueblo la ratificara en referéndum." },
  { id: "con-13", lesson: "es-constitucion", level: "medium",
    q: "¿Qué mayoría exige el procedimiento ordinario de reforma?",
    options: [
      "Mayoría simple de cada cámara",
      "Mayoría absoluta del Congreso",
      "Tres quintos de cada cámara",
      "Dos tercios de cada cámara",
    ],
    answer: 2,
    explanation: "Tres quintos de Congreso y Senado. Los dos tercios corresponden al procedimiento agravado del artículo 168, que además obliga a disolver las Cortes." },

  // ── Derechos y libertades fundamentales ────────────────────────────────
  { id: "der-1", lesson: "es-derechos", level: "medium",
    q: "¿Qué artículos están protegidos por el recurso de amparo?",
    options: ["Del 1 al 9", "Del 14 al 29", "Del 30 al 38", "Del 39 al 52"],
    answer: 1,
    explanation: "Del 14 al 29: la igualdad y los derechos fundamentales y libertades públicas. Los de los artículos 39 a 52 son principios rectores y no llegan al amparo." },
  { id: "der-2", lesson: "es-derechos", level: "medium",
    q: "¿Qué establece el artículo 14?",
    options: [
      "El derecho a la vida",
      "La igualdad ante la ley sin discriminación alguna",
      "La libertad de expresión",
      "El derecho a la educación",
    ],
    answer: 1,
    explanation: "La igualdad ante la ley, sin que pueda prevalecer discriminación por nacimiento, raza, sexo, religión, opinión o cualquier otra condición personal o social." },
  { id: "der-3", lesson: "es-derechos", level: "medium",
    q: "¿Qué abolió el artículo 15?",
    options: ["La esclavitud", "La pena de muerte", "La censura", "La prisión por deudas"],
    answer: 1,
    explanation: "La pena de muerte, con una salvedad inicial para las leyes penales militares en tiempo de guerra. Esa excepción se suprimió por ley en 1995." },
  { id: "der-4", lesson: "es-derechos", level: "hard",
    q: "¿Cuándo desapareció por completo la pena de muerte del ordenamiento español?",
    options: ["En 1978", "En 1985", "En 1995", "En 2005"],
    answer: 2,
    explanation: "La Constitución la abolió en 1978 salvo para las leyes penales militares en tiempo de guerra, y esa última excepción se eliminó por ley en 1995." },
  { id: "der-5", lesson: "es-derechos", level: "easy",
    q: "¿Qué protege el artículo 18?",
    options: [
      "El honor, la intimidad, el domicilio y el secreto de las comunicaciones",
      "El derecho de huelga",
      "La libertad de circulación",
      "El derecho de petición",
    ],
    answer: 0,
    explanation: "Es el artículo de la vida privada: honor, intimidad, propia imagen, inviolabilidad del domicilio y secreto de las comunicaciones." },
  { id: "der-6", lesson: "es-derechos", level: "medium",
    q: "¿En qué casos puede entrarse en un domicilio sin permiso del titular?",
    options: [
      "Nunca",
      "Con resolución judicial o en caso de delito flagrante",
      "Siempre que lo pida la policía",
      "Con autorización del ayuntamiento",
    ],
    answer: 1,
    explanation: "El domicilio es inviolable. Solo caben el consentimiento del titular, la resolución judicial y el delito flagrante: fuera de esos tres supuestos, la entrada es ilegal." },
  { id: "der-7", lesson: "es-derechos", level: "medium",
    q: "¿Para qué sirve el habeas corpus?",
    options: [
      "Para recurrir una sentencia firme",
      "Para llevar de inmediato ante un juez a quien esté detenido ilegalmente",
      "Para pedir asistencia letrada gratuita",
      "Para impugnar una ley ante el Tribunal Constitucional",
    ],
    answer: 1,
    explanation: "Está previsto en el artículo 17 y sirve para poner sin demora a un detenido a disposición judicial. Es la garantía práctica del límite de las setenta y dos horas." },
  { id: "der-8", lesson: "es-derechos", level: "hard",
    q: "¿Hace falta autorización para celebrar una manifestación en la vía pública?",
    options: [
      "Sí, la autoridad debe concederla",
      "No: basta comunicarla previamente a la autoridad",
      "Solo si participan más de mil personas",
      "Solo en las capitales de provincia",
    ],
    answer: 1,
    explanation: "El artículo 21 exige comunicación previa, no autorización. La autoridad solo puede prohibirla por razones fundadas de alteración del orden público con peligro para personas o bienes." },
  { id: "der-9", lesson: "es-derechos", level: "medium",
    q: "¿Qué prohíbe expresamente el artículo 20 en materia de prensa?",
    options: ["La publicidad", "La censura previa", "Las publicaciones extranjeras", "El anonimato de las fuentes"],
    answer: 1,
    explanation: "La censura previa. El mismo artículo reconoce la libertad de expresión y el derecho a comunicar y recibir información veraz." },
  { id: "der-10", lesson: "es-derechos", level: "hard",
    q: "¿A qué deben orientarse las penas privativas de libertad?",
    options: [
      "A la retribución del daño causado",
      "A la reeducación y la reinserción social",
      "A la disuasión de terceros",
      "Al resarcimiento de la víctima",
    ],
    answer: 1,
    explanation: "El artículo 25 fija la reeducación y la reinserción como orientación de las penas y las medidas de seguridad. Es un mandato constitucional, no una recomendación." },
  { id: "der-11", lesson: "es-derechos", level: "medium",
    q: "¿Dónde está reconocido el derecho a una vivienda digna?",
    options: [
      "Entre los derechos fundamentales, con amparo",
      "En el artículo 47, entre los principios rectores",
      "En el título preliminar",
      "No aparece en la Constitución",
    ],
    answer: 1,
    explanation: "Está en el artículo 47, entre los principios rectores de la política social y económica: obliga al legislador, pero no se reclama directamente ante un juez como la libertad de expresión." },
  { id: "der-12", lesson: "es-derechos", level: "hard",
    q: "¿Cuál es la diferencia práctica entre un derecho fundamental y un principio rector?",
    options: [
      "Ninguna: los dos se alegan igual",
      "El fundamental llega al amparo constitucional; el principio rector solo conforme a las leyes que lo desarrollen",
      "El principio rector obliga a las comunidades y el fundamental al Estado",
      "El principio rector no aparece en el texto constitucional",
    ],
    answer: 1,
    explanation: "La diferencia es de protección, no de importancia. Los fundamentales exigen ley orgánica y llegan al Tribunal Constitucional por la vía del amparo." },
  { id: "der-13", lesson: "es-derechos", level: "easy",
    q: "¿Qué garantiza el artículo 24?",
    options: [
      "La tutela judicial efectiva y la presunción de inocencia",
      "La libertad religiosa",
      "El derecho al trabajo",
      "La inviolabilidad del domicilio",
    ],
    answer: 0,
    explanation: "Juez ordinario predeterminado por la ley, defensa y asistencia de letrado, proceso sin dilaciones indebidas y presunción de inocencia. Es el artículo del proceso justo." },

  // ── Deberes de los ciudadanos y la nacionalidad ────────────────────────
  { id: "deb-1", lesson: "es-deberes", level: "medium",
    q: "¿Cuándo quedó suspendido el servicio militar obligatorio en España?",
    options: ["En 1978", "En 1985", "En 2001", "Sigue vigente"],
    answer: 2,
    explanation: "En 2001. Desde entonces las Fuerzas Armadas son enteramente profesionales, aunque el artículo 30 mantiene el derecho y el deber de defender a España." },
  { id: "deb-2", lesson: "es-deberes", level: "easy",
    q: "¿Qué artículo impone contribuir al sostenimiento de los gastos públicos?",
    options: ["El artículo 30", "El artículo 31", "El artículo 35", "El artículo 47"],
    answer: 1,
    explanation: "El artículo 31, según la capacidad económica de cada uno. El 30 trata de la defensa y el 35 del trabajo." },
  { id: "deb-3", lesson: "es-deberes", level: "medium",
    q: "¿Qué carácter no puede tener nunca el sistema tributario?",
    options: ["Progresivo", "Confiscatorio", "Igualitario", "General"],
    answer: 1,
    explanation: "El artículo 31 exige que sea justo, igual y progresivo, y prohíbe expresamente que tenga alcance confiscatorio: la carga no puede vaciar el patrimonio de quien la soporta." },
  { id: "deb-4", lesson: "es-deberes", level: "medium",
    q: "¿Cuál es la regla principal de la nacionalidad española de origen?",
    options: [
      "Nacer en territorio español",
      "Nacer de padre o madre españoles",
      "Residir cinco años en España",
      "Estar inscrito en el padrón municipal",
    ],
    answer: 1,
    explanation: "Rige el criterio de la sangre: es español de origen quien nace de padre o madre españoles, nazca donde nazca. Nacer en España no basta por sí solo." },
  { id: "deb-5", lesson: "es-deberes", level: "hard",
    q: "¿Puede privarse de la nacionalidad a un español de origen?",
    options: [
      "Sí, por sentencia judicial",
      "No: el artículo 11 lo prohíbe",
      "Sí, si adquiere otra nacionalidad",
      "Solo en tiempo de guerra",
    ],
    answer: 1,
    explanation: "El artículo 11 lo prohíbe expresamente. Quien la ha adquirido por residencia sí puede perderla en supuestos tasados, pero el español de origen no." },
  { id: "deb-6", lesson: "es-deberes", level: "medium",
    q: "¿Con qué países permite la Constitución tratados de doble nacionalidad?",
    options: [
      "Con ninguno",
      "Con los países iberoamericanos y aquellos con vinculación particular con España",
      "Solo con los Estados de la Unión Europea",
      "Con todos los países del mundo",
    ],
    answer: 1,
    explanation: "El artículo 11 los prevé para los países iberoamericanos y para los que hayan tenido o tengan una vinculación particular con España, como Andorra, Filipinas, Guinea Ecuatorial y Portugal." },
  { id: "deb-7", lesson: "es-deberes", level: "medium",
    q: "¿Qué plazo de residencia se exige a quien ha obtenido la condición de refugiado?",
    options: ["Un año", "Dos años", "Cinco años", "Diez años"],
    answer: 2,
    explanation: "Cinco años. Es un plazo intermedio entre el general de diez y el de dos que corresponde a los países con vínculo histórico." },
  { id: "deb-8", lesson: "es-deberes", level: "hard",
    q: "¿Qué plazo se aplica a quien nació en territorio español pero no es español de origen?",
    options: ["Un año", "Dos años", "Cinco años", "Diez años"],
    answer: 0,
    explanation: "Un año, el plazo más corto, junto con supuestos como llevar un año casado con una persona española sin estar separado." },
  { id: "deb-9", lesson: "es-deberes", level: "medium",
    q: "¿Qué dos pruebas acreditan el suficiente grado de integración?",
    options: [
      "Un examen de historia y otro de geografía",
      "La prueba de lengua DELE A2 y la prueba CCSE",
      "Una entrevista en el ayuntamiento y un certificado de empadronamiento",
      "Un examen del Ministerio de Justicia y una prueba médica",
    ],
    answer: 1,
    explanation: "Las dos las administra el Instituto Cervantes: el DELE A2 examina la lengua y la CCSE los conocimientos constitucionales y socioculturales." },
  { id: "deb-10", lesson: "es-deberes", level: "hard",
    q: "¿Quién está exento de la prueba de lengua DELE A2?",
    options: [
      "Los mayores de sesenta y cinco años",
      "Quienes proceden de países donde el español es lengua oficial",
      "Quienes llevan más de veinte años en España",
      "Nadie está exento",
    ],
    answer: 1,
    explanation: "La exención alcanza a los nacionales de países hispanohablantes, que sí deben realizar en cambio la prueba CCSE." },
  { id: "deb-11", lesson: "es-deberes", level: "easy",
    q: "¿A qué edad se alcanza la mayoría de edad en España?",
    options: ["A los dieciséis", "A los dieciocho", "A los veintiuno", "A los veinticinco"],
    answer: 1,
    explanation: "A los dieciocho, y con ella llegan el derecho de voto y la plena capacidad de obrar." },
  { id: "deb-12", lesson: "es-deberes", level: "medium",
    q: "¿A partir de qué edad es obligatorio tener el DNI?",
    options: ["A los siete", "A los catorce", "A los dieciocho", "No es obligatorio"],
    answer: 1,
    explanation: "A partir de los catorce años, cuatro antes de la mayoría de edad. Puede solicitarse antes de forma voluntaria." },
  { id: "deb-13", lesson: "es-deberes", level: "hard",
    q: "¿Qué recoge el artículo 35 además del derecho al trabajo?",
    options: [
      "El deber de trabajar",
      "El derecho de huelga",
      "El salario mínimo",
      "La jornada de cuarenta horas",
    ],
    answer: 0,
    explanation: "El artículo 35 enuncia a la vez el deber y el derecho al trabajo, junto con la libre elección de profesión y una remuneración suficiente. La huelga está en el artículo 28." },

  // ── Fiestas y calendario ───────────────────────────────────────────────
  { id: "fie-1", lesson: "es-fiestas", level: "medium",
    q: "¿Cuántos festivos del calendario laboral fija el ayuntamiento?",
    options: ["Ninguno", "Dos", "Cuatro", "Seis"],
    answer: 1,
    explanation: "Dos de los catorce son locales y los decide cada municipio, normalmente el día del patrón y la fiesta mayor. Por eso un festivo puede no serlo a treinta kilómetros." },
  { id: "fie-2", lesson: "es-fiestas", level: "medium",
    q: "¿Qué día se celebra la fiesta de Cataluña?",
    options: ["El 23 de abril", "El 25 de julio", "El 11 de septiembre", "El 9 de octubre"],
    answer: 2,
    explanation: "El 11 de septiembre, la Diada. El 25 de julio es Galicia, el 9 de octubre la Comunidad Valenciana y el 23 de abril Aragón y Castilla y León." },
  { id: "fie-3", lesson: "es-fiestas", level: "medium",
    q: "¿Qué día se celebra la fiesta de Galicia?",
    options: ["El 28 de febrero", "El 25 de julio", "El 11 de septiembre", "El 6 de diciembre"],
    answer: 1,
    explanation: "El 25 de julio, día de Santiago Apóstol, patrón de España y de Galicia." },
  { id: "fie-4", lesson: "es-fiestas", level: "hard",
    q: "¿Qué día se celebra la fiesta de Andalucía?",
    options: ["El 28 de febrero", "El 23 de abril", "El 2 de mayo", "El 9 de octubre"],
    answer: 0,
    explanation: "El 28 de febrero, aniversario del referéndum autonómico de 1980. El 2 de mayo es Madrid y el 23 de abril Aragón y Castilla y León." },
  { id: "fie-5", lesson: "es-fiestas", level: "easy",
    q: "¿Qué día llegan tradicionalmente los regalos a los niños en España?",
    options: ["El 24 de diciembre", "El 25 de diciembre", "El 31 de diciembre", "El 6 de enero"],
    answer: 3,
    explanation: "El 6 de enero, con los Reyes Magos, cuya cabalgata se celebra la tarde del día 5. En muchas casas conviven hoy ambas fechas, pero la de Reyes sigue siendo la principal." },
  { id: "fie-6", lesson: "es-fiestas", level: "medium",
    q: "¿Qué día de Semana Santa es festivo en toda España?",
    options: ["El Domingo de Ramos", "El Jueves Santo", "El Viernes Santo", "El Lunes de Pascua"],
    answer: 2,
    explanation: "El Viernes Santo lo es en todo el país. El Jueves Santo lo es en la mayoría de comunidades pero no en todas, y el Lunes de Pascua solo en algunas." },
  { id: "fie-7", lesson: "es-fiestas", level: "hard",
    q: "¿Desde qué lugar se retransmiten las campanadas de Nochevieja?",
    options: [
      "Desde la Plaza Mayor de Madrid",
      "Desde la Puerta del Sol de Madrid",
      "Desde la Sagrada Familia de Barcelona",
      "Desde la Giralda de Sevilla",
    ],
    answer: 1,
    explanation: "Desde el reloj de la Puerta del Sol. La retransmisión es uno de los programas de televisión más vistos del año en España." },
  { id: "fie-8", lesson: "es-fiestas", level: "medium",
    q: "¿En qué ciudad se celebran los San Fermines?",
    options: ["En Bilbao", "En Pamplona", "En Zaragoza", "En Logroño"],
    answer: 1,
    explanation: "En Pamplona, del 6 al 14 de julio, y los encierros de la mañana son su imagen más conocida fuera de España." },
  { id: "fie-9", lesson: "es-fiestas", level: "medium",
    q: "¿En qué ciudad se celebra la Feria de Abril?",
    options: ["En Málaga", "En Córdoba", "En Sevilla", "En Granada"],
    answer: 2,
    explanation: "En Sevilla, dos semanas después de Semana Santa, con casetas, caballos y trajes de flamenca." },
  { id: "fie-10", lesson: "es-fiestas", level: "hard",
    q: "¿Qué son las chirigotas?",
    options: [
      "Los monumentos que se queman en las Fallas",
      "Las agrupaciones que cantan con letras satíricas en el carnaval de Cádiz",
      "Los encierros de las fiestas de Pamplona",
      "Las casetas de la Feria de Abril",
    ],
    answer: 1,
    explanation: "Son la seña de identidad del carnaval gaditano: coplas de humor y crítica que se preparan durante todo el año y compiten en el Gran Teatro Falla." },
  { id: "fie-11", lesson: "es-fiestas", level: "medium",
    q: "¿Qué es hacer puente?",
    options: [
      "Trabajar en festivo para librar otro día",
      "Librar el lunes o el viernes contiguo a un festivo que cae en martes o jueves",
      "Cambiar un festivo local por uno nacional",
      "Acumular las vacaciones al final del año",
    ],
    answer: 1,
    explanation: "Cuando el festivo cae en martes o jueves, muchos toman también el día que lo separa del fin de semana. Si coinciden dos festivos cercanos se habla, medio en broma, de acueducto." },
  { id: "fie-12", lesson: "es-fiestas", level: "medium",
    q: "¿Cuándo se queman los monumentos de las Fallas?",
    options: [
      "La noche del 19 de marzo",
      "La noche de San Juan, el 23 de junio",
      "El 15 de agosto",
      "El último día del carnaval",
    ],
    answer: 0,
    explanation: "La noche del 19 de marzo, la cremà. Los monumentos se levantan durante días por toda la ciudad y arden todos la misma noche." },
  { id: "fie-13", lesson: "es-fiestas", level: "hard",
    q: "¿Puede una comunidad autónoma sustituir un festivo estatal por otro propio?",
    options: [
      "No, la lista estatal es idéntica en todo el país",
      "Sí, dentro de los límites que fija la ley",
      "Solo las comunidades con lengua propia",
      "Solo con autorización del Gobierno central",
    ],
    answer: 1,
    explanation: "Las comunidades pueden sustituir algunos festivos estatales por fiestas propias, de modo que ni siquiera la lista del Estado se aplica igual en todas partes." },
  // ── La Corona ──────────────────────────────────────────────────────────
  { id: "cor-1", lesson: "es-corona", level: "easy",
    q: "¿Qué cargo ocupa el rey en el Estado español?",
    options: ["Presidente del Gobierno", "Jefe del Estado", "Presidente de las Cortes", "Jefe de la Administración"],
    answer: 1,
    explanation: "Jefe del Estado, símbolo de su unidad y permanencia. Quien dirige la política es el presidente del Gobierno, que es otro cargo y está en otro edificio." },
  { id: "cor-2", lesson: "es-corona", level: "medium",
    q: "¿Qué dos verbos emplea el artículo 56 para describir la función del rey?",
    options: ["Gobernar y administrar", "Arbitrar y moderar", "Legislar y sancionar", "Dirigir y coordinar"],
    answer: 1,
    explanation: "Arbitra y modera el funcionamiento regular de las instituciones. Ninguno de los dos verbos significa gobernar, y esa elección de palabras es deliberada." },
  { id: "cor-3", lesson: "es-corona", level: "medium",
    q: "¿Quién puede refrendar el nombramiento del presidente del Gobierno?",
    options: [
      "El presidente del Congreso",
      "El ministro de la Presidencia",
      "El presidente del Tribunal Supremo",
      "Nadie: ese acto no se refrenda",
    ],
    answer: 0,
    explanation: "La propuesta y el nombramiento del presidente del Gobierno, y la disolución de las Cortes prevista en el artículo 99, los refrenda el presidente del Congreso. Los demás actos, el Gobierno." },
  { id: "cor-4", lesson: "es-corona", level: "hard",
    q: "¿Por qué la Constitución declara inviolable la persona del rey?",
    options: [
      "Porque su cargo es vitalicio",
      "Porque todos sus actos los refrenda otro, que asume la responsabilidad",
      "Porque no interviene en ningún acto público",
      "Porque lo protege un tratado internacional",
    ],
    answer: 1,
    explanation: "La irresponsabilidad del rey solo se sostiene sobre el refrendo: siempre hay alguien que firma con él y responde. Un acto sin refrendo carece de validez." },
  { id: "cor-5", lesson: "es-corona", level: "medium",
    q: "¿En qué plazo debe el rey sancionar las leyes aprobadas por las Cortes?",
    options: ["En quince días", "En un mes", "En tres meses", "No hay plazo"],
    answer: 0,
    explanation: "Quince días para sancionar y promulgar. Es un acto debido: no puede negarse ni retrasarlo a voluntad." },
  { id: "cor-6", lesson: "es-corona", level: "medium",
    q: "¿Qué tipo de indultos prohíbe la ley española?",
    options: ["Los indultos generales", "Los indultos a extranjeros", "Los indultos por delitos económicos", "Ninguno"],
    answer: 0,
    explanation: "El rey ejerce el derecho de gracia con arreglo a la ley, y esa ley prohíbe los indultos generales. Los individuales sí son posibles, a propuesta del Gobierno." },
  { id: "cor-7", lesson: "es-corona", level: "hard",
    q: "¿Qué criterio de sucesión establece todavía el artículo 57?",
    options: [
      "Igualdad absoluta entre hombres y mujeres",
      "Preferencia del varón sobre la mujer en el mismo grado",
      "Elección por las Cortes entre los descendientes",
      "Preferencia del hijo mayor sin distinción de sexo",
    ],
    answer: 1,
    explanation: "Es la única preferencia por razón de sexo que queda en el texto. Cambiarla exigiría el procedimiento agravado del artículo 168, con disolución de las Cortes y referéndum." },
  { id: "cor-8", lesson: "es-corona", level: "medium",
    q: "¿En qué año fue proclamado rey Juan Carlos I?",
    options: ["En 1969", "En 1975", "En 1978", "En 1981"],
    answer: 1,
    explanation: "En 1975, dos días después de la muerte de Franco. La Constitución llegaría tres años más tarde, en 1978." },
  { id: "cor-9", lesson: "es-corona", level: "medium",
    q: "¿En qué año fue proclamado Felipe VI?",
    options: ["En 2004", "En 2011", "En 2014", "En 2018"],
    answer: 2,
    explanation: "El 19 de junio de 2014, tras la abdicación de su padre. La proclamación se celebró ante las Cortes Generales." },
  { id: "cor-10", lesson: "es-corona", level: "easy",
    q: "¿Cuál es la residencia habitual de la familia real?",
    options: ["El Palacio Real", "El Palacio de la Zarzuela", "El Palacio de la Moncloa", "El Palacio de las Cortes"],
    answer: 1,
    explanation: "La Zarzuela es la residencia; el Palacio Real se reserva para actos oficiales. La Moncloa es del presidente del Gobierno." },
  { id: "cor-11", lesson: "es-corona", level: "hard",
    q: "¿Qué hace el rey al ser proclamado ante las Cortes?",
    options: [
      "Presenta un programa de gobierno",
      "Presta juramento de guardar y hacer guardar la Constitución",
      "Firma un pacto con los partidos",
      "Nombra al presidente del Gobierno",
    ],
    answer: 1,
    explanation: "Jura o promete guardar y hacer guardar la Constitución y las leyes, y respetar los derechos de los ciudadanos y de las comunidades autónomas." },
  { id: "cor-12", lesson: "es-corona", level: "medium",
    q: "¿Quién tiene el mando supremo de las Fuerzas Armadas?",
    options: ["El presidente del Gobierno", "El rey", "El ministro de Defensa", "El jefe del Estado Mayor"],
    answer: 1,
    explanation: "El artículo 62 se lo atribuye al rey. La dirección efectiva de la defensa corresponde al Gobierno, según el artículo 97: el mando es simbólico y la política es del ejecutivo." },
  { id: "cor-13", lesson: "es-corona", level: "hard",
    q: "¿Qué ocurre con un acto del rey que no lleva refrendo?",
    options: [
      "Es válido pero recurrible",
      "Carece de validez",
      "Debe ratificarlo el Congreso",
      "Lo asume el Consejo de Ministros",
    ],
    answer: 1,
    explanation: "Sin refrendo el acto no vale. Es la pieza que hace compatibles un jefe del Estado irresponsable y un sistema en el que todo acto tiene un responsable." },

  // ── Las Cortes Generales ───────────────────────────────────────────────
  { id: "cort-1", lesson: "es-cortes", level: "medium",
    q: "¿Entre qué cifras permite la Constitución fijar el número de diputados?",
    options: ["Entre 200 y 300", "Entre 300 y 400", "Entre 250 y 350", "No fija ninguna horquilla"],
    answer: 1,
    explanation: "Entre trescientos y cuatrocientos. La ley electoral ha elegido siempre trescientos cincuenta, pero podría moverse dentro de ese margen sin reformar la Constitución." },
  { id: "cort-2", lesson: "es-cortes", level: "medium",
    q: "¿Cuál es la circunscripción electoral en las elecciones al Congreso?",
    options: ["La comunidad autónoma", "La provincia", "El municipio", "Toda España como circunscripción única"],
    answer: 1,
    explanation: "La provincia, más Ceuta y Melilla con un diputado cada una. La circunscripción única solo se usa en las elecciones europeas." },
  { id: "cort-3", lesson: "es-cortes", level: "hard",
    q: "¿Qué mecanismo da a las provincias pequeñas más peso relativo?",
    options: [
      "El sistema D'Hondt",
      "El mínimo inicial de dos escaños por provincia",
      "El umbral del tres por ciento",
      "Las listas cerradas",
    ],
    answer: 1,
    explanation: "Cada provincia parte de dos escaños antes de repartir el resto por población. Es un efecto distinto del que produce el D'Hondt, y suele atribuirse por error a este último." },
  { id: "cort-4", lesson: "es-cortes", level: "medium",
    q: "¿Qué umbral debe superar una lista para obtener escaño?",
    options: [
      "El uno por ciento nacional",
      "El tres por ciento de los votos válidos de su circunscripción",
      "El cinco por ciento nacional",
      "No hay umbral",
    ],
    answer: 1,
    explanation: "El tres por ciento, y se calcula por circunscripción, no en el conjunto del país. En provincias pequeñas el umbral efectivo es en la práctica mucho más alto." },
  { id: "cort-5", lesson: "es-cortes", level: "medium",
    q: "¿Qué significa que las listas sean cerradas y bloqueadas?",
    options: [
      "Que solo pueden presentarlas los partidos con representación",
      "Que se vota la candidatura entera en el orden fijado por el partido",
      "Que no se publican hasta el día de la votación",
      "Que no admiten candidatos independientes",
    ],
    answer: 1,
    explanation: "Cerrada significa que no se pueden mezclar candidatos de listas distintas; bloqueada, que no se puede alterar el orden. El votante elige un partido, no personas." },
  { id: "cort-6", lesson: "es-cortes", level: "medium",
    q: "¿Cuántos senadores elige directamente cada provincia peninsular?",
    options: ["Dos", "Tres", "Cuatro", "Depende de su población"],
    answer: 2,
    explanation: "Cuatro por provincia peninsular, con independencia de la población. Las islas y las ciudades autónomas siguen reglas propias, y a todos ellos se suman los designados por las comunidades." },
  { id: "cort-7", lesson: "es-cortes", level: "hard",
    q: "¿Cómo designan las comunidades autónomas a sus senadores?",
    options: [
      "Uno por comunidad y otro más por cada millón de habitantes",
      "Cuatro por comunidad",
      "Uno por provincia",
      "En proporción a los escaños de su parlamento",
    ],
    answer: 0,
    explanation: "Uno fijo por comunidad y otro adicional por cada millón de habitantes, designados por su asamblea legislativa. Es la vía territorial del Senado, junto a la provincial." },
  { id: "cort-8", lesson: "es-cortes", level: "medium",
    q: "¿Cuánto dura una legislatura?",
    options: ["Tres años", "Cuatro años", "Cinco años", "Seis años"],
    answer: 1,
    explanation: "Cuatro años, salvo disolución anticipada, que en España ha sido frecuente: pocas legislaturas han llegado completas a su término." },
  { id: "cort-9", lesson: "es-cortes", level: "hard",
    q: "¿Cuánto tiempo debe pasar para que el Congreso levante un veto del Senado por mayoría simple?",
    options: ["Quince días", "Un mes", "Dos meses", "Seis meses"],
    answer: 2,
    explanation: "Dos meses. Antes de ese plazo también puede levantarlo, pero necesita mayoría absoluta: el tiempo rebaja la exigencia." },
  { id: "cort-10", lesson: "es-cortes", level: "medium",
    q: "¿Qué es la Diputación Permanente?",
    options: [
      "El grupo que vela por los poderes de la cámara cuando está disuelta o fuera de sesiones",
      "La comisión que redacta los presupuestos",
      "El órgano que dirige los debates",
      "El conjunto de diputados con más antigüedad",
    ],
    answer: 0,
    explanation: "Cada cámara tiene la suya, presidida por su presidente. Es lo que impide que el Parlamento desaparezca del todo entre una disolución y las siguientes elecciones." },
  { id: "cort-11", lesson: "es-cortes", level: "easy",
    q: "¿Qué tres funciones atribuye el artículo 66 a las Cortes Generales?",
    options: [
      "Legislar, aprobar los presupuestos y controlar al Gobierno",
      "Legislar, juzgar y gobernar",
      "Elegir al rey, legislar y nombrar jueces",
      "Aprobar tratados, indultar y recaudar",
    ],
    answer: 0,
    explanation: "Potestad legislativa, presupuestos y control de la acción del Gobierno. Juzgar corresponde al poder judicial y gobernar al ejecutivo." },
  { id: "cort-12", lesson: "es-cortes", level: "medium",
    q: "¿Cuántos diputados eligen Ceuta y Melilla?",
    options: ["Ninguno", "Uno cada una", "Dos cada una", "Cuatro cada una"],
    answer: 1,
    explanation: "Un diputado cada una. Son circunscripciones propias, distintas de las provincias, y también eligen senadores con reglas específicas." },
  { id: "cort-13", lesson: "es-cortes", level: "hard",
    q: "¿Por qué se dice que el bicameralismo español es imperfecto?",
    options: [
      "Porque el Senado tiene menos miembros",
      "Porque las dos cámaras no tienen el mismo peso y el Congreso decide en última instancia",
      "Porque el Senado no se elige por sufragio",
      "Porque solo una de las dos aprueba los presupuestos",
    ],
    answer: 1,
    explanation: "El Congreso inviste al presidente, puede derribarlo y levanta los vetos del Senado. Imperfecto es aquí un término técnico, no un juicio de valor." },

  // ── El Gobierno ────────────────────────────────────────────────────────
  { id: "gob-1", lesson: "es-gobierno", level: "easy",
    q: "¿Quiénes componen el Gobierno?",
    options: [
      "El presidente, los vicepresidentes y los ministros",
      "El rey y los ministros",
      "Los diputados del partido más votado",
      "El presidente y los presidentes autonómicos",
    ],
    answer: 0,
    explanation: "Presidente, vicepresidentes en su caso y ministros, que reunidos forman el Consejo de Ministros. El rey no forma parte del Gobierno." },
  { id: "gob-2", lesson: "es-gobierno", level: "medium",
    q: "¿Qué artículo define las funciones del Gobierno?",
    options: ["El artículo 66", "El artículo 97", "El artículo 99", "El artículo 117"],
    answer: 1,
    explanation: "El 97: política interior y exterior, Administración civil y militar, defensa, función ejecutiva y potestad reglamentaria. El 99 regula la investidura." },
  { id: "gob-3", lesson: "es-gobierno", level: "medium",
    q: "¿Qué hace el rey antes de proponer un candidato a la presidencia?",
    options: [
      "Consultar a los representantes designados por los grupos políticos",
      "Consultar al Tribunal Constitucional",
      "Convocar un referéndum",
      "Nombrar un gobierno provisional",
    ],
    answer: 0,
    explanation: "Las consultas son una ronda de reuniones con los grupos con representación, y sirven para saber quién puede reunir una mayoría antes de proponer un nombre." },
  { id: "gob-4", lesson: "es-gobierno", level: "hard",
    q: "¿Qué ocurre si en dos meses nadie logra ser investido presidente?",
    options: [
      "Gobierna el partido más votado",
      "El rey disuelve las Cortes y se convocan nuevas elecciones",
      "Decide el Senado",
      "Se prorroga el gobierno anterior cuatro años",
    ],
    answer: 1,
    explanation: "El plazo corre desde la primera votación de investidura. España ha llegado a repetir elecciones por esta vía en más de una ocasión." },
  { id: "gob-5", lesson: "es-gobierno", level: "medium",
    q: "¿Qué mayoría basta en la segunda votación de investidura?",
    options: ["Mayoría absoluta", "Mayoría simple", "Tres quintos", "La misma que en la primera"],
    answer: 1,
    explanation: "Mayoría simple: más votos a favor que en contra. Se celebra cuarenta y ocho horas después de la primera, en la que se exigía mayoría absoluta." },
  { id: "gob-6", lesson: "es-gobierno", level: "medium",
    q: "¿Qué fracción de los diputados debe firmar una moción de censura?",
    options: ["Una décima parte", "Una cuarta parte", "Un tercio", "La mayoría absoluta"],
    answer: 0,
    explanation: "Una décima parte del Congreso para presentarla. Para que prospere hace falta después la mayoría absoluta de la cámara." },
  { id: "gob-7", lesson: "es-gobierno", level: "hard",
    q: "¿Cuántas veces ha prosperado una moción de censura desde 1978?",
    options: ["Ninguna", "Una", "Tres", "Cinco"],
    answer: 1,
    explanation: "Una sola, en 2018. El carácter constructivo lo explica: es fácil reunir votos contra alguien y difícil reunirlos a favor de un sustituto concreto." },
  { id: "gob-8", lesson: "es-gobierno", level: "medium",
    q: "¿Qué mayoría exige una cuestión de confianza?",
    options: ["Mayoría simple", "Mayoría absoluta", "Tres quintos", "Dos tercios"],
    answer: 0,
    explanation: "Mayoría simple, a diferencia de la moción de censura, que exige mayoría absoluta. La plantea el propio presidente y perderla le obliga a dimitir." },
  { id: "gob-9", lesson: "es-gobierno", level: "hard",
    q: "¿Cuándo NO puede el presidente disolver las Cortes?",
    options: [
      "En el primer año de legislatura",
      "Mientras esté en trámite una moción de censura",
      "Durante el periodo de sesiones",
      "En año electoral europeo",
    ],
    answer: 1,
    explanation: "Ni con una moción de censura en trámite, ni antes de que haya pasado un año desde la disolución anterior. Las dos limitaciones están en el artículo 115." },
  { id: "gob-10", lesson: "es-gobierno", level: "medium",
    q: "¿Qué es la potestad reglamentaria?",
    options: [
      "La facultad del Gobierno de dictar normas de rango inferior a la ley",
      "El derecho del Gobierno a vetar leyes",
      "La capacidad de convocar referendos",
      "El poder de nombrar jueces",
    ],
    answer: 0,
    explanation: "Los reglamentos desarrollan y aplican las leyes sin poder contradecirlas. Es una de las funciones que el artículo 97 atribuye al Gobierno." },
  { id: "gob-11", lesson: "es-gobierno", level: "easy",
    q: "¿Cómo se llama el órgano colegiado que forman el presidente y los ministros?",
    options: ["El Consejo de Estado", "El Consejo de Ministros", "El Consejo General", "La Junta de Gobierno"],
    answer: 1,
    explanation: "El Consejo de Ministros. El Consejo de Estado es otra cosa: el supremo órgano consultivo del Gobierno." },
  { id: "gob-12", lesson: "es-gobierno", level: "medium",
    q: "¿Cuántos días deben pasar entre la presentación de una moción de censura y su votación?",
    options: ["Dos", "Cinco", "Diez", "Quince"],
    answer: 1,
    explanation: "Cinco días, y en los dos primeros pueden presentarse mociones alternativas. El plazo da tiempo a negociar y a que aparezcan otros candidatos." },
  { id: "gob-13", lesson: "es-gobierno", level: "hard",
    q: "¿Qué le ocurre al candidato incluido en una moción de censura que prospera?",
    options: [
      "Debe someterse después a una investidura ordinaria",
      "Queda automáticamente investido presidente",
      "Asume solo de forma interina hasta las elecciones",
      "Debe ser ratificado por el Senado",
    ],
    answer: 1,
    explanation: "La moción constructiva inviste y destituye en el mismo acto. Por eso no puede presentarse sin candidato: no serviría para nada dejar el país sin gobierno." },

  // ── El poder judicial y el Tribunal Constitucional ─────────────────────
  { id: "jus-1", lesson: "es-justicia", level: "medium",
    q: "¿En nombre de quién se administra la justicia en España?",
    options: ["Del pueblo", "Del rey", "Del Estado", "De las Cortes"],
    answer: 1,
    explanation: "El artículo 117 dice que la justicia emana del pueblo y se administra en nombre del rey. Las dos mitades de la frase van juntas y suelen citarse a medias." },
  { id: "jus-2", lesson: "es-justicia", level: "medium",
    q: "¿Cómo se accede a la carrera judicial?",
    options: ["Por nombramiento del Gobierno", "Por oposición", "Por elección popular", "Por designación del CGPJ"],
    answer: 1,
    explanation: "Por oposición, un examen público y competitivo. Es lo que mantiene el acceso fuera del alcance de la política, aunque el gobierno de la carrera lo lleve el CGPJ." },
  { id: "jus-3", lesson: "es-justicia", level: "medium",
    q: "¿Cuántos vocales tiene el Consejo General del Poder Judicial?",
    options: ["Doce", "Quince", "Veinte", "Veinticinco"],
    answer: 2,
    explanation: "Veinte vocales más su presidente, que lo es también del Tribunal Supremo, con mandato de cinco años. Doce son los magistrados del Tribunal Constitucional." },
  { id: "jus-4", lesson: "es-justicia", level: "hard",
    q: "¿Cuáles son los cuatro órdenes jurisdiccionales?",
    options: [
      "Civil, penal, contencioso-administrativo y social",
      "Civil, penal, militar y mercantil",
      "Constitucional, civil, penal y laboral",
      "Ordinario, especial, foral y autonómico",
    ],
    answer: 0,
    explanation: "El contencioso-administrativo resuelve los pleitos con la Administración y el social los laborales. La jurisdicción militar existe, pero no es uno de los cuatro órdenes ordinarios." },
  { id: "jus-5", lesson: "es-justicia", level: "medium",
    q: "¿Qué tribunal tiene competencia en toda España sobre delitos como el terrorismo?",
    options: ["El Tribunal Supremo", "La Audiencia Nacional", "El Tribunal Constitucional", "Las Audiencias Provinciales"],
    answer: 1,
    explanation: "La Audiencia Nacional, con sede en Madrid y jurisdicción en todo el territorio para materias tasadas: terrorismo, delitos económicos de gran alcance, extradiciones." },
  { id: "jus-6", lesson: "es-justicia", level: "medium",
    q: "¿Cuántos Tribunales Superiores de Justicia hay?",
    options: ["Uno", "Uno por provincia", "Uno por comunidad autónoma", "Cuatro, uno por orden jurisdiccional"],
    answer: 2,
    explanation: "Uno por comunidad autónoma. Culminan la organización judicial en su territorio, pero no están por encima del Tribunal Supremo." },
  { id: "jus-7", lesson: "es-justicia", level: "hard",
    q: "¿Quién nombra al fiscal general del Estado?",
    options: [
      "El rey, a propuesta del Gobierno, oído el CGPJ",
      "El Congreso por tres quintos",
      "El Tribunal Supremo",
      "El propio Ministerio Fiscal",
    ],
    answer: 0,
    explanation: "Lo nombra el rey a propuesta del Gobierno, oído el Consejo General del Poder Judicial. Esa dependencia del ejecutivo es objeto de debate recurrente." },
  { id: "jus-8", lesson: "es-justicia", level: "medium",
    q: "¿Cuántos magistrados del Tribunal Constitucional propone el Congreso?",
    options: ["Dos", "Cuatro", "Seis", "Ocho"],
    answer: 1,
    explanation: "Cuatro, por mayoría de tres quintos. Otros cuatro los propone el Senado, dos el Gobierno y dos el Consejo General del Poder Judicial." },
  { id: "jus-9", lesson: "es-justicia", level: "medium",
    q: "¿Cuánto dura el mandato de un magistrado del Tribunal Constitucional?",
    options: ["Cinco años", "Seis años", "Nueve años", "Doce años"],
    answer: 2,
    explanation: "Nueve años, y el tribunal se renueva por terceras partes cada tres, de modo que nunca cambia entero de una vez." },
  { id: "jus-10", lesson: "es-justicia", level: "hard",
    q: "¿Cada cuánto se renueva por terceras partes el Tribunal Constitucional?",
    options: ["Cada año", "Cada tres años", "Cada cinco años", "Cada nueve años"],
    answer: 1,
    explanation: "Cada tres años se renueva un tercio. El escalonamiento evita que una sola mayoría parlamentaria componga el tribunal entero." },
  { id: "jus-11", lesson: "es-justicia", level: "medium",
    q: "¿Cuál de estas NO es competencia del Tribunal Constitucional?",
    options: [
      "El recurso de inconstitucionalidad",
      "El recurso de amparo",
      "Los conflictos de competencia entre el Estado y las comunidades",
      "El recurso de casación penal",
    ],
    answer: 3,
    explanation: "La casación es del Tribunal Supremo, que culmina la jurisdicción ordinaria. El Constitucional juzga leyes, derechos fundamentales y repartos de competencia." },
  { id: "jus-12", lesson: "es-justicia", level: "easy",
    q: "¿Qué orden jurisdiccional resuelve los pleitos con la Administración?",
    options: ["El civil", "El penal", "El contencioso-administrativo", "El social"],
    answer: 2,
    explanation: "El contencioso-administrativo. El social ve los conflictos laborales y de Seguridad Social, y el civil los de particulares entre sí." },
  { id: "jus-13", lesson: "es-justicia", level: "hard",
    q: "¿Qué prevé el artículo 125 sobre la participación ciudadana en la justicia?",
    options: [
      "El tribunal del jurado",
      "La elección popular de los jueces",
      "El referéndum sobre sentencias",
      "La mediación obligatoria",
    ],
    answer: 0,
    explanation: "El artículo 125 abre la puerta a la acción popular y al jurado, que juzga determinados delitos. Los jueces profesionales no se eligen: se accede por oposición." },

  // ── Elecciones y participación ciudadana ──────────────────────────────
  { id: "par-1", lesson: "es-participacion", level: "easy",
    q: "¿Desde qué edad se puede votar en España?",
    options: ["Desde los dieciséis", "Desde los dieciocho", "Desde los veintiuno", "Desde los veinticinco"],
    answer: 1,
    explanation: "Desde los dieciocho, que es también la mayoría de edad. El sufragio es universal, libre, igual, directo y secreto." },
  { id: "par-2", lesson: "es-participacion", level: "medium",
    q: "¿Qué circunscripción se emplea en las elecciones europeas?",
    options: ["La provincia", "La comunidad autónoma", "Toda España como circunscripción única", "El municipio"],
    answer: 2,
    explanation: "Circunscripción única para todo el país, a diferencia de las generales, que se reparten por provincias." },
  { id: "par-3", lesson: "es-participacion", level: "hard",
    q: "Si ningún candidato reúne la mayoría absoluta de los concejales, ¿quién resulta elegido alcalde?",
    options: [
      "Se repiten las elecciones",
      "El cabeza de la lista más votada",
      "El concejal de más edad",
      "Decide el pleno por sorteo",
    ],
    answer: 1,
    explanation: "La ley prevé esa salida automática para que ningún ayuntamiento quede sin alcalde. Es la razón de que gobiernen a veces listas que no tienen mayoría en el pleno." },
  { id: "par-4", lesson: "es-participacion", level: "medium",
    q: "¿Qué exige el artículo 6 a los partidos políticos?",
    options: [
      "Que tengan sede en Madrid",
      "Que su estructura interna y su funcionamiento sean democráticos",
      "Que presenten candidatos en todas las provincias",
      "Que se financien solo con cuotas",
    ],
    answer: 1,
    explanation: "El mismo requisito que el artículo 7 impone a sindicatos y asociaciones empresariales. Es una exigencia poco frecuente en el derecho comparado." },
  { id: "par-5", lesson: "es-participacion", level: "medium",
    q: "¿Cuáles son los dos sindicatos mayoritarios en España?",
    options: [
      "Comisiones Obreras y la Unión General de Trabajadores",
      "La CNT y la UGT",
      "USO y CSIF",
      "ELA y LAB",
    ],
    answer: 0,
    explanation: "CCOO y UGT. Los convenios que negocian se aplican a todo el sector y no solo a sus afiliados, lo que explica que su peso sea mayor que su afiliación." },
  { id: "par-6", lesson: "es-participacion", level: "hard",
    q: "¿Qué materias quedan excluidas de la iniciativa legislativa popular?",
    options: [
      "Ninguna",
      "Los tributos, lo internacional, el derecho de gracia y las leyes orgánicas",
      "Solo la reforma constitucional",
      "Todo lo que afecte a las comunidades autónomas",
    ],
    answer: 1,
    explanation: "La exclusión es amplia y limita bastante el alcance del instrumento: quedan fuera precisamente algunas de las materias sobre las que más se pediría legislar." },
  { id: "par-7", lesson: "es-participacion", level: "medium",
    q: "¿De quién depende el Defensor del Pueblo?",
    options: ["Del Gobierno", "De las Cortes Generales", "Del Tribunal Constitucional", "Del Consejo General del Poder Judicial"],
    answer: 1,
    explanation: "Es alto comisionado de las Cortes Generales, no del Gobierno. Esa dependencia parlamentaria es lo que le permite supervisar a la Administración." },
  { id: "par-8", lesson: "es-participacion", level: "hard",
    q: "¿Son ejecutivas las resoluciones del Defensor del Pueblo?",
    options: [
      "Sí, obligan a la Administración",
      "No: recomienda y da publicidad, y puede recurrir leyes ante el Tribunal Constitucional",
      "Sí, si las ratifica el Congreso",
      "Solo en materia de extranjería",
    ],
    answer: 1,
    explanation: "Su fuerza es la del informe público y la del recurso. No anula actos ni impone sanciones: para eso están los tribunales." },
  { id: "par-9", lesson: "es-participacion", level: "medium",
    q: "¿Qué organismo fiscaliza las cuentas del Estado y del sector público?",
    options: ["El Tribunal de Cuentas", "El Banco de España", "La Agencia Tributaria", "El Consejo de Estado"],
    answer: 0,
    explanation: "El Tribunal de Cuentas, previsto en el artículo 136 y dependiente también de las Cortes. La Agencia Tributaria recauda, que es otra función." },
  { id: "par-10", lesson: "es-participacion", level: "medium",
    q: "¿Quién convoca un referéndum consultivo?",
    options: [
      "El rey, a propuesta del presidente autorizada por el Congreso",
      "El Congreso por sí solo",
      "El Gobierno por decreto",
      "Las comunidades autónomas en su territorio",
    ],
    answer: 0,
    explanation: "Los tres pasos del artículo 92 son sucesivos: propone el presidente, autoriza el Congreso, convoca el rey. Y su resultado es consultivo, no vinculante en sentido jurídico." },
  { id: "par-11", lesson: "es-participacion", level: "easy",
    q: "¿Qué se vota en unas elecciones municipales?",
    options: ["El alcalde", "Los concejales", "El presidente de la diputación", "El delegado del Gobierno"],
    answer: 1,
    explanation: "Una lista de concejales. El alcalde lo elige después el pleno, y el presidente de la diputación provincial sale de entre los concejales electos." },
  { id: "par-12", lesson: "es-participacion", level: "hard",
    q: "¿Qué permite el derecho de petición del artículo 29?",
    options: [
      "Dirigirse por escrito a los poderes públicos",
      "Exigir una respuesta favorable de la Administración",
      "Convocar una manifestación",
      "Recurrir una ley ante el Tribunal Constitucional",
    ],
    answer: 0,
    explanation: "Es un derecho antiguo, sencillo y poco utilizado: permite dirigirse por escrito, individual o colectivamente, sin garantizar el contenido de la respuesta." },
  { id: "par-13", lesson: "es-participacion", level: "medium",
    q: "¿Cómo se elige al presidente de una comunidad autónoma?",
    options: [
      "Directamente por los ciudadanos",
      "Por el parlamento autonómico, que lo inviste",
      "Por el Gobierno central",
      "Por los alcaldes de la comunidad",
    ],
    answer: 1,
    explanation: "Igual que el presidente del Gobierno en las generales: se vota una cámara y la cámara inviste. La única elección directa de personas en España es la del Senado." },
];
