import type { CountryQuestion } from "@/lib/countryStudies";

/**
 * La colección de práctica del curso «Vivir en España».
 *
 * Construida como las británica, alemana, francesa, polaca e italiana, y
 * separada de los exámenes que cierran cada lección por la misma razón:
 * aquellos llegan con el texto todavía en pantalla, y estas vuelven en orden
 * desordenado mucho después de haber leído.
 *
 * Ninguna pregunta de una lección reaparece aquí. Nada sirve dos veces —
 * check-es-questions compara los dos conjuntos y detiene la compilación si se
 * solapan.
 *
 * Cada pregunta lleva el identificador de la lección que la enseña. El
 * capítulo se deduce de la lección, no de una segunda lista llevada a mano.
 *
 * NO SON LAS PREGUNTAS DEL CCSE. El Instituto Cervantes publica un manual de
 * 300 preguntas y esas son suyas: estas están escritas para este curso. Se
 * comparte el temario, no el texto.
 *
 * LA DIFICULTAD se asigna, no se calcula. «easy»: la respuesta está en la
 * lección de forma explícita. «medium»: hay que recordar un nombre, una fecha
 * o una cifra. «hard»: hay que juntar dos hechos, o la pregunta apunta a una
 * confusión frecuente — el Congreso y el Senado, el jefe del Estado y el del
 * Gobierno, la Constitución de 1812 y la de 1978.
 */

export const ES_QUESTIONS: CountryQuestion[] = [
  // ── Símbolos nacionales ────────────────────────────────────────────────
  { id: "sim-1", lesson: "es-simbolos", level: "easy",
    q: "¿Qué artículo de la Constitución describe la bandera?",
    options: ["El artículo 1", "El artículo 3", "El artículo 4", "El artículo 11"],
    answer: 2,
    explanation: "El artículo 4. El 3 se ocupa de las lenguas y el 11 de la nacionalidad: los tres están en el título preliminar y se confunden con facilidad." },
  { id: "sim-2", lesson: "es-simbolos", level: "medium",
    q: "¿En el reinado de quién se adoptaron el rojo y el amarillo?",
    options: ["De Felipe II", "De Carlos III", "De Fernando VII", "De Alfonso XIII"],
    answer: 1,
    explanation: "Carlos III convocó en 1785 un concurso para dotar a la Armada de un pabellón distinguible. De la marina pasó al ejército y, ya en el siglo XIX, a bandera nacional." },
  { id: "sim-3", lesson: "es-simbolos", level: "medium",
    q: "¿Por qué se eligieron el rojo y el amarillo para el pabellón?",
    options: [
      "Por ser los colores de la Casa Real",
      "Para que la escuadra se distinguiera desde lejos en el mar",
      "Por recordar el oro de América",
      "Por imitar a la bandera francesa",
    ],
    answer: 1,
    explanation: "Casi todas las flotas europeas usaban fondos blancos con escudos y de lejos se confundían. El rojo y el amarillo se ven a mucha distancia: la razón fue práctica antes que simbólica." },
  { id: "sim-4", lesson: "es-simbolos", level: "medium",
    q: "¿Qué reino representa la granada situada al pie del escudo?",
    options: ["Navarra", "Aragón", "Granada", "León"],
    answer: 2,
    explanation: "La granada recuerda el reino nazarí incorporado en 1492, el último de la Península. Navarra aporta las cadenas y Aragón los cuatro palos." },
  { id: "sim-5", lesson: "es-simbolos", level: "hard",
    q: "¿Qué lema llevan las columnas de Hércules del escudo?",
    options: ["PLUS ULTRA", "NON PLUS ULTRA", "UNA GRANDE Y LIBRE", "TANTO MONTA"],
    answer: 0,
    explanation: "Plus ultra, más allá. Antes del descubrimiento de América el lema era el contrario, non plus ultra: nada más allá del estrecho. Se le quitó la negación." },
  { id: "sim-6", lesson: "es-simbolos", level: "easy",
    q: "¿Cómo se llama el himno nacional español?",
    options: ["Himno de Riego", "Marcha Real", "La Marsellesa", "Cara al sol"],
    answer: 1,
    explanation: "La Marcha Real. El Himno de Riego fue el himno de la Segunda República, entre 1931 y 1939." },
  { id: "sim-7", lesson: "es-simbolos", level: "medium",
    q: "¿Desde qué año está documentado el himno español?",
    options: ["Desde 1492", "Desde 1761", "Desde 1812", "Desde 1978"],
    answer: 1,
    explanation: "Aparece en 1761 como Marcha Granadera, lo que lo convierte en uno de los himnos más antiguos de Europa." },
  { id: "sim-8", lesson: "es-simbolos", level: "medium",
    q: "¿Qué se celebra el 6 de diciembre?",
    options: [
      "La Fiesta Nacional",
      "El Día de la Constitución",
      "La proclamación del rey",
      "El Día de la Hispanidad",
    ],
    answer: 1,
    explanation: "El Día de la Constitución, por el referéndum de 1978. La Fiesta Nacional es el 12 de octubre, y el Día de la Hispanidad es otro nombre para esa misma fecha." },
  { id: "sim-9", lesson: "es-simbolos", level: "hard",
    q: "¿Qué se conmemora el 2 de mayo en la Comunidad de Madrid?",
    options: [
      "La entrada de los Reyes Católicos en Granada",
      "El levantamiento de 1808 contra las tropas de Napoleón",
      "La proclamación de la Segunda República",
      "La aprobación del Estatuto de Autonomía",
    ],
    answer: 1,
    explanation: "El levantamiento del pueblo de Madrid en 1808, que abre la Guerra de la Independencia. Es fiesta de la comunidad, no nacional." },
  { id: "sim-10", lesson: "es-simbolos", level: "medium",
    q: "¿Qué lengua declara oficial del Estado el artículo 3?",
    options: ["El castellano", "El español y el catalán", "Todas las lenguas de España por igual", "No lo dice ningún artículo"],
    answer: 0,
    explanation: "El castellano es la lengua española oficial del Estado, y el mismo artículo añade que las demás lenguas españolas serán también oficiales en sus respectivas comunidades." },
  { id: "sim-11", lesson: "es-simbolos", level: "hard",
    q: "¿Cuál es la diferencia entre la bandera con escudo y la bandera sin escudo?",
    options: [
      "La de los edificios oficiales lleva escudo; la de uso común normalmente no",
      "La del escudo solo puede usarla la Casa Real",
      "La sin escudo está prohibida",
      "Son banderas de dos épocas distintas",
    ],
    answer: 0,
    explanation: "Ambas son correctas. La versión oficial, la de organismos y actos del Estado, incorpora el escudo; la que se cuelga de un balcón o se ve en un estadio suele ser la lisa." },
  { id: "sim-12", lesson: "es-simbolos", level: "medium",
    q: "¿Qué figuras ocupan los dos primeros cuarteles del escudo?",
    options: ["Un águila y una cruz", "Un castillo y un león", "Dos columnas", "Una granada y unas cadenas"],
    answer: 1,
    explanation: "El castillo de Castilla y el león de León. Las cadenas son de Navarra, la granada del reino de Granada y las columnas enmarcan el conjunto." },
  { id: "sim-13", lesson: "es-simbolos", level: "hard",
    q: "¿Qué reino representan las cadenas del escudo?",
    options: ["Castilla", "Aragón", "Navarra", "Portugal"],
    answer: 2,
    explanation: "Las cadenas son el emblema de Navarra. Aragón aporta los cuatro palos rojos sobre fondo dorado, y Portugal nunca formó parte del escudo." },

  // ── La Constitución de 1978 ────────────────────────────────────────────
  { id: "con-1", lesson: "es-constitucion", level: "easy",
    q: "¿Cuántos artículos tiene la Constitución española?",
    options: ["Noventa y nueve", "Ciento sesenta y nueve", "Doscientos", "Trescientos"],
    answer: 1,
    explanation: "Ciento sesenta y nueve, repartidos en un título preliminar y diez títulos, más las disposiciones finales. Es un texto largo para los estándares europeos." },
  { id: "con-2", lesson: "es-constitucion", level: "medium",
    q: "¿Cuándo entró en vigor la Constitución?",
    options: [
      "El 6 de diciembre de 1978",
      "El 27 de diciembre de 1978",
      "El 29 de diciembre de 1978",
      "El 1 de enero de 1979",
    ],
    answer: 2,
    explanation: "El 29 de diciembre, el día de su publicación en el Boletín Oficial del Estado. El 6 fue el referéndum y el 27 la sanción del rey." },
  { id: "con-3", lesson: "es-constitucion", level: "medium",
    q: "¿Cómo se conoce a los siete diputados que redactaron el borrador?",
    options: [
      "Los constituyentes",
      "Los padres de la Constitución",
      "La comisión de notables",
      "El consejo de redacción",
    ],
    answer: 1,
    explanation: "Se les llama los padres de la Constitución. Pertenecían a partidos distintos, lo que era el punto: el texto se escribió para que ninguna fuerza quedara fuera." },
  { id: "con-4", lesson: "es-constitucion", level: "hard",
    q: "¿Qué palabra resume el método con el que se redactó la Constitución?",
    options: ["Imposición", "Consenso", "Plebiscito", "Codificación"],
    answer: 1,
    explanation: "Consenso. Algunos artículos son deliberadamente amplios porque se acordó la frase precisamente por admitir más de una lectura: era el precio de que nadie quedara excluido." },
  { id: "con-5", lesson: "es-constitucion", level: "medium",
    q: "¿Qué título de la Constitución trata de la organización territorial del Estado?",
    options: ["El título preliminar", "El título I", "El título VI", "El título VIII"],
    answer: 3,
    explanation: "El título VIII. De él nacen las comunidades autónomas, y por eso al modelo se le llama a veces Estado del título VIII." },
  { id: "con-6", lesson: "es-constitucion", level: "medium",
    q: "¿Qué artículos forman el título preliminar?",
    options: ["Del 1 al 9", "Del 1 al 14", "Del 10 al 55", "Del 1 al 29"],
    answer: 0,
    explanation: "Del 1 al 9: qué es España, dónde reside la soberanía, las lenguas, la bandera, la capital. Del 10 al 55 va el título I, sobre derechos y deberes." },
  { id: "con-7", lesson: "es-constitucion", level: "hard",
    q: "¿Qué dos afirmaciones contiene el artículo 2?",
    options: [
      "La unidad de la Nación y el derecho a la autonomía de nacionalidades y regiones",
      "La soberanía popular y la monarquía parlamentaria",
      "La oficialidad del castellano y de las demás lenguas",
      "La igualdad ante la ley y la prohibición de discriminación",
    ],
    answer: 0,
    explanation: "Las dos mitades se acordaron juntas y ninguna se entiende sin la otra. Sobre ellas se construyó después todo el Estado autonómico." },
  { id: "con-8", lesson: "es-constitucion", level: "medium",
    q: "¿Qué artículo se reformó en 2011?",
    options: ["El artículo 13", "El artículo 135", "El artículo 2", "El artículo 168"],
    answer: 1,
    explanation: "El 135, sobre estabilidad presupuestaria, en plena crisis de deuda. La otra reforma, la de 1992, tocó el artículo 13." },
  { id: "con-9", lesson: "es-constitucion", level: "hard",
    q: "¿Por qué se reformó la Constitución en 1992?",
    options: [
      "Para permitir el voto de extranjeros en las elecciones municipales tras Maastricht",
      "Para introducir el euro",
      "Para reformar el Senado",
      "Para ampliar las competencias autonómicas",
    ],
    answer: 0,
    explanation: "El Tratado de Maastricht obligaba a reconocer el sufragio pasivo en las municipales a los ciudadanos comunitarios, y hubo que añadir dos palabras al artículo 13." },
  { id: "con-10", lesson: "es-constitucion", level: "medium",
    q: "¿Qué procedimiento de reforma obliga a disolver las Cortes y convocar elecciones?",
    options: ["El del artículo 167", "El del artículo 168", "El del artículo 92", "Ninguno lo exige"],
    answer: 1,
    explanation: "El procedimiento agravado del artículo 168, que además exige dos tercios de ambas cámaras antes y después, y un referéndum obligatorio al final." },
  { id: "con-11", lesson: "es-constitucion", level: "hard",
    q: "¿Qué partes de la Constitución protege el procedimiento agravado?",
    options: [
      "Solo el título de la Corona",
      "El título preliminar, los derechos fundamentales de la sección primera y el título de la Corona",
      "Todo el texto por igual",
      "Solo el título VIII",
    ],
    answer: 1,
    explanation: "Son las tres partes que el constituyente quiso poner casi fuera de alcance. Todo lo demás se reforma por el procedimiento ordinario, con tres quintos de cada cámara." },
  { id: "con-12", lesson: "es-constitucion", level: "easy",
    q: "¿Quién sancionó la Constitución en diciembre de 1978?",
    options: ["El presidente del Gobierno", "El rey", "El presidente de las Cortes", "El Tribunal Constitucional"],
    answer: 1,
    explanation: "El rey la sancionó el 27 de diciembre, después de que las Cortes la aprobaran y el pueblo la ratificara en referéndum." },
  { id: "con-13", lesson: "es-constitucion", level: "medium",
    q: "¿Qué mayoría exige el procedimiento ordinario de reforma?",
    options: [
      "Mayoría simple de cada cámara",
      "Mayoría absoluta del Congreso",
      "Tres quintos de cada cámara",
      "Dos tercios de cada cámara",
    ],
    answer: 2,
    explanation: "Tres quintos de Congreso y Senado. Los dos tercios corresponden al procedimiento agravado del artículo 168, que además obliga a disolver las Cortes." },

  // ── Derechos y libertades fundamentales ────────────────────────────────
  { id: "der-1", lesson: "es-derechos", level: "medium",
    q: "¿Qué artículos están protegidos por el recurso de amparo?",
    options: ["Del 1 al 9", "Del 14 al 29", "Del 30 al 38", "Del 39 al 52"],
    answer: 1,
    explanation: "Del 14 al 29: la igualdad y los derechos fundamentales y libertades públicas. Los de los artículos 39 a 52 son principios rectores y no llegan al amparo." },
  { id: "der-2", lesson: "es-derechos", level: "medium",
    q: "¿Qué establece el artículo 14?",
    options: [
      "El derecho a la vida",
      "La igualdad ante la ley sin discriminación alguna",
      "La libertad de expresión",
      "El derecho a la educación",
    ],
    answer: 1,
    explanation: "La igualdad ante la ley, sin que pueda prevalecer discriminación por nacimiento, raza, sexo, religión, opinión o cualquier otra condición personal o social." },
  { id: "der-3", lesson: "es-derechos", level: "medium",
    q: "¿Qué abolió el artículo 15?",
    options: ["La esclavitud", "La pena de muerte", "La censura", "La prisión por deudas"],
    answer: 1,
    explanation: "La pena de muerte, con una salvedad inicial para las leyes penales militares en tiempo de guerra. Esa excepción se suprimió por ley en 1995." },
  { id: "der-4", lesson: "es-derechos", level: "hard",
    q: "¿Cuándo desapareció por completo la pena de muerte del ordenamiento español?",
    options: ["En 1978", "En 1985", "En 1995", "En 2005"],
    answer: 2,
    explanation: "La Constitución la abolió en 1978 salvo para las leyes penales militares en tiempo de guerra, y esa última excepción se eliminó por ley en 1995." },
  { id: "der-5", lesson: "es-derechos", level: "easy",
    q: "¿Qué protege el artículo 18?",
    options: [
      "El honor, la intimidad, el domicilio y el secreto de las comunicaciones",
      "El derecho de huelga",
      "La libertad de circulación",
      "El derecho de petición",
    ],
    answer: 0,
    explanation: "Es el artículo de la vida privada: honor, intimidad, propia imagen, inviolabilidad del domicilio y secreto de las comunicaciones." },
  { id: "der-6", lesson: "es-derechos", level: "medium",
    q: "¿En qué casos puede entrarse en un domicilio sin permiso del titular?",
    options: [
      "Nunca",
      "Con resolución judicial o en caso de delito flagrante",
      "Siempre que lo pida la policía",
      "Con autorización del ayuntamiento",
    ],
    answer: 1,
    explanation: "El domicilio es inviolable. Solo caben el consentimiento del titular, la resolución judicial y el delito flagrante: fuera de esos tres supuestos, la entrada es ilegal." },
  { id: "der-7", lesson: "es-derechos", level: "medium",
    q: "¿Para qué sirve el habeas corpus?",
    options: [
      "Para recurrir una sentencia firme",
      "Para llevar de inmediato ante un juez a quien esté detenido ilegalmente",
      "Para pedir asistencia letrada gratuita",
      "Para impugnar una ley ante el Tribunal Constitucional",
    ],
    answer: 1,
    explanation: "Está previsto en el artículo 17 y sirve para poner sin demora a un detenido a disposición judicial. Es la garantía práctica del límite de las setenta y dos horas." },
  { id: "der-8", lesson: "es-derechos", level: "hard",
    q: "¿Hace falta autorización para celebrar una manifestación en la vía pública?",
    options: [
      "Sí, la autoridad debe concederla",
      "No: basta comunicarla previamente a la autoridad",
      "Solo si participan más de mil personas",
      "Solo en las capitales de provincia",
    ],
    answer: 1,
    explanation: "El artículo 21 exige comunicación previa, no autorización. La autoridad solo puede prohibirla por razones fundadas de alteración del orden público con peligro para personas o bienes." },
  { id: "der-9", lesson: "es-derechos", level: "medium",
    q: "¿Qué prohíbe expresamente el artículo 20 en materia de prensa?",
    options: ["La publicidad", "La censura previa", "Las publicaciones extranjeras", "El anonimato de las fuentes"],
    answer: 1,
    explanation: "La censura previa. El mismo artículo reconoce la libertad de expresión y el derecho a comunicar y recibir información veraz." },
  { id: "der-10", lesson: "es-derechos", level: "hard",
    q: "¿A qué deben orientarse las penas privativas de libertad?",
    options: [
      "A la retribución del daño causado",
      "A la reeducación y la reinserción social",
      "A la disuasión de terceros",
      "Al resarcimiento de la víctima",
    ],
    answer: 1,
    explanation: "El artículo 25 fija la reeducación y la reinserción como orientación de las penas y las medidas de seguridad. Es un mandato constitucional, no una recomendación." },
  { id: "der-11", lesson: "es-derechos", level: "medium",
    q: "¿Dónde está reconocido el derecho a una vivienda digna?",
    options: [
      "Entre los derechos fundamentales, con amparo",
      "En el artículo 47, entre los principios rectores",
      "En el título preliminar",
      "No aparece en la Constitución",
    ],
    answer: 1,
    explanation: "Está en el artículo 47, entre los principios rectores de la política social y económica: obliga al legislador, pero no se reclama directamente ante un juez como la libertad de expresión." },
  { id: "der-12", lesson: "es-derechos", level: "hard",
    q: "¿Cuál es la diferencia práctica entre un derecho fundamental y un principio rector?",
    options: [
      "Ninguna: los dos se alegan igual",
      "El fundamental llega al amparo constitucional; el principio rector solo conforme a las leyes que lo desarrollen",
      "El principio rector obliga a las comunidades y el fundamental al Estado",
      "El principio rector no aparece en el texto constitucional",
    ],
    answer: 1,
    explanation: "La diferencia es de protección, no de importancia. Los fundamentales exigen ley orgánica y llegan al Tribunal Constitucional por la vía del amparo." },
  { id: "der-13", lesson: "es-derechos", level: "easy",
    q: "¿Qué garantiza el artículo 24?",
    options: [
      "La tutela judicial efectiva y la presunción de inocencia",
      "La libertad religiosa",
      "El derecho al trabajo",
      "La inviolabilidad del domicilio",
    ],
    answer: 0,
    explanation: "Juez ordinario predeterminado por la ley, defensa y asistencia de letrado, proceso sin dilaciones indebidas y presunción de inocencia. Es el artículo del proceso justo." },

  // ── Deberes de los ciudadanos y la nacionalidad ────────────────────────
  { id: "deb-1", lesson: "es-deberes", level: "medium",
    q: "¿Cuándo quedó suspendido el servicio militar obligatorio en España?",
    options: ["En 1978", "En 1985", "En 2001", "Sigue vigente"],
    answer: 2,
    explanation: "En 2001. Desde entonces las Fuerzas Armadas son enteramente profesionales, aunque el artículo 30 mantiene el derecho y el deber de defender a España." },
  { id: "deb-2", lesson: "es-deberes", level: "easy",
    q: "¿Qué artículo impone contribuir al sostenimiento de los gastos públicos?",
    options: ["El artículo 30", "El artículo 31", "El artículo 35", "El artículo 47"],
    answer: 1,
    explanation: "El artículo 31, según la capacidad económica de cada uno. El 30 trata de la defensa y el 35 del trabajo." },
  { id: "deb-3", lesson: "es-deberes", level: "medium",
    q: "¿Qué carácter no puede tener nunca el sistema tributario?",
    options: ["Progresivo", "Confiscatorio", "Igualitario", "General"],
    answer: 1,
    explanation: "El artículo 31 exige que sea justo, igual y progresivo, y prohíbe expresamente que tenga alcance confiscatorio: la carga no puede vaciar el patrimonio de quien la soporta." },
  { id: "deb-4", lesson: "es-deberes", level: "medium",
    q: "¿Cuál es la regla principal de la nacionalidad española de origen?",
    options: [
      "Nacer en territorio español",
      "Nacer de padre o madre españoles",
      "Residir cinco años en España",
      "Estar inscrito en el padrón municipal",
    ],
    answer: 1,
    explanation: "Rige el criterio de la sangre: es español de origen quien nace de padre o madre españoles, nazca donde nazca. Nacer en España no basta por sí solo." },
  { id: "deb-5", lesson: "es-deberes", level: "hard",
    q: "¿Puede privarse de la nacionalidad a un español de origen?",
    options: [
      "Sí, por sentencia judicial",
      "No: el artículo 11 lo prohíbe",
      "Sí, si adquiere otra nacionalidad",
      "Solo en tiempo de guerra",
    ],
    answer: 1,
    explanation: "El artículo 11 lo prohíbe expresamente. Quien la ha adquirido por residencia sí puede perderla en supuestos tasados, pero el español de origen no." },
  { id: "deb-6", lesson: "es-deberes", level: "medium",
    q: "¿Con qué países permite la Constitución tratados de doble nacionalidad?",
    options: [
      "Con ninguno",
      "Con los países iberoamericanos y aquellos con vinculación particular con España",
      "Solo con los Estados de la Unión Europea",
      "Con todos los países del mundo",
    ],
    answer: 1,
    explanation: "El artículo 11 los prevé para los países iberoamericanos y para los que hayan tenido o tengan una vinculación particular con España, como Andorra, Filipinas, Guinea Ecuatorial y Portugal." },
  { id: "deb-7", lesson: "es-deberes", level: "medium",
    q: "¿Qué plazo de residencia se exige a quien ha obtenido la condición de refugiado?",
    options: ["Un año", "Dos años", "Cinco años", "Diez años"],
    answer: 2,
    explanation: "Cinco años. Es un plazo intermedio entre el general de diez y el de dos que corresponde a los países con vínculo histórico." },
  { id: "deb-8", lesson: "es-deberes", level: "hard",
    q: "¿Qué plazo se aplica a quien nació en territorio español pero no es español de origen?",
    options: ["Un año", "Dos años", "Cinco años", "Diez años"],
    answer: 0,
    explanation: "Un año, el plazo más corto, junto con supuestos como llevar un año casado con una persona española sin estar separado." },
  { id: "deb-9", lesson: "es-deberes", level: "medium",
    q: "¿Qué dos pruebas acreditan el suficiente grado de integración?",
    options: [
      "Un examen de historia y otro de geografía",
      "La prueba de lengua DELE A2 y la prueba CCSE",
      "Una entrevista en el ayuntamiento y un certificado de empadronamiento",
      "Un examen del Ministerio de Justicia y una prueba médica",
    ],
    answer: 1,
    explanation: "Las dos las administra el Instituto Cervantes: el DELE A2 examina la lengua y la CCSE los conocimientos constitucionales y socioculturales." },
  { id: "deb-10", lesson: "es-deberes", level: "hard",
    q: "¿Quién está exento de la prueba de lengua DELE A2?",
    options: [
      "Los mayores de sesenta y cinco años",
      "Quienes proceden de países donde el español es lengua oficial",
      "Quienes llevan más de veinte años en España",
      "Nadie está exento",
    ],
    answer: 1,
    explanation: "La exención alcanza a los nacionales de países hispanohablantes, que sí deben realizar en cambio la prueba CCSE." },
  { id: "deb-11", lesson: "es-deberes", level: "easy",
    q: "¿A qué edad se alcanza la mayoría de edad en España?",
    options: ["A los dieciséis", "A los dieciocho", "A los veintiuno", "A los veinticinco"],
    answer: 1,
    explanation: "A los dieciocho, y con ella llegan el derecho de voto y la plena capacidad de obrar." },
  { id: "deb-12", lesson: "es-deberes", level: "medium",
    q: "¿A partir de qué edad es obligatorio tener el DNI?",
    options: ["A los siete", "A los catorce", "A los dieciocho", "No es obligatorio"],
    answer: 1,
    explanation: "A partir de los catorce años, cuatro antes de la mayoría de edad. Puede solicitarse antes de forma voluntaria." },
  { id: "deb-13", lesson: "es-deberes", level: "hard",
    q: "¿Qué recoge el artículo 35 además del derecho al trabajo?",
    options: [
      "El deber de trabajar",
      "El derecho de huelga",
      "El salario mínimo",
      "La jornada de cuarenta horas",
    ],
    answer: 0,
    explanation: "El artículo 35 enuncia a la vez el deber y el derecho al trabajo, junto con la libre elección de profesión y una remuneración suficiente. La huelga está en el artículo 28." },

  // ── Fiestas y calendario ───────────────────────────────────────────────
  { id: "fie-1", lesson: "es-fiestas", level: "medium",
    q: "¿Cuántos festivos del calendario laboral fija el ayuntamiento?",
    options: ["Ninguno", "Dos", "Cuatro", "Seis"],
    answer: 1,
    explanation: "Dos de los catorce son locales y los decide cada municipio, normalmente el día del patrón y la fiesta mayor. Por eso un festivo puede no serlo a treinta kilómetros." },
  { id: "fie-2", lesson: "es-fiestas", level: "medium",
    q: "¿Qué día se celebra la fiesta de Cataluña?",
    options: ["El 23 de abril", "El 25 de julio", "El 11 de septiembre", "El 9 de octubre"],
    answer: 2,
    explanation: "El 11 de septiembre, la Diada. El 25 de julio es Galicia, el 9 de octubre la Comunidad Valenciana y el 23 de abril Aragón y Castilla y León." },
  { id: "fie-3", lesson: "es-fiestas", level: "medium",
    q: "¿Qué día se celebra la fiesta de Galicia?",
    options: ["El 28 de febrero", "El 25 de julio", "El 11 de septiembre", "El 6 de diciembre"],
    answer: 1,
    explanation: "El 25 de julio, día de Santiago Apóstol, patrón de España y de Galicia." },
  { id: "fie-4", lesson: "es-fiestas", level: "hard",
    q: "¿Qué día se celebra la fiesta de Andalucía?",
    options: ["El 28 de febrero", "El 23 de abril", "El 2 de mayo", "El 9 de octubre"],
    answer: 0,
    explanation: "El 28 de febrero, aniversario del referéndum autonómico de 1980. El 2 de mayo es Madrid y el 23 de abril Aragón y Castilla y León." },
  { id: "fie-5", lesson: "es-fiestas", level: "easy",
    q: "¿Qué día llegan tradicionalmente los regalos a los niños en España?",
    options: ["El 24 de diciembre", "El 25 de diciembre", "El 31 de diciembre", "El 6 de enero"],
    answer: 3,
    explanation: "El 6 de enero, con los Reyes Magos, cuya cabalgata se celebra la tarde del día 5. En muchas casas conviven hoy ambas fechas, pero la de Reyes sigue siendo la principal." },
  { id: "fie-6", lesson: "es-fiestas", level: "medium",
    q: "¿Qué día de Semana Santa es festivo en toda España?",
    options: ["El Domingo de Ramos", "El Jueves Santo", "El Viernes Santo", "El Lunes de Pascua"],
    answer: 2,
    explanation: "El Viernes Santo lo es en todo el país. El Jueves Santo lo es en la mayoría de comunidades pero no en todas, y el Lunes de Pascua solo en algunas." },
  { id: "fie-7", lesson: "es-fiestas", level: "hard",
    q: "¿Desde qué lugar se retransmiten las campanadas de Nochevieja?",
    options: [
      "Desde la Plaza Mayor de Madrid",
      "Desde la Puerta del Sol de Madrid",
      "Desde la Sagrada Familia de Barcelona",
      "Desde la Giralda de Sevilla",
    ],
    answer: 1,
    explanation: "Desde el reloj de la Puerta del Sol. La retransmisión es uno de los programas de televisión más vistos del año en España." },
  { id: "fie-8", lesson: "es-fiestas", level: "medium",
    q: "¿En qué ciudad se celebran los San Fermines?",
    options: ["En Bilbao", "En Pamplona", "En Zaragoza", "En Logroño"],
    answer: 1,
    explanation: "En Pamplona, del 6 al 14 de julio, y los encierros de la mañana son su imagen más conocida fuera de España." },
  { id: "fie-9", lesson: "es-fiestas", level: "medium",
    q: "¿En qué ciudad se celebra la Feria de Abril?",
    options: ["En Málaga", "En Córdoba", "En Sevilla", "En Granada"],
    answer: 2,
    explanation: "En Sevilla, dos semanas después de Semana Santa, con casetas, caballos y trajes de flamenca." },
  { id: "fie-10", lesson: "es-fiestas", level: "hard",
    q: "¿Qué son las chirigotas?",
    options: [
      "Los monumentos que se queman en las Fallas",
      "Las agrupaciones que cantan con letras satíricas en el carnaval de Cádiz",
      "Los encierros de las fiestas de Pamplona",
      "Las casetas de la Feria de Abril",
    ],
    answer: 1,
    explanation: "Son la seña de identidad del carnaval gaditano: coplas de humor y crítica que se preparan durante todo el año y compiten en el Gran Teatro Falla." },
  { id: "fie-11", lesson: "es-fiestas", level: "medium",
    q: "¿Qué es hacer puente?",
    options: [
      "Trabajar en festivo para librar otro día",
      "Librar el lunes o el viernes contiguo a un festivo que cae en martes o jueves",
      "Cambiar un festivo local por uno nacional",
      "Acumular las vacaciones al final del año",
    ],
    answer: 1,
    explanation: "Cuando el festivo cae en martes o jueves, muchos toman también el día que lo separa del fin de semana. Si coinciden dos festivos cercanos se habla, medio en broma, de acueducto." },
  { id: "fie-12", lesson: "es-fiestas", level: "medium",
    q: "¿Cuándo se queman los monumentos de las Fallas?",
    options: [
      "La noche del 19 de marzo",
      "La noche de San Juan, el 23 de junio",
      "El 15 de agosto",
      "El último día del carnaval",
    ],
    answer: 0,
    explanation: "La noche del 19 de marzo, la cremà. Los monumentos se levantan durante días por toda la ciudad y arden todos la misma noche." },
  { id: "fie-13", lesson: "es-fiestas", level: "hard",
    q: "¿Puede una comunidad autónoma sustituir un festivo estatal por otro propio?",
    options: [
      "No, la lista estatal es idéntica en todo el país",
      "Sí, dentro de los límites que fija la ley",
      "Solo las comunidades con lengua propia",
      "Solo con autorización del Gobierno central",
    ],
    answer: 1,
    explanation: "Las comunidades pueden sustituir algunos festivos estatales por fiestas propias, de modo que ni siquiera la lista del Estado se aplica igual en todas partes." },
];
