import type { Blueprint, VocabSeed } from "./types";

/**
 * The everyday concrete world, taught as words.
 *
 * The catalogue reached five thousand words without ever teaching Hund,
 * Katze, Kopf, Baum or Tomate: the sentence course mentions them, but no
 * pack ever listed them as vocabulary, so the words tracker, Listen and the
 * Immersion extension had a B2 depth inventory sitting on top of a missing
 * A1 floor: about 5,000 words, no animals, and a great deal else missing.
 * These packs are that floor — animals, the body,
 * plants and landscape, food, the kitchen, the household, clothes, jobs and
 * weather — every entry checked against the existing catalogue first, so
 * nothing here re-teaches a word another pack already owns.
 *
 * Same contract as every word pack: hand-authored tuples, article verified,
 * append-only after release. Words with identical German and English
 * spellings (Tiger, Hamster, Butter) are deliberately absent — the catalogue
 * drops a card whose back repeats its front, and it is right to.
 */
const focus = "The concrete everyday world: the words for things a learner can point at, from animals and the body to food, clothes and weather.";

const adjective = (de: string, en: string, use?: string): VocabSeed => ({ de, lookup: de, fallbackEn: en, tip: "adjective", ...(use ? { use } : {}) });
const adverb = (de: string, en: string, use?: string): VocabSeed => ({ de, lookup: de, fallbackEn: en, tip: "adverb", ...(use ? { use } : {}) });
const verbFromDe = (de: string, en: string, use?: string): VocabSeed => ({ de, lookup: de.replace(/^sich /, ""), fallbackEn: en, tip: "verb", ...(use ? { use } : {}) });
const noun = (article: "der" | "die" | "das", de: string, en: string, use?: string): VocabSeed => ({ de: `${article} ${de}`, lookup: de, fallbackEn: en, tip: "noun", article, ...(use ? { use } : {}) });

const pack = (label: string, level: string, theme: string, description: string, seeds: VocabSeed[]): Blueprint => ({
  label,
  level,
  theme,
  description,
  focus,
  seeds,
  dialogues: [],
  phrases: [],
});

export const everydayWordPartBlueprints: Record<string, Blueprint> = {
  part461: pack("Part 461", "A1", "Pets and farm animals", "The animals of homes and farms — the first animals every German child learns to name.", [
    noun("der", "Hund", "dog", "plural: die Hunde"),
    noun("die", "Katze", "cat", "plural: die Katzen; a tomcat is der Kater"),
    noun("das", "Pferd", "horse", "plural: die Pferde"),
    noun("die", "Kuh", "cow", "plural: die Kühe"),
    noun("das", "Schwein", "pig", "Schwein haben = to be lucky (colloquial)"),
    noun("das", "Schaf", "sheep", "plural: die Schafe"),
    noun("das", "Huhn", "chicken, hen", "plural: die Hühner"),
    noun("der", "Hahn", "rooster", "also the tap: der Wasserhahn"),
    noun("die", "Ente", "duck", "also a false news story: eine Zeitungsente"),
    noun("die", "Gans", "goose", "plural: die Gänse"),
    noun("der", "Esel", "donkey", "also a mild word for a fool"),
    noun("der", "Ochse", "ox"),
    noun("der", "Truthahn", "turkey (bird)", "on menus usually die Pute"),
    noun("das", "Kaninchen", "rabbit", "the pet; the wild cousin is der Hase"),
    noun("der", "Hase", "hare", "der Osterhase = the Easter bunny"),
    noun("das", "Meerschweinchen", "guinea pig", "literally 'little sea pig'"),
    noun("der", "Vogel", "bird", "plural: die Vögel; einen Vogel haben = to be crazy (colloquial)"),
    noun("der", "Fisch", "fish", "plural: die Fische"),
    noun("die", "Ratte", "rat"),
    noun("der", "Welpe", "puppy", "weak noun: den Welpen"),
    noun("das", "Kätzchen", "kitten", "-chen nouns are always das"),
    noun("das", "Fohlen", "foal"),
    noun("das", "Kalb", "calf", "plural: die Kälber; veal is das Kalbfleisch"),
    noun("das", "Lamm", "lamb", "plural: die Lämmer"),
  ]),

  part462: pack("Part 462", "A1", "Wild animals", "Animals of forests, mountains and safaris — from the woods behind the house to the zoo.", [
    noun("der", "Fuchs", "fox", "plural: die Füchse; also a clever person"),
    noun("der", "Wolf", "wolf", "plural: die Wölfe"),
    noun("der", "Bär", "bear", "weak noun: den Bären"),
    noun("der", "Eisbär", "polar bear", "literally 'ice bear'"),
    noun("der", "Hirsch", "stag, red deer"),
    noun("das", "Reh", "roe deer", "the small deer of German forests; Bambi is a Reh"),
    noun("das", "Wildschwein", "wild boar", "common in German forests — and gardens"),
    noun("der", "Igel", "hedgehog"),
    noun("das", "Eichhörnchen", "squirrel", "famously hard to pronounce; from die Eiche (oak)"),
    noun("der", "Dachs", "badger"),
    noun("der", "Biber", "beaver"),
    noun("der", "Otter", "otter (animal)"),
    noun("der", "Luchs", "lynx (wild cat)"),
    noun("der", "Maulwurf", "mole (animal)", "literally 'mouth-throw' — it throws up earth"),
    noun("die", "Fledermaus", "bat (animal)", "literally 'flutter mouse'"),
    noun("der", "Elefant", "elephant", "weak noun: den Elefanten"),
    noun("der", "Löwe", "lion", "weak noun: den Löwen"),
    noun("die", "Giraffe", "giraffe"),
    noun("der", "Affe", "monkey, ape", "weak noun: den Affen"),
    noun("das", "Nashorn", "rhinoceros", "literally 'nose horn'"),
    noun("das", "Nilpferd", "hippopotamus", "literally 'Nile horse'; also das Flusspferd"),
    noun("das", "Känguru", "kangaroo"),
    noun("das", "Kamel", "camel", "also a mild insult, like calling someone a fool"),
    noun("der", "Leopard", "leopard", "weak noun: den Leoparden"),
    noun("der", "Gepard", "cheetah"),
    noun("der", "Schimpanse", "chimpanzee", "weak noun: den Schimpansen"),
    noun("das", "Krokodil", "crocodile"),
    noun("der", "Waschbär", "raccoon", "literally 'wash bear' — it appears to wash its food"),
    noun("das", "Stachelschwein", "porcupine", "literally 'spike pig'"),
    noun("das", "Faultier", "sloth (animal)", "literally 'lazy animal'"),
  ]),

  part463: pack("Part 463", "A2", "Birds, sea life and insects", "The creatures of sky, water and garden — birds you hear, sea animals you meet on holiday, insects at the picnic.", [
    noun("der", "Adler", "eagle", "on Germany's federal coat of arms"),
    noun("die", "Eule", "owl"),
    noun("der", "Falke", "falcon, hawk", "weak noun: den Falken"),
    noun("der", "Rabe", "raven", "weak noun: den Raben"),
    noun("die", "Krähe", "crow"),
    noun("die", "Taube", "pigeon, dove", "German uses one word for both"),
    noun("der", "Spatz", "sparrow", "also a term of endearment"),
    noun("die", "Amsel", "blackbird"),
    noun("der", "Storch", "stork", "plural: die Störche; delivers the babies in the old story"),
    noun("der", "Schwan", "swan", "plural: die Schwäne"),
    noun("die", "Möwe", "seagull"),
    noun("der", "Papagei", "parrot"),
    noun("der", "Pfau", "peacock"),
    noun("der", "Delfin", "dolphin"),
    noun("der", "Wal", "whale", "plural: die Wale"),
    noun("der", "Hai", "shark", "also der Haifisch"),
    noun("der", "Tintenfisch", "octopus, squid", "literally 'ink fish'"),
    noun("die", "Qualle", "jellyfish"),
    noun("der", "Krebs", "crab", "also the star sign Cancer and the illness cancer"),
    noun("die", "Muschel", "mussel, seashell"),
    noun("die", "Schildkröte", "turtle, tortoise", "literally 'shield toad'"),
    noun("die", "Eidechse", "lizard"),
    noun("der", "Frosch", "frog", "plural: die Frösche; einen Frosch im Hals haben = a frog in one's throat"),
    noun("die", "Kröte", "toad", "Kröten is also slang for money"),
    noun("die", "Biene", "bee", "fleißig wie eine Biene = busy as a bee"),
    noun("die", "Wespe", "wasp"),
    noun("die", "Hummel", "bumblebee"),
    noun("die", "Ameise", "ant"),
    noun("der", "Schmetterling", "butterfly", "Schmetterlinge im Bauch = butterflies in your stomach"),
    noun("der", "Käfer", "beetle, bug", "the classic VW Beetle is der Käfer"),
    noun("der", "Marienkäfer", "ladybird, ladybug", "a lucky symbol in Germany"),
    noun("die", "Libelle", "dragonfly"),
    noun("die", "Heuschrecke", "grasshopper, locust"),
    noun("der", "Wurm", "worm", "plural: die Würmer"),
    noun("der", "Regenwurm", "earthworm", "literally 'rain worm'"),
  ]),

  part464: pack("Part 464", "A1", "The body from head to toe", "The visible body — what hurts at the doctor's and what you wash in the morning.", [
    noun("der", "Kopf", "head", "plural: die Köpfe"),
    noun("das", "Haar", "hair", "usually plural: die Haare waschen"),
    noun("das", "Gesicht", "face", "plural: die Gesichter"),
    noun("das", "Ohr", "ear", "plural: die Ohren"),
    noun("der", "Mund", "mouth", "plural: die Münder"),
    noun("die", "Lippe", "lip"),
    noun("der", "Zahn", "tooth", "plural: die Zähne; Zähne putzen = to brush your teeth"),
    noun("die", "Zunge", "tongue"),
    noun("die", "Stirn", "forehead", "die Stirn runzeln = to frown"),
    noun("das", "Kinn", "chin"),
    noun("die", "Wange", "cheek", "everyday speech also says die Backe"),
    noun("der", "Hals", "neck, throat", "Hals- und Beinbruch! = break a leg!"),
    noun("die", "Schulter", "shoulder"),
    noun("die", "Hand", "hand", "plural: die Hände"),
    noun("der", "Finger", "finger", "plural: die Finger"),
    noun("der", "Ellbogen", "elbow", "also spelled der Ellenbogen"),
    noun("das", "Handgelenk", "wrist", "literally 'hand joint'"),
    noun("der", "Fingernagel", "fingernail", "plural: die Fingernägel"),
    noun("die", "Brust", "chest, breast"),
    noun("der", "Bauch", "belly, stomach", "plural: die Bäuche; Bauchschmerzen = stomach ache"),
    noun("der", "Rücken", "back (of the body)", "Rückenschmerzen = back pain"),
    noun("die", "Hüfte", "hip"),
    noun("das", "Bein", "leg", "plural: die Beine"),
    noun("das", "Knie", "knee", "plural: die Knie"),
    noun("der", "Fuß", "foot", "plural: die Füße; zu Fuß = on foot"),
    noun("der", "Zeh", "toe", "also die Zehe; der große Zeh = the big toe"),
    noun("der", "Knöchel", "ankle, knuckle", "German uses one word for both"),
    noun("die", "Wade", "calf (of the leg)"),
    noun("der", "Oberschenkel", "thigh", "literally 'upper leg'"),
    noun("der", "Po", "bottom, bum", "the everyday, child-friendly word"),
    noun("die", "Haut", "skin", "plural: die Häute; nass bis auf die Haut = soaked to the skin"),
  ]),

  part465: pack("Part 465", "B1", "Inside the body", "Organs, bones and everything the doctor talks about that you cannot see.", [
    noun("der", "Knochen", "bone", "plural: die Knochen"),
    noun("der", "Muskel", "muscle", "weak-ish plural: die Muskeln"),
    noun("das", "Gehirn", "brain", "in everyday speech often just das Hirn"),
    noun("die", "Lunge", "lung"),
    noun("die", "Leber", "liver"),
    noun("die", "Niere", "kidney"),
    noun("der", "Magen", "stomach (organ)", "the organ; the belly you see is der Bauch"),
    noun("der", "Darm", "intestine, gut", "plural: die Därme"),
    noun("das", "Blut", "blood", "Blut abnehmen = to take a blood sample"),
    noun("die", "Ader", "vein, blood vessel"),
    noun("die", "Rippe", "rib"),
    noun("die", "Wirbelsäule", "spine, backbone", "literally 'vertebra column'"),
    noun("der", "Schädel", "skull", "Schädel brummen = to have a thumping head"),
    noun("die", "Kehle", "throat (inside)", "the inside; the outside of the neck is der Hals"),
    noun("der", "Gaumen", "palate, roof of the mouth"),
    noun("die", "Speiseröhre", "oesophagus, food pipe", "literally 'food tube'"),
    noun("die", "Milz", "spleen"),
    noun("die", "Sehne", "tendon"),
    noun("das", "Gelenk", "joint (of the body)"),
  ]),

  part466: pack("Part 466", "A2", "Trees, plants and flowers", "What grows: the common trees, garden flowers and wild plants of a German walk.", [
    noun("der", "Baum", "tree", "plural: die Bäume"),
    noun("die", "Blume", "flower", "plural: die Blumen"),
    noun("das", "Blatt", "leaf", "plural: die Blätter; also a sheet of paper"),
    noun("der", "Ast", "branch", "plural: die Äste"),
    noun("der", "Stamm", "trunk (of a tree)", "also a regulars' table: der Stammtisch"),
    noun("die", "Rinde", "bark (of a tree)", "also the rind of cheese or bread crust"),
    noun("die", "Eiche", "oak", "the classic German tree"),
    noun("die", "Buche", "beech"),
    noun("die", "Tanne", "fir", "der Tannenbaum = the Christmas tree"),
    noun("die", "Fichte", "spruce", "the most common tree in German forests"),
    noun("die", "Kiefer", "pine (tree)", "der Kiefer (masculine) is the jaw — the article decides"),
    noun("der", "Ahorn", "maple"),
    noun("die", "Kastanie", "chestnut", "conkers children collect in autumn"),
    noun("die", "Weide", "willow", "also a pasture where animals graze"),
    noun("die", "Linde", "lime tree, linden", "the tree of village squares — Unter den Linden"),
    noun("die", "Rose", "rose (flower)"),
    noun("die", "Nelke", "carnation", "also the spice clove: die Gewürznelke"),
    noun("das", "Gänseblümchen", "daisy", "literally 'little goose flower'"),
    noun("der", "Löwenzahn", "dandelion", "literally 'lion's tooth'"),
    noun("das", "Veilchen", "violet (flower)", "also a black eye, jokingly"),
    noun("die", "Orchidee", "orchid"),
    noun("der", "Kaktus", "cactus", "plural: die Kakteen"),
    noun("der", "Farn", "fern"),
    noun("das", "Moos", "moss", "also slang for money"),
    noun("der", "Efeu", "ivy"),
    noun("die", "Brennnessel", "stinging nettle", "literally 'burning nettle' — three n's in a row"),
    noun("die", "Distel", "thistle"),
    noun("das", "Schilf", "reed, reeds"),
    noun("das", "Getreide", "grain, cereal crops"),
    noun("der", "Weizen", "wheat", "das Weizenbier / das Weißbier = wheat beer"),
    noun("der", "Roggen", "rye", "German bread's favourite grain: das Roggenbrot"),
    noun("der", "Hafer", "oats", "die Haferflocken = porridge oats"),
    noun("die", "Gerste", "barley", "what beer is brewed from"),
    noun("der", "Mais", "corn, maize"),
  ]),

  part467: pack("Part 467", "A1", "Landscape and the natural world", "The land itself: mountains, rivers, sky and stone — the vocabulary of every hike and every view.", [
    noun("der", "Berg", "mountain", "plural: die Berge; in die Berge fahren = to go to the mountains"),
    noun("der", "Hügel", "hill"),
    noun("das", "Gebirge", "mountain range", "das Hochgebirge = the high mountains"),
    noun("der", "Hang", "slope, hillside"),
    noun("die", "Klippe", "cliff"),
    noun("der", "Wald", "forest, wood", "plural: die Wälder"),
    noun("die", "Wiese", "meadow"),
    noun("der", "Fluss", "river", "plural: die Flüsse"),
    noun("der", "Bach", "stream, brook", "plural: die Bäche"),
    noun("der", "Teich", "pond"),
    noun("das", "Meer", "sea", "ans Meer fahren = to go to the seaside"),
    noun("der", "Ozean", "ocean"),
    noun("der", "Strand", "beach", "plural: die Strände; am Strand = at the beach"),
    noun("die", "Küste", "coast"),
    noun("die", "Wüste", "desert", "not to be confused with der Wüstling or das Dessert"),
    noun("der", "Dschungel", "jungle"),
    noun("der", "Vulkan", "volcano"),
    noun("der", "Wasserfall", "waterfall"),
    noun("der", "Gletscher", "glacier"),
    noun("der", "Sumpf", "swamp, marsh"),
    noun("das", "Moor", "bog, moor"),
    noun("der", "Fels", "rock, cliff face", "also der Felsen"),
    noun("der", "Stein", "stone", "plural: die Steine"),
    noun("der", "Sand", "sand"),
    noun("die", "Erde", "earth, soil", "also the planet: die Erde"),
    noun("der", "Schlamm", "mud"),
    noun("der", "Himmel", "sky, heaven", "German uses one word for both"),
    noun("die", "Wolke", "cloud"),
    noun("der", "Stern", "star", "plural: die Sterne"),
    noun("der", "Mond", "moon"),
    noun("die", "Sonne", "sun", "die Sonne scheint = the sun is shining"),
    noun("der", "Regenbogen", "rainbow"),
    noun("der", "Horizont", "horizon", "also figurative: den Horizont erweitern"),
    noun("die", "Strömung", "current (of water)", "also a movement or trend in art or politics"),
    noun("die", "Quelle", "spring, source", "also the source of information"),
  ]),

  part468: pack("Part 468", "A1", "Fruit and nuts", "The fruit bowl and the baking cupboard — what you buy at the market by the kilo.", [
    noun("die", "Birne", "pear", "also the colloquial word for a light bulb"),
    noun("die", "Orange", "orange (fruit)", "also die Apfelsine in the north"),
    noun("die", "Zitrone", "lemon"),
    noun("die", "Erdbeere", "strawberry", "literally 'earth berry'"),
    noun("die", "Himbeere", "raspberry"),
    noun("die", "Blaubeere", "blueberry", "also die Heidelbeere"),
    noun("die", "Pflaume", "plum"),
    noun("der", "Pfirsich", "peach"),
    noun("die", "Aprikose", "apricot", "die Marille in Austria"),
    noun("die", "Traube", "grape", "usually plural: die Trauben; die Weintraube"),
    noun("die", "Melone", "melon", "also a bowler hat"),
    noun("die", "Wassermelone", "watermelon"),
    noun("die", "Ananas", "pineapple"),
    noun("der", "Granatapfel", "pomegranate", "literally 'grenade apple'"),
    noun("die", "Feige", "fig", "the adjective feige means cowardly"),
    noun("die", "Dattel", "date (fruit)"),
    noun("die", "Rosine", "raisin", "Rosinen im Kopf haben = to have big ideas"),
    noun("die", "Nuss", "nut", "plural: die Nüsse; eine harte Nuss = a tough nut to crack"),
    noun("die", "Walnuss", "walnut"),
    noun("die", "Haselnuss", "hazelnut"),
    noun("die", "Erdnuss", "peanut", "literally 'earth nut'"),
    noun("die", "Mandel", "almond", "plural also means tonsils: die Mandeln"),
  ]),

  part469: pack("Part 469", "A1", "Vegetables and herbs", "The vegetable aisle and the herb pots on the windowsill.", [
    noun("die", "Kartoffel", "potato", "plural: die Kartoffeln"),
    noun("die", "Tomate", "tomato"),
    noun("die", "Gurke", "cucumber", "die saure Gurke = the pickled gherkin"),
    noun("die", "Karotte", "carrot", "also die Möhre, especially in the north"),
    noun("die", "Zwiebel", "onion"),
    noun("der", "Knoblauch", "garlic"),
    noun("die", "Paprika", "pepper (vegetable)", "the vegetable; the spice powder is der Paprika"),
    noun("die", "Zucchini", "courgette, zucchini"),
    noun("die", "Aubergine", "aubergine, eggplant"),
    noun("der", "Brokkoli", "broccoli"),
    noun("der", "Blumenkohl", "cauliflower", "literally 'flower cabbage'"),
    noun("der", "Rosenkohl", "Brussels sprouts", "literally 'rose cabbage'"),
    noun("der", "Spinat", "spinach"),
    noun("der", "Salat", "lettuce, salad", "the plant and the dish share one word"),
    noun("der", "Kohl", "cabbage"),
    noun("der", "Sellerie", "celery, celeriac"),
    noun("das", "Radieschen", "radish", "the small red kind; the big white one is der Rettich"),
    noun("der", "Rettich", "white radish, daikon"),
    noun("die", "Rübe", "turnip, beet", "die Rote Bete = beetroot"),
    noun("der", "Kürbis", "pumpkin, squash"),
    noun("die", "Erbse", "pea", "plural: die Erbsen"),
    noun("die", "Linse", "lentil", "also a camera or glasses lens"),
    noun("der", "Spargel", "asparagus", "a German spring obsession: die Spargelzeit"),
    noun("die", "Artischocke", "artichoke"),
    noun("der", "Fenchel", "fennel"),
    noun("der", "Ingwer", "ginger"),
    noun("die", "Petersilie", "parsley"),
    noun("der", "Schnittlauch", "chives", "literally 'cut leek'"),
    noun("das", "Basilikum", "basil"),
    noun("der", "Thymian", "thyme"),
    noun("der", "Rosmarin", "rosemary"),
    noun("die", "Minze", "mint (herb)", "der Pfefferminztee = peppermint tea"),
  ]),

  part470: pack("Part 470", "A2", "Cooking and food staples", "What the recipe calls for: staples, seasonings, and the meat and fish counters.", [
    noun("der", "Essig", "vinegar", "Essig und Öl = oil and vinegar"),
    noun("der", "Honig", "honey"),
    noun("die", "Marmelade", "jam", "in German any fruit jam, not only marmalade"),
    noun("das", "Mehl", "flour"),
    noun("die", "Hefe", "yeast", "das Hefeweizen = the yeast wheat beer"),
    noun("der", "Teig", "dough, batter"),
    noun("der", "Zimt", "cinnamon"),
    noun("der", "Kümmel", "caraway", "the seed in German bread; cumin is Kreuzkümmel"),
    noun("der", "Koriander", "coriander, cilantro"),
    noun("die", "Muskatnuss", "nutmeg"),
    noun("der", "Kuchen", "cake", "Kaffee und Kuchen = the German afternoon ritual"),
    noun("der", "Zwieback", "rusk", "the twice-baked dry bread for upset stomachs"),
    noun("der", "Quark", "quark (soft cheese)", "the soft fresh cheese German fridges always hold"),
    noun("der", "Joghurt", "yoghurt"),
    noun("die", "Margarine", "margarine (spread)"),
    noun("der", "Speck", "bacon", "Speck also means padding you'd like to lose"),
    noun("die", "Wurst", "sausage", "plural: die Würste; Das ist mir Wurst = I don't care"),
    noun("das", "Schnitzel", "schnitzel, breaded cutlet"),
    noun("das", "Kotelett", "chop, cutlet"),
    noun("der", "Lachs", "salmon"),
    noun("die", "Forelle", "trout"),
    noun("der", "Thunfisch", "tuna", "literally 'tuna fish'"),
    noun("die", "Garnele", "prawn, shrimp"),
  ]),

  part471: pack("Part 471", "A2", "In the kitchen", "The drawer full of tools: everything you reach for while cooking that is not food.", [
    noun("die", "Schüssel", "bowl"),
    noun("der", "Krug", "jug, pitcher", "plural: die Krüge; der Bierkrug = the beer stein"),
    noun("das", "Tablett", "tray", "not das Tablet — that is the computer"),
    noun("die", "Untertasse", "saucer", "literally 'under-cup'"),
    noun("die", "Tischdecke", "tablecloth"),
    noun("das", "Sieb", "sieve, colander"),
    noun("die", "Reibe", "grater"),
    noun("das", "Nudelholz", "rolling pin", "literally 'noodle wood'"),
    noun("der", "Dosenöffner", "tin opener, can opener"),
    noun("der", "Flaschenöffner", "bottle opener"),
    noun("der", "Korkenzieher", "corkscrew", "literally 'cork puller'"),
    noun("die", "Schöpfkelle", "ladle", "also der Schöpflöffel"),
    noun("der", "Pfannenwender", "spatula, fish slice", "literally 'pan turner'"),
    noun("der", "Topflappen", "oven cloth, pot holder", "literally 'pot rag'"),
    noun("die", "Frischhaltefolie", "cling film", "literally 'keep-fresh foil'"),
    noun("die", "Alufolie", "aluminium foil, tin foil"),
    noun("das", "Backpapier", "baking paper"),
    noun("die", "Spüle", "kitchen sink", "spülen = to wash up"),
    noun("der", "Wasserhahn", "tap, faucet", "literally 'water rooster'"),
    noun("der", "Abfluss", "drain, plughole"),
    noun("der", "Mülleimer", "rubbish bin", "the small one inside; the big one outside is die Mülltonne"),
    noun("die", "Mülltonne", "wheelie bin, dustbin", "the big outdoor bin, colour-coded for recycling"),
    noun("der", "Müllbeutel", "bin bag, bin liner"),
  ]),

  part472: pack("Part 472", "A2", "Around the house", "Cleaning, fixing and the small fittings of home — the vocabulary of Saturday chores.", [
    noun("der", "Besen", "broom", "neue Besen kehren gut = a new broom sweeps clean"),
    noun("die", "Kehrschaufel", "dustpan"),
    noun("das", "Bügelbrett", "ironing board", "bügeln = to iron"),
    noun("die", "Wäscheleine", "washing line, clothesline"),
    noun("der", "Kleiderbügel", "coat hanger, clothes hanger"),
    noun("die", "Seife", "soap"),
    noun("das", "Handtuch", "towel", "das Handtuch werfen = to throw in the towel"),
    noun("der", "Waschlappen", "flannel, washcloth", "also a colloquial word for a wimp"),
    noun("der", "Kamm", "comb", "plural: die Kämme; kämmen = to comb"),
    noun("der", "Rasierer", "razor, shaver", "sich rasieren = to shave"),
    noun("der", "Föhn", "hairdryer", "also the warm Alpine wind that gives people headaches"),
    noun("der", "Spiegel", "mirror"),
    noun("das", "Wattestäbchen", "cotton bud, cotton swab"),
    noun("das", "Taschentuch", "tissue, handkerchief", "literally 'pocket cloth'"),
    noun("das", "Toilettenpapier", "toilet paper"),
    noun("das", "Kissen", "cushion, pillow"),
    noun("das", "Kopfkissen", "pillow (for sleeping)"),
    noun("die", "Bettdecke", "duvet, blanket"),
    noun("das", "Laken", "sheet (for the bed)", "also das Bettlaken"),
    noun("die", "Decke", "blanket, ceiling", "one word for both — context decides"),
    noun("die", "Jalousie", "venetian blind", "from French; the curtain is der Vorhang"),
    noun("die", "Fliese", "tile", "gefliest = tiled"),
    noun("die", "Türklinke", "door handle"),
    noun("das", "Schlüsselloch", "keyhole"),
    noun("die", "Klingel", "doorbell", "klingeln = to ring"),
    noun("der", "Zaun", "fence", "plural: die Zäune"),
    noun("der", "Dachboden", "attic, loft"),
    noun("der", "Kamin", "fireplace, chimney"),
    noun("der", "Rauchmelder", "smoke detector", "legally required in German homes"),
    noun("die", "Taschenlampe", "torch, flashlight", "literally 'pocket lamp'"),
    noun("das", "Streichholz", "matchstick, match (for fire)", "literally 'strike wood'"),
    noun("die", "Schere", "scissors", "singular in German: die Schere ist scharf"),
    noun("der", "Kleber", "glue", "also der Klebstoff; kleben = to stick"),
    noun("der", "Faden", "thread", "plural: die Fäden; den Faden verlieren = to lose one's thread"),
    noun("der", "Knopf", "button", "plural: die Knöpfe — clothes button or push button"),
    noun("der", "Schraubenzieher", "screwdriver", "also der Schraubendreher"),
    noun("die", "Säge", "saw (tool)", "sägen = to saw"),
    noun("das", "Verlängerungskabel", "extension cord, extension lead", "the single long cable; the multi-socket strip is die Steckerleiste"),
  ]),

  part473: pack("Part 473", "A1", "Clothes and fabrics", "What you wear and what it is made of — from underwear drawer to winter coat.", [
    noun("das", "Hemd", "shirt", "plural: die Hemden"),
    noun("die", "Bluse", "blouse"),
    noun("der", "Pullover", "jumper, sweater", "shortened: der Pulli"),
    noun("die", "Strickjacke", "cardigan", "literally 'knit jacket'"),
    noun("die", "Weste", "waistcoat, vest (sleeveless)"),
    noun("der", "Anzug", "suit (clothing)", "plural: die Anzüge"),
    noun("die", "Krawatte", "tie (clothing)", "also der Schlips"),
    noun("der", "Gürtel", "belt", "den Gürtel enger schnallen = to tighten one's belt"),
    noun("das", "Kleid", "dress", "plural: die Kleider, which also means clothes"),
    noun("der", "Mantel", "coat", "plural: die Mäntel"),
    noun("die", "Jacke", "jacket"),
    noun("die", "Regenjacke", "rain jacket"),
    noun("die", "Daunenjacke", "down jacket, puffer jacket"),
    noun("der", "Handschuh", "glove", "literally 'hand shoe'"),
    noun("der", "Schal", "scarf", "plural: die Schals"),
    noun("die", "Mütze", "beanie, woolly hat"),
    noun("der", "Hut", "hat", "plural: die Hüte; Hut ab! = hats off!"),
    noun("die", "Kappe", "cap (hat)", "the baseball kind is often just die Cap"),
    noun("die", "Socke", "sock", "plural: die Socken"),
    noun("der", "Strumpf", "stocking, long sock", "plural: die Strümpfe"),
    noun("die", "Strumpfhose", "tights, pantyhose", "literally 'stocking trousers'"),
    noun("die", "Unterhose", "underpants, briefs"),
    noun("das", "Unterhemd", "vest, undershirt"),
    noun("der", "BH", "bra", "short for der Büstenhalter; say beh-hah"),
    noun("der", "Schlafanzug", "pyjamas", "literally 'sleep suit'; also der Pyjama"),
    noun("die", "Badehose", "swimming trunks"),
    noun("der", "Badeanzug", "swimsuit, swimming costume"),
    noun("der", "Stiefel", "boot", "plural: die Stiefel"),
    noun("die", "Sandale", "sandal"),
    noun("der", "Hausschuh", "slipper", "literally 'house shoe'"),
    noun("der", "Kragen", "collar"),
    noun("die", "Kapuze", "hood (of clothing)", "der Kapuzenpullover = the hoodie"),
    noun("das", "Knopfloch", "buttonhole"),
    noun("die", "Wolle", "wool"),
    noun("die", "Baumwolle", "cotton", "literally 'tree wool'"),
    noun("die", "Seide", "silk"),
    noun("das", "Leinen", "linen"),
    noun("der", "Samt", "velvet"),
    adjective("gestreift", "striped"),
    adjective("kariert", "checked, plaid", "also squared paper: kariertes Papier"),
    adjective("gepunktet", "polka-dotted, spotted"),
    noun("der", "Kleiderschrank", "wardrobe", "literally 'clothes cupboard'"),
  ]),

  part474: pack("Part 474", "A1", "Jobs people do", "Professions you meet every week — masculine forms shown; add -in for the feminine: die Lehrerin.", [
    noun("der", "Arzt", "doctor (medical)", "feminine: die Ärztin; beim Arzt = at the doctor's"),
    noun("der", "Zahnarzt", "dentist", "literally 'tooth doctor'"),
    noun("die", "Krankenschwester", "nurse", "male nurses are der Krankenpfleger"),
    noun("die", "Hebamme", "midwife"),
    noun("der", "Chirurg", "surgeon", "weak noun: den Chirurgen"),
    noun("der", "Apotheker", "pharmacist, chemist"),
    noun("der", "Psychologe", "psychologist", "weak noun: den Psychologen"),
    noun("der", "Lehrer", "teacher", "feminine: die Lehrerin"),
    noun("der", "Erzieher", "nursery teacher, educator", "the profession at the Kita"),
    noun("der", "Professor", "professor", "feminine: die Professorin"),
    noun("der", "Richter", "judge (in court)"),
    noun("der", "Polizist", "police officer", "weak noun: den Polizisten"),
    noun("der", "Feuerwehrmann", "firefighter", "plural: die Feuerwehrleute"),
    noun("der", "Soldat", "soldier", "weak noun: den Soldaten"),
    noun("der", "Pilot", "pilot", "weak noun: den Piloten"),
    noun("der", "Flugbegleiter", "flight attendant", "feminine: die Flugbegleiterin"),
    noun("der", "Busfahrer", "bus driver"),
    noun("der", "Lokführer", "train driver", "die Lok = the locomotive"),
    noun("der", "Kapitän", "captain (ship or team)"),
    noun("der", "Seemann", "sailor, seaman", "plural: die Seeleute"),
    noun("der", "Astronaut", "astronaut", "weak noun: den Astronauten"),
    noun("der", "Mechaniker", "mechanic"),
    noun("der", "Elektriker", "electrician"),
    noun("der", "Tischler", "carpenter, joiner", "also der Schreiner in the south"),
    noun("der", "Maurer", "bricklayer, mason"),
    noun("der", "Dachdecker", "roofer", "literally 'roof coverer'"),
    noun("der", "Ingenieur", "engineer", "say in-zheh-NEUR — the g is French"),
    noun("der", "Architekt", "architect", "weak noun: den Architekten"),
    noun("der", "Bäcker", "baker", "beim Bäcker = at the bakery"),
    noun("der", "Kellner", "waiter", "feminine: die Kellnerin; call them with 'Entschuldigung!'"),
    noun("der", "Gärtner", "gardener"),
    noun("der", "Bauer", "farmer", "weak noun: den Bauern; also the pawn in chess"),
    noun("der", "Fischer", "fisherman"),
    noun("der", "Förster", "forester, ranger"),
    noun("der", "Schneider", "tailor", "frieren wie ein Schneider = to be freezing cold"),
    noun("der", "Uhrmacher", "watchmaker"),
    noun("der", "Journalist", "journalist", "weak noun: den Journalisten"),
    noun("der", "Fotograf", "photographer", "weak noun: den Fotografen"),
    noun("der", "Sänger", "singer", "feminine: die Sängerin"),
    noun("der", "Musiker", "musician"),
    noun("der", "Bildhauer", "sculptor", "literally 'picture hewer'"),
    noun("der", "Schriftsteller", "writer, author", "literally 'script placer'"),
    noun("der", "Übersetzer", "translator", "translates writing; speech is der Dolmetscher"),
    noun("der", "Dolmetscher", "interpreter", "interprets speech live"),
    noun("der", "Bibliothekar", "librarian"),
    noun("der", "Kassierer", "cashier", "an der Kasse = at the till"),
    noun("der", "Verkäufer", "shop assistant, seller"),
    noun("der", "Buchhalter", "accountant, bookkeeper", "literally 'book holder'"),
    noun("der", "Wissenschaftler", "scientist", "die Wissenschaft = science"),
    noun("der", "Forscher", "researcher", "forschen = to research"),
    noun("der", "Briefträger", "postman", "literally 'letter carrier'; also der Postbote"),
    noun("der", "Bürgermeister", "mayor", "literally 'citizens' master'"),
  ]),

  part510: pack("Part 510", "A1", "Around town", "The buildings, corners and street furniture of every German town — what you walk past on the way to anywhere.", [
    noun("der", "Dom", "cathedral", "the Kölner Dom is THE Dom"),
    noun("der", "Turm", "tower", "plural: die Türme; also the rook in chess"),
    noun("das", "Denkmal", "monument, memorial"),
    noun("der", "Brunnen", "fountain, well"),
    noun("der", "Spielplatz", "playground", "literally 'play square'"),
    noun("der", "Sandkasten", "sandpit, sandbox"),
    noun("die", "Fußgängerzone", "pedestrian zone", "the car-free shopping heart of German towns"),
    noun("die", "Ampel", "traffic light", "bei Rot über die Ampel = running a red light"),
    noun("die", "Kreuzung", "crossroads, junction"),
    noun("der", "Zebrastreifen", "zebra crossing", "literally 'zebra stripes'"),
    noun("der", "Kreisverkehr", "roundabout", "literally 'circle traffic'"),
    noun("die", "Einbahnstraße", "one-way street"),
    noun("der", "Bürgersteig", "pavement, sidewalk", "also der Gehweg"),
    noun("die", "Laterne", "street lamp, lantern", "children carry Laternen on St. Martin's Day"),
    noun("die", "Bushaltestelle", "bus stop"),
    noun("die", "Tankstelle", "petrol station, gas station", "tanken = to fill up"),
    noun("das", "Parkhaus", "multi-storey car park, parking garage"),
    noun("das", "Hochhaus", "high-rise, tower block"),
    noun("der", "Wolkenkratzer", "skyscraper", "literally 'cloud scraper'"),
    noun("das", "Einkaufszentrum", "shopping centre, mall"),
    noun("die", "Buchhandlung", "bookshop, bookstore"),
    noun("die", "Bäckerei", "bakery", "where the morning Brötchen come from"),
    noun("die", "Konditorei", "cake shop, patisserie"),
    noun("die", "Reinigung", "dry cleaner's", "also simply the act of cleaning"),
    noun("der", "Waschsalon", "launderette, laundromat"),
    noun("das", "Postamt", "post office", "usually just die Post these days"),
    noun("das", "Gefängnis", "prison, jail", "plural: die Gefängnisse"),
    noun("die", "Kaserne", "barracks"),
    noun("die", "Galerie", "gallery (art)"),
    noun("das", "Theater", "theatre", "Theater machen = to make a fuss"),
    noun("die", "Oper", "opera, opera house"),
    noun("der", "Zirkus", "circus", "also a fuss: mach keinen Zirkus"),
    noun("das", "Stadion", "stadium", "plural: die Stadien"),
    noun("das", "Schwimmbad", "swimming pool (public baths)", "outdoor is das Freibad, indoor das Hallenbad"),
    noun("das", "Hallenbad", "indoor swimming pool"),
    noun("die", "Turnhalle", "gym hall, gymnasium", "the school sports hall — a fitness gym is das Fitnessstudio"),
  ]),

  part511: pack("Part 511", "A2", "On the road", "Vehicles and the parts of a car every driver ends up naming — at the garage, at the checkpoint, in the breakdown lane.", [
    noun("das", "Motorrad", "motorbike, motorcycle"),
    noun("der", "Roller", "scooter", "both the Vespa kind and the kick scooter"),
    noun("das", "Mofa", "moped", "short for Motorfahrrad"),
    noun("der", "Lastwagen", "lorry, truck", "usually shortened to der LKW"),
    noun("der", "Lieferwagen", "delivery van"),
    noun("der", "Wohnwagen", "caravan, trailer home", "towed; the motorhome is das Wohnmobil"),
    noun("der", "Traktor", "tractor", "also der Trecker in the north"),
    noun("der", "Bagger", "excavator, digger", "baggern also means to flirt hard (colloquial)"),
    noun("der", "Kran", "crane (machine)", "plural: die Kräne; the bird is der Kranich"),
    noun("der", "Krankenwagen", "ambulance", "literally 'sick-person car'"),
    noun("das", "Feuerwehrauto", "fire engine"),
    noun("das", "Polizeiauto", "police car"),
    noun("die", "Straßenbahn", "tram, streetcar", "shortened: die Bahn or die Tram"),
    noun("die", "Fähre", "ferry"),
    noun("das", "Segelboot", "sailing boat"),
    noun("das", "Ruderboot", "rowing boat"),
    noun("das", "Kanu", "canoe"),
    noun("der", "Hubschrauber", "helicopter", "literally 'lift-screwer'; also der Helikopter"),
    noun("der", "Lenker", "handlebars", "on a car it is das Lenkrad (steering wheel)"),
    noun("das", "Pedal", "pedal", "in die Pedale treten = to pedal hard"),
    noun("die", "Kupplung", "clutch", "die Kupplung kommen lassen = to release the clutch"),
    noun("das", "Gaspedal", "accelerator, gas pedal"),
    noun("der", "Scheinwerfer", "headlight, spotlight", "literally 'shine thrower'"),
    noun("das", "Kennzeichen", "number plate, license plate", "also das Nummernschild"),
    noun("die", "Windschutzscheibe", "windscreen, windshield", "literally 'wind protection pane'"),
    noun("der", "Scheibenwischer", "windscreen wiper"),
    noun("der", "Rückspiegel", "rear-view mirror"),
    noun("der", "Sicherheitsgurt", "seatbelt", "sich anschnallen = to buckle up"),
    noun("die", "Motorhaube", "bonnet, hood (of a car)", "literally 'engine hood'"),
    noun("der", "Auspuff", "exhaust (of a car)"),
    noun("der", "Tank", "fuel tank", "tanken = to fill up; the military tank is der Panzer"),
    noun("der", "Ersatzreifen", "spare tyre"),
    noun("der", "Wagenheber", "car jack", "literally 'car lifter'"),
    noun("das", "Warndreieck", "warning triangle", "legally required in every German car"),
  ]),

  part512: pack("Part 512", "A1", "School and desk things", "What lives in a pencil case, a school bag and a desk drawer.", [
    noun("der", "Bleistift", "pencil", "literally 'lead pen'"),
    noun("der", "Kugelschreiber", "ballpoint pen", "shortened: der Kuli"),
    noun("der", "Füller", "fountain pen", "German pupils learn to write with one"),
    noun("der", "Radiergummi", "rubber, eraser", "radieren = to erase"),
    noun("der", "Spitzer", "pencil sharpener", "spitz = pointed"),
    noun("das", "Lineal", "ruler (for drawing)"),
    noun("der", "Zirkel", "pair of compasses", "for drawing circles; the direction finder is der Kompass"),
    noun("der", "Taschenrechner", "calculator", "literally 'pocket reckoner'"),
    noun("die", "Mappe", "document folder, portfolio"),
    noun("der", "Ranzen", "school satchel", "also der Schulranzen; the backpack kind is der Schulrucksack"),
    noun("die", "Kreide", "chalk"),
    noun("der", "Pausenhof", "school yard", "also der Schulhof; die Pause = break time"),
    noun("das", "Klassenzimmer", "classroom"),
    noun("der", "Stundenplan", "timetable (school)", "literally 'hours plan'"),
    noun("die", "Hausaufgabe", "homework", "usually plural: Hausaufgaben machen"),
    noun("die", "Ferien", "school holidays", "always plural; a booked holiday is der Urlaub"),
    noun("die", "Büroklammer", "paper clip"),
    noun("der", "Locher", "hole punch"),
    noun("der", "Tacker", "stapler", "tackern = to staple; also der Hefter"),
    noun("der", "Textmarker", "highlighter"),
    noun("der", "Notizblock", "notepad"),
    noun("der", "Kalender", "calendar, diary"),
    noun("der", "Briefumschlag", "envelope", "literally 'letter wrap'"),
    noun("der", "Aktenordner", "ring binder, file folder", "die Akte = the file"),
    noun("die", "Schreibtischlampe", "desk lamp"),
    noun("der", "Papierkorb", "waste-paper basket", "also the recycle bin on a computer"),
    noun("der", "Kopierer", "photocopier", "kopieren = to copy"),
    noun("der", "Bildschirmschoner", "screensaver", "literally 'screen protector'"),
  ]),

  part513: pack("Part 513", "A2", "Sport and music", "Playing, training, winning — and the instruments and ensembles of making music.", [
    noun("das", "Tischtennis", "table tennis", "a German café and youth-club staple"),
    noun("das", "Turnen", "gymnastics", "turnen = to do gymnastics"),
    noun("die", "Leichtathletik", "athletics, track and field", "literally 'light athletics'"),
    verbFromDe("schwimmen", "to swim", "irregular: schwamm, ist geschwommen; swimming as a sport is das Schwimmen"),
    verbFromDe("segeln", "to sail"),
    verbFromDe("rudern", "to row (a boat)"),
    verbFromDe("reiten", "to ride (a horse)", "on a bike or bus it is fahren"),
    verbFromDe("klettern", "to climb", "takes sein: Sie ist auf den Baum geklettert"),
    verbFromDe("joggen", "to jog"),
    noun("der", "Torwart", "goalkeeper", "also der Torhüter"),
    noun("der", "Pokal", "trophy, cup", "der DFB-Pokal = the German FA cup"),
    noun("die", "Medaille", "medal", "say me-DAL-ye"),
    noun("die", "Weltmeisterschaft", "world championship, World Cup", "shortened: die WM"),
    noun("die", "Olympiade", "Olympics", "officially die Olympischen Spiele"),
    noun("die", "Gitarre", "guitar"),
    noun("die", "Flöte", "flute, recorder", "the school recorder is die Blockflöte"),
    noun("die", "Trompete", "trumpet"),
    noun("die", "Trommel", "drum", "die Werbetrommel rühren = to drum up publicity"),
    noun("die", "Harfe", "harp"),
    noun("der", "Chor", "choir", "say kohr; plural: die Chöre"),
    noun("das", "Orchester", "orchestra", "say or-KES-ter"),
    noun("der", "Dirigent", "orchestra conductor", "weak noun: den Dirigenten; a ticket inspector is der Schaffner"),
    noun("der", "Konzertsaal", "concert hall"),
    noun("das", "Bühnenbild", "stage set, scenery", "literally 'stage picture'"),
  ]),

  part514: pack("Part 514", "A1", "Verbs of doing and moving", "The physical verbs of hands, feet and voice — everyday actions no theme pack happened to own.", [
    verbFromDe("fangen", "to catch (a ball or animal)", "irregular: fängt, fing, hat gefangen"),
    verbFromDe("schieben", "to push (along)", "einen Einkaufswagen schieben = to push a trolley"),
    verbFromDe("heben", "to lift, raise", "irregular: hob, hat gehoben"),
    verbFromDe("kriechen", "to crawl, creep", "takes sein: ist gekrochen"),
    verbFromDe("hüpfen", "to hop, bounce"),
    verbFromDe("schleichen", "to sneak, creep", "sich anschleichen = to sneak up"),
    verbFromDe("schreien", "to scream, shout", "irregular: schrie, hat geschrien"),
    verbFromDe("weinen", "to cry, weep", "crying tears — shouting is schreien"),
    verbFromDe("lächeln", "to smile"),
    verbFromDe("gähnen", "to yawn"),
    verbFromDe("husten", "to cough"),
    verbFromDe("zittern", "to tremble, shiver", "vor Kälte zittern = to shiver with cold"),
    verbFromDe("umarmen", "to hug, embrace", "not separable: Sie umarmt ihn"),
    verbFromDe("beißen", "to bite", "irregular: biss, hat gebissen"),
    verbFromDe("kauen", "to chew"),
    verbFromDe("schlucken", "to swallow"),
    verbFromDe("riechen", "to smell", "both directions: Ich rieche Kaffee / Das riecht gut"),
    verbFromDe("stinken", "to stink", "irregular: stank, hat gestunken"),
    verbFromDe("leuchten", "to glow, shine", "a lamp leuchtet; the sun scheint"),
    verbFromDe("brennen", "to burn", "irregular: brannte, hat gebrannt; es brennt! = fire!"),
    verbFromDe("schmelzen", "to melt", "irregular: schmilzt, schmolz"),
    verbFromDe("gefrieren", "to freeze (of water)", "a person freezing is frieren"),
    verbFromDe("spritzen", "to splash, spray, squirt"),
    verbFromDe("gießen", "to pour, water (plants)", "Blumen gießen; es gießt = it's pouring"),
    verbFromDe("graben", "to dig", "irregular: gräbt, grub, hat gegraben"),
    verbFromDe("pflanzen", "to plant"),
    verbFromDe("melken", "to milk"),
    verbFromDe("jagen", "to hunt, chase"),
    verbFromDe("angeln", "to fish (with a rod)", "commercial fishing is fischen"),
    verbFromDe("stricken", "to knit"),
    verbFromDe("nähen", "to sew"),
    verbFromDe("fegen", "to sweep", "also kehren in the south"),
    verbFromDe("schrauben", "to screw (with a screwdriver)"),
    verbFromDe("bohren", "to drill", "in der Nase bohren = to pick one's nose"),
    verbFromDe("falten", "to fold"),
    verbFromDe("reißen", "to tear, rip", "irregular: riss, hat gerissen"),
    verbFromDe("biegen", "to bend", "irregular: bog, hat gebogen"),
  ]),

  part515: pack("Part 515", "A1", "How things look, feel and taste", "Sensory adjectives for describing what is in front of you.", [
    adjective("schmutzig", "dirty, grubby"),
    adjective("dreckig", "dirty, filthy", "a shade stronger and more colloquial than schmutzig"),
    adjective("nass", "wet", "klatschnass = soaking wet"),
    adjective("blass", "pale", "blass werden = to go pale"),
    adjective("mild", "mild (of taste or weather)"),
    adjective("faul", "lazy", "also rotten: ein fauler Apfel — and faule Ausreden, lame excuses"),
    adjective("gekocht", "boiled, cooked"),
    adjective("gebraten", "fried, roasted"),
    adjective("eklig", "disgusting, gross"),
    adjective("hübsch", "pretty, cute"),
    adjective("hässlich", "ugly"),
    adjective("dünn", "thin", "of things and people; watery coffee is dünner Kaffee"),
    adjective("schlank", "slim", "the polite word for a slim person"),
    adjective("mager", "lean, skinny, low-fat", "Magerquark = low-fat quark"),
    adjective("fett", "fatty, greasy", "youth slang: fett = awesome; the noun das Fett = fat"),
    adjective("wach", "awake", "hellwach = wide awake"),
    adjective("durstig", "thirsty", "more commonly: Ich habe Durst"),
    adjective("nackt", "naked, bare"),
  ]),

  part516: pack("Part 516", "A2", "Health and at the doctor's", "Symptoms, injuries and the things a German doctor's visit is made of.", [
    noun("das", "Fieber", "fever, temperature", "Fieber messen = to take a temperature"),
    noun("der", "Schnupfen", "runny nose, sniffles"),
    noun("die", "Erkältung", "common cold", "sich erkälten = to catch a cold"),
    noun("die", "Kopfschmerzen", "headache", "always plural: Ich habe Kopfschmerzen"),
    noun("die", "Bauchschmerzen", "stomach ache", "always plural"),
    noun("die", "Halsschmerzen", "sore throat", "always plural"),
    noun("der", "Durchfall", "diarrhoea", "literally 'through-fall'"),
    noun("die", "Verstopfung", "constipation", "also a blocked pipe"),
    noun("das", "Erbrechen", "vomiting", "sich übergeben = to vomit (the polite verb)"),
    noun("der", "Puls", "pulse", "den Puls messen = to take a pulse"),
    noun("das", "Fieberthermometer", "clinical thermometer"),
    noun("das", "Röntgenbild", "X-ray image", "röntgen = to X-ray, after Wilhelm Röntgen"),
    noun("die", "Krücke", "crutch", "usually plural: auf Krücken"),
    noun("der", "Rollstuhl", "wheelchair", "literally 'roll chair'"),
    noun("der", "Impfstoff", "vaccine", "die Impfung = the vaccination"),
    noun("das", "Symptom", "symptom, sign of illness"),
    adjective("bewusstlos", "unconscious", "literally 'consciousness-less'"),
    adjective("verletzt", "injured, hurt", "also feelings: verletzend = hurtful"),
    adjective("gebrochen", "broken (of a bone)", "ein gebrochenes Bein; also gebrochenes Deutsch = broken German"),
    adjective("verstaucht", "sprained", "sich den Knöchel verstauchen"),
  ]),

  part517: pack("Part 517", "A1", "Family ties", "The whole family tree — in-laws, steps, halves and the words for life's married and unmarried states.", [
    noun("der", "Zwilling", "twin", "plural: die Zwillinge; also the star sign Gemini"),
    noun("der", "Säugling", "infant, newborn", "from saugen (to suckle); everyday speech says das Baby"),
    noun("das", "Kleinkind", "toddler", "literally 'small child'"),
    noun("die", "Witwe", "widow"),
    noun("der", "Witwer", "widower"),
    noun("die", "Waise", "orphan", "das Waisenhaus = the orphanage"),
    noun("die", "Patin", "godmother", "the godfather is der Pate"),
    noun("die", "Schwiegermutter", "mother-in-law"),
    noun("der", "Schwiegervater", "father-in-law"),
    noun("die", "Schwiegertochter", "daughter-in-law"),
    noun("der", "Schwiegersohn", "son-in-law"),
    noun("der", "Schwager", "brother-in-law"),
    noun("die", "Schwägerin", "sister-in-law"),
    noun("der", "Neffe", "nephew", "weak noun: den Neffen"),
    noun("die", "Nichte", "niece"),
    noun("die", "Cousine", "cousin (female)", "also die Kusine; the male cousin is der Cousin"),
    noun("die", "Enkelin", "granddaughter", "the grandson is der Enkel"),
    noun("die", "Urgroßmutter", "great-grandmother", "ur- stacks: die Ururgroßmutter"),
    noun("der", "Stiefvater", "stepfather"),
    noun("die", "Stiefmutter", "stepmother", "the fairy-tale villain: die böse Stiefmutter"),
    noun("der", "Halbbruder", "half-brother"),
    noun("die", "Halbschwester", "half-sister"),
    noun("das", "Pflegekind", "foster child", "die Pflegefamilie = the foster family"),
    verbFromDe("adoptieren", "to adopt (a child)"),
    adjective("verlobt", "engaged (to be married)", "sich verloben = to get engaged"),
    noun("die", "Verlobte", "fiancée", "the man is der Verlobte — article does the work"),
    noun("die", "Braut", "bride", "plural: die Bräute"),
    noun("der", "Bräutigam", "groom, bridegroom"),
    noun("der", "Hochzeitstag", "wedding day, wedding anniversary"),
    adjective("geschieden", "divorced", "die Scheidung = the divorce"),
    adjective("verwitwet", "widowed"),
    adjective("ledig", "single, unmarried", "the form-filling word; casually: Ich bin Single"),
    adjective("alleinerziehend", "single-parent", "eine alleinerziehende Mutter"),
  ]),

  part518: pack("Part 518", "A1", "Celebrations and holidays", "Birthdays, Christmas, Easter and the German holiday calendar.", [
    noun("die", "Feier", "celebration, party", "feiern = to celebrate; die Weihnachtsfeier = the Christmas do"),
    noun("die", "Kerze", "candle", "Kerzen ausblasen = to blow out candles"),
    noun("das", "Feuerwerk", "fireworks", "half of Germany sets it off at Silvester"),
    noun("der", "Geburtstagskuchen", "birthday cake"),
    noun("der", "Weihnachtsbaum", "Christmas tree", "also der Tannenbaum"),
    noun("der", "Weihnachtsmann", "Father Christmas, Santa Claus", "in the south the Christkind brings the presents"),
    noun("das", "Geschenkpapier", "wrapping paper"),
    { de: "Ostern", lookup: "Ostern", fallbackEn: "Easter", tip: "noun", use: "article-less like Weihnachten: Frohe Ostern! = Happy Easter" },
    { de: "Neujahr", lookup: "Neujahr", fallbackEn: "New Year's Day", tip: "noun", use: "the evening before is Silvester" },
    noun("der", "Advent", "Advent (the pre-Christmas weeks)", "der Adventskalender counts them down"),
    noun("der", "Nikolaus", "St Nicholas Day (6 December)", "boots out on the 5th, sweets in them on the 6th"),
    noun("der", "Muttertag", "Mother's Day"),
    noun("der", "Vatertag", "Father's Day", "an Ascension-Day tradition involving handcarts and beer"),
    noun("der", "Valentinstag", "Valentine's Day"),
  ]),

  part519: pack("Part 519", "A2", "Materials and metals", "What things are made of — from the toolbox to the building site.", [
    noun("das", "Eisen", "iron (metal)", "the flat-iron is das Bügeleisen"),
    noun("der", "Stahl", "steel"),
    noun("das", "Kupfer", "copper"),
    noun("das", "Silber", "silver", "die Silberhochzeit = the 25th anniversary"),
    noun("das", "Gold", "gold (the metal)", "die Goldene Hochzeit = the 50th anniversary"),
    noun("die", "Bronze", "bronze (metal)", "say brong-suh"),
    noun("das", "Blech", "sheet metal, baking tray", "frisch vom Blech = fresh off the tray"),
    noun("der", "Draht", "wire", "einen guten Draht zu jemandem haben = to have a good rapport"),
    noun("das", "Plastik", "plastic", "the everyday word; the technical one is der Kunststoff"),
    noun("der", "Gummi", "rubber (material)", "das Gummiband = the rubber band"),
    noun("die", "Pappe", "cardboard", "nicht von Pappe = not to be sneezed at"),
    noun("der", "Ziegel", "brick, roof tile"),
    noun("der", "Beton", "concrete (building material)", "say beh-TONG, from French"),
    noun("der", "Zement", "cement"),
    noun("der", "Gips", "plaster, plaster cast", "ein Bein in Gips = a leg in a cast"),
    noun("das", "Porzellan", "porcelain, china"),
    noun("die", "Keramik", "ceramics, pottery"),
    noun("der", "Marmor", "marble (stone)"),
    noun("der", "Granit", "granite", "auf Granit beißen = to hit a brick wall"),
    noun("der", "Kies", "gravel", "also slang for money"),
    noun("der", "Asphalt", "asphalt, tarmac"),
    noun("der", "Teer", "tar"),
    noun("das", "Benzin", "petrol, gasoline"),
    noun("der", "Diesel", "diesel fuel"),
    noun("das", "Gas", "gas (fuel)", "Gas geben = to accelerate, to hurry up"),
    adjective("rostig", "rusty", "der Rost = the rust"),
  ]),

  part520: pack("Part 520", "A1", "Containers and crockery", "What food and drink live in — the cupboard's worth of vessels German kitchens name precisely.", [
    noun("die", "Flasche", "bottle", "also a useless person: Du Flasche!"),
    noun("die", "Tube", "tube (of paste)", "die Tube Zahnpasta"),
    noun("die", "Schachtel", "small box, packet", "eine Schachtel Pralinen = a box of chocolates"),
    noun("der", "Sack", "sack, large bag", "plural: die Säcke"),
    noun("die", "Tüte", "carrier bag, paper bag", "eine Tüte Gummibärchen = a bag of gummy bears"),
    noun("das", "Fass", "barrel, keg", "Bier vom Fass = draught beer; das schlägt dem Fass den Boden aus!"),
    noun("der", "Kanister", "jerry can, canister"),
    noun("die", "Kanne", "teapot, coffee pot", "die Gießkanne = the watering can"),
    noun("der", "Becher", "mug, beaker, tumbler", "der Joghurtbecher = the yoghurt pot"),
    noun("der", "Teller", "plate", "ein Teller Suppe = a plate of soup"),
    noun("die", "Schale", "shallow dish, peel", "one word for a fruit bowl and a banana skin"),
    noun("der", "Henkel", "loop handle (of a mug or bag)", "a door or pan handle is der Griff"),
    noun("der", "Verschluss", "cap, fastener, seal"),
    noun("der", "Korken", "cork (stopper)", "der Korkenzieher pulls it"),
  ]),

  part521: pack("Part 521", "A2", "In the garden", "Beds, buds and the shed full of tools German gardens run on.", [
    noun("die", "Hecke", "hedge"),
    noun("das", "Beet", "flower bed, vegetable patch", "das Hochbeet = the raised bed"),
    noun("das", "Gewächshaus", "greenhouse", "literally 'growth house'"),
    noun("der", "Schuppen", "garden shed", "also, unappetisingly, dandruff"),
    noun("der", "Balkon", "balcony", "say bal-KONG; plural: die Balkone"),
    noun("der", "Blumentopf", "flower pot"),
    noun("der", "Samen", "seed", "plural: die Samen"),
    noun("die", "Knospe", "bud (of a flower)"),
    noun("die", "Blüte", "blossom, bloom", "in voller Blüte = in full bloom"),
    noun("der", "Dorn", "thorn", "plural: die Dornen — keine Rose ohne Dornen"),
    noun("der", "Stachel", "sting, spine, prickle", "bees and hedgehogs have Stacheln"),
    noun("der", "Rasenmäher", "lawnmower", "den Rasen mähen = to mow the lawn"),
    noun("die", "Harke", "rake", "the northern word"),
    noun("der", "Rechen", "rake (southern Germany)", "same tool as die Harke"),
    noun("der", "Spaten", "spade"),
    noun("die", "Schaufel", "shovel, scoop"),
    noun("die", "Schubkarre", "wheelbarrow", "literally 'push cart'"),
    noun("der", "Rasensprenger", "sprinkler (garden)", "literally 'lawn sprayer'"),
    noun("der", "Komposthaufen", "compost heap"),
    noun("das", "Vogelhäuschen", "bird box, bird feeder"),
  ]),

  part522: pack("Part 522", "A2", "Character and personality", "The adjectives Germans reach for when describing what someone is like.", [
    adjective("schüchtern", "shy"),
    adjective("frech", "cheeky, impudent", "frech wie Oskar = cheeky as anything"),
    adjective("höflich", "polite", "die Höflichkeit = politeness"),
    adjective("unehrlich", "dishonest"),
    adjective("eingebildet", "conceited, stuck-up", "also imagined: eine eingebildete Krankheit"),
    adjective("gierig", "greedy", "die Gier = greed"),
    adjective("egoistisch", "selfish"),
    adjective("dickköpfig", "stubborn, pig-headed", "literally 'thick-headed'; also stur"),
    adjective("nachdenklich", "thoughtful, pensive"),
    adjective("unordentlich", "untidy, messy"),
    adjective("unpünktlich", "unpunctual, late", "the cardinal German sin"),
    adjective("unzuverlässig", "unreliable"),
    adjective("fleißig", "hard-working, diligent", "fleißig wie eine Biene"),
    adjective("klug", "clever, smart", "comparative: klüger"),
    adjective("humorvoll", "humorous, full of humour"),
    adjective("charmant", "charming"),
    adjective("langweilig", "boring", "die Langeweile = boredom"),
    adjective("lebhaft", "lively, vivacious"),
  ]),

  part523: pack("Part 523", "A1", "Countries and languages", "Where people are from and what they speak — the names German gives the world.", [
    { de: "Polen", lookup: "Polen", fallbackEn: "Poland", tip: "noun", use: "the neighbour to the east; polnisch = Polish" },
    { de: "Russland", lookup: "Russland", fallbackEn: "Russia", tip: "noun" },
    { de: "die Türkei", lookup: "Türkei", fallbackEn: "Turkey (country)", tip: "noun", article: "die", use: "one of the few countries with an article: in der Türkei" },
    { de: "die Niederlande", lookup: "Niederlande", fallbackEn: "the Netherlands", tip: "noun", article: "die", use: "plural with article: in den Niederlanden" },
    { de: "Norwegen", lookup: "Norwegen", fallbackEn: "Norway", tip: "noun" },
    { de: "Tschechien", lookup: "Tschechien", fallbackEn: "Czechia, the Czech Republic", tip: "noun" },
    { de: "Ungarn", lookup: "Ungarn", fallbackEn: "Hungary", tip: "noun" },
    { de: "Schottland", lookup: "Schottland", fallbackEn: "Scotland", tip: "noun" },
    { de: "Amerika", lookup: "Amerika", fallbackEn: "America", tip: "noun", use: "the USA is die USA: in den USA" },
    { de: "Kanada", lookup: "Kanada", fallbackEn: "Canada", tip: "noun" },
    { de: "Mexiko", lookup: "Mexiko", fallbackEn: "Mexico", tip: "noun" },
    { de: "Brasilien", lookup: "Brasilien", fallbackEn: "Brazil", tip: "noun" },
    { de: "Australien", lookup: "Australien", fallbackEn: "Australia", tip: "noun" },
    { de: "Ägypten", lookup: "Ägypten", fallbackEn: "Egypt", tip: "noun" },
    adjective("spanisch", "Spanish", "the language: Spanisch, capitalised"),
    adjective("polnisch", "Polish (from Poland)"),
    adjective("türkisch", "Turkish"),
    adjective("griechisch", "Greek"),
    adjective("niederländisch", "Dutch", "the language is also called Holländisch colloquially"),
    adjective("japanisch", "Japanese"),
    adjective("arabisch", "Arabic, Arab"),
  ]),

  part524: pack("Part 524", "A2", "Saying it out loud", "Verbs for how people talk — from whispering to whining — plus the audio gear it happens through.", [
    verbFromDe("plaudern", "to chat, natter", "ein Plauderton = a chatty tone"),
    verbFromDe("schweigen", "to stay silent", "irregular: schwieg, hat geschwiegen; das Schweigen = the silence"),
    verbFromDe("murmeln", "to mumble, murmur"),
    verbFromDe("stottern", "to have a stutter, stammer", "of speech; a lagging game ruckelt"),
    verbFromDe("jammern", "to whine, moan", "hör auf zu jammern = stop moaning"),
    verbFromDe("sich beklagen", "to complain, lament", "sich beklagen über + accusative"),
    verbFromDe("beschimpfen", "to call someone names, hurl insults at"),
    verbFromDe("schwören", "to vow, swear an oath", "irregular: schwor, hat geschworen; Ich schwöre! = I swear!"),
    verbFromDe("trösten", "to comfort, console", "der Trost = consolation"),
    verbFromDe("ermutigen", "to encourage", "der Mut = courage"),
    verbFromDe("sich entschuldigen", "to apologise", "sich bei jemandem entschuldigen = to apologise to someone"),
    verbFromDe("sich bedanken", "to say thank you", "sich bei jemandem bedanken = to thank someone"),
    verbFromDe("duzen", "to use du with someone", "the informal you — offered, not assumed"),
    verbFromDe("siezen", "to use Sie with someone", "the polite you — the safe default with strangers"),
    noun("der", "Kopfhörer", "headphones", "usually plural: die Kopfhörer"),
    noun("der", "Lautsprecher", "loudspeaker, speaker", "literally 'loud speaker'"),
    noun("die", "Speicherkarte", "memory card"),
    noun("die", "E-Mail", "email", "feminine; in the south sometimes das E-Mail"),
  ]),

  part525: pack("Part 525", "B1", "Feelings by name", "The nouns for what you feel — grief to glee, named the way Germans name them.", [
    noun("die", "Trauer", "grief, mourning", "in Trauer sein = to be in mourning"),
    noun("die", "Wut", "anger, fury", "eine Wut im Bauch haben = to be seething"),
    noun("der", "Zorn", "wrath, deep anger", "the elevated, biblical register of Wut"),
    noun("der", "Hass", "hatred, hate", "hassen = to hate"),
    noun("die", "Furcht", "fear (formal register)", "everyday speech says die Angst"),
    noun("die", "Panik", "panic", "Keine Panik! = don't panic!"),
    noun("das", "Mitleid", "pity, sympathy", "Mitleid haben mit = to feel sorry for"),
    noun("die", "Langeweile", "boredom", "literally 'long while'"),
    noun("die", "Begeisterung", "enthusiasm, excitement", "begeistert = thrilled"),
    noun("die", "Zufriedenheit", "contentment, satisfaction"),
    noun("die", "Einsamkeit", "loneliness, solitude"),
    noun("das", "Misstrauen", "distrust, suspicion", "the opposite of das Vertrauen"),
    noun("die", "Feigheit", "cowardice", "feige = cowardly"),
    noun("die", "Ungeduld", "impatience", "vor Ungeduld = with impatience"),
    noun("der", "Ärger", "annoyance, trouble", "Ärger machen = to cause trouble"),
    noun("der", "Frust", "frustration", "colloquial for die Frustration; Frust schieben = to be frustrated"),
  ]),

  part526: pack("Part 526", "A2", "Money in hand", "Coins, notes, rates and receipts — the money words of an ordinary week.", [
    noun("das", "Kleingeld", "small change, coins", "Haben Sie es passend? = do you have exact change?"),
    noun("die", "Münze", "coin"),
    noun("der", "Geldschein", "banknote, bill", "often just der Schein"),
    noun("der", "Schein", "banknote, certificate", "also appearance: der Schein trügt = looks deceive"),
    noun("die", "Zinsen", "interest on money", "always plural in this sense"),
    noun("das", "Taschengeld", "pocket money, allowance", "literally 'pocket money'"),
    noun("das", "Preisschild", "price tag"),
    noun("die", "Quittung", "receipt (official)", "also comeuppance: die Quittung bekommen"),
    noun("der", "Rabattcode", "discount code, voucher code"),
    noun("die", "Gutschrift", "credit note, refunded credit"),
    noun("die", "Währung", "currency", "eine stabile Währung = a stable currency"),
    noun("der", "Wechselkurs", "exchange rate"),
    noun("die", "Ersparnis", "saving, savings", "plural: die Ersparnisse = one's savings"),
  ]),

  part527: pack("Part 527", "A2", "Weights and measures", "Spoons, litres and kilometres — how German measures the everyday.", [
    noun("die", "Viertelstunde", "quarter of an hour", "eine Viertelstunde = fifteen minutes"),
    noun("der", "Esslöffel", "tablespoon", "recipes abbreviate it EL"),
    noun("der", "Teelöffel", "teaspoon", "recipes abbreviate it TL"),
    noun("der", "Liter", "litre"),
    noun("der", "Milliliter", "millilitre"),
    noun("das", "Gramm", "gram", "100 Gramm = a common deli order"),
    noun("das", "Kilogramm", "kilogram", "usually just das Kilo"),
    noun("der", "Meter", "metre"),
    noun("der", "Millimeter", "millimetre"),
    noun("der", "Kilometer", "kilometre", "abbreviated km, said 'kah-em'"),
    noun("die", "Breite", "width, breadth"),
    noun("die", "Länge", "length", "sich in die Länge ziehen = to drag on"),
  ]),

  part528: pack("Part 528", "A2", "Screen, stage and page", "Films, theatre and books — the words of an evening's entertainment.", [
    noun("die", "Nachrichten", "news broadcast, the news", "always plural; one piece of news is die Nachricht"),
    noun("die", "Komödie", "comedy (film or play)"),
    noun("der", "Krimi", "crime story, detective show", "Germany's favourite genre — see Tatort"),
    noun("das", "Plakat", "poster, billboard"),
    noun("der", "Regisseur", "film director", "say re-zhi-SUR, from French"),
    noun("die", "Synchronisation", "dubbing (of films)", "Germany dubs almost everything; die Synchronstimme = the dubbed voice"),
    noun("die", "Eintrittskarte", "admission ticket", "der Eintritt = admission"),
    noun("der", "Applaus", "applause", "Applaus spenden = to applaud"),
    noun("das", "Gedicht", "poem", "ein Gedicht aufsagen = to recite a poem"),
    noun("das", "Märchen", "fairy tale", "erzähl keine Märchen = don't tell stories"),
    noun("die", "Sage", "legend, saga", "die Nibelungensage"),
    noun("das", "Lesezeichen", "bookmark", "in books and browsers alike"),
  ]),

  part529: pack("Part 529", "A2", "Cooking verbs", "What recipes tell you to do — stir, season, fry and freeze, in the words German recipes actually use.", [
    verbFromDe("grillen", "to barbecue, grill"),
    verbFromDe("dünsten", "to steam-cook, braise gently"),
    verbFromDe("rühren", "to stir", "auch: umrühren; rührend = touching (emotionally)"),
    verbFromDe("hacken", "to chop finely", "gehackte Zwiebeln = chopped onions; also to hack a computer"),
    verbFromDe("reiben", "to grate, rub", "irregular: rieb, hat gerieben; die Reibe does it"),
    verbFromDe("salzen", "to salt, add salt"),
    verbFromDe("pfeffern", "to pepper, add pepper", "gepfeffert also means steep: gepfefferte Preise"),
    verbFromDe("servieren", "to serve (food)"),
    verbFromDe("auftauen", "to defrost, thaw", "separable: taut auf; also people warming up socially"),
    verbFromDe("einfrieren", "to put in the freezer, freeze food", "separable: friert ein"),
    verbFromDe("erhitzen", "to heat up (in cooking)", "Öl erhitzen = to heat oil"),
    verbFromDe("abkühlen", "to cool down", "separable: kühlt ab — cakes and tempers alike"),
    verbFromDe("marinieren", "to marinate"),
    verbFromDe("panieren", "to bread, coat in breadcrumbs", "what makes a Schnitzel a Schnitzel"),
    verbFromDe("garnieren", "to garnish"),
    verbFromDe("übergießen", "to pour over", "mit Brühe übergießen = to pour stock over"),
    verbFromDe("abtropfen", "to drain (let drip off)", "Nudeln abtropfen lassen = to drain pasta"),
    verbFromDe("pürieren", "to purée, blend smooth"),
    verbFromDe("vermischen", "to mix together, combine"),
    verbFromDe("bestreichen", "to spread onto, brush with", "mit Butter bestreichen = to spread with butter"),
    verbFromDe("bestreuen", "to sprinkle with", "mit Zucker bestreuen = to sprinkle with sugar"),
  ]),

  part530: pack("Part 530", "A1", "Shapes, sides and directions", "Squares and spheres, front and back, above and below — how German places things in space.", [
    noun("das", "Quadrat", "square (shape)", "quadratisch = square-shaped"),
    noun("das", "Dreieck", "triangle", "literally 'three-corner'"),
    noun("das", "Rechteck", "rectangle", "literally 'right-angle corner'"),
    noun("die", "Kugel", "sphere, ball (solid)", "also a scoop of ice cream: eine Kugel Vanille"),
    noun("die", "Kante", "sharp edge, corner edge", "Ecken und Kanten = rough edges"),
    noun("die", "Vorderseite", "front side, front face"),
    noun("die", "Rückseite", "back side, reverse", "siehe Rückseite = see reverse"),
    noun("die", "Innenseite", "inside surface, inner side"),
    noun("die", "Außenseite", "outside surface, outer side"),
    adverb("vorne", "at the front", "nach vorne = to the front; da vorne = up ahead"),
    adverb("hinten", "at the back", "nach hinten = backwards; da hinten = back there"),
    adverb("innen", "on the inside", "innen und außen = inside and out"),
    adverb("außen", "on the outside"),
    adverb("dazwischen", "in between", "literally 'there-between'"),
    adverb("oberhalb", "above, upstream of", "takes genitive: oberhalb der Tür"),
    adverb("unterhalb", "below, beneath", "takes genitive: unterhalb des Fensters"),
    adjective("quer", "across, sideways", "quer durch die Stadt = right across town"),
    adjective("senkrecht", "vertical, upright"),
    adjective("waagerecht", "horizontal, level", "die Waage = the scales"),
  ]),

  part531: pack("Part 531", "A1", "The daily routine", "Waking, washing, dressing, driving — the verbs a normal day is built from.", [
    verbFromDe("aufstehen", "to get up", "separable: steht auf, ist aufgestanden"),
    verbFromDe("sich anziehen", "to get dressed", "irregular: zog an, hat angezogen"),
    verbFromDe("sich ausziehen", "to get undressed", "also to move out of a flat: ausziehen"),
    verbFromDe("sich umziehen", "to get changed (clothes)", "without sich, umziehen means to move house"),
    verbFromDe("sich waschen", "to wash (oneself)", "irregular: wäscht, wusch, hat gewaschen"),
    verbFromDe("duschen", "to shower, have a shower", "also sich duschen — both are right"),
    verbFromDe("baden", "to have a bath, bathe", "also swimming outdoors: baden gehen — which also means to flop"),
    verbFromDe("sich schminken", "to put on make-up"),
    verbFromDe("sich rasieren", "to shave"),
    verbFromDe("frühstücken", "to have breakfast", "one verb for the whole meal"),
    verbFromDe("putzen", "to clean (the house)", "Zähne putzen = to brush teeth; die Putzfrau cleans"),
    verbFromDe("staubsaugen", "to vacuum, hoover", "der Staubsauger = the vacuum cleaner"),
    verbFromDe("tanken", "to fill up with fuel", "auch figurativ: Energie tanken = to recharge"),
    verbFromDe("parken", "to park (a car)"),
    verbFromDe("abbiegen", "to turn off (when driving)", "separable: biegt ab, ist abgebogen; links abbiegen"),
    verbFromDe("einsteigen", "to get in, board", "separable: steigt ein, ist eingestiegen"),
    verbFromDe("aussteigen", "to get out, get off", "also to drop out of a career or deal"),
    verbFromDe("sich beeilen", "to hurry up", "Beeil dich! = hurry up!"),
  ]),

  part532: pack("Part 532", "A1", "Weather in motion", "What the sky actually does — the verbs and adjectives of every German weather chat.", [
    verbFromDe("regnen", "to rain", "es regnet in Strömen = it's pouring"),
    verbFromDe("schneien", "to snow"),
    verbFromDe("hageln", "to hail", "es hagelt Kritik = criticism rains down"),
    verbFromDe("donnern", "to thunder", "also to thunder along a road"),
    verbFromDe("blitzen", "to flash with lightning", "geblitzt werden = to be caught by a speed camera"),
    verbFromDe("stürmen", "to be stormy, storm", "es stürmt; also to storm a goal or a building"),
    verbFromDe("wehen", "to blow (of wind)", "der Wind weht"),
    verbFromDe("tauen", "to thaw, melt away", "es taut = the snow is melting"),
    adjective("bewölkt", "cloudy, overcast", "stark bewölkt = heavily overcast"),
    adjective("regnerisch", "rainy"),
    adjective("windig", "windy", "also a shady character: eine windige Type"),
    adjective("neblig", "foggy, misty"),
    adjective("eisig", "icy, freezing cold", "also an icy silence: eisiges Schweigen"),
    adjective("wechselhaft", "changeable (of weather)", "the forecaster's favourite word"),
    adjective("heiter", "bright and dry, fair skies", "of people: cheerful; aus heiterem Himmel = out of the blue"),
  ]),

  part533: {
    label: "Part 533",
    level: "A1",
    theme: "Building blocks",
    description: "Short complete sentences that longer course sentences grow from — learn the core, then meet it again with one more idea attached.",
    focus: "Leon's repetition principle: learn the smallest sentence that makes sense on its own, then extend it. Every phrase here is a verbatim prefix of longer course sentences, so the chain machinery serves the pair together.",
    seeds: [],
    dialogues: [],
    phrases: [
      { de: "Wie geht es?", en: "How's it going?", short: "Wie geht's?", shortEn: "How's it going?", use: "The bare frame; with a person it becomes Wie geht es dir/Ihnen?" },
      { de: "Wie sagt man das?", en: "How do you say that?", use: "Add auf Deutsch to ask for the German word." },
      { de: "Ein bisschen langsamer.", en: "A little slower.", use: "Softer with bitte on the end." },
      { de: "Wie lange machst du das?", en: "How long are you doing that for?", use: "With schon it asks how long ALREADY: Wie lange machst du das schon?" },
      { de: "Ich brauche das.", en: "I need that.", short: "Ich brauch das.", shortEn: "I need that.", use: "In speech the -e drops: Ich brauch das." },
      { de: "Was machst du?", en: "What are you doing?", use: "With beruflich it asks about work; with genau it asks for detail." },
      { de: "Ich arbeite.", en: "I'm working.", use: "Grows naturally: in der Stadt, als Lehrer, von zu Hause." },
      { de: "Passt das?", en: "Does that work?", use: "Checking a time or plan; für dich makes it personal." },
      { de: "Wie heißt das?", en: "What's that called?", use: "Point at anything. Wie heißt das Ding da? for the thing over there." },
      { de: "Verstehst du?", en: "Do you understand?", use: "Casual check-in mid-explanation." },
      { de: "Das kann ich.", en: "I can do that.", use: "Confident and short; the verb arrives later: Das kann ich verstehen." },
      { de: "Das geht.", en: "That works.", use: "Also 'that's acceptable'; Das geht nicht = that won't do." },
      { de: "Das kenn ich.", en: "I know that one.", long: "Das kenne ich.", use: "For things familiar to you — kennen, not wissen." },

      /* The second batch, chosen by counting what the catalogue actually grows
         from rather than by guessing. "Ich weiß." alone is the opening of 140
         longer sentences, "Ich kann." of 122 — every one of those is a lesson
         where the words are already half known. Leon asked for two of these by
         name after meeting the long forms cold: "surely before [Ich geh gerne
         ins Kino] we could have [Wir können das nicht] and [I like going]". */

      // Knowing, thinking, hoping
      { de: "Ich weiß.", en: "I know.", use: "For facts. Knowing a person or a place is kennen: Ich kenne ihn." },
      // Glossed "I see." until the collision turned up: "I understand" is the
      // better gloss, because "I see" belongs to sehen. This pack made it worse
      // than a general risk. Ich sehe das. sits
      // seven cards below glossed "I see it that way.", and the card directly
      // under this one already says "I don't understand." So the prompt "I
      // see." asked for verstehen while its own neighbours taught sehen for
      // the same English. The idiom is real and stays in the note; the prompt
      // has to name the verb it wants.
      { de: "Ich verstehe.", en: "I understand.", use: "English usually says 'I see' here. Says you followed it, not that you agree." },
      { de: "Ich verstehe nicht.", en: "I don't understand.", use: "Add das to point at the specific thing: Ich verstehe das nicht." },
      { de: "Ich denke schon.", en: "I think so.", use: "schon is what completes it — bare 'Ich denke' or 'Ich glaube' trails off. With a comma it carries the thought instead: Ich denke, das stimmt." },
      { de: "Ich denke nach.", en: "I'm thinking about it.", use: "nachdenken is thinking something OVER. Bare 'Ich denke' does not mean this — it opens an opinion: Ich denke, das stimmt." },
      { de: "Ich hoffe es.", en: "I hope so.", use: "The es is what makes it a complete reply. With a comma comes the wish instead: Ich hoffe, es klappt." },
      { de: "Ich sehe das.", en: "I see it that way.", use: "Not eyesight — this is how you view something. Ich sehe das anders = I disagree." },

      // Can, must, want
      { de: "Ich kann.", en: "I can.", use: "A complete answer to Kannst du? The verb is left off once it is obvious." },
      { de: "Ich kann nicht.", en: "I can't.", use: "The blunt refusal. Ich kann nicht mehr = I've had enough." },
      { de: "Ich kann das nicht.", en: "I can't do that.", use: "Now it is THAT you can't do, not everything." },
      { de: "Wir können das nicht.", en: "We can't do that.", use: "Same sentence, shared: können is the wir form of kann." },
      { de: "Ich muss.", en: "I have to.", use: "German drops the obvious verb; English needs 'to'." },
      { de: "Ich muss noch was erledigen.", en: "I've still got things to do.", use: "etwas erledigen = to get things done. Bare 'Ich muss noch' stops mid-thought and needs what follows." },
      { de: "Ich will nicht.", en: "I don't want to.", use: "Blunt. Ich möchte nicht is the polite version." },
      { de: "Ich will das nicht.", en: "I don't want that.", use: "Pointing at the thing you are refusing." },
      { de: "Ich möchte das.", en: "I'd like that.", use: "möchte is the polite want — what you order with." },
      { de: "Ich möchte nicht.", en: "I'd rather not.", use: "Softer refusal than Ich will nicht." },

      // Having and doing
      { de: "Ich habe das.", en: "I've got that.", use: "Answers Hast du das? Spoken you'll hear Ich hab das." },
      { de: "Ich habe es.", en: "I've got it.", use: "es for something already named; das for something pointed at." },
      { de: "Ich mache das.", en: "I'll do that.", use: "Taking the job on. Ich mache das gleich = I'll do it right away." },
      { de: "Ich mache das nicht.", en: "I'm not doing that.", use: "A refusal of the task, not of the person." },
      { de: "Wir haben das.", en: "We have that.", use: "In a shop it means it's in stock." },
      { de: "Wir gehen.", en: "We're going.", use: "German present tense covers 'we go' and 'we are going'." },
      { de: "Ich gehe gerne.", en: "I like going.", use: "gerne after the verb turns doing into liking to do. Spoken: Ich geh gerne." },

      // Naming the thing in front of you
      { de: "Das ist es.", en: "That's it.", use: "The moment something is right. Das ist es nicht = that's not it." },
      { de: "Das ist gut.", en: "That's good.", use: "Plain approval — of a plan, a meal, anything." },
      { de: "Es ist gut.", en: "It's fine.", use: "Closer to 'that'll do' than to praise." },
      { de: "Es geht.", en: "It's OK.", use: "The honest answer to Wie geht's? — not great, not bad." },

      // Asking
      { de: "Hast du das?", en: "Have you got that?", use: "du for a friend; Haben Sie das? in a shop." },
      { de: "Kann ich das?", en: "Can I do that?", use: "Asking permission or ability — German does not separate them here." },
      { de: "Können Sie das?", en: "Can you do that?", use: "The Sie form, for anyone you would not call du." },
      { de: "Willst du das?", en: "Do you want that?", use: "Direct. Möchtest du das? is the polite one." },
      { de: "Was ist das?", en: "What's that?", use: "The single most useful question there is. Point and ask." },
      { de: "Wo ist das?", en: "Where is that?", use: "For a place you cannot find. Wo ist das Fundbüro? = where's lost property?" },
      { de: "Gibt es das?", en: "Is there such a thing?", use: "es gibt = there is / there are, whatever follows." },
      { de: "Ist das alles?", en: "Is that all?", use: "At a counter it asks whether you want anything else." },
    ],
  },

  /**
   * Asking a partner how they are and what they are doing is a daily
   * conversation with almost no cards behind it. The course already had the
   * greeting version — Wie geht's dir?, Alles klar? — but almost nothing for the rest of the
   * day: the midday text, the are-you-eating question, the one you send when
   * she has gone quiet. Everything here is du, because that is who it is for.
   */
  part534: {
    label: "Part 534",
    level: "A1",
    theme: "Checking in on each other",
    description: "The messages you send someone you love during the day — what are you doing, how did it go, have you eaten, are you okay.",
    focus: "Asking after someone across a whole day rather than only greeting them. Grouped by the moment you would send it: right now, the day, how she is, looking after her, and the replies to expect back.",
    seeds: [],
    dialogues: [],
    phrases: [
      // Right now
      { de: "Was machst du gerade?", en: "What are you doing right now?", use: "gerade = right now. Probably the most-sent message in German." },
      { de: "Was machst du so?", en: "What are you up to?", use: "so makes it idle curiosity rather than an interrogation." },
      { de: "Bist du wach?", en: "Are you awake?", use: "The first message of the morning." },
      { de: "Bist du noch wach?", en: "Are you still awake?", use: "noch = still. The late-night version." },
      { de: "Störe ich?", en: "Am I interrupting?", use: "Literally 'am I disturbing'. Opens a call she might not have time for." },
      { de: "Hast du kurz Zeit?", en: "Have you got a minute?", use: "kurz does a lot of work here — it promises you won't take long." },
      { de: "Soll ich dich anrufen?", en: "Shall I call you?", use: "soll ich = shall I. Offering, not asking permission." },
      { de: "Bist du beschäftigt?", en: "Are you busy?", use: "Störe ich? is the softer way to ask the same thing." },

      // How the day is going
      { de: "Wie läuft dein Tag?", en: "How's your day going?", use: "laufen for how something is going — no running involved." },
      { de: "Wie war dein Tag bisher?", en: "How's your day been so far?", use: "bisher = so far, up to now." },
      { de: "Was hast du heute gemacht?", en: "What did you do today?", use: "The evening question. Perfect tense, formed with haben." },
      { de: "Was machst du heute Abend?", en: "What are you doing this evening?", use: "heute Abend is one unit — today-evening." },
      { de: "Wann bist du fertig?", en: "When do you finish?", use: "fertig = done — with work, with a job, with anything." },
      { de: "Wann kommst du nach Hause?", en: "When are you coming home?", use: "nach Hause for going home; zu Hause for being there." },
      { de: "Bist du schon zu Hause?", en: "Are you home yet?", use: "schon = yet. zu Hause here, because she'd already be there." },
      { de: "Kommst du gut durch den Tag?", en: "Are you getting through the day okay?", use: "For a day you both knew was going to be hard." },
      { de: "Wie war's?", en: "How was it?", long: "Wie war es?", use: "Ask it straight after anything — the evening, the appointment, the call." },
      { de: "Wie ist es gelaufen?", en: "How did it go?", use: "For something with an outcome: an exam, an interview, a difficult talk." },
      { de: "Wie war dein Termin?", en: "How was your appointment?", use: "der Termin is any booked slot — doctor, hairdresser, meeting." },

      // How she actually is
      { de: "Wie fühlst du dich?", en: "How are you feeling?", use: "Asks about her state. Wie geht's dir? is closer to a greeting." },
      { de: "Geht's dir besser?", en: "Are you feeling better?", long: "Geht es dir besser?", use: "After illness, or after a day that went badly." },
      { de: "Hast du gut geschlafen?", en: "Did you sleep well?", use: "Once you're both up it shortens to Gut geschlafen?" },
      { de: "Bist du müde?", en: "Are you tired?", use: "Müde covers sleepy and worn out both." },
      { de: "Du klingst müde.", en: "You sound tired.", use: "klingen = to sound. On the phone; Du siehst müde aus for how she looks." },
      { de: "Du bist so still heute.", en: "You're so quiet today.", use: "An opening, not an accusation. It leaves room for her to say why." },
      { de: "Alles in Ordnung?", en: "Everything alright?", use: "A shade more serious than Alles klar? — you've noticed something." },
      { de: "Stimmt was nicht?", en: "Is something wrong?", long: "Stimmt etwas nicht?", use: "Gentler than Was ist los? — it asks rather than demands." },
      { de: "Willst du drüber reden?", en: "Do you want to talk about it?", long: "Willst du darüber reden?", use: "Spoken German shortens darüber to drüber constantly." },
      { de: "Erzähl mal.", en: "Tell me about it.", use: "mal takes the edge off an imperative — an invitation, not an order." },

      // Looking after her
      { de: "Hast du schon gegessen?", en: "Have you eaten yet?", use: "Asked far more often in German than the English is in English." },
      { de: "Hast du genug getrunken?", en: "Have you had enough to drink?", use: "Germans genuinely do ask each other this." },
      { de: "Brauchst du was?", en: "Do you need anything?", long: "Brauchst du etwas?", use: "was is the everyday spoken form of etwas." },
      { de: "Ruh dich aus.", en: "Get some rest.", use: "sich ausruhen is reflexive — the dich is not optional." },
      { de: "Schlaf gut.", en: "Sleep well.", use: "Schlaf schön is just as common and a shade warmer." },
      { de: "Ich hab an dich gedacht.", en: "I was thinking about you.", long: "Ich habe an dich gedacht.", use: "denken AN someone — the an is what makes it about a person. Often the whole reason for the message." },
      { de: "Ich wollte nur hören, wie's dir geht.", en: "I just wanted to hear how you're doing.", use: "The reason for the message, said out loud. wollte = wanted." },
      { de: "Melde dich, wenn du reden willst.", en: "Get in touch if you want to talk.", use: "sich melden = to get in touch, and it always needs its dich." },
      { de: "Schreib mir, wenn du da bist.", en: "Text me when you get there.", use: "schreiben covers texting. da = there, wherever she's heading." },
      { de: "Sag Bescheid, wenn du losfährst.", en: "Let me know when you set off.", use: "Bescheid sagen = to let someone know; losfahren = to set off by car or train." },

      // What comes back
      { de: "Mir geht's gut.", en: "I'm good.", long: "Mir geht es gut.", use: "mir, not ich — German says it goes well TO me." },
      { de: "Mir geht's nicht so gut.", en: "I'm not doing great.", use: "nicht so gut is understatement; it can mean quite bad." },
      { de: "Alles gut, und bei dir?", en: "All good, and you?", use: "bei dir = at your end. Hands the question straight back." },
      { de: "Bin unterwegs.", en: "I'm on my way.", long: "Ich bin unterwegs.", use: "Dropping the ich is normal in texts." },
      { de: "Bin gleich da.", en: "I'll be there in a minute.", long: "Ich bin gleich da.", use: "gleich = in a moment, shortly." },
    ],
  },


  /* Four packs of everyday things the course turned out not to name, found by
     testing a hundred candidate words against the whole catalogue rather than
     guessing at gaps. Tools and office vocabulary came back fully covered and
     are not repeated here; what was missing was scattered — the bathroom, the
     things you pack, small children, and the odds and ends in a drawer. */

  part535: pack("Part 535", "A1", "The bathroom and the bedroom", "The room you start the day in and the room you end it in.", [
    noun("das", "Shampoo", "shampoo"),
    noun("das", "Duschgel", "shower gel"),
    noun("das", "Waschbecken", "washbasin", "the kitchen one is die Spüle"),
    noun("die", "Dusche", "shower", "duschen = to have a shower"),
    noun("die", "Badewanne", "bathtub"),
    noun("die", "Toilette", "toilet", "das Klo in relaxed speech"),
    noun("das", "Deo", "deodorant", "short for das Deodorant"),
    noun("die", "Creme", "cream", "for skin; whipped cream is die Sahne"),
    noun("die", "Nagelschere", "nail scissors"),
    noun("die", "Pinzette", "tweezers"),
    noun("der", "Nachttisch", "bedside table"),
    noun("der", "Teppich", "carpet", "a small one is der Läufer"),
    noun("die", "Lampe", "lamp"),
    noun("der", "Sessel", "armchair", "the sofa is das Sofa or die Couch"),
    noun("der", "Hocker", "stool", "no back — that is what makes it a Hocker"),
    noun("das", "Fensterbrett", "windowsill"),
  ]),

  part536: pack("Part 536", "A2", "Getting out and getting there", "What you pack, what you catch, and the signs you want to have read before you need them.", [
    noun("der", "Koffer", "suitcase"),
    noun("das", "Gepäck", "luggage", "no plural — always singular in German"),
    noun("das", "Hotel", "hotel"),
    noun("die", "Sonnencreme", "sun cream"),
    noun("der", "Reiseführer", "guidebook", "also the human guide"),
    noun("der", "Sitzplatz", "seat", "the reserved kind; a chair is der Stuhl"),
    noun("der", "Abflug", "departure", "of a plane; a train leaving is die Abfahrt"),
    noun("der", "Fahrplan", "timetable", "for trains and buses"),
    noun("die", "Rückfahrkarte", "return ticket", "one-way is die einfache Fahrt"),
    noun("die", "Brieftasche", "wallet", "das Portemonnaie is just as common"),
    noun("der", "Schlüsselbund", "keyring"),
    noun("der", "Rauch", "smoke", "rauchen = to smoke"),
    noun("die", "Warnung", "warning"),
    noun("der", "Notausgang", "emergency exit", "die Not = emergency, distress"),
    noun("der", "Feuerlöscher", "fire extinguisher", "löschen = to put out"),
    noun("der", "Schatten", "shade", "the same word does shadow"),
    noun("der", "Sonnenschein", "sunshine"),
    noun("der", "Windstoß", "gust of wind"),
  ]),

  part537: pack("Part 537", "A2", "Little ones and their things", "The vocabulary of a house with a small child in it.", [
    noun("der", "Schnuller", "dummy", "pacifier in American English"),
    noun("der", "Kinderwagen", "pram", "the buggy kind is der Buggy"),
    noun("die", "Rassel", "rattle"),
    noun("die", "Wiege", "cradle"),
    noun("das", "Spielzeug", "toy", "usually singular for toys in general"),
    noun("der", "Hochstuhl", "high chair"),
    noun("der", "Buntstift", "coloured pencil", "bunt = colourful"),
    noun("die", "Knete", "play dough", "kneten = to knead"),
    noun("das", "Schaukelpferd", "rocking horse", "schaukeln = to swing, to rock"),
  ]),

  part538: pack("Part 538", "A2", "Small things around the house", "The drawer things — nameable, forgettable, and awkward to mime.", [
    noun("der", "Strohhalm", "drinking straw", "das Stroh = straw, the stuff"),
    noun("der", "Untersetzer", "coaster"),
    noun("der", "Eiswürfel", "ice cube", "der Würfel = cube, and also dice"),
    noun("die", "Zuckerdose", "sugar bowl"),
    noun("das", "Gewürz", "spice"),
    noun("das", "Backpulver", "baking powder"),
    noun("der", "Puderzucker", "icing sugar"),
    noun("der", "Fäustling", "mitten", "die Faust = fist; usually worn in pairs"),
    noun("der", "Aschenbecher", "ashtray", "die Asche = ash"),
    noun("das", "Notizbuch", "notebook", "the paper kind"),
  ]),

  part475: pack("Part 475", "A2", "Weather, seasons and spans of time", "Weather worth remarking on, and the words for stretches of time bigger than a week.", [
    noun("der", "Frühling", "spring (season)", "also das Frühjahr"),
    adjective("sommerlich", "summery"),
    adjective("winterlich", "wintry"),
    adjective("herbstlich", "autumnal"),
    noun("der", "Nebel", "fog, mist"),
    noun("der", "Frost", "frost"),
    noun("der", "Tau", "dew", "the rope is das Tau — the article decides"),
    noun("das", "Eis", "ice", "also ice cream — context decides"),
    noun("der", "Schnee", "snow", "Schnee von gestern = water under the bridge"),
    noun("die", "Schneeflocke", "snowflake"),
    noun("der", "Schneemann", "snowman"),
    noun("der", "Orkan", "hurricane-force storm", "a severe der Sturm"),
    noun("das", "Erdbeben", "earthquake", "literally 'earth quaking'"),
    noun("die", "Kältewelle", "cold snap, cold wave", "counterpart of die Hitzewelle"),
    noun("die", "Dämmerung", "twilight, dusk, dawn", "die Morgendämmerung / die Abenddämmerung"),
    noun("der", "Sonnenaufgang", "sunrise", "aufgehen = to rise (of the sun)"),
    noun("der", "Mittag", "midday, noon", "zu Mittag essen = to have lunch"),
    noun("der", "Augenblick", "moment, instant", "Einen Augenblick, bitte! = one moment, please"),
    noun("der", "Zeitraum", "period of time, timespan"),
    noun("das", "Jahrzehnt", "decade"),
    noun("das", "Jahrhundert", "century"),
    noun("das", "Jahrtausend", "millennium"),
    noun("das", "Schaltjahr", "leap year", "literally 'switch year'"),
    noun("die", "Ewigkeit", "eternity", "Das dauert ja eine Ewigkeit! = this is taking forever!"),
    adverb("vorgestern", "the day before yesterday"),
    adverb("übermorgen", "the day after tomorrow"),
    adverb("damals", "back then, in those days"),
  ]),
};
