import type { Blueprint } from "./types";

/**
 * Larger topic expansions live separately from the original numbered course
 * file so adding a new pack never changes the index-based progress IDs of an
 * existing phrase. Keep new packs append-only once they have shipped.
 */
export const expansionPartBlueprints: Record<string, Blueprint> = {
  part151: {
    label: "Part 151",
    level: "B1",
    theme: "Online safety, scams and account recovery",
    description: "Spot suspicious messages, protect an account, recover access and report fraud without guessing at the words on the screen.",
    focus: "Practical digital-safety German: sich als jemand ausgeben, sperren lassen, zurücksetzen, Zwei-Faktor-Authentifizierung and calm ways to verify a request.",
    seeds: [
      { de: "das Benutzerkonto", lookup: "Benutzerkonto", fallbackEn: "user account", tip: "noun", article: "das" },
      { de: "der Bestätigungscode", lookup: "Bestätigungscode", fallbackEn: "verification code", tip: "noun", article: "der" },
      { de: "die Zwei-Faktor-Authentifizierung", lookup: "Zwei-Faktor-Authentifizierung", fallbackEn: "two-factor authentication", tip: "noun", article: "die" },
      { de: "die Phishing-Mail", lookup: "Phishing-Mail", fallbackEn: "phishing email", tip: "noun", article: "die" },
      { de: "der Betrugsversuch", lookup: "Betrugsversuch", fallbackEn: "attempted fraud, scam attempt", tip: "noun", article: "der" },
      { de: "das Datenleck", lookup: "Datenleck", fallbackEn: "data breach", tip: "noun", article: "das" },
      { de: "die Sicherungskopie", lookup: "Sicherungskopie", fallbackEn: "backup copy", tip: "noun", article: "die" },
      { de: "verdächtig", lookup: "verdächtig", fallbackEn: "suspicious", tip: "adjective" },
      { de: "sperren", lookup: "sperren", fallbackEn: "to block, lock", tip: "verb" },
      { de: "entsperren", lookup: "entsperren", fallbackEn: "to unlock", tip: "verb" },
      { de: "zurücksetzen", lookup: "zurücksetzen", fallbackEn: "to reset", tip: "verb" },
      { de: "sich als jemand ausgeben", lookup: "ausgeben", fallbackEn: "to pose as, pretend to be", tip: "verb phrase" },
      { de: "melden", lookup: "melden", fallbackEn: "to report", tip: "verb" },
      { de: "überprüfen", lookup: "überprüfen", fallbackEn: "to check, verify", tip: "verb" },
      { de: "sichern", lookup: "sichern", fallbackEn: "to secure, back up", tip: "verb" },
    ],
    phrases: [
      { de: "Diese Nachricht sieht verdächtig aus.", en: "This message looks suspicious.", use: "'verdächtig aussehen' is the natural first reaction when the sender, wording or link does not look right." },
      { de: "Klick nicht auf den Link.", en: "Don't click the link.", use: "The spoken du-command is 'Klick'; a more formal warning is 'Klicken Sie nicht auf den Link'." },
      { de: "Öffne den Anhang nur, wenn du ihn erwartet und den Absender überprüft hast.", en: "Only open the attachment if you were expecting it and have verified the sender.", use: "After 'wenn', the completed actions stay together at the end: 'erwartet und ... überprüft hast'." },
      { de: "Gib niemandem deinen Bestätigungscode.", en: "Don't give your verification code to anyone.", use: "German uses positive-looking 'niemandem' for the recipient; it is dative because someone is being given something." },
      { de: "Die Nachricht setzt mich unter Druck, sofort zu bezahlen.", en: "The message is pressuring me to pay immediately.", use: "'jemanden unter Druck setzen' is the standard phrase for creating pressure; urgency is a common warning sign." },
      { de: "Das Angebot klingt zu gut, um wahr zu sein.", en: "The offer sounds too good to be true.", use: "The pattern 'zu + adjective + um ... zu' corresponds to English 'too ... to ...'; do not translate 'um' separately here." },
      { de: "Der Absender gibt sich als meine Bank aus.", en: "The sender is pretending to be my bank. / The sender is posing as my bank.", use: "Separable 'sich als jemand ausgeben' becomes 'gibt sich ... aus'. It means claiming a false identity." },
      { de: "Meine Bank würde niemals per Nachricht nach meiner PIN fragen.", en: "My bank would never ask for my PIN in a message.", use: "'nach etwas fragen' takes the dative, so it is 'nach meiner PIN'." },
      { de: "Ich suche die Nummer selbst auf der offiziellen Website und rufe dort an.", en: "I'll look up the number myself on the official website and call it.", use: "Use contact details you found independently, never the number contained in the suspicious message." },
      { de: "Im Zweifel rufe ich die Firma selbst an.", en: "If in doubt, I'll call the company myself.", use: "'im Zweifel' is the compact everyday equivalent of 'if in doubt'; separable 'anrufen' ends with 'an'." },
      { de: "Überweis kein Geld an unbekannte Personen.", en: "Don't transfer money to people you don't know.", use: "Spoken imperative 'Überweis' is common; careful written German may use 'Überweise'." },
      { de: "Ich glaube, mein Konto wurde gehackt.", en: "I think my account has been hacked.", use: "German commonly uses the simple passive 'wurde gehackt' where English uses 'has been hacked'." },
      { de: "Ändere sofort dein Passwort.", en: "Change your password immediately.", use: "The careful imperative is 'Ändere'. Use a unique password rather than a small variation of the old one." },
      { de: "Verwende für jedes Konto ein anderes Passwort.", en: "Use a different password for every account.", use: "'für' takes the accusative: 'für jedes Konto'. 'ein anderes' means a different one for each account." },
      { de: "Aktiviere die Zwei-Faktor-Authentifizierung.", en: "Enable two-factor authentication.", use: "Apps often shorten this to '2FA'; the full German term is feminine because 'Authentifizierung' is feminine." },
      { de: "Ich habe diese Anmeldung nicht bestätigt.", en: "I didn't approve this sign-in. / I didn't confirm this login.", use: "'die Anmeldung' can mean a sign-in, registration or application; the account context makes the meaning clear." },
      { de: "Melde dich auf allen anderen Geräten ab.", en: "Sign out of all the other devices.", use: "Reflexive 'sich abmelden' ends your active sessions; the locations are dative after 'auf'." },
      { de: "Mein Konto wurde vorübergehend gesperrt.", en: "My account has been temporarily locked.", use: "'gesperrt' covers locked, blocked and suspended; 'vorübergehend' says the restriction is temporary." },
      { de: "Ich kann mein Passwort nicht zurücksetzen.", en: "I can't reset my password.", use: "After modal 'kann', the separable verb stays together at the end: 'zurücksetzen'." },
      { de: "Die E-Mail zum Zurücksetzen des Passworts ist nicht angekommen.", en: "The password-reset email hasn't arrived. / The reset email hasn't come through.", use: "'zum Zurücksetzen des Passworts' makes the purpose explicit; 'ankommen' forms the perfect with 'sein'." },
      { de: "Schau auch in deinem Spamordner nach.", en: "Check your spam folder as well.", use: "Separable 'nachschauen' becomes 'Schau ... nach'; the location is dative after 'in'." },
      { de: "Jemand hat in meinem Namen etwas bestellt.", en: "Someone ordered something in my name.", use: "The fixed phrase is 'in jemandes Namen'; here 'meinem' is dative after 'in'." },
      { de: "Ich habe meine Karte sofort sperren lassen.", en: "I had my card blocked immediately. / I got my card frozen straight away.", use: "'etwas sperren lassen' means arranging for the bank or provider to block it." },
      { de: "Ich möchte diesen Betrugsversuch melden.", en: "I'd like to report this attempted fraud. / I want to report this scam attempt.", use: "'melden' is the useful verb for reporting fraud to a bank, platform or police service." },
      { de: "Meine Daten waren von einem Datenleck betroffen.", en: "My data was affected by a data breach.", use: "The pattern is 'von etwas betroffen sein'; 'von' takes the dative." },
      { de: "Erstelle regelmäßig Sicherungskopien deiner wichtigsten Dateien.", en: "Back up your most important files regularly.", use: "German can say 'Sicherungskopien erstellen'; in tech speech, 'Backups machen' is also common." },
      { de: "Installiere Sicherheitsupdates, sobald sie verfügbar sind.", en: "Install security updates as soon as they're available.", use: "After 'sobald', the verb goes to the end: 'sobald sie verfügbar sind'." },
      { de: "Gib einer unbekannten Person niemals Fernzugriff auf dein Gerät.", en: "Never give a stranger remote access to your device.", use: "'jemandem Fernzugriff geben' takes the dative. A genuine support worker should not pressure you into granting access." },
    ],
    dialogues: [
      { title: "A suspicious bank message", lines: [
        { speaker: "A", de: "Meine Bank will, dass ich sofort auf diesen Link klicke.", en: "My bank wants me to click this link immediately." },
        { speaker: "B", de: "Klick nicht drauf. Die Nachricht sieht verdächtig aus.", en: "Don't click it. The message looks suspicious." },
        { speaker: "A", de: "Wie kann ich prüfen, ob sie echt ist?", en: "How can I check whether it's genuine?" },
        { speaker: "B", de: "Ruf die Bank über die Nummer auf ihrer offiziellen Website an.", en: "Call the bank using the number on its official website." },
      ]},
      { title: "Recovering an account", lines: [
        { speaker: "A", de: "Ich glaube, jemand hat auf mein Konto zugegriffen.", en: "I think someone has accessed my account." },
        { speaker: "B", de: "Ändere zuerst dein Passwort und melde dich auf allen anderen Geräten ab.", en: "Change your password first and sign out of all the other devices." },
        { speaker: "A", de: "Soll ich auch die Zwei-Faktor-Authentifizierung aktivieren?", en: "Should I enable two-factor authentication as well?" },
        { speaker: "B", de: "Ja, und speichere die Wiederherstellungscodes an einem sicheren Ort.", en: "Yes, and keep the recovery codes somewhere safe." },
      ]},
    ],
  },

  part152: {
    label: "Part 152",
    level: "B1-B2",
    theme: "Telling a story clearly: what happened next",
    description: "Tell a real story in order, add background, reveal the turning point and explain how it all ended without producing disconnected sentences.",
    focus: "Story-building phrases such as das Ganze fing damit an, gerade als, inzwischen, es stellte sich heraus, im Nachhinein and je ... desto ...",
    seeds: [
      { de: "der Hintergrund", lookup: "Hintergrund", fallbackEn: "background, context", tip: "noun", article: "der" },
      { de: "der Zufall", lookup: "Zufall", fallbackEn: "coincidence, chance", tip: "noun", article: "der" },
      { de: "das Missverständnis", lookup: "Missverständnis", fallbackEn: "misunderstanding", tip: "noun", article: "das" },
      { de: "die Wendung", lookup: "Wendung", fallbackEn: "turn, twist", tip: "noun", article: "die" },
      { de: "der Ausgang", lookup: "Ausgang", fallbackEn: "outcome, result; also exit in a building", tip: "noun", article: "der" },
      { de: "plötzlich", lookup: "plötzlich", fallbackEn: "suddenly", tip: "adverb" },
      { de: "inzwischen", lookup: "inzwischen", fallbackEn: "meanwhile, by now", tip: "adverb" },
      { de: "schließlich", lookup: "schließlich", fallbackEn: "eventually, after all", tip: "adverb" },
      { de: "ausgerechnet", lookup: "ausgerechnet", fallbackEn: "of all people or times", tip: "adverb" },
      { de: "rückblickend", lookup: "rückblickend", fallbackEn: "looking back", tip: "adverb" },
      { de: "sich herausstellen", lookup: "herausstellen", fallbackEn: "to turn out", tip: "verb" },
      { de: "dazwischenkommen", lookup: "dazwischenkommen", fallbackEn: "to come up, get in the way", tip: "verb" },
      { de: "bemerken", lookup: "bemerken", fallbackEn: "to notice", tip: "verb" },
      { de: "sich erinnern", lookup: "erinnern", fallbackEn: "to remember", tip: "verb" },
      { de: "übertreiben", lookup: "übertreiben", fallbackEn: "to exaggerate", tip: "verb" },
    ],
    phrases: [
      { de: "Das Ganze fing damit an, dass ich meinen Zug verpasst habe.", en: "The whole thing started when I missed my train. / It all began with me missing my train.", use: "'damit anfangen, dass ...' introduces the first event and sends the verb in the dass-clause to the end." },
      { de: "Eigentlich wollte ich nur kurz etwas abholen.", en: "I only meant to pick something up quickly. / I only intended to pick something up.", use: "Story-opening 'eigentlich' sets up the original plan before reality changes it." },
      { de: "Zuerst dachte ich, es wäre kein großes Problem.", en: "At first, I thought it wouldn't be a big problem. / At first, I didn't think it was a big deal.", use: "'zuerst' gives the first viewpoint; 'wäre' keeps the thought at one remove rather than declaring a fact." },
      { de: "Auf dem Weg dorthin habe ich eine alte Freundin getroffen.", en: "On the way there, I ran into an old friend.", use: "'auf dem Weg dorthin' links the background journey to an event; 'jemanden treffen' takes the accusative." },
      { de: "Gerade als ich losgehen wollte, klingelte mein Handy.", en: "Just as I was about to leave, my phone rang.", use: "'gerade als' marks an interruption at an exact moment; 'wollte' goes to the end of its clause." },
      { de: "Plötzlich stand ein fremder Hund vor mir.", en: "Suddenly, an unfamiliar dog was standing in front of me. / Suddenly, there was a dog I didn't know standing in front of me.", use: "German 'fremd' means unknown or unfamiliar here, not odd; starting with 'plötzlich' puts the finite verb second." },
      { de: "Zu diesem Zeitpunkt wusste ich noch nichts davon.", en: "At that point, I still knew nothing about it.", use: "'zu diesem Zeitpunkt' anchors what the storyteller knew then, not what they know now." },
      { de: "Inzwischen hatten die anderen schon angefangen.", en: "By then, the others had already started.", use: "In this sequence, 'inzwischen' means by then; pluperfect 'hatten angefangen' places their action before the next past event." },
      { de: "Was ich damals nicht wusste, war, dass die Tür schon abgeschlossen war.", en: "What I didn't know at the time was that the door was already locked.", use: "This frame reveals information to the listener while preserving what the storyteller knew at the time." },
      { de: "Es stellte sich heraus, dass wir am falschen Eingang gewartet hatten.", en: "It turned out that we'd been waiting at the wrong entrance.", use: "Separable 'sich herausstellen' becomes 'stellte sich heraus'; the discovery follows in a dass-clause." },
      { de: "Da wurde mir klar, warum niemand gekommen war.", en: "That was when I realised why nobody had come.", use: "'Da wurde mir klar' marks the moment of realisation; the person who realises is dative 'mir'." },
      { de: "Als ob das nicht schon genug gewesen wäre, fing es auch noch an zu regnen.", en: "As if that wasn't enough, it started raining as well.", use: "'Als ob' normally uses 'wäre' here because it presents an imagined comparison: as if that had not already been enough." },
      { de: "Ausgerechnet an diesem Tag war mein Handyakku leer.", en: "My phone battery was flat that day of all days.", use: "'ausgerechnet' highlights the worst, funniest or most surprising person, place or time." },
      { de: "Dann kam auch noch ein Missverständnis dazu.", en: "Then there was a misunderstanding on top of everything else.", use: "'auch noch' adds another problem; 'dazukommen' means being added to what is already happening." },
      { de: "Eins führte zum anderen, und plötzlich waren wir drei Stunden zu spät.", en: "One thing led to another, and suddenly we were three hours late.", use: "'Eins führte zum anderen' skips unimportant middle steps while keeping the chain of events clear." },
      { de: "Je länger wir warteten, desto ungeduldiger wurden wir.", en: "The longer we waited, the more impatient we became.", use: "The fixed comparison is 'je ... desto ...'; both halves use a comparative." },
      { de: "Am Ende ist alles besser ausgegangen als erwartet.", en: "In the end, everything turned out better than expected.", use: "'ausgehen' describes the outcome of a situation; its perfect uses 'sein': 'ist ausgegangen'." },
      { de: "Zum Glück hatte jemand einen Ersatzschlüssel dabei.", en: "Luckily, someone had a spare key with them.", use: "'zum Glück' comments on the result without changing the event order." },
      { de: "Leider kam kurz vor Schluss noch etwas dazwischen.", en: "Unfortunately, something came up just before the end.", use: "'etwas kommt dazwischen' means an unexpected event interferes with the plan." },
      { de: "Seitdem prüfe ich immer zweimal, welchen Eingang wir meinen.", en: "Ever since then, I always double-check which entrance we're talking about.", use: "'seitdem' connects a past lesson with a habit that continues now." },
      { de: "Das war der Moment, in dem sich alles geändert hat.", en: "That was the moment when everything changed.", use: "After a noun such as 'der Moment', German uses relative 'in dem' where English often uses 'when'." },
      { de: "Ich weiß nicht mehr genau, wie wir auf diese Idee gekommen sind.", en: "I can't remember exactly how we came up with this idea.", use: "'nicht mehr wissen' means no longer remembering; 'auf eine Idee kommen' means coming up with an idea." },
      { de: "Wenn ich mich richtig erinnere, war das an einem Dienstag.", en: "If I remember correctly, that was on a Tuesday.", use: "German 'sich erinnern' is reflexive, so the 'mich' cannot be dropped in careful speech." },
      { de: "Um es kurz zu machen: Wir mussten wieder von vorne anfangen.", en: "To cut a long story short, we had to start again from the beginning. / In short, we had to start over.", use: "'um es kurz zu machen' signals that details are being skipped; a colon naturally introduces the outcome." },
      { de: "Das klingt erfunden, ist aber wirklich passiert.", en: "It sounds made up, but it really happened.", use: "German can omit the repeated subject 'das' before 'ist' in this balanced sentence." },
      { de: "Du hättest dabei sein müssen.", en: "You had to be there. / You should have been there.", use: "This often means the story cannot fully capture how funny or strange the moment was, not that attendance was compulsory." },
      { de: "Im Nachhinein hätten wir früher reagieren sollen.", en: "In hindsight, we should have reacted sooner.", use: "For past regret, German uses 'hätten' and leaves both action words together at the end: 'reagieren sollen'." },
      { de: "Rückblickend war die ganze Sache eigentlich ziemlich lustig.", en: "Looking back, the whole thing was actually quite funny.", use: "'rückblickend' gives the storyteller's present judgement after time has changed the feeling." },
    ],
    dialogues: [
      { title: "Why everyone was late", lines: [
        { speaker: "A", de: "Warum seid ihr gestern so spät gekommen?", en: "Why did you all arrive so late yesterday?" },
        { speaker: "B", de: "Das Ganze fing damit an, dass unser Zug ausgefallen ist.", en: "It all started when our train was cancelled." },
        { speaker: "A", de: "Und dann?", en: "And then?" },
        { speaker: "B", de: "Es stellte sich heraus, dass der Ersatzbus am anderen Ausgang hielt.", en: "It turned out that the replacement bus stopped at the other exit." },
      ]},
      { title: "A lucky ending", lines: [
        { speaker: "A", de: "Habt ihr den verlorenen Schlüssel noch gefunden?", en: "Did you find the lost key in the end?" },
        { speaker: "B", de: "Ja. Ausgerechnet der Hund hatte ihn unter das Sofa geschoben.", en: "Yes. The dog, of all creatures, had pushed it under the sofa." },
        { speaker: "A", de: "Wie habt ihr ihn gefunden?", en: "How did you find it?" },
        { speaker: "B", de: "Zum Glück hat er später wieder damit gespielt.", en: "Luckily, he started playing with it again later." },
      ]},
    ],
  },

  part153: {
    label: "Part 153",
    level: "A2-B1",
    theme: "Board games, tabletop RPGs and taking turns",
    description: "Explain the rules, take a turn, count points and play a tabletop role-playing session without falling back to English for every action.",
    focus: "Useful table language: dran sein, eine Karte ziehen, würfeln, Felder vorrücken, Hausregeln, Charakterbögen and checks in a tabletop RPG.",
    seeds: [
      { de: "das Brettspiel", lookup: "Brettspiel", fallbackEn: "board game", tip: "noun", article: "das" },
      { de: "das Spielbrett", lookup: "Spielbrett", fallbackEn: "game board", tip: "noun", article: "das" },
      { de: "die Spielfigur", lookup: "Spielfigur", fallbackEn: "playing piece, pawn", tip: "noun", article: "die" },
      { de: "der Würfel", lookup: "Würfel", fallbackEn: "one die; plural: dice", tip: "noun", article: "der" },
      { de: "der Kartenstapel", lookup: "Kartenstapel", fallbackEn: "deck, pile of cards", tip: "noun", article: "der" },
      { de: "der Zug", lookup: "Zug", fallbackEn: "turn, move", tip: "noun", article: "der" },
      { de: "die Runde", lookup: "Runde", fallbackEn: "round", tip: "noun", article: "die" },
      { de: "das Feld", lookup: "Feld", fallbackEn: "space, square", tip: "noun", article: "das" },
      { de: "die Hausregel", lookup: "Hausregel", fallbackEn: "house rule", tip: "noun", article: "die" },
      { de: "der Mitspieler", lookup: "Mitspieler", fallbackEn: "fellow player", tip: "noun", article: "der" },
      { de: "der Spielleiter", lookup: "Spielleiter", fallbackEn: "game master", tip: "noun", article: "der" },
      { de: "der Charakterbogen", lookup: "Charakterbogen", fallbackEn: "character sheet", tip: "noun", article: "der" },
      { de: "die Probe", lookup: "Probe", fallbackEn: "check, test", tip: "noun", article: "die" },
      { de: "würfeln", lookup: "würfeln", fallbackEn: "to roll dice", tip: "verb" },
      { de: "mischen", lookup: "mischen", fallbackEn: "to shuffle, mix", tip: "verb" },
    ],
    phrases: [
      { de: "Wessen Zug ist es?", en: "Whose turn is it?", use: "For a game turn, German asks 'Wessen Zug ist es?'; everyday speech also uses the shorter 'Wer ist dran?'." },
      { de: "Du bist dran.", en: "It's your turn. / You're up.", use: "'dran sein' is the everyday pattern for turns in games, queues and chores." },
      { de: "Ich muss eine Runde aussetzen.", en: "I have to miss a turn. / I have to skip my next turn.", use: "'eine Runde aussetzen' means missing one turn or round. For a whole gaming session, say 'Ich bin diesmal nicht dabei'." },
      { de: "Zieh eine Karte vom Stapel.", en: "Draw a card from the deck.", use: "Imperative of 'ziehen' is 'Zieh'; 'vom' contracts 'von dem'." },
      { de: "Misch die Karten noch einmal.", en: "Shuffle the cards again.", use: "The casual imperative is 'Misch'; 'die Karten mischen' is the normal phrase for shuffling." },
      { de: "Würfle noch einmal.", en: "Roll again. / Roll the dice again.", use: "German usually needs no object because 'würfeln' already means rolling dice." },
      { de: "Zieh deine Spielfigur um drei Felder vor.", en: "Move your playing piece forward three spaces.", use: "Board-game instructions commonly use 'eine Spielfigur um drei Felder vorziehen'; the distance follows 'um'." },
      { de: "Du musst zwei Felder zurück.", en: "You have to go back two spaces.", use: "Spoken German can leave out 'gehen' after the modal when the direction makes the action obvious." },
      { de: "Wie viele Punkte hast du?", en: "How many points have you got? / How many points do you have?", use: "'wie viele' is used with countable plurals such as 'Punkte'." },
      { de: "Wer erklärt kurz die Regeln?", en: "Who can quickly explain the rules? / Who's going to give us a quick rundown of the rules?", use: "Present tense naturally asks who will take the task; 'kurz' promises a brief explanation." },
      { de: "Ich habe die Regel noch nicht ganz verstanden.", en: "I don't quite understand the rule yet. / I haven't quite got the rule yet.", use: "'noch nicht ganz' is a gentle way to admit partial understanding rather than total confusion." },
      { de: "Gilt diese Karte auch für mich?", en: "Does this card apply to me as well?", use: "'für jemanden gelten' means applying to a person or situation; 'für' takes the accusative." },
      { de: "Das zählt nicht; du hast zu früh gewürfelt.", en: "That doesn't count; you rolled too early.", use: "'Das zählt nicht' is the standard verdict when an action is invalid." },
      { de: "Wir spielen heute ohne Hausregeln.", en: "We're playing without house rules today.", use: "'ohne' takes the accusative; plural 'Hausregeln' looks unchanged." },
      { de: "Darf ich meinen Zug noch zurücknehmen?", en: "Can I take my move back? / Can I undo my move?", use: "'einen Zug zurücknehmen' is the standard way to ask whether a completed move can be undone." },
      { de: "Wenn wir gleich viele Punkte haben, gibt es ein Unentschieden.", en: "If we have the same number of points, it's a draw.", use: "'gleich viele' means the same number; after 'wenn', 'haben' goes to the end." },
      { de: "Das Spiel ist knapper, als ich erwartet hatte.", en: "The game is closer than I expected.", use: "A close contest is 'knapp'; comparison uses 'als', never 'wie', after a comparative." },
      { de: "Willst du dich für eine Runde mit mir verbünden?", en: "Do you want to form an alliance with me for one round?", use: "'sich mit jemandem verbünden' specifically means forming an alliance; 'mit' takes the dative." },
      { de: "Du hast mich gerade verraten.", en: "You just betrayed me.", use: "'verraten' can mean betraying a teammate or revealing a secret; the game context makes it playful." },
      { de: "Wer übernimmt heute die Spielleitung?", en: "Who's going to be the game master today? / Who's running the game today?", use: "'die Spielleitung übernehmen' means taking responsibility for running the session." },
      { de: "Ich erstelle einen neuen Charakter.", en: "I'm creating a new character.", use: "Masculine 'der Charakter' becomes accusative 'einen neuen Charakter'." },
      { de: "Was steht auf deinem Charakterbogen?", en: "What does it say on your character sheet?", use: "German asks what 'steht' on written material; the fixed location after 'auf' is dative." },
      { de: "Mach bitte eine Wahrnehmungsprobe.", en: "Make a perception check, please. / Roll a perception check, please.", use: "Tabletop German uses 'eine Probe machen'; many groups also say English-influenced 'auf Wahrnehmung würfeln'." },
      { de: "Ich würfle auf Überreden.", en: "I'm rolling persuasion. / I'll make a persuasion check.", use: "In tabletop speech, 'auf etwas würfeln' names the skill. The same skill may be called 'Überzeugen' or 'Diplomatie' in another system." },
      { de: "In diesem System ist das ein kritischer Erfolg.", en: "In this system, that's a critical success.", use: "Critical-success rules differ between systems; a natural twenty is not automatically a critical success in every game." },
      { de: "Mein Charakter hat nur noch einen Trefferpunkt.", en: "My character only has one hit point left.", use: "'nur noch' means only remaining; singular is 'einen Trefferpunkt'." },
      { de: "Ich untersuche die Tür auf Fallen.", en: "I check the door for traps.", use: "'etwas auf etwas untersuchen' means examining it for a particular problem or feature." },
      { de: "Wir hören hier auf und spielen nächste Woche weiter.", en: "We'll stop here and carry on next week.", use: "Both verbs split: 'hören ... auf' and 'spielen ... weiter'. This closes a session without ending the campaign." },
    ],
    dialogues: [
      { title: "Learning a new board game", lines: [
        { speaker: "A", de: "Ich kenne das Spiel noch nicht. Wer erklärt die Regeln?", en: "I don't know this game yet. Who's going to explain the rules?" },
        { speaker: "B", de: "Mach ich. Du ziehst zuerst zwei Karten.", en: "I will. First, you draw two cards." },
        { speaker: "A", de: "Und wann darf ich meine Figur bewegen?", en: "And when can I move my piece?" },
        { speaker: "B", de: "Nachdem du gewürfelt hast. Du bist übrigens zuerst dran.", en: "After you've rolled. You're first, by the way." },
      ]},
      { title: "A tabletop check", lines: [
        { speaker: "A", de: "Ich untersuche die Tür auf Fallen.", en: "I check the door for traps." },
        { speaker: "B", de: "Dann mach eine Wahrnehmungsprobe.", en: "Then make a perception check." },
        { speaker: "A", de: "Eine natürliche Zwanzig!", en: "A natural twenty!" },
        { speaker: "B", de: "Damit schaffst du die Probe und entdeckst einen versteckten Mechanismus.", en: "That passes the check, and you discover a hidden mechanism." },
      ]},
    ],
  },

  part154: {
    label: "Part 154",
    level: "A2-B1",
    theme: "DIY tools and fixing things at home",
    description: "Name the tools, measure before drilling, put furniture together and describe the small faults that turn a five-minute job into an afternoon.",
    focus: "Practical home-project German: ausmessen, festziehen, lockern, die Sicherung ausschalten, Leitungen in der Wand and knowing when to call a professional.",
    seeds: [
      { de: "der Werkzeugkasten", lookup: "Werkzeugkasten", fallbackEn: "toolbox", tip: "noun", article: "der" },
      { de: "der Hammer", lookup: "Hammer", fallbackEn: "hammer", tip: "noun", article: "der" },
      { de: "der Schraubendreher", lookup: "Schraubendreher", fallbackEn: "screwdriver", tip: "noun", article: "der" },
      { de: "die Schraube", lookup: "Schraube", fallbackEn: "screw", tip: "noun", article: "die" },
      { de: "der Nagel", lookup: "Nagel", fallbackEn: "nail", tip: "noun", article: "der" },
      { de: "die Bohrmaschine", lookup: "Bohrmaschine", fallbackEn: "drill", tip: "noun", article: "die" },
      { de: "der Bohrer", lookup: "Bohrer", fallbackEn: "drill bit", tip: "noun", article: "der" },
      { de: "die Wasserwaage", lookup: "Wasserwaage", fallbackEn: "spirit level", tip: "noun", article: "die" },
      { de: "das Maßband", lookup: "Maßband", fallbackEn: "tape measure", tip: "noun", article: "das" },
      { de: "die Zange", lookup: "Zange", fallbackEn: "pliers", tip: "noun", article: "die" },
      { de: "der Dübel", lookup: "Dübel", fallbackEn: "wall plug, anchor", tip: "noun", article: "der" },
      { de: "die Sicherung", lookup: "Sicherung", fallbackEn: "fuse, circuit breaker", tip: "noun", article: "die" },
      { de: "die Dichtung", lookup: "Dichtung", fallbackEn: "seal, washer, gasket", tip: "noun", article: "die" },
      { de: "das Scharnier", lookup: "Scharnier", fallbackEn: "hinge", tip: "noun", article: "das" },
      { de: "ausmessen", lookup: "ausmessen", fallbackEn: "to measure up", tip: "verb" },
    ],
    phrases: [
      { de: "Wo ist der Werkzeugkasten?", en: "Where's the toolbox?", use: "Masculine compound 'der Werkzeugkasten' literally means the box for tools." },
      { de: "Ich brauche einen Kreuzschlitzschraubendreher.", en: "I need a Phillips screwdriver. / I need a cross-head screwdriver.", use: "The full German name describes the cross-shaped slot; people may shorten it to 'Kreuzschlitz'." },
      { de: "Miss zuerst die Wand aus.", en: "Measure the wall first.", use: "Imperative of 'ausmessen' is 'Miss ... aus'; measure before marking or drilling." },
      { de: "Markier die Stelle mit einem Bleistift.", en: "Mark the spot with a pencil.", use: "Casual spoken imperative 'Markier' is common; the tool follows dative 'mit einem Bleistift'." },
      { de: "Prüf mit der Wasserwaage, ob es gerade ist.", en: "Use the spirit level to check whether it's straight.", use: "After 'ob', the verb goes to the end: 'ob es gerade ist'." },
      { de: "Welche Schraube passt in diesen Dübel?", en: "Which screw fits this wall plug? / Which screw fits this anchor?", use: "With 'passen in', the thing something fits into is expressed with the accusative: 'in diesen Dübel'." },
      { de: "Der Bohrer ist für diesen Dübel zu klein.", en: "The drill bit is too small for this wall plug.", use: "'der Bohrer' is the bit; 'die Bohrmaschine' is the powered drill itself." },
      { de: "Befestige das Werkstück, bevor du bohrst.", en: "Secure the workpiece before drilling.", use: "Use clamps or another suitable support rather than holding material close to a moving drill bit." },
      { de: "Pass auf, in der Wand könnten Leitungen verlaufen.", en: "Be careful, there could be cables or pipes running through the wall.", use: "'die Leitung' can be an electrical cable or a pipe; the context and a detector tell you which." },
      { de: "Schalte den betreffenden Stromkreis aus und prüfe, ob er wirklich spannungsfrei ist.", en: "Switch off the relevant circuit and verify that it is dead.", use: "If you are not trained or cannot verify this safely, call an electrician." },
      { de: "Der Nagel ist krumm geworden.", en: "The nail has bent.", use: "German describes the changed state with 'ist krumm geworden'." },
      { de: "Die Schraube dreht durch.", en: "The screw is spinning without tightening. / The screw won't bite.", use: "'durchdrehen' here means the screw keeps turning without gripping; it can also mean a person losing control." },
      { de: "Zieh die Schraube nicht zu fest an.", en: "Don't overtighten the screw. / Don't tighten the screw too much.", use: "Separable 'anziehen' becomes 'Zieh ... an'; 'zu fest' means excessively tight." },
      { de: "Kannst du die Mutter mit der Zange festhalten?", en: "Can you hold the nut with the pliers?", use: "'die Mutter' means both mother and a metal nut; the DIY context removes the ambiguity." },
      { de: "Jetzt sitzt das Teil fest.", en: "The part is firmly in place now.", use: "'fest sitzen' means being securely seated here; 'jetzt' makes the successful result clear." },
      { de: "Ich kriege die Schraube nicht locker.", en: "I can't get the screw loose.", use: "Spoken 'etwas lockerkriegen' means managing to loosen it after trying." },
      { de: "Der Wasserhahn tropft schon wieder.", en: "The tap is dripping again.", use: "'tropfen' is a drip one drop at a time; a larger uncontrolled leak is 'undicht sein' or 'auslaufen'." },
      { de: "Die Dichtung muss ausgetauscht werden.", en: "The seal needs to be replaced. / The washer needs replacing.", use: "This is a passive necessity: 'muss ausgetauscht werden'." },
      { de: "Unter dem Waschbecken ist es feucht.", en: "It's damp under the sink.", use: "'feucht' is damp or moist; it often reveals a slow leak before a puddle appears." },
      { de: "Wir sollten zuerst das Wasser abstellen.", en: "We should turn the water off first.", use: "'das Wasser abstellen' means shutting off the supply, not merely turning off a running tap." },
      { de: "Der Rauchmelder braucht eine neue Batterie.", en: "The smoke alarm needs a new battery.", use: "German 'brauchen' directly takes the thing needed; feminine 'eine neue Batterie'." },
      { de: "Die Tür schleift über den Boden.", en: "The door is catching on the floor. / The door is scraping along the floor.", use: "'schleifen' describes the bottom of the door rubbing instead of moving freely." },
      { de: "Das Scharnier quietscht bei jeder Bewegung.", en: "The hinge squeaks every time it moves.", use: "'bei jeder Bewegung' means with every movement; 'quietschen' is the high squeaking sound." },
      { de: "Die Wand klingt hohl.", en: "The wall sounds hollow.", use: "'hohl klingen' describes the sound when you tap it. It does not show whether cables or pipes are behind the wall." },
      { de: "Wir müssen das Loch noch zuspachteln.", en: "We still need to fill the hole. / We still need to fill the hole with filler.", use: "'zuspachteln' means filling a small hole with filler; it stays together after modal 'müssen'." },
      { de: "Das Silikon ist noch nicht trocken.", en: "The silicone sealant isn't dry yet.", use: "In DIY German, neuter 'das Silikon' commonly means silicone sealant, not the chemical element in English." },
      { de: "Heb die Anleitung auf, falls wir sie später brauchen.", en: "Keep the instructions in case we need them later.", use: "Separable 'aufheben' means keeping rather than discarding; after 'falls', 'brauchen' goes to the end." },
      { de: "Wenn wir uns nicht sicher sind, holen wir lieber eine Fachkraft.", en: "If we're not sure, we'd better call a professional.", use: "'eine Fachkraft holen' means bringing in someone qualified; 'lieber' expresses the safer preferred choice." },
    ],
    dialogues: [
      { title: "Putting up a shelf", lines: [
        { speaker: "A", de: "Ist das Regal so gerade?", en: "Is the shelf straight like that?" },
        { speaker: "B", de: "Warte, ich prüfe es mit der Wasserwaage.", en: "Wait, I'll check it with the spirit level." },
        { speaker: "A", de: "Soll ich die Löcher schon markieren?", en: "Should I mark the holes now?" },
        { speaker: "B", de: "Ja, aber prüf vorher mit einem geeigneten Leitungssucher, ob dort Leitungen verlaufen.", en: "Yes, but first use a suitable detector to check for cables or pipes there." },
      ]},
      { title: "A leak under the sink", lines: [
        { speaker: "A", de: "Unter dem Waschbecken ist alles feucht.", en: "Everything under the sink is damp." },
        { speaker: "B", de: "Dann stellen wir zuerst das Wasser ab.", en: "Then we'll turn the water off first." },
        { speaker: "A", de: "Kannst du sehen, wo es tropft?", en: "Can you see where it's dripping from?" },
        { speaker: "B", de: "Ja, die Dichtung ist undicht und muss ausgetauscht werden.", en: "Yes, the seal is leaking and needs to be replaced." },
      ]},
    ],
  },

  part155: {
    label: "Part 155",
    level: "A1-A2",
    theme: "At the bakery, deli counter and weekly market",
    description: "Order bread and cold cuts, ask for the right amount and buy fresh produce at a counter where pointing is not always enough.",
    focus: "Everyday counter German: dran sein, hätte gern, schneiden, dünn geschnitten, davon nehme ich, prices by weight and natural ways to finish an order.",
    seeds: [
      { de: "das Gebäck", lookup: "Gebäck", fallbackEn: "baked goods, pastry", tip: "noun", article: "das" },
      { de: "das Körnerbrötchen", lookup: "Körnerbrötchen", fallbackEn: "seeded roll", tip: "noun", article: "das" },
      { de: "das Roggenbrot", lookup: "Roggenbrot", fallbackEn: "rye bread", tip: "noun", article: "das" },
      { de: "das Vollkornbrot", lookup: "Vollkornbrot", fallbackEn: "wholemeal bread, whole-grain bread", tip: "noun", article: "das" },
      { de: "die Brezel", lookup: "Brezel", fallbackEn: "pretzel", tip: "noun", article: "die" },
      { de: "die Frischetheke", lookup: "Frischetheke", fallbackEn: "fresh-food counter, deli counter", tip: "noun", article: "die" },
      { de: "der Aufschnitt", lookup: "Aufschnitt", fallbackEn: "cold cuts, sliced meat", tip: "noun", article: "der" },
      { de: "die Rohmilch", lookup: "Rohmilch", fallbackEn: "raw milk", tip: "noun", article: "die" },
      { de: "der Wochenmarkt", lookup: "Wochenmarkt", fallbackEn: "weekly market, farmers' market", tip: "noun", article: "der" },
      { de: "der Stückpreis", lookup: "Stückpreis", fallbackEn: "price per item", tip: "noun", article: "der" },
      { de: "der Kilopreis", lookup: "Kilopreis", fallbackEn: "price per kilo", tip: "noun", article: "der" },
      { de: "reif", lookup: "reif", fallbackEn: "ripe", tip: "adjective" },
      { de: "der Brotlaib", lookup: "Brotlaib", fallbackEn: "loaf of bread", tip: "noun", article: "der" },
      { de: "einpacken", lookup: "einpacken", fallbackEn: "to wrap, pack", tip: "verb" },
      { de: "probieren", lookup: "probieren", fallbackEn: "to try, taste", tip: "verb" },
    ],
    phrases: [
      { de: "Wer ist als Nächstes dran?", en: "Who's next?", use: "The normal staff question when there is no ticket system or obvious queue." },
      { de: "Ich glaube, ich bin dran.", en: "I think I'm next. / I think it's my turn.", use: "A polite way to claim your place without accusing anyone of pushing in." },
      { de: "Ich hätte gern zwei normale Brötchen und ein Körnerbrötchen, bitte.", en: "I'd like two plain rolls and one seeded roll, please.", use: "'Ich hätte gern ...' is the dependable polite order; neuter 'Brötchen' looks the same in singular and plural." },
      { de: "Ein halbes Roggenbrot, bitte.", en: "Half a loaf of rye bread, please.", use: "Many German bakeries sell large loaves by the half; 'halbes' takes the neuter ending." },
      { de: "Können Sie das Brot bitte schneiden?", en: "Could you slice the bread, please?", use: "Most bakeries can put a loaf through a slicing machine when asked." },
      { de: "Nicht zu dick, bitte.", en: "Not too thick, please.", use: "A useful short clarification for sliced bread, cheese or cold cuts." },
      { de: "Was ist das da mit den Körnern drauf?", en: "What's that one with the seeds on top?", use: "'das da' plus a visible feature is completely natural when you do not know a product's name." },
      { de: "Ist das ein Vollkornbrot?", en: "Is that wholemeal bread? / Is that whole-grain bread?", use: "'Vollkorn' describes the flour; seeds on the outside alone do not make bread wholemeal." },
      { de: "Ist das Brot von heute?", en: "Was this bread baked today? / Is this bread from today?", use: "'von heute' is the simple way to check whether something was made that day." },
      { de: "Welche Brötchen sind noch warm?", en: "Which rolls are still warm?", use: "'welche' asks staff to choose from the rolls currently available." },
      { de: "Ich nehme noch zwei Brezeln dazu.", en: "I'll have two pretzels as well.", use: "'dazunehmen' means adding something to an order already in progress." },
      { de: "Das war's, danke.", en: "That's all, thanks.", use: "The natural answer when staff ask 'Sonst noch etwas?' and the order is complete." },
      { de: "Können Sie das bitte getrennt einpacken?", en: "Could you wrap that separately, please?", use: "Useful for sweet and savoury food or purchases going to different households." },
      { de: "Eine Tragetasche brauche ich nicht, danke.", en: "I don't need a carrier bag, thanks.", use: "'die Tragetasche' clearly means the carrier bag, not the paper wrapping needed for the food." },
      { de: "Von der Salami hätte ich gern hundertfünfzig Gramm.", en: "I'd like 150 grams of the salami.", use: "Starting with 'Von der Salami' points to the item; 'hätte ich gern' keeps the request polite." },
      { de: "Bitte möglichst dünn geschnitten.", en: "Sliced as thinly as possible, please.", use: "A compact standard request at a cheese or cold-cuts counter." },
      { de: "Darf's ein bisschen mehr sein?", en: "Is a little more okay? / Is it all right if it's slightly over?", use: "Staff ask this when the amount on the scale is a little above what you requested; 'Darf's' contracts 'Darf es'." },
      { de: "Ja, das passt so.", en: "Yes, that's fine. / Yes, that's fine like that.", use: "Accepts the amount currently on the scale; it does not mean an item physically fits." },
      { de: "Können Sie mir davon ein Stück abschneiden?", en: "Could you cut me a piece of that?", use: "'davon' points back to the cheese, meat or cake without repeating its name." },
      { de: "Kann ich den Käse mal probieren?", en: "Could I try the cheese? / Could I taste the cheese?", use: "'mal' softens the request; tasting is normal at many cheese counters and market stalls." },
      { de: "Ist der Käse aus Rohmilch?", en: "Is the cheese made from raw milk?", use: "'aus Rohmilch' describes what the cheese is made from and can matter during pregnancy." },
      { de: "Sind die Erdbeeren aus der Region?", en: "Are these strawberries local? / Are the strawberries from the region?", use: "'aus der Region' is the common market wording for locally grown produce." },
      { de: "Welche Äpfel sind eher süß?", en: "Which apples are on the sweeter side?", use: "'eher' softens the comparison and asks for a tendency rather than a guarantee." },
      { de: "Sind die Avocados schon reif?", en: "Are the avocados ripe yet?", use: "'schon' asks whether the expected ripe stage has been reached." },
      { de: "Davon nehme ich ein halbes Kilo.", en: "I'll take half a kilo of those.", use: "'davon' avoids repeating the product name after pointing or asking a question about it." },
      { de: "Können Sie die Tomaten bitte in eine extra Tüte tun?", en: "Could you put the tomatoes in a separate bag, please?", use: "Everyday 'in eine Tüte tun' is more natural at a stall than a formal packing verb." },
      { de: "Haben Sie auch kleinere Stücke?", en: "Do you have any smaller pieces?", use: "Works for cheese, meat, cake and produce sold in pre-cut pieces." },
      { de: "Was kostet das pro Kilo?", en: "How much is that per kilo?", use: "The standard question when a sign shows no clear unit price." },
      { de: "Ist das der Stückpreis oder der Kilopreis?", en: "Is that the price per item or per kilo?", use: "A precise way to clarify a handwritten or ambiguous market sign." },
      { de: "Ich habe kein Bargeld dabei. Nehmen Sie auch Kartenzahlung?", en: "I don't have any cash on me. Do you take card payments as well?", use: "'Bargeld dabeihaben' means having cash with you; 'Nehmen Sie Kartenzahlung?' is useful at smaller stalls." },
    ],
    dialogues: [
      { title: "Sunday morning at the bakery", lines: [
        { speaker: "A", de: "Ich hätte gern zwei normale Brötchen und ein Körnerbrötchen.", en: "I'd like two plain rolls and one seeded roll." },
        { speaker: "B", de: "Gerne. Sonst noch etwas?", en: "Of course. Anything else?" },
        { speaker: "A", de: "Ein halbes Roggenbrot, bitte. Können Sie es schneiden?", en: "Half a loaf of rye bread, please. Could you slice it?" },
        { speaker: "B", de: "Natürlich. Darf es sonst noch etwas sein?", en: "Of course. Would you like anything else?" },
      ]},
      { title: "At the deli counter", lines: [
        { speaker: "A", de: "Von der Salami hätte ich gern hundertfünfzig Gramm.", en: "I'd like 150 grams of the salami." },
        { speaker: "B", de: "Darf's ein bisschen mehr sein?", en: "Is a little more okay?" },
        { speaker: "A", de: "Ja, das passt so. Bitte möglichst dünn geschnitten.", en: "Yes, that's fine. Sliced as thinly as possible, please." },
        { speaker: "B", de: "Gern. Möchten Sie noch etwas?", en: "Certainly. Would you like anything else?" },
      ]},
      { title: "Fruit at the weekly market", lines: [
        { speaker: "A", de: "Welche Äpfel sind eher süß?", en: "Which apples are on the sweeter side?" },
        { speaker: "B", de: "Diese hier. Sie kommen auch aus der Region.", en: "These ones. They're local as well." },
        { speaker: "A", de: "Dann nehme ich davon ein halbes Kilo.", en: "Then I'll take half a kilo of those." },
        { speaker: "B", de: "Gerne. Brauchen Sie eine Tüte?", en: "Certainly. Do you need a bag?" },
      ]},
    ],
  },

  part156: {
    label: "Part 156",
    level: "A2",
    theme: "At the drugstore: toiletries, laundry and photos",
    description: "Find everyday toiletries, choose suitable products for sensitive skin and laundry, then use the photo counter without confusing a drugstore with a pharmacy.",
    focus: "Practical dm/Rossmann-style German: ohne Duftstoffe, für empfindliche Haut, Reisegröße, Nachfüllpackung, Buntwäsche, Flecken and printing photos from a phone.",
    seeds: [
      { de: "die Zahnpasta", lookup: "Zahnpasta", fallbackEn: "toothpaste", tip: "noun", article: "die" },
      { de: "die Zahnbürste", lookup: "Zahnbürste", fallbackEn: "toothbrush", tip: "noun", article: "die" },
      { de: "die Borste", lookup: "Borste", fallbackEn: "bristle", tip: "noun", article: "die" },
      { de: "der Duftstoff", lookup: "Duftstoff", fallbackEn: "fragrance, perfume ingredient", tip: "noun", article: "der" },
      { de: "die Kopfhaut", lookup: "Kopfhaut", fallbackEn: "scalp", tip: "noun", article: "die" },
      { de: "die Feuchtigkeitscreme", lookup: "Feuchtigkeitscreme", fallbackEn: "moisturiser", tip: "noun", article: "die" },
      { de: "der Lichtschutzfaktor", lookup: "Lichtschutzfaktor", fallbackEn: "sun protection factor, SPF", tip: "noun", article: "der" },
      { de: "die Reisegröße", lookup: "Reisegröße", fallbackEn: "travel size", tip: "noun", article: "die" },
      { de: "die Nachfüllpackung", lookup: "Nachfüllpackung", fallbackEn: "refill pack", tip: "noun", article: "die" },
      { de: "das Waschmittel", lookup: "Waschmittel", fallbackEn: "laundry detergent", tip: "noun", article: "das" },
      { de: "die Buntwäsche", lookup: "Buntwäsche", fallbackEn: "coloured laundry, colours", tip: "noun", article: "die" },
      { de: "die Weißwäsche", lookup: "Weißwäsche", fallbackEn: "white laundry, whites", tip: "noun", article: "die" },
      { de: "der Weichspüler", lookup: "Weichspüler", fallbackEn: "fabric softener", tip: "noun", article: "der" },
      { de: "der Fleckenentferner", lookup: "Fleckenentferner", fallbackEn: "stain remover", tip: "noun", article: "der" },
      { de: "das Feuchttuch", lookup: "Feuchttuch", fallbackEn: "wet wipe", tip: "noun", article: "das" },
      { de: "die Binde", lookup: "Binde", fallbackEn: "sanitary pad", tip: "noun", article: "die" },
      { de: "die Kontaktlinsenlösung", lookup: "Kontaktlinsenlösung", fallbackEn: "contact-lens solution", tip: "noun", article: "die" },
      { de: "die Rasierklinge", lookup: "Rasierklinge", fallbackEn: "razor blade", tip: "noun", article: "die" },
    ],
    phrases: [
      { de: "Wo finde ich die Zahnpasta?", en: "Where can I find the toothpaste?", use: "A simple product-location question; German products normally 'stand' on a shelf, but 'finden' is safest when asking staff." },
      { de: "Ich suche eine Zahnbürste mit weichen Borsten.", en: "I'm looking for a toothbrush with soft bristles.", use: "Toothbrush choices are usually 'weich', 'mittel' and 'hart'; 'mit' takes dative plural." },
      { de: "Haben Sie dieses Shampoo auch ohne Duftstoffe?", en: "Do you have a fragrance-free version of this shampoo? / Do you have this shampoo without fragrance?", use: "'ohne Duftstoffe' is useful for allergies and sensitive skin; 'ohne' takes the accusative." },
      { de: "Ich brauche etwas für empfindliche Kopfhaut.", en: "I need something for a sensitive scalp.", use: "This asks for a suitable product without pretending to know which brand or ingredient is best." },
      { de: "Ist diese Creme fürs Gesicht oder für den Körper?", en: "Is this cream for the face or the body?", use: "'fürs' is the everyday contraction of 'für das'." },
      { de: "Ist die Creme auch für empfindliche Haut geeignet?", en: "Is the cream suitable for sensitive skin as well?", use: "The fixed pattern is 'für etwas geeignet sein'; 'für' takes the accusative." },
      { de: "Ich suche eine Feuchtigkeitscreme, die nicht fettet.", en: "I'm looking for a moisturiser that isn't greasy.", use: "Product descriptions use 'nicht fetten' for a cream that does not leave an oily layer." },
      { de: "Welchen Lichtschutzfaktor hat diese Sonnencreme?", en: "What SPF is this sunscreen?", use: "German packaging normally abbreviates 'Lichtschutzfaktor' to 'LSF'." },
      { de: "Ist die Sonnencreme wasserfest?", en: "Is the sunscreen water-resistant?", use: "'wasserfest' is the wording commonly printed on German packaging." },
      { de: "Gibt es das auch als Reisegröße?", en: "Does this come in a travel size?", use: "'als Reisegröße' asks whether the same product is available in a smaller travel format." },
      { de: "Haben Sie dafür eine Nachfüllpackung?", en: "Do you have a refill pack for that?", use: "'dafür' points back to a dispenser or product already being discussed." },
      { de: "Wo steht das Waschmittel?", en: "Where's the laundry detergent?", use: "Products 'stehen' on shelves in German; this sounds natural in a shop." },
      { de: "Ist das für Buntwäsche oder Weißwäsche?", en: "Is that for colours or whites?", use: "These are the basic German detergent categories: coloured laundry and white laundry." },
      { de: "Kann ich das auch für Wolle nehmen?", en: "Can I use that for wool as well?", use: "Everyday German often uses 'nehmen' for choosing or using a product; it sounds lighter than 'benutzen'." },
      { de: "Wie viel Waschmittel brauche ich pro Waschgang?", en: "How much detergent do I need per wash?", use: "'der Waschgang' is one machine cycle or load; 'pro' states the amount for each one." },
      { de: "Brauche ich dazu noch Weichspüler?", en: "Do I still need fabric softener with that?", use: "'dazu' means alongside the detergent already chosen." },
      { de: "Ich suche etwas gegen Rotweinflecken.", en: "I'm looking for something for red-wine stains.", use: "'etwas gegen ...' is the practical shop pattern for stain remover and non-prescription remedies." },
      { de: "Mein Kind wiegt zehn Kilo. Welche Windelgröße brauche ich?", en: "My child weighs ten kilos. What nappy size do I need? / What diaper size do I need?", use: "Nappy sizes on German packaging are based on the child's weight." },
      { de: "Haben Sie Feuchttücher ohne Parfüm?", en: "Do you have fragrance-free wet wipes? / Do you have unperfumed wet wipes?", use: "'ohne Parfüm' is common packaging language for sensitive skin." },
      { de: "Wo finde ich Tampons und Binden?", en: "Where can I find tampons and pads?", use: "Direct, neutral everyday language; 'die Binde' is a sanitary pad in this context." },
      { de: "Ich suche Tampons in der Saugstärke Normal.", en: "I'm looking for regular-absorbency tampons.", use: "'Normal' and 'Super' are familiar product labels; 'Saugstärke' means absorbency." },
      { de: "Ich brauche Kontaktlinsenlösung für weiche Linsen.", en: "I need contact-lens solution for soft lenses.", use: "'für weiche Linsen' prevents buying solution intended for a different lens type." },
      { de: "Haben Sie Rasierklingen für dieses Modell?", en: "Do you have razor blades for this model?", use: "Showing the handle or old packet makes 'dieses Modell' a natural reference." },
      { de: "Gibt es davon einen Tester?", en: "Is there a tester for this?", use: "'davon' points to the visible product without repeating its name; ask before opening a sealed one." },
      { de: "Die Farbe ist auf meiner Haut zu dunkel.", en: "The shade is too dark on my skin.", use: "'die Farbe' can mean the cosmetic shade when the product context is clear." },
      { de: "Kann ich hier Passbilder machen lassen?", en: "Can I have passport photos taken here?", use: "'etwas machen lassen' means arranging for the shop or machine to do it for you." },
      { de: "Ich möchte ein paar Fotos vom Handy ausdrucken.", en: "I'd like to print a few photos from my phone.", use: "Drugstore photo kiosks are common; 'vom Handy' contracts 'von dem Handy'." },
      { de: "Kann ich die Fotos sofort mitnehmen?", en: "Can I take the photos away straight away?", use: "This checks whether printing is instant rather than ready for collection later." },
      { de: "Die Packung ist beschädigt. Haben Sie noch eine andere?", en: "The package is damaged. Do you have another one?", use: "Feminine 'eine andere' stands in for 'eine andere Packung' without repeating the noun." },
      { de: "Das Preisschild fehlt. Was kostet das?", en: "The price label is missing. How much is this?", use: "A clear two-sentence request when a product or shelf has no visible price." },
    ],
    dialogues: [
      { title: "Finding shampoo and skin care", lines: [
        { speaker: "A", de: "Ich brauche etwas für empfindliche Kopfhaut.", en: "I need something for a sensitive scalp." },
        { speaker: "B", de: "Soll es ohne Duftstoffe sein?", en: "Would you like it to be fragrance-free?" },
        { speaker: "A", de: "Ja, bitte. Und haben Sie auch eine Feuchtigkeitscreme fürs Gesicht, ebenfalls ohne Duftstoffe?", en: "Yes, please. And do you also have a fragrance-free moisturiser for the face?" },
        { speaker: "B", de: "Ja, diese hier ist ohne Duftstoffe und für empfindliche Haut geeignet.", en: "Yes, this one is fragrance-free and suitable for sensitive skin." },
      ]},
      { title: "Choosing laundry detergent", lines: [
        { speaker: "A", de: "Ist das Waschmittel für Buntwäsche oder Weißwäsche?", en: "Is this detergent for colours or whites?" },
        { speaker: "B", de: "Für Buntwäsche. Für Wolle brauchen Sie ein anderes.", en: "For colours. You'll need a different one for wool." },
        { speaker: "A", de: "Brauche ich dazu noch Weichspüler?", en: "Do I need fabric softener with it?" },
        { speaker: "B", de: "Nein, nicht unbedingt. Das hängt von der Wäsche ab.", en: "No, not necessarily. It depends on the laundry." },
      ]},
      { title: "Printing photos from a phone", lines: [
        { speaker: "A", de: "Ich möchte ein paar Fotos vom Handy ausdrucken.", en: "I'd like to print a few photos from my phone." },
        { speaker: "B", de: "Das geht dort am Automaten.", en: "You can do that at the machine over there." },
        { speaker: "A", de: "Kann ich die Fotos sofort mitnehmen?", en: "Can I take the photos away straight away?" },
        { speaker: "B", de: "Ja, bei diesem Format dauert es nur ein paar Minuten.", en: "Yes, it only takes a few minutes for this size." },
      ]},
    ],
  },

  part157: {
    label: "Part 157",
    level: "A1-A2",
    theme: "Talking to your pets",
    description: "Use the short, warm German people actually say to dogs and cats: everyday commands, walks, food, praise, cuddles, grooming and reassurance when they are unwell.",
    focus: "Natural pet-directed German: short commands such as Sitz and Bleib, warm praise, feeding and walking routines, and calm language for care and vet visits.",
    seeds: [
      { de: "das Leckerli", lookup: "Leckerli", fallbackEn: "treat", tip: "noun", article: "das" },
      { de: "das Futter", lookup: "Futter", fallbackEn: "pet food, animal feed", tip: "noun", article: "das" },
      { de: "der Napf", lookup: "Napf", fallbackEn: "pet bowl", tip: "noun", article: "der" },
      { de: "die Pfote", lookup: "Pfote", fallbackEn: "paw", tip: "noun", article: "die" },
      { de: "die Leine", lookup: "Leine", fallbackEn: "lead, leash", tip: "noun", article: "die" },
      { de: "das Geschirr", lookup: "Geschirr", fallbackEn: "harness", tip: "noun", article: "das" },
      { de: "das Körbchen", lookup: "Körbchen", fallbackEn: "pet bed, basket", tip: "noun", article: "das" },
      { de: "das Fell", lookup: "Fell", fallbackEn: "fur, coat", tip: "noun", article: "das" },
      { de: "die Bürste", lookup: "Bürste", fallbackEn: "brush", tip: "noun", article: "die" },
      { de: "die Kralle", lookup: "Kralle", fallbackEn: "claw", tip: "noun", article: "die" },
      { de: "die Wunde", lookup: "Wunde", fallbackEn: "wound", tip: "noun", article: "die" },
      { de: "die Medizin", lookup: "Medizin", fallbackEn: "medicine", tip: "noun", article: "die" },
      { de: "der Trichter", lookup: "Trichter", fallbackEn: "cone, funnel", tip: "noun", article: "der" },
      { de: "kuscheln", lookup: "kuscheln", fallbackEn: "to cuddle", tip: "verb" },
      { de: "streicheln", lookup: "streicheln", fallbackEn: "to stroke, pet", tip: "verb" },
      { de: "füttern", lookup: "füttern", fallbackEn: "to feed", tip: "verb" },
      { de: "bellen", lookup: "bellen", fallbackEn: "to bark", tip: "verb" },
      { de: "miauen", lookup: "miauen", fallbackEn: "to meow", tip: "verb" },
      { de: "kratzen", lookup: "kratzen", fallbackEn: "to scratch", tip: "verb" },
      { de: "lecken", lookup: "lecken", fallbackEn: "to lick", tip: "verb" },
      { de: "anhänglich", lookup: "anhänglich", fallbackEn: "affectionate, clingy", tip: "adjective" },
    ],
    phrases: [
      { de: "Komm her!", en: "Come here!", use: "The everyday command for calling a pet over. In relaxed speech, 'Komm mal her' sounds a little softer.", group: "pet-commands" },
      { de: "Bleib da!", en: "Stay there!", use: "'Bleib' is the du-command from 'bleiben'. Dog-training classes often use the even shorter 'Bleib!'", group: "pet-commands" },
      { de: "Sitz!", en: "Sit!", use: "The standard German dog command. It is the noun-like command 'Sitz', not the full sentence 'Setz dich hin'.", group: "pet-commands" },
      { de: "Platz!", en: "Lie down! / Down!", use: "As a dog command, 'Platz!' means lie down. Away from pet training, 'der Platz' means a place, seat or square.", group: "pet-commands" },
      { de: "Gib Pfötchen!", en: "Give me your paw! / Paw!", use: "'Pfötchen' is the affectionate small form of 'Pfote'. This is the usual command for asking a dog to offer a paw.", group: "pet-commands" },
      { de: "Bei Fuß!", en: "Heel!", use: "The established training command for walking closely beside your leg. Outside training, people also shorten it to 'Fuß!'.", group: "pet-commands" },
      { de: "Warte kurz!", en: "Wait a moment!", use: "A natural home command when opening a door, clipping on a lead or putting food down.", group: "pet-commands" },
      { de: "Ganz langsam.", en: "Easy. / Slowly.", use: "Said calmly to slow an excited or nervous animal down. The gentle tone matters more than making it a full sentence.", group: "pet-commands" },
      { de: "Nein, lass das!", en: "No, leave it!", use: "'Lass das' tells the animal to stop touching or doing something. If something is already in its mouth, owners often use 'Aus!'.", group: "pet-commands" },
      { de: "Komm, gib das her!", en: "Come on, give me that!", use: "'etwas hergeben' means handing something over to the speaker. This sounds natural when retrieving a sock or toy.", group: "pet-commands" },
      { de: "Runter vom Sofa!", en: "Get off the sofa! / Get down from the couch!", use: "Pet commands often leave out the verb. The complete version is 'Geh vom Sofa runter', but owners normally use this short form.", group: "pet-commands" },
      { de: "Nicht hochspringen!", en: "Don't jump up!", use: "Use this when a dog jumps up at a person. 'hochspringen' describes the upward jump, not jumping over something.", group: "pet-commands" },

      { de: "Komm, wir gehen Gassi.", en: "Come on, let's go for a walk.", use: "'Gassi gehen' is the normal phrase for walking a dog. You do not use it for a walk without a dog.", group: "walk-time" },
      { de: "Willst du raus?", en: "Do you want to go out?", use: "The ordinary question to a dog at the door. 'raus' is the conversational form of 'heraus' or 'hinaus'.", group: "walk-time" },
      { de: "Musst du mal raus?", en: "Do you need to go out?", use: "With a pet, this usually means needing the toilet. The little 'mal' makes the question sound natural and gentle.", group: "walk-time" },
      { de: "Komm, hier lang!", en: "Come on, this way!", use: "A short direction while walking. German says 'hier lang' where English says 'this way'.", group: "walk-time" },
      { de: "Bleib schön bei mir.", en: "Stay close to me.", use: "Here 'schön' does not mean beautiful; it softens the instruction and encourages the animal to remain nearby.", group: "walk-time" },
      { de: "Nicht auf die Straße!", en: "Stay out of the road! / Don't go into the street!", use: "A natural urgent warning. German can use this short phrase without a verb when the danger is obvious.", group: "walk-time" },

      { de: "Na, hast du Hunger?", en: "So, are you hungry? / Hungry?", use: "'Na' is a warm conversational opener used constantly with pets. It does not need a separate English translation.", group: "food-time" },
      { de: "Du kriegst gleich dein Futter.", en: "You'll get your food in a moment.", use: "'kriegen' is the ordinary spoken alternative to 'bekommen'. 'gleich' means very soon here, not exactly equal.", group: "food-time" },
      { de: "Willst du ein Leckerli?", en: "Do you want a treat?", use: "'das Leckerli' is the everyday word for a small pet treat. The plural is 'Leckerlis'.", group: "food-time" },
      { de: "Hey, nicht so schnell!", en: "Hey, not so fast!", use: "A natural warning to an animal gulping food. The situation supplies the missing verb, so German keeps it short.", group: "food-time" },
      { de: "Das darfst du nicht fressen.", en: "You mustn't eat that. / You're not allowed to eat that.", use: "Animals 'fressen'; people 'essen'. 'darfst du nicht' says something is not allowed, rather than that the animal cannot do it.", group: "food-time" },
      { de: "Klau nichts vom Tisch!", en: "Don't steal anything from the table!", use: "'klauen' is the common conversational word for stealing. The careful written imperative is 'Klaue', but spoken German usually drops the final e.", group: "food-time" },
      { de: "Trink erst mal was.", en: "Have a drink first. / Drink something first.", use: "'erst mal' means for now or first of all. 'was' is the everyday short form of 'etwas'.", group: "food-time" },

      { de: "Na, hast du mich vermisst?", en: "Did you miss me?", use: "A warm greeting when you come home. The perfect tense is what German normally uses for this recent event.", group: "pet-affection" },
      { de: "Du bist mein kleiner Schatz.", en: "You're my little sweetheart.", use: "'Schatz' is a very common affectionate name for people and pets. Change 'kleiner' to 'kleine' for a female animal.", group: "pet-affection" },
      { de: "Komm her, wir kuscheln ein bisschen.", en: "Come here, let's have a cuddle.", use: "'kuscheln' is to cuddle or snuggle. German uses the present tense after 'wir' as a warm suggestion.", group: "pet-affection" },
      { de: "Braver Junge!", en: "Good boy!", use: "The normal praise for a male dog. For a female dog, say 'Braves Mädchen!'.", group: "pet-affection" },
      { de: "Braves Mädchen!", en: "Good girl!", use: "The normal praise for a female dog. The ending changes because 'Mädchen' is grammatically neuter: 'braves'.", group: "pet-affection" },
      { de: "Fein gemacht!", en: "Good job! / Well done!", use: "Very common praise during training. 'Fein!' on its own is also enough when the pet has followed a command.", group: "pet-affection" },
      { de: "Du bist heute aber anhänglich.", en: "You're very clingy today. / You're extra affectionate today.", use: "With a pet, 'anhänglich' can sound fond rather than critical. 'aber' adds friendly surprise here; it does not mean but.", group: "pet-affection" },
      { de: "Machst du mir ein bisschen Platz?", en: "Can you make a little room for me?", use: "A playful question to a pet occupying the sofa or bed. German often uses a present-tense question as a gentle request.", group: "pet-affection" },

      { de: "Zeig mal deine Pfote.", en: "Let me see your paw. / Show me your paw.", use: "'Zeig mal' is gentler than a bare command. Use it before checking for a thorn, cut or sore pad.", group: "pet-care" },
      { de: "Wo tut's dir denn weh?", en: "Where does it hurt?", use: "'tut's' is spoken 'tut es'. A pet cannot answer in words, but this is exactly how owners talk while checking it over.", group: "pet-care" },
      { de: "Lass mich das mal anschauen.", en: "Let me have a look at that.", use: "'Lass mich mal ...' is a natural, gentle request. 'anschauen' means to take a look at something closely.", group: "pet-care" },
      { de: "Nicht lecken!", en: "Don't lick it!", use: "A short warning after treatment or when a pet worries a sore spot. The object is obvious, so German leaves it out.", group: "pet-care" },
      { de: "Hör auf zu kratzen.", en: "Stop scratching.", use: "The pattern is 'aufhören zu' followed by the action. The separable verb becomes 'Hör ... auf' in the command.", group: "pet-care" },
      { de: "Du musst jetzt deine Medizin nehmen.", en: "You need to take your medicine now.", use: "German uses 'Medizin nehmen' just like English uses 'take medicine'. The sentence also works when coaxing medicine hidden in food.", group: "pet-care" },
      { de: "Wir fahren jetzt zum Tierarzt.", en: "We're going to the vet now.", use: "The usual way to announce a vet visit to a pet. 'zum Tierarzt' can mean the practice generally, whether the vet is a man or a woman.", group: "pet-care" },
      { de: "Das piekst nur ganz kurz.", en: "It'll only prick for a second. / It'll only sting for a moment.", use: "A gentle reassurance before an injection. 'pieksen' is the everyday word for a small, sharp prick.", group: "pet-care" },
      { de: "Gleich hast du's geschafft.", en: "You're nearly done. / It'll be over in a moment.", use: "'du's' is spoken 'du es'. Owners use this to reassure a pet near the end of an examination or treatment.", long: "Gleich hast du es geschafft.", group: "pet-care" },
      { de: "Den Trichter musst du noch anlassen.", en: "You still need to keep the cone on.", use: "After an operation, 'der Trichter' is the protective cone. 'anlassen' means keeping something on rather than switching it on here.", group: "pet-care" },
      { de: "Keine Angst, ich bleib die ganze Zeit bei dir.", en: "Don't be scared, I'll stay with you the whole time.", use: "A calm reassurance at the vet. 'bleib' is the normal spoken form of 'bleibe'; the full form is also correct.", long: "Keine Angst, ich bleibe die ganze Zeit bei dir.", group: "pet-care" },
      { de: "Komm, ich mach dich sauber.", en: "Come on, I'll clean you up.", use: "'jemanden sauber machen' is the everyday phrase for cleaning mud or dirt off a pet.", group: "pet-care" },
      { de: "Du hast Schlamm an den Pfoten.", en: "You've got mud on your paws.", use: "German uses 'an den Pfoten' for dirt attached to the paws. The plural after 'an' is dative here.", group: "pet-care" },
      { de: "Jetzt wird gebürstet.", en: "Time for a brush. / You're getting brushed now.", use: "This impersonal passive is a playful way to announce an unavoidable routine without repeatedly saying 'you'.", group: "pet-care" },
      { de: "Du brauchst dringend ein Bad.", en: "You really need a bath.", use: "'dringend' literally means urgently, but owners often use it humorously when a pet smells or is covered in mud.", group: "pet-care" },
      { de: "Komm, ich trockne dich ab.", en: "Come on, I'll dry you off.", use: "Separable 'abtrocknen' becomes 'trockne ... ab'. This is what you say after rain, a bath or a muddy walk.", group: "pet-care" },

      { de: "Ab ins Körbchen!", en: "Off to bed! / Into your bed!", use: "A cheerful bedtime instruction. 'das Körbchen' is a pet bed even when it is not literally a wicker basket.", group: "pet-routine" },
      { de: "Warum miaust du denn so?", en: "Why are you meowing like that?", use: "'denn' makes the question sound curious rather than annoyed. The verb for a cat's sound is 'miauen'.", group: "pet-routine" },
      { de: "Was bellst du denn?", en: "What are you barking at? / Why are you barking?", use: "This common pet-directed question asks what has prompted the barking. English normally needs 'at' or 'why'.", group: "pet-routine" },
      { de: "Jetzt hör mal auf zu bellen.", en: "Stop barking now. / Come on, stop barking.", use: "'jetzt' and 'mal' make this sound like something an owner says after the barking has carried on, not a formal command.", group: "pet-routine" },
      { de: "Hast du wieder was angestellt?", en: "Have you been up to something again? / What have you done this time?", use: "'etwas anstellen' is the everyday phrase for doing something naughty. The pet's guilty look supplies the context.", group: "pet-routine" },
      { de: "Wo warst du denn schon wieder?", en: "Where have you been this time?", use: "'schon wieder' conveys that the disappearing act has happened before; 'denn' keeps the question conversational.", group: "pet-routine" },
      { de: "Du bist ja klatschnass!", en: "You're absolutely soaked!", use: "'klatschnass' is a vivid everyday word for completely wet. 'ja' marks the obvious surprise when the pet comes back in.", group: "pet-routine" },
    ],
    dialogues: [
      { title: "Getting ready for a walk", lines: [
        { speaker: "A", de: "Na, musst du mal raus?", en: "So, do you need to go out?" },
        { speaker: "B", de: "Warte kurz, ich hol nur schnell die Leine.", en: "Wait a moment, I'll just quickly get the lead." },
        { speaker: "B", de: "So, komm her. Jetzt machen wir das Geschirr dran.", en: "Right, come here. Let's put your harness on now." },
        { speaker: "B", de: "Los geht's, wir gehen Gassi!", en: "Off we go, let's go for a walk!" },
      ]},
      { title: "A muddy return home", lines: [
        { speaker: "A", de: "Du bist ja völlig nass und hast Schlamm an allen Pfoten!", en: "You're completely soaked and you've got mud on every paw!" },
        { speaker: "A", de: "Bleib kurz da, ich hole ein Handtuch.", en: "Stay there a moment, I'll get a towel." },
        { speaker: "A", de: "Komm, ich trockne dich erst mal ab.", en: "Come on, I'll dry you off first." },
        { speaker: "A", de: "Fein gemacht. Jetzt darfst du rein.", en: "Good job. You can come inside now." },
      ]},
      { title: "Keeping calm at the vet", lines: [
        { speaker: "A", de: "Keine Angst, ich bin direkt bei dir.", en: "Don't be scared, I'm right here with you." },
        { speaker: "A", de: "Zeig der Tierärztin mal deine Pfote.", en: "Let the vet see your paw." },
        { speaker: "B", de: "Ich schaue mir die Stelle nur kurz an.", en: "I'm only going to look at the sore spot for a moment." },
        { speaker: "A", de: "Ganz ruhig. Danach kriegst du ein Leckerli.", en: "Easy. You'll get a treat afterwards." },
      ]},
    ],
  },
};
