import type { Blueprint, VocabSeed } from "./types";

/**
 * Words chosen by asking the course what it does NOT teach.
 *
 * THE METHOD. Every earlier pack started from a source — a frequency bank, an
 * immersion export, a spreadsheet — and kept whatever of it was new. Those
 * sources are spent: the 2,502 commonest words are taught to the last one, and
 * the eight-thousand-row sheet had 502 words left in it, which parts 585-604
 * took. So this one starts from the other end. Thirty everyday fields were
 * probed with twenty ordinary words each against the BUILT catalogue, and the
 * fields that answered worst decide what gets written. Naturwissenschaft came
 * back at 35 per cent, the worst of the thirty: der Magnet, die Säure, das
 * Molekül and der Widerstand were all missing while the kitchen and the
 * bathroom were complete.
 *
 * WHY THAT FIELD IS WORTH TEACHING. It is not school physics for its own sake.
 * These are the words a doctor uses for a test result, a landlord for damp, a
 * news report for a heatwave, and every appliance manual ever printed.
 *
 * Checked against the built catalogue rather than the pack files, so a word
 * already taught under another spelling did not count as new — and against the
 * umlaut fold the progress id uses, which is why rosten and die Spule are not
 * here: they collide with rösten and die Spüle and could never become cards.
 *
 * Append-only after release, like every word pack: progress is global by lemma
 * and pack order is curriculum order.
 */
const focus = "The words behind everyday explanations: what things are made of, what makes them move, and how any of it is measured.";

const pack = (label: string, level: string, theme: string, description: string, seeds: VocabSeed[]): Blueprint => ({
  label,
  level,
  theme,
  description,
  focus,
  seeds,
  dialogues: [],
  phrases: [],
});

export const fieldWordPartBlueprints: Record<string, Blueprint> = {
  part605: pack("Part 605", "B1", "What makes things move", "Force, friction and the simple machines a manual assumes you know.", [
    { de: "die Reibung", lookup: "Reibung", fallbackEn: "friction", tip: "noun", article: "die" },
    { de: "die Dichte", lookup: "Dichte", fallbackEn: "density", tip: "noun", article: "die" },
    { de: "der Hebel", lookup: "Hebel", fallbackEn: "lever", tip: "noun", article: "der", use: "the bar you push, and the lever on a machine" },
    { de: "das Zahnrad", lookup: "Zahnrad", fallbackEn: "gear, cog", tip: "noun", article: "das" },
    { de: "der Kolben", lookup: "Kolben", fallbackEn: "piston", tip: "noun", article: "der", use: "in an engine; in a lab it is the round flask" },
    { de: "der Auftrieb", lookup: "Auftrieb", fallbackEn: "buoyancy, lift", tip: "noun", article: "der", use: "what holds a boat up and what a wing makes" },
    { de: "die Trägheit", lookup: "Trägheit", fallbackEn: "inertia", tip: "noun", article: "die", use: "in physics; of a person it means sluggishness" },
    { de: "die Umdrehung", lookup: "Umdrehung", fallbackEn: "revolution, turn", tip: "noun", article: "die", use: "one full turn: 3.000 Umdrehungen pro Minute" },
    { de: "der Wirkungsgrad", lookup: "Wirkungsgrad", fallbackEn: "efficiency", tip: "noun", article: "der", use: "of an engine or a boiler, given as a percentage" },
    { de: "das Vakuum", lookup: "Vakuum", fallbackEn: "vacuum", tip: "noun", article: "das" },
    { de: "die Schwingung", lookup: "Schwingung", fallbackEn: "vibration, oscillation", tip: "noun", article: "die" },
    { de: "die Frequenz", lookup: "Frequenz", fallbackEn: "frequency", tip: "noun", article: "die" },
    { de: "der Schall", lookup: "Schall", fallbackEn: "sound", tip: "noun", article: "der", use: "sound as a physical thing; der Klang is how it sounds" },
    { de: "das Echo", lookup: "Echo", fallbackEn: "echo", tip: "noun", article: "das" },
    { de: "die Brechung", lookup: "Brechung", fallbackEn: "refraction", tip: "noun", article: "die", use: "why a straw looks bent in a glass of water" },
    { de: "die Wärmeleitung", lookup: "Wärmeleitung", fallbackEn: "heat conduction", tip: "noun", article: "die" },
    { de: "der Schmelzpunkt", lookup: "Schmelzpunkt", fallbackEn: "melting point", tip: "noun", article: "der" },
    { de: "der Siedepunkt", lookup: "Siedepunkt", fallbackEn: "boiling point", tip: "noun", article: "der" },
  ]),
  part606: pack("Part 606", "B1", "Electricity in the house", "The words on a fuse box, on a charger and on the bill from an electrician.", [
    { de: "der Stromkreis", lookup: "Stromkreis", fallbackEn: "circuit", tip: "noun", article: "der" },
    { de: "die Stromstärke", lookup: "Stromstärke", fallbackEn: "current", tip: "noun", article: "die", use: "measured in amps; die Spannung is the voltage" },
    { de: "der Widerstand", lookup: "Widerstand", fallbackEn: "resistance", tip: "noun", article: "der", use: "electrical resistance, and resistance to anything else" },
    { de: "die Ladung", lookup: "Ladung", fallbackEn: "charge, load", tip: "noun", article: "die", use: "the charge in a battery, and the load on a lorry" },
    { de: "der Magnet", lookup: "Magnet", fallbackEn: "magnet", tip: "noun", article: "der" },
    { de: "das Magnetfeld", lookup: "Magnetfeld", fallbackEn: "magnetic field", tip: "noun", article: "das" },
    { de: "der Funke", lookup: "Funke", fallbackEn: "spark", tip: "noun", article: "der" },
  ]),
  part607: pack("Part 607", "B1", "What things are made of", "Acids, gases and metals, on a label and in a lesson.", [
    { de: "die Säure", lookup: "Säure", fallbackEn: "acid", tip: "noun", article: "die" },
    { de: "die Lauge", lookup: "Lauge", fallbackEn: "alkaline solution, lye", tip: "noun", article: "die", use: "the opposite of an acid, and the lye a pretzel is dipped in" },
    { de: "das Gemisch", lookup: "Gemisch", fallbackEn: "mixture", tip: "noun", article: "das" },
    { de: "das Molekül", lookup: "Molekül", fallbackEn: "molecule", tip: "noun", article: "das" },
    { de: "das Atom", lookup: "Atom", fallbackEn: "atom", tip: "noun", article: "das" },
    { de: "das Elektron", lookup: "Elektron", fallbackEn: "electron", tip: "noun", article: "das" },
    { de: "der Feststoff", lookup: "Feststoff", fallbackEn: "solid (state of matter)", tip: "noun", article: "der", use: "a solid as a state of matter" },
    { de: "die Flüssigkeit", lookup: "Flüssigkeit", fallbackEn: "fluid, liquid", tip: "noun", article: "die" },
    { de: "der Dampf", lookup: "Dampf", fallbackEn: "steam, vapour", tip: "noun", article: "der" },
    { de: "die Legierung", lookup: "Legierung", fallbackEn: "alloy", tip: "noun", article: "die" },
    { de: "das Blei", lookup: "Blei", fallbackEn: "lead", tip: "noun", article: "das", use: "the metal; bleifrei on a petrol pump means unleaded" },
    { de: "das Zink", lookup: "Zink", fallbackEn: "zinc", tip: "noun", article: "das" },
    { de: "das Messing", lookup: "Messing", fallbackEn: "brass", tip: "noun", article: "das" },
    { de: "der Schwefel", lookup: "Schwefel", fallbackEn: "sulphur", tip: "noun", article: "der" },
    { de: "der Kohlenstoff", lookup: "Kohlenstoff", fallbackEn: "carbon", tip: "noun", article: "der" },
    { de: "der Sauerstoff", lookup: "Sauerstoff", fallbackEn: "oxygen", tip: "noun", article: "der" },
    { de: "der Wasserstoff", lookup: "Wasserstoff", fallbackEn: "hydrogen", tip: "noun", article: "der" },
    { de: "der Stickstoff", lookup: "Stickstoff", fallbackEn: "nitrogen", tip: "noun", article: "der" },
    { de: "das Kohlendioxid", lookup: "Kohlendioxid", fallbackEn: "carbon dioxide", tip: "noun", article: "das" },
    { de: "die Faser", lookup: "Faser", fallbackEn: "fibre", tip: "noun", article: "die" },
    { de: "der Klebstoff", lookup: "Klebstoff", fallbackEn: "adhesive, glue", tip: "noun", article: "der" },
    { de: "das Lösungsmittel", lookup: "Lösungsmittel", fallbackEn: "solvent", tip: "noun", article: "das" },
    { de: "der Kristall", lookup: "Kristall", fallbackEn: "crystal", tip: "noun", article: "der" },
    { de: "das Gestein", lookup: "Gestein", fallbackEn: "rock", tip: "noun", article: "das", use: "rock as a material; der Stein is a single stone" },
    { de: "der Lehm", lookup: "Lehm", fallbackEn: "clay, loam", tip: "noun", article: "der", use: "the heavy soil, and what old walls are built of" },
    { de: "verdampfen", lookup: "verdampfen", fallbackEn: "to evaporate", tip: "verb", use: "to boil away; verdunsten is the slow kind at room temperature" },
    { de: "sieden", lookup: "sieden", fallbackEn: "to boil, to simmer", tip: "verb", use: "the technical word; kochen is what a kitchen says" },
    { de: "ätzen", lookup: "ätzen", fallbackEn: "to corrode, to etch", tip: "verb", use: "what an acid does to a surface" },
  ]),
  part608: pack("Part 608", "B1", "Bodies and living things", "The biology behind a test result and a nature programme.", [
    { de: "das Gewebe", lookup: "Gewebe", fallbackEn: "tissue", tip: "noun", article: "das", use: "body tissue, and woven fabric" },
    { de: "das Organ", lookup: "Organ", fallbackEn: "organ", tip: "noun", article: "das" },
    { de: "der Nerv", lookup: "Nerv", fallbackEn: "nerve", tip: "noun", article: "der", use: "Das geht mir auf die Nerven = that gets on my nerves" },
    { de: "das Skelett", lookup: "Skelett", fallbackEn: "skeleton", tip: "noun", article: "das" },
    { de: "das Gen", lookup: "Gen", fallbackEn: "gene", tip: "noun", article: "das" },
    { de: "die Vererbung", lookup: "Vererbung", fallbackEn: "heredity, inheritance", tip: "noun", article: "die", use: "of traits; das Erbe is what you inherit from a will" },
    { de: "die Gattung", lookup: "Gattung", fallbackEn: "genus, kind", tip: "noun", article: "die", use: "in biology, and a genre in art" },
    { de: "die Nahrungskette", lookup: "Nahrungskette", fallbackEn: "food chain", tip: "noun", article: "die" },
    { de: "die Fortpflanzung", lookup: "Fortpflanzung", fallbackEn: "reproduction", tip: "noun", article: "die" },
    { de: "der Keim", lookup: "Keim", fallbackEn: "germ, sprout", tip: "noun", article: "der", use: "the germ that makes you ill, and the shoot on a seed" },
    { de: "die Bakterie", lookup: "Bakterie", fallbackEn: "bacterium", tip: "noun", article: "die", use: "usually said in the plural: Bakterien" },
    { de: "die Alge", lookup: "Alge", fallbackEn: "alga", tip: "noun", article: "die", use: "usually said in the plural: Algen im Teich" },
    { de: "der Stängel", lookup: "Stängel", fallbackEn: "stem, stalk", tip: "noun", article: "der" },
    { de: "die Photosynthese", lookup: "Photosynthese", fallbackEn: "photosynthesis", tip: "noun", article: "die" },
  ]),
  part609: pack("Part 609", "B1", "Measuring and working it out", "The instruments, the shapes and the arithmetic a result is written in.", [
    { de: "die Skala", lookup: "Skala", fallbackEn: "scale", tip: "noun", article: "die", use: "the markings you read off; die Waage is what you weigh on" },
    { de: "das Thermometer", lookup: "Thermometer", fallbackEn: "thermometer", tip: "noun", article: "das" },
    { de: "der Messbecher", lookup: "Messbecher", fallbackEn: "measuring jug", tip: "noun", article: "der" },
    { de: "das Mikroskop", lookup: "Mikroskop", fallbackEn: "microscope", tip: "noun", article: "das" },
    { de: "das Fernrohr", lookup: "Fernrohr", fallbackEn: "spyglass", tip: "noun", article: "das", use: "the handheld kind; das Teleskop is the big one" },
    { de: "das Teleskop", lookup: "Teleskop", fallbackEn: "telescope", tip: "noun", article: "das" },
    { de: "das Reagenzglas", lookup: "Reagenzglas", fallbackEn: "test tube", tip: "noun", article: "das" },
    { de: "die Pipette", lookup: "Pipette", fallbackEn: "pipette, dropper", tip: "noun", article: "die" },
    { de: "die Auswertung", lookup: "Auswertung", fallbackEn: "analysis, evaluation", tip: "noun", article: "die", use: "what you do with the results once they are in" },
    { de: "die Formel", lookup: "Formel", fallbackEn: "formula", tip: "noun", article: "die" },
    { de: "die Gleichung", lookup: "Gleichung", fallbackEn: "equation", tip: "noun", article: "die" },
    { de: "die Konstante", lookup: "Konstante", fallbackEn: "constant (in maths)", tip: "noun", article: "die" },
    { de: "die Potenz", lookup: "Potenz", fallbackEn: "power, exponent", tip: "noun", article: "die", use: "zwei hoch drei is two to the power of three" },
    { de: "der Durchmesser", lookup: "Durchmesser", fallbackEn: "diameter", tip: "noun", article: "der" },
    { de: "der Radius", lookup: "Radius", fallbackEn: "radius", tip: "noun", article: "der" },
    { de: "der Kegel", lookup: "Kegel", fallbackEn: "cone", tip: "noun", article: "der", use: "the shape, and the pin you knock down at bowling" },
    { de: "die Pyramide", lookup: "Pyramide", fallbackEn: "pyramid", tip: "noun", article: "die" },
    { de: "die Symmetrie", lookup: "Symmetrie", fallbackEn: "symmetry", tip: "noun", article: "die" },
  ]),
  part610: pack("Part 610", "B2", "The earth and the sky", "What the weather report, the climate page and the space news are talking about.", [
    { de: "die Erosion", lookup: "Erosion", fallbackEn: "erosion", tip: "noun", article: "die" },
    { de: "der Krater", lookup: "Krater", fallbackEn: "crater", tip: "noun", article: "der" },
    { de: "die Ozonschicht", lookup: "Ozonschicht", fallbackEn: "ozone layer", tip: "noun", article: "die" },
    { de: "der Treibhauseffekt", lookup: "Treibhauseffekt", fallbackEn: "greenhouse effect", tip: "noun", article: "der" },
    { de: "die Erderwärmung", lookup: "Erderwärmung", fallbackEn: "global warming", tip: "noun", article: "die" },
    { de: "die Windstärke", lookup: "Windstärke", fallbackEn: "wind force", tip: "noun", article: "die", use: "given as a number on the Beaufort scale" },
    { de: "der Komet", lookup: "Komet", fallbackEn: "comet", tip: "noun", article: "der" },
    { de: "der Meteorit", lookup: "Meteorit", fallbackEn: "meteorite", tip: "noun", article: "der" },
    { de: "die Galaxie", lookup: "Galaxie", fallbackEn: "galaxy", tip: "noun", article: "die" },
    { de: "die Sonnenfinsternis", lookup: "Sonnenfinsternis", fallbackEn: "solar eclipse", tip: "noun", article: "die" },
    { de: "die Schwerelosigkeit", lookup: "Schwerelosigkeit", fallbackEn: "weightlessness", tip: "noun", article: "die" },
    { de: "die Raumfahrt", lookup: "Raumfahrt", fallbackEn: "space travel", tip: "noun", article: "die" },
    { de: "die Raumstation", lookup: "Raumstation", fallbackEn: "space station", tip: "noun", article: "die" },
  ]),
part611: pack("Part 611", "B1", "A ship and its parts", "What the pieces of a boat are called, from the keel up.", [
    { de: "der Rumpf", lookup: "Rumpf", fallbackEn: "hull", tip: "noun", article: "der", use: "of a ship or a plane; of a person it is the torso" },
    { de: "das Heck", lookup: "Heck", fallbackEn: "stern, rear", tip: "noun", article: "das", use: "the back of a boat or a car" },
    { de: "der Mast", lookup: "Mast", fallbackEn: "mast", tip: "noun", article: "der" },
    { de: "der Kiel", lookup: "Kiel", fallbackEn: "keel", tip: "noun", article: "der" },
    { de: "das Deck", lookup: "Deck", fallbackEn: "deck", tip: "noun", article: "das" },
    { de: "die Reling", lookup: "Reling", fallbackEn: "railing", tip: "noun", article: "die", use: "the rail you lean on at the edge of a deck" },
    { de: "die Kajüte", lookup: "Kajüte", fallbackEn: "cabin", tip: "noun", article: "die", use: "the room you sleep in on a boat" },
    { de: "das Steuerrad", lookup: "Steuerrad", fallbackEn: "steering wheel", tip: "noun", article: "das" },
    { de: "das Segel", lookup: "Segel", fallbackEn: "sail", tip: "noun", article: "das" },
    { de: "das Segeltuch", lookup: "Segeltuch", fallbackEn: "canvas", tip: "noun", article: "das" },
    { de: "der Anker", lookup: "Anker", fallbackEn: "anchor", tip: "noun", article: "der" },
    { de: "das Ruder", lookup: "Ruder", fallbackEn: "oar, rudder", tip: "noun", article: "das", use: "the oar you row with, and the rudder that steers" },
    { de: "das Paddel", lookup: "Paddel", fallbackEn: "paddle", tip: "noun", article: "das" },
    { de: "die Schiffsschraube", lookup: "Schiffsschraube", fallbackEn: "propeller", tip: "noun", article: "die" },
    { de: "steuerbord", lookup: "steuerbord", fallbackEn: "starboard", tip: "adjective", use: "the right-hand side facing forward" },
    { de: "backbord", lookup: "backbord", fallbackEn: "port side", tip: "adjective", use: "the left-hand side facing forward" },
    { de: "der Tiefgang", lookup: "Tiefgang", fallbackEn: "draught", tip: "noun", article: "der", use: "how deep a loaded ship sits in the water" },
    { de: "die Tonnage", lookup: "Tonnage", fallbackEn: "tonnage", tip: "noun", article: "die" },
  ]),
  part612: pack("Part 612", "B1", "Boats and the people on them", "The kinds of vessel and the jobs aboard.", [
    { de: "der Kutter", lookup: "Kutter", fallbackEn: "cutter, fishing boat", tip: "noun", article: "der" },
    { de: "der Trawler", lookup: "Trawler", fallbackEn: "trawler", tip: "noun", article: "der" },
    { de: "der Frachter", lookup: "Frachter", fallbackEn: "cargo ship", tip: "noun", article: "der" },
    { de: "der Tanker", lookup: "Tanker", fallbackEn: "tanker", tip: "noun", article: "der" },
    { de: "die Jacht", lookup: "Jacht", fallbackEn: "yacht", tip: "noun", article: "die" },
    { de: "das Kajak", lookup: "Kajak", fallbackEn: "kayak", tip: "noun", article: "das" },
    { de: "das Floß", lookup: "Floß", fallbackEn: "raft", tip: "noun", article: "das" },
    { de: "der Matrose", lookup: "Matrose", fallbackEn: "sailor", tip: "noun", article: "der" },
    { de: "der Steuermann", lookup: "Steuermann", fallbackEn: "helmsman", tip: "noun", article: "der" },
    { de: "der Lotse", lookup: "Lotse", fallbackEn: "pilot (of a ship)", tip: "noun", article: "der", use: "the local who steers a ship into harbour" },
    { de: "der Reeder", lookup: "Reeder", fallbackEn: "shipowner", tip: "noun", article: "der" },
    { de: "die Besatzung", lookup: "Besatzung", fallbackEn: "crew", tip: "noun", article: "die" },
    { de: "der Fährmann", lookup: "Fährmann", fallbackEn: "ferryman", tip: "noun", article: "der" },
    { de: "der Hafenmeister", lookup: "Hafenmeister", fallbackEn: "harbourmaster", tip: "noun", article: "der" },
  ]),
  part613: pack("Part 613", "B1", "The harbour", "Where a ship ties up, and the paperwork waiting for it.", [
    { de: "der Kai", lookup: "Kai", fallbackEn: "quay", tip: "noun", article: "der" },
    { de: "die Werft", lookup: "Werft", fallbackEn: "shipyard", tip: "noun", article: "die" },
    { de: "die Mole", lookup: "Mole", fallbackEn: "jetty, breakwater", tip: "noun", article: "die" },
    { de: "der Pier", lookup: "Pier", fallbackEn: "pier", tip: "noun", article: "der" },
    { de: "das Hafenbecken", lookup: "Hafenbecken", fallbackEn: "harbour basin", tip: "noun", article: "das" },
    { de: "die Anlegestelle", lookup: "Anlegestelle", fallbackEn: "landing stage", tip: "noun", article: "die" },
    { de: "der Wellenbrecher", lookup: "Wellenbrecher", fallbackEn: "breakwater", tip: "noun", article: "der" },
    { de: "der Deich", lookup: "Deich", fallbackEn: "dyke, sea wall", tip: "noun", article: "der" },
    { de: "der Leuchtturm", lookup: "Leuchtturm", fallbackEn: "lighthouse", tip: "noun", article: "der" },
    { de: "die Boje", lookup: "Boje", fallbackEn: "buoy", tip: "noun", article: "die" },
    { de: "die Seekarte", lookup: "Seekarte", fallbackEn: "nautical chart", tip: "noun", article: "die" },
    { de: "das Logbuch", lookup: "Logbuch", fallbackEn: "logbook", tip: "noun", article: "das" },
    { de: "die Seemeile", lookup: "Seemeile", fallbackEn: "nautical mile", tip: "noun", article: "die" },
    { de: "der Knoten", lookup: "Knoten", fallbackEn: "knot", tip: "noun", article: "der", use: "the knot you tie, and the speed a ship goes at" },
    { de: "die Verladung", lookup: "Verladung", fallbackEn: "loading", tip: "noun", article: "die" },
    { de: "die Zollkontrolle", lookup: "Zollkontrolle", fallbackEn: "customs check", tip: "noun", article: "die" },
    { de: "der Zollbeamte", lookup: "Zollbeamte", fallbackEn: "customs officer", tip: "noun", article: "der" },
    { de: "die Wasserstraße", lookup: "Wasserstraße", fallbackEn: "waterway", tip: "noun", article: "die" },
    { de: "der Seeweg", lookup: "Seeweg", fallbackEn: "sea route", tip: "noun", article: "der" },
    { de: "anlegen", lookup: "anlegen", fallbackEn: "to dock, to moor", tip: "verb", use: "of a boat coming in; ablegen is casting off" },
    { de: "ankern", lookup: "ankern", fallbackEn: "to anchor", tip: "verb" },
  ]),
  part614: pack("Part 614", "B1", "The sea itself", "Tides, currents and the shapes a coast takes.", [
    { de: "die Gezeiten", lookup: "Gezeiten", fallbackEn: "tides", tip: "noun", article: "die", use: "always plural: Ebbe und Flut together" },
    { de: "die Brandung", lookup: "Brandung", fallbackEn: "surf", tip: "noun", article: "die", use: "where the waves break on the shore" },
    { de: "der Wirbel", lookup: "Wirbel", fallbackEn: "whirl, fuss", tip: "noun", article: "der", use: "a whirlpool of water, and a fuss about nothing" },
    { de: "die Untiefe", lookup: "Untiefe", fallbackEn: "shallows", tip: "noun", article: "die", use: "shallow water a boat can run aground in" },
    { de: "der Fjord", lookup: "Fjord", fallbackEn: "fjord", tip: "noun", article: "der" },
    { de: "die Lagune", lookup: "Lagune", fallbackEn: "lagoon", tip: "noun", article: "die" },
    { de: "die Meerenge", lookup: "Meerenge", fallbackEn: "strait", tip: "noun", article: "die" },
    { de: "der Meeresboden", lookup: "Meeresboden", fallbackEn: "seabed", tip: "noun", article: "der" },
    { de: "die Tiefsee", lookup: "Tiefsee", fallbackEn: "deep sea", tip: "noun", article: "die" },
    { de: "das Salzwasser", lookup: "Salzwasser", fallbackEn: "salt water", tip: "noun", article: "das" },
    { de: "das Süßwasser", lookup: "Süßwasser", fallbackEn: "fresh water", tip: "noun", article: "das" },
    { de: "der Salzgehalt", lookup: "Salzgehalt", fallbackEn: "salt content", tip: "noun", article: "der" },
    { de: "der Seegang", lookup: "Seegang", fallbackEn: "swell", tip: "noun", article: "der", use: "how rough the water is: hoher Seegang" },
    { de: "die Sturmflut", lookup: "Sturmflut", fallbackEn: "storm surge", tip: "noun", article: "die" },
    { de: "die Windstille", lookup: "Windstille", fallbackEn: "calm", tip: "noun", article: "die", use: "no wind at all" },
    { de: "die Gischt", lookup: "Gischt", fallbackEn: "spray, foam", tip: "noun", article: "die" },
    { de: "das Weltmeer", lookup: "Weltmeer", fallbackEn: "ocean", tip: "noun", article: "das", use: "usually plural, die Weltmeere: the oceans of the world" },
    { de: "die Nordsee", lookup: "Nordsee", fallbackEn: "North Sea", tip: "noun", article: "die" },
    { de: "die Ostsee", lookup: "Ostsee", fallbackEn: "Baltic Sea", tip: "noun", article: "die" },
  ]),
  part615: pack("Part 615", "B1", "What lives in it", "Fish on a menu, birds over the water, and what a rock pool holds.", [
    { de: "die Krabbe", lookup: "Krabbe", fallbackEn: "crab", tip: "noun", article: "die" },
    { de: "der Hummer", lookup: "Hummer", fallbackEn: "lobster", tip: "noun", article: "der" },
    { de: "der Kabeljau", lookup: "Kabeljau", fallbackEn: "cod", tip: "noun", article: "der" },
    { de: "die Scholle", lookup: "Scholle", fallbackEn: "plaice", tip: "noun", article: "die" },
    { de: "die Makrele", lookup: "Makrele", fallbackEn: "mackerel", tip: "noun", article: "die" },
    { de: "der Karpfen", lookup: "Karpfen", fallbackEn: "carp", tip: "noun", article: "der" },
    { de: "der Aal", lookup: "Aal", fallbackEn: "eel", tip: "noun", article: "der" },
    { de: "der Rochen", lookup: "Rochen", fallbackEn: "ray", tip: "noun", article: "der", use: "the flat fish, not a ray of light" },
    { de: "der Seehund", lookup: "Seehund", fallbackEn: "seal", tip: "noun", article: "der" },
    { de: "der Albatros", lookup: "Albatros", fallbackEn: "albatross", tip: "noun", article: "der" },
    { de: "der Kormoran", lookup: "Kormoran", fallbackEn: "cormorant", tip: "noun", article: "der" },
    { de: "der Reiher", lookup: "Reiher", fallbackEn: "heron", tip: "noun", article: "der" },
    { de: "der Seeigel", lookup: "Seeigel", fallbackEn: "sea urchin", tip: "noun", article: "der" },
    { de: "der Seestern", lookup: "Seestern", fallbackEn: "starfish", tip: "noun", article: "der" },
    { de: "die Auster", lookup: "Auster", fallbackEn: "oyster", tip: "noun", article: "die" },
    { de: "die Miesmuschel", lookup: "Miesmuschel", fallbackEn: "mussel", tip: "noun", article: "die" },
    { de: "der Seetang", lookup: "Seetang", fallbackEn: "seaweed", tip: "noun", article: "der" },
    { de: "der Laich", lookup: "Laich", fallbackEn: "spawn", tip: "noun", article: "der" },
    { de: "die Fischgräte", lookup: "Fischgräte", fallbackEn: "fish bone", tip: "noun", article: "die" },
    { de: "die Schuppe", lookup: "Schuppe", fallbackEn: "scale (on a fish)", tip: "noun", article: "die" },
    { de: "die Kieme", lookup: "Kieme", fallbackEn: "gill", tip: "noun", article: "die" },
  ]),
  part616: pack("Part 616", "B1", "Fishing and diving", "Two ways of going into the water on purpose.", [
    { de: "die Angel", lookup: "Angel", fallbackEn: "fishing rod", tip: "noun", article: "die" },
    { de: "der Angelhaken", lookup: "Angelhaken", fallbackEn: "fish hook", tip: "noun", article: "der" },
    { de: "der Köder", lookup: "Köder", fallbackEn: "bait", tip: "noun", article: "der" },
    { de: "die Reuse", lookup: "Reuse", fallbackEn: "fish trap", tip: "noun", article: "die" },
    { de: "die Fangquote", lookup: "Fangquote", fallbackEn: "catch quota", tip: "noun", article: "die" },
    { de: "die Fischerei", lookup: "Fischerei", fallbackEn: "fishing industry", tip: "noun", article: "die" },
    { de: "die Überfischung", lookup: "Überfischung", fallbackEn: "overfishing", tip: "noun", article: "die" },
    { de: "fischen", lookup: "fischen", fallbackEn: "to fish", tip: "verb", use: "as a trade; angeln is fishing with a rod for pleasure" },
    { de: "der Taucher", lookup: "Taucher", fallbackEn: "diver", tip: "noun", article: "der" },
    { de: "der Tauchgang", lookup: "Tauchgang", fallbackEn: "dive", tip: "noun", article: "der", use: "one trip underwater" },
    { de: "der Schnorchel", lookup: "Schnorchel", fallbackEn: "snorkel", tip: "noun", article: "der" },
    { de: "schnorcheln", lookup: "schnorcheln", fallbackEn: "to snorkel", tip: "verb" },
    { de: "die Sauerstoffflasche", lookup: "Sauerstoffflasche", fallbackEn: "air tank", tip: "noun", article: "die" },
    { de: "die Flosse", lookup: "Flosse", fallbackEn: "fin, flipper", tip: "noun", article: "die", use: "on a fish, and on your foot when diving" },
    { de: "der Neoprenanzug", lookup: "Neoprenanzug", fallbackEn: "wetsuit", tip: "noun", article: "der" },
  ]),
  part617: pack("Part 617", "B1", "Trouble at sea, and a day at the beach", "What goes wrong out there, who comes for you, and what the shore is for otherwise.", [
    { de: "die Seenot", lookup: "Seenot", fallbackEn: "distress at sea", tip: "noun", article: "die" },
    { de: "der Schiffbruch", lookup: "Schiffbruch", fallbackEn: "shipwreck", tip: "noun", article: "der", use: "the event; das Wrack is what is left" },
    { de: "das Wrack", lookup: "Wrack", fallbackEn: "wreck", tip: "noun", article: "das" },
    { de: "kentern", lookup: "kentern", fallbackEn: "to capsize", tip: "verb" },
    { de: "stranden", lookup: "stranden", fallbackEn: "to run aground, to be stranded", tip: "verb" },
    { de: "bergen", lookup: "bergen", fallbackEn: "to recover, to salvage", tip: "verb", use: "to bring people or wreckage out of danger" },
    { de: "die Rettungsweste", lookup: "Rettungsweste", fallbackEn: "life jacket", tip: "noun", article: "die" },
    { de: "der Rettungsring", lookup: "Rettungsring", fallbackEn: "life ring", tip: "noun", article: "der" },
    { de: "das Rettungsboot", lookup: "Rettungsboot", fallbackEn: "lifeboat", tip: "noun", article: "das" },
    { de: "der Rettungsschwimmer", lookup: "Rettungsschwimmer", fallbackEn: "lifeguard", tip: "noun", article: "der" },
    { de: "die Seenotrettung", lookup: "Seenotrettung", fallbackEn: "sea rescue", tip: "noun", article: "die" },
    { de: "die Küstenwache", lookup: "Küstenwache", fallbackEn: "coastguard", tip: "noun", article: "die" },
    { de: "der Funkspruch", lookup: "Funkspruch", fallbackEn: "radio message", tip: "noun", article: "der" },
    { de: "die Seekrankheit", lookup: "Seekrankheit", fallbackEn: "seasickness", tip: "noun", article: "die" },
    { de: "die Ölpest", lookup: "Ölpest", fallbackEn: "oil spill", tip: "noun", article: "die" },
    { de: "der Strandkorb", lookup: "Strandkorb", fallbackEn: "hooded beach chair", tip: "noun", article: "der", use: "the wicker seat with a roof, found on German beaches" },
    { de: "der Liegestuhl", lookup: "Liegestuhl", fallbackEn: "deckchair", tip: "noun", article: "der" },
    { de: "die Sandburg", lookup: "Sandburg", fallbackEn: "sandcastle", tip: "noun", article: "die" },
    { de: "der Kiesel", lookup: "Kiesel", fallbackEn: "pebble", tip: "noun", article: "der" },
    { de: "das Treibholz", lookup: "Treibholz", fallbackEn: "driftwood", tip: "noun", article: "das" },
    { de: "planschen", lookup: "planschen", fallbackEn: "to splash about", tip: "verb" },
    { de: "waten", lookup: "waten", fallbackEn: "to wade", tip: "verb" },
  ]),
part618: pack("Part 618", "B1", "The trades", "What each tradesperson is called, and who to ring for what.", [
    { de: "der Handwerker", lookup: "Handwerker", fallbackEn: "tradesperson", tip: "noun", article: "der", use: "anyone who works with their hands for a living" },
    { de: "der Schreiner", lookup: "Schreiner", fallbackEn: "joiner", tip: "noun", article: "der", use: "the southern word; der Tischler is the northern one" },
    { de: "der Zimmermann", lookup: "Zimmermann", fallbackEn: "carpenter", tip: "noun", article: "der", use: "the one who builds roofs and frames, not furniture" },
    { de: "der Schlosser", lookup: "Schlosser", fallbackEn: "metalworker, locksmith", tip: "noun", article: "der" },
    { de: "der Schneider", lookup: "Schneider", fallbackEn: "tailor", tip: "noun", article: "der" },
    { de: "der Fliesenleger", lookup: "Fliesenleger", fallbackEn: "tiler", tip: "noun", article: "der" },
    { de: "der Stuckateur", lookup: "Stuckateur", fallbackEn: "plasterer", tip: "noun", article: "der" },
    { de: "der Glaser", lookup: "Glaser", fallbackEn: "glazier", tip: "noun", article: "der" },
    { de: "der Installateur", lookup: "Installateur", fallbackEn: "fitter, plumber", tip: "noun", article: "der" },
    { de: "der Facharbeiter", lookup: "Facharbeiter", fallbackEn: "skilled worker", tip: "noun", article: "der" },
    { de: "der Fachmann", lookup: "Fachmann", fallbackEn: "expert", tip: "noun", article: "der", use: "the person who actually knows the trade" },
    { de: "der Betrieb", lookup: "Betrieb", fallbackEn: "business, operation", tip: "noun", article: "der", use: "the firm you work at; in Betrieb also means in service" },
    { de: "die Belegschaft", lookup: "Belegschaft", fallbackEn: "workforce", tip: "noun", article: "die" },
  ]),
  part619: pack("Part 619", "B1", "Learning a trade", "The German apprenticeship, from the contract to the certificate.", [
    { de: "der Lehrling", lookup: "Lehrling", fallbackEn: "apprentice", tip: "noun", article: "der", use: "the older word; der Azubi is what people say now" },
    { de: "der Geselle", lookup: "Geselle", fallbackEn: "journeyman", tip: "noun", article: "der", use: "qualified, but not yet a Meister" },
    { de: "das Ausbildungsjahr", lookup: "Ausbildungsjahr", fallbackEn: "year of training", tip: "noun", article: "das" },
    { de: "die Zwischenprüfung", lookup: "Zwischenprüfung", fallbackEn: "interim exam", tip: "noun", article: "die" },
    { de: "die Abschlussprüfung", lookup: "Abschlussprüfung", fallbackEn: "final exam", tip: "noun", article: "die" },
    { de: "der Meisterbrief", lookup: "Meisterbrief", fallbackEn: "master craftsman certificate", tip: "noun", article: "der" },
    { de: "die Innung", lookup: "Innung", fallbackEn: "trade guild", tip: "noun", article: "die" },
    { de: "die Zunft", lookup: "Zunft", fallbackEn: "guild", tip: "noun", article: "die", use: "the historical one; die Innung is its modern successor" },
    { de: "die Handwerkskammer", lookup: "Handwerkskammer", fallbackEn: "chamber of crafts", tip: "noun", article: "die" },
  ]),
  part620: pack("Part 620", "B1", "The building site", "Who runs it, what fences it off and what holds the building up.", [
    { de: "der Bauleiter", lookup: "Bauleiter", fallbackEn: "site manager", tip: "noun", article: "der" },
    { de: "der Polier", lookup: "Polier", fallbackEn: "foreman", tip: "noun", article: "der" },
    { de: "der Bauarbeiter", lookup: "Bauarbeiter", fallbackEn: "construction worker", tip: "noun", article: "der" },
    { de: "der Betonmischer", lookup: "Betonmischer", fallbackEn: "cement mixer", tip: "noun", article: "der" },
    { de: "der Bauhelm", lookup: "Bauhelm", fallbackEn: "hard hat", tip: "noun", article: "der" },
    { de: "die Absperrung", lookup: "Absperrung", fallbackEn: "barrier", tip: "noun", article: "die" },
    { de: "der Bauzaun", lookup: "Bauzaun", fallbackEn: "site fence", tip: "noun", article: "der" },
    { de: "die Baugrube", lookup: "Baugrube", fallbackEn: "excavation pit", tip: "noun", article: "die" },
    { de: "das Fundament", lookup: "Fundament", fallbackEn: "foundation", tip: "noun", article: "das" },
    { de: "der Sparren", lookup: "Sparren", fallbackEn: "rafter", tip: "noun", article: "der" },
    { de: "die Isolierung", lookup: "Isolierung", fallbackEn: "insulation", tip: "noun", article: "die" },
    { de: "der Gipskarton", lookup: "Gipskarton", fallbackEn: "plasterboard", tip: "noun", article: "der" },
    { de: "der Innenausbau", lookup: "Innenausbau", fallbackEn: "interior fit-out", tip: "noun", article: "der" },
    { de: "der Trockenbau", lookup: "Trockenbau", fallbackEn: "drywall construction", tip: "noun", article: "der" },
    { de: "der Bauantrag", lookup: "Bauantrag", fallbackEn: "planning application", tip: "noun", article: "der" },
    { de: "die Baugenehmigung", lookup: "Baugenehmigung", fallbackEn: "planning permission", tip: "noun", article: "die" },
    { de: "der Bauplan", lookup: "Bauplan", fallbackEn: "building plan", tip: "noun", article: "der" },
    { de: "der Aufriss", lookup: "Aufriss", fallbackEn: "elevation drawing", tip: "noun", article: "der", use: "the view from the side; der Grundriss is from above" },
  ]),
  part621: pack("Part 621", "B1", "In the workshop", "The tools a job needs after the drill and the hammer.", [
    { de: "die Schraubzwinge", lookup: "Schraubzwinge", fallbackEn: "clamp", tip: "noun", article: "die" },
    { de: "das Richtscheit", lookup: "Richtscheit", fallbackEn: "straightedge", tip: "noun", article: "das" },
    { de: "die Kelle", lookup: "Kelle", fallbackEn: "trowel", tip: "noun", article: "die" },
    { de: "der Spachtel", lookup: "Spachtel", fallbackEn: "filling knife", tip: "noun", article: "der", use: "the blade; die Spachtelmasse is the filler itself" },
    { de: "die Feile", lookup: "Feile", fallbackEn: "file", tip: "noun", article: "die", use: "the tool you smooth metal with" },
    { de: "das Stemmeisen", lookup: "Stemmeisen", fallbackEn: "chisel", tip: "noun", article: "das" },
    { de: "die Drehbank", lookup: "Drehbank", fallbackEn: "lathe", tip: "noun", article: "die" },
    { de: "das Schweißgerät", lookup: "Schweißgerät", fallbackEn: "welder", tip: "noun", article: "das", use: "the machine, not the person" },
    { de: "das Sägeblatt", lookup: "Sägeblatt", fallbackEn: "saw blade", tip: "noun", article: "das" },
    { de: "die Kettensäge", lookup: "Kettensäge", fallbackEn: "chainsaw", tip: "noun", article: "die" },
    { de: "das Bandmaß", lookup: "Bandmaß", fallbackEn: "tape measure", tip: "noun", article: "das" },
    { de: "das Bohrfutter", lookup: "Bohrfutter", fallbackEn: "drill chuck", tip: "noun", article: "das" },
    { de: "der Atemschutz", lookup: "Atemschutz", fallbackEn: "respiratory protection", tip: "noun", article: "der", use: "the mask a dusty job needs" },
    { de: "die Arbeitskleidung", lookup: "Arbeitskleidung", fallbackEn: "workwear", tip: "noun", article: "die" },
    { de: "der Overall", lookup: "Overall", fallbackEn: "boiler suit", tip: "noun", article: "der" },
    { de: "die Sägespäne", lookup: "Sägespäne", fallbackEn: "sawdust", tip: "noun", article: "die", use: "always plural" },
  ]),
  part622: pack("Part 622", "B1", "Wood, metal and the bits between", "What a workshop keeps in its drawers and stacks against the wall.", [
    { de: "das Rohr", lookup: "Rohr", fallbackEn: "pipe, tube", tip: "noun", article: "das" },
    { de: "die Leiste", lookup: "Leiste", fallbackEn: "strip, moulding", tip: "noun", article: "die", use: "the wooden strip along a wall or an edge" },
    { de: "das Sperrholz", lookup: "Sperrholz", fallbackEn: "plywood", tip: "noun", article: "das" },
    { de: "die Spanplatte", lookup: "Spanplatte", fallbackEn: "chipboard", tip: "noun", article: "die" },
    { de: "das Furnier", lookup: "Furnier", fallbackEn: "veneer", tip: "noun", article: "das" },
    { de: "der Leim", lookup: "Leim", fallbackEn: "wood glue", tip: "noun", article: "der" },
    { de: "die Maserung", lookup: "Maserung", fallbackEn: "grain", tip: "noun", article: "die", use: "the pattern in a piece of wood" },
    { de: "der Span", lookup: "Span", fallbackEn: "shaving, chip", tip: "noun", article: "der" },
    { de: "die Nut", lookup: "Nut", fallbackEn: "groove", tip: "noun", article: "die" },
    { de: "die Gehrung", lookup: "Gehrung", fallbackEn: "mitre", tip: "noun", article: "die", use: "the 45-degree cut where two edges meet" },
    { de: "die Rille", lookup: "Rille", fallbackEn: "groove, ridge", tip: "noun", article: "die" },
    { de: "das Gewinde", lookup: "Gewinde", fallbackEn: "thread", tip: "noun", article: "das", use: "the spiral on a screw or in a nut" },
    { de: "die Unterlegscheibe", lookup: "Unterlegscheibe", fallbackEn: "washer", tip: "noun", article: "die" },
    { de: "der Niet", lookup: "Niet", fallbackEn: "rivet", tip: "noun", article: "der" },
    { de: "die Klammer", lookup: "Klammer", fallbackEn: "clip, bracket", tip: "noun", article: "die", use: "the clip that holds things together, and the bracket in writing" },
    { de: "das Ersatzteil", lookup: "Ersatzteil", fallbackEn: "spare part", tip: "noun", article: "das" },
  ]),
  part623: pack("Part 623", "B1", "Doing the work", "The verbs a quote lists and an invoice charges for.", [
    { de: "schweißen", lookup: "schweißen", fallbackEn: "to weld", tip: "verb" },
    { de: "löten", lookup: "löten", fallbackEn: "to solder", tip: "verb" },
    { de: "fräsen", lookup: "fräsen", fallbackEn: "to mill, to rout", tip: "verb" },
    { de: "hobeln", lookup: "hobeln", fallbackEn: "to plane", tip: "verb" },
    { de: "feilen", lookup: "feilen", fallbackEn: "to file", tip: "verb" },
    { de: "verputzen", lookup: "verputzen", fallbackEn: "to plaster", tip: "verb" },
    { de: "mauern", lookup: "mauern", fallbackEn: "to lay bricks", tip: "verb" },
    { de: "fliesen", lookup: "fliesen", fallbackEn: "to tile", tip: "verb" },
    { de: "grundieren", lookup: "grundieren", fallbackEn: "to prime", tip: "verb", use: "the coat that goes on before the paint" },
    { de: "abdichten", lookup: "abdichten", fallbackEn: "to seal", tip: "verb" },
    { de: "dämmen", lookup: "dämmen", fallbackEn: "to insulate", tip: "verb" },
    { de: "zuschneiden", lookup: "zuschneiden", fallbackEn: "to cut to size", tip: "verb" },
    { de: "anzeichnen", lookup: "anzeichnen", fallbackEn: "to mark out", tip: "verb" },
    { de: "reparieren", lookup: "reparieren", fallbackEn: "to repair", tip: "verb" },
    { de: "montieren", lookup: "montieren", fallbackEn: "to fit, to assemble", tip: "verb" },
    { de: "abmontieren", lookup: "abmontieren", fallbackEn: "to take off, to dismantle", tip: "verb" },
    { de: "ausbauen", lookup: "ausbauen", fallbackEn: "to remove, to extend", tip: "verb", use: "to take a part out, and to build a loft out" },
    { de: "verschrauben", lookup: "verschrauben", fallbackEn: "to bolt together", tip: "verb" },
    { de: "anschrauben", lookup: "anschrauben", fallbackEn: "to screw on", tip: "verb" },
    { de: "festziehen", lookup: "festziehen", fallbackEn: "to tighten", tip: "verb" },
    { de: "vernieten", lookup: "vernieten", fallbackEn: "to rivet", tip: "verb" },
    { de: "verleimen", lookup: "verleimen", fallbackEn: "to glue together", tip: "verb" },
    { de: "verzinken", lookup: "verzinken", fallbackEn: "to galvanise", tip: "verb" },
    { de: "abschleifen", lookup: "abschleifen", fallbackEn: "to sand down", tip: "verb" },
    { de: "entgraten", lookup: "entgraten", fallbackEn: "to deburr", tip: "verb", use: "to take the sharp edge off a cut" },
    { de: "justieren", lookup: "justieren", fallbackEn: "to adjust", tip: "verb" },
    { de: "nachrüsten", lookup: "nachrüsten", fallbackEn: "to retrofit", tip: "verb" },
  ]),
  part624: pack("Part 624", "B1", "The quote and the invoice", "What the job costs, and what happens when it is finished.", [
    { de: "das Aufmaß", lookup: "Aufmaß", fallbackEn: "measured quantities", tip: "noun", article: "das", use: "the measuring-up a quote is built from" },
    { de: "die Materialkosten", lookup: "Materialkosten", fallbackEn: "cost of materials", tip: "noun", article: "die", use: "always plural" },
    { de: "die Pauschale", lookup: "Pauschale", fallbackEn: "flat rate", tip: "noun", article: "die" },
    { de: "das Skonto", lookup: "Skonto", fallbackEn: "early payment discount", tip: "noun", article: "das" },
    { de: "das Zahlungsziel", lookup: "Zahlungsziel", fallbackEn: "payment deadline", tip: "noun", article: "das" },
    { de: "die Abnahme", lookup: "Abnahme", fallbackEn: "sign-off, acceptance", tip: "noun", article: "die", use: "the walk-round where the customer accepts the work" },
    { de: "die Wartung", lookup: "Wartung", fallbackEn: "servicing, maintenance", tip: "noun", article: "die" },
    { de: "die Montage", lookup: "Montage", fallbackEn: "installation", tip: "noun", article: "die" },
    { de: "die Demontage", lookup: "Demontage", fallbackEn: "removal, dismantling", tip: "noun", article: "die" },
    { de: "der Auftraggeber", lookup: "Auftraggeber", fallbackEn: "client", tip: "noun", article: "der" },
    { de: "der Auftragnehmer", lookup: "Auftragnehmer", fallbackEn: "contractor", tip: "noun", article: "der" },
    { de: "der Subunternehmer", lookup: "Subunternehmer", fallbackEn: "subcontractor", tip: "noun", article: "der" },
    { de: "die Norm", lookup: "Norm", fallbackEn: "standard", tip: "noun", article: "die", use: "the written rule a job has to meet" },
  ]),
part625: pack("Part 625", "B1", "Up the mountain", "Climbing words, from the rope to the ridge.", [
    { de: "der Bergsteiger", lookup: "Bergsteiger", fallbackEn: "mountaineer", tip: "noun", article: "der" },
    { de: "der Bergführer", lookup: "Bergführer", fallbackEn: "mountain guide", tip: "noun", article: "der" },
    { de: "die Seilschaft", lookup: "Seilschaft", fallbackEn: "rope team", tip: "noun", article: "die", use: "the climbers tied to one rope; also a clique in politics" },
    { de: "der Klettersteig", lookup: "Klettersteig", fallbackEn: "via ferrata", tip: "noun", article: "der", use: "a route fitted with cables and rungs" },
    { de: "das Steigeisen", lookup: "Steigeisen", fallbackEn: "crampon", tip: "noun", article: "das" },
    { de: "der Pickel", lookup: "Pickel", fallbackEn: "ice axe, spot", tip: "noun", article: "der", use: "the ice axe, and the spot on your face" },
    { de: "der Karabiner", lookup: "Karabiner", fallbackEn: "carabiner", tip: "noun", article: "der" },
    { de: "das Kletterseil", lookup: "Kletterseil", fallbackEn: "climbing rope", tip: "noun", article: "das" },
    { de: "der Klettergurt", lookup: "Klettergurt", fallbackEn: "climbing harness", tip: "noun", article: "der" },
    { de: "die Felswand", lookup: "Felswand", fallbackEn: "rock face", tip: "noun", article: "die" },
    { de: "der Überhang", lookup: "Überhang", fallbackEn: "overhang", tip: "noun", article: "der" },
    { de: "der Grat", lookup: "Grat", fallbackEn: "ridge", tip: "noun", article: "der" },
    // Passport first. Every one of the course's own sentences with this word
    // means the document — "Ohne Pass geht am Flughafen gar nichts" — and the
    // frequency that ranks the card comes from those sentences, so a card
    // glossed as the road over a mountain arrived early and taught the sense
    // nobody was saying. The mountain stays as the second meaning.
    { de: "der Pass", lookup: "Pass", fallbackEn: "passport, mountain pass", tip: "noun", article: "der", use: "the document at the border or airport (der Reisepass in full); also the road over a mountain" },
    { de: "die Hochebene", lookup: "Hochebene", fallbackEn: "plateau", tip: "noun", article: "die" },
    { de: "die Steigung", lookup: "Steigung", fallbackEn: "gradient, incline", tip: "noun", article: "die" },
    { de: "die Schlucht", lookup: "Schlucht", fallbackEn: "gorge, ravine", tip: "noun", article: "die" },
    { de: "das Geröll", lookup: "Geröll", fallbackEn: "scree", tip: "noun", article: "das" },
    { de: "der Felsblock", lookup: "Felsblock", fallbackEn: "boulder", tip: "noun", article: "der" },
    { de: "der Schotter", lookup: "Schotter", fallbackEn: "gravel, ballast", tip: "noun", article: "der" },
    { de: "das Abseilen", lookup: "Abseilen", fallbackEn: "abseiling", tip: "noun", article: "das" },
    { de: "die Bergtour", lookup: "Bergtour", fallbackEn: "mountain hike", tip: "noun", article: "die" },
    { de: "die Trittsicherheit", lookup: "Trittsicherheit", fallbackEn: "sure-footedness", tip: "noun", article: "die", use: "what a route description asks you to have" },
    { de: "die Schwindelfreiheit", lookup: "Schwindelfreiheit", fallbackEn: "head for heights", tip: "noun", article: "die" },
  ]),
  part626: pack("Part 626", "B1", "The path and the way-marking", "What you carry, and how you know you are still on the route.", [
    { de: "der Wanderschuh", lookup: "Wanderschuh", fallbackEn: "walking boot", tip: "noun", article: "der" },
    { de: "der Wanderstock", lookup: "Wanderstock", fallbackEn: "walking pole", tip: "noun", article: "der" },
    { de: "der Rucksackgurt", lookup: "Rucksackgurt", fallbackEn: "rucksack strap", tip: "noun", article: "der" },
    { de: "die Regenhose", lookup: "Regenhose", fallbackEn: "waterproof trousers", tip: "noun", article: "die" },
    { de: "der Kompass", lookup: "Kompass", fallbackEn: "compass", tip: "noun", article: "der" },
    { de: "die Wanderkarte", lookup: "Wanderkarte", fallbackEn: "walking map", tip: "noun", article: "die" },
    { de: "der Wegweiser", lookup: "Wegweiser", fallbackEn: "signpost", tip: "noun", article: "der" },
    { de: "der Rundweg", lookup: "Rundweg", fallbackEn: "circular route", tip: "noun", article: "der" },
    { de: "die Serpentine", lookup: "Serpentine", fallbackEn: "hairpin bend", tip: "noun", article: "die" },
    { de: "die Kehre", lookup: "Kehre", fallbackEn: "bend, turn", tip: "noun", article: "die" },
    { de: "der Aussichtspunkt", lookup: "Aussichtspunkt", fallbackEn: "viewpoint", tip: "noun", article: "der" },
    { de: "die Tagestour", lookup: "Tagestour", fallbackEn: "day trip", tip: "noun", article: "die" },
    { de: "der Rastplatz", lookup: "Rastplatz", fallbackEn: "rest area", tip: "noun", article: "der" },
    { de: "der Wanderführer", lookup: "Wanderführer", fallbackEn: "walking guidebook", tip: "noun", article: "der" },
    { de: "die Wanderlust", lookup: "Wanderlust", fallbackEn: "urge to travel", tip: "noun", article: "die", use: "English borrowed the word; German still means it literally" },
    { de: "die Schneegrenze", lookup: "Schneegrenze", fallbackEn: "snow line", tip: "noun", article: "die" },
    { de: "die Baumgrenze", lookup: "Baumgrenze", fallbackEn: "tree line", tip: "noun", article: "die" },
  ]),
  part627: pack("Part 627", "B1", "Camping and the fire", "A night outdoors, and what it takes to eat and stay dry.", [
    { de: "der Zeltplatz", lookup: "Zeltplatz", fallbackEn: "camping pitch", tip: "noun", article: "der" },
    { de: "die Zeltstange", lookup: "Zeltstange", fallbackEn: "tent pole", tip: "noun", article: "die" },
    { de: "das Vorzelt", lookup: "Vorzelt", fallbackEn: "awning", tip: "noun", article: "das" },
    { de: "der Klappstuhl", lookup: "Klappstuhl", fallbackEn: "folding chair", tip: "noun", article: "der" },
    { de: "der Windschutz", lookup: "Windschutz", fallbackEn: "windbreak", tip: "noun", article: "der" },
    { de: "die Plane", lookup: "Plane", fallbackEn: "tarpaulin", tip: "noun", article: "die" },
    { de: "das Spannseil", lookup: "Spannseil", fallbackEn: "guy rope", tip: "noun", article: "das" },
    { de: "das Biwak", lookup: "Biwak", fallbackEn: "bivouac", tip: "noun", article: "das" },
    { de: "das Lagerfeuer", lookup: "Lagerfeuer", fallbackEn: "campfire", tip: "noun", article: "das" },
    { de: "das Brennholz", lookup: "Brennholz", fallbackEn: "firewood", tip: "noun", article: "das" },
    { de: "die Asche", lookup: "Asche", fallbackEn: "ash", tip: "noun", article: "die" },
    { de: "der Zunder", lookup: "Zunder", fallbackEn: "tinder", tip: "noun", article: "der" },
    { de: "die Feldflasche", lookup: "Feldflasche", fallbackEn: "canteen", tip: "noun", article: "die" },
    { de: "die Trinkflasche", lookup: "Trinkflasche", fallbackEn: "water bottle", tip: "noun", article: "die" },
    { de: "der Proviant", lookup: "Proviant", fallbackEn: "provisions", tip: "noun", article: "der", use: "the food you take with you for the day" },
    { de: "die Verpflegung", lookup: "Verpflegung", fallbackEn: "catering, meals", tip: "noun", article: "die" },
    { de: "der Müsliriegel", lookup: "Müsliriegel", fallbackEn: "cereal bar", tip: "noun", article: "der" },
    { de: "der Wasserfilter", lookup: "Wasserfilter", fallbackEn: "water filter", tip: "noun", article: "der" },
    { de: "der Wasserkanister", lookup: "Wasserkanister", fallbackEn: "water canister", tip: "noun", article: "der" },
    { de: "das Mückenspray", lookup: "Mückenspray", fallbackEn: "insect repellent", tip: "noun", article: "das" },
  ]),
  part628: pack("Part 628", "B1", "Woods, water and high pasture", "The kinds of country a walk goes through.", [
    { de: "der Waldboden", lookup: "Waldboden", fallbackEn: "forest floor", tip: "noun", article: "der" },
    { de: "der Laubwald", lookup: "Laubwald", fallbackEn: "deciduous forest", tip: "noun", article: "der" },
    { de: "der Nadelwald", lookup: "Nadelwald", fallbackEn: "coniferous forest", tip: "noun", article: "der" },
    { de: "der Mischwald", lookup: "Mischwald", fallbackEn: "mixed forest", tip: "noun", article: "der" },
    { de: "das Wurzelwerk", lookup: "Wurzelwerk", fallbackEn: "root system", tip: "noun", article: "das" },
    { de: "der Hochsitz", lookup: "Hochsitz", fallbackEn: "hunting stand", tip: "noun", article: "der" },
    { de: "die Lärche", lookup: "Lärche", fallbackEn: "larch", tip: "noun", article: "die" },
    { de: "die Esche", lookup: "Esche", fallbackEn: "ash tree", tip: "noun", article: "die" },
    { de: "die Eichel", lookup: "Eichel", fallbackEn: "acorn", tip: "noun", article: "die" },
    { de: "der Tannenzapfen", lookup: "Tannenzapfen", fallbackEn: "fir cone", tip: "noun", article: "der" },
    { de: "die Heide", lookup: "Heide", fallbackEn: "heath, moorland", tip: "noun", article: "die" },
    { de: "die Steppe", lookup: "Steppe", fallbackEn: "steppe", tip: "noun", article: "die" },
    { de: "die Oase", lookup: "Oase", fallbackEn: "oasis", tip: "noun", article: "die" },
    { de: "der Wildbach", lookup: "Wildbach", fallbackEn: "mountain torrent", tip: "noun", article: "der" },
    { de: "der Bergbach", lookup: "Bergbach", fallbackEn: "mountain stream", tip: "noun", article: "der" },
    { de: "der Weiher", lookup: "Weiher", fallbackEn: "pond", tip: "noun", article: "der" },
    { de: "das Naturschutzgebiet", lookup: "Naturschutzgebiet", fallbackEn: "nature reserve", tip: "noun", article: "das" },
    { de: "die Alm", lookup: "Alm", fallbackEn: "alpine pasture", tip: "noun", article: "die" },
    { de: "die Almwiese", lookup: "Almwiese", fallbackEn: "alpine meadow", tip: "noun", article: "die" },
    { de: "die Sennhütte", lookup: "Sennhütte", fallbackEn: "alpine dairy hut", tip: "noun", article: "die" },
    { de: "der Tropfstein", lookup: "Tropfstein", fallbackEn: "stalactite", tip: "noun", article: "der" },
    { de: "das Bergwerk", lookup: "Bergwerk", fallbackEn: "mine", tip: "noun", article: "das" },
  ]),
  part629: pack("Part 629", "B1", "Animals you might see", "What crosses the path, and what calls from the trees.", [
    { de: "das Murmeltier", lookup: "Murmeltier", fallbackEn: "marmot", tip: "noun", article: "das" },
    { de: "die Gams", lookup: "Gams", fallbackEn: "chamois", tip: "noun", article: "die" },
    { de: "der Bussard", lookup: "Bussard", fallbackEn: "buzzard", tip: "noun", article: "der" },
    { de: "der Kuckuck", lookup: "Kuckuck", fallbackEn: "cuckoo", tip: "noun", article: "der" },
    { de: "die Meise", lookup: "Meise", fallbackEn: "tit", tip: "noun", article: "die", use: "the small garden bird" },
    { de: "der Fink", lookup: "Fink", fallbackEn: "finch", tip: "noun", article: "der" },
    { de: "der Specht", lookup: "Specht", fallbackEn: "woodpecker", tip: "noun", article: "der" },
    { de: "der Molch", lookup: "Molch", fallbackEn: "newt", tip: "noun", article: "der" },
    { de: "die Kreuzotter", lookup: "Kreuzotter", fallbackEn: "adder", tip: "noun", article: "die" },
    { de: "der Marder", lookup: "Marder", fallbackEn: "marten", tip: "noun", article: "der" },
    { de: "das Wiesel", lookup: "Wiesel", fallbackEn: "weasel", tip: "noun", article: "das" },
  ]),
  part630: pack("Part 630", "B1", "Mountain weather, and when it goes wrong", "What the forecast warns about, and who comes for you.", [
    { de: "der Graupel", lookup: "Graupel", fallbackEn: "soft hail", tip: "noun", article: "der" },
    { de: "der Raureif", lookup: "Raureif", fallbackEn: "hoarfrost", tip: "noun", article: "der" },
    { de: "der Bodenfrost", lookup: "Bodenfrost", fallbackEn: "ground frost", tip: "noun", article: "der" },
    { de: "die Schneedecke", lookup: "Schneedecke", fallbackEn: "snow cover", tip: "noun", article: "die" },
    { de: "der Schneesturm", lookup: "Schneesturm", fallbackEn: "blizzard", tip: "noun", article: "der" },
    { de: "der Eiszapfen", lookup: "Eiszapfen", fallbackEn: "icicle", tip: "noun", article: "der" },
    { de: "die Glätte", lookup: "Glätte", fallbackEn: "icy conditions", tip: "noun", article: "die", use: "what the traffic report warns about in winter" },
    { de: "die Böe", lookup: "Böe", fallbackEn: "gust", tip: "noun", article: "die" },
    { de: "der Aufwind", lookup: "Aufwind", fallbackEn: "updraught", tip: "noun", article: "der", use: "what a bird circles on; also a figurative upturn" },
    { de: "die Lawinengefahr", lookup: "Lawinengefahr", fallbackEn: "avalanche risk", tip: "noun", article: "die" },
    { de: "der Steinschlag", lookup: "Steinschlag", fallbackEn: "rockfall", tip: "noun", article: "der" },
    { de: "die Höhenkrankheit", lookup: "Höhenkrankheit", fallbackEn: "altitude sickness", tip: "noun", article: "die" },
    { de: "die Bergrettung", lookup: "Bergrettung", fallbackEn: "mountain rescue", tip: "noun", article: "die" },
    { de: "die Signalpfeife", lookup: "Signalpfeife", fallbackEn: "signal whistle", tip: "noun", article: "die" },
  ]),
part631: pack("Part 631", "B1", "At the post office", "Sending something, and what the counter calls it.", [
    { de: "das Porto", lookup: "Porto", fallbackEn: "postage", tip: "noun", article: "das" },
    { de: "der Postbote", lookup: "Postbote", fallbackEn: "postman", tip: "noun", article: "der" },
    { de: "das Postfach", lookup: "Postfach", fallbackEn: "PO box", tip: "noun", article: "das" },
    { de: "die Postfiliale", lookup: "Postfiliale", fallbackEn: "post office branch", tip: "noun", article: "die" },
    { de: "die Frankiermaschine", lookup: "Frankiermaschine", fallbackEn: "franking machine", tip: "noun", article: "die" },
    { de: "die Warensendung", lookup: "Warensendung", fallbackEn: "goods shipment", tip: "noun", article: "die", use: "a cheap postal class for things rather than letters" },
    { de: "die Büchersendung", lookup: "Büchersendung", fallbackEn: "book rate parcel", tip: "noun", article: "die" },
    { de: "die Luftpost", lookup: "Luftpost", fallbackEn: "airmail", tip: "noun", article: "die" },
    { de: "die Nachnahme", lookup: "Nachnahme", fallbackEn: "cash on delivery", tip: "noun", article: "die" },
    { de: "zustellen", lookup: "zustellen", fallbackEn: "to deliver", tip: "verb", use: "what the post does; liefern is what a shop does" },
    { de: "die Zustellung", lookup: "Zustellung", fallbackEn: "delivery", tip: "noun", article: "die" },
    { de: "der Zustellversuch", lookup: "Zustellversuch", fallbackEn: "delivery attempt", tip: "noun", article: "der" },
    { de: "die Auslieferung", lookup: "Auslieferung", fallbackEn: "dispatch, delivery", tip: "noun", article: "die" },
    { de: "der Auslieferungsfahrer", lookup: "Auslieferungsfahrer", fallbackEn: "delivery driver", tip: "noun", article: "der" },
    { de: "die Empfangsbestätigung", lookup: "Empfangsbestätigung", fallbackEn: "proof of receipt", tip: "noun", article: "die" },
  ]),
  part632: pack("Part 632", "B1", "Packing a parcel", "What goes round it, what goes on it, and who pays if it breaks.", [
    { de: "die Versandtasche", lookup: "Versandtasche", fallbackEn: "mailing bag", tip: "noun", article: "die" },
    { de: "die Wellpappe", lookup: "Wellpappe", fallbackEn: "corrugated cardboard", tip: "noun", article: "die" },
    { de: "das Füllmaterial", lookup: "Füllmaterial", fallbackEn: "packing material", tip: "noun", article: "das" },
    { de: "der Aufkleber", lookup: "Aufkleber", fallbackEn: "sticker", tip: "noun", article: "der" },
    { de: "der Barcode", lookup: "Barcode", fallbackEn: "barcode", tip: "noun", article: "der" },
    { de: "das Sperrgut", lookup: "Sperrgut", fallbackEn: "bulky goods", tip: "noun", article: "das", use: "anything too big for the normal parcel rate" },
    { de: "der Lieferschein", lookup: "Lieferschein", fallbackEn: "delivery note", tip: "noun", article: "der" },
    { de: "der Frachtbrief", lookup: "Frachtbrief", fallbackEn: "consignment note", tip: "noun", article: "der" },
    { de: "die Frachtkosten", lookup: "Frachtkosten", fallbackEn: "freight charges", tip: "noun", article: "die", use: "always plural" },
    { de: "der Transportschaden", lookup: "Transportschaden", fallbackEn: "damage in transit", tip: "noun", article: "der" },
    { de: "die Haftungsgrenze", lookup: "Haftungsgrenze", fallbackEn: "liability limit", tip: "noun", article: "die" },
    { de: "der Versicherungswert", lookup: "Versicherungswert", fallbackEn: "insured value", tip: "noun", article: "der" },
  ]),
  part633: pack("Part 633", "B1", "Ordering, and sending it back", "The words an online order uses when something is wrong with it.", [
    { de: "die Bestellnummer", lookup: "Bestellnummer", fallbackEn: "order number", tip: "noun", article: "die" },
    { de: "die Bestellbestätigung", lookup: "Bestellbestätigung", fallbackEn: "order confirmation", tip: "noun", article: "die" },
    { de: "die Versandbestätigung", lookup: "Versandbestätigung", fallbackEn: "dispatch confirmation", tip: "noun", article: "die" },
    { de: "die Sammelbestellung", lookup: "Sammelbestellung", fallbackEn: "group order", tip: "noun", article: "die" },
    { de: "der Mindestbestellwert", lookup: "Mindestbestellwert", fallbackEn: "minimum order value", tip: "noun", article: "der" },
    { de: "die Nachbestellung", lookup: "Nachbestellung", fallbackEn: "repeat order", tip: "noun", article: "die" },
    { de: "die Vorkasse", lookup: "Vorkasse", fallbackEn: "payment in advance", tip: "noun", article: "die" },
    { de: "die Rechnungsadresse", lookup: "Rechnungsadresse", fallbackEn: "billing address", tip: "noun", article: "die" },
    { de: "die Lieferadresse", lookup: "Lieferadresse", fallbackEn: "delivery address", tip: "noun", article: "die" },
    { de: "der Lieferverzug", lookup: "Lieferverzug", fallbackEn: "late delivery", tip: "noun", article: "der" },
    { de: "die Teillieferung", lookup: "Teillieferung", fallbackEn: "part delivery", tip: "noun", article: "die" },
    { de: "die Ersatzlieferung", lookup: "Ersatzlieferung", fallbackEn: "replacement delivery", tip: "noun", article: "die" },
    { de: "das Rückgaberecht", lookup: "Rückgaberecht", fallbackEn: "right of return", tip: "noun", article: "das" },
    { de: "die Rücksendung", lookup: "Rücksendung", fallbackEn: "return shipment", tip: "noun", article: "die" },
    { de: "das Rücksendeetikett", lookup: "Rücksendeetikett", fallbackEn: "return label", tip: "noun", article: "das" },
    { de: "der Umtausch", lookup: "Umtausch", fallbackEn: "exchange", tip: "noun", article: "der", use: "swapping a bought item for another" },
    { de: "der Widerruf", lookup: "Widerruf", fallbackEn: "cancellation", tip: "noun", article: "der", use: "the legal right to undo an order within a fortnight" },
    { de: "die Reklamation", lookup: "Reklamation", fallbackEn: "complaint about goods", tip: "noun", article: "die" },
  ]),
  part634: pack("Part 634", "B1", "The warehouse behind the shop", "Where the goods sit before anyone orders them.", [
    { de: "die Spedition", lookup: "Spedition", fallbackEn: "haulage firm", tip: "noun", article: "die" },
    { de: "die Lagerhalle", lookup: "Lagerhalle", fallbackEn: "warehouse", tip: "noun", article: "die" },
    { de: "der Lagerbestand", lookup: "Lagerbestand", fallbackEn: "stock level", tip: "noun", article: "der" },
    { de: "der Gabelstapler", lookup: "Gabelstapler", fallbackEn: "forklift truck", tip: "noun", article: "der" },
    { de: "die Inventur", lookup: "Inventur", fallbackEn: "stocktaking", tip: "noun", article: "die" },
    { de: "der Großhandel", lookup: "Großhandel", fallbackEn: "wholesale", tip: "noun", article: "der" },
    { de: "der Einzelhandel", lookup: "Einzelhandel", fallbackEn: "retail", tip: "noun", article: "der" },
    { de: "der Zwischenhändler", lookup: "Zwischenhändler", fallbackEn: "middleman", tip: "noun", article: "der" },
    { de: "die Handelsware", lookup: "Handelsware", fallbackEn: "merchandise", tip: "noun", article: "die" },
    { de: "der Warenwert", lookup: "Warenwert", fallbackEn: "value of goods", tip: "noun", article: "der" },
    { de: "die Paketstation", lookup: "Paketstation", fallbackEn: "parcel locker", tip: "noun", article: "die" },
    { de: "die Abholstation", lookup: "Abholstation", fallbackEn: "collection point", tip: "noun", article: "die" },
  ]),
  part635: pack("Part 635", "B2", "Across a border", "What customs wants to know about a parcel.", [
    { de: "die Einfuhr", lookup: "Einfuhr", fallbackEn: "import", tip: "noun", article: "die" },
    { de: "die Ausfuhr", lookup: "Ausfuhr", fallbackEn: "export", tip: "noun", article: "die" },
    { de: "die Zollgebühr", lookup: "Zollgebühr", fallbackEn: "customs charge", tip: "noun", article: "die" },
    { de: "die Zollerklärung", lookup: "Zollerklärung", fallbackEn: "customs declaration", tip: "noun", article: "die" },
    { de: "die Zollinhaltserklärung", lookup: "Zollinhaltserklärung", fallbackEn: "customs contents form", tip: "noun", article: "die", use: "the green slip you stick on a parcel going abroad" },
    { de: "die Ausfuhrgenehmigung", lookup: "Ausfuhrgenehmigung", fallbackEn: "export licence", tip: "noun", article: "die" },
  ]),
  part636: pack("Part 636", "B2", "Insurance", "The cover a German household is expected to have.", [
    { de: "die Haftpflicht", lookup: "Haftpflicht", fallbackEn: "personal liability cover", tip: "noun", article: "die", use: "the policy that pays when you break someone's things" },
    { de: "der Hausrat", lookup: "Hausrat", fallbackEn: "household contents", tip: "noun", article: "der" },
    { de: "der Rechtsschutz", lookup: "Rechtsschutz", fallbackEn: "legal expenses cover", tip: "noun", article: "der" },
    { de: "die Prämie", lookup: "Prämie", fallbackEn: "premium, bonus", tip: "noun", article: "die", use: "what you pay an insurer, and a bonus at work" },
    { de: "der Versicherungsnehmer", lookup: "Versicherungsnehmer", fallbackEn: "policyholder", tip: "noun", article: "der" },
    { de: "der Versicherungsschutz", lookup: "Versicherungsschutz", fallbackEn: "insurance cover", tip: "noun", article: "der" },
    { de: "der Schadensfall", lookup: "Schadensfall", fallbackEn: "claim event", tip: "noun", article: "der", use: "im Schadensfall = if you have to claim" },
    { de: "die Teilkasko", lookup: "Teilkasko", fallbackEn: "third party fire and theft", tip: "noun", article: "die" },
    { de: "die Vollkasko", lookup: "Vollkasko", fallbackEn: "fully comprehensive cover", tip: "noun", article: "die" },
    { de: "die Berufsunfähigkeit", lookup: "Berufsunfähigkeit", fallbackEn: "inability to work", tip: "noun", article: "die" },
    { de: "die Beitragserhöhung", lookup: "Beitragserhöhung", fallbackEn: "premium increase", tip: "noun", article: "die" },
    { de: "die Bescheinigung", lookup: "Bescheinigung", fallbackEn: "certificate", tip: "noun", article: "die", use: "the piece of paper confirming something officially" },
  ]),
  part637: pack("Part 637", "B2", "Paying and being paid", "The paperwork either side of the money.", [
    { de: "der Beleg", lookup: "Beleg", fallbackEn: "receipt, voucher", tip: "noun", article: "der", use: "any slip that proves a payment" },
    { de: "die Quittung", lookup: "Quittung", fallbackEn: "receipt", tip: "noun", article: "die", use: "the one you ask for by name at a till" },
    { de: "die Rechnungsnummer", lookup: "Rechnungsnummer", fallbackEn: "invoice number", tip: "noun", article: "die" },
    { de: "die Steuernummer", lookup: "Steuernummer", fallbackEn: "tax number", tip: "noun", article: "die" },
    { de: "die Umsatzsteuer", lookup: "Umsatzsteuer", fallbackEn: "sales tax", tip: "noun", article: "die" },
    { de: "die Buchhaltung", lookup: "Buchhaltung", fallbackEn: "accounts, bookkeeping", tip: "noun", article: "die" },
    { de: "die Einzugsermächtigung", lookup: "Einzugsermächtigung", fallbackEn: "direct debit mandate", tip: "noun", article: "die" },
    { de: "das Guthaben", lookup: "Guthaben", fallbackEn: "credit balance", tip: "noun", article: "das" },
    { de: "die Abbuchung", lookup: "Abbuchung", fallbackEn: "debit", tip: "noun", article: "die" },
    { de: "der Zahlungseingang", lookup: "Zahlungseingang", fallbackEn: "incoming payment", tip: "noun", article: "der" },
    { de: "der Zahlungsverzug", lookup: "Zahlungsverzug", fallbackEn: "payment arrears", tip: "noun", article: "der" },
    { de: "die Bonität", lookup: "Bonität", fallbackEn: "creditworthiness", tip: "noun", article: "die" },
    { de: "die Bürgschaft", lookup: "Bürgschaft", fallbackEn: "guarantee, surety", tip: "noun", article: "die", use: "standing surety for someone else's debt" },
    { de: "die Vollstreckung", lookup: "Vollstreckung", fallbackEn: "enforcement", tip: "noun", article: "die" },
  ]),
part638: pack("Part 638", "B1", "How it actually feels", "What you say when the doctor asks what is wrong.", [
    { de: "das Kribbeln", lookup: "Kribbeln", fallbackEn: "tingling", tip: "noun", article: "das" },
    { de: "der Juckreiz", lookup: "Juckreiz", fallbackEn: "itching", tip: "noun", article: "der" },
    { de: "der Eiter", lookup: "Eiter", fallbackEn: "pus", tip: "noun", article: "der" },
    { de: "die Blutung", lookup: "Blutung", fallbackEn: "bleeding", tip: "noun", article: "die" },
    { de: "der Bruch", lookup: "Bruch", fallbackEn: "fracture, break", tip: "noun", article: "der", use: "a broken bone; also a hernia, and a fraction in maths" },
    { de: "der Schorf", lookup: "Schorf", fallbackEn: "scab", tip: "noun", article: "der" },
    { de: "das Herzrasen", lookup: "Herzrasen", fallbackEn: "racing heart", tip: "noun", article: "das" },
    { de: "die Ohnmacht", lookup: "Ohnmacht", fallbackEn: "fainting fit", tip: "noun", article: "die", use: "in Ohnmacht fallen = to faint" },
    { de: "die Blässe", lookup: "Blässe", fallbackEn: "pallor", tip: "noun", article: "die" },
    { de: "die Schlafstörung", lookup: "Schlafstörung", fallbackEn: "sleep disorder", tip: "noun", article: "die" },
  ]),
  part639: pack("Part 639", "B1", "Illnesses by name", "The ones a sick note, a vaccination record or a family history names.", [
    { de: "die Gicht", lookup: "Gicht", fallbackEn: "gout", tip: "noun", article: "die" },
    { de: "der Bluthochdruck", lookup: "Bluthochdruck", fallbackEn: "high blood pressure", tip: "noun", article: "der" },
    { de: "die Blinddarmentzündung", lookup: "Blinddarmentzündung", fallbackEn: "appendicitis", tip: "noun", article: "die" },
    { de: "der Nierenstein", lookup: "Nierenstein", fallbackEn: "kidney stone", tip: "noun", article: "der" },
    { de: "der Gallenstein", lookup: "Gallenstein", fallbackEn: "gallstone", tip: "noun", article: "der" },
    { de: "das Magengeschwür", lookup: "Magengeschwür", fallbackEn: "stomach ulcer", tip: "noun", article: "das" },
    { de: "die Neurodermitis", lookup: "Neurodermitis", fallbackEn: "eczema", tip: "noun", article: "die" },
    { de: "die Gürtelrose", lookup: "Gürtelrose", fallbackEn: "shingles", tip: "noun", article: "die" },
    { de: "die Masern", lookup: "Masern", fallbackEn: "measles", tip: "noun", article: "die", use: "always plural" },
    { de: "der Mumps", lookup: "Mumps", fallbackEn: "mumps", tip: "noun", article: "der" },
    { de: "die Röteln", lookup: "Röteln", fallbackEn: "rubella", tip: "noun", article: "die", use: "always plural" },
    { de: "der Keuchhusten", lookup: "Keuchhusten", fallbackEn: "whooping cough", tip: "noun", article: "der" },
    { de: "der Tetanus", lookup: "Tetanus", fallbackEn: "tetanus", tip: "noun", article: "der" },
    { de: "die Tollwut", lookup: "Tollwut", fallbackEn: "rabies", tip: "noun", article: "die" },
    { de: "die Malaria", lookup: "Malaria", fallbackEn: "malaria", tip: "noun", article: "die" },
    { de: "die Tuberkulose", lookup: "Tuberkulose", fallbackEn: "tuberculosis", tip: "noun", article: "die" },
    { de: "die Seuche", lookup: "Seuche", fallbackEn: "plague, epidemic disease", tip: "noun", article: "die" },
    { de: "die Panikattacke", lookup: "Panikattacke", fallbackEn: "panic attack", tip: "noun", article: "die" },
    { de: "der Alzheimer", lookup: "Alzheimer", fallbackEn: "Alzheimer's", tip: "noun", article: "der" },
  ]),
  part640: pack("Part 640", "B1", "Further into the body", "The parts a diagnosis names that a first course never does.", [
    { de: "die Schläfe", lookup: "Schläfe", fallbackEn: "temple", tip: "noun", article: "die", use: "the side of your head, not a building" },
    { de: "die Wade", lookup: "Wade", fallbackEn: "calf", tip: "noun", article: "die", use: "the back of your lower leg" },
    { de: "die Achsel", lookup: "Achsel", fallbackEn: "armpit", tip: "noun", article: "die" },
    { de: "das Fußgelenk", lookup: "Fußgelenk", fallbackEn: "ankle joint", tip: "noun", article: "das" },
    { de: "die Kniescheibe", lookup: "Kniescheibe", fallbackEn: "kneecap", tip: "noun", article: "die" },
    { de: "das Schulterblatt", lookup: "Schulterblatt", fallbackEn: "shoulder blade", tip: "noun", article: "das" },
    { de: "der Knorpel", lookup: "Knorpel", fallbackEn: "cartilage", tip: "noun", article: "der" },
    { de: "die Luftröhre", lookup: "Luftröhre", fallbackEn: "windpipe", tip: "noun", article: "die" },
    { de: "die Bauchspeicheldrüse", lookup: "Bauchspeicheldrüse", fallbackEn: "pancreas", tip: "noun", article: "die" },
    { de: "der Dickdarm", lookup: "Dickdarm", fallbackEn: "large intestine", tip: "noun", article: "der" },
    { de: "der Dünndarm", lookup: "Dünndarm", fallbackEn: "small intestine", tip: "noun", article: "der" },
    { de: "die Schilddrüse", lookup: "Schilddrüse", fallbackEn: "thyroid gland", tip: "noun", article: "die" },
    { de: "die Pupille", lookup: "Pupille", fallbackEn: "pupil (of the eye)", tip: "noun", article: "die" },
    { de: "der Gehörgang", lookup: "Gehörgang", fallbackEn: "ear canal", tip: "noun", article: "der" },
    { de: "das Immunsystem", lookup: "Immunsystem", fallbackEn: "immune system", tip: "noun", article: "das" },
    { de: "die Abwehrkräfte", lookup: "Abwehrkräfte", fallbackEn: "the body's defences", tip: "noun", article: "die", use: "always plural, and what a German conversation blames a cold on" },
    { de: "der Antikörper", lookup: "Antikörper", fallbackEn: "antibody", tip: "noun", article: "der" },
  ]),
  part641: pack("Part 641", "B1", "Tests and what they say", "The numbers on the printout, and the booklets that hold them.", [
    { de: "der Ultraschall", lookup: "Ultraschall", fallbackEn: "ultrasound", tip: "noun", article: "der" },
    { de: "der Blutwert", lookup: "Blutwert", fallbackEn: "blood level", tip: "noun", article: "der" },
    { de: "der Laborwert", lookup: "Laborwert", fallbackEn: "lab result", tip: "noun", article: "der" },
    { de: "der Blutzucker", lookup: "Blutzucker", fallbackEn: "blood sugar", tip: "noun", article: "der" },
    { de: "das Cholesterin", lookup: "Cholesterin", fallbackEn: "cholesterol", tip: "noun", article: "das" },
    { de: "die Körpertemperatur", lookup: "Körpertemperatur", fallbackEn: "body temperature", tip: "noun", article: "die" },
    { de: "die Krankenakte", lookup: "Krankenakte", fallbackEn: "medical file", tip: "noun", article: "die" },
    { de: "die Früherkennung", lookup: "Früherkennung", fallbackEn: "early detection", tip: "noun", article: "die" },
    { de: "der Mutterpass", lookup: "Mutterpass", fallbackEn: "maternity record", tip: "noun", article: "der", use: "the booklet a pregnancy is recorded in" },
    { de: "die Gesundheitskarte", lookup: "Gesundheitskarte", fallbackEn: "health insurance card", tip: "noun", article: "die" },
    { de: "die Sehschärfe", lookup: "Sehschärfe", fallbackEn: "visual acuity", tip: "noun", article: "die" },
    { de: "der Augenarzt", lookup: "Augenarzt", fallbackEn: "eye doctor", tip: "noun", article: "der" },
    { de: "der Kieferorthopäde", lookup: "Kieferorthopäde", fallbackEn: "orthodontist", tip: "noun", article: "der" },
  ]),
  part642: pack("Part 642", "B1", "Who treats you", "The job titles on the badge and on the referral.", [
    { de: "der Krankenpfleger", lookup: "Krankenpfleger", fallbackEn: "nurse", tip: "noun", article: "der" },
    { de: "die Pflegerin", lookup: "Pflegerin", fallbackEn: "carer", tip: "noun", article: "die" },
    { de: "der Sanitäter", lookup: "Sanitäter", fallbackEn: "paramedic", tip: "noun", article: "der" },
    { de: "der Rettungssanitäter", lookup: "Rettungssanitäter", fallbackEn: "emergency paramedic", tip: "noun", article: "der" },
    { de: "der Anästhesist", lookup: "Anästhesist", fallbackEn: "anaesthetist", tip: "noun", article: "der" },
    { de: "der Radiologe", lookup: "Radiologe", fallbackEn: "radiologist", tip: "noun", article: "der" },
    { de: "der Apotheker", lookup: "Apotheker", fallbackEn: "pharmacist", tip: "noun", article: "der" },
    { de: "der Physiotherapeut", lookup: "Physiotherapeut", fallbackEn: "physiotherapist", tip: "noun", article: "der" },
    { de: "der Ergotherapeut", lookup: "Ergotherapeut", fallbackEn: "occupational therapist", tip: "noun", article: "der" },
    { de: "der Logopäde", lookup: "Logopäde", fallbackEn: "speech therapist", tip: "noun", article: "der" },
    { de: "der Psychiater", lookup: "Psychiater", fallbackEn: "psychiatrist", tip: "noun", article: "der" },
    { de: "die Stationsschwester", lookup: "Stationsschwester", fallbackEn: "ward sister", tip: "noun", article: "die" },
    { de: "der Belegarzt", lookup: "Belegarzt", fallbackEn: "visiting consultant", tip: "noun", article: "der" },
    { de: "die Arzthelferin", lookup: "Arzthelferin", fallbackEn: "doctor's receptionist", tip: "noun", article: "die", use: "the person at the desk who books you in" },
  ]),
  part643: pack("Part 643", "B1", "The ambulance", "What arrives, what it sounds like, and what you do for it.", [
    { de: "der Krankenwagen", lookup: "Krankenwagen", fallbackEn: "ambulance", tip: "noun", article: "der" },
    { de: "der Rettungshubschrauber", lookup: "Rettungshubschrauber", fallbackEn: "air ambulance", tip: "noun", article: "der" },
    { de: "die Erstversorgung", lookup: "Erstversorgung", fallbackEn: "initial treatment", tip: "noun", article: "die" },
    { de: "die Unfallstelle", lookup: "Unfallstelle", fallbackEn: "scene of the accident", tip: "noun", article: "die" },
    { de: "das Blaulicht", lookup: "Blaulicht", fallbackEn: "flashing blue light", tip: "noun", article: "das" },
    { de: "das Martinshorn", lookup: "Martinshorn", fallbackEn: "siren", tip: "noun", article: "das", use: "the two-tone German siren, named after its maker" },
    { de: "die Rettungsgasse", lookup: "Rettungsgasse", fallbackEn: "emergency corridor", tip: "noun", article: "die", use: "the lane drivers must open on a jammed motorway" },
    { de: "der Notfall", lookup: "Notfall", fallbackEn: "emergency", tip: "noun", article: "der" },
    { de: "die Triage", lookup: "Triage", fallbackEn: "triage", tip: "noun", article: "die" },
    { de: "die Intensivstation", lookup: "Intensivstation", fallbackEn: "intensive care unit", tip: "noun", article: "die" },
    { de: "die Beatmungsmaske", lookup: "Beatmungsmaske", fallbackEn: "breathing mask", tip: "noun", article: "die" },
    { de: "der Notfallausweis", lookup: "Notfallausweis", fallbackEn: "emergency medical card", tip: "noun", article: "der" },
    { de: "der Allergiepass", lookup: "Allergiepass", fallbackEn: "allergy card", tip: "noun", article: "der" },
  ]),
  part644: pack("Part 644", "B1", "Treatment and what helps after", "What is put in, taken out, or handed to you on the way home.", [
    { de: "die Gehhilfe", lookup: "Gehhilfe", fallbackEn: "walking aid", tip: "noun", article: "die" },
    { de: "die Prothese", lookup: "Prothese", fallbackEn: "prosthesis", tip: "noun", article: "die" },
    { de: "der Herzschrittmacher", lookup: "Herzschrittmacher", fallbackEn: "pacemaker", tip: "noun", article: "der" },
    { de: "der Katheter", lookup: "Katheter", fallbackEn: "catheter", tip: "noun", article: "der" },
    { de: "die Wundnaht", lookup: "Wundnaht", fallbackEn: "stitches", tip: "noun", article: "die" },
    { de: "das Implantat", lookup: "Implantat", fallbackEn: "implant", tip: "noun", article: "das" },
    { de: "das Gebiss", lookup: "Gebiss", fallbackEn: "set of teeth, dentures", tip: "noun", article: "das" },
    { de: "die Transplantation", lookup: "Transplantation", fallbackEn: "transplant", tip: "noun", article: "die" },
    { de: "die Chemotherapie", lookup: "Chemotherapie", fallbackEn: "chemotherapy", tip: "noun", article: "die" },
    { de: "die Bestrahlung", lookup: "Bestrahlung", fallbackEn: "radiotherapy", tip: "noun", article: "die" },
    { de: "die Geschwulst", lookup: "Geschwulst", fallbackEn: "growth, swelling", tip: "noun", article: "die" },
    { de: "die Mullbinde", lookup: "Mullbinde", fallbackEn: "gauze bandage", tip: "noun", article: "die" },
    { de: "die Kompresse", lookup: "Kompresse", fallbackEn: "compress", tip: "noun", article: "die" },
    { de: "das Brillengestell", lookup: "Brillengestell", fallbackEn: "spectacle frame", tip: "noun", article: "das" },
    { de: "die Kontaktlinse", lookup: "Kontaktlinse", fallbackEn: "contact lens", tip: "noun", article: "die" },
    { de: "der Treppenlift", lookup: "Treppenlift", fallbackEn: "stairlift", tip: "noun", article: "der" },
  ]),
  part645: pack("Part 645", "B1", "At the pharmacy", "What the counter asks and what the leaflet warns.", [
    { de: "die Rezeptpflicht", lookup: "Rezeptpflicht", fallbackEn: "prescription requirement", tip: "noun", article: "die" },
    { de: "die Packungsbeilage", lookup: "Packungsbeilage", fallbackEn: "package leaflet", tip: "noun", article: "die" },
    { de: "die Augentropfen", lookup: "Augentropfen", fallbackEn: "eye drops", tip: "noun", article: "die", use: "always plural" },
    { de: "die Ohrentropfen", lookup: "Ohrentropfen", fallbackEn: "ear drops", tip: "noun", article: "die", use: "always plural" },
    { de: "die Nahrungsergänzung", lookup: "Nahrungsergänzung", fallbackEn: "dietary supplement", tip: "noun", article: "die" },
    { de: "die Rezeptgebühr", lookup: "Rezeptgebühr", fallbackEn: "prescription charge", tip: "noun", article: "die" },
    { de: "das Heilmittel", lookup: "Heilmittel", fallbackEn: "remedy", tip: "noun", article: "das" },
    { de: "das Hilfsmittel", lookup: "Hilfsmittel", fallbackEn: "aid, assistive device", tip: "noun", article: "das" },
    { de: "die Überdosis", lookup: "Überdosis", fallbackEn: "overdose", tip: "noun", article: "die" },
    { de: "die Vergiftung", lookup: "Vergiftung", fallbackEn: "poisoning", tip: "noun", article: "die" },
    { de: "das Blutdruckmessgerät", lookup: "Blutdruckmessgerät", fallbackEn: "blood pressure monitor", tip: "noun", article: "das" },
    { de: "das Desinfektionsmittel", lookup: "Desinfektionsmittel", fallbackEn: "disinfectant", tip: "noun", article: "das" },
    { de: "die Wärmflasche", lookup: "Wärmflasche", fallbackEn: "hot water bottle", tip: "noun", article: "die" },
  ]),
  part646: pack("Part 646", "B1", "Getting better", "The slow half, after the treatment is over.", [
    { de: "genesen", lookup: "genesen", fallbackEn: "to recover", tip: "verb", use: "the formal word; sich erholen is the everyday one" },
    { de: "die Genesung", lookup: "Genesung", fallbackEn: "recovery", tip: "noun", article: "die" },
    { de: "die Schonung", lookup: "Schonung", fallbackEn: "taking it easy", tip: "noun", article: "die" },
    { de: "die Schonkost", lookup: "Schonkost", fallbackEn: "bland diet", tip: "noun", article: "die" },
    { de: "die Dehnung", lookup: "Dehnung", fallbackEn: "stretching", tip: "noun", article: "die" },
    { de: "die Beweglichkeit", lookup: "Beweglichkeit", fallbackEn: "mobility", tip: "noun", article: "die" },
    { de: "der Muskelaufbau", lookup: "Muskelaufbau", fallbackEn: "building muscle", tip: "noun", article: "der" },
    { de: "die Mangelernährung", lookup: "Mangelernährung", fallbackEn: "malnutrition", tip: "noun", article: "die" },
    { de: "die Laktose", lookup: "Laktose", fallbackEn: "lactose", tip: "noun", article: "die" },
    { de: "das Gluten", lookup: "Gluten", fallbackEn: "gluten", tip: "noun", article: "das" },
    { de: "die Gewichtszunahme", lookup: "Gewichtszunahme", fallbackEn: "weight gain", tip: "noun", article: "die" },
    { de: "die Gewichtsabnahme", lookup: "Gewichtsabnahme", fallbackEn: "weight loss", tip: "noun", article: "die" },
    { de: "verabreichen", lookup: "verabreichen", fallbackEn: "to administer", tip: "verb", use: "what a nurse does with a dose" },
    { de: "röntgen", lookup: "röntgen", fallbackEn: "to X-ray", tip: "verb", use: "from Röntgen, who found the rays" },
    { de: "schienen", lookup: "schienen", fallbackEn: "to splint", tip: "verb" },
    { de: "humpeln", lookup: "humpeln", fallbackEn: "to hobble", tip: "verb" },
    { de: "hinken", lookup: "hinken", fallbackEn: "to limp", tip: "verb", use: "also of a comparison that does not hold" },
  ]),
  part647: pack("Part 647", "B1", "A birth, and care in old age", "The two ends of a life, and the words around them.", [
    { de: "der Kaiserschnitt", lookup: "Kaiserschnitt", fallbackEn: "caesarean section", tip: "noun", article: "der" },
    { de: "die Frühgeburt", lookup: "Frühgeburt", fallbackEn: "premature birth", tip: "noun", article: "die" },
    { de: "die Stillzeit", lookup: "Stillzeit", fallbackEn: "breastfeeding period", tip: "noun", article: "die" },
    { de: "das Wochenbett", lookup: "Wochenbett", fallbackEn: "period after childbirth", tip: "noun", article: "das" },
    { de: "die Altenpflege", lookup: "Altenpflege", fallbackEn: "elderly care", tip: "noun", article: "die" },
    { de: "das Seniorenheim", lookup: "Seniorenheim", fallbackEn: "retirement home", tip: "noun", article: "das" },
    { de: "die Betreuung", lookup: "Betreuung", fallbackEn: "care, supervision", tip: "noun", article: "die" },
    { de: "die Sturzgefahr", lookup: "Sturzgefahr", fallbackEn: "risk of falling", tip: "noun", article: "die" },
    { de: "die Selbsthilfegruppe", lookup: "Selbsthilfegruppe", fallbackEn: "support group", tip: "noun", article: "die" },
    { de: "die Vorsorgevollmacht", lookup: "Vorsorgevollmacht", fallbackEn: "lasting power of attorney", tip: "noun", article: "die" },
  ]),
  part648: pack("Part 648", "B2", "What the insurer pays for", "The German health system, in the words it uses about itself.", [
    { de: "der Eigenanteil", lookup: "Eigenanteil", fallbackEn: "own contribution", tip: "noun", article: "der" },
    { de: "der Kassenpatient", lookup: "Kassenpatient", fallbackEn: "public health patient", tip: "noun", article: "der" },
    { de: "der Privatpatient", lookup: "Privatpatient", fallbackEn: "private patient", tip: "noun", article: "der" },
    { de: "die Wahlleistung", lookup: "Wahlleistung", fallbackEn: "optional extra service", tip: "noun", article: "die" },
    { de: "der Nachtdienst", lookup: "Nachtdienst", fallbackEn: "night duty", tip: "noun", article: "der" },
    { de: "der Schichtdienst", lookup: "Schichtdienst", fallbackEn: "shift work", tip: "noun", article: "der" },
    { de: "die Beitragsbemessung", lookup: "Beitragsbemessung", fallbackEn: "contribution assessment", tip: "noun", article: "die" },
  ]),
};
