import bundledWordBank from "@/lib/bundledWordBank.json";

type WordBankEntry = {
  de?: string;
  en?: string;
  lookup?: string;
  tip?: string;
};

const stripGermanPunctuation = (value: string) => String(value ?? "")
  .normalize("NFC")
  .replace(/^[\s.,!?;:()[\]{}"'„“‚‘«»…–—-]+|[\s.,!?;:()[\]{}"'„“‚‘«»…–—-]+$/gu, "");

const wordKey = (value: string) => stripGermanPunctuation(value).toLocaleLowerCase("de-DE");

const conciseGloss = (value: string) => String(value ?? "")
  .trim()
  .replace(/\s+/g, " ")
  .replace(/,\s*/g, " / ");

const exactGlosses = new Map<string, string>();
const verbFormGlosses = new Map<string, string>();
const adjectiveFormGlosses = new Map<string, string>();
const nounGlosses = new Map<string, string>();

const addGloss = (map: Map<string, string>, words: string, gloss: string) => {
  for (const word of words.split(/\s+/).filter(Boolean)) {
    const key = wordKey(word);
    if (key && !map.has(key)) map.set(key, gloss);
  }
};

// High-frequency grammar words and irregular forms are deliberately curated.
// A single word can have several normal English meanings, so short alternatives
// are shown where context decides which one fits.
const coreGlossGroups: Array<[string, string]> = [
  ["ich", "I"],
  ["du", "you (informal)"],
  ["er", "he / it"],
  ["sie", "she / they / you (formal)"],
  ["es", "it"],
  ["wir", "we"],
  ["ihr", "you all / her / their"],
  ["ihre ihren ihrem ihrer ihres", "her / their / your (formal)"],
  ["mich", "me"],
  ["dich", "you (informal)"],
  ["ihn", "him / it"],
  ["uns", "us"],
  ["euch", "you all"],
  ["mir", "me / to me"],
  ["dir", "you / to you (informal)"],
  ["ihm", "him / it / to him"],
  ["ihnen", "them / you (formal)"],
  ["mein meine meinen meinem meiner meines", "my / mine"],
  ["dein deine deinen deinem deiner deines", "your / yours (informal)"],
  ["sein", "be / his / its"],
  ["seine seinen seinem seiner seines", "his / its"],
  ["unser unsere unseren unserem unserer unseres", "our / ours"],
  ["euer eure euren eurem eurer eures", "your / yours (plural)"],
  ["dies dieser diese diesen diesem dieses", "this / these"],
  ["jener jene jenen jenem jenes", "that / those"],
  ["der die das den dem des", "the / that / which"],
  ["ein eine einen einem einer eines", "a / an / one"],
  ["kein keine keinen keinem keiner keines", "no / not a / none"],
  ["wer", "who"],
  ["wen wem", "whom / who"],
  ["wessen", "whose"],
  ["was", "what"],
  ["wann", "when"],
  ["wo", "where"],
  ["wohin", "where to"],
  ["woher", "where from"],
  ["irgendwo", "somewhere"],
  ["warum wieso weshalb", "why"],
  ["wie", "how / like"],
  ["welch welcher welche welchen welchem welches", "which"],
  ["und", "and"],
  ["oder", "or"],
  ["aber", "but"],
  ["sondern", "but rather"],
  ["weil", "because"],
  ["denn", "because / then"],
  ["da", "there / since"],
  ["dass", "that"],
  ["wenn", "if / when"],
  ["falls", "if / in case"],
  ["ob", "whether / if"],
  ["obwohl", "although"],
  ["während", "while / during"],
  ["bevor", "before"],
  ["sobald", "as soon as"],
  ["nachdem", "after"],
  ["damit", "so that / with it"],
  ["als", "as / when / than"],
  ["also", "so / therefore"],
  ["deshalb deswegen darum", "that's why / therefore"],
  ["trotzdem", "still / nevertheless"],
  ["sonst", "otherwise / else"],
  ["für", "for"],
  ["wegen", "because of"],
  ["mit", "with"],
  ["ohne", "without"],
  ["gegen", "against / around"],
  ["durch", "through"],
  ["um", "around / at / in order to"],
  ["bis", "until / by"],
  ["von", "from / of / by"],
  ["zu", "to / too"],
  ["bei", "at / with / near"],
  ["nach", "after / to"],
  ["aus", "from / out of"],
  ["seit", "since / for"],
  ["vor", "before / in front of / ago"],
  ["hinter", "behind"],
  ["neben", "next to / besides"],
  ["zwischen", "between"],
  ["über", "over / about"],
  ["unter", "under / among"],
  ["an", "at / on"],
  ["auf", "on / onto"],
  ["in", "in / into"],
  ["im", "in the"],
  ["ins", "into the"],
  ["aufs", "onto the / on the"],
  ["am", "at the / on the"],
  ["ans", "to the / onto the"],
  ["beim", "at the / while"],
  ["vom", "from the / of the"],
  ["zum", "to the"],
  ["zur", "to the"],
  ["fürs", "for the"],
  ["übers", "over the / about the"],
  ["nicht", "not"],
  ["ja", "yes / of course"],
  ["nein", "no"],
  ["doch", "yes (contradicting) / though / actually"],
  ["auch", "also / too"],
  ["nur", "only / just"],
  ["schon", "already / certainly"],
  ["noch", "still / another / yet"],
  ["erst", "only / not until / first"],
  ["wieder", "again"],
  ["immer", "always"],
  ["nie niemals", "never"],
  ["oft", "often"],
  ["manchmal", "sometimes"],
  ["vielleicht", "maybe / perhaps"],
  ["wahrscheinlich", "probably"],
  ["wirklich", "really"],
  ["überhaupt", "at all / generally"],
  ["etwa", "about / approximately"],
  ["eigentlich", "actually / really"],
  ["genau", "exactly"],
  ["einfach", "simply / easy"],
  ["gerade", "just now / straight"],
  ["gleich", "in a moment / same"],
  ["mal", "just / sometime"],
  ["halt eben", "just / simply"],
  ["sehr", "very"],
  ["so", "so / like that"],
  ["zu", "too / to"],
  ["mehr", "more"],
  ["weniger", "less / fewer"],
  ["viel viele vielen vielem vieler vieles", "much / many / a lot"],
  ["wenig wenige wenigen wenigem weniger weniges", "little / few"],
  ["alles", "everything / all"],
  ["alle allen aller", "all / everyone"],
  ["etwas", "something / a little"],
  ["nichts", "nothing"],
  ["jemand jemanden jemandem", "someone / somebody"],
  ["niemand niemanden niemandem", "nobody / no one"],
  ["man", "you / people / one"],
  ["selbst selber", "self / yourself"],
  ["sich", "himself / herself / itself / themselves"],
  ["hier", "here"],
  ["dort", "there"],
  ["drinnen", "inside"],
  ["draußen", "outside"],
  ["heute", "today"],
  ["morgen", "tomorrow / morning"],
  ["gestern", "yesterday"],
  ["jetzt", "now"],
  ["dann", "then"],
  ["später", "later"],
  ["vorher", "before / beforehand"],
  ["früher", "earlier / in the past"],
  ["sofort", "right away"],
  ["gern gerne", "gladly / like to"],
  ["bitte", "please / you're welcome"],
  ["danke", "thanks / thank you"],
  ["hallo", "hello"],
  ["tschüss", "bye"],
  ["okay ok", "okay"],
  ["ab", "off / from"],
  ["dran", "on it / your turn"],
  ["daran", "on that / about that"],
  ["darauf", "on that / after that"],
  ["darüber", "about it / above it"],
  ["drüber", "about it / over it"],
  ["danach", "after that / afterwards"],
  ["drauf", "on it / onto it"],
  ["dabei", "with it / while doing so"],
  ["dafür", "for it / for that"],
  ["davon", "of it / from it"],
  ["dazu", "for that / with it / also"],
  ["zurück", "back"],
  ["hin", "there / toward"],
  ["her", "here / toward the speaker"],
  ["drin", "inside / in it"],
  ["raus", "out"],
  ["runter", "down"],
  ["vorne", "at the front"],
  ["hinten", "at the back"],
  ["zusammen", "together"],
  ["vorbei", "over / past"],
  ["los", "off / let's go"],
  ["einmal", "once / one time"],
  ["zweimal", "twice"],
  ["dreimal", "three times"],
  ["diesmal", "this time"],
  ["nochmal", "again / one more time"],
  ["bisschen", "a little / a bit"],
  ["gar", "at all / completely"],
  ["kaum", "hardly / barely"],
  ["eher", "rather / sooner"],
  ["genug", "enough"],
  ["fast", "almost"],
  ["wohl", "probably / well"],
  ["endlich", "finally"],
  ["ewig", "forever / ages"],
  ["eh", "anyway"],
  ["egal", "doesn't matter / no matter"],
  ["zuerst", "first / at first"],
  ["unbedingt", "definitely / absolutely"],
  ["ziemlich", "quite / fairly"],
  ["anders", "different / differently"],
  ["andere anderen anderem anderer anderes", "other / different"],
  ["allein alleine", "alone"],
  ["beide beiden beider beides", "both"],
  ["froh", "glad / happy"],
  ["kaputt", "broken"],
  ["länger", "longer"],
  ["verrückt", "crazy"],
  ["letzte letzten letzter letztem letztes", "last"],
  ["leider", "unfortunately"],
  ["sorry", "sorry"],
  ["na", "well / hey"],
  ["ach oh", "oh"],
  ["ne", "a / right? (colloquial)"],
  ["links", "left"],
  ["rechts", "right"],
  ["müde", "tired"],
  ["milch", "milk"],
  ["brot", "bread"],
  ["deutschland", "Germany"],
  ["waffe", "weapon"],
  ["jacke", "jacket"],
  ["regal", "shelf"],
  ["schluss", "end / finish"],
  ["ki", "AI"],
  ["weh", "sore / hurt"],
  ["ich's", "I ... it"],
  ["du's", "you ... it"],
  ["bescheid", "information / notice"],
  ["ahnung", "idea / clue"],
  ["entschuldigung", "sorry / excuse me"],
  ["vorsicht", "careful / watch out"],
  ["feierabend", "finished work / time off after work"],
  ["verspätung", "delay / lateness"],
  ["bad", "bathroom"],
  ["stück", "piece"],
  ["unterwegs", "on the way / out and about"],
  ["paar", "a few / a couple"],
  ["hab's", "have it"],
  ["geht's", "how's it going / is it going"],
  ["gibt's", "there is / there are"],
  ["jeder jede jeden jedem jedes", "every / each"],
  ["eins", "one"],
  ["zwei", "two"],
  ["drei", "three"],
  ["vier", "four"],
  ["fünf", "five"],
  ["sechs", "six"],
  ["sieben", "seven"],
  ["acht", "eight"],
  ["neun", "nine"],
  ["zehn", "ten"],
  ["elf", "eleven"],
  ["zwölf", "twelve"],
  ["dreizehn", "thirteen"],
  ["vierzehn", "fourteen"],
  ["fünfzehn", "fifteen"],
  ["sechzehn", "sixteen"],
  ["siebzehn", "seventeen"],
  ["achtzehn", "eighteen"],
  ["neunzehn", "nineteen"],
  ["zwanzig", "twenty"],
  ["dreißig", "thirty"],
  ["vierzig", "forty"],
  ["fünfzig", "fifty"],
  ["sechzig", "sixty"],
  ["siebzig", "seventy"],
  ["achtzig", "eighty"],
  ["neunzig", "ninety"],
  ["hundert", "hundred"],
  ["null", "zero"],
  ["erste ersten erster erstem erstes", "first"],
  ["zweite zweiten zweiter zweitem zweites", "second"],
  ["dritte dritten dritter drittem drittes", "third"],
  ["nächste nächsten nächster nächstem nächstes", "next"],
  ["beste besten bester bestem bestes", "best"],
  ["bin bist ist sind seid war warst waren wart gewesen", "be / am / is / are / was / were"],
  ["habe hast hat haben habt hatte hattest hatten hattet gehabt", "have / has / had"],
  ["werde wirst wird werden werdet wurde wurdest wurden wurdet geworden", "become / will / became"],
  ["kann kannst können könnt konnte konntest konnten konntet gekonnt", "can / be able to"],
  ["muss musst müssen müsst musste musstest mussten musstet gemusst", "must / have to"],
  ["will willst wollen wollt wollte wolltest wollten wolltet gewollt", "want / want to"],
  ["soll sollst sollen sollt sollte solltest sollten solltet gesollt", "should / be supposed to"],
  ["darf darfst dürfen dürft durfte durftest durften durftet gedurft", "may / be allowed to"],
  ["mag magst mögen mögt mochte mochtest mochten mochtet gemocht", "like"],
  ["möchte möchtest möchten möchtet", "would like"],
  ["wäre wär wärst wären wärt", "would be"],
  ["hätte hätt hättest hätten hättet", "would have"],
  ["würde würd würdest würden würdet", "would"],
  ["könnte könntest könnten könntet", "could"],
  ["müsste müsstest müssten müsstet", "would have to"],
  ["dürfte dürftest dürften dürftet", "might / would be allowed to"],
  ["weiß weißt wissen wisst wusste wusstest wussten wusstet gewusst", "know"],
  ["gehe gehst geht gehen ging gingst gingen gingt gegangen", "go / walk"],
  ["komme kommst kommt kommen kam kamst kamen kamt gekommen", "come"],
  ["angekommen", "arrived"],
  ["kriege krieg kriegst kriegt kriegen", "get / manage"],
  ["sehe siehst sieht sehen sah sahst sahen saht gesehen", "see"],
  ["spreche sprichst spricht sprechen sprach sprachst sprachen spracht gesprochen", "speak / talk"],
  ["sage sagst sagt sagen sagte sagtest sagten sagtet gesagt", "say / tell"],
  ["denke denkst denkt denken dachte dachtest dachten dachtet gedacht", "think"],
  ["finde findest findet finden fand fandest fanden fandet gefunden", "find / think"],
  ["nehme nimmst nimmt nehmen nahm nahmst nahmen nahmt genommen", "take"],
  ["nimm", "take"],
  ["gebe gibst gibt geben gab gabst gaben gabt gegeben", "give / there is"],
  ["koste kostest kostet kosten kostete gekostet", "cost / taste"],
  ["falle fällst fällt fallen fiel fielst fielen fielt gefallen", "fall / be pleasing"],
  ["gefällt", "is pleasing / likes"],
  ["bleibe bleibst bleibt bleiben blieb bliebst blieben bliebt geblieben", "stay / remain"],
  ["lasse lässt lasst lassen ließ ließt ließen ließt gelassen", "let / leave"],
  // Position vs placement, plus the untruth verb English collapses into "lie".
  // These six are the pairs learners actually mix up, so each gloss names what
  // the OTHER one isn't: liegen/sitzen/stehen say where something already is
  // (no object), legen/setzen/stellen put something there (they take one), and
  // lügen has nothing to do with either — English just spells it the same.
  ["stehe stehst steht stehen stand standest standen standet gestanden", "be standing / be upright"],
  ["stelle stellst stellt stellen stellte stelltest stellten stelltet gestellt", "stand something up / put upright"],
  ["liege liegst liegt liegen lag lagst lagen lagt gelegen", "be lying / be located (not tell a lie)"],
  ["lege legst legt legen legte legtest legten legtet gelegt", "lay something down / put flat"],
  ["lüge lügst lügt lügen log logst logen logt gelogen", "tell a lie / lie to someone"],
  ["sitze sitzt sitzen saß saßt saßen gesessen", "be sitting / be seated"],
  ["setze setzt setzen setzte setztest setzten setztet gesetzt", "sit someone down / put, set"],
  ["esse isst esst essen aß aßt aßen gegessen", "eat"],
  ["trinke trinkst trinkt trinken trank trankst tranken trankt getrunken", "drink"],
  ["fahre fährst fährt fahren fuhr fuhrst fuhren fuhrt gefahren", "drive / travel"],
  ["schlafe schläfst schläft schlafen schlief schliefst schliefen schlieft geschlafen", "sleep"],
  ["lese liest lest lesen las last lasen gelesen", "read"],
  ["schreibe schreibst schreibt schreiben schrieb schriebst schrieben schriebt geschrieben", "write"],
  ["bringe bringst bringt bringen brachte brachtest brachten brachtet gebracht", "bring"],
  ["tue tust tut tun tat tatest taten tatet getan", "do"],
  ["heiße heißt heißen hieß hießt hießen geheißen", "be called / mean"],
  ["helfe hilfst hilft helfen half halfst halfen halft geholfen", "help"],
  ["treffe triffst trifft treffen traf trafst trafen traft getroffen", "meet / hit"],
  ["laufe läufst läuft laufen lief liefst liefen lieft gelaufen", "run / walk"],
  ["halte hältst hält halten hielt hieltest hielten hieltet gehalten", "hold / stop"],
  ["verstehe verstehst versteht verstehen verstand verstandest verstanden verstandet", "understand"],
  ["vergesse vergisst vergesst vergessen vergaß vergaßt vergaßen", "forget"],
  ["verliere verlierst verliert verlieren verlor verlorst verloren", "lose"],
  ["fange fängst fängt fangen fing fingst fingen fingt", "catch / start"],
  ["fang", "catch / start"],
  ["angefangen", "started"],
  ["rufe rufst ruft rufen rief riefst riefen gerufen angerufen", "call / shout"],
  ["gucke guckst guckt gucken geguckt", "look / watch"],
  ["gelte giltst gilt gelten galt galten gegolten", "apply / be valid"],
  ["wünsche wünschst wünscht wünschen wünschte wünschtest wünschten gewünscht", "wish"],
  ["verspreche versprichst verspricht versprechen versprach versprochen", "promise"],
  ["gedanke gedanken", "thought"],
  ["gleis gleise gleisen", "platform / track"],
  ["oma omas", "grandma"],
  ["opa opas", "grandpa"],
  ["blume blumen", "flower"],
  ["glückwunsch glückwünsche", "congratulations"],
  ["wäsche", "washing / laundry"],
  ["irgendwann", "at some point"],
  ["meistens", "usually / mostly"],
  ["super", "great / super"],
  ["abends", "in the evenings"],
  ["morgens", "in the mornings"],
  ["drüben", "over there"],
  ["rüber", "over / across"],
  ["oben", "up / at the top"],
  ["unten", "down / at the bottom"],
  ["kühlschrank kühlschränke", "fridge"],
  ["heizung heizungen", "heating"],
  ["online", "online"],
  ["per", "by / via"],
  ["sofa sofas", "sofa"],
  ["toi", "(toi, toi, toi) good luck"],
  ["geschnitten", "cut / sliced"],
  ["statt", "instead of"],
  ["daumen", "thumb"],
  ["reserviert", "reserved"],
  ["rieche riechst riecht riechen roch gerochen", "smell"],
  ["wach", "awake"],
  ["ausgefallen", "cancelled / unusual"],
  ["bloß", "just / only"],
  ["cent", "cent"],
  ["flur flure", "hall / hallway"],
  ["gebeten", "asked / requested"],
  ["guck", "look / watch"],
  ["hey", "hey"],
  ["irgendwie", "somehow"],
  ["kilo kilos", "kilo"],
  ["anna tom jonas", "(name)"],
  ["damals", "back then"],
  ["sogar", "even"],
  ["tüte tüten", "bag"],
  ["brille brillen", "glasses"],
  ["extra", "extra / specially"],
  ["irgendwas", "something / anything"],
  ["je", "ever / per"],
  ["komisch", "funny / odd"],
  ["lach lache lachst lacht lachen lachte gelacht", "laugh"],
  ["meinte meintest meinten gemeint", "meant / said"],
  ["mist", "darn / blast"],
  ["schlimmer", "worse"],
  ["tee tees", "tea"],
  ["überall", "everywhere"],
  ["übrigens", "by the way"],
  ["wenn's", "if it / when it"],
  ["zweihundert", "two hundred"],
  ["aufhören", "to stop"],
  ["schwanz schwänze", "tail"],
  ["deckel", "lid / beer mat (tab)"],
  ["mitternacht", "midnight"],
  ["suppe suppen", "soup"],
  ["anstoßen", "to clink glasses / to toast"],
  ["bald", "soon"],
  ["freut", "pleases / is glad"],
  ["hauptsache", "the main thing"],
  ["hoffentlich", "hopefully"],
  ["prost", "cheers"],
  ["schlimm", "bad / serious"],
  ["aufzug aufzüge", "lift / elevator"],
  ["automat automaten", "machine / dispenser"],
  ["besonders", "especially"],
  ["dünn", "thin"],
  ["eingeschlafen", "fallen asleep"],
  ["gib", "give"],
  ["homeoffice", "working from home"],
  ["beileid", "condolences"],
  ["abseits", "offside"],
  ["mail mails", "email"],
  ["nerven", "nerves"],
  ["treppenhaus", "stairwell"],
  ["unterschreiben unterschrieben", "to sign"],
  ["wlan", "wifi"],
  ["brötchen", "bread roll"],
  ["dasselbe", "the same"],
  ["hose hosen", "trousers"],
  ["inzwischen", "by now / meanwhile"],
  ["käse", "cheese"],
  ["kiste kisten", "box / crate"],
  ["manche", "some"],
  ["muskelkater", "muscle ache"],
  ["nachts", "at night"],
  ["pro", "per"],
  ["scheiße", "(rude) damn / crap"],
  ["kita kitas", "nursery / daycare"],
  ["fieber", "fever"],
  ["mathe", "maths"],
  ["router", "router"],
  ["süß", "sweet / cute"],
  ["vergiss", "forget"],
  ["werkstatt werkstätten", "garage / workshop"],
  ["zettel", "note / slip of paper"],
  ["allem", "everything (dative)"],
  ["bar", "cash"],
  ["fällig", "due"],
  ["heiraten", "to marry"],
  ["innerhalb", "within"],
  ["lädt", "loads / invites"],
  ["leihen", "to lend / to borrow"],
  ["schlaf", "sleep"],
  ["schwimmen", "to swim"],
  ["sonntags", "on Sundays"],
  ["abgemacht", "agreed / it is a deal"],
  ["billiger", "cheaper"],
  ["keller", "cellar / basement"],
  ["klingelt", "rings"],
  ["tomaten", "tomatoes"],
  ["übernimmt", "takes over"],
  ["überweisung", "bank transfer"],
  ["waschen", "to wash"],
  ["absagen", "to cancel / to decline"],
  ["briefkasten", "letterbox / postbox"],
  ["erstaunlich", "astonishing"],
  ["frisst", "eats (of an animal)"],
  ["genauso", "exactly the same"],
  ["grüß", "greet / say hello"],
  ["heb", "lift / keep"],
  ["kürzer", "shorter"],
  ["nachher", "afterwards / later"],
  ["rückmeldung", "reply / feedback"],
  ["hamburg", "Hamburg (city)"],
  ["koffer", "suitcase"],
  ["schlange", "queue / snake"],
  ["angemeldet", "signed up / registered"],
  ["arm", "arm / poor"],
  ["griff", "handle / grip"],
  ["hochzeit", "wedding"],
  ["salat", "salad / lettuce"],
  ["seitdem", "since then"],
  ["tafel", "board / bar of chocolate"],
  ["taxi", "taxi"],
  ["tippe", "type / tap in"],
  ["trägt", "carries / wears"],
  ["tüv", "TÜV, the vehicle inspection"],
  ["untertiteln", "subtitles"],
  ["vorsichtig", "careful / carefully"],
  ["weber", "Weber (surname)"],
  ["woran", "at what / of what"],
  ["abgegeben", "handed in"],
  ["größer", "bigger"],
  ["meisten", "most"],
  ["still", "quiet / still"],
  ["fundbüro", "lost-property office"],
  ["futter", "lining / animal feed"],
  ["herum", "around"],
  ["notdienst", "emergency duty"],
  ["öfter", "more often"],
  ["spiegel", "mirror"],
  ["trinkgeld", "tip"],
  ["worauf", "on what / for what"],
  ["zufällig", "by chance"],
  ["zwiebeln", "onions"],
  ["abendessen", "dinner / evening meal"],
  ["absage", "cancellation / rejection"],
  ["anstrengend", "tiring"],
  ["ärger", "trouble / annoyance"],
  ["salz", "salt"],
  ["schnee", "snow"],
  ["dahin", "until then / there"],
  ["jederzeit", "at any time"],
  ["kaution", "deposit"],
  ["längst", "long since"],
  ["locker", "loose / relaxed"],
  ["pflaster", "plaster / paving"],
  ["vertretung", "stand-in / cover"],
  ["abo", "subscription"],
  ["abschlag", "payment on account"],
  ["ausgang", "exit / outcome"],
  ["balkon", "balcony"],
  ["brei", "purée / porridge"],
  ["dagegen", "against it"],
  ["date", "date (romantic)"],
  ["deal", "deal"],
  ["e-mail", "email"],
  ["sperrmüll", "bulky waste"],
  ["stets", "always"],
  ["verboten", "forbidden"],
  ["erkältung", "cold (illness)"],
  ["erwischt", "caught"],
  ["kündigungsfrist", "notice period"],
  ["lüften", "to air (a room)"],
  ["schild", "sign"],
  ["schrank", "wardrobe / cupboard"],
  ["übergabe", "handover"],
  ["wenigstens", "at least"],
  ["brutto", "gross (before tax)"],
  ["eingefroren", "frozen"],
  ["einschlafen", "to fall asleep"],
  ["einschreiben", "registered letter"],
  ["entschuldigen", "to apologise / excuse"],
  ["erdbeeren", "strawberries"],
  ["erstattung", "refund"],
  // The words the lesson catalogue uses most that had no gloss — surfaced
  // by check-learning-mode's coverage floor when the capstone dialogues
  // grew the catalogue, and worth having for every sentence that was
  // already using them.
  ["schuld", "to blame / at fault"],
  ["leise", "quiet / quietly"],
  ["vorhin", "just now / earlier"],
  ["solange", "as long as / for the time being"],
  ["gewitter", "thunderstorm"],
  ["sowieso", "anyway / in any case"],
  ["freue freu freust", "glad (sich freuen = to be glad / look forward)"],
  ["gewonnen", "won (gewinnen)"],
  ["waschmaschine", "washing machine"],
  ["schraube", "screw"],
  ["zelt", "tent"],
  ["stock", "floor / storey; stick"],
  ["pünktlich", "on time / punctual"],
  ["daraus", "out of it / from it"],
  ["nervt", "annoys / gets on the nerves (nerven)"],
  ["peinlich", "embarrassing"],
  ["nämlich", "namely / you see"],
  ["knie", "knee"],
  ["worum", "about what"],
  ["sauer", "cross / annoyed; sour"],
  ["wahrheit", "truth"],
  ["reparieren", "to repair"],
  ["spazieren", "to stroll / go for a walk"],
  ["protokoll", "minutes / record"],
  ["hütte", "hut / mountain lodge"],
  ["köln", "Cologne"],
  ["mama", "mum"],
  ["laune", "mood"],
  ["liebsten", "am liebsten = best of all / ideally"],
  ["stau", "traffic jam"],
  ["karton", "cardboard box"],
  ["gießen", "to water / to pour"],
  ["winterreifen", "winter tyres"],
  ["grillen", "to barbecue / grill"],
  ["höchstens", "at most"],
  ["stoßlüften", "to air a room briefly with windows wide open"],
  ["uhrzeit", "time (of day)"],
  ["pizza", "pizza"],
  ["abgesagt", "cancelled (absagen)"],
  ["berlin", "Berlin"],
  ["packe packst", "pack (packen)"],
  ["korb", "basket"],
  ["meeting", "meeting"],
  ["wirf", "throw! (werfen)"],
  ["moin", "hello (northern Germany, any time of day)"],
  ["schlapp", "worn out / limp"],
  ["schwein", "pig; Schwein haben = to be lucky"],
  ["schwindelig", "dizzy"],
  ["nervös", "nervous"],
  ["klausur", "written exam"],
  ["absicht", "intention (mit Absicht = on purpose)"],
  ["sowas", "something like that"],
  ["witz", "joke"],
  ["streiten", "to argue / quarrel"],
  ["fressen", "to eat (of animals; rude of people)"],
  ["überfordert", "overwhelmed / out of one's depth"],
  // The lesson catalogue's most frequent words the glossary could not
  // answer, found by measuring rather than guessing: every gap that
  // appears four or more times across the taught sentences.
  ["daten", "data; also: to date someone"],
  ["voraus", "ahead / in advance (im Voraus)"],
  ["beleidigt", "offended (beleidigen)"],
  ["durchs", "durch das = through the"],
  ["höher", "higher (hoch)"],
  ["kalender", "calendar / diary"],
  ["manchen", "some (manche)"],
  ["nen", "einen = a (spoken short form)"],
  ["rechnet", "calculates / reckons (rechnen)"],
  ["regnen regnet", "to rain / it rains"],
  ["schirm", "umbrella (der Regenschirm)"],
  ["übernommen", "taken over / covered (übernehmen)"],
  ["war's", "war es = it was / that was"],
  ["wird's", "wird es = it will / it gets"],
  ["abteil", "compartment (on a train)"],
  ["ausgegangen", "gone out; run out (ausgehen)"],
  ["außen", "outside / on the outside"],
  ["bescheinigung", "certificate / written confirmation"],
  ["bestanden", "passed (an exam); existed (bestehen)"],
  ["brennt", "burns / is on fire (brennen)"],
  ["desto", "je ... desto = the ... the"],
  ["dieselbe derselben selben", "the same"],
  ["duschen", "to shower"],
  ["einiges", "quite a bit / a fair amount"],
  ["einpacken", "to pack up / wrap up"],
  ["gewährleistung", "statutory warranty"],
  ["kette", "chain / necklace"],
  ["kopie", "copy"],
  ["kurve", "bend / curve"],
  ["langweilig", "boring"],
  ["lärm", "noise (the disturbing kind)"],
  ["leiser", "quieter (leise)"],
  ["mantel", "coat"],
  ["nachbarin", "neighbour (female)"],
  ["nüsse", "nuts (die Nuss)"],
  ["pack packen", "pack! / to pack; grab"],
  ["quatsch", "nonsense / rubbish"],
  ["rauchen rauche", "to smoke / I smoke"],
  ["schimmel", "mould; also: white horse"],
  ["schönste", "most beautiful (schön)"],
  ["sprich", "speak! (sprechen); i.e. / that is"],
  ["steckdose", "power socket"],
  ["streichen gestrichen", "to paint (a wall); to cancel / cross out"],
  ["tasse", "cup"],
  ["tierarzt", "vet"],
  ["überstunden", "overtime (die Überstunde)"],
  ["unterschrift", "signature"],
  ["warteschleife", "hold loop (on the phone)"],
  ["wir's", "wir es = we ... it"],
  ["wohnzimmer", "living room"],
  ["zusage", "acceptance / firm yes"],
  ["zweit", "zu zweit = the two of us / as a pair"],
  ["abgeschleppt", "towed away (abschleppen)"],
  ["absender", "sender (on an envelope)"],
  ["allergisch", "allergic"],
  ["ansteckend", "contagious"],
  ["ausgebucht", "fully booked"],
  ["außer", "except for / besides"],
  ["aussieht", "looks / appears (aussehen)"],
  ["bargeld", "cash"],
  ["bestätigung", "confirmation"],
  ["beträgt", "amounts to (betragen)"],
  ["bisher", "so far / up to now"],
  ["block", "notepad; block"],
  ["blöd", "stupid / annoying"],
  ["bohren gebohrt", "to drill / drilled"],
  ["bon", "receipt (der Kassenbon)"],
  ["böse", "angry / mean; evil"],
  ["budget", "budget"],
  ["bußgeld", "fine (for an offence)"],
  ["café", "café"],
  ["eier", "eggs (das Ei)"],
  ["elfmeter", "penalty kick"],
  ["entschädigung", "compensation"],
  ["ergibt", "results in / yields (ergeben)"],
  ["eu", "the EU (Europäische Union)"],
  ["fahrkarte", "ticket (train or bus)"],
  ["flasche", "bottle"],
  ["gassi", "Gassi gehen = to walk the dog"],
  ["gestiegen", "risen / climbed (steigen)"],
  ["gewissen", "conscience (das Gewissen); certain (gewisse)"],
  ["gleichfalls", "likewise / you too"],
  ["hammer", "hammer; colloquially: amazing"],
  ["harmlos", "harmless"],
  ["hat's", "hat es = it has / there is"],
  ["hauptbahnhof", "main station"],
  ["hausmeister", "caretaker / building manager"],
  ["höhle", "cave / den"],
  ["ice", "ICE = German high-speed train"],
  ["impfung impfungen", "vaccination(s)"],
  ["innen", "inside / on the inside"],
  ["kartons", "cardboard boxes (der Karton)"],
  ["kater", "tomcat; hangover"],
  ["klatschnass", "soaking wet"],
  ["kleingeld", "small change"],
  ["klemmt", "is stuck / jams (klemmen)"],
  ["klopf", "knock! (klopfen)"],
  ["knöchel", "ankle; knuckle"],
  ["kompromiss", "compromise"],
  ["kratzer kratzt", "scratch / scratches (kratzen)"],
  ["kurier", "courier"],
  ["leuchtet", "glows / is lit (leuchten)"],
  ["live", "live (broadcast)"],
  ["lustig", "funny"],
  ["meins", "mine"],
  ["miss", "measure! (messen)"],
  ["missverständnis", "misunderstanding"],
  ["mitgenommen", "taken along; worn down (mitnehmen)"],
  ["mitten", "in the middle (mitten in)"],
  ["müll", "rubbish / waste"],
  ["n", "ein = a (spoken short form)"],
  ["nebenbei", "on the side / in passing"],
  ["packstation", "parcel locker (Packstation)"],
  ["portemonnaie", "wallet / purse"],
  ["probezeit", "probation period"],
  ["pulli", "jumper / sweater"],
  ["putzen putze", "to clean / I clean"],
  ["ran", "heran = up to it (komm ran = come closer)"],
  ["rasen", "lawn; to speed"],
  ["räume räumt", "rooms; clears (räumen)"],
  ["reg", "reg dich nicht auf = don't get worked up (aufregen)"],
  ["reparatur", "repair"],
  ["rollläden", "roller shutters (der Rollladen)"],
  ["rum", "herum = around (spoken short form)"],
  ["sammle", "collect (sammeln)"],
  ["scharf", "spicy / sharp"],
  ["schieben", "to push"],
  ["schwäche", "weakness"],
  ["sonnencreme", "sunscreen"],
  ["spinnt", "is acting up / is crazy (spinnen)"],
  ["stundenlang", "for hours"],
  ["sturm", "storm"],
  ["süchtig", "addicted"],
  ["supermarkt", "supermarket"],
  ["torte", "gateau / layered cake"],
  ["toxisch", "toxic"],
  ["ü", "über = over (as in Ü30); the letter ü"],
  ["ums", "um das = around the / about the"],
  ["verschenken", "to give away"],
  ["vertan", "sich vertan = made a slip (sich vertun)"],
  ["voran", "forward / ahead (voran|kommen)"],
  ["waage", "scales (for weighing); Libra"],
  ["wärmer", "warmer (warm)"],
  ["wartezimmer", "waiting room"],
  ["wecker", "alarm clock"],
  ["weichen", "to give way / yield; soft (weiche)"],
  ["wertstoffhof", "recycling centre"],
  ["whatsapp", "WhatsApp"],
  ["wie's", "wie es = how it"],
  ["wörtlich", "literal / word for word"],
  ["zurückgeben", "to give back / return"],
  ["zwar", "admittedly / und zwar = namely"],
  ["abgebrochen", "broken off / cancelled (abbrechen)"],
  ["abgelaufen", "expired (ablaufen)"],
  ["abgezogen", "deducted / pulled off (abziehen)"],
  ["abholung", "collection / pickup"],
  ["abkürzung", "shortcut; abbreviation"],
  ["abmahnung", "formal warning (from an employer or lawyer)"],
  ["absetzen", "to drop someone off; to deduct (tax)"],
  ["abwechselnd", "taking turns / alternately"],
  ["algorithmus", "algorithm"],
  ["ampel", "traffic lights"],
  ["aneinander", "against / to one another"],
  ["angezogen", "dressed (anziehen)"],
  ["anhang", "attachment (email); appendix"],
  ["arbeitszeugnis", "employer's reference"],
  ["aufgewachsen", "grew up (aufwachsen)"],
  ["aufhebungsvertrag", "mutual termination agreement"],
  ["aufräumen", "to tidy up"],
  ["aufstehen", "to get up"],
  ["ausleihen", "to borrow / lend out"],
  ["außerhalb", "outside of"],
  ["auswendig", "by heart"],
  ["bäcker", "baker / bakery"],
  ["bart", "beard"],
  ["batterie batterien", "battery / batteries"],
  ["baumarkt", "DIY store"],
  ["becken", "pool basin; pelvis; sink"],
  ["beruht", "rests on / is based on (beruhen)"],
  ["beschwert", "complained (sich beschweren)"],
  ["besserung", "gute Besserung = get well soon"],
  ["betriebsrat", "works council"],
  ["beworben", "applied (sich bewerben)"],
  ["bildschirmzeit", "screen time"],
  ["blackout", "blackout / mind going blank"],
  ["bock", "Bock haben = to feel like it"],
  ["bonus", "bonus"],
  ["boss", "boss"],
  ["braten", "to fry / roast; the roast"],
  ["bremst", "brakes (bremsen)"],
  ["datenvolumen", "mobile data allowance"],
  ["dazwischengekommen", "something came up (dazwischenkommen)"],
  ["deutschlandticket", "Deutschlandticket (flat-rate transit pass)"],
  ["dritt", "zu dritt = the three of us"],
  ["dübel", "wall plug / dowel"],
  ["ehe", "marriage; ehe = before (formal)"],
  ["eingeladen", "invited (einladen)"],
  ["einlegen", "to insert; to lodge (an appeal); to pickle"],
  ["einsteigen", "to get in / board"],
  ["elternzeit", "parental leave"],
  ["empfindliche", "sensitive (empfindlich)"],
  ["entschuldige", "sorry / excuse me (entschuldigen)"],
  ["erholt", "recovered / rested (sich erholen)"],
  ["faden", "thread"],
  ["färben", "to dye / colour"],
  ["fernbedienung", "remote control"],
  ["fett", "fat; greasy; bold (type)"],
  ["fleck", "stain / spot"],
  ["flohmarkt", "flea market"],
  ["friseur", "hairdresser"],
  ["frühling", "spring (the season)"],
  ["führerschein", "driving licence"],
  ["füttern", "to feed (an animal or baby)"],
  ["garderobe", "cloakroom; coat rack"],
  ["gas", "gas; Gas geben = to speed up"],
  ["gebügelt", "ironed (bügeln)"],
  ["geil", "awesome (very casual); horny"],
  ["gepäck", "luggage"],
  ["gespannt", "curious / eager to see"],
  ["gitarre", "guitar"],
  ["gramm", "gram"],
  ["grammatik", "grammar"],
  ["großeltern", "grandparents"],
  ["grüßen", "to greet / say hello to"],
  ["haftpflichtversicherung", "personal liability insurance"],
  ["hals", "neck / throat"],
  ["handtücher", "towels (das Handtuch)"],
  ["hausaufgaben", "homework"],
  ["heizen", "to heat"],
  ["herd", "cooker / stove"],
  ["heuschnupfen", "hay fever"],
  ["hingelegt", "lay down; put down (hinlegen)"],
  ["hinterfragen", "to question / scrutinise"],
  ["hitze", "heat"],
  ["horoskop", "horoscope"],
  ["hungrig", "hungry"],
  ["impfpass", "vaccination record"],
  ["inflation", "inflation"],
  ["irgendetwas", "something / anything"],
  ["irre", "crazy / mad; ich irre mich = I am wrong"],
  ["jucken", "to itch"],
  ["kassenbon", "till receipt"],
  ["kellner", "waiter"],
  ["kerzen", "candles (die Kerze)"],
  ["kinderwagen", "pram / stroller"],
  ["kirmes", "funfair"],
  ["klavier", "piano"],
  ["klingeln", "to ring (bell or phone)"],
  ["kofferraum", "car boot / trunk"],
  ["kompliment", "compliment"],
  ["kostenvoranschlag", "cost estimate / quote"],
  ["krankmeldung", "sick note"],
  ["krise", "crisis"],
  ["kürzen", "to shorten / cut (a budget)"],
  ["längsten", "longest (lang); am längsten"],
  ["läuft's", "läuft es = how's it going"],
  ["lebenslauf", "CV / résumé"],
  ["letztlich", "ultimately / in the end"],
  ["loadout", "loadout (gaming)"],
  ["lobby", "hotel lobby; political lobby"],
  ["losgehen", "to set off; to start"],
  ["mikrowelle", "microwave"],
  ["mindern", "to reduce / diminish"],
  ["mitgebracht", "brought along (mitbringen)"],
  ["monatsende", "end of the month"],
  ["münchen", "Munich"],
  ["mund", "mouth"],
  ["muskeln", "muscles (der Muskel)"],
  ["nachtruhe", "night-time quiet (quiet hours)"],
  ["nacken", "nape / back of the neck"],
  ["nah", "near / close"],
  ["narkose", "anaesthetic"],
  ["nebenkosten", "utility / service charges"],
  ["nebenwirkungen", "side effects (die Nebenwirkung)"],
  ["netto", "net (after deductions)"],
  ["neuanfang", "fresh start"],
  ["normalerweise", "normally / usually"],
  ["ofen", "oven"],
  ["ostern", "Easter"],
  ["parkschein", "parking ticket (the one you buy)"],
  ["party", "party"],
  ["pfand", "deposit (on bottles)"],
  ["pfeift", "whistles (pfeifen)"],
  ["plastik", "plastic"],
  ["platt", "flat (tyre); exhausted"],
  ["platten", "flat tyre (der Platten); records"],
  ["platzt", "bursts (platzen)"],
  ["pony", "fringe / bangs; pony"],
  ["porto", "postage"],
  ["prognose", "forecast / prognosis"],
  ["puste", "aus der Puste = out of breath"],
  ["quietscht", "squeaks (quietschen)"],
  ["rappelvoll", "packed / crammed full"],
  ["rausgehen", "to go outside"],
  ["reisepass", "passport"],
  ["reißverschluss", "zip / zipper"],
  ["restmüll", "residual waste (grey bin)"],
  ["risiken", "risks (das Risiko)"],
  ["ruhestand", "retirement"],
  ["rutsch", "guten Rutsch = happy New Year (slide over well)"],
  ["satt", "full (after eating)"],
  ["säule", "pillar / column; charging post"],
  ["sauna", "sauna"],
  ["schade", "a pity / a shame"],
  ["schatz", "darling; treasure"],
  ["scheitel", "parting (in hair)"],
  ["schief", "crooked / lopsided; schiefgehen = to go wrong"],
  ["schlauch", "hose; inner tube"],
  ["schwör", "ich schwör = I swear (casual)"],
  ["socken", "socks (die Socke)"],
  ["sortieren", "to sort"],
  ["soße", "sauce / gravy"],
  ["soweit", "so far; ready (soweit sein)"],
  ["spiegelglatt", "slippery as glass (icy)"],
  ["spoiler", "spoiler"],
  ["spülmaschine", "dishwasher"],
  ["standesamtlich", "at the registry office (wedding)"],
  ["stecker", "plug"],
  ["strauß", "bouquet; ostrich"],
  ["streik", "strike"],
  ["stumm", "mute / silent"],
  ["tagesmutter", "childminder"],
  ["takt", "beat / bar (music); tact"],
  ["tanken", "to fill up (fuel)"],
  ["tauschen", "to swap"],
  ["tausend", "thousand"],
  ["telefonieren", "to talk on the phone"],
  ["teller", "plate"],
  ["tempo", "speed; tissue (brand)"],
  ["these", "thesis / claim"],
  ["tics", "tics"],
  ["tierheim", "animal shelter"],
  ["top", "great / in top shape; top (garment)"],
  ["tot", "dead"],
  ["trotz", "despite"],
  ["truhe", "chest (furniture)"],
  ["übel", "nauseous; awful (mir ist übel)"],
  ["übermorgen", "the day after tomorrow"],
  ["überweisen", "to transfer (money); to refer (a patient)"],
  ["umgestiegen", "changed (trains); switched (umsteigen)"],
  ["umsteigen", "to change (trains); to switch over"],
  ["umtauschen", "to exchange (a purchase)"],
  ["unsicherheit", "uncertainty / insecurity"],
  ["verlängerung", "extension; extra time"],
  ["vertragen", "to tolerate; sich vertragen = to get along"],
  ["vorbeikommen", "to drop by"],
  ["vorspeise", "starter"],
  ["wahnsinnig", "insane; incredibly (wahnsinnig gut)"],
  ["wäscht", "washes (waschen)"],
  ["wasserkocher", "kettle"],
  ["widerstand", "resistance"],
  ["wiegt", "weighs (wiegen)"],
  ["wirt", "landlord (of a pub)"],
  ["worden", "been (passive perfect: ist ... worden)"],
  ["wunde", "wound"],
  ["zufall", "coincidence"],
  ["zufriedenheit", "satisfaction / contentment"],
  ["zugbindung", "train-specific ticket restriction"],
  ["zugestellt", "delivered (zustellen)"],
  ["zuhören", "to listen"],
  ["zurücksetzen", "to reset; to reverse (a car)"],
  ["zweiundzwanzig", "twenty-two"],
];

for (const [words, gloss] of coreGlossGroups) addGloss(exactGlosses, words, gloss);

const addGeneratedVerbForms = (lemma: string, gloss: string) => {
  if (!lemma || lemma.includes(" ") || lemma.includes("-")) return;
  const stem = lemma.endsWith("en") ? lemma.slice(0, -2) : lemma.endsWith("n") ? lemma.slice(0, -1) : "";
  if (stem.length < 3) return;

  const needsExtraE = /[td]$/u.test(stem);
  const endsInSibilant = /[sßxz]$/u.test(stem);
  const regularParticiple = `${stem}${needsExtraE ? "et" : "t"}`;
  const forms = [
    stem,
    `${stem}e`,
    needsExtraE ? `${stem}est` : endsInSibilant ? `${stem}t` : `${stem}st`,
    needsExtraE ? `${stem}et` : `${stem}t`,
    lemma,
    needsExtraE ? `${stem}et` : `${stem}t`,
    lemma,
  ];
  if (lemma.endsWith("ieren") || /^(be|emp|ent|er|ge|miss|ver|zer)/u.test(lemma)) {
    forms.push(regularParticiple);
  } else {
    forms.push(`ge${regularParticiple}`);
  }
  for (const form of forms) {
    const key = wordKey(form);
    if (key && !verbFormGlosses.has(key)) verbFormGlosses.set(key, gloss);
  }
};

const addGeneratedAdjectiveForms = (lemma: string, gloss: string) => {
  if (!lemma || lemma.includes(" ") || lemma.includes("-")) return;
  const stems = new Set([lemma]);
  if (lemma.endsWith("er") && lemma.length > 4) stems.add(lemma.slice(0, -2) + "r");
  if (lemma.endsWith("el") && lemma.length > 4) stems.add(lemma.slice(0, -2) + "l");
  if (lemma === "hoch") stems.add("hoh");
  for (const stem of stems) {
    for (const ending of ["e", "en", "er", "es", "em"]) {
      const key = wordKey(stem + ending);
      if (key && !adjectiveFormGlosses.has(key)) adjectiveFormGlosses.set(key, gloss);
    }
  }
};

for (const rawEntry of bundledWordBank as WordBankEntry[]) {
  const gloss = conciseGloss(rawEntry.en ?? "");
  if (!gloss) continue;

  const lookup = stripGermanPunctuation(rawEntry.lookup ?? "");
  const bareGerman = stripGermanPunctuation(rawEntry.de ?? "").replace(/^(der|die|das)\s+/iu, "");
  for (const source of [lookup, bareGerman]) {
    const key = wordKey(source);
    if (key && !exactGlosses.has(key)) exactGlosses.set(key, gloss);
  }

  const lemma = wordKey(lookup || bareGerman);
  if (rawEntry.tip === "verb") addGeneratedVerbForms(lemma, gloss);
  if (rawEntry.tip === "adjective") addGeneratedAdjectiveForms(lemma, gloss);
  if (rawEntry.tip === "noun" && lemma && !nounGlosses.has(lemma)) nounGlosses.set(lemma, gloss);
}

const deUmlaut = (value: string) => value
  .replaceAll("ä", "a")
  .replaceAll("ö", "o")
  .replaceAll("ü", "u")
  .replaceAll("äu", "au");

const nounGloss = (word: string, key: string) => {
  if (!/^\p{Lu}/u.test(stripGermanPunctuation(word))) return null;
  const candidates = new Set([key, deUmlaut(key)]);
  let frontier = [key];
  for (let pass = 0; pass < 2; pass += 1) {
    const next: string[] = [];
    for (const candidate of frontier) {
      for (const suffix of ["ern", "en", "er", "es", "e", "n", "s"]) {
        if (!candidate.endsWith(suffix) || candidate.length - suffix.length < 3) continue;
        const stem = candidate.slice(0, -suffix.length);
        for (const variant of [stem, deUmlaut(stem)]) {
          if (!candidates.has(variant)) {
            candidates.add(variant);
            next.push(variant);
          }
        }
      }
    }
    frontier = next;
  }
  for (const candidate of candidates) {
    const gloss = nounGlosses.get(candidate);
    if (gloss) return gloss;
  }
  return null;
};

/**
 * Returns a short English gloss for a visible German word. The lookup is
 * entirely offline: curated high-frequency forms plus the bundled hardcoded
 * word bank. Unknown words stay unlabelled instead of guessing from a server.
 *
 * `midSentenceCapital` says the word was capitalised somewhere other than the
 * start of its sentence, which in German all but names it a noun. Without it
 * the curated particle and verb entries answer first, and "Das letzte Mal"
 * glosses Mal as "just / sometime" — the softener in "sag mal", not the
 * occasion the sentence means. Same trap for Essen (food, not eat), Weiß
 * (white, not knows), Fest (party, not firm) and Laut (sound, not loud).
 *
 * It is a hint, not an override: if nothing in the noun bank matches, the
 * ordinary lookup answers exactly as before. Callers that cannot see where
 * the word sits should leave it off rather than guess.
 */
export function germanWordGloss(
  word: string,
  options?: { midSentenceCapital?: boolean }
): string | null {
  const key = wordKey(word);
  if (!key) return null;
  if (options?.midSentenceCapital) {
    const noun = nounGloss(word, key);
    if (noun) return noun;
  }
  return exactGlosses.get(key)
    ?? verbFormGlosses.get(key)
    ?? adjectiveFormGlosses.get(key)
    ?? nounGloss(word, key)
    ?? null;
}
