/**
 * The forms a German verb takes that no suffix rule can undo.
 *
 * A strong verb changes its stem vowel — gefunden does not contain finden,
 * gibt does not contain geben — and sein, haben and the modals are irregular
 * outright. Anything that counts words in German text has to join these back
 * to their lemma or it undercounts the commonest verbs in the language by
 * orders of magnitude: the course's own conversational corpus uses sein 2,459
 * times, and a suffix-only counter found three of them.
 *
 * Written as principal parts, one line per verb, because that is how the
 * language is organised and how the list stays checkable. The Immersion
 * extension carries the same table for its hovers and cannot import from here
 * — it is a standalone content script — so check-verb-forms asserts the two
 * agree rather than trusting them to.
 */
export const GERMAN_VERB_FORMS: Record<string, string> = {
  "abnehmen": "abgenommen",
  "anbieten": "angeboten",
  "anfangen": "angefangen",
  "angehen": "angegangen",
  "ankommen": "angekommen",
  "annehmen": "angenommen",
  "ansehen": "angesehen",
  "antreiben": "angetrieben",
  "aufnehmen": "aufgenommen",
  "ausgeben": "ausgegeben",
  "ausgehen": "ausgegangen",
  "aussehen": "ausgesehen",
  "befehlen": "befahl befiehlst befiehlt befohlen",
  "beginnen": "begann begannen begonnen begönne",
  "behalten": "behielt behielten behält behältst",
  "beißen": "biss bissen gebissen",
  "bekommen": "bekam bekamen bekäme",
  "bestehen": "bestand bestanden",
  "betrügen": "betrog betrogen",
  "biegen": "bog bogen gebogen",
  "bieten": "bot boten geboten",
  "binden": "band banden gebunden",
  "bitten": "bat baten gebeten",
  "bleiben": "blieb blieben geblieben",
  "brechen": "brach brachen brichst bricht gebrochen",
  "brennen": "brannte brannten gebrannt",
  "bringen": "brachte brachten gebracht",
  "dürfen": "darf darfst durfte durften dürft dürfte dürften gedurft",
  "eingehen": "eingegangen",
  "einladen": "eingeladen",
  "empfehlen": "empfahl empfiehlst empfiehlt empfohlen",
  "enthalten": "enthielt enthielten enthält enthältst",
  "entscheiden": "entschied entschieden",
  "entstehen": "entstand entstanden",
  "erkennen": "erkannt erkannte erkannten",
  "erschaffen": "erschuf erschufen",
  "erscheinen": "erschien erschienen",
  "essen": "aß aßen gegessen isst äße",
  "fahren": "fuhr fuhren fährst fährt gefahren",
  "fallen": "fiel fielen fällst fällt gefallen",
  "fangen": "fing fingen gefangen",
  "fernsehen": "ferngesehen",
  "finden": "fand fanden fandst fände gefunden",
  "fliegen": "flog flogen flöge geflogen",
  "fliehen": "floh flohen geflohen",
  "frieren": "fror froren gefroren",
  "geben": "gab gaben gabst gabt gegeben gibst gibt gäbe gäben",
  "gefallen": "gefiel gefielen gefällst gefällt",
  "gehen": "gegangen ging ginge gingen gingst",
  "gelingen": "gelang gelangen gelungen",
  "gelten": "galt galten gegolten gilt giltst",
  "genießen": "genoss genossen",
  "geschehen": "geschah geschahen geschieht",
  "gewinnen": "gewann gewannen gewonnen gewönne",
  "gießen": "gegossen goss gossen",
  "graben": "gegraben grub gruben gräbst gräbt",
  "greifen": "gegriffen griff griffen",
  "haben": "gehabt habe habt hast hat hatte hatten hattest hätte hätten hättest",
  "halten": "gehalten hielt hielten hält hältst",
  "hängen": "gehangen hing hingen",
  "heben": "gehoben hob hoben",
  "heißen": "geheißen hieß hießen",
  "helfen": "geholfen half halfen hilfst hilft hülfe",
  "herausfinden": "herausgefunden",
  "kennen": "gekannt kannte kannten",
  "klingen": "geklungen klang klangen",
  "kommen": "gekommen kam kamen kamst käme",
  "können": "gekonnt kann kannst konnte konnten könnt könnte könnten",
  "laden": "geladen lud luden lädst lädt",
  "lassen": "gelassen ließ ließe ließen lässt",
  "laufen": "gelaufen lief liefen läufst läuft",
  "leiden": "gelitten litt litten",
  "lesen": "gelesen las lasen liest läse",
  "liegen": "gelegen lag lagen läge",
  "lügen": "gelogen log logen",
  "messen": "gemessen maß maßen misst",
  "mitkommen": "mitgekommen",
  "mitnehmen": "mitgenommen",
  "mögen": "gemocht mag magst mochte mochten mögt",
  "müssen": "gemusst muss musst musste mussten müsst müsste müssten",
  "nehmen": "genommen nahm nahmen nimmst nimmt nähme",
  "nennen": "genannt nannte nannten",
  "raten": "geraten riet rieten rät rätst",
  "reißen": "gerissen riss rissen",
  "reiten": "geritten ritt ritten",
  "rennen": "gerannt rannte rannten",
  "riechen": "gerochen roch rochen",
  "rufen": "gerufen rief riefen",
  "schaffen": "geschaffen schuf schufen",
  "scheinen": "geschienen schien schienen",
  "schieben": "geschoben schob schoben",
  "schießen": "geschossen schoss schossen",
  "schlafen": "geschlafen schlief schliefen schläfst schläft",
  "schlagen": "geschlagen schlug schlugen schlägst schlägt",
  "schließen": "geschlossen schließt schloss schlossen",
  "schneiden": "geschnitten schnitt schnitten",
  "schreiben": "geschrieben schrieb schrieben",
  "schwimmen": "geschwommen schwamm schwammen",
  "sehen": "gesehen sah sahen siehst sieht sähe",
  "sein": "bin bist gewesen ist sei seid seien sind war waren warst wart wäre wären",
  "senden": "gesandt sandte sandten",
  "singen": "gesungen sang sangen",
  "sinken": "gesunken sank sanken",
  "sitzen": "gesessen saß saßen säße",
  "sollen": "gesollt soll sollst sollt sollte sollten",
  "sprechen": "gesprochen sprach sprachen sprachst spracht sprichst spricht spräche",
  "springen": "gesprungen sprang sprangen",
  "stattfinden": "stattgefunden",
  "stechen": "gestochen stach stachen stichst sticht",
  "stehen": "gestanden stand standen stände stünde",
  "stehlen": "gestohlen stahl stiehlst stiehlt",
  "steigen": "gestiegen stieg stiegen",
  "sterben": "gestorben starb starben stirbst stirbt",
  "streiten": "gestritten stritt stritten",
  "teilnehmen": "teilgenommen",
  "tragen": "getragen trug trugen trägst trägt trüge",
  "treffen": "getroffen traf trafen triffst trifft träfe",
  "treiben": "getrieben trieb trieben",
  "treten": "getreten trat traten tritt trittst",
  "trinken": "getrunken trank tranken tränke",
  "tun": "getan tat taten tust tut",
  "übereinstimmen": "übereingestimmt",
  "umgehen": "umgegangen",
  "verbieten": "verbot verboten",
  "verbringen": "verbracht verbrachte",
  "vergehen": "vergangen",
  "vergessen": "vergaß vergaßen vergessen vergisst",
  "verlassen": "verließ verließen verlässt",
  "verlieren": "verlor verloren verlöre",
  "verschwinden": "verschwand verschwanden verschwunden",
  "versprechen": "versprach versprichst verspricht",
  "verstehen": "verstand verstanden verstünde",
  "vorgehen": "vorgegangen",
  "wachsen": "gewachsen wuchs wuchsen wächst",
  "waschen": "gewaschen wusch wuschen wäschst wäscht",
  "wenden": "gewandt wandte wandten",
  "werben": "geworben warb warben wirbst wirbt",
  "werden": "geworden ward werde werdet wird wirst worden wurde wurden wurdest würde würden",
  "werfen": "geworfen warf warfen wirfst wirft würfe",
  "wissen": "gewusst weiß weißt wisst wusste wussten wüsste",
  "wollen": "gewollt will willst wollt wollte wollten",
  "ziehen": "gezogen zog zogen zöge",
  "zunehmen": "zugenommen",
  "zurückkommen": "zurückgekommen",
  "zwingen": "gezwungen zwang zwangen",
};

const FORM_TO_LEMMA = new Map<string, string>();
for (const [lemma, forms] of Object.entries(GERMAN_VERB_FORMS)) {
  for (const form of forms.split(" ")) FORM_TO_LEMMA.set(form, lemma);
}

/**
 * The dictionary form of an inflected verb, or null when this table does not
 * know it. Never guesses: a wrong lemma silently moves one word's count onto
 * another word, which is worse than the undercount it was meant to fix.
 */
export function germanVerbLemma(form: string | undefined): string | null {
  const key = String(form ?? "").toLocaleLowerCase("de-DE").trim();
  return key ? FORM_TO_LEMMA.get(key) ?? null : null;
}

export const GERMAN_VERB_FORM_COUNT = FORM_TO_LEMMA.size;
