import type { Blueprint } from "./types";

/**
 * Words surfaced by the Micheon Immersion browser extension from the
 * learner's REAL browsing, curated by hand: names, brands and English
 * filler removed, inflections resolved to their lemmas, every entry
 * checked against the existing catalogue and article-verified. The
 * collection file recorded how often each word was actually seen, and
 * the packs keep that frequency order -- what the learner meets most
 * often comes first.
 *
 * Append-only after release, like every word pack: progress is global
 * by lemma and pack order is curriculum order.
 */
const focus = "Vocabulary the learner demonstrably meets in real browsing, from interface German to everyday conversational glue.";

export const immersionWordPartBlueprints: Record<string, Blueprint> = {
  part440: {
    label: "Part 440",
    level: "A2-B2",
    theme: "Interface German",
    description: "The German every app, site and menu speaks: displaying, clicking, following, settings and the words around them.",
    focus,
    seeds: [
      { de: "das Englisch", lookup: "Englisch", fallbackEn: "English (language)", tip: "noun", article: "das", use: "usually article-less: Ich spreche Englisch; the adjective englisch is lowercase" },
      { de: "die Originalsprache", lookup: "Originalsprache", fallbackEn: "original language", tip: "noun", article: "die", use: "of a film or text: im Original / in der Originalsprache" },
      { de: "der Trend", lookup: "Trend", fallbackEn: "trend, tendency", tip: "noun", article: "der", use: "established loanword; 'Trends' is the social-media trending list" },
      { de: "das Königreich", lookup: "Königreich", fallbackEn: "kingdom", tip: "noun", article: "das", use: "das Vereinigte Königreich = the United Kingdom" },
      { de: "vereinigen", lookup: "vereinigen", fallbackEn: "to unite, to unify", tip: "verb", use: "participle as name: das Vereinigte Königreich = the United Kingdom" },
      { de: "anzeigen", lookup: "anzeigen", fallbackEn: "to display, to show", tip: "verb", use: "UI German; also jemanden anzeigen = to report someone to the police" },
      { de: "der Bot", lookup: "Bot", fallbackEn: "bot (software)", tip: "noun", article: "der", use: "established IT loanword: chat bot, software agent" },
      { de: "das Tool", lookup: "Tool", fallbackEn: "tool (software)", tip: "noun", article: "das", use: "IT loanword; a physical tool is das Werkzeug" },
      { de: "klicken", lookup: "klicken", fallbackEn: "to click", tip: "verb", use: "auf einen Link klicken = to click on a link" },
      { de: "die Vorstellung", lookup: "Vorstellung", fallbackEn: "idea, introduction, performance", tip: "noun", article: "die", use: "also cinema showing; sich vorstellen = to introduce oneself / to imagine" },
      { de: "zurück", lookup: "zurück", fallbackEn: "back", tip: "adverb", use: "hin und zurück = there and back, return (ticket)" },
      { de: "genau", lookup: "genau", fallbackEn: "exact, exactly", tip: "adjective", use: "common as agreement: Genau! = exactly!" },
      { de: "kommen", lookup: "kommen", fallbackEn: "to come", tip: "verb" },
      { de: "verwenden", lookup: "verwenden", fallbackEn: "to use, to utilise", tip: "verb", use: "near-synonym of benutzen; slightly more formal" },
      { de: "live", lookup: "live", fallbackEn: "live (broadcast)", tip: "adverb", use: "pronounced like English 'life'; live übertragen = to broadcast live" },
      { de: "fragen", lookup: "fragen", fallbackEn: "to ask", tip: "verb", use: "gefragt sein = to be in demand (as in the collected 'Deine Hilfe ist gefragt')" },
      { de: "der Kurzbefehl", lookup: "Kurzbefehl", fallbackEn: "keyboard shortcut", tip: "noun", article: "der", use: "UI German (Tastaturkurzbefehl); der Befehl = command" },
      { de: "die Tastatur", lookup: "Tastatur", fallbackEn: "keyboard", tip: "noun", article: "die", use: "computer keyboard; a piano keyboard is die Klaviatur" },
      { de: "boosten", lookup: "boosten", fallbackEn: "to boost", tip: "verb", use: "colloquial anglicism (Duden-listed); marketing and social media register" },
      { de: "frei", lookup: "frei", fallbackEn: "free", tip: "adjective", use: "free as in available or unrestricted; free of charge is kostenlos" },
      { de: "die Funktion", lookup: "Funktion", fallbackEn: "function, feature", tip: "noun", article: "die", use: "in apps usually 'feature'" },
      { de: "die Statistik", lookup: "Statistik", fallbackEn: "statistics, statistic", tip: "noun", article: "die" },
      { de: "die Timeline", lookup: "Timeline", fallbackEn: "timeline (social media feed)", tip: "noun", article: "die", use: "social-media loanword; a historical timeline is der Zeitstrahl" },
      { de: "die Aufmerksamkeit", lookup: "Aufmerksamkeit", fallbackEn: "attention", tip: "noun", article: "die", use: "Aufmerksamkeit auf sich ziehen = to attract attention" },
      { de: "automatisch", lookup: "automatisch", fallbackEn: "automatic, automatically", tip: "adjective" },
      { de: "das Problem", lookup: "Problem", fallbackEn: "problem, issue", tip: "noun", article: "das", use: "Kein Problem! = no problem" },
      { de: "der Agent", lookup: "Agent", fallbackEn: "agent, operative", tip: "noun", article: "der", use: "secret agent; now also AI agent (der KI-Agent)" },
      { de: "bereits", lookup: "bereits", fallbackEn: "already", tip: "adverb", use: "more formal synonym of schon" },
      { de: "der Desktop", lookup: "Desktop", fallbackEn: "desktop (computer)", tip: "noun", article: "der", use: "IT loanword: desktop computer or screen desktop" },
      { de: "warum", lookup: "warum", fallbackEn: "why", tip: "adverb", use: "synonyms: wieso, weshalb" },
      { de: "grundlegend", lookup: "grundlegend", fallbackEn: "fundamental, basic", tip: "adjective" },
      { de: "hilfreich", lookup: "hilfreich", fallbackEn: "helpful, useful", tip: "adjective", use: "a thing is hilfreich (useful); a person who likes helping is hilfsbereit" },
      { de: "also", lookup: "also", fallbackEn: "so, therefore, well", tip: "adverb", use: "false friend: never means English 'also' (that is auch)" },
      { de: "bald", lookup: "bald", fallbackEn: "soon", tip: "adverb", use: "Bis bald! = see you soon" },
      { de: "drücken", lookup: "drücken", fallbackEn: "to press, to push", tip: "verb", use: "eine Taste drücken = to press a key; die Daumen drücken = to keep one's fingers crossed" },
      { de: "das Fragezeichen", lookup: "Fragezeichen", fallbackEn: "question mark", tip: "noun", article: "das" },
      { de: "wirklich", lookup: "wirklich", fallbackEn: "really, truly", tip: "adverb", use: "as adjective: real, actual" },
      { de: "daran", lookup: "daran", fallbackEn: "on it, of it", tip: "adverb", use: "da(r)- + an: daran denken = to think of it; daran arbeiten = to work on it" },
      { de: "super", lookup: "super", fallbackEn: "great, super", tip: "adjective", use: "colloquial; invariable: ein super Film" },
      { de: "aktiv", lookup: "aktiv", fallbackEn: "active", tip: "adjective" },
    ],
    dialogues: [],
    phrases: [],
  },
  part441: {
    label: "Part 441",
    level: "A2-B2",
    theme: "Everyday glue words",
    description: "High-frequency everyday words -- the connectors, intensifiers and core verbs real posts and comments are made of.",
    focus,
    seeds: [
      { de: "einfach", lookup: "einfach", fallbackEn: "simple, easy", tip: "adjective", use: "as adverb often 'just': einfach fragen = just ask" },
      { de: "entfolgen", lookup: "entfolgen", fallbackEn: "to unfollow", tip: "verb", use: "social media; takes dative: jemandem entfolgen" },
      { de: "die Person", lookup: "Person", fallbackEn: "person, individual", tip: "noun", article: "die", use: "always feminine, even for men" },
      { de: "das Projekt", lookup: "Projekt", fallbackEn: "project", tip: "noun", article: "das" },
      { de: "benötigen", lookup: "benötigen", fallbackEn: "to require, to need", tip: "verb", use: "more formal than brauchen; common in instructions" },
      { de: "der Spaß", lookup: "Spaß", fallbackEn: "fun", tip: "noun", article: "der", use: "Viel Spaß! = have fun; Spaß machen = to be fun" },
      { de: "absolut", lookup: "absolut", fallbackEn: "absolute, absolutely", tip: "adjective" },
      { de: "großartig", lookup: "großartig", fallbackEn: "great, magnificent", tip: "adjective" },
      { de: "immer", lookup: "immer", fallbackEn: "always", tip: "adverb", use: "immer noch = still; immer mehr = more and more" },
      { de: "die Pracht", lookup: "Pracht", fallbackEn: "splendour, magnificence", tip: "noun", article: "die", use: "elevated register; adjective prächtig = splendid" },
      { de: "sagen", lookup: "sagen", fallbackEn: "to say, to tell", tip: "verb" },
      { de: "sogar", lookup: "sogar", fallbackEn: "even (intensifier)", tip: "adverb", use: "sogar noch besser = even better" },
      { de: "unglaublich", lookup: "unglaublich", fallbackEn: "unbelievable, incredible", tip: "adjective" },
      { de: "verbessern", lookup: "verbessern", fallbackEn: "to improve", tip: "verb", use: "sich verbessern – to get better / improve oneself" },
      { de: "atemberaubend", lookup: "atemberaubend", fallbackEn: "breathtaking", tip: "adjective" },
      { de: "benutzen", lookup: "benutzen", fallbackEn: "to use", tip: "verb", use: "synonym: verwenden" },
      { de: "dabei", lookup: "dabei", fallbackEn: "in the process, at the same time; with it", tip: "adverb", use: "dabei sein – to be there / take part" },
      { de: "dazu", lookup: "dazu", fallbackEn: "in addition, with it; for that purpose", tip: "adverb", use: "noch dazu – on top of that" },
      { de: "drei", lookup: "drei", fallbackEn: "three", tip: "numeral" },
      { de: "sehen", lookup: "sehen", fallbackEn: "to see", tip: "verb", use: "irregular: sieht, sah, hat gesehen" },
      { de: "der Gott", lookup: "Gott", fallbackEn: "god", tip: "noun", article: "der", use: "Oh mein Gott! – Oh my God!" },
      { de: "groß", lookup: "groß", fallbackEn: "big, large; tall", tip: "adjective", use: "comparative: größer, superlative: am größten" },
      { de: "können", lookup: "können", fallbackEn: "can, to be able to", tip: "verb", use: "modal verb; könnte – could" },
      { de: "nun", lookup: "nun", fallbackEn: "now", tip: "adverb", use: "slightly more formal than jetzt; also a filler: 'well…'" },
      { de: "okay", lookup: "okay", fallbackEn: "okay, fine", tip: "adjective", use: "informal loan from English; das Okay – the go-ahead" },
      { de: "wobei", lookup: "wobei", fallbackEn: "whereby; though, that said", tip: "conjunction", use: "often introduces a qualifying afterthought: 'wobei …' – 'that said …'" },
      { de: "analysieren", lookup: "analysieren", fallbackEn: "to analyse", tip: "verb" },
      { de: "animieren", lookup: "animieren", fallbackEn: "to animate; to encourage (someone to do something)", tip: "verb" },
      { de: "bedeuten", lookup: "bedeuten", fallbackEn: "to mean, to signify", tip: "verb", use: "Was bedeutet das? – What does that mean?" },
      { de: "beisammen", lookup: "beisammen", fallbackEn: "together (in one place)", tip: "adverb", use: "alles beisammen haben – to have everything together" },
      { de: "bekommen", lookup: "bekommen", fallbackEn: "to get, to receive", tip: "verb", use: "false friend: not 'to become' (that is werden)" },
      { de: "besonders", lookup: "besonders", fallbackEn: "especially, particularly", tip: "adverb" },
      { de: "bieten", lookup: "bieten", fallbackEn: "to offer, to provide", tip: "verb", use: "anbieten is the more concrete 'to offer sb sth'" },
      { de: "die Community", lookup: "Community", fallbackEn: "community (online)", tip: "noun", article: "die", use: "English loan, mainly online communities; a local community is die Gemeinde" },
      { de: "eigen", lookup: "eigen", fallbackEn: "own", tip: "adjective", use: "der eigene Computer – one's own computer; also: peculiar" },
      { de: "entwickeln", lookup: "entwickeln", fallbackEn: "to develop", tip: "verb", use: "sich entwickeln – to evolve, to develop" },
      { de: "erhöhen", lookup: "erhöhen", fallbackEn: "to increase, to raise", tip: "verb" },
      { de: "erstellen", lookup: "erstellen", fallbackEn: "to create, to draw up", tip: "verb", use: "common for files and accounts: ein Konto erstellen – to create an account" },
      { de: "extrem", lookup: "extrem", fallbackEn: "extreme; extremely", tip: "adjective" },
      { de: "ganz", lookup: "ganz", fallbackEn: "whole, entire; quite", tip: "adjective", use: "as adverb: ganz gut – quite good" },
    ],
    dialogues: [],
    phrases: [],
  },
  part442: {
    label: "Part 442",
    level: "A2-B2",
    theme: "Digital life",
    description: "Social media, accounts and online life: the naturalised loanwords and German coinages people actually write with.",
    focus,
    seeds: [
      { de: "bitten", lookup: "bitten", fallbackEn: "to ask (for), to request", tip: "verb", use: "bitten um + accusative; irregular: bat, hat gebeten" },
      { de: "komplett", lookup: "komplett", fallbackEn: "complete, completely", tip: "adjective" },
      { de: "die Kompression", lookup: "Kompression", fallbackEn: "compression", tip: "noun", article: "die", use: "technical register: audio, medicine, engineering" },
      { de: "die Kontrolle", lookup: "Kontrolle", fallbackEn: "control; check, inspection", tip: "noun", article: "die", use: "unter Kontrolle – under control; also a ticket or passport check" },
      { de: "kürzlich", lookup: "kürzlich", fallbackEn: "recently", tip: "adverb", use: "normally an adverb; synonym: vor Kurzem" },
      { de: "lange", lookup: "lange", fallbackEn: "for a long time", tip: "adverb", use: "schon lange – for a long time now; adjective: lang – long" },
      { de: "die Lautstärke", lookup: "Lautstärke", fallbackEn: "volume (loudness)", tip: "noun", article: "die" },
      { de: "leben", lookup: "leben", fallbackEn: "to live", tip: "verb", use: "das Leben – life" },
      { de: "natürlich", lookup: "natürlich", fallbackEn: "of course, naturally", tip: "adverb", use: "as adjective: natural (natürliche Zutaten – natural ingredients)" },
      { de: "neugierig", lookup: "neugierig", fallbackEn: "curious, nosy", tip: "adjective", use: "neugierig auf + accusative" },
      { de: "niedrig", lookup: "niedrig", fallbackEn: "low", tip: "adjective", use: "opposite: hoch" },
      { de: "das Produkt", lookup: "Produkt", fallbackEn: "product", tip: "noun", article: "das" },
      { de: "sanft", lookup: "sanft", fallbackEn: "gentle, soft", tip: "adjective" },
      { de: "sodass", lookup: "sodass", fallbackEn: "so that, with the result that", tip: "conjunction", use: "also written 'so dass'" },
      { de: "sowohl", lookup: "sowohl", fallbackEn: "both … and", tip: "conjunction", use: "fixed pair: sowohl X als auch Y – both X and Y" },
      { de: "synchronisieren", lookup: "synchronisieren", fallbackEn: "to synchronise", tip: "verb", use: "also: to dub a film" },
      { de: "der Ton", lookup: "Ton", fallbackEn: "sound, tone", tip: "noun", article: "der", use: "also: clay; der gute Ton – good manners" },
      { de: "weich", lookup: "weich", fallbackEn: "soft", tip: "adjective", use: "opposite: hart" },
      { de: "werden", lookup: "werden", fallbackEn: "to become; will (future auxiliary)", tip: "verb", use: "würde + infinitive – would" },
      { de: "der Zugang", lookup: "Zugang", fallbackEn: "access", tip: "noun", article: "der", use: "Zugang zu + dative – access to" },
      { de: "amerikanisch", lookup: "amerikanisch", fallbackEn: "American", tip: "adjective", use: "lowercase in German, like all nationality adjectives" },
      { de: "aufgeregt", lookup: "aufgeregt", fallbackEn: "excited, nervous", tip: "adjective", use: "from aufregen; sich aufregen – to get worked up" },
      { de: "befriedigend", lookup: "befriedigend", fallbackEn: "satisfying, satisfactory", tip: "adjective", use: "also the German school grade 3 ('satisfactory')" },
      { de: "begrüßen", lookup: "begrüßen", fallbackEn: "to greet, to welcome", tip: "verb" },
      { de: "der Benutzer", lookup: "Benutzer", fallbackEn: "user", tip: "noun", article: "der", use: "from benutzen; feminine: die Benutzerin" },
      { de: "beängstigend", lookup: "beängstigend", fallbackEn: "frightening, worrying", tip: "adjective" },
      { de: "der Blitzschlag", lookup: "Blitzschlag", fallbackEn: "lightning strike", tip: "noun", article: "der" },
      { de: "buchstäblich", lookup: "buchstäblich", fallbackEn: "literally", tip: "adverb" },
      { de: "debuggen", lookup: "debuggen", fallbackEn: "to debug", tip: "verb", use: "IT loanword; perfect: hat debuggt" },
      { de: "das Ding", lookup: "Ding", fallbackEn: "thing", tip: "noun", article: "das", use: "plural: die Dinge" },
      { de: "erhalten", lookup: "erhalten", fallbackEn: "to receive, to preserve", tip: "verb", use: "formal alternative to 'bekommen'" },
      { de: "erreichen", lookup: "erreichen", fallbackEn: "to reach, to achieve", tip: "verb" },
      { de: "launchen", lookup: "launchen", fallbackEn: "to launch (a product)", tip: "verb", use: "marketing jargon; perfect: hat gelauncht" },
      { de: "ändern", lookup: "ändern", fallbackEn: "to change, to alter", tip: "verb" },
      { de: "haptisch", lookup: "haptisch", fallbackEn: "haptic, tactile", tip: "adjective" },
      { de: "hinweg", lookup: "hinweg", fallbackEn: "away, over", tip: "adverb", use: "über etwas hinweg = across/over something" },
      { de: "die Innovation", lookup: "Innovation", fallbackEn: "innovation, novelty", tip: "noun", article: "die" },
      { de: "intelligent", lookup: "intelligent", fallbackEn: "intelligent, clever", tip: "adjective" },
      { de: "der Junge", lookup: "Junge", fallbackEn: "boy", tip: "noun", article: "der", use: "plural 'Jungs' = guys, lads (colloquial)" },
      { de: "knackig", lookup: "knackig", fallbackEn: "crisp, crunchy", tip: "adjective", use: "colloquially also snappy, punchy (UI, prose, deadlines)" },
    ],
    dialogues: [],
    phrases: [],
  },
  part443: {
    label: "Part 443",
    level: "A2-B2",
    theme: "Opinions and reactions",
    description: "Reacting, agreeing, praising and complaining the way comment sections do it.",
    focus,
    seeds: [
      { de: "langfristig", lookup: "langfristig", fallbackEn: "long-term", tip: "adjective" },
      { de: "liefern", lookup: "liefern", fallbackEn: "to deliver, to supply", tip: "verb" },
      { de: "lokal", lookup: "lokal", fallbackEn: "local, locally", tip: "adjective", use: "IT: lokal laufen = to run locally" },
      { de: "lächerlich", lookup: "lächerlich", fallbackEn: "ridiculous, laughable", tip: "adjective" },
      { de: "die Million", lookup: "Million", fallbackEn: "million (number)", tip: "noun", article: "die", use: "plural: die Millionen (zwei Millionen Nutzer)" },
      { de: "mithören", lookup: "mithören", fallbackEn: "to listen in, to overhear", tip: "verb", use: "separable: hört mit, hat mitgehört" },
      { de: "das Modell", lookup: "Modell", fallbackEn: "model", tip: "noun", article: "das" },
      { de: "mächtig", lookup: "mächtig", fallbackEn: "powerful, mighty", tip: "adjective", use: "colloquial intensifier: mächtig stolz = mighty proud" },
      { de: "der Nutzer", lookup: "Nutzer", fallbackEn: "user", tip: "noun", article: "der", use: "standard word for app/service users; cf. der Benutzer" },
      { de: "offen", lookup: "offen", fallbackEn: "open, frank", tip: "adjective" },
      { de: "der Parameter", lookup: "Parameter", fallbackEn: "parameter, variable", tip: "noun", article: "der", use: "plural: die Parameter" },
      { de: "die Produktlinie", lookup: "Produktlinie", fallbackEn: "product line", tip: "noun", article: "die" },
      { de: "reaktionsschnell", lookup: "reaktionsschnell", fallbackEn: "quick to react, responsive", tip: "adjective" },
      { de: "riesig", lookup: "riesig", fallbackEn: "huge, enormous", tip: "adjective" },
      { de: "der Schieberegler", lookup: "Schieberegler", fallbackEn: "slider", tip: "noun", article: "der", use: "UI control; also fader on audio equipment" },
      { de: "schnell", lookup: "schnell", fallbackEn: "fast, quick", tip: "adjective" },
      { de: "selbst", lookup: "selbst", fallbackEn: "-self, even", tip: "adverb", use: "after noun/pronoun = myself, himself etc.; before it = even (selbst er = even he)" },
      { de: "sicherstellen", lookup: "sicherstellen", fallbackEn: "to ensure, to make sure", tip: "verb", use: "separable: stellt sicher, hat sichergestellt" },
      { de: "sich spezialisieren", lookup: "spezialisieren", fallbackEn: "to specialise", tip: "verb", use: "sich spezialisieren auf + accusative" },
      { de: "die Synchronisierung", lookup: "Synchronisierung", fallbackEn: "synchronisation, sync", tip: "noun", article: "die", use: "also die Synchronisation" },
      { de: "das Update", lookup: "Update", fallbackEn: "update (software)", tip: "noun", article: "das", use: "IT loanword; plural: die Updates" },
      { de: "verschieden", lookup: "verschieden", fallbackEn: "different, various", tip: "adjective" },
      { de: "visuell", lookup: "visuell", fallbackEn: "visual, visually", tip: "adjective" },
      { de: "das Volumen", lookup: "Volumen", fallbackEn: "volume", tip: "noun", article: "das", use: "amount/capacity, not loudness (that is die Lautstärke); plural: die Volumina" },
      { de: "weiterentwickeln", lookup: "weiterentwickeln", fallbackEn: "to develop further, to refine", tip: "verb", use: "separable; sich weiterentwickeln = to evolve, to grow" },
      { de: "während", lookup: "während", fallbackEn: "during, while", tip: "preposition", use: "preposition + genitive; as conjunction = while, whereas" },
      { de: "die Zukunft", lookup: "Zukunft", fallbackEn: "future", tip: "noun", article: "die" },
      { de: "zusätzlich", lookup: "zusätzlich", fallbackEn: "additional, extra", tip: "adjective" },
      { de: "zuvor", lookup: "zuvor", fallbackEn: "before, previously", tip: "adverb" },
      { de: "der Abend", lookup: "Abend", fallbackEn: "evening", tip: "noun", article: "der", use: "heute Abend = this evening, tonight" },
      { de: "anstatt", lookup: "anstatt", fallbackEn: "instead of", tip: "preposition", use: "+ genitive; anstatt zu + infinitive = instead of doing" },
      { de: "aufgebracht", lookup: "aufgebracht", fallbackEn: "irate, outraged, upset", tip: "adjective", use: "aufgebracht sein über + accusative = to be irate about" },
      { de: "der Autor", lookup: "Autor", fallbackEn: "author", tip: "noun", article: "der", use: "plural: die Autoren; female: die Autorin" },
      { de: "außerhalb", lookup: "außerhalb", fallbackEn: "outside, outside of", tip: "preposition", use: "+ genitive: außerhalb der Stadt; also adverb" },
      { de: "der Blog", lookup: "Blog", fallbackEn: "blog (website)", tip: "noun", article: "der", use: "Duden allows der or das Blog" },
      { de: "britisch", lookup: "britisch", fallbackEn: "British", tip: "adjective" },
      { de: "die Chancengleichheit", lookup: "Chancengleichheit", fallbackEn: "equal opportunities", tip: "noun", article: "die" },
      { de: "der Drehbuchautor", lookup: "Drehbuchautor", fallbackEn: "screenwriter, scriptwriter", tip: "noun", article: "der" },
      { de: "der Ersteller", lookup: "Ersteller", fallbackEn: "creator, author", tip: "noun", article: "der", use: "agent noun of erstellen; frequent in app UIs" },
      { de: "der Gesprächsverlauf", lookup: "Gesprächsverlauf", fallbackEn: "conversation history, course of a conversation", tip: "noun", article: "der", use: "chat and app UIs: conversation history" },
    ],
    dialogues: [],
    phrases: [],
  },
  part444: {
    label: "Part 444",
    level: "A2-B2",
    theme: "Real usage leftovers",
    description: "The rest of the genuinely useful words surfaced by real browsing, from formal connectors to vivid descriptions.",
    focus,
    seeds: [
      { de: "gut", lookup: "gut", fallbackEn: "good, well", tip: "adjective" },
      { de: "innerhalb", lookup: "innerhalb", fallbackEn: "within, inside", tip: "preposition", use: "takes genitive or von + dative: innerhalb von 15 Minuten" },
      { de: "international", lookup: "international", fallbackEn: "international, worldwide", tip: "adjective" },
      { de: "das Investment", lookup: "Investment", fallbackEn: "investment (finance)", tip: "noun", article: "das", use: "finance loan; everyday synonym: die Investition" },
      { de: "kostenlos", lookup: "kostenlos", fallbackEn: "free of charge, free", tip: "adjective" },
      { de: "die Leute", lookup: "Leute", fallbackEn: "people", tip: "noun", article: "die", use: "plural only" },
      { de: "die Milliarde", lookup: "Milliarde", fallbackEn: "billion", tip: "noun", article: "die", use: "false friend: die Billion = trillion" },
      { de: "die Minute", lookup: "Minute", fallbackEn: "minute (of time)", tip: "noun", article: "die" },
      { de: "die Nacht", lookup: "Nacht", fallbackEn: "night", tip: "noun", article: "die" },
      { de: "der Newsletter", lookup: "Newsletter", fallbackEn: "newsletter (email)", tip: "noun", article: "der", use: "English loan; plural: die Newsletter" },
      { de: "oben", lookup: "oben", fallbackEn: "above, at the top, upstairs", tip: "adverb" },
      { de: "der Platz", lookup: "Platz", fallbackEn: "place, square, seat", tip: "noun", article: "der", use: "auf Platz 3 = in third place" },
      { de: "der Preis", lookup: "Preis", fallbackEn: "price, prize", tip: "noun", article: "der" },
      { de: "quantisieren", lookup: "quantisieren", fallbackEn: "to quantise", tip: "verb", use: "technical: physics, AI model compression" },
      { de: "die Redefreiheit", lookup: "Redefreiheit", fallbackEn: "freedom of speech, free speech", tip: "noun", article: "die" },
      { de: "roh", lookup: "roh", fallbackEn: "raw, crude", tip: "adjective" },
      { de: "scheinen", lookup: "scheinen", fallbackEn: "to seem, to appear, to shine", tip: "verb", use: "scheinen + zu-infinitive = to seem to" },
      { de: "der Schlaf", lookup: "Schlaf", fallbackEn: "sleep", tip: "noun", article: "der" },
      { de: "der Schritt", lookup: "Schritt", fallbackEn: "step", tip: "noun", article: "der", use: "Schritt für Schritt = step by step" },
      { de: "die Sensation", lookup: "Sensation", fallbackEn: "sensation, stir", tip: "noun", article: "die" },
      { de: "standardmäßig", lookup: "standardmäßig", fallbackEn: "by default, as standard", tip: "adjective", use: "software staple, usually adverbial: by default" },
      { de: "der Trick", lookup: "Trick", fallbackEn: "trick, ploy", tip: "noun", article: "der", use: "long-naturalised loan; plural: die Tricks" },
      { de: "tun", lookup: "tun", fallbackEn: "to do", tip: "verb", use: "Was tun? = what to do?; weh tun = to hurt" },
      { de: "wachsen", lookup: "wachsen", fallbackEn: "to grow", tip: "verb", use: "irregular: wächst, wuchs, ist gewachsen" },
      { de: "der Webdesigner", lookup: "Webdesigner", fallbackEn: "web designer", tip: "noun", article: "der", use: "English loan (Duden), profession" },
      { de: "die Website", lookup: "Website", fallbackEn: "website, web page", tip: "noun", article: "die", use: "English loan; compare die Webseite = web page" },
      { de: "wecken", lookup: "wecken", fallbackEn: "to wake, to rouse", tip: "verb", use: "transitive; figurative: Interesse wecken = to spark interest" },
      { de: "weiter", lookup: "weiter", fallbackEn: "further, additional", tip: "adjective", use: "weitere Informationen = further information; as adverb: onwards" },
      { de: "der Wert", lookup: "Wert", fallbackEn: "value, worth", tip: "noun", article: "der" },
      { de: "willkommen", lookup: "willkommen", fallbackEn: "welcome", tip: "adjective", use: "Herzlich willkommen! = Welcome!" },
      { de: "das Wort", lookup: "Wort", fallbackEn: "word", tip: "noun", article: "das", use: "plurals: Wörter (individual words), Worte (utterances)" },
      { de: "die Zeit", lookup: "Zeit", fallbackEn: "time", tip: "noun", article: "die" },
      { de: "ziemlich", lookup: "ziemlich", fallbackEn: "quite, rather, fairly", tip: "adverb" },
      { de: "zurückbringen", lookup: "zurückbringen", fallbackEn: "to bring back, to return", tip: "verb", use: "separable: bringt … zurück" },
    ],
    dialogues: [],
    phrases: [],
  },
  part445: {
    label: "Part 445",
    level: "A1-B1",
    theme: "Everyday words from real browsing",
    description: "Genuinely new everyday words found in the second Immersion export, with names, brands, duplicates and inflected forms removed.",
    focus,
    seeds: [
      { de: "reposten", lookup: "reposten", fallbackEn: "to repost", tip: "verb", use: "social-media loanword; perfect: hat repostet" },
      { de: "möchten", lookup: "möchten", fallbackEn: "would like", tip: "verb", use: "polite everyday form: Ich möchte ..." },
      { de: "danke", lookup: "danke", fallbackEn: "thanks, thank you", tip: "interjection", use: "very common standalone reply; Danke schön = thank you very much" },
      { de: "dann", lookup: "dann", fallbackEn: "then", tip: "adverb" },
      { de: "still", lookup: "still", fallbackEn: "quiet, silent", tip: "adjective", use: "still sein = to be quiet; not English 'still' (immer noch)" },
      { de: "derzeit", lookup: "derzeit", fallbackEn: "currently, at present", tip: "adverb", use: "neutral written/UI word; in conversation jetzt or gerade is often more natural" },
      { de: "anstelle", lookup: "anstelle", fallbackEn: "instead of", tip: "preposition", use: "also anstatt; followed by genitive or von + dative" },
      { de: "darüber", lookup: "darüber", fallbackEn: "about it, over it", tip: "adverb", use: "darüber sprechen = to talk about it" },
      { de: "ein bisschen", lookup: "bisschen", fallbackEn: "a little, a bit", tip: "phrase", use: "very common conversational softener; normally used with ein: ein bisschen müde" },
      { de: "dumm", lookup: "dumm", fallbackEn: "stupid, silly", tip: "adjective", use: "common but blunt when aimed at a person" },
      { de: "die Geschwister", lookup: "Geschwister", fallbackEn: "siblings", tip: "noun", article: "die", use: "normally plural; one sibling is ein Geschwisterteil" },
      { de: "die Hitze", lookup: "Hitze", fallbackEn: "heat", tip: "noun", article: "die", use: "weather or intense heat; ordinary warmth is Wärme" },
      { de: "irgendwie", lookup: "irgendwie", fallbackEn: "somehow, kind of", tip: "adverb", use: "very common conversational softener" },
      { de: "niemand", lookup: "niemand", fallbackEn: "nobody, no one", tip: "pronoun", use: "can take endings: niemanden, niemandem" },
      { de: "schlau", lookup: "schlau", fallbackEn: "clever, smart", tip: "adjective" },
      { de: "trotz", lookup: "trotz", fallbackEn: "despite, in spite of", tip: "preposition", use: "standard German takes genitive; dative is common in speech" },
      { de: "wegen", lookup: "wegen", fallbackEn: "because of", tip: "preposition", use: "standard German takes genitive; dative is widespread in speech" },
      { de: "arm", lookup: "arm", fallbackEn: "poor", tip: "adjective", use: "lowercase arm = poor; the body part is der Arm" },
    ],
    dialogues: [],
    phrases: [],
  },
  part446: {
    label: "Part 446",
    level: "A2-B2",
    theme: "Useful reading and discussion words",
    description: "Practical words from real German posts and interfaces, prioritised by broad usefulness rather than the source topic.",
    focus,
    seeds: [
      { de: "bitte", lookup: "bitte", fallbackEn: "please, you're welcome", tip: "adverb", use: "also Bitte? = pardon? and bitte schön = here you go" },
      { de: "entkommen", lookup: "entkommen", fallbackEn: "to escape", tip: "verb", use: "takes dative: einer Gefahr entkommen" },
      { de: "ernsthaft", lookup: "ernsthaft", fallbackEn: "seriously, serious", tip: "adjective", use: "Ernsthaft? = Seriously?" },
      { de: "explizit", lookup: "explizit", fallbackEn: "explicit, explicitly", tip: "adjective", use: "more formal; ausdrücklich is another common equivalent" },
      { de: "kaum", lookup: "kaum", fallbackEn: "hardly, barely", tip: "adverb", use: "Ich kann es kaum erwarten = I can't wait" },
      { de: "die Konversation", lookup: "Konversation", fallbackEn: "conversation", tip: "noun", article: "die", use: "neutral/formal; everyday speech usually uses Gespräch" },
      { de: "mitten", lookup: "mitten", fallbackEn: "right in the middle", tip: "adverb", use: "mitten im Gespräch = in the middle of the conversation" },
      { de: "schlafen", lookup: "schlafen", fallbackEn: "to sleep", tip: "verb", use: "irregular: schläft, schlief, hat geschlafen" },
      { de: "sofort", lookup: "sofort", fallbackEn: "immediately, right away", tip: "adverb" },
      { de: "verfassen", lookup: "verfassen", fallbackEn: "to write, compose", tip: "verb", use: "a formal text, report or post; everyday 'write' is schreiben" },
      { de: "verfügen", lookup: "verfügen", fallbackEn: "to have at one's disposal", tip: "verb", use: "formal: über etwas verfügen = to have something available" },
      { de: "verärgern", lookup: "verärgern", fallbackEn: "to annoy, upset", tip: "verb", use: "jemanden verärgern; sich ärgern is to get annoyed" },
      { de: "das Verbot", lookup: "Verbot", fallbackEn: "ban, prohibition", tip: "noun", article: "das" },
      { de: "die Abschreckung", lookup: "Abschreckung", fallbackEn: "deterrence", tip: "noun", article: "die", use: "mostly news, politics and formal discussion" },
      { de: "die Pressestelle", lookup: "Pressestelle", fallbackEn: "press office", tip: "noun", article: "die" },
      { de: "der Riss", lookup: "Riss", fallbackEn: "crack, tear", tip: "noun", article: "der", use: "plural: die Risse" },
      { de: "weiterhin", lookup: "weiterhin", fallbackEn: "still, continuing to", tip: "adverb", use: "often used in news and neutral speech: Es gilt weiterhin = It still applies" },
      { de: "wieder", lookup: "wieder", fallbackEn: "again", tip: "adverb" },
      { de: "wohlhabend", lookup: "wohlhabend", fallbackEn: "wealthy, well-off", tip: "adjective", use: "neutral; reich is the more direct everyday word for rich" },
      { de: "worum", lookup: "worum", fallbackEn: "what ... about", tip: "adverb", use: "Worum geht's? = What's it about?" },
    ],
    dialogues: [],
    phrases: [],
  },
  part447: {
    label: "Part 447",
    level: "A1-B2",
    theme: "Everyday reactions from real browsing",
    description: "Common conversational words surfaced by real German posts, taught through short phrases people can reuse immediately.",
    focus,
    seeds: [
      { de: "posten", lookup: "posten", fallbackEn: "to post (online)", tip: "verb", use: "social-media verb; perfect: hat gepostet" },
      { de: "jemand", lookup: "jemand", fallbackEn: "someone, somebody", tip: "pronoun", use: "changes in some sentences: jemanden, jemandem" },
      { de: "jemals", lookup: "jemals", fallbackEn: "ever", tip: "adverb", use: "especially common in questions and negatives" },
      { de: "dasselbe", lookup: "dasselbe", fallbackEn: "the same thing", tip: "pronoun", use: "not das Gleiche: dasselbe is literally the very same one" },
      { de: "meist", lookup: "meist", fallbackEn: "mostly, usually", tip: "adverb", use: "also used before nouns as die meisten = most" },
      { de: "meistens", lookup: "meistens", fallbackEn: "usually, most of the time", tip: "adverb", use: "very common in conversation; meist is the shorter neutral form" },
      { de: "drin", lookup: "drin", fallbackEn: "inside, in it, in there", tip: "adverb", use: "everyday short form of darin; not for formal writing" },
      { de: "sich freuen", lookup: "freuen", fallbackEn: "to be happy, to look forward to", tip: "verb", use: "sich auf etwas freuen = to look forward to something" },
      { de: "wütend", lookup: "wütend", fallbackEn: "angry, furious", tip: "adjective", use: "wütend auf jemanden / über etwas" },
      { de: "durchdrehen", lookup: "durchdrehen", fallbackEn: "to lose it, to go crazy", tip: "verb", use: "very conversational; separable: dreht durch" },
      { de: "ertragen", lookup: "ertragen", fallbackEn: "to bear, to stand, to endure", tip: "verb", use: "Ich kann das nicht ertragen = I can't stand that" },
      { de: "das Chaos", lookup: "Chaos", fallbackEn: "chaos, mess", tip: "noun", article: "das", use: "often means a messy or disorganised situation, not literal catastrophe" },
      { de: "zweifeln", lookup: "zweifeln", fallbackEn: "to doubt", tip: "verb", use: "an etwas zweifeln; an sich selbst zweifeln" },
      { de: "angewidert", lookup: "angewidert", fallbackEn: "disgusted", tip: "adjective", use: "stronger and less casual than widerlich finden" },
      { de: "entsetzlich", lookup: "entsetzlich", fallbackEn: "awful, terrible", tip: "adjective", use: "a strong reaction to bad news or an unpleasant experience" },
      { de: "ackern", lookup: "ackern", fallbackEn: "to slog away, to work very hard", tip: "verb", use: "casual; literally also to plough a field" },
      { de: "zutiefst", lookup: "zutiefst", fallbackEn: "deeply, profoundly", tip: "adverb", use: "strong and usually more serious than sehr" },
      { de: "zusammentragen", lookup: "zusammentragen", fallbackEn: "to collect, to compile", tip: "verb", use: "separable: Informationen zusammentragen" },
    ],
    dialogues: [],
    phrases: [
      { de: "Hast du das schon gepostet?", en: "Have you posted that yet?", use: "A normal quick question about a photo, message or update.", group: "real-browsing-everyday", lessonPriority: -180000 },
      { de: "Ist da jemand drin?", en: "Is someone in there?", use: "At a bathroom, changing room or any closed space.", group: "real-browsing-everyday", lessonPriority: -175000 },
      { de: "Hast du das jemals ausprobiert?", en: "Have you ever tried that?", use: "A very reusable conversational question.", group: "real-browsing-everyday", lessonPriority: -170000 },
      { de: "Ich hab dieselbe Frage.", en: "I have the same question.", long: "Ich habe dieselbe Frage.", use: "Natural in a group, class, meeting or chat.", group: "real-browsing-everyday", lessonPriority: -165000 },
      { de: "Das ist meistens so.", en: "That's usually how it is.", use: "A relaxed way to describe the usual pattern.", group: "real-browsing-everyday", lessonPriority: -160000 },
      { de: "Ich freu mich drauf.", en: "I'm looking forward to it.", long: "Ich freue mich darauf.", use: "The short form is what people normally say in conversation.", group: "real-browsing-everyday", lessonPriority: -190000 },
      { de: "Das macht mich echt wütend.", en: "That really makes me angry.", use: "Direct but natural when something genuinely bothers you.", group: "real-browsing-everyday", lessonPriority: -155000 },
      { de: "Ich dreh gleich durch.", en: "I'm about to lose it.", long: "Ich drehe gleich durch.", use: "Casual and dramatic; often frustration rather than literal loss of control.", group: "real-browsing-everyday", lessonPriority: -150000 },
      { de: "Ich kann das nicht mehr ertragen.", en: "I can't stand this anymore.", use: "A strong but common complaint.", group: "real-browsing-everyday", lessonPriority: -145000 },
      { de: "Hier ist echt Chaos.", en: "It's a real mess in here.", use: "Everyday Chaos often means disorder or a messy situation.", group: "real-browsing-everyday", lessonPriority: -140000 },
      { de: "Ich hab echt an mir gezweifelt.", en: "I really doubted myself.", long: "Ich habe wirklich an mir gezweifelt.", use: "Natural when talking honestly about confidence.", group: "real-browsing-everyday", lessonPriority: -125000 },
      { de: "Das ist ja entsetzlich.", en: "That's awful.", use: "A strong sympathetic reaction to bad news.", group: "real-browsing-everyday", lessonPriority: -120000 },
      { de: "Ich musste heute echt ackern.", en: "I really had to work hard today.", use: "Casual; ackern makes the work sound tiring or relentless.", group: "real-browsing-everyday", lessonPriority: -100000 },
      { de: "Das hat sich echt gelohnt.", en: "That was really worth it.", use: "A very common positive verdict after effort, money or waiting.", group: "real-browsing-everyday", lessonPriority: -185000 },
    ],
  },
  part448: {
    label: "Part 448",
    level: "A2-C1",
    theme: "Useful web and news vocabulary",
    description: "Reusable reading vocabulary found in German posts after account names, brands, interface chrome and English leakage were removed.",
    focus,
    seeds: [
      { de: "der Anwendungsfall", lookup: "Anwendungsfall", fallbackEn: "use case", tip: "noun", article: "der", use: "common in technology and business discussions" },
      { de: "nativ", lookup: "nativ", fallbackEn: "native, natively", tip: "adjective", use: "technical: nativ laufen = to run natively" },
      { de: "die Internetgeschwindigkeit", lookup: "Internetgeschwindigkeit", fallbackEn: "internet speed", tip: "noun", article: "die" },
      { de: "der Stellenabbau", lookup: "Stellenabbau", fallbackEn: "job cuts, workforce reduction", tip: "noun", article: "der", use: "standard news and workplace vocabulary" },
      { de: "der Hacker", lookup: "Hacker", fallbackEn: "hacker", tip: "noun", article: "der", use: "plural: die Hacker; feminine: die Hackerin" },
      { de: "die Bedrohung", lookup: "Bedrohung", fallbackEn: "threat", tip: "noun", article: "die" },
      { de: "die Epidemie", lookup: "Epidemie", fallbackEn: "epidemic", tip: "noun", article: "die" },
      { de: "bewässern", lookup: "bewässern", fallbackEn: "to water, to irrigate", tip: "verb", use: "for land or larger areas; plants are more often gegossen in conversation" },
      { de: "der Gartenschlauch", lookup: "Gartenschlauch", fallbackEn: "garden hose", tip: "noun", article: "der" },
      { de: "die Raumzeit", lookup: "Raumzeit", fallbackEn: "spacetime", tip: "noun", article: "die", use: "physics vocabulary surfaced by a real science post" },
    ],
    dialogues: [],
    phrases: [
      { de: "Das ist ein typischer Anwendungsfall.", en: "That's a typical use case.", use: "Common in technical and product discussions.", group: "real-browsing-reading", lessonPriority: 120000 },
      { de: "Das läuft nativ.", en: "It runs natively.", use: "Short technical explanation about software or hardware.", group: "real-browsing-reading", lessonPriority: 130000 },
      { de: "Mein Internet ist heute echt langsam.", en: "My internet is really slow today.", use: "The conversational sentence people use; Internetgeschwindigkeit is useful when you need the precise noun.", group: "real-browsing-reading", lessonPriority: -90000 },
      { de: "Es droht ein weiterer Stellenabbau.", en: "There could be more job cuts.", use: "Neutral news and workplace wording.", group: "real-browsing-reading", lessonPriority: 180000 },
      { de: "Das klingt nach einer echten Bedrohung.", en: "That sounds like a real threat.", use: "Useful in serious discussions without sounding legalistic.", group: "real-browsing-reading", lessonPriority: 150000 },
      { de: "Kannst du den Gartenschlauch holen?", en: "Can you get the garden hose?", use: "Straightforward household request.", group: "real-browsing-reading", lessonPriority: 210000 },
      { de: "Ich muss noch die Pflanzen gießen.", en: "I still need to water the plants.", use: "This is the ordinary conversational wording; bewässern is used for larger areas or formal descriptions.", group: "real-browsing-reading", lessonPriority: 50000 },
    ],
  },
  part449: {
    label: "Part 449",
    level: "A1-B1",
    theme: "Messages and everyday interface German",
    description: "Useful words surfaced again in real German browsing, with account names, handles, brands and repeated site chrome removed.",
    focus,
    seeds: [
      { de: "die Mitteilung", lookup: "Mitteilung", fallbackEn: "message, notification, notice", tip: "noun", article: "die", use: "plural: die Mitteilungen; apps also commonly say die Benachrichtigung for a notification" },
      { de: "die Startseite", lookup: "Startseite", fallbackEn: "home page, start page", tip: "noun", article: "die", use: "website and app navigation; zurück zur Startseite = back to the home page" },
      { de: "das Premium-Abo", lookup: "Premium-Abo", fallbackEn: "premium subscription", tip: "noun", article: "das", use: "apps and services often shorten this to Premium in menu labels" },
      { de: "kollektiv", lookup: "kollektiv", fallbackEn: "collective, jointly", tip: "adjective", use: "more formal than gemeinsam; common in news and community contexts" },
      { de: "erbärmlich", lookup: "erbärmlich", fallbackEn: "pathetic, pitiful", tip: "adjective", use: "a strong negative judgement; can sound harsh when aimed at a person" },
      { de: "verabscheuen", lookup: "verabscheuen", fallbackEn: "to detest, to loathe", tip: "verb", use: "very strong and more serious than nicht mögen; in everyday speech nicht ausstehen is often more natural" },
      { de: "Großbritannien", lookup: "Großbritannien", fallbackEn: "Great Britain, Britain", tip: "proper noun", use: "the island containing England, Scotland and Wales; the full country name is das Vereinigte Königreich" },
    ],
    dialogues: [],
    phrases: [
      { de: "Ich hab eine neue Benachrichtigung bekommen.", en: "I got a new notification.", long: "Ich habe eine neue Benachrichtigung bekommen.", use: "The normal conversational wording for a phone or app notification. Mitteilung is also used in menus and for an official message or notice.", group: "real-browsing-interface", lessonPriority: -170000 },
      { de: "Hast du meine Nachricht gesehen?", en: "Did you see my message?", use: "The everyday sentence people usually need in conversation; Nachricht is more natural than Mitteilung for a personal message.", group: "real-browsing-interface", lessonPriority: -185000 },
      { de: "Geh zurück zur Startseite.", en: "Go back to the home page.", use: "A simple instruction when helping someone use a site or app.", group: "real-browsing-interface", lessonPriority: 80000 },
      { de: "Ich hab kein Premium-Abo.", en: "I don't have a premium subscription.", long: "Ich habe kein Premium-Abonnement.", use: "Premium-Abo is the normal concise wording in conversation; apps often label the section simply Premium.", group: "real-browsing-interface", lessonPriority: 75000 },
      { de: "Das ist einfach erbärmlich.", en: "That's just pathetic.", use: "A blunt, natural reaction to disgraceful behaviour or a very poor effort.", group: "real-browsing-interface", lessonPriority: 65000 },
      { de: "Ich kann dieses Verhalten echt nicht ausstehen.", en: "I really can't stand this behaviour.", long: "Ich verabscheue dieses Verhalten zutiefst.", use: "The first version is more conversational. Verabscheuen is stronger and common in serious or written statements.", group: "real-browsing-interface", lessonPriority: 90000 },
      { de: "Ich war noch nie in Großbritannien.", en: "I've never been to Britain.", use: "A reusable travel sentence; Großbritannien is commonly used for Britain.", group: "real-browsing-interface", lessonPriority: 70000 },
      { de: "Das war eine kollektive Entscheidung.", en: "That was a collective decision.", use: "Neutral wording for a decision made by a whole group; gemeinsam entschieden is more conversational.", group: "real-browsing-interface", lessonPriority: 190000 },
    ],
  },
  part450: {
    label: "Part 450",
    level: "A1-B1",
    theme: "Useful words from real browsing",
    description: "A small, carefully filtered follow-up from the latest Immersion export: genuine German only, taught through natural sentences rather than copied post text.",
    focus,
    seeds: [
      { de: "mehr", lookup: "mehr", fallbackEn: "more", tip: "adverb", use: "very common; noch mehr means even more or some more" },
      { de: "Schweden", lookup: "Schweden", fallbackEn: "Sweden", tip: "proper noun", use: "normally used without an article: aus Schweden, in Schweden" },
      { de: "schwedisch", lookup: "schwedisch", fallbackEn: "Swedish", tip: "adjective", use: "lowercase as an adjective; Schwedisch is capitalised when it means the language" },
      { de: "tot", lookup: "tot", fallbackEn: "dead", tip: "adjective", use: "direct and sometimes blunt; gestorben is often gentler when talking about a person" },
    ],
    dialogues: [],
    phrases: [
      { de: "Willst du noch mehr?", en: "Do you want some more?", use: "A very common everyday use of mehr with food, drinks or anything being offered.", group: "real-browsing-follow-up", lessonPriority: -220000 },
      { de: "Ich hab's dir versprochen.", en: "I promised you.", long: "Ich habe es dir versprochen.", use: "The natural spoken version. Without sich, versprechen means to promise; sich versprechen means to misspeak.", group: "real-browsing-follow-up", lessonPriority: -190000 },
      { de: "Wir sammeln Geld für ein Geschenk.", en: "We're collecting money for a present.", use: "A common use of sammeln among friends, at work or in a family.", group: "real-browsing-follow-up", lessonPriority: -130000 },
      { de: "Kommst du aus Schweden?", en: "Are you from Sweden?", use: "A simple, natural question about where someone is from.", group: "real-browsing-follow-up", lessonPriority: -120000 },
      { de: "Das ist eine schwedische Firma.", en: "That's a Swedish company.", use: "A reusable way to describe where a company or brand comes from.", group: "real-browsing-follow-up", lessonPriority: 70000 },
      { de: "Ist er wirklich tot?", en: "Is he really dead?", use: "Direct and appropriate when checking a fact. In a sensitive conversation, ask Ist er wirklich gestorben? instead.", group: "real-browsing-follow-up", lessonPriority: 100000 },
      { de: "Er ist leider gestorben.", en: "He died, unfortunately.", use: "Usually gentler than Er ist tot when telling someone about a person's death.", group: "real-browsing-follow-up", lessonPriority: 110000 },
    ],
  },
};
