import type { CountryQuestion } from "@/lib/countryStudies";

/**
 * La raccolta di esercizio del corso «Vivere in Italia».
 *
 * Costruita come quelle britannica, tedesca, francese e polacca, e separata
 * dai quiz dentro le lezioni per la stessa ragione: quelli chiudono la
 * lezione mentre il testo è ancora sullo schermo, queste tornano in ordine
 * sparso molto tempo dopo la lettura.
 *
 * Nessuna domanda di lezione ricompare qui. Niente può servire due volte —
 * check-it-questions confronta i due insiemi e ferma la compilazione se si
 * sovrappongono.
 *
 * Ogni domanda porta l'identificatore della lezione che la insegna. Il
 * capitolo si ricava dalla lezione, non da un secondo elenco tenuto a mano.
 *
 * LA DIFFICOLTÀ è assegnata, non calcolata. «easy»: la risposta sta nella
 * lezione in modo esplicito. «medium»: bisogna ricordare un nome, una data o
 * un numero. «hard»: bisogna mettere insieme due fatti, oppure la domanda
 * punta a una confusione ricorrente — il 2 giugno e il 17 marzo, l'articolo
 * 138 e l'articolo 75, il dialetto e la lingua minoritaria.
 *
 * I TEMI seguono il contenuto delle lezioni e non un catalogo d'esame: in
 * Italia quell'esame non esiste. Le domande verificano se si capisce il
 * paese, non se si è superata una prova.
 */

export const IT_QUESTIONS: CountryQuestion[] = [
  // ── Simboli nazionali ──────────────────────────────────────────────────
  { id: "sim-1", lesson: "it-simboli", level: "easy",
    q: "Quale articolo della Costituzione descrive la bandiera?",
    options: ["L'articolo 1", "L'articolo 6", "L'articolo 11", "L'articolo 12"],
    answer: 3,
    explanation: "L'articolo 12 chiude i principi fondamentali e descrive il tricolore a tre bande verticali di uguali dimensioni." },
  { id: "sim-2", lesson: "it-simboli", level: "easy",
    q: "Come si chiama ufficialmente l'inno nazionale?",
    options: ["Fratelli d'Italia", "Il Canto degli Italiani", "Inno di Mameli", "Va' pensiero"],
    answer: 1,
    explanation: "Il titolo ufficiale è Il Canto degli Italiani. Fratelli d'Italia è il primo verso e Inno di Mameli il nome corrente: entrambi indicano lo stesso brano, ma non sono il titolo." },
  { id: "sim-3", lesson: "it-simboli", level: "medium",
    q: "In quale città nacque il tricolore nel 1797?",
    options: ["Milano", "Reggio Emilia", "Torino", "Bologna"],
    answer: 1,
    explanation: "Il 7 gennaio 1797 la Repubblica Cispadana adottò il tricolore a Reggio Emilia. Per questo il 7 gennaio è la Festa del Tricolore." },
  { id: "sim-4", lesson: "it-simboli", level: "medium",
    q: "Chi compose la musica dell'inno nazionale?",
    options: ["Goffredo Mameli", "Giuseppe Verdi", "Michele Novaro", "Gioachino Rossini"],
    answer: 2,
    explanation: "La musica è di Michele Novaro, il testo di Goffredo Mameli. Il nome corrente ricorda solo l'autore delle parole." },
  { id: "sim-5", lesson: "it-simboli", level: "medium",
    q: "Da quando è in vigore l'emblema della Repubblica?",
    options: ["Dal 1861", "Dal 1946", "Dal 1948", "Dal 2017"],
    answer: 2,
    explanation: "L'emblema, scelto per concorso pubblico, è in vigore dal 5 maggio 1948, pochi mesi dopo l'entrata in vigore della Costituzione." },
  { id: "sim-6", lesson: "it-simboli", level: "easy",
    q: "Quale ramo dell'emblema rappresenta la pace?",
    options: ["Il ramo di quercia", "Il ramo di olivo", "Il ramo di alloro", "Il ramo di palma"],
    answer: 1,
    explanation: "L'olivo sta per la pace, la quercia per la forza e la dignità. Sono due alberi diffusi in tutta la penisola." },
  { id: "sim-7", lesson: "it-simboli", level: "medium",
    q: "Che cosa richiama la ruota dentata dell'emblema?",
    options: ["L'industria automobilistica", "Il lavoro", "La navigazione", "Il tempo"],
    answer: 1,
    explanation: "L'ingranaggio richiama il lavoro, su cui l'articolo 1 fonda la Repubblica: l'emblema cita la Costituzione." },
  { id: "sim-8", lesson: "it-simboli", level: "hard",
    q: "In che anno Il Canto degli Italiani è diventato inno ufficiale per legge?",
    options: ["Nel 1946", "Nel 1948", "Nel 1977", "Nel 2017"],
    answer: 3,
    explanation: "Adottato in via provvisoria nel 1946, è diventato inno ufficiale soltanto con la legge del 4 dicembre 2017: settant'anni da provvisorio." },
  { id: "sim-9", lesson: "it-simboli", level: "medium",
    q: "Che cosa si celebra il 7 gennaio?",
    options: ["La Festa della Repubblica", "La Festa del Tricolore", "L'Epifania civile", "La Giornata della Costituzione"],
    answer: 1,
    explanation: "Il 7 gennaio è la Festa del Tricolore, anniversario dell'adozione della bandiera nel 1797. Non è giorno festivo." },
  { id: "sim-10", lesson: "it-simboli", level: "hard",
    q: "Quale evento ricorda il 4 novembre?",
    options: [
      "L'armistizio del 1918 e l'unità nazionale",
      "La liberazione dal nazifascismo",
      "La nascita della Repubblica",
      "L'entrata in guerra del 1940",
    ],
    answer: 0,
    explanation: "Il 4 novembre è il Giorno dell'Unità nazionale e Festa delle Forze armate, legato all'armistizio del 1918. La Liberazione è il 25 aprile e la Repubblica il 2 giugno." },
  { id: "sim-11", lesson: "it-simboli", level: "easy",
    q: "Come sono disposte le bande del tricolore?",
    options: [
      "Orizzontali, di larghezza diversa",
      "Verticali, di uguali dimensioni",
      "Orizzontali, di uguali dimensioni",
      "In diagonale",
    ],
    answer: 1,
    explanation: "Tre bande verticali di uguali dimensioni. Le bande orizzontali sono quelle della bandiera ungherese, che ha gli stessi colori disposti diversamente." },
  { id: "sim-12", lesson: "it-simboli", level: "medium",
    q: "Chi disegnò l'emblema della Repubblica?",
    options: ["Paolo Paschetto", "Giuseppe Terragni", "Renato Guttuso", "Bruno Munari"],
    answer: 0,
    explanation: "L'emblema fu disegnato da Paolo Paschetto, vincitore del concorso pubblico bandito dal governo nel 1946." },
  { id: "sim-13", lesson: "it-simboli", level: "hard",
    q: "Perché l'Italia ha un emblema e non uno stemma?",
    options: [
      "Perché lo stemma è riservato alle monarchie e l'emblema non discende da una dinastia",
      "Perché l'araldica è vietata dalla Costituzione",
      "Perché uno stemma sarebbe troppo costoso da riprodurre",
      "Perché lo stemma spetta solo alle regioni",
    ],
    answer: 0,
    explanation: "Uno stemma discende da una famiglia regnante; l'emblema fu inventato da una repubblica appena nata, scegliendolo per concorso pubblico. È una differenza di origine, non di forma." },

  // ── La Costituzione e i principi fondamentali ──────────────────────────
  { id: "cos-1", lesson: "it-costituzione", level: "easy",
    q: "Quanti articoli ha la Costituzione italiana?",
    options: ["Dodici", "Cinquantacinque", "Centotrentanove", "Duecento"],
    answer: 2,
    explanation: "Centotrentanove articoli, più diciotto disposizioni transitorie e finali. Dodici sono i soli principi fondamentali." },
  { id: "cos-2", lesson: "it-costituzione", level: "medium",
    q: "Chi promulgò la Costituzione nel dicembre 1947?",
    options: ["Alcide De Gasperi", "Enrico De Nicola", "Luigi Einaudi", "Umberto II"],
    answer: 1,
    explanation: "Enrico De Nicola, capo provvisorio dello Stato. Einaudi sarà il primo Presidente della Repubblica eletto dal Parlamento, nel 1948." },
  { id: "cos-3", lesson: "it-costituzione", level: "medium",
    q: "Quando fu eletta l'Assemblea costituente?",
    options: ["Il 25 aprile 1945", "Il 2 giugno 1946", "Il 22 dicembre 1947", "Il 18 aprile 1948"],
    answer: 1,
    explanation: "L'Assemblea fu eletta il 2 giugno 1946, lo stesso giorno del referendum istituzionale: una scheda per la forma dello Stato, una per i costituenti." },
  { id: "cos-4", lesson: "it-costituzione", level: "hard",
    q: "Che cosa rese storico il voto del 2 giugno 1946?",
    options: [
      "Fu il primo voto a scrutinio segreto",
      "Fu la prima volta che votarono le donne a livello nazionale",
      "Fu il primo voto con le schede stampate",
      "Fu il primo voto aperto ai diciottenni",
    ],
    answer: 1,
    explanation: "Fu la prima consultazione a suffragio davvero universale: le donne votarono per la prima volta a livello nazionale. Il voto ai diciottenni arriverà solo nel 1975." },
  { id: "cos-5", lesson: "it-costituzione", level: "medium",
    q: "Su che cosa è fondata la Repubblica secondo l'articolo 1?",
    options: ["Sulla famiglia", "Sul lavoro", "Sulla libertà", "Sulla proprietà"],
    answer: 1,
    explanation: "Una repubblica democratica fondata sul lavoro: la formula fu il compromesso fra chi voleva una repubblica dei lavoratori e chi ne voleva una definizione più generale." },
  { id: "cos-6", lesson: "it-costituzione", level: "hard",
    q: "Che cosa aggiunge il secondo comma dell'articolo 3?",
    options: [
      "L'uguaglianza davanti alla legge",
      "Il compito della Repubblica di rimuovere gli ostacoli di fatto all'uguaglianza",
      "Il divieto di discriminazione religiosa",
      "La parità fra uomo e donna nel lavoro",
    ],
    answer: 1,
    explanation: "Il primo comma enuncia l'uguaglianza formale, il secondo quella sostanziale: non basta che la legge sia uguale, la Repubblica deve rimuovere gli ostacoli che la rendono ineffettiva. È il comma su cui poggiano le politiche sociali." },
  { id: "cos-7", lesson: "it-costituzione", level: "hard",
    q: "Su quale articolo poggia l'adesione italiana all'Unione europea?",
    options: ["L'articolo 1", "L'articolo 3", "L'articolo 11", "L'articolo 138"],
    answer: 2,
    explanation: "L'articolo 11 consente, in condizioni di parità con gli altri Stati, le limitazioni di sovranità necessarie a un ordinamento che assicuri pace e giustizia. Lo stesso articolo che ripudia la guerra apre all'Europa." },
  { id: "cos-8", lesson: "it-costituzione", level: "easy",
    q: "Che cosa ripudia l'articolo 11?",
    options: ["La pena di morte", "La guerra", "La censura", "Il lavoro minorile"],
    answer: 1,
    explanation: "L'Italia ripudia la guerra come strumento di offesa alla libertà degli altri popoli e come mezzo di risoluzione delle controversie internazionali. La pena di morte è abolita dall'articolo 27." },
  { id: "cos-9", lesson: "it-costituzione", level: "medium",
    q: "Quale articolo disciplina la revisione della Costituzione?",
    options: ["L'articolo 75", "L'articolo 101", "L'articolo 138", "L'articolo 139"],
    answer: 2,
    explanation: "L'articolo 138 detta la procedura aggravata; il 139 pone il limite invalicabile della forma repubblicana. Il 75 riguarda invece il referendum abrogativo." },
  { id: "cos-10", lesson: "it-costituzione", level: "hard",
    q: "Quando può essere chiesto il referendum confermativo su una legge costituzionale?",
    options: [
      "Sempre, dopo l'approvazione",
      "Solo se nella seconda votazione non si raggiungono i due terzi",
      "Solo se lo chiede il Presidente della Repubblica",
      "Mai: le leggi costituzionali non sono referendabili",
    ],
    answer: 1,
    explanation: "Se ciascuna Camera approva con almeno i due terzi, la legge è definitiva. Sotto quella soglia, cinquecentomila elettori, cinque consigli regionali o un quinto dei parlamentari possono chiedere il referendum." },
  { id: "cos-11", lesson: "it-costituzione", level: "hard",
    q: "Il referendum confermativo dell'articolo 138 è valido solo se vota la maggioranza degli aventi diritto?",
    options: [
      "Sì, come tutti i referendum",
      "No, non ha quorum di partecipazione",
      "Sì, ma solo per le riforme della Parte II",
      "Dipende dal numero di firme raccolte",
    ],
    answer: 1,
    explanation: "Il confermativo non ha quorum: vale qualunque sia l'affluenza. Il quorum di metà più uno degli aventi diritto riguarda il referendum abrogativo dell'articolo 75." },
  { id: "cos-12", lesson: "it-costituzione", level: "easy",
    q: "Quali articoli formano la Parte II, sull'ordinamento della Repubblica?",
    options: ["Dall'1 al 12", "Dal 13 al 54", "Dal 55 al 139", "Dal 100 al 139"],
    answer: 2,
    explanation: "Principi fondamentali 1–12, Parte I sui diritti e doveri 13–54, Parte II sull'ordinamento 55–139." },
  { id: "cos-13", lesson: "it-costituzione", level: "medium",
    q: "Quando l'Assemblea costituente approvò il testo della Costituzione?",
    options: ["Il 2 giugno 1946", "Il 22 dicembre 1947", "Il 1º gennaio 1948", "Il 18 aprile 1948"],
    answer: 1,
    explanation: "Approvazione il 22 dicembre 1947, promulgazione il 27 dicembre, entrata in vigore il 1º gennaio 1948. Il 18 aprile 1948 sono invece le prime elezioni politiche repubblicane." },

  // ── Diritti e doveri dei cittadini ─────────────────────────────────────
  { id: "dir-1", lesson: "it-diritti-doveri", level: "easy",
    q: "Quali articoli formano la Parte I, sui diritti e doveri?",
    options: ["Dall'1 al 12", "Dal 13 al 54", "Dal 55 al 96", "Dal 101 al 139"],
    answer: 1,
    explanation: "La Parte I va dall'articolo 13 al 54 ed è divisa in quattro titoli: rapporti civili, etico-sociali, economici e politici." },
  { id: "dir-2", lesson: "it-diritti-doveri", level: "medium",
    q: "In quanti titoli è divisa la Parte I della Costituzione?",
    options: ["Due", "Tre", "Quattro", "Sei"],
    answer: 2,
    explanation: "Quattro: rapporti civili, rapporti etico-sociali, rapporti economici e rapporti politici. Ogni titolo guarda la persona da un lato diverso." },
  { id: "dir-3", lesson: "it-diritti-doveri", level: "medium",
    q: "Quale articolo esclude la pena di morte?",
    options: ["L'articolo 13", "L'articolo 21", "L'articolo 24", "L'articolo 27"],
    answer: 3,
    explanation: "L'articolo 27 chiude affermando che non è ammessa la pena di morte, dopo aver stabilito la personalità della responsabilità penale e il fine rieducativo della pena." },
  { id: "dir-4", lesson: "it-diritti-doveri", level: "hard",
    q: "Quale principio NON è contenuto nell'articolo 27?",
    options: [
      "La responsabilità penale è personale",
      "L'imputato non è considerato colpevole fino alla condanna definitiva",
      "Le pene devono tendere alla rieducazione",
      "Nessuno può essere distolto dal giudice naturale",
    ],
    answer: 3,
    explanation: "Il giudice naturale è garantito dall'articolo 25. L'articolo 27 riunisce personalità della responsabilità, presunzione di non colpevolezza, fine rieducativo della pena e divieto della pena di morte." },
  { id: "dir-5", lesson: "it-diritti-doveri", level: "medium",
    q: "Che cosa garantisce l'articolo 21?",
    options: [
      "La libertà di riunione",
      "La libertà di manifestare il proprio pensiero",
      "La libertà di associazione",
      "La libertà religiosa",
    ],
    answer: 1,
    explanation: "L'articolo 21 riguarda la manifestazione del pensiero con la parola, lo scritto e ogni mezzo di diffusione. Riunione è l'articolo 17, associazione il 18, religione il 19." },
  { id: "dir-6", lesson: "it-diritti-doveri", level: "medium",
    q: "La stampa può essere sottoposta ad autorizzazioni o censure?",
    options: [
      "Sì, in caso di emergenza nazionale",
      "No, l'articolo 21 lo esclude",
      "Sì, se lo decide il Ministero dell'interno",
      "Solo per le pubblicazioni straniere",
    ],
    answer: 1,
    explanation: "L'articolo 21 esclude autorizzazioni e censure: è una frase scritta da chi aveva appena vissuto vent'anni di giornali autorizzati. Restano possibili i sequestri per atto motivato dell'autorità giudiziaria." },
  { id: "dir-7", lesson: "it-diritti-doveri", level: "easy",
    q: "Quale articolo tutela la salute come diritto dell'individuo?",
    options: ["L'articolo 29", "L'articolo 32", "L'articolo 34", "L'articolo 38"],
    answer: 1,
    explanation: "L'articolo 32 definisce la salute diritto dell'individuo e interesse della collettività, e garantisce cure gratuite agli indigenti. È la base del Servizio sanitario nazionale." },
  { id: "dir-8", lesson: "it-diritti-doveri", level: "medium",
    q: "Che cos'è il patrocinio a spese dello Stato?",
    options: [
      "Un contributo per le spese processuali di chi non può permettersele",
      "Un fondo per le vittime di reato",
      "Un'assicurazione obbligatoria per gli avvocati",
      "Un sussidio per i detenuti",
    ],
    answer: 0,
    explanation: "Nasce dall'articolo 24, che impone allo Stato di assicurare ai non abbienti i mezzi per agire e difendersi davanti a ogni giurisdizione." },
  { id: "dir-9", lesson: "it-diritti-doveri", level: "medium",
    q: "Quale articolo riconosce il diritto di sciopero?",
    options: ["L'articolo 35", "L'articolo 39", "L'articolo 40", "L'articolo 46"],
    answer: 2,
    explanation: "L'articolo 40 riconosce il diritto di sciopero, che si esercita nell'ambito delle leggi che lo regolano. L'articolo 39 riguarda invece la libertà sindacale." },
  { id: "dir-10", lesson: "it-diritti-doveri", level: "hard",
    q: "Chi non vota alle elezioni politiche che conseguenza subisce?",
    options: [
      "Una sanzione amministrativa",
      "Nessuna: il dovere civico non è sanzionato",
      "La sospensione dei diritti politici",
      "L'esclusione dai concorsi pubblici",
    ],
    answer: 1,
    explanation: "L'articolo 48 chiama il voto dovere civico, ma non prevede sanzioni. Dovere civico indica un obbligo morale e politico, non un obbligo giuridico assistito da pena." },
  { id: "dir-11", lesson: "it-diritti-doveri", level: "medium",
    q: "Quale articolo impone fedeltà alla Repubblica e l'osservanza della Costituzione?",
    options: ["L'articolo 48", "L'articolo 52", "L'articolo 53", "L'articolo 54"],
    answer: 3,
    explanation: "L'articolo 54 chiede a tutti fedeltà alla Repubblica e, a chi ricopre funzioni pubbliche, di adempierle con disciplina e onore." },
  { id: "dir-12", lesson: "it-diritti-doveri", level: "hard",
    q: "Le garanzie dell'articolo 13 sulla libertà personale valgono solo per i cittadini italiani?",
    options: [
      "Sì, solo per i cittadini",
      "No, l'articolo dice nessuno e vale per chiunque",
      "Solo per i cittadini dell'Unione europea",
      "Solo per chi ha la residenza",
    ],
    answer: 1,
    explanation: "L'articolo 13 usa la parola nessuno e l'articolo 21 la parola tutti: sono garanzie riferite alla persona. Riservati ai cittadini sono soprattutto i diritti politici, come il voto." },
  { id: "dir-13", lesson: "it-diritti-doveri", level: "easy",
    q: "Quale articolo definisce sacro dovere la difesa della patria?",
    options: ["L'articolo 48", "L'articolo 52", "L'articolo 53", "L'articolo 11"],
    answer: 1,
    explanation: "L'articolo 52. Il 48 riguarda il voto, il 53 i tributi e l'11 il ripudio della guerra: quattro articoli che si citano spesso insieme e si confondono facilmente." },

  // ── La lingua italiana e le minoranze linguistiche ─────────────────────
  { id: "lin-1", lesson: "it-lingue", level: "easy",
    q: "Quale articolo della Costituzione tutela le minoranze linguistiche?",
    options: ["L'articolo 3", "L'articolo 6", "L'articolo 9", "L'articolo 12"],
    answer: 1,
    explanation: "L'articolo 6 impegna la Repubblica a tutelare con apposite norme le minoranze linguistiche. L'attuazione arriverà però solo con la legge 482 del 1999." },
  { id: "lin-2", lesson: "it-lingue", level: "medium",
    q: "Quante minoranze linguistiche storiche riconosce la legge del 1999?",
    options: ["Sei", "Nove", "Dodici", "Venti"],
    answer: 2,
    explanation: "Dodici: albanesi, catalane, germaniche, greche, slovene, croate, e le popolazioni parlanti francese, franco-provenzale, friulano, ladino, occitano e sardo." },
  { id: "lin-3", lesson: "it-lingue", level: "medium",
    q: "In quale regione il tedesco è equiparato all'italiano?",
    options: ["In Friuli Venezia Giulia", "In Trentino-Alto Adige", "In Valle d'Aosta", "In Veneto"],
    answer: 1,
    explanation: "In Alto Adige il tedesco è equiparato all'italiano: atti bilingui, scuole distinte per gruppo linguistico e proporzionale etnica per i posti pubblici." },
  { id: "lin-4", lesson: "it-lingue", level: "medium",
    q: "In che anno fu fondata l'Accademia della Crusca?",
    options: ["Nel 1321", "Nel 1583", "Nel 1861", "Nel 1948"],
    answer: 1,
    explanation: "Fondata a Firenze nel 1583, è la più antica accademia linguistica del mondo ancora attiva." },
  { id: "lin-5", lesson: "it-lingue", level: "hard",
    q: "Perché il napoletano non è considerato una variante dell'italiano?",
    options: [
      "Perché ha un alfabeto diverso",
      "Perché discende dal latino per conto proprio, come lingua romanza sorella",
      "Perché è parlato solo in una città",
      "Perché non ha una tradizione scritta",
    ],
    answer: 1,
    explanation: "I cosiddetti dialetti italiani in genere non derivano dall'italiano: derivano dal latino in parallelo. Il napoletano ha inoltre una lunga tradizione scritta e letteraria." },
  { id: "lin-6", lesson: "it-lingue", level: "medium",
    q: "Quale studioso propose la stima più citata sugli italofoni al momento dell'Unità?",
    options: ["Benedetto Croce", "Tullio De Mauro", "Antonio Gramsci", "Bruno Migliorini"],
    answer: 1,
    explanation: "La stima di poco più del due per cento è di Tullio De Mauro. Altri studiosi propongono percentuali più alte, comunque lontane dalla maggioranza della popolazione." },
  { id: "lin-7", lesson: "it-lingue", level: "hard",
    q: "Che cos'è la proporzionale etnica in Alto Adige?",
    options: [
      "Una ripartizione dei posti nel pubblico impiego fra i gruppi linguistici",
      "Un sistema elettorale riservato alle minoranze",
      "Una quota di studenti stranieri per classe",
      "Una divisione del bilancio provinciale fra i comuni",
    ],
    answer: 0,
    explanation: "I posti nel pubblico impiego sono ripartiti fra gruppo italiano, tedesco e ladino in proporzione alla loro consistenza, dichiarata al censimento." },
  { id: "lin-8", lesson: "it-lingue", level: "medium",
    q: "Quali lingue minoritarie sono tutelate in Friuli Venezia Giulia?",
    options: ["Il tedesco e il ladino", "Lo sloveno e il friulano", "Il croato e l'albanese", "L'occitano e il sardo"],
    answer: 1,
    explanation: "Lo sloveno nelle province di Trieste, Gorizia e Udine, e il friulano, parlato da alcune centinaia di migliaia di persone." },
  { id: "lin-9", lesson: "it-lingue", level: "easy",
    q: "Da quale città viene il modello su cui si è formato l'italiano standard?",
    options: ["Roma", "Firenze", "Milano", "Venezia"],
    answer: 1,
    explanation: "Il fiorentino letterario del Trecento, quello di Dante, Petrarca e Boccaccio, fu adottato nel Cinquecento come modello scritto per tutta la penisola." },
  { id: "lin-10", lesson: "it-lingue", level: "medium",
    q: "Quale mezzo contribuì più di ogni altro a diffondere l'italiano parlato nel dopoguerra?",
    options: ["Il cinema", "La televisione", "La radio a galena", "I giornali"],
    answer: 1,
    explanation: "Negli anni Cinquanta e Sessanta la televisione portò l'italiano nelle case di chi parlava solo dialetto, insieme alla scuola dell'obbligo e all'emigrazione interna." },
  { id: "lin-11", lesson: "it-lingue", level: "hard",
    q: "Da dove viene il nome dell'Accademia della Crusca?",
    options: [
      "Dal quartiere fiorentino in cui nacque",
      "Dall'immagine della farina separata dalla crusca",
      "Dal cognome del fondatore",
      "Da un'antica corporazione di fornai",
    ],
    answer: 1,
    explanation: "Il nome richiama il lavoro di separare la farina buona dalla crusca: separare le parole da accogliere da quelle da scartare." },
  { id: "lin-12", lesson: "it-lingue", level: "medium",
    q: "In quale regione si parlano, oltre al francese, varietà germaniche walser?",
    options: ["In Valle d'Aosta", "In Liguria", "In Emilia-Romagna", "In Calabria"],
    answer: 0,
    explanation: "Le comunità walser vivono nelle valli alpine della Valle d'Aosta e del Piemonte. In Valle d'Aosta convivono quindi italiano, francese e parlate germaniche." },
  { id: "lin-13", lesson: "it-lingue", level: "hard",
    q: "L'italiano è dichiarato lingua ufficiale nei principi fondamentali della Costituzione?",
    options: [
      "Sì, all'articolo 6",
      "Sì, all'articolo 12",
      "No: lo si ricava dallo statuto del Trentino-Alto Adige e dalla legge 482",
      "No: non è lingua ufficiale in nessun testo",
    ],
    answer: 2,
    explanation: "La Costituzione non lo dice. L'italiano è indicato come lingua ufficiale nello statuto speciale del Trentino-Alto Adige e nella legge 482 del 1999: una cosa ovvia che non sta dove ci si aspetta." },

  // ── Feste civili e religiose ───────────────────────────────────────────
  { id: "fes-1", lesson: "it-feste", level: "easy",
    q: "Quanti sono i giorni festivi nazionali, oltre al patrono locale?",
    options: ["Otto", "Dieci", "Dodici", "Quindici"],
    answer: 2,
    explanation: "Dodici giorni festivi per legge, più il santo patrono, che è festivo soltanto nel proprio comune." },
  { id: "fes-2", lesson: "it-feste", level: "medium",
    q: "Quando si celebra il patrono di Milano?",
    options: ["Il 19 settembre", "Il 4 ottobre", "Il 7 dicembre", "Il 29 giugno"],
    answer: 2,
    explanation: "Sant'Ambrogio si celebra il 7 dicembre: a Milano è giorno festivo e apre la stagione della Scala. Il 19 settembre è san Gennaro a Napoli." },
  { id: "fes-3", lesson: "it-feste", level: "medium",
    q: "Chi è il patrono di Napoli?",
    options: ["San Petronio", "San Gennaro", "San Marco", "Santa Rosalia"],
    answer: 1,
    explanation: "San Gennaro, celebrato il 19 settembre. San Petronio è di Bologna, san Marco di Venezia e santa Rosalia di Palermo." },
  { id: "fes-4", lesson: "it-feste", level: "easy",
    q: "Che cosa si celebra il 1º maggio?",
    options: ["La Liberazione", "La festa dei lavoratori", "La festa della Repubblica", "L'Unità nazionale"],
    answer: 1,
    explanation: "Il 1º maggio è la festa dei lavoratori, una delle quattro ricorrenze civili del calendario italiano." },
  { id: "fes-5", lesson: "it-feste", level: "medium",
    q: "Quando si celebrano i santi Pietro e Paolo, patroni di Roma?",
    options: ["Il 21 aprile", "Il 29 giugno", "Il 4 ottobre", "Il 1º novembre"],
    answer: 1,
    explanation: "Il 29 giugno, giorno festivo soltanto a Roma. Il 21 aprile è invece il Natale di Roma, che non è festivo." },
  { id: "fes-6", lesson: "it-feste", level: "hard",
    q: "Il giorno del patrono è festivo in tutta Italia?",
    options: [
      "Sì, come le altre dodici feste",
      "No, soltanto nel comune di cui è patrono",
      "Sì, ma solo nei capoluoghi di regione",
      "No, non è mai festivo per legge",
    ],
    answer: 1,
    explanation: "È festivo solo nel proprio comune: un ufficio milanese chiude il 7 dicembre, mentre a Roma lo stesso giorno si lavora normalmente." },
  { id: "fes-7", lesson: "it-feste", level: "medium",
    q: "Con quale nome è comunemente conosciuto il Lunedì dell'Angelo?",
    options: ["Pasquetta", "Carnevale", "Befana", "Ferragosto"],
    answer: 0,
    explanation: "Il lunedì dopo Pasqua si chiama ufficialmente Lunedì dell'Angelo e comunemente Pasquetta. È una festa mobile, come la Pasqua da cui dipende." },
  { id: "fes-8", lesson: "it-feste", level: "medium",
    q: "Che cosa si ricorda il 10 febbraio?",
    options: [
      "Le vittime della Shoah",
      "Le vittime delle foibe e l'esodo giuliano-dalmata",
      "Le vittime del terrorismo",
      "I caduti della Grande guerra",
    ],
    answer: 1,
    explanation: "Il Giorno del Ricordo, istituito per le vittime delle foibe e per l'esodo delle popolazioni istriane, fiumane e dalmate." },
  { id: "fes-9", lesson: "it-feste", level: "hard",
    q: "A quale fatto del 1978 è legata la data del 9 maggio?",
    options: [
      "Alla strage di piazza Fontana",
      "Al ritrovamento del corpo di Aldo Moro",
      "All'attentato di via Fani",
      "Alla strage di Bologna",
    ],
    answer: 1,
    explanation: "Il 9 maggio 1978 fu ritrovato il corpo di Aldo Moro. Quella data è oggi il Giorno della memoria delle vittime del terrorismo. Il rapimento in via Fani era avvenuto il 16 marzo." },
  { id: "fes-10", lesson: "it-feste", level: "easy",
    q: "Quale festa cade il 26 dicembre?",
    options: ["L'Immacolata", "Santo Stefano", "L'Epifania", "Ognissanti"],
    answer: 1,
    explanation: "Santo Stefano, il giorno dopo Natale. L'Immacolata è l'8 dicembre, l'Epifania il 6 gennaio e Ognissanti il 1º novembre." },
  { id: "fes-11", lesson: "it-feste", level: "medium",
    q: "Quando cade l'Immacolata Concezione?",
    options: ["Il 1º novembre", "Il 6 dicembre", "L'8 dicembre", "Il 6 gennaio"],
    answer: 2,
    explanation: "L'8 dicembre. In molte case è il giorno in cui si fa l'albero di Natale, e a Roma il papa rende omaggio alla colonna di piazza di Spagna." },
  { id: "fes-12", lesson: "it-feste", level: "hard",
    q: "Da che cosa dipende la data della Pasqua?",
    options: [
      "Da una data fissa stabilita nel Concilio di Trento",
      "Dal primo plenilunio di primavera",
      "Dal calendario civile dello Stato",
      "Dall'inizio della Quaresima, fissato al 1º marzo",
    ],
    answer: 1,
    explanation: "La Pasqua cade la domenica successiva al primo plenilunio dopo l'equinozio di primavera. Da lei dipendono a cascata Carnevale, Quaresima e Pasquetta." },
  { id: "fes-13", lesson: "it-feste", level: "medium",
    q: "Che cosa porta la Befana la notte del 6 gennaio?",
    options: [
      "I doni ai bambini, e carbone di zucchero a chi non è stato buono",
      "Le uova di cioccolato",
      "I dolci del Carnevale",
      "I regali ai soli adulti",
    ],
    answer: 0,
    explanation: "La Befana riempie le calze la notte dell'Epifania. Non è festa religiosa nel senso stretto: è una tradizione popolare che si è appoggiata alla data del 6 gennaio." },
  // ── Il Parlamento ──────────────────────────────────────────────────────
  { id: "par-1", lesson: "it-parlamento", level: "easy",
    q: "Quanti sono oggi i senatori elettivi?",
    options: ["Cento", "Duecento", "Trecentoquindici", "Quattrocento"],
    answer: 1,
    explanation: "Duecento dal 2022. Trecentoquindici era il numero precedente e quattrocento è quello dei deputati." },
  { id: "par-2", lesson: "it-parlamento", level: "easy",
    q: "In quale palazzo si riunisce la Camera dei deputati?",
    options: ["Palazzo Madama", "Palazzo Chigi", "Palazzo Montecitorio", "Palazzo della Consulta"],
    answer: 2,
    explanation: "Montecitorio è la Camera, Madama il Senato, Chigi il governo e la Consulta la Corte costituzionale: quattro palazzi romani che nei giornali stanno per quattro istituzioni." },
  { id: "par-3", lesson: "it-parlamento", level: "medium",
    q: "In quale palazzo si riunisce il Senato?",
    options: ["Palazzo Madama", "Palazzo Montecitorio", "Palazzo Chigi", "Il Quirinale"],
    answer: 0,
    explanation: "Palazzo Madama, che deve il nome a Margherita d'Austria. Il Quirinale è la residenza del Presidente della Repubblica." },
  { id: "par-4", lesson: "it-parlamento", level: "medium",
    q: "Quanti anni bisogna avere per essere eletti senatori?",
    options: ["Venticinque", "Trenta", "Quaranta", "Cinquanta"],
    answer: 2,
    explanation: "Quaranta per il Senato, venticinque per la Camera. Cinquanta è invece l'età minima per il Presidente della Repubblica." },
  { id: "par-5", lesson: "it-parlamento", level: "medium",
    q: "Quanti anni bisogna avere per essere eletti deputati?",
    options: ["Diciotto", "Ventuno", "Venticinque", "Quaranta"],
    answer: 2,
    explanation: "Venticinque. A diciotto si può votare per entrambe le camere, ma per candidarsi le soglie restano più alte." },
  { id: "par-6", lesson: "it-parlamento", level: "medium",
    q: "Quanti erano deputati e senatori elettivi prima della riforma?",
    options: ["500 e 250", "630 e 315", "700 e 350", "400 e 200"],
    answer: 1,
    explanation: "Seicentotrenta e trecentoquindici, fino alla legislatura iniziata nel 2022. Quattrocento e duecento sono i numeri attuali." },
  { id: "par-7", lesson: "it-parlamento", level: "hard",
    q: "Che cosa si intende per navetta parlamentare?",
    options: [
      "Il passaggio di un testo da una camera all'altra finché non è identico",
      "Il servizio che collega Montecitorio e Palazzo Madama",
      "La sessione notturna di approvazione del bilancio",
      "Il voto di fiducia ripetuto due volte",
    ],
    answer: 0,
    explanation: "Una legge deve essere approvata nel medesimo testo da entrambe le camere: se una la modifica, torna all'altra. L'andirivieni può ripetersi molte volte ed è la conseguenza diretta del bicameralismo paritario." },
  { id: "par-8", lesson: "it-parlamento", level: "medium",
    q: "Quanto dura una legislatura?",
    options: ["Quattro anni", "Cinque anni", "Sei anni", "Sette anni"],
    answer: 1,
    explanation: "Cinque anni, salvo scioglimento anticipato. Sette anni è la durata del mandato presidenziale, e in Italia le legislature arrivate a scadenza naturale sono una minoranza." },
  { id: "par-9", lesson: "it-parlamento", level: "hard",
    q: "Quante firme servono per chiedere un referendum abrogativo?",
    options: ["Cinquantamila", "Centomila", "Cinquecentomila", "Un milione"],
    answer: 2,
    explanation: "Cinquecentomila elettori, oppure cinque consigli regionali. Centomila firme servono invece per una proposta di legge di iniziativa popolare." },
  { id: "par-10", lesson: "it-parlamento", level: "hard",
    q: "Quando è valido un referendum abrogativo?",
    options: [
      "Sempre, qualunque sia l'affluenza",
      "Se partecipa la maggioranza degli aventi diritto",
      "Se partecipa un terzo degli aventi diritto",
      "Se lo convalida la Corte costituzionale dopo il voto",
    ],
    answer: 1,
    explanation: "Serve il quorum di metà più uno degli aventi diritto. Molti referendum sono falliti non perché il no abbia vinto, ma perché non ci si è presentati: astenersi è un modo di far cadere la consultazione." },
  { id: "par-11", lesson: "it-parlamento", level: "medium",
    q: "Quale di queste materie NON può essere sottoposta a referendum abrogativo?",
    options: ["Il diritto di famiglia", "L'energia nucleare", "Le leggi tributarie e di bilancio", "La legge elettorale"],
    answer: 2,
    explanation: "L'articolo 75 esclude leggi tributarie e di bilancio, amnistia e indulto, e la ratifica dei trattati internazionali. Divorzio, aborto e nucleare sono invece stati tutti oggetto di referendum." },
  { id: "par-12", lesson: "it-parlamento", level: "easy",
    q: "A quale età si vota oggi per il Senato?",
    options: ["Diciotto anni", "Ventun anni", "Venticinque anni", "Trent'anni"],
    answer: 0,
    explanation: "Diciotto, dalla legge costituzionale del 2021. Prima il Senato si eleggeva dai venticinque anni in su, e i più giovani avevano in mano una scheda sola." },
  { id: "par-13", lesson: "it-parlamento", level: "hard",
    q: "Quanti senatori a vita può nominare il Presidente della Repubblica?",
    options: ["Nessuno", "Fino a tre", "Fino a cinque", "Senza limite"],
    answer: 2,
    explanation: "Fino a cinque, per altissimi meriti nel campo sociale, scientifico, artistico o letterario. Gli ex Presidenti della Repubblica non rientrano in questo numero: lo sono di diritto." },

  // ── Il Governo ─────────────────────────────────────────────────────────
  { id: "gov-1", lesson: "it-governo", level: "easy",
    q: "Dove ha sede il governo italiano?",
    options: ["Al Quirinale", "A Palazzo Chigi", "A Palazzo Madama", "A Montecitorio"],
    answer: 1,
    explanation: "Palazzo Chigi. Il Quirinale è del Presidente della Repubblica: due palazzi a pochi minuti a piedi e due poteri distinti." },
  { id: "gov-2", lesson: "it-governo", level: "medium",
    q: "Che cosa sono le consultazioni?",
    options: [
      "I sondaggi commissionati dai partiti prima del voto",
      "Gli incontri del Presidente della Repubblica con i gruppi parlamentari",
      "Le riunioni del Consiglio dei ministri",
      "Le audizioni dei ministri in commissione",
    ],
    answer: 1,
    explanation: "Prima di nominare un Presidente del Consiglio, il capo dello Stato riceve i gruppi per capire chi possa raccogliere una maggioranza. Non sono previste nel dettaglio dalla Costituzione: sono una prassi consolidata." },
  { id: "gov-3", lesson: "it-governo", level: "medium",
    q: "Entro quanti giorni dalla formazione il governo si presenta per la fiducia?",
    options: ["Tre", "Dieci", "Trenta", "Sessanta"],
    answer: 1,
    explanation: "Dieci giorni, secondo l'articolo 94. Sessanta è il termine di conversione dei decreti legge e tre il tempo minimo prima di discutere una mozione di sfiducia." },
  { id: "gov-4", lesson: "it-governo", level: "hard",
    q: "Da quante camere deve ottenere la fiducia un governo?",
    options: [
      "Solo dalla Camera dei deputati",
      "Solo dal Senato",
      "Da entrambe",
      "Da una qualsiasi delle due, a scelta del Presidente del Consiglio",
    ],
    answer: 2,
    explanation: "Da entrambe, ed è una conseguenza del bicameralismo paritario. Un governo che ha i numeri alla Camera ma non al Senato non può esistere: è la ragione per cui le maggioranze italiane sono spesso larghe e fragili." },
  { id: "gov-5", lesson: "it-governo", level: "medium",
    q: "Quale articolo consente al governo il decreto legge?",
    options: ["L'articolo 75", "L'articolo 76", "L'articolo 77", "L'articolo 92"],
    answer: 2,
    explanation: "L'articolo 77, per casi straordinari di necessità e urgenza. Il 76 riguarda il decreto legislativo su delega, il 75 il referendum abrogativo e il 92 la nomina del governo." },
  { id: "gov-6", lesson: "it-governo", level: "medium",
    q: "Che cos'è un decreto legislativo?",
    options: [
      "Una norma scritta dal governo su delega del Parlamento",
      "Una norma d'urgenza che vale subito",
      "Un regolamento di attuazione di una legge",
      "Una legge approvata da una sola camera",
    ],
    answer: 0,
    explanation: "Il Parlamento delega, fissando principi, criteri e un termine; il governo scrive il testo. Serve per normative lunghe e tecniche come i codici. Il decreto legge, invece, nasce dall'urgenza e non da una delega." },
  { id: "gov-7", lesson: "it-governo", level: "hard",
    q: "Chi propone al Presidente della Repubblica i nomi dei ministri?",
    options: [
      "I segretari dei partiti di maggioranza",
      "Il Presidente del Consiglio incaricato",
      "Il presidente della Camera",
      "Nessuno: li sceglie il Presidente della Repubblica da solo",
    ],
    answer: 1,
    explanation: "L'articolo 92 dice che il Presidente della Repubblica nomina i ministri su proposta del Presidente del Consiglio. La proposta è dell'uno, la nomina dell'altro: nessuno dei due decide da solo." },
  { id: "gov-8", lesson: "it-governo", level: "medium",
    q: "Da quanti parlamentari deve essere firmata una mozione di sfiducia?",
    options: ["Da dieci", "Da un decimo dei componenti della camera", "Da un quarto", "Dalla maggioranza assoluta"],
    answer: 1,
    explanation: "Un decimo dei componenti. La soglia è bassa di proposito: presentare la mozione deve essere possibile, approvarla è un'altra cosa." },
  { id: "gov-9", lesson: "it-governo", level: "hard",
    q: "Dopo quanto tempo dalla presentazione può essere discussa una mozione di sfiducia?",
    options: ["Subito", "Non prima di tre giorni", "Non prima di dieci giorni", "Non prima di un mese"],
    answer: 1,
    explanation: "Tre giorni almeno. L'attesa serve a raffreddare gli animi e a dare tempo al governo di cercare i voti che gli mancano." },
  { id: "gov-10", lesson: "it-governo", level: "easy",
    q: "Chi compone il Consiglio dei ministri?",
    options: [
      "Il Presidente del Consiglio e i ministri",
      "Il Presidente della Repubblica e i ministri",
      "I capigruppo parlamentari",
      "I presidenti delle regioni",
    ],
    answer: 0,
    explanation: "Il Presidente del Consiglio e i ministri insieme formano il Consiglio dei ministri, che è l'organo collegiale del governo." },
  { id: "gov-11", lesson: "it-governo", level: "hard",
    q: "In che modo cadono di solito i governi italiani?",
    options: [
      "Con un voto di sfiducia in aula",
      "Per dimissioni del Presidente del Consiglio",
      "Per decisione del Presidente della Repubblica",
      "Alla scadenza naturale dei cinque anni",
    ],
    answer: 1,
    explanation: "Quasi sempre per dimissioni: un partito lascia la maggioranza e il Presidente del Consiglio sale al Quirinale prima di essere messo in minoranza. Le mozioni di sfiducia approvate si contano sulle dita." },
  { id: "gov-12", lesson: "it-governo", level: "medium",
    q: "Un regolamento del governo può contraddire una legge?",
    options: [
      "Sì, se è più recente",
      "No: attua la legge e non può andarle contro",
      "Sì, in caso di urgenza",
      "Solo con il parere della Corte costituzionale",
    ],
    answer: 1,
    explanation: "Il regolamento sta sotto la legge nella gerarchia delle fonti: ne detta i dettagli attuativi e non può contraddirla. Per fare qualcosa con forza di legge servono il decreto legge o il decreto legislativo." },
  { id: "gov-13", lesson: "it-governo", level: "easy",
    q: "Quale palazzo è la residenza del Presidente della Repubblica?",
    options: ["Palazzo Chigi", "Il Quirinale", "Palazzo Madama", "Il Viminale"],
    answer: 1,
    explanation: "Il Quirinale, che fu dei papi e poi dei re. Il Viminale è il Ministero dell'interno, un altro nome di palazzo che nei giornali sostituisce l'istituzione." },

  // ── Il Presidente della Repubblica ─────────────────────────────────────
  { id: "pre-1", lesson: "it-presidente", level: "easy",
    q: "Qual è l'età minima per essere eletti Presidente della Repubblica?",
    options: ["Quaranta anni", "Quarantacinque anni", "Cinquant'anni", "Sessant'anni"],
    answer: 2,
    explanation: "Cinquant'anni, oltre alla cittadinanza italiana e al godimento dei diritti civili e politici. Quaranta è l'età minima per il Senato." },
  { id: "pre-2", lesson: "it-presidente", level: "medium",
    q: "Quanti delegati regionali partecipano all'elezione del Presidente?",
    options: ["Venti", "Cinquantotto", "Sessanta", "Cento"],
    answer: 1,
    explanation: "Cinquantotto: tre per ogni regione e uno soltanto per la Valle d'Aosta. Si aggiungono ai deputati e ai senatori riuniti in seduta comune." },
  { id: "pre-3", lesson: "it-presidente", level: "hard",
    q: "Quanti delegati esprime la Valle d'Aosta all'elezione presidenziale?",
    options: ["Nessuno", "Uno", "Due", "Tre come tutte le altre"],
    answer: 1,
    explanation: "Uno solo: è l'eccezione prevista proprio per la sua dimensione. Tutte le altre diciannove regioni ne esprimono tre." },
  { id: "pre-4", lesson: "it-presidente", level: "medium",
    q: "Quale maggioranza serve nei primi tre scrutini per eleggere il Presidente?",
    options: ["La maggioranza semplice", "La maggioranza assoluta", "I due terzi", "L'unanimità"],
    answer: 2,
    explanation: "Due terzi dell'assemblea nei primi tre scrutini; dal quarto basta la maggioranza assoluta. La soglia alta all'inizio spinge a cercare un nome largamente condiviso." },
  { id: "pre-5", lesson: "it-presidente", level: "medium",
    q: "Che maggioranza basta dal quarto scrutinio in poi?",
    options: ["La maggioranza assoluta", "I due terzi", "I tre quinti", "La maggioranza dei presenti"],
    answer: 0,
    explanation: "La maggioranza assoluta dei componenti. È il momento in cui l'elezione diventa possibile per una coalizione senza bisogno dell'opposizione." },
  { id: "pre-6", lesson: "it-presidente", level: "hard",
    q: "Chi sono i franchi tiratori in un'elezione presidenziale?",
    options: [
      "I delegati regionali che votano per ultimi",
      "I parlamentari che votano diversamente da quanto indicato dal proprio gruppo",
      "I senatori a vita",
      "Gli scrutatori incaricati dello spoglio",
    ],
    answer: 1,
    explanation: "Il voto è segreto, e la segretezza permette di disobbedire al gruppo senza che si sappia chi è stato. Alcune elezioni sono naufragate proprio su questo, richiedendo decine di scrutini." },
  { id: "pre-7", lesson: "it-presidente", level: "medium",
    q: "Chi presiede il Consiglio superiore della magistratura?",
    options: [
      "Il ministro della Giustizia",
      "Il primo presidente della Cassazione",
      "Il Presidente della Repubblica",
      "Il presidente della Corte costituzionale",
    ],
    answer: 2,
    explanation: "Lo presiede il capo dello Stato, come garanzia di indipendenza. Il primo presidente della Cassazione e il procuratore generale ne fanno parte di diritto, e il ministro della Giustizia non ne fa parte affatto." },
  { id: "pre-8", lesson: "it-presidente", level: "medium",
    q: "Quanti giudici costituzionali nomina il Presidente della Repubblica?",
    options: ["Tre", "Cinque", "Sette", "Quindici"],
    answer: 1,
    explanation: "Cinque su quindici. Altri cinque li elegge il Parlamento in seduta comune e cinque vengono dalle supreme magistrature." },
  { id: "pre-9", lesson: "it-presidente", level: "hard",
    q: "Per quali atti il Presidente della Repubblica può essere chiamato a rispondere?",
    options: [
      "Per qualsiasi reato, come ogni cittadino",
      "Per alto tradimento e attentato alla Costituzione",
      "Per le leggi che promulga",
      "Per nessun atto, in nessun caso",
    ],
    answer: 1,
    explanation: "Solo per questi due. Per il resto degli atti compiuti nell'esercizio delle funzioni non è responsabile: risponde il ministro che li controfirma." },
  { id: "pre-10", lesson: "it-presidente", level: "medium",
    q: "A che cosa serve la controfirma ministeriale?",
    options: [
      "A certificare la firma del Presidente",
      "A far assumere al ministro la responsabilità dell'atto",
      "A rendere l'atto immediatamente esecutivo",
      "A trasmettere l'atto alla Corte costituzionale",
    ],
    answer: 1,
    explanation: "L'articolo 89 lega ogni atto presidenziale alla firma del ministro proponente, che se ne assume la responsabilità. È il modo di conciliare un capo dello Stato irresponsabile con un sistema in cui qualcuno deve rispondere." },
  { id: "pre-11", lesson: "it-presidente", level: "easy",
    q: "Quale di questi poteri spetta al Presidente della Repubblica?",
    options: ["Approvare il bilancio", "Concedere la grazia", "Nominare i sindaci", "Fissare le aliquote fiscali"],
    answer: 1,
    explanation: "La grazia è un potere presidenziale. Bilancio e tasse spettano al Parlamento e al governo, e i sindaci li eleggono i cittadini." },
  { id: "pre-12", lesson: "it-presidente", level: "hard",
    q: "Chi giudica il Presidente messo in stato d'accusa?",
    options: [
      "La Corte di cassazione",
      "Il Parlamento in seduta comune",
      "La Corte costituzionale integrata da sedici membri esterni",
      "Un tribunale ordinario di Roma",
    ],
    answer: 2,
    explanation: "La Corte costituzionale, allargata a sedici giudici aggregati sorteggiati da un elenco di cittadini. Il Parlamento in seduta comune mette in stato d'accusa, ma non giudica." },
  { id: "pre-13", lesson: "it-presidente", level: "medium",
    q: "Chi mette il Presidente in stato d'accusa?",
    options: [
      "Il Parlamento in seduta comune",
      "La sola Camera dei deputati",
      "Il Consiglio dei ministri",
      "La Corte costituzionale d'ufficio",
    ],
    answer: 0,
    explanation: "Il Parlamento in seduta comune, a maggioranza assoluta. Poi il giudizio passa alla Corte costituzionale nella sua composizione allargata." },

  // ── La giustizia e la Corte costituzionale ─────────────────────────────
  { id: "giu-1", lesson: "it-giustizia", level: "easy",
    q: "Quale articolo dichiara la magistratura autonoma e indipendente?",
    options: ["L'articolo 24", "L'articolo 101", "L'articolo 104", "L'articolo 112"],
    answer: 2,
    explanation: "L'articolo 104. Il 101 stabilisce che i giudici sono soggetti soltanto alla legge, il 112 l'obbligatorietà dell'azione penale e il 24 il diritto di difesa." },
  { id: "giu-2", lesson: "it-giustizia", level: "medium",
    q: "A che cosa sono soggetti i giudici secondo la Costituzione?",
    options: [
      "Al ministro della Giustizia",
      "Soltanto alla legge",
      "Alle direttive del CSM",
      "Al Presidente della Repubblica",
    ],
    answer: 1,
    explanation: "Soltanto alla legge, dice l'articolo 101. Il CSM gestisce le carriere ma non può dire a un giudice come decidere, e il ministro non ha alcun potere sulle sentenze." },
  { id: "giu-3", lesson: "it-giustizia", level: "medium",
    q: "Che cosa comporta l'obbligatorietà dell'azione penale?",
    options: [
      "Che il pubblico ministero deve procedere su ogni notizia di reato",
      "Che ogni processo deve concludersi entro un anno",
      "Che l'imputato deve essere sempre difeso da un avvocato",
      "Che ogni condanna prevede il carcere",
    ],
    answer: 0,
    explanation: "Ricevuta una notizia di reato, il pubblico ministero non può scegliere di lasciar perdere. In teoria elimina ogni discrezionalità politica; nella pratica, con più fascicoli che magistrati, la scelta si sposta sull'ordine delle priorità." },
  { id: "giu-4", lesson: "it-giustizia", level: "medium",
    q: "Quale articolo stabilisce l'obbligatorietà dell'azione penale?",
    options: ["L'articolo 27", "L'articolo 101", "L'articolo 104", "L'articolo 112"],
    answer: 3,
    explanation: "L'articolo 112. È uno degli articoli più discussi della Costituzione, perché la sua attuazione dipende da quante risorse ha la giustizia." },
  { id: "giu-5", lesson: "it-giustizia", level: "easy",
    q: "Quanti gradi di giudizio prevede il sistema italiano?",
    options: ["Uno", "Due", "Tre", "Quattro"],
    answer: 2,
    explanation: "Primo grado, appello e Cassazione. I primi due esaminano i fatti, il terzo soltanto la corretta applicazione della legge." },
  { id: "giu-6", lesson: "it-giustizia", level: "hard",
    q: "Quando una sentenza penale diventa definitiva?",
    options: [
      "Alla fine del primo grado",
      "Dopo l'appello",
      "Dopo la pronuncia della Cassazione",
      "Dopo la conferma della Corte costituzionale",
    ],
    answer: 2,
    explanation: "Passa in giudicato dopo la Cassazione. Fino ad allora vale l'articolo 27: l'imputato non è considerato colpevole. La Corte costituzionale non entra nei processi: giudica le leggi." },
  { id: "giu-7", lesson: "it-giustizia", level: "medium",
    q: "Dove ha sede la Corte costituzionale?",
    options: ["A Palazzo della Consulta", "A Palazzo Chigi", "A Palazzo Madama", "Al Quirinale"],
    answer: 0,
    explanation: "Palazzo della Consulta, di fronte al Quirinale. Per questo la Corte viene chiamata semplicemente la Consulta." },
  { id: "giu-8", lesson: "it-giustizia", level: "medium",
    q: "Quanto dura il mandato di un giudice costituzionale?",
    options: ["Cinque anni", "Sette anni", "Nove anni", "A vita"],
    answer: 2,
    explanation: "Nove anni. Più lungo di una legislatura e del mandato presidenziale, così che nessun giudice debba qualcosa a chi lo ha nominato." },
  { id: "giu-9", lesson: "it-giustizia", level: "hard",
    q: "Un giudice costituzionale può essere rinominato alla scadenza?",
    options: [
      "Sì, una volta",
      "Sì, senza limiti",
      "No: il mandato non è rinnovabile",
      "Solo se lo propone il Presidente della Repubblica",
    ],
    answer: 2,
    explanation: "Non è rinnovabile, ed è parte della garanzia: un giudice che non può sperare in un secondo mandato non ha ragione di compiacere chi lo ha scelto." },
  { id: "giu-10", lesson: "it-giustizia", level: "medium",
    q: "Quale di questi compiti NON spetta alla Corte costituzionale?",
    options: [
      "Giudicare la legittimità costituzionale delle leggi",
      "Decidere i conflitti di attribuzione fra Stato e regioni",
      "Giudicare in appello i processi penali",
      "Decidere se un referendum abrogativo è ammissibile",
    ],
    answer: 2,
    explanation: "L'appello spetta alla magistratura ordinaria. La Corte costituzionale giudica leggi, conflitti fra poteri, accuse contro il Presidente e ammissibilità dei referendum: mai un imputato." },
  { id: "giu-11", lesson: "it-giustizia", level: "hard",
    q: "Da quando perde efficacia una legge dichiarata incostituzionale?",
    options: [
      "Dal giorno in cui era stata approvata",
      "Dal giorno successivo alla pubblicazione della sentenza",
      "Dopo un anno, per dare tempo al Parlamento",
      "Solo se il Parlamento la abroga",
    ],
    answer: 1,
    explanation: "Cessa di avere efficacia dal giorno dopo la pubblicazione della decisione. Non serve alcun intervento del Parlamento: la norma esce dall'ordinamento da sola." },
  { id: "giu-12", lesson: "it-giustizia", level: "medium",
    q: "Chi decide trasferimenti, promozioni e provvedimenti disciplinari dei magistrati?",
    options: [
      "Il ministro della Giustizia",
      "Il Consiglio superiore della magistratura",
      "La Corte di cassazione",
      "Il Parlamento",
    ],
    answer: 1,
    explanation: "Il CSM, presieduto dal Presidente della Repubblica. Tenere queste decisioni fuori dal governo è ciò che rende concreta l'indipendenza dell'articolo 104." },
  { id: "giu-13", lesson: "it-giustizia", level: "easy",
    q: "Con quale nome viene comunemente indicata la Corte costituzionale?",
    options: ["La Cassazione", "La Consulta", "Il Viminale", "La Corte dei conti"],
    answer: 1,
    explanation: "La Consulta, dal palazzo che la ospita. La Corte dei conti è un altro organo, che controlla la spesa pubblica." },

  // ── Regioni, province e comuni ─────────────────────────────────────────
  { id: "reg-1", lesson: "it-regioni", level: "easy",
    q: "Quante sono le regioni italiane?",
    options: ["Quindici", "Diciotto", "Venti", "Ventidue"],
    answer: 2,
    explanation: "Venti, di cui cinque a statuto speciale e quindici a statuto ordinario." },
  { id: "reg-2", lesson: "it-regioni", level: "medium",
    q: "In che anno è stato riformato il Titolo V della Costituzione?",
    options: ["Nel 1970", "Nel 1993", "Nel 2001", "Nel 2020"],
    answer: 2,
    explanation: "Nel 2001. La riforma ha ribaltato il criterio delle competenze e ha messo lo Stato per ultimo nell'elenco degli enti della Repubblica." },
  { id: "reg-3", lesson: "it-regioni", level: "hard",
    q: "Dopo la riforma del 2001, a chi spettano le materie non elencate nella Costituzione?",
    options: ["Allo Stato", "Alle regioni", "Ai comuni", "Sono decise di volta in volta dalla Corte costituzionale"],
    answer: 1,
    explanation: "Alle regioni. Prima valeva il criterio opposto: le regioni potevano legiferare solo sulle materie espressamente elencate. Il ribaltamento ha però moltiplicato i conflitti davanti alla Corte." },
  { id: "reg-4", lesson: "it-regioni", level: "medium",
    q: "Quali sono le due province autonome italiane?",
    options: ["Trieste e Gorizia", "Trento e Bolzano", "Aosta e Sondrio", "Cagliari e Sassari"],
    answer: 1,
    explanation: "Trento e Bolzano, che dentro il Trentino-Alto Adige hanno più poteri della regione stessa. È l'assetto nato dalla tutela della minoranza di lingua tedesca." },
  { id: "reg-5", lesson: "it-regioni", level: "medium",
    q: "Quante sono le città metropolitane?",
    options: ["Sei", "Dieci", "Quattordici", "Venti"],
    answer: 2,
    explanation: "Quattordici, istituite dal 2015 al posto delle province nei territori dei grandi capoluoghi. Il sindaco del capoluogo ne è anche sindaco metropolitano." },
  { id: "reg-6", lesson: "it-regioni", level: "hard",
    q: "Perché la Sicilia ha uno statuto speciale?",
    options: [
      "Perché è la regione più popolosa",
      "Perché è un'isola con un forte movimento autonomista nel dopoguerra",
      "Perché ospita una minoranza linguistica riconosciuta",
      "Perché confina con uno Stato estero",
    ],
    answer: 1,
    explanation: "Lo statuto siciliano è del 1946, precedente alla Costituzione stessa: fu concesso mentre il movimento indipendentista era forte. Le altre speciali nascono da minoranze linguistiche o da confini contesi." },
  { id: "reg-7", lesson: "it-regioni", level: "medium",
    q: "Quanti sono all'incirca i comuni italiani?",
    options: ["Ottocento", "Duemila", "Ottomila", "Ventimila"],
    answer: 2,
    explanation: "Circa ottomila, dalle grandi città a paesi di poche decine di abitanti. La frammentazione è tale che da anni si discute di accorpare i più piccoli." },
  { id: "reg-8", lesson: "it-regioni", level: "hard",
    q: "Che cosa comporta la regola per cui consiglio e presidente regionale stanno o cadono insieme?",
    options: [
      "Che il presidente può sciogliere il consiglio quando vuole",
      "Che se il presidente cade, si torna al voto per entrambi",
      "Che il consiglio elegge il presidente fra i propri membri",
      "Che il presidente non può essere sfiduciato",
    ],
    answer: 1,
    explanation: "Dimissioni, sfiducia o impedimento del presidente sciolgono anche il consiglio e portano a nuove elezioni. Serve a evitare che una regione resti anni senza guida mentre si cercano maggioranze in aula." },
  { id: "reg-9", lesson: "it-regioni", level: "medium",
    q: "Il titolo di governatore per il presidente di una regione è ufficiale?",
    options: [
      "Sì, è previsto dalla Costituzione",
      "Sì, dal 2001",
      "No: è un uso giornalistico",
      "Sì, ma solo nelle regioni a statuto speciale",
    ],
    answer: 2,
    explanation: "La Costituzione parla di Presidente della Giunta regionale. Governatore è entrato dall'uso dei giornali, per analogia con gli Stati americani, e non ha alcun valore giuridico." },
  { id: "reg-10", lesson: "it-regioni", level: "easy",
    q: "Chi approva le leggi regionali?",
    options: ["Il consiglio regionale", "La giunta regionale", "Il prefetto", "Il Parlamento nazionale"],
    answer: 0,
    explanation: "Il consiglio regionale legifera, la giunta governa. È la stessa distinzione che a livello nazionale corre fra Parlamento e governo." },
  { id: "reg-11", lesson: "it-regioni", level: "medium",
    q: "Sopra quale soglia di abitanti l'elezione del sindaco prevede il ballottaggio?",
    options: ["Cinquemila", "Quindicimila", "Cinquantamila", "Centomila"],
    answer: 1,
    explanation: "Quindicimila abitanti. Nei comuni più piccoli si vince al primo turno con la maggioranza relativa, senza secondo turno." },
  { id: "reg-12", lesson: "it-regioni", level: "hard",
    q: "Chi rappresenta il governo nazionale in ogni provincia?",
    options: ["Il presidente della provincia", "Il prefetto", "Il questore", "Il sindaco del capoluogo"],
    answer: 1,
    explanation: "Il prefetto, che dipende dal Ministero dell'interno. È lui a ricevere le domande di cittadinanza e a firmare gli accordi di integrazione: non è un organo eletto e non appartiene all'ente locale." },
  { id: "reg-13", lesson: "it-regioni", level: "medium",
    q: "Quale di queste materie resta di competenza esclusiva dello Stato?",
    options: ["Il turismo", "L'agricoltura", "L'immigrazione", "L'artigianato"],
    answer: 2,
    explanation: "Immigrazione, difesa, moneta e giustizia sono fra le materie esclusive dello Stato. Turismo, agricoltura e artigianato ricadono invece nella competenza regionale." },
];
