import type { Course } from "@/lib/courses";

/**
 * Life in the UK.
 *
 * The official test is 24 questions in 45 minutes and you need 18 right — 75%.
 * It is drawn from the Home Office handbook, which is Crown copyright, and the
 * commercial question banks are their publishers' copyright. Neither is
 * reproduced here. What follows is written from scratch against the published
 * syllabus: the same five chapters, the same facts, in our own words. Dates,
 * institutions and how Parliament works belong to nobody.
 *
 * The history sections are deliberately the longest. They carry the most
 * questions in the real test and they are the part that is hardest to guess
 * from living here.
 */
export const lifeInTheUkCourse: Course = {
  id: "life-in-the-uk",
  kind: "citizenship",
  name: "Life in the UK",
  tagline: "History, government and traditions — everything the citizenship test asks.",
  icon: "🏛️",
  available: true,
  lessons: [
    // ── Chapter 1: values and principles ──────────────────────────────────
    {
      id: "values",
      title: "The test, and the values behind it",
      section: "Values and principles",
      badge: "lesson 1",
      blocks: [
        { type: "p", text: "The Life in the UK Test is a requirement for both settlement (indefinite leave to remain) and citizenship. It is **24 multiple-choice questions in 45 minutes**, and the pass mark is **18 out of 24** — 75%." },
        { type: "cards", items: [
          { h4: "Where", p: "At a registered test centre, booked online. You must book at least 3 days ahead and bring the same ID you booked with." },
          { h4: "Who", p: "Usually required if you are aged 18 to 64. There are exemptions for some long-term medical conditions." },
          { h4: "Result", p: "You find out on the day. If you fail you can retake it, but you must wait 7 days between attempts." },
        ] },
        { type: "callout", variant: "why", text: "Why this lesson first: the test does not only ask facts. Several questions ask what British society expects of you, and those answers come straight from the values below." },
        { type: "h3", text: "The fundamental principles" },
        { type: "p", text: "The UK sets out a short list of shared values. Learn them as a list — questions often ask you to pick which one is *not* included." },
        { type: "cards", items: [
          { h4: "Democracy", p: "Government by the people, through elected representatives." },
          { h4: "The rule of law", p: "Everyone is subject to the law, including those who govern." },
          { h4: "Individual liberty", p: "Freedom to live as you choose within the law." },
          { h4: "Tolerance", p: "Respect for those of different faiths and beliefs, and of none." },
          { h4: "Participation", p: "Taking part in community life — voting, volunteering, jury service." },
        ] },
        { type: "h3", text: "The citizenship ceremony" },
        { type: "p", text: "If your application succeeds you attend a ceremony, usually run by your local council, within three months. There you swear an **oath of allegiance** (or make an **affirmation** if you prefer not to swear by God) and give a **pledge** to respect the UK's rights, freedoms and laws." },
        { type: "quiz",
          q: "How many questions must you answer correctly to pass the Life in the UK Test?",
          options: [
            { text: "16 out of 24", correct: false },
            { text: "18 out of 24", correct: true },
            { text: "20 out of 24", correct: false },
            { text: "24 out of 24", correct: false },
          ],
          explanation: "The pass mark is 75% — 18 of the 24 questions, in 45 minutes." },
        { type: "quiz",
          q: "At a citizenship ceremony, what is the alternative for someone who does not wish to swear by God?",
          options: [
            { text: "They are excused the oath entirely", correct: false },
            { text: "They make an affirmation instead", correct: true },
            { text: "They swear on a different holy book", correct: false },
            { text: "They sign a written declaration only", correct: false },
          ],
          explanation: "An affirmation carries exactly the same legal weight as the oath. This reflects the value of tolerance — including tolerance of those with no religious belief." },
      ],
    },

    // ── Chapter 2: what is the UK? ────────────────────────────────────────
    {
      id: "what-is-the-uk",
      title: "Four nations, four flags, four saints",
      section: "What is the UK?",
      badge: "lesson 2",
      blocks: [
        { type: "p", text: "This trips people up constantly, and the test knows it. **The United Kingdom** is England, Scotland, Wales and Northern Ireland. **Great Britain** is only England, Scotland and Wales — it is the island, so Northern Ireland is not part of it." },
        { type: "callout", variant: "warn", text: "The Channel Islands and the Isle of Man are Crown Dependencies. They are NOT part of the UK. They have their own governments and are linked to the Crown, not to Parliament in Westminster." },
        { type: "h3", text: "Capitals" },
        { type: "cards", items: [
          { h4: "England — London", p: "Also the capital of the UK as a whole, and the seat of the UK Parliament." },
          { h4: "Scotland — Edinburgh", p: "Home of the Scottish Parliament, at Holyrood." },
          { h4: "Wales — Cardiff", p: "Home of the Welsh Parliament, the Senedd." },
          { h4: "Northern Ireland — Belfast", p: "Home of the Northern Ireland Assembly, at Stormont." },
        ] },
        { type: "h3", text: "Patron saints and their days" },
        { type: "p", text: "Four saints, four dates. Two fall in March, and that is the pair most often confused." },
        { type: "cards", items: [
          { h4: "St David — 1 March", p: "Wales. Dewi Sant in Welsh." },
          { h4: "St Patrick — 17 March", p: "Northern Ireland." },
          { h4: "St George — 23 April", p: "England." },
          { h4: "St Andrew — 30 November", p: "Scotland. St Andrew's Day is a bank holiday in Scotland." },
        ] },
        { type: "h3", text: "The Union Flag" },
        { type: "p", text: "The Union Flag — often called the Union Jack — combines three crosses: the red cross of St George on white for England, the white diagonal cross of St Andrew on blue for Scotland, and the red diagonal cross of St Patrick on white for Ireland." },
        { type: "callout", variant: "why", text: "Why Wales is missing: when the first Union Flag was designed, Wales had already been joined to England, so it was not treated as a separate kingdom. The Welsh dragon flies on its own flag instead." },
        { type: "h3", text: "Languages" },
        { type: "p", text: "English is spoken throughout. Welsh is an official language in Wales and is taught in schools there. Gaelic is spoken in parts of Scotland, and Irish is spoken in Northern Ireland." },
        { type: "quiz",
          q: "Which of these is part of Great Britain but you would be wrong to include when listing the UK's four nations' capitals?",
          options: [
            { text: "Nothing — Great Britain and the UK contain the same nations", correct: false },
            { text: "Northern Ireland is in Great Britain but not the UK", correct: false },
            { text: "Northern Ireland is in the UK but not in Great Britain", correct: true },
            { text: "The Isle of Man is in both", correct: false },
          ],
          explanation: "Great Britain is the island: England, Scotland and Wales. The UK adds Northern Ireland. The Isle of Man is in neither — it is a Crown Dependency." },
        { type: "quiz",
          q: "Which patron saint's day falls on 1 March?",
          options: [
            { text: "St Patrick", correct: false },
            { text: "St David", correct: true },
            { text: "St George", correct: false },
            { text: "St Andrew", correct: false },
          ],
          explanation: "St David of Wales, 1 March. St Patrick follows on 17 March — the two March dates are the ones people mix up." },
      ],
    },

    // ── Chapter 3: history ────────────────────────────────────────────────
    {
      id: "early-britain",
      title: "Early Britain: Stone Age to the Romans",
      section: "A long and illustrious history",
      badge: "lesson 3",
      blocks: [
        { type: "p", text: "For most of prehistory Britain was not an island. It was joined to the continent by land, and people walked here. Around **10,000 years ago** the land bridge flooded and Britain was cut off." },
        { type: "h3", text: "Stone Age and Bronze Age" },
        { type: "cards", items: [
          { h4: "Stonehenge", p: "On Salisbury Plain in Wiltshire. Built in stages from around 3000 BC, probably a place of ceremony and burial." },
          { h4: "Skara Brae", p: "A Stone Age village on Orkney, off the north coast of Scotland — the best preserved in northern Europe." },
          { h4: "Bronze Age", p: "People learned to make bronze tools and weapons, lived in roundhouses and buried their dead in round barrows." },
        ] },
        { type: "h3", text: "The Iron Age" },
        { type: "p", text: "Iron tools and weapons followed. People lived in tribes led by chieftains, built hill forts such as **Maiden Castle** in Dorset, and spoke Celtic languages. The first coins in Britain were minted in this period, some carrying the names of Iron Age kings." },
        { type: "h3", text: "The Romans" },
        { type: "p", text: "**Julius Caesar invaded in 55 BC — and failed.** The successful invasion came nearly a century later, in **AD 43 under the Emperor Claudius**. The Romans stayed for almost 400 years." },
        { type: "callout", variant: "warn", text: "A favourite test trap: Caesar 55 BC is the famous date, but it was an unsuccessful raid. Claudius in AD 43 is the invasion that actually conquered Britain." },
        { type: "cards", items: [
          { h4: "Boudicca", p: "Queen of the Iceni in eastern England, who led a fierce rebellion against the Romans. Her statue stands on Westminster Bridge in London." },
          { h4: "Hadrian's Wall", p: "Built on the orders of the Emperor Hadrian in AD 122 to keep out the Picts of what is now Scotland. Much of it still stands." },
          { h4: "AD 410", p: "The Roman army left Britain to defend other parts of the empire, and never returned." },
        ] },
        { type: "p", text: "The Romans never conquered what is now Scotland or Ireland. They did build the towns, roads and public baths that shaped Britain for centuries afterwards." },
        { type: "quiz",
          q: "Which Roman emperor's invasion successfully conquered Britain?",
          options: [
            { text: "Julius Caesar, in 55 BC", correct: false },
            { text: "Claudius, in AD 43", correct: true },
            { text: "Hadrian, in AD 122", correct: false },
            { text: "Augustus, in AD 410", correct: false },
          ],
          explanation: "Caesar's 55 BC expedition failed. Claudius invaded in AD 43 and that conquest held. Hadrian's date, AD 122, is his wall — not an invasion." },
        { type: "quiz",
          q: "Why was Hadrian's Wall built?",
          options: [
            { text: "To keep out the Vikings", correct: false },
            { text: "To mark the border with Wales", correct: false },
            { text: "To keep out the Picts from the north", correct: true },
            { text: "To defend against invasion from Ireland", correct: false },
          ],
          explanation: "It was built across northern England to defend the province against the Picts, the tribes of what is now Scotland. The Vikings did not arrive for another 600 years." },
      ],
    },

    {
      id: "invaders",
      title: "Invaders and settlers: Anglo-Saxons, Vikings and 1066",
      section: "A long and illustrious history",
      badge: "lesson 4",
      blocks: [
        { type: "p", text: "After the Romans left, tribes from what is now Germany, Denmark and the Netherlands settled in Britain. These were the **Anglo-Saxons**, and the language they brought became English." },
        { type: "cards", items: [
          { h4: "Sutton Hoo", p: "A ship burial in Suffolk, filled with treasure — the grave of an Anglo-Saxon king, and the richest find of its kind in Britain." },
          { h4: "St Augustine", p: "Sent from Rome in AD 597, he converted the south to Christianity and became the first Archbishop of Canterbury." },
          { h4: "St Columba", p: "Founded a monastery on Iona, off the Scottish coast, spreading Christianity in the north." },
          { h4: "St Patrick", p: "Became the patron saint of Ireland after his missionary work there." },
        ] },
        { type: "h3", text: "The Vikings" },
        { type: "p", text: "Viking raids began in **AD 789**, from Denmark and Norway. At first they raided and left; later they settled, especially in the east and north of England, in the area that became known as the **Danelaw**. Place names ending in *-by* and *-thorpe* are their legacy." },
        { type: "p", text: "**King Alfred the Great** of Wessex was the Anglo-Saxon king who defeated the Vikings in battle and forced them to a settlement — the only English monarch commonly called 'the Great'." },
        { type: "h3", text: "1066 — the date to know" },
        { type: "p", text: "If you learn one date, learn this one. In **1066 William, Duke of Normandy, defeated King Harold at the Battle of Hastings** and became William the Conqueror. It is the last time Britain was successfully invaded." },
        { type: "cards", items: [
          { h4: "The Bayeux Tapestry", p: "An embroidery, still on display in France, showing the events of the conquest." },
          { h4: "The Domesday Book", p: "Ordered by William in 1086 — a survey of who owned what across England, for taxation." },
          { h4: "Norman French", p: "The language of the new ruling class. English absorbed thousands of its words and became the language we speak today." },
        ] },
        { type: "quiz",
          q: "Who did William of Normandy defeat at the Battle of Hastings in 1066?",
          options: [
            { text: "King Alfred", correct: false },
            { text: "King Harold", correct: true },
            { text: "King Canute", correct: false },
            { text: "King John", correct: false },
          ],
          explanation: "Harold was the last Anglo-Saxon king of England. Alfred the Great reigned two centuries earlier; King John comes later, with Magna Carta." },
        { type: "quiz",
          q: "What was the Domesday Book?",
          options: [
            { text: "A record of who owned land across England", correct: true },
            { text: "A list of laws issued by William the Conqueror", correct: false },
            { text: "An account of the Battle of Hastings", correct: false },
            { text: "The first English translation of the Bible", correct: false },
          ],
          explanation: "It was a survey completed in 1086 recording landholding across England, so that it could be taxed. The tapestry, not the book, tells the story of the battle." },
      ],
    },

    {
      id: "middle-ages",
      title: "The Middle Ages: Magna Carta, war and plague",
      section: "A long and illustrious history",
      badge: "lesson 5",
      blocks: [
        { type: "h3", text: "Magna Carta, 1215" },
        { type: "p", text: "**King John** was forced by his noblemen to agree to a charter of rights at Runnymede in **1215**. Magna Carta — Latin for 'the Great Charter' — established a principle that still underpins the country: **the king was not above the law**." },
        { type: "callout", variant: "why", text: "Why it matters beyond history: this is the root of the 'rule of law' value from lesson 1. Expect questions that connect the two." },
        { type: "h3", text: "Wales and Scotland" },
        { type: "cards", items: [
          { h4: "Wales, 1284", p: "The Statute of Rhuddlan annexed Wales to the English Crown. Welsh rebellion followed, led most famously by Owain Glyndŵr." },
          { h4: "Scotland, 1314", p: "Robert the Bruce defeated the English at the Battle of Bannockburn, and Scotland remained independent for centuries more." },
        ] },
        { type: "h3", text: "The Black Death" },
        { type: "p", text: "Plague reached England in **1348** and killed roughly a third of the population. Because so few labourers survived, those who did could demand better conditions — the beginning of the end of the feudal system, and the rise of a middle class of landowning farmers." },
        { type: "h3", text: "The Hundred Years War" },
        { type: "p", text: "England and France fought on and off from **1337 to 1453**. The best-remembered English victory is the **Battle of Agincourt in 1415**, won by Henry V against far larger French numbers, thanks largely to the English longbow." },
        { type: "h3", text: "The Wars of the Roses" },
        { type: "p", text: "A civil war for the throne between the House of Lancaster (a red rose) and the House of York (a white rose), running from 1455. It ended at the **Battle of Bosworth Field in 1485**, where Richard III was killed and **Henry Tudor became Henry VII**." },
        { type: "callout", variant: "analogy", text: "The Tudor rose — red with a white centre — was created to symbolise the two houses joined. You still see it on coins and uniforms today." },
        { type: "quiz",
          q: "What principle did Magna Carta establish in 1215?",
          options: [
            { text: "That Parliament must approve all taxes", correct: false },
            { text: "That the king was subject to the law, not above it", correct: true },
            { text: "That every man had the right to vote", correct: false },
            { text: "That the Church was independent of Rome", correct: false },
          ],
          explanation: "Magna Carta bound the king to the law. Parliamentary control of taxation and the break with Rome came centuries later." },
        { type: "quiz",
          q: "The Wars of the Roses ended in 1485 at which battle?",
          options: [
            { text: "Agincourt", correct: false },
            { text: "Bannockburn", correct: false },
            { text: "Bosworth Field", correct: true },
            { text: "Hastings", correct: false },
          ],
          explanation: "Bosworth Field, where Richard III died and Henry Tudor took the throne as Henry VII, founding the Tudor dynasty." },
      ],
    },

    {
      id: "tudors",
      title: "The Tudors: Reformation and Elizabeth I",
      section: "A long and illustrious history",
      badge: "lesson 6",
      blocks: [
        { type: "h3", text: "Henry VIII and the break with Rome" },
        { type: "p", text: "Henry VIII wanted his marriage annulled and the Pope refused. So he broke with Rome, made himself head of the **Church of England**, and dissolved the monasteries. This was the English **Reformation** — done for dynastic reasons as much as religious ones." },
        { type: "p", text: "**Six wives, in order:** Catherine of Aragon, Anne Boleyn, Jane Seymour, Anne of Cleves, Catherine Howard, Catherine Parr." },
        { type: "callout", variant: "analogy", text: "The traditional mnemonic for their fates: divorced, beheaded, died; divorced, beheaded, survived." },
        { type: "p", text: "Wales was formally united with England by the **Acts of Union of 1536 and 1543**, giving Wales representation in the English Parliament and making English the language of its courts." },
        { type: "h3", text: "Edward VI and Mary I" },
        { type: "cards", items: [
          { h4: "Edward VI", p: "Henry's son, a strong Protestant. The Book of Common Prayer, still used in Anglican churches, dates from his reign. He died aged 15." },
          { h4: "Mary I", p: "A devout Catholic who reversed the Reformation and had Protestants executed — hence the nickname 'Bloody Mary'." },
        ] },
        { type: "h3", text: "Elizabeth I" },
        { type: "p", text: "Elizabeth restored the Protestant settlement but sought a middle way that most people could live with. Her reign is remembered for exploration, for Shakespeare's theatre, and above all for the defeat of the **Spanish Armada in 1588** — a fleet sent by Philip II of Spain to invade England." },
        { type: "h3", text: "Scotland and the union of crowns" },
        { type: "p", text: "**Mary, Queen of Scots** fled to England, was held prisoner for years and was executed in 1587. It was her son who inherited: when Elizabeth died childless in **1603, James VI of Scotland became James I of England** as well — one king, but still two separate countries." },
        { type: "quiz",
          q: "What was the Spanish Armada?",
          options: [
            { text: "A Spanish fleet sent to invade England in 1588", correct: true },
            { text: "A trade agreement between England and Spain", correct: false },
            { text: "The English fleet that defeated Spain in the Caribbean", correct: false },
            { text: "A treaty ending the Hundred Years War", correct: false },
          ],
          explanation: "Philip II of Spain sent it in 1588. Its defeat is one of the defining events of Elizabeth I's reign." },
        { type: "quiz",
          q: "What happened in 1603?",
          options: [
            { text: "England and Scotland became a single kingdom", correct: false },
            { text: "James VI of Scotland also became James I of England", correct: true },
            { text: "Elizabeth I defeated the Spanish Armada", correct: false },
            { text: "The Act of Union with Wales was passed", correct: false },
          ],
          explanation: "This was the Union of the Crowns — one monarch over two still-separate kingdoms. The countries were not politically united until the Act of Union in 1707." },
      ],
    },

    {
      id: "stuarts",
      title: "The Stuarts: civil war, plague, fire and the Bill of Rights",
      section: "A long and illustrious history",
      badge: "lesson 7",
      blocks: [
        { type: "h3", text: "The Gunpowder Plot, 1605" },
        { type: "p", text: "A group of Catholic conspirators tried to blow up the House of Lords and kill James I. **Guy Fawkes** was caught guarding the explosives. The failure is still marked every **5 November** with bonfires and fireworks." },
        { type: "h3", text: "The Civil War" },
        { type: "p", text: "Charles I believed he ruled by divine right and clashed repeatedly with Parliament over money and religion. War broke out in **1642** between the king's supporters (Cavaliers) and Parliament's (Roundheads). Parliament won, and in **1649 Charles I was executed** — the only English king ever put to death by his own subjects." },
        { type: "p", text: "**Oliver Cromwell** ruled the republic that followed, as Lord Protector. England had no monarch for eleven years." },
        { type: "h3", text: "The Restoration" },
        { type: "p", text: "In **1660** Parliament invited **Charles II** back to the throne. Two disasters marked his reign in quick succession: the **Great Plague of 1665** and the **Great Fire of London in 1666**." },
        { type: "cards", items: [
          { h4: "Habeas Corpus Act, 1679", p: "Established that nobody could be held in prison unlawfully — a foundation of the rule of law." },
          { h4: "The Royal Society", p: "Founded in Charles II's reign to promote science. Isaac Newton was among its members." },
        ] },
        { type: "h3", text: "The Glorious Revolution, 1688" },
        { type: "p", text: "James II was Catholic and Parliament feared a Catholic dynasty. Protestant nobles invited **William of Orange**, the Dutch husband of James's daughter Mary, to take the throne. He landed with an army, James fled, and power changed hands with almost no fighting — hence 'glorious'." },
        { type: "p", text: "The **Bill of Rights of 1689** followed, and it is the hinge of British government. From then on the monarch could not rule without Parliament: no taxes and no army without its consent, and regular parliaments guaranteed. This is the beginning of **constitutional monarchy**." },
        { type: "quiz",
          q: "What is celebrated on 5 November?",
          options: [
            { text: "The execution of Charles I", correct: false },
            { text: "The failure of the Gunpowder Plot", correct: true },
            { text: "The end of the Great Fire of London", correct: false },
            { text: "The signing of the Bill of Rights", correct: false },
          ],
          explanation: "Guy Fawkes was caught on the night of 4–5 November 1605 guarding explosives beneath the House of Lords. Bonfire Night marks the plot's failure." },
        { type: "quiz",
          q: "What did the Bill of Rights of 1689 establish?",
          options: [
            { text: "That every adult had the right to vote", correct: false },
            { text: "That the monarch could not rule without Parliament", correct: true },
            { text: "That Catholics could hold public office", correct: false },
            { text: "That England and Scotland were one kingdom", correct: false },
          ],
          explanation: "It made the monarch dependent on Parliament for taxes and for an army, creating constitutional monarchy. Votes for all adults took another 240 years." },
      ],
    },

    {
      id: "georgians",
      title: "Union, empire and industry: the Georgians",
      section: "A long and illustrious history",
      badge: "lesson 8",
      blocks: [
        { type: "h3", text: "The Act of Union, 1707" },
        { type: "p", text: "England and Scotland had shared a monarch since 1603. In **1707 the Act of Union** merged their parliaments too, creating the **Kingdom of Great Britain** with one Parliament at Westminster." },
        { type: "p", text: "Not everyone accepted it. Supporters of the exiled Stuart claim — the **Jacobites** — rebelled. **Bonnie Prince Charlie** led a rising in 1745 that reached deep into England before being crushed at the **Battle of Culloden in 1746**, the last battle fought on British soil." },
        { type: "h3", text: "The Enlightenment" },
        { type: "p", text: "An age of new ideas about reason, economics and society. Two Scots stand out: **Adam Smith**, whose economic thinking still shapes the subject, and **David Hume**, the philosopher." },
        { type: "h3", text: "The Industrial Revolution" },
        { type: "p", text: "Britain was the first country to industrialise. Steam power, coal, iron and textile machinery transformed it from a farming country into a manufacturing one, and people moved from villages into fast-growing cities." },
        { type: "cards", items: [
          { h4: "James Watt", p: "A Scot whose improvements to the steam engine made it genuinely useful for industry." },
          { h4: "Richard Arkwright", p: "Pioneered efficient, powered factory production in textiles." },
          { h4: "Canals and railways", p: "Built to move coal and goods, and then people, at a speed nobody had experienced." },
        ] },
        { type: "callout", variant: "warn", text: "Conditions were brutal: long hours, dangerous machinery and child labour were normal. The reforms that ended them came later, in the Victorian era." },
        { type: "h3", text: "War with France" },
        { type: "cards", items: [
          { h4: "Trafalgar, 1805", p: "Admiral Nelson destroyed the French and Spanish fleets, and was killed in the battle. Nelson's Column in Trafalgar Square commemorates him." },
          { h4: "Waterloo, 1815", p: "The Duke of Wellington finally defeated Napoleon, ending more than twenty years of war." },
        ] },
        { type: "h3", text: "The slave trade and its abolition" },
        { type: "p", text: "Britain grew rich partly through the transatlantic slave trade. A campaign led by **William Wilberforce** and others, including Quakers, turned public opinion against it. The **slave trade was abolished in 1807**, and **slavery itself throughout the British Empire in 1833**." },
        { type: "p", text: "The **Act of Union of 1801** joined Ireland to Great Britain, creating the United Kingdom of Great Britain and Ireland." },
        { type: "quiz",
          q: "The Act of Union of 1707 created which kingdom?",
          options: [
            { text: "The United Kingdom of Great Britain and Ireland", correct: false },
            { text: "The Kingdom of Great Britain", correct: true },
            { text: "The Kingdom of England and Wales", correct: false },
            { text: "The United Kingdom as it exists today", correct: false },
          ],
          explanation: "1707 united the English and Scottish parliaments into the Kingdom of Great Britain. Ireland was added in 1801." },
        { type: "quiz",
          q: "In which year was slavery abolished throughout the British Empire?",
          options: [
            { text: "1807", correct: false },
            { text: "1815", correct: false },
            { text: "1833", correct: true },
            { text: "1867", correct: false },
          ],
          explanation: "1807 ended the slave trade; 1833 abolished slavery itself across the empire. Both dates appear as options, so read the question carefully." },
      ],
    },

    {
      id: "victorians",
      title: "The Victorians and the height of empire",
      section: "A long and illustrious history",
      badge: "lesson 9",
      blocks: [
        { type: "p", text: "**Queen Victoria reigned from 1837 to 1901** — 64 years, and the longest reign until Elizabeth II passed it. At its height the British Empire covered around a quarter of the world's population." },
        { type: "h3", text: "Reform at home" },
        { type: "p", text: "The century brought steady extension of the vote and of workers' protections: laws limiting the hours women and children could work, the growth of trade unions, and Reform Acts that widened the franchise — though still only to men, and at first only to men with property." },
        { type: "cards", items: [
          { h4: "Florence Nightingale", p: "Transformed nursing during the Crimean War (1853–56) and founded the first nursing school, at St Thomas' Hospital in London." },
          { h4: "Isambard Kingdom Brunel", p: "Engineer of the Great Western Railway, and of bridges, tunnels and steamships." },
          { h4: "The Great Exhibition, 1851", p: "Held in the Crystal Palace in Hyde Park, to display British industry and design to the world." },
        ] },
        { type: "h3", text: "Ireland" },
        { type: "p", text: "The **Irish famine** of the 1840s killed around a million people and drove many more to emigrate. Ireland's population fell sharply and the demand for Home Rule grew through the rest of the century." },
        { type: "h3", text: "The Boer War" },
        { type: "p", text: "Fought in South Africa from 1899 to 1902 against Dutch settlers. It was long, costly and unpopular, and marked the point where confidence in the empire began to waver." },
        { type: "quiz",
          q: "Who was Florence Nightingale?",
          options: [
            { text: "The first woman to sit in Parliament", correct: false },
            { text: "A nurse in the Crimean War who founded a nursing school", correct: true },
            { text: "The engineer of the Great Western Railway", correct: false },
            { text: "A leader of the suffragette movement", correct: false },
          ],
          explanation: "She reformed nursing during the Crimean War and opened a training school at St Thomas' Hospital. Brunel was the railway engineer." },
      ],
    },

    {
      id: "twentieth-century",
      title: "War, welfare and votes: the twentieth century",
      section: "A long and illustrious history",
      badge: "lesson 10",
      blocks: [
        { type: "h3", text: "The First World War, 1914–1918" },
        { type: "p", text: "Britain entered after Germany invaded Belgium. More than a million British and Empire servicemen died. The **Battle of the Somme in 1916** saw around 60,000 British casualties on its first day alone. The war is remembered every year on **Remembrance Day, 11 November**, with poppies and a two-minute silence at 11am." },
        { type: "h3", text: "Votes for women" },
        { type: "p", text: "The **suffragettes** campaigned, and often went to prison, for the right to vote. In **1918 women over 30 who met a property qualification** were enfranchised. It was **1928** before women could vote at **21, on the same terms as men**." },
        { type: "callout", variant: "warn", text: "Two dates, two different things. 1918 is partial — over 30, with property. 1928 is equality at 21. Questions test the difference." },
        { type: "h3", text: "Ireland divides" },
        { type: "p", text: "After a war of independence, the **Irish Free State** was established in **1922** as a separate country, while six counties in the north remained in the UK. The country's name changed to the **United Kingdom of Great Britain and Northern Ireland**." },
        { type: "h3", text: "The Second World War, 1939–1945" },
        { type: "p", text: "Britain declared war after Germany invaded Poland. **Winston Churchill** became Prime Minister in 1940." },
        { type: "cards", items: [
          { h4: "Dunkirk, 1940", p: "Over 300,000 troops were evacuated from the French coast, many by small civilian boats." },
          { h4: "The Battle of Britain, 1940", p: "The RAF held off the German air force, preventing an invasion. Churchill's tribute to the pilots: 'Never in the field of human conflict was so much owed by so many to so few.'" },
          { h4: "D-Day, 6 June 1944", p: "Allied forces landed in Normandy, beginning the liberation of western Europe." },
        ] },
        { type: "p", text: "**Alan Turing** and colleagues at Bletchley Park broke German codes, work now credited with shortening the war." },
        { type: "h3", text: "The welfare state" },
        { type: "p", text: "The **Beveridge Report of 1942** set out a plan to tackle what it called the five 'giants' of want, disease, ignorance, squalor and idleness. After the war the Labour government acted on it, and in **1948 the National Health Service was founded** under **Aneurin Bevan** — free healthcare at the point of use." },
        { type: "quiz",
          q: "In 1918, which women were given the right to vote?",
          options: [
            { text: "All women over 21", correct: false },
            { text: "Women over 30 who met a property qualification", correct: true },
            { text: "All women over 18", correct: false },
            { text: "Married women only", correct: false },
          ],
          explanation: "1918 was partial. Equal voting rights at 21 came ten years later, in 1928." },
        { type: "quiz",
          q: "Who was the minister who led the founding of the NHS in 1948?",
          options: [
            { text: "Winston Churchill", correct: false },
            { text: "William Beveridge", correct: false },
            { text: "Aneurin Bevan", correct: true },
            { text: "Clement Attlee", correct: false },
          ],
          explanation: "Bevan was the Health Minister who created it. Beveridge wrote the 1942 report that inspired it; Attlee was the Prime Minister of the government that delivered it." },
      ],
    },

    {
      id: "since-1945",
      title: "Britain since 1945: immigration, Europe and devolution",
      section: "A long and illustrious history",
      badge: "lesson 11",
      blocks: [
        { type: "h3", text: "Rebuilding and immigration" },
        { type: "p", text: "Post-war Britain was short of workers. People were invited from the Caribbean, India, Pakistan and Bangladesh to help rebuild and to staff the new NHS and the transport system — the generation often called the **Windrush** generation, after the ship that brought an early group in 1948." },
        { type: "p", text: "Later decades brought further migration, including Ugandan Asians expelled in 1972, and people from across the EU after 2004. Modern Britain is the result." },
        { type: "h3", text: "The end of empire" },
        { type: "p", text: "India and Pakistan became independent in 1947, and most remaining colonies followed over the next thirty years. Many joined the **Commonwealth**, a voluntary association of independent countries." },
        { type: "h3", text: "Europe" },
        { type: "p", text: "The UK joined the European Economic Community in **1973**. In a referendum in **2016** it voted to leave the European Union, and formally left in **2020**." },
        { type: "h3", text: "Northern Ireland" },
        { type: "p", text: "Three decades of conflict known as **the Troubles** were largely brought to an end by the **Good Friday Agreement of 1998**, which established a power-sharing assembly at Stormont." },
        { type: "h3", text: "Devolution" },
        { type: "p", text: "Following referendums, powers were transferred from Westminster in **1999** to a **Scottish Parliament**, a **Welsh Assembly** (now the Senedd) and a **Northern Ireland Assembly**. Each controls devolved matters such as health and education; defence, foreign policy and immigration stay with the UK Parliament." },
        { type: "cards", items: [
          { h4: "Margaret Thatcher", p: "The UK's first female Prime Minister, in office 1979–1990." },
          { h4: "The Falklands, 1982", p: "Britain retook the islands after an Argentine invasion." },
          { h4: "The Commonwealth", p: "Around 56 member states. Membership is voluntary and carries no legal obligation on members." },
        ] },
        { type: "quiz",
          q: "In which year were the Scottish Parliament and Welsh Assembly established?",
          options: [
            { text: "1979", correct: false },
            { text: "1998", correct: false },
            { text: "1999", correct: true },
            { text: "2004", correct: false },
          ],
          explanation: "Referendums were held in 1997 and the devolved bodies opened in 1999. 1998 is the Good Friday Agreement — a different, neighbouring date." },
        { type: "quiz",
          q: "Which of these remains the responsibility of the UK Parliament rather than the devolved administrations?",
          options: [
            { text: "Health", correct: false },
            { text: "Education", correct: false },
            { text: "Defence and foreign policy", correct: true },
            { text: "Local transport", correct: false },
          ],
          explanation: "Defence, foreign policy and immigration are reserved to Westminster. Health and education are devolved, which is why the NHS and schools differ across the four nations." },
      ],
    },

    // ── Chapter 4: a modern, thriving society ─────────────────────────────
    {
      id: "society",
      title: "A modern, thriving society: sport, arts and traditions",
      section: "A modern, thriving society",
      badge: "lesson 12",
      blocks: [
        { type: "h3", text: "Sport" },
        { type: "cards", items: [
          { h4: "Football", p: "The modern game was codified in England. Each of the four nations has its own national team and league." },
          { h4: "Cricket", p: "Originated in England. The Ashes is the long-running series against Australia." },
          { h4: "Rugby", p: "The Six Nations is contested by England, Scotland, Wales, Ireland, France and Italy." },
          { h4: "Tennis", p: "Wimbledon, held in London, is the oldest tennis tournament in the world." },
        ] },
        { type: "p", text: "**Sir Roger Bannister** ran the first mile under four minutes, in 1954. The UK has hosted the Olympic Games three times, most recently in **London in 2012**." },
        { type: "h3", text: "Arts and literature" },
        { type: "p", text: "**William Shakespeare**, born in Stratford-upon-Avon, is the best known figure in English literature. Later names the test may expect include the Brontë sisters, Charles Dickens, Jane Austen and Thomas Hardy." },
        { type: "cards", items: [
          { h4: "The Proms", p: "An eight-week season of classical concerts, ending with the Last Night of the Proms." },
          { h4: "The Turner Prize", p: "An annual award for contemporary British art, named after the painter J. M. W. Turner." },
          { h4: "The Mercury Prize and the BRITs", p: "Awards for popular music." },
          { h4: "The Edinburgh Festival Fringe", p: "The world's largest arts festival, held every August." },
        ] },
        { type: "h3", text: "Festivals and traditions" },
        { type: "cards", items: [
          { h4: "New Year — 1 January", p: "In Scotland, Hogmanay is celebrated on 31 December and is a major holiday." },
          { h4: "Easter", p: "Good Friday and Easter Monday are both bank holidays." },
          { h4: "Remembrance Day — 11 November", p: "Poppies are worn and a two-minute silence is held at 11am." },
          { h4: "Christmas — 25 December", p: "Boxing Day, 26 December, is also a public holiday." },
        ] },
        { type: "p", text: "Other traditions include **Bonfire Night** on 5 November, **Hallowe'en** on 31 October, **Valentine's Day** on 14 February, **April Fool's Day** on 1 April (jokes only until midday), **Mothering Sunday** in March and **Father's Day** in June. Diwali, Eid, Hanukkah and Vaisakhi are widely celebrated too." },
        { type: "quiz",
          q: "What is the Turner Prize awarded for?",
          options: [
            { text: "Popular music", correct: false },
            { text: "Contemporary British art", correct: true },
            { text: "Literature", correct: false },
            { text: "Film and television", correct: false },
          ],
          explanation: "It is named after the painter J. M. W. Turner and awarded for contemporary art. The Mercury Prize and the BRITs are the music awards." },
        { type: "quiz",
          q: "When is Hogmanay celebrated, and where is it especially important?",
          options: [
            { text: "31 December, in Scotland", correct: true },
            { text: "1 January, in Wales", correct: false },
            { text: "25 January, in Scotland", correct: false },
            { text: "31 October, in Northern Ireland", correct: false },
          ],
          explanation: "Hogmanay is New Year's Eve, 31 December, and is a major Scottish celebration. 25 January is Burns Night, which is also Scottish but marks the poet's birthday." },
      ],
    },

    // ── Chapter 5: government, law and your role ──────────────────────────
    {
      id: "government",
      title: "Government, the monarchy and how laws are made",
      section: "Government, the law and your role",
      badge: "lesson 13",
      blocks: [
        { type: "h3", text: "A constitutional monarchy" },
        { type: "p", text: "The monarch is head of state but does not run the government. The UK's constitution is **unwritten** — or more precisely uncodified: it exists across statutes, conventions and case law rather than in a single document." },
        { type: "p", text: "The monarch's role is largely ceremonial: opening Parliament, appointing the Prime Minister, and giving royal assent to legislation. The monarch is expected to remain politically neutral." },
        { type: "h3", text: "Parliament" },
        { type: "p", text: "Parliament has three parts: the **House of Commons**, the **House of Lords** and the **monarch**." },
        { type: "cards", items: [
          { h4: "House of Commons", p: "650 elected MPs, each representing a constituency. This is the chamber with real power — and the only one you elect." },
          { h4: "House of Lords", p: "Not elected. Members are appointed, mostly life peers, and can revise and delay legislation but generally cannot block what the Commons insists on." },
          { h4: "The Speaker", p: "Chairs debates in the Commons, keeps order and must be politically neutral. Elected by fellow MPs." },
        ] },
        { type: "h3", text: "Elections" },
        { type: "p", text: "General elections use **first past the post**: the candidate with the most votes in each constituency wins the seat. The leader of the party that can command a majority is normally invited by the monarch to become **Prime Minister**." },
        { type: "p", text: "You can vote from age **18** in a UK general election, and you must be on the electoral register. In Scotland and Wales, 16- and 17-year-olds can vote in devolved elections." },
        { type: "h3", text: "Government" },
        { type: "cards", items: [
          { h4: "The Cabinet", p: "Senior ministers chosen by the Prime Minister, each usually running a department." },
          { h4: "The opposition", p: "The largest party not in government. Its leader appoints a shadow cabinet to scrutinise ministers." },
          { h4: "The civil service", p: "Politically neutral officials who carry out government policy whichever party is in power." },
          { h4: "Local government", p: "Councils run local services — schools, housing, refuse, planning — funded partly by council tax." },
        ] },
        { type: "quiz",
          q: "How many members of the House of Lords are elected by the public?",
          options: [
            { text: "All of them", correct: false },
            { text: "About half", correct: false },
            { text: "None — members are appointed", correct: true },
            { text: "Only the life peers", correct: false },
          ],
          explanation: "The Lords is entirely unelected. That is precisely why it can revise and delay but not ultimately override the elected Commons." },
        { type: "quiz",
          q: "What does 'first past the post' mean?",
          options: [
            { text: "Seats are shared out in proportion to votes cast", correct: false },
            { text: "The candidate with the most votes in a constituency wins it", correct: true },
            { text: "Voters rank candidates in order of preference", correct: false },
            { text: "The party with the most votes nationally forms the government", correct: false },
          ],
          explanation: "Each constituency elects one MP — whoever gets the most votes there, even without an overall majority of them." },
      ],
    },

    {
      id: "law-and-role",
      title: "The law, your rights and your responsibilities",
      section: "Government, the law and your role",
      badge: "lesson 14",
      blocks: [
        { type: "h3", text: "Two kinds of law" },
        { type: "cards", items: [
          { h4: "Criminal law", p: "Offences against society — theft, assault, dangerous driving. Cases are brought by the state and can lead to a fine or prison." },
          { h4: "Civil law", p: "Disputes between people or organisations — debt, housing, discrimination at work, faulty goods. The remedy is usually compensation, not punishment." },
        ] },
        { type: "h3", text: "The courts" },
        { type: "cards", items: [
          { h4: "Magistrates' courts", p: "Handle most minor criminal cases in England, Wales and Northern Ireland. Magistrates are usually unpaid volunteers from the local community. In Scotland the equivalent is the Justice of the Peace court." },
          { h4: "Crown Court", p: "Serious criminal cases, heard before a judge and a jury of 12. In Scotland, serious cases go to the Sheriff Court or High Court, where a jury has 15 members." },
          { h4: "County courts", p: "Civil disputes such as debt and personal injury. Small claims can be dealt with informally." },
          { h4: "Youth courts", p: "For defendants aged 10 to 17, with no public access and no jury." },
        ] },
        { type: "callout", variant: "warn", text: "The age of criminal responsibility is 10 in England, Wales and Northern Ireland, but 12 in Scotland. Scotland has its own legal system throughout." },
        { type: "h3", text: "The police" },
        { type: "p", text: "The police are expected to be independent of government and to act with integrity. If you are unhappy with the police you can complain — to the force itself, or to the independent body that oversees them. Police and Crime Commissioners are elected in England and Wales." },
        { type: "h3", text: "Your responsibilities" },
        { type: "cards", items: [
          { h4: "Taxes", p: "Income tax and National Insurance are usually deducted from your pay through PAYE. If you are self-employed you must complete a self-assessment return." },
          { h4: "Jury service", p: "If you are on the electoral register and aged 18 to 70 you may be called. It is a duty, not an invitation." },
          { h4: "Driving", p: "You need a licence, insurance and a valid MOT for a vehicle over three years old. You can drive a car at 17." },
          { h4: "The electoral register", p: "Registering to vote also matters for credit checks and jury service." },
        ] },
        { type: "h3", text: "Taking part" },
        { type: "p", text: "The final value from lesson 1 is participation. That means voting, but also volunteering, helping at a school as a governor or parent, joining a neighbourhood group, giving blood, or standing for office yourself. You can contact your MP about any matter that concerns you — their surgeries are open to constituents." },
        { type: "quiz",
          q: "Which court hears serious criminal cases with a jury in England and Wales?",
          options: [
            { text: "The magistrates' court", correct: false },
            { text: "The county court", correct: false },
            { text: "The Crown Court", correct: true },
            { text: "The youth court", correct: false },
          ],
          explanation: "Crown Court, before a judge and 12 jurors. Magistrates' courts handle minor crime without a jury, and county courts handle civil disputes." },
        { type: "quiz",
          q: "What is the age of criminal responsibility in Scotland?",
          options: [
            { text: "10", correct: false },
            { text: "12", correct: true },
            { text: "16", correct: false },
            { text: "18", correct: false },
          ],
          explanation: "12 in Scotland, but 10 in England, Wales and Northern Ireland. Scotland has a separate legal system, and the test expects you to know the differences." },
        { type: "cta", title: "That is the whole syllabus", sub: "Go back through the quizzes until you are getting them right without hesitating — the real test gives you under two minutes a question." },
      ],
    },
  ],
};
