import type { Blueprint, VocabSeed } from "./types";

/**
 * The packs that take the taught inventory past eight thousand words.
 *
 * Every entry is a word the courses did not already teach — checked against
 * the built catalogue rather than against the pack files, so a word taught
 * under another spelling counts as taught. They are grouped by where a
 * learner meets them: a courtroom, a building site, a hospital ward.
 */
const focus = "Precise vocabulary for the situations a learner meets once they are past everyday small talk — offices, trades, treatment rooms and the countryside.";

const noun = (article: "der" | "die" | "das", de: string, en: string): VocabSeed =>
  ({ de: `${article} ${de}`, lookup: de, fallbackEn: en, tip: "noun", article });
const verb = (de: string, en: string): VocabSeed =>
  ({ de, lookup: de.replace(/^sich /, ""), fallbackEn: en, tip: "verb" });
const adjective = (de: string, en: string): VocabSeed =>
  ({ de, lookup: de, fallbackEn: en, tip: "adjective" });
const adverb = (de: string, en: string): VocabSeed =>
  ({ de, lookup: de, fallbackEn: en, tip: "adverb" });

const pack = (label: string, level: string, theme: string, description: string, seeds: VocabSeed[]): Blueprint =>
  ({ label, level, theme, description, focus, seeds, dialogues: [], phrases: [] });

export const moreWordPartBlueprints: Record<string, Blueprint> = {
  part561: pack("Part 561", "B2", "Lawyers and the courtroom", "Who is in the room, what they argue about, and the words a summons is written in.", [
    noun("der", "Anwalt", "lawyer"),
    noun("die", "Anwältin", "female lawyer"),
    noun("der", "Notar", "notary"),
    noun("der", "Vertragspartner", "contracting party"),
    noun("die", "Klausel", "clause"),
    noun("der", "Gerichtssaal", "courtroom"),
    noun("der", "Schöffe", "lay judge"),
    noun("das", "Alibi", "alibi"),
    noun("die", "Spurensicherung", "forensics team"),
    noun("der", "Tatort", "crime scene"),
    noun("die", "Beweislast", "burden of proof"),
    noun("der", "Sachverständige", "expert witness"),
    noun("die", "Berufung", "appeal"),
    noun("die", "Revision", "appeal on points of law"),
    noun("die", "Haftung", "liability"),
    noun("die", "Fahrlässigkeit", "negligence"),
    noun("die", "Notwehr", "self-defence"),
    noun("der", "Nachlass", "estate of the deceased"),
    noun("das", "Testament", "will"),
    noun("der", "Pflichtteil", "statutory share of an inheritance"),
    noun("die", "Vormundschaft", "guardianship"),
    noun("die", "Zwangsversteigerung", "forced auction"),
    noun("der", "Gläubiger", "creditor"),
    noun("der", "Schuldner", "debtor"),
    noun("das", "Inkasso", "debt collection"),
    noun("die", "Pfändung", "seizure of assets"),
    noun("der", "Bürge", "guarantor"),
  ]),
  part562: pack("Part 562", "B1", "Renting a flat", "The deposit, the service charges and the paperwork between one tenant and the next.", [
    noun("die", "Kaution", "rental deposit"),
    noun("die", "Nebenkosten", "service charges"),
    noun("der", "Mietvertrag", "tenancy agreement"),
    noun("die", "Betriebskostenabrechnung", "annual service charge statement"),
    noun("die", "Eigenbedarfskündigung", "eviction for the landlord's own use"),
    noun("die", "Wohnungsgenossenschaft", "housing cooperative"),
    noun("der", "Wohnberechtigungsschein", "certificate of eligibility for subsidised housing"),
    noun("das", "Führungszeugnis", "certificate of good conduct"),
    noun("die", "Ausweispflicht", "duty to carry ID"),
    noun("die", "Auskunft", "information given on request"),
    noun("die", "Sprechzeit", "opening hours for enquiries"),
    noun("die", "Bearbeitungsgebühr", "processing fee"),
    noun("die", "Dienststelle", "office of a public authority"),
    noun("das", "Amtsgericht", "local court"),
    noun("der", "Ombudsmann", "ombudsman"),
    noun("die", "Schlichtung", "mediation of a dispute"),
  ]),
  part563: pack("Part 563", "B2", "Parliament and the ballot box", "How a government is formed, argued with and voted out.", [
    noun("der", "Bundesrat", "Federal Council"),
    noun("die", "Koalition", "coalition"),
    noun("die", "Opposition", "opposition"),
    noun("das", "Mandat", "seat in parliament"),
    noun("die", "Legislaturperiode", "parliamentary term"),
    noun("das", "Kabinett", "cabinet"),
    noun("der", "Staatssekretär", "state secretary"),
    noun("die", "Volksabstimmung", "referendum"),
    noun("der", "Wahlzettel", "ballot paper"),
    noun("der", "Wahlkreis", "constituency"),
    noun("der", "Rücktritt", "resignation"),
    noun("das", "Misstrauensvotum", "vote of no confidence"),
    noun("das", "Grundrecht", "fundamental right"),
    noun("die", "Gleichbehandlung", "equal treatment"),
    noun("die", "Versammlungsfreiheit", "freedom of assembly"),
    noun("der", "Vertragsentwurf", "draft treaty"),
    noun("die", "Ratifizierung", "ratification"),
    noun("das", "Abkommen", "international agreement"),
    noun("die", "Sanktion", "sanction"),
    noun("der", "Botschafter", "ambassador"),
    noun("das", "Konsulat", "consulate"),
  ]),
  part564: pack("Part 564", "B1", "Arriving and staying", "The words on every form between the border and a passport.", [
    noun("das", "Visum", "visa"),
    noun("die", "Aufenthaltserlaubnis", "residence permit"),
    noun("der", "Asylantrag", "asylum application"),
    noun("die", "Abschiebung", "deportation"),
    noun("die", "Duldung", "temporary suspension of deportation"),
    noun("das", "Sprachzertifikat", "language certificate"),
    noun("die", "Anerkennungsstelle", "recognition authority"),
    noun("die", "Berufsanerkennung", "recognition of a professional qualification"),
    noun("die", "Staatsbürgerschaft", "citizenship"),
    noun("der", "Doppelpass", "dual citizenship"),
    noun("die", "Einbürgerung", "naturalisation"),
  ]),
  part565: pack("Part 565", "B1", "The hospital", "From the ambulance to the ward — what happens, who does it, and what it is called.", [
    noun("die", "Wiederbelebung", "resuscitation"),
    noun("die", "Bahre", "stretcher"),
    noun("die", "Infusion", "drip"),
    noun("die", "Narkose", "general anaesthetic"),
    noun("der", "Operationssaal", "operating theatre"),
    noun("die", "Nachsorge", "aftercare"),
    noun("die", "Ergotherapie", "occupational therapy"),
    noun("die", "Logopädie", "speech therapy"),
    noun("der", "Heilpraktiker", "alternative practitioner"),
    noun("die", "Homöopathie", "homeopathy"),
    noun("das", "Antibiotikum", "antibiotic"),
    noun("das", "Schmerzmittel", "painkiller"),
    noun("die", "Blutabnahme", "blood draw"),
    noun("der", "Abstrich", "swab"),
    noun("die", "Bluttransfusion", "blood transfusion"),
    noun("die", "Organspende", "organ donation"),
    noun("die", "Patientenverfügung", "living will"),
    noun("das", "Skalpell", "scalpel"),
    noun("die", "Kanüle", "cannula"),
    noun("das", "Stethoskop", "stethoscope"),
    noun("die", "Hygiene", "hygiene"),
    noun("die", "Desinfektion", "disinfection"),
    noun("die", "Sterilisation", "sterilisation"),
  ]),
  part566: pack("Part 566", "B1", "Illnesses by name", "What the diagnosis actually says, from a cold to a stroke.", [
    noun("das", "Asthma", "asthma"),
    noun("die", "Bronchitis", "bronchitis"),
    noun("die", "Lungenentzündung", "pneumonia"),
    noun("die", "Grippe", "flu"),
    noun("der", "Schüttelfrost", "shivering fit"),
    noun("die", "Zerrung", "pulled muscle"),
    noun("der", "Bänderriss", "torn ligament"),
    noun("die", "Arthrose", "osteoarthritis"),
    noun("das", "Rheuma", "rheumatism"),
    noun("die", "Osteoporose", "osteoporosis"),
    noun("der", "Diabetes", "diabetes"),
    noun("der", "Cholesterinspiegel", "cholesterol level"),
    noun("der", "Herzinfarkt", "heart attack"),
    noun("der", "Schlaganfall", "stroke"),
    noun("die", "Demenz", "dementia"),
    noun("die", "Depression", "depression"),
    noun("die", "Angststörung", "anxiety disorder"),
    noun("das", "Burnout", "burnout"),
    noun("die", "Quarantäne", "quarantine"),
    noun("die", "Ansteckung", "infection passed on"),
    noun("die", "Inkubationszeit", "incubation period"),
    noun("der", "Erreger", "pathogen"),
    noun("das", "Virus", "virus"),
    noun("das", "Bakterium", "bacterium"),
  ]),
  part567: pack("Part 567", "B1", "Teeth, eyes and ears", "The three specialists everyone ends up seeing, and what they fit.", [
    noun("der", "Zahnersatz", "dentures"),
    noun("die", "Plombe", "filling"),
    noun("die", "Zahnspange", "braces"),
    noun("die", "Prophylaxe", "preventive dental cleaning"),
    noun("die", "Kurzsichtigkeit", "short-sightedness"),
    noun("die", "Weitsichtigkeit", "long-sightedness"),
    noun("die", "Hornhaut", "cornea"),
    noun("die", "Netzhaut", "retina"),
    noun("die", "Sehhilfe", "visual aid"),
    noun("das", "Hörgerät", "hearing aid"),
    noun("der", "Tinnitus", "tinnitus"),
    noun("das", "Trommelfell", "eardrum"),
    noun("der", "Gleichgewichtssinn", "sense of balance"),
    noun("die", "Schiene", "splint"),
    noun("die", "Krankschreibung", "sick note"),
    noun("die", "Terminvergabe", "appointment booking"),
    noun("die", "Praxisgebühr", "surgery fee"),
    noun("die", "Chipkarte", "health insurance card"),
    noun("die", "Pflegestufe", "level of care needed"),
  ]),
  part568: pack("Part 568", "B1", "The shell of a building", "What a house is made of before anyone paints it — from the foundation to the roof.", [
    noun("der", "Rohbau", "shell of a building"),
    noun("das", "Fundament", "foundation"),
    noun("der", "Estrich", "screed"),
    noun("die", "Dämmung", "insulation"),
    noun("die", "Fassade", "facade"),
    noun("der", "Putz", "plaster on a wall"),
    noun("die", "Grundierung", "primer"),
    noun("die", "Spachtelmasse", "filler"),
    noun("das", "Silikon", "silicone sealant"),
    noun("der", "Fugenkitt", "grout"),
    noun("die", "Fuge", "joint between tiles"),
    noun("der", "Fliesenkleber", "tile adhesive"),
    noun("der", "Mörtel", "mortar"),
    noun("die", "Bewehrung", "steel reinforcement"),
    noun("der", "Stahlträger", "steel beam"),
    noun("der", "Balken", "wooden beam"),
    noun("der", "Dachstuhl", "roof truss"),
    noun("die", "Dachrinne", "gutter"),
    noun("das", "Fallrohr", "downpipe"),
    noun("der", "Kellerschacht", "basement light well"),
    noun("der", "Fensterrahmen", "window frame"),
    noun("die", "Doppelverglasung", "double glazing"),
    noun("der", "Rollladen", "roller shutter"),
    noun("das", "Rollo", "roller blind"),
    noun("die", "Markise", "awning"),
    noun("die", "Türschwelle", "threshold"),
    noun("der", "Türspion", "peephole"),
    noun("der", "Riegel", "bolt on a door"),
    noun("das", "Vorhängeschloss", "padlock"),
    noun("der", "Zylinder", "lock cylinder"),
    noun("das", "Gerüst", "scaffolding"),
    noun("die", "Trittleiter", "step ladder"),
    noun("der", "Container", "skip"),
  ]),
  part569: pack("Part 569", "B1", "Tools in the shed", "What is actually in the toolbox, named one by one.", [
    noun("der", "Akkuschrauber", "cordless screwdriver"),
    noun("der", "Schlagbohrer", "hammer drill"),
    noun("der", "Bohrhammer", "rotary hammer"),
    noun("die", "Stichsäge", "jigsaw"),
    noun("die", "Kreissäge", "circular saw"),
    noun("der", "Winkelschleifer", "angle grinder"),
    noun("die", "Schleifmaschine", "sander"),
    noun("der", "Hobel", "plane"),
    noun("die", "Feile", "file"),
    noun("die", "Raspel", "rasp"),
    noun("die", "Zwinge", "clamp"),
    noun("der", "Schraubstock", "vice"),
    noun("der", "Vorschlaghammer", "sledgehammer"),
    noun("der", "Meißel", "chisel"),
    noun("die", "Kneifzange", "pincers"),
    noun("die", "Rohrzange", "pipe wrench"),
    noun("der", "Schraubenschlüssel", "spanner"),
    noun("der", "Inbusschlüssel", "Allen key"),
    noun("der", "Ratschenkasten", "socket set"),
    noun("der", "Zollstock", "folding rule"),
    noun("die", "Schnur", "string"),
    noun("die", "Richtschnur", "guide line"),
    noun("das", "Lot", "plumb line"),
    noun("die", "Schablone", "stencil"),
    noun("die", "Schutzbrille", "safety goggles"),
    noun("der", "Gehörschutz", "ear defenders"),
    noun("die", "Staubmaske", "dust mask"),
    noun("der", "Arbeitshandschuh", "work glove"),
    noun("der", "Sicherheitsschuh", "safety shoe"),
    noun("die", "Schutzfolie", "protective film"),
    noun("das", "Abdeckvlies", "dust sheet"),
    noun("das", "Kreppband", "masking tape"),
    noun("das", "Montageband", "mounting tape"),
    noun("der", "Kabelbinder", "cable tie"),
    noun("die", "Schelle", "pipe clamp"),
  ]),
  part570: pack("Part 570", "B1", "Paint, glue and wiring", "The tins on the shelf and the box on the wall — what each is for.", [
    noun("die", "Beize", "wood stain"),
    noun("der", "Lack", "gloss paint"),
    noun("der", "Klarlack", "clear varnish"),
    noun("die", "Lasur", "wood glaze"),
    noun("der", "Firnis", "varnish on a painting"),
    noun("das", "Terpentin", "turpentine"),
    noun("die", "Verdünnung", "paint thinner"),
    noun("der", "Kleister", "wallpaper paste"),
    noun("der", "Holzleim", "wood glue"),
    noun("der", "Sekundenkleber", "superglue"),
    noun("das", "Schleifpapier", "sandpaper"),
    noun("der", "Sicherungskasten", "fuse box"),
    noun("der", "Fehlerstromschutzschalter", "residual current device"),
    noun("der", "Lichtschalter", "light switch"),
    noun("die", "Klemme", "terminal connector"),
    noun("der", "Verteilerkasten", "junction box"),
    noun("die", "Erdung", "earthing"),
    noun("die", "Leuchtstoffröhre", "fluorescent tube"),
    noun("der", "Bewegungsmelder", "motion sensor"),
    noun("die", "Zeitschaltuhr", "timer switch"),
    noun("der", "Stromzähler", "electricity meter"),
    noun("der", "Wasserzähler", "water meter"),
    noun("die", "Fußbodenheizung", "underfloor heating"),
    noun("die", "Zirkulationspumpe", "circulation pump"),
    noun("die", "Regenrinne", "roof channel"),
    noun("die", "Sickergrube", "soakaway"),
    noun("der", "Gully", "drain in the road"),
    noun("die", "Kanalisation", "sewer system"),
    noun("die", "Kläranlage", "sewage works"),
    noun("das", "Abwasser", "waste water"),
    noun("der", "Wasseranschluss", "water connection"),
    noun("der", "Hausanschluss", "utility connection to a house"),
  ]),
  part571: pack("Part 571", "B1", "On the farm", "The field, the barn and the animals in it — the words a village runs on.", [
    noun("der", "Acker", "field under crops"),
    noun("die", "Furche", "furrow"),
    noun("der", "Pflug", "plough"),
    noun("die", "Egge", "harrow"),
    noun("die", "Sämaschine", "seed drill"),
    noun("der", "Mähdrescher", "combine harvester"),
    noun("der", "Ertrag", "yield"),
    noun("die", "Aussaat", "sowing"),
    noun("die", "Fruchtfolge", "crop rotation"),
    noun("die", "Brache", "fallow land"),
    noun("die", "Gülle", "liquid manure"),
    noun("das", "Silo", "silo"),
    noun("die", "Scheune", "barn"),
    noun("der", "Stall", "animal shed"),
    noun("die", "Weidefläche", "grazing land"),
    noun("der", "Zaunpfahl", "fence post"),
    noun("der", "Stacheldraht", "barbed wire"),
    noun("die", "Herde", "herd"),
    noun("das", "Ferkel", "piglet"),
    noun("die", "Sau", "sow"),
    noun("der", "Eber", "boar"),
    noun("das", "Geflügel", "poultry"),
    noun("die", "Bruthenne", "brooding hen"),
    noun("der", "Trog", "trough"),
    noun("die", "Tränke", "drinking trough"),
    noun("der", "Hirte", "shepherd"),
    noun("der", "Schäferhund", "sheepdog"),
    noun("das", "Gatter", "gate in a fence"),
    noun("die", "Sense", "scythe"),
    noun("die", "Sichel", "sickle"),
    noun("der", "Rechen", "garden rake"),
    noun("die", "Mistgabel", "pitchfork"),
    noun("der", "Halm", "stalk"),
    noun("die", "Ähre", "ear of grain"),
    noun("die", "Spreu", "chaff"),
    noun("das", "Stroh", "straw"),
    noun("das", "Heu", "hay"),
    noun("das", "Korn", "grain"),
    noun("die", "Mühle", "mill"),
    noun("der", "Müller", "miller"),
  ]),
  part572: pack("Part 572", "B1", "Bees, vines and barrels", "Where honey, wine and beer come from before the shop.", [
    noun("der", "Bienenstock", "beehive"),
    noun("der", "Imker", "beekeeper"),
    noun("die", "Wabe", "honeycomb"),
    noun("der", "Nektar", "nectar"),
    noun("die", "Bestäubung", "pollination"),
    noun("der", "Obstgarten", "orchard"),
    noun("der", "Weinberg", "vineyard"),
    noun("die", "Rebe", "vine"),
    noun("die", "Lese", "grape harvest"),
    noun("der", "Winzer", "winemaker"),
    noun("die", "Presse", "press for fruit"),
    noun("der", "Most", "unfermented juice"),
    noun("die", "Gärung", "fermentation"),
    noun("das", "Malz", "malt"),
    noun("der", "Sud", "brewing liquid"),
    noun("die", "Destillation", "distillation"),
    noun("der", "Schnaps", "spirits"),
  ]),
  part573: pack("Part 573", "B1", "Deep in the woods", "What grows where the path stops — trees, berries and the ground under them.", [
    noun("der", "Waldrand", "edge of the wood"),
    noun("der", "Forst", "managed forest"),
    noun("das", "Unterholz", "undergrowth"),
    noun("der", "Waldweg", "forest track"),
    noun("die", "Schneise", "cleared strip through a wood"),
    noun("der", "Baumstumpf", "tree stump"),
    noun("der", "Zweig", "twig"),
    noun("der", "Trieb", "shoot on a plant"),
    noun("das", "Laub", "foliage"),
    noun("der", "Zapfen", "pine cone"),
    noun("die", "Baumkrone", "treetop"),
    noun("der", "Jahresring", "annual ring"),
    noun("das", "Harz", "resin"),
    noun("der", "Steinpilz", "porcini mushroom"),
    noun("der", "Pfifferling", "chanterelle"),
    noun("der", "Fliegenpilz", "fly agaric"),
    noun("die", "Flechte", "lichen"),
    noun("der", "Farnwedel", "fern frond"),
    noun("die", "Beere", "berry"),
    noun("die", "Brombeere", "blackberry"),
    noun("die", "Heidelbeere", "bilberry"),
    noun("die", "Preiselbeere", "lingonberry"),
    noun("die", "Hagebutte", "rosehip"),
    noun("der", "Holunder", "elder"),
    noun("die", "Eberesche", "rowan"),
    noun("die", "Erle", "alder"),
    noun("die", "Espe", "aspen"),
    noun("die", "Ulme", "elm"),
    noun("der", "Wacholder", "juniper"),
    noun("die", "Zeder", "cedar"),
    noun("die", "Agave", "agave"),
    noun("der", "Bambus", "bamboo"),
    noun("das", "Schilfrohr", "reed"),
    noun("die", "Seerose", "water lily"),
  ]),
  part574: pack("Part 574", "B1", "Water and coast", "Every kind of water on a map, and the edge it meets land at.", [
    noun("der", "Tümpel", "small pool"),
    noun("der", "Weiher", "pond"),
    noun("der", "Stausee", "reservoir"),
    noun("die", "Talsperre", "dam across a valley"),
    noun("die", "Böschung", "embankment"),
    noun("der", "Damm", "dyke"),
    noun("die", "Furt", "ford"),
    noun("der", "Steg", "footbridge"),
    noun("der", "Anleger", "landing stage"),
    noun("die", "Schleuse", "lock on a canal"),
    noun("die", "Mündung", "river mouth"),
    noun("der", "Nebenfluss", "tributary"),
    noun("das", "Delta", "delta"),
    noun("die", "Sandbank", "sandbank"),
    noun("das", "Watt", "tidal flats"),
    noun("die", "Düne", "dune"),
    noun("das", "Riff", "reef"),
    noun("die", "Bucht", "bay"),
    noun("das", "Kap", "cape"),
    noun("die", "Landzunge", "spit of land"),
    noun("die", "Halbinsel", "peninsula"),
    noun("der", "Archipel", "archipelago"),
  ]),
  part575: pack("Part 575", "B1", "What is on the plate", "The courses of a meal and the dishes a German menu actually lists.", [
    noun("die", "Nachspeise", "dessert course"),
    noun("die", "Sättigungsbeilage", "starchy side dish"),
    noun("die", "Brühe", "broth"),
    noun("der", "Fond", "cooking stock"),
    noun("die", "Sauce", "sauce"),
    noun("das", "Dressing", "salad dressing"),
    noun("die", "Vinaigrette", "vinaigrette"),
    noun("der", "Dip", "dip"),
    noun("die", "Paste", "paste"),
    noun("das", "Püree", "mash"),
    noun("der", "Auflauf", "bake"),
    noun("der", "Eintopf", "one-pot stew"),
    noun("die", "Suppe", "soup"),
    noun("die", "Cremesuppe", "cream soup"),
    noun("der", "Schmorbraten", "pot roast"),
    noun("das", "Gulasch", "goulash"),
    noun("die", "Roulade", "beef roll"),
    noun("die", "Bulette", "meat patty"),
    noun("die", "Bratwurst", "fried sausage"),
    noun("die", "Blutwurst", "black pudding"),
    noun("der", "Käseaufschnitt", "sliced cheese platter"),
    noun("der", "Frischkäse", "cream cheese"),
    noun("der", "Hartkäse", "hard cheese"),
    noun("der", "Weichkäse", "soft cheese"),
    noun("der", "Schimmelkäse", "blue cheese"),
    noun("die", "Molke", "whey"),
    noun("die", "Buttermilch", "buttermilk"),
    noun("die", "Schlagsahne", "whipped cream"),
    noun("der", "Schmand", "soured cream"),
  ]),
  part576: pack("Part 576", "B1", "Baking day", "Dough, filling and topping — what a German bakery window is made of.", [
    noun("der", "Pudding", "set custard"),
    noun("die", "Grütze", "fruit or grain porridge"),
    noun("der", "Grieß", "semolina"),
    noun("die", "Stärke", "starch for thickening"),
    noun("das", "Bindemittel", "thickening agent"),
    noun("der", "Hefeteig", "yeast dough"),
    noun("der", "Blätterteig", "puff pastry"),
    noun("der", "Mürbeteig", "shortcrust pastry"),
    noun("der", "Rührteig", "sponge batter"),
    noun("der", "Guss", "poured topping"),
    noun("der", "Zuckerguss", "icing"),
    noun("die", "Streusel", "crumble topping"),
    noun("die", "Kruste", "crust"),
    noun("die", "Krume", "crumb of a loaf"),
    noun("die", "Semmel", "bread roll in the south"),
    noun("der", "Hefezopf", "sweet plaited loaf"),
    noun("der", "Stollen", "Christmas fruit loaf"),
    noun("der", "Lebkuchen", "gingerbread"),
    noun("die", "Waffel", "waffle"),
    noun("der", "Pfannkuchen", "pancake"),
    noun("der", "Eierkuchen", "egg pancake"),
    noun("der", "Kaiserschmarrn", "shredded sweet pancake"),
    noun("der", "Knödel", "dumpling"),
    noun("der", "Kloß", "large dumpling"),
    noun("die", "Maultasche", "filled pasta pocket"),
  ]),
  part577: pack("Part 577", "B1", "Storing and preserving", "How food is kept from one season to the next, and the pans it is cooked in.", [
    noun("der", "Bräter", "roasting pot"),
    noun("der", "Schnellkochtopf", "pressure cooker"),
    noun("der", "Wok", "wok"),
    noun("der", "Spieß", "skewer"),
    noun("die", "Räucherkammer", "smokehouse"),
    noun("die", "Salzlake", "brine"),
    noun("das", "Pökelsalz", "curing salt"),
    noun("die", "Konserve", "tinned food"),
    noun("das", "Einweckglas", "preserving jar"),
    noun("der", "Gummiring", "rubber sealing ring"),
    noun("die", "Vorratskammer", "store cupboard"),
    noun("die", "Speisekammer", "larder"),
    noun("das", "Gefrierfach", "freezer compartment"),
    noun("die", "Gefriertruhe", "chest freezer"),
    noun("die", "Kühlkette", "cold chain"),
    noun("das", "Verfallsdatum", "expiry date"),
  ]),
  part578: pack("Part 578", "B1", "Reading the label", "What the small print on a packet says, and the counter it was bought at.", [
    noun("die", "Nährwerttabelle", "nutrition table"),
    noun("der", "Kaloriengehalt", "calorie content"),
    noun("das", "Kohlenhydrat", "carbohydrate"),
    noun("die", "Ballaststoffe", "dietary fibre"),
    noun("das", "Vitamin", "vitamin"),
    noun("das", "Mineral", "mineral"),
    noun("das", "Spurenelement", "trace element"),
    noun("der", "Farbstoff", "colouring"),
    noun("das", "Konservierungsmittel", "preservative"),
    noun("der", "Geschmacksverstärker", "flavour enhancer"),
    noun("die", "Lebensmittelkennzeichnung", "food labelling"),
    noun("die", "Allergenkennzeichnung", "allergen labelling"),
    noun("der", "Bioladen", "organic shop"),
    noun("das", "Siegel", "seal of quality"),
    noun("die", "Herkunftsangabe", "statement of origin"),
    noun("die", "Regionalität", "regional sourcing"),
    noun("die", "Saisonware", "seasonal produce"),
    noun("die", "Feinkost", "delicatessen food"),
    noun("die", "Fischtheke", "fish counter"),
    noun("der", "Fischhändler", "fishmonger"),
    noun("die", "Käsetheke", "cheese counter"),
    noun("die", "Weinhandlung", "wine shop"),
    noun("der", "Barkeeper", "bartender"),
    noun("die", "Zapfanlage", "beer tap system"),
    noun("das", "Fassbier", "draught beer"),
    noun("die", "Zeche", "the bill in a pub"),
    noun("die", "Trinkgeldkasse", "tip jar"),
  ]),
  part579: pack("Part 579", "B1", "Music on paper", "How a piece is written down, and what the room it is played in is fitted with.", [
    noun("die", "Tonart", "musical key"),
    noun("die", "Harmonie", "harmony"),
    noun("der", "Akkord", "chord"),
    noun("die", "Tonleiter", "scale"),
    noun("das", "Vorzeichen", "accidental in music"),
    noun("der", "Notenschlüssel", "clef"),
    noun("das", "Notenblatt", "sheet of music"),
    noun("die", "Partitur", "score"),
    noun("die", "Tonanlage", "sound system"),
    noun("der", "Verstärker", "amplifier"),
    noun("das", "Mischpult", "mixing desk"),
    noun("das", "Tonstudio", "recording studio"),
    noun("die", "Abmischung", "mix of a recording"),
    noun("die", "Nachbearbeitung", "post-production"),
  ]),
  part580: pack("Part 580", "B1", "Stage and screen", "Behind the curtain and behind the camera — who does what, and what it is called.", [
    noun("die", "Generalprobe", "dress rehearsal"),
    noun("der", "Applaus", "applause"),
    noun("die", "Requisite", "stage prop"),
    noun("der", "Souffleur", "prompter"),
    noun("der", "Vorspann", "opening credits"),
    noun("die", "Kameraführung", "camerawork"),
    noun("die", "Großaufnahme", "close-up"),
    noun("die", "Totale", "wide shot"),
    noun("der", "Zeitraffer", "time lapse"),
    noun("die", "Zeitlupe", "slow motion"),
    noun("der", "Dreh", "filming"),
    noun("der", "Drehort", "filming location"),
    noun("die", "Statisterie", "the extras"),
    noun("die", "Hauptrolle", "leading role"),
    noun("die", "Nebenrolle", "supporting role"),
    noun("das", "Casting", "casting"),
    noun("die", "Gage", "performer's fee"),
    noun("der", "Kinostart", "cinema release"),
    noun("die", "Erstaufführung", "premiere"),
    noun("die", "Nominierung", "nomination"),
    noun("die", "Preisverleihung", "awards ceremony"),
  ]),
  part581: pack("Part 581", "B1", "In front of the canvas", "How a picture is made, and the words a gallery describes it with.", [
    noun("die", "Staffelei", "easel"),
    noun("die", "Palette", "painter's palette"),
    noun("das", "Aquarell", "watercolour"),
    noun("das", "Ölgemälde", "oil painting"),
    noun("die", "Radierung", "etching"),
    noun("der", "Holzschnitt", "woodcut"),
    noun("der", "Kupferstich", "copperplate engraving"),
    noun("die", "Lithografie", "lithograph"),
    noun("die", "Skizze", "sketch"),
    noun("der", "Entwurf", "draft design"),
    noun("die", "Perspektive", "perspective"),
    noun("der", "Fluchtpunkt", "vanishing point"),
    noun("die", "Proportion", "proportion"),
    noun("der", "Farbton", "shade of colour"),
    noun("die", "Sättigung", "colour saturation"),
    noun("der", "Kontrast", "contrast"),
    noun("der", "Schattenwurf", "cast shadow"),
    noun("die", "Komposition", "composition of a picture"),
    noun("das", "Passepartout", "mount around a picture"),
    noun("die", "Vernissage", "private view"),
    noun("die", "Dauerleihgabe", "long-term loan to a museum"),
    noun("der", "Kurator", "curator"),
    noun("die", "Restaurierung", "restoration"),
    noun("die", "Fälschung", "forgery"),
    noun("die", "Provenienz", "provenance"),
    noun("der", "Auktionator", "auctioneer"),
    noun("das", "Höchstgebot", "highest bid"),
    noun("der", "Schätzwert", "estimated value"),
    noun("die", "Vitrine", "display case"),
  ]),
  part582: pack("Part 582", "B2", "Made by hand", "The workshop trades — clay, iron and precious stones.", [
    noun("die", "Skulptur", "sculpture"),
    noun("die", "Büste", "bust"),
    noun("das", "Relief", "relief carving"),
    noun("der", "Brennofen", "kiln"),
    noun("die", "Töpferscheibe", "potter's wheel"),
    noun("das", "Mosaik", "mosaic"),
    noun("das", "Buntglas", "stained glass"),
    noun("die", "Schmiede", "forge"),
    noun("der", "Blasebalg", "bellows"),
    noun("die", "Gravur", "engraving"),
    noun("der", "Edelstein", "gemstone"),
    noun("der", "Schliff", "cut of a stone"),
    noun("das", "Karat", "carat"),
    noun("die", "Perle", "pearl"),
    noun("der", "Ohrring", "earring"),
    noun("die", "Brosche", "brooch"),
  ]),
  part583: pack("Part 583", "B2", "Saying what you think of it", "Verbs for weighing something up, conceding a point and holding a line.", [
    verb("darlegen", "to set out an argument"),
    verb("eingestehen", "to admit"),
    verb("beschwichtigen", "to placate"),
    verb("bevormunden", "to patronise"),
    verb("belächeln", "to smile at pityingly"),
    verb("missbilligen", "to disapprove of"),
    verb("rügen", "to reprimand"),
    verb("ermahnen", "to admonish"),
    verb("mahnen", "to urge with a warning"),
    verb("nahelegen", "to strongly suggest"),
    verb("kundtun", "to make known"),
    verb("entlarven", "to expose someone"),
    verb("verschleiern", "to obscure deliberately"),
    verb("vertuschen", "to cover up"),
    verb("hintergehen", "to go behind someone's back"),
    verb("überlisten", "to outwit"),
    verb("umgarnen", "to charm into agreeing"),
    verb("erwägen", "to consider carefully"),
    verb("sichten", "to go through and sort"),
    verb("umreißen", "to outline"),
    verb("hinnehmen", "to accept without protest"),
    verb("erdulden", "to endure"),
    verb("ausharren", "to hold out"),
    verb("trotzen", "to defy"),
    verb("wappnen", "to brace yourself"),
    verb("verhelfen", "to help someone to something"),
    verb("vereiteln", "to thwart"),
    verb("unterbinden", "to put a stop to"),
    verb("schmälern", "to diminish"),
    verb("zuspitzen", "to come to a head"),
    verb("überbrücken", "to bridge a gap"),
    verb("festigen", "to consolidate"),
    verb("zerstreuen", "to dispel doubts"),
  ]),
  part584: pack("Part 584", "B2", "Precise words for how something is done", "Adjectives that judge the work rather than the thing — thorough, groundbreaking, half-hearted.", [
    adjective("akribisch", "meticulous"),
    adjective("bahnbrechend", "groundbreaking"),
    adjective("prägnant", "concise and pointed"),
    adjective("halbherzig", "half-hearted"),
    adjective("ausgeklügelt", "ingeniously worked out"),
  ]),
};
