import { Phrase } from "./types";

/**
 * Hand-curated everyday German phrasebank.
 *
 * Each topic becomes a bundled lesson "Part" (see contentBank.ts). These are
 * checked, natural sentences a German actually uses day to day — the reliable,
 * offline core of the app. The remote APIs only ever *add* on top of this.
 */
export interface CuratedTopic {
  id: string;          // becomes the part key, e.g. "cb-greetings"
  label: string;
  level: string;       // A1 / A2 / B1
  theme: string;
  description: string;
  focus: string;
  phrases: Phrase[];
}

export const curatedTopics: CuratedTopic[] = [
  {
    id: "cb-greetings",
    label: "Greetings & politeness",
    level: "A1",
    theme: "Greetings & politeness",
    description: "The everyday hellos, goodbyes, and polite words you need in every single conversation.",
    focus: "Greet people, say please and thank you, and react politely.",
    phrases: [
      { de: "Hallo!", en: "Hello!", use: "Everyday greeting", fr: "Salut !" },
      { de: "Guten Morgen!", en: "Good morning!", use: "Until about 11am", fr: "Bonjour !" },
      { de: "Guten Tag!", en: "Good day! / Hello!", use: "Neutral daytime greeting", fr: "Bonjour !" },
      { de: "Guten Abend!", en: "Good evening!", use: "From early evening", fr: "Bonsoir !" },
      { de: "Gute Nacht!", en: "Good night!", use: "Going to bed", fr: "Bonne nuit !" },
      { de: "Tschüss!", en: "Bye!", use: "Casual goodbye", fr: "À plus !" },
      { de: "Auf Wiedersehen!", en: "Goodbye.", use: "Formal goodbye", fr: "Au revoir !" },
      { de: "Bis später!", en: "See you later!", use: "Leaving for now", fr: "À plus tard !" },
      { de: "Bis morgen!", en: "See you tomorrow!", use: "Parting until next day", fr: "À demain !" },
      { de: "Wie geht es dir?", en: "How are you? / How are you doing? / How is it going?", use: "Informal", fr: "Comment vas-tu ?" },
      { de: "Wie geht es Ihnen?", en: "How are you? / How are you doing?", use: "Formal", fr: "Comment allez-vous ?" },
      { de: "Mir geht es gut, danke.", en: "I'm fine, thanks. / I'm good, thanks. / I'm doing well, thanks.", use: "Standard reply", fr: "Je vais bien, merci." },
      { de: "Und dir?", en: "And you?", use: "Returning the question", fr: "Et toi ?" },
      { de: "Danke schön!", en: "Thank you very much! / Thanks a lot! / Thank you!", use: "Polite thanks", fr: "Merci beaucoup !" },
      { de: "Vielen Dank!", en: "Many thanks! / Thank you very much! / Thanks a lot!", use: "Stronger thanks", fr: "Mille mercis !" },
      { de: "Bitte schön.", en: "You're welcome. / Here you go.", use: "Reply to thanks", fr: "Je vous en prie." },
      { de: "Gern geschehen.", en: "My pleasure. / You're welcome.", use: "Reply to thanks", fr: "Avec plaisir." },
      { de: "Entschuldigung!", en: "Excuse me!", use: "Getting attention or apologising", fr: "Excusez-moi !" },
      { de: "Es tut mir leid.", en: "I'm sorry.", use: "Genuine apology", fr: "Je suis désolé." },
      { de: "Kein Problem.", en: "No problem.", use: "Reassuring", fr: "Pas de problème." },
    ],
  },
  {
    id: "cb-introductions",
    label: "Introducing yourself",
    level: "A1",
    theme: "Introducing yourself",
    description: "Say who you are, where you're from, and ask the same of others.",
    focus: "Names, origin, languages, and first-meeting small talk.",
    phrases: [
      { de: "Wie heißt du?", en: "What's your name? / What are you called?", use: "Informal" },
      { de: "Wie heißen Sie?", en: "What's your name? / What are you called?", use: "Formal" },
      { de: "Ich heiße Anna.", en: "My name is Anna. / I am called Anna.", use: "Stating your name" },
      { de: "Ich bin Tom.", en: "I'm Tom.", use: "Casual self-intro" },
      { de: "Freut mich!", en: "Nice to meet you! / Pleased to meet you!", use: "On being introduced" },
      { de: "Woher kommst du?", en: "Where are you from?", use: "Informal" },
      { de: "Ich komme aus England.", en: "I'm from England.", use: "Stating origin" },
      { de: "Wo wohnst du?", en: "Where do you live?", use: "Asking location" },
      { de: "Ich wohne in Berlin.", en: "I live in Berlin.", use: "Stating where you live" },
      { de: "Was machst du beruflich?", en: "What do you do for work? / What do you do for a living? / What is your job?", use: "Asking job" },
      { de: "Ich bin Studentin.", en: "I'm a student.", use: "Stating occupation (female)" },
      { de: "Ich arbeite als Lehrer.", en: "I work as a teacher.", use: "Stating job" },
      { de: "Wie alt bist du?", en: "How old are you?", use: "Asking age" },
      { de: "Ich bin dreißig Jahre alt.", en: "I'm thirty years old.", use: "Stating age" },
      { de: "Sprichst du Englisch?", en: "Do you speak English?", use: "Very useful question" },
      { de: "Ich spreche ein bisschen Deutsch.", en: "I speak a little German.", use: "Managing expectations" },
      { de: "Ich lerne gerade Deutsch.", en: "I'm currently learning German.", use: "Explaining your level" },
      { de: "Können Sie das bitte wiederholen?", en: "Could you repeat that, please?", use: "When you didn't catch it" },
    ],
  },
  {
    id: "cb-smalltalk",
    label: "Small talk & feelings",
    level: "A2",
    theme: "Small talk & feelings",
    description: "Keep a conversation going and say how you really feel.",
    focus: "React naturally, express moods, and fill pauses like a native.",
    phrases: [
      { de: "Was gibt's Neues?", en: "What's new?", use: "Casual opener" },
      { de: "Alles klar?", en: "Everything okay?", use: "Very common check-in" },
      { de: "Alles gut.", en: "All good.", use: "Reassuring reply" },
      { de: "Ich bin müde.", en: "I'm tired.", use: "Stating a feeling" },
      { de: "Ich bin glücklich.", en: "I'm happy.", use: "Positive feeling" },
      { de: "Ich bin gestresst.", en: "I'm stressed.", use: "Common complaint" },
      { de: "Ich habe Hunger.", en: "I'm hungry. / I have hunger.", use: "Literally 'I have hunger'" },
      { de: "Ich habe Durst.", en: "I'm thirsty. / I have thirst.", use: "Literally 'I have thirst'" },
      { de: "Das freut mich.", en: "I'm glad to hear that.", use: "Positive reaction" },
      { de: "Schade!", en: "What a shame! / Too bad! / That is a shame!", use: "Disappointment" },
      { de: "Genau!", en: "Exactly!", use: "Agreement" },
      { de: "Ach so!", en: "Oh, I see!", use: "Understanding something" },
      { de: "Wirklich?", en: "Really?", use: "Surprise" },
      { de: "Kein Stress.", en: "No worries. / No stress.", use: "Calming someone" },
      { de: "Viel Glück!", en: "Good luck!", use: "Wishing well" },
      { de: "Mach's gut!", en: "Take care!", use: "Warm goodbye" },
      { de: "Wie war dein Tag?", en: "How was your day?", use: "Everyday question" },
      { de: "Ich kann es kaum erwarten.", en: "I can hardly wait.", use: "Excitement" },
    ],
  },
  {
    id: "cb-numbers-time",
    label: "Numbers, time & dates",
    level: "A1",
    theme: "Numbers, time & dates",
    description: "Tell the time, name the day, and handle numbers in real situations.",
    focus: "Ask and give times, days, and quantities.",
    phrases: [
      { de: "Wie spät ist es?", en: "What time is it? / How late is it?", use: "Asking the time" },
      { de: "Es ist drei Uhr.", en: "It's three o'clock.", use: "Telling time" },
      { de: "Es ist halb acht.", en: "It's half past seven. / It's half seven.", use: "Careful: 'halb acht' = 7:30" },
      { de: "Es ist Viertel nach neun.", en: "It's quarter past nine. / It's quarter after nine.", use: "Telling time" },
      { de: "Um wie viel Uhr?", en: "At what time? / What time?", use: "Asking for an exact time" },
      { de: "Welcher Tag ist heute?", en: "What day is it today?", use: "Asking the day" },
      { de: "Heute ist Montag.", en: "Today is Monday.", use: "Stating the day" },
      { de: "Morgen ist Freitag.", en: "Tomorrow is Friday.", use: "Talking about days" },
      { de: "Am Wochenende habe ich Zeit.", en: "I have time at the weekend. / I have time on the weekend.", use: "Planning" },
      { de: "Welches Datum haben wir heute?", en: "What's the date today? / What is today's date?", use: "Asking the date" },
      { de: "Ich habe um zehn Uhr einen Termin.", en: "I have an appointment at ten.", use: "Scheduling" },
      { de: "Wie viel kostet das?", en: "How much does that cost? / How much is that? / What does that cost?", use: "Numbers in shops" },
      { de: "Das macht zwölf Euro.", en: "That comes to twelve euros. / That is twelve euros. / That makes twelve euros.", use: "Hearing a price" },
      { de: "Ich komme in fünf Minuten.", en: "I'll be there in five minutes. / I am coming in five minutes. / I will come in five minutes.", use: "Time estimate" },
      { de: "Es ist noch früh.", en: "It's still early.", use: "Time comment" },
      { de: "Es ist schon spät.", en: "It's already late.", use: "Time comment" },
    ],
  },
  {
    id: "cb-shopping",
    label: "Shopping & money",
    level: "A1",
    theme: "Shopping & money",
    description: "Buy things, ask prices, and pay without stress.",
    focus: "Prices, payment, sizes, and asking for what you want.",
    phrases: [
      { de: "Was kostet das?", en: "How much is this? / What does this cost? / How much does this cost?", use: "Asking a price" },
      { de: "Das ist zu teuer.", en: "That's too expensive.", use: "Reacting to a price" },
      { de: "Haben Sie das in einer anderen Größe?", en: "Do you have this in another size?", use: "Clothes shopping" },
      { de: "Kann ich das anprobieren?", en: "Can I try this on?", use: "Clothes shopping" },
      { de: "Ich schaue nur, danke.", en: "I'm just looking, thanks.", use: "To a salesperson" },
      { de: "Ich nehme das.", en: "I'll take it. / I will take this.", use: "Deciding to buy" },
      { de: "Kann ich mit Karte zahlen?", en: "Can I pay by card?", use: "At the till" },
      { de: "Ich zahle bar.", en: "I'll pay cash.", use: "At the till" },
      { de: "Wo ist die Kasse?", en: "Where's the checkout? / Where is the till? / Where is the cash register?", use: "Finding the till" },
      { de: "Brauchen Sie eine Tüte?", en: "Do you need a bag?", use: "You may be asked this" },
      { de: "Einen Moment, bitte.", en: "One moment, please.", use: "Buying time" },
      { de: "Haben Sie das auf Lager?", en: "Do you have this in stock?", use: "Checking availability" },
      { de: "Wo finde ich das?", en: "Where can I find this? / Where do I find this?", use: "Asking in a shop" },
      { de: "Können Sie mir helfen?", en: "Can you help me?", use: "Asking for help" },
      { de: "Ich hätte gern eine Quittung.", en: "I'd like a receipt.", use: "After paying" },
      { de: "Stimmt so.", en: "Keep the change.", use: "When paying with a tip" },
    ],
  },
  {
    id: "cb-food",
    label: "Food & restaurant",
    level: "A2",
    theme: "Food & restaurant",
    description: "Order food and drink and handle a café or restaurant with confidence.",
    focus: "Ordering, asking for the menu, and paying.",
    phrases: [
      { de: "Einen Tisch für zwei, bitte.", en: "A table for two, please.", use: "Arriving" },
      { de: "Die Speisekarte, bitte.", en: "The menu, please.", use: "Getting started" },
      { de: "Was können Sie empfehlen?", en: "What can you recommend?", use: "Asking for tips" },
      { de: "Ich hätte gern einen Kaffee.", en: "I'd like a coffee.", use: "Ordering politely" },
      { de: "Ich nehme das Schnitzel.", en: "I'll have the schnitzel. / I will take the schnitzel.", use: "Ordering a dish" },
      { de: "Für mich bitte ein Wasser.", en: "A water for me, please.", use: "Ordering a drink" },
      { de: "Zum Mitnehmen, bitte.", en: "To take away, please. / To go, please.", use: "Takeaway" },
      { de: "Ich bin Vegetarier.", en: "I'm a vegetarian.", use: "Dietary need" },
      { de: "Hat das Nüsse?", en: "Does this have nuts?", use: "Allergy check" },
      { de: "Guten Appetit!", en: "Enjoy your meal! / Bon appetit!", use: "Said before eating" },
      { de: "Es schmeckt sehr gut.", en: "It tastes great. / It tastes very good. / It tastes really good.", use: "Complimenting the food" },
      { de: "Können wir bitte zahlen?", en: "Could we pay, please?", use: "Asking for the bill" },
      { de: "Die Rechnung, bitte.", en: "The bill, please. / The check, please.", use: "Asking for the bill" },
      { de: "Zusammen oder getrennt?", en: "Together or separately?", use: "You'll be asked this" },
      { de: "Getrennt, bitte.", en: "Separately, please.", use: "Splitting the bill" },
      { de: "Das hat gut geschmeckt, danke.", en: "That was delicious, thank you. / That tasted good, thanks.", use: "Leaving happy" },
    ],
  },
  {
    id: "cb-directions",
    label: "Directions & transport",
    level: "A2",
    theme: "Directions & transport",
    description: "Find your way and use buses, trains, and taxis.",
    focus: "Ask for directions, buy tickets, and understand replies.",
    phrases: [
      { de: "Entschuldigung, wo ist der Bahnhof?", en: "Excuse me, where's the station? / Excuse me, where is the train station?", use: "Asking directions" },
      { de: "Wie komme ich zum Zentrum?", en: "How do I get to the centre?", use: "Asking the way" },
      { de: "Ist es weit von hier?", en: "Is it far from here?", use: "Checking distance" },
      { de: "Gehen Sie geradeaus.", en: "Go straight ahead.", use: "Typical reply" },
      { de: "Biegen Sie links ab.", en: "Turn left.", use: "Typical reply" },
      { de: "Biegen Sie rechts ab.", en: "Turn right.", use: "Typical reply" },
      { de: "Es ist gleich um die Ecke.", en: "It's just around the corner.", use: "Typical reply" },
      { de: "Ich habe mich verlaufen.", en: "I'm lost.", use: "On foot" },
      { de: "Eine Fahrkarte nach München, bitte.", en: "A ticket to Munich, please.", use: "Buying a ticket" },
      { de: "Wann fährt der nächste Zug?", en: "When does the next train leave? / When is the next train? / When does the next train go?", use: "Timetable" },
      { de: "Von welchem Gleis fährt der Zug?", en: "Which platform does the train leave from?", use: "At the station" },
      { de: "Hält dieser Bus am Markt?", en: "Does this bus stop at the market?", use: "On the bus" },
      { de: "Wo muss ich umsteigen?", en: "Where do I have to change? / Where do I need to change? / Where do I change trains?", use: "Connections" },
      { de: "Können Sie mir ein Taxi rufen?", en: "Can you call me a taxi?", use: "At a hotel" },
      { de: "Halten Sie hier, bitte.", en: "Stop here, please.", use: "In a taxi" },
      { de: "Wie lange dauert die Fahrt?", en: "How long does the trip take? / How long does the journey take? / How long is the trip?", use: "Checking duration" },
    ],
  },
  {
    id: "cb-hotel",
    label: "Hotel & accommodation",
    level: "A2",
    theme: "Hotel & accommodation",
    description: "Check in, ask about your room, and handle problems.",
    focus: "Bookings, facilities, and check-out.",
    phrases: [
      { de: "Ich habe ein Zimmer reserviert.", en: "I have a room booked. / I have booked a room. / I have a reservation.", use: "Checking in" },
      { de: "Haben Sie ein Zimmer frei?", en: "Do you have a room available? / Do you have a room free? / Do you have a free room?", use: "Without a booking" },
      { de: "Ein Einzelzimmer, bitte.", en: "A single room, please.", use: "Room type" },
      { de: "Ein Doppelzimmer für drei Nächte.", en: "A double room for three nights.", use: "Booking" },
      { de: "Was kostet die Nacht?", en: "How much is it per night? / What does the night cost? / How much does the night cost? / What is the cost for the night? / How much is the night?", use: "Asking the rate" },
      { de: "Ist das Frühstück inklusive?", en: "Is breakfast included?", use: "Checking" },
      { de: "Um wie viel Uhr ist Check-out?", en: "What time is check-out?", use: "Practical question" },
      { de: "Wo ist der Aufzug?", en: "Where's the lift? / Where is the elevator?", use: "Finding your way" },
      { de: "Das WLAN funktioniert nicht.", en: "The Wi-Fi isn't working.", use: "Reporting a problem" },
      { de: "Die Heizung ist kaputt.", en: "The heating is broken.", use: "Reporting a problem" },
      { de: "Können Sie das Zimmer reinigen?", en: "Could you clean the room?", use: "Request" },
      { de: "Ich möchte auschecken.", en: "I'd like to check out.", use: "Leaving" },
      { de: "Kann ich mein Gepäck hier lassen?", en: "Can I leave my luggage here?", use: "After check-out" },
      { de: "Können Sie ein Taxi bestellen?", en: "Could you order a taxi?", use: "Leaving" },
    ],
  },
  {
    id: "cb-work",
    label: "At work & office",
    level: "B1",
    theme: "At work & office",
    description: "Get through a workday: meetings, emails, and colleagues.",
    focus: "Professional everyday language and polite requests.",
    phrases: [
      { de: "Ich habe eine Frage.", en: "I have a question.", use: "In a meeting" },
      { de: "Können wir kurz sprechen?", en: "Can we talk for a moment?", use: "Pulling someone aside" },
      { de: "Ich kümmere mich darum.", en: "I'll take care of it.", use: "Taking on a task" },
      { de: "Das mache ich sofort.", en: "I'll do that right away.", use: "Confirming" },
      { de: "Können Sie mir das erklären?", en: "Could you explain that to me?", use: "Asking for clarity" },
      { de: "Ich bin in einer Besprechung.", en: "I'm in a meeting.", use: "Being unavailable" },
      { de: "Ich schicke Ihnen eine E-Mail.", en: "I'll send you an email. / I will email you. / I send you an email. / I'm sending you an email.", use: "Following up" },
      { de: "Haben Sie kurz Zeit?", en: "Do you have a minute? / Do you have a moment?", use: "Polite interruption" },
      { de: "Wann ist die Frist?", en: "When's the deadline? / What is the deadline?", use: "Checking timing" },
      { de: "Das Meeting wurde verschoben.", en: "The meeting was postponed.", use: "Schedule change" },
      { de: "Ich bin damit einverstanden.", en: "I agree with that.", use: "Agreeing" },
      { de: "Das sehe ich anders.", en: "I see it differently.", use: "Polite disagreement" },
      { de: "Können wir einen Termin vereinbaren?", en: "Can we arrange a meeting? / Can we book an appointment? / Can we schedule an appointment? / Can we make an appointment?", use: "Scheduling" },
      { de: "Ich melde mich später.", en: "I'll get back to you later.", use: "Deferring" },
      { de: "Vielen Dank für Ihre Hilfe.", en: "Thank you for your help.", use: "Closing politely" },
      { de: "Schönen Feierabend!", en: "Have a good evening (after work)!", use: "End of workday" },
    ],
  },
  {
    id: "cb-health",
    label: "Doctor & health",
    level: "B1",
    theme: "Doctor & health",
    description: "Describe symptoms and get help at a doctor or pharmacy.",
    focus: "Symptoms, appointments, and pharmacy basics.",
    phrases: [
      { de: "Ich fühle mich nicht gut.", en: "I don't feel well.", use: "General complaint" },
      { de: "Ich bin krank.", en: "I'm ill. / I am sick.", use: "Stating you're sick" },
      { de: "Ich habe Kopfschmerzen.", en: "I have a headache.", use: "Symptom" },
      { de: "Ich habe Bauchschmerzen.", en: "I have a stomach ache.", use: "Symptom" },
      { de: "Mir ist schlecht.", en: "I feel sick.", use: "Symptom" },
      { de: "Ich habe Fieber.", en: "I have a fever.", use: "Symptom" },
      { de: "Ich brauche einen Arzt.", en: "I need a doctor.", use: "Urgent" },
      { de: "Ich möchte einen Termin machen.", en: "I'd like to make an appointment.", use: "At the practice" },
      { de: "Wo tut es weh?", en: "Where does it hurt?", use: "The doctor may ask" },
      { de: "Es tut hier weh.", en: "It hurts here.", use: "Pointing" },
      { de: "Ich bin gegen Penicillin allergisch.", en: "I'm allergic to penicillin.", use: "Important info" },
      { de: "Haben Sie etwas gegen Husten?", en: "Do you have something for a cough?", use: "At the pharmacy" },
      { de: "Wie oft soll ich das nehmen?", en: "How often should I take this?", use: "Medication" },
      { de: "Wo ist die nächste Apotheke?", en: "Where's the nearest pharmacy? / Where is the closest pharmacy?", use: "Finding help" },
      { de: "Rufen Sie einen Krankenwagen!", en: "Call an ambulance!", use: "Emergency" },
    ],
  },
  {
    id: "cb-phone",
    label: "Phone & internet",
    level: "A2",
    theme: "Phone & internet",
    description: "Make calls, leave messages, and get online.",
    focus: "Phone etiquette and connectivity basics.",
    phrases: [
      { de: "Hallo, wer ist da?", en: "Hello, who's calling? / Hello, who is it? / Hello, who is there?", use: "Answering" },
      { de: "Kann ich bitte mit Herrn Müller sprechen?", en: "May I speak to Mr Müller, please?", use: "Asking for someone" },
      { de: "Einen Moment, ich verbinde Sie.", en: "One moment, I'll put you through.", use: "Transferring" },
      { de: "Er ist gerade nicht da.", en: "He's not here right now.", use: "Taking a message" },
      { de: "Kann ich etwas ausrichten?", en: "Can I take a message?", use: "On the phone" },
      { de: "Können Sie mich zurückrufen?", en: "Could you call me back?", use: "Request" },
      { de: "Die Verbindung ist schlecht.", en: "The connection is bad.", use: "Poor signal" },
      { de: "Ich kann Sie nicht hören.", en: "I can't hear you.", use: "Call problem" },
      { de: "Wie ist das WLAN-Passwort?", en: "What's the Wi-Fi password?", use: "Getting online" },
      { de: "Ich habe kein Netz.", en: "I have no signal. / I have no service. / I have no reception.", use: "Mobile data" },
      { de: "Mein Akku ist fast leer.", en: "My battery is almost dead. / My battery is almost empty.", use: "Common complaint" },
      { de: "Kann ich mein Handy hier aufladen?", en: "Can I charge my phone here?", use: "Request" },
      { de: "Ich schreibe dir eine Nachricht.", en: "I'll text you. / I will write you a message. / I will send you a message. / I write you a message. / I'm writing you a message.", use: "Messaging" },
      { de: "Schick mir die Adresse.", en: "Send me the address.", use: "Casual request" },
    ],
  },
  {
    id: "cb-plans",
    label: "Plans & invitations",
    level: "A2",
    theme: "Plans & invitations",
    description: "Make plans, invite people, and accept or decline.",
    focus: "Suggesting, agreeing, and arranging to meet.",
    phrases: [
      { de: "Hast du heute Abend Zeit?", en: "Are you free this evening? / Do you have time this evening? / Are you free tonight? / Do you have time tonight?", use: "Making plans" },
      { de: "Wollen wir uns treffen?", en: "Shall we meet up? / Shall we meet? / Do we want to meet?", use: "Suggesting" },
      { de: "Hast du Lust auf einen Kaffee?", en: "Do you fancy a coffee? / Do you feel like a coffee? / Are you up for a coffee?", use: "Casual invite" },
      { de: "Wann passt es dir?", en: "When suits you? / When works for you? / When does it suit you?", use: "Finding a time" },
      { de: "Wo treffen wir uns?", en: "Where shall we meet?", use: "Setting a place" },
      { de: "Treffen wir uns um acht.", en: "Let's meet at eight.", use: "Proposing a time" },
      { de: "Das klingt gut!", en: "That sounds good!", use: "Accepting" },
      { de: "Gerne!", en: "Gladly!", use: "Enthusiastic yes" },
      { de: "Ich kann leider nicht.", en: "Unfortunately I can't. / I can't, unfortunately. / Sadly I can't.", use: "Declining" },
      { de: "Vielleicht ein anderes Mal.", en: "Maybe another time.", use: "Soft decline" },
      { de: "Ich muss leider absagen.", en: "I'm afraid I have to cancel. / Unfortunately I have to cancel.", use: "Cancelling" },
      { de: "Kommst du mit?", en: "Are you coming along? / Are you coming? / Are you coming with?", use: "Inviting" },
      { de: "Bring doch jemanden mit.", en: "Feel free to bring someone.", use: "Open invite" },
      { de: "Wir sehen uns dann!", en: "See you then!", use: "Confirming" },
      { de: "Ich freue mich darauf.", en: "I'm looking forward to it.", use: "Showing enthusiasm" },
    ],
  },
  {
    id: "cb-opinions",
    label: "Opinions & discussion",
    level: "B1",
    theme: "Opinions & discussion",
    description: "Say what you think, agree, disagree, and explain why.",
    focus: "Expressing and supporting opinions naturally.",
    phrases: [
      { de: "Ich denke, dass das stimmt.", en: "I think that's right. / I think that is true.", use: "Stating a view" },
      { de: "Meiner Meinung nach ist das falsch.", en: "In my opinion, that's wrong.", use: "Opinion phrase" },
      { de: "Ich finde das interessant.", en: "I find that interesting.", use: "Reacting" },
      { de: "Da hast du recht.", en: "You're right about that. / You're right.", use: "Agreeing" },
      { de: "Das stimmt nicht ganz.", en: "That's not quite right. / That is not quite true.", use: "Mild disagreement" },
      { de: "Ich bin mir nicht sicher.", en: "I'm not sure.", use: "Hedging" },
      { de: "Es kommt darauf an.", en: "It depends.", use: "Very common reply" },
      { de: "Einerseits ja, andererseits nein.", en: "On one hand yes, on the other no.", use: "Balanced view" },
      { de: "Was meinst du dazu?", en: "What do you think about it? / What do you think?", use: "Inviting opinion" },
      { de: "Ich sehe das genauso.", en: "I see it the same way.", use: "Strong agreement" },
      { de: "Das ist eine gute Frage.", en: "That's a good question.", use: "Buying time" },
      { de: "Ehrlich gesagt, finde ich das schwierig.", en: "Honestly, I find that difficult.", use: "Candid view" },
      { de: "Zum Beispiel?", en: "For example?", use: "Asking for detail" },
      { de: "Genau das meine ich.", en: "That's exactly what I mean.", use: "Emphasis" },
      { de: "Ich verstehe deinen Punkt.", en: "I understand your point.", use: "Acknowledging" },
    ],
  },
  {
    id: "cb-emergencies",
    label: "Problems & emergencies",
    level: "A2",
    theme: "Problems & emergencies",
    description: "Get help fast when something goes wrong.",
    focus: "Asking for help, reporting problems, and emergencies.",
    phrases: [
      { de: "Hilfe!", en: "Help!", use: "Emergency" },
      { de: "Können Sie mir helfen?", en: "Can you help me?", use: "Asking for help" },
      { de: "Ich brauche Hilfe.", en: "I need help.", use: "Stating need" },
      { de: "Rufen Sie die Polizei!", en: "Call the police!", use: "Emergency" },
      { de: "Es ist ein Notfall.", en: "It's an emergency.", use: "Urgent" },
      { de: "Ich habe meinen Pass verloren.", en: "I've lost my passport.", use: "Reporting a loss" },
      { de: "Mein Handy wurde gestohlen.", en: "My phone was stolen.", use: "Reporting theft" },
      { de: "Ich habe mich verirrt.", en: "I've got lost. / I'm lost. / I got lost.", use: "Lost" },
      { de: "Wo ist das nächste Krankenhaus?", en: "Where's the nearest hospital? / Where is the closest hospital?", use: "Finding help" },
      { de: "Sprechen Sie Englisch?", en: "Do you speak English?", use: "Finding a common language" },
      { de: "Ich verstehe das nicht.", en: "I don't understand.", use: "Communication breakdown" },
      { de: "Langsamer, bitte.", en: "Slower, please.", use: "Asking to slow down" },
      { de: "Was soll ich tun?", en: "What should I do?", use: "Seeking guidance" },
      { de: "Bleiben Sie ruhig.", en: "Stay calm.", use: "Reassuring" },
    ],
  },
  {
    id: "cb-routine",
    label: "Daily routine & home",
    level: "A2",
    theme: "Daily routine & home",
    description: "Talk about your day, your home, and household tasks.",
    focus: "Describing routines and everyday actions.",
    phrases: [
      { de: "Ich stehe um sieben Uhr auf.", en: "I get up at seven.", use: "Routine" },
      { de: "Ich dusche und frühstücke.", en: "I shower and have breakfast.", use: "Morning routine" },
      { de: "Ich fahre zur Arbeit.", en: "I drive to work.", use: "Routine" },
      { de: "Ich arbeite den ganzen Tag.", en: "I work all day.", use: "Routine" },
      { de: "Ich koche das Abendessen.", en: "I cook dinner.", use: "Evening routine" },
      { de: "Ich räume die Küche auf.", en: "I tidy up the kitchen.", use: "Chores" },
      { de: "Ich muss noch einkaufen.", en: "I still have to do the shopping. / I still have to go shopping. / I still need to do the shopping.", use: "Errand" },
      { de: "Ich wasche die Wäsche.", en: "I'm doing the laundry. / I'm washing the laundry. / I wash the laundry.", use: "Chores" },
      { de: "Ich gehe früh ins Bett.", en: "I go to bed early.", use: "Routine" },
      { de: "Ich bin gleich fertig.", en: "I'm almost done. / I'm almost ready. / I'm almost finished.", use: "At home" },
      { de: "Kannst du mir kurz helfen?", en: "Can you help me for a second? / Can you help me for a moment? / Can you quickly help me?", use: "Household request" },
      { de: "Das Licht ist noch an.", en: "The light is still on.", use: "Around the house" },
      { de: "Ich habe keine Zeit.", en: "I don't have time.", use: "Very common" },
      { de: "Heute bleibe ich zu Hause.", en: "Today I'm staying home. / Today I'm staying at home. / I'm staying home today.", use: "Plans" },
    ],
  },
  {
    id: "cb-weather",
    label: "Weather & seasons",
    level: "A1",
    theme: "Weather & seasons",
    description: "Make weather small talk — a German favourite.",
    focus: "Describe and ask about the weather.",
    phrases: [
      { de: "Wie ist das Wetter heute?", en: "How's the weather today?", use: "Opener" },
      { de: "Es ist schön draußen.", en: "It's lovely outside. / It's nice outside. / It's beautiful outside.", use: "Positive" },
      { de: "Es regnet.", en: "It's raining.", use: "Weather" },
      { de: "Es schneit.", en: "It's snowing.", use: "Weather" },
      { de: "Die Sonne scheint.", en: "The sun is shining.", use: "Weather" },
      { de: "Es ist kalt.", en: "It's cold.", use: "Weather" },
      { de: "Es ist heiß.", en: "It's hot.", use: "Weather" },
      { de: "Es ist windig.", en: "It's windy.", use: "Weather" },
      { de: "Nimm einen Regenschirm mit.", en: "Take an umbrella. / Take an umbrella with you.", use: "Advice" },
      { de: "Morgen soll es regnen.", en: "It's supposed to rain tomorrow. / Tomorrow it's supposed to rain. / It should rain tomorrow.", use: "Forecast" },
      { de: "Was für ein schöner Tag!", en: "What a beautiful day! / What a lovely day! / What a nice day!", use: "Exclamation" },
      { de: "Im Winter ist es früh dunkel.", en: "In winter it gets dark early.", use: "Seasons" },
      { de: "Im Sommer gehe ich gern schwimmen.", en: "In summer I like to go swimming.", use: "Seasons" },
    ],
  },
  {
    id: "cb-family",
    label: "Family & relationships",
    level: "A2",
    theme: "Family & relationships",
    description: "Talk about the people in your life.",
    focus: "Family members and relationship status.",
    phrases: [
      { de: "Hast du Geschwister?", en: "Do you have siblings? / Do you have brothers and sisters?", use: "Getting to know someone" },
      { de: "Ich habe einen Bruder und eine Schwester.", en: "I have a brother and a sister.", use: "Family" },
      { de: "Ich bin verheiratet.", en: "I'm married.", use: "Relationship status" },
      { de: "Ich bin Single.", en: "I'm single.", use: "Relationship status" },
      { de: "Das ist meine Frau.", en: "This is my wife.", use: "Introducing" },
      { de: "Das ist mein Mann.", en: "This is my husband.", use: "Introducing" },
      { de: "Wir haben zwei Kinder.", en: "We have two children.", use: "Family" },
      { de: "Meine Eltern wohnen in Hamburg.", en: "My parents live in Hamburg.", use: "Family" },
      { de: "Wie geht es deiner Familie?", en: "How's your family? / How is your family doing?", use: "Caring question" },
      { de: "Er ist ein guter Freund von mir.", en: "He's a good friend of mine.", use: "Describing people" },
      { de: "Wir kennen uns schon lange.", en: "We've known each other a long time.", use: "Relationships" },
      { de: "Ich vermisse meine Familie.", en: "I miss my family.", use: "Feeling" },
      { de: "Grüß deine Familie von mir.", en: "Say hi to your family from me. / Say hello to your family from me. / Greet your family from me.", use: "Warm closing" },
    ],
  },
  {
    id: "cb-reactions",
    label: "Quick reactions & filler",
    level: "A2",
    theme: "Quick reactions & filler",
    description: "The little words that make you sound natural, not like a textbook.",
    focus: "Spoken reactions, agreement, and conversational glue.",
    phrases: [
      { de: "Na klar!", en: "Of course!", use: "Enthusiastic yes" },
      { de: "Stimmt.", en: "True.", use: "Agreeing" },
      { de: "Echt?", en: "For real? / Really?", use: "Surprise" },
      { de: "Kein Wunder.", en: "No wonder.", use: "Reacting" },
      { de: "Mal sehen.", en: "We'll see. / Let's see.", use: "Non-committal" },
      { de: "Auf jeden Fall!", en: "Definitely!", use: "Strong agreement" },
      { de: "Quatsch!", en: "Nonsense!", use: "Friendly disbelief" },
      { de: "Schon gut.", en: "It's fine. / It's okay. / Never mind.", use: "Brushing off" },
      { de: "Macht nichts.", en: "It doesn't matter. / Doesn't matter. / Never mind.", use: "Reassuring" },
      { de: "Wie bitte?", en: "Sorry, what? / Pardon? / Excuse me?", use: "Didn't hear / polite" },
      { de: "Moment mal!", en: "Hang on a second!", use: "Interjecting" },
      { de: "Genau so.", en: "Exactly like that.", use: "Confirming" },
      { de: "Das ist mir egal.", en: "I don't care. / I don't mind. / It's all the same to me.", use: "Indifference" },
      { de: "Viel Spaß!", en: "Have fun!", use: "Well-wishing" },
      { de: "Pass auf dich auf.", en: "Take care of yourself.", use: "Warm goodbye" },
    ],
  },
];
