import type { CountryQuestion } from "@/lib/countryStudies";

/**
 * Pula ćwiczeniowa kursu „Życie w Polsce”.
 *
 * Zbudowana jak pule brytyjska, niemiecka i francuska, i oddzielona od quizów
 * w lekcjach z tego samego powodu: tamte zamykają lekcję, gdy tekst jest
 * jeszcze na ekranie, a te wracają w nieuporządkowanej kolejności, długo po
 * czytaniu.
 *
 * Żadne pytanie z lekcji nie pojawia się tutaj ponownie. Nic nie może służyć
 * dwa razy — check-pl-questions porównuje oba zbiory i przerywa kompilację,
 * gdy się pokryją.
 *
 * Każde pytanie nosi identyfikator lekcji, która go uczy. Rozdział bierze się
 * z lekcji, a nie z drugiego spisu prowadzonego ręcznie.
 *
 * TRUDNOŚĆ jest ustalona, nie wyliczona. „easy”: odpowiedź stoi w lekcji
 * wprost. „medium”: trzeba pamiętać nazwę, datę albo liczbę. „hard”: trzeba
 * zestawić dwa fakty albo pytanie celuje w znane pomylenie — 3 maja i 11
 * listopada, Sejm i Senat, wojewoda i marszałek, 1791 i 1997.
 *
 * TEMATY idą za treścią lekcji, a nie za katalogiem egzaminacyjnym: takiego
 * egzaminu w Polsce nie ma. Pytania sprawdzają, czy się rozumie kraj, a nie
 * czy się zdało.
 */

export const PL_QUESTIONS: CountryQuestion[] = [
  // ── Symbole narodowe ───────────────────────────────────────────────────
  { id: "sym-1", lesson: "pl-symbole", level: "easy",
    q: "Co przedstawia godło Rzeczypospolitej Polskiej?",
    options: [
      "Białego orła w złotej koronie na czerwonym tle",
      "Czarnego orła na złotym tle",
      "Białego orła bez korony na niebieskim tle",
      "Złotego lwa na czerwonym tle",
    ],
    answer: 0,
    explanation: "Orzeł biały w złotej koronie, na czerwonym polu — opisuje go artykuł 28 Konstytucji." },
  { id: "sym-2", lesson: "pl-symbole", level: "medium",
    q: "Kiedy obchodzi się Dzień Flagi Rzeczypospolitej Polskiej?",
    options: ["1 maja", "2 maja", "3 maja", "11 listopada"],
    answer: 1,
    explanation: "2 maja, między Świętem Pracy a Świętem Konstytucji 3 Maja." },
  { id: "sym-3", lesson: "pl-symbole", level: "hard",
    q: "W którym roku orzeł w godle odzyskał koronę?",
    options: ["1918", "1945", "1990", "1997"],
    answer: 2,
    explanation: "W 1990 roku. W czasach PRL orzeł korony nie miał; 1918 to odzyskanie niepodległości, 1997 to Konstytucja." },

  // ── Konstytucja i wartości ustrojowe ───────────────────────────────────
  { id: "kon-1", lesson: "pl-konstytucja", level: "easy",
    q: "Który akt prawny jest w Polsce najwyższy?",
    options: ["Ustawa sejmowa", "Konstytucja", "Rozporządzenie ministra", "Uchwała rady gminy"],
    answer: 1,
    explanation: "Konstytucja. Żadna ustawa ani rozporządzenie nie może być z nią sprzeczne." },
  { id: "kon-2", lesson: "pl-konstytucja", level: "medium",
    q: "W jakim trybie przyjęto obowiązującą Konstytucję RP?",
    options: [
      "Uchwalona przez Sejm i zatwierdzona w referendum",
      "Nadana przez Prezydenta",
      "Uchwalona wyłącznie przez Senat",
      "Przyjęta rozporządzeniem Rady Ministrów",
    ],
    answer: 0,
    explanation: "Zgromadzenie Narodowe ją uchwaliło, a obywatele potwierdzili w referendum w 1997 roku." },
  { id: "sym-4", lesson: "pl-symbole", level: "easy",
    q: "Jak nazywa się hymn państwowy Polski?",
    options: ["Rota", "Mazurek Dąbrowskiego", "Warszawianka", "Bogurodzica"],
    answer: 1,
    explanation: "Mazurek Dąbrowskiego, z 1797 roku. Rota i Warszawianka to pieśni patriotyczne, ale nie hymn." },
  { id: "sym-5", lesson: "pl-symbole", level: "easy",
    q: "Jakie kolory ma flaga Polski?",
    options: ["Biały i czerwony", "Czerwony i złoty", "Biały i niebieski", "Czerwony i czarny"],
    answer: 0,
    explanation: "Biel u góry, czerwień u dołu — barwy wzięte z orła i pola herbowego." },
  { id: "sym-6", lesson: "pl-symbole", level: "medium",
    q: "W którym artykule Konstytucji opisane są godło, barwy i hymn?",
    options: ["W artykule 1", "W artykule 28", "W artykule 30", "W artykule 87"],
    answer: 1,
    explanation: "Artykuł 28 wymienia wszystkie trzy symbole i obejmuje je ochroną prawną." },
  { id: "sym-7", lesson: "pl-symbole", level: "medium",
    q: "W którym roku powstał Mazurek Dąbrowskiego?",
    options: ["1791", "1797", "1830", "1918"],
    answer: 1,
    explanation: "1797, we Włoszech, w Legionach Polskich — gdy państwa polskiego nie było na mapie." },
  { id: "sym-8", lesson: "pl-symbole", level: "medium",
    q: "Kiedy oficjalnie ustalono biel i czerwień jako barwy narodowe?",
    options: ["W 1791 roku", "W 1831 roku", "W 1918 roku", "W 1990 roku"],
    answer: 1,
    explanation: "7 lutego 1831 roku, w czasie powstania listopadowego. Herb jest o wieki starszy niż same barwy." },
  { id: "sym-9", lesson: "pl-symbole", level: "hard",
    q: "Czym różni się flaga z godłem od zwykłej flagi państwowej?",
    options: [
      "Używają jej wyłącznie polskie statki i placówki dyplomatyczne",
      "Wywiesza się ją tylko 11 listopada",
      "Jest wersją historyczną, dziś nieużywaną",
      "Różni się odcieniem czerwieni",
    ],
    answer: 0,
    explanation: "Wersja z godłem jest zastrzeżona dla statków i placówek za granicą — nie wywiesza się jej na balkonie." },
  { id: "sym-10", lesson: "pl-symbole", level: "hard",
    q: "Dlaczego orzeł w godle nosi koronę, choć Polska jest republiką?",
    options: [
      "Bo korona oznacza suwerenność państwa, a nie monarchię",
      "Bo Polska formalnie pozostaje królestwem",
      "Bo tak zdecydował Sejm w 1997 roku",
      "Bo korona odróżnia godło od herbu Warszawy",
    ],
    answer: 0,
    explanation: "Korona jest znakiem niezawisłości państwa. Wróciła na głowę orła w 1990 roku, po okresie PRL." },
  { id: "sym-11", lesson: "pl-symbole", level: "easy",
    q: "Kiedy obchodzi się Dzień Flagi?",
    options: ["1 maja", "2 maja", "3 maja", "1 sierpnia"],
    answer: 1,
    explanation: "2 maja — dzień między Świętem Pracy a Świętem Konstytucji 3 Maja." },
  { id: "sym-12", lesson: "pl-symbole", level: "medium",
    q: "Jakie są pierwsze słowa polskiego hymnu?",
    options: [
      "Boże, coś Polskę",
      "Jeszcze Polska nie zginęła",
      "Nie rzucim ziemi",
      "Warszawo ma",
    ],
    answer: 1,
    explanation: "„Jeszcze Polska nie zginęła, kiedy my żyjemy” — zdanie napisane w czasie rozbiorów." },

  { id: "kon-3", lesson: "pl-konstytucja", level: "easy",
    q: "Jaką formą państwa jest Polska według Konstytucji?",
    options: ["Monarchią", "Republiką", "Federacją", "Konfederacją"],
    answer: 1,
    explanation: "Republiką — głowę państwa się wybiera na kadencję, a nie dziedziczy." },
  { id: "kon-4", lesson: "pl-konstytucja", level: "medium",
    q: "Która konstytucja obowiązywała w PRL do 1997 roku?",
    options: ["Marcowa z 1921", "Kwietniowa z 1935", "Z 1952 roku", "Z 1989 roku"],
    answer: 2,
    explanation: "Konstytucja PRL z 1952 roku, wielokrotnie zmieniana, obowiązywała do wejścia w życie obecnej." },
  { id: "kon-5", lesson: "pl-konstytucja", level: "medium",
    q: "Ile miesięcy obowiązywała Konstytucja 3 maja?",
    options: ["Czternaście miesięcy", "Pięć lat", "Dwadzieścia lat", "Do rozbiorów w 1795 roku"],
    answer: 0,
    explanation: "Czternaście miesięcy. Sąsiedzi wkroczyli zbrojnie, a w 1793 roku doszło do drugiego rozbioru." },
  { id: "kon-6", lesson: "pl-konstytucja", level: "medium",
    q: "Która konstytucja wzmocniła pozycję prezydenta kosztem parlamentu?",
    options: ["Marcowa z 1921", "Kwietniowa z 1935", "Z 1952 roku", "Z 1997 roku"],
    answer: 1,
    explanation: "Kwietniowa z 1935 roku, uchwalona pod koniec życia Piłsudskiego." },
  { id: "kon-7", lesson: "pl-konstytucja", level: "hard",
    q: "Kiedy przy zmianie Konstytucji można zażądać referendum?",
    options: [
      "Zawsze, przy każdej zmianie",
      "Gdy zmiana dotyczy rozdziałów o ustroju, wolnościach albo o samej procedurze zmiany",
      "Nigdy — Konstytucję zmienia wyłącznie parlament",
      "Tylko gdy zażąda tego Prezydent",
    ],
    answer: 1,
    explanation: "Referendum zatwierdzające dotyczy rozdziałów I, II i XII — ustroju, wolności i trybu zmiany." },
  { id: "kon-8", lesson: "pl-konstytucja", level: "hard",
    q: "Co oznacza zasada, że organy władzy działają „na podstawie i w granicach prawa”?",
    options: [
      "Że urząd może zrobić tylko to, na co pozwala mu przepis",
      "Że urząd może zrobić wszystko, czego przepis nie zakazuje",
      "Że przepisy obowiązują tylko obywateli",
      "Że decyzje urzędu są ostateczne",
    ],
    answer: 0,
    explanation: "Odwrotnie niż u obywatela: obywatelowi wolno wszystko, czego prawo nie zabrania, urzędowi tylko to, na co prawo zezwala." },
  { id: "kon-9", lesson: "pl-konstytucja", level: "easy",
    q: "Czy ustawa może być sprzeczna z Konstytucją?",
    options: [
      "Nie, Konstytucja jest najwyższym prawem",
      "Tak, jeśli uchwali ją Sejm większością 2/3",
      "Tak, jeśli podpisze ją Prezydent",
      "Tak, w stanie wyjątkowym",
    ],
    answer: 0,
    explanation: "Nie. Sprzeczną z Konstytucją ustawę może uchylić Trybunał Konstytucyjny." },
  { id: "kon-10", lesson: "pl-konstytucja", level: "easy",
    q: "Jak nazywa się zasada rozdzielenia władzy ustawodawczej, wykonawczej i sądowniczej?",
    options: ["Podział władz", "Federalizm", "Centralizm", "Subsydiarność"],
    answer: 0,
    explanation: "Podział i równowaga władz — jedna z podstawowych zasad ustrojowych." },
  { id: "kon-11", lesson: "pl-konstytucja", level: "medium",
    q: "Który organ uchwalił Konstytucję z 1997 roku?",
    options: ["Sejm", "Senat", "Zgromadzenie Narodowe", "Rada Ministrów"],
    answer: 2,
    explanation: "Zgromadzenie Narodowe, czyli Sejm i Senat obradujące wspólnie; obywatele potwierdzili ją w referendum." },

  { id: "pra-1", lesson: "pl-prawa", level: "easy",
    q: "Co oznacza domniemanie niewinności?",
    options: [
      "Że oskarżony jest niewinny, dopóki sąd nie orzeknie prawomocnie",
      "Że oskarżony musi udowodnić swoją niewinność",
      "Że policja nie może nikogo zatrzymać",
      "Że wyrok można wydać tylko za zgodą oskarżonego",
    ],
    answer: 0,
    explanation: "Ciężar dowodu spoczywa na oskarżycielu, nie na oskarżonym." },
  { id: "pra-2", lesson: "pl-prawa", level: "easy",
    q: "Od którego roku życia przysługuje prawo głosowania?",
    options: ["Od 16", "Od 18", "Od 21", "Od 25"],
    answer: 1,
    explanation: "Od 18 lat. 21 lat trzeba mieć, żeby kandydować do Sejmu, 30 — do Senatu." },
  { id: "pra-3", lesson: "pl-prawa", level: "medium",
    q: "Co można zrobić, gdy naruszył wolność sam przepis, a nie wyrok?",
    options: [
      "Złożyć skargę konstytucyjną do Trybunału Konstytucyjnego",
      "Wnieść apelację do sądu okręgowego",
      "Złożyć wniosek do wojewody",
      "Nic — przepisów nie da się zakwestionować",
    ],
    answer: 0,
    explanation: "Skarga konstytucyjna, po wyczerpaniu drogi sądowej; sporządza ją adwokat albo radca prawny." },
  { id: "pra-4", lesson: "pl-prawa", level: "medium",
    q: "Co gwarantuje europejskie rozporządzenie RODO?",
    options: [
      "Prawo do informacji o swoich danych, ich poprawienia i usunięcia",
      "Prawo do bezpłatnego internetu",
      "Prawo do zasiłku dla bezrobotnych",
      "Prawo do pracy w każdym kraju świata",
    ],
    answer: 0,
    explanation: "RODO obowiązuje od 2018 roku; nadzoruje je Prezes Urzędu Ochrony Danych Osobowych." },
  { id: "pra-5", lesson: "pl-prawa", level: "medium",
    q: "Kto stoi na straży praw dzieci?",
    options: ["Rzecznik Praw Dziecka", "Rzecznik Praw Obywatelskich", "Kurator oświaty", "Sąd rodzinny"],
    answer: 0,
    explanation: "Rzecznik Praw Dziecka działa osobno od Rzecznika Praw Obywatelskich." },
  { id: "pra-6", lesson: "pl-prawa", level: "hard",
    q: "Czego nigdy nie wolno naruszyć przy ograniczaniu wolności?",
    options: [
      "Istoty danej wolności",
      "Terminu wejścia w życie ustawy",
      "Zasady jawności obrad",
      "Kompetencji wojewody",
    ],
    answer: 0,
    explanation: "Ograniczenie musi być konieczne i wprowadzone ustawą, ale istoty wolności naruszyć nie może." },
  { id: "pra-7", lesson: "pl-prawa", level: "hard",
    q: "Dlaczego nie można ukarać kogoś za czyn, który w chwili popełnienia nie był zabroniony?",
    options: [
      "Bo prawo karne nie działa wstecz",
      "Bo przedawnienie następuje po roku",
      "Bo zgody musiałby udzielić Sejm",
      "Bo taki czyn zawsze jest wykroczeniem, nie przestępstwem",
    ],
    answer: 0,
    explanation: "Zasada lex retro non agit — prawo karne nie działa wstecz." },
  { id: "pra-8", lesson: "pl-prawa", level: "easy",
    q: "Czy w Polsce obowiązuje cenzura prewencyjna?",
    options: [
      "Nie, jest zakazana przez Konstytucję",
      "Tak, sprawuje ją ministerstwo kultury",
      "Tak, wobec prasy zagranicznej",
      "Tak, w czasie kampanii wyborczej",
    ],
    answer: 0,
    explanation: "Konstytucja zakazuje cenzury prewencyjnej i koncesjonowania prasy." },
  { id: "pra-9", lesson: "pl-prawa", level: "medium",
    q: "Do jakiego wieku nauka w szkole publicznej jest bezpłatna i obowiązkowa?",
    options: ["Do 15 lat", "Do 16 lat", "Do 18 lat", "Do ukończenia studiów"],
    answer: 2,
    explanation: "Do 18. roku życia. Studia dzienne na uczelniach publicznych też są bezpłatne, ale nieobowiązkowe." },

  { id: "obo-1", lesson: "pl-obowiazki", level: "easy",
    q: "Kogo obowiązuje przestrzeganie prawa Rzeczypospolitej?",
    options: [
      "Każdego, kto znajduje się pod jej władzą, także cudzoziemca",
      "Wyłącznie obywateli polskich",
      "Wyłącznie osoby pełnoletnie",
      "Wyłącznie osoby zameldowane",
    ],
    answer: 0,
    explanation: "Obowiązek dotyczy każdego na terytorium państwa, niezależnie od obywatelstwa." },
  { id: "obo-2", lesson: "pl-obowiazki", level: "medium",
    q: "Co może nałożyć podatek?",
    options: ["Tylko ustawa", "Rozporządzenie ministra", "Uchwała rady gminy", "Decyzja wojewody"],
    answer: 0,
    explanation: "Ciężary publiczne nakłada wyłącznie ustawa — to gwarancja konstytucyjna." },
  { id: "obo-3", lesson: "pl-obowiazki", level: "medium",
    q: "Co przysługuje osobie, która ze względu na przekonania nie może pełnić służby wojskowej?",
    options: ["Służba zastępcza", "Zwolnienie bez żadnych obowiązków", "Kara grzywny", "Utrata prawa głosu"],
    answer: 0,
    explanation: "Konstytucja przewiduje skierowanie do służby zastępczej." },
  { id: "obo-4", lesson: "pl-obowiazki", level: "hard",
    q: "W którym roku zawieszono w Polsce obowiązkową zasadniczą służbę wojskową?",
    options: ["1999", "2004", "2009", "2014"],
    answer: 2,
    explanation: "W 2009 roku. Obowiązek obrony ojczyzny pozostał w Konstytucji, ale poboru w czasie pokoju się nie prowadzi." },
  { id: "obo-5", lesson: "pl-obowiazki", level: "easy",
    q: "Czy udział w wyborach jest w Polsce obowiązkowy?",
    options: [
      "Nie, głosowanie jest prawem, nie obowiązkiem",
      "Tak, za nieoddanie głosu grozi grzywna",
      "Tak, dla osób powyżej 25 lat",
      "Tak, w wyborach prezydenckich",
    ],
    answer: 0,
    explanation: "Nie ma kary za nieoddanie głosu. Prawo wybierania przysługuje od 18. roku życia." },
  { id: "obo-6", lesson: "pl-obowiazki", level: "medium",
    q: "Gdzie mogą głosować obywatele mieszkający za granicą?",
    options: [
      "W obwodach przy placówkach dyplomatycznych",
      "Nigdzie — tracą prawo głosu",
      "Wyłącznie korespondencyjnie do Sejmu",
      "Wyłącznie po powrocie do kraju",
    ],
    answer: 0,
    explanation: "Przy ambasadach i konsulatach tworzy się obwody głosowania." },
  { id: "obo-7", lesson: "pl-obowiazki", level: "hard",
    q: "Kto odpowiada za pogorszenie stanu środowiska?",
    options: [
      "Ten, kto je spowodował",
      "Wyłącznie gmina",
      "Wyłącznie Skarb Państwa",
      "Nikt — to obowiązek moralny bez sankcji",
    ],
    answer: 0,
    explanation: "Konstytucja wprost wiąże odpowiedzialność ze sprawcą pogorszenia." },
  { id: "obo-8", lesson: "pl-obowiazki", level: "easy",
    q: "Kto odpowiada za to, żeby dziecko wypełniało obowiązek nauki?",
    options: ["Rodzice albo opiekunowie", "Wyłącznie szkoła", "Wójt gminy", "Kurator sądowy"],
    answer: 0,
    explanation: "Odpowiadają rodzice albo opiekunowie prawni; szkoła publiczna jest przy tym bezpłatna." },
  { id: "sej-1", lesson: "pl-sejm-senat", level: "easy",
    q: "Na ile lat wybiera się Sejm i Senat?",
    options: ["Na 3 lata", "Na 4 lata", "Na 5 lat", "Na 6 lat"],
    answer: 1,
    explanation: "Na 4 lata. Prezydenta wybiera się na 5 lat, samorząd również na 5." },
  { id: "sej-2", lesson: "pl-sejm-senat", level: "easy",
    q: "Ile lat musi mieć kandydat na posła?",
    options: ["18", "21", "25", "30"],
    answer: 1,
    explanation: "21 lat. Senatorem można zostać po ukończeniu 30 lat." },
  { id: "sej-3", lesson: "pl-sejm-senat", level: "medium",
    q: "Ile dni ma Senat na zajęcie stanowiska wobec ustawy Sejmu?",
    options: ["7 dni", "14 dni", "30 dni", "60 dni"],
    answer: 2,
    explanation: "30 dni. Po bezskutecznym upływie terminu ustawę uznaje się za przyjętą." },
  { id: "sej-4", lesson: "pl-sejm-senat", level: "medium",
    q: "Ilu obywateli musi podpisać się pod obywatelskim projektem ustawy?",
    options: ["10 tysięcy", "50 tysięcy", "100 tysięcy", "500 tysięcy"],
    answer: 2,
    explanation: "100 tysięcy — tyle samo, ile potrzeba do zgłoszenia kandydata na Prezydenta." },
  { id: "sej-5", lesson: "pl-sejm-senat", level: "medium",
    q: "Jaki próg wyborczy obowiązuje pojedynczą partię w wyborach do Sejmu?",
    options: ["3 procent", "5 procent", "8 procent", "Nie ma progu"],
    answer: 1,
    explanation: "5 procent dla partii, 8 dla koalicji. Mniejszości narodowe są z progu zwolnione." },
  { id: "sej-6", lesson: "pl-sejm-senat", level: "hard",
    q: "Czym różni się sposób wyboru Sejmu od sposobu wyboru Senatu?",
    options: [
      "Sejm wybiera się proporcjonalnie z list, Senat większościowo w stu okręgach",
      "Sejm wybiera się większościowo, Senat proporcjonalnie",
      "Oba wybiera się identycznie",
      "Senatorów wskazuje Prezydent",
    ],
    answer: 0,
    explanation: "Do Sejmu głosuje się na listy i dzieli mandaty metodą d'Hondta; w Senacie w każdym okręgu wygrywa jeden kandydat." },
  { id: "sej-7", lesson: "pl-sejm-senat", level: "hard",
    q: "Jaką większością Sejm odrzuca poprawki Senatu?",
    options: ["Zwykłą", "Bezwzględną", "Trzech piątych", "Dwóch trzecich"],
    answer: 1,
    explanation: "Bezwzględną. Trzy piąte potrzebne są do odrzucenia weta Prezydenta." },
  { id: "sej-8", lesson: "pl-sejm-senat", level: "medium",
    q: "Co to jest Zgromadzenie Narodowe?",
    options: [
      "Sejm i Senat obradujące wspólnie",
      "Zjazd przedstawicieli samorządów",
      "Posiedzenie Rady Ministrów z Prezydentem",
      "Zebranie wszystkich sędziów Sądu Najwyższego",
    ],
    answer: 0,
    explanation: "Zbiera się rzadko: przysięga Prezydenta, uznanie go za trwale niezdolnego, postawienie przed Trybunałem Stanu." },
  { id: "sej-9", lesson: "pl-sejm-senat", level: "hard",
    q: "Co chroni immunitet poselski?",
    options: [
      "Mandat, a nie osobę — izba może go uchylić",
      "Osobę dożywotnio",
      "Wyłącznie wypowiedzi na sali sejmowej",
      "Majątek posła przed egzekucją",
    ],
    answer: 0,
    explanation: "Bez zgody izby nie można pociągnąć posła do odpowiedzialności karnej, ale izba może immunitet uchylić." },
  { id: "sej-10", lesson: "pl-sejm-senat", level: "easy",
    q: "Kto podpisuje ustawę na końcu drogi legislacyjnej?",
    options: ["Marszałek Sejmu", "Prezydent", "Premier", "Prezes Trybunału Konstytucyjnego"],
    answer: 1,
    explanation: "Prezydent — albo podpisuje, albo wetuje, albo kieruje ustawę do Trybunału Konstytucyjnego." },

  { id: "prez-1", lesson: "pl-prezydent", level: "easy",
    q: "Ile lat musi mieć kandydat na Prezydenta?",
    options: ["21", "30", "35", "40"],
    answer: 2,
    explanation: "35 lat i 100 tysięcy podpisów poparcia." },
  { id: "prez-2", lesson: "pl-prezydent", level: "easy",
    q: "Ile kadencji może sprawować ta sama osoba jako Prezydent?",
    options: ["Jedną", "Dwie", "Trzy", "Bez ograniczeń"],
    answer: 1,
    explanation: "Najwyżej dwie pięcioletnie kadencje." },
  { id: "prez-3", lesson: "pl-prezydent", level: "medium",
    q: "Ile dni ma Prezydent na podpisanie ustawy?",
    options: ["7 dni", "14 dni", "21 dni", "30 dni"],
    answer: 2,
    explanation: "21 dni. W tym czasie może też zawetować ustawę albo skierować ją do Trybunału." },
  { id: "prez-4", lesson: "pl-prezydent", level: "medium",
    q: "Kto zastępuje Prezydenta, gdy ten nie może sprawować urzędu?",
    options: ["Premier", "Marszałek Sejmu", "Marszałek Senatu", "Prezes Sądu Najwyższego"],
    answer: 1,
    explanation: "Marszałek Sejmu, a gdyby i on nie mógł — Marszałek Senatu. Tak było w kwietniu 2010 roku." },
  { id: "prez-5", lesson: "pl-prezydent", level: "medium",
    q: "Co to jest kontrasygnata?",
    options: [
      "Podpis Prezesa Rady Ministrów pod aktem Prezydenta",
      "Drugie czytanie ustawy w Sejmie",
      "Zgoda Senatu na powołanie ministra",
      "Podpis Prezydenta pod uchwałą Sejmu",
    ],
    answer: 0,
    explanation: "Premier bierze przez nią odpowiedzialność za akt przed Sejmem. Prerogatywy jej nie wymagają." },
  { id: "prez-6", lesson: "pl-prezydent", level: "hard",
    q: "Która z tych czynności NIE wymaga kontrasygnaty premiera?",
    options: ["Prawo łaski", "Ratyfikacja umowy międzynarodowej", "Powołanie ambasadora", "Wydanie rozporządzenia"],
    answer: 0,
    explanation: "Prawo łaski jest prerogatywą — podobnie jak zarządzenie wyborów czy nadanie obywatelstwa." },
  { id: "prez-7", lesson: "pl-prezydent", level: "hard",
    q: "Co się dzieje, gdy w pierwszej turze nikt nie zdobędzie ponad połowy głosów?",
    options: [
      "Po dwóch tygodniach odbywa się druga tura między dwoma najlepszymi",
      "Wybiera Zgromadzenie Narodowe",
      "Wygrywa kandydat z największą liczbą głosów",
      "Wybory powtarza się w całości",
    ],
    answer: 0,
    explanation: "Druga tura, dwa tygodnie później, między dwoma kandydatami z najlepszym wynikiem." },
  { id: "prez-8", lesson: "pl-prezydent", level: "easy",
    q: "Gdzie mieści się siedziba Prezydenta Rzeczypospolitej?",
    options: ["Na Wawelu", "W Pałacu Prezydenckim w Warszawie", "W Belwederze w Krakowie", "W Sejmie"],
    answer: 1,
    explanation: "Pałac Prezydencki przy Krakowskim Przedmieściu w Warszawie." },
  { id: "prez-9", lesson: "pl-prezydent", level: "medium",
    q: "Kim jest Prezydent wobec Sił Zbrojnych?",
    options: [
      "Najwyższym zwierzchnikiem",
      "Dowódcą operacyjnym",
      "Doradcą Ministra Obrony",
      "Nie ma z nimi związku",
    ],
    answer: 0,
    explanation: "Najwyższym zwierzchnikiem; w czasie pokoju sprawuje to zwierzchnictwo przez Ministra Obrony Narodowej." },

  { id: "rzad-1", lesson: "pl-rzad", level: "easy",
    q: "Jak inaczej nazywa się Prezes Rady Ministrów?",
    options: ["Premier", "Marszałek", "Kanclerz", "Prezydent"],
    answer: 0,
    explanation: "Premier. Marszałek kieruje obradami Sejmu albo Senatu." },
  { id: "rzad-2", lesson: "pl-rzad", level: "medium",
    q: "Kto desygnuje Prezesa Rady Ministrów?",
    options: ["Sejm", "Prezydent", "Senat", "Marszałek Sejmu"],
    answer: 1,
    explanation: "Prezydent desygnuje, a Sejm udziela rządowi wotum zaufania." },
  { id: "rzad-3", lesson: "pl-rzad", level: "medium",
    q: "W ciągu ilu miesięcy parlament musi uchwalić budżet, żeby Prezydent nie mógł skrócić kadencji Sejmu?",
    options: ["Dwóch", "Trzech", "Czterech", "Sześciu"],
    answer: 2,
    explanation: "Czterech miesięcy od przedłożenia projektu." },
  { id: "rzad-4", lesson: "pl-rzad", level: "medium",
    q: "Który organ bada wydatki państwa i podlega Sejmowi?",
    options: [
      "Najwyższa Izba Kontroli",
      "Ministerstwo Finansów",
      "Narodowy Bank Polski",
      "Trybunał Konstytucyjny",
    ],
    answer: 0,
    explanation: "NIK podlega Sejmowi, nie rządowi — dlatego może kontrolować rząd." },
  { id: "rzad-5", lesson: "pl-rzad", level: "hard",
    q: "Co określa podział działów administracji rządowej między ministrów?",
    options: ["Ustawa", "Decyzja premiera", "Rozporządzenie Prezydenta", "Uchwała Sejmu"],
    answer: 0,
    explanation: "Ustawa o działach administracji rządowej. Liczba ministerstw bywa różna, ale działy są ustawowe." },
  { id: "rzad-6", lesson: "pl-rzad", level: "hard",
    q: "Który organ sądzi najwyższych urzędników za naruszenie Konstytucji lub ustawy?",
    options: ["Trybunał Stanu", "Trybunał Konstytucyjny", "Sąd Najwyższy", "Naczelny Sąd Administracyjny"],
    answer: 0,
    explanation: "Trybunał Stanu — za delikty konstytucyjne, a nie za zwykłe przestępstwa." },
  { id: "rzad-7", lesson: "pl-rzad", level: "easy",
    q: "Kto prowadzi bieżącą politykę wewnętrzną i zagraniczną państwa?",
    options: ["Rada Ministrów", "Prezydent", "Sejm", "Trybunał Konstytucyjny"],
    answer: 0,
    explanation: "Rada Ministrów. Prezydent reprezentuje państwo i stoi na straży Konstytucji." },
  { id: "rzad-8", lesson: "pl-rzad", level: "medium",
    q: "Jakiej większości wymaga wotum zaufania dla rządu?",
    options: ["Zwykłej", "Bezwzględnej", "Trzech piątych", "Dwóch trzecich"],
    answer: 1,
    explanation: "Bezwzględnej większości głosów w obecności co najmniej połowy ustawowej liczby posłów." },

  { id: "sad-1", lesson: "pl-sady", level: "easy",
    q: "W którym sądzie zaczyna się większość spraw?",
    options: ["W rejonowym", "W okręgowym", "W apelacyjnym", "W Sądzie Najwyższym"],
    answer: 0,
    explanation: "W sądzie rejonowym; odwołania trafiają do okręgowego, dalej do apelacyjnego." },
  { id: "sad-2", lesson: "pl-sady", level: "medium",
    q: "Który sąd rozpatruje skargę na decyzję urzędu?",
    options: [
      "Wojewódzki sąd administracyjny",
      "Sąd rejonowy",
      "Trybunał Konstytucyjny",
      "Sąd Najwyższy",
    ],
    answer: 0,
    explanation: "Sądy administracyjne mają własną drogę; kasację rozpatruje Naczelny Sąd Administracyjny." },
  { id: "sad-3", lesson: "pl-sady", level: "medium",
    q: "Co oznacza dwuinstancyjność postępowania?",
    options: [
      "Że od wyroku przysługuje odwołanie",
      "Że sprawę sądzi dwóch sędziów",
      "Że wyrok zapada po dwóch rozprawach",
      "Że rozprawa jest jawna",
    ],
    answer: 0,
    explanation: "Każdą sprawę można poddać ocenie sądu wyższej instancji." },
  { id: "sad-4", lesson: "pl-sady", level: "medium",
    q: "Kto prowadzi postępowanie przygotowawcze i oskarża przed sądem?",
    options: ["Prokurator", "Adwokat", "Komornik", "Ławnik"],
    answer: 0,
    explanation: "Prokurator. Adwokat broni, komornik wykonuje orzeczenia." },
  { id: "sad-5", lesson: "pl-sady", level: "hard",
    q: "Czym zajmuje się Sąd Najwyższy?",
    options: [
      "Czuwa nad jednolitością orzecznictwa, nie sądzi spraw od początku",
      "Rozpatruje wszystkie sprawy karne w kraju",
      "Bada zgodność ustaw z Konstytucją",
      "Nadzoruje pracę urzędów wojewódzkich",
    ],
    answer: 0,
    explanation: "Rozpatruje kasacje i podejmuje uchwały wykładnicze; zgodnością ustaw z Konstytucją zajmuje się Trybunał." },
  { id: "sad-6", lesson: "pl-sady", level: "hard",
    q: "Czemu podlegają sędziowie przy orzekaniu?",
    options: [
      "Tylko Konstytucji i ustawom",
      "Ministrowi Sprawiedliwości",
      "Uchwałom Sejmu",
      "Wytycznym prokuratora",
    ],
    answer: 0,
    explanation: "Sędziowie są niezawiśli i podlegają wyłącznie Konstytucji oraz ustawom." },
  { id: "sad-7", lesson: "pl-sady", level: "easy",
    q: "Kto może otrzymać obrońcę z urzędu?",
    options: [
      "Osoba, której nie stać na adwokata",
      "Każdy, kto o to poprosi",
      "Tylko cudzoziemcy",
      "Nikt — obrońcę trzeba opłacić",
    ],
    answer: 0,
    explanation: "Sąd wyznacza obrońcę z urzędu, gdy oskarżony nie ma środków na obronę." },
  { id: "sad-8", lesson: "pl-sady", level: "medium",
    q: "Kto wykonuje prawomocne orzeczenia sądu, gdy dłużnik ich nie wypełnia?",
    options: ["Komornik", "Prokurator", "Policja", "Wojewoda"],
    answer: 0,
    explanation: "Komornik sądowy prowadzi egzekucję." },

  { id: "sam-1", lesson: "pl-samorzad", level: "easy",
    q: "Jak nazywa się podstawowa jednostka samorządu terytorialnego?",
    options: ["Gmina", "Powiat", "Województwo", "Sołectwo"],
    answer: 0,
    explanation: "Gmina odpowiada za wszystko, czego nie zastrzeżono dla innych szczebli." },
  { id: "sam-2", lesson: "pl-samorzad", level: "easy",
    q: "Kto kieruje gminą wiejską?",
    options: ["Wójt", "Burmistrz", "Starosta", "Marszałek"],
    answer: 0,
    explanation: "Wójt na wsi, burmistrz w mieście, prezydent w większym mieście." },
  { id: "sam-3", lesson: "pl-samorzad", level: "medium",
    q: "Kto stoi na czele powiatu?",
    options: ["Starosta", "Wójt", "Wojewoda", "Marszałek"],
    answer: 0,
    explanation: "Starosta, wybierany przez radę powiatu." },
  { id: "sam-4", lesson: "pl-samorzad", level: "medium",
    q: "Który szczebel samorządu zarządza funduszami europejskimi w regionie?",
    options: ["Województwo", "Powiat", "Gmina", "Sołectwo"],
    answer: 0,
    explanation: "Samorząd województwa odpowiada za rozwój regionu i programy regionalne." },
  { id: "sam-5", lesson: "pl-samorzad", level: "medium",
    q: "Co ile lat odbywają się wybory samorządowe?",
    options: ["Co 3 lata", "Co 4 lata", "Co 5 lat", "Co 6 lat"],
    answer: 2,
    explanation: "Co 5 lat — kadencję wydłużono z czterech lat w 2018 roku." },
  { id: "sam-6", lesson: "pl-samorzad", level: "hard",
    q: "Skąd gmina bierze dochody własne?",
    options: [
      "Z podatku od nieruchomości i opłat lokalnych",
      "Wyłącznie z dotacji rządowych",
      "Z podatku VAT",
      "Ze składek zdrowotnych",
    ],
    answer: 0,
    explanation: "Do tego dochodzi udział w PIT i CIT oraz subwencje z budżetu państwa." },
  { id: "sam-7", lesson: "pl-samorzad", level: "hard",
    q: "Jak nazywa się jednostka pomocnicza gminy na wsi?",
    options: ["Sołectwo", "Dzielnica", "Osiedle", "Obwód"],
    answer: 0,
    explanation: "Sołectwo, z sołtysem na czele. W mieście są dzielnice albo osiedla." },
  { id: "sam-8", lesson: "pl-samorzad", level: "medium",
    q: "Jak mieszkańcy mogą odwołać wójta przed końcem kadencji?",
    options: [
      "W referendum lokalnym",
      "Uchwałą wojewody",
      "Decyzją premiera",
      "Nie da się tego zrobić",
    ],
    answer: 0,
    explanation: "Referendum lokalne może odwołać zarówno wójta, jak i radę." },
  { id: "sam-9", lesson: "pl-samorzad", level: "easy",
    q: "Który szczebel samorządu wydaje prawo jazdy i rejestruje pojazdy?",
    options: ["Powiat", "Gmina", "Województwo", "Państwo"],
    answer: 0,
    explanation: "Starostwo powiatowe. Gmina zajmuje się szkołami podstawowymi i sprawami lokalnymi." },
  { id: "poc-1", lesson: "pl-poczatki", level: "easy",
    q: "Który władca przyjął chrzest w 966 roku?",
    options: ["Mieszko I", "Bolesław Chrobry", "Kazimierz Wielki", "Władysław Jagiełło"],
    answer: 0,
    explanation: "Mieszko I, książę Polan. Jego syn Bolesław Chrobry koronował się w 1025 roku." },
  { id: "poc-2", lesson: "pl-poczatki", level: "easy",
    q: "Jak nazywała się pierwsza dynastia panująca w Polsce?",
    options: ["Piastowie", "Jagiellonowie", "Wazowie", "Habsburgowie"],
    answer: 0,
    explanation: "Piastowie, od Mieszka I do 1370 roku. Potem przyszli Jagiellonowie." },
  { id: "poc-3", lesson: "pl-poczatki", level: "medium",
    q: "Kto był pierwszym koronowanym królem Polski?",
    options: ["Mieszko I", "Bolesław Chrobry", "Kazimierz Wielki", "Władysław Łokietek"],
    answer: 1,
    explanation: "Bolesław Chrobry, w 1025 roku. Mieszko I był księciem, nie królem." },
  { id: "poc-4", lesson: "pl-poczatki", level: "medium",
    q: "O którym władcy mówi się, że „zastał Polskę drewnianą, a zostawił murowaną”?",
    options: ["O Bolesławie Chrobrym", "O Kazimierzu Wielkim", "O Władysławie Jagielle", "O Janie III Sobieskim"],
    answer: 1,
    explanation: "O Kazimierzu Wielkim (1333–1370), ostatnim królu z dynastii Piastów." },
  { id: "poc-5", lesson: "pl-poczatki", level: "medium",
    q: "Co ustaliła unia lubelska z 1569 roku?",
    options: [
      "Powstanie Rzeczypospolitej Obojga Narodów",
      "Chrzest Litwy",
      "Rozejm z Krzyżakami",
      "Powrót stolicy do Gniezna",
    ],
    answer: 0,
    explanation: "Polska i Litwa utworzyły jedno państwo ze wspólnym sejmem i wspólnym królem." },
  { id: "poc-6", lesson: "pl-poczatki", level: "hard",
    q: "Co oznaczało liberum veto?",
    options: [
      "Że jeden poseł mógł zerwać obrady sejmu",
      "Że król mógł odrzucić każdą ustawę",
      "Że szlachta wybierała króla",
      "Że mieszczanie mieli głos w sejmie",
    ],
    answer: 0,
    explanation: "Sprzeciw jednego posła unieważniał obrady — z czasem sparaliżowało to państwo." },
  { id: "poc-7", lesson: "pl-poczatki", level: "hard",
    q: "Co wydarzyło się w 1385 roku w Krewie?",
    options: [
      "Zawarto unię Polski z Litwą",
      "Wybuchła wojna z Krzyżakami",
      "Uchwalono pierwszą konstytucję",
      "Przeniesiono stolicę do Warszawy",
    ],
    answer: 0,
    explanation: "Jagiełło przyjął chrzest, ożenił się z Jadwigą i został królem Polski." },
  { id: "poc-8", lesson: "pl-poczatki", level: "medium",
    q: "Kto ogłosił teorię heliocentryczną w polskim złotym wieku?",
    options: ["Mikołaj Kopernik", "Jan Kochanowski", "Jan Długosz", "Andrzej Frycz Modrzewski"],
    answer: 0,
    explanation: "Mikołaj Kopernik. Kochanowski był poetą piszącym po polsku zamiast po łacinie." },
  { id: "poc-9", lesson: "pl-poczatki", level: "easy",
    q: "Które miasto było pierwszą stolicą Polski?",
    options: ["Gniezno", "Kraków", "Warszawa", "Poznań"],
    answer: 0,
    explanation: "Gniezno; tam w 1000 roku doszło do zjazdu z cesarzem Ottonem III." },

  { id: "roz-1", lesson: "pl-rozbiory", level: "easy",
    q: "Które państwa dokonały rozbiorów Polski?",
    options: [
      "Rosja, Prusy i Austria",
      "Rosja, Szwecja i Turcja",
      "Prusy, Francja i Austria",
      "Austria, Węgry i Rosja",
    ],
    answer: 0,
    explanation: "Trzy rozbiory w latach 1772, 1793 i 1795." },
  { id: "roz-2", lesson: "pl-rozbiory", level: "easy",
    q: "W którym roku doszło do trzeciego rozbioru Polski?",
    options: ["1772", "1791", "1793", "1795"],
    answer: 3,
    explanation: "1795 — po nim państwo polskie zniknęło z mapy na 123 lata." },
  { id: "roz-3", lesson: "pl-rozbiory", level: "medium",
    q: "Kto poprowadził insurekcję z 1794 roku?",
    options: ["Tadeusz Kościuszko", "Józef Piłsudski", "Romuald Traugutt", "Jan Henryk Dąbrowski"],
    answer: 0,
    explanation: "Tadeusz Kościuszko. Po klęsce nastąpił trzeci rozbiór." },
  { id: "roz-4", lesson: "pl-rozbiory", level: "medium",
    q: "W którym roku wybuchło powstanie listopadowe?",
    options: ["1794", "1830", "1846", "1863"],
    answer: 1,
    explanation: "1830, w Warszawie, przeciw Rosji. Styczniowe wybuchło w 1863." },
  { id: "roz-5", lesson: "pl-rozbiory", level: "medium",
    q: "Który zabór uzyskał w 1867 roku autonomię z polskimi szkołami i sejmem?",
    options: ["Rosyjski", "Pruski", "Austriacki", "Żaden"],
    answer: 2,
    explanation: "Galicja w zaborze austriackim — uboga, ale z sejmem krajowym we Lwowie." },
  { id: "roz-6", lesson: "pl-rozbiory", level: "hard",
    q: "Na czym polegała praca organiczna?",
    options: [
      "Na zakładaniu szkół, spółdzielni i czytelni zamiast zbrojnych zrywów",
      "Na przygotowaniach do kolejnego powstania",
      "Na emigracji zarobkowej do Ameryki",
      "Na współpracy z władzami zaborczymi w administracji",
    ],
    answer: 0,
    explanation: "Kierunek przyjęty po klęsce 1863 roku: wzmacnianie społeczeństwa zamiast walki zbrojnej." },
  { id: "roz-7", lesson: "pl-rozbiory", level: "hard",
    q: "Za co Maria Skłodowska-Curie otrzymała pierwszą Nagrodę Nobla w 1903 roku?",
    options: ["Za fizykę", "Za chemię", "Za literaturę", "Za medycynę"],
    answer: 0,
    explanation: "Fizyka w 1903, chemia w 1911 — jako pierwsza osoba uhonorowana Noblem dwukrotnie." },
  { id: "roz-8", lesson: "pl-rozbiory", level: "easy",
    q: "Który kompozytor jest najbardziej znanym Polakiem epoki romantyzmu?",
    options: ["Fryderyk Chopin", "Karol Szymanowski", "Stanisław Moniuszko", "Ignacy Paderewski"],
    answer: 0,
    explanation: "Fryderyk Chopin. Jego imię nosi konkurs pianistyczny w Warszawie." },

  { id: "drp-1", lesson: "pl-druga-rp", level: "easy",
    q: "Komu Rada Regencyjna przekazała władzę wojskową 11 listopada 1918 roku?",
    options: ["Józefowi Piłsudskiemu", "Romanowi Dmowskiemu", "Ignacemu Paderewskiemu", "Wincentemu Witosowi"],
    answer: 0,
    explanation: "Józefowi Piłsudskiemu. Dzień ten jest dziś Narodowym Świętem Niepodległości." },
  { id: "drp-2", lesson: "pl-druga-rp", level: "medium",
    q: "Jak nazywa się reforma, która w 1924 roku wprowadziła złotego?",
    options: ["Reforma Grabskiego", "Plan Balcerowicza", "Reforma Wielopolskiego", "Plan Marshalla"],
    answer: 0,
    explanation: "Reforma Władysława Grabskiego. Plan Balcerowicza to rok 1990." },
  { id: "drp-3", lesson: "pl-druga-rp", level: "medium",
    q: "Który port zbudowano od podstaw w dwudziestoleciu międzywojennym?",
    options: ["Gdynię", "Gdańsk", "Szczecin", "Świnoujście"],
    answer: 0,
    explanation: "Gdynię, od 1926 roku — Gdańsk był wtedy Wolnym Miastem." },
  { id: "drp-4", lesson: "pl-druga-rp", level: "medium",
    q: "Jaka część mieszkańców II Rzeczypospolitej należała do mniejszości narodowych?",
    options: ["Około jedna dziesiąta", "Około jedna trzecia", "Około połowa", "Prawie nikt"],
    answer: 1,
    explanation: "Około jednej trzeciej: Ukraińcy, Żydzi, Białorusini, Niemcy, Litwini. Dziś kraj jest jednolity narodowościowo." },
  { id: "drp-5", lesson: "pl-druga-rp", level: "hard",
    q: "Ile systemów prawnych odziedziczyła Polska po zaborcach w 1918 roku?",
    options: ["Jeden", "Dwa", "Trzy", "Sześć"],
    answer: 2,
    explanation: "Trzy — po każdym z zaborców. Do tego różne koleje i cztery waluty w obiegu." },
  { id: "drp-6", lesson: "pl-druga-rp", level: "hard",
    q: "Jak nazywano okres rządów obozu piłsudczykowskiego po 1926 roku?",
    options: ["Sanacja", "Odwilż", "Transformacja", "Restauracja"],
    answer: 0,
    explanation: "Sanacja, czyli „uzdrowienie”. Rola parlamentu w tym czasie malała." },
  { id: "drp-7", lesson: "pl-druga-rp", level: "easy",
    q: "W którym roku uchwalono konstytucję marcową?",
    options: ["1918", "1921", "1926", "1935"],
    answer: 1,
    explanation: "1921. Konstytucja kwietniowa to 1935 rok." },

  { id: "woj-1", lesson: "pl-wojna", level: "easy",
    q: "Od ostrzału którego miejsca rozpoczęła się II wojna światowa?",
    options: ["Westerplatte", "Wawelu", "Twierdzy Modlin", "Helu"],
    answer: 0,
    explanation: "Westerplatte pod Gdańskiem, 1 września 1939 roku o świcie." },
  { id: "woj-2", lesson: "pl-wojna", level: "easy",
    q: "Które państwo zaatakowało Polskę 17 września 1939 roku?",
    options: ["Związek Radziecki", "Węgry", "Słowacja", "Rumunia"],
    answer: 0,
    explanation: "ZSRR, wykonując tajny protokół paktu Ribbentrop–Mołotow." },
  { id: "woj-3", lesson: "pl-wojna", level: "medium",
    q: "Jak nazywała się największa podziemna armia okupowanej Europy?",
    options: ["Armia Krajowa", "Armia Ludowa", "Legiony Polskie", "Bataliony Chłopskie"],
    answer: 0,
    explanation: "Armia Krajowa, podległa rządowi w Londynie." },
  { id: "woj-4", lesson: "pl-wojna", level: "medium",
    q: "W którym roku wybuchło powstanie w getcie warszawskim?",
    options: ["1940", "1942", "1943", "1944"],
    answer: 2,
    explanation: "Kwiecień 1943. Powstanie Warszawskie to sierpień 1944 — to dwa różne zrywy." },
  { id: "woj-5", lesson: "pl-wojna", level: "medium",
    q: "Ile dni trwało Powstanie Warszawskie?",
    options: ["23 dni", "43 dni", "63 dni", "83 dni"],
    answer: 2,
    explanation: "63 dni, od 1 sierpnia 1944. Po jego upadku miasto zostało celowo zburzone." },
  { id: "woj-6", lesson: "pl-wojna", level: "hard",
    q: "Co wydarzyło się w Katyniu wiosną 1940 roku?",
    options: [
      "NKWD zamordowało blisko 22 tysiące polskich oficerów",
      "Wybuchło powstanie przeciw Niemcom",
      "Podpisano rozejm z ZSRR",
      "Utworzono getto",
    ],
    answer: 0,
    explanation: "Zbrodnia katyńska — mord na oficerach, policjantach i urzędnikach, przez dekady zaprzeczany." },
  { id: "woj-7", lesson: "pl-wojna", level: "hard",
    q: "Jak nazywała się organizacja niosąca w okupowanej Polsce pomoc Żydom?",
    options: ["Żegota", "Żagiew", "Zośka", "Wachlarz"],
    answer: 0,
    explanation: "Rada Pomocy Żydom „Żegota”. Za pomoc groziła kara śmierci, także dla całej rodziny." },
  { id: "woj-8", lesson: "pl-wojna", level: "medium",
    q: "Którą bitwę stoczyli w 1944 roku żołnierze generała Andersa we Włoszech?",
    options: ["O Monte Cassino", "Pod Lenino", "Pod Falaise", "O Arnhem"],
    answer: 0,
    explanation: "Monte Cassino, po przejściu szlaku przez Bliski Wschód." },
  { id: "woj-9", lesson: "pl-wojna", level: "hard",
    q: "Jaką część ludności straciła Polska w czasie II wojny światowej?",
    options: ["Około jedną dwudziestą", "Około jedną dziesiątą", "Około jedną piątą", "Około połowę"],
    answer: 2,
    explanation: "Około 6 milionów osób, blisko jedna piąta przedwojennej ludności." },

  { id: "prl-1", lesson: "pl-prl", level: "easy",
    q: "Jak nazywała się partia rządząca w PRL?",
    options: ["PZPR", "PSL", "AK", "NSZZ"],
    answer: 0,
    explanation: "Polska Zjednoczona Partia Robotnicza, jedyna partia sprawująca władzę." },
  { id: "prl-2", lesson: "pl-prl", level: "easy",
    q: "W której stoczni wybuchł strajk, który doprowadził do powstania Solidarności?",
    options: ["W Gdańskiej", "W Szczecińskiej", "W Gdyńskiej", "W Ustce"],
    answer: 0,
    explanation: "Stocznia Gdańska, sierpień 1980. Strajki objęły też Szczecin i inne miasta." },
  { id: "prl-3", lesson: "pl-prl", level: "medium",
    q: "Kto stanął na czele Solidarności w 1980 roku?",
    options: ["Lech Wałęsa", "Tadeusz Mazowiecki", "Jacek Kuroń", "Bronisław Geremek"],
    answer: 0,
    explanation: "Lech Wałęsa, elektryk ze Stoczni Gdańskiej, późniejszy prezydent." },
  { id: "prl-4", lesson: "pl-prl", level: "medium",
    q: "Kto wprowadził stan wojenny 13 grudnia 1981 roku?",
    options: ["Wojciech Jaruzelski", "Edward Gierek", "Władysław Gomułka", "Stanisław Kania"],
    answer: 0,
    explanation: "Generał Wojciech Jaruzelski. Solidarność została zdelegalizowana, działacze internowani." },
  { id: "prl-5", lesson: "pl-prl", level: "medium",
    q: "W którym roku Karol Wojtyła został papieżem?",
    options: ["1976", "1978", "1980", "1981"],
    answer: 1,
    explanation: "1978. Jego pielgrzymka do Polski rok później miała ogromne znaczenie społeczne." },
  { id: "prl-6", lesson: "pl-prl", level: "hard",
    q: "Jak nazywano nielegalny obieg książek i pism w PRL?",
    options: ["Drugi obieg", "Czarna prasa", "Wolne słowo", "Podziemna poczta"],
    answer: 0,
    explanation: "Drugi obieg, zwany też samizdatem — druk i kolportaż poza cenzurą." },
  { id: "prl-7", lesson: "pl-prl", level: "hard",
    q: "Jaki organ powstał po strajkach w Radomiu i Ursusie w 1976 roku?",
    options: [
      "Komitet Obrony Robotników",
      "Polska Zjednoczona Partia Robotnicza",
      "Rada Państwa",
      "Trybunał Konstytucyjny",
    ],
    answer: 0,
    explanation: "KOR — inteligenci wspierający represjonowanych robotników; jeden z korzeni Solidarności." },
  { id: "prl-8", lesson: "pl-prl", level: "easy",
    q: "Co oznaczały kartki w PRL?",
    options: [
      "Reglamentację towarów, na przykład mięsa i cukru",
      "Bilety komunikacji miejskiej",
      "Zaproszenia na zebrania partyjne",
      "Legitymacje szkolne",
    ],
    answer: 0,
    explanation: "System kartkowy przydzielał ograniczone ilości towarów w gospodarce niedoboru." },

  { id: "trp-1", lesson: "pl-trzecia-rp", level: "easy",
    q: "Jak nazywały się rozmowy władzy z opozycją wiosną 1989 roku?",
    options: ["Okrągły Stół", "Porozumienia sierpniowe", "Konferencja w Poczdamie", "Pakt gdański"],
    answer: 0,
    explanation: "Okrągły Stół; ustalono na nim częściowo wolne wybory 4 czerwca." },
  { id: "trp-2", lesson: "pl-trzecia-rp", level: "medium",
    q: "Kto został pierwszym niekomunistycznym premierem w bloku wschodnim?",
    options: ["Tadeusz Mazowiecki", "Lech Wałęsa", "Leszek Balcerowicz", "Jan Olszewski"],
    answer: 0,
    explanation: "Tadeusz Mazowiecki, we wrześniu 1989 roku." },
  { id: "trp-3", lesson: "pl-trzecia-rp", level: "medium",
    q: "Jak nazywał się program reform gospodarczych z 1990 roku?",
    options: ["Plan Balcerowicza", "Reforma Grabskiego", "Plan Marshalla", "Program Wilczka"],
    answer: 0,
    explanation: "Plan Balcerowicza otworzył rynek; ceny wzrosły, ale zniknęły puste półki." },
  { id: "trp-4", lesson: "pl-trzecia-rp", level: "medium",
    q: "Co zmieniła reforma administracyjna z 1999 roku?",
    options: [
      "49 województw zastąpiono 16 i przywrócono powiaty",
      "Zniesiono gminy",
      "Wprowadzono podział na dzielnice",
      "Połączono województwa z powiatami",
    ],
    answer: 0,
    explanation: "Z 49 województw zrobiono 16, a powiaty wróciły jako środkowy szczebel." },
  { id: "trp-5", lesson: "pl-trzecia-rp", level: "hard",
    q: "Ilu członków miało Zgromadzenie Narodowe wybrać na prezydenta w 1989 roku, zanim wprowadzono wybory powszechne?",
    options: [
      "Prezydenta wybrało wtedy Zgromadzenie Narodowe, nie obywatele",
      "Prezydenta wybrali obywatele już w 1989 roku",
      "Urzędu prezydenta wtedy nie było",
      "Prezydenta wskazał premier",
    ],
    answer: 0,
    explanation: "W 1989 roku prezydenta wybrało Zgromadzenie Narodowe; pierwsze wybory powszechne odbyły się rok później." },
  { id: "trp-6", lesson: "pl-trzecia-rp", level: "hard",
    q: "Co wydarzyło się 10 kwietnia 2010 roku?",
    options: [
      "Katastrofa samolotu pod Smoleńskiem",
      "Wejście do strefy Schengen",
      "Referendum europejskie",
      "Powódź tysiąclecia",
    ],
    answer: 0,
    explanation: "Zginęło 96 osób, w tym prezydent Lech Kaczyński. Delegacja leciała na obchody rocznicy zbrodni katyńskiej." },
  { id: "trp-7", lesson: "pl-trzecia-rp", level: "easy",
    q: "W którym roku odbyły się w Polsce pierwsze wolne wybory samorządowe?",
    options: ["1989", "1990", "1997", "1999"],
    answer: 1,
    explanation: "1990 — odrodziły się wtedy gminy jako samorząd." },
  { id: "geo-1", lesson: "pl-geografia", level: "easy",
    q: "Z iloma państwami graniczy Polska?",
    options: ["Z pięcioma", "Z sześcioma", "Z siedmioma", "Z ośmioma"],
    answer: 2,
    explanation: "Siedem: Niemcy, Czechy, Słowacja, Ukraina, Białoruś, Litwa i Rosja." },
  { id: "geo-2", lesson: "pl-geografia", level: "easy",
    q: "Nad którym morzem leży Polska?",
    options: ["Nad Bałtykiem", "Nad Morzem Północnym", "Nad Adriatykiem", "Nad Morzem Czarnym"],
    answer: 0,
    explanation: "Nad Morzem Bałtyckim, na północy kraju." },
  { id: "geo-3", lesson: "pl-geografia", level: "medium",
    q: "Ile wynosi powierzchnia Polski?",
    options: ["Około 213 tysięcy km²", "Około 312 tysięcy km²", "Około 412 tysięcy km²", "Około 512 tysięcy km²"],
    answer: 1,
    explanation: "Około 312 700 km² — szóste miejsce w Unii Europejskiej." },
  { id: "geo-4", lesson: "pl-geografia", level: "medium",
    q: "Jak nazywa się kraina jezior na północnym wschodzie kraju?",
    options: ["Mazury", "Podlasie", "Kaszuby", "Kujawy"],
    answer: 0,
    explanation: "Mazury; największe jezioro to Śniardwy." },
  { id: "geo-5", lesson: "pl-geografia", level: "medium",
    q: "Które zwierzę jest symbolem Puszczy Białowieskiej?",
    options: ["Żubr", "Ryś", "Niedźwiedź", "Bocian"],
    answer: 0,
    explanation: "Żubr. Puszcza Białowieska jest ostatnim fragmentem pierwotnej puszczy niżowej Europy." },
  { id: "geo-6", lesson: "pl-geografia", level: "hard",
    q: "Jaki klimat panuje w Polsce?",
    options: [
      "Umiarkowany przejściowy",
      "Śródziemnomorski",
      "Kontynentalny suchy",
      "Oceaniczny wilgotny",
    ],
    answer: 0,
    explanation: "Przejściowy między morskim a kontynentalnym — stąd zmienna pogoda i wyraźne cztery pory roku." },
  { id: "geo-7", lesson: "pl-geografia", level: "hard",
    q: "Ile parków narodowych jest w Polsce?",
    options: ["13", "18", "23", "30"],
    answer: 2,
    explanation: "23. Najwyżej położony to Tatrzański, nad morzem leży Słowiński z ruchomymi wydmami." },
  { id: "geo-8", lesson: "pl-geografia", level: "easy",
    q: "W którym kierunku opada rzeźba terenu Polski?",
    options: ["Z południa na północ", "Ze wschodu na zachód", "Z północy na południe", "Z zachodu na wschód"],
    answer: 0,
    explanation: "Góry na południu, niziny i wybrzeże na północy — dlatego rzeki płyną na północ." },
  { id: "geo-9", lesson: "pl-geografia", level: "medium",
    q: "Ile metrów wysokości mają Rysy?",
    options: ["1602 m", "2499 m", "3000 m", "1725 m"],
    answer: 1,
    explanation: "2499 m n.p.m. Śnieżka w Karkonoszach ma 1602 m." },

  { id: "mia-1", lesson: "pl-miasta", level: "easy",
    q: "Które miasto jest stolicą Polski?",
    options: ["Kraków", "Warszawa", "Gdańsk", "Poznań"],
    answer: 1,
    explanation: "Warszawa, od końca XVI wieku. Wcześniej stolicą był Kraków." },
  { id: "mia-2", lesson: "pl-miasta", level: "easy",
    q: "Ile mniej więcej osób mieszka w Polsce?",
    options: ["Około 18 milionów", "Około 28 milionów", "Około 37 milionów", "Około 50 milionów"],
    answer: 2,
    explanation: "Około 37–38 milionów." },
  { id: "mia-3", lesson: "pl-miasta", level: "medium",
    q: "Które miasto jest największym portem Polski?",
    options: ["Gdańsk", "Szczecin", "Gdynia", "Kołobrzeg"],
    answer: 0,
    explanation: "Gdańsk — także miasto porozumień sierpniowych i początku Solidarności." },
  { id: "mia-4", lesson: "pl-miasta", level: "medium",
    q: "Nad którą rzeką leży Wrocław?",
    options: ["Nad Wisłą", "Nad Odrą", "Nad Wartą", "Nad Bugiem"],
    answer: 1,
    explanation: "Nad Odrą. Poznań leży nad Wartą, Warszawa i Kraków nad Wisłą." },
  { id: "mia-5", lesson: "pl-miasta", level: "medium",
    q: "Który obiekt w Polsce wpisano na listę UNESCO jako kopalnię czynną od średniowiecza?",
    options: ["Wieliczkę", "Zamość", "Malbork", "Toruń"],
    answer: 0,
    explanation: "Kopalnia soli w Wieliczce, z kaplicami wykutymi w solnej skale." },
  { id: "mia-6", lesson: "pl-miasta", level: "hard",
    q: "Za co wpisano warszawską Starówkę na listę UNESCO?",
    options: [
      "Za powojenną odbudowę zniszczonego miasta",
      "Za zachowane oryginalne mury średniowieczne",
      "Za architekturę modernistyczną",
      "Za układ urbanistyczny z XIX wieku",
    ],
    answer: 0,
    explanation: "Właśnie za odbudowę — wyjątkowy przypadek na tej liście." },
  { id: "mia-7", lesson: "pl-miasta", level: "hard",
    q: "Które województwo ma siedziby władz w dwóch różnych miastach?",
    options: [
      "Kujawsko-pomorskie",
      "Mazowieckie",
      "Małopolskie",
      "Podlaskie",
    ],
    answer: 0,
    explanation: "Sejmik obraduje w Toruniu, a wojewoda urzęduje w Bydgoszczy. Podobnie dzieli się województwo lubuskie." },
  { id: "mia-8", lesson: "pl-miasta", level: "medium",
    q: "Jaki język ma w Polsce status języka regionalnego?",
    options: ["Kaszubski", "Śląski", "Łemkowski", "Góralski"],
    answer: 0,
    explanation: "Kaszubski. Uznanych mniejszości narodowych jest dziewięć, etnicznych cztery." },
  { id: "mia-9", lesson: "pl-miasta", level: "easy",
    q: "Które miasto jest siedzibą Uniwersytetu Jagiellońskiego?",
    options: ["Warszawa", "Kraków", "Wrocław", "Lublin"],
    answer: 1,
    explanation: "Kraków; uczelnia działa od 1364 roku." },

  { id: "gos-1", lesson: "pl-gospodarka", level: "easy",
    q: "Na ile groszy dzieli się złoty?",
    options: ["10", "50", "100", "1000"],
    answer: 2,
    explanation: "Na 100 groszy." },
  { id: "gos-2", lesson: "pl-gospodarka", level: "easy",
    q: "Który bank emituje polski pieniądz?",
    options: ["Narodowy Bank Polski", "Bank Gospodarstwa Krajowego", "Europejski Bank Centralny", "PKO BP"],
    answer: 0,
    explanation: "Narodowy Bank Polski. EBC emituje euro, którego Polska nie przyjęła." },
  { id: "gos-3", lesson: "pl-gospodarka", level: "medium",
    q: "Ile wynosi podstawowa stawka VAT?",
    options: ["19 procent", "21 procent", "23 procent", "25 procent"],
    answer: 2,
    explanation: "23 procent. Na żywność, książki i niektóre usługi obowiązują stawki niższe." },
  { id: "gos-4", lesson: "pl-gospodarka", level: "medium",
    q: "Ile dni urlopu przysługuje pracownikowi ze stażem powyżej 10 lat?",
    options: ["20 dni", "24 dni", "26 dni", "30 dni"],
    answer: 2,
    explanation: "26 dni. Poniżej 10 lat stażu — 20 dni. Nauka wlicza się do stażu." },
  { id: "gos-5", lesson: "pl-gospodarka", level: "medium",
    q: "Która instytucja pobiera składki emerytalne i rentowe?",
    options: ["ZUS", "NFZ", "NBP", "KRUS dla wszystkich"],
    answer: 0,
    explanation: "Zakład Ubezpieczeń Społecznych. NFZ finansuje leczenie, KRUS dotyczy rolników." },
  { id: "gos-6", lesson: "pl-gospodarka", level: "hard",
    q: "W jakim wieku przechodzą na emeryturę kobiety i mężczyźni?",
    options: [
      "Kobiety w wieku 60 lat, mężczyźni 65",
      "Wszyscy w wieku 65 lat",
      "Kobiety 62, mężczyźni 67",
      "Wszyscy w wieku 67 lat",
    ],
    answer: 0,
    explanation: "60 i 65 lat. Wysokość emerytury zależy od sumy składek i przewidywanej długości życia." },
  { id: "gos-7", lesson: "pl-gospodarka", level: "hard",
    q: "Gdzie wpisuje się spółki, a nie jednoosobową działalność?",
    options: ["Do KRS", "Do CEIDG", "Do ZUS", "Do urzędu skarbowego"],
    answer: 0,
    explanation: "Krajowy Rejestr Sądowy. CEIDG służy jednoosobowej działalności gospodarczej." },
  { id: "gos-8", lesson: "pl-gospodarka", level: "easy",
    q: "Ile godzin dziennie wynosi zasadniczo czas pracy?",
    options: ["6 godzin", "7 godzin", "8 godzin", "10 godzin"],
    answer: 2,
    explanation: "8 godzin dziennie i przeciętnie 40 tygodniowo w przyjętym okresie rozliczeniowym." },
  { id: "gos-9", lesson: "pl-gospodarka", level: "medium",
    q: "Jaki numer identyfikacyjny jest potrzebny do rozliczeń podatkowych firmy?",
    options: ["NIP", "PESEL", "REGON", "IBAN"],
    answer: 0,
    explanation: "NIP. PESEL identyfikuje osobę fizyczną, REGON jest numerem statystycznym." },

  { id: "swt-1", lesson: "pl-swiat", level: "easy",
    q: "Ile państw wstąpiło do Unii Europejskiej razem z Polską w 2004 roku?",
    options: ["Cztery", "Sześć", "Dziewięć", "Dwanaście"],
    answer: 2,
    explanation: "Polska i dziewięć innych państw — największe rozszerzenie w historii Unii." },
  { id: "swt-2", lesson: "pl-swiat", level: "easy",
    q: "Od kiedy Polska należy do strefy Schengen?",
    options: ["Od 1999", "Od 2004", "Od 2007", "Od 2014"],
    answer: 2,
    explanation: "Od 2007 roku — granice wewnętrzne przekracza się od tej pory bez kontroli." },
  { id: "swt-3", lesson: "pl-swiat", level: "medium",
    q: "Jak nazywa się współpraca regionalna Polski z Czechami, Słowacją i Węgrami?",
    options: [
      "Grupa Wyszehradzka",
      "Trójkąt Weimarski",
      "Rada Nordycka",
      "Inicjatywa Trójmorza",
    ],
    answer: 0,
    explanation: "Grupa Wyszehradzka. Trójkąt Weimarski to współpraca z Niemcami i Francją." },
  { id: "swt-4", lesson: "pl-swiat", level: "medium",
    q: "Co ile lat Polacy wybierają posłów do Parlamentu Europejskiego?",
    options: ["Co 4 lata", "Co 5 lat", "Co 6 lat", "Co 7 lat"],
    answer: 1,
    explanation: "Co 5 lat, w wyborach bezpośrednich." },
  { id: "swt-5", lesson: "pl-swiat", level: "medium",
    q: "Jaka część głosujących poparła wejście do Unii w referendum z 2003 roku?",
    options: [
      "Ponad połowa",
      "Ponad dwie trzecie",
      "Ponad trzy czwarte",
      "Ponad dziewięć dziesiątych",
    ],
    answer: 2,
    explanation: "Ponad trzy czwarte głosujących, przy frekwencji blisko 59 procent." },
  { id: "swt-6", lesson: "pl-swiat", level: "hard",
    q: "Dlaczego wschodnia granica Polski ma szczególne znaczenie?",
    options: [
      "Jest zarazem zewnętrzną granicą Unii Europejskiej i NATO",
      "Jest najkrótszą granicą kraju",
      "Nie jest strzeżona",
      "Przebiega wyłącznie po rzekach",
    ],
    answer: 0,
    explanation: "Granica z Ukrainą, Białorusią i Rosją jest granicą zewnętrzną obu organizacji." },
  { id: "swt-7", lesson: "pl-swiat", level: "hard",
    q: "Ile mniej więcej osób liczy Polonia na świecie?",
    options: [
      "Około miliona",
      "Kilka milionów",
      "Kilkanaście do dwudziestu milionów",
      "Ponad pięćdziesiąt milionów",
    ],
    answer: 2,
    explanation: "Szacunki mówią o kilkunastu do dwudziestu milionów; największe skupiska są w USA, Niemczech i Wielkiej Brytanii." },
  { id: "swt-8", lesson: "pl-swiat", level: "medium",
    q: "Co stało się w Polsce po pełnoskalowej agresji Rosji na Ukrainę w 2022 roku?",
    options: [
      "Przez kraj przeszły miliony uchodźców",
      "Zamknięto granicę zachodnią",
      "Wprowadzono stan wojenny",
      "Polska wystąpiła z NATO",
    ],
    answer: 0,
    explanation: "Największy ruch ludności w tej części Europy od czasów II wojny światowej." },
  { id: "rel-1", lesson: "pl-religia", level: "easy",
    q: "Które wyznanie deklaruje w Polsce największa część mieszkańców?",
    options: ["Rzymskokatolickie", "Prawosławne", "Ewangelickie", "Żadne"],
    answer: 0,
    explanation: "Rzymskokatolickie, choć udział praktykujących od lat maleje." },
  { id: "rel-2", lesson: "pl-religia", level: "medium",
    q: "Jaka umowa reguluje stosunki państwa z Kościołem katolickim?",
    options: ["Konkordat", "Ustawa wyznaniowa", "Rozporządzenie ministra", "Uchwała Sejmu"],
    answer: 0,
    explanation: "Konkordat ze Stolicą Apostolską z 1993 roku." },
  { id: "rel-3", lesson: "pl-religia", level: "medium",
    q: "W którym regionie mieszka najwięcej wyznawców prawosławia?",
    options: ["Na Podlasiu", "Na Śląsku", "Na Pomorzu", "W Wielkopolsce"],
    answer: 0,
    explanation: "Na Podlasiu, przy wschodniej granicy kraju." },
  { id: "rel-4", lesson: "pl-religia", level: "medium",
    q: "Kto decyduje, czy dziecko chodzi w szkole na religię?",
    options: [
      "Rodzice albo pełnoletni uczeń",
      "Dyrektor szkoły",
      "Kurator oświaty",
      "Proboszcz parafii",
    ],
    answer: 0,
    explanation: "Religia jest nieobowiązkowa; alternatywą jest etyka albo żadne z tych zajęć." },
  { id: "rel-5", lesson: "pl-religia", level: "hard",
    q: "Gdzie stoją zabytkowe meczety Tatarów polskich?",
    options: [
      "W Kruszynianach i Bohonikach",
      "W Zakopanem i Nowym Targu",
      "W Gdańsku i Gdyni",
      "We Wrocławiu i Opolu",
    ],
    answer: 0,
    explanation: "Na Podlasiu; Tatarzy osiedli tam przed wiekami." },
  { id: "rel-6", lesson: "pl-religia", level: "hard",
    q: "W którym regionie żyje najwięcej ewangelików?",
    options: ["Na Śląsku Cieszyńskim", "Na Mazurach", "Na Kaszubach", "W Małopolsce"],
    answer: 0,
    explanation: "Na Śląsku Cieszyńskim, gdzie protestantyzm ma nieprzerwaną tradycję od reformacji." },
  { id: "rel-7", lesson: "pl-religia", level: "easy",
    q: "Czy Polska ma religię państwową?",
    options: ["Nie", "Tak, katolicyzm", "Tak, prawosławie", "Tak, ale tylko formalnie"],
    answer: 0,
    explanation: "Nie. Państwo jest bezstronne w sprawach przekonań religijnych." },
  { id: "rel-8", lesson: "pl-religia", level: "medium",
    q: "Które miasto jest siedzibą prymasa Polski?",
    options: ["Gniezno", "Częstochowa", "Kraków", "Warszawa"],
    answer: 0,
    explanation: "Gniezno, pierwsza stolica i najstarsza metropolia w kraju." },

  { id: "swi-1", lesson: "pl-swieta", level: "easy",
    q: "Co upamiętnia 1 sierpnia?",
    options: [
      "Wybuch Powstania Warszawskiego",
      "Odzyskanie niepodległości",
      "Uchwalenie Konstytucji",
      "Wejście do Unii Europejskiej",
    ],
    answer: 0,
    explanation: "Powstanie Warszawskie z 1944 roku. O 17.00 w Warszawie wyją syreny." },
  { id: "swi-2", lesson: "pl-swieta", level: "easy",
    q: "Który dzień jest w Polsce Świętem Wojska Polskiego?",
    options: ["3 maja", "1 sierpnia", "15 sierpnia", "11 listopada"],
    answer: 2,
    explanation: "15 sierpnia, w rocznicę Bitwy Warszawskiej; tego samego dnia przypada Wniebowzięcie." },
  { id: "swi-3", lesson: "pl-swieta", level: "medium",
    q: "Ile potraw tradycyjnie podaje się na wigilijnym stole?",
    options: ["Siedem", "Dziewięć", "Dwanaście", "Trzynaście"],
    answer: 2,
    explanation: "Dwanaście. Zwyczajowo zostawia się też jedno wolne miejsce przy stole." },
  { id: "swi-4", lesson: "pl-swieta", level: "medium",
    q: "Jak nazywa się zwyczaj polewania wodą w poniedziałek wielkanocny?",
    options: ["Śmigus-dyngus", "Andrzejki", "Dożynki", "Ostatki"],
    answer: 0,
    explanation: "Śmigus-dyngus — zwyczaj starszy niż chrześcijaństwo w Polsce." },
  { id: "swi-5", lesson: "pl-swieta", level: "medium",
    q: "Co robi się w Polsce 1 listopada?",
    options: [
      "Odwiedza się groby bliskich i zapala znicze",
      "Świętuje się początek roku szkolnego",
      "Obchodzi się rocznicę niepodległości",
      "Organizuje się dożynki",
    ],
    answer: 0,
    explanation: "Wszystkich Świętych. Cmentarze świecą wtedy przez całą noc." },
  { id: "swi-6", lesson: "pl-swieta", level: "hard",
    q: "Kiedy obchodzi się andrzejki?",
    options: ["29 listopada", "6 grudnia", "31 grudnia", "2 lutego"],
    answer: 0,
    explanation: "Wieczór 29 listopada, z wróżbami z lanego wosku. 6 grudnia to mikołajki." },
  { id: "swi-7", lesson: "pl-swieta", level: "hard",
    q: "Kiedy zaczyna się w Polsce rok szkolny?",
    options: ["1 września", "15 września", "1 października", "Po Wszystkich Świętych"],
    answer: 0,
    explanation: "1 września; kończy się w drugiej połowie czerwca." },
  { id: "swi-8", lesson: "pl-swieta", level: "easy",
    q: "Które dwa dni grudnia są w Polsce wolne od pracy z okazji Bożego Narodzenia?",
    options: ["24 i 25 grudnia", "25 i 26 grudnia", "26 i 27 grudnia", "24 i 31 grudnia"],
    answer: 1,
    explanation: "25 i 26 grudnia. Wigilia 24 grudnia jest dniem pracującym, choć zwykle skróconym." },

  { id: "edu-1", lesson: "pl-edukacja", level: "easy",
    q: "Jakim egzaminem kończy się szkoła podstawowa?",
    options: ["Egzaminem ósmoklasisty", "Maturą", "Egzaminem zawodowym", "Testem kompetencji"],
    answer: 0,
    explanation: "Egzaminem ósmoklasisty. Matura kończy liceum albo technikum." },
  { id: "edu-2", lesson: "pl-edukacja", level: "easy",
    q: "Ile lat trwa liceum ogólnokształcące?",
    options: ["3 lata", "4 lata", "5 lat", "6 lat"],
    answer: 1,
    explanation: "Cztery lata. Technikum trwa pięć." },
  { id: "edu-3", lesson: "pl-edukacja", level: "medium",
    q: "Czy studia dzienne na uczelniach publicznych są płatne?",
    options: [
      "Nie, są bezpłatne",
      "Tak, dla wszystkich",
      "Tak, poza pierwszym rokiem",
      "Tak, dla osób powyżej 25 lat",
    ],
    answer: 0,
    explanation: "Studia dzienne na uczelniach publicznych są bezpłatne; płatne bywają zaoczne i uczelnie prywatne." },
  { id: "edu-4", lesson: "pl-edukacja", level: "medium",
    q: "Która instytucja finansuje leczenie ze składek?",
    options: ["NFZ", "ZUS", "KRUS", "GUS"],
    answer: 0,
    explanation: "Narodowy Fundusz Zdrowia. ZUS zajmuje się emeryturami i rentami." },
  { id: "edu-5", lesson: "pl-edukacja", level: "medium",
    q: "Do kogo idzie się najpierw z problemem zdrowotnym?",
    options: [
      "Do lekarza rodzinnego",
      "Bezpośrednio do specjalisty",
      "Na izbę przyjęć",
      "Do apteki",
    ],
    answer: 0,
    explanation: "Lekarz podstawowej opieki zdrowotnej kieruje dalej do specjalisty." },
  { id: "edu-6", lesson: "pl-edukacja", level: "hard",
    q: "Ile cyfr ma numer PESEL?",
    options: ["Dziewięć", "Dziesięć", "Jedenaście", "Trzynaście"],
    answer: 2,
    explanation: "Jedenaście. Zawiera datę urodzenia, a przedostatnia cyfra oznacza płeć." },
  { id: "edu-7", lesson: "pl-edukacja", level: "hard",
    q: "Jak dziś wygląda recepta na lek?",
    options: [
      "To e-recepta: kod z SMS-a albo z aplikacji",
      "Papierowy druk z pieczątką",
      "Wpis do książeczki zdrowia",
      "Ustne polecenie lekarza",
    ],
    answer: 0,
    explanation: "E-recepta. Część leków jest refundowana, czyli tańsza dzięki dopłacie NFZ." },
  { id: "edu-8", lesson: "pl-edukacja", level: "easy",
    q: "Która uczelnia w Polsce jest najstarsza?",
    options: [
      "Uniwersytet Jagielloński",
      "Uniwersytet Warszawski",
      "Politechnika Warszawska",
      "Uniwersytet Wrocławski",
    ],
    answer: 0,
    explanation: "Uniwersytet Jagielloński, założony w 1364 roku." },

  { id: "cod-1", lesson: "pl-codziennosc", level: "easy",
    q: "Gdzie załatwia się większość spraw urzędowych mieszkańca?",
    options: [
      "W urzędzie gminy albo miasta",
      "W urzędzie wojewódzkim",
      "W sądzie rejonowym",
      "W urzędzie skarbowym",
    ],
    answer: 0,
    explanation: "W urzędzie gminy lub miasta, a coraz częściej przez internet." },
  { id: "cod-2", lesson: "pl-codziennosc", level: "medium",
    q: "Co pozwala potwierdzić tożsamość w urzędowych sprawach przez internet?",
    options: ["Profil zaufany", "Numer REGON", "Karta biblioteczna", "Adres e-mail"],
    answer: 0,
    explanation: "Profil zaufany, obok aplikacji mObywatel." },
  { id: "cod-3", lesson: "pl-codziennosc", level: "medium",
    q: "Jak wygląda handel w niedziele?",
    options: [
      "Jest ograniczony ustawą, z wyjątkami",
      "Jest całkowicie zakazany",
      "Odbywa się bez ograniczeń",
      "Zależy od decyzji wojewody",
    ],
    answer: 0,
    explanation: "Otwarte pozostają między innymi piekarnie, stacje paliw i sklepy prowadzone przez właściciela." },
  { id: "cod-4", lesson: "pl-codziennosc", level: "medium",
    q: "Jak zwraca się do osoby starszej albo nieznajomej?",
    options: [
      "„Pan” albo „pani”",
      "Po imieniu",
      "„Cześć”",
      "„Ty”",
    ],
    answer: 0,
    explanation: "Formy „pan” i „pani” są w Polsce standardem wobec osób nieznajomych i starszych." },
  { id: "cod-5", lesson: "pl-codziennosc", level: "hard",
    q: "Który organ konstytucyjny czuwa nad rynkiem mediów?",
    options: [
      "Krajowa Rada Radiofonii i Telewizji",
      "Ministerstwo Kultury",
      "Urząd Ochrony Konkurencji i Konsumentów",
      "Najwyższa Izba Kontroli",
    ],
    answer: 0,
    explanation: "KRRiT, wymieniona wprost w Konstytucji." },
  { id: "cod-6", lesson: "pl-codziennosc", level: "hard",
    q: "Co ile lat odbywa się w Warszawie Konkurs Chopinowski?",
    options: ["Co dwa lata", "Co trzy lata", "Co pięć lat", "Co dziesięć lat"],
    answer: 2,
    explanation: "Co pięć lat — jeden z najstarszych konkursów pianistycznych na świecie." },
  { id: "cod-7", lesson: "pl-codziennosc", level: "medium",
    q: "Które dyscypliny sportu są w Polsce najpopularniejsze?",
    options: [
      "Piłka nożna i siatkówka",
      "Krykiet i rugby",
      "Baseball i hokej",
      "Golf i tenis",
    ],
    answer: 0,
    explanation: "Piłka nożna i siatkówka; zimą kraj ogląda też skoki narciarskie." },
  { id: "cod-8", lesson: "pl-codziennosc", level: "easy",
    q: "Które danie jest tradycyjną potrawą polskiej kuchni?",
    options: ["Pierogi", "Paella", "Sushi", "Gulasz węgierski"],
    answer: 0,
    explanation: "Pierogi, obok bigosu, żurku, rosołu i kotleta schabowego." },
  { id: "cod-9", lesson: "pl-codziennosc", level: "medium",
    q: "Jak wygląda własność mieszkań w Polsce na tle Europy?",
    options: [
      "Udział własności jest jednym z najwyższych",
      "Prawie wszyscy wynajmują",
      "Mieszkania należą do gmin",
      "Własność jest zakazana",
    ],
    answer: 0,
    explanation: "Większość ludzi mieszka we własnym mieszkaniu albo domu." },
  { id: "drp-8", lesson: "pl-druga-rp", level: "easy",
    q: "Który poeta jest jednym z najbardziej znanych twórców dwudziestolecia międzywojennego?",
    options: ["Julian Tuwim", "Adam Mickiewicz", "Jan Kochanowski", "Wisława Szymborska"],
    answer: 0,
    explanation: "Julian Tuwim. Mickiewicz to romantyzm, Kochanowski renesans, Szymborska druga połowa XX wieku." },
  { id: "drp-9", lesson: "pl-druga-rp", level: "medium",
    q: "W którym roku powstało Polskie Radio?",
    options: ["1918", "1924", "1930", "1939"],
    answer: 1,
    explanation: "1924 — jedna z instytucji budowanych w młodym państwie od podstaw." },
  { id: "drp-10", lesson: "pl-druga-rp", level: "hard",
    q: "Który konflikt zakończyła Bitwa Warszawska?",
    options: [
      "Wojnę z Rosją bolszewicką",
      "I wojnę światową",
      "Powstanie wielkopolskie",
      "Wojnę z Czechosłowacją",
    ],
    answer: 0,
    explanation: "Wojnę polsko-bolszewicką. Zatrzymała ofensywę zmierzającą na zachód Europy." },

  { id: "trp-8", lesson: "pl-trzecia-rp", level: "easy",
    q: "Jaką część miejsc w Senacie zdobyła Solidarność w wyborach 4 czerwca 1989 roku?",
    options: ["99 na 100", "65 na 100", "50 na 100", "35 na 100"],
    answer: 0,
    explanation: "99 na 100. W Sejmie zdobyła wszystkie mandaty, o które wolno jej było się ubiegać." },
  { id: "trp-9", lesson: "pl-trzecia-rp", level: "medium",
    q: "Kto był prezydentem Polski bezpośrednio po Lechu Wałęsie?",
    options: ["Aleksander Kwaśniewski", "Lech Kaczyński", "Bronisław Komorowski", "Andrzej Duda"],
    answer: 0,
    explanation: "Aleksander Kwaśniewski, przez dwie kadencje." },
  { id: "trp-10", lesson: "pl-trzecia-rp", level: "hard",
    q: "Jaka była największa zmiana gospodarcza początku lat dziewięćdziesiątych?",
    options: [
      "Przejście od gospodarki planowanej do rynkowej",
      "Wprowadzenie euro",
      "Nacjonalizacja przemysłu",
      "Wprowadzenie kartek na żywność",
    ],
    answer: 0,
    explanation: "Otwarcie rynku. Ceny wzrosły i wiele zakładów upadło, ale niedobory się skończyły." },

  { id: "obo-9", lesson: "pl-obowiazki", level: "medium",
    q: "Czy Konstytucja nakłada obowiązki także na osoby niebędące obywatelami?",
    options: [
      "Tak, obowiązek przestrzegania prawa dotyczy każdego",
      "Nie, wyłącznie na obywateli",
      "Tylko na osoby pracujące",
      "Tylko na osoby zameldowane",
    ],
    answer: 0,
    explanation: "Przestrzeganie prawa obowiązuje każdego pod władzą Rzeczypospolitej; obrona ojczyzny — obywateli." },
  { id: "obo-10", lesson: "pl-obowiazki", level: "hard",
    q: "Czym jest wstępnie wypełnione zeznanie podatkowe?",
    options: [
      "Rozliczeniem przygotowanym przez urząd, które wystarczy sprawdzić i zatwierdzić",
      "Zeznaniem składanym przez pracodawcę zamiast pracownika",
      "Wnioskiem o zwolnienie z podatku",
      "Deklaracją składaną co miesiąc",
    ],
    answer: 0,
    explanation: "Urząd skarbowy udostępnia je przez internet; podatnik może je poprawić albo przyjąć." },

  { id: "sad-9", lesson: "pl-sady", level: "medium",
    q: "Kto wybiera ławników?",
    options: ["Rady gmin", "Prezydent", "Minister Sprawiedliwości", "Sąd Najwyższy"],
    answer: 0,
    explanation: "Rady gmin. Przy wyrokowaniu ławnik ma taki sam głos jak sędzia zawodowy." },
  { id: "sad-10", lesson: "pl-sady", level: "hard",
    q: "Czy Trybunał Konstytucyjny może zmienić wyrok w konkretnej sprawie?",
    options: [
      "Nie, przygląda się przepisowi, a nie rozstrzygnięciu",
      "Tak, jest sądem najwyższej instancji",
      "Tak, na wniosek prokuratora",
      "Tak, w sprawach karnych",
    ],
    answer: 0,
    explanation: "Trybunał bada zgodność przepisu z Konstytucją; wyroki zmieniają sądy wyższej instancji." },

  { id: "rzad-9", lesson: "pl-rzad", level: "medium",
    q: "Czym są interpelacje poselskie?",
    options: [
      "Pisemnymi pytaniami posłów do członków rządu",
      "Wnioskami o odwołanie rządu",
      "Projektami ustaw",
      "Uchwałami Senatu",
    ],
    answer: 0,
    explanation: "Narzędzie kontroli: poseł pyta, minister ma obowiązek odpowiedzieć." },
  { id: "rzad-10", lesson: "pl-rzad", level: "hard",
    q: "Co się dzieje, gdy Sejm nie udzieli rządowi wotum zaufania w pierwszym kroku?",
    options: [
      "Inicjatywę przejmuje Sejm, a Konstytucja przewiduje kolejne kroki",
      "Rozpisuje się natychmiast nowe wybory",
      "Rząd i tak obejmuje urząd",
      "Decyduje Senat",
    ],
    answer: 0,
    explanation: "Konstytucja przewiduje trzy kolejne procedury, żeby państwo nie zostało bez rządu." },

  { id: "prl-9", lesson: "pl-prl", level: "medium",
    q: "Co zapoczątkował robotniczy protest w Poznaniu w 1956 roku?",
    options: ["Odwilż", "Stan wojenny", "Powstanie Solidarności", "Rozwiązanie PZPR"],
    answer: 0,
    explanation: "Protest stłumiono wojskiem, ale zapoczątkował okres politycznej odwilży." },
  { id: "prl-10", lesson: "pl-prl", level: "hard",
    q: "Ilu członków liczyła Solidarność w szczytowym momencie?",
    options: ["Około miliona", "Około trzech milionów", "Blisko dziesięciu milionów", "Ponad dwadzieścia milionów"],
    answer: 2,
    explanation: "Blisko dziesięć milionów — w kraju liczącym wtedy około 36 milionów mieszkańców." },

  { id: "roz-9", lesson: "pl-rozbiory", level: "medium",
    q: "Co nastąpiło po klęsce powstania styczniowego w zaborze rosyjskim?",
    options: [
      "Nasilona rusyfikacja, konfiskaty i zsyłki",
      "Przyznanie autonomii",
      "Zniesienie cenzury",
      "Powrót polskiego sejmu",
    ],
    answer: 0,
    explanation: "Represje objęły szkolnictwo, majątki i tysiące uczestników zesłanych na Sybir." },
  { id: "roz-10", lesson: "pl-rozbiory", level: "hard",
    q: "Który malarz utrwalał sceny z historii Polski w czasie zaborów?",
    options: ["Jan Matejko", "Stanisław Wyspiański", "Jacek Malczewski", "Józef Chełmoński"],
    answer: 0,
    explanation: "Jan Matejko, autor między innymi „Bitwy pod Grunwaldem” i „Konstytucji 3 Maja”." },

  { id: "rel-9", lesson: "pl-religia", level: "medium",
    q: "Jak nazywają się piesze wędrówki na Jasną Górę odbywające się latem?",
    options: ["Pielgrzymki", "Procesje", "Odpusty", "Rekolekcje"],
    answer: 0,
    explanation: "Sierpniowe pielgrzymki idą tam z całego kraju, niektóre po kilkanaście dni." },
  { id: "rel-10", lesson: "pl-religia", level: "hard",
    q: "Co jest alternatywą dla lekcji religii w szkole publicznej?",
    options: ["Etyka", "Filozofia", "Historia Kościoła", "Nic — udział jest obowiązkowy"],
    answer: 0,
    explanation: "Etyka albo rezygnacja z obu zajęć. Wybór należy do rodziców lub pełnoletniego ucznia." },

  { id: "swt-9", lesson: "pl-swiat", level: "medium",
    q: "Który trybunał czuwa nad stosowaniem prawa Unii Europejskiej?",
    options: [
      "Trybunał Sprawiedliwości UE w Luksemburgu",
      "Europejski Trybunał Praw Człowieka w Strasburgu",
      "Trybunał Konstytucyjny",
      "Międzynarodowy Trybunał Karny",
    ],
    answer: 0,
    explanation: "Luksemburg zajmuje się prawem unijnym, Strasburg skargami na naruszenie praw człowieka." },
  { id: "swt-10", lesson: "pl-swiat", level: "hard",
    q: "Czy Polska zobowiązała się kiedyś do przyjęcia euro?",
    options: [
      "Tak, w traktacie akcesyjnym, bez wyznaczonej daty",
      "Nie, uzyskała trwałe wyłączenie",
      "Tak, z terminem na rok 2010",
      "Nie, kwestii tej nigdy nie poruszano",
    ],
    answer: 0,
    explanation: "Zobowiązanie istnieje, ale bez terminu; waluta pozostaje złotym." },

  { id: "swi-9", lesson: "pl-swieta", level: "medium",
    q: "Ile tygodni trwają zwykle ferie zimowe?",
    options: ["Jeden tydzień", "Dwa tygodnie", "Trzy tygodnie", "Miesiąc"],
    answer: 1,
    explanation: "Dwa tygodnie, w różnych terminach zależnie od województwa." },
  { id: "swi-10", lesson: "pl-swieta", level: "hard",
    q: "Które święto kościelne jest w Polsce dniem wolnym i wypada w czwartek?",
    options: ["Boże Ciało", "Wniebowzięcie", "Wszystkich Świętych", "Trzech Króli"],
    answer: 0,
    explanation: "Boże Ciało zawsze wypada w czwartek; pozostałe mają stałe daty." },

  { id: "edu-9", lesson: "pl-edukacja", level: "medium",
    q: "Ile lat trwa technikum?",
    options: ["3 lata", "4 lata", "5 lat", "6 lat"],
    answer: 2,
    explanation: "Pięć lat. Liceum trwa cztery, szkoła branżowa krócej." },
  { id: "edu-10", lesson: "pl-edukacja", level: "hard",
    q: "Co oznacza, że lek jest refundowany?",
    options: [
      "Że NFZ dopłaca do jego ceny",
      "Że jest wydawany bez recepty",
      "Że można go zwrócić do apteki",
      "Że produkuje go państwo",
    ],
    answer: 0,
    explanation: "Dopłata NFZ obniża cenę dla pacjenta." },

  { id: "sym-13", lesson: "pl-symbole", level: "medium",
    q: "Kiedy wywiesza się flagę państwową?",
    options: [
      "W dni świąt państwowych i podczas uroczystości",
      "Codziennie na każdym domu",
      "Wyłącznie w Warszawie",
      "Tylko podczas meczów reprezentacji",
    ],
    answer: 0,
    explanation: "Na budynkach urzędów i podczas uroczystości; mieszkańcy wywieszają ją zwyczajowo w święta." },

  { id: "kon-12", lesson: "pl-konstytucja", level: "hard",
    q: "Czym różni się pozycja obywatela od pozycji urzędu wobec prawa?",
    options: [
      "Obywatelowi wolno wszystko, czego prawo nie zabrania; urzędowi tylko to, na co prawo zezwala",
      "Obie są identyczne",
      "Urzędowi wolno więcej niż obywatelowi",
      "Obywatel podlega tylko Konstytucji",
    ],
    answer: 0,
    explanation: "Ta różnica jest istotą państwa prawa." },

  { id: "sej-11", lesson: "pl-sejm-senat", level: "medium",
    q: "Kto poza posłami i rządem ma inicjatywę ustawodawczą?",
    options: [
      "Senat, Prezydent i grupa 100 tysięcy obywateli",
      "Wyłącznie Prezydent",
      "Wojewodowie",
      "Sądy powszechne",
    ],
    answer: 0,
    explanation: "Projekt może złożyć także Senat, Prezydent albo grupa stu tysięcy obywateli." },

  { id: "geo-10", lesson: "pl-geografia", level: "medium",
    q: "Która kraina historyczna leży wokół Poznania?",
    options: ["Wielkopolska", "Małopolska", "Mazowsze", "Podlasie"],
    answer: 0,
    explanation: "Wielkopolska. Mazowsze leży wokół Warszawy, Małopolska wokół Krakowa." },

  { id: "mia-10", lesson: "pl-miasta", level: "medium",
    q: "Ile mniej więcej osób mieszka w Warszawie?",
    options: ["Około 800 tysięcy", "Około 1,2 miliona", "Około 1,8 miliona", "Około 3 milionów"],
    answer: 2,
    explanation: "Około 1,8 miliona — największe miasto kraju." },

  { id: "gos-10", lesson: "pl-gospodarka", level: "medium",
    q: "Kto ustala wysokość płacy minimalnej?",
    options: [
      "Rada Ministrów w rozporządzeniu, co roku",
      "Każdy pracodawca osobno",
      "Sejm raz na kadencję",
      "Wojewoda dla swojego regionu",
    ],
    answer: 0,
    explanation: "Ustalana corocznie i obowiązuje wszystkich pracowników w kraju." },

  { id: "sam-10", lesson: "pl-samorzad", level: "medium",
    q: "Czym jest budżet obywatelski?",
    options: [
      "Częścią budżetu gminy, o której przeznaczeniu decydują mieszkańcy",
      "Budżetem państwa na cele socjalne",
      "Funduszem unijnym",
      "Podatkiem lokalnym",
    ],
    answer: 0,
    explanation: "Mieszkańcy zgłaszają projekty i głosują, na co pójdzie wydzielona kwota." },

  { id: "prez-10", lesson: "pl-prezydent", level: "medium",
    q: "Przed kim Prezydent składa przysięgę?",
    options: ["Przed Zgromadzeniem Narodowym", "Przed Sejmem", "Przed Sądem Najwyższym", "Przed Radą Ministrów"],
    answer: 0,
    explanation: "Przed Zgromadzeniem Narodowym, czyli połączonymi izbami parlamentu." },

  { id: "pra-10", lesson: "pl-prawa", level: "medium",
    q: "Kto nadzoruje w Polsce ochronę danych osobowych?",
    options: [
      "Prezes Urzędu Ochrony Danych Osobowych",
      "Rzecznik Praw Obywatelskich",
      "Krajowa Rada Radiofonii i Telewizji",
      "Minister Cyfryzacji",
    ],
    answer: 0,
    explanation: "Prezes UODO, na podstawie przepisów RODO obowiązujących od 2018 roku." },

  { id: "poc-10", lesson: "pl-poczatki", level: "medium",
    q: "Jak nazywała się dynastia rządząca po Piastach?",
    options: ["Jagiellonowie", "Wazowie", "Wettynowie", "Andegawenowie"],
    answer: 0,
    explanation: "Jagiellonowie, od unii z Litwą w 1385 roku." },

  { id: "woj-10", lesson: "pl-wojna", level: "medium",
    q: "Dokąd przeniósł się polski rząd po klęsce we wrześniu 1939 roku?",
    options: ["Do Londynu", "Do Paryża na stałe", "Do Moskwy", "Do Sztokholmu"],
    answer: 0,
    explanation: "Najpierw do Francji, a po jej upadku do Londynu." },

  { id: "cod-10", lesson: "pl-codziennosc", level: "medium",
    q: "Kto prowadzi w Polsce koleje dalekobieżne?",
    options: ["PKP", "PKS", "LOT", "ZTM"],
    answer: 0,
    explanation: "Polskie Koleje Państwowe i spółki z nimi związane. PKS to autobusy, LOT to linie lotnicze." },
  { id: "sym-14", lesson: "pl-symbole", level: "hard",
    q: "Co grozi za publiczne znieważenie symboli państwowych?",
    options: [
      "Odpowiedzialność karna — symbole są chronione prawem",
      "Nic, to kwestia obyczaju",
      "Grzywna nakładana przez wojewodę",
      "Utrata prawa głosu",
    ],
    answer: 0,
    explanation: "Godło, barwy i hymn są objęte ochroną prawną; znieważenie ich jest przestępstwem." },
  { id: "kon-13", lesson: "pl-konstytucja", level: "medium",
    q: "Ile rozdziałów Konstytucji podlega zatwierdzeniu w referendum przy zmianie?",
    options: ["Trzy", "Jeden", "Wszystkie", "Żaden"],
    answer: 0,
    explanation: "Rozdziały o ustroju, o wolnościach i o trybie zmiany Konstytucji." },
  { id: "pra-11", lesson: "pl-prawa", level: "easy",
    q: "Czy państwo zapewnia prawo do nauki?",
    options: [
      "Tak, nauka jest bezpłatna w szkołach publicznych",
      "Nie, edukacja jest w pełni prywatna",
      "Tylko dla obywateli polskich",
      "Tylko do 12. roku życia",
    ],
    answer: 0,
    explanation: "Konstytucja gwarantuje prawo do nauki, bezpłatnej w szkołach publicznych." },
  { id: "pra-12", lesson: "pl-prawa", level: "hard",
    q: "Ile czasu ma sąd na decyzję o tymczasowym aresztowaniu po przekazaniu zatrzymanego?",
    options: ["24 godziny", "48 godzin", "72 godziny", "7 dni"],
    answer: 0,
    explanation: "Do 48 godzin na przekazanie sądowi i kolejne 24 na decyzję — razem najwyżej 72 godziny." },
  { id: "obo-11", lesson: "pl-obowiazki", level: "easy",
    q: "Co Konstytucja wymienia jako pierwszy obowiązek obywatela?",
    options: [
      "Wierność Rzeczypospolitej i troskę o dobro wspólne",
      "Płacenie podatków",
      "Służbę wojskową",
      "Udział w wyborach",
    ],
    answer: 0,
    explanation: "Z tego ogólnego sformułowania wynikają pozostałe obowiązki." },
  { id: "sej-12", lesson: "pl-sejm-senat", level: "hard",
    q: "Które ugrupowania są zwolnione z progu wyborczego do Sejmu?",
    options: [
      "Komitety mniejszości narodowych",
      "Partie rządzące",
      "Komitety obywatelskie",
      "Nikt nie jest zwolniony",
    ],
    answer: 0,
    explanation: "Zwolnienie dotyczy komitetów mniejszości narodowych." },
  { id: "prez-11", lesson: "pl-prezydent", level: "hard",
    q: "Co się stanie, jeśli Prezydent skieruje ustawę do Trybunału Konstytucyjnego?",
    options: [
      "Nie może już jej zawetować",
      "Może ją potem jeszcze zawetować",
      "Ustawa wchodzi w życie natychmiast",
      "Sejm musi ją uchwalić ponownie",
    ],
    answer: 0,
    explanation: "Wybór jest rozłączny: albo weto, albo droga do Trybunału." },
  { id: "rzad-11", lesson: "pl-rzad", level: "easy",
    q: "Kto wchodzi w skład Rady Ministrów?",
    options: [
      "Premier i ministrowie",
      "Premier i Prezydent",
      "Posłowie i senatorowie",
      "Wojewodowie",
    ],
    answer: 0,
    explanation: "Prezes Rady Ministrów i ministrowie kierujący działami administracji." },
  { id: "sad-11", lesson: "pl-sady", level: "easy",
    q: "Czy rozprawy sądowe są w Polsce jawne?",
    options: [
      "Tak, co do zasady, a wyrok ogłasza się publicznie",
      "Nie, wszystkie są tajne",
      "Tylko w sprawach cywilnych",
      "Tylko za zgodą stron",
    ],
    answer: 0,
    explanation: "Jawność jest zasadą; wyjątki wymagają podstawy w ustawie." },
  { id: "sam-11", lesson: "pl-samorzad", level: "easy",
    q: "Ile szczebli ma polski samorząd terytorialny?",
    options: ["Jeden", "Dwa", "Trzy", "Cztery"],
    answer: 2,
    explanation: "Gmina, powiat i województwo." },
  { id: "poc-11", lesson: "pl-poczatki", level: "hard",
    q: "Co oznaczała wolna elekcja?",
    options: [
      "Że króla wybierała szlachta",
      "Że tron dziedziczył najstarszy syn",
      "Że króla wskazywał papież",
      "Że królem zostawał zwycięzca turnieju",
    ],
    answer: 0,
    explanation: "Króla wybierała szlachta; zniosła to dopiero Konstytucja 3 maja." },
  { id: "roz-11", lesson: "pl-rozbiory", level: "easy",
    q: "W którym roku doszło do pierwszego rozbioru Polski?",
    options: ["1764", "1772", "1791", "1795"],
    answer: 1,
    explanation: "1772. Drugi nastąpił w 1793, trzeci w 1795 roku." },
  { id: "drp-11", lesson: "pl-druga-rp", level: "medium",
    q: "Jak nazywano powstania, które zdecydowały o przynależności Górnego Śląska?",
    options: ["Powstania śląskie", "Powstanie wielkopolskie", "Powstanie warszawskie", "Powstanie krakowskie"],
    answer: 0,
    explanation: "Trzy powstania śląskie w latach 1919–1921, obok plebiscytu." },
  { id: "woj-11", lesson: "pl-wojna", level: "easy",
    q: "Jak nazywał się największy niemiecki obóz koncentracyjny i zagłady na ziemiach polskich?",
    options: ["Auschwitz-Birkenau", "Dachau", "Buchenwald", "Mauthausen"],
    answer: 0,
    explanation: "Auschwitz-Birkenau, dziś miejsce pamięci wpisane na listę UNESCO." },
  { id: "prl-11", lesson: "pl-prl", level: "easy",
    q: "Jak nazywały się porozumienia kończące strajk w Stoczni Gdańskiej?",
    options: ["Porozumienia sierpniowe", "Okrągły Stół", "Umowa gdańska", "Pakt o stabilizacji"],
    answer: 0,
    explanation: "Porozumienia sierpniowe z 1980 roku; na ich podstawie powstała Solidarność." },
  { id: "trp-11", lesson: "pl-trzecia-rp", level: "medium",
    q: "Jaką część miejsc w Sejmie w 1989 roku obsadzono w wolnych wyborach?",
    options: ["35 procent", "50 procent", "65 procent", "100 procent"],
    answer: 0,
    explanation: "35 procent w Sejmie; Senat był wolny w całości." },
  { id: "geo-11", lesson: "pl-geografia", level: "medium",
    q: "Jak nazywa się największe jezioro w Polsce?",
    options: ["Śniardwy", "Mamry", "Hańcza", "Gopło"],
    answer: 0,
    explanation: "Śniardwy na Mazurach. Hańcza jest najgłębsza, ale nie największa." },
  { id: "mia-11", lesson: "pl-miasta", level: "hard",
    q: "Ile jest w Polsce uznanych mniejszości narodowych?",
    options: ["Cztery", "Sześć", "Dziewięć", "Dwanaście"],
    answer: 2,
    explanation: "Dziewięć mniejszości narodowych i cztery etniczne; językiem regionalnym jest kaszubski." },
  { id: "gos-11", lesson: "pl-gospodarka", level: "hard",
    q: "Czym różni się umowa o pracę od umowy zlecenia?",
    options: [
      "Umowa o pracę daje urlop i ochronę przed zwolnieniem",
      "Umowa zlecenia jest zawsze korzystniejsza",
      "Nie różnią się niczym",
      "Umowa o pracę nie wymaga składek",
    ],
    answer: 0,
    explanation: "Z umowy o pracę wynikają urlop, ochrona stosunku pracy i pełne składki." },
  { id: "swt-11", lesson: "pl-swiat", level: "easy",
    q: "Do której organizacji obronnej należy Polska od 1999 roku?",
    options: ["Do NATO", "Do Układu Warszawskiego", "Do ONZ", "Do OBWE"],
    answer: 0,
    explanation: "Do NATO, razem z Czechami i Węgrami. Układ Warszawski rozwiązano w 1991 roku." },
  { id: "rel-11", lesson: "pl-religia", level: "easy",
    q: "Który obraz znajduje się na Jasnej Górze?",
    options: [
      "Matki Boskiej Częstochowskiej",
      "Matki Boskiej Ostrobramskiej",
      "Świętego Stanisława",
      "Świętej Jadwigi",
    ],
    answer: 0,
    explanation: "Obraz Matki Boskiej Częstochowskiej, cel największych pielgrzymek w kraju." },
  { id: "swi-11", lesson: "pl-swieta", level: "easy",
    q: "Kiedy w Polsce jada się kolację wigilijną?",
    options: [
      "24 grudnia, po pierwszej gwiazdce",
      "25 grudnia w południe",
      "31 grudnia wieczorem",
      "6 stycznia",
    ],
    answer: 0,
    explanation: "Wieczorem 24 grudnia, tradycyjnie po pojawieniu się pierwszej gwiazdy." },
  { id: "edu-11", lesson: "pl-edukacja", level: "easy",
    q: "Jaki egzamin otwiera drogę na studia?",
    options: ["Matura", "Egzamin ósmoklasisty", "Egzamin zawodowy", "Test kompetencji"],
    answer: 0,
    explanation: "Matura; jej wyniki decydują o przyjęciu na uczelnię." },
  { id: "cod-11", lesson: "pl-codziennosc", level: "hard",
    q: "Skąd biorą się opłaty za wodę i ogrzewanie w bloku?",
    options: [
      "Zwykle rozlicza je wspólnota albo spółdzielnia, osobno od czynszu najmu",
      "Zawsze są wliczone w czynsz najmu",
      "Pobiera je gmina",
      "Płaci je wyłącznie właściciel mieszkania",
    ],
    answer: 0,
    explanation: "Przy najmie opłaty eksploatacyjne często idą osobno, do wspólnoty albo spółdzielni." },
];

