import type { Blueprint, VocabSeed } from "./types";

/**
 * The last hundred and twenty-two, to round the inventory to eight thousand.
 *
 * Read out of stores the app already carries and had never taught from: the
 * immersion gap list and the glossary the browser extension reads. Every one
 * has a German side, an English side and, for the nouns, an article that came
 * with it - none of that was decided here.
 *
 * WHAT WAS LEFT OUT. Grammar words, because the sentences teach them and a
 * part of speech for each would have been invented. Capitalised words with no
 * article, because a guessed gender is a wrong gender. Anything with a space,
 * because those are phrases and this is a word list.
 *
 * THE PART OF SPEECH is the store's own where it carries one. Otherwise a verb
 * is read from its ending, with a short list of the words that end like one
 * and are not - gestern was being taught as a verb until it was written down.
 */
const focus = "Reviewed words the courses had never taught, from the immersion gap list and the extension glossary.";

const pack = (label: string, level: string, theme: string, description: string, seeds: VocabSeed[]): Blueprint => ({
  label,
  level,
  theme,
  description,
  focus,
  seeds,
  dialogues: [],
  phrases: [],
});

export const roundingWordPartBlueprints: Record<string, Blueprint> = {
  part545: pack("Part 545", "B1", "Words to eight thousand 1", "Reviewed words no pack taught yet, 1–31 of 156.", [
    { de: "die Kriegsführung", lookup: "Kriegsführung", fallbackEn: "warfare", tip: "noun", article: "die" },
    { de: "der Fachartikel", lookup: "Fachartikel", fallbackEn: "paper", tip: "noun", article: "der" },
    { de: "das Plug-in", lookup: "Plug-in", fallbackEn: "plugin", tip: "noun", article: "das" },
    { de: "der Kühlschrank", lookup: "Kühlschrank", fallbackEn: "fridge", tip: "noun", article: "der" },
    { de: "die Mobilität", lookup: "Mobilität", fallbackEn: "mobility", tip: "noun", article: "die" },
    { de: "der Mehrspielermodus", lookup: "Mehrspielermodus", fallbackEn: "multiplayer", tip: "noun", article: "der" },
    { de: "das Gerüst", lookup: "Gerüst", fallbackEn: "scaffold", tip: "noun", article: "das" },
    { de: "der Arbeitsablauf", lookup: "Arbeitsablauf", fallbackEn: "workflow", tip: "noun", article: "der" },
    { de: "die Autonomie", lookup: "Autonomie", fallbackEn: "autonomy", tip: "noun", article: "die" },
    { de: "der Kapitalist", lookup: "Kapitalist", fallbackEn: "capitalist", tip: "noun", article: "der" },
    { de: "die Kontinuität", lookup: "Kontinuität", fallbackEn: "continuity", tip: "noun", article: "die" },
    { de: "der Drache", lookup: "Drache", fallbackEn: "dragon", tip: "noun", article: "der" },
    { de: "das Startprogramm", lookup: "Startprogramm", fallbackEn: "launcher", tip: "noun", article: "das" },
    { de: "die Personalisierung", lookup: "Personalisierung", fallbackEn: "personalisation", tip: "noun", article: "die" },
    { de: "das Risikokapital", lookup: "Risikokapital", fallbackEn: "venture capital", tip: "noun", article: "das" },
    { de: "die Korrektur", lookup: "Korrektur", fallbackEn: "correction", tip: "noun", article: "die" },
    { de: "der Anruf", lookup: "Anruf", fallbackEn: "phone call", tip: "noun", article: "der" },
    { de: "die Konsole", lookup: "Konsole", fallbackEn: "console", tip: "noun", article: "die" },
    { de: "der Aufschwung", lookup: "Aufschwung", fallbackEn: "upturn", tip: "noun", article: "der" },
    { de: "das Kampfsystem", lookup: "Kampfsystem", fallbackEn: "combat system", tip: "noun", article: "das" },
    { de: "das Bewegungssystem", lookup: "Bewegungssystem", fallbackEn: "movement system", tip: "noun", article: "das" },
    { de: "das Pilotprojekt", lookup: "Pilotprojekt", fallbackEn: "pilot project", tip: "noun", article: "das" },
    { de: "die Vorbereitungszeit", lookup: "Vorbereitungszeit", fallbackEn: "preparation time", tip: "noun", article: "die" },
    { de: "das Installationsprogramm", lookup: "Installationsprogramm", fallbackEn: "installer", tip: "noun", article: "das" },
    { de: "der Pinselstrich", lookup: "Pinselstrich", fallbackEn: "brushstroke", tip: "noun", article: "der" },
    { de: "der Spesenbericht", lookup: "Spesenbericht", fallbackEn: "expense report", tip: "noun", article: "der" },
    { de: "das Manöver", lookup: "Manöver", fallbackEn: "manoeuvre", tip: "noun", article: "das" },
    { de: "der Fünftklässler", lookup: "Fünftklässler", fallbackEn: "fifth-grader", tip: "noun", article: "der" },
    { de: "der Ausgabestil", lookup: "Ausgabestil", fallbackEn: "output style", tip: "noun", article: "der" },
    { de: "das Siedlungsprojekt", lookup: "Siedlungsprojekt", fallbackEn: "settlement project", tip: "noun", article: "das" },
    { de: "die Kennzahl", lookup: "Kennzahl", fallbackEn: "key figure", tip: "noun", article: "die" },
  ]),
  part546: pack("Part 546", "B1", "Words to eight thousand 2", "Reviewed words no pack taught yet, 32–62 of 156.", [
    { de: "der Weltraum", lookup: "Weltraum", fallbackEn: "outer space", tip: "noun", article: "der" },
    { de: "die Entwicklungshilfe", lookup: "Entwicklungshilfe", fallbackEn: "development aid", tip: "noun", article: "die" },
    { de: "der Kumpel", lookup: "Kumpel", fallbackEn: "mate", tip: "noun", article: "der" },
    { de: "der Strafgerichtshof", lookup: "Strafgerichtshof", fallbackEn: "criminal court", tip: "noun", article: "der" },
    { de: "die Nutzerzahl", lookup: "Nutzerzahl", fallbackEn: "user numbers", tip: "noun", article: "die" },
    { de: "der Parcours", lookup: "Parcours", fallbackEn: "obstacle course", tip: "noun", article: "der" },
    { de: "die Zerstörung", lookup: "Zerstörung", fallbackEn: "destruction", tip: "noun", article: "die" },
    { de: "die Kürzung", lookup: "Kürzung", fallbackEn: "cut", tip: "noun", article: "die" },
    { de: "das Diagramm", lookup: "Diagramm", fallbackEn: "graph", tip: "noun", article: "das" },
    { de: "der Kontrollpunkt", lookup: "Kontrollpunkt", fallbackEn: "checkpoint", tip: "noun", article: "der" },
    { de: "das Abendessen", lookup: "Abendessen", fallbackEn: "dinner", tip: "noun", article: "das" },
    { de: "das Alltagsgespräch", lookup: "Alltagsgespräch", fallbackEn: "small talk", tip: "noun", article: "das" },
    { de: "der Unterwasserlauf", lookup: "Unterwasserlauf", fallbackEn: "underwater run", tip: "noun", article: "der" },
    { de: "die Großtante", lookup: "Großtante", fallbackEn: "great-aunt", tip: "noun", article: "die" },
    { de: "die Landkarte", lookup: "Landkarte", fallbackEn: "map", tip: "noun", article: "die" },
    { de: "die Konfiguration", lookup: "Konfiguration", fallbackEn: "config", tip: "noun", article: "die" },
    { de: "das Impressum", lookup: "Impressum", fallbackEn: "legal notice", tip: "noun", article: "das" },
    { de: "die Datenspeicherung", lookup: "Datenspeicherung", fallbackEn: "data storage", tip: "noun", article: "die" },
    { de: "der Stich", lookup: "Stich", fallbackEn: "sting", tip: "noun", article: "der" },
    { de: "der Anblick", lookup: "Anblick", fallbackEn: "sight", tip: "noun", article: "der" },
    { de: "der Befehl", lookup: "Befehl", fallbackEn: "command", tip: "noun", article: "der" },
    { de: "das Eingeständnis", lookup: "Eingeständnis", fallbackEn: "admission", tip: "noun", article: "das" },
    { de: "die Fassade", lookup: "Fassade", fallbackEn: "facade", tip: "noun", article: "die" },
    { de: "die Fertilitätsrate", lookup: "Fertilitätsrate", fallbackEn: "fertility rate", tip: "noun", article: "die" },
    { de: "das Freiwild", lookup: "Freiwild", fallbackEn: "fair game", tip: "noun", article: "das" },
    { de: "die Gesamtbevölkerung", lookup: "Gesamtbevölkerung", fallbackEn: "total population", tip: "noun", article: "die" },
    { de: "die Aufrufzahl", lookup: "Aufrufzahl", fallbackEn: "view count", tip: "noun", article: "die" },
    { de: "der Salto", lookup: "Salto", fallbackEn: "somersault", tip: "noun", article: "der" },
    { de: "die Beschränkung", lookup: "Beschränkung", fallbackEn: "restriction", tip: "noun", article: "die" },
    { de: "die Fruchtbarkeit", lookup: "Fruchtbarkeit", fallbackEn: "fertility", tip: "noun", article: "die" },
    { de: "das Einkommensgebiet", lookup: "Einkommensgebiet", fallbackEn: "income area", tip: "noun", article: "das" },
  ]),
  part547: pack("Part 547", "B1", "Words to eight thousand 3", "Reviewed words no pack taught yet, 63–93 of 156.", [
    { de: "die Linke", lookup: "Linke", fallbackEn: "the left", tip: "noun", article: "die" },
    { de: "die Führungsebene", lookup: "Führungsebene", fallbackEn: "leadership", tip: "noun", article: "die" },
    { de: "das Leck", lookup: "Leck", fallbackEn: "leak", tip: "noun", article: "das" },
    { de: "die Speicherung", lookup: "Speicherung", fallbackEn: "retention", tip: "noun", article: "die" },
    { de: "das Ratenlimit", lookup: "Ratenlimit", fallbackEn: "rate limit", tip: "noun", article: "das" },
    { de: "der Abonnementpreis", lookup: "Abonnementpreis", fallbackEn: "subscription price", tip: "noun", article: "der" },
    { de: "die Spielerzahl", lookup: "Spielerzahl", fallbackEn: "player count", tip: "noun", article: "die" },
    { de: "der Lebensmitteleinkauf", lookup: "Lebensmitteleinkauf", fallbackEn: "grocery shopping", tip: "noun", article: "der" },
    { de: "der Treibstoff", lookup: "Treibstoff", fallbackEn: "fuel", tip: "noun", article: "der" },
    { de: "der Premierminister", lookup: "Premierminister", fallbackEn: "prime minister", tip: "noun", article: "der" },
    { de: "die Eilmeldung", lookup: "Eilmeldung", fallbackEn: "breaking news", tip: "noun", article: "die" },
    { de: "die Einstellung von Personal", lookup: "Einstellung von Personal", fallbackEn: "recruitment", tip: "noun", article: "die" },
    { de: "die Verwaltung von Systemen", lookup: "Verwaltung von Systemen", fallbackEn: "admin", tip: "noun", article: "die" },
    { de: "der Pfennig", lookup: "Pfennig", fallbackEn: "penny", tip: "noun", article: "der" },
    { de: "die Nachfolge", lookup: "Nachfolge", fallbackEn: "succession", tip: "noun", article: "die" },
    { de: "die Ankündigung", lookup: "Ankündigung", fallbackEn: "announcement", tip: "noun", article: "die" },
    { de: "die Festnahme", lookup: "Festnahme", fallbackEn: "arrest", tip: "noun", article: "die" },
    { de: "der Verdächtige", lookup: "Verdächtige", fallbackEn: "suspect", tip: "noun", article: "der" },
    { de: "der Abschaum", lookup: "Abschaum", fallbackEn: "scum", tip: "noun", article: "der" },
    { de: "die Ungerechtigkeit", lookup: "Ungerechtigkeit", fallbackEn: "injustice", tip: "noun", article: "die" },
    { de: "der Börsengang", lookup: "Börsengang", fallbackEn: "stock market flotation", tip: "noun", article: "der" },
    { de: "der Fanatiker", lookup: "Fanatiker", fallbackEn: "fanatic", tip: "noun", article: "der" },
    { de: "der Rechtsstreit", lookup: "Rechtsstreit", fallbackEn: "legal dispute", tip: "noun", article: "der" },
    { de: "der Unterstützer", lookup: "Unterstützer", fallbackEn: "supporter", tip: "noun", article: "der" },
    { de: "der Aufruhr", lookup: "Aufruhr", fallbackEn: "uproar", tip: "noun", article: "der" },
    { de: "die Empörung", lookup: "Empörung", fallbackEn: "outrage", tip: "noun", article: "die" },
    { de: "der Einbruch", lookup: "Einbruch", fallbackEn: "break-in", tip: "noun", article: "der" },
    { de: "der Zulauf", lookup: "Zulauf", fallbackEn: "influx", tip: "noun", article: "der" },
    { de: "die Minderheit", lookup: "Minderheit", fallbackEn: "minority", tip: "noun", article: "die" },
    { de: "der Wahlkampf", lookup: "Wahlkampf", fallbackEn: "election campaign", tip: "noun", article: "der" },
    { de: "der Haushaltsplan", lookup: "Haushaltsplan", fallbackEn: "budget plan", tip: "noun", article: "der" },
  ]),
  part548: pack("Part 548", "B1", "Words to eight thousand 4", "Reviewed words no pack taught yet, 94–124 of 156.", [
    { de: "der Vorwand", lookup: "Vorwand", fallbackEn: "excuse, pretext", tip: "noun", article: "der", use: "a reason given to hide the real one: unter dem Vorwand, dass … — on the pretext that …" },
    { de: "die Verschwörung", lookup: "Verschwörung", fallbackEn: "conspiracy", tip: "noun", article: "die" },
    { de: "der Demonstrant", lookup: "Demonstrant", fallbackEn: "protester", tip: "noun", article: "der" },
    { de: "der Ärmelkanal", lookup: "Ärmelkanal", fallbackEn: "the English Channel", tip: "noun", article: "der" },
    { de: "das Schlauchboot", lookup: "Schlauchboot", fallbackEn: "dinghy", tip: "noun", article: "das" },
    { de: "die Wunschliste", lookup: "Wunschliste", fallbackEn: "wish list", tip: "noun", article: "die" },
    { de: "das Abstellgleis", lookup: "Abstellgleis", fallbackEn: "siding", tip: "noun", article: "das" },
    { de: "der Schurkenstaat", lookup: "Schurkenstaat", fallbackEn: "rogue state", tip: "noun", article: "der" },
    { de: "der Nachtclub", lookup: "Nachtclub", fallbackEn: "nightclub", tip: "noun", article: "der" },
    { de: "das Vertrauensproblem", lookup: "Vertrauensproblem", fallbackEn: "trust problem", tip: "noun", article: "das" },
    { de: "der Installationsprozess", lookup: "Installationsprozess", fallbackEn: "installation process", tip: "noun", article: "der" },
    { de: "das Asyl", lookup: "Asyl", fallbackEn: "asylum", tip: "noun", article: "das" },
    { de: "der Behälter", lookup: "Behälter", fallbackEn: "container", tip: "noun", article: "der" },
    { de: "das Lehrbuch", lookup: "Lehrbuch", fallbackEn: "textbook", tip: "noun", article: "das" },
    { de: "die Vertrauenswürdigkeit", lookup: "Vertrauenswürdigkeit", fallbackEn: "trustworthiness", tip: "noun", article: "die" },
    { de: "der Blödsinn", lookup: "Blödsinn", fallbackEn: "nonsense", tip: "noun", article: "der" },
    { de: "betreten", lookup: "betreten", fallbackEn: "to enter", tip: "verb" },
    { de: "wiederverwenden", lookup: "wiederverwenden", fallbackEn: "to reuse", tip: "verb" },
    { de: "simulieren", lookup: "simulieren", fallbackEn: "to simulate", tip: "verb" },
    { de: "durchsuchen", lookup: "durchsuchen", fallbackEn: "to search through", tip: "verb" },
    { de: "hinnehmen", lookup: "hinnehmen", fallbackEn: "to put up with", tip: "verb" },
    { de: "zusehen", lookup: "zusehen", fallbackEn: "to watch", tip: "verb" },
    { de: "halbieren", lookup: "halbieren", fallbackEn: "to halve", tip: "verb" },
    { de: "patchen", lookup: "patchen", fallbackEn: "to patch", tip: "verb" },
    { de: "misshandeln", lookup: "misshandeln", fallbackEn: "to abuse", tip: "verb" },
    { de: "drucken", lookup: "drucken", fallbackEn: "to print", tip: "verb" },
    { de: "favorisieren", lookup: "favorisieren", fallbackEn: "to favour", tip: "verb" },
    { de: "herauskommen", lookup: "herauskommen", fallbackEn: "to come out", tip: "verb" },
    { de: "überleben", lookup: "überleben", fallbackEn: "to survive", tip: "verb" },
    { de: "hereinbrechen", lookup: "hereinbrechen", fallbackEn: "to set in", tip: "verb" },
    { de: "bezweifeln", lookup: "bezweifeln", fallbackEn: "to doubt", tip: "verb" },
  ]),
  part549: pack("Part 549", "B1", "Words to eight thousand 5", "Reviewed words no pack taught yet, 125–155 of 156.", [
    { de: "herumlaufen", lookup: "herumlaufen", fallbackEn: "to walk around", tip: "verb" },
    { de: "zurückschlagen", lookup: "zurückschlagen", fallbackEn: "to strike back", tip: "verb" },
    { de: "erwägen", lookup: "erwägen", fallbackEn: "to consider", tip: "verb" },
    { de: "horten", lookup: "horten", fallbackEn: "to hoard", tip: "verb" },
    { de: "umgeben", lookup: "umgeben", fallbackEn: "to surround", tip: "verb" },
    { de: "umbenennen", lookup: "umbenennen", fallbackEn: "to rename", tip: "verb" },
    { de: "überqueren", lookup: "überqueren", fallbackEn: "to cross", tip: "verb" },
    { de: "sichten", lookup: "sichten", fallbackEn: "to sight", tip: "verb" },
    { de: "monetarisieren", lookup: "monetarisieren", fallbackEn: "to monetise", tip: "verb" },
    { de: "billiger", lookup: "billiger", fallbackEn: "cheaper", tip: "adjective" },
    { de: "sämtlich", lookup: "sämtlich", fallbackEn: "entire", tip: "adjective" },
    { de: "unbedingt", lookup: "unbedingt", fallbackEn: "absolutely", tip: "adjective" },
    { de: "endlich", lookup: "endlich", fallbackEn: "finally", tip: "adjective" },
    { de: "froh", lookup: "froh", fallbackEn: "glad", tip: "adjective" },
    { de: "härter", lookup: "härter", fallbackEn: "harder", tip: "adjective" },
    { de: "fantastisch", lookup: "fantastisch", fallbackEn: "incredible", tip: "adjective" },
    { de: "gebildet", lookup: "gebildet", fallbackEn: "educated", tip: "adjective" },
    { de: "gefälscht", lookup: "gefälscht", fallbackEn: "fake", tip: "adjective" },
    { de: "gotisch", lookup: "gotisch", fallbackEn: "gothic", tip: "adjective" },
    { de: "praxisnah", lookup: "praxisnah", fallbackEn: "real-world", tip: "adjective" },
    { de: "wiederverwendbar", lookup: "wiederverwendbar", fallbackEn: "reusable", tip: "adjective" },
    { de: "wiederkehrend", lookup: "wiederkehrend", fallbackEn: "recurring", tip: "adjective" },
    { de: "umgangssprachlich", lookup: "umgangssprachlich", fallbackEn: "colloquial", tip: "adjective" },
    { de: "erweitert", lookup: "erweitert", fallbackEn: "advanced", tip: "adjective" },
    { de: "geplant", lookup: "geplant", fallbackEn: "planned", tip: "adjective" },
    { de: "aktualisiert", lookup: "aktualisiert", fallbackEn: "updated", tip: "adjective" },
    { de: "gestern", lookup: "gestern", fallbackEn: "yesterday", tip: "adverb" },
    { de: "israelisch", lookup: "israelisch", fallbackEn: "Israeli", tip: "adjective" },
    { de: "ikonisch", lookup: "ikonisch", fallbackEn: "iconic", tip: "adjective" },
    { de: "inspirierend", lookup: "inspirierend", fallbackEn: "inspiring", tip: "adjective" },
    { de: "inakzeptabel", lookup: "inakzeptabel", fallbackEn: "unacceptable", tip: "adjective" },
  ]),
  part550: pack("Part 550", "B1", "Words to eight thousand 6", "Reviewed words no pack taught yet, 156–156 of 156.", [
    { de: "ausgedehnt", lookup: "ausgedehnt", fallbackEn: "extended", tip: "adjective" },
  ]),
};
