import type { Blueprint, VocabSeed } from "./types";

/**
 * Five hundred words read out of an eight-thousand-row spreadsheet.
 *
 * THE SOURCE was a single column of German, articles included on the nouns and
 * nothing else - no English, no part of speech, no order. Eight thousand rows
 * hold 2,495 words, because the sheet lists an adjective once per case ending
 * and a verb once per participle form: froh arrives five times, sagen seven.
 * They collapse to the form a card teaches, which is the form a dictionary
 * lists - froh, not frohem; sagen, not sagendem.
 *
 * WHAT WAS LEFT OUT, since that is the half that decides quality. 1,696 words
 * were already taught and are not taught twice. 99 are grammar words - der,
 * dich, weder - which the sentences teach and which would need a part of
 * speech invented for them, the same rule parts 545-550 were written under.
 * 64 are not German: the sheet builds adjectives by gluing -artig onto
 * whatever it has, so langsamartig, stolzartig and flexibelartig sit in it
 * beside real words, and a course teaching those teaches something nobody says.
 *
 * THE ENGLISH, THE FRENCH AND THE POLISH were written here, because the sheet
 * carried none of them. Every noun keeps the article the sheet gave it, with
 * one correction: it had das Ausweis.
 *
 * Append-only after release, like every word pack: progress is global by lemma
 * and pack order is curriculum order.
 */
const focus = "Everyday German from a bulk word list, reviewed word by word: the things in a home, what you do to them, and how they are described.";

const pack = (label: string, level: string, theme: string, description: string, seeds: VocabSeed[]): Blueprint => ({
  label,
  level,
  theme,
  description,
  focus,
  seeds,
  dialogues: [],
  phrases: [],
});

export const sheetWordPartBlueprints: Record<string, Blueprint> = {
  part585: pack("Part 585", "A2", "Words for words", "The grammar words a course needs to explain itself: the parts of speech and the four cases, by name.", [
    { de: "das Adjektiv", lookup: "Adjektiv", fallbackEn: "adjective", tip: "noun", article: "das" },
    { de: "das Adverb", lookup: "Adverb", fallbackEn: "adverb", tip: "noun", article: "das" },
    { de: "das Nomen", lookup: "Nomen", fallbackEn: "noun", tip: "noun", article: "das", use: "the grammar word; das Substantiv is the other name for it" },
    { de: "das Pronomen", lookup: "Pronomen", fallbackEn: "pronoun", tip: "noun", article: "das" },
    { de: "das Verb", lookup: "Verb", fallbackEn: "verb", tip: "noun", article: "das" },
    { de: "die Präposition", lookup: "Präposition", fallbackEn: "preposition", tip: "noun", article: "die" },
    { de: "die Konjunktion", lookup: "Konjunktion", fallbackEn: "conjunction", tip: "noun", article: "die" },
    { de: "der Nominativ", lookup: "Nominativ", fallbackEn: "nominative", tip: "noun", article: "der", use: "the case a subject stands in: der Mann schläft" },
    { de: "der Akkusativ", lookup: "Akkusativ", fallbackEn: "accusative", tip: "noun", article: "der", use: "the case a direct object stands in: ich sehe den Mann" },
    { de: "der Dativ", lookup: "Dativ", fallbackEn: "dative", tip: "noun", article: "der", use: "the case an indirect object stands in: ich gebe dem Mann das Buch" },
    { de: "der Genitiv", lookup: "Genitiv", fallbackEn: "genitive", tip: "noun", article: "der", use: "the possessive case: das Auto des Mannes" },
    { de: "der Singular", lookup: "Singular", fallbackEn: "singular", tip: "noun", article: "der" },
    { de: "der Plural", lookup: "Plural", fallbackEn: "plural", tip: "noun", article: "der" },
    { de: "das Wörterbuch", lookup: "Wörterbuch", fallbackEn: "dictionary", tip: "noun", article: "das" },
    { de: "die Schrift", lookup: "Schrift", fallbackEn: "writing, script, font", tip: "noun", article: "die", use: "handwriting, a script, and the font on a screen" },
    { de: "portugiesisch", lookup: "portugiesisch", fallbackEn: "Portuguese", tip: "adjective", use: "the language and anything from Portugal; lower case as an adjective" },
  ]),
  part586: pack("Part 586", "A1", "Rooms and what stands in them", "The rooms of a home, the stairs and lift between them, and the everyday things inside.", [
    { de: "das Bad", lookup: "Bad", fallbackEn: "bathroom, bath", tip: "noun", article: "das", use: "the room; ein Bad nehmen = to take a bath" },
    { de: "das Schlafzimmer", lookup: "Schlafzimmer", fallbackEn: "bedroom", tip: "noun", article: "das" },
    { de: "das Wohnzimmer", lookup: "Wohnzimmer", fallbackEn: "living room", tip: "noun", article: "das" },
    { de: "das Kinderzimmer", lookup: "Kinderzimmer", fallbackEn: "children's room", tip: "noun", article: "das" },
    { de: "das Sofa", lookup: "Sofa", fallbackEn: "sofa, couch", tip: "noun", article: "das" },
    { de: "der Stuhl", lookup: "Stuhl", fallbackEn: "chair", tip: "noun", article: "der", use: "a chair with a back; der Sessel is an armchair" },
    { de: "der Flur", lookup: "Flur", fallbackEn: "hallway, corridor", tip: "noun", article: "der", use: "the hall inside a flat or house" },
    { de: "die Etage", lookup: "Etage", fallbackEn: "floor, storey", tip: "noun", article: "die", use: "in der dritten Etage = on the third floor" },
    { de: "die Treppe", lookup: "Treppe", fallbackEn: "stairs, staircase", tip: "noun", article: "die" },
    { de: "der Aufzug", lookup: "Aufzug", fallbackEn: "lift, elevator", tip: "noun", article: "der" },
    { de: "der Lift", lookup: "Lift", fallbackEn: "lift, elevator", tip: "noun", article: "der", use: "the short everyday word for der Aufzug" },
    { de: "die Garage", lookup: "Garage", fallbackEn: "garage", tip: "noun", article: "die", use: "pronounced the French way: ga-RAH-zhe" },
    { de: "die Waschmaschine", lookup: "Waschmaschine", fallbackEn: "washing machine", tip: "noun", article: "die" },
    { de: "der Trockner", lookup: "Trockner", fallbackEn: "tumble dryer", tip: "noun", article: "der" },
    { de: "die Kaffeemaschine", lookup: "Kaffeemaschine", fallbackEn: "coffee machine", tip: "noun", article: "die" },
    { de: "das Messer", lookup: "Messer", fallbackEn: "knife", tip: "noun", article: "das" },
    { de: "die Gabel", lookup: "Gabel", fallbackEn: "fork", tip: "noun", article: "die" },
    { de: "der Löffel", lookup: "Löffel", fallbackEn: "spoon", tip: "noun", article: "der" },
    { de: "das Seil", lookup: "Seil", fallbackEn: "rope", tip: "noun", article: "das" },
    { de: "der Stift", lookup: "Stift", fallbackEn: "pen, pencil", tip: "noun", article: "der", use: "the everyday word for anything you write with" },
    { de: "der Marker", lookup: "Marker", fallbackEn: "marker pen, highlighter", tip: "noun", article: "der" },
    { de: "der Schmuck", lookup: "Schmuck", fallbackEn: "jewellery", tip: "noun", article: "der", use: "singular in German, plural in English: der Schmuck ist teuer" },
    { de: "der Ring", lookup: "Ring", fallbackEn: "ring", tip: "noun", article: "der" },
    { de: "die Brille", lookup: "Brille", fallbackEn: "glasses, spectacles", tip: "noun", article: "die", use: "singular in German: meine Brille ist neu" },
    { de: "die Sonnenbrille", lookup: "Sonnenbrille", fallbackEn: "sunglasses", tip: "noun", article: "die" },
    { de: "die Hose", lookup: "Hose", fallbackEn: "trousers, pants", tip: "noun", article: "die", use: "singular in German: die Hose ist zu eng" },
    { de: "die Jeans", lookup: "Jeans", fallbackEn: "jeans", tip: "noun", article: "die" },
    { de: "das Armband", lookup: "Armband", fallbackEn: "bracelet, wristband", tip: "noun", article: "das" },
  ]),
  part587: pack("Part 587", "A2", "Papers, platforms and places", "The documents you show, the platform you wait on and the corners of a town you walk through.", [
    { de: "der Ausweis", lookup: "Ausweis", fallbackEn: "ID card, identity document", tip: "noun", article: "der", use: "the card you show to prove who you are" },
    { de: "der Führerschein", lookup: "Führerschein", fallbackEn: "driving licence", tip: "noun", article: "der" },
    { de: "die Fahrkarte", lookup: "Fahrkarte", fallbackEn: "ticket", tip: "noun", article: "die", use: "for a train, bus or tram" },
    { de: "der Bahnsteig", lookup: "Bahnsteig", fallbackEn: "platform", tip: "noun", article: "der", use: "the platform a train pulls into" },
    { de: "die Bahnhofshalle", lookup: "Bahnhofshalle", fallbackEn: "station concourse", tip: "noun", article: "die", use: "the covered hall inside a station" },
    { de: "das Taxi", lookup: "Taxi", fallbackEn: "taxi, cab", tip: "noun", article: "das" },
    { de: "der Tunnel", lookup: "Tunnel", fallbackEn: "tunnel", tip: "noun", article: "der" },
    { de: "der Pfad", lookup: "Pfad", fallbackEn: "path, trail", tip: "noun", article: "der", use: "a narrow walking path; also a file path" },
    { de: "die Gasse", lookup: "Gasse", fallbackEn: "lane, alley", tip: "noun", article: "die", use: "a narrow street between buildings" },
    { de: "die Kurve", lookup: "Kurve", fallbackEn: "bend, curve", tip: "noun", article: "die", use: "in the road, and a curve on a graph" },
    { de: "der Spaziergang", lookup: "Spaziergang", fallbackEn: "walk, stroll", tip: "noun", article: "der", use: "einen Spaziergang machen = to go for a walk" },
    { de: "der Supermarkt", lookup: "Supermarkt", fallbackEn: "supermarket", tip: "noun", article: "der" },
    { de: "die Arztpraxis", lookup: "Arztpraxis", fallbackEn: "doctor's surgery, doctor's office", tip: "noun", article: "die" },
    { de: "die Pension", lookup: "Pension", fallbackEn: "guest house, B&B", tip: "noun", article: "die", use: "a small family-run place to stay; also a pension" },
    { de: "die Ferne", lookup: "Ferne", fallbackEn: "distance", tip: "noun", article: "die", use: "in der Ferne = in the distance" },
  ]),
  part588: pack("Part 588", "A1", "Lunch and what is on the table", "The midday meal, the food on it, and being hungry or thirsty.", [
    { de: "das Mittagessen", lookup: "Mittagessen", fallbackEn: "lunch", tip: "noun", article: "das" },
    { de: "die Mahlzeit", lookup: "Mahlzeit", fallbackEn: "meal", tip: "noun", article: "die", use: "also said as a greeting around midday in offices and canteens" },
    { de: "das Salz", lookup: "Salz", fallbackEn: "salt", tip: "noun", article: "das" },
    { de: "der Pfeffer", lookup: "Pfeffer", fallbackEn: "pepper", tip: "noun", article: "der", use: "the spice; a bell pepper is die Paprika" },
    { de: "der Käse", lookup: "Käse", fallbackEn: "cheese", tip: "noun", article: "der" },
    { de: "der Reis", lookup: "Reis", fallbackEn: "rice", tip: "noun", article: "der" },
    { de: "die Butter", lookup: "Butter", fallbackEn: "butter", tip: "noun", article: "die" },
    { de: "die Nudel", lookup: "Nudel", fallbackEn: "noodle, piece of pasta", tip: "noun", article: "die", use: "usually plural: die Nudeln = pasta" },
    { de: "die Pasta", lookup: "Pasta", fallbackEn: "pasta", tip: "noun", article: "die", use: "the Italian word, used for the dish" },
    { de: "die Pizza", lookup: "Pizza", fallbackEn: "pizza", tip: "noun", article: "die" },
    { de: "die Soße", lookup: "Soße", fallbackEn: "sauce, gravy", tip: "noun", article: "die", use: "also spelled Sauce on menus" },
    { de: "die Schokolade", lookup: "Schokolade", fallbackEn: "chocolate", tip: "noun", article: "die" },
    { de: "der Saft", lookup: "Saft", fallbackEn: "juice", tip: "noun", article: "der" },
    { de: "das Protein", lookup: "Protein", fallbackEn: "protein", tip: "noun", article: "das" },
    { de: "der Hunger", lookup: "Hunger", fallbackEn: "hunger", tip: "noun", article: "der", use: "Ich habe Hunger = I'm hungry, with no article" },
    { de: "der Durst", lookup: "Durst", fallbackEn: "thirst", tip: "noun", article: "der", use: "Ich habe Durst = I'm thirsty, with no article" },
  ]),
  part589: pack("Part 589", "A2", "Who people are", "Jobs and family in the feminine forms the course had only in the masculine, and the two university degrees.", [
    { de: "die Ärztin", lookup: "Ärztin", fallbackEn: "doctor (female)", tip: "noun", article: "die" },
    { de: "die Chefin", lookup: "Chefin", fallbackEn: "boss (female)", tip: "noun", article: "die" },
    { de: "die Fahrerin", lookup: "Fahrerin", fallbackEn: "driver (female)", tip: "noun", article: "die" },
    { de: "die Kundin", lookup: "Kundin", fallbackEn: "client (female), customer", tip: "noun", article: "die", use: "der Kunde is the masculine form; the extension glossary keeps customer pointing at it" },
    { de: "die Nachbarin", lookup: "Nachbarin", fallbackEn: "neighbour (female)", tip: "noun", article: "die" },
    { de: "die Partnerin", lookup: "Partnerin", fallbackEn: "partner (female)", tip: "noun", article: "die" },
    { de: "die Schauspielerin", lookup: "Schauspielerin", fallbackEn: "actress", tip: "noun", article: "die" },
    { de: "die Spielerin", lookup: "Spielerin", fallbackEn: "player (female)", tip: "noun", article: "die" },
    { de: "die Studentin", lookup: "Studentin", fallbackEn: "student (female)", tip: "noun", article: "die", use: "at university; a school pupil is die Schülerin" },
    { de: "die Sängerin", lookup: "Sängerin", fallbackEn: "singer (female)", tip: "noun", article: "die" },
    { de: "die Trainerin", lookup: "Trainerin", fallbackEn: "coach, trainer (female)", tip: "noun", article: "die" },
    { de: "die Verkäuferin", lookup: "Verkäuferin", fallbackEn: "shop assistant (female)", tip: "noun", article: "die" },
    { de: "der Sportler", lookup: "Sportler", fallbackEn: "athlete, sportsman", tip: "noun", article: "der" },
    { de: "der Großvater", lookup: "Großvater", fallbackEn: "grandfather", tip: "noun", article: "der", use: "the formal word; everyday German says Opa" },
    { de: "die Großmutter", lookup: "Großmutter", fallbackEn: "grandmother", tip: "noun", article: "die", use: "the formal word; everyday German says Oma" },
    { de: "der Bachelor", lookup: "Bachelor", fallbackEn: "bachelor's degree", tip: "noun", article: "der", use: "the first university degree" },
    { de: "der Master", lookup: "Master", fallbackEn: "master's degree", tip: "noun", article: "der" },
  ]),
  part590: pack("Part 590", "A2", "Sport and the outdoors", "The ball games by name, the gear you take camping, and the hobbies German turns into nouns.", [
    { de: "das Hobby", lookup: "Hobby", fallbackEn: "hobby", tip: "noun", article: "das" },
    { de: "das Tennis", lookup: "Tennis", fallbackEn: "tennis", tip: "noun", article: "das" },
    { de: "das Badminton", lookup: "Badminton", fallbackEn: "badminton", tip: "noun", article: "das" },
    { de: "das Hockey", lookup: "Hockey", fallbackEn: "hockey", tip: "noun", article: "das" },
    { de: "das Golf", lookup: "Golf", fallbackEn: "golf", tip: "noun", article: "das" },
    { de: "das Yoga", lookup: "Yoga", fallbackEn: "yoga", tip: "noun", article: "das" },
    { de: "das Boxen", lookup: "Boxen", fallbackEn: "boxing", tip: "noun", article: "das", use: "the sport, from boxen = to box" },
    { de: "der Basketball", lookup: "Basketball", fallbackEn: "basketball", tip: "noun", article: "der" },
    { de: "der Handball", lookup: "Handball", fallbackEn: "handball", tip: "noun", article: "der" },
    { de: "der Volleyball", lookup: "Volleyball", fallbackEn: "volleyball", tip: "noun", article: "der" },
    { de: "der Ski", lookup: "Ski", fallbackEn: "ski", tip: "noun", article: "der", use: "Ski fahren = to go skiing, written as two words" },
    { de: "der Schläger", lookup: "Schläger", fallbackEn: "racket, bat, club", tip: "noun", article: "der", use: "whatever you hit the ball with" },
    { de: "das Turnier", lookup: "Turnier", fallbackEn: "tournament", tip: "noun", article: "das" },
    { de: "die Liga", lookup: "Liga", fallbackEn: "league", tip: "noun", article: "die" },
    { de: "die Fitness", lookup: "Fitness", fallbackEn: "fitness", tip: "noun", article: "die", use: "also the gym sense: ins Fitnessstudio gehen" },
    { de: "das Radfahren", lookup: "Radfahren", fallbackEn: "cycling", tip: "noun", article: "das" },
    { de: "das Tanzen", lookup: "Tanzen", fallbackEn: "dancing", tip: "noun", article: "das" },
    { de: "das Malen", lookup: "Malen", fallbackEn: "painting", tip: "noun", article: "das", use: "the activity, from malen = to paint" },
    { de: "das Fotografieren", lookup: "Fotografieren", fallbackEn: "photography", tip: "noun", article: "das", use: "the activity, from fotografieren" },
    { de: "das Camping", lookup: "Camping", fallbackEn: "camping", tip: "noun", article: "das" },
    { de: "das Zelt", lookup: "Zelt", fallbackEn: "tent", tip: "noun", article: "das" },
    { de: "der Schlafsack", lookup: "Schlafsack", fallbackEn: "sleeping bag", tip: "noun", article: "der" },
    { de: "das Picknick", lookup: "Picknick", fallbackEn: "picnic", tip: "noun", article: "das" },
    { de: "der Grill", lookup: "Grill", fallbackEn: "barbecue, grill", tip: "noun", article: "der" },
    { de: "der Sonnenschirm", lookup: "Sonnenschirm", fallbackEn: "parasol, sunshade", tip: "noun", article: "der" },
    { de: "der Pool", lookup: "Pool", fallbackEn: "swimming pool", tip: "noun", article: "der", use: "the everyday word; das Schwimmbad is a public pool" },
  ]),
  part591: pack("Part 591", "B1", "Things the course had no name for", "Ordinary nouns from either side of a day: a scanner and an icon, flu and a rescue, cold and a flame.", [
    { de: "das Icon", lookup: "Icon", fallbackEn: "icon", tip: "noun", article: "das", use: "on a screen" },
    { de: "die Hardware", lookup: "Hardware", fallbackEn: "hardware", tip: "noun", article: "die", use: "the physical machine, against die Software" },
    { de: "der Scanner", lookup: "Scanner", fallbackEn: "scanner", tip: "noun", article: "der" },
    { de: "der Upload", lookup: "Upload", fallbackEn: "upload", tip: "noun", article: "der" },
    { de: "die Biologie", lookup: "Biologie", fallbackEn: "biology", tip: "noun", article: "die" },
    { de: "die Geografie", lookup: "Geografie", fallbackEn: "geography", tip: "noun", article: "die", use: "also spelled Geographie" },
    { de: "die Konzentration", lookup: "Konzentration", fallbackEn: "concentration", tip: "noun", article: "die" },
    { de: "die Entschuldigung", lookup: "Entschuldigung", fallbackEn: "apology, excuse", tip: "noun", article: "die", use: "Entschuldigung! on its own means sorry or excuse me" },
    { de: "die Erholung", lookup: "Erholung", fallbackEn: "rest, recovery", tip: "noun", article: "die", use: "the resting you do after effort or illness" },
    { de: "die Flamme", lookup: "Flamme", fallbackEn: "flame", tip: "noun", article: "die" },
    { de: "die Kälte", lookup: "Kälte", fallbackEn: "coldness, the cold", tip: "noun", article: "die", use: "the cold as a thing; kalt is the adjective" },
    { de: "die Niederlage", lookup: "Niederlage", fallbackEn: "defeat", tip: "noun", article: "die", use: "the opposite of der Sieg" },
    { de: "die Rettung", lookup: "Rettung", fallbackEn: "rescue", tip: "noun", article: "die" },
    { de: "die Reservierung", lookup: "Reservierung", fallbackEn: "reservation, booking", tip: "noun", article: "die" },
    { de: "der Notfall", lookup: "Notfall", fallbackEn: "emergency", tip: "noun", article: "der", use: "im Notfall = in an emergency" },
    { de: "der Planet", lookup: "Planet", fallbackEn: "planet", tip: "noun", article: "der" },
    { de: "der Tiger", lookup: "Tiger", fallbackEn: "tiger", tip: "noun", article: "der" },
    { de: "das Geräusch", lookup: "Geräusch", fallbackEn: "sound, noise", tip: "noun", article: "das", use: "any sound; der Lärm is noise that bothers you" },
    { de: "der Cent", lookup: "Cent", fallbackEn: "cent", tip: "noun", article: "der", use: "the hundredth of a euro" },
  ]),
  part592: pack("Part 592", "B1", "The German of screens", "What you do to a file, a page or an account, from anklicken to verschluesseln.", [
    { de: "abspielen", lookup: "abspielen", fallbackEn: "to play (a recording)", tip: "verb", use: "a file, a video or a track, not a game" },
    { de: "anklicken", lookup: "anklicken", fallbackEn: "to click on", tip: "verb" },
    { de: "ausloggen", lookup: "ausloggen", fallbackEn: "to log out", tip: "verb", use: "sich ausloggen; einloggen is the other way" },
    { de: "ausschalten", lookup: "ausschalten", fallbackEn: "to switch off", tip: "verb", use: "einschalten is to switch on" },
    { de: "downloaden", lookup: "downloaden", fallbackEn: "to download", tip: "verb", use: "herunterladen is the German word for the same thing" },
    { de: "eintippen", lookup: "eintippen", fallbackEn: "to type in", tip: "verb", use: "tippen is to type, eintippen is to type something in" },
    { de: "entpacken", lookup: "entpacken", fallbackEn: "to unzip, to unpack", tip: "verb", use: "a zip file, and a suitcase" },
    { de: "zippen", lookup: "zippen", fallbackEn: "to zip", tip: "verb", use: "to put files into a zip archive" },
    { de: "komprimieren", lookup: "komprimieren", fallbackEn: "to compress", tip: "verb" },
    { de: "exportieren", lookup: "exportieren", fallbackEn: "to export", tip: "verb" },
    { de: "importieren", lookup: "importieren", fallbackEn: "to import", tip: "verb" },
    { de: "kopieren", lookup: "kopieren", fallbackEn: "to copy", tip: "verb" },
    { de: "konfigurieren", lookup: "konfigurieren", fallbackEn: "to configure", tip: "verb" },
    { de: "digitalisieren", lookup: "digitalisieren", fallbackEn: "to digitise", tip: "verb" },
    { de: "automatisieren", lookup: "automatisieren", fallbackEn: "to automate", tip: "verb" },
    { de: "personalisieren", lookup: "personalisieren", fallbackEn: "to personalise", tip: "verb" },
    { de: "rendern", lookup: "rendern", fallbackEn: "to render", tip: "verb", use: "IT loanword: video and graphics" },
    { de: "scannen", lookup: "scannen", fallbackEn: "to scan", tip: "verb" },
    { de: "scrollen", lookup: "scrollen", fallbackEn: "to scroll", tip: "verb" },
    { de: "zoomen", lookup: "zoomen", fallbackEn: "to zoom", tip: "verb" },
    { de: "liken", lookup: "liken", fallbackEn: "to like (online)", tip: "verb", use: "social-media loanword; the German verb is gefallen" },
    { de: "chatten", lookup: "chatten", fallbackEn: "to chat (online)", tip: "verb" },
    { de: "mailen", lookup: "mailen", fallbackEn: "to email", tip: "verb" },
    { de: "faxen", lookup: "faxen", fallbackEn: "to fax", tip: "verb" },
    { de: "codieren", lookup: "codieren", fallbackEn: "to code, to encode", tip: "verb" },
    { de: "designen", lookup: "designen", fallbackEn: "to design", tip: "verb", use: "loanword; gestalten is the German verb" },
    { de: "stylen", lookup: "stylen", fallbackEn: "to style", tip: "verb", use: "hair, clothes, a page" },
    { de: "verschlüsseln", lookup: "verschlüsseln", fallbackEn: "to encrypt", tip: "verb" },
    { de: "entschlüsseln", lookup: "entschlüsseln", fallbackEn: "to decrypt, to decipher", tip: "verb" },
    { de: "markieren", lookup: "markieren", fallbackEn: "to mark, to select", tip: "verb", use: "text on a screen, and a spot on a map" },
    { de: "etikettieren", lookup: "etikettieren", fallbackEn: "to label", tip: "verb" },
    { de: "nummerieren", lookup: "nummerieren", fallbackEn: "to number", tip: "verb" },
    { de: "notieren", lookup: "notieren", fallbackEn: "to note down", tip: "verb" },
    { de: "skizzieren", lookup: "skizzieren", fallbackEn: "to sketch, to outline", tip: "verb", use: "a drawing, and a plan in rough" },
    { de: "strukturieren", lookup: "strukturieren", fallbackEn: "to structure", tip: "verb" },
    { de: "kategorisieren", lookup: "kategorisieren", fallbackEn: "to categorise", tip: "verb" },
    { de: "klassifizieren", lookup: "klassifizieren", fallbackEn: "to classify", tip: "verb" },
    { de: "gruppieren", lookup: "gruppieren", fallbackEn: "to group", tip: "verb" },
    { de: "kalkulieren", lookup: "kalkulieren", fallbackEn: "to calculate, to cost out", tip: "verb", use: "rechnen is the everyday word for doing sums" },
    { de: "kalibrieren", lookup: "kalibrieren", fallbackEn: "to calibrate", tip: "verb" },
    { de: "verifizieren", lookup: "verifizieren", fallbackEn: "to verify", tip: "verb" },
  ]),
  part593: pack("Part 593", "B1", "Making, mending and cleaning", "The verbs of a workbench and a household: gluing, sawing, stacking, airing, drying.", [
    { de: "befestigen", lookup: "befestigen", fallbackEn: "to fix, to fasten", tip: "verb", use: "to attach something so it stays put" },
    { de: "heften", lookup: "heften", fallbackEn: "to staple, to pin", tip: "verb", use: "paper together" },
    { de: "kleben", lookup: "kleben", fallbackEn: "to glue, to stick", tip: "verb" },
    { de: "kleistern", lookup: "kleistern", fallbackEn: "to paste", tip: "verb", use: "wallpaper, with paste" },
    { de: "lochen", lookup: "lochen", fallbackEn: "to punch a hole in", tip: "verb", use: "paper, for a ring binder" },
    { de: "hämmern", lookup: "hämmern", fallbackEn: "to hammer", tip: "verb" },
    { de: "schleifen", lookup: "schleifen", fallbackEn: "to sand, to grind", tip: "verb", use: "wood or metal smooth" },
    { de: "schnitzen", lookup: "schnitzen", fallbackEn: "to carve", tip: "verb", use: "in wood" },
    { de: "polieren", lookup: "polieren", fallbackEn: "to polish", tip: "verb" },
    { de: "lackieren", lookup: "lackieren", fallbackEn: "to varnish, to paint", tip: "verb", use: "with a hard glossy coat; also nail varnish" },
    { de: "montieren", lookup: "montieren", fallbackEn: "to assemble, to fit", tip: "verb", use: "to put a thing together or onto a wall" },
    { de: "demontieren", lookup: "demontieren", fallbackEn: "to dismantle", tip: "verb" },
    { de: "modellieren", lookup: "modellieren", fallbackEn: "to model, to shape", tip: "verb", use: "in clay, and a model of a system" },
    { de: "formen", lookup: "formen", fallbackEn: "to form, to shape", tip: "verb" },
    { de: "weben", lookup: "weben", fallbackEn: "to weave", tip: "verb" },
    { de: "häkeln", lookup: "häkeln", fallbackEn: "to crochet", tip: "verb" },
    { de: "knöpfen", lookup: "knöpfen", fallbackEn: "to button", tip: "verb", use: "zuknöpfen is the everyday form" },
    { de: "kämmen", lookup: "kämmen", fallbackEn: "to comb", tip: "verb" },
    { de: "saugen", lookup: "saugen", fallbackEn: "to vacuum, to suck", tip: "verb", use: "staubsaugen is the full word for hoovering" },
    { de: "spülen", lookup: "spülen", fallbackEn: "to rinse, to wash up", tip: "verb", use: "dishes, and rinsing anything under water" },
    { de: "stapeln", lookup: "stapeln", fallbackEn: "to stack", tip: "verb" },
    { de: "packen", lookup: "packen", fallbackEn: "to pack, to grab", tip: "verb", use: "a suitcase, and taking hold of something hard" },
    { de: "lagern", lookup: "lagern", fallbackEn: "to store", tip: "verb", use: "to keep goods somewhere until they are needed" },
    { de: "trocknen", lookup: "trocknen", fallbackEn: "to dry", tip: "verb" },
    { de: "lüften", lookup: "lüften", fallbackEn: "to air, to ventilate", tip: "verb", use: "opening the window is a daily German habit" },
    { de: "abdunkeln", lookup: "abdunkeln", fallbackEn: "to darken, to dim", tip: "verb", use: "a room or a screen" },
    { de: "stempeln", lookup: "stempeln", fallbackEn: "to stamp", tip: "verb" },
    { de: "kehren", lookup: "kehren", fallbackEn: "to sweep", tip: "verb", use: "the floor or the street" },
    { de: "rösten", lookup: "rösten", fallbackEn: "to roast, to toast", tip: "verb", use: "coffee, nuts, bread" },
    { de: "portionieren", lookup: "portionieren", fallbackEn: "to portion out", tip: "verb" },
    { de: "mixen", lookup: "mixen", fallbackEn: "to mix, to blend", tip: "verb" },
    { de: "raspeln", lookup: "raspeln", fallbackEn: "to grate", tip: "verb", use: "carrots, cheese" },
  ]),
  part594: pack("Part 594", "B1", "Cameras, locks and levers", "Verbs for pictures, for locking and unlocking, and for what a body does to hold something up.", [
    { de: "belichten", lookup: "belichten", fallbackEn: "to expose", tip: "verb", use: "a photograph, to light" },
    { de: "filmen", lookup: "filmen", fallbackEn: "to film", tip: "verb" },
    { de: "fokussieren", lookup: "fokussieren", fallbackEn: "to focus", tip: "verb", use: "a camera, and your attention" },
    { de: "vergrößern", lookup: "vergrößern", fallbackEn: "to enlarge, to zoom in", tip: "verb", use: "verkleinern is the other way" },
    { de: "beschneiden", lookup: "beschneiden", fallbackEn: "to crop, to trim", tip: "verb", use: "a photo, a hedge" },
    { de: "dekorieren", lookup: "dekorieren", fallbackEn: "to decorate", tip: "verb" },
    { de: "möblieren", lookup: "möblieren", fallbackEn: "to furnish", tip: "verb" },
    { de: "renovieren", lookup: "renovieren", fallbackEn: "to renovate, to do up", tip: "verb" },
    { de: "entriegeln", lookup: "entriegeln", fallbackEn: "to unlock", tip: "verb", use: "a door or a screen; verriegeln is the other way" },
    { de: "verriegeln", lookup: "verriegeln", fallbackEn: "to lock, to bolt", tip: "verb" },
    { de: "koppeln", lookup: "koppeln", fallbackEn: "to pair, to couple", tip: "verb", use: "two devices, two carriages" },
    { de: "spannen", lookup: "spannen", fallbackEn: "to tighten, to be tight", tip: "verb", use: "a rope, and clothes that pull" },
    { de: "strecken", lookup: "strecken", fallbackEn: "to stretch", tip: "verb", use: "your legs, a material" },
    { de: "stemmen", lookup: "stemmen", fallbackEn: "to lift, to heave", tip: "verb", use: "weights, and something heavy against resistance" },
    { de: "lehnen", lookup: "lehnen", fallbackEn: "to lean", tip: "verb", use: "sich an etwas lehnen = to lean on something" },
    { de: "beugen", lookup: "beugen", fallbackEn: "to bend", tip: "verb", use: "an arm, a knee; sich beugen = to bow" },
    { de: "knien", lookup: "knien", fallbackEn: "to kneel", tip: "verb" },
    { de: "rollen", lookup: "rollen", fallbackEn: "to roll", tip: "verb" },
    { de: "bremsen", lookup: "bremsen", fallbackEn: "to brake, to slow down", tip: "verb" },
    { de: "stoppen", lookup: "stoppen", fallbackEn: "to stop", tip: "verb", use: "anhalten is the German verb for a vehicle stopping" },
  ]),
  part595: pack("Part 595", "B1", "Garden, ground and games outside", "Sowing, ploughing and composting, then the sports you do on water, snow and tarmac.", [
    { de: "gärtnern", lookup: "gärtnern", fallbackEn: "to garden", tip: "verb" },
    { de: "säen", lookup: "säen", fallbackEn: "to sow", tip: "verb" },
    { de: "düngen", lookup: "düngen", fallbackEn: "to fertilise", tip: "verb" },
    { de: "pflügen", lookup: "pflügen", fallbackEn: "to plough", tip: "verb" },
    { de: "pflücken", lookup: "pflücken", fallbackEn: "to pick", tip: "verb", use: "fruit, flowers" },
    { de: "keimen", lookup: "keimen", fallbackEn: "to germinate, to sprout", tip: "verb" },
    { de: "blühen", lookup: "blühen", fallbackEn: "to bloom, to flower", tip: "verb" },
    { de: "welken", lookup: "welken", fallbackEn: "to wilt, to wither", tip: "verb" },
    { de: "tränken", lookup: "tränken", fallbackEn: "to soak, to water", tip: "verb", use: "to soak something through, or water animals" },
    { de: "züchten", lookup: "züchten", fallbackEn: "to breed, to grow", tip: "verb", use: "animals, plants" },
    { de: "kompostieren", lookup: "kompostieren", fallbackEn: "to compost", tip: "verb" },
    { de: "recyceln", lookup: "recyceln", fallbackEn: "to recycle", tip: "verb" },
    { de: "buddeln", lookup: "buddeln", fallbackEn: "to dig", tip: "verb", use: "colloquial, what children do in sand; graben is neutral" },
    { de: "fischen", lookup: "fischen", fallbackEn: "to fish", tip: "verb", use: "angeln is the everyday word for fishing with a rod" },
    { de: "impfen", lookup: "impfen", fallbackEn: "to vaccinate", tip: "verb" },
    { de: "bummeln", lookup: "bummeln", fallbackEn: "to stroll, to dawdle", tip: "verb", use: "to wander with no hurry; also to be too slow" },
    { de: "paddeln", lookup: "paddeln", fallbackEn: "to paddle", tip: "verb", use: "in a canoe or kayak" },
    { de: "radeln", lookup: "radeln", fallbackEn: "to cycle", tip: "verb", use: "the casual word for Rad fahren" },
    { de: "rodeln", lookup: "rodeln", fallbackEn: "to sledge, to toboggan", tip: "verb" },
    { de: "skaten", lookup: "skaten", fallbackEn: "to skate, to skateboard", tip: "verb" },
    { de: "snowboarden", lookup: "snowboarden", fallbackEn: "to snowboard", tip: "verb" },
    { de: "surfen", lookup: "surfen", fallbackEn: "to surf", tip: "verb", use: "on water, and on the web" },
    { de: "dribbeln", lookup: "dribbeln", fallbackEn: "to dribble", tip: "verb", use: "with a ball" },
    { de: "kicken", lookup: "kicken", fallbackEn: "to kick, to play football", tip: "verb", use: "casual: kicken gehen = to go and play football" },
    { de: "köpfen", lookup: "köpfen", fallbackEn: "to head", tip: "verb", use: "to head a ball" },
    { de: "ringen", lookup: "ringen", fallbackEn: "to wrestle, to struggle", tip: "verb", use: "the sport, and struggling for words" },
  ]),
  part596: pack("Part 596", "B1", "Wonder, worry and working it out", "Verbs of feeling and of understanding, several of them reflexive: sich wundern, sich aergern, sich langweilen.", [
    { de: "staunen", lookup: "staunen", fallbackEn: "to be amazed", tip: "verb" },
    { de: "bewundern", lookup: "bewundern", fallbackEn: "to admire", tip: "verb" },
    { de: "sich wundern", lookup: "wundern", fallbackEn: "to be surprised", tip: "verb", use: "always with sich: ich wundere mich" },
    { de: "sich ärgern", lookup: "ärgern", fallbackEn: "to be annoyed", tip: "verb", use: "always with sich; jemanden ärgern = to annoy someone" },
    { de: "wüten", lookup: "wüten", fallbackEn: "to rage", tip: "verb", use: "a storm, a fire, or a person out of control" },
    { de: "sich langweilen", lookup: "langweilen", fallbackEn: "to be bored", tip: "verb", use: "always with sich: ich langweile mich" },
    { de: "sich entspannen", lookup: "entspannen", fallbackEn: "to relax", tip: "verb" },
    { de: "enttäuschen", lookup: "enttäuschen", fallbackEn: "to disappoint", tip: "verb" },
    { de: "verwirren", lookup: "verwirren", fallbackEn: "to confuse", tip: "verb" },
    { de: "fürchten", lookup: "fürchten", fallbackEn: "to fear", tip: "verb", use: "sich fürchten vor = to be afraid of" },
    { de: "ahnen", lookup: "ahnen", fallbackEn: "to sense, to have an idea", tip: "verb", use: "Ich ahne, was kommt = I can sense what's coming" },
    { de: "begreifen", lookup: "begreifen", fallbackEn: "to grasp, to understand", tip: "verb", use: "to understand something properly, not just hear it" },
    { de: "lehren", lookup: "lehren", fallbackEn: "to teach", tip: "verb", use: "unterrichten is the everyday word for school teaching" },
    { de: "benoten", lookup: "benoten", fallbackEn: "to grade, to mark", tip: "verb", use: "schoolwork" },
    { de: "korrigieren", lookup: "korrigieren", fallbackEn: "to correct", tip: "verb" },
    { de: "vervollständigen", lookup: "vervollständigen", fallbackEn: "to complete", tip: "verb", use: "to fill in what is missing" },
    { de: "dolmetschen", lookup: "dolmetschen", fallbackEn: "to interpret", tip: "verb", use: "spoken translation; übersetzen is written" },
    { de: "dichten", lookup: "dichten", fallbackEn: "to write poetry", tip: "verb", use: "also to seal something so it is watertight" },
    { de: "komponieren", lookup: "komponieren", fallbackEn: "to compose", tip: "verb", use: "music" },
    { de: "musizieren", lookup: "musizieren", fallbackEn: "to make music", tip: "verb", use: "to play music together" },
    { de: "argumentieren", lookup: "argumentieren", fallbackEn: "to argue, to reason", tip: "verb", use: "to make a case, not to have a row" },
    { de: "debattieren", lookup: "debattieren", fallbackEn: "to debate", tip: "verb" },
    { de: "demonstrieren", lookup: "demonstrieren", fallbackEn: "to demonstrate, to protest", tip: "verb", use: "both showing how and marching" },
    { de: "experimentieren", lookup: "experimentieren", fallbackEn: "to experiment", tip: "verb" },
    { de: "regenerieren", lookup: "regenerieren", fallbackEn: "to regenerate, to recover", tip: "verb" },
    { de: "rekrutieren", lookup: "rekrutieren", fallbackEn: "to recruit", tip: "verb" },
  ]),
  part597: pack("Part 597", "B1", "Getting things done", "The verbs of arrangements and errands: booking, signing, presenting, setting off and driving on.", [
    { de: "vermarkten", lookup: "vermarkten", fallbackEn: "to market", tip: "verb", use: "to sell something as a product" },
    { de: "patentieren", lookup: "patentieren", fallbackEn: "to patent", tip: "verb" },
    { de: "reservieren", lookup: "reservieren", fallbackEn: "to reserve, to book", tip: "verb" },
    { de: "terminieren", lookup: "terminieren", fallbackEn: "to schedule", tip: "verb", use: "to fix a date for something" },
    { de: "pausieren", lookup: "pausieren", fallbackEn: "to pause, to take a break", tip: "verb" },
    { de: "ruhen", lookup: "ruhen", fallbackEn: "to rest", tip: "verb", use: "formal; sich ausruhen is the everyday verb" },
    { de: "sonnen", lookup: "sonnen", fallbackEn: "to sunbathe", tip: "verb", use: "sich sonnen: always with sich" },
    { de: "verschwenden", lookup: "verschwenden", fallbackEn: "to waste", tip: "verb", use: "time, money, food" },
    { de: "verteidigen", lookup: "verteidigen", fallbackEn: "to defend", tip: "verb" },
    { de: "unterschreiben", lookup: "unterschreiben", fallbackEn: "to sign", tip: "verb", use: "a contract, a form" },
    { de: "vortragen", lookup: "vortragen", fallbackEn: "to present, to recite", tip: "verb", use: "to deliver something in front of people" },
    { de: "abreisen", lookup: "abreisen", fallbackEn: "to depart, to set off", tip: "verb", use: "to leave a place you were staying" },
    { de: "weiterfahren", lookup: "weiterfahren", fallbackEn: "to drive on, to carry on", tip: "verb" },
    { de: "zurückfahren", lookup: "zurückfahren", fallbackEn: "to drive back", tip: "verb" },
    { de: "entlanggehen", lookup: "entlanggehen", fallbackEn: "to walk along", tip: "verb", use: "die Straße entlanggehen" },
    { de: "vorübergehen", lookup: "vorübergehen", fallbackEn: "to pass, to go by", tip: "verb", use: "of time and of trouble: das geht vorüber" },
    { de: "dringen", lookup: "dringen", fallbackEn: "to penetrate, to press", tip: "verb", use: "an durch etwas dringen: to get through something" },
    { de: "kreuzen", lookup: "kreuzen", fallbackEn: "to cross", tip: "verb", use: "paths, and crossing something out" },
    { de: "wiegen", lookup: "wiegen", fallbackEn: "to weigh", tip: "verb", use: "both what a thing weighs and putting it on scales" },
    { de: "bewirten", lookup: "bewirten", fallbackEn: "to entertain, to cater for", tip: "verb", use: "to feed and look after guests" },
    { de: "shoppen", lookup: "shoppen", fallbackEn: "to shop", tip: "verb", use: "casual loanword; einkaufen is the German verb" },
    { de: "coachen", lookup: "coachen", fallbackEn: "to coach", tip: "verb" },
    { de: "telefonieren", lookup: "telefonieren", fallbackEn: "to phone, to be on the phone", tip: "verb", use: "mit jemandem telefonieren" },
    { de: "anfragen", lookup: "anfragen", fallbackEn: "to enquire, to request", tip: "verb", use: "to ask formally for something" },
    { de: "erfinden", lookup: "erfinden", fallbackEn: "to invent", tip: "verb" },
  ]),
  part598: pack("Part 598", "B1", "How people are", "Character in one word, from tapfer and gesellig to hartnaeckig, wortkarg and unfreundlich.", [
    { de: "böse", lookup: "böse", fallbackEn: "angry, wicked", tip: "adjective", use: "angry with someone, and evil in a fairy tale" },
    { de: "gemein", lookup: "gemein", fallbackEn: "mean, nasty", tip: "adjective", use: "Das ist gemein! = that's not fair" },
    { de: "aggressiv", lookup: "aggressiv", fallbackEn: "aggressive", tip: "adjective" },
    { de: "hartnäckig", lookup: "hartnäckig", fallbackEn: "stubborn, persistent", tip: "adjective", use: "a person who will not give up, and a stain that will not go" },
    { de: "tapfer", lookup: "tapfer", fallbackEn: "brave", tip: "adjective" },
    { de: "traurig", lookup: "traurig", fallbackEn: "sad", tip: "adjective" },
    { de: "melancholisch", lookup: "melancholisch", fallbackEn: "melancholy", tip: "adjective" },
    { de: "fröhlich", lookup: "fröhlich", fallbackEn: "cheerful, merry", tip: "adjective", use: "Fröhliche Weihnachten = merry Christmas" },
    { de: "gesellig", lookup: "gesellig", fallbackEn: "sociable", tip: "adjective", use: "someone who likes company" },
    { de: "redselig", lookup: "redselig", fallbackEn: "talkative", tip: "adjective" },
    { de: "wortkarg", lookup: "wortkarg", fallbackEn: "taciturn, of few words", tip: "adjective" },
    { de: "offenherzig", lookup: "offenherzig", fallbackEn: "open-hearted, candid", tip: "adjective" },
    { de: "liebevoll", lookup: "liebevoll", fallbackEn: "loving, affectionate", tip: "adjective" },
    { de: "lieblos", lookup: "lieblos", fallbackEn: "unloving, careless", tip: "adjective", use: "done without any care" },
    { de: "hilflos", lookup: "hilflos", fallbackEn: "helpless", tip: "adjective" },
    { de: "nervös", lookup: "nervös", fallbackEn: "nervous", tip: "adjective" },
    { de: "optimistisch", lookup: "optimistisch", fallbackEn: "optimistic", tip: "adjective" },
    { de: "pessimistisch", lookup: "pessimistisch", fallbackEn: "pessimistic", tip: "adjective" },
    { de: "tolerant", lookup: "tolerant", fallbackEn: "tolerant", tip: "adjective" },
    { de: "intolerant", lookup: "intolerant", fallbackEn: "intolerant", tip: "adjective" },
    { de: "respektvoll", lookup: "respektvoll", fallbackEn: "respectful", tip: "adjective" },
    { de: "respektlos", lookup: "respektlos", fallbackEn: "disrespectful", tip: "adjective" },
    { de: "undankbar", lookup: "undankbar", fallbackEn: "ungrateful, thankless", tip: "adjective" },
    { de: "unfreundlich", lookup: "unfreundlich", fallbackEn: "unfriendly", tip: "adjective" },
    { de: "unaufmerksam", lookup: "unaufmerksam", fallbackEn: "inattentive", tip: "adjective" },
    { de: "unbeliebt", lookup: "unbeliebt", fallbackEn: "unpopular", tip: "adjective" },
    { de: "unglücklich", lookup: "unglücklich", fallbackEn: "unhappy, unfortunate", tip: "adjective" },
    { de: "unangenehm", lookup: "unangenehm", fallbackEn: "unpleasant, awkward", tip: "adjective" },
    { de: "komisch", lookup: "komisch", fallbackEn: "funny, odd", tip: "adjective", use: "usually means strange rather than amusing: das ist komisch" },
    { de: "chaotisch", lookup: "chaotisch", fallbackEn: "chaotic", tip: "adjective" },
    { de: "energisch", lookup: "energisch", fallbackEn: "forceful, energetic", tip: "adjective" },
    { de: "kraftvoll", lookup: "kraftvoll", fallbackEn: "powerful", tip: "adjective" },
    { de: "schwungvoll", lookup: "schwungvoll", fallbackEn: "lively, sweeping", tip: "adjective", use: "done with momentum" },
    { de: "beschäftigt", lookup: "beschäftigt", fallbackEn: "busy", tip: "adjective", use: "of a person, not of a phone line" },
    { de: "konzentriert", lookup: "konzentriert", fallbackEn: "focused, concentrated", tip: "adjective" },
    { de: "spontan", lookup: "spontan", fallbackEn: "spontaneous", tip: "adjective" },
    { de: "romantisch", lookup: "romantisch", fallbackEn: "romantic", tip: "adjective" },
    { de: "abgelenkt", lookup: "abgelenkt", fallbackEn: "distracted", tip: "adjective" },
    { de: "entspannt", lookup: "entspannt", fallbackEn: "relaxed", tip: "adjective" },
  ]),
  part599: pack("Part 599", "B1", "How a thing seems", "Judgements about a thing rather than a person: clear or unclear, likely or unthinkable, visible or not.", [
    { de: "erschrocken", lookup: "erschrocken", fallbackEn: "startled, shocked", tip: "adjective" },
    { de: "verheiratet", lookup: "verheiratet", fallbackEn: "married", tip: "adjective", use: "mit jemandem verheiratet sein" },
    { de: "unerfahren", lookup: "unerfahren", fallbackEn: "inexperienced", tip: "adjective" },
    { de: "gewöhnlich", lookup: "gewöhnlich", fallbackEn: "ordinary, usual", tip: "adjective" },
    { de: "untypisch", lookup: "untypisch", fallbackEn: "untypical, out of character", tip: "adjective" },
    { de: "identisch", lookup: "identisch", fallbackEn: "identical", tip: "adjective" },
    { de: "konstant", lookup: "konstant", fallbackEn: "constant, steady", tip: "adjective" },
    { de: "neutral", lookup: "neutral", fallbackEn: "neutral", tip: "adjective" },
    { de: "passiv", lookup: "passiv", fallbackEn: "passive", tip: "adjective" },
    { de: "rational", lookup: "rational", fallbackEn: "rational", tip: "adjective" },
    { de: "logisch", lookup: "logisch", fallbackEn: "logical", tip: "adjective", use: "Logisch! is also a casual \"obviously\"" },
    { de: "indirekt", lookup: "indirekt", fallbackEn: "indirect", tip: "adjective" },
    { de: "inkorrekt", lookup: "inkorrekt", fallbackEn: "incorrect", tip: "adjective" },
    { de: "unklar", lookup: "unklar", fallbackEn: "unclear", tip: "adjective" },
    { de: "undeutlich", lookup: "undeutlich", fallbackEn: "indistinct, unclear", tip: "adjective", use: "of speech and handwriting you cannot make out" },
    { de: "unpräzise", lookup: "unpräzise", fallbackEn: "imprecise", tip: "adjective" },
    { de: "unrealistisch", lookup: "unrealistisch", fallbackEn: "unrealistic", tip: "adjective" },
    { de: "unwahrscheinlich", lookup: "unwahrscheinlich", fallbackEn: "unlikely, improbable", tip: "adjective", use: "also colloquially \"incredibly\": unwahrscheinlich gut" },
    { de: "undenkbar", lookup: "undenkbar", fallbackEn: "unthinkable", tip: "adjective" },
    { de: "denkbar", lookup: "denkbar", fallbackEn: "conceivable", tip: "adjective" },
    { de: "unverständlich", lookup: "unverständlich", fallbackEn: "incomprehensible", tip: "adjective" },
    { de: "unmerklich", lookup: "unmerklich", fallbackEn: "imperceptible", tip: "adjective" },
    { de: "unsichtbar", lookup: "unsichtbar", fallbackEn: "invisible", tip: "adjective" },
    { de: "unhörbar", lookup: "unhörbar", fallbackEn: "inaudible", tip: "adjective" },
    { de: "hörbar", lookup: "hörbar", fallbackEn: "audible", tip: "adjective" },
  ]),
  part600: pack("Part 600", "B2", "What can be done to a thing", "The -bar adjectives German builds out of verbs: lesbar, essbar, tragbar, bezahlbar.", [
    { de: "lesbar", lookup: "lesbar", fallbackEn: "legible, readable", tip: "adjective" },
    { de: "unlesbar", lookup: "unlesbar", fallbackEn: "illegible", tip: "adjective" },
    { de: "lösbar", lookup: "lösbar", fallbackEn: "solvable", tip: "adjective" },
    { de: "unlösbar", lookup: "unlösbar", fallbackEn: "unsolvable", tip: "adjective" },
    { de: "messbar", lookup: "messbar", fallbackEn: "measurable", tip: "adjective" },
    { de: "merkbar", lookup: "merkbar", fallbackEn: "noticeable", tip: "adjective" },
    { de: "zählbar", lookup: "zählbar", fallbackEn: "countable", tip: "adjective" },
    { de: "essbar", lookup: "essbar", fallbackEn: "edible", tip: "adjective" },
    { de: "trinkbar", lookup: "trinkbar", fallbackEn: "drinkable", tip: "adjective" },
    { de: "tragbar", lookup: "tragbar", fallbackEn: "portable, wearable", tip: "adjective", use: "small enough to carry, and bearable" },
    { de: "transportierbar", lookup: "transportierbar", fallbackEn: "transportable", tip: "adjective" },
    { de: "dehnbar", lookup: "dehnbar", fallbackEn: "stretchy, elastic", tip: "adjective" },
    { de: "brennbar", lookup: "brennbar", fallbackEn: "flammable", tip: "adjective" },
    { de: "bezahlbar", lookup: "bezahlbar", fallbackEn: "affordable", tip: "adjective" },
    { de: "unbezahlbar", lookup: "unbezahlbar", fallbackEn: "priceless, unaffordable", tip: "adjective", use: "both too dear to buy and beyond price" },
    { de: "kaufbar", lookup: "kaufbar", fallbackEn: "purchasable, for sale", tip: "adjective" },
    { de: "verkäuflich", lookup: "verkäuflich", fallbackEn: "saleable, for sale", tip: "adjective" },
  ]),
  part601: pack("Part 601", "B2", "Un-, and what things cost", "The un- opposites of everyday adjectives, and the words German prices and quality wear.", [
    { de: "unvergleichbar", lookup: "unvergleichbar", fallbackEn: "incomparable", tip: "adjective" },
    { de: "unvermeidbar", lookup: "unvermeidbar", fallbackEn: "unavoidable", tip: "adjective" },
    { de: "unverantwortlich", lookup: "unverantwortlich", fallbackEn: "irresponsible", tip: "adjective" },
    { de: "unvorsichtig", lookup: "unvorsichtig", fallbackEn: "careless, incautious", tip: "adjective" },
    { de: "unnötig", lookup: "unnötig", fallbackEn: "unnecessary", tip: "adjective" },
    { de: "unwichtig", lookup: "unwichtig", fallbackEn: "unimportant", tip: "adjective" },
    { de: "unmöglich", lookup: "unmöglich", fallbackEn: "impossible", tip: "adjective" },
    { de: "unfair", lookup: "unfair", fallbackEn: "unfair", tip: "adjective" },
    { de: "ungerecht", lookup: "ungerecht", fallbackEn: "unjust", tip: "adjective" },
    { de: "ungeplant", lookup: "ungeplant", fallbackEn: "unplanned", tip: "adjective" },
    { de: "unpraktisch", lookup: "unpraktisch", fallbackEn: "impractical", tip: "adjective" },
    { de: "unproduktiv", lookup: "unproduktiv", fallbackEn: "unproductive", tip: "adjective" },
    { de: "produktiv", lookup: "produktiv", fallbackEn: "productive", tip: "adjective" },
    { de: "ineffizient", lookup: "ineffizient", fallbackEn: "inefficient", tip: "adjective" },
    { de: "unreif", lookup: "unreif", fallbackEn: "unripe, immature", tip: "adjective", use: "fruit, and a person" },
    { de: "unsensibel", lookup: "unsensibel", fallbackEn: "insensitive", tip: "adjective" },
    { de: "unbequem", lookup: "unbequem", fallbackEn: "uncomfortable", tip: "adjective" },
    { de: "uneben", lookup: "uneben", fallbackEn: "uneven, bumpy", tip: "adjective", use: "ground, a surface" },
    { de: "krumm", lookup: "krumm", fallbackEn: "crooked, bent", tip: "adjective" },
    { de: "starr", lookup: "starr", fallbackEn: "rigid, stiff", tip: "adjective" },
    { de: "spröde", lookup: "spröde", fallbackEn: "brittle, chapped", tip: "adjective", use: "material that snaps, and dry lips" },
    { de: "zart", lookup: "zart", fallbackEn: "tender, delicate", tip: "adjective", use: "meat, skin, a touch" },
    { de: "saftig", lookup: "saftig", fallbackEn: "juicy", tip: "adjective" },
    { de: "köstlich", lookup: "köstlich", fallbackEn: "delicious", tip: "adjective", use: "a step up from lecker" },
    { de: "altbacken", lookup: "altbacken", fallbackEn: "stale, old-fashioned", tip: "adjective", use: "bread going hard, and ideas doing the same" },
    { de: "gebacken", lookup: "gebacken", fallbackEn: "baked", tip: "adjective" },
    { de: "gefroren", lookup: "gefroren", fallbackEn: "frozen", tip: "adjective" },
    { de: "flüssig", lookup: "flüssig", fallbackEn: "liquid, fluent", tip: "adjective", use: "both a liquid and speech that flows" },
    { de: "kühl", lookup: "kühl", fallbackEn: "cool", tip: "adjective" },
    { de: "billig", lookup: "billig", fallbackEn: "cheap", tip: "adjective", use: "often suggests poor quality; preiswert is cheap and good" },
    { de: "preiswert", lookup: "preiswert", fallbackEn: "good value", tip: "adjective", use: "cheap for what you get, with no insult in it" },
    { de: "hochpreisig", lookup: "hochpreisig", fallbackEn: "high-priced", tip: "adjective", use: "the word adverts use instead of teuer" },
    { de: "kostenintensiv", lookup: "kostenintensiv", fallbackEn: "costly", tip: "adjective", use: "business German for something that eats money" },
    { de: "arbeitsintensiv", lookup: "arbeitsintensiv", fallbackEn: "labour-intensive", tip: "adjective" },
    { de: "pflegeintensiv", lookup: "pflegeintensiv", fallbackEn: "high-maintenance", tip: "adjective", use: "a plant, a garden, a floor" },
    { de: "pflegeleicht", lookup: "pflegeleicht", fallbackEn: "easy-care, low-maintenance", tip: "adjective", use: "on clothing labels and in flat adverts" },
    { de: "mittelfristig", lookup: "mittelfristig", fallbackEn: "medium-term", tip: "adjective" },
    { de: "schnelllebig", lookup: "schnelllebig", fallbackEn: "fast-moving, fast-paced", tip: "adjective", use: "a fast-changing world or industry" },
    { de: "schnellstmöglich", lookup: "schnellstmöglich", fallbackEn: "as soon as possible", tip: "adjective", use: "the word German letters use for ASAP" },
    { de: "obligatorisch", lookup: "obligatorisch", fallbackEn: "compulsory", tip: "adjective" },
    { de: "legal", lookup: "legal", fallbackEn: "legal, lawful", tip: "adjective", use: "allowed by law; juristisch is legal as in \"of law\"" },
    { de: "erlaubt", lookup: "erlaubt", fallbackEn: "permitted, allowed", tip: "adjective" },
    { de: "verboten", lookup: "verboten", fallbackEn: "forbidden, prohibited", tip: "adjective", use: "the word on every German sign that says no" },
  ]),
  part602: pack("Part 602", "B2", "Times, places and flat adverts", "Adjectives for a time of day, a kind of landscape, and the German a flat is advertised in.", [
    { de: "kompliziert", lookup: "kompliziert", fallbackEn: "complicated", tip: "adjective" },
    { de: "altmodisch", lookup: "altmodisch", fallbackEn: "old-fashioned", tip: "adjective" },
    { de: "abendlich", lookup: "abendlich", fallbackEn: "in the evening", tip: "adjective", use: "der abendliche Spaziergang = the evening walk" },
    { de: "morgendlich", lookup: "morgendlich", fallbackEn: "morning", tip: "adjective" },
    { de: "nächtlich", lookup: "nächtlich", fallbackEn: "nightly, nocturnal", tip: "adjective" },
    { de: "werktäglich", lookup: "werktäglich", fallbackEn: "on working days", tip: "adjective", use: "Monday to Saturday, the German working week" },
    { de: "frühlingshaft", lookup: "frühlingshaft", fallbackEn: "springlike", tip: "adjective", use: "weather that feels like spring" },
    { de: "wolkig", lookup: "wolkig", fallbackEn: "cloudy", tip: "adjective" },
    { de: "bergig", lookup: "bergig", fallbackEn: "mountainous", tip: "adjective" },
    { de: "hügelig", lookup: "hügelig", fallbackEn: "hilly", tip: "adjective" },
    { de: "küstennah", lookup: "küstennah", fallbackEn: "near the coast", tip: "adjective" },
    { de: "wassernah", lookup: "wassernah", fallbackEn: "close to water", tip: "adjective" },
    { de: "urban", lookup: "urban", fallbackEn: "urban", tip: "adjective", use: "städtisch is the everyday German word" },
    { de: "dörflich", lookup: "dörflich", fallbackEn: "village-like, rural", tip: "adjective" },
    { de: "belebt", lookup: "belebt", fallbackEn: "busy, lively", tip: "adjective", use: "a street or square with people on it" },
    { de: "bewohnt", lookup: "bewohnt", fallbackEn: "inhabited", tip: "adjective" },
    { de: "unbewohnt", lookup: "unbewohnt", fallbackEn: "uninhabited", tip: "adjective" },
    { de: "möbliert", lookup: "möbliert", fallbackEn: "furnished", tip: "adjective", use: "the word in every German flat advert" },
    { de: "unmöbliert", lookup: "unmöbliert", fallbackEn: "unfurnished", tip: "adjective" },
    { de: "renoviert", lookup: "renoviert", fallbackEn: "renovated, done up", tip: "adjective" },
    { de: "modernisiert", lookup: "modernisiert", fallbackEn: "modernised", tip: "adjective" },
    { de: "geräumig", lookup: "geräumig", fallbackEn: "spacious", tip: "adjective" },
    { de: "vollbesetzt", lookup: "vollbesetzt", fallbackEn: "fully booked, full", tip: "adjective", use: "a train, a theatre, a course" },
    { de: "unzugänglich", lookup: "unzugänglich", fallbackEn: "inaccessible", tip: "adjective" },
  ]),
  part603: pack("Part 603", "B2", "Friendly to whom, harmful to what", "The -freundlich compounds German builds to say who a thing suits, and their harmful opposites.", [
    { de: "behindertengerecht", lookup: "behindertengerecht", fallbackEn: "wheelchair-accessible", tip: "adjective" },
    { de: "benutzerfreundlich", lookup: "benutzerfreundlich", fallbackEn: "user-friendly", tip: "adjective" },
    { de: "kundenfreundlich", lookup: "kundenfreundlich", fallbackEn: "customer-friendly", tip: "adjective" },
    { de: "familienfreundlich", lookup: "familienfreundlich", fallbackEn: "family-friendly", tip: "adjective" },
    { de: "kinderfreundlich", lookup: "kinderfreundlich", fallbackEn: "child-friendly", tip: "adjective" },
    { de: "tierfreundlich", lookup: "tierfreundlich", fallbackEn: "pet-friendly", tip: "adjective" },
    { de: "fahrradfreundlich", lookup: "fahrradfreundlich", fallbackEn: "bike-friendly", tip: "adjective" },
    { de: "umweltfreundlich", lookup: "umweltfreundlich", fallbackEn: "environmentally friendly", tip: "adjective" },
    { de: "umweltschädlich", lookup: "umweltschädlich", fallbackEn: "harmful to the environment", tip: "adjective" },
    { de: "schädlich", lookup: "schädlich", fallbackEn: "harmful", tip: "adjective" },
    { de: "gefährdet", lookup: "gefährdet", fallbackEn: "at risk, endangered", tip: "adjective", use: "a species, a job, a person" },
    { de: "geschützt", lookup: "geschützt", fallbackEn: "protected", tip: "adjective" },
    { de: "ungeschützt", lookup: "ungeschützt", fallbackEn: "unprotected", tip: "adjective" },
    { de: "gesundheitsbewusst", lookup: "gesundheitsbewusst", fallbackEn: "health-conscious", tip: "adjective" },
    { de: "sicherheitsbewusst", lookup: "sicherheitsbewusst", fallbackEn: "safety-conscious", tip: "adjective" },
    { de: "friedlich", lookup: "friedlich", fallbackEn: "peaceful", tip: "adjective" },
    { de: "bösartig", lookup: "bösartig", fallbackEn: "malicious, malignant", tip: "adjective", use: "a nasty person, and a malignant tumour" },
    { de: "gutartig", lookup: "gutartig", fallbackEn: "benign", tip: "adjective", use: "the medical opposite of bösartig" },
    { de: "erfolglos", lookup: "erfolglos", fallbackEn: "unsuccessful", tip: "adjective" },
    { de: "nutzlos", lookup: "nutzlos", fallbackEn: "useless", tip: "adjective" },
    { de: "sinnlos", lookup: "sinnlos", fallbackEn: "pointless, senseless", tip: "adjective" },
    { de: "wertlos", lookup: "wertlos", fallbackEn: "worthless", tip: "adjective" },
    { de: "verschwenderisch", lookup: "verschwenderisch", fallbackEn: "wasteful, extravagant", tip: "adjective" },
    { de: "zusammengehörig", lookup: "zusammengehörig", fallbackEn: "belonging together", tip: "adjective", use: "two things that form a pair or a set" },
    { de: "robust", lookup: "robust", fallbackEn: "robust, sturdy", tip: "adjective" },
  ]),
  part604: pack("Part 604", "A2", "Colours, shapes and fields", "Light and dark shades, the shapes of things, and the adjectives for a school subject.", [
    { de: "farbig", lookup: "farbig", fallbackEn: "coloured, colourful", tip: "adjective" },
    { de: "farblos", lookup: "farblos", fallbackEn: "colourless", tip: "adjective" },
    { de: "silbern", lookup: "silbern", fallbackEn: "made of silver, silver-coloured", tip: "adjective", use: "made of silver or the colour of it" },
    { de: "violett", lookup: "violett", fallbackEn: "violet, purple", tip: "adjective" },
    { de: "hellblau", lookup: "hellblau", fallbackEn: "light blue", tip: "adjective", use: "hell- makes any colour lighter" },
    { de: "dunkelblau", lookup: "dunkelblau", fallbackEn: "dark blue", tip: "adjective", use: "dunkel- makes any colour darker" },
    { de: "hellgrau", lookup: "hellgrau", fallbackEn: "light grey", tip: "adjective" },
    { de: "dunkelgrau", lookup: "dunkelgrau", fallbackEn: "dark grey", tip: "adjective" },
    { de: "hellgrün", lookup: "hellgrün", fallbackEn: "light green", tip: "adjective" },
    { de: "dunkelgrün", lookup: "dunkelgrün", fallbackEn: "dark green", tip: "adjective" },
    { de: "oval", lookup: "oval", fallbackEn: "oval", tip: "adjective" },
    { de: "quadratisch", lookup: "quadratisch", fallbackEn: "square", tip: "adjective" },
    { de: "rechteckig", lookup: "rechteckig", fallbackEn: "rectangular", tip: "adjective" },
    { de: "dreieckig", lookup: "dreieckig", fallbackEn: "triangular", tip: "adjective" },
    { de: "mathematisch", lookup: "mathematisch", fallbackEn: "mathematical", tip: "adjective" },
    { de: "physikalisch", lookup: "physikalisch", fallbackEn: "physical (of physics)", tip: "adjective", use: "of physics; körperlich is physical of the body" },
    { de: "geografisch", lookup: "geografisch", fallbackEn: "geographical", tip: "adjective" },
    { de: "pflanzlich", lookup: "pflanzlich", fallbackEn: "plant-based", tip: "adjective", use: "pflanzliche Milch = plant milk" },
    { de: "tierisch", lookup: "tierisch", fallbackEn: "of animals, animal", tip: "adjective", use: "also colloquially \"massively\": tierisch gut" },
    { de: "privatwirtschaftlich", lookup: "privatwirtschaftlich", fallbackEn: "private-sector", tip: "adjective" },
    { de: "offline", lookup: "offline", fallbackEn: "offline", tip: "adjective" },
    { de: "abgelegen", lookup: "abgelegen", fallbackEn: "remote, secluded", tip: "adjective", use: "a place far from everything" },
  ]),
};
