import { lifeInTheUkCourse } from "@/lib/lifeInTheUkCourse";

/**
 * The Life in the UK practice bank.
 *
 * Separate from the quizzes embedded in the lessons on purpose. Those exist to
 * close a lesson while the material is still on screen; these exist to be drawn
 * from repeatedly, in any order, long after the lesson was read. Mixing the two
 * would mean either a lesson that never ends or a practice pool of 23 questions.
 *
 * Every question carries the id of the lesson that teaches it, so "learn the
 * topic, then answer questions on that topic" is one filter rather than a
 * parallel taxonomy someone has to maintain by hand. The chapter comes from the
 * lesson, so filtering by broad area (history, government) and by narrow topic
 * (the Tudors, devolution) are the same mechanism.
 *
 * Difficulty is authored, not derived. Easy means the fact is stated plainly in
 * the lesson; medium means it needs recall of a specific name, date or number;
 * hard means it needs two facts held together, or it targets a trap the real
 * test is known to set — 55 BC against AD 43, 1807 against 1833, 1918 against
 * 1928.
 *
 * Nothing here is copied from the Home Office handbook or any commercial
 * question bank. The facts are public; the wording is ours.
 */

export type UkLevel = "easy" | "medium" | "hard";

export type UkQuestion = {
  /** Stable across releases: progress, mistakes and favourites are keyed on it. */
  id: string;
  /** The id of the lesson in lifeInTheUkCourse that teaches this. */
  lesson: string;
  level: UkLevel;
  q: string;
  options: string[];
  /** Index into options. Exactly one right answer, pinned by check-uk-questions. */
  answer: number;
  explanation: string;
};

export const UK_LEVELS: UkLevel[] = ["easy", "medium", "hard"];

export const UK_LEVEL_LABEL: Record<UkLevel, string> = {
  easy: "Easy",
  medium: "Medium",
  hard: "Hard",
};

export const UK_QUESTIONS: UkQuestion[] = [
  // ── British Values & Principles ────────────────────────────────────────
  // bv-1, bv-2, bv-7, bv-8, bv-10 and bv-11 used to ask about exam procedure —
  // the time limit, the pass mark, the ceremony, the retake wait, the age
  // range. Michelle asked for none of that in the course, so they were
  // REPLACED rather than deleted: dropping six would have left this category
  // with half the questions of any other and skewed the weighted picker
  // towards it. The replacements ask about the same lesson's actual content.
  { id: "bv-1", lesson: "british-values", level: "easy",
    q: "What does the rule of law mean?",
    options: [
      "The police may act outside the law when necessary",
      "Everyone is subject to the law, including the government",
      "Only judges are bound by the law",
      "Laws apply only to citizens",
    ], answer: 1,
    explanation: "Nobody is above the law — not ministers, not the police, not the government itself. That is what makes it the rule of LAW rather than the rule of whoever is in charge." },
  { id: "bv-2", lesson: "british-values", level: "easy",
    q: "What does tolerance mean as a British value?",
    options: [
      "Agreeing with every religion",
      "Respect for people of different faiths and beliefs, and of none",
      "Keeping your opinions to yourself",
      "Following the established church",
    ], answer: 1,
    explanation: "Tolerance is respect, not agreement — and it explicitly covers people with no religious belief as well as believers." },
  { id: "bv-3", lesson: "british-values", level: "medium",
    q: "Which of these is one of the UK's fundamental values?",
    options: ["Loyalty to a political party", "The rule of law", "Compulsory military service", "Membership of a church"], answer: 1,
    explanation: "The rule of law means everyone is subject to the law, including those who govern. The others are not British values at all." },
  { id: "bv-4", lesson: "british-values", level: "medium",
    q: "How many protected characteristics does the Equality Act 2010 list?",
    options: ["Five", "Seven", "Nine", "Twelve"], answer: 2,
    explanation: "Nine: age, disability, gender reassignment, marriage and civil partnership, pregnancy and maternity, race, religion or belief, sex, and sexual orientation." },
  { id: "bv-5", lesson: "british-values", level: "hard",
    q: "Which of these is NOT protected under the Equality Act 2010?",
    options: ["Pregnancy and maternity", "Political opinion", "Gender reassignment", "Marriage and civil partnership"], answer: 1,
    explanation: "Political opinion is not a protected characteristic in Great Britain. The other three are among the nine that are." },
  { id: "bv-6", lesson: "british-values", level: "medium",
    q: "Is freedom of speech in the UK unlimited?",
    options: ["Yes, nothing said may be prosecuted", "No — inciting violence or racial hatred is a criminal offence", "Yes, but only in private", "No — all criticism of the government is banned"], answer: 1,
    explanation: "Freedom of speech is a real right with a real boundary. Speech that incites violence or racial hatred is a crime." },
  { id: "bv-7", lesson: "british-values", level: "easy",
    q: "Which law sets out the protected characteristics?",
    options: ["The Human Rights Act 1998", "The Equality Act 2010", "Magna Carta", "The Bill of Rights 1689"], answer: 1,
    explanation: "The Equality Act 2010. The Human Rights Act 1998 is the separate law that brought the European Convention on Human Rights into UK law." },
  { id: "bv-8", lesson: "british-values", level: "hard",
    q: "A landlord refuses to rent to someone because of their religion. What is this?",
    options: [
      "Lawful, as it is private property",
      "Unlawful discrimination under the Equality Act 2010",
      "Lawful if no contract was signed",
      "A civil matter with no legal protection",
    ], answer: 1,
    explanation: "Religion or belief is one of the nine protected characteristics, and housing is covered. Owning the property does not create an exemption." },
  { id: "bv-9", lesson: "british-values", level: "medium",
    q: "Which of these is a responsibility rather than a right?",
    options: ["Freedom of religion", "A fair trial", "Serving on a jury when summoned", "Freedom from discrimination"], answer: 2,
    explanation: "Jury service is a duty you must perform when called. The other three are rights you hold." },
  { id: "bv-10", lesson: "british-values", level: "easy",
    q: "What does democracy mean in the UK?",
    options: [
      "The monarch decides policy",
      "Government by the people, through representatives they elect and can vote out",
      "Every law is put to a public vote",
      "The courts choose the government",
    ], answer: 1,
    explanation: "Representative democracy: you elect MPs, and you can remove them at the next election. Referendums happen but are the exception, not the system." },
  { id: "bv-11", lesson: "british-values", level: "hard",
    q: "Which of these is a right rather than a responsibility?",
    options: [
      "Paying income tax",
      "Serving on a jury when summoned",
      "Freedom from unfair discrimination",
      "Obeying the law",
    ], answer: 2,
    explanation: "Freedom from discrimination is a right you hold. Tax, jury service and obeying the law are duties owed in return." },
  { id: "bv-12", lesson: "british-values", level: "medium",
    q: "What does 'individual liberty' mean as a British value?",
    options: ["Freedom to do anything at all", "Freedom to live as you choose within the law", "Freedom from paying tax", "Freedom to ignore laws you disagree with"], answer: 1,
    explanation: "Liberty operates inside the law, not outside it. You change laws you disagree with by campaigning and voting." },

  // ── The UK & Geography ─────────────────────────────────────────────────
  { id: "geo-1", lesson: "uk-geography", level: "easy",
    q: "Which four nations make up the United Kingdom?",
    options: ["England, Scotland, Wales and Ireland", "England, Scotland, Wales and Northern Ireland", "England, Scotland, Wales and the Isle of Man", "England, Wales, Northern Ireland and the Channel Islands"], answer: 1,
    explanation: "Northern Ireland, not the whole of Ireland. The Republic of Ireland is a separate country." },
  { id: "geo-2", lesson: "uk-geography", level: "easy",
    q: "What is the capital of Wales?",
    options: ["Swansea", "Cardiff", "Newport", "Bangor"], answer: 1,
    explanation: "Cardiff, home of the Senedd — the Welsh Parliament." },
  { id: "geo-3", lesson: "uk-geography", level: "easy",
    q: "What is the capital of Scotland?",
    options: ["Glasgow", "Edinburgh", "Aberdeen", "Dundee"], answer: 1,
    explanation: "Edinburgh, where the Scottish Parliament sits at Holyrood. Glasgow is larger but is not the capital." },
  { id: "geo-4", lesson: "uk-geography", level: "medium",
    q: "Which is the largest city in Scotland?",
    options: ["Edinburgh", "Glasgow", "Aberdeen", "Inverness"], answer: 1,
    explanation: "Glasgow is the largest by population; Edinburgh is the capital. The test likes this split." },
  { id: "geo-5", lesson: "uk-geography", level: "medium",
    q: "Which mountain is the highest in Wales?",
    options: ["Ben Nevis", "Scafell Pike", "Snowdon", "Slieve Donard"], answer: 2,
    explanation: "Snowdon — Yr Wyddfa — at 1,085 m. Ben Nevis is Scotland's and the UK's highest." },
  { id: "geo-6", lesson: "uk-geography", level: "medium",
    q: "Which is the highest mountain in England?",
    options: ["Scafell Pike", "Snowdon", "Ben Nevis", "Helvellyn"], answer: 0,
    explanation: "Scafell Pike in the Lake District, 978 m — the lowest of the four national high points." },
  { id: "geo-7", lesson: "uk-geography", level: "hard",
    q: "What is the largest freshwater lake by area in the whole UK?",
    options: ["Loch Lomond", "Windermere", "Lough Neagh", "Loch Ness"], answer: 2,
    explanation: "Lough Neagh in Northern Ireland. Loch Lomond is the largest in Great Britain, and Windermere the largest in England." },
  { id: "geo-8", lesson: "uk-geography", level: "easy",
    q: "Which sea lies to the east of Great Britain?",
    options: ["The Irish Sea", "The North Sea", "The Atlantic Ocean", "The English Channel"], answer: 1,
    explanation: "The North Sea to the east, the Channel to the south, the Irish Sea to the west." },
  { id: "geo-9", lesson: "uk-geography", level: "medium",
    q: "Which of these is a Crown Dependency rather than part of the UK?",
    options: ["Anglesey", "The Isle of Wight", "The Isle of Man", "The Isles of Scilly"], answer: 2,
    explanation: "The Isle of Man and the Channel Islands are Crown Dependencies with their own governments. The others are UK islands." },
  { id: "geo-10", lesson: "uk-geography", level: "hard",
    q: "How many National Parks are there in the UK?",
    options: ["10", "15", "20", "25"], answer: 1,
    explanation: "15, including the Lake District, Snowdonia, the Cairngorms and the Peak District." },
  { id: "geo-11", lesson: "uk-geography", level: "easy",
    q: "Which river flows through London?",
    options: ["The Severn", "The Thames", "The Trent", "The Mersey"], answer: 1,
    explanation: "The Thames — the second longest river in the UK, after the Severn." },
  { id: "geo-12", lesson: "uk-geography", level: "hard",
    q: "In which year did the Channel Tunnel open?",
    options: ["1984", "1990", "1994", "2000"], answer: 2,
    explanation: "1994, linking Folkestone with Coquelles in France — the UK's only fixed land link to the continent." },
  { id: "geo-13", lesson: "uk-geography", level: "easy",
    q: "Which of these is an official language in Wales?",
    options: ["Gaelic", "Welsh", "Cornish", "Irish"], answer: 1,
    explanation: "Welsh is official in Wales and taught in schools there. Gaelic is spoken in parts of Scotland, Irish in Northern Ireland." },
  { id: "geo-14", lesson: "uk-geography", level: "medium",
    q: "How many counties does Northern Ireland have?",
    options: ["Four", "Six", "Nine", "Twelve"], answer: 1,
    explanation: "Six: Antrim, Armagh, Down, Fermanagh, Londonderry and Tyrone." },

  // ── National Identity & Symbols ────────────────────────────────────────
  { id: "sym-1", lesson: "identity-symbols", level: "easy",
    q: "What is the national flower of England?",
    options: ["The thistle", "The rose", "The daffodil", "The shamrock"], answer: 1,
    explanation: "The rose — the red and white Tudor rose, from the end of the Wars of the Roses." },
  { id: "sym-2", lesson: "identity-symbols", level: "easy",
    q: "Which plant is the emblem of Scotland?",
    options: ["The thistle", "The shamrock", "The leek", "The oak"], answer: 0,
    explanation: "The thistle, a spiny purple flower, has been Scotland's emblem for centuries." },
  { id: "sym-3", lesson: "identity-symbols", level: "medium",
    q: "On what date is St Andrew's Day?",
    options: ["1 March", "17 March", "23 April", "30 November"], answer: 3,
    explanation: "30 November, and it is a bank holiday in Scotland." },
  { id: "sym-4", lesson: "identity-symbols", level: "easy",
    q: "St George is the patron saint of which nation?",
    options: ["Scotland", "England", "Wales", "Northern Ireland"], answer: 1,
    explanation: "England, celebrated on 23 April. His red cross on white forms part of the Union Flag." },
  { id: "sym-5", lesson: "identity-symbols", level: "hard",
    q: "Which patron saints' days both fall in March?",
    options: ["St George and St Andrew", "St David and St Patrick", "St Patrick and St George", "St David and St Andrew"], answer: 1,
    explanation: "St David on 1 March and St Patrick on 17 March. These two are the pair most often confused." },
  { id: "sym-6", lesson: "identity-symbols", level: "medium",
    q: "Which three crosses make up the Union Flag?",
    options: ["St George, St Andrew and St David", "St George, St Andrew and St Patrick", "St Patrick, St David and St Andrew", "St George, St David and St Patrick"], answer: 1,
    explanation: "England's St George, Scotland's St Andrew and Ireland's St Patrick. Wales is not represented." },
  { id: "sym-7", lesson: "identity-symbols", level: "hard",
    q: "Why is Wales not represented on the Union Flag?",
    options: ["Wales refused to join", "Wales was already united with England when the flag was designed", "The dragon was considered unsuitable", "Wales joined the UK only in 1900"], answer: 1,
    explanation: "By 1606 Wales had already been joined to England, so it was not treated as a separate kingdom." },
  { id: "sym-8", lesson: "identity-symbols", level: "easy",
    q: "What is the national anthem of the UK?",
    options: ["Land of Hope and Glory", "God Save the King", "Jerusalem", "Rule, Britannia!"], answer: 1,
    explanation: "God Save the King — God Save the Queen during a queen's reign. The words follow the monarch's gender." },
  { id: "sym-9", lesson: "identity-symbols", level: "easy",
    q: "Which animal appears on the flag of Wales?",
    options: ["A lion", "A unicorn", "A dragon", "An eagle"], answer: 2,
    explanation: "Y Ddraig Goch, the Red Dragon, on a green and white field." },
  { id: "sym-10", lesson: "identity-symbols", level: "medium",
    q: "Which two animals support the Royal Coat of Arms?",
    options: ["A lion and a unicorn", "A lion and a dragon", "An eagle and a lion", "A unicorn and a stag"], answer: 0,
    explanation: "The lion for England and the unicorn for Scotland." },
  { id: "sym-11", lesson: "identity-symbols", level: "easy",
    q: "Which flower is associated with Northern Ireland?",
    options: ["The daffodil", "The shamrock", "The thistle", "The rose"], answer: 1,
    explanation: "The shamrock, the three-leaved clover associated with St Patrick." },
  { id: "sym-12", lesson: "identity-symbols", level: "easy",
    q: "What does the Scottish flag, the Saltire, look like?",
    options: ["A red cross on white", "A white diagonal cross on blue", "A red diagonal cross on white", "A red dragon on green and white"], answer: 1,
    explanation: "A white diagonal cross — St Andrew's saltire — on a blue background." },

  // ── Early British History ──────────────────────────────────────────────
  { id: "early-1", lesson: "early-british-history", level: "medium",
    q: "In which year did Claudius begin the Roman conquest of Britain?",
    options: ["55 BC", "AD 43", "AD 122", "AD 410"], answer: 1,
    explanation: "AD 43 under Claudius. Caesar's earlier expedition in 55 BC failed to conquer anything." },
  { id: "early-2", lesson: "early-british-history", level: "hard",
    q: "What happened when Julius Caesar came to Britain in 55 BC?",
    options: ["He conquered the whole island", "His expedition failed and Britain was not conquered", "He built Hadrian's Wall", "He was defeated by Boudicca"], answer: 1,
    explanation: "Caesar came and left. The conquest began almost a century later under Claudius, in AD 43." },
  { id: "early-3", lesson: "early-british-history", level: "easy",
    q: "Who built a wall across northern England to keep out the tribes of the north?",
    options: ["Julius Caesar", "Emperor Hadrian", "Alfred the Great", "William the Conqueror"], answer: 1,
    explanation: "Hadrian's Wall, begun around AD 122. The Romans never conquered what is now Scotland." },
  { id: "early-4", lesson: "early-british-history", level: "easy",
    q: "Who led a revolt against Roman rule in eastern England?",
    options: ["Boudicca", "Alfred the Great", "Robert the Bruce", "William Wallace"], answer: 0,
    explanation: "Boudicca, queen of the Iceni. Her statue stands on Westminster Bridge in London." },
  { id: "early-5", lesson: "early-british-history", level: "medium",
    q: "In which year did the Romans leave Britain?",
    options: ["AD 122", "AD 410", "AD 597", "AD 789"], answer: 1,
    explanation: "AD 410, when troops were withdrawn to defend Rome itself." },
  { id: "early-6", lesson: "early-british-history", level: "hard",
    q: "What was the Danelaw?",
    options: ["A Roman legal code", "The part of England under Danish rule after Alfred the Great's settlement", "The law brought by the Normans in 1066", "A tax paid to the Vikings"], answer: 1,
    explanation: "Alfred could not drive the Vikings out entirely, so a boundary was agreed. The north and east kept Danish law." },
  { id: "early-7", lesson: "early-british-history", level: "medium",
    q: "Which king defeated the Vikings and agreed the boundary that created the Danelaw?",
    options: ["Alfred the Great", "Harold", "Canute", "Edward the Confessor"], answer: 0,
    explanation: "Alfred the Great, King of Wessex — the only English monarch called 'the Great'." },
  { id: "early-8", lesson: "early-british-history", level: "easy",
    q: "Which prehistoric monument stands in Wiltshire?",
    options: ["Hadrian's Wall", "Stonehenge", "Skara Brae", "Maiden Castle"], answer: 1,
    explanation: "Stonehenge, built in the Stone Age and still a World Heritage Site." },
  { id: "early-9", lesson: "early-british-history", level: "medium",
    q: "Where is the Stone Age settlement of Skara Brae?",
    options: ["Cornwall", "Orkney", "Anglesey", "The Isle of Wight"], answer: 1,
    explanation: "Skara Brae is in Orkney, off the north coast of Scotland." },
  { id: "early-10", lesson: "early-british-history", level: "medium",
    q: "The languages of which people gave rise to modern Welsh, Gaelic and Irish?",
    options: ["The Romans", "The Celts", "The Vikings", "The Normans"], answer: 1,
    explanation: "The Celts of the Iron Age. Their languages survive in Wales, Scotland and Ireland." },
  { id: "early-11", lesson: "early-british-history", level: "hard",
    q: "Where does the name 'England' come from?",
    options: ["The Angles, one of the tribes who settled after the Romans", "A Roman province called Anglia", "The Norman word for island", "A Viking king named Engle"], answer: 0,
    explanation: "Angles, Saxons and Jutes settled after AD 410. 'Angle-land' became England." },
  { id: "early-12", lesson: "early-british-history", level: "easy",
    q: "In which year was the Battle of Hastings?",
    options: ["1066", "1086", "1215", "1348"], answer: 0,
    explanation: "1066 — William of Normandy defeated Harold. It is the last successful invasion of Britain." },
  { id: "early-13", lesson: "early-british-history", level: "medium",
    q: "Who founded a monastery on Iona and helped convert Scotland to Christianity?",
    options: ["St Augustine", "St Columba", "St Patrick", "St David"], answer: 1,
    explanation: "St Columba in Scotland; St Augustine did the same in the south and became the first Archbishop of Canterbury." },

  // ── Medieval Britain ───────────────────────────────────────────────────
  { id: "med-1", lesson: "medieval-britain", level: "easy",
    q: "In which year was Magna Carta agreed?",
    options: ["1066", "1215", "1314", "1485"], answer: 1,
    explanation: "1215 at Runnymede, forced on King John by his barons." },
  { id: "med-2", lesson: "medieval-britain", level: "medium",
    q: "What principle did Magna Carta establish?",
    options: ["That everyone could vote", "That the king was subject to the law", "That Parliament chose the monarch", "That England and Scotland were united"], answer: 1,
    explanation: "The king was bound by law and could not tax at will. It did not create Parliament or give anyone the vote." },
  { id: "med-3", lesson: "medieval-britain", level: "easy",
    q: "What was the Domesday Book?",
    options: ["A record of church law", "A survey of land ownership and value across England", "A list of English kings", "The first English dictionary"], answer: 1,
    explanation: "Ordered by William the Conqueror in 1086 to record who owned what and what it was worth." },
  { id: "med-4", lesson: "medieval-britain", level: "hard",
    q: "Who won the Battle of Bannockburn in 1314?",
    options: ["Edward I", "William Wallace", "Robert the Bruce", "Henry V"], answer: 2,
    explanation: "Robert the Bruce, securing Scottish independence. Wallace had led the earlier resistance and was executed in 1305." },
  { id: "med-5", lesson: "medieval-britain", level: "easy",
    q: "Which king conquered Wales and built a ring of castles there?",
    options: ["Henry II", "Edward I", "Richard I", "King John"], answer: 1,
    explanation: "Edward I. The Statute of Rhuddlan of 1284 annexed Wales to the English Crown." },
  { id: "med-6", lesson: "medieval-britain", level: "medium",
    q: "Roughly how much of Britain's population died in the Black Death?",
    options: ["A tenth", "A third", "A half", "Two thirds"], answer: 1,
    explanation: "About a third, from 1348. The resulting shortage of labour helped end the feudal system." },
  { id: "med-7", lesson: "medieval-britain", level: "hard",
    q: "What triggered the Peasants' Revolt of 1381?",
    options: ["A new poll tax", "The Black Death", "The loss of France", "The murder of Thomas Becket"], answer: 0,
    explanation: "A poll tax imposed after the Black Death. The revolt was led by Wat Tyler." },
  { id: "med-8", lesson: "medieval-britain", level: "medium",
    q: "How long did the Hundred Years War last?",
    options: ["Exactly 100 years", "From 1337 to 1453", "From 1215 to 1315", "From 1485 to 1585"], answer: 1,
    explanation: "1337 to 1453 — 116 years, on and off, despite the name." },
  { id: "med-9", lesson: "medieval-britain", level: "hard",
    q: "Which houses fought the Wars of the Roses?",
    options: ["Tudor and Stuart", "Lancaster and York", "York and Normandy", "Wessex and Mercia"], answer: 1,
    explanation: "Lancaster (red rose) and York (white rose). The Tudor rose combined both after 1485." },
  { id: "med-10", lesson: "medieval-britain", level: "medium",
    q: "Which battle ended the Wars of the Roses in 1485?",
    options: ["Agincourt", "Bosworth Field", "Bannockburn", "Hastings"], answer: 1,
    explanation: "Bosworth Field. Richard III was killed and Henry Tudor became Henry VII." },
  { id: "med-11", lesson: "medieval-britain", level: "medium",
    q: "Who was murdered in Canterbury Cathedral in 1170?",
    options: ["Thomas Becket", "Richard I", "William Wallace", "Wat Tyler"], answer: 0,
    explanation: "Thomas Becket, Archbishop of Canterbury, after quarrelling with Henry II." },
  { id: "med-12", lesson: "medieval-britain", level: "medium",
    q: "Which English king won the Battle of Agincourt in 1415?",
    options: ["Henry V", "Edward III", "Richard I", "Henry II"], answer: 0,
    explanation: "Henry V. Despite such victories, England ended the Hundred Years War holding only Calais." },
  { id: "med-13", lesson: "medieval-britain", level: "medium",
    q: "Which king spent almost his entire reign abroad on crusade?",
    options: ["King John", "Richard I", "Henry II", "Edward I"], answer: 1,
    explanation: "Richard I, the Lionheart. His brother John succeeded him and was forced to accept Magna Carta." },

  // ── The Tudors ─────────────────────────────────────────────────────────
  { id: "tud-1", lesson: "tudors", level: "easy",
    q: "How many wives did Henry VIII have?",
    options: ["Four", "Five", "Six", "Seven"], answer: 2,
    explanation: "Six: divorced, beheaded, died; divorced, beheaded, survived." },
  { id: "tud-2", lesson: "tudors", level: "medium",
    q: "Why did Henry VIII break with the Roman Catholic Church?",
    options: ["He converted to Protestantism by conviction", "The Pope refused to annul his marriage to Catherine of Aragon", "Parliament voted to leave", "He was excommunicated for heresy"], answer: 1,
    explanation: "The break began as a dispute over his first marriage. He made himself Head of the Church of England." },
  { id: "tud-3", lesson: "tudors", level: "medium",
    q: "In which year was the Spanish Armada defeated?",
    options: ["1534", "1558", "1588", "1603"], answer: 2,
    explanation: "1588 — beaten off by the English navy and then scattered by storms." },
  { id: "tud-4", lesson: "tudors", level: "hard",
    q: "Which of Henry VIII's wives was the mother of Elizabeth I?",
    options: ["Catherine of Aragon", "Anne Boleyn", "Jane Seymour", "Catherine Parr"], answer: 1,
    explanation: "Anne Boleyn, who was beheaded. Catherine of Aragon was Mary I's mother and Jane Seymour Edward VI's." },
  { id: "tud-5", lesson: "tudors", level: "easy",
    q: "Where was William Shakespeare born?",
    options: ["London", "Stratford-upon-Avon", "Canterbury", "Oxford"], answer: 1,
    explanation: "Stratford-upon-Avon in 1564. He worked in London, at the Globe Theatre." },
  { id: "tud-6", lesson: "tudors", level: "medium",
    q: "Which monarch was known as 'Bloody Mary'?",
    options: ["Mary I", "Mary II", "Mary, Queen of Scots", "Elizabeth I"], answer: 0,
    explanation: "Mary I, a devout Catholic who reversed the Reformation and had Protestants executed." },
  { id: "tud-7", lesson: "tudors", level: "medium",
    q: "What was the Dissolution of the Monasteries?",
    options: ["The closing of monasteries and seizure of their wealth by the Crown", "A new set of monastic rules", "The founding of new monasteries", "A tax on the Church paid to Rome"], answer: 0,
    explanation: "It followed Henry VIII's break with Rome and transferred great wealth to the Crown." },
  { id: "tud-8", lesson: "tudors", level: "hard",
    q: "How long did Elizabeth I reign?",
    options: ["About 20 years", "About 45 years", "About 60 years", "About 70 years"], answer: 1,
    explanation: "45 years. She never married and found a religious middle way that largely held." },
  { id: "tud-9", lesson: "tudors", level: "easy",
    q: "Which Tudor king ended the Wars of the Roses and founded the dynasty?",
    options: ["Henry VII", "Henry VIII", "Edward VI", "Richard III"], answer: 0,
    explanation: "Henry VII won at Bosworth Field in 1485." },
  { id: "tud-10", lesson: "tudors", level: "hard",
    q: "Whose son became James VI of Scotland and then James I of England?",
    options: ["Elizabeth I", "Mary, Queen of Scots", "Mary I", "Anne Boleyn"], answer: 1,
    explanation: "Mary, Queen of Scots, executed in 1587. Her son united the two crowns in 1603." },
  { id: "tud-11", lesson: "tudors", level: "medium",
    q: "Which of these plays did Shakespeare write?",
    options: ["The Canterbury Tales", "Macbeth", "Paradise Lost", "Oliver Twist"], answer: 1,
    explanation: "Macbeth. The Canterbury Tales is Chaucer, Paradise Lost is Milton, Oliver Twist is Dickens." },
  { id: "tud-12", lesson: "tudors", level: "medium",
    q: "Which Tudor monarch died at the age of 15?",
    options: ["Edward VI", "Mary I", "Henry VII", "Elizabeth I"], answer: 0,
    explanation: "Edward VI, Henry VIII's only surviving son. The Book of Common Prayer dates from his reign." },

  // ── Stuarts & Civil War ────────────────────────────────────────────────
  { id: "stu-1", lesson: "stuarts-civil-war", level: "easy",
    q: "What is remembered every year on 5 November?",
    options: ["The end of the First World War", "The failure of the Gunpowder Plot", "The Great Fire of London", "The execution of Charles I"], answer: 1,
    explanation: "Guy Fawkes and his fellow plotters failed to blow up Parliament in 1605." },
  { id: "stu-2", lesson: "stuarts-civil-war", level: "easy",
    q: "Who were the Cavaliers?",
    options: ["Supporters of Parliament", "Supporters of the King", "Scottish rebels", "Members of the Gunpowder Plot"], answer: 1,
    explanation: "Cavaliers, or Royalists, supported Charles I. The Roundheads supported Parliament." },
  { id: "stu-3", lesson: "stuarts-civil-war", level: "medium",
    q: "In which year was Charles I executed?",
    options: ["1642", "1649", "1660", "1688"], answer: 1,
    explanation: "1649 — the only English king put to death by his own subjects." },
  { id: "stu-4", lesson: "stuarts-civil-war", level: "hard",
    q: "What title did Oliver Cromwell hold?",
    options: ["King of England", "Lord Protector", "Prime Minister", "Lord Chancellor"], answer: 1,
    explanation: "Lord Protector of the Commonwealth. He refused the crown." },
  { id: "stu-5", lesson: "stuarts-civil-war", level: "medium",
    q: "What was the Restoration of 1660?",
    options: ["Parliament inviting Charles II back to the throne", "The rebuilding of London after the fire", "The return of Catholicism", "The reopening of the monasteries"], answer: 0,
    explanation: "After Cromwell's death Parliament invited Charles II to return, ending the republic." },
  { id: "stu-6", lesson: "stuarts-civil-war", level: "hard",
    q: "What did the Bill of Rights of 1689 establish?",
    options: ["Votes for all men over 21", "That the monarch could not raise taxes or keep an army without Parliament", "The union of England and Scotland", "Freedom of religion for Catholics"], answer: 1,
    explanation: "It made the monarchy constitutional: no taxation or standing army without Parliament, regular parliaments, free elections." },
  { id: "stu-7", lesson: "stuarts-civil-war", level: "hard",
    q: "Why is the change of monarch in 1688 called the Glorious Revolution?",
    options: ["It restored the monarchy after a republic", "William of Orange took the throne with almost no bloodshed in England", "It gave ordinary people the vote", "It ended a war with France"], answer: 1,
    explanation: "James II fled rather than fight, so the throne changed hands without a battle in England." },
  { id: "stu-8", lesson: "stuarts-civil-war", level: "medium",
    q: "Which two monarchs ruled jointly after the Glorious Revolution?",
    options: ["William III and Mary II", "Charles II and James II", "James I and Charles I", "Mary I and Elizabeth I"], answer: 0,
    explanation: "William of Orange and his wife Mary, James II's Protestant daughter." },
  { id: "stu-9", lesson: "stuarts-civil-war", level: "easy",
    q: "In which year was the Great Fire of London?",
    options: ["1649", "1660", "1665", "1666"], answer: 3,
    explanation: "1666, the year after the Great Plague of 1665." },
  { id: "stu-10", lesson: "stuarts-civil-war", level: "hard",
    q: "What did Charles I believe about his authority?",
    options: ["That it came from Parliament", "That it came from God — the divine right of kings", "That it came from the Church of England", "That it could be voted on"], answer: 1,
    explanation: "The divine right of kings. He ruled eleven years without calling Parliament, and the quarrel became war in 1642." },
  { id: "stu-11", lesson: "stuarts-civil-war", level: "medium",
    q: "Which Bible translation was ordered by James I?",
    options: ["The Book of Common Prayer", "The King James Bible", "The Geneva Bible", "The Great Bible"], answer: 1,
    explanation: "The King James Bible, still the best-known English translation." },
  { id: "stu-12", lesson: "stuarts-civil-war", level: "medium",
    q: "Which scientific institution was founded during the reign of Charles II?",
    options: ["The Royal Society", "The British Museum", "The National Gallery", "The Royal Institution"], answer: 0,
    explanation: "The Royal Society, Britain's oldest scientific institution, founded in the 1660s." },

  // ── Britain 1700–1900 ──────────────────────────────────────────────────
  { id: "b18-1", lesson: "britain-1700-1900", level: "medium",
    q: "What did the Act of Union of 1707 create?",
    options: ["The United Kingdom", "The Kingdom of Great Britain", "The Commonwealth", "The British Empire"], answer: 1,
    explanation: "It joined the parliaments of England and Scotland as Great Britain. Ireland was added in 1801, creating the UK." },
  { id: "b18-2", lesson: "britain-1700-1900", level: "medium",
    q: "Which Act of Union created the United Kingdom by adding Ireland?",
    options: ["The Act of 1707", "The Act of 1801", "The Act of 1832", "The Act of 1922"], answer: 1,
    explanation: "1707 made Great Britain; 1801 added Ireland and made it the United Kingdom." },
  { id: "b18-3", lesson: "britain-1700-1900", level: "medium",
    q: "Which battle in 1746 was the last fought on British soil?",
    options: ["Culloden", "Waterloo", "Trafalgar", "Bosworth Field"], answer: 0,
    explanation: "Culloden, where the Jacobite rising under Bonnie Prince Charlie was crushed." },
  { id: "b18-4", lesson: "britain-1700-1900", level: "easy",
    q: "Which Act abolished slavery throughout the British Empire?",
    options: ["The Act of 1807", "The Act of 1833", "The Reform Act of 1832", "The Act of 1801"], answer: 1,
    explanation: "1807 ended the slave trade; 1833 abolished slavery itself and freed those already enslaved." },
  { id: "b18-5", lesson: "britain-1700-1900", level: "hard",
    q: "What did the Act of 1807 abolish?",
    options: ["Slavery itself throughout the Empire", "The slave trade — the buying and carrying of enslaved people", "Child labour in factories", "The East India Company"], answer: 1,
    explanation: "1807 stopped the trade. Slavery itself continued until the Act of 1833." },
  { id: "b18-6", lesson: "britain-1700-1900", level: "easy",
    q: "Who led the parliamentary campaign against the slave trade?",
    options: ["William Wilberforce", "Isambard Kingdom Brunel", "Robert Peel", "Charles Darwin"], answer: 0,
    explanation: "Wilberforce, supported by the Quakers among others." },
  { id: "b18-7", lesson: "britain-1700-1900", level: "medium",
    q: "Who commanded the British fleet at Trafalgar in 1805?",
    options: ["The Duke of Wellington", "Admiral Nelson", "Captain Cook", "Sir Francis Drake"], answer: 1,
    explanation: "Nelson won and was killed in the battle. Nelson's Column stands in Trafalgar Square." },
  { id: "b18-8", lesson: "britain-1700-1900", level: "medium",
    q: "Who finally defeated Napoleon at Waterloo in 1815?",
    options: ["Admiral Nelson", "The Duke of Wellington", "William Pitt", "George III"], answer: 1,
    explanation: "Wellington beat Napoleon on land, ten years after Nelson had beaten the French at sea." },
  { id: "b18-9", lesson: "britain-1700-1900", level: "easy",
    q: "How long did Queen Victoria reign?",
    options: ["From 1801 to 1837", "From 1837 to 1901", "From 1901 to 1936", "From 1760 to 1820"], answer: 1,
    explanation: "64 years — the second longest reign, after Elizabeth II." },
  { id: "b18-10", lesson: "britain-1700-1900", level: "hard",
    q: "Who improved the steam engine and made industrial power practical?",
    options: ["George Stephenson", "James Watt", "Isambard Kingdom Brunel", "Michael Faraday"], answer: 1,
    explanation: "James Watt. Stephenson built the Rocket and the first passenger railways." },
  { id: "b18-11", lesson: "britain-1700-1900", level: "easy",
    q: "Who founded modern nursing during the Crimean War?",
    options: ["Florence Nightingale", "Emmeline Pankhurst", "Elizabeth Fry", "Mary Seacole"], answer: 0,
    explanation: "Florence Nightingale, who set up the first nursing school at St Thomas' Hospital in London." },
  { id: "b18-12", lesson: "britain-1700-1900", level: "medium",
    q: "What did Charles Darwin publish in 1859?",
    options: ["Principia Mathematica", "On the Origin of Species", "The Wealth of Nations", "A Christmas Carol"], answer: 1,
    explanation: "On the Origin of Species, setting out evolution by natural selection." },
  { id: "b18-13", lesson: "britain-1700-1900", level: "medium",
    q: "What was displayed at the Great Exhibition of 1851?",
    options: ["British industrial and imperial achievement, in the Crystal Palace", "The Crown Jewels", "Paintings from the National Gallery", "The first railway engines only"], answer: 0,
    explanation: "It showcased Britain at the height of its industrial power, in the purpose-built Crystal Palace." },
  { id: "b18-14", lesson: "britain-1700-1900", level: "hard",
    q: "In which year did the American colonies declare independence?",
    options: ["1746", "1776", "1801", "1815"], answer: 1,
    explanation: "1776. Britain lost its most valuable settler colonies." },
  { id: "b18-15", lesson: "britain-1700-1900", level: "medium",
    q: "Which engineer built the Great Western Railway and the Clifton Suspension Bridge?",
    options: ["James Watt", "George Stephenson", "Isambard Kingdom Brunel", "Thomas Telford"], answer: 2,
    explanation: "Brunel — railways, bridges, tunnels and pioneering steamships." },

  // ── Britain 1900–Present ───────────────────────────────────────────────
  { id: "b19-1", lesson: "britain-1900-present", level: "easy",
    q: "On what date did the First World War end?",
    options: ["8 May 1918", "11 November 1918", "1 September 1939", "6 June 1944"], answer: 1,
    explanation: "11 November 1918 — which is why Remembrance Day falls on that date." },
  { id: "b19-2", lesson: "britain-1900-present", level: "hard",
    q: "In which year did women get the vote on the same terms as men?",
    options: ["1918", "1928", "1945", "1969"], answer: 1,
    explanation: "1918 gave the vote to women over 30 with a property qualification; 1928 brought full equality at 21." },
  { id: "b19-3", lesson: "britain-1900-present", level: "hard",
    q: "What did the Representation of the People Act of 1918 do for women?",
    options: ["Gave all women over 21 the vote", "Gave women over 30 who met a property qualification the vote", "Gave no women the vote", "Allowed women to stand for Parliament only"], answer: 1,
    explanation: "Over 30, and with property. Equality with men at 21 waited another ten years, until 1928." },
  { id: "b19-4", lesson: "britain-1900-present", level: "easy",
    q: "Who led the suffragette campaign for votes for women?",
    options: ["Florence Nightingale", "Emmeline Pankhurst", "Margaret Thatcher", "Elizabeth Fry"], answer: 1,
    explanation: "Emmeline Pankhurst. The campaign used protests, hunger strikes and imprisonment." },
  { id: "b19-5", lesson: "britain-1900-present", level: "easy",
    q: "Who was Prime Minister for most of the Second World War?",
    options: ["Clement Attlee", "Winston Churchill", "Neville Chamberlain", "David Lloyd George"], answer: 1,
    explanation: "Churchill became Prime Minister in 1940 and led Britain for the rest of the war." },
  { id: "b19-6", lesson: "britain-1900-present", level: "medium",
    q: "What was the Battle of Britain?",
    options: ["A naval battle in the Atlantic", "The RAF holding off the German air force in 1940", "The Allied landings in Normandy", "The bombing of London"], answer: 1,
    explanation: "The air battle of 1940 that prevented invasion. The Blitz was the bombing of British cities." },
  { id: "b19-7", lesson: "britain-1900-present", level: "medium",
    q: "What happened on 6 June 1944?",
    options: ["VE Day", "The D-Day landings in Normandy", "The start of the Blitz", "The evacuation from Dunkirk"], answer: 1,
    explanation: "D-Day — the Allied landings that opened the campaign to liberate western Europe." },
  { id: "b19-8", lesson: "britain-1900-present", level: "medium",
    q: "Who founded the National Health Service in 1948?",
    options: ["William Beveridge", "Aneurin Bevan", "Clement Attlee", "Winston Churchill"], answer: 1,
    explanation: "Bevan as Health Minister. Beveridge wrote the 1942 report; Attlee was the Prime Minister of the day." },
  { id: "b19-9", lesson: "britain-1900-present", level: "medium",
    q: "What did the Beveridge Report of 1942 identify?",
    options: ["Five giants: want, disease, ignorance, squalor and idleness", "The causes of the war", "A plan for decolonisation", "The structure of the Commonwealth"], answer: 0,
    explanation: "Those five giants became the target of the post-war welfare state." },
  { id: "b19-10", lesson: "britain-1900-present", level: "medium",
    q: "Which ship gave its name to a generation of post-war arrivals from the Caribbean?",
    options: ["The Empire Windrush", "The Mayflower", "HMS Victory", "The Cutty Sark"], answer: 0,
    explanation: "The Empire Windrush arrived in 1948, the same year the NHS was founded." },
  { id: "b19-11", lesson: "britain-1900-present", level: "easy",
    q: "When did the UK formally leave the European Union?",
    options: ["June 2016", "31 January 2020", "31 December 2020", "1 January 2021"], answer: 1,
    explanation: "The referendum was June 2016; the UK left on 31 January 2020, with a transition period to year end." },
  { id: "b19-12", lesson: "britain-1900-present", level: "hard",
    q: "In which year did the UK join the European Economic Community?",
    options: ["1957", "1973", "1979", "1992"], answer: 1,
    explanation: "1973. The EEC later became the European Union." },
  { id: "b19-13", lesson: "britain-1900-present", level: "medium",
    q: "Who became the first woman Prime Minister of the UK?",
    options: ["Theresa May", "Margaret Thatcher", "Emmeline Pankhurst", "Barbara Castle"], answer: 1,
    explanation: "Margaret Thatcher in 1979. Theresa May was the second, in 2016." },
  { id: "b19-14", lesson: "britain-1900-present", level: "hard",
    q: "Which agreement of 1998 brought peace to Northern Ireland?",
    options: ["The Good Friday Agreement", "The Anglo-Irish Agreement", "The Treaty of Rome", "The Act of Union"], answer: 0,
    explanation: "The Good Friday Agreement, which also created the power-sharing Northern Ireland Assembly." },
  { id: "b19-15", lesson: "britain-1900-present", level: "medium",
    q: "Which countries became independent in 1947, beginning decolonisation?",
    options: ["Kenya and Nigeria", "India and Pakistan", "Australia and New Zealand", "Jamaica and Barbados"], answer: 1,
    explanation: "India and Pakistan first, then most of Africa and the Caribbean. Many joined the Commonwealth." },
  { id: "b19-16", lesson: "britain-1900-present", level: "medium",
    q: "Where did codebreakers work to break German ciphers in the Second World War?",
    options: ["Bletchley Park", "Chequers", "Portsmouth", "Sandhurst"], answer: 0,
    explanation: "Bletchley Park, where Alan Turing and others shortened the war." },

  // ── Important Dates & Timeline ─────────────────────────────────────────
  { id: "tl-1", lesson: "timeline", level: "medium",
    q: "Which came first: Magna Carta or the Battle of Hastings?",
    options: ["Magna Carta", "The Battle of Hastings", "They happened in the same year", "Magna Carta came first, by two centuries"], answer: 1,
    explanation: "Hastings 1066, Magna Carta 1215 — the Conquest comes first, by about 150 years." },
  { id: "tl-2", lesson: "timeline", level: "hard",
    q: "Put these in order: the Spanish Armada, the Great Fire of London, the Act of Union with Scotland.",
    options: ["Armada, Great Fire, Act of Union", "Great Fire, Armada, Act of Union", "Act of Union, Armada, Great Fire", "Armada, Act of Union, Great Fire"], answer: 0,
    explanation: "Armada 1588, Great Fire 1666, Act of Union 1707." },
  { id: "tl-3", lesson: "timeline", level: "medium",
    q: "Which happened first: the founding of the NHS or the end of the Second World War?",
    options: ["The NHS", "The end of the war", "The same year", "The NHS, by ten years"], answer: 1,
    explanation: "The war ended in 1945; the NHS opened in 1948, built by the government elected afterwards." },
  { id: "tl-4", lesson: "timeline", level: "hard",
    q: "Which of these happened in 1689?",
    options: ["The Bill of Rights", "The Act of Union", "The Glorious Revolution", "The Great Fire of London"], answer: 0,
    explanation: "The Glorious Revolution was 1688; the Bill of Rights that settled its terms was 1689." },
  { id: "tl-5", lesson: "timeline", level: "medium",
    q: "In which year did the Romans first successfully invade Britain?",
    options: ["55 BC", "AD 43", "AD 122", "AD 410"], answer: 1,
    explanation: "AD 43 under Claudius. 55 BC was Caesar's failed expedition; AD 122 Hadrian's Wall; AD 410 the departure." },
  { id: "tl-6", lesson: "timeline", level: "hard",
    q: "Which came first: the abolition of the slave trade or the Battle of Waterloo?",
    options: ["The abolition of the slave trade, in 1807", "Waterloo, in 1815", "They happened the same year", "Waterloo, by twenty years"], answer: 0,
    explanation: "The slave trade was abolished in 1807, eight years before Waterloo in 1815." },
  { id: "tl-7", lesson: "timeline", level: "medium",
    q: "In which year did London most recently host the Olympic Games?",
    options: ["1948", "2000", "2012", "2016"], answer: 2,
    explanation: "2012. London has hosted three times — 1908, 1948 and 2012 — more than any other city." },
  { id: "tl-8", lesson: "timeline", level: "easy",
    q: "In which year did Queen Elizabeth II die?",
    options: ["2020", "2021", "2022", "2023"], answer: 2,
    explanation: "September 2022, after 70 years — the longest reign in British history. Charles III succeeded her." },
  { id: "tl-9", lesson: "timeline", level: "hard",
    q: "Which came first: the Peasants' Revolt or the Black Death?",
    options: ["The Peasants' Revolt", "The Black Death", "The same year", "The Peasants' Revolt, by fifty years"], answer: 1,
    explanation: "The Black Death arrived in 1348; the revolt followed in 1381, triggered by a poll tax imposed afterwards." },
  { id: "tl-10", lesson: "timeline", level: "medium",
    q: "In which year did the Scottish Parliament and the Welsh Assembly first sit?",
    options: ["1979", "1997", "1999", "2007"], answer: 2,
    explanation: "1999, after referendums in 1997." },
  { id: "tl-11", lesson: "timeline", level: "hard",
    q: "Which of these is the oldest?",
    options: ["Hadrian's Wall", "Stonehenge", "The Tower of London", "Edinburgh Castle"], answer: 1,
    explanation: "Stonehenge, from about 2500 BC — over two thousand years older than Hadrian's Wall." },

  // ── The Monarchy ───────────────────────────────────────────────────────
  { id: "mon-1", lesson: "the-monarchy", level: "easy",
    q: "What kind of monarchy does the UK have?",
    options: ["An absolute monarchy", "A constitutional monarchy", "An elected monarchy", "No monarchy at all"], answer: 1,
    explanation: "The monarch is Head of State but does not govern. Parliament makes the law." },
  { id: "mon-2", lesson: "the-monarchy", level: "medium",
    q: "What is Royal Assent?",
    options: ["The monarch's power to veto any law", "The monarch's formal signature that turns a bill into an Act", "The ceremony crowning a monarch", "The monarch's approval of a new Prime Minister"], answer: 1,
    explanation: "The final formal step in making a law. It has not been refused since 1708." },
  { id: "mon-3", lesson: "the-monarchy", level: "medium",
    q: "Who writes the speech the monarch reads at the State Opening of Parliament?",
    options: ["The monarch", "The government", "The Speaker of the Commons", "The House of Lords"], answer: 1,
    explanation: "The government writes it — it sets out their plans, not the monarch's views." },
  { id: "mon-4", lesson: "the-monarchy", level: "easy",
    q: "Who became monarch in September 2022?",
    options: ["King Charles III", "Prince William", "Queen Camilla", "King George VII"], answer: 0,
    explanation: "Charles III succeeded his mother, Elizabeth II, on her death." },
  { id: "mon-5", lesson: "the-monarchy", level: "easy",
    q: "Where does a coronation take place?",
    options: ["St Paul's Cathedral", "Westminster Abbey", "Buckingham Palace", "The Tower of London"], answer: 1,
    explanation: "Westminster Abbey, conducted by the Archbishop of Canterbury." },
  { id: "mon-6", lesson: "the-monarchy", level: "hard",
    q: "Since the law changed in 2013, who inherits the throne?",
    options: ["The eldest son", "The eldest child, regardless of sex", "Whoever Parliament chooses", "The eldest male relative"], answer: 1,
    explanation: "The eldest child inherits. An older sister is no longer passed over for a younger brother." },
  { id: "mon-7", lesson: "the-monarchy", level: "medium",
    q: "Can the monarch express political opinions in public?",
    options: ["Yes, freely", "No — the monarch must remain politically neutral", "Only during elections", "Only in the House of Lords"], answer: 1,
    explanation: "Political neutrality is the whole point of the office. The monarch does not vote either." },
  { id: "mon-8", lesson: "the-monarchy", level: "hard",
    q: "How long did Queen Elizabeth II reign?",
    options: ["50 years", "64 years", "70 years", "75 years"], answer: 2,
    explanation: "70 years, from 1952 to 2022 — the longest in British history. Victoria's 64 years is second." },
  { id: "mon-9", lesson: "the-monarchy", level: "easy",
    q: "Who is the heir to the throne?",
    options: ["Prince William", "Prince Harry", "Princess Anne", "Prince Edward"], answer: 0,
    explanation: "Prince William, Prince of Wales." },
  { id: "mon-10", lesson: "the-monarchy", level: "hard",
    q: "What role does the monarch play in appointing a Prime Minister?",
    options: ["Chooses whoever they prefer", "Invites the leader who can command a majority in the Commons", "Appoints the leader of the largest party in the Lords", "Has no role at all"], answer: 1,
    explanation: "The monarch invites whoever can command a Commons majority — a formal act with no personal choice in practice." },

  // ── Government & Parliament ────────────────────────────────────────────
  { id: "gov-1", lesson: "government-parliament", level: "easy",
    q: "How many MPs sit in the House of Commons?",
    options: ["500", "650", "800", "1,000"], answer: 1,
    explanation: "650, one for each constituency, each elected by first past the post." },
  { id: "gov-2", lesson: "government-parliament", level: "medium",
    q: "How do people become members of the House of Lords?",
    options: ["Elected by constituencies", "Appointed, or sitting as hereditary peers or bishops", "Chosen by the House of Commons", "Selected at random"], answer: 1,
    explanation: "The Lords is not elected. Most are life peers, alongside some hereditary peers and senior Church of England bishops." },
  { id: "gov-3", lesson: "government-parliament", level: "easy",
    q: "What is the maximum period between UK general elections?",
    options: ["Three years", "Four years", "Five years", "Seven years"], answer: 2,
    explanation: "Five years, though an election can be called sooner." },
  { id: "gov-4", lesson: "government-parliament", level: "easy",
    q: "Where does the Prime Minister live and work?",
    options: ["Buckingham Palace", "10 Downing Street", "The Palace of Westminster", "Chequers only"], answer: 1,
    explanation: "10 Downing Street in London." },
  { id: "gov-5", lesson: "government-parliament", level: "medium",
    q: "What voting system is used to elect MPs to the House of Commons?",
    options: ["Proportional representation", "First past the post", "The single transferable vote", "A second ballot"], answer: 1,
    explanation: "First past the post — whoever gets the most votes in a constituency wins the seat." },
  { id: "gov-6", lesson: "government-parliament", level: "medium",
    q: "What is a by-election?",
    options: ["A second round of a general election", "An election in one constituency when its MP dies or resigns", "An election for the House of Lords", "A local council election"], answer: 1,
    explanation: "It fills a single seat between general elections." },
  { id: "gov-7", lesson: "government-parliament", level: "medium",
    q: "Who chairs debates in the House of Commons?",
    options: ["The Prime Minister", "The Speaker", "The Leader of the Opposition", "The Lord Chancellor"], answer: 1,
    explanation: "The Speaker, who is politically neutral and gives up party allegiance." },
  { id: "gov-8", lesson: "government-parliament", level: "easy",
    q: "From what age can you vote in a UK general election?",
    options: ["16", "17", "18", "21"], answer: 2,
    explanation: "18, and you must be on the electoral register. Photo ID is now required at polling stations in Great Britain." },
  { id: "gov-9", lesson: "government-parliament", level: "hard",
    q: "What is the Cabinet?",
    options: ["All MPs of the governing party", "About 20 senior ministers chosen by the Prime Minister", "The House of Lords committee", "The civil service leadership"], answer: 1,
    explanation: "Senior ministers, each running a department — Chancellor of the Exchequer, Home Secretary, Foreign Secretary and so on." },
  { id: "gov-10", lesson: "government-parliament", level: "easy",
    q: "What is the Opposition?",
    options: ["Members of the Lords who vote against the government", "The largest party not in government", "Any MP who rebels", "The civil service"], answer: 1,
    explanation: "Its leader is Leader of the Opposition and heads a shadow cabinet challenging each minister." },
  { id: "gov-11", lesson: "government-parliament", level: "medium",
    q: "Are civil servants politically neutral?",
    options: ["No — they change with each government", "Yes — they carry out policy but stay in post when the government changes", "Only senior ones", "They are elected"], answer: 1,
    explanation: "Ministers come and go; the civil service stays and serves whichever government is in office." },
  { id: "gov-12", lesson: "government-parliament", level: "medium",
    q: "What are local council services funded by?",
    options: ["National Insurance", "Council tax and central government funding", "Income tax only", "The Crown"], answer: 1,
    explanation: "Councils run schools, refuse collection, housing, roads and libraries, funded by council tax and central grants." },
  { id: "gov-13", lesson: "government-parliament", level: "hard",
    q: "What must happen before a bill becomes an Act of Parliament?",
    options: ["Only a Commons vote", "Debate and agreement in both Houses, then Royal Assent", "A public referendum", "Approval by the Supreme Court"], answer: 1,
    explanation: "Commons, then Lords, back to the Commons if amended, then the monarch's Royal Assent." },
  { id: "gov-14", lesson: "government-parliament", level: "medium",
    q: "Which of these is a national party in Scotland?",
    options: ["Plaid Cymru", "The SNP", "Sinn Féin", "The Liberal Democrats"], answer: 1,
    explanation: "The Scottish National Party. Plaid Cymru is the Welsh national party." },

  // ── Devolution ─────────────────────────────────────────────────────────
  { id: "dev-1", lesson: "devolution", level: "medium",
    q: "What are members of the Scottish Parliament called?",
    options: ["MPs", "MSPs", "MSs", "MLAs"], answer: 1,
    explanation: "MSPs in Scotland, MSs in the Senedd, MLAs in the Northern Ireland Assembly, MPs at Westminster." },
  { id: "dev-2", lesson: "devolution", level: "medium",
    q: "What are members of the Northern Ireland Assembly called?",
    options: ["MSPs", "MSs", "MLAs", "TDs"], answer: 2,
    explanation: "MLAs — Members of the Legislative Assembly, at Stormont." },
  { id: "dev-3", lesson: "devolution", level: "medium",
    q: "Which of these is a reserved matter kept by the UK Parliament?",
    options: ["Health", "Education", "Defence and foreign policy", "Housing"], answer: 2,
    explanation: "Defence, foreign policy, immigration, the currency and national security are reserved. Health, education and housing are devolved." },
  { id: "dev-4", lesson: "devolution", level: "easy",
    q: "Where does the Scottish Parliament sit?",
    options: ["Stormont", "Holyrood", "The Senedd", "Westminster"], answer: 1,
    explanation: "Holyrood in Edinburgh. Stormont is Northern Ireland's, the Senedd is Wales'." },
  { id: "dev-5", lesson: "devolution", level: "easy",
    q: "What is the Welsh Parliament called?",
    options: ["The Senedd", "Holyrood", "Stormont", "The Assembly"], answer: 0,
    explanation: "Senedd Cymru. It was called the National Assembly for Wales until 2020." },
  { id: "dev-6", lesson: "devolution", level: "hard",
    q: "Does England have its own devolved parliament?",
    options: ["Yes, in Manchester", "Yes, alongside the UK Parliament", "No — English matters are decided by the UK Parliament", "Yes, since 1999"], answer: 2,
    explanation: "England has no devolved parliament, which is why the UK Parliament and 'the English one' are easy to confuse." },
  { id: "dev-7", lesson: "devolution", level: "medium",
    q: "Which agreement created the Northern Ireland Assembly?",
    options: ["The Act of Union", "The Good Friday Agreement of 1998", "The Treaty of Rome", "The Scotland Act"], answer: 1,
    explanation: "The Good Friday Agreement, with power shared between communities." },
  { id: "dev-8", lesson: "devolution", level: "hard",
    q: "Why do university fees and NHS rules differ across the UK?",
    options: ["Each nation sets its own taxes entirely", "Health and education are devolved matters", "The EU required it", "Local councils decide"], answer: 1,
    explanation: "Health and education are devolved, so each nation's government sets its own policy." },

  // ── Law & Justice ──────────────────────────────────────────────────────
  { id: "law-1", lesson: "law-justice", level: "easy",
    q: "How many people sit on a jury in a Crown Court in England and Wales?",
    options: ["10", "12", "15", "20"], answer: 1,
    explanation: "12 in England, Wales and Northern Ireland. Scotland is the exception, with 15." },
  { id: "law-2", lesson: "law-justice", level: "medium",
    q: "How many people sit on a jury in Scotland?",
    options: ["10", "12", "15", "18"], answer: 2,
    explanation: "15 — Scotland has its own legal system and differs from the rest of the UK here." },
  { id: "law-3", lesson: "law-justice", level: "easy",
    q: "Who normally hears minor criminal cases in England and Wales?",
    options: ["Crown Court judges with a jury", "Magistrates, usually unpaid volunteers", "The Supreme Court", "Barristers sitting as a panel"], answer: 1,
    explanation: "Magistrates handle the great majority of criminal cases and are members of the local community." },
  { id: "law-4", lesson: "law-justice", level: "medium",
    q: "Which of these is a civil rather than a criminal matter?",
    options: ["Theft", "A dispute with a landlord over a deposit", "Assault", "Dangerous driving"], answer: 1,
    explanation: "Civil law covers disputes between people and organisations. The other three are criminal offences." },
  { id: "law-5", lesson: "law-justice", level: "easy",
    q: "What is the highest court of appeal in the UK?",
    options: ["The Crown Court", "The Court of Appeal", "The Supreme Court", "The House of Lords"], answer: 2,
    explanation: "The Supreme Court, which took over that role from the House of Lords in 2009." },
  { id: "law-6", lesson: "law-justice", level: "medium",
    q: "Between which ages can you be summoned for jury service?",
    options: ["16 to 65", "18 to 70", "21 to 70", "18 to 65"], answer: 1,
    explanation: "18 to 70, if you are on the electoral register. It is a legal duty." },
  { id: "law-7", lesson: "law-justice", level: "hard",
    q: "What is legal aid?",
    options: ["Free advice from the police", "Public funding for legal advice or representation for those who cannot afford it", "A charity run by solicitors", "Insurance against losing a case"], answer: 1,
    explanation: "It exists so the right to a fair trial is real rather than theoretical." },
  { id: "law-8", lesson: "law-justice", level: "medium",
    q: "What is the difference between a solicitor and a barrister?",
    options: ["Solicitors advise and prepare cases; barristers argue in the higher courts", "Barristers advise; solicitors judge", "There is no difference", "Solicitors work only for the government"], answer: 0,
    explanation: "Solicitors give advice and represent clients in lower courts; barristers are specialist advocates in the higher courts." },
  { id: "law-9", lesson: "law-justice", level: "medium",
    q: "Who decides the sentence in a Crown Court trial?",
    options: ["The jury", "The judge", "The magistrates", "The prosecution"], answer: 1,
    explanation: "The jury decides guilt; the judge decides the law and the sentence." },
  { id: "law-10", lesson: "law-justice", level: "medium",
    q: "Are judges independent of the government?",
    options: ["No, they are appointed by ministers and follow their instructions", "Yes — they interpret the law and can find government action unlawful", "Only in the Supreme Court", "Only in civil cases"], answer: 1,
    explanation: "Judicial independence is central to the rule of law. A government act found unlawful must be put right." },
  { id: "law-11", lesson: "law-justice", level: "hard",
    q: "What is the age of criminal responsibility in Scotland?",
    options: ["10", "12", "14", "16"], answer: 1,
    explanation: "12 in Scotland and 10 in England, Wales and Northern Ireland — a difference the test likes to ask about." },
  { id: "law-12", lesson: "law-justice", level: "medium",
    q: "Must the police obey the law themselves?",
    options: ["No, they are exempt while on duty", "Yes — and complaints against them are investigated independently", "Only senior officers", "Only in civil matters"], answer: 1,
    explanation: "Everyone is subject to the law, including the police. That is what the rule of law means." },

  // ── Rights & Responsibilities ──────────────────────────────────────────
  { id: "rr-1", lesson: "rights-responsibilities", level: "medium",
    q: "What does National Insurance pay towards?",
    options: ["Only the NHS", "The state pension and certain benefits", "Local council services", "Private health insurance"], answer: 1,
    explanation: "NI contributions build entitlement to the state pension and some benefits. Council tax pays for local services." },
  { id: "rr-2", lesson: "rights-responsibilities", level: "medium",
    q: "How do most employees pay income tax?",
    options: ["By annual cheque", "Through PAYE, deducted by the employer", "Through Self Assessment", "At their local council"], answer: 1,
    explanation: "PAYE — Pay As You Earn. The self-employed complete a Self Assessment return instead." },
  { id: "rr-3", lesson: "rights-responsibilities", level: "medium",
    q: "Which body collects tax in the UK?",
    options: ["The Treasury", "HM Revenue and Customs", "The Bank of England", "The Home Office"], answer: 1,
    explanation: "HMRC collects income tax, National Insurance and other taxes." },
  { id: "rr-4", lesson: "rights-responsibilities", level: "medium",
    q: "Which Act brought the European Convention on Human Rights into UK law?",
    options: ["The Equality Act 2010", "The Human Rights Act 1998", "The Bill of Rights 1689", "Magna Carta"], answer: 1,
    explanation: "The Human Rights Act 1998." },
  { id: "rr-5", lesson: "rights-responsibilities", level: "easy",
    q: "Which of these is a responsibility of living in the UK?",
    options: ["Joining a political party", "Paying tax and National Insurance", "Attending church", "Owning property"], answer: 1,
    explanation: "Tax and National Insurance fund the NHS, schools, roads, defence and the police." },
  { id: "rr-6", lesson: "rights-responsibilities", level: "hard",
    q: "How is a vote cast in a UK election?",
    options: ["Publicly, by show of hands", "By secret ballot", "By declaring it to a returning officer", "Online only"], answer: 1,
    explanation: "By secret ballot — your vote cannot be seen or traced." },
  { id: "rr-7", lesson: "rights-responsibilities", level: "medium",
    q: "What should you do about a law you disagree with?",
    options: ["Ignore it", "Campaign and vote to change it, while still obeying it", "Take it to the monarch", "Refuse to pay tax"], answer: 1,
    explanation: "Obey the law while working to change it. That is the difference between liberty and lawlessness." },

  // ── British Society & Culture ──────────────────────────────────────────
  { id: "soc-1", lesson: "society-culture", level: "medium",
    q: "Roughly what is the population of the UK?",
    options: ["About 45 million", "About 67 million", "About 85 million", "About 100 million"], answer: 1,
    explanation: "Around 67 million, with much the largest share in England." },
  { id: "soc-2", lesson: "society-culture", level: "easy",
    q: "What is the legal position on forced marriage in the UK?",
    options: ["Allowed with parental consent", "A criminal offence", "Allowed over 21", "A civil matter only"], answer: 1,
    explanation: "Forcing someone to marry is a crime. An arranged marriage both people freely accept is lawful; a forced one is not." },
  { id: "soc-3", lesson: "society-culture", level: "easy",
    q: "What is a civil partnership?",
    options: ["A business agreement", "A legal alternative to marriage with similar rights", "A form of employment contract", "A council housing arrangement"], answer: 1,
    explanation: "Open to both same-sex and opposite-sex couples, with rights similar to marriage." },
  { id: "soc-4", lesson: "society-culture", level: "medium",
    q: "When did same-sex marriage become legal in Northern Ireland?",
    options: ["2014", "2016", "2020", "It is not legal there"], answer: 2,
    explanation: "2020 in Northern Ireland; 2014 in England, Wales and Scotland." },
  { id: "soc-5", lesson: "society-culture", level: "medium",
    q: "How is volunteering regarded in the UK?",
    options: ["As unusual and discouraged", "As a valued part of community life", "As paid part-time work", "As compulsory for citizens"], answer: 1,
    explanation: "Charity shops, food banks, sports clubs, school governors — giving time is treated as valuable as giving money." },
  { id: "soc-6", lesson: "society-culture", level: "hard",
    q: "Roughly what share of the UK population belongs to a minority ethnic group?",
    options: ["About a twentieth", "About a fifth", "About a half", "About three quarters"], answer: 1,
    explanation: "Roughly a fifth, with the largest cities being the most diverse." },

  // ── Religion & Beliefs ─────────────────────────────────────────────────
  { id: "rel-1", lesson: "religion-beliefs", level: "medium",
    q: "Who is the Supreme Governor of the Church of England?",
    options: ["The Archbishop of Canterbury", "The monarch", "The Prime Minister", "The Pope"], answer: 1,
    explanation: "The monarch — a role dating from Henry VIII's break with Rome. The Archbishop of Canterbury is its senior bishop." },
  { id: "rel-2", lesson: "religion-beliefs", level: "hard",
    q: "Which nation of the UK has a Presbyterian national church?",
    options: ["England", "Scotland", "Wales", "Northern Ireland"], answer: 1,
    explanation: "The Church of Scotland. Wales and Northern Ireland have no established church at all." },
  { id: "rel-3", lesson: "religion-beliefs", level: "easy",
    q: "What is the second largest religion in the UK?",
    options: ["Hinduism", "Islam", "Judaism", "Sikhism"], answer: 1,
    explanation: "Islam. Christianity is the largest, and a large and growing share of people report no religion." },
  { id: "rel-4", lesson: "religion-beliefs", level: "easy",
    q: "Which festival is known as the festival of lights?",
    options: ["Eid al-Fitr", "Diwali", "Vaisakhi", "Hanukkah"], answer: 1,
    explanation: "Diwali, the Hindu festival of lights, also marked by Sikhs and Jains." },
  { id: "rel-5", lesson: "religion-beliefs", level: "hard",
    q: "Who founded Sikhism?",
    options: ["Guru Nanak", "The Buddha", "Guru Gobind Singh", "Moses"], answer: 0,
    explanation: "Guru Nanak. Vaisakhi is the major Sikh festival." },
  { id: "rel-6", lesson: "religion-beliefs", level: "medium",
    q: "Does religious tolerance in the UK protect people with no religion?",
    options: ["No, only believers", "Yes — belief and non-belief are both protected", "Only in Scotland", "Only in schools"], answer: 1,
    explanation: "Religion or belief is a protected characteristic, and that includes having none." },
  { id: "rel-7", lesson: "religion-beliefs", level: "medium",
    q: "Which senior clergy sit in the House of Lords?",
    options: ["Roman Catholic bishops", "Church of England bishops", "Church of Scotland ministers", "No clergy sit in the Lords"], answer: 1,
    explanation: "Senior Church of England bishops sit in the Lords — a consequence of it being the established church in England." },

  // ── British Traditions & Celebrations ──────────────────────────────────
  { id: "tra-1", lesson: "traditions-celebrations", level: "easy",
    q: "What is celebrated on 26 December?",
    options: ["Christmas Eve", "Boxing Day", "New Year's Eve", "Twelfth Night"], answer: 1,
    explanation: "Boxing Day, a public holiday throughout the UK." },
  { id: "tra-2", lesson: "traditions-celebrations", level: "medium",
    q: "What is Hogmanay?",
    options: ["The Scottish New Year celebration on 31 December", "A Welsh harvest festival", "The day before Lent", "A Northern Irish holiday in July"], answer: 0,
    explanation: "New Year's Eve in Scotland, celebrated on a larger scale than elsewhere. Scotland also takes 2 January as a holiday." },
  { id: "tra-3", lesson: "traditions-celebrations", level: "easy",
    q: "What is eaten on Shrove Tuesday?",
    options: ["Hot cross buns", "Pancakes", "Christmas pudding", "Haggis"], answer: 1,
    explanation: "Pancake Day, the day before Lent begins. It is not a public holiday." },
  { id: "tra-4", lesson: "traditions-celebrations", level: "medium",
    q: "What does Remembrance Day on 11 November mark?",
    options: ["The Gunpowder Plot", "The end of the First World War", "The Battle of Britain", "VE Day"], answer: 1,
    explanation: "The armistice of 11 November 1918. Poppies are worn and there is a two-minute silence at 11am." },
  { id: "tra-5", lesson: "traditions-celebrations", level: "hard",
    q: "Which two patron saints' days are public holidays in their nations?",
    options: ["St George's and St David's", "St Patrick's and St Andrew's", "St George's and St Andrew's", "All four are public holidays"], answer: 1,
    explanation: "St Patrick's Day in Northern Ireland and St Andrew's Day in Scotland. St George's and St David's are not." },
  { id: "tra-6", lesson: "traditions-celebrations", level: "easy",
    q: "What are bank holidays?",
    options: ["Days when only banks close", "Public holidays when most businesses close", "Days for paying taxes", "Religious festivals only"], answer: 1,
    explanation: "They differ between the four nations, and include days in early May, late May and August." },
  { id: "tra-7", lesson: "traditions-celebrations", level: "medium",
    q: "When is Burns Night?",
    options: ["1 January", "25 January", "1 March", "30 November"], answer: 1,
    explanation: "25 January, celebrating Robert Burns, Scotland's national poet." },
  { id: "tra-8", lesson: "traditions-celebrations", level: "easy",
    q: "On what date is Halloween?",
    options: ["31 October", "5 November", "1 November", "11 November"], answer: 0,
    explanation: "31 October — an ancient festival, now marked with costumes and pumpkins. Bonfire Night follows on 5 November." },
  { id: "tra-9", lesson: "traditions-celebrations", level: "medium",
    q: "Which Easter days are public holidays in most of the UK?",
    options: ["Good Friday and Easter Monday", "Easter Sunday only", "The whole Easter week", "Maundy Thursday only"], answer: 0,
    explanation: "Good Friday and Easter Monday. The date moves each year, falling in March or April." },
  { id: "tra-10", lesson: "traditions-celebrations", level: "medium",
    q: "What is traditionally eaten for Christmas dinner in Britain?",
    options: ["Roast turkey", "Haggis", "Fish and chips", "Roast lamb"], answer: 0,
    explanation: "Roast turkey with vegetables, followed by Christmas pudding." },

  // ── Sports & Leisure ───────────────────────────────────────────────────
  { id: "spo-1", lesson: "sports-leisure", level: "easy",
    q: "Where is the Wimbledon tennis tournament held?",
    options: ["Manchester", "London", "Edinburgh", "Birmingham"], answer: 1,
    explanation: "Wimbledon is a district of south-west London — the oldest tennis tournament in the world." },
  { id: "spo-2", lesson: "sports-leisure", level: "medium",
    q: "Which sport originated in Scotland?",
    options: ["Cricket", "Golf", "Rugby league", "Tennis"], answer: 1,
    explanation: "Golf, with St Andrews as its historic home. Cricket and rugby originated in England." },
  { id: "spo-3", lesson: "sports-leisure", level: "medium",
    q: "How many times has London hosted the summer Olympic Games?",
    options: ["Once", "Twice", "Three times", "Four times"], answer: 2,
    explanation: "1908, 1948 and 2012 — more than any other city." },
  { id: "spo-4", lesson: "sports-leisure", level: "medium",
    q: "What is the Ashes?",
    options: ["A rugby tournament", "A Test cricket series between England and Australia", "A horse race at Aintree", "A golf championship"], answer: 1,
    explanation: "The historic cricket series between England and Australia. Lord's in London is the most famous ground." },
  { id: "spo-5", lesson: "sports-leisure", level: "easy",
    q: "Which nations compete in the Six Nations rugby championship?",
    options: ["Only the four UK nations", "England, Scotland, Wales, Ireland, France and Italy", "The Commonwealth nations", "England, Wales, Australia, France, Italy and Ireland"], answer: 1,
    explanation: "The four home nations plus France and Italy — and Ireland competes as one team, north and south." },
  { id: "spo-6", lesson: "sports-leisure", level: "hard",
    q: "Where is the Grand National run?",
    options: ["Ascot", "Aintree", "Epsom", "Cheltenham"], answer: 1,
    explanation: "Aintree, near Liverpool. Royal Ascot and the Derby at Epsom are the other famous meetings." },
  { id: "spo-7", lesson: "sports-leisure", level: "hard",
    q: "How do the UK nations compete at the Commonwealth Games?",
    options: ["As one British team", "Each nation competes separately", "Only England competes", "As two teams, Britain and Ireland"], answer: 1,
    explanation: "England, Scotland, Wales and Northern Ireland each enter separately — unlike at the Olympics." },
  { id: "spo-8", lesson: "sports-leisure", level: "medium",
    q: "What is the oldest football competition in the world?",
    options: ["The Premier League", "The FA Cup", "The World Cup", "The Champions League"], answer: 1,
    explanation: "The FA Cup, an English competition and the oldest in the sport." },
  { id: "spo-9", lesson: "sports-leisure", level: "medium",
    q: "Which organisation cares for many historic houses, gardens and coastline in the UK?",
    options: ["The National Trust", "English Heritage only", "The Royal Society", "The British Museum"], answer: 0,
    explanation: "The National Trust, a charity that protects historic places and open countryside." },

  // ── Literature, Art & Music ────────────────────────────────────────────
  { id: "lit-1", lesson: "literature-art-music", level: "medium",
    q: "Who wrote The Canterbury Tales?",
    options: ["William Shakespeare", "Geoffrey Chaucer", "Charles Dickens", "Robert Burns"], answer: 1,
    explanation: "Chaucer, in the fourteenth century — two hundred years before Shakespeare." },
  { id: "lit-2", lesson: "literature-art-music", level: "easy",
    q: "Which city were The Beatles from?",
    options: ["Manchester", "Liverpool", "London", "Birmingham"], answer: 1,
    explanation: "Liverpool — the most commercially successful band in British history." },
  { id: "lit-3", lesson: "literature-art-music", level: "medium",
    q: "Robert Burns is the national poet of which nation?",
    options: ["Wales", "Scotland", "Northern Ireland", "England"], answer: 1,
    explanation: "Scotland's Bard. He wrote Auld Lang Syne, sung at New Year around the world." },
  { id: "lit-4", lesson: "literature-art-music", level: "easy",
    q: "Who wrote Pride and Prejudice?",
    options: ["Jane Austen", "Charlotte Brontë", "George Eliot", "Agatha Christie"], answer: 0,
    explanation: "Jane Austen, whose novels portray English social life in the early nineteenth century." },
  { id: "lit-5", lesson: "literature-art-music", level: "easy",
    q: "Which novelist wrote Oliver Twist and Great Expectations?",
    options: ["Thomas Hardy", "Charles Dickens", "Rudyard Kipling", "George Orwell"], answer: 1,
    explanation: "Charles Dickens, whose books exposed the poverty of industrial Britain." },
  { id: "lit-6", lesson: "literature-art-music", level: "hard",
    q: "Where is the National Gallery?",
    options: ["Trafalgar Square, London", "Edinburgh", "Manchester", "Oxford"], answer: 0,
    explanation: "Trafalgar Square in London. It holds the national collection of paintings and is free to enter." },
  { id: "lit-7", lesson: "literature-art-music", level: "medium",
    q: "In which year was the British Museum founded?",
    options: ["1653", "1753", "1853", "1901"], answer: 1,
    explanation: "1753 — the first national public museum in the world, and free to enter." },
  { id: "lit-8", lesson: "literature-art-music", level: "medium",
    q: "Which prize for contemporary art is named after a British painter?",
    options: ["The Booker Prize", "The Turner Prize", "The Mercury Prize", "The Brit Award"], answer: 1,
    explanation: "The Turner Prize, named after J. M. W. Turner, the painter of light and sea." },
  { id: "lit-9", lesson: "literature-art-music", level: "medium",
    q: "What are the Proms?",
    options: ["A summer season of classical concerts at the Royal Albert Hall", "A rock festival in Somerset", "A poetry competition", "A dance tradition in Wales"], answer: 0,
    explanation: "Running since 1895 and ending with the Last Night of the Proms." },
  { id: "lit-10", lesson: "literature-art-music", level: "hard",
    q: "Which of these composers was British?",
    options: ["Edward Elgar", "Johann Sebastian Bach", "Wolfgang Amadeus Mozart", "Antonín Dvořák"], answer: 0,
    explanation: "Elgar, alongside Purcell, Holst, Vaughan Williams and Britten." },

  // ── Science & Inventions ───────────────────────────────────────────────
  { id: "sci-1", lesson: "science-inventions", level: "easy",
    q: "Who discovered penicillin?",
    options: ["Isaac Newton", "Alexander Fleming", "Michael Faraday", "Charles Darwin"], answer: 1,
    explanation: "Fleming, a Scottish scientist, in 1928. It became the first widely used antibiotic." },
  { id: "sci-2", lesson: "science-inventions", level: "medium",
    q: "Who invented the World Wide Web?",
    options: ["Alan Turing", "Tim Berners-Lee", "John Logie Baird", "Charles Babbage"], answer: 1,
    explanation: "Tim Berners-Lee, in 1989 while working at CERN." },
  { id: "sci-3", lesson: "science-inventions", level: "easy",
    q: "Which scientist described gravity and the laws of motion?",
    options: ["Isaac Newton", "Michael Faraday", "Ernest Rutherford", "Charles Darwin"], answer: 0,
    explanation: "Newton, whose Principia Mathematica is one of the most important scientific books ever written." },
  { id: "sci-4", lesson: "science-inventions", level: "hard",
    q: "Who gave the first public demonstration of television?",
    options: ["Alexander Graham Bell", "John Logie Baird", "Michael Faraday", "James Watt"], answer: 1,
    explanation: "John Logie Baird, a Scot. Bell developed the telephone." },
  { id: "sci-5", lesson: "science-inventions", level: "hard",
    q: "Whose X-ray work was essential to discovering the structure of DNA?",
    options: ["Rosalind Franklin", "Florence Nightingale", "Ada Lovelace", "Dorothy Hodgkin"], answer: 0,
    explanation: "Rosalind Franklin, alongside Crick and Watson." },
  { id: "sci-6", lesson: "science-inventions", level: "easy",
    q: "Who discovered electromagnetic induction, the principle behind the electric motor?",
    options: ["James Watt", "Michael Faraday", "Isaac Newton", "George Stephenson"], answer: 1,
    explanation: "Michael Faraday — the principle behind both the motor and the generator." },
  { id: "sci-7", lesson: "science-inventions", level: "medium",
    q: "Where was Dolly the sheep, the first cloned mammal, created?",
    options: ["Wales", "Scotland", "England", "Northern Ireland"], answer: 1,
    explanation: "Scotland, in 1996." },
  { id: "sci-8", lesson: "science-inventions", level: "medium",
    q: "In which country did the first successful IVF birth take place?",
    options: ["The United States", "England", "France", "Australia"], answer: 1,
    explanation: "England, in 1978." },
  { id: "sci-9", lesson: "science-inventions", level: "medium",
    q: "Who laid the foundations of computer science and worked at Bletchley Park?",
    options: ["Alan Turing", "Tim Berners-Lee", "Isaac Newton", "Ernest Rutherford"], answer: 0,
    explanation: "Alan Turing, whose codebreaking work shortened the Second World War." },

  // ── Famous British People ──────────────────────────────────────────────
  { id: "fam-1", lesson: "famous-people", level: "easy",
    q: "Who was the first woman Prime Minister of the UK?",
    options: ["Emmeline Pankhurst", "Margaret Thatcher", "Theresa May", "Florence Nightingale"], answer: 1,
    explanation: "Margaret Thatcher, from 1979 to 1990. Theresa May was the second, from 2016." },
  { id: "fam-2", lesson: "famous-people", level: "medium",
    q: "Which Prime Minister's government built the welfare state and the NHS?",
    options: ["Winston Churchill", "Clement Attlee", "David Lloyd George", "Margaret Thatcher"], answer: 1,
    explanation: "Attlee's government, elected in 1945. Bevan founded the NHS as his Health Minister." },
  { id: "fam-3", lesson: "famous-people", level: "medium",
    q: "Who opened Britain's first Indian restaurant and introduced shampooing?",
    options: ["Sake Dean Mahomet", "Mary Seacole", "Rudyard Kipling", "Gandhi"], answer: 0,
    explanation: "Sake Dean Mahomet, an early figure in Britain's multicultural history." },
  { id: "fam-4", lesson: "famous-people", level: "easy",
    q: "Which explorer's voyages mapped much of the Pacific?",
    options: ["Sir Francis Drake", "Captain James Cook", "Sir Walter Raleigh", "Ernest Shackleton"], answer: 1,
    explanation: "Captain James Cook, in the eighteenth century." },
  { id: "fam-5", lesson: "famous-people", level: "hard",
    q: "Who was voted the greatest Briton in a national poll?",
    options: ["Winston Churchill", "Isaac Newton", "William Shakespeare", "Queen Elizabeth II"], answer: 0,
    explanation: "Winston Churchill, who led Britain through the Second World War." },
  { id: "fam-6", lesson: "famous-people", level: "easy",
    q: "Who led Scottish resistance to Edward I and was executed in 1305?",
    options: ["Robert the Bruce", "William Wallace", "Bonnie Prince Charlie", "Rob Roy"], answer: 1,
    explanation: "William Wallace. Robert the Bruce later won independence at Bannockburn in 1314." },
  { id: "fam-7", lesson: "famous-people", level: "medium",
    q: "Which of these people campaigned to abolish the slave trade?",
    options: ["Isambard Kingdom Brunel", "William Wilberforce", "Oliver Cromwell", "Alexander Fleming"], answer: 1,
    explanation: "Wilberforce led the parliamentary campaign that ended the trade in 1807." },

  // ── Education & Healthcare ─────────────────────────────────────────────
  { id: "edu-1", lesson: "education-healthcare", level: "medium",
    q: "Between which ages is education compulsory in England?",
    options: ["4 to 16", "5 to 16", "6 to 18", "5 to 14"], answer: 1,
    explanation: "5 to 16 in England, Wales and Scotland; Northern Ireland starts at 4. In England you must stay in education or training until 18." },
  { id: "edu-2", lesson: "education-healthcare", level: "easy",
    q: "Which number do you call for urgent medical advice that is not an emergency?",
    options: ["999", "111", "101", "112"], answer: 1,
    explanation: "111 is the NHS urgent advice line. 999 and 112 are emergencies; 101 is non-emergency police." },
  { id: "edu-3", lesson: "education-healthcare", level: "easy",
    q: "Which numbers reach the emergency services in the UK?",
    options: ["999 or 112", "111 or 101", "911 only", "100 or 200"], answer: 0,
    explanation: "Both 999 and 112 are free from any phone and reach police, ambulance, fire and coastguard." },
  { id: "edu-4", lesson: "education-healthcare", level: "medium",
    q: "What does 'free at the point of use' mean for the NHS?",
    options: ["The NHS costs the taxpayer nothing", "You are not charged for treatment when you receive it, because it is funded by taxation", "Only emergencies are free", "Only citizens are treated free"], answer: 1,
    explanation: "Care is based on clinical need, not ability to pay, and is paid for through taxation." },
  { id: "edu-5", lesson: "education-healthcare", level: "easy",
    q: "Who is normally your first point of contact for NHS healthcare?",
    options: ["A hospital consultant", "Your GP", "A pharmacist", "The ambulance service"], answer: 1,
    explanation: "A general practitioner. You need to be registered with a local practice to be referred onward for most care." },
  { id: "edu-6", lesson: "education-healthcare", level: "hard",
    q: "Where are NHS prescriptions free?",
    options: ["Everywhere in the UK", "Scotland, Wales and Northern Ireland", "England only", "Nowhere"], answer: 1,
    explanation: "Free in Scotland, Wales and Northern Ireland; charged in England, with many exemptions." },
  { id: "edu-7", lesson: "education-healthcare", level: "easy",
    q: "What are the main exams taken at 16 in England, Wales and Northern Ireland?",
    options: ["A levels", "GCSEs", "Highers", "Degrees"], answer: 1,
    explanation: "GCSEs. Scotland has National Qualifications instead, and Highers in place of A levels." },
  { id: "edu-8", lesson: "education-healthcare", level: "hard",
    q: "Which are the two oldest universities in the UK?",
    options: ["Oxford and Cambridge", "Edinburgh and Glasgow", "London and Durham", "St Andrews and Aberdeen"], answer: 0,
    explanation: "Oxford and Cambridge. Tuition fees differ across the UK because education is devolved." },
  { id: "edu-9", lesson: "education-healthcare", level: "medium",
    q: "Is misusing the 999 emergency number an offence?",
    options: ["No, it is simply discouraged", "Yes, it is an offence", "Only if repeated", "Only for businesses"], answer: 1,
    explanation: "999 is for a life at risk, serious injury, a crime in progress or a fire. Misusing it is an offence — 111 exists for everything else urgent." },
];

// ── Category model ────────────────────────────────────────────────────────
// Derived from the course rather than declared twice. A lesson added there
// becomes a filterable category here for free, and check-uk-questions fails if
// a question ever names a lesson that does not exist.

export type UkCategory = {
  /** The lesson id — also the value stored in UkQuestion.lesson. */
  id: string;
  title: string;
  /** One of the five official syllabus chapters. */
  chapter: string;
  count: number;
};

export function ukCategories(): UkCategory[] {
  const lessons = lifeInTheUkCourse.lessons ?? [];
  return lessons.map((lesson) => ({
    id: lesson.id,
    title: lesson.title,
    chapter: lesson.section,
    count: UK_QUESTIONS.filter((question) => question.lesson === lesson.id).length,
  }));
}

/** The five official chapters, in the order the course teaches them. */
export function ukChapters(): string[] {
  const seen: string[] = [];
  for (const lesson of lifeInTheUkCourse.lessons ?? []) {
    if (!seen.includes(lesson.section)) seen.push(lesson.section);
  }
  return seen;
}

export function ukQuestionsForLesson(lessonId: string): UkQuestion[] {
  return UK_QUESTIONS.filter((question) => question.lesson === lessonId);
}

export function ukQuestionsForChapter(chapter: string): UkQuestion[] {
  const lessonIds = new Set(
    (lifeInTheUkCourse.lessons ?? []).filter((lesson) => lesson.section === chapter).map((lesson) => lesson.id)
  );
  return UK_QUESTIONS.filter((question) => lessonIds.has(question.lesson));
}

export function ukQuestionById(id: string): UkQuestion | undefined {
  return UK_QUESTIONS.find((question) => question.id === id);
}

export function ukLessonTitle(lessonId: string): string {
  return (lifeInTheUkCourse.lessons ?? []).find((lesson) => lesson.id === lessonId)?.title ?? lessonId;
}
