/**
 * The usage notes in German.
 *
 * Keyed by the English note exactly as the card carries it. A note missing
 * from here shows its English, so this file is filled in batches without any
 * card ever going blank — see usageNotes.ts for how it is loaded and why it
 * is not part of the interface tables.
 *
 * Fourteen thousand notes exist. This holds the ones translated so far, and
 * check-usage-notes prints how far along each language is on every build.
 */
export const USE_DE: Record<string, string> = {
  "Afterwards": "Danach",
  "Agreeing": "Zustimmen",
  "always plural": "immer Plural",
  "Asking for the bill": "Nach der Rechnung fragen",
  "At the till": "An der Kasse",
  "Banter": "Geplänkel",
  "Buying time": "Zeit gewinnen",
  "Casual reply": "Lockere Antwort",
  "Chores": "Hausarbeit",
  "Common complaint": "Häufige Beschwerde",
  "Confirming": "Bestätigen",
  "Consent": "Einverständnis",
  "Consent — always check": "Einverständnis — immer nachfragen",
  "Dating": "Dating",
  "Desire": "Wunsch",
  "Emergency": "Notfall",
  "Emphasis": "Betonung",
  "Enemy info": "Gegnerinfo",
  "Enthusiastic yes": "Begeistertes Ja",
  "Essential": "Unverzichtbar",
  "Everyday slang (Bock haben)": "Alltagsslang (Bock haben)",
  "Family": "Familie",
  "Farewell": "Abschied",
  "Feeling": "Gefühl",
  "Finding help": "Hilfe finden",
  "Flight status update": "Flugstatus",
  "Flirting": "Flirten",
  "Formal": "Förmlich",
  "Gen-Z": "Gen Z",
  "Greeting": "Begrüßung",
  "Gunsmith": "Waffenschmied",
  "In the moment": "Im Moment",
  "Introducing": "Vorstellen",
  "Leaving": "Gehen",
  "Loadout": "Ausrüstung",
  "Making a move": "Den ersten Schritt machen",
  "Making plans": "Pläne machen",
  "Meta": "Meta",
  "Opinion": "Meinung",
  "Ordering food": "Essen bestellen",
  "Plans": "Pläne",
  "Position callout": "Positionsansage",
  "Reacting": "Reagieren",
  "Reassuring": "Beruhigen",
  "Relationship status": "Beziehungsstatus",
  "Reporting a problem": "Ein Problem melden",
  "Request": "Bitte",
  "Routine": "Routine",
  "Scheduling": "Termine",
  "Seasons": "Jahreszeiten",
  "Slang": "Slang",
  "Status callout": "Statusansage",
  "Strong agreement": "Starke Zustimmung",
  "Surprise": "Überraschung",
  "Symptom": "Symptom",
  "Team play": "Teamspiel",
  "Telling time": "Uhrzeit sagen",
  "Texting": "Chatten",
  "Time comment": "Bemerkung zur Zeit",
  "Typical reply": "Typische Antwort",
  "Unlocks": "Freischaltungen",
  "Urgent": "Dringend",
  "Very common leisure activity": "Sehr verbreitete Freizeitbeschäftigung",
  "Weather": "Wetter",
  "Written German too": "Auch im Schriftdeutsch",
};
