/**
 * The usage notes in Polish.
 *
 * Keyed by the English note exactly as the card carries it. A note missing
 * from here shows its English, so this file is filled in batches without any
 * card ever going blank — see usageNotes.ts for how it is loaded and why it
 * is not part of the interface tables.
 *
 * Fourteen thousand notes exist. This holds the ones translated so far, and
 * check-usage-notes prints how far along each language is on every build.
 */
export const USE_PL: Record<string, string> = {
  "'doppelt' — double. 'Menge' is a quantity, and colloquially 'a lot'.": "'doppelt' — podwójnie. 'Menge' to ilość, a potocznie 'dużo'.",
  "'draufschauen' — to look at it. Colloquial and separable.": "'draufschauen' — zerknąć na to. Potoczne i rozdzielnie złożone.",
  "'durch sein' — colloquially done for: soaked, worn out, finished.": "'durch sein' — potocznie skończony: przemoczony, zużyty, wykończony.",
  "'eigentlich' — the casual opener for a serious adult conversation.": "'eigentlich' — swobodny wstęp do poważnej rozmowy dorosłych.",
  "'Elfer' is the casual clip everyone uses in speech": "'Elfer' to swobodny skrót, którego wszyscy używają w mowie",
  "'ewig' — eternally, used casually for 'ages'. 'laden' for loading.": "'ewig' — wiecznie, swobodnie w znaczeniu 'całe wieki'. 'laden' o ładowaniu.",
  "'gar nicht erst' — not even starting. Avoiding the problem entirely.": "'gar nicht erst' — nawet nie zaczynać. Całkowite uniknięcie problemu.",
  "'gläubig' — devout. Said plainly, this ends no friendships in Germany.": "'gläubig' — wierzący. Powiedziane wprost, w Niemczech nie kończy żadnej przyjaźni.",
  "'schlapp' (colloquial) = run-down, drained; 'kaum' = barely.": "'schlapp' (potocznie) = osłabiony, wyczerpany; 'kaum' = ledwo.",
  "A colloquial fixed expression. It is not sexual in this use.": "Utarte wyrażenie potoczne. W tym użyciu nie ma wydźwięku seksualnego.",
  "A common use of sammeln among friends, at work or in a family.": "Częste użycie sammeln wśród przyjaciół, w pracy lub w rodzinie.",
  "A direct warning that a condition or necessary step cannot be skipped.": "Wyraźne ostrzeżenie, że warunku lub koniecznego kroku nie da się pominąć.",
  "A serious accusation, not casual criticism.": "Poważne oskarżenie, nie zdawkowa krytyka.",
  "A standing offer between partners or close friends; warm, no drama.": "Oferta, która zawsze obowiązuje — między partnerami lub bliskimi przyjaciółmi; ciepła, bez dramatu.",
  "A very common informal way to check whether a day suits someone.": "Bardzo częsty, nieformalny sposób sprawdzenia, czy dany dzień komuś pasuje.",
  "Afterwards": "Potem",
  "Agreeing": "Zgadzanie się",
  "also colloquially \"incredibly\": unwahrscheinlich gut": "potocznie także 'niesamowicie': unwahrscheinlich gut",
  "also colloquially \"massively\": tierisch gut": "potocznie także 'strasznie': tierisch gut",
  "always plural": "zawsze w liczbie mnogiej",
  "Asking for the bill": "Prośba o rachunek",
  "At the till": "Przy kasie",
  "auslaufen — leaking out. 'hinüber sein' — colloquially beyond saving.": "auslaufen — wyciekać. 'hinüber sein' — potocznie: nie do uratowania.",
  "Banter": "Przekomarzanie",
  "beraten — advising. 'einen' — the colloquial accusative of man.": "beraten — doradzać. 'einen' — potoczny biernik od man.",
  "Blunt insult, literally a full fencepost. Friends-only register.": "Dosadna obelga, dosłownie cały słupek od płotu. Tylko wśród przyjaciół.",
  "bumming a cigarette; casual, smoker-to-smoker only": "sępienie papierosa; swobodnie, tylko palacz do palacza",
  "Buying time": "Granie na zwłokę",
  "Casual": "Swobodnie",
  "Casual — Ding literally means 'thing'": "Swobodnie — Ding dosłownie znaczy 'rzecz'",
  "Casual — literally 'now we have the salad'": "Swobodnie — dosłownie 'teraz mamy sałatkę'",
  "Casual — literally 'that's not my beer'": "Swobodnie — dosłownie 'to nie moje piwo'",
  "Casual — literally 'you had pig'": "Swobodnie — dosłownie 'miałeś świnię'",
  "Casual agreement": "Swobodna zgoda",
  "Casual check-in mid-explanation.": "Swobodne upewnienie się w środku wyjaśnienia.",
  "casual clipping of 'Prominenter' — everyday word": "swobodny skrót od 'Prominenter' — słowo codzienne",
  "Casual complaint, one hour in. Someone packed too much Brotzeit.": "Swobodne narzekanie po godzinie. Ktoś spakował za dużo Brotzeit.",
  "casual compliment; stehen + dative = to suit someone": "swobodny komplement; stehen + celownik = komuś pasować",
  "Casual date invite (better than formal 'Möchten Sie...')": "Swobodne zaproszenie na randkę (lepsze niż formalne 'Möchten Sie...')",
  "casual Denglisch — 'Ich hab gecodet' is completely normal among devs": "swobodny denglisch — 'Ich hab gecodet' jest wśród programistów zupełnie normalne",
  "Casual directive": "Swobodne polecenie",
  "Casual everyday goodbye — used everywhere in Germany": "Swobodne, codzienne pożegnanie — używane w całych Niemczech",
  "Casual everyday reassurance": "Swobodne, codzienne uspokojenie",
  "Casual for playing video games; in money contexts it means to gamble.": "Swobodnie o graniu w gry wideo; w kontekście pieniędzy oznacza hazard.",
  "Casual goodbye — borrowed from Italian, extremely popular in Germany": "Swobodne pożegnanie — zapożyczone z włoskiego, bardzo popularne w Niemczech",
  "casual gym slang for lifting weights; 'pumpen gehen'": "swobodny slang siłowni o podnoszeniu ciężarów; 'pumpen gehen'",
  "Casual invite": "Swobodne zaproszenie",
  "casual loanword; einkaufen is the German verb": "swobodne zapożyczenie; einkaufen to niemiecki czasownik",
  "Casual opener": "Swobodny wstęp do rozmowy",
  "Casual opener for close friends": "Swobodny wstęp wśród bliskich przyjaciół",
  "Casual opinion": "Swobodna opinia",
  "Casual positive update": "Swobodna, dobra wiadomość",
  "Casual reminiscing; 'was los sein' = something happening.": "Swobodne wspominanie; 'was los sein' = coś się dzieje.",
  "Casual reply": "Swobodna odpowiedź",
  "Casual request": "Swobodna prośba",
  "Casual request to repeat": "Swobodna prośba o powtórzenie",
  "Casual self-intro": "Swobodne przedstawienie się",
  "Casual slang command": "Swobodne, slangowe polecenie",
  "Casual slang farewell": "Swobodne, slangowe pożegnanie",
  "casual spoken; from sich fertig machen = sich zurechtmachen": "swobodna mowa; od sich fertig machen = szykować się",
  "casual spoken; the machen-lassen pattern for anything done at a salon": "swobodna mowa; konstrukcja machen-lassen dla wszystkiego, co robi się w salonie",
  "casual, admiring; 'definiert' = lean and cut, more technical": "swobodnie, z podziwem; 'definiert' = wyrzeźbiony, bardziej fachowo",
  "Casual, teasing — literally 'do you have tomatoes on your eyes?'": "Swobodnie, żartobliwie — dosłownie 'masz pomidory na oczach?'",
  "Casual, to companions. Famous last words on any hike.": "Swobodnie, do towarzyszy. Słynne ostatnie słowa na każdej wędrówce.",
  "Casual, wry — literally 'life is no pony farm'": "Swobodnie, z przekąsem — dosłownie 'życie to nie kucykowa farma'",
  "casual, younger speakers; Hautpflege is the more formal word": "swobodnie, raczej młodsi mówiący; Hautpflege to słowo bardziej oficjalne",
  "casual; 'platt' = wiped out, works for any exhaustion": "swobodnie; 'platt' = wykończony, pasuje do każdego wyczerpania",
  "casual; 'Proteinshake' works too": "swobodnie; 'Proteinshake' też działa",
  "casual; 'sich etwas ziehen' = to pull a muscle": "swobodnie; 'sich etwas ziehen' = naciągnąć sobie mięsień",
  "Casual; ackern makes the work sound tiring or relentless.": "Swobodnie; ackern sprawia, że praca brzmi na męczącą i nieustanną.",
  "Casual; adults admit it with a grin": "Swobodnie; dorośli przyznają się do tego z uśmiechem",
  "casual; literally also to plough a field": "swobodnie; dosłownie także orać pole",
  "casual; the question everyone asks": "swobodnie; pytanie, które zadają wszyscy",
  "casual; the standard (optimistic) answer": "swobodnie; standardowa (optymistyczna) odpowiedź",
  "Casual; the way adults confess it with a grin.": "Swobodnie; tak dorośli przyznają się do tego z uśmiechem.",
  "casual: kicken gehen = to go and play football": "swobodnie: kicken gehen = iść pograć w piłkę",
  "Casual. 'Sich etwas holen' = to catch/get something (sunburn, a cold).": "Swobodnie. 'Sich etwas holen' = złapać coś (oparzenie słoneczne, przeziębienie).",
  "casually clipped to 'der Elfer'": "potocznie skracane do 'der Elfer'",
  "Chores": "Obowiązki domowe",
  "close friends only — sharing a cigarette or vape": "tylko wśród bliskich przyjaciół — dzielenie się papierosem lub e-papierosem",
  "coden is casual Denglisch; completely normal in the du-form dev crowd.": "coden to swobodny denglisch; zupełnie normalny w środowisku programistów na ty.",
  "Colloquial (Kopfnuss = headbutt/noogie)": "Potocznie (Kopfnuss = uderzenie głową lub prztyczek w głowę)",
  "Colloquial and strong; verbal or psychological cruelty": "Potoczne i mocne; okrucieństwo słowne lub psychiczne",
  "Colloquial but harmless — safe with colleagues and family.": "Potoczne, ale niegroźne — bezpieczne wśród współpracowników i rodziny.",
  "Colloquial but serious; 'zu dritt' = three of them together.": "Potoczne, ale poważne; 'zu dritt' = we trójkę.",
  "Colloquial combo of Ja + Nein": "Potoczne połączenie Ja + Nein",
  "colloquial intensifier: mächtig stolz = mighty proud": "potoczny wzmacniacz: mächtig stolz = ogromnie dumny",
  "Colloquial shortcut": "Potoczny skrót",
  "colloquial, what children do in sand; graben is neutral": "potocznie, to, co dzieci robią w piasku; graben jest neutralne",
  "colloquial; invariable: ein super Film": "potocznie; nieodmienne: ein super Film",
  "colloquially also snappy, punchy (UI, prose, deadlines)": "potocznie także zwięzły, dosadny (interfejsy, teksty, terminy)",
  "colloquially shortened to 'das Gespräch'": "potocznie skracane do 'das Gespräch'",
  "common and informal; can describe a person, idea or situation": "częste i nieformalne; może opisywać osobę, pomysł lub sytuację",
  "Common complaint": "Częsta skarga",
  "Common slang reaction": "Częsta reakcja w slangu",
  "Common slang reaction to bad news — mies = lousy, shabby": "Częsta slangowa reakcja na złe wieści — mies = kiepski, marny",
  "Confirming": "Potwierdzanie",
  "Consent": "Zgoda",
  "Consent — always check": "Zgoda — zawsze pytaj",
  "das Bügeleisen — the iron. The warning every household repeats.": "das Bügeleisen — żelazko. Ostrzeżenie powtarzane w każdym domu.",
  "das Halbjahreszeugnis — the February report. The early warning system.": "das Halbjahreszeugnis — świadectwo lutowe. System wczesnego ostrzegania.",
  "Dating": "Randki",
  "der Strafzettel, colloquially das Knöllchen = parking ticket": "der Strafzettel, potocznie das Knöllchen = mandat za parkowanie",
  "Desire": "Pragnienie",
  "die Lawine — the avalanche. The warning is not decorative.": "die Lawine — lawina. To ostrzeżenie nie jest ozdobą.",
  "eh = anyway / in any case (colloquial 'ohnehin')": "eh = i tak / tak czy owak (potocznie 'ohnehin')",
  "Emergency": "Nagły wypadek",
  "Emphasis": "Podkreślenie",
  "Emphatic casual yes": "Dobitne, swobodne tak",
  "Enemy info": "Informacja o wrogu",
  "Enthusiastic yes": "Entuzjastyczne tak",
  "Essential": "Niezbędne",
  "everyday casual word; also means the stubbed-out butt": "codzienne, swobodne słowo; oznacza też zgaszony niedopałek",
  "Everyday colloquial spelling of nichts": "Codzienna, potoczna pisownia nichts",
  "Everyday connection method (slang 'schreib mir')": "Codzienny sposób na kontakt (slangowo 'schreib mir')",
  "Everyday slang (Bock haben)": "Codzienny slang (Bock haben)",
  "Everyday slang (spendieren = to treat)": "Codzienny slang (spendieren = postawić, zafundować)",
  "Facharzt = specialist; colloquially also \"einen Termin ausmachen\"": "Facharzt = lekarz specjalista; potocznie także 'einen Termin ausmachen'",
  "Falschparken = illegal/incorrect parking": "Falschparken = parkowanie niezgodne z przepisami",
  "Family": "Rodzina",
  "Famous last words — friends will quote it back at you for months.": "Słynne ostatnie słowa — przyjaciele będą ci to cytować przez miesiące.",
  "Farewell": "Pożegnanie",
  "Feeling": "Uczucie",
  "fett = huge (colloquial intensifier); standard dev talk, not rude.": "fett = ogromny (potoczny wzmacniacz); zwykły żargon programistów, nie jest niegrzeczny.",
  "Finding help": "Szukanie pomocy",
  "Fixed casual set expression; already short, so no further clipping.": "Utarte, swobodne wyrażenie; już krótkie, więc bez dalszego skracania.",
  "Flight status update": "Status lotu",
  "Flirting": "Flirtowanie",
  "Formal": "Formalne",
  "Frustrated, to friends. 'schon wieder' carries the job-hunt fatigue.": "Sfrustrowane, wśród przyjaciół. 'schon wieder' niesie zmęczenie szukaniem pracy.",
  "Gen-Z": "Gen Z",
  "Greeting": "Powitanie",
  "Grufti = colloquial for goth (from Gruft = tomb/crypt)": "Grufti = potocznie o gotach (od Gruft = krypta, grobowiec)",
  "Gunsmith": "Rusznikarz",
  "half-joking quitter's line; 'ich schwör' is casual spoken German": "na wpół żartobliwa deklaracja rzucenia czegoś; 'ich schwör' to swobodna mowa niemiecka",
  "idiomatic, informal": "idiomatyczne, nieformalne",
  "in casual speech often shortened to was: Hast du was gehört?": "w swobodnej mowie często skracane do was: Hast du was gehört?",
  "In the moment": "W tej chwili",
  "Informal": "Nieformalne",
  "Informal — friends only": "Nieformalne — tylko wśród przyjaciół",
  "Informal — the spoken contraction you'll usually hear": "Nieformalne — mówiona forma ściągnięta, którą zwykle usłyszysz",
  "Informal — to strangers or staff say: Sprechen Sie Englisch?": "Nieformalne — do obcych lub obsługi mów: Sprechen Sie Englisch?",
  "Informal and rude: jemandem den Stinkefinger zeigen.": "Nieformalne i niegrzeczne: jemandem den Stinkefinger zeigen.",
  "informal loan from English; das Okay – the go-ahead": "nieformalne zapożyczenie z angielskiego; das Okay – zielone światło",
  "Informal reply — with Sie say: Und Ihnen?": "Nieformalna odpowiedź — przy Sie mówi się: Und Ihnen?",
  "Informal term for a friend": "Nieformalne określenie przyjaciela",
  "informal, e.g. eine brenzlige Situation": "nieformalne, np. eine brenzlige Situation",
  "Introducing": "Przedstawianie się",
  "Knast = colloquial for jail/prison": "Knast = potocznie o więzieniu, pace",
  "Komm doch mal vorbei! — the casual open invitation.": "Komm doch mal vorbei! — swobodne, otwarte zaproszenie.",
  "Leaving": "Wychodzenie",
  "Loadout": "Wyposażenie",
  "Logisch! is also a casual \"obviously\"": "Logisch! to także swobodne 'jasne'",
  "Making a move": "Pierwszy krok",
  "Making plans": "Planowanie",
  "medium insult — banter-safe among close friends with the right tone": "obelga średniego kalibru — w żartach wśród bliskich przyjaciół, przy właściwym tonie",
  "medium-strong — banter only with thick-skinned close friends": "dość mocne — tylko w żartach wśród bliskich przyjaciół z grubą skórą",
  "Meta": "Meta",
  "Opinion": "Opinia",
  "Ordering food": "Zamawianie jedzenia",
  "Plans": "Plany",
  "Position callout": "Podanie pozycji",
  "Reacting": "Reagowanie",
  "Reassuring": "Uspokajanie",
  "Relationship status": "Status związku",
  "Reporting a problem": "Zgłaszanie problemu",
  "Request": "Prośba",
  "Routine": "Rutyna",
  "Scheduling": "Umawianie terminów",
  "Seasons": "Pory roku",
  "Slang": "Slang",
  "Status callout": "Podanie statusu",
  "Strong agreement": "Mocna zgoda",
  "Surprise": "Zaskoczenie",
  "Symptom": "Objaw",
  "Team play": "Gra zespołowa",
  "Telling time": "Podawanie godziny",
  "Texting": "Pisanie wiadomości",
  "Time comment": "Uwaga o czasie",
  "Typical reply": "Typowa odpowiedź",
  "Unlocks": "Odblokowania",
  "Urgent": "Pilne",
  "Very common leisure activity": "Bardzo popularne zajęcie w czasie wolnym",
  "Weather": "Pogoda",
  "Written German too": "Także w piśmie",
};
