/**
 * The usage notes in German.
 *
 * Keyed by the English note exactly as the card carries it. A note missing
 * from here shows its English, so this file is filled in batches without any
 * card ever going blank — see usageNotes.ts for how it is loaded and why it
 * is not part of the interface tables.
 *
 * Fourteen thousand notes exist. This holds the ones translated so far, and
 * check-usage-notes prints how far along each language is on every build.
 */
export const USE_DE: Record<string, string> = {
  "'abschleppen' — to tow. Colloquially it also means pulling someone in a bar.": "'abschleppen' — wegschleppen. Umgangssprachlich heißt es auch, jemanden in einer Bar aufzureißen.",
  "'angesagt sein' — forecast, announced. Also slang for what's currently trendy.": "'angesagt sein' — vorhergesagt, angekündigt. Im Slang auch: gerade im Trend.",
  "'auf etwas stehen' — to be into something. Informal, current, and used constantly.": "'auf etwas stehen' — etwas mögen. Informell, aktuell und ständig im Gebrauch.",
  "'bedeuten' for meaning. 'Was heißt das?' is the more casual version and just as correct.": "'bedeuten' für die Bedeutung. 'Was heißt das?' ist die lockerere Fassung und genauso richtig.",
  "'Das Match' — loan for a full competitive game; 'ist Schluss' = are we done. Casual.": "'Das Match' — Lehnwort für ein ganzes Wettkampfspiel; 'ist Schluss' = ist Feierabend. Locker.",
  "'davon' avoids repeating the product name after pointing or asking a question about it.": "'davon' erspart es, den Produktnamen zu wiederholen, nachdem man darauf gezeigt oder danach gefragt hat.",
  "'davon' refers to an amount of the thing already being discussed and avoids repeating its name.": "'davon' bezieht sich auf eine Menge der schon besprochenen Sache und erspart die Wiederholung des Namens.",
  "'Der Hammer' = the standard casual superlative for events. Informal, all ages under about 50.": "'Der Hammer' = der übliche lockere Superlativ für Ereignisse. Informell, alle Altersgruppen unter etwa 50.",
  "'Der Ping' — English loan, no alternative. 'übel' is youth slang for 'terrible'.": "'Der Ping' — englisches Lehnwort ohne Alternative. 'übel' ist Jugendslang für 'schrecklich'.",
  "'doppelt' — double. 'Menge' is a quantity, and colloquially 'a lot'.": "'doppelt' — zweifach. 'Menge' ist eine Quantität und umgangssprachlich 'viel'.",
  "'dran sein' — to be next in turn. Compact, informal and used constantly.": "'dran sein' — als Nächster an der Reihe sein. Knapp, informell und ständig im Gebrauch.",
  "'draufschauen' — to look at it. Colloquial and separable.": "'draufschauen' — einen Blick darauf werfen. Umgangssprachlich und trennbar.",
  "'Du hast einen guten Musikgeschmack' is a real compliment between friends or on a date.": "'Du hast einen guten Musikgeschmack' ist ein echtes Kompliment unter Freunden oder beim Date.",
  "'durch sein' — colloquially done for: soaked, worn out, finished.": "'durch sein' — umgangssprachlich erledigt: durchnässt, abgenutzt, am Ende.",
  "'eigentlich' — the casual opener for a serious adult conversation.": "'eigentlich' — der lockere Einstieg in ein ernstes Gespräch unter Erwachsenen.",
  "'Elfer' is the casual clip everyone uses in speech": "'Elfer' ist die lockere Kurzform, die alle sprechen",
  "'ewig' — eternally, used casually for 'ages'. 'laden' for loading.": "'ewig' — für immer, locker gebraucht für 'ewig lange'. 'laden' fürs Laden.",
  "'frei Schnauze' — literally free snout: no recipe, pure instinct. Wonderfully casual.": "'frei Schnauze' — wörtlich freie Schnauze: kein Rezept, reines Gefühl. Herrlich locker.",
  "'gar nicht erst' — not even starting. Avoiding the problem entirely.": "'gar nicht erst' — erst gar nicht anfangen. Das Problem ganz vermeiden.",
  "'glatt' — slippery with ice. The winter warning Germans text each other.": "'glatt' — vereist und rutschig. Die Winterwarnung, die Deutsche einander schreiben.",
  "'gläubig' — devout. Said plainly, this ends no friendships in Germany.": "'gläubig' — fromm. Nüchtern gesagt beendet das in Deutschland keine Freundschaft.",
  "'gucken' is the casual everyday verb (north/central); the south says 'schauen'": "'gucken' ist das lockere Alltagsverb (Norden/Mitte); der Süden sagt 'schauen'",
  "'halbe-halbe' is common informal German for dividing something into two equal parts.": "'halbe-halbe' ist geläufiges informelles Deutsch dafür, etwas in zwei gleiche Teile zu teilen.",
  "'hinkriegen' — to manage or pull something off. Informal, warm and extremely common.": "'hinkriegen' — etwas schaffen oder hinbekommen. Informell, warm und äußerst geläufig.",
  "'jeder zahlt seins' — the German default among friends. No awkwardness; it's the system.": "'jeder zahlt seins' — der deutsche Normalfall unter Freunden. Nichts Peinliches daran; so läuft es.",
  "'Jetzt reicht's' is the short version, and the last warning before a row.": "'Jetzt reicht's' ist die Kurzfassung — und die letzte Warnung vor dem Streit.",
  "'Kein Thema' — not a topic: it doesn't even need discussing. Friendship in two words.": "'Kein Thema' — wörtlich kein Gesprächsgegenstand: darüber muss man gar nicht reden. Freundschaft in zwei Wörtern.",
  "'mal' makes the command sound casual; use 'in die Ecke' when directing light into it.": "'mal' lässt die Aufforderung locker klingen; 'in die Ecke' nimmt man, wenn man Licht hineinlenkt.",
  "'mal' softens the imperative into a casual request; masculine object is 'deinen Benutzernamen'.": "'mal' macht aus dem Imperativ eine lockere Bitte; das maskuline Objekt heißt 'deinen Benutzernamen'.",
  "'mal' turns an offer into something casual. Two seconds, no commitment.": "'mal' macht aus dem Angebot etwas Lockeres. Zwei Sekunden, keine Verpflichtung.",
  "'mitnehmen' is separable; in the informal imperative, 'mit' lands at the end.": "'mitnehmen' ist trennbar; im informellen Imperativ landet 'mit' am Ende.",
  "'Pass auf!' is the fastest warning; separable 'aufpassen' becomes 'pass ... auf'.": "'Pass auf!' ist die schnellste Warnung; das trennbare 'aufpassen' wird zu 'pass ... auf'.",
  "'rausfliegen' — from the fuse pack, here about a back. Colloquial and instantly understood.": "'rausfliegen' — aus dem Sicherungs-Paket, hier über einen Rücken. Umgangssprachlich und sofort verstanden.",
  "'schauen' or 'gucken' — gucken is more casual. No preposition before the platform.": "'schauen' oder 'gucken' — gucken ist lockerer. Vor der Plattform steht keine Präposition.",
  "'schlapp' (colloquial) = run-down, drained; 'kaum' = barely.": "'schlapp' (umgangssprachlich) = kraftlos, ausgelaugt; 'kaum' = fast gar nicht.",
  "'sicherheitshalber' explains that you are checking to avoid an unnecessary mistake.": "'sicherheitshalber' erklärt, dass man nachschaut, um einen unnötigen Fehler zu vermeiden.",
  "'sportlich' — sporty, and also 'smart-casual' about clothes. Both are common.": "'sportlich' — sportlich, bei Kleidung auch leger-elegant. Beides ist geläufig.",
  "'total' as an intensifier is thoroughly spoken German and slightly informal.": "'total' als Verstärker ist durch und durch gesprochenes Deutsch und leicht informell.",
  "'unterschiedlich' — differing. Germans use it constantly to avoid overgeneralising.": "'unterschiedlich' — verschieden. Deutsche gebrauchen es ständig, um nicht zu verallgemeinern.",
  "'was trinken gehen' — the standard invitation. Casual, open-ended, no commitment implied.": "'was trinken gehen' — die Standardeinladung. Locker, offen, ohne jede Verpflichtung.",
  "'wegmachen' colloquially for putting something aside. 'mal' softens the announcement.": "'wegmachen' umgangssprachlich dafür, etwas wegzuräumen. 'mal' macht die Ankündigung weicher.",
  "'Wie hoch' for amounts of money. A completely normal question between German friends.": "'Wie hoch' für Geldbeträge. Eine völlig normale Frage unter deutschen Freunden.",
  "'wieder drauf haben' — colloquial and compact. Bike chains come off constantly.": "'wieder drauf haben' — umgangssprachlich und knapp. Fahrradketten springen ständig ab.",
  "'Wofür' is the normal neutral form; 'für was' is regional or very casual.": "'Wofür' ist die normale neutrale Form; 'für was' ist regional oder sehr locker.",
  "'Zeit mitbringen' — the honest warning. Open hours mean open-ended waiting.": "'Zeit mitbringen' — die ehrliche Warnung. Offene Sprechzeiten bedeuten offenes Warten.",
  "A casual purpose question when someone has an object, tool, file or unusual plan.": "Eine lockere Frage nach dem Zweck, wenn jemand einen Gegenstand, ein Werkzeug, eine Datei oder einen ungewöhnlichen Plan hat.",
  "A colloquial fixed expression. It is not sexual in this use.": "Eine feste umgangssprachliche Wendung. In dieser Verwendung nicht sexuell gemeint.",
  "A common informal response to disappointing news or an annoying problem.": "Eine geläufige informelle Reaktion auf enttäuschende Nachrichten oder ein ärgerliches Problem.",
  "A common use of sammeln among friends, at work or in a family.": "Eine geläufige Verwendung von sammeln unter Freunden, bei der Arbeit oder in der Familie.",
  "A considerate response to bad news when a casual reaction would feel too light.": "Eine rücksichtsvolle Antwort auf schlechte Nachrichten, wenn eine lockere Reaktion zu leicht wirken würde.",
  "A direct warning that a condition or necessary step cannot be skipped.": "Eine deutliche Warnung, dass eine Bedingung oder ein nötiger Schritt nicht übersprungen werden kann.",
  "A natural follow-up after meeting two friends. 'seid ihr' addresses both people together.": "Eine natürliche Anschlussfrage, wenn man zwei Freunde trifft. 'seid ihr' spricht beide zusammen an.",
  "A normal informal request for a very short wait. Add 'bitte' when you want it to sound softer.": "Eine normale informelle Bitte um ganz kurzes Warten. Mit 'bitte' klingt sie weicher.",
  "A practical check that helps the group avoid stopping again once the task has begun.": "Eine praktische Rückfrage, damit die Gruppe nicht noch einmal anhalten muss, wenn es losgegangen ist.",
  "A serious accusation, not casual criticism.": "Ein schwerer Vorwurf, keine beiläufige Kritik.",
  "A standard informal request. The favour itself normally follows immediately.": "Eine übliche informelle Bitte. Der eigentliche Gefallen folgt normalerweise sofort.",
  "A standard Monday small-talk question with friends, classmates and colleagues you know.": "Die übliche Montags-Small-Talk-Frage unter Freunden, Mitschülern und bekannten Kollegen.",
  "A standing offer between partners or close friends; warm, no drama.": "Ein Angebot, das immer gilt — unter Partnern oder engen Freunden; warm, ohne Drama.",
  "A very common informal way to check whether a day suits someone.": "Eine sehr geläufige informelle Art zu fragen, ob ein Tag jemandem passt.",
  "abgefahren — driven off, worn. Also slang for 'amazing'; the tyre meaning is older.": "abgefahren — abgenutzt, heruntergefahren. Im Slang auch 'irre gut'; die Reifenbedeutung ist älter.",
  "Achtung! is the warning word; die Ampel = the traffic light, always feminine.": "Achtung! ist das Warnwort; die Ampel = die Verkehrsampel, immer feminin.",
  "Afterwards": "Danach",
  "Agreeing": "Zustimmen",
  "Allotment neighbours — advisors, rivals and friends across one fence. Mostly all three.": "Nachbarn in der Kleingartenanlage — Ratgeber, Rivalen und Freunde über einen Zaun hinweg. Meist alles drei.",
  "also colloquially \"incredibly\": unwahrscheinlich gut": "umgangssprachlich auch 'unglaublich': unwahrscheinlich gut",
  "also colloquially \"massively\": tierisch gut": "umgangssprachlich auch 'enorm': tierisch gut",
  "always plural": "immer Plural",
  "An informal reaction to a plan failing, something breaking or another everyday setback.": "Eine informelle Reaktion darauf, dass ein Plan scheitert, etwas kaputtgeht oder der Alltag dazwischenkommt.",
  "Asking for the bill": "Nach der Rechnung fragen",
  "At the table, informal. One guest: 'Greif zu!' Signals the eating may begin.": "Am Tisch, informell. Bei einem Gast: 'Greif zu!' Es signalisiert, dass gegessen werden darf.",
  "At the till": "An der Kasse",
  "aufblasen — inflating. 'Hilf mir mal' — the casual recruiting of bystanders.": "aufblasen — aufpumpen. 'Hilf mir mal' — das lockere Einspannen von Umstehenden.",
  "aufdrängen — pressing something on someone. The warning before every market stroll.": "aufdrängen — jemandem etwas aufnötigen. Die Warnung vor jedem Marktbummel.",
  "aufziehen — a storm pulling up. denn delivers the warning in plain word order.": "aufziehen — ein Gewitter zieht herauf. denn bringt die Warnung in schlichter Wortstellung.",
  "auslaufen — leaking out. 'hinüber sein' — colloquially beyond saving.": "auslaufen — herauslaufen. 'hinüber sein' — umgangssprachlich nicht mehr zu retten.",
  "Banter": "Geplänkel",
  "beraten — advising. 'einen' — the colloquial accusative of man.": "beraten — Rat geben. 'einen' — der umgangssprachliche Akkusativ von man.",
  "Between friends: Kannst du mir zehn Euro borgen? Standard German prefers leihen.": "Unter Freunden: Kannst du mir zehn Euro borgen? Das Standarddeutsch bevorzugt leihen.",
  "Blunt but completely normal between partners and friends — German directness in action": "Direkt, aber unter Partnern und Freunden völlig normal — deutsche Direktheit in Aktion",
  "Blunt insult, literally a full fencepost. Friends-only register.": "Derbe Beleidigung, wörtlich ein ganzer Zaunpfosten. Nur unter Freunden.",
  "borgen — the casual borrow-lend verb. die Leiter migrates between households like a shared pet.": "borgen — das lockere Verb fürs Leihen. Die Leiter wandert zwischen Haushalten wie ein geteiltes Haustier.",
  "bumming a cigarette; casual, smoker-to-smoker only": "eine Zigarette schnorren; locker, nur von Raucher zu Raucher",
  "Buying time": "Zeit gewinnen",
  "Casual": "Locker",
  "Casual — Ding literally means 'thing'": "Locker — Ding heißt wörtlich 'Sache'",
  "Casual — literally 'now we have the salad'": "Locker — wörtlich 'jetzt haben wir den Salat'",
  "Casual — literally 'that's not my beer'": "Locker — wörtlich 'das ist nicht mein Bier'",
  "Casual — literally 'you had pig'": "Locker — wörtlich 'du hast Schwein gehabt'",
  "Casual agreement": "Lockere Zustimmung",
  "Casual and dramatic; often frustration rather than literal loss of control.": "Locker und dramatisch; meist Frust statt echtem Kontrollverlust.",
  "Casual check-in mid-explanation.": "Lockere Rückfrage mitten in einer Erklärung.",
  "casual clipping of 'Prominenter' — everyday word": "lockere Kurzform von 'Prominenter' — Alltagswort",
  "Casual complaint, one hour in. Someone packed too much Brotzeit.": "Lockere Beschwerde nach einer Stunde. Jemand hat zu viel Brotzeit eingepackt.",
  "casual compliment; stehen + dative = to suit someone": "lockeres Kompliment; stehen + Dativ = jemandem gut zu Gesicht stehen",
  "Casual date invite (better than formal 'Möchten Sie...')": "Lockere Verabredung (besser als das förmliche 'Möchten Sie...')",
  "Casual dating vocabulary with friends. The verb is fully germanized: ghosten, geghostet.": "Lockerer Dating-Wortschatz unter Freunden. Das Verb ist voll eingedeutscht: ghosten, geghostet.",
  "casual Denglisch — 'Ich hab gecodet' is completely normal among devs": "lockeres Denglisch — 'Ich hab gecodet' ist unter Entwicklern völlig normal",
  "Casual directive": "Lockere Aufforderung",
  "Casual everyday goodbye — used everywhere in Germany": "Lockerer Alltagsabschied — überall in Deutschland üblich",
  "Casual everyday reassurance": "Lockere Beruhigung im Alltag",
  "Casual favour between friends (du). 'drüberschauen' = give it a quick once-over.": "Lockerer Gefallen unter Freunden (du). 'drüberschauen' = kurz drüberlesen.",
  "Casual for playing video games; in money contexts it means to gamble.": "Locker fürs Computerspielen; beim Geld heißt es glücksspielen.",
  "Casual goodbye — borrowed from Italian, extremely popular in Germany": "Lockerer Abschied — aus dem Italienischen entlehnt, in Deutschland sehr beliebt",
  "casual gym slang for lifting weights; 'pumpen gehen'": "lockerer Gym-Slang fürs Gewichtheben; 'pumpen gehen'",
  "Casual imperative 'Investier' is common spoken German; full written form is 'Investiere'.": "Der lockere Imperativ 'Investier' ist geläufiges gesprochenes Deutsch; die volle Schriftform lautet 'Investiere'.",
  "Casual imperative 'Setz' is short for 'Setze'; 'am' contracts dative 'an dem'.": "Der lockere Imperativ 'Setz' ist die Kurzform von 'Setze'; 'am' zieht den Dativ 'an dem' zusammen.",
  "Casual invite": "Lockere Einladung",
  "Casual kitchen-table economics; sich lohnen = to be worth it — very high-frequency verb": "Lockere Küchentisch-Ökonomie; sich lohnen = sich rentieren — ein sehr häufiges Verb",
  "casual loanword; einkaufen is the German verb": "lockeres Lehnwort; einkaufen ist das deutsche Verb",
  "Casual opener": "Lockerer Gesprächseinstieg",
  "Casual opener for close friends": "Lockerer Einstieg unter engen Freunden",
  "Casual opinion": "Lockere Meinungsäußerung",
  "Casual positive update": "Lockere gute Nachricht zwischendurch",
  "Casual register inside student life; durcharbeiten = work through without a break.": "Lockeres Register aus dem Studentenleben; durcharbeiten = ohne Unterbrechung weiterarbeiten.",
  "Casual reminiscing; 'was los sein' = something happening.": "Lockeres Schwelgen in Erinnerungen; 'was los sein' = es ist etwas los.",
  "Casual reply": "Lockere Antwort",
  "Casual request": "Lockere Bitte",
  "Casual request to repeat": "Lockere Bitte um Wiederholung",
  "Casual self-intro": "Lockere Vorstellung der eigenen Person",
  "Casual slang command": "Lockere Slang-Aufforderung",
  "Casual slang farewell": "Lockerer Slang-Abschied",
  "Casual spoken imperative 'Markier' is common; the tool follows dative 'mit einem Bleistift'.": "Der lockere gesprochene Imperativ 'Markier' ist geläufig; das Werkzeug folgt im Dativ 'mit einem Bleistift'.",
  "casual spoken; from sich fertig machen = sich zurechtmachen": "lockere gesprochene Sprache; von sich fertig machen = sich zurechtmachen",
  "casual spoken; the machen-lassen pattern for anything done at a salon": "lockere gesprochene Sprache; das machen-lassen-Muster für alles, was im Salon gemacht wird",
  "casual, admiring; 'definiert' = lean and cut, more technical": "locker und bewundernd; 'definiert' = schlank und muskulös, eher fachlich",
  "Casual, enthusiastic. 'Der Wahnsinn' is the go-to superlative among friends.": "Locker und begeistert. 'Der Wahnsinn' ist der Standard-Superlativ unter Freunden.",
  "casual, everyday; der Lidstrich is the German word, Eyeliner is what people say": "locker, alltäglich; der Lidstrich ist das deutsche Wort, Eyeliner sagen die Leute",
  "Casual, relieved-triumphant, to friends. 'überstehen' = to survive something unpleasant.": "Locker, erleichtert-triumphierend, unter Freunden. 'überstehen' = etwas Unangenehmes durchstehen.",
  "Casual, teasing — literally 'do you have tomatoes on your eyes?'": "Locker und neckend — wörtlich 'hast du Tomaten auf den Augen?'",
  "Casual, to companions. Famous last words on any hike.": "Locker, an die Begleitung. Berühmte letzte Worte auf jeder Wanderung.",
  "Casual, to one person (du) — group: Lasst uns anfangen; formal: Fangen wir an": "Locker, an eine Person (du) — Gruppe: Lasst uns anfangen; förmlich: Fangen wir an",
  "Casual, universal. The standard excuse to step outside — nobody questions frische Luft.": "Locker, überall verständlich. Die Standardausrede, um nach draußen zu gehen — frische Luft hinterfragt niemand.",
  "Casual, wry — literally 'life is no pony farm'": "Locker und trocken — wörtlich 'das Leben ist kein Ponyhof'",
  "casual, younger speakers; Hautpflege is the more formal word": "locker, eher jüngere Sprecher; Hautpflege ist das förmlichere Wort",
  "Casual; 'die Pause' is the break, 'der Pausenhof' the yard it happens on.": "Locker; 'die Pause' ist die Unterbrechung, 'der Pausenhof' der Hof, auf dem sie stattfindet.",
  "casual; 'platt' = wiped out, works for any exhaustion": "locker; 'platt' = völlig fertig, passt für jede Erschöpfung",
  "casual; 'Proteinshake' works too": "locker; 'Proteinshake' geht auch",
  "casual; 'pumpen gehen' marks you as a weights person, not a treadmill person": "locker; 'pumpen gehen' weist dich als Hantel-Typ aus, nicht als Laufband-Typ",
  "casual; 'sich etwas ziehen' = to pull a muscle": "locker; 'sich etwas ziehen' = sich einen Muskel zerren",
  "Casual; ackern makes the work sound tiring or relentless.": "Locker; ackern lässt die Arbeit anstrengend und unerbittlich klingen.",
  "Casual; adults admit it with a grin": "Locker; Erwachsene geben es grinsend zu",
  "casual; literally also to plough a field": "locker; wörtlich auch einen Acker pflügen",
  "casual; stechen lassen (literally 'have it pricked') is the idiomatic verb for tattoos": "locker; stechen lassen — wörtlich mit der Nadel stechen lassen — ist das idiomatische Verb für Tattoos",
  "casual; the question everyone asks": "locker; die Frage, die alle stellen",
  "casual; the standard (optimistic) answer": "locker; die übliche (optimistische) Antwort",
  "Casual; the way adults confess it with a grin.": "Locker; so gestehen Erwachsene es grinsend.",
  "casual: kicken gehen = to go and play football": "locker: kicken gehen = Fußball spielen gehen",
  "Casual. 'Baden gehen' = swim outdoors (lake, sea); 'schwimmen gehen' leans towards the pool.": "Locker. 'Baden gehen' = draußen schwimmen (See, Meer); 'schwimmen gehen' zielt eher aufs Schwimmbad.",
  "Casual. 'Eine Runde drehen' = do a loop; works for walks, bike rides or a quick drive.": "Locker. 'Eine Runde drehen' = eine Runde machen; passt für Spaziergänge, Radtouren oder eine kurze Fahrt.",
  "Casual. 'Sich etwas holen' = to catch/get something (sunburn, a cold).": "Locker. 'Sich etwas holen' = sich etwas zuziehen (Sonnenbrand, Erkältung).",
  "casually clipped to 'der Elfer'": "umgangssprachlich verkürzt zu 'der Elfer'",
  "Chores": "Hausarbeit",
  "close friends only — sharing a cigarette or vape": "nur unter engen Freunden — eine Zigarette oder Vape teilen",
  "Coarse and common among friends. It can sound confrontational when said angrily.": "Derb und unter Freunden geläufig. Wütend gesagt kann es konfrontativ klingen.",
  "Coarse-casual — 'forget it, who cares'. Banter-safe among friends; not for formal company.": "Derb-locker — 'vergiss es, wen kümmert's'. Unter Freunden als Spaß okay; nicht in förmlicher Runde.",
  "coden is casual Denglisch; completely normal in the du-form dev crowd.": "coden ist lockeres Denglisch; in der Du-Entwicklerszene völlig normal.",
  "Colloquial (Kopfnuss = headbutt/noogie)": "Umgangssprachlich (Kopfnuss = Stoß mit dem Kopf bzw. Klaps auf den Kopf)",
  "Colloquial and strong; covers verbal and psychological cruelty, not just physical.": "Umgangssprachlich und heftig; meint verbale und seelische Grausamkeit, nicht nur körperliche.",
  "Colloquial and strong; verbal or psychological cruelty": "Umgangssprachlich und heftig; verbale oder seelische Grausamkeit",
  "colloquial anglicism (Duden-listed); marketing and social media register": "umgangssprachlicher Anglizismus (im Duden verzeichnet); Register aus Marketing und sozialen Medien",
  "Colloquial but harmless — safe with colleagues and family.": "Umgangssprachlich, aber harmlos — bei Kollegen und Familie unbedenklich.",
  "Colloquial but serious; 'zu dritt' = three of them together.": "Umgangssprachlich, aber ernst; 'zu dritt' = drei zusammen.",
  "Colloquial combo of Ja + Nein": "Umgangssprachliche Mischung aus Ja + Nein",
  "colloquial intensifier: mächtig stolz = mighty proud": "umgangssprachlicher Verstärker: mächtig stolz = sehr stolz",
  "Colloquial short form of herauskommen; also used of films, products or models being released.": "Umgangssprachliche Kurzform von herauskommen; auch für Filme, Produkte oder Modelle, die erscheinen.",
  "Colloquial shortcut": "Umgangssprachliche Kurzform",
  "Colloquial, mild — gasped mid-laughter or typed in chats. Friends, family, relaxed colleagues.": "Umgangssprachlich, mild — mitten im Lachen hervorgestoßen oder in den Chat getippt. Freunde, Familie, entspannte Kollegen.",
  "colloquial, what children do in sand; graben is neutral": "umgangssprachlich, was Kinder im Sand tun; graben ist neutral",
  "Colloquial; 'sich prügeln' is physical, much stronger than 'sich streiten'.": "Umgangssprachlich; 'sich prügeln' ist körperlich und viel stärker als 'sich streiten'.",
  "colloquial; invariable: ein super Film": "umgangssprachlich; unveränderlich: ein super Film",
  "colloquially also snappy, punchy (UI, prose, deadlines)": "umgangssprachlich auch knackig, prägnant (Oberflächen, Texte, Fristen)",
  "colloquially shortened to 'das Gespräch'": "umgangssprachlich verkürzt zu 'das Gespräch'",
  "common and informal; can describe a person, idea or situation": "geläufig und informell; kann eine Person, eine Idee oder eine Situation beschreiben",
  "Common complaint": "Häufige Beschwerde",
  "Common slang reaction": "Häufige Slang-Reaktion",
  "Common slang reaction to bad news — mies = lousy, shabby": "Häufige Slang-Reaktion auf schlechte Nachrichten — mies = übel, schäbig",
  "Confirming": "Bestätigen",
  "Consent": "Einverständnis",
  "Consent — always check": "Einverständnis — immer nachfragen",
  "Conversational geopolitics with an opinion baked in — fine among friends, spicier at work": "Geopolitik im Gespräch, mit eingebauter Meinung — unter Freunden okay, bei der Arbeit heikler",
  "dark humour among friends; 'Echsenmenschen' is the go-to absurd-conspiracy reference": "schwarzer Humor unter Freunden; 'Echsenmenschen' ist der Standardverweis auf absurde Verschwörungen",
  "das Band — the conveyor. Braking on it is the one real mistake to avoid.": "das Band — das Förderband. Darauf zu bremsen ist der eine Fehler, den man vermeiden sollte.",
  "das Bügeleisen — the iron. The warning every household repeats.": "das Bügeleisen — das Gerät zum Bügeln. Die Warnung, die in jedem Haushalt fällt.",
  "das Halbjahreszeugnis — the February report. The early warning system.": "das Halbjahreszeugnis — das Zeugnis im Februar. Das Frühwarnsystem.",
  "Das hängt davon ab = it depends. Casually, mit Freunden abhängen = to hang out.": "Das hängt davon ab = es kommt darauf an. Locker heißt mit Freunden abhängen: mit Freunden rumhängen.",
  "das Profil — the tread. 'ist runter' — worn away; casual passive Germany runs on.": "das Profil — das Reifenprofil. 'ist runter' — abgefahren; das lockere Passiv, mit dem Deutschland fährt.",
  "das Rücklicht — the rear light. 'nur noch schwach' — the warning phase before darkness.": "das Rücklicht — die hintere Leuchte. 'nur noch schwach' — die Warnphase vor der Dunkelheit.",
  "das Teil — the casual word for any piece of clothing. The rule that prevents the pink wash.": "das Teil — das lockere Wort für jedes Kleidungsstück. Die Regel, die die rosa Wäsche verhindert.",
  "das Wartezimmer — from the doctor pack, considerably louder. Cats sit high; dogs make friends.": "das Wartezimmer — aus dem Arzt-Paket, deutlich lauter. Katzen sitzen oben; Hunde schließen Freundschaften.",
  "Dating": "Dating",
  "Deliberately vague — it lets both sides keep it casual. 'was' here is short for 'etwas'.": "Bewusst vage — beide Seiten können es locker halten. 'was' steht hier kurz für 'etwas'.",
  "der Aszendent — the follow-up question that separates casual from committed.": "der Aszendent — die Nachfrage, die Gelegenheitsinteresse von echtem Ernst trennt.",
  "der Helferkreis — the informal volunteer group, common in refugee and neighbourhood support.": "der Helferkreis — die informelle Freiwilligengruppe, verbreitet in der Flüchtlings- und Nachbarschaftshilfe.",
  "der Platten — the flat tyre, colloquial and universal. The commute's classic opening line.": "der Platten — der platte Reifen, umgangssprachlich und überall verstanden. Der Klassiker als Einstieg auf dem Arbeitsweg.",
  "der Strafzettel, colloquially das Knöllchen = parking ticket": "der Strafzettel, umgangssprachlich das Knöllchen = Strafzettel fürs Parken",
  "Desire": "Wunsch",
  "die Abmahnung — the warning shot, at work or over copyright. Serious, not final.": "die Abmahnung — der Warnschuss, im Job oder beim Urheberrecht. Ernst, aber nicht endgültig.",
  "die Abmahnung — the written warning. Serious, but far from a dismissal.": "die Abmahnung — die schriftliche Verwarnung. Ernst, aber weit entfernt von einer Kündigung.",
  "die Hausnummer — colloquial for a rough figure. More with a role change.": "die Hausnummer — umgangssprachlich für einen ungefähren Betrag. Mehr, wenn sich die Rolle ändert.",
  "die Jugendfeuerwehr — where most volunteers begin. Knots, hoses and friendships.": "die Jugendfeuerwehr — wo die meisten Freiwilligen anfangen. Knoten, Schläuche und Freundschaften.",
  "die Kantine — the subsidised lunch. The invitation that builds actual friendships.": "die Kantine — das bezuschusste Mittagessen. Die Einladung, aus der echte Freundschaften werden.",
  "die Lawine — the avalanche. The warning is not decorative.": "die Lawine — der Schneeabgang. Die Warnung ist keine Zierde.",
  "Direct and neutral: 'Ich bin schwanger.' Colloquially, 'schwanger von ihm' names the father.": "Direkt und neutral: 'Ich bin schwanger.' Umgangssprachlich nennt 'schwanger von ihm' den Vater.",
  "düngen = to fertilize; der Dünger = fertilizer. Du register — said between family/friends": "düngen = Nährstoffe ausbringen; der Dünger = das Düngemittel. Du-Register — unter Familie und Freunden gesagt",
  "eh = anyway / in any case (colloquial 'ohnehin')": "eh = sowieso / in jedem Fall (umgangssprachlich für 'ohnehin')",
  "eine Runde schmeißen — literally throwing a round. Casual, generous, slightly theatrical.": "eine Runde schmeißen — wörtlich eine Runde werfen. Locker, großzügig, ein bisschen theatralisch.",
  "Emergency": "Notfall",
  "Emphasis": "Betonung",
  "Emphatic casual yes": "Nachdrückliches, lockeres Ja",
  "Encouragement between friends or from a partner — the compliment learners most want to hear.": "Ermutigung unter Freunden oder vom Partner — das Kompliment, das Lernende am liebsten hören.",
  "Enemy info": "Gegnerinfo",
  "English loan, fully naturalized and plural; 'doch' makes it dismissive — casual register": "englisches Lehnwort, voll eingebürgert und im Plural; 'doch' macht es abwertend — lockeres Register",
  "Enthusiastic yes": "Begeistertes Ja",
  "Essential": "Unverzichtbar",
  "everyday casual word; also means the stubbed-out butt": "lockeres Alltagswort; bedeutet auch den ausgedrückten Stummel",
  "Everyday colloquial spelling of nichts": "Alltägliche umgangssprachliche Schreibweise von nichts",
  "Everyday connection method (slang 'schreib mir')": "Alltäglicher Weg, in Kontakt zu bleiben (Slang 'schreib mir')",
  "Everyday criticism, medium weight; fine in casual talk about colleagues or exes.": "Alltagskritik von mittlerem Gewicht; im lockeren Gespräch über Kollegen oder Ex-Partner in Ordnung.",
  "Everyday office and friend request; rüberschicken (send over) is the casual variant.": "Alltagsbitte im Büro und unter Freunden; rüberschicken ist die lockere Variante.",
  "Everyday slang (Bock haben)": "Alltagsslang (Bock haben)",
  "Everyday slang (spendieren = to treat)": "Alltäglicher Slang (spendieren = einladen, ausgeben)",
  "Facharzt = specialist; colloquially also \"einen Termin ausmachen\"": "Facharzt = Spezialist; umgangssprachlich auch 'einen Termin ausmachen'",
  "Falschparken = illegal/incorrect parking": "Falschparken = verbotenes oder falsches Parken",
  "Family": "Familie",
  "Famous last words — friends will quote it back at you for months.": "Berühmte letzte Worte — Freunde zitieren dich damit noch monatelang.",
  "Farewell": "Abschied",
  "Feeling": "Gefühl",
  "feiern = to celebrate, colloquially 'to love something'; very current usage.": "feiern = ein Fest begehen, umgangssprachlich auch 'etwas großartig finden'; sehr aktueller Gebrauch.",
  "fett = huge (colloquial intensifier); standard dev talk, not rude.": "fett = riesig (umgangssprachlicher Verstärker); normaler Entwickler-Jargon, nicht unhöflich.",
  "Finding help": "Hilfe finden",
  "Fixed casual set expression; already short, so no further clipping.": "Feste, lockere Wendung; schon kurz, also keine weitere Verkürzung.",
  "flach and steil around dahinter — the swimming-pool warning as a geometry lesson.": "flach und steil rund um dahinter — die Schwimmbadwarnung als Geometriestunde.",
  "Flight status update": "Flugstatus",
  "Flirting": "Flirten",
  "Formal": "Förmlich",
  "Frustrated, to friends. 'schon wieder' carries the job-hunt fatigue.": "Frustriert, unter Freunden. 'schon wieder' trägt den Frust der Jobsuche.",
  "geblitzt werden = to get caught by a speed camera — the standard colloquial verb for it": "geblitzt werden = von einem Blitzer erwischt werden — das übliche umgangssprachliche Verb dafür",
  "Gen-Z": "Gen Z",
  "Genuine compliment between friends; on a date it's practically flirting.": "Echtes Kompliment unter Freunden; beim Date ist es praktisch Flirten.",
  "gereizt — irritable, like a nerve already touched. Fair warning to the room.": "gereizt — reizbar, wie ein schon berührter Nerv. Eine faire Warnung an alle im Raum.",
  "gib — du-imperative of geben with vowel change; mal keeps it casual, not bossy.": "gib — du-Imperativ von geben mit Vokalwechsel; mal hält es locker statt befehlend.",
  "Greeting": "Begrüßung",
  "Grufti = colloquial for goth (from Gruft = tomb/crypt)": "Grufti = umgangssprachlich für Gothic-Anhänger (von Gruft = Grabgewölbe)",
  "Gunsmith": "Waffenschmied",
  "Half-joking household rule for the unsortable. Colloquial, said with a shrug.": "Halb im Scherz gemeinte Haushaltsregel für alles Unsortierbare. Umgangssprachlich, mit einem Schulterzucken gesagt.",
  "half-joking quitter's line; 'ich schwör' is casual spoken German": "halb im Scherz gemeinter Aufhör-Spruch; 'ich schwör' ist lockeres gesprochenes Deutsch",
  "idiomatic, informal": "idiomatisch, informell",
  "Im Alter von 30 = at the age of 30. As an exclamation, Alter! = dude! — very casual.": "Im Alter von 30 = mit 30 Jahren. Als Ausruf heißt Alter! so viel wie 'Mann!' — sehr locker.",
  "in casual speech often shortened to was: Hast du was gehört?": "in lockerer Rede oft zu was verkürzt: Hast du was gehört?",
  "In the moment": "Im Moment",
  "Informal": "Informell",
  "Informal — friends only": "Informell — nur unter Freunden",
  "Informal — the spoken contraction you'll usually hear": "Informell — die gesprochene Verkürzung, die man meist hört",
  "Informal — to strangers or staff say: Sprechen Sie Englisch?": "Informell — zu Fremden oder Personal sagt man: Sprechen Sie Englisch?",
  "Informal and rude: jemandem den Stinkefinger zeigen.": "Informell und unhöflich: jemandem den Stinkefinger zeigen.",
  "Informal and warm, mostly southern. 'Grüß Gott' is its formal, Bavarian and Austrian cousin.": "Informell und herzlich, vor allem im Süden. 'Grüß Gott' ist der förmliche bayerisch-österreichische Verwandte.",
  "Informal imperative of separable 'aufheben': 'Heb ... auf'; the full written form is 'Hebe'.": "Informeller Imperativ des trennbaren 'aufheben': 'Heb ... auf'; die volle Schriftform lautet 'Hebe'.",
  "informal loan from English; das Okay – the go-ahead": "informelles Lehnwort aus dem Englischen; das Okay – die Zustimmung",
  "Informal reply — with Sie say: Und Ihnen?": "Informelle Antwort — mit Sie sagt man: Und Ihnen?",
  "Informal term for a friend": "Informelles Wort für einen Freund",
  "informal, e.g. eine brenzlige Situation": "informell, z. B. eine brenzlige Situation",
  "informal; the standard German way to say someone drifted off into conspiracy land": "informell; die übliche deutsche Art zu sagen, dass jemand in Verschwörungsgefilde abgedriftet ist",
  "Introducing": "Vorstellen",
  "justifying one more — works for cigarettes and beers alike; very casual": "die Rechtfertigung für noch eine — passt für Zigaretten wie für Bier; sehr locker",
  "kicken — casual football. der Bolzplatz — the scuffed pitch every neighbourhood has.": "kicken — Fußball ohne großen Rahmen. Der Bolzplatz — der abgewetzte Platz, den jedes Viertel hat.",
  "klamm — damp, and colloquially short of cash. Honest without being dramatic.": "klamm — feucht, umgangssprachlich auch knapp bei Kasse. Ehrlich, ohne dramatisch zu werden.",
  "klingen — sounding. The honest warning given to every violin household's neighbours.": "klingen — tönen. Die ehrliche Warnung an die Nachbarn jedes Geigenhaushalts.",
  "knapp bei Kasse — tight at the till. The honest sentence that friends answer with einladen.": "knapp bei Kasse — knapp an der Kasse. Der ehrliche Satz, auf den Freunde mit einladen antworten.",
  "Knast = colloquial for jail/prison": "Knast = umgangssprachlich für Gefängnis",
  "Komm doch mal vorbei! — the casual open invitation.": "Komm doch mal vorbei! — die lockere, offene Einladung.",
  "Leaving": "Gehen",
  "Loadout": "Ausrüstung",
  "Logisch! is also a casual \"obviously\"": "Logisch! ist auch ein lockeres 'na klar'",
  "Making a move": "Den ersten Schritt machen",
  "Making plans": "Pläne machen",
  "medium insult — banter-safe among close friends with the right tone": "mittelschwere Beleidigung — unter engen Freunden im richtigen Ton als Spaß okay",
  "medium-strong — banter only with thick-skinned close friends": "mittelstark — nur als Spaß unter engen Freunden mit dickem Fell",
  "Meta": "Meta",
  "Opinion": "Meinung",
  "Ordering food": "Essen bestellen",
  "Plans": "Pläne",
  "Position callout": "Positionsansage",
  "Reacting": "Reagieren",
  "Reassuring": "Beruhigen",
  "Relationship status": "Beziehungsstatus",
  "Reporting a problem": "Ein Problem melden",
  "Request": "Bitte",
  "Routine": "Routine",
  "Scheduling": "Termine",
  "Seasons": "Jahreszeiten",
  "Slang": "Slang",
  "Status callout": "Statusansage",
  "Strong agreement": "Starke Zustimmung",
  "Surprise": "Überraschung",
  "Symptom": "Symptom",
  "Team play": "Teamspiel",
  "Telling time": "Uhrzeit sagen",
  "Texting": "Chatten",
  "Time comment": "Bemerkung zur Zeit",
  "Typical reply": "Typische Antwort",
  "Unlocks": "Freischaltungen",
  "Urgent": "Dringend",
  "Very common leisure activity": "Sehr verbreitete Freizeitbeschäftigung",
  "Weather": "Wetter",
  "Written German too": "Auch im Schriftdeutsch",
};
