/**
 * The usage notes in Spanish.
 *
 * Keyed by the English note exactly as the card carries it. A note missing
 * from here shows its English, so this file is filled in batches without any
 * card ever going blank — see usageNotes.ts for how it is loaded and why it
 * is not part of the interface tables.
 *
 * Fourteen thousand notes exist. This holds the ones translated so far, and
 * check-usage-notes prints how far along each language is on every build.
 */
export const USE_ES: Record<string, string> = {
  "Afterwards": "Después",
  "Agreeing": "Estar de acuerdo",
  "always plural": "siempre en plural",
  "Asking for the bill": "Pedir la cuenta",
  "At the till": "En la caja",
  "Banter": "Bromas",
  "Buying time": "Ganar tiempo",
  "Casual reply": "Respuesta informal",
  "Chores": "Tareas de casa",
  "Common complaint": "Queja frecuente",
  "Confirming": "Confirmar",
  "Consent": "Consentimiento",
  "Consent — always check": "Consentimiento — pregunta siempre",
  "Dating": "Citas",
  "Desire": "Deseo",
  "Emergency": "Emergencia",
  "Emphasis": "Énfasis",
  "Enemy info": "Info del enemigo",
  "Enthusiastic yes": "Sí entusiasta",
  "Essential": "Imprescindible",
  "Everyday slang (Bock haben)": "Argot cotidiano (Bock haben)",
  "Family": "Familia",
  "Farewell": "Despedida",
  "Feeling": "Sentimiento",
  "Finding help": "Buscar ayuda",
  "Flight status update": "Estado del vuelo",
  "Flirting": "Ligar",
  "Formal": "Formal",
  "Gen-Z": "Gen Z",
  "Greeting": "Saludo",
  "Gunsmith": "Armería",
  "In the moment": "En el momento",
  "Introducing": "Presentarse",
  "Leaving": "Irse",
  "Loadout": "Equipamiento",
  "Making a move": "Dar el primer paso",
  "Making plans": "Hacer planes",
  "Meta": "Meta",
  "Opinion": "Opinión",
  "Ordering food": "Pedir comida",
  "Plans": "Planes",
  "Position callout": "Aviso de posición",
  "Reacting": "Reaccionar",
  "Reassuring": "Tranquilizar",
  "Relationship status": "Estado sentimental",
  "Reporting a problem": "Informar de un problema",
  "Request": "Petición",
  "Routine": "Rutina",
  "Scheduling": "Programar",
  "Seasons": "Estaciones",
  "Slang": "Argot",
  "Status callout": "Aviso de estado",
  "Strong agreement": "Acuerdo rotundo",
  "Surprise": "Sorpresa",
  "Symptom": "Síntoma",
  "Team play": "Juego en equipo",
  "Telling time": "Decir la hora",
  "Texting": "Mensajes",
  "Time comment": "Comentario sobre la hora",
  "Typical reply": "Respuesta típica",
  "Unlocks": "Desbloqueos",
  "Urgent": "Urgente",
  "Very common leisure activity": "Actividad de ocio muy común",
  "Weather": "El tiempo",
  "Written German too": "También en alemán escrito",
};
