/**
 * The usage notes in Italian.
 *
 * Keyed by the English note exactly as the card carries it. A note missing
 * from here shows its English, so this file is filled in batches without any
 * card ever going blank — see usageNotes.ts for how it is loaded and why it
 * is not part of the interface tables.
 *
 * Fourteen thousand notes exist. This holds the ones translated so far, and
 * check-usage-notes prints how far along each language is on every build.
 */
export const USE_IT: Record<string, string> = {
  "'doppelt' — double. 'Menge' is a quantity, and colloquially 'a lot'.": "'doppelt' — doppio. 'Menge' è una quantità e, colloquialmente, 'molto'.",
  "'draufschauen' — to look at it. Colloquial and separable.": "'draufschauen' — dargli un'occhiata. Colloquiale e separabile.",
  "'durch sein' — colloquially done for: soaked, worn out, finished.": "'durch sein' — colloquialmente spacciato: fradicio, consumato, finito.",
  "'eigentlich' — the casual opener for a serious adult conversation.": "'eigentlich' — l'attacco disinvolto di una conversazione seria tra adulti.",
  "'Elfer' is the casual clip everyone uses in speech": "'Elfer' è l'abbreviazione informale che tutti usano parlando",
  "'ewig' — eternally, used casually for 'ages'. 'laden' for loading.": "'ewig' — eternamente, in tono informale 'un'eternità'. 'laden' per il caricamento.",
  "'gar nicht erst' — not even starting. Avoiding the problem entirely.": "'gar nicht erst' — non cominciare nemmeno. Evitare del tutto il problema.",
  "'gläubig' — devout. Said plainly, this ends no friendships in Germany.": "'gläubig' — credente. Detto con semplicità, in Germania non rovina nessuna amicizia.",
  "'schlapp' (colloquial) = run-down, drained; 'kaum' = barely.": "'schlapp' (colloquiale) = fiacco, svuotato; 'kaum' = appena.",
  "A colloquial fixed expression. It is not sexual in this use.": "Un'espressione fissa colloquiale. In questo uso non ha senso sessuale.",
  "A common use of sammeln among friends, at work or in a family.": "Un uso comune di sammeln tra amici, al lavoro o in famiglia.",
  "A direct warning that a condition or necessary step cannot be skipped.": "Un avvertimento diretto: una condizione o un passaggio necessario non si può saltare.",
  "A serious accusation, not casual criticism.": "Un'accusa grave, non una critica di passaggio.",
  "A standing offer between partners or close friends; warm, no drama.": "Un'offerta sempre valida tra partner o amici stretti; affettuosa, senza drammi.",
  "A very common informal way to check whether a day suits someone.": "Un modo informale molto comune per chiedere se un giorno va bene a qualcuno.",
  "Afterwards": "Dopo",
  "Agreeing": "Essere d'accordo",
  "also colloquially \"incredibly\": unwahrscheinlich gut": "colloquialmente anche 'incredibilmente': unwahrscheinlich gut",
  "also colloquially \"massively\": tierisch gut": "colloquialmente anche 'da matti': tierisch gut",
  "always plural": "sempre plurale",
  "Asking for the bill": "Chiedere il conto",
  "At the till": "Alla cassa",
  "auslaufen — leaking out. 'hinüber sein' — colloquially beyond saving.": "auslaufen — fuoriuscire. 'hinüber sein' — colloquialmente, andato.",
  "Banter": "Battute",
  "beraten — advising. 'einen' — the colloquial accusative of man.": "beraten — consigliare. 'einen' — l'accusativo colloquiale di man.",
  "Blunt insult, literally a full fencepost. Friends-only register.": "Insulto pesante, alla lettera un palo da recinzione intero. Solo tra amici.",
  "bumming a cigarette; casual, smoker-to-smoker only": "scroccare una sigaretta; informale, solo tra fumatori",
  "Buying time": "Prendere tempo",
  "Casual": "Informale",
  "Casual — Ding literally means 'thing'": "Informale — Ding significa letteralmente 'cosa'",
  "Casual — literally 'now we have the salad'": "Informale — letteralmente 'adesso abbiamo l'insalata'",
  "Casual — literally 'that's not my beer'": "Informale — letteralmente 'non è birra mia'",
  "Casual — literally 'you had pig'": "Informale — letteralmente 'hai avuto maiale'",
  "Casual agreement": "Assenso informale",
  "Casual check-in mid-explanation.": "Verifica informale nel mezzo di una spiegazione.",
  "casual clipping of 'Prominenter' — everyday word": "abbreviazione informale di 'Prominenter' — parola di tutti i giorni",
  "Casual complaint, one hour in. Someone packed too much Brotzeit.": "Lamentela informale dopo un'ora. Qualcuno ha messo nello zaino troppa Brotzeit.",
  "casual compliment; stehen + dative = to suit someone": "complimento informale; stehen + dativo = star bene a qualcuno",
  "Casual date invite (better than formal 'Möchten Sie...')": "Invito a un appuntamento in tono informale (meglio del formale 'Möchten Sie...')",
  "casual Denglisch — 'Ich hab gecodet' is completely normal among devs": "denglisch informale — 'Ich hab gecodet' è del tutto normale tra sviluppatori",
  "Casual directive": "Indicazione informale",
  "Casual everyday goodbye — used everywhere in Germany": "Saluto informale di tutti i giorni — usato in tutta la Germania",
  "Casual everyday reassurance": "Rassicurazione informale di tutti i giorni",
  "Casual for playing video games; in money contexts it means to gamble.": "Informale per giocare ai videogiochi; se c'è di mezzo il denaro, significa scommettere.",
  "Casual goodbye — borrowed from Italian, extremely popular in Germany": "Saluto informale — preso in prestito dall'italiano, popolarissimo in Germania",
  "casual gym slang for lifting weights; 'pumpen gehen'": "gergo informale da palestra per sollevare pesi; 'pumpen gehen'",
  "Casual invite": "Invito informale",
  "casual loanword; einkaufen is the German verb": "prestito informale; einkaufen è il verbo tedesco",
  "Casual opener": "Apertura di conversazione informale",
  "Casual opener for close friends": "Apertura informale tra amici stretti",
  "Casual opinion": "Opinione informale",
  "Casual positive update": "Aggiornamento positivo in tono informale",
  "Casual reminiscing; 'was los sein' = something happening.": "Ricordi in tono informale; 'was los sein' = succede qualcosa.",
  "Casual reply": "Risposta informale",
  "Casual request": "Richiesta informale",
  "Casual request to repeat": "Richiesta informale di ripetere",
  "Casual self-intro": "Presentazione di sé informale",
  "Casual slang command": "Ordine in gergo informale",
  "Casual slang farewell": "Saluto di commiato in gergo informale",
  "casual spoken; from sich fertig machen = sich zurechtmachen": "parlato informale; da sich fertig machen = prepararsi, sistemarsi",
  "casual spoken; the machen-lassen pattern for anything done at a salon": "parlato informale; lo schema machen-lassen per tutto ciò che si fa dal parrucchiere",
  "casual, admiring; 'definiert' = lean and cut, more technical": "informale e ammirato; 'definiert' = asciutto e scolpito, più tecnico",
  "Casual, teasing — literally 'do you have tomatoes on your eyes?'": "Informale e canzonatorio — letteralmente 'hai i pomodori sugli occhi?'",
  "Casual, to companions. Famous last words on any hike.": "Informale, ai compagni. Le famose ultime parole di ogni escursione.",
  "Casual, wry — literally 'life is no pony farm'": "Informale e ironico — letteralmente 'la vita non è un maneggio di pony'",
  "casual, younger speakers; Hautpflege is the more formal word": "informale, parlanti più giovani; Hautpflege è la parola più formale",
  "casual; 'platt' = wiped out, works for any exhaustion": "informale; 'platt' = a pezzi, va bene per qualsiasi stanchezza",
  "casual; 'Proteinshake' works too": "informale; va bene anche 'Proteinshake'",
  "casual; 'sich etwas ziehen' = to pull a muscle": "informale; 'sich etwas ziehen' = farsi uno stiramento",
  "Casual; ackern makes the work sound tiring or relentless.": "Informale; ackern fa suonare il lavoro come faticoso e senza tregua.",
  "Casual; adults admit it with a grin": "Informale; gli adulti lo ammettono con un sorriso",
  "casual; literally also to plough a field": "informale; letteralmente anche arare un campo",
  "casual; the question everyone asks": "informale; la domanda che fanno tutti",
  "casual; the standard (optimistic) answer": "informale; la risposta tipica (ottimista)",
  "Casual; the way adults confess it with a grin.": "Informale; il modo in cui gli adulti lo confessano con un sorriso.",
  "casual: kicken gehen = to go and play football": "informale: kicken gehen = andare a giocare a calcio",
  "Casual. 'Sich etwas holen' = to catch/get something (sunburn, a cold).": "Informale. 'Sich etwas holen' = beccarsi qualcosa (scottatura, raffreddore).",
  "casually clipped to 'der Elfer'": "abbreviato colloquialmente in 'der Elfer'",
  "Chores": "Faccende domestiche",
  "close friends only — sharing a cigarette or vape": "solo tra amici stretti — condividere una sigaretta o una vape",
  "coden is casual Denglisch; completely normal in the du-form dev crowd.": "coden è denglisch informale; del tutto normale nell'ambiente dev che si dà del tu.",
  "Colloquial (Kopfnuss = headbutt/noogie)": "Colloquiale (Kopfnuss = testata o scappellotto)",
  "Colloquial and strong; verbal or psychological cruelty": "Colloquiale e forte; crudeltà verbale o psicologica",
  "Colloquial but harmless — safe with colleagues and family.": "Colloquiale ma innocuo — tranquillo con colleghi e familiari.",
  "Colloquial but serious; 'zu dritt' = three of them together.": "Colloquiale ma serio; 'zu dritt' = in tre.",
  "Colloquial combo of Ja + Nein": "Fusione colloquiale di Ja + Nein",
  "colloquial intensifier: mächtig stolz = mighty proud": "intensificatore colloquiale: mächtig stolz = fiero da matti",
  "Colloquial shortcut": "Scorciatoia colloquiale",
  "colloquial, what children do in sand; graben is neutral": "colloquiale, quello che fanno i bambini nella sabbia; graben è neutro",
  "colloquial; invariable: ein super Film": "colloquiale; invariabile: ein super Film",
  "colloquially also snappy, punchy (UI, prose, deadlines)": "colloquialmente anche scattante, incisivo (interfacce, testi, scadenze)",
  "colloquially shortened to 'das Gespräch'": "abbreviato colloquialmente in 'das Gespräch'",
  "common and informal; can describe a person, idea or situation": "comune e informale; può descrivere una persona, un'idea o una situazione",
  "Common complaint": "Lamentela comune",
  "Common slang reaction": "Reazione comune in gergo",
  "Common slang reaction to bad news — mies = lousy, shabby": "Reazione comune in gergo a una brutta notizia — mies = pessimo, scadente",
  "Confirming": "Confermare",
  "Consent": "Consenso",
  "Consent — always check": "Consenso — chiedi sempre",
  "das Bügeleisen — the iron. The warning every household repeats.": "das Bügeleisen — il ferro da stiro. L'avvertimento che si ripete in ogni casa.",
  "das Halbjahreszeugnis — the February report. The early warning system.": "das Halbjahreszeugnis — la pagella di febbraio. Il sistema di allerta precoce.",
  "Dating": "Appuntamenti",
  "der Strafzettel, colloquially das Knöllchen = parking ticket": "der Strafzettel, colloquialmente das Knöllchen = multa per divieto di sosta",
  "Desire": "Desiderio",
  "die Lawine — the avalanche. The warning is not decorative.": "die Lawine — la valanga. L'avvertimento non è decorativo.",
  "eh = anyway / in any case (colloquial 'ohnehin')": "eh = comunque / in ogni caso (colloquiale per 'ohnehin')",
  "Emergency": "Emergenza",
  "Emphasis": "Enfasi",
  "Emphatic casual yes": "Sì informale ed enfatico",
  "Enemy info": "Info sul nemico",
  "Enthusiastic yes": "Sì entusiasta",
  "Essential": "Essenziale",
  "everyday casual word; also means the stubbed-out butt": "parola informale di tutti i giorni; indica anche il mozzicone spento",
  "Everyday colloquial spelling of nichts": "Grafia colloquiale quotidiana di nichts",
  "Everyday connection method (slang 'schreib mir')": "Modo quotidiano per restare in contatto (gergo 'schreib mir')",
  "Everyday slang (Bock haben)": "Gergo quotidiano (Bock haben)",
  "Everyday slang (spendieren = to treat)": "Gergo di tutti i giorni (spendieren = offrire)",
  "Facharzt = specialist; colloquially also \"einen Termin ausmachen\"": "Facharzt = medico specialista; colloquialmente anche 'einen Termin ausmachen'",
  "Falschparken = illegal/incorrect parking": "Falschparken = parcheggio irregolare o vietato",
  "Family": "Famiglia",
  "Famous last words — friends will quote it back at you for months.": "Famose ultime parole — gli amici te le ricorderanno per mesi.",
  "Farewell": "Congedo",
  "Feeling": "Sentimento",
  "fett = huge (colloquial intensifier); standard dev talk, not rude.": "fett = enorme (intensificatore colloquiale); gergo dev normale, non volgare.",
  "Finding help": "Trovare aiuto",
  "Fixed casual set expression; already short, so no further clipping.": "Espressione fissa informale; già breve, quindi niente ulteriori accorciamenti.",
  "Flight status update": "Stato del volo",
  "Flirting": "Flirtare",
  "Formal": "Formale",
  "Frustrated, to friends. 'schon wieder' carries the job-hunt fatigue.": "Con frustrazione, tra amici. 'schon wieder' porta la stanchezza della ricerca di lavoro.",
  "Gen-Z": "Gen Z",
  "Greeting": "Saluto",
  "Grufti = colloquial for goth (from Gruft = tomb/crypt)": "Grufti = colloquiale per goth (da Gruft = cripta, tomba)",
  "Gunsmith": "Armaiolo",
  "half-joking quitter's line; 'ich schwör' is casual spoken German": "battuta mezzo scherzosa di chi molla; 'ich schwör' è tedesco parlato informale",
  "idiomatic, informal": "idiomatico, informale",
  "in casual speech often shortened to was: Hast du was gehört?": "nel parlato informale spesso ridotto a was: Hast du was gehört?",
  "In the moment": "Sul momento",
  "Informal": "Informale",
  "Informal — friends only": "Informale — solo tra amici",
  "Informal — the spoken contraction you'll usually hear": "Informale — la contrazione parlata che si sente di solito",
  "Informal — to strangers or staff say: Sprechen Sie Englisch?": "Informale — a estranei o al personale si dice: Sprechen Sie Englisch?",
  "Informal and rude: jemandem den Stinkefinger zeigen.": "Informale e volgare: jemandem den Stinkefinger zeigen.",
  "informal loan from English; das Okay – the go-ahead": "prestito informale dall'inglese; das Okay – il via libera",
  "Informal reply — with Sie say: Und Ihnen?": "Risposta informale — con Sie si dice: Und Ihnen?",
  "Informal term for a friend": "Termine informale per un amico",
  "informal, e.g. eine brenzlige Situation": "informale, per es. eine brenzlige Situation",
  "Introducing": "Presentarsi",
  "Knast = colloquial for jail/prison": "Knast = colloquiale per carcere, galera",
  "Komm doch mal vorbei! — the casual open invitation.": "Komm doch mal vorbei! — l'invito aperto e informale.",
  "Leaving": "Andarsene",
  "Loadout": "Equipaggiamento",
  "Logisch! is also a casual \"obviously\"": "Logisch! è anche un 'ovvio' informale",
  "Making a move": "Fare il primo passo",
  "Making plans": "Fare programmi",
  "medium insult — banter-safe among close friends with the right tone": "insulto medio — accettabile per scherzo tra amici stretti, col tono giusto",
  "medium-strong — banter only with thick-skinned close friends": "medio-forte — solo per scherzo tra amici stretti dalla pelle dura",
  "Meta": "Meta",
  "Opinion": "Opinione",
  "Ordering food": "Ordinare da mangiare",
  "Plans": "Programmi",
  "Position callout": "Segnalazione di posizione",
  "Reacting": "Reagire",
  "Reassuring": "Rassicurare",
  "Relationship status": "Stato sentimentale",
  "Reporting a problem": "Segnalare un problema",
  "Request": "Richiesta",
  "Routine": "Routine",
  "Scheduling": "Organizzare",
  "Seasons": "Stagioni",
  "Slang": "Gergo",
  "Status callout": "Segnalazione di stato",
  "Strong agreement": "Accordo deciso",
  "Surprise": "Sorpresa",
  "Symptom": "Sintomo",
  "Team play": "Gioco di squadra",
  "Telling time": "Dire l'ora",
  "Texting": "Messaggi",
  "Time comment": "Commento sull'ora",
  "Typical reply": "Risposta tipica",
  "Unlocks": "Sblocchi",
  "Urgent": "Urgente",
  "Very common leisure activity": "Attività del tempo libero molto comune",
  "Weather": "Tempo",
  "Written German too": "Anche nel tedesco scritto",
};
