/**
 * The usage notes in Polish.
 *
 * Keyed by the English note exactly as the card carries it. A note missing
 * from here shows its English, so this file is filled in batches without any
 * card ever going blank — see usageNotes.ts for how it is loaded and why it
 * is not part of the interface tables.
 *
 * Fourteen thousand notes exist. This holds the ones translated so far, and
 * check-usage-notes prints how far along each language is on every build.
 */
export const USE_PL: Record<string, string> = {
  "'abschleppen' — to tow. Colloquially it also means pulling someone in a bar.": "'abschleppen' — holować. Potocznie znaczy też poderwać kogoś w barze.",
  "'angesagt sein' — forecast, announced. Also slang for what's currently trendy.": "'angesagt sein' — zapowiedziany, prognozowany. W slangu też: modny, na czasie.",
  "'auf den Cent genau' is the fixed phrase — a virtue in a shop, a friendship-killer at a table. 'abrechnen' is the verb for settling up, and this is the polite way to call off over-precise splitting.": "'auf den Cent genau' to utarte wyrażenie — w sklepie cnota, przy stole zabójca przyjaźni. 'abrechnen' to czasownik od rozliczania się, a to grzeczny sposób, by odpuścić dzielenie co do grosza.",
  "'auf etwas stehen' — to be into something. Informal, current, and used constantly.": "'auf etwas stehen' — lubić coś, kręcić na czymś. Nieformalne, aktualne i używane bez przerwy.",
  "'Auf etwas stehen' = to be into something. Informal fan talk; works for genres, bands, and people.": "'Auf etwas stehen' = lubić coś. Nieformalna mowa fanów; pasuje do gatunków, zespołów i ludzi.",
  "'auf jemanden aufpassen' covers cats, kids and luggage alike. Plain present tense is how favours get asked between friends — no 'könntest du bitte' needed.": "'auf jemanden aufpassen' dotyczy kotów, dzieci i bagażu tak samo. Zwykły czas teraźniejszy to sposób proszenia o przysługę wśród przyjaciół — żadne 'könntest du bitte' nie jest potrzebne.",
  "'aufgewacht sein' as conspiracist self-description; comprehension only — hearing this is a warning sign": "'aufgewacht sein' jako autoopis wyznawców spisków; tylko do rozumienia — usłyszenie tego to sygnał ostrzegawczy",
  "'bedeuten' for meaning. 'Was heißt das?' is the more casual version and just as correct.": "'bedeuten' o znaczeniu. 'Was heißt das?' to wersja swobodniejsza i równie poprawna.",
  "'bei jemandem was offen haben' = to have something outstanding with someone — friendly and vague, so you avoid the heavy word 'Schulden'. Works in both directions: 'Du hast noch was bei mir offen.'": "'bei jemandem was offen haben' = mieć u kogoś coś do wyrównania — przyjaźnie i nieostro, żeby uniknąć ciężkiego słowa 'Schulden'. Działa w obie strony: 'Du hast noch was bei mir offen.'",
  "'Bei uns' = in my country/family. 'Riesenthema' (giant topic) is casual and vivid — good for explaining your own culture.": "'Bei uns' = u nas w kraju albo w rodzinie. 'Riesenthema' (wielki temat) jest swobodne i obrazowe — dobre do tłumaczenia własnej kultury.",
  "'blank sein' = to have literally nothing left — a notch below 'pleite' and very casual. Friends and family only; never to a colleague or a landlord.": "'blank sein' = nie mieć dosłownie nic — stopień niżej niż 'pleite' i bardzo swobodne. Tylko wśród przyjaciół i rodziny; nigdy do współpracownika czy właściciela mieszkania.",
  "'borgen' — to lend informally between friends; 'leihen' works too. The dative person comes first: borgst du MIR.": "'borgen' — pożyczać nieformalnie wśród przyjaciół; 'leihen' też przejdzie. Osoba w celowniku idzie pierwsza: borgst du MIR.",
  "'Das Match' — loan for a full competitive game; 'ist Schluss' = are we done. Casual.": "'Das Match' — zapożyczenie na cały mecz; 'ist Schluss' = koniec. Swobodnie.",
  "'davon' avoids repeating the product name after pointing or asking a question about it.": "'davon' pozwala nie powtarzać nazwy produktu po wskazaniu go lub zapytaniu o niego.",
  "'davon' refers to an amount of the thing already being discussed and avoids repeating its name.": "'davon' odnosi się do ilości rzeczy, o której już mowa, i pozwala nie powtarzać jej nazwy.",
  "'Der Hammer' = the standard casual superlative for events. Informal, all ages under about 50.": "'Der Hammer' = standardowy, swobodny superlatyw o wydarzeniach. Nieformalne, wszyscy poniżej mniej więcej 50 lat.",
  "'Der Ping' — English loan, no alternative. 'übel' is youth slang for 'terrible'.": "'Der Ping' — zapożyczenie z angielskiego, bez odpowiednika. 'übel' to młodzieżowy slang na 'okropny'.",
  "'dir' means you are choosing it for yourself; 'Such was aus' also works. 'aus' moves to the end. This is the warm, informal way to offer someone a choice.": "'dir' znaczy, że wybierasz dla siebie; 'Such was aus' też przejdzie. 'aus' idzie na koniec. Tak ciepło i nieformalnie daje się komuś wybór.",
  "'doch mal' turns the instruction into a casual suggestion. 'anrufen' splits around the person being called.": "'doch mal' zamienia polecenie w swobodną propozycję. 'anrufen' rozdziela się wokół osoby, do której dzwonisz.",
  "'doppelt' — double. 'Menge' is a quantity, and colloquially 'a lot'.": "'doppelt' — podwójnie. 'Menge' to ilość, a potocznie 'dużo'.",
  "'dran sein' — to be next in turn. Compact, informal and used constantly.": "'dran sein' — być następnym w kolejce. Zwięzłe, nieformalne i używane bez przerwy.",
  "'dran' (= daran) is the ultra-casual kitchen way to say 'onto it'; how home cooks actually talk, never written in recipes.": "'dran' (= daran) to bardzo swobodna kuchenna forma na 'do tego'; tak naprawdę mówią domowi kucharze, w przepisach tego nie ma.",
  "'draufschauen' — to look at it. Colloquial and separable.": "'draufschauen' — zerknąć na to. Potoczne i rozdzielnie złożone.",
  "'drücken' is the everyday word for hugging — warmer and more casual than 'umarmen'. Also in goodbyes and texts: 'Ich drück dich!' = hugs!": "'drücken' to codzienne słowo na przytulenie — cieplejsze i swobodniejsze niż 'umarmen'. Także przy pożegnaniach i w wiadomościach: 'Ich drück dich!'",
  "'Du hast einen guten Musikgeschmack' is a real compliment between friends or on a date.": "'Du hast einen guten Musikgeschmack' to prawdziwy komplement wśród przyjaciół albo na randce.",
  "'durch sein' — colloquially done for: soaked, worn out, finished.": "'durch sein' — potocznie skończony: przemoczony, zużyty, wykończony.",
  "'duzen' — to address someone as du. THE sentence for crossing from formal to informal. Traditionally the older person or the senior one offers it.": "'duzen' — mówić komuś na ty. TO zdanie przy przejściu z pan/pani na ty. Tradycyjnie proponuje je osoba starsza albo wyżej postawiona.",
  "'eigentlich' — the casual opener for a serious adult conversation.": "'eigentlich' — swobodny wstęp do poważnej rozmowy dorosłych.",
  "'ein schlechtes Gewissen haben' = to feel guilty. The second cancellation needs this sentence; the third needs it plus a concrete new date attached, or the friendship quietly cools.": "'ein schlechtes Gewissen haben' = mieć wyrzuty sumienia. Przy drugim odwołaniu trzeba tego zdania; przy trzecim jeszcze konkretnej nowej daty, inaczej przyjaźń po cichu stygnie.",
  "'einschlafen' means to fall asleep, but about a habit, a group chat or a friendship it means it quietly died — no decision, no announcement. The gentlest way to admit you stopped going.": "'einschlafen' znaczy zasnąć, ale o nawyku, czacie grupowym albo przyjaźni: po cichu wygasła — bez decyzji, bez ogłoszenia. Najłagodniejszy sposób przyznania, że przestało się chodzić.",
  "'Elfer' is the casual clip everyone uses in speech": "'Elfer' to swobodny skrót, którego wszyscy używają w mowie",
  "'Er ist trocken' is THE standard, respectful phrase for a recovering alcoholic who no longer drinks — not slang, not euphemism.": "'Er ist trocken' to TO standardowe, pełne szacunku określenie osoby uzależnionej od alkoholu, która już nie pije — nie slang, nie eufemizm.",
  "'etwas aufrechnen' = to offset one thing against another, and between friends it's an accusation. This is the German way of saying the friendship is worth more than the four euros.": "'etwas aufrechnen' = potrącać jedno z drugim, a wśród przyjaciół to zarzut. Tak po niemiecku mówi się, że przyjaźń jest warta więcej niż te cztery euro.",
  "'ewig' — eternally, used casually for 'ages'. 'laden' for loading.": "'ewig' — wiecznie, swobodnie w znaczeniu 'całe wieki'. 'laden' o ładowaniu.",
  "'fertig sein' about a person means finished in the sense of nothing left in the tank. Blunt but affectionate between friends and flatmates — say it to your boss and it's simply an insult.": "'fertig sein' o osobie znaczy: bak pusty. Bez ogródek, ale czule wśród przyjaciół i współlokatorów — powiedziane szefowi to po prostu obelga.",
  "'fies' is the mean-spirited one — sharper than 'gemein' and very spoken. Between friends it's often half-admiring after a brutal joke; said flat, with no smile, it's completely serious.": "'fies' to słowo złośliwe — ostrzejsze niż 'gemein' i bardzo mówione. Wśród przyjaciół po brutalnym żarcie brzmi często półpodziwiająco; powiedziane płasko, bez uśmiechu, jest całkiem serio.",
  "'frei Schnauze' — literally free snout: no recipe, pure instinct. Wonderfully casual.": "'frei Schnauze' — dosłownie wolny pysk: bez przepisu, sam instynkt. Cudownie swobodne.",
  "'für Samstag' — booked for a day. A Transporter needs no lorry licence, which is why friends get asked.": "'für Samstag' — zarezerwowany na jeden dzień. Na Transportera nie trzeba prawa jazdy na ciężarówkę, dlatego pyta się przyjaciół.",
  "'gar nicht erst' — not even starting. Avoiding the problem entirely.": "'gar nicht erst' — nawet nie zaczynać. Całkowite uniknięcie problemu.",
  "'glatt' — slippery with ice. The winter warning Germans text each other.": "'glatt' — oblodzony, śliski. Zimowe ostrzeżenie, które Niemcy wysyłają sobie w wiadomościach.",
  "'gläubig' — devout. Said plainly, this ends no friendships in Germany.": "'gläubig' — wierzący. Powiedziane wprost, w Niemczech nie kończy żadnej przyjaźni.",
  "'gucken' is the casual everyday verb (north/central); the south says 'schauen'": "'gucken' to swobodny, codzienny czasownik (północ i centrum); południe mówi 'schauen'",
  "'Hä?' — bafflement, rising tone. Rude to teachers, standard between friends. 'Sinn ergeben' — to make sense.": "'Hä?' — zdziwienie, wznosząca intonacja. Wobec nauczycieli niegrzeczne, wśród przyjaciół normalne. 'Sinn ergeben' — mieć sens.",
  "'halbe-halbe' is common informal German for dividing something into two equal parts.": "'halbe-halbe' to częste, nieformalne niemieckie wyrażenie o dzieleniu czegoś na pół.",
  "'hinkriegen' — to manage or pull something off. Informal, warm and extremely common.": "'hinkriegen' — dać radę, ogarnąć coś. Nieformalne, ciepłe i bardzo częste.",
  "'Ich meinte damit, dass ...' states the intended meaning directly and avoids an unnecessarily heavy sentence frame.": "'Ich meinte damit, dass ...' podaje zamierzone znaczenie wprost i pozwala uniknąć niepotrzebnie ciężkiej konstrukcji zdania.",
  "'in einfach' is colloquial and slightly jokey — asking for simpler words, not slower speech. Germans find it charming from a learner; 'Leichte Sprache' even exists as an official concept.": "'in einfach' jest potoczne i lekko żartobliwe — prosisz o prostsze słowa, nie o wolniejsze mówienie. Od uczącego się Niemcy uznają to za urocze; 'Leichte Sprache' istnieje nawet jako oficjalne pojęcie.",
  "'jeder zahlt seins' — the German default among friends. No awkwardness; it's the system.": "'jeder zahlt seins' — niemiecka norma wśród przyjaciół. Żadnej niezręczności; tak to działa.",
  "'jemandem etwas abkaufen' = to buy someone's story. Warm rather than confrontational between close friends, because it proves you've been paying attention — but presumptuous to an acquaintance.": "'jemandem etwas abkaufen' = kupić czyjąś wersję. Wśród bliskich przyjaciół raczej ciepłe niż konfrontacyjne, bo dowodzi, że słuchałeś — wobec znajomego jednak zarozumiałe.",
  "'jemanden anstecken' = to pass your bug on. 'bloß' in a command is the urgent flavour — said with an arm held out, it's half genuine warning, half joke.": "'jemanden anstecken' = zarazić kogoś swoim wirusem. 'bloß' w rozkazie dodaje nuty naglącej — powiedziane z wyciągniętą ręką, to pół prawdziwego ostrzeżenia, pół żartu.",
  "'jemanden unter Druck setzen' is the standard phrase for creating pressure; urgency is a common warning sign.": "'jemanden unter Druck setzen' to standardowe wyrażenie o wywieraniu presji; pośpiech to częsty sygnał ostrzegawczy.",
  "'jemanden vollquatschen' = to talk at someone non-stop. The standard climbdown once the rant runs out of steam. Casual, friends only.": "'jemanden vollquatschen' = zagadać kogoś bez przerwy. Standardowe wycofanie się, gdy potok słów wyhamuje. Swobodne, tylko wśród przyjaciół.",
  "'jemanden von der Seite anmachen' = to start on someone unprovoked, on the street or on the train. Street-level slang, not office German.": "'jemanden von der Seite anmachen' = zaczepić kogoś bez powodu, na ulicy albo w pociągu. Uliczny slang, nie biurowy niemiecki.",
  "'Jetzt reicht's' is the short version, and the last warning before a row.": "'Jetzt reicht's' to wersja krótka — i ostatnie ostrzeżenie przed awanturą.",
  "'Keep your ears stiff' — parting encouragement to someone facing a hard stretch. Warm, informal, and said at doors.": "'Trzymaj uszy sztywno' — pożegnalna zachęta dla kogoś, kogo czeka trudny czas. Ciepłe, nieformalne, mówione w drzwiach.",
  "'kein ... mehr' means there is none left. 'Klopapier' is the ordinary informal word used at home.": "'kein ... mehr' znaczy, że nic nie zostało. 'Klopapier' to zwykłe, nieformalne słowo używane w domu.",
  "'Kein Thema' — not a topic: it doesn't even need discussing. Friendship in two words.": "'Kein Thema' — nie ma tematu: nie ma nawet o czym rozmawiać. Przyjaźń w dwóch słowach.",
  "'knapp' covers anything in short supply — time, money, a train connection. Here it's the warning shot before you either turn up breathless or cancel.": "'knapp' pasuje do wszystkiego, czego brakuje — czasu, pieniędzy, przesiadki. Tu to strzał ostrzegawczy, zanim dobiegniesz bez tchu albo odwołasz.",
  "'Land unter' comes from coastal flood warnings and means properly overwhelmed. Casual — for colleagues, not for clients.": "'Land unter' pochodzi z nadmorskich ostrzeżeń powodziowych i znaczy: kompletnie zawalony. Swobodne — do kolegów z pracy, nie do klientów.",
  "'laufen' is the verb for films showing — 'Der läuft noch' = it's still on. The 'denn ... so' pair turns it into a casual browse instead of a demand.": "'laufen' to czasownik o filmach na afiszu — 'Der läuft noch' = jeszcze go grają. Para 'denn ... so' zmienia to w swobodne przeglądanie zamiast żądania.",
  "'mal' makes the command sound casual; use 'in die Ecke' when directing light into it.": "'mal' sprawia, że polecenie brzmi swobodnie; 'in die Ecke' używa się, kierując tam światło.",
  "'mal' softens the imperative into a casual request; masculine object is 'deinen Benutzernamen'.": "'mal' zmienia tryb rozkazujący w swobodną prośbę; dopełnienie w rodzaju męskim to 'deinen Benutzernamen'.",
  "'mal' turns an offer into something casual. Two seconds, no commitment.": "'mal' zamienia propozycję w coś swobodnego. Dwie sekundy, żadnych zobowiązań.",
  "'Man sieht sich' — literally one sees oneself — is the standard casual sign-off when no date is fixed.": "'Man sieht sich' — dosłownie widzimy się — to standardowe, swobodne pożegnanie, gdy nie ma ustalonej daty.",
  "'mitnehmen' is separable; in the informal imperative, 'mit' lands at the end.": "'mitnehmen' jest rozdzielnie złożone; w nieformalnym trybie rozkazującym 'mit' ląduje na końcu.",
  "'Nie im Leben' = never in a million years; 'legit' is borrowed straight from English gaming slang. The standard disbelief formula.": "'Nie im Leben' = w życiu nie; 'legit' jest wzięte wprost z angielskiego slangu graczy. Standardowa formuła niedowierzania.",
  "'Pass auf!' is the fastest warning; separable 'aufpassen' becomes 'pass ... auf'.": "'Pass auf!' to najszybsze ostrzeżenie; rozdzielne 'aufpassen' zmienia się w 'pass ... auf'.",
  "'rauf und runter' = over and over — how Germans confess an obsession with a song or a show ('Die Serie hab ich rauf und runter geguckt'). Casual, affectionate, no negative edge at all.": "'rauf und runter' = w kółko — tak Niemcy przyznają się do obsesji na punkcie piosenki albo serialu ('Die Serie hab ich rauf und runter geguckt'). Swobodne, czułe, bez cienia negatywnego zabarwienia.",
  "'rausfliegen' — from the fuse pack, here about a back. Colloquial and instantly understood.": "'rausfliegen' — z zestawu o bezpiecznikach, tu o plecach. Potoczne i od razu zrozumiałe.",
  "'rumhängen' (from 'herumhängen') = to hang about doing nothing. Casual and slightly teenage — perfect between friends and partners, odd in front of your boss.": "'rumhängen' (od 'herumhängen') = obijać się i nic nie robić. Swobodne i lekko nastoletnie — idealne wśród przyjaciół i partnerów, dziwne przy szefie.",
  "'schauen' or 'gucken' — gucken is more casual. No preposition before the platform.": "'schauen' albo 'gucken' — gucken jest swobodniejsze. Przed nazwą platformy nie ma przyimka.",
  "'schlapp' (colloquial) = run-down, drained; 'kaum' = barely.": "'schlapp' (potocznie) = osłabiony, wyczerpany; 'kaum' = ledwo.",
  "'schwurbeln' is the current word for conspiracy-rambling; informal, everywhere since the pandemic": "'schwurbeln' to obecne słowo na spiskowe bełkotanie; nieformalne, od czasu pandemii wszędzie",
  "'sich aufs Ohr hauen' — literally to throw yourself onto your ear. Casual and a bit blokey, for friends and flatmates; 'ein Nickerchen machen' is the neutral way to describe the same twenty minutes.": "'sich aufs Ohr hauen' — dosłownie rzucić się na ucho. Swobodne i trochę kumpelskie, do przyjaciół i współlokatorów; 'ein Nickerchen machen' opisuje te same dwadzieścia minut neutralnie.",
  "'Sich ein Haustier anschaffen' = to get a pet. Affectionate casual slang: 'das Fellbaby' (fur baby).": "'Sich ein Haustier anschaffen' = sprawić sobie zwierzaka. Czuły, swobodny slang: 'das Fellbaby' (futrzane dziecko).",
  "'sich etwas kaputt machen' = to wreck a body part — casual, slightly dramatic, used for backs and knees above all. 'Unkraut jäten' = to weed.": "'sich etwas kaputt machen' = zniszczyć sobie jakąś część ciała — swobodne, lekko dramatyczne, głównie o plecach i kolanach. 'Unkraut jäten' = pielić chwasty.",
  "'Sich etwas ziehen' = to download, distinctly casual register; the standard buddy advice before a risky purchase.": "'Sich etwas ziehen' = ściągnąć, wyraźnie swobodny rejestr; standardowa rada kumpla przed ryzykownym zakupem.",
  "'sich etwas ziehen' is slang for downloading; more neutral: 'runterladen' or the loan verb 'downloaden' — all three are common.": "'sich etwas ziehen' to slang o pobieraniu; neutralniej: 'runterladen' albo zapożyczone 'downloaden' — wszystkie trzy są częste.",
  "'sich irren' — the dignified admission, equally at home in a meeting and in the kitchen. Blunter and more colloquial: 'Ich lag komplett falsch.' Never 'Ich war falsch' — that isn't German.": "'sich irren' — godne przyznanie się do błędu, tak samo na zebraniu jak w kuchni. Dosadniej i potoczniej: 'Ich lag komplett falsch.' Nigdy 'Ich war falsch' — to nie jest niemiecki.",
  "'sich reinsteigern' = to spiral into something; informal, the natural way to describe the rabbit-hole process": "'sich reinsteigern' = nakręcać się na czymś; nieformalne, naturalny sposób opisania wpadania w tę spiralę",
  "'sicherheitshalber' explains that you are checking to avoid an unnecessary mistake.": "'sicherheitshalber' wyjaśnia, że sprawdzasz, by uniknąć niepotrzebnego błędu.",
  "'spinnen' — literally to spin — is the everyday verb for being crazy. Between friends it is affectionate; at a stranger it is an insult.": "'spinnen' — dosłownie prząść — to codzienny czasownik o byciu szalonym. Wśród przyjaciół czułe; wobec obcego to obelga.",
  "'sportlich' — sporty, and also 'smart-casual' about clothes. Both are common.": "'sportlich' — sportowy, a przy ubraniach też elegancko-swobodny. Oba znaczenia są częste.",
  "'Strafzettel' — penalty slip. Also 'Knöllchen' colloquially, which sounds far too sweet for what it is.": "'Strafzettel' — mandat. Potocznie także 'Knöllchen', co brzmi o wiele za słodko jak na to, czym jest.",
  "'total' as an intensifier is thoroughly spoken German and slightly informal.": "'total' jako wzmacniacz to na wskroś mówiony niemiecki, lekko nieformalny.",
  "'unbedingt' + colloquial 'was' (for etwas) = maximum urgency, zero formality. Best-friend register; the standard wind-up before gossip.": "'unbedingt' + potoczne 'was' (zamiast etwas) = maksymalna pilność, zero formalności. Rejestr najlepszych przyjaciół; standardowy rozbieg przed plotką.",
  "'unterschiedlich' — differing. Germans use it constantly to avoid overgeneralising.": "'unterschiedlich' — różny, rozmaity. Niemcy używają tego bez przerwy, by nie uogólniać.",
  "'Voll der/die X' is casual youth-speak amplification; pure banter register among friends and in voice chat.": "'Voll der/die X' to swobodne, młodzieżowe wzmocnienie; czysto żartobliwy rejestr wśród przyjaciół i na czacie głosowym.",
  "'voll' is THE everyday intensifier under about 40 — voll gut, voll nervig, voll teuer. Casual but harmless; drop it for the grown-up version: 'Das ist ziemlich langweilig.'": "'voll' to TEN codzienny wzmacniacz poniżej czterdziestki — voll gut, voll nervig, voll teuer. Swobodne, ale niegroźne; w wersji dorosłej się je pomija: 'Das ist ziemlich langweilig.'",
  "'was trinken gehen' — the standard invitation. Casual, open-ended, no commitment implied.": "'was trinken gehen' — standardowe zaproszenie. Swobodne, otwarte, bez zobowiązań.",
  "'wegmachen' colloquially for putting something aside. 'mal' softens the announcement.": "'wegmachen' potocznie o odłożeniu czegoś na bok. 'mal' łagodzi zapowiedź.",
  "'Wie hoch' for amounts of money. A completely normal question between German friends.": "'Wie hoch' o kwotach pieniędzy. Zupełnie normalne pytanie wśród niemieckich przyjaciół.",
  "'wieder drauf haben' — colloquial and compact. Bike chains come off constantly.": "'wieder drauf haben' — potoczne i zwięzłe. Łańcuchy w rowerach spadają bez przerwy.",
  "'Wofür' is the normal neutral form; 'für was' is regional or very casual.": "'Wofür' to normalna, neutralna forma; 'für was' jest regionalne albo bardzo swobodne.",
  "'Zeit mitbringen' — the honest warning. Open hours mean open-ended waiting.": "'Zeit mitbringen' — uczciwe ostrzeżenie. Godziny bez zapisów oznaczają czekanie bez końca.",
  "'zurückrufen' is separable: ich rufe dich zurück. 'mitten in was' (= in etwas) is casual spoken German; at work the same excuse is 'Ich bin gerade in einem Termin.'": "'zurückrufen' jest rozdzielnie złożone: ich rufe dich zurück. 'mitten in was' (= in etwas) to swobodna mowa niemiecka; w pracy ta sama wymówka brzmi 'Ich bin gerade in einem Termin.'",
  "'Zuschlagen' = to strike when a deal appears — THE verb for sale purchases, gaming or otherwise. Casual bragging register.": "'Zuschlagen' = skorzystać, gdy pojawi się okazja — TEN czasownik o zakupach na wyprzedaży, w grach i nie tylko. Swobodny rejestr przechwałki.",
  "\"Kiste\" is a crate or box, and colloquially any old thing. Say this before you sign for anything that looks tampered with.": "'Kiste' to skrzynka albo pudło, a potocznie byle co. Powiedz to, zanim pokwitujesz coś, co wygląda na naruszone.",
  "18+ conversational — the standard casual way to ask about turn-ons ('stehen auf + Akk'). Between partners or in open flirting, never at work.": "Rozmowa 18+ — standardowy, swobodny sposób pytania o to, co kogoś kręci ('stehen auf + biernik'). Między partnerami albo w otwartym flircie, nigdy w pracy.",
  "A broad casual check-in about life, work or whatever is currently going on. The situation decides how wide the answer should be.": "Szerokie, swobodne zapytanie o życie, pracę albo cokolwiek dzieje się teraz. Sytuacja decyduje, jak obszerna ma być odpowiedź.",
  "A broad casual question about someone's work, studies or life. It usually asks more than what they are doing this exact second.": "Szerokie, swobodne pytanie o czyjąś pracę, studia albo życie. Zwykle chodzi o coś więcej niż to, co ktoś robi w tej sekundzie.",
  "A broad catch-up question about someone's current life. 'zurzeit' means these days or at present, and 'so' keeps the question casual.": "Szerokie pytanie o bieżące życie. 'zurzeit' znaczy obecnie, a 'so' utrzymuje pytanie w swobodnym tonie.",
  "A casual event or venue question. 'mit wem' asks which person or group someone came with or is spending time with.": "Swobodne pytanie na imprezie albo w lokalu. 'mit wem' pyta, z jaką osobą albo grupą ktoś przyszedł lub spędza czas.",
  "A casual first-meeting question about whether someone comes from the local area. It is less broad than asking which country or city they come from.": "Swobodne pytanie przy pierwszym spotkaniu, czy ktoś jest z okolicy. Węższe niż pytanie o kraj albo miasto pochodzenia.",
  "A casual purpose question when someone has an object, tool, file or unusual plan.": "Swobodne pytanie o cel, gdy ktoś ma jakiś przedmiot, narzędzie, plik albo nietypowy plan.",
  "A casual question about an object when you do not know or do not need its exact name. 'Ding' is everyday but vague.": "Swobodne pytanie o przedmiot, gdy nie zna się albo nie potrzebuje jego dokładnej nazwy. 'Ding' jest codzienne, ale nieostre.",
  "A colloquial fixed expression. It is not sexual in this use.": "Utarte wyrażenie potoczne. W tym użyciu nie ma wydźwięku seksualnego.",
  "A common getting-to-know-you question when either work or study could fit. Avoid it if the setting makes the answer obvious.": "Częste pytanie na poznanie się, gdy w grę wchodzi praca albo studia. Odpuść je, jeśli sytuacja i tak zdradza odpowiedź.",
  "A common informal reassurance. It literally mentions your head, but the meaning is not to worry.": "Częste, nieformalne uspokojenie. Dosłownie mowa o głowie, ale sens brzmi: nie martw się.",
  "A common informal response to disappointing news or an annoying problem.": "Częsta, nieformalna reakcja na rozczarowujące wieści albo irytujący problem.",
  "A common shortened suggestion to avoid deciding too early. A complete version is 'Warten wir erst mal ab'.": "Częsta, skrócona propozycja, by nie decydować za wcześnie. Pełna wersja to 'Warten wir erst mal ab'.",
  "A common use of sammeln among friends, at work or in a family.": "Częste użycie sammeln wśród przyjaciół, w pracy lub w rodzinie.",
  "A considerate response to bad news when a casual reaction would feel too light.": "Taktowna odpowiedź na złe wieści, gdy swobodna reakcja wydawałaby się zbyt lekka.",
  "A direct informal question about ability. English keeps the main verb in its plain form after 'can': 'Can you do...?', never 'Can you to do...?'.": "Bezpośrednie, nieformalne pytanie o umiejętność. W angielskim po 'can' czasownik główny zostaje w formie podstawowej: 'Can you do...?', nigdy 'Can you to do...?'.",
  "A direct warning that a condition or necessary step cannot be skipped.": "Wyraźne ostrzeżenie, że warunku lub koniecznego kroku nie da się pominąć.",
  "A natural follow-up after meeting two friends. 'seid ihr' addresses both people together.": "Naturalne pytanie po spotkaniu dwojga przyjaciół. 'seid ihr' zwraca się do obojga naraz.",
  "A natural urgent warning. German can use this short phrase without a verb when the danger is obvious.": "Naturalne, pilne ostrzeżenie. Niemiecki potrafi obejść się bez czasownika, gdy niebezpieczeństwo jest oczywiste.",
  "A natural warning to an animal gulping food. The situation supplies the missing verb, so German keeps it short.": "Naturalne ostrzeżenie dla zwierzęcia, które połyka jedzenie. Sytuacja dostarcza brakującego czasownika, więc niemiecki zostaje krótki.",
  "A normal informal request for a very short wait. Add 'bitte' when you want it to sound softer.": "Zwykła, nieformalna prośba o krótką chwilę czekania. Dodaj 'bitte', by zabrzmiała łagodniej.",
  "A practical check that helps the group avoid stopping again once the task has begun.": "Praktyczne upewnienie się, dzięki któremu grupa nie musi znów przerywać po rozpoczęciu.",
  "A safety warning in frost, snow or freezing rain. 'glatt' does not always mean icy, so slippery is the broad translation.": "Ostrzeżenie o bezpieczeństwie przy mrozie, śniegu albo marznącym deszczu. 'glatt' nie zawsze znaczy oblodzony, dlatego szerokim tłumaczeniem jest śliski.",
  "A serious accusation, not casual criticism.": "Poważne oskarżenie, nie zdawkowa krytyka.",
  "A shade more emotional than 'keine Lust' — this is about your state, not the activity. Warning: between partners at night it means exactly what it means in English.": "Odrobinę bardziej emocjonalne niż 'keine Lust' — chodzi o twój stan, nie o czynność. Uwaga: między partnerami wieczorem znaczy dokładnie to, co po angielsku.",
  "A short warning after treatment or when a pet worries a sore spot. The object is obvious, so German leaves it out.": "Krótkie ostrzeżenie po zabiegu albo gdy zwierzę drapie bolące miejsce. Dopełnienie jest oczywiste, więc niemiecki je pomija.",
  "A shortened vulgar dismissal. It can be joking only between very close friends with the right tone; otherwise it is an insult.": "Skrócona, wulgarna odprawa. Jako żart przechodzi tylko wśród bardzo bliskich przyjaciół, przy właściwym tonie; poza tym to obelga.",
  "A standard informal request. The favour itself normally follows immediately.": "Standardowa, nieformalna prośba. Sama przysługa zwykle następuje od razu.",
  "A standard Monday small-talk question with friends, classmates and colleagues you know.": "Standardowe poniedziałkowe pytanie na rozgrzewkę wśród przyjaciół, kolegów z klasy i znajomych z pracy.",
  "A standing offer between partners or close friends; warm, no drama.": "Oferta, która zawsze obowiązuje — między partnerami lub bliskimi przyjaciółmi; ciepła, bez dramatu.",
  "A very common casual follow-up when the first topic is finished and you want the conversation to continue.": "Bardzo częste, swobodne pytanie na dokładkę, gdy pierwszy temat się wyczerpał, a rozmowa ma trwać.",
  "A very common informal way to check whether a day suits someone.": "Bardzo częsty, nieformalny sposób sprawdzenia, czy dany dzień komuś pasuje.",
  "abgefahren — driven off, worn. Also slang for 'amazing'; the tyre meaning is older.": "abgefahren — zjeżdżony, zużyty. W slangu też 'odjazdowy'; znaczenie o oponie jest starsze.",
  "Achtung! is the warning word; die Ampel = the traffic light, always feminine.": "Achtung! to słowo ostrzegawcze; die Ampel = sygnalizacja świetlna, zawsze rodzaju żeńskiego.",
  "Affectionate or dry, harmless — literally 'fun bird'. Said fondly, or deadpan when the joke was bad. Safe with anyone informal.": "Czułe albo suche, niegroźne — dosłownie 'ptak od żartów'. Mówione serdecznie albo bez wyrazu, gdy żart był kiepski. Bezpieczne z każdym w tonie nieformalnym.",
  "Affectionate teasing, harmless — partner, kids, close friends. Almost never stings; it implies fond exasperation, not stupidity.": "Czułe przekomarzanie, niegroźne — partner, dzieci, bliscy przyjaciele. Prawie nigdy nie boli; sugeruje serdeczne zniecierpliwienie, nie głupotę.",
  "Affectionate, harmless — for someone talking nonsense or clowning around. Partner, friends, kids. Warm, never a real insult.": "Czułe, niegroźne — o kimś, kto plecie bzdury albo błaznuje. Partner, przyjaciele, dzieci. Ciepłe, nigdy prawdziwa obelga.",
  "Afterwards": "Potem",
  "Agreeing": "Zgadzanie się",
  "Allotment neighbours — advisors, rivals and friends across one fence. Mostly all three.": "Sąsiedzi z działki — doradcy, rywale i przyjaciele przez jeden płot. Najczęściej wszystko naraz.",
  "Almost always plural; singular das Beziehungsproblem. Neutral, the word you use confiding in friends.": "Prawie zawsze w liczbie mnogiej; liczba pojedyncza das Beziehungsproblem. Neutralne, słowo używane w zwierzeniach przyjaciołom.",
  "also colloquially \"incredibly\": unwahrscheinlich gut": "potocznie także 'niesamowicie': unwahrscheinlich gut",
  "also colloquially \"massively\": tierisch gut": "potocznie także 'strasznie': tierisch gut",
  "always plural": "zawsze w liczbie mnogiej",
  "Among friends, immediately after the news. 'Mal' softens it into eager excitement, not a command.": "Wśród przyjaciół, zaraz po wiadomości. 'Mal' zmienia to w niecierpliwą ekscytację, nie w rozkaz.",
  "An informal reaction to a plan failing, something breaking or another everyday setback.": "Nieformalna reakcja na to, że plan się sypie, coś się psuje albo trafia się codzienny zawód.",
  "Anglicism, under-40 casual; scrollen is fully naturalized for everyone, doomscrollen still youth-flavoured": "Anglicyzm, swobodnie poniżej czterdziestki; scrollen jest u wszystkich w pełni przyswojone, doomscrollen wciąż brzmi młodzieżowo",
  "ANGRY — the final rung before consequences, and everyone hears it that way. Adults use it on each other too, where it lands as a real threat rather than a warning.": "GNIEWNE — ostatni szczebel przed konsekwencjami i wszyscy tak to słyszą. Dorośli mówią to również do siebie, gdzie brzmi raczej jak realna groźba niż ostrzeżenie.",
  "Ask two or more people for the story of how they first met. It can be about friends, a couple or colleagues.": "Zapytaj dwie lub więcej osób o historię ich pierwszego spotkania. Może chodzić o przyjaciół, parę albo współpracowników.",
  "Asking for the bill": "Prośba o rachunek",
  "At the table, informal. One guest: 'Greif zu!' Signals the eating may begin.": "Przy stole, nieformalnie. Do jednego gościa: 'Greif zu!' To znak, że można zacząć jeść.",
  "At the till": "Przy kasie",
  "aufblasen — inflating. 'Hilf mir mal' — the casual recruiting of bystanders.": "aufblasen — nadmuchiwać. 'Hilf mir mal' — swobodne werbowanie stojących obok.",
  "aufdrängen — pressing something on someone. The warning before every market stroll.": "aufdrängen — narzucać komuś coś. Ostrzeżenie przed każdym spacerem po targu.",
  "aufziehen — a storm pulling up. denn delivers the warning in plain word order.": "aufziehen — burza nadciąga. denn podaje ostrzeżenie w prostym szyku zdania.",
  "Aus der Kirche austreten = to formally leave the church. Casually, mal austreten = to nip to the loo.": "Aus der Kirche austreten = formalnie wystąpić z Kościoła. Swobodnie mal austreten = wyskoczyć do toalety.",
  "auslaufen — leaking out. 'hinüber sein' — colloquially beyond saving.": "auslaufen — wyciekać. 'hinüber sein' — potocznie: nie do uratowania.",
  "ausstrecken splits in the imperative; mal softens the order to a casual prompt. German uses die, not 'your', with body parts.": "ausstrecken rozdziela się w trybie rozkazującym; mal zmienia rozkaz w swobodną zachętę. Przy częściach ciała niemiecki używa die, a nie 'twój'.",
  "Banter": "Przekomarzanie",
  "beim Umzug = with the move. Moving house with friends (and pizza afterwards) is completely standard in Germany.": "beim Umzug = przy przeprowadzce. Przeprowadzka z przyjaciółmi (i pizza na koniec) jest w Niemczech zupełnie normalna.",
  "beraten — advising. 'einen' — the colloquial accusative of man.": "beraten — doradzać. 'einen' — potoczny biernik od man.",
  "Between friends: Kannst du mir zehn Euro borgen? Standard German prefers leihen.": "Wśród przyjaciół: Kannst du mir zehn Euro borgen? Niemiecki standardowy woli leihen.",
  "Blunt but completely normal between partners and friends — German directness in action": "Bez ogródek, ale między partnerami i przyjaciółmi zupełnie normalne — niemiecka bezpośredniość w praktyce",
  "Blunt but standard dismissal of a politician. Strong opinion, casual delivery — fine between partners and friends. '...von ihr' for her.": "Bez ogródek, ale standardowa odprawa dla polityka. Mocna opinia, swobodny ton — między partnerami i przyjaciółmi w porządku. '...von ihr' o niej.",
  "Blunt insult, literally a full fencepost. Friends-only register.": "Dosadna obelga, dosłownie cały słupek od płotu. Tylko wśród przyjaciół.",
  "Blunt self-criticism that admits your behaviour was bad. It can sound sincere among friends, but use a cleaner apology at work.": "Dosadna samokrytyka przyznająca, że twoje zachowanie było złe. Wśród przyjaciół może brzmieć szczerze, ale w pracy użyj czystszych przeprosin.",
  "borgen — the casual borrow-lend verb. die Leiter migrates between households like a shared pet.": "borgen — swobodny czasownik od pożyczania. die Leiter wędruje między domami jak wspólne zwierzę.",
  "Both a literal on-set announcement and a warning that everything from now on is Content; läuft = runs, the standard verb for recording devices.": "Zarazem dosłowna zapowiedź na planie i ostrzeżenie, że od teraz wszystko jest Contentem; läuft = działa, standardowy czasownik o urządzeniach nagrywających.",
  "bumming a cigarette; casual, smoker-to-smoker only": "sępienie papierosa; swobodnie, tylko palacz do palacza",
  "Buying time": "Granie na zwłokę",
  "Careful — between two people who might be dating, this IS the small confession, one step below 'Ich hab dich lieb'. Between friends it's plain and warm. Tone and timing carry the whole meaning.": "Ostrożnie — między dwojgiem ludzi, którzy może się spotykają, TO jest to małe wyznanie, stopień niżej niż 'Ich hab dich lieb'. Wśród przyjaciół jest zwyczajne i ciepłe. Ton i moment niosą całe znaczenie.",
  "Casual": "Swobodnie",
  "Casual — and ambiguous by design: 'zocken' means both gambling and video gaming. Among under-40s the default reading is gaming; in a casino context it's gambling.": "Swobodne — i celowo dwuznaczne: 'zocken' znaczy zarówno uprawiać hazard, jak i grać w gry wideo. Poniżej czterdziestki domyślnie chodzi o gry; w kontekście kasyna to hazard.",
  "Casual — Ding literally means 'thing'": "Swobodnie — Ding dosłownie znaczy 'rzecz'",
  "Casual — literally 'now we have the salad'": "Swobodnie — dosłownie 'teraz mamy sałatkę'",
  "Casual — literally 'that's not my beer'": "Swobodnie — dosłownie 'to nie moje piwo'",
  "Casual — literally 'you had pig'": "Swobodnie — dosłownie 'miałeś świnię'",
  "Casual agreement": "Swobodna zgoda",
  "Casual and dramatic; often frustration rather than literal loss of control.": "Swobodne i dramatyczne; częściej frustracja niż faktyczna utrata panowania.",
  "casual between friends; the English loans (Foundation, Concealer) are standard in German — French keeps 'fond de teint'": "swobodnie wśród przyjaciół; angielskie zapożyczenia (Foundation, Concealer) są w niemieckim standardem — francuski zachowuje 'fond de teint'",
  "Casual check-in mid-explanation.": "Swobodne upewnienie się w środku wyjaśnienia.",
  "casual clipping of 'Prominenter' — everyday word": "swobodny skrót od 'Prominenter' — słowo codzienne",
  "Casual complaint, one hour in. Someone packed too much Brotzeit.": "Swobodne narzekanie po godzinie. Ktoś spakował za dużo Brotzeit.",
  "casual compliment; stehen + dative = to suit someone": "swobodny komplement; stehen + celownik = komuś pasować",
  "Casual criticism, mild to sharp depending on tone — from amused head-shake about a friend to genuine warning about a date.": "Swobodna krytyka, od łagodnej po ostrą zależnie od tonu — od rozbawionego kręcenia głową nad przyjacielem po poważne ostrzeżenie przed randką.",
  "Casual date invite (better than formal 'Möchten Sie...')": "Swobodne zaproszenie na randkę (lepsze niż formalne 'Möchten Sie...')",
  "Casual dating vocabulary with friends. The verb is fully germanized: ghosten, geghostet.": "Swobodne słownictwo randkowe wśród przyjaciół. Czasownik jest w pełni zniemczony: ghosten, geghostet.",
  "Casual dating-discourse talk, mostly among friends dissecting someone's behaviour. Anglicism, feminine in German: die Red Flag (French keeps it masculine: un red flag).": "Swobodna rozmowa o randkowaniu, najczęściej wśród przyjaciół rozbierających czyjeś zachowanie na czynniki. Anglicyzm, w niemieckim rodzaju żeńskiego: die Red Flag (francuski zachowuje rodzaj męski: un red flag).",
  "casual Denglisch — 'Ich hab gecodet' is completely normal among devs": "swobodny denglisch — 'Ich hab gecodet' jest wśród programistów zupełnie normalne",
  "Casual directive": "Swobodne polecenie",
  "Casual everyday goodbye — used everywhere in Germany": "Swobodne, codzienne pożegnanie — używane w całych Niemczech",
  "Casual everyday reassurance": "Swobodne, codzienne uspokojenie",
  "Casual favour between friends (du). 'drüberschauen' = give it a quick once-over.": "Swobodna przysługa wśród przyjaciół (du). 'drüberschauen' = szybko coś przejrzeć.",
  "Casual for playing video games; in money contexts it means to gamble.": "Swobodnie o graniu w gry wideo; w kontekście pieniędzy oznacza hazard.",
  "Casual goodbye — borrowed from Italian, extremely popular in Germany": "Swobodne pożegnanie — zapożyczone z włoskiego, bardzo popularne w Niemczech",
  "casual gym slang for lifting weights; 'pumpen gehen'": "swobodny slang siłowni o podnoszeniu ciężarów; 'pumpen gehen'",
  "Casual idiom, literally 'sponge over it' (wiping the slate): declares a small quarrel officially closed. Friends and partners, minor stuff only — don't 'Schwamm drüber' a real hurt.": "Swobodny idiom, dosłownie 'gąbką po tym' (starcie tablicy): ogłasza małą kłótnię za oficjalnie zamkniętą. Przyjaciele i partnerzy, tylko przy drobiazgach — prawdziwej krzywdy się nie ściera.",
  "Casual imperative 'Investier' is common spoken German; full written form is 'Investiere'.": "Swobodny tryb rozkazujący 'Investier' jest częsty w mowie; pełna forma pisana to 'Investiere'.",
  "Casual imperative 'Markier' is common in voice chat; after 'damit', 'verlaufen' goes to the end.": "Swobodny tryb rozkazujący 'Markier' jest częsty na czacie głosowym; po 'damit' 'verlaufen' idzie na koniec.",
  "Casual imperative 'Setz' is short for 'Setze'; 'am' contracts dative 'an dem'.": "Swobodny tryb rozkazujący 'Setz' to skrót od 'Setze'; 'am' ściąga celownik 'an dem'.",
  "Casual imperative of separable 'hinzufügen' is 'Füg ... hinzu'; the person being added is accusative 'mich'.": "Swobodny tryb rozkazujący od rozdzielnego 'hinzufügen' to 'Füg ... hinzu'; dodawana osoba stoi w bierniku: 'mich'.",
  "Casual invite": "Swobodne zaproszenie",
  "Casual kitchen-table economics; sich lohnen = to be worth it — very high-frequency verb": "Swobodna ekonomia przy kuchennym stole; sich lohnen = opłacać się — bardzo częsty czasownik",
  "casual loanword; einkaufen is the German verb": "swobodne zapożyczenie; einkaufen to niemiecki czasownik",
  "Casual media criticism among friends; sich aufregen über = to get worked up about — essential B1 verb": "Swobodna krytyka mediów wśród przyjaciół; sich aufregen über = denerwować się czymś — kluczowy czasownik na poziomie B1",
  "casual money-vent to friends, du-register — the one informal line in this pack; the bank formally calls it 'Dispositionskredit'": "swobodne narzekanie na pieniądze wśród przyjaciół, rejestr na ty — jedyna nieformalna linijka w tym zestawie; bank nazywa to oficjalnie 'Dispositionskredit'",
  "Casual opener": "Swobodny wstęp do rozmowy",
  "Casual opener for close friends": "Swobodny wstęp wśród bliskich przyjaciół",
  "Casual opinion": "Swobodna opinia",
  "Casual pointing-at-things question with friends — how learners actually acquire everyday nouns. 'das Ding' = thingy.": "Swobodne pytanie ze wskazaniem palcem, wśród przyjaciół — tak uczący się naprawdę przyswajają codzienne rzeczowniki. 'das Ding' = ten dinks.",
  "Casual positive update": "Swobodna, dobra wiadomość",
  "Casual pub folklore — 'angeblich' (supposedly) does the honest work here. It's a myth: the Konterbier only postpones the hangover, and needing one regularly is a recognised warning sign.": "Swobodny folklor knajpiany — 'angeblich' (rzekomo) wykonuje tu uczciwą robotę. To mit: Konterbier tylko odracza kaca, a regularna potrzeba takiego piwa to uznany sygnał ostrzegawczy.",
  "Casual register inside student life; durcharbeiten = work through without a break.": "Swobodny rejestr ze studenckiego życia; durcharbeiten = pracować bez przerwy.",
  "Casual reminiscing; 'was los sein' = something happening.": "Swobodne wspominanie; 'was los sein' = coś się dzieje.",
  "Casual reply": "Swobodna odpowiedź",
  "Casual request": "Swobodna prośba",
  "Casual request to repeat": "Swobodna prośba o powtórzenie",
  "Casual self-intro": "Swobodne przedstawienie się",
  "Casual slang command": "Swobodne, slangowe polecenie",
  "Casual slang farewell": "Swobodne, slangowe pożegnanie",
  "Casual speech drops the prefix: you 'schieben' a plan with a friend, you 'verschieben' a Termin with a doctor or a client. 'auf' + accusative for the new date.": "W swobodnej mowie odpada przedrostek: plan z przyjacielem się 'schiebt', a Termin u lekarza czy klienta się 'verschiebt'. 'auf' + biernik przy nowej dacie.",
  "Casual spoken imperative 'Markier' is common; the tool follows dative 'mit einem Bleistift'.": "Swobodny, mówiony tryb rozkazujący 'Markier' jest częsty; narzędzie idzie w celowniku 'mit einem Bleistift'.",
  "Casual spoken; 'ich wechsel' instead of textbook 'ich wechsle' is normal in speech. 'Die Klasse' is standard, no English loan here.": "Swobodna mowa; 'ich wechsel' zamiast podręcznikowego 'ich wechsle' jest w mowie normalne. 'Die Klasse' to standard, żadnego angielskiego zapożyczenia.",
  "casual spoken; from sich fertig machen = sich zurechtmachen": "swobodna mowa; od sich fertig machen = szykować się",
  "casual spoken; the machen-lassen pattern for anything done at a salon": "swobodna mowa; konstrukcja machen-lassen dla wszystkiego, co robi się w salonie",
  "casual, admiring; 'definiert' = lean and cut, more technical": "swobodnie, z podziwem; 'definiert' = wyrzeźbiony, bardziej fachowo",
  "Casual, concerned — 'die Spielothek' (slot arcade) sits several rungs below 'das Casino' in register and respectability; the sentence itself signals worry.": "Swobodnie i z troską — 'die Spielothek' (salon automatów) stoi o kilka szczebli niżej niż 'das Casino' pod względem rejestru i renomy; samo zdanie sygnalizuje niepokój.",
  "Casual, enthusiastic. 'Der Wahnsinn' is the go-to superlative among friends.": "Swobodnie, z entuzjazmem. 'Der Wahnsinn' to superlatyw pierwszego wyboru wśród przyjaciół.",
  "casual, everyday; der Lidstrich is the German word, Eyeliner is what people say": "swobodnie, na co dzień; der Lidstrich to niemieckie słowo, ale ludzie mówią Eyeliner",
  "Casual, exasperated. Standard lakeside-evening lament; 'fressen' (animal eating) makes it vivid.": "Swobodnie i z irytacją. Standardowe narzekanie wieczorem nad jeziorem; 'fressen' (o jedzeniu zwierząt) czyni to obrazowym.",
  "Casual, mild — amused disbelief among friends and family. Friendly in tone, but too blunt for strangers or superiors.": "Swobodne, łagodne — rozbawione niedowierzanie wśród przyjaciół i rodziny. Przyjazne w tonie, ale zbyt bezpośrednie wobec obcych i przełożonych.",
  "Casual, mild — the adjective version, interchangeable with 'einen Kater haben'. Fine in any informal setting.": "Swobodne, łagodne — wersja przymiotnikowa, wymienna z 'einen Kater haben'. W każdej nieformalnej sytuacji w porządku.",
  "Casual, mild — the standard morning-after sentence among friends and relaxed colleagues. 'fett' intensifies it.": "Swobodne, łagodne — standardowe zdanie następnego poranka wśród przyjaciół i wyluzowanych współpracowników. 'fett' je wzmacnia.",
  "Casual, mild — the standard verdict on a Flachwitz. Said with a groan and half a smile; friends and colleagues.": "Swobodne, łagodne — standardowy werdykt o Flachwitz. Mówione z jękiem i półuśmiechem; przyjaciele i współpracownicy.",
  "Casual, playful — everyday micro-betting between friends. 'die Wette' = the bet; the structure was immortalized by the TV show 'Wetten, dass..?'.": "Swobodne, żartobliwe — codzienny mały zakład wśród przyjaciół. 'die Wette' = zakład; strukturę uwiecznił program telewizyjny 'Wetten, dass..?'.",
  "Casual, relieved-triumphant, to friends. 'überstehen' = to survive something unpleasant.": "Swobodnie, z ulgą i triumfem, wśród przyjaciół. 'überstehen' = przetrwać coś nieprzyjemnego.",
  "Casual, relieved. 'Kriegen' is the everyday spoken 'bekommen'. Rare Bahn stories have happy endings — savour them.": "Swobodne, z ulgą. 'Kriegen' to codzienne, mówione 'bekommen'. Rzadko historie kolejowe kończą się dobrze — delektuj się nimi.",
  "Casual, teasing — literally 'do you have tomatoes on your eyes?'": "Swobodnie, żartobliwie — dosłownie 'masz pomidory na oczach?'",
  "Casual, to companions. Famous last words on any hike.": "Swobodnie, do towarzyszy. Słynne ostatnie słowa na każdej wędrówce.",
  "Casual, to friends/partner. 'An den See fahren' is the German summer ritual — pack the Picknick.": "Swobodnie, do przyjaciół albo partnera. 'An den See fahren' to niemiecki rytuał lata — spakuj Picknick.",
  "Casual, to one person (du) — group: Lasst uns anfangen; formal: Fangen wir an": "Swobodnie, do jednej osoby (du) — do grupy: Lasst uns anfangen; oficjalnie: Fangen wir an",
  "Casual, universal. The standard excuse to step outside — nobody questions frische Luft.": "Swobodne, uniwersalne. Standardowa wymówka, by wyjść na zewnątrz — frische Luft nikt nie kwestionuje.",
  "Casual, wry — literally 'life is no pony farm'": "Swobodnie, z przekąsem — dosłownie 'życie to nie kucykowa farma'",
  "casual, younger speakers; Hautpflege is the more formal word": "swobodnie, raczej młodsi mówiący; Hautpflege to słowo bardziej oficjalne",
  "Casual; 'die Pause' is the break, 'der Pausenhof' the yard it happens on.": "Swobodnie; 'die Pause' to przerwa, 'der Pausenhof' to boisko, na którym się odbywa.",
  "casual; 'platt' = wiped out, works for any exhaustion": "swobodnie; 'platt' = wykończony, pasuje do każdego wyczerpania",
  "casual; 'Proteinshake' works too": "swobodnie; 'Proteinshake' też działa",
  "casual; 'pumpen gehen' marks you as a weights person, not a treadmill person": "swobodnie; 'pumpen gehen' oznacza cię jako osobę od ciężarów, nie od bieżni",
  "casual; 'sich etwas ziehen' = to pull a muscle": "swobodnie; 'sich etwas ziehen' = naciągnąć sobie mięsień",
  "Casual; ackern makes the work sound tiring or relentless.": "Swobodnie; ackern sprawia, że praca brzmi na męczącą i nieustanną.",
  "Casual; adults admit it with a grin": "Swobodnie; dorośli przyznają się do tego z uśmiechem",
  "casual; literally also to plough a field": "swobodnie; dosłownie także orać pole",
  "casual; stechen lassen (literally 'have it pricked') is the idiomatic verb for tattoos": "swobodnie; stechen lassen (dosłownie 'dać się nakłuć') to idiomatyczny czasownik o tatuażach",
  "casual; the question everyone asks": "swobodnie; pytanie, które zadają wszyscy",
  "casual; the standard (optimistic) answer": "swobodnie; standardowa (optymistyczna) odpowiedź",
  "Casual; the way adults confess it with a grin.": "Swobodnie; tak dorośli przyznają się do tego z uśmiechem.",
  "casual: kicken gehen = to go and play football": "swobodnie: kicken gehen = iść pograć w piłkę",
  "Casual. 'Baden gehen' = swim outdoors (lake, sea); 'schwimmen gehen' leans towards the pool.": "Swobodnie. 'Baden gehen' = kąpiel na świeżym powietrzu (jezioro, morze); 'schwimmen gehen' bardziej o basenie.",
  "Casual. 'Eine Runde drehen' = do a loop; works for walks, bike rides or a quick drive.": "Swobodnie. 'Eine Runde drehen' = zrobić kółko; pasuje do spaceru, przejażdżki rowerem albo krótkiej jazdy autem.",
  "Casual. 'Sich etwas holen' = to catch/get something (sunburn, a cold).": "Swobodnie. 'Sich etwas holen' = złapać coś (oparzenie słoneczne, przeziębienie).",
  "casually clipped to 'der Elfer'": "potocznie skracane do 'der Elfer'",
  "Chores": "Obowiązki domowe",
  "close friends only — sharing a cigarette or vape": "tylko wśród bliskich przyjaciół — dzielenie się papierosem lub e-papierosem",
  "Coarse — stronger than 'das ist mir egal'. Friends only; rude if said to a teacher, boss, or official.": "Dosadne — mocniejsze niż 'das ist mir egal'. Tylko wśród przyjaciół; wobec nauczyciela, szefa czy urzędnika niegrzeczne.",
  "Coarse and common among friends. It can sound confrontational when said angrily.": "Dosadne i częste wśród przyjaciół. Powiedziane ze złością może zabrzmieć konfrontacyjnie.",
  "Coarse-casual — 'forget it, who cares'. Banter-safe among friends; not for formal company.": "Dosadne i swobodne — 'daj spokój, kogo to obchodzi'. W żartach wśród przyjaciół tak; w oficjalnym gronie nie.",
  "coden is casual Denglisch; completely normal in the du-form dev crowd.": "coden to swobodny denglisch; zupełnie normalny w środowisku programistów na ty.",
  "Colloquial (Kopfnuss = headbutt/noogie)": "Potocznie (Kopfnuss = uderzenie głową lub prztyczek w głowę)",
  "Colloquial and strong; covers verbal and psychological cruelty, not just physical.": "Potoczne i mocne; obejmuje okrucieństwo słowne i psychiczne, nie tylko fizyczne.",
  "Colloquial and strong; verbal or psychological cruelty": "Potoczne i mocne; okrucieństwo słowne lub psychiczne",
  "colloquial and very common; 'Funkstille' is the go-to image for a communication freeze in families": "potoczne i bardzo częste; 'Funkstille' to typowy obraz zamrożonej komunikacji w rodzinach",
  "colloquial anglicism (Duden-listed); marketing and social media register": "potoczny anglicyzm (odnotowany w Dudenie); rejestr marketingu i mediów społecznościowych",
  "Colloquial but harmless — safe with colleagues and family.": "Potoczne, ale niegroźne — bezpieczne wśród współpracowników i rodziny.",
  "Colloquial but harmless — the polite cousin of 'verarschen'. Safe with colleagues, in-laws, anyone informal.": "Potoczne, ale niegroźne — grzeczny kuzyn 'verarschen'. Bezpieczne ze współpracownikami, teściami, każdym w tonie nieformalnym.",
  "Colloquial but serious; 'zu dritt' = three of them together.": "Potoczne, ale poważne; 'zu dritt' = we trójkę.",
  "Colloquial combo of Ja + Nein": "Potoczne połączenie Ja + Nein",
  "Colloquial fixed expression meaning that someone loses their nerve or retreats. It is not sexual in this use.": "Utarte wyrażenie potoczne o tym, że ktoś traci odwagę albo się wycofuje. W tym użyciu nie ma wydźwięku seksualnego.",
  "Colloquial idiom, mild — groaning at a joke everyone has heard a hundred times. Friends and casual colleagues.": "Potoczny idiom, łagodny — jęk nad żartem, który wszyscy słyszeli sto razy. Przyjaciele i wyluzowani współpracownicy.",
  "colloquial intensifier: mächtig stolz = mighty proud": "potoczny wzmacniacz: mächtig stolz = ogromnie dumny",
  "Colloquial short form of herauskommen; also used of films, products or models being released.": "Potoczna forma skrócona od herauskommen; używana też o premierach filmów, produktów czy modeli.",
  "Colloquial shortcut": "Potoczny skrót",
  "Colloquial, mild — casual settings with friends, family, relaxed colleagues. Often typed in chats too.": "Potoczne, łagodne — swobodne sytuacje z przyjaciółmi, rodziną, wyluzowanymi współpracownikami. Często też wpisywane na czacie.",
  "Colloquial, mild — gasped mid-laughter or typed in chats. Friends, family, relaxed colleagues.": "Potoczne, łagodne — wyrzucone w środku śmiechu albo wpisane na czacie. Przyjaciele, rodzina, wyluzowani współpracownicy.",
  "colloquial, what children do in sand; graben is neutral": "potocznie, to, co dzieci robią w piasku; graben jest neutralne",
  "Colloquial; 'sich prügeln' is physical, much stronger than 'sich streiten'.": "Potoczne; 'sich prügeln' jest fizyczne, dużo mocniejsze niż 'sich streiten'.",
  "colloquial; invariable: ein super Film": "potocznie; nieodmienne: ein super Film",
  "colloquially also snappy, punchy (UI, prose, deadlines)": "potocznie także zwięzły, dosadny (interfejsy, teksty, terminy)",
  "colloquially shortened to 'das Gespräch'": "potocznie skracane do 'das Gespräch'",
  "Colloquially, Der Hammer! means amazing or awesome — the literal tool is the primary card meaning.": "Potocznie Der Hammer! znaczy rewelacyjny — podstawowym znaczeniem karty jest jednak narzędzie.",
  "common and informal; can describe a person, idea or situation": "częste i nieformalne; może opisywać osobę, pomysł lub sytuację",
  "Common complaint": "Częsta skarga",
  "Common slang reaction": "Częsta reakcja w slangu",
  "Common slang reaction to bad news — mies = lousy, shabby": "Częsta slangowa reakcja na złe wieści — mies = kiepski, marny",
  "Confirming": "Potwierdzanie",
  "Consent": "Zgoda",
  "Consent — always check": "Zgoda — zawsze pytaj",
  "Conversational geopolitics with an opinion baked in — fine among friends, spicier at work": "Geopolityka w rozmowie, z wbudowaną opinią — wśród przyjaciół w porządku, w pracy bardziej zapalne",
  "dark humour among friends; 'Echsenmenschen' is the go-to absurd-conspiracy reference": "czarny humor wśród przyjaciół; 'Echsenmenschen' to typowe odniesienie do absurdalnych spisków",
  "das Band — the conveyor. Braking on it is the one real mistake to avoid.": "das Band — taśma. Hamowanie na niej to jedyny prawdziwy błąd, którego należy unikać.",
  "das Bügeleisen — the iron. The warning every household repeats.": "das Bügeleisen — żelazko. Ostrzeżenie powtarzane w każdym domu.",
  "das Halbjahreszeugnis — the February report. The early warning system.": "das Halbjahreszeugnis — świadectwo lutowe. System wczesnego ostrzegania.",
  "Das hängt davon ab = it depends. Casually, mit Freunden abhängen = to hang out.": "Das hängt davon ab = to zależy. Swobodnie mit Freunden abhängen = spędzać czas ze znajomymi.",
  "das Profil — the tread. 'ist runter' — worn away; casual passive Germany runs on.": "das Profil — bieżnik. 'ist runter' — starty; swobodna strona bierna, na której jeżdżą Niemcy.",
  "das Rücklicht — the rear light. 'nur noch schwach' — the warning phase before darkness.": "das Rücklicht — tylne światło. 'nur noch schwach' — faza ostrzegawcza przed ciemnością.",
  "das Spritgeld — the fuel share. Simple beats fair-to-the-cent; friendships prefer round numbers.": "das Spritgeld — składka na paliwo. Prosto bije uczciwie co do centa; przyjaźnie wolą okrągłe liczby.",
  "das Teil — the casual word for any piece of clothing. The rule that prevents the pink wash.": "das Teil — swobodne słowo na dowolną część garderoby. Zasada, która ratuje pranie przed różem.",
  "das Wartezimmer — from the doctor pack, considerably louder. Cats sit high; dogs make friends.": "das Wartezimmer — z zestawu o lekarzu, znacznie głośniejsza. Koty siedzą wysoko; psy zawierają przyjaźnie.",
  "Dating": "Randki",
  "Deadpan sarcasm, mild — the everyday ironic groan at bad news. Universal: friends, family, muttered at work.": "Sucha ironia, łagodna — codzienne ironiczne westchnienie nad złymi wieściami. Uniwersalne: przyjaciele, rodzina, mruknięte w pracy.",
  "Deliberately vague — it lets both sides keep it casual. 'was' here is short for 'etwas'.": "Celowo nieokreślone — pozwala obu stronom zachować swobodę. 'was' to tu skrót od 'etwas'.",
  "Denglish gym slang, completely standard between lifters; more formal: 'Kannst du mir Hilfestellung geben?'": "Denglishowy slang siłowni, wśród ćwiczących zupełnie standardowy; bardziej oficjalnie: 'Kannst du mir Hilfestellung geben?'",
  "der Aszendent — the follow-up question that separates casual from committed.": "der Aszendent — dopytanie, które oddziela ciekawskich od naprawdę zaangażowanych.",
  "der Helferkreis — the informal volunteer group, common in refugee and neighbourhood support.": "der Helferkreis — nieformalna grupa wolontariuszy, częsta w pomocy uchodźcom i sąsiedzkiej.",
  "der Platten — the flat tyre, colloquial and universal. The commute's classic opening line.": "der Platten — złapana guma, potocznie i wszędzie zrozumiale. Klasyczne otwarcie rozmowy o dojazdach.",
  "der Strafzettel, colloquially das Knöllchen = parking ticket": "der Strafzettel, potocznie das Knöllchen = mandat za parkowanie",
  "Desire": "Pragnienie",
  "die Abmahnung — the warning shot, at work or over copyright. Serious, not final.": "die Abmahnung — strzał ostrzegawczy, w pracy albo w sprawach praw autorskich. Poważny, ale nie ostateczny.",
  "die Abmahnung — the written warning. Serious, but far from a dismissal.": "die Abmahnung — pisemne upomnienie. Poważne, ale daleko mu do zwolnienia.",
  "die Hausnummer — colloquial for a rough figure. More with a role change.": "die Hausnummer — potocznie o orientacyjnej kwocie. Więcej, gdy zmienia się stanowisko.",
  "die Jugendfeuerwehr — where most volunteers begin. Knots, hoses and friendships.": "die Jugendfeuerwehr — tam zaczyna większość ochotników. Węzły, węże i przyjaźnie.",
  "die Kantine — the subsidised lunch. The invitation that builds actual friendships.": "die Kantine — dofinansowany obiad. Zaproszenie, z którego rodzą się prawdziwe przyjaźnie.",
  "die Lawine — the avalanche. The warning is not decorative.": "die Lawine — lawina. To ostrzeżenie nie jest ozdobą.",
  "Direct and neutral: 'Ich bin schwanger.' Colloquially, 'schwanger von ihm' names the father.": "Wprost i neutralnie: 'Ich bin schwanger.' Potocznie 'schwanger von ihm' wskazuje ojca.",
  "drohen with a thing as subject = to loom/threaten to occur: Dehydrierung droht. sonst carries the warning.": "drohen z rzeczą jako podmiotem = grozić, nadciągać: Dehydrierung droht. sonst niesie ostrzeżenie.",
  "du-form for friends and partners. With strangers or officials: 'Können Sie das bitte wiederholen?'": "Forma na ty dla przyjaciół i partnerów. Wobec obcych albo urzędników: 'Können Sie das bitte wiederholen?'",
  "düngen = to fertilize; der Dünger = fertilizer. Du register — said between family/friends": "düngen = nawozić; der Dünger = nawóz. Rejestr na ty — mówione w rodzinie i wśród przyjaciół",
  "eh = anyway / in any case (colloquial 'ohnehin')": "eh = i tak / tak czy owak (potocznie 'ohnehin')",
  "eine Runde schmeißen — literally throwing a round. Casual, generous, slightly theatrical.": "eine Runde schmeißen — dosłownie rzucić kolejkę. Swobodnie, hojnie, odrobinę teatralnie.",
  "Emergency": "Nagły wypadek",
  "Emphasis": "Podkreślenie",
  "Emphatic casual yes": "Dobitne, swobodne tak",
  "Encouragement between friends or from a partner — the compliment learners most want to hear.": "Zachęta wśród przyjaciół albo od partnera — komplement, który uczący się najbardziej chcą usłyszeć.",
  "Enemy info": "Informacja o wrogu",
  "English loan, fully naturalized and plural; 'doch' makes it dismissive — casual register": "zapożyczenie z angielskiego, w pełni przyswojone i w liczbie mnogiej; 'doch' nadaje lekceważący ton — rejestr swobodny",
  "Enthusiastic yes": "Entuzjastyczne tak",
  "Essential": "Niezbędne",
  "everyday casual word; also means the stubbed-out butt": "codzienne, swobodne słowo; oznacza też zgaszony niedopałek",
  "Everyday colloquial spelling of nichts": "Codzienna, potoczna pisownia nichts",
  "Everyday connection method (slang 'schreib mir')": "Codzienny sposób na kontakt (slangowo 'schreib mir')",
  "Everyday criticism, medium weight; fine in casual talk about colleagues or exes.": "Codzienna krytyka średniego kalibru; w swobodnej rozmowie o współpracownikach albo byłych jest w porządku.",
  "Everyday office and friend request; rüberschicken (send over) is the casual variant.": "Codzienna prośba w biurze i wśród przyjaciół; rüberschicken (przesłać) to wariant swobodny.",
  "Everyday slang (Bock haben)": "Codzienny slang (Bock haben)",
  "Everyday slang (spendieren = to treat)": "Codzienny slang (spendieren = postawić, zafundować)",
  "Excited announcement to friends and family. Once the context is clear, everyone just says 'Gespräch'.": "Podekscytowana wiadomość dla przyjaciół i rodziny. Gdy kontekst jest jasny, wszyscy mówią po prostu 'Gespräch'.",
  "Extremely common in speech as a hedge: Das ist quasi dasselbe. Latin by origin, fully casual in use.": "Bardzo częste w mowie jako złagodzenie: Das ist quasi dasselbe. Pochodzenia łacińskiego, w użyciu zupełnie swobodne.",
  "Facharzt = specialist; colloquially also \"einen Termin ausmachen\"": "Facharzt = lekarz specjalista; potocznie także 'einen Termin ausmachen'",
  "Falschparken = illegal/incorrect parking": "Falschparken = parkowanie niezgodne z przepisami",
  "Family": "Rodzina",
  "Famous last words — friends will quote it back at you for months.": "Słynne ostatnie słowa — przyjaciele będą ci to cytować przez miesiące.",
  "Farewell": "Pożegnanie",
  "Feeling": "Uczucie",
  "feiern = to celebrate, colloquially 'to love something'; very current usage.": "feiern = świętować, potocznie też 'uwielbiać coś'; bardzo aktualne użycie.",
  "fett = huge (colloquial intensifier); standard dev talk, not rude.": "fett = ogromny (potoczny wzmacniacz); zwykły żargon programistów, nie jest niegrzeczny.",
  "Finding help": "Szukanie pomocy",
  "firm but civil pushback; the 'doch längst' signals mild exasperation — fine with family, friends, colleagues": "stanowczy, ale kulturalny sprzeciw; 'doch längst' sygnalizuje lekkie zniecierpliwienie — w rodzinie, wśród przyjaciół i kolegów w porządku",
  "Fixed casual set expression; already short, so no further clipping.": "Utarte, swobodne wyrażenie; już krótkie, więc bez dalszego skracania.",
  "flach and steil around dahinter — the swimming-pool warning as a geometry lesson.": "flach i steil wokół dahinter — ostrzeżenie z basenu jako lekcja geometrii.",
  "Flight status update": "Status lotu",
  "Flirting": "Flirtowanie",
  "Formal": "Formalne",
  "Frustrated, to friends. 'schon wieder' carries the job-hunt fatigue.": "Sfrustrowane, wśród przyjaciół. 'schon wieder' niesie zmęczenie szukaniem pracy.",
  "geblitzt werden = to get caught by a speed camera — the standard colloquial verb for it": "geblitzt werden = zostać złapanym przez fotoradar — standardowy potoczny czasownik na to",
  "Gen-Z": "Gen Z",
  "Genuine compliment between friends; on a date it's practically flirting.": "Prawdziwy komplement wśród przyjaciół; na randce to praktycznie flirt.",
  "gereizt — irritable, like a nerve already touched. Fair warning to the room.": "gereizt — poirytowany, jak już drażniony nerw. Uczciwe ostrzeżenie dla wszystkich w pokoju.",
  "gib — du-imperative of geben with vowel change; mal keeps it casual, not bossy.": "gib — tryb rozkazujący na ty od geben z przegłosem; mal zachowuje swobodę zamiast rozkazu.",
  "Greeting": "Powitanie",
  "Grufti = colloquial for goth (from Gruft = tomb/crypt)": "Grufti = potocznie o gotach (od Gruft = krypta, grobowiec)",
  "Gunsmith": "Rusznikarz",
  "Half-joking household rule for the unsortable. Colloquial, said with a shrug.": "Na wpół żartobliwa domowa zasada na wszystko, czego nie da się posegregować. Potoczne, mówione ze wzruszeniem ramion.",
  "half-joking quitter's line; 'ich schwör' is casual spoken German": "na wpół żartobliwa deklaracja rzucenia czegoś; 'ich schwör' to swobodna mowa niemiecka",
  "hol mal = casual imperative; note 'das Licht geht nicht' would mean the lamp itself is broken, not a power cut": "hol mal = swobodny tryb rozkazujący; uwaga: 'das Licht geht nicht' znaczyłoby, że zepsuta jest sama lampa, a nie że nie ma prądu",
  "Hopeful repair language. 'Hinkriegen' is colloquial and warm — much more natural than 'reparieren'.": "Pełen nadziei język naprawy. 'Hinkriegen' jest potoczne i ciepłe — dużo naturalniejsze niż 'reparieren'.",
  "How you confess a current obsession. 'Auf Dauerschleife' = on endless loop; casual, very common.": "Tak przyznaje się do bieżącej obsesji. 'Auf Dauerschleife' = w nieskończonej pętli; swobodne, bardzo częste.",
  "idiomatic, informal": "idiomatyczne, nieformalne",
  "Im Alter von 30 = at the age of 30. As an exclamation, Alter! = dude! — very casual.": "Im Alter von 30 = w wieku 30 lat. Jako okrzyk Alter! = stary! — bardzo swobodne.",
  "in casual speech often shortened to was: Hast du was gehört?": "w swobodnej mowie często skracane do was: Hast du was gehört?",
  "In the moment": "W tej chwili",
  "Informal": "Nieformalne",
  "Informal — friends only": "Nieformalne — tylko wśród przyjaciół",
  "Informal — the spoken contraction you'll usually hear": "Nieformalne — mówiona forma ściągnięta, którą zwykle usłyszysz",
  "Informal — to strangers or staff say: Sprechen Sie Englisch?": "Nieformalne — do obcych lub obsługi mów: Sprechen Sie Englisch?",
  "Informal and rude: jemandem den Stinkefinger zeigen.": "Nieformalne i niegrzeczne: jemandem den Stinkefinger zeigen.",
  "Informal and warm, mostly southern. 'Grüß Gott' is its formal, Bavarian and Austrian cousin.": "Nieformalne i ciepłe, głównie na południu. 'Grüß Gott' to jego oficjalny, bawarsko-austriacki kuzyn.",
  "Informal imperative of separable 'ablehnen' is 'Lehn ... ab'; after 'wenn', 'kennst' goes to the end.": "Nieformalny tryb rozkazujący od rozdzielnego 'ablehnen' to 'Lehn ... ab'; po 'wenn' 'kennst' idzie na koniec.",
  "Informal imperative of separable 'aufheben': 'Heb ... auf'; the full written form is 'Hebe'.": "Nieformalny tryb rozkazujący od rozdzielnego 'aufheben': 'Heb ... auf'; pełna forma pisana to 'Hebe'.",
  "informal loan from English; das Okay – the go-ahead": "nieformalne zapożyczenie z angielskiego; das Okay – zielone światło",
  "Informal reply — with Sie say: Und Ihnen?": "Nieformalna odpowiedź — przy Sie mówi się: Und Ihnen?",
  "Informal term for a friend": "Nieformalne określenie przyjaciela",
  "informal, e.g. eine brenzlige Situation": "nieformalne, np. eine brenzlige Situation",
  "informal; the standard German way to say someone drifted off into conspiracy land": "nieformalne; standardowy niemiecki sposób powiedzenia, że ktoś odpłynął w stronę spisków",
  "Introducing": "Przedstawianie się",
  "justifying one more — works for cigarettes and beers alike; very casual": "usprawiedliwienie dla jeszcze jednego — pasuje i do papierosów, i do piwa; bardzo swobodne",
  "kicken — casual football. der Bolzplatz — the scuffed pitch every neighbourhood has.": "kicken — piłka na luzie. der Bolzplatz — wydeptane boisko, jakie ma każda dzielnica.",
  "klamm — damp, and colloquially short of cash. Honest without being dramatic.": "klamm — wilgotny, a potocznie: bez grosza. Szczere, bez dramatyzowania.",
  "klingen — sounding. The honest warning given to every violin household's neighbours.": "klingen — brzmieć. Uczciwe ostrzeżenie dla sąsiadów każdego domu ze skrzypcami.",
  "knapp bei Kasse — tight at the till. The honest sentence that friends answer with einladen.": "knapp bei Kasse — krucho w kasie. Szczere zdanie, na które przyjaciele odpowiadają einladen.",
  "knapp bei Kasse sein = to be short of money; casual register, said among friends and family": "knapp bei Kasse sein = mieć mało pieniędzy; rejestr swobodny, mówione wśród przyjaciół i rodziny",
  "Knast = colloquial for jail/prison": "Knast = potocznie o więzieniu, pace",
  "Komm doch mal vorbei! — the casual open invitation.": "Komm doch mal vorbei! — swobodne, otwarte zaproszenie.",
  "Krankmeldung (colloquial) is what people say; the official document is the Krankschreibung / AU-Bescheinigung": "Krankmeldung (potocznie) to, co mówią ludzie; oficjalny dokument nazywa się Krankschreibung albo AU-Bescheinigung",
  "Ladder level 4, STRONG — for genuine anger or shock. Friends only; heads will turn if you shout it in public.": "Poziom 4 drabiny, MOCNE — na prawdziwy gniew albo szok. Tylko wśród przyjaciół; krzyknięte publicznie, wszyscy się obejrzą.",
  "Leaving": "Wychodzenie",
  "Level 2, medium-mild — like English 'damn'; fine among adults, avoid formal settings": "Poziom 2, średnio-łagodny — jak angielskie 'damn'; wśród dorosłych w porządku, unikać sytuacji oficjalnych",
  "Loadout": "Wyposażenie",
  "Logisch! is also a casual \"obviously\"": "Logisch! to także swobodne 'jasne'",
  "Making a move": "Pierwszy krok",
  "Making plans": "Planowanie",
  "medium insult — banter-safe among close friends with the right tone": "obelga średniego kalibru — w żartach wśród bliskich przyjaciół, przy właściwym tonie",
  "medium-strong — banter only with thick-skinned close friends": "dość mocne — tylko w żartach wśród bliskich przyjaciół z grubą skórą",
  "Messaging — informal (du); in formal calls: Ich schreibe Ihnen eine Nachricht": "Pisanie wiadomości — nieformalnie (du); oficjalnie: Ich schreibe Ihnen eine Nachricht",
  "Meta": "Meta",
  "MILD-MEDIUM — dismissive ('you're not right in the head') rather than aggressive. Banter-safe among friends.": "ŁAGODNE DO ŚREDNIEGO — lekceważące ('nie masz wszystkich w domu'), a nie agresywne. W żartach wśród przyjaciół w porządku.",
  "MILD-MEDIUM — often affectionate among friends and family ('you silly thing'). Still rude to strangers.": "ŁAGODNE DO ŚREDNIEGO — wśród przyjaciół i rodziny często czułe ('ty gapo'). Wobec obcych mimo to niegrzeczne.",
  "mild-medium — often affectionate banter among friends": "łagodne do średniego — często czułe przekomarzanie wśród przyjaciół",
  "mithelfen — pitching in. The morning-after miracle that separates friends from guests.": "mithelfen — dołożyć się do pomocy. Cud poranka po imprezie, który oddziela przyjaciół od gości.",
  "mocking the classic 'Spiegel-Poser', a fixture of every gym; casual, said behind their back": "kpina z klasycznego 'Spiegel-Posera', stałego elementu każdej siłowni; swobodnie, mówione za plecami",
  "mocking, informal; the Aluhut is THE German ridicule image for conspiracists": "kpiąco, nieformalnie; Aluhut to TEN niemiecki obraz drwiny z wyznawców spisków",
  "nachfragen — following up. The sentence that saves the friendship.": "nachfragen — dopytać. Zdanie, które ratuje przyjaźń.",
  "neu laden = to reload — neu as an adverb before the verb; einfach shrugs it casual.": "neu laden = załadować od nowa — neu jako przysłówek przed czasownikiem; einfach nadaje swobodny ton.",
  "Neutral opener that signals something is on your mind; works with friends and family.": "Neutralny wstęp, który sygnalizuje, że coś ci leży na sercu; pasuje do przyjaciół i rodziny.",
  "neutral small talk; works with anyone — casually dropped article is typical": "neutralna pogawędka; pasuje do każdego — swobodnie pomijany rodzajnik jest typowy",
  "neutral word; among friends it's almost always 'die Kippe'": "słowo neutralne; wśród przyjaciół prawie zawsze 'die Kippe'",
  "Neutral-casual; 'Abi' is what everyone says — the full 'Abitur' sounds formal.": "Neutralno-swobodne; wszyscy mówią 'Abi' — pełne 'Abitur' brzmi oficjalnie.",
  "Neutral-casual; 'kriegen' is the spoken form of 'bekommen'.": "Neutralno-swobodne; 'kriegen' to mówiona forma 'bekommen'.",
  "Neutral-colloquial; 'zuschlagen' = to throw a punch, to strike.": "Neutralno-potoczne; 'zuschlagen' = uderzyć, zadać cios.",
  "Neutral, casual — a no-fuss way to not drink without explaining yourself. No justification expected.": "Neutralne, swobodne — bezproblemowy sposób, by nie pić i się nie tłumaczyć. Nikt nie oczekuje uzasadnienia.",
  "Neutral, casual 'hab'. The standard sequel to Verspätung — deliver it with weary resignation, not anger.": "Neutralne, swobodne 'hab'. Standardowy ciąg dalszy po Verspätung — mów to ze zmęczoną rezygnacją, nie ze złością.",
  "Neutral, common — disbelief that hovers between amused and appalled. Safe with anyone informal.": "Neutralne, częste — niedowierzanie gdzieś między rozbawieniem a zgrozą. Bezpieczne z każdym w tonie nieformalnym.",
  "Neutral, friendly — the standard joke opener among friends, family and colleagues. 'den' refers to der Witz.": "Neutralne, przyjazne — standardowy wstęp do dowcipu wśród przyjaciół, rodziny i kolegów. 'den' odnosi się do der Witz.",
  "Neutral, to friends/family/partner. THE suggestion — a leisurely loop, especially Sunday afternoon.": "Neutralne, do przyjaciół, rodziny albo partnera. TA propozycja — spokojne kółko, zwłaszcza w niedzielne popołudnie.",
  "Neutral, to whoever planned the route. 'Die Tour' is the casual word for a planned hike.": "Neutralnie, do osoby, która zaplanowała trasę. 'Die Tour' to swobodne słowo na zaplanowaną wędrówkę.",
  "Noun phrase + und + consequence — a conditional without wenn; landen in = to end up in, informal and vivid.": "Fraza rzeczownikowa + und + skutek — zdanie warunkowe bez wenn; landen in = wylądować w czymś, nieformalne i obrazowe.",
  "oder so = or something / or whatever (casual suggestions)": "oder so = albo coś w tym stylu (swobodne propozycje)",
  "Opinion": "Opinia",
  "Ordering food": "Zamawianie jedzenia",
  "Plans": "Plany",
  "Platform warning before train doors close": "Ostrzeżenie na peronie przed zamknięciem drzwi pociągu",
  "Players say Wishlist even though Steam's German UI says Wunschliste; 'schon ewig' = for ages. Neutral-casual.": "Gracze mówią Wishlist, choć niemiecki interfejs Steama pokazuje Wunschliste; 'schon ewig' = od wieków. Neutralno-swobodne.",
  "Playful defensiveness, mild — said with mock indignation when friends laugh at your mishap. Casual settings.": "Żartobliwa obrona, łagodna — mówione z udawanym oburzeniem, gdy przyjaciele śmieją się z twojej wpadki. Swobodne sytuacje.",
  "pleite — from bankruptcy, used casually. 'gerade' makes it temporary.": "pleite — od bankructwa, używane swobodnie. 'gerade' czyni to przejściowym.",
  "plural 'Jungs' = guys, lads (colloquial)": "liczba mnoga 'Jungs' = chłopaki, ekipa (potocznie)",
  "polite check with friends before lighting up; expected around non-smokers": "grzeczne upewnienie się wśród przyjaciół, zanim się zapali; oczekiwane przy niepalących",
  "polite warning shot before or instead of details; 'heikel' = delicate/tricky": "grzeczny strzał ostrzegawczy przed szczegółami albo zamiast nich; 'heikel' = delikatny, drażliwy",
  "polite-casual at the salon; was = etwas in spoken German": "grzecznie i swobodnie w salonie; was = etwas w mówionym niemieckim",
  "Position callout": "Podanie pozycji",
  "Post-breakup confession to close friends; serious and vulnerable, no banter register.": "Wyznanie po rozstaniu wobec bliskich przyjaciół; poważne i bezbronne, bez żartobliwego tonu.",
  "Reacting": "Reagowanie",
  "Reassuring": "Uspokajanie",
  "Relationship status": "Status związku",
  "Reporting a problem": "Zgłaszanie problemu",
  "Request": "Prośba",
  "resigned, informal; standard line among worried friends of a Schwurbler": "z rezygnacją, nieformalnie; standardowe zdanie wśród zmartwionych przyjaciół Schwurblera",
  "resigned; extremely common among friends and family of someone who's gone down the hole": "z rezygnacją; bardzo częste wśród przyjaciół i rodziny kogoś, kto się w to wciągnął",
  "Retail-investor bravado among friends; 'nachkaufen' = to buy more of what you already hold": "brawura drobnego inwestora wśród przyjaciół; 'nachkaufen' = dokupić więcej tego, co się już ma",
  "Routine": "Rutyna",
  "Said while handing over the Mitbringsel at the door, informal.": "Mówione przy wręczaniu Mitbringsel w drzwiach, nieformalnie.",
  "Say this when someone is about to see mutual friends or family. To several listeners, use 'Grüßt'.": "Powiedz to, gdy ktoś zaraz zobaczy wspólnych przyjaciół albo rodzinę. Do kilku osób użyj 'Grüßt'.",
  "Scheduling": "Umawianie terminów",
  "schlauchen — sapping your energy like a hose. Colloquial and exactly right.": "schlauchen — wysysać siły jak wąż. Potoczne i idealnie trafne.",
  "schreiben = to write / spell (informal)": "schreiben = pisać / literować (nieformalnie)",
  "Seasons": "Pory roku",
  "self-deprecating joke; 'ich schwör' is casual spoken German": "żart z siebie; 'ich schwör' to swobodna mowa niemiecka",
  "separable: 'Ich probier mal was aus.' Casual speech clips it to 'probieren': 'Ich probier mal ne andere Waffe'": "rozdzielnie złożony: 'Ich probier mal was aus.' W swobodnej mowie skracane do 'probieren': 'Ich probier mal ne andere Waffe'",
  "sich befassen mit = to engage with; the je/desto frame around a negation — avoidance measured in growth.": "sich befassen mit = zajmować się czymś; konstrukcja je/desto wokół przeczenia — unikanie mierzone przyrostem.",
  "sich etwas freihalten — keeping a day open. The advance reservation of friendship.": "sich etwas freihalten — zarezerwować sobie wolny dzień. Rezerwacja przyjaźni z wyprzedzeniem.",
  "sich hinlegen — putting yourself down. 'mal' makes it casual, not dramatic.": "sich hinlegen — położyć się. 'mal' czyni to swobodnym, nie dramatycznym.",
  "sich kurzschließen = to quickly sync (colloquial workplace); aneinander vorbeiarbeiten is a set idiom.": "sich kurzschließen = szybko się dogadać (potocznie w pracy); aneinander vorbeiarbeiten to utarte wyrażenie.",
  "Slang": "Slang",
  "Slang — the English loan stays English; ein deutsches Bad is a bathroom": "Slang — angielskie zapożyczenie zostaje angielskie; ein deutsches Bad to łazienka",
  "Slang (voll = really/very)": "Slang (voll = naprawdę, bardzo)",
  "Slang expression of enthusiasm": "Slangowy wyraz zachwytu",
  "Small-talk staple with international friends and colleagues; expect Germans to argue about their own answer.": "Klasyk pogawędki z międzynarodowymi przyjaciółmi i współpracownikami; licz się z tym, że Niemcy pokłócą się o własną odpowiedź.",
  "Some platforms add friends through masculine 'der Freundescode'; accusative is 'deinen Freundescode'.": "Niektóre platformy dodają znajomych przez rodzaj męski 'der Freundescode'; w bierniku 'deinen Freundescode'.",
  "spiegelglatt — mirror-smooth. The radio traffic warning word.": "spiegelglatt — gładki jak lustro. Ostrzegawcze słowo z komunikatów drogowych w radiu.",
  "spoken clip of 'Dispositionskredit'; 'im Dispo sein' = to be overdrawn — casual, everyone says it": "mówiony skrót od 'Dispositionskredit'; 'im Dispo sein' = być na minusie — swobodne, wszyscy tak mówią",
  "standard match-day question among friends, colleagues, in the Kneipe": "standardowe pytanie w dniu meczu wśród przyjaciół, kolegów z pracy, w Kneipe",
  "Standard term in news and casual talk alike; can get heated between generations.": "Standardowe określenie i w wiadomościach, i w swobodnej rozmowie; między pokoleniami bywa gorąco.",
  "Standard third-person relationship analysis among friends; casual armchair-psychology weight.": "Standardowa analiza cudzego związku wśród przyjaciół; swobodna psychologia z fotela.",
  "Status callout": "Podanie statusu",
  "Strong agreement": "Mocna zgoda",
  "stronger and less casual than widerlich finden": "mocniejsze i mniej swobodne niż widerlich finden",
  "Surprise": "Zaskoczenie",
  "Symptom": "Objaw",
  "talking about quitting with friends or partner": "rozmowa o rzuceniu nałogu z przyjaciółmi albo partnerem",
  "tanken — refuelling. Driving on the warning light is called auf Reserve fahren.": "tanken — tankować. Jazda na zapalonej kontrolce nazywa się auf Reserve fahren.",
  "Team play": "Gra zespołowa",
  "Teasing between partners or friends; 'etwa' adds the playful gotcha tone.": "Przekomarzanie między partnerami albo przyjaciółmi; 'etwa' dodaje żartobliwy ton przyłapania.",
  "Telling time": "Podawanie godziny",
  "Texting": "Pisanie wiadomości",
  "The 'gerade' matters — asking about the current obsession, not the all-time answer. Casual, du-form.": "'gerade' ma znaczenie — pytanie dotyczy bieżącej obsesji, nie odpowiedzi wszech czasów. Swobodnie, forma na ty.",
  "The Anprobe-zu-Hause strategy: order both, keep one, return the other; casual du-register": "Strategia Anprobe-zu-Hause: zamówić oba, jeden zostawić, drugi odesłać; swobodny rejestr na ty",
  "The barber will ask you this; colloquially you'll also hear 'Wie viel Millimeter an den Seiten?'": "O to zapyta cię fryzjer; potocznie usłyszysz też 'Wie viel Millimeter an den Seiten?'",
  "The casual imperative is 'Misch'; 'die Karten mischen' is the normal phrase for shuffling.": "Swobodny tryb rozkazujący to 'Misch'; 'die Karten mischen' to zwykłe wyrażenie o tasowaniu.",
  "The casual tier. Beste Grüße, Viele Grüße, VG: the ladder descends with familiarity.": "Stopień swobodny. Beste Grüße, Viele Grüße, VG: drabina opada wraz z zażyłością.",
  "the casual word for Rad fahren": "swobodne słowo na Rad fahren",
  "The classic couple question. 'Sich (Dativ) etwas holen' is the casual verb for getting a pet.": "Klasyczne pytanie w związku. 'Sich (Dativ) etwas holen' to swobodny czasownik o wzięciu zwierzaka.",
  "The classic no-fault breakup explanation — sad but blame-free. What people tell friends afterwards.": "Klasyczne wyjaśnienie rozstania bez winnych — smutne, ale bez oskarżeń. To, co potem mówi się przyjaciołom.",
  "THE dating-scene diagnosis of the decade; said casually but half-seriously about anyone who won't commit.": "TA randkowa diagnoza dekady; mówiona swobodnie, ale półserio o każdym, kto nie chce się zaangażować.",
  "The default Grußformel — never wrong, never exciting. MfG in casual shorthand.": "Domyślna Grußformel — nigdy błędna, nigdy porywająca. W swobodnym skrócie: MfG.",
  "The dramatic version for partners and close friends — du-form territory, carries real weight": "Dramatyczna wersja dla partnerów i bliskich przyjaciół — terytorium na ty, z prawdziwym ciężarem",
  "The embarrassment-avoidance rule. Half of all lost keys are in the other jacket.": "Zasada unikania wstydu. Połowa zgubionych kluczy jest w drugiej kurtce.",
  "The excited announcement to friends and family. 'Einen Antrag machen' is the standard idiom for proposing.": "Podekscytowana wiadomość dla przyjaciół i rodziny. 'Einen Antrag machen' to standardowe wyrażenie o oświadczynach.",
  "The first question every friend asks. Casual, expected, and everyone wants the full story.": "Pierwsze pytanie, które zadaje każdy przyjaciel. Swobodne, oczekiwane, a wszyscy chcą całej historii.",
  "The flare-up warning. Move it to the side; never pour water on.": "Ostrzeżenie przed buchnięciem ognia. Odstaw na bok; nigdy nie polewaj wodą.",
  "The German ID card — der Perso in casual speech.": "Niemiecki dowód osobisty — w swobodnej mowie der Perso.",
  "THE gym-bro question; casual, between guys who lift": "TO pytanie z siłowni; swobodne, między tymi, którzy podnoszą ciężary",
  "The hedge 'eher' is key — Germans rarely self-label without it. Safe self-description among friends.": "Złagodzenie 'eher' jest kluczowe — Niemcy rzadko przyklejają sobie etykietę bez niego. Bezpieczny autoopis wśród przyjaciół.",
  "The hike itself; casually also 'die Tour'.": "Sama wędrówka; swobodnie także 'die Tour'.",
  "The honest cost warning. Under a hundred euros, most people simply pay.": "Uczciwe ostrzeżenie o kosztach. Poniżej stu euro większość ludzi po prostu płaci.",
  "The honest warning, issued once and remembered forever by flatmates.": "Uczciwe ostrzeżenie, wypowiedziane raz i zapamiętane na zawsze przez współlokatorów.",
  "The host's standard warm goodbye at the door, informal.": "Standardowe, ciepłe pożegnanie gospodarza w drzwiach, nieformalne.",
  "the key de-escalation and warmth line in mixed-belief couples and friendships; sincere register": "kluczowe zdanie łagodzące i ocieplające w parach i przyjaźniach o różnych wierzeniach; rejestr szczery",
  "The late-summer warning. Cover your drink — the wasp finds it anyway.": "Ostrzeżenie późnego lata. Przykryj napój — osa i tak go znajdzie.",
  "the modern word for conspiracy-rambling; informal and very common now": "współczesne słowo na spiskowe bełkotanie; nieformalne i dziś bardzo częste",
  "The most common casual check-in — short for Wie geht es?": "Najczęstsze swobodne zapytanie o samopoczucie — skrót od Wie geht es?",
  "The order that avoids regret. Half a percent matters less than one good extra.": "Kolejność, która oszczędza żalu. Pół procenta znaczy mniej niż jeden dobry dodatek.",
  "The permission that keeps friendships alive through a separation.": "Przyzwolenie, które utrzymuje przyjaźnie przy życiu mimo rozstania.",
  "The positive mirror. 'Etwas/nichts/viel von jemandem halten' is THE casual pattern for rating people.": "Pozytywne odbicie. 'Etwas/nichts/viel von jemandem halten' to TEN swobodny wzorzec oceniania ludzi.",
  "The promise that keeps friendships": "Obietnica, która utrzymuje przyjaźnie",
  "The proud line — drop it casually among friends and watch the questions start.": "Dumne zdanie — rzuć je mimochodem wśród przyjaciół i patrz, jak zaczynają się pytania.",
  "The quiet ending of many friendships, described without accusation.": "Ciche zakończenie wielu przyjaźni, opisane bez oskarżeń.",
  "The reciprocity ledger of friendship — informal, unwritten, never forgotten.": "Rejestr wzajemności w przyjaźni — nieformalny, niepisany, nigdy niezapomniany.",
  "The refusal that protects the friendship by naming the rule, not the person.": "Odmowa, która chroni przyjaźń, bo wskazuje zasadę, a nie osobę.",
  "The sentence that softens hard truths between friends.": "Zdanie, które łagodzi trudne prawdy między przyjaciółmi.",
  "The sequence that avoids visible edges. Professionals call it 'vorschneiden'.": "Kolejność, która pozwala uniknąć widocznych krawędzi. Profesjonaliści mówią na to 'vorschneiden'.",
  "The so makes the question casual — 'what do you do, generally?' The small-talk classic.": "To so czyni pytanie swobodnym — 'czym się tak w ogóle zajmujesz?' Klasyk pogawędki.",
  "The solemn one — anniversaries, vows, letters. Partner only; too big for casual goodbyes.": "Forma uroczysta — rocznice, przysięgi, listy. Tylko dla partnera; za wielka na swobodne pożegnania.",
  "The spoken du-command is 'Klick'; a more formal warning is 'Klicken Sie nicht auf den Link'.": "Mówiony rozkaz na ty to 'Klick'; bardziej oficjalne ostrzeżenie brzmi 'Klicken Sie nicht auf den Link'.",
  "The standard closing courtesy among friends. Expected, and noticed if forgotten.": "Standardowa grzeczność na koniec wśród przyjaciół. Oczekiwana — i widać, gdy jej zabraknie.",
  "The standard earworm complaint, informal. Often followed by singing it and infecting everyone else.": "Standardowe narzekanie na natrętną melodię, nieformalne. Często kończy się jej zanuceniem i zarażeniem wszystkich wokół.",
  "The standard sigh after any pay-rise or salary talk; casual, universal": "Standardowe westchnienie po każdej rozmowie o podwyżce; swobodne, uniwersalne",
  "the standard verb; coden is its casual twin": "standardowy czasownik; coden to jego swobodny bliźniak",
  "The standard warm reply you WILL hear — 'echt' makes it casual and sincere. Just say 'Danke!', don't argue.": "Standardowa, ciepła odpowiedź, którą NA PEWNO usłyszysz — 'echt' czyni ją swobodną i szczerą. Powiedz po prostu 'Danke!', nie dyskutuj.",
  "the standard way to disclose a serious rift; neutral register, works with friends and colleagues alike": "standardowy sposób ujawnienia poważnego rozłamu; rejestr neutralny, pasuje zarówno do przyjaciół, jak i współpracowników",
  "The standard way to promise a return invitation at the door, informal.": "Standardowy sposób obiecania rewizyty w drzwiach, nieformalnie.",
  "the standard word; casually 'die Muckibude' or just 'das Gym'": "standardowe słowo; swobodnie 'die Muckibude' albo po prostu 'das Gym'",
  "The stylist asks this at the end; reinmachen is casual spoken German": "O to pyta fryzjer na koniec; reinmachen to swobodna mowa niemiecka",
  "the universal leg-day complaint; casual": "uniwersalne narzekanie po dniu nóg; swobodne",
  "The warning against illegal puppy trade. Cheap, sick, and it funds more of it.": "Ostrzeżenie przed nielegalnym handlem szczeniętami. Tanie, chore i finansuje kolejne.",
  "The written warning from an employer or lawyer — one step before consequences.": "Pisemne upomnienie od pracodawcy albo prawnika — krok przed konsekwencjami.",
  "This impersonal passive is a playful way to announce an unavoidable routine without repeatedly saying 'you'.": "Ta bezosobowa strona bierna to żartobliwy sposób zapowiadania nieuniknionej rutyny bez ciągłego mówienia 'ty'.",
  "Time comment": "Uwaga o czasie",
  "To friends or your partner right after trying a new word. Invites a gentle correction.": "Do przyjaciół albo partnera zaraz po wypróbowaniu nowego słowa. Zaprasza do łagodnej poprawki.",
  "Two words that stop a small hand. 'Vorsicht' works alone as a warning.": "Dwa słowa, które zatrzymują małą rączkę. 'Vorsicht' działa samo jako ostrzeżenie.",
  "Typical reply": "Typowa odpowiedź",
  "überweisen + dative person — sending money person-to-person. How friends settle up in Germany.": "überweisen + osoba w celowniku — przelew od osoby do osoby. Tak przyjaciele rozliczają się w Niemczech.",
  "um einen Gefallen bitten — the formal opening of informal help. Germans appreciate the framing.": "um einen Gefallen bitten — oficjalne otwarcie nieformalnej pomocy. Niemcy cenią takie ujęcie.",
  "Unlocks": "Odblokowania",
  "Urgent": "Pilne",
  "Urgent warning": "Pilne ostrzeżenie",
  "verschreien — jinxing by saying. The warning shouted across German offices daily.": "verschreien — zapeszyć, wypowiadając na głos. Ostrzeżenie wykrzykiwane codziennie w niemieckich biurach.",
  "verschwitzen — sweating an appointment away: forgetting it entirely. Casual, honest, forgivable once.": "verschwitzen — przepocić termin, czyli zapomnieć o nim zupełnie. Swobodne, szczere, raz wybaczalne.",
  "verstoßen gegen + Akkusativ; mit etwas rechnen müssen is the standard warning of consequences.": "verstoßen gegen + biernik; mit etwas rechnen müssen to standardowe ostrzeżenie o konsekwencjach.",
  "Very casual slang for friends": "Bardzo swobodny slang na przyjaciół",
  "very casual, said just before a penalty; 'der' instead of 'er' is typical fan speech": "bardzo swobodne, mówione tuż przed rzutem karnym; 'der' zamiast 'er' to typowa mowa kibiców",
  "Very casual: 'ne' = 'eine', 'probier mal' softens it. With friends, not in writing.": "Bardzo swobodne: 'ne' = 'eine', 'probier mal' łagodzi. Wśród przyjaciół, nie na piśmie.",
  "Very common (informal alternative to 'Die Rechnung bitte')": "Bardzo częste (nieformalna alternatywa dla 'Die Rechnung bitte')",
  "Very common casual slang": "Bardzo częsty, swobodny slang",
  "Very common colloquial verb for losing your temper": "Bardzo częsty potoczny czasownik o utracie panowania nad sobą",
  "Very common colloquial; about losing your temper, not going crazy.": "Bardzo częste potocznie; chodzi o wybuch złości, nie o szaleństwo.",
  "Very common leisure activity": "Bardzo popularne zajęcie w czasie wolnym",
  "Very common, casual — Bock = desire/appetite": "Bardzo częste, swobodne — Bock = ochota",
  "Very common, casual — literally 'that's sausage to me'": "Bardzo częste, swobodne — dosłownie 'to mi kiełbasa'",
  "Very common, direct — friends or real annoyance": "Bardzo częste, bezpośrednie — wśród przyjaciół albo przy prawdziwej złości",
  "vorbeischauen — looking past: the casual visit. 'auf einen Kaffee' — the unit of neighbourliness.": "vorbeischauen — wpaść na chwilę: swobodna wizyta. 'auf einen Kaffee' — jednostka miary sąsiedzkości.",
  "Vorsicht + statement — the standard kitchen warning shape.": "Vorsicht + zdanie — standardowy kształt ostrzeżenia w kuchni.",
  "Vulgar-casual: Willst du mich verarschen? = are you kidding me?": "Wulgarno-swobodne: Willst du mich verarschen? = robisz sobie ze mnie jaja?",
  "Vulgar-ish (from Arsch = arse). Fine among friends, avoid with strangers or at work.": "Raczej wulgarne (od Arsch). Wśród przyjaciół w porządku, unikać przy obcych i w pracy.",
  "Warm casual goodbye — informal (du), friends only": "Ciepłe, swobodne pożegnanie — nieformalne (du), tylko wśród przyjaciół",
  "warm compliment for partner or close friends; stronger than 'gut'": "ciepły komplement dla partnera albo bliskich przyjaciół; mocniejszy niż 'gut'",
  "Warm compliment, safe in any casual context.": "Ciepły komplement, bezpieczny w każdej swobodnej sytuacji.",
  "Warm door greeting to friends (ihr). One person: 'Komm rein!'; formal: 'Kommen Sie rein!'": "Ciepłe powitanie w drzwiach dla przyjaciół (ihr). Jedna osoba: 'Komm rein!'; oficjalnie: 'Kommen Sie rein!'",
  "Warm du-form for friends and family. Softer and more personal than the formal Beileid formulas.": "Ciepła forma na ty dla przyjaciół i rodziny. Łagodniejsza i bardziej osobista niż oficjalne formuły kondolencyjne.",
  "Warm goodbye — informal (du), friends only": "Ciepłe pożegnanie — nieformalne (du), tylko wśród przyjaciół",
  "Warm toast among friends, couples, teams celebrating something together. Follows or replaces 'Prost'.": "Ciepły toast wśród przyjaciół, par, zespołów świętujących coś razem. Następuje po 'Prost' albo je zastępuje.",
  "Warm, casual encouragement before a challenge. 'You've got this' is the most natural English equivalent.": "Ciepła, swobodna zachęta przed wyzwaniem. Najbliższym angielskim odpowiednikiem jest 'You've got this'.",
  "Warning": "Ostrzeżenie",
  "Weather": "Pogoda",
  "What you ask the neighbours during an outage; weg sein = to be gone (very common colloquial)": "O co pytasz sąsiadów przy awarii prądu; weg sein = zniknąć, nie działać (bardzo częste potocznie)",
  "What your investment earns; 'Rendite abwerfen' = to yield a return, colloquially also 'Rendite machen'": "To, co zarabia twoja inwestycja; 'Rendite abwerfen' = przynosić zysk, potocznie także 'Rendite machen'",
  "Written German too": "Także w piśmie",
  "youth slang from 'suchten' (die Sucht = addiction): hat durchgesuchtet; 'binge-watchen' also works": "młodzieżowy slang od 'suchten' (die Sucht = nałóg): hat durchgesuchtet; 'binge-watchen' też przejdzie",
  "zunächst and bislang bracket the timeline; es das geblieben — das stands for harmlos.": "zunächst i bislang obejmują oś czasu; es das geblieben — das zastępuje harmlos.",
  "zurückzahlen — paying back. The clause that keeps the friendship intact.": "zurückzahlen — oddać dług. Zdanie podrzędne, które zachowuje przyjaźń w całości.",
};
