/**
 * The usage notes in Portuguese.
 *
 * Keyed by the English note exactly as the card carries it. A note missing
 * from here shows its English, so this file is filled in batches without any
 * card ever going blank — see usageNotes.ts for how it is loaded and why it
 * is not part of the interface tables.
 *
 * Fourteen thousand notes exist. This holds the ones translated so far, and
 * check-usage-notes prints how far along each language is on every build.
 */
export const USE_PT: Record<string, string> = {
  "'abschleppen' — to tow. Colloquially it also means pulling someone in a bar.": "'abschleppen' — rebocar. Coloquialmente também significa engatar alguém num bar.",
  "'angesagt sein' — forecast, announced. Also slang for what's currently trendy.": "'angesagt sein' — anunciado, previsto. Em calão também: o que está na moda agora.",
  "'auf etwas stehen' — to be into something. Informal, current, and used constantly.": "'auf etwas stehen' — curtir alguma coisa. Informal, atual e usado a toda a hora.",
  "'bedeuten' for meaning. 'Was heißt das?' is the more casual version and just as correct.": "'bedeuten' para o significado. 'Was heißt das?' é a versão mais descontraída e igualmente correta.",
  "'Das Match' — loan for a full competitive game; 'ist Schluss' = are we done. Casual.": "'Das Match' — estrangeirismo para um jogo completo; 'ist Schluss' = acabou. Descontraído.",
  "'davon' avoids repeating the product name after pointing or asking a question about it.": "'davon' evita repetir o nome do produto depois de apontar para ele ou de perguntar por ele.",
  "'davon' refers to an amount of the thing already being discussed and avoids repeating its name.": "'davon' remete para uma quantidade da coisa já mencionada e evita repetir-lhe o nome.",
  "'Der Hammer' = the standard casual superlative for events. Informal, all ages under about 50.": "'Der Hammer' = o superlativo descontraído típico para um evento. Informal, abaixo dos 50 anos, mais ou menos.",
  "'Der Ping' — English loan, no alternative. 'übel' is youth slang for 'terrible'.": "'Der Ping' — estrangeirismo do inglês, sem alternativa. 'übel' é calão juvenil para 'horrível'.",
  "'doppelt' — double. 'Menge' is a quantity, and colloquially 'a lot'.": "'doppelt' — duplo. 'Menge' é uma quantidade e, coloquialmente, 'muito'.",
  "'dran sein' — to be next in turn. Compact, informal and used constantly.": "'dran sein' — ser o próximo na vez. Compacto, informal e usado a toda a hora.",
  "'draufschauen' — to look at it. Colloquial and separable.": "'draufschauen' — dar uma olhada. Coloquial e separável.",
  "'Du hast einen guten Musikgeschmack' is a real compliment between friends or on a date.": "'Du hast einen guten Musikgeschmack' é um elogio a sério entre amigos ou num encontro.",
  "'durch sein' — colloquially done for: soaked, worn out, finished.": "'durch sein' — coloquialmente acabado: encharcado, gasto, no fim.",
  "'eigentlich' — the casual opener for a serious adult conversation.": "'eigentlich' — a abertura descontraída de uma conversa séria entre adultos.",
  "'Elfer' is the casual clip everyone uses in speech": "'Elfer' é a forma curta descontraída que todos usam na fala",
  "'ewig' — eternally, used casually for 'ages'. 'laden' for loading.": "'ewig' — eternamente, em tom descontraído 'uma eternidade'. 'laden' para carregar.",
  "'frei Schnauze' — literally free snout: no recipe, pure instinct. Wonderfully casual.": "'frei Schnauze' — literalmente focinho livre: sem receita, puro instinto. Maravilhosamente descontraído.",
  "'gar nicht erst' — not even starting. Avoiding the problem entirely.": "'gar nicht erst' — nem sequer começar. Evitar o problema por completo.",
  "'glatt' — slippery with ice. The winter warning Germans text each other.": "'glatt' — escorregadio por causa do gelo. O aviso de inverno que os alemães mandam por mensagem.",
  "'gläubig' — devout. Said plainly, this ends no friendships in Germany.": "'gläubig' — crente, praticante. Dito com naturalidade, na Alemanha não acaba com amizades.",
  "'gucken' is the casual everyday verb (north/central); the south says 'schauen'": "'gucken' é o verbo descontraído do dia a dia (norte e centro); o sul diz 'schauen'",
  "'halbe-halbe' is common informal German for dividing something into two equal parts.": "'halbe-halbe' é alemão informal comum para dividir alguma coisa em duas partes iguais.",
  "'hinkriegen' — to manage or pull something off. Informal, warm and extremely common.": "'hinkriegen' — conseguir fazer alguma coisa, safar-se. Informal, caloroso e muito comum.",
  "'jeder zahlt seins' — the German default among friends. No awkwardness; it's the system.": "'jeder zahlt seins' — o normal entre amigos na Alemanha. Nada de embaraço; é assim que funciona.",
  "'Jetzt reicht's' is the short version, and the last warning before a row.": "'Jetzt reicht's' é a versão curta, e o último aviso antes da discussão.",
  "'Kein Thema' — not a topic: it doesn't even need discussing. Friendship in two words.": "'Kein Thema' — não é assunto: nem é preciso falar disso. A amizade em duas palavras.",
  "'mal' makes the command sound casual; use 'in die Ecke' when directing light into it.": "'mal' faz a ordem soar descontraída; usa-se 'in die Ecke' quando se dirige a luz para lá.",
  "'mal' softens the imperative into a casual request; masculine object is 'deinen Benutzernamen'.": "'mal' transforma o imperativo num pedido descontraído; o objeto masculino é 'deinen Benutzernamen'.",
  "'mal' turns an offer into something casual. Two seconds, no commitment.": "'mal' torna o oferecimento descontraído. Dois segundos, sem compromisso.",
  "'mitnehmen' is separable; in the informal imperative, 'mit' lands at the end.": "'mitnehmen' é separável; no imperativo informal, 'mit' vai para o fim.",
  "'Pass auf!' is the fastest warning; separable 'aufpassen' becomes 'pass ... auf'.": "'Pass auf!' é o aviso mais rápido; o separável 'aufpassen' passa a 'pass ... auf'.",
  "'rausfliegen' — from the fuse pack, here about a back. Colloquial and instantly understood.": "'rausfliegen' — do pacote dos fusíveis, aqui sobre umas costas. Coloquial e percebido no imediato.",
  "'schauen' or 'gucken' — gucken is more casual. No preposition before the platform.": "'schauen' ou 'gucken' — gucken é mais descontraído. Sem preposição antes da plataforma.",
  "'schlapp' (colloquial) = run-down, drained; 'kaum' = barely.": "'schlapp' (coloquial) = abatido, esgotado; 'kaum' = mal, quase não.",
  "'sicherheitshalber' explains that you are checking to avoid an unnecessary mistake.": "'sicherheitshalber' explica que estás a verificar para evitar um erro desnecessário.",
  "'sportlich' — sporty, and also 'smart-casual' about clothes. Both are common.": "'sportlich' — desportivo, e nas roupas também 'smart casual'. Ambos são comuns.",
  "'total' as an intensifier is thoroughly spoken German and slightly informal.": "'total' como intensificador é alemão falado puro e ligeiramente informal.",
  "'unterschiedlich' — differing. Germans use it constantly to avoid overgeneralising.": "'unterschiedlich' — diferente, variável. Os alemães usam-no sem parar para não generalizar.",
  "'was trinken gehen' — the standard invitation. Casual, open-ended, no commitment implied.": "'was trinken gehen' — o convite padrão. Descontraído, aberto, sem compromisso.",
  "'wegmachen' colloquially for putting something aside. 'mal' softens the announcement.": "'wegmachen' coloquialmente para arrumar alguma coisa de lado. 'mal' suaviza o anúncio.",
  "'Wie hoch' for amounts of money. A completely normal question between German friends.": "'Wie hoch' para quantias de dinheiro. Uma pergunta perfeitamente normal entre amigos alemães.",
  "'wieder drauf haben' — colloquial and compact. Bike chains come off constantly.": "'wieder drauf haben' — coloquial e compacto. As correntes das bicicletas saltam a toda a hora.",
  "'Wofür' is the normal neutral form; 'für was' is regional or very casual.": "'Wofür' é a forma neutra normal; 'für was' é regional ou muito descontraído.",
  "'Zeit mitbringen' — the honest warning. Open hours mean open-ended waiting.": "'Zeit mitbringen' — o aviso honesto. Horário sem marcação significa espera sem fim.",
  "A casual purpose question when someone has an object, tool, file or unusual plan.": "Uma pergunta descontraída sobre a finalidade, quando alguém tem um objeto, uma ferramenta, um ficheiro ou um plano invulgar.",
  "A colloquial fixed expression. It is not sexual in this use.": "Uma expressão fixa coloquial. Neste uso não tem sentido sexual.",
  "A common informal response to disappointing news or an annoying problem.": "Uma resposta informal comum a notícias dececionantes ou a um problema chato.",
  "A common use of sammeln among friends, at work or in a family.": "Um uso comum de sammeln entre amigos, no trabalho ou em família.",
  "A considerate response to bad news when a casual reaction would feel too light.": "Uma resposta atenciosa a más notícias, quando uma reação descontraída pareceria leve demais.",
  "A direct warning that a condition or necessary step cannot be skipped.": "Um aviso direto: uma condição ou um passo necessário não pode ser saltado.",
  "A natural follow-up after meeting two friends. 'seid ihr' addresses both people together.": "Uma pergunta de seguimento natural depois de encontrar dois amigos. 'seid ihr' dirige-se aos dois ao mesmo tempo.",
  "A normal informal request for a very short wait. Add 'bitte' when you want it to sound softer.": "Um pedido informal normal para esperar um instante. Junta 'bitte' para soar mais suave.",
  "A practical check that helps the group avoid stopping again once the task has begun.": "Uma verificação prática que evita ao grupo ter de parar outra vez depois de começar.",
  "A serious accusation, not casual criticism.": "Uma acusação grave, não uma crítica passageira.",
  "A standard informal request. The favour itself normally follows immediately.": "Um pedido informal padrão. O favor em si vem normalmente logo a seguir.",
  "A standard Monday small-talk question with friends, classmates and colleagues you know.": "A típica pergunta de conversa de segunda-feira com amigos, colegas de turma e colegas conhecidos.",
  "A standing offer between partners or close friends; warm, no drama.": "Um oferecimento sempre válido entre parceiros ou amigos próximos; caloroso, sem drama.",
  "A very common informal way to check whether a day suits someone.": "Uma forma informal muito comum de perguntar se um dia serve a alguém.",
  "abgefahren — driven off, worn. Also slang for 'amazing'; the tyre meaning is older.": "abgefahren — gasto, careca. Em calão também 'espetacular'; o sentido do pneu é mais antigo.",
  "Achtung! is the warning word; die Ampel = the traffic light, always feminine.": "Achtung! é a palavra de aviso; die Ampel = o semáforo, sempre feminino.",
  "Afterwards": "Depois",
  "Agreeing": "Concordar",
  "Allotment neighbours — advisors, rivals and friends across one fence. Mostly all three.": "Vizinhos de horta urbana — conselheiros, rivais e amigos dos dois lados de uma cerca. Quase sempre as três coisas.",
  "also colloquially \"incredibly\": unwahrscheinlich gut": "coloquialmente também 'incrivelmente': unwahrscheinlich gut",
  "also colloquially \"massively\": tierisch gut": "coloquialmente também 'para caramba': tierisch gut",
  "always plural": "sempre no plural",
  "An informal reaction to a plan failing, something breaking or another everyday setback.": "Uma reação informal quando um plano falha, algo se parte ou surge outro contratempo do dia a dia.",
  "Asking for the bill": "Pedir a conta",
  "At the table, informal. One guest: 'Greif zu!' Signals the eating may begin.": "À mesa, informal. Com um convidado: 'Greif zu!' Sinaliza que já se pode começar a comer.",
  "At the till": "Na caixa",
  "aufblasen — inflating. 'Hilf mir mal' — the casual recruiting of bystanders.": "aufblasen — encher de ar. 'Hilf mir mal' — a forma descontraída de recrutar quem está por perto.",
  "aufdrängen — pressing something on someone. The warning before every market stroll.": "aufdrängen — impingir alguma coisa a alguém. O aviso antes de cada passeio pelo mercado.",
  "aufziehen — a storm pulling up. denn delivers the warning in plain word order.": "aufziehen — uma tempestade a aproximar-se. denn dá o aviso na ordem de palavras mais simples.",
  "auslaufen — leaking out. 'hinüber sein' — colloquially beyond saving.": "auslaufen — vazar. 'hinüber sein' — coloquialmente, sem salvação.",
  "Banter": "Brincadeira",
  "beraten — advising. 'einen' — the colloquial accusative of man.": "beraten — aconselhar. 'einen' — o acusativo coloquial de man.",
  "Between friends: Kannst du mir zehn Euro borgen? Standard German prefers leihen.": "Entre amigos: Kannst du mir zehn Euro borgen? O alemão padrão prefere leihen.",
  "Blunt but completely normal between partners and friends — German directness in action": "Direto mas perfeitamente normal entre parceiros e amigos — a franqueza alemã em ação",
  "Blunt insult, literally a full fencepost. Friends-only register.": "Insulto direto, literalmente um poste de cerca inteiro. Só entre amigos.",
  "borgen — the casual borrow-lend verb. die Leiter migrates between households like a shared pet.": "borgen — o verbo descontraído de emprestar e pedir emprestado. die Leiter migra entre casas como um animal partilhado.",
  "bumming a cigarette; casual, smoker-to-smoker only": "pedir um cigarro emprestado; descontraído, só de fumador para fumador",
  "Buying time": "Ganhar tempo",
  "Casual": "Descontraído",
  "Casual — Ding literally means 'thing'": "Descontraído — Ding significa literalmente 'coisa'",
  "Casual — literally 'now we have the salad'": "Descontraído — literalmente 'agora temos a salada'",
  "Casual — literally 'that's not my beer'": "Descontraído — literalmente 'isso não é a minha cerveja'",
  "Casual — literally 'you had pig'": "Descontraído — literalmente 'tiveste porco'",
  "Casual agreement": "Concordância descontraída",
  "Casual and dramatic; often frustration rather than literal loss of control.": "Descontraído e dramático; muitas vezes frustração e não perda real de controlo.",
  "Casual check-in mid-explanation.": "Verificação descontraída a meio de uma explicação.",
  "casual clipping of 'Prominenter' — everyday word": "forma curta descontraída de 'Prominenter' — palavra do dia a dia",
  "Casual complaint, one hour in. Someone packed too much Brotzeit.": "Queixa descontraída ao fim de uma hora. Alguém levou Brotzeit a mais.",
  "casual compliment; stehen + dative = to suit someone": "elogio descontraído; stehen + dativo = ficar bem a alguém",
  "Casual date invite (better than formal 'Möchten Sie...')": "Convite para um encontro em tom descontraído (melhor do que o formal 'Möchten Sie...')",
  "Casual dating vocabulary with friends. The verb is fully germanized: ghosten, geghostet.": "Vocabulário descontraído de encontros entre amigos. O verbo está totalmente germanizado: ghosten, geghostet.",
  "casual Denglisch — 'Ich hab gecodet' is completely normal among devs": "denglisch descontraído — 'Ich hab gecodet' é perfeitamente normal entre programadores",
  "Casual directive": "Instrução descontraída",
  "Casual everyday goodbye — used everywhere in Germany": "Despedida descontraída do dia a dia — usada em toda a Alemanha",
  "Casual everyday reassurance": "Frase de tranquilização descontraída do dia a dia",
  "Casual favour between friends (du). 'drüberschauen' = give it a quick once-over.": "Favor descontraído entre amigos (du). 'drüberschauen' = dar uma vista de olhos rápida.",
  "Casual for playing video games; in money contexts it means to gamble.": "Descontraído para jogar videojogos; quando envolve dinheiro, significa apostar.",
  "Casual goodbye — borrowed from Italian, extremely popular in Germany": "Despedida descontraída — vinda do italiano, muito popular na Alemanha",
  "casual gym slang for lifting weights; 'pumpen gehen'": "calão descontraído de ginásio para levantar pesos; 'pumpen gehen'",
  "Casual imperative 'Investier' is common spoken German; full written form is 'Investiere'.": "O imperativo descontraído 'Investier' é comum na fala; a forma escrita completa é 'Investiere'.",
  "Casual imperative 'Setz' is short for 'Setze'; 'am' contracts dative 'an dem'.": "O imperativo descontraído 'Setz' abrevia 'Setze'; 'am' contrai o dativo 'an dem'.",
  "Casual invite": "Convite descontraído",
  "Casual kitchen-table economics; sich lohnen = to be worth it — very high-frequency verb": "Economia descontraída de mesa de cozinha; sich lohnen = valer a pena — verbo muito frequente",
  "casual loanword; einkaufen is the German verb": "estrangeirismo descontraído; einkaufen é o verbo alemão",
  "Casual opener": "Abertura de conversa descontraída",
  "Casual opener for close friends": "Abertura descontraída entre amigos próximos",
  "Casual opinion": "Opinião descontraída",
  "Casual positive update": "Novidade positiva em tom descontraído",
  "Casual register inside student life; durcharbeiten = work through without a break.": "Registo descontraído da vida de estudante; durcharbeiten = trabalhar sem parar.",
  "Casual reminiscing; 'was los sein' = something happening.": "Recordações em tom descontraído; 'was los sein' = estar a acontecer algo.",
  "Casual reply": "Resposta descontraída",
  "Casual request": "Pedido descontraído",
  "Casual request to repeat": "Pedido descontraído para repetir",
  "Casual self-intro": "Apresentação pessoal descontraída",
  "Casual slang command": "Ordem em calão descontraído",
  "Casual slang farewell": "Despedida em calão descontraído",
  "Casual spoken imperative 'Markier' is common; the tool follows dative 'mit einem Bleistift'.": "O imperativo falado descontraído 'Markier' é comum; a ferramenta vai no dativo: 'mit einem Bleistift'.",
  "casual spoken; from sich fertig machen = sich zurechtmachen": "fala descontraída; de sich fertig machen = arranjar-se",
  "casual spoken; the machen-lassen pattern for anything done at a salon": "fala descontraída; o padrão machen-lassen para tudo o que se faz num salão",
  "casual, admiring; 'definiert' = lean and cut, more technical": "descontraído e admirativo; 'definiert' = seco e definido, mais técnico",
  "Casual, enthusiastic. 'Der Wahnsinn' is the go-to superlative among friends.": "Descontraído e entusiasmado. 'Der Wahnsinn' é o superlativo de eleição entre amigos.",
  "casual, everyday; der Lidstrich is the German word, Eyeliner is what people say": "descontraído, do dia a dia; der Lidstrich é a palavra alemã, mas as pessoas dizem Eyeliner",
  "Casual, relieved-triumphant, to friends. 'überstehen' = to survive something unpleasant.": "Descontraído, aliviado e triunfante, entre amigos. 'überstehen' = sobreviver a algo desagradável.",
  "Casual, teasing — literally 'do you have tomatoes on your eyes?'": "Descontraído e trocista — literalmente 'tens tomates nos olhos?'",
  "Casual, to companions. Famous last words on any hike.": "Descontraído, aos companheiros. As famosas últimas palavras de qualquer caminhada.",
  "Casual, to one person (du) — group: Lasst uns anfangen; formal: Fangen wir an": "Descontraído, a uma pessoa (du) — ao grupo: Lasst uns anfangen; formal: Fangen wir an",
  "Casual, universal. The standard excuse to step outside — nobody questions frische Luft.": "Descontraído, universal. A desculpa padrão para sair — ninguém questiona o frische Luft.",
  "Casual, wry — literally 'life is no pony farm'": "Descontraído e irónico — literalmente 'a vida não é uma quinta de póneis'",
  "casual, younger speakers; Hautpflege is the more formal word": "descontraído, falantes mais jovens; Hautpflege é a palavra mais formal",
  "Casual; 'die Pause' is the break, 'der Pausenhof' the yard it happens on.": "Descontraído; 'die Pause' é o intervalo, 'der Pausenhof' o recreio onde ele acontece.",
  "casual; 'platt' = wiped out, works for any exhaustion": "descontraído; 'platt' = de rastos, serve para qualquer cansaço",
  "casual; 'Proteinshake' works too": "descontraído; 'Proteinshake' também serve",
  "casual; 'pumpen gehen' marks you as a weights person, not a treadmill person": "descontraído; 'pumpen gehen' marca-te como pessoa dos pesos, não da passadeira",
  "casual; 'sich etwas ziehen' = to pull a muscle": "descontraído; 'sich etwas ziehen' = distender um músculo",
  "Casual; ackern makes the work sound tiring or relentless.": "Descontraído; ackern faz o trabalho soar cansativo e implacável.",
  "Casual; adults admit it with a grin": "Descontraído; os adultos admitem-no com um sorriso",
  "casual; literally also to plough a field": "descontraído; literalmente também lavrar um campo",
  "casual; stechen lassen (literally 'have it pricked') is the idiomatic verb for tattoos": "descontraído; stechen lassen (literalmente 'mandar picar') é o verbo idiomático para as tatuagens",
  "casual; the question everyone asks": "descontraído; a pergunta que toda a gente faz",
  "casual; the standard (optimistic) answer": "descontraído; a resposta habitual (otimista)",
  "Casual; the way adults confess it with a grin.": "Descontraído; a forma como os adultos o confessam com um sorriso.",
  "casual: kicken gehen = to go and play football": "descontraído: kicken gehen = ir jogar à bola",
  "Casual. 'Baden gehen' = swim outdoors (lake, sea); 'schwimmen gehen' leans towards the pool.": "Descontraído. 'Baden gehen' = ir a banhos ao ar livre (lago, mar); 'schwimmen gehen' puxa mais para a piscina.",
  "Casual. 'Eine Runde drehen' = do a loop; works for walks, bike rides or a quick drive.": "Descontraído. 'Eine Runde drehen' = dar uma volta; serve para passeios, voltas de bicicleta ou um passeio curto de carro.",
  "Casual. 'Sich etwas holen' = to catch/get something (sunburn, a cold).": "Descontraído. 'Sich etwas holen' = apanhar alguma coisa (escaldão, constipação).",
  "casually clipped to 'der Elfer'": "encurtado coloquialmente para 'der Elfer'",
  "Chores": "Tarefas domésticas",
  "close friends only — sharing a cigarette or vape": "só entre amigos próximos — partilhar um cigarro ou um vaper",
  "Coarse and common among friends. It can sound confrontational when said angrily.": "Grosseiro e comum entre amigos. Dito com raiva, pode soar a confronto.",
  "Coarse-casual — 'forget it, who cares'. Banter-safe among friends; not for formal company.": "Grosseiro e descontraído — 'esquece, quem se importa'. Vale como brincadeira entre amigos; não em companhia formal.",
  "coden is casual Denglisch; completely normal in the du-form dev crowd.": "coden é denglisch descontraído; perfeitamente normal no meio dev que se trata por tu.",
  "Colloquial (Kopfnuss = headbutt/noogie)": "Coloquial (Kopfnuss = cabeçada ou cascudo)",
  "Colloquial and strong; covers verbal and psychological cruelty, not just physical.": "Coloquial e forte; abrange a crueldade verbal e psicológica, não só a física.",
  "Colloquial and strong; verbal or psychological cruelty": "Coloquial e forte; crueldade verbal ou psicológica",
  "colloquial anglicism (Duden-listed); marketing and social media register": "anglicismo coloquial (registado no Duden); registo do marketing e das redes sociais",
  "Colloquial but harmless — safe with colleagues and family.": "Coloquial mas inofensivo — seguro com colegas e família.",
  "Colloquial but serious; 'zu dritt' = three of them together.": "Coloquial mas sério; 'zu dritt' = os três juntos.",
  "Colloquial combo of Ja + Nein": "Mistura coloquial de Ja + Nein",
  "colloquial intensifier: mächtig stolz = mighty proud": "intensificador coloquial: mächtig stolz = orgulhosíssimo",
  "Colloquial short form of herauskommen; also used of films, products or models being released.": "Forma curta coloquial de herauskommen; também para filmes, produtos ou modelos que saem.",
  "Colloquial shortcut": "Atalho coloquial",
  "Colloquial, mild — gasped mid-laughter or typed in chats. Friends, family, relaxed colleagues.": "Coloquial, ligeiro — atirado a meio de uma gargalhada ou escrito no chat. Amigos, família, colegas descontraídos.",
  "colloquial, what children do in sand; graben is neutral": "coloquial, o que as crianças fazem na areia; graben é neutro",
  "Colloquial; 'sich prügeln' is physical, much stronger than 'sich streiten'.": "Coloquial; 'sich prügeln' é físico, muito mais forte do que 'sich streiten'.",
  "colloquial; invariable: ein super Film": "coloquial; invariável: ein super Film",
  "colloquially also snappy, punchy (UI, prose, deadlines)": "coloquialmente também ágil, incisivo (interfaces, textos, prazos)",
  "colloquially shortened to 'das Gespräch'": "encurtado coloquialmente para 'das Gespräch'",
  "common and informal; can describe a person, idea or situation": "comum e informal; pode descrever uma pessoa, uma ideia ou uma situação",
  "Common complaint": "Queixa comum",
  "Common slang reaction": "Reação comum em calão",
  "Common slang reaction to bad news — mies = lousy, shabby": "Reação comum em calão a más notícias — mies = mau, reles",
  "Confirming": "Confirmar",
  "Consent": "Consentimento",
  "Consent — always check": "Consentimento — pergunta sempre",
  "Conversational geopolitics with an opinion baked in — fine among friends, spicier at work": "Geopolítica de conversa com opinião incluída — tudo bem entre amigos, mais melindroso no trabalho",
  "dark humour among friends; 'Echsenmenschen' is the go-to absurd-conspiracy reference": "humor negro entre amigos; 'Echsenmenschen' é a referência típica às conspirações absurdas",
  "das Band — the conveyor. Braking on it is the one real mistake to avoid.": "das Band — o tapete rolante. Travar em cima é o único erro a evitar mesmo.",
  "das Bügeleisen — the iron. The warning every household repeats.": "das Bügeleisen — o ferro de engomar. O aviso que se repete em todas as casas.",
  "das Halbjahreszeugnis — the February report. The early warning system.": "das Halbjahreszeugnis — a pauta de fevereiro. O sistema de alerta precoce.",
  "Das hängt davon ab = it depends. Casually, mit Freunden abhängen = to hang out.": "Das hängt davon ab = depende. Em tom descontraído, mit Freunden abhängen = passar tempo com os amigos.",
  "das Profil — the tread. 'ist runter' — worn away; casual passive Germany runs on.": "das Profil — o piso do pneu. 'ist runter' — gasto; a passiva descontraída sobre a qual a Alemanha anda.",
  "das Rücklicht — the rear light. 'nur noch schwach' — the warning phase before darkness.": "das Rücklicht — a luz de trás. 'nur noch schwach' — a fase de aviso antes da escuridão.",
  "das Teil — the casual word for any piece of clothing. The rule that prevents the pink wash.": "das Teil — a palavra descontraída para qualquer peça de roupa. A regra que evita a roupa toda cor-de-rosa.",
  "das Wartezimmer — from the doctor pack, considerably louder. Cats sit high; dogs make friends.": "das Wartezimmer — do pacote do médico, bastante mais barulhenta. Os gatos ficam no alto; os cães fazem amigos.",
  "Dating": "Encontros",
  "Deliberately vague — it lets both sides keep it casual. 'was' here is short for 'etwas'.": "Deliberadamente vago — deixa ambas as partes manterem o tom descontraído. Aqui 'was' é a forma curta de 'etwas'.",
  "der Aszendent — the follow-up question that separates casual from committed.": "der Aszendent — a pergunta seguinte que separa os curiosos dos convictos.",
  "der Helferkreis — the informal volunteer group, common in refugee and neighbourhood support.": "der Helferkreis — o grupo de voluntários informal, comum no apoio a refugiados e de bairro.",
  "der Platten — the flat tyre, colloquial and universal. The commute's classic opening line.": "der Platten — o furo no pneu, coloquial e universal. A clássica frase de abertura sobre o trajeto.",
  "der Strafzettel, colloquially das Knöllchen = parking ticket": "der Strafzettel, coloquialmente das Knöllchen = multa de estacionamento",
  "Desire": "Desejo",
  "die Abmahnung — the warning shot, at work or over copyright. Serious, not final.": "die Abmahnung — o tiro de aviso, no trabalho ou por direitos de autor. Sério, mas não definitivo.",
  "die Abmahnung — the written warning. Serious, but far from a dismissal.": "die Abmahnung — a advertência por escrito. Séria, mas longe de um despedimento.",
  "die Hausnummer — colloquial for a rough figure. More with a role change.": "die Hausnummer — coloquial para um valor aproximado. Mais, se o cargo mudar.",
  "die Jugendfeuerwehr — where most volunteers begin. Knots, hoses and friendships.": "die Jugendfeuerwehr — onde começa a maioria dos voluntários. Nós, mangueiras e amizades.",
  "die Kantine — the subsidised lunch. The invitation that builds actual friendships.": "die Kantine — o almoço subsidiado. O convite de onde nascem amizades a sério.",
  "die Lawine — the avalanche. The warning is not decorative.": "die Lawine — a avalanche. O aviso não é decorativo.",
  "Direct and neutral: 'Ich bin schwanger.' Colloquially, 'schwanger von ihm' names the father.": "Direto e neutro: 'Ich bin schwanger.' Coloquialmente, 'schwanger von ihm' nomeia o pai.",
  "düngen = to fertilize; der Dünger = fertilizer. Du register — said between family/friends": "düngen = adubar; der Dünger = o adubo. Registo do du — diz-se em família e entre amigos",
  "eh = anyway / in any case (colloquial 'ohnehin')": "eh = de qualquer forma / em todo o caso (coloquial por 'ohnehin')",
  "eine Runde schmeißen — literally throwing a round. Casual, generous, slightly theatrical.": "eine Runde schmeißen — literalmente atirar uma rodada. Descontraído, generoso, um pouco teatral.",
  "Emergency": "Emergência",
  "Emphasis": "Ênfase",
  "Emphatic casual yes": "Sim descontraído e enfático",
  "Encouragement between friends or from a partner — the compliment learners most want to hear.": "Incentivo entre amigos ou do parceiro — o elogio que quem aprende mais quer ouvir.",
  "Enemy info": "Info do inimigo",
  "English loan, fully naturalized and plural; 'doch' makes it dismissive — casual register": "estrangeirismo do inglês, plenamente naturalizado e no plural; 'doch' torna-o desdenhoso — registo descontraído",
  "Enthusiastic yes": "Sim entusiasmado",
  "Essential": "Essencial",
  "everyday casual word; also means the stubbed-out butt": "palavra descontraída do dia a dia; também significa a beata apagada",
  "Everyday colloquial spelling of nichts": "Grafia coloquial do dia a dia de nichts",
  "Everyday connection method (slang 'schreib mir')": "Forma do dia a dia de manter o contacto (calão 'schreib mir')",
  "Everyday criticism, medium weight; fine in casual talk about colleagues or exes.": "Crítica do dia a dia, de peso médio; serve numa conversa descontraída sobre colegas ou ex.",
  "Everyday office and friend request; rüberschicken (send over) is the casual variant.": "Pedido do dia a dia no escritório e entre amigos; rüberschicken (mandar) é a variante descontraída.",
  "Everyday slang (Bock haben)": "Calão do dia a dia (Bock haben)",
  "Everyday slang (spendieren = to treat)": "Calão do dia a dia (spendieren = pagar, oferecer)",
  "Facharzt = specialist; colloquially also \"einen Termin ausmachen\"": "Facharzt = médico especialista; coloquialmente também 'einen Termin ausmachen'",
  "Falschparken = illegal/incorrect parking": "Falschparken = estacionar mal ou onde não se deve",
  "Family": "Família",
  "Famous last words — friends will quote it back at you for months.": "Famosas últimas palavras — os amigos vão citá-las durante meses.",
  "Farewell": "Despedida",
  "Feeling": "Sentimento",
  "feiern = to celebrate, colloquially 'to love something'; very current usage.": "feiern = festejar, coloquialmente 'adorar alguma coisa'; uso muito atual.",
  "fett = huge (colloquial intensifier); standard dev talk, not rude.": "fett = enorme (intensificador coloquial); jargão dev normal, não é grosseiro.",
  "Finding help": "Encontrar ajuda",
  "Fixed casual set expression; already short, so no further clipping.": "Expressão fixa descontraída; já é curta, por isso não se encurta mais.",
  "flach and steil around dahinter — the swimming-pool warning as a geometry lesson.": "flach e steil à volta de dahinter — o aviso da piscina como aula de geometria.",
  "Flight status update": "Estado do voo",
  "Flirting": "Namoriscar",
  "Formal": "Formal",
  "Frustrated, to friends. 'schon wieder' carries the job-hunt fatigue.": "Com frustração, entre amigos. 'schon wieder' carrega o cansaço da procura de emprego.",
  "geblitzt werden = to get caught by a speed camera — the standard colloquial verb for it": "geblitzt werden = ser apanhado por um radar — o verbo coloquial padrão para isso",
  "Gen-Z": "Gen Z",
  "Genuine compliment between friends; on a date it's practically flirting.": "Elogio genuíno entre amigos; num encontro é praticamente namoro.",
  "gereizt — irritable, like a nerve already touched. Fair warning to the room.": "gereizt — irritável, como um nervo já tocado. Um aviso honesto a toda a sala.",
  "gib — du-imperative of geben with vowel change; mal keeps it casual, not bossy.": "gib — imperativo de du de geben com mudança de vogal; mal mantém o tom descontraído, não mandão.",
  "Greeting": "Cumprimento",
  "Grufti = colloquial for goth (from Gruft = tomb/crypt)": "Grufti = coloquial para gótico (de Gruft = cripta, jazigo)",
  "Gunsmith": "Armeiro",
  "Half-joking household rule for the unsortable. Colloquial, said with a shrug.": "Regra caseira meio a brincar para tudo o que não se consegue separar. Coloquial, dito com um encolher de ombros.",
  "half-joking quitter's line; 'ich schwör' is casual spoken German": "frase meio a brincar de quem desiste; 'ich schwör' é alemão falado descontraído",
  "idiomatic, informal": "idiomático, informal",
  "Im Alter von 30 = at the age of 30. As an exclamation, Alter! = dude! — very casual.": "Im Alter von 30 = aos 30 anos. Como exclamação, Alter! = meu! — muito descontraído.",
  "in casual speech often shortened to was: Hast du was gehört?": "na fala descontraída encurta-se muitas vezes para was: Hast du was gehört?",
  "In the moment": "No momento",
  "Informal": "Informal",
  "Informal — friends only": "Informal — só entre amigos",
  "Informal — the spoken contraction you'll usually hear": "Informal — a contração falada que se ouve normalmente",
  "Informal — to strangers or staff say: Sprechen Sie Englisch?": "Informal — a desconhecidos ou a funcionários diz-se: Sprechen Sie Englisch?",
  "Informal and rude: jemandem den Stinkefinger zeigen.": "Informal e grosseiro: jemandem den Stinkefinger zeigen.",
  "Informal and warm, mostly southern. 'Grüß Gott' is its formal, Bavarian and Austrian cousin.": "Informal e caloroso, sobretudo no sul. 'Grüß Gott' é o primo formal, bávaro e austríaco.",
  "Informal imperative of separable 'aufheben': 'Heb ... auf'; the full written form is 'Hebe'.": "Imperativo informal do separável 'aufheben': 'Heb ... auf'; a forma escrita completa é 'Hebe'.",
  "informal loan from English; das Okay – the go-ahead": "estrangeirismo informal do inglês; das Okay – a luz verde",
  "Informal reply — with Sie say: Und Ihnen?": "Resposta informal — com Sie diz-se: Und Ihnen?",
  "Informal term for a friend": "Termo informal para um amigo",
  "informal, e.g. eine brenzlige Situation": "informal, p. ex. eine brenzlige Situation",
  "informal; the standard German way to say someone drifted off into conspiracy land": "informal; a forma alemã padrão de dizer que alguém derivou para o mundo das conspirações",
  "Introducing": "Apresentar-se",
  "justifying one more — works for cigarettes and beers alike; very casual": "para justificar mais um — serve tanto para cigarros como para cervejas; muito descontraído",
  "kicken — casual football. der Bolzplatz — the scuffed pitch every neighbourhood has.": "kicken — futebol descontraído. der Bolzplatz — o campo pelado que cada bairro tem.",
  "klamm — damp, and colloquially short of cash. Honest without being dramatic.": "klamm — húmido, e coloquialmente sem dinheiro. Honesto sem ser dramático.",
  "klingen — sounding. The honest warning given to every violin household's neighbours.": "klingen — soar. O aviso honesto aos vizinhos de qualquer casa com violino.",
  "knapp bei Kasse — tight at the till. The honest sentence that friends answer with einladen.": "knapp bei Kasse — apertado na caixa. A frase honesta a que os amigos respondem com einladen.",
  "Knast = colloquial for jail/prison": "Knast = coloquial para prisão, cadeia",
  "Komm doch mal vorbei! — the casual open invitation.": "Komm doch mal vorbei! — o convite aberto e descontraído.",
  "Leaving": "Ir embora",
  "Loadout": "Equipamento",
  "Logisch! is also a casual \"obviously\"": "Logisch! é também um 'claro' descontraído",
  "Making a move": "Dar o primeiro passo",
  "Making plans": "Fazer planos",
  "medium insult — banter-safe among close friends with the right tone": "insulto médio — aceitável como brincadeira entre amigos próximos, com o tom certo",
  "medium-strong — banter only with thick-skinned close friends": "médio-forte — só a brincar com amigos próximos de pele grossa",
  "Meta": "Meta",
  "Opinion": "Opinião",
  "Ordering food": "Pedir comida",
  "Plans": "Planos",
  "Position callout": "Aviso de posição",
  "Reacting": "Reagir",
  "Reassuring": "Tranquilizar",
  "Relationship status": "Estado da relação",
  "Reporting a problem": "Comunicar um problema",
  "Request": "Pedido",
  "Routine": "Rotina",
  "Scheduling": "Marcar",
  "Seasons": "Estações",
  "Slang": "Calão",
  "Status callout": "Aviso de estado",
  "Strong agreement": "Concordância forte",
  "Surprise": "Surpresa",
  "Symptom": "Sintoma",
  "Team play": "Jogo em equipa",
  "Telling time": "Dizer as horas",
  "Texting": "Mensagens",
  "Time comment": "Comentário sobre a hora",
  "Typical reply": "Resposta típica",
  "Unlocks": "Desbloqueios",
  "Urgent": "Urgente",
  "Very common leisure activity": "Atividade de lazer muito comum",
  "Weather": "Tempo",
  "Written German too": "Também no alemão escrito",
};
