/**
 * The usage notes in Italian.
 *
 * Keyed by the English note exactly as the card carries it. A note missing
 * from here shows its English, so this file is filled in batches without any
 * card ever going blank — see usageNotes.ts for how it is loaded and why it
 * is not part of the interface tables.
 *
 * Fourteen thousand notes exist. This holds the ones translated so far, and
 * check-usage-notes prints how far along each language is on every build.
 */
export const USE_IT: Record<string, string> = {
  "Afterwards": "Dopo",
  "Agreeing": "Essere d'accordo",
  "always plural": "sempre plurale",
  "Asking for the bill": "Chiedere il conto",
  "At the till": "Alla cassa",
  "Banter": "Battute",
  "Buying time": "Prendere tempo",
  "Casual reply": "Risposta informale",
  "Chores": "Faccende domestiche",
  "Common complaint": "Lamentela comune",
  "Confirming": "Confermare",
  "Consent": "Consenso",
  "Consent — always check": "Consenso — chiedi sempre",
  "Dating": "Appuntamenti",
  "Desire": "Desiderio",
  "Emergency": "Emergenza",
  "Emphasis": "Enfasi",
  "Enemy info": "Info sul nemico",
  "Enthusiastic yes": "Sì entusiasta",
  "Essential": "Essenziale",
  "Everyday slang (Bock haben)": "Gergo quotidiano (Bock haben)",
  "Family": "Famiglia",
  "Farewell": "Congedo",
  "Feeling": "Sentimento",
  "Finding help": "Trovare aiuto",
  "Flight status update": "Stato del volo",
  "Flirting": "Flirtare",
  "Formal": "Formale",
  "Gen-Z": "Gen Z",
  "Greeting": "Saluto",
  "Gunsmith": "Armaiolo",
  "In the moment": "Sul momento",
  "Introducing": "Presentarsi",
  "Leaving": "Andarsene",
  "Loadout": "Equipaggiamento",
  "Making a move": "Fare il primo passo",
  "Making plans": "Fare programmi",
  "Meta": "Meta",
  "Opinion": "Opinione",
  "Ordering food": "Ordinare da mangiare",
  "Plans": "Programmi",
  "Position callout": "Segnalazione di posizione",
  "Reacting": "Reagire",
  "Reassuring": "Rassicurare",
  "Relationship status": "Stato sentimentale",
  "Reporting a problem": "Segnalare un problema",
  "Request": "Richiesta",
  "Routine": "Routine",
  "Scheduling": "Organizzare",
  "Seasons": "Stagioni",
  "Slang": "Gergo",
  "Status callout": "Segnalazione di stato",
  "Strong agreement": "Accordo deciso",
  "Surprise": "Sorpresa",
  "Symptom": "Sintomo",
  "Team play": "Gioco di squadra",
  "Telling time": "Dire l'ora",
  "Texting": "Messaggi",
  "Time comment": "Commento sull'ora",
  "Typical reply": "Risposta tipica",
  "Unlocks": "Sblocchi",
  "Urgent": "Urgente",
  "Very common leisure activity": "Attività del tempo libero molto comune",
  "Weather": "Tempo",
  "Written German too": "Anche nel tedesco scritto",
};
