/**
 * The usage notes in Spanish.
 *
 * Keyed by the English note exactly as the card carries it. A note missing
 * from here shows its English, so this file is filled in batches without any
 * card ever going blank — see usageNotes.ts for how it is loaded and why it
 * is not part of the interface tables.
 *
 * Fourteen thousand notes exist. This holds the ones translated so far, and
 * check-usage-notes prints how far along each language is on every build.
 */
export const USE_ES: Record<string, string> = {
  "'doppelt' — double. 'Menge' is a quantity, and colloquially 'a lot'.": "'doppelt' — doble. 'Menge' es una cantidad y, coloquialmente, 'mucho'.",
  "'draufschauen' — to look at it. Colloquial and separable.": "'draufschauen' — echarle un vistazo. Coloquial y separable.",
  "'durch sein' — colloquially done for: soaked, worn out, finished.": "'durch sein' — coloquialmente acabado: empapado, gastado, terminado.",
  "'eigentlich' — the casual opener for a serious adult conversation.": "'eigentlich' — la entrada informal a una conversación seria entre adultos.",
  "'Elfer' is the casual clip everyone uses in speech": "'Elfer' es el recorte informal que todos usan al hablar",
  "'ewig' — eternally, used casually for 'ages'. 'laden' for loading.": "'ewig' — eternamente, en tono informal 'un siglo'. 'laden' para cargar.",
  "'gar nicht erst' — not even starting. Avoiding the problem entirely.": "'gar nicht erst' — ni siquiera empezar. Evitar el problema por completo.",
  "'gläubig' — devout. Said plainly, this ends no friendships in Germany.": "'gläubig' — creyente. Dicho sin más, en Alemania no rompe ninguna amistad.",
  "'schlapp' (colloquial) = run-down, drained; 'kaum' = barely.": "'schlapp' (coloquial) = decaído, agotado; 'kaum' = apenas.",
  "A colloquial fixed expression. It is not sexual in this use.": "Una expresión fija coloquial. En este uso no tiene sentido sexual.",
  "A common use of sammeln among friends, at work or in a family.": "Un uso habitual de sammeln entre amigos, en el trabajo o en familia.",
  "A direct warning that a condition or necessary step cannot be skipped.": "Una advertencia directa: no se puede saltar una condición o un paso necesario.",
  "A serious accusation, not casual criticism.": "Una acusación grave, no una crítica pasajera.",
  "A standing offer between partners or close friends; warm, no drama.": "Un ofrecimiento que siempre está en pie, entre pareja o amigos cercanos; cálido, sin dramas.",
  "A very common informal way to check whether a day suits someone.": "Una forma informal muy común de preguntar si un día le viene bien a alguien.",
  "Afterwards": "Después",
  "Agreeing": "Estar de acuerdo",
  "also colloquially \"incredibly\": unwahrscheinlich gut": "coloquialmente también 'increíblemente': unwahrscheinlich gut",
  "also colloquially \"massively\": tierisch gut": "coloquialmente también 'un montón': tierisch gut",
  "always plural": "siempre en plural",
  "Asking for the bill": "Pedir la cuenta",
  "At the till": "En la caja",
  "auslaufen — leaking out. 'hinüber sein' — colloquially beyond saving.": "auslaufen — salirse, gotear. 'hinüber sein' — coloquialmente, irrecuperable.",
  "Banter": "Bromas",
  "beraten — advising. 'einen' — the colloquial accusative of man.": "beraten — asesorar. 'einen' — el acusativo coloquial de man.",
  "Blunt insult, literally a full fencepost. Friends-only register.": "Insulto directo, literalmente un poste de valla entero. Solo entre amigos.",
  "bumming a cigarette; casual, smoker-to-smoker only": "gorronear un cigarrillo; informal, solo de fumador a fumador",
  "Buying time": "Ganar tiempo",
  "Casual": "Informal",
  "Casual — Ding literally means 'thing'": "Informal — Ding significa literalmente 'cosa'",
  "Casual — literally 'now we have the salad'": "Informal — literalmente 'ahora tenemos la ensalada'",
  "Casual — literally 'that's not my beer'": "Informal — literalmente 'esa no es mi cerveza'",
  "Casual — literally 'you had pig'": "Informal — literalmente 'tuviste cerdo'",
  "Casual agreement": "Acuerdo informal",
  "Casual check-in mid-explanation.": "Comprobación informal a mitad de una explicación.",
  "casual clipping of 'Prominenter' — everyday word": "recorte informal de 'Prominenter' — palabra de uso diario",
  "Casual complaint, one hour in. Someone packed too much Brotzeit.": "Queja informal tras una hora. Alguien metió demasiada Brotzeit.",
  "casual compliment; stehen + dative = to suit someone": "cumplido informal; stehen + dativo = quedarle bien a alguien",
  "Casual date invite (better than formal 'Möchten Sie...')": "Invitación a una cita en tono informal (mejor que el formal 'Möchten Sie...')",
  "casual Denglisch — 'Ich hab gecodet' is completely normal among devs": "denglisch informal — 'Ich hab gecodet' es de lo más normal entre desarrolladores",
  "Casual directive": "Indicación informal",
  "Casual everyday goodbye — used everywhere in Germany": "Despedida informal de cada día — se usa en toda Alemania",
  "Casual everyday reassurance": "Frase de tranquilidad informal del día a día",
  "Casual for playing video games; in money contexts it means to gamble.": "Informal para jugar a videojuegos; con dinero de por medio significa apostar.",
  "Casual goodbye — borrowed from Italian, extremely popular in Germany": "Despedida informal — tomada del italiano, muy popular en Alemania",
  "casual gym slang for lifting weights; 'pumpen gehen'": "argot informal de gimnasio para levantar pesas; 'pumpen gehen'",
  "Casual invite": "Invitación informal",
  "casual loanword; einkaufen is the German verb": "préstamo informal; einkaufen es el verbo alemán",
  "Casual opener": "Entrada de conversación informal",
  "Casual opener for close friends": "Entrada informal entre amigos cercanos",
  "Casual opinion": "Opinión informal",
  "Casual positive update": "Novedad positiva en tono informal",
  "Casual reminiscing; 'was los sein' = something happening.": "Recuerdos en tono informal; 'was los sein' = pasa algo.",
  "Casual reply": "Respuesta informal",
  "Casual request": "Petición informal",
  "Casual request to repeat": "Petición informal de que repitan",
  "Casual self-intro": "Presentación personal informal",
  "Casual slang command": "Orden en argot informal",
  "Casual slang farewell": "Despedida en argot informal",
  "casual spoken; from sich fertig machen = sich zurechtmachen": "habla informal; de sich fertig machen = arreglarse",
  "casual spoken; the machen-lassen pattern for anything done at a salon": "habla informal; el patrón machen-lassen para todo lo que se hace en un salón",
  "casual, admiring; 'definiert' = lean and cut, more technical": "informal y admirativo; 'definiert' = definido y marcado, más técnico",
  "Casual, teasing — literally 'do you have tomatoes on your eyes?'": "Informal y burlón — literalmente '¿tienes tomates en los ojos?'",
  "Casual, to companions. Famous last words on any hike.": "Informal, a los acompañantes. Las últimas palabras célebres de cualquier caminata.",
  "Casual, wry — literally 'life is no pony farm'": "Informal e irónico — literalmente 'la vida no es una granja de ponis'",
  "casual, younger speakers; Hautpflege is the more formal word": "informal, hablantes jóvenes; Hautpflege es la palabra más formal",
  "casual; 'platt' = wiped out, works for any exhaustion": "informal; 'platt' = hecho polvo, sirve para cualquier agotamiento",
  "casual; 'Proteinshake' works too": "informal; 'Proteinshake' también vale",
  "casual; 'sich etwas ziehen' = to pull a muscle": "informal; 'sich etwas ziehen' = darse un tirón muscular",
  "Casual; ackern makes the work sound tiring or relentless.": "Informal; ackern hace que el trabajo suene agotador e implacable.",
  "Casual; adults admit it with a grin": "Informal; los adultos lo admiten con una sonrisa",
  "casual; literally also to plough a field": "informal; literalmente también arar un campo",
  "casual; the question everyone asks": "informal; la pregunta que todo el mundo hace",
  "casual; the standard (optimistic) answer": "informal; la respuesta típica (optimista)",
  "Casual; the way adults confess it with a grin.": "Informal; así lo confiesan los adultos con una sonrisa.",
  "casual: kicken gehen = to go and play football": "informal: kicken gehen = ir a jugar al fútbol",
  "Casual. 'Sich etwas holen' = to catch/get something (sunburn, a cold).": "Informal. 'Sich etwas holen' = pillar algo (una quemadura solar, un resfriado).",
  "casually clipped to 'der Elfer'": "recortado coloquialmente a 'der Elfer'",
  "Chores": "Tareas de casa",
  "close friends only — sharing a cigarette or vape": "solo entre amigos cercanos — compartir un cigarrillo o un vaper",
  "coden is casual Denglisch; completely normal in the du-form dev crowd.": "coden es denglisch informal; de lo más normal en el mundillo dev que se tutea.",
  "Colloquial (Kopfnuss = headbutt/noogie)": "Coloquial (Kopfnuss = cabezazo o coscorrón)",
  "Colloquial and strong; verbal or psychological cruelty": "Coloquial y fuerte; crueldad verbal o psicológica",
  "Colloquial but harmless — safe with colleagues and family.": "Coloquial pero inofensivo — seguro con compañeros y familia.",
  "Colloquial but serious; 'zu dritt' = three of them together.": "Coloquial pero serio; 'zu dritt' = entre tres.",
  "Colloquial combo of Ja + Nein": "Mezcla coloquial de Ja + Nein",
  "colloquial intensifier: mächtig stolz = mighty proud": "intensificador coloquial: mächtig stolz = orgullosísimo",
  "Colloquial shortcut": "Atajo coloquial",
  "colloquial, what children do in sand; graben is neutral": "coloquial, lo que hacen los niños en la arena; graben es neutro",
  "colloquial; invariable: ein super Film": "coloquial; invariable: ein super Film",
  "colloquially also snappy, punchy (UI, prose, deadlines)": "coloquialmente también ágil, contundente (interfaces, textos, plazos)",
  "colloquially shortened to 'das Gespräch'": "acortado coloquialmente a 'das Gespräch'",
  "common and informal; can describe a person, idea or situation": "habitual e informal; puede describir a una persona, una idea o una situación",
  "Common complaint": "Queja frecuente",
  "Common slang reaction": "Reacción habitual en argot",
  "Common slang reaction to bad news — mies = lousy, shabby": "Reacción habitual en argot ante malas noticias — mies = malo, cutre",
  "Confirming": "Confirmar",
  "Consent": "Consentimiento",
  "Consent — always check": "Consentimiento — pregunta siempre",
  "das Bügeleisen — the iron. The warning every household repeats.": "das Bügeleisen — la plancha. La advertencia que repite cada casa.",
  "das Halbjahreszeugnis — the February report. The early warning system.": "das Halbjahreszeugnis — el boletín de febrero. El sistema de alerta temprana.",
  "Dating": "Citas",
  "der Strafzettel, colloquially das Knöllchen = parking ticket": "der Strafzettel, coloquialmente das Knöllchen = multa de aparcamiento",
  "Desire": "Deseo",
  "die Lawine — the avalanche. The warning is not decorative.": "die Lawine — la avalancha. La advertencia no es decorativa.",
  "eh = anyway / in any case (colloquial 'ohnehin')": "eh = de todos modos / en cualquier caso (coloquial por 'ohnehin')",
  "Emergency": "Emergencia",
  "Emphasis": "Énfasis",
  "Emphatic casual yes": "Sí informal y enfático",
  "Enemy info": "Info del enemigo",
  "Enthusiastic yes": "Sí entusiasta",
  "Essential": "Imprescindible",
  "everyday casual word; also means the stubbed-out butt": "palabra informal de cada día; también significa la colilla apagada",
  "Everyday colloquial spelling of nichts": "Grafía coloquial cotidiana de nichts",
  "Everyday connection method (slang 'schreib mir')": "Manera cotidiana de mantener el contacto (argot 'schreib mir')",
  "Everyday slang (Bock haben)": "Argot cotidiano (Bock haben)",
  "Everyday slang (spendieren = to treat)": "Argot cotidiano (spendieren = invitar)",
  "Facharzt = specialist; colloquially also \"einen Termin ausmachen\"": "Facharzt = médico especialista; coloquialmente también 'einen Termin ausmachen'",
  "Falschparken = illegal/incorrect parking": "Falschparken = aparcar mal o donde no se debe",
  "Family": "Familia",
  "Famous last words — friends will quote it back at you for months.": "Últimas palabras célebres — tus amigos te lo repetirán durante meses.",
  "Farewell": "Despedida",
  "Feeling": "Sentimiento",
  "fett = huge (colloquial intensifier); standard dev talk, not rude.": "fett = enorme (intensificador coloquial); jerga dev habitual, no es grosero.",
  "Finding help": "Buscar ayuda",
  "Fixed casual set expression; already short, so no further clipping.": "Expresión fija informal; ya es corta, así que no se recorta más.",
  "Flight status update": "Estado del vuelo",
  "Flirting": "Ligar",
  "Formal": "Formal",
  "Frustrated, to friends. 'schon wieder' carries the job-hunt fatigue.": "Con frustración, entre amigos. 'schon wieder' lleva el cansancio de buscar trabajo.",
  "Gen-Z": "Gen Z",
  "Greeting": "Saludo",
  "Grufti = colloquial for goth (from Gruft = tomb/crypt)": "Grufti = coloquial para gótico (de Gruft = cripta, tumba)",
  "Gunsmith": "Armería",
  "half-joking quitter's line; 'ich schwör' is casual spoken German": "frase medio en broma de quien lo deja; 'ich schwör' es alemán hablado informal",
  "idiomatic, informal": "idiomático, informal",
  "in casual speech often shortened to was: Hast du was gehört?": "en el habla informal se acorta a menudo a was: Hast du was gehört?",
  "In the moment": "En el momento",
  "Informal": "Informal",
  "Informal — friends only": "Informal — solo entre amigos",
  "Informal — the spoken contraction you'll usually hear": "Informal — la contracción hablada que se oye normalmente",
  "Informal — to strangers or staff say: Sprechen Sie Englisch?": "Informal — a desconocidos o al personal se dice: Sprechen Sie Englisch?",
  "Informal and rude: jemandem den Stinkefinger zeigen.": "Informal y grosero: jemandem den Stinkefinger zeigen.",
  "informal loan from English; das Okay – the go-ahead": "préstamo informal del inglés; das Okay – el visto bueno",
  "Informal reply — with Sie say: Und Ihnen?": "Respuesta informal — con Sie se dice: Und Ihnen?",
  "Informal term for a friend": "Término informal para un amigo",
  "informal, e.g. eine brenzlige Situation": "informal, p. ej. eine brenzlige Situation",
  "Introducing": "Presentarse",
  "Knast = colloquial for jail/prison": "Knast = coloquial para cárcel, trena",
  "Komm doch mal vorbei! — the casual open invitation.": "Komm doch mal vorbei! — la invitación abierta e informal.",
  "Leaving": "Irse",
  "Loadout": "Equipamiento",
  "Logisch! is also a casual \"obviously\"": "Logisch! es también un 'obvio' informal",
  "Making a move": "Dar el primer paso",
  "Making plans": "Hacer planes",
  "medium insult — banter-safe among close friends with the right tone": "insulto medio — vale como broma entre amigos cercanos con el tono adecuado",
  "medium-strong — banter only with thick-skinned close friends": "de fuerza media-alta — solo en broma con amigos cercanos de piel dura",
  "Meta": "Meta",
  "Opinion": "Opinión",
  "Ordering food": "Pedir comida",
  "Plans": "Planes",
  "Position callout": "Aviso de posición",
  "Reacting": "Reaccionar",
  "Reassuring": "Tranquilizar",
  "Relationship status": "Estado sentimental",
  "Reporting a problem": "Informar de un problema",
  "Request": "Petición",
  "Routine": "Rutina",
  "Scheduling": "Programar",
  "Seasons": "Estaciones",
  "Slang": "Argot",
  "Status callout": "Aviso de estado",
  "Strong agreement": "Acuerdo rotundo",
  "Surprise": "Sorpresa",
  "Symptom": "Síntoma",
  "Team play": "Juego en equipo",
  "Telling time": "Decir la hora",
  "Texting": "Mensajes",
  "Time comment": "Comentario sobre la hora",
  "Typical reply": "Respuesta típica",
  "Unlocks": "Desbloqueos",
  "Urgent": "Urgente",
  "Very common leisure activity": "Actividad de ocio muy común",
  "Weather": "El tiempo",
  "Written German too": "También en alemán escrito",
};
