/**
 * The usage notes in Italian.
 *
 * Keyed by the English note exactly as the card carries it. A note missing
 * from here shows its English, so this file is filled in batches without any
 * card ever going blank — see usageNotes.ts for how it is loaded and why it
 * is not part of the interface tables.
 *
 * Fourteen thousand notes exist. This holds the ones translated so far, and
 * check-usage-notes prints how far along each language is on every build.
 */
export const USE_IT: Record<string, string> = {
  "'abschleppen' — to tow. Colloquially it also means pulling someone in a bar.": "'abschleppen' — rimorchiare. Colloquialmente significa anche rimorchiare qualcuno in un bar.",
  "'angesagt sein' — forecast, announced. Also slang for what's currently trendy.": "'angesagt sein' — annunciato, previsto. In gergo anche: quello che va di moda adesso.",
  "'auf etwas stehen' — to be into something. Informal, current, and used constantly.": "'auf etwas stehen' — andare matti per qualcosa. Informale, attuale e usatissimo.",
  "'bedeuten' for meaning. 'Was heißt das?' is the more casual version and just as correct.": "'bedeuten' per il significato. 'Was heißt das?' è la versione più informale e altrettanto corretta.",
  "'Das Match' — loan for a full competitive game; 'ist Schluss' = are we done. Casual.": "'Das Match' — prestito per una partita intera; 'ist Schluss' = è finita. Informale.",
  "'davon' avoids repeating the product name after pointing or asking a question about it.": "'davon' evita di ripetere il nome del prodotto dopo averlo indicato o dopo averne chiesto.",
  "'davon' refers to an amount of the thing already being discussed and avoids repeating its name.": "'davon' rimanda a una quantità della cosa di cui si sta già parlando ed evita di ripeterne il nome.",
  "'Der Hammer' = the standard casual superlative for events. Informal, all ages under about 50.": "'Der Hammer' = il superlativo informale tipico per un evento. Informale, sotto i 50 anni circa.",
  "'Der Ping' — English loan, no alternative. 'übel' is youth slang for 'terrible'.": "'Der Ping' — prestito dall'inglese, senza alternative. 'übel' è gergo giovanile per 'orribile'.",
  "'doppelt' — double. 'Menge' is a quantity, and colloquially 'a lot'.": "'doppelt' — doppio. 'Menge' è una quantità e, colloquialmente, 'molto'.",
  "'dran sein' — to be next in turn. Compact, informal and used constantly.": "'dran sein' — essere il prossimo di turno. Compatto, informale e usatissimo.",
  "'draufschauen' — to look at it. Colloquial and separable.": "'draufschauen' — dargli un'occhiata. Colloquiale e separabile.",
  "'Du hast einen guten Musikgeschmack' is a real compliment between friends or on a date.": "'Du hast einen guten Musikgeschmack' è un complimento vero tra amici o a un appuntamento.",
  "'durch sein' — colloquially done for: soaked, worn out, finished.": "'durch sein' — colloquialmente spacciato: fradicio, consumato, finito.",
  "'eigentlich' — the casual opener for a serious adult conversation.": "'eigentlich' — l'attacco disinvolto di una conversazione seria tra adulti.",
  "'Elfer' is the casual clip everyone uses in speech": "'Elfer' è l'abbreviazione informale che tutti usano parlando",
  "'ewig' — eternally, used casually for 'ages'. 'laden' for loading.": "'ewig' — eternamente, in tono informale 'un'eternità'. 'laden' per il caricamento.",
  "'frei Schnauze' — literally free snout: no recipe, pure instinct. Wonderfully casual.": "'frei Schnauze' — alla lettera muso libero: niente ricetta, puro istinto. Splendidamente informale.",
  "'gar nicht erst' — not even starting. Avoiding the problem entirely.": "'gar nicht erst' — non cominciare nemmeno. Evitare del tutto il problema.",
  "'glatt' — slippery with ice. The winter warning Germans text each other.": "'glatt' — ghiacciato, scivoloso. L'avvertimento invernale che i tedeschi si scrivono.",
  "'gläubig' — devout. Said plainly, this ends no friendships in Germany.": "'gläubig' — credente. Detto con semplicità, in Germania non rovina nessuna amicizia.",
  "'gucken' is the casual everyday verb (north/central); the south says 'schauen'": "'gucken' è il verbo informale di tutti i giorni (nord e centro); il sud dice 'schauen'",
  "'halbe-halbe' is common informal German for dividing something into two equal parts.": "'halbe-halbe' è tedesco informale comune per dividere qualcosa in due parti uguali.",
  "'hinkriegen' — to manage or pull something off. Informal, warm and extremely common.": "'hinkriegen' — riuscire a fare qualcosa, farcela. Informale, caloroso e comunissimo.",
  "'jeder zahlt seins' — the German default among friends. No awkwardness; it's the system.": "'jeder zahlt seins' — la regola normale tra amici in Germania. Niente imbarazzo: funziona così.",
  "'Jetzt reicht's' is the short version, and the last warning before a row.": "'Jetzt reicht's' è la versione breve, e l'ultimo avvertimento prima della lite.",
  "'Kein Thema' — not a topic: it doesn't even need discussing. Friendship in two words.": "'Kein Thema' — non è un argomento: non c'è nemmeno da discuterne. L'amicizia in due parole.",
  "'mal' makes the command sound casual; use 'in die Ecke' when directing light into it.": "'mal' rende l'ordine informale; 'in die Ecke' si usa quando ci si dirige la luce dentro.",
  "'mal' softens the imperative into a casual request; masculine object is 'deinen Benutzernamen'.": "'mal' ammorbidisce l'imperativo in una richiesta informale; l'oggetto maschile è 'deinen Benutzernamen'.",
  "'mal' turns an offer into something casual. Two seconds, no commitment.": "'mal' rende l'offerta informale. Due secondi, nessun impegno.",
  "'mitnehmen' is separable; in the informal imperative, 'mit' lands at the end.": "'mitnehmen' è separabile; nell'imperativo informale, 'mit' finisce in fondo.",
  "'Pass auf!' is the fastest warning; separable 'aufpassen' becomes 'pass ... auf'.": "'Pass auf!' è l'avvertimento più rapido; il separabile 'aufpassen' diventa 'pass ... auf'.",
  "'rausfliegen' — from the fuse pack, here about a back. Colloquial and instantly understood.": "'rausfliegen' — dal pacchetto sui fusibili, qui su una schiena. Colloquiale e capito all'istante.",
  "'schauen' or 'gucken' — gucken is more casual. No preposition before the platform.": "'schauen' o 'gucken' — gucken è più informale. Nessuna preposizione davanti alla piattaforma.",
  "'schlapp' (colloquial) = run-down, drained; 'kaum' = barely.": "'schlapp' (colloquiale) = fiacco, svuotato; 'kaum' = appena.",
  "'sicherheitshalber' explains that you are checking to avoid an unnecessary mistake.": "'sicherheitshalber' spiega che stai controllando per evitare un errore inutile.",
  "'sportlich' — sporty, and also 'smart-casual' about clothes. Both are common.": "'sportlich' — sportivo, e con i vestiti anche 'casual elegante'. Entrambi sono comuni.",
  "'total' as an intensifier is thoroughly spoken German and slightly informal.": "'total' come intensificatore è tedesco parlato al cento per cento e un po' informale.",
  "'unterschiedlich' — differing. Germans use it constantly to avoid overgeneralising.": "'unterschiedlich' — diverso, variabile. I tedeschi lo usano di continuo per non generalizzare.",
  "'was trinken gehen' — the standard invitation. Casual, open-ended, no commitment implied.": "'was trinken gehen' — l'invito standard. Informale, aperto, senza impegno.",
  "'wegmachen' colloquially for putting something aside. 'mal' softens the announcement.": "'wegmachen' colloquialmente per mettere via qualcosa. 'mal' addolcisce l'annuncio.",
  "'Wie hoch' for amounts of money. A completely normal question between German friends.": "'Wie hoch' per le somme di denaro. Una domanda del tutto normale tra amici tedeschi.",
  "'wieder drauf haben' — colloquial and compact. Bike chains come off constantly.": "'wieder drauf haben' — colloquiale e compatto. Le catene delle bici saltano di continuo.",
  "'Wofür' is the normal neutral form; 'für was' is regional or very casual.": "'Wofür' è la forma neutra normale; 'für was' è regionale o molto informale.",
  "'Zeit mitbringen' — the honest warning. Open hours mean open-ended waiting.": "'Zeit mitbringen' — l'avvertimento onesto. Orari senza appuntamento vogliono dire attesa senza fine.",
  "A casual purpose question when someone has an object, tool, file or unusual plan.": "Una domanda informale sullo scopo, quando qualcuno ha un oggetto, un attrezzo, un file o un piano insolito.",
  "A colloquial fixed expression. It is not sexual in this use.": "Un'espressione fissa colloquiale. In questo uso non ha senso sessuale.",
  "A common informal response to disappointing news or an annoying problem.": "Una reazione informale comune a una notizia deludente o a un problema fastidioso.",
  "A common use of sammeln among friends, at work or in a family.": "Un uso comune di sammeln tra amici, al lavoro o in famiglia.",
  "A considerate response to bad news when a casual reaction would feel too light.": "Una risposta rispettosa a una brutta notizia, quando una reazione informale suonerebbe troppo leggera.",
  "A direct warning that a condition or necessary step cannot be skipped.": "Un avvertimento diretto: una condizione o un passaggio necessario non si può saltare.",
  "A natural follow-up after meeting two friends. 'seid ihr' addresses both people together.": "Una domanda di seguito naturale dopo aver incontrato due amici. 'seid ihr' si rivolge a entrambi insieme.",
  "A normal informal request for a very short wait. Add 'bitte' when you want it to sound softer.": "Una normale richiesta informale di aspettare un attimo. Aggiungi 'bitte' per addolcirla.",
  "A practical check that helps the group avoid stopping again once the task has begun.": "Una verifica pratica che evita al gruppo di doversi fermare di nuovo una volta iniziato.",
  "A serious accusation, not casual criticism.": "Un'accusa grave, non una critica di passaggio.",
  "A standard informal request. The favour itself normally follows immediately.": "Una richiesta informale standard. Il favore vero e proprio arriva di solito subito dopo.",
  "A standard Monday small-talk question with friends, classmates and colleagues you know.": "La classica domanda di convenevoli del lunedì tra amici, compagni di classe e colleghi che si conoscono.",
  "A standing offer between partners or close friends; warm, no drama.": "Un'offerta sempre valida tra partner o amici stretti; affettuosa, senza drammi.",
  "A very common informal way to check whether a day suits someone.": "Un modo informale molto comune per chiedere se un giorno va bene a qualcuno.",
  "abgefahren — driven off, worn. Also slang for 'amazing'; the tyre meaning is older.": "abgefahren — consumato, liscio. In gergo anche 'pazzesco'; il senso legato allo pneumatico è più antico.",
  "Achtung! is the warning word; die Ampel = the traffic light, always feminine.": "Achtung! è la parola di avvertimento; die Ampel = il semaforo, sempre femminile.",
  "Afterwards": "Dopo",
  "Agreeing": "Essere d'accordo",
  "Allotment neighbours — advisors, rivals and friends across one fence. Mostly all three.": "Vicini dell'orto urbano — consiglieri, rivali e amici ai due lati di una staccionata. Quasi sempre tutte e tre le cose.",
  "also colloquially \"incredibly\": unwahrscheinlich gut": "colloquialmente anche 'incredibilmente': unwahrscheinlich gut",
  "also colloquially \"massively\": tierisch gut": "colloquialmente anche 'da matti': tierisch gut",
  "always plural": "sempre plurale",
  "An informal reaction to a plan failing, something breaking or another everyday setback.": "Una reazione informale quando un piano salta, qualcosa si rompe o arriva un altro contrattempo quotidiano.",
  "Asking for the bill": "Chiedere il conto",
  "At the table, informal. One guest: 'Greif zu!' Signals the eating may begin.": "A tavola, informale. Con un solo ospite: 'Greif zu!' Segnala che si può iniziare a mangiare.",
  "At the till": "Alla cassa",
  "aufblasen — inflating. 'Hilf mir mal' — the casual recruiting of bystanders.": "aufblasen — gonfiare. 'Hilf mir mal' — il modo informale di arruolare chi sta lì intorno.",
  "aufdrängen — pressing something on someone. The warning before every market stroll.": "aufdrängen — rifilare qualcosa a qualcuno. L'avvertimento prima di ogni giro al mercato.",
  "aufziehen — a storm pulling up. denn delivers the warning in plain word order.": "aufziehen — un temporale che si avvicina. denn dà l'avvertimento con l'ordine delle parole più semplice.",
  "auslaufen — leaking out. 'hinüber sein' — colloquially beyond saving.": "auslaufen — fuoriuscire. 'hinüber sein' — colloquialmente, andato.",
  "Banter": "Battute",
  "beraten — advising. 'einen' — the colloquial accusative of man.": "beraten — consigliare. 'einen' — l'accusativo colloquiale di man.",
  "Between friends: Kannst du mir zehn Euro borgen? Standard German prefers leihen.": "Tra amici: Kannst du mir zehn Euro borgen? Il tedesco standard preferisce leihen.",
  "Blunt but completely normal between partners and friends — German directness in action": "Diretto ma del tutto normale tra partner e amici — la schiettezza tedesca in azione",
  "Blunt insult, literally a full fencepost. Friends-only register.": "Insulto pesante, alla lettera un palo da recinzione intero. Solo tra amici.",
  "borgen — the casual borrow-lend verb. die Leiter migrates between households like a shared pet.": "borgen — il verbo informale per prestare e farsi prestare. die Leiter migra di casa in casa come un animale in comune.",
  "bumming a cigarette; casual, smoker-to-smoker only": "scroccare una sigaretta; informale, solo tra fumatori",
  "Buying time": "Prendere tempo",
  "Casual": "Informale",
  "Casual — Ding literally means 'thing'": "Informale — Ding significa letteralmente 'cosa'",
  "Casual — literally 'now we have the salad'": "Informale — letteralmente 'adesso abbiamo l'insalata'",
  "Casual — literally 'that's not my beer'": "Informale — letteralmente 'non è birra mia'",
  "Casual — literally 'you had pig'": "Informale — letteralmente 'hai avuto maiale'",
  "Casual agreement": "Assenso informale",
  "Casual and dramatic; often frustration rather than literal loss of control.": "Informale e drammatico; spesso frustrazione più che una vera perdita di controllo.",
  "Casual check-in mid-explanation.": "Verifica informale nel mezzo di una spiegazione.",
  "casual clipping of 'Prominenter' — everyday word": "abbreviazione informale di 'Prominenter' — parola di tutti i giorni",
  "Casual complaint, one hour in. Someone packed too much Brotzeit.": "Lamentela informale dopo un'ora. Qualcuno ha messo nello zaino troppa Brotzeit.",
  "casual compliment; stehen + dative = to suit someone": "complimento informale; stehen + dativo = star bene a qualcuno",
  "Casual date invite (better than formal 'Möchten Sie...')": "Invito a un appuntamento in tono informale (meglio del formale 'Möchten Sie...')",
  "Casual dating vocabulary with friends. The verb is fully germanized: ghosten, geghostet.": "Lessico informale degli appuntamenti tra amici. Il verbo è del tutto germanizzato: ghosten, geghostet.",
  "casual Denglisch — 'Ich hab gecodet' is completely normal among devs": "denglisch informale — 'Ich hab gecodet' è del tutto normale tra sviluppatori",
  "Casual directive": "Indicazione informale",
  "Casual everyday goodbye — used everywhere in Germany": "Saluto informale di tutti i giorni — usato in tutta la Germania",
  "Casual everyday reassurance": "Rassicurazione informale di tutti i giorni",
  "Casual favour between friends (du). 'drüberschauen' = give it a quick once-over.": "Piccolo favore informale tra amici (du). 'drüberschauen' = dare una scorsa veloce.",
  "Casual for playing video games; in money contexts it means to gamble.": "Informale per giocare ai videogiochi; se c'è di mezzo il denaro, significa scommettere.",
  "Casual goodbye — borrowed from Italian, extremely popular in Germany": "Saluto informale — preso in prestito dall'italiano, popolarissimo in Germania",
  "casual gym slang for lifting weights; 'pumpen gehen'": "gergo informale da palestra per sollevare pesi; 'pumpen gehen'",
  "Casual imperative 'Investier' is common spoken German; full written form is 'Investiere'.": "L'imperativo informale 'Investier' è comune nel parlato; la forma scritta completa è 'Investiere'.",
  "Casual imperative 'Setz' is short for 'Setze'; 'am' contracts dative 'an dem'.": "L'imperativo informale 'Setz' abbrevia 'Setze'; 'am' contrae il dativo 'an dem'.",
  "Casual invite": "Invito informale",
  "Casual kitchen-table economics; sich lohnen = to be worth it — very high-frequency verb": "Economia informale da tavolo di cucina; sich lohnen = valerne la pena — verbo molto frequente",
  "casual loanword; einkaufen is the German verb": "prestito informale; einkaufen è il verbo tedesco",
  "Casual opener": "Apertura di conversazione informale",
  "Casual opener for close friends": "Apertura informale tra amici stretti",
  "Casual opinion": "Opinione informale",
  "Casual positive update": "Aggiornamento positivo in tono informale",
  "Casual register inside student life; durcharbeiten = work through without a break.": "Registro informale della vita da studente; durcharbeiten = lavorare senza pause.",
  "Casual reminiscing; 'was los sein' = something happening.": "Ricordi in tono informale; 'was los sein' = succede qualcosa.",
  "Casual reply": "Risposta informale",
  "Casual request": "Richiesta informale",
  "Casual request to repeat": "Richiesta informale di ripetere",
  "Casual self-intro": "Presentazione di sé informale",
  "Casual slang command": "Ordine in gergo informale",
  "Casual slang farewell": "Saluto di commiato in gergo informale",
  "Casual spoken imperative 'Markier' is common; the tool follows dative 'mit einem Bleistift'.": "L'imperativo parlato informale 'Markier' è comune; lo strumento segue al dativo: 'mit einem Bleistift'.",
  "casual spoken; from sich fertig machen = sich zurechtmachen": "parlato informale; da sich fertig machen = prepararsi, sistemarsi",
  "casual spoken; the machen-lassen pattern for anything done at a salon": "parlato informale; lo schema machen-lassen per tutto ciò che si fa dal parrucchiere",
  "casual, admiring; 'definiert' = lean and cut, more technical": "informale e ammirato; 'definiert' = asciutto e scolpito, più tecnico",
  "Casual, enthusiastic. 'Der Wahnsinn' is the go-to superlative among friends.": "Informale ed entusiasta. 'Der Wahnsinn' è il superlativo d'elezione tra amici.",
  "casual, everyday; der Lidstrich is the German word, Eyeliner is what people say": "informale, quotidiano; der Lidstrich è la parola tedesca, ma si dice Eyeliner",
  "Casual, relieved-triumphant, to friends. 'überstehen' = to survive something unpleasant.": "Informale, sollevato e trionfante, tra amici. 'überstehen' = superare qualcosa di sgradevole.",
  "Casual, teasing — literally 'do you have tomatoes on your eyes?'": "Informale e canzonatorio — letteralmente 'hai i pomodori sugli occhi?'",
  "Casual, to companions. Famous last words on any hike.": "Informale, ai compagni. Le famose ultime parole di ogni escursione.",
  "Casual, to one person (du) — group: Lasst uns anfangen; formal: Fangen wir an": "Informale, a una sola persona (du) — al gruppo: Lasst uns anfangen; formale: Fangen wir an",
  "Casual, universal. The standard excuse to step outside — nobody questions frische Luft.": "Informale, universale. La scusa standard per uscire — nessuno mette in dubbio la frische Luft.",
  "Casual, wry — literally 'life is no pony farm'": "Informale e ironico — letteralmente 'la vita non è un maneggio di pony'",
  "casual, younger speakers; Hautpflege is the more formal word": "informale, parlanti più giovani; Hautpflege è la parola più formale",
  "Casual; 'die Pause' is the break, 'der Pausenhof' the yard it happens on.": "Informale; 'die Pause' è la ricreazione, 'der Pausenhof' il cortile dove si svolge.",
  "casual; 'platt' = wiped out, works for any exhaustion": "informale; 'platt' = a pezzi, va bene per qualsiasi stanchezza",
  "casual; 'Proteinshake' works too": "informale; va bene anche 'Proteinshake'",
  "casual; 'pumpen gehen' marks you as a weights person, not a treadmill person": "informale; 'pumpen gehen' ti classifica come tipo da pesi, non da tapis roulant",
  "casual; 'sich etwas ziehen' = to pull a muscle": "informale; 'sich etwas ziehen' = farsi uno stiramento",
  "Casual; ackern makes the work sound tiring or relentless.": "Informale; ackern fa suonare il lavoro come faticoso e senza tregua.",
  "Casual; adults admit it with a grin": "Informale; gli adulti lo ammettono con un sorriso",
  "casual; literally also to plough a field": "informale; letteralmente anche arare un campo",
  "casual; stechen lassen (literally 'have it pricked') is the idiomatic verb for tattoos": "informale; stechen lassen (letteralmente 'farsi pungere') è il verbo idiomatico per i tatuaggi",
  "casual; the question everyone asks": "informale; la domanda che fanno tutti",
  "casual; the standard (optimistic) answer": "informale; la risposta tipica (ottimista)",
  "Casual; the way adults confess it with a grin.": "Informale; il modo in cui gli adulti lo confessano con un sorriso.",
  "casual: kicken gehen = to go and play football": "informale: kicken gehen = andare a giocare a calcio",
  "Casual. 'Baden gehen' = swim outdoors (lake, sea); 'schwimmen gehen' leans towards the pool.": "Informale. 'Baden gehen' = fare il bagno all'aperto (lago, mare); 'schwimmen gehen' tende alla piscina.",
  "Casual. 'Eine Runde drehen' = do a loop; works for walks, bike rides or a quick drive.": "Informale. 'Eine Runde drehen' = fare un giro; vale per passeggiate, giri in bici o una breve uscita in auto.",
  "Casual. 'Sich etwas holen' = to catch/get something (sunburn, a cold).": "Informale. 'Sich etwas holen' = beccarsi qualcosa (scottatura, raffreddore).",
  "casually clipped to 'der Elfer'": "abbreviato colloquialmente in 'der Elfer'",
  "Chores": "Faccende domestiche",
  "close friends only — sharing a cigarette or vape": "solo tra amici stretti — condividere una sigaretta o una vape",
  "Coarse and common among friends. It can sound confrontational when said angrily.": "Volgare e comune tra amici. Detto con rabbia può suonare provocatorio.",
  "Coarse-casual — 'forget it, who cares'. Banter-safe among friends; not for formal company.": "Volgare e informale — 'lascia perdere, chi se ne importa'. Va per scherzo tra amici; non in contesti formali.",
  "coden is casual Denglisch; completely normal in the du-form dev crowd.": "coden è denglisch informale; del tutto normale nell'ambiente dev che si dà del tu.",
  "Colloquial (Kopfnuss = headbutt/noogie)": "Colloquiale (Kopfnuss = testata o scappellotto)",
  "Colloquial and strong; covers verbal and psychological cruelty, not just physical.": "Colloquiale e forte; comprende la crudeltà verbale e psicologica, non solo quella fisica.",
  "Colloquial and strong; verbal or psychological cruelty": "Colloquiale e forte; crudeltà verbale o psicologica",
  "colloquial anglicism (Duden-listed); marketing and social media register": "anglicismo colloquiale (registrato nel Duden); registro del marketing e dei social",
  "Colloquial but harmless — safe with colleagues and family.": "Colloquiale ma innocuo — tranquillo con colleghi e familiari.",
  "Colloquial but serious; 'zu dritt' = three of them together.": "Colloquiale ma serio; 'zu dritt' = in tre.",
  "Colloquial combo of Ja + Nein": "Fusione colloquiale di Ja + Nein",
  "colloquial intensifier: mächtig stolz = mighty proud": "intensificatore colloquiale: mächtig stolz = fiero da matti",
  "Colloquial short form of herauskommen; also used of films, products or models being released.": "Forma breve colloquiale di herauskommen; si usa anche per film, prodotti o modelli che escono.",
  "Colloquial shortcut": "Scorciatoia colloquiale",
  "Colloquial, mild — gasped mid-laughter or typed in chats. Friends, family, relaxed colleagues.": "Colloquiale, leggero — buttato lì ridendo o digitato in chat. Amici, famiglia, colleghi rilassati.",
  "colloquial, what children do in sand; graben is neutral": "colloquiale, quello che fanno i bambini nella sabbia; graben è neutro",
  "Colloquial; 'sich prügeln' is physical, much stronger than 'sich streiten'.": "Colloquiale; 'sich prügeln' è fisico, molto più forte di 'sich streiten'.",
  "colloquial; invariable: ein super Film": "colloquiale; invariabile: ein super Film",
  "colloquially also snappy, punchy (UI, prose, deadlines)": "colloquialmente anche scattante, incisivo (interfacce, testi, scadenze)",
  "colloquially shortened to 'das Gespräch'": "abbreviato colloquialmente in 'das Gespräch'",
  "common and informal; can describe a person, idea or situation": "comune e informale; può descrivere una persona, un'idea o una situazione",
  "Common complaint": "Lamentela comune",
  "Common slang reaction": "Reazione comune in gergo",
  "Common slang reaction to bad news — mies = lousy, shabby": "Reazione comune in gergo a una brutta notizia — mies = pessimo, scadente",
  "Confirming": "Confermare",
  "Consent": "Consenso",
  "Consent — always check": "Consenso — chiedi sempre",
  "Conversational geopolitics with an opinion baked in — fine among friends, spicier at work": "Geopolitica da conversazione con un'opinione incorporata — bene tra amici, più delicata al lavoro",
  "dark humour among friends; 'Echsenmenschen' is the go-to absurd-conspiracy reference": "umorismo nero tra amici; 'Echsenmenschen' è il riferimento tipico alle cospirazioni assurde",
  "das Band — the conveyor. Braking on it is the one real mistake to avoid.": "das Band — il nastro trasportatore. Frenare sopra è l'unico vero errore da evitare.",
  "das Bügeleisen — the iron. The warning every household repeats.": "das Bügeleisen — il ferro da stiro. L'avvertimento che si ripete in ogni casa.",
  "das Halbjahreszeugnis — the February report. The early warning system.": "das Halbjahreszeugnis — la pagella di febbraio. Il sistema di allerta precoce.",
  "Das hängt davon ab = it depends. Casually, mit Freunden abhängen = to hang out.": "Das hängt davon ab = dipende. In tono informale, mit Freunden abhängen = stare in giro con gli amici.",
  "das Profil — the tread. 'ist runter' — worn away; casual passive Germany runs on.": "das Profil — il battistrada. 'ist runter' — consumato; il passivo informale su cui viaggia la Germania.",
  "das Rücklicht — the rear light. 'nur noch schwach' — the warning phase before darkness.": "das Rücklicht — la luce posteriore. 'nur noch schwach' — la fase di avviso prima del buio.",
  "das Teil — the casual word for any piece of clothing. The rule that prevents the pink wash.": "das Teil — la parola informale per qualsiasi capo. La regola che evita il bucato rosa.",
  "das Wartezimmer — from the doctor pack, considerably louder. Cats sit high; dogs make friends.": "das Wartezimmer — dal pacchetto sul medico, decisamente più rumorosa. I gatti stanno in alto; i cani fanno amicizia.",
  "Dating": "Appuntamenti",
  "Deliberately vague — it lets both sides keep it casual. 'was' here is short for 'etwas'.": "Volutamente vago — permette a entrambi di restare sul leggero. Qui 'was' sta per 'etwas'.",
  "der Aszendent — the follow-up question that separates casual from committed.": "der Aszendent — la domanda di rincalzo che separa i curiosi dai convinti.",
  "der Helferkreis — the informal volunteer group, common in refugee and neighbourhood support.": "der Helferkreis — il gruppo di volontari informale, comune nel sostegno ai rifugiati e di quartiere.",
  "der Platten — the flat tyre, colloquial and universal. The commute's classic opening line.": "der Platten — la gomma a terra, colloquiale e universale. La classica battuta d'apertura sul tragitto.",
  "der Strafzettel, colloquially das Knöllchen = parking ticket": "der Strafzettel, colloquialmente das Knöllchen = multa per divieto di sosta",
  "Desire": "Desiderio",
  "die Abmahnung — the warning shot, at work or over copyright. Serious, not final.": "die Abmahnung — il colpo d'avvertimento, al lavoro o sul diritto d'autore. Serio, ma non definitivo.",
  "die Abmahnung — the written warning. Serious, but far from a dismissal.": "die Abmahnung — il richiamo scritto. Serio, ma ben lontano da un licenziamento.",
  "die Hausnummer — colloquial for a rough figure. More with a role change.": "die Hausnummer — colloquiale per una cifra di massima. Di più se cambia il ruolo.",
  "die Jugendfeuerwehr — where most volunteers begin. Knots, hoses and friendships.": "die Jugendfeuerwehr — dove comincia la maggior parte dei volontari. Nodi, manichette e amicizie.",
  "die Kantine — the subsidised lunch. The invitation that builds actual friendships.": "die Kantine — il pranzo sovvenzionato. L'invito da cui nascono amicizie vere.",
  "die Lawine — the avalanche. The warning is not decorative.": "die Lawine — la valanga. L'avvertimento non è decorativo.",
  "Direct and neutral: 'Ich bin schwanger.' Colloquially, 'schwanger von ihm' names the father.": "Diretto e neutro: 'Ich bin schwanger.' Colloquialmente, 'schwanger von ihm' nomina il padre.",
  "düngen = to fertilize; der Dünger = fertilizer. Du register — said between family/friends": "düngen = concimare; der Dünger = il concime. Registro del du — si dice tra familiari e amici",
  "eh = anyway / in any case (colloquial 'ohnehin')": "eh = comunque / in ogni caso (colloquiale per 'ohnehin')",
  "eine Runde schmeißen — literally throwing a round. Casual, generous, slightly theatrical.": "eine Runde schmeißen — alla lettera lanciare un giro. Informale, generoso, un po' teatrale.",
  "Emergency": "Emergenza",
  "Emphasis": "Enfasi",
  "Emphatic casual yes": "Sì informale ed enfatico",
  "Encouragement between friends or from a partner — the compliment learners most want to hear.": "Incoraggiamento tra amici o dal partner — il complimento che chi studia desidera di più sentirsi dire.",
  "Enemy info": "Info sul nemico",
  "English loan, fully naturalized and plural; 'doch' makes it dismissive — casual register": "prestito dall'inglese, pienamente naturalizzato e al plurale; 'doch' lo rende sprezzante — registro informale",
  "Enthusiastic yes": "Sì entusiasta",
  "Essential": "Essenziale",
  "everyday casual word; also means the stubbed-out butt": "parola informale di tutti i giorni; indica anche il mozzicone spento",
  "Everyday colloquial spelling of nichts": "Grafia colloquiale quotidiana di nichts",
  "Everyday connection method (slang 'schreib mir')": "Modo quotidiano per restare in contatto (gergo 'schreib mir')",
  "Everyday criticism, medium weight; fine in casual talk about colleagues or exes.": "Critica quotidiana di peso medio; va bene in una chiacchierata informale su colleghi o ex.",
  "Everyday office and friend request; rüberschicken (send over) is the casual variant.": "Richiesta quotidiana in ufficio e tra amici; rüberschicken (mandare) è la variante informale.",
  "Everyday slang (Bock haben)": "Gergo quotidiano (Bock haben)",
  "Everyday slang (spendieren = to treat)": "Gergo di tutti i giorni (spendieren = offrire)",
  "Facharzt = specialist; colloquially also \"einen Termin ausmachen\"": "Facharzt = medico specialista; colloquialmente anche 'einen Termin ausmachen'",
  "Falschparken = illegal/incorrect parking": "Falschparken = parcheggio irregolare o vietato",
  "Family": "Famiglia",
  "Famous last words — friends will quote it back at you for months.": "Famose ultime parole — gli amici te le ricorderanno per mesi.",
  "Farewell": "Congedo",
  "Feeling": "Sentimento",
  "feiern = to celebrate, colloquially 'to love something'; very current usage.": "feiern = festeggiare, colloquialmente 'adorare qualcosa'; uso molto attuale.",
  "fett = huge (colloquial intensifier); standard dev talk, not rude.": "fett = enorme (intensificatore colloquiale); gergo dev normale, non volgare.",
  "Finding help": "Trovare aiuto",
  "Fixed casual set expression; already short, so no further clipping.": "Espressione fissa informale; già breve, quindi niente ulteriori accorciamenti.",
  "flach and steil around dahinter — the swimming-pool warning as a geometry lesson.": "flach e steil intorno a dahinter — l'avvertimento della piscina come lezione di geometria.",
  "Flight status update": "Stato del volo",
  "Flirting": "Flirtare",
  "Formal": "Formale",
  "Frustrated, to friends. 'schon wieder' carries the job-hunt fatigue.": "Con frustrazione, tra amici. 'schon wieder' porta la stanchezza della ricerca di lavoro.",
  "geblitzt werden = to get caught by a speed camera — the standard colloquial verb for it": "geblitzt werden = essere beccati dall'autovelox — il verbo colloquiale standard per dirlo",
  "Gen-Z": "Gen Z",
  "Genuine compliment between friends; on a date it's practically flirting.": "Complimento sincero tra amici; a un appuntamento è praticamente un flirt.",
  "gereizt — irritable, like a nerve already touched. Fair warning to the room.": "gereizt — irritabile, come un nervo già toccato. Un avvertimento leale a tutta la stanza.",
  "gib — du-imperative of geben with vowel change; mal keeps it casual, not bossy.": "gib — imperativo del du di geben con alternanza vocalica; mal lo mantiene informale, non autoritario.",
  "Greeting": "Saluto",
  "Grufti = colloquial for goth (from Gruft = tomb/crypt)": "Grufti = colloquiale per goth (da Gruft = cripta, tomba)",
  "Gunsmith": "Armaiolo",
  "Half-joking household rule for the unsortable. Colloquial, said with a shrug.": "Regola domestica mezzo scherzosa per tutto ciò che non si può smistare. Colloquiale, detta con una scrollata di spalle.",
  "half-joking quitter's line; 'ich schwör' is casual spoken German": "battuta mezzo scherzosa di chi molla; 'ich schwör' è tedesco parlato informale",
  "idiomatic, informal": "idiomatico, informale",
  "Im Alter von 30 = at the age of 30. As an exclamation, Alter! = dude! — very casual.": "Im Alter von 30 = all'età di 30 anni. Come esclamazione, Alter! = bello! — molto informale.",
  "in casual speech often shortened to was: Hast du was gehört?": "nel parlato informale spesso ridotto a was: Hast du was gehört?",
  "In the moment": "Sul momento",
  "Informal": "Informale",
  "Informal — friends only": "Informale — solo tra amici",
  "Informal — the spoken contraction you'll usually hear": "Informale — la contrazione parlata che si sente di solito",
  "Informal — to strangers or staff say: Sprechen Sie Englisch?": "Informale — a estranei o al personale si dice: Sprechen Sie Englisch?",
  "Informal and rude: jemandem den Stinkefinger zeigen.": "Informale e volgare: jemandem den Stinkefinger zeigen.",
  "Informal and warm, mostly southern. 'Grüß Gott' is its formal, Bavarian and Austrian cousin.": "Informale e caloroso, soprattutto al sud. 'Grüß Gott' è il suo cugino formale, bavarese e austriaco.",
  "Informal imperative of separable 'aufheben': 'Heb ... auf'; the full written form is 'Hebe'.": "Imperativo informale del separabile 'aufheben': 'Heb ... auf'; la forma scritta completa è 'Hebe'.",
  "informal loan from English; das Okay – the go-ahead": "prestito informale dall'inglese; das Okay – il via libera",
  "Informal reply — with Sie say: Und Ihnen?": "Risposta informale — con Sie si dice: Und Ihnen?",
  "Informal term for a friend": "Termine informale per un amico",
  "informal, e.g. eine brenzlige Situation": "informale, per es. eine brenzlige Situation",
  "informal; the standard German way to say someone drifted off into conspiracy land": "informale; il modo tedesco standard per dire che qualcuno è scivolato nel complottismo",
  "Introducing": "Presentarsi",
  "justifying one more — works for cigarettes and beers alike; very casual": "per giustificarne un'altra — vale sia per le sigarette sia per le birre; molto informale",
  "kicken — casual football. der Bolzplatz — the scuffed pitch every neighbourhood has.": "kicken — calcio informale. der Bolzplatz — il campetto consumato che ogni quartiere possiede.",
  "klamm — damp, and colloquially short of cash. Honest without being dramatic.": "klamm — umido, e colloquialmente a corto di soldi. Onesto senza fare dramma.",
  "klingen — sounding. The honest warning given to every violin household's neighbours.": "klingen — suonare. L'avvertimento onesto ai vicini di ogni casa con un violino.",
  "knapp bei Kasse — tight at the till. The honest sentence that friends answer with einladen.": "knapp bei Kasse — a corto in cassa. La frase onesta a cui gli amici rispondono con einladen.",
  "Knast = colloquial for jail/prison": "Knast = colloquiale per carcere, galera",
  "Komm doch mal vorbei! — the casual open invitation.": "Komm doch mal vorbei! — l'invito aperto e informale.",
  "Leaving": "Andarsene",
  "Loadout": "Equipaggiamento",
  "Logisch! is also a casual \"obviously\"": "Logisch! è anche un 'ovvio' informale",
  "Making a move": "Fare il primo passo",
  "Making plans": "Fare programmi",
  "medium insult — banter-safe among close friends with the right tone": "insulto medio — accettabile per scherzo tra amici stretti, col tono giusto",
  "medium-strong — banter only with thick-skinned close friends": "medio-forte — solo per scherzo tra amici stretti dalla pelle dura",
  "Meta": "Meta",
  "Opinion": "Opinione",
  "Ordering food": "Ordinare da mangiare",
  "Plans": "Programmi",
  "Position callout": "Segnalazione di posizione",
  "Reacting": "Reagire",
  "Reassuring": "Rassicurare",
  "Relationship status": "Stato sentimentale",
  "Reporting a problem": "Segnalare un problema",
  "Request": "Richiesta",
  "Routine": "Routine",
  "Scheduling": "Organizzare",
  "Seasons": "Stagioni",
  "Slang": "Gergo",
  "Status callout": "Segnalazione di stato",
  "Strong agreement": "Accordo deciso",
  "Surprise": "Sorpresa",
  "Symptom": "Sintomo",
  "Team play": "Gioco di squadra",
  "Telling time": "Dire l'ora",
  "Texting": "Messaggi",
  "Time comment": "Commento sull'ora",
  "Typical reply": "Risposta tipica",
  "Unlocks": "Sblocchi",
  "Urgent": "Urgente",
  "Very common leisure activity": "Attività del tempo libero molto comune",
  "Weather": "Tempo",
  "Written German too": "Anche nel tedesco scritto",
};
