/**
 * The usage notes in French.
 *
 * Keyed by the English note exactly as the card carries it. A note missing
 * from here shows its English, so this file is filled in batches without any
 * card ever going blank — see usageNotes.ts for how it is loaded and why it
 * is not part of the interface tables.
 *
 * Fourteen thousand notes exist. This holds the ones translated so far, and
 * check-usage-notes prints how far along each language is on every build.
 */
export const USE_FR: Record<string, string> = {
  "Afterwards": "Ensuite",
  "Agreeing": "Approuver",
  "always plural": "toujours au pluriel",
  "Asking for the bill": "Demander l'addition",
  "At the till": "À la caisse",
  "Banter": "Vannes",
  "Buying time": "Gagner du temps",
  "Casual reply": "Réponse décontractée",
  "Chores": "Tâches ménagères",
  "Common complaint": "Plainte courante",
  "Confirming": "Confirmer",
  "Consent": "Consentement",
  "Consent — always check": "Consentement — toujours demander",
  "Dating": "Rencontres",
  "Desire": "Envie",
  "Emergency": "Urgence",
  "Emphasis": "Insistance",
  "Enemy info": "Info ennemi",
  "Enthusiastic yes": "Oui enthousiaste",
  "Essential": "Essentiel",
  "Everyday slang (Bock haben)": "Argot du quotidien (Bock haben)",
  "Family": "Famille",
  "Farewell": "Au revoir",
  "Feeling": "Sentiment",
  "Finding help": "Trouver de l'aide",
  "Flight status update": "Statut du vol",
  "Flirting": "Draguer",
  "Formal": "Formel",
  "Gen-Z": "Gen Z",
  "Greeting": "Salutation",
  "Gunsmith": "Armurier",
  "In the moment": "Sur le moment",
  "Introducing": "Se présenter",
  "Leaving": "Partir",
  "Loadout": "Équipement",
  "Making a move": "Faire le premier pas",
  "Making plans": "Faire des projets",
  "Meta": "Méta",
  "Opinion": "Opinion",
  "Ordering food": "Commander à manger",
  "Plans": "Projets",
  "Position callout": "Annonce de position",
  "Reacting": "Réagir",
  "Reassuring": "Rassurer",
  "Relationship status": "Statut relationnel",
  "Reporting a problem": "Signaler un problème",
  "Request": "Demande",
  "Routine": "Routine",
  "Scheduling": "Planification",
  "Seasons": "Saisons",
  "Slang": "Argot",
  "Status callout": "Annonce d'état",
  "Strong agreement": "Accord appuyé",
  "Surprise": "Surprise",
  "Symptom": "Symptôme",
  "Team play": "Jeu d'équipe",
  "Telling time": "Dire l'heure",
  "Texting": "Textos",
  "Time comment": "Remarque sur l'heure",
  "Typical reply": "Réponse typique",
  "Unlocks": "Déblocages",
  "Urgent": "Urgent",
  "Very common leisure activity": "Loisir très courant",
  "Weather": "Météo",
  "Written German too": "Aussi à l'écrit",
};
