/**
 * The usage notes in Portuguese.
 *
 * Keyed by the English note exactly as the card carries it. A note missing
 * from here shows its English, so this file is filled in batches without any
 * card ever going blank — see usageNotes.ts for how it is loaded and why it
 * is not part of the interface tables.
 *
 * Fourteen thousand notes exist. This holds the ones translated so far, and
 * check-usage-notes prints how far along each language is on every build.
 */
export const USE_PT: Record<string, string> = {
  "Afterwards": "Depois",
  "Agreeing": "Concordar",
  "always plural": "sempre no plural",
  "Asking for the bill": "Pedir a conta",
  "At the till": "Na caixa",
  "Banter": "Brincadeira",
  "Buying time": "Ganhar tempo",
  "Casual reply": "Resposta descontraída",
  "Chores": "Tarefas domésticas",
  "Common complaint": "Queixa comum",
  "Confirming": "Confirmar",
  "Consent": "Consentimento",
  "Consent — always check": "Consentimento — pergunta sempre",
  "Dating": "Encontros",
  "Desire": "Desejo",
  "Emergency": "Emergência",
  "Emphasis": "Ênfase",
  "Enemy info": "Info do inimigo",
  "Enthusiastic yes": "Sim entusiasmado",
  "Essential": "Essencial",
  "Everyday slang (Bock haben)": "Calão do dia a dia (Bock haben)",
  "Family": "Família",
  "Farewell": "Despedida",
  "Feeling": "Sentimento",
  "Finding help": "Encontrar ajuda",
  "Flight status update": "Estado do voo",
  "Flirting": "Namoriscar",
  "Formal": "Formal",
  "Gen-Z": "Gen Z",
  "Greeting": "Cumprimento",
  "Gunsmith": "Armeiro",
  "In the moment": "No momento",
  "Introducing": "Apresentar-se",
  "Leaving": "Ir embora",
  "Loadout": "Equipamento",
  "Making a move": "Dar o primeiro passo",
  "Making plans": "Fazer planos",
  "Meta": "Meta",
  "Opinion": "Opinião",
  "Ordering food": "Pedir comida",
  "Plans": "Planos",
  "Position callout": "Aviso de posição",
  "Reacting": "Reagir",
  "Reassuring": "Tranquilizar",
  "Relationship status": "Estado da relação",
  "Reporting a problem": "Comunicar um problema",
  "Request": "Pedido",
  "Routine": "Rotina",
  "Scheduling": "Marcar",
  "Seasons": "Estações",
  "Slang": "Calão",
  "Status callout": "Aviso de estado",
  "Strong agreement": "Concordância forte",
  "Surprise": "Surpresa",
  "Symptom": "Sintoma",
  "Team play": "Jogo em equipa",
  "Telling time": "Dizer as horas",
  "Texting": "Mensagens",
  "Time comment": "Comentário sobre a hora",
  "Typical reply": "Resposta típica",
  "Unlocks": "Desbloqueios",
  "Urgent": "Urgente",
  "Very common leisure activity": "Atividade de lazer muito comum",
  "Weather": "Tempo",
  "Written German too": "Também no alemão escrito",
};
