/**
 * The usage notes in Polish.
 *
 * Keyed by the English note exactly as the card carries it. A note missing
 * from here shows its English, so this file is filled in batches without any
 * card ever going blank — see usageNotes.ts for how it is loaded and why it
 * is not part of the interface tables.
 *
 * Fourteen thousand notes exist. This holds the ones translated so far, and
 * check-usage-notes prints how far along each language is on every build.
 */
export const USE_PL: Record<string, string> = {
  "Afterwards": "Potem",
  "Agreeing": "Zgadzanie się",
  "always plural": "zawsze w liczbie mnogiej",
  "Asking for the bill": "Prośba o rachunek",
  "At the till": "Przy kasie",
  "Banter": "Przekomarzanie",
  "Buying time": "Granie na zwłokę",
  "Casual reply": "Swobodna odpowiedź",
  "Chores": "Obowiązki domowe",
  "Common complaint": "Częsta skarga",
  "Confirming": "Potwierdzanie",
  "Consent": "Zgoda",
  "Consent — always check": "Zgoda — zawsze pytaj",
  "Dating": "Randki",
  "Desire": "Pragnienie",
  "Emergency": "Nagły wypadek",
  "Emphasis": "Podkreślenie",
  "Enemy info": "Informacja o wrogu",
  "Enthusiastic yes": "Entuzjastyczne tak",
  "Essential": "Niezbędne",
  "Everyday slang (Bock haben)": "Codzienny slang (Bock haben)",
  "Family": "Rodzina",
  "Farewell": "Pożegnanie",
  "Feeling": "Uczucie",
  "Finding help": "Szukanie pomocy",
  "Flight status update": "Status lotu",
  "Flirting": "Flirtowanie",
  "Formal": "Formalne",
  "Gen-Z": "Gen Z",
  "Greeting": "Powitanie",
  "Gunsmith": "Rusznikarz",
  "In the moment": "W tej chwili",
  "Introducing": "Przedstawianie się",
  "Leaving": "Wychodzenie",
  "Loadout": "Wyposażenie",
  "Making a move": "Pierwszy krok",
  "Making plans": "Planowanie",
  "Meta": "Meta",
  "Opinion": "Opinia",
  "Ordering food": "Zamawianie jedzenia",
  "Plans": "Plany",
  "Position callout": "Podanie pozycji",
  "Reacting": "Reagowanie",
  "Reassuring": "Uspokajanie",
  "Relationship status": "Status związku",
  "Reporting a problem": "Zgłaszanie problemu",
  "Request": "Prośba",
  "Routine": "Rutyna",
  "Scheduling": "Umawianie terminów",
  "Seasons": "Pory roku",
  "Slang": "Slang",
  "Status callout": "Podanie statusu",
  "Strong agreement": "Mocna zgoda",
  "Surprise": "Zaskoczenie",
  "Symptom": "Objaw",
  "Team play": "Gra zespołowa",
  "Telling time": "Podawanie godziny",
  "Texting": "Pisanie wiadomości",
  "Time comment": "Uwaga o czasie",
  "Typical reply": "Typowa odpowiedź",
  "Unlocks": "Odblokowania",
  "Urgent": "Pilne",
  "Very common leisure activity": "Bardzo popularne zajęcie w czasie wolnym",
  "Weather": "Pogoda",
  "Written German too": "Także w piśmie",
};
