/**
 * The usage notes in French.
 *
 * Keyed by the English note exactly as the card carries it. A note missing
 * from here shows its English, so this file is filled in batches without any
 * card ever going blank — see usageNotes.ts for how it is loaded and why it
 * is not part of the interface tables.
 *
 * Fourteen thousand notes exist. This holds the ones translated so far, and
 * check-usage-notes prints how far along each language is on every build.
 */
export const USE_FR: Record<string, string> = {
  "'doppelt' — double. 'Menge' is a quantity, and colloquially 'a lot'.": "'doppelt' — double. 'Menge' est une quantité, et familièrement 'beaucoup'.",
  "'draufschauen' — to look at it. Colloquial and separable.": "'draufschauen' — y jeter un œil. Familier et à particule séparable.",
  "'durch sein' — colloquially done for: soaked, worn out, finished.": "'durch sein' — familièrement fichu : trempé, usé, fini.",
  "'eigentlich' — the casual opener for a serious adult conversation.": "'eigentlich' — l'entrée en matière décontractée d'une conversation sérieuse entre adultes.",
  "'Elfer' is the casual clip everyone uses in speech": "'Elfer' est l'abréviation décontractée que tout le monde emploie à l'oral",
  "'ewig' — eternally, used casually for 'ages'. 'laden' for loading.": "'ewig' — éternellement, employé de façon décontractée pour 'une éternité'. 'laden' pour le chargement.",
  "'gar nicht erst' — not even starting. Avoiding the problem entirely.": "'gar nicht erst' — ne même pas commencer. Éviter complètement le problème.",
  "'gläubig' — devout. Said plainly, this ends no friendships in Germany.": "'gläubig' — croyant, pratiquant. Dit simplement, cela ne brise aucune amitié en Allemagne.",
  "'schlapp' (colloquial) = run-down, drained; 'kaum' = barely.": "'schlapp' (familier) = à plat, vidé ; 'kaum' = à peine.",
  "A colloquial fixed expression. It is not sexual in this use.": "Une expression figée familière. Elle n'a rien de sexuel dans cet emploi.",
  "A common use of sammeln among friends, at work or in a family.": "Un emploi courant de sammeln entre amis, au travail ou en famille.",
  "A direct warning that a condition or necessary step cannot be skipped.": "Un avertissement direct : une condition ou une étape nécessaire ne peut pas être sautée.",
  "A serious accusation, not casual criticism.": "Une accusation grave, pas une critique en passant.",
  "A standing offer between partners or close friends; warm, no drama.": "Une proposition toujours valable entre partenaires ou amis proches ; chaleureuse, sans drame.",
  "A very common informal way to check whether a day suits someone.": "Une manière informelle très courante de demander si un jour convient à quelqu'un.",
  "Afterwards": "Ensuite",
  "Agreeing": "Approuver",
  "also colloquially \"incredibly\": unwahrscheinlich gut": "familièrement aussi 'incroyablement' : unwahrscheinlich gut",
  "also colloquially \"massively\": tierisch gut": "familièrement aussi 'vachement' : tierisch gut",
  "always plural": "toujours au pluriel",
  "Asking for the bill": "Demander l'addition",
  "At the till": "À la caisse",
  "auslaufen — leaking out. 'hinüber sein' — colloquially beyond saving.": "auslaufen — fuir, s'écouler. 'hinüber sein' — familièrement, fichu.",
  "Banter": "Vannes",
  "beraten — advising. 'einen' — the colloquial accusative of man.": "beraten — conseiller. 'einen' — l'accusatif familier de man.",
  "Blunt insult, literally a full fencepost. Friends-only register.": "Insulte brutale, littéralement un piquet de clôture entier. À réserver aux amis.",
  "bumming a cigarette; casual, smoker-to-smoker only": "taxer une cigarette ; décontracté, entre fumeurs seulement",
  "Buying time": "Gagner du temps",
  "Casual": "Décontracté",
  "Casual — Ding literally means 'thing'": "Décontracté — Ding signifie littéralement 'chose'",
  "Casual — literally 'now we have the salad'": "Décontracté — littéralement 'maintenant on a la salade'",
  "Casual — literally 'that's not my beer'": "Décontracté — littéralement 'ce n'est pas ma bière'",
  "Casual — literally 'you had pig'": "Décontracté — littéralement 'tu as eu du cochon'",
  "Casual agreement": "Accord décontracté",
  "Casual check-in mid-explanation.": "Petite vérification décontractée en pleine explication.",
  "casual clipping of 'Prominenter' — everyday word": "abréviation décontractée de 'Prominenter' — mot de tous les jours",
  "Casual complaint, one hour in. Someone packed too much Brotzeit.": "Plainte décontractée au bout d'une heure. Quelqu'un a emporté trop de Brotzeit.",
  "casual compliment; stehen + dative = to suit someone": "compliment décontracté ; stehen + datif = aller bien à quelqu'un",
  "Casual date invite (better than formal 'Möchten Sie...')": "Invitation à un rendez-vous, ton décontracté (mieux que le formel 'Möchten Sie...')",
  "casual Denglisch — 'Ich hab gecodet' is completely normal among devs": "denglisch décontracté — 'Ich hab gecodet' est tout à fait normal chez les développeurs",
  "Casual directive": "Consigne décontractée",
  "Casual everyday goodbye — used everywhere in Germany": "Au revoir décontracté du quotidien — employé partout en Allemagne",
  "Casual everyday reassurance": "Petite phrase rassurante et décontractée du quotidien",
  "Casual for playing video games; in money contexts it means to gamble.": "Décontracté pour jouer aux jeux vidéo ; avec de l'argent, cela signifie parier.",
  "Casual goodbye — borrowed from Italian, extremely popular in Germany": "Au revoir décontracté — emprunté à l'italien, très répandu en Allemagne",
  "casual gym slang for lifting weights; 'pumpen gehen'": "argot décontracté de salle de sport pour soulever de la fonte ; 'pumpen gehen'",
  "Casual invite": "Invitation décontractée",
  "casual loanword; einkaufen is the German verb": "emprunt décontracté ; einkaufen est le verbe allemand",
  "Casual opener": "Entrée en matière décontractée",
  "Casual opener for close friends": "Entrée en matière décontractée entre amis proches",
  "Casual opinion": "Avis exprimé de façon décontractée",
  "Casual positive update": "Bonne nouvelle donnée sur un ton décontracté",
  "Casual reminiscing; 'was los sein' = something happening.": "Souvenirs évoqués sur un ton décontracté ; 'was los sein' = il se passe quelque chose.",
  "Casual reply": "Réponse décontractée",
  "Casual request": "Demande décontractée",
  "Casual request to repeat": "Demande décontractée de répéter",
  "Casual self-intro": "Présentation de soi décontractée",
  "Casual slang command": "Ordre en argot décontracté",
  "Casual slang farewell": "Au revoir en argot décontracté",
  "casual spoken; from sich fertig machen = sich zurechtmachen": "oral décontracté ; de sich fertig machen = se préparer, s'apprêter",
  "casual spoken; the machen-lassen pattern for anything done at a salon": "oral décontracté ; la tournure machen-lassen pour tout ce qui se fait chez le coiffeur",
  "casual, admiring; 'definiert' = lean and cut, more technical": "décontracté et admiratif ; 'definiert' = sec et dessiné, plus technique",
  "Casual, teasing — literally 'do you have tomatoes on your eyes?'": "Décontracté et taquin — littéralement 'tu as des tomates sur les yeux ?'",
  "Casual, to companions. Famous last words on any hike.": "Décontracté, à ses compagnons. La phrase fatidique de toute randonnée.",
  "Casual, wry — literally 'life is no pony farm'": "Décontracté et pince-sans-rire — littéralement 'la vie n'est pas un poney-club'",
  "casual, younger speakers; Hautpflege is the more formal word": "décontracté, plutôt chez les jeunes ; Hautpflege est le mot plus formel",
  "casual; 'platt' = wiped out, works for any exhaustion": "décontracté ; 'platt' = lessivé, valable pour toute forme d'épuisement",
  "casual; 'Proteinshake' works too": "décontracté ; 'Proteinshake' fonctionne aussi",
  "casual; 'sich etwas ziehen' = to pull a muscle": "décontracté ; 'sich etwas ziehen' = se faire un claquage",
  "Casual; ackern makes the work sound tiring or relentless.": "Décontracté ; ackern fait sonner le travail comme épuisant et sans répit.",
  "Casual; adults admit it with a grin": "Décontracté ; les adultes l'avouent avec un sourire en coin",
  "casual; literally also to plough a field": "décontracté ; littéralement aussi labourer un champ",
  "casual; the question everyone asks": "décontracté ; la question que tout le monde pose",
  "casual; the standard (optimistic) answer": "décontracté ; la réponse habituelle (optimiste)",
  "Casual; the way adults confess it with a grin.": "Décontracté ; la façon dont les adultes l'avouent avec un sourire.",
  "casual: kicken gehen = to go and play football": "décontracté : kicken gehen = aller jouer au foot",
  "Casual. 'Sich etwas holen' = to catch/get something (sunburn, a cold).": "Décontracté. 'Sich etwas holen' = attraper quelque chose (coup de soleil, rhume).",
  "casually clipped to 'der Elfer'": "abrégé familièrement en 'der Elfer'",
  "Chores": "Tâches ménagères",
  "close friends only — sharing a cigarette or vape": "entre amis proches seulement — partager une cigarette ou une vapoteuse",
  "coden is casual Denglisch; completely normal in the du-form dev crowd.": "coden est du denglisch décontracté ; tout à fait normal dans le milieu dev qui se tutoie.",
  "Colloquial (Kopfnuss = headbutt/noogie)": "Familier (Kopfnuss = coup de tête ou pichenette sur le crâne)",
  "Colloquial and strong; verbal or psychological cruelty": "Familier et fort ; cruauté verbale ou psychologique",
  "Colloquial but harmless — safe with colleagues and family.": "Familier mais anodin — sans risque avec les collègues et la famille.",
  "Colloquial but serious; 'zu dritt' = three of them together.": "Familier mais grave ; 'zu dritt' = à trois.",
  "Colloquial combo of Ja + Nein": "Mot-valise familier de Ja + Nein",
  "colloquial intensifier: mächtig stolz = mighty proud": "intensificateur familier : mächtig stolz = drôlement fier",
  "Colloquial shortcut": "Raccourci familier",
  "colloquial, what children do in sand; graben is neutral": "familier, ce que les enfants font dans le sable ; graben est neutre",
  "colloquial; invariable: ein super Film": "familier ; invariable : ein super Film",
  "colloquially also snappy, punchy (UI, prose, deadlines)": "familièrement aussi vif, percutant (interfaces, textes, délais)",
  "colloquially shortened to 'das Gespräch'": "abrégé familièrement en 'das Gespräch'",
  "common and informal; can describe a person, idea or situation": "courant et informel ; peut décrire une personne, une idée ou une situation",
  "Common complaint": "Plainte courante",
  "Common slang reaction": "Réaction courante en argot",
  "Common slang reaction to bad news — mies = lousy, shabby": "Réaction argotique courante à une mauvaise nouvelle — mies = nul, minable",
  "Confirming": "Confirmer",
  "Consent": "Consentement",
  "Consent — always check": "Consentement — toujours demander",
  "das Bügeleisen — the iron. The warning every household repeats.": "das Bügeleisen — le fer à repasser. L'avertissement que répète chaque foyer.",
  "das Halbjahreszeugnis — the February report. The early warning system.": "das Halbjahreszeugnis — le bulletin de février. Le système d'alerte précoce.",
  "Dating": "Rencontres",
  "der Strafzettel, colloquially das Knöllchen = parking ticket": "der Strafzettel, familièrement das Knöllchen = contravention de stationnement",
  "Desire": "Envie",
  "die Lawine — the avalanche. The warning is not decorative.": "die Lawine — l'avalanche. L'avertissement n'est pas décoratif.",
  "eh = anyway / in any case (colloquial 'ohnehin')": "eh = de toute façon / en tout cas (familier pour 'ohnehin')",
  "Emergency": "Urgence",
  "Emphasis": "Insistance",
  "Emphatic casual yes": "Oui décontracté et appuyé",
  "Enemy info": "Info ennemi",
  "Enthusiastic yes": "Oui enthousiaste",
  "Essential": "Essentiel",
  "everyday casual word; also means the stubbed-out butt": "mot décontracté du quotidien ; désigne aussi le mégot écrasé",
  "Everyday colloquial spelling of nichts": "Orthographe familière courante de nichts",
  "Everyday connection method (slang 'schreib mir')": "Moyen de rester en contact au quotidien (argot 'schreib mir')",
  "Everyday slang (Bock haben)": "Argot du quotidien (Bock haben)",
  "Everyday slang (spendieren = to treat)": "Argot du quotidien (spendieren = offrir, payer sa tournée)",
  "Facharzt = specialist; colloquially also \"einen Termin ausmachen\"": "Facharzt = médecin spécialiste ; familièrement aussi 'einen Termin ausmachen'",
  "Falschparken = illegal/incorrect parking": "Falschparken = stationnement illicite ou mal fait",
  "Family": "Famille",
  "Famous last words — friends will quote it back at you for months.": "Phrase fatidique — tes amis te la ressortiront pendant des mois.",
  "Farewell": "Au revoir",
  "Feeling": "Sentiment",
  "fett = huge (colloquial intensifier); standard dev talk, not rude.": "fett = énorme (intensificateur familier) ; jargon dev courant, pas grossier.",
  "Finding help": "Trouver de l'aide",
  "Fixed casual set expression; already short, so no further clipping.": "Expression figée décontractée ; déjà courte, donc pas d'abréviation supplémentaire.",
  "Flight status update": "Statut du vol",
  "Flirting": "Draguer",
  "Formal": "Formel",
  "Frustrated, to friends. 'schon wieder' carries the job-hunt fatigue.": "Agacé, entre amis. 'schon wieder' porte toute la lassitude de la recherche d'emploi.",
  "Gen-Z": "Gen Z",
  "Greeting": "Salutation",
  "Grufti = colloquial for goth (from Gruft = tomb/crypt)": "Grufti = familier pour gothique (de Gruft = caveau, crypte)",
  "Gunsmith": "Armurier",
  "half-joking quitter's line; 'ich schwör' is casual spoken German": "réplique à moitié sérieuse de celui qui abandonne ; 'ich schwör' est de l'allemand parlé décontracté",
  "idiomatic, informal": "idiomatique, informel",
  "in casual speech often shortened to was: Hast du was gehört?": "à l'oral décontracté, souvent abrégé en was : Hast du was gehört?",
  "In the moment": "Sur le moment",
  "Informal": "Informel",
  "Informal — friends only": "Informel — entre amis seulement",
  "Informal — the spoken contraction you'll usually hear": "Informel — la contraction orale qu'on entend le plus souvent",
  "Informal — to strangers or staff say: Sprechen Sie Englisch?": "Informel — à des inconnus ou au personnel, dites : Sprechen Sie Englisch?",
  "Informal and rude: jemandem den Stinkefinger zeigen.": "Informel et grossier : jemandem den Stinkefinger zeigen.",
  "informal loan from English; das Okay – the go-ahead": "emprunt informel à l'anglais ; das Okay – le feu vert",
  "Informal reply — with Sie say: Und Ihnen?": "Réponse informelle — avec Sie, on dit : Und Ihnen?",
  "Informal term for a friend": "Terme informel pour un ami",
  "informal, e.g. eine brenzlige Situation": "informel, p. ex. eine brenzlige Situation",
  "Introducing": "Se présenter",
  "Knast = colloquial for jail/prison": "Knast = familier pour prison, taule",
  "Komm doch mal vorbei! — the casual open invitation.": "Komm doch mal vorbei! — l'invitation ouverte et décontractée.",
  "Leaving": "Partir",
  "Loadout": "Équipement",
  "Logisch! is also a casual \"obviously\"": "Logisch! est aussi un 'évidemment' décontracté",
  "Making a move": "Faire le premier pas",
  "Making plans": "Faire des projets",
  "medium insult — banter-safe among close friends with the right tone": "insulte moyenne — passe en plaisanterie entre amis proches, avec le bon ton",
  "medium-strong — banter only with thick-skinned close friends": "assez fort — à réserver aux plaisanteries entre amis proches qui ont le cuir épais",
  "Meta": "Méta",
  "Opinion": "Opinion",
  "Ordering food": "Commander à manger",
  "Plans": "Projets",
  "Position callout": "Annonce de position",
  "Reacting": "Réagir",
  "Reassuring": "Rassurer",
  "Relationship status": "Statut relationnel",
  "Reporting a problem": "Signaler un problème",
  "Request": "Demande",
  "Routine": "Routine",
  "Scheduling": "Planification",
  "Seasons": "Saisons",
  "Slang": "Argot",
  "Status callout": "Annonce d'état",
  "Strong agreement": "Accord appuyé",
  "Surprise": "Surprise",
  "Symptom": "Symptôme",
  "Team play": "Jeu d'équipe",
  "Telling time": "Dire l'heure",
  "Texting": "Textos",
  "Time comment": "Remarque sur l'heure",
  "Typical reply": "Réponse typique",
  "Unlocks": "Déblocages",
  "Urgent": "Urgent",
  "Very common leisure activity": "Loisir très courant",
  "Weather": "Météo",
  "Written German too": "Aussi à l'écrit",
};
