/**
 * The usage notes in Spanish.
 *
 * Keyed by the English note exactly as the card carries it. A note missing
 * from here shows its English, so this file is filled in batches without any
 * card ever going blank — see usageNotes.ts for how it is loaded and why it
 * is not part of the interface tables.
 *
 * Fourteen thousand notes exist. This holds the ones translated so far, and
 * check-usage-notes prints how far along each language is on every build.
 */
export const USE_ES: Record<string, string> = {
  "'abschleppen' — to tow. Colloquially it also means pulling someone in a bar.": "'abschleppen' — remolcar. Coloquialmente también significa ligar con alguien en un bar.",
  "'angesagt sein' — forecast, announced. Also slang for what's currently trendy.": "'angesagt sein' — anunciado, previsto. En argot también: lo que está de moda ahora.",
  "'auf etwas stehen' — to be into something. Informal, current, and used constantly.": "'auf etwas stehen' — que te vaya algo. Informal, actual y de uso constante.",
  "'bedeuten' for meaning. 'Was heißt das?' is the more casual version and just as correct.": "'bedeuten' para el significado. 'Was heißt das?' es la versión más informal e igual de correcta.",
  "'Das Match' — loan for a full competitive game; 'ist Schluss' = are we done. Casual.": "'Das Match' — préstamo para un partido completo; 'ist Schluss' = se acabó. Informal.",
  "'davon' avoids repeating the product name after pointing or asking a question about it.": "'davon' evita repetir el nombre del producto después de señalarlo o de preguntar por él.",
  "'davon' refers to an amount of the thing already being discussed and avoids repeating its name.": "'davon' remite a una cantidad de la cosa ya mencionada y evita repetir su nombre.",
  "'Der Hammer' = the standard casual superlative for events. Informal, all ages under about 50.": "'Der Hammer' = el superlativo informal típico para un evento. Informal, hasta unos 50 años.",
  "'Der Ping' — English loan, no alternative. 'übel' is youth slang for 'terrible'.": "'Der Ping' — préstamo del inglés, sin alternativa. 'übel' es argot juvenil para 'horrible'.",
  "'doppelt' — double. 'Menge' is a quantity, and colloquially 'a lot'.": "'doppelt' — doble. 'Menge' es una cantidad y, coloquialmente, 'mucho'.",
  "'dran sein' — to be next in turn. Compact, informal and used constantly.": "'dran sein' — ser el siguiente en el turno. Compacto, informal y de uso constante.",
  "'draufschauen' — to look at it. Colloquial and separable.": "'draufschauen' — echarle un vistazo. Coloquial y separable.",
  "'Du hast einen guten Musikgeschmack' is a real compliment between friends or on a date.": "'Du hast einen guten Musikgeschmack' es un cumplido de verdad entre amigos o en una cita.",
  "'durch sein' — colloquially done for: soaked, worn out, finished.": "'durch sein' — coloquialmente acabado: empapado, gastado, terminado.",
  "'eigentlich' — the casual opener for a serious adult conversation.": "'eigentlich' — la entrada informal a una conversación seria entre adultos.",
  "'Elfer' is the casual clip everyone uses in speech": "'Elfer' es el recorte informal que todos usan al hablar",
  "'ewig' — eternally, used casually for 'ages'. 'laden' for loading.": "'ewig' — eternamente, en tono informal 'un siglo'. 'laden' para cargar.",
  "'frei Schnauze' — literally free snout: no recipe, pure instinct. Wonderfully casual.": "'frei Schnauze' — literalmente hocico libre: sin receta, puro instinto. Maravillosamente informal.",
  "'gar nicht erst' — not even starting. Avoiding the problem entirely.": "'gar nicht erst' — ni siquiera empezar. Evitar el problema por completo.",
  "'glatt' — slippery with ice. The winter warning Germans text each other.": "'glatt' — resbaladizo por el hielo. La advertencia de invierno que los alemanes se mandan por mensaje.",
  "'gläubig' — devout. Said plainly, this ends no friendships in Germany.": "'gläubig' — creyente. Dicho sin más, en Alemania no rompe ninguna amistad.",
  "'gucken' is the casual everyday verb (north/central); the south says 'schauen'": "'gucken' es el verbo informal de cada día (norte y centro); el sur dice 'schauen'",
  "'halbe-halbe' is common informal German for dividing something into two equal parts.": "'halbe-halbe' es alemán informal habitual para repartir algo en dos partes iguales.",
  "'hinkriegen' — to manage or pull something off. Informal, warm and extremely common.": "'hinkriegen' — apañárselas, conseguir algo. Informal, cálido y muy habitual.",
  "'jeder zahlt seins' — the German default among friends. No awkwardness; it's the system.": "'jeder zahlt seins' — lo normal entre amigos en Alemania. Nada incómodo; es el sistema.",
  "'Jetzt reicht's' is the short version, and the last warning before a row.": "'Jetzt reicht's' es la versión corta, y la última advertencia antes de la bronca.",
  "'Kein Thema' — not a topic: it doesn't even need discussing. Friendship in two words.": "'Kein Thema' — no es tema: ni hace falta hablarlo. La amistad en dos palabras.",
  "'mal' makes the command sound casual; use 'in die Ecke' when directing light into it.": "'mal' hace que la orden suene informal; 'in die Ecke' se usa al dirigir la luz hacia allí.",
  "'mal' softens the imperative into a casual request; masculine object is 'deinen Benutzernamen'.": "'mal' convierte el imperativo en una petición informal; el objeto masculino es 'deinen Benutzernamen'.",
  "'mal' turns an offer into something casual. Two seconds, no commitment.": "'mal' convierte el ofrecimiento en algo informal. Dos segundos, sin compromiso.",
  "'mitnehmen' is separable; in the informal imperative, 'mit' lands at the end.": "'mitnehmen' es separable; en el imperativo informal, 'mit' va al final.",
  "'Pass auf!' is the fastest warning; separable 'aufpassen' becomes 'pass ... auf'.": "'Pass auf!' es la advertencia más rápida; el separable 'aufpassen' se convierte en 'pass ... auf'.",
  "'rausfliegen' — from the fuse pack, here about a back. Colloquial and instantly understood.": "'rausfliegen' — del paquete de los fusibles, aquí sobre una espalda. Coloquial y se entiende al instante.",
  "'schauen' or 'gucken' — gucken is more casual. No preposition before the platform.": "'schauen' o 'gucken' — gucken es más informal. Sin preposición delante de la plataforma.",
  "'schlapp' (colloquial) = run-down, drained; 'kaum' = barely.": "'schlapp' (coloquial) = decaído, agotado; 'kaum' = apenas.",
  "'sicherheitshalber' explains that you are checking to avoid an unnecessary mistake.": "'sicherheitshalber' explica que compruebas algo para evitar un error innecesario.",
  "'sportlich' — sporty, and also 'smart-casual' about clothes. Both are common.": "'sportlich' — deportivo, y también 'smart casual' con la ropa. Ambos usos son habituales.",
  "'total' as an intensifier is thoroughly spoken German and slightly informal.": "'total' como intensificador es alemán hablado puro y algo informal.",
  "'unterschiedlich' — differing. Germans use it constantly to avoid overgeneralising.": "'unterschiedlich' — dispar, variable. Los alemanes lo usan sin parar para no generalizar.",
  "'was trinken gehen' — the standard invitation. Casual, open-ended, no commitment implied.": "'was trinken gehen' — la invitación estándar. Informal, abierta, sin compromiso.",
  "'wegmachen' colloquially for putting something aside. 'mal' softens the announcement.": "'wegmachen' coloquialmente para apartar algo. 'mal' suaviza el aviso.",
  "'Wie hoch' for amounts of money. A completely normal question between German friends.": "'Wie hoch' para cantidades de dinero. Una pregunta de lo más normal entre amigos alemanes.",
  "'wieder drauf haben' — colloquial and compact. Bike chains come off constantly.": "'wieder drauf haben' — coloquial y compacto. Las cadenas de bici se salen constantemente.",
  "'Wofür' is the normal neutral form; 'für was' is regional or very casual.": "'Wofür' es la forma neutra normal; 'für was' es regional o muy informal.",
  "'Zeit mitbringen' — the honest warning. Open hours mean open-ended waiting.": "'Zeit mitbringen' — la advertencia honesta. Horario sin cita significa espera sin final.",
  "A casual purpose question when someone has an object, tool, file or unusual plan.": "Una pregunta informal por la finalidad, cuando alguien tiene un objeto, una herramienta, un archivo o un plan poco habitual.",
  "A colloquial fixed expression. It is not sexual in this use.": "Una expresión fija coloquial. En este uso no tiene sentido sexual.",
  "A common informal response to disappointing news or an annoying problem.": "Una respuesta informal habitual ante una noticia decepcionante o un problema molesto.",
  "A common use of sammeln among friends, at work or in a family.": "Un uso habitual de sammeln entre amigos, en el trabajo o en familia.",
  "A considerate response to bad news when a casual reaction would feel too light.": "Una respuesta considerada ante malas noticias, cuando una reacción informal sonaría demasiado ligera.",
  "A direct warning that a condition or necessary step cannot be skipped.": "Una advertencia directa: no se puede saltar una condición o un paso necesario.",
  "A natural follow-up after meeting two friends. 'seid ihr' addresses both people together.": "Una continuación natural al encontrarte con dos amigos. 'seid ihr' se dirige a los dos a la vez.",
  "A normal informal request for a very short wait. Add 'bitte' when you want it to sound softer.": "Una petición informal normal para una espera muy breve. Añade 'bitte' si la quieres más suave.",
  "A practical check that helps the group avoid stopping again once the task has begun.": "Una comprobación práctica que evita al grupo tener que parar otra vez una vez empezado.",
  "A serious accusation, not casual criticism.": "Una acusación grave, no una crítica pasajera.",
  "A standard informal request. The favour itself normally follows immediately.": "Una petición informal estándar. El favor en sí suele venir justo después.",
  "A standard Monday small-talk question with friends, classmates and colleagues you know.": "La típica pregunta de charla del lunes con amigos, compañeros de clase y colegas conocidos.",
  "A standing offer between partners or close friends; warm, no drama.": "Un ofrecimiento que siempre está en pie, entre pareja o amigos cercanos; cálido, sin dramas.",
  "A very common informal way to check whether a day suits someone.": "Una forma informal muy común de preguntar si un día le viene bien a alguien.",
  "abgefahren — driven off, worn. Also slang for 'amazing'; the tyre meaning is older.": "abgefahren — gastado, desgastado. En argot también 'alucinante'; el sentido del neumático es más antiguo.",
  "Achtung! is the warning word; die Ampel = the traffic light, always feminine.": "Achtung! es la palabra de advertencia; die Ampel = el semáforo, siempre femenino.",
  "Afterwards": "Después",
  "Agreeing": "Estar de acuerdo",
  "Allotment neighbours — advisors, rivals and friends across one fence. Mostly all three.": "Vecinos de huerto urbano — asesores, rivales y amigos a un lado y otro de la valla. Casi siempre las tres cosas.",
  "also colloquially \"incredibly\": unwahrscheinlich gut": "coloquialmente también 'increíblemente': unwahrscheinlich gut",
  "also colloquially \"massively\": tierisch gut": "coloquialmente también 'un montón': tierisch gut",
  "always plural": "siempre en plural",
  "An informal reaction to a plan failing, something breaking or another everyday setback.": "Una reacción informal cuando un plan falla, algo se rompe o surge otro contratiempo cotidiano.",
  "Asking for the bill": "Pedir la cuenta",
  "At the table, informal. One guest: 'Greif zu!' Signals the eating may begin.": "En la mesa, informal. Con un invitado: 'Greif zu!' Señala que ya se puede empezar a comer.",
  "At the till": "En la caja",
  "aufblasen — inflating. 'Hilf mir mal' — the casual recruiting of bystanders.": "aufblasen — inflar. 'Hilf mir mal' — la manera informal de reclutar a quien esté cerca.",
  "aufdrängen — pressing something on someone. The warning before every market stroll.": "aufdrängen — endilgarle algo a alguien. La advertencia antes de cada paseo por el mercado.",
  "aufziehen — a storm pulling up. denn delivers the warning in plain word order.": "aufziehen — una tormenta que se acerca. denn da la advertencia con el orden de palabras más simple.",
  "auslaufen — leaking out. 'hinüber sein' — colloquially beyond saving.": "auslaufen — salirse, gotear. 'hinüber sein' — coloquialmente, irrecuperable.",
  "Banter": "Bromas",
  "beraten — advising. 'einen' — the colloquial accusative of man.": "beraten — asesorar. 'einen' — el acusativo coloquial de man.",
  "Between friends: Kannst du mir zehn Euro borgen? Standard German prefers leihen.": "Entre amigos: Kannst du mir zehn Euro borgen? El alemán estándar prefiere leihen.",
  "Blunt but completely normal between partners and friends — German directness in action": "Directo pero de lo más normal entre pareja y amigos — la franqueza alemana en acción",
  "Blunt insult, literally a full fencepost. Friends-only register.": "Insulto directo, literalmente un poste de valla entero. Solo entre amigos.",
  "borgen — the casual borrow-lend verb. die Leiter migrates between households like a shared pet.": "borgen — el verbo informal de prestar y pedir prestado. die Leiter migra de casa en casa como una mascota compartida.",
  "bumming a cigarette; casual, smoker-to-smoker only": "gorronear un cigarrillo; informal, solo de fumador a fumador",
  "Buying time": "Ganar tiempo",
  "Casual": "Informal",
  "Casual — Ding literally means 'thing'": "Informal — Ding significa literalmente 'cosa'",
  "Casual — literally 'now we have the salad'": "Informal — literalmente 'ahora tenemos la ensalada'",
  "Casual — literally 'that's not my beer'": "Informal — literalmente 'esa no es mi cerveza'",
  "Casual — literally 'you had pig'": "Informal — literalmente 'tuviste cerdo'",
  "Casual agreement": "Acuerdo informal",
  "Casual and dramatic; often frustration rather than literal loss of control.": "Informal y dramático; suele ser frustración más que una pérdida real de control.",
  "Casual check-in mid-explanation.": "Comprobación informal a mitad de una explicación.",
  "casual clipping of 'Prominenter' — everyday word": "recorte informal de 'Prominenter' — palabra de uso diario",
  "Casual complaint, one hour in. Someone packed too much Brotzeit.": "Queja informal tras una hora. Alguien metió demasiada Brotzeit.",
  "casual compliment; stehen + dative = to suit someone": "cumplido informal; stehen + dativo = quedarle bien a alguien",
  "Casual date invite (better than formal 'Möchten Sie...')": "Invitación a una cita en tono informal (mejor que el formal 'Möchten Sie...')",
  "Casual dating vocabulary with friends. The verb is fully germanized: ghosten, geghostet.": "Vocabulario informal de citas entre amigos. El verbo está germanizado del todo: ghosten, geghostet.",
  "casual Denglisch — 'Ich hab gecodet' is completely normal among devs": "denglisch informal — 'Ich hab gecodet' es de lo más normal entre desarrolladores",
  "Casual directive": "Indicación informal",
  "Casual everyday goodbye — used everywhere in Germany": "Despedida informal de cada día — se usa en toda Alemania",
  "Casual everyday reassurance": "Frase de tranquilidad informal del día a día",
  "Casual favour between friends (du). 'drüberschauen' = give it a quick once-over.": "Favor informal entre amigos (du). 'drüberschauen' = echarle un vistazo rápido.",
  "Casual for playing video games; in money contexts it means to gamble.": "Informal para jugar a videojuegos; con dinero de por medio significa apostar.",
  "Casual goodbye — borrowed from Italian, extremely popular in Germany": "Despedida informal — tomada del italiano, muy popular en Alemania",
  "casual gym slang for lifting weights; 'pumpen gehen'": "argot informal de gimnasio para levantar pesas; 'pumpen gehen'",
  "Casual imperative 'Investier' is common spoken German; full written form is 'Investiere'.": "El imperativo informal 'Investier' es habitual en el alemán hablado; la forma escrita completa es 'Investiere'.",
  "Casual imperative 'Setz' is short for 'Setze'; 'am' contracts dative 'an dem'.": "El imperativo informal 'Setz' abrevia 'Setze'; 'am' contrae el dativo 'an dem'.",
  "Casual invite": "Invitación informal",
  "Casual kitchen-table economics; sich lohnen = to be worth it — very high-frequency verb": "Economía informal de mesa de cocina; sich lohnen = merecer la pena — verbo muy frecuente",
  "casual loanword; einkaufen is the German verb": "préstamo informal; einkaufen es el verbo alemán",
  "Casual opener": "Entrada de conversación informal",
  "Casual opener for close friends": "Entrada informal entre amigos cercanos",
  "Casual opinion": "Opinión informal",
  "Casual positive update": "Novedad positiva en tono informal",
  "Casual register inside student life; durcharbeiten = work through without a break.": "Registro informal de la vida estudiantil; durcharbeiten = trabajar sin parar.",
  "Casual reminiscing; 'was los sein' = something happening.": "Recuerdos en tono informal; 'was los sein' = pasa algo.",
  "Casual reply": "Respuesta informal",
  "Casual request": "Petición informal",
  "Casual request to repeat": "Petición informal de que repitan",
  "Casual self-intro": "Presentación personal informal",
  "Casual slang command": "Orden en argot informal",
  "Casual slang farewell": "Despedida en argot informal",
  "Casual spoken imperative 'Markier' is common; the tool follows dative 'mit einem Bleistift'.": "El imperativo hablado informal 'Markier' es habitual; la herramienta va en dativo: 'mit einem Bleistift'.",
  "casual spoken; from sich fertig machen = sich zurechtmachen": "habla informal; de sich fertig machen = arreglarse",
  "casual spoken; the machen-lassen pattern for anything done at a salon": "habla informal; el patrón machen-lassen para todo lo que se hace en un salón",
  "casual, admiring; 'definiert' = lean and cut, more technical": "informal y admirativo; 'definiert' = definido y marcado, más técnico",
  "Casual, enthusiastic. 'Der Wahnsinn' is the go-to superlative among friends.": "Informal y entusiasta. 'Der Wahnsinn' es el superlativo de cabecera entre amigos.",
  "casual, everyday; der Lidstrich is the German word, Eyeliner is what people say": "informal, cotidiano; der Lidstrich es la palabra alemana, pero la gente dice Eyeliner",
  "Casual, relieved-triumphant, to friends. 'überstehen' = to survive something unpleasant.": "Informal, con alivio triunfal, entre amigos. 'überstehen' = sobrevivir a algo desagradable.",
  "Casual, teasing — literally 'do you have tomatoes on your eyes?'": "Informal y burlón — literalmente '¿tienes tomates en los ojos?'",
  "Casual, to companions. Famous last words on any hike.": "Informal, a los acompañantes. Las últimas palabras célebres de cualquier caminata.",
  "Casual, to one person (du) — group: Lasst uns anfangen; formal: Fangen wir an": "Informal, a una persona (du) — al grupo: Lasst uns anfangen; formal: Fangen wir an",
  "Casual, universal. The standard excuse to step outside — nobody questions frische Luft.": "Informal, universal. La excusa estándar para salir fuera — nadie cuestiona el frische Luft.",
  "Casual, wry — literally 'life is no pony farm'": "Informal e irónico — literalmente 'la vida no es una granja de ponis'",
  "casual, younger speakers; Hautpflege is the more formal word": "informal, hablantes jóvenes; Hautpflege es la palabra más formal",
  "Casual; 'die Pause' is the break, 'der Pausenhof' the yard it happens on.": "Informal; 'die Pause' es el recreo, 'der Pausenhof' el patio donde ocurre.",
  "casual; 'platt' = wiped out, works for any exhaustion": "informal; 'platt' = hecho polvo, sirve para cualquier agotamiento",
  "casual; 'Proteinshake' works too": "informal; 'Proteinshake' también vale",
  "casual; 'pumpen gehen' marks you as a weights person, not a treadmill person": "informal; 'pumpen gehen' te marca como persona de pesas, no de cinta de correr",
  "casual; 'sich etwas ziehen' = to pull a muscle": "informal; 'sich etwas ziehen' = darse un tirón muscular",
  "Casual; ackern makes the work sound tiring or relentless.": "Informal; ackern hace que el trabajo suene agotador e implacable.",
  "Casual; adults admit it with a grin": "Informal; los adultos lo admiten con una sonrisa",
  "casual; literally also to plough a field": "informal; literalmente también arar un campo",
  "casual; stechen lassen (literally 'have it pricked') is the idiomatic verb for tattoos": "informal; stechen lassen (literalmente 'hacerse pinchar') es el verbo idiomático para los tatuajes",
  "casual; the question everyone asks": "informal; la pregunta que todo el mundo hace",
  "casual; the standard (optimistic) answer": "informal; la respuesta típica (optimista)",
  "Casual; the way adults confess it with a grin.": "Informal; así lo confiesan los adultos con una sonrisa.",
  "casual: kicken gehen = to go and play football": "informal: kicken gehen = ir a jugar al fútbol",
  "Casual. 'Baden gehen' = swim outdoors (lake, sea); 'schwimmen gehen' leans towards the pool.": "Informal. 'Baden gehen' = bañarse al aire libre (lago, mar); 'schwimmen gehen' tira más a la piscina.",
  "Casual. 'Eine Runde drehen' = do a loop; works for walks, bike rides or a quick drive.": "Informal. 'Eine Runde drehen' = dar una vuelta; sirve para paseos, salidas en bici o un trayecto corto en coche.",
  "Casual. 'Sich etwas holen' = to catch/get something (sunburn, a cold).": "Informal. 'Sich etwas holen' = pillar algo (una quemadura solar, un resfriado).",
  "casually clipped to 'der Elfer'": "recortado coloquialmente a 'der Elfer'",
  "Chores": "Tareas de casa",
  "close friends only — sharing a cigarette or vape": "solo entre amigos cercanos — compartir un cigarrillo o un vaper",
  "Coarse and common among friends. It can sound confrontational when said angrily.": "Basto y habitual entre amigos. Dicho con rabia puede sonar a desafío.",
  "Coarse-casual — 'forget it, who cares'. Banter-safe among friends; not for formal company.": "Basto e informal — 'olvídalo, qué más da'. Vale como broma entre amigos; no en compañía formal.",
  "coden is casual Denglisch; completely normal in the du-form dev crowd.": "coden es denglisch informal; de lo más normal en el mundillo dev que se tutea.",
  "Colloquial (Kopfnuss = headbutt/noogie)": "Coloquial (Kopfnuss = cabezazo o coscorrón)",
  "Colloquial and strong; covers verbal and psychological cruelty, not just physical.": "Coloquial y fuerte; abarca la crueldad verbal y psicológica, no solo la física.",
  "Colloquial and strong; verbal or psychological cruelty": "Coloquial y fuerte; crueldad verbal o psicológica",
  "colloquial anglicism (Duden-listed); marketing and social media register": "anglicismo coloquial (recogido en el Duden); registro de marketing y redes sociales",
  "Colloquial but harmless — safe with colleagues and family.": "Coloquial pero inofensivo — seguro con compañeros y familia.",
  "Colloquial but serious; 'zu dritt' = three of them together.": "Coloquial pero serio; 'zu dritt' = entre tres.",
  "Colloquial combo of Ja + Nein": "Mezcla coloquial de Ja + Nein",
  "colloquial intensifier: mächtig stolz = mighty proud": "intensificador coloquial: mächtig stolz = orgullosísimo",
  "Colloquial short form of herauskommen; also used of films, products or models being released.": "Forma corta coloquial de herauskommen; también para películas, productos o modelos que salen.",
  "Colloquial shortcut": "Atajo coloquial",
  "Colloquial, mild — gasped mid-laughter or typed in chats. Friends, family, relaxed colleagues.": "Coloquial, suave — soltado entre risas o escrito en un chat. Amigos, familia, compañeros de confianza.",
  "colloquial, what children do in sand; graben is neutral": "coloquial, lo que hacen los niños en la arena; graben es neutro",
  "Colloquial; 'sich prügeln' is physical, much stronger than 'sich streiten'.": "Coloquial; 'sich prügeln' es físico, mucho más fuerte que 'sich streiten'.",
  "colloquial; invariable: ein super Film": "coloquial; invariable: ein super Film",
  "colloquially also snappy, punchy (UI, prose, deadlines)": "coloquialmente también ágil, contundente (interfaces, textos, plazos)",
  "colloquially shortened to 'das Gespräch'": "acortado coloquialmente a 'das Gespräch'",
  "common and informal; can describe a person, idea or situation": "habitual e informal; puede describir a una persona, una idea o una situación",
  "Common complaint": "Queja frecuente",
  "Common slang reaction": "Reacción habitual en argot",
  "Common slang reaction to bad news — mies = lousy, shabby": "Reacción habitual en argot ante malas noticias — mies = malo, cutre",
  "Confirming": "Confirmar",
  "Consent": "Consentimiento",
  "Consent — always check": "Consentimiento — pregunta siempre",
  "Conversational geopolitics with an opinion baked in — fine among friends, spicier at work": "Geopolítica de conversación con opinión incorporada — bien entre amigos, más delicado en el trabajo",
  "dark humour among friends; 'Echsenmenschen' is the go-to absurd-conspiracy reference": "humor negro entre amigos; 'Echsenmenschen' es la referencia típica a las conspiraciones absurdas",
  "das Band — the conveyor. Braking on it is the one real mistake to avoid.": "das Band — la cinta transportadora. Frenar encima es el único error de verdad que hay que evitar.",
  "das Bügeleisen — the iron. The warning every household repeats.": "das Bügeleisen — la plancha. La advertencia que repite cada casa.",
  "das Halbjahreszeugnis — the February report. The early warning system.": "das Halbjahreszeugnis — el boletín de febrero. El sistema de alerta temprana.",
  "Das hängt davon ab = it depends. Casually, mit Freunden abhängen = to hang out.": "Das hängt davon ab = depende. En tono informal, mit Freunden abhängen = pasar el rato con amigos.",
  "das Profil — the tread. 'ist runter' — worn away; casual passive Germany runs on.": "das Profil — el dibujo del neumático. 'ist runter' — gastado; la pasiva informal sobre la que rueda Alemania.",
  "das Rücklicht — the rear light. 'nur noch schwach' — the warning phase before darkness.": "das Rücklicht — la luz trasera. 'nur noch schwach' — la fase de aviso antes de la oscuridad.",
  "das Teil — the casual word for any piece of clothing. The rule that prevents the pink wash.": "das Teil — la palabra informal para cualquier prenda. La regla que evita la colada rosa.",
  "das Wartezimmer — from the doctor pack, considerably louder. Cats sit high; dogs make friends.": "das Wartezimmer — del paquete del médico, bastante más ruidosa. Los gatos se ponen en alto; los perros hacen amigos.",
  "Dating": "Citas",
  "Deliberately vague — it lets both sides keep it casual. 'was' here is short for 'etwas'.": "Deliberadamente vago — deja que ambas partes lo mantengan informal. Aquí 'was' es la forma corta de 'etwas'.",
  "der Aszendent — the follow-up question that separates casual from committed.": "der Aszendent — la repregunta que separa a los curiosos de los convencidos.",
  "der Helferkreis — the informal volunteer group, common in refugee and neighbourhood support.": "der Helferkreis — el grupo de voluntarios informal, habitual en el apoyo a refugiados y de barrio.",
  "der Platten — the flat tyre, colloquial and universal. The commute's classic opening line.": "der Platten — el pinchazo, coloquial y universal. La frase clásica para abrir la charla del trayecto.",
  "der Strafzettel, colloquially das Knöllchen = parking ticket": "der Strafzettel, coloquialmente das Knöllchen = multa de aparcamiento",
  "Desire": "Deseo",
  "die Abmahnung — the warning shot, at work or over copyright. Serious, not final.": "die Abmahnung — el aviso serio, en el trabajo o por derechos de autor. Grave, pero no definitivo.",
  "die Abmahnung — the written warning. Serious, but far from a dismissal.": "die Abmahnung — la amonestación por escrito. Grave, pero muy lejos de un despido.",
  "die Hausnummer — colloquial for a rough figure. More with a role change.": "die Hausnummer — coloquial para una cifra aproximada. Más si cambia el puesto.",
  "die Jugendfeuerwehr — where most volunteers begin. Knots, hoses and friendships.": "die Jugendfeuerwehr — donde empiezan la mayoría de los voluntarios. Nudos, mangueras y amistades.",
  "die Kantine — the subsidised lunch. The invitation that builds actual friendships.": "die Kantine — la comida subvencionada. La invitación de la que salen amistades de verdad.",
  "die Lawine — the avalanche. The warning is not decorative.": "die Lawine — la avalancha. La advertencia no es decorativa.",
  "Direct and neutral: 'Ich bin schwanger.' Colloquially, 'schwanger von ihm' names the father.": "Directo y neutro: 'Ich bin schwanger.' Coloquialmente, 'schwanger von ihm' nombra al padre.",
  "düngen = to fertilize; der Dünger = fertilizer. Du register — said between family/friends": "düngen = abonar; der Dünger = el abono. Registro de du — se dice entre familia y amigos",
  "eh = anyway / in any case (colloquial 'ohnehin')": "eh = de todos modos / en cualquier caso (coloquial por 'ohnehin')",
  "eine Runde schmeißen — literally throwing a round. Casual, generous, slightly theatrical.": "eine Runde schmeißen — literalmente lanzar una ronda. Informal, generoso, un poco teatral.",
  "Emergency": "Emergencia",
  "Emphasis": "Énfasis",
  "Emphatic casual yes": "Sí informal y enfático",
  "Encouragement between friends or from a partner — the compliment learners most want to hear.": "Ánimo entre amigos o de la pareja — el cumplido que más quieren oír quienes aprenden.",
  "Enemy info": "Info del enemigo",
  "English loan, fully naturalized and plural; 'doch' makes it dismissive — casual register": "préstamo del inglés, plenamente naturalizado y en plural; 'doch' lo vuelve despectivo — registro informal",
  "Enthusiastic yes": "Sí entusiasta",
  "Essential": "Imprescindible",
  "everyday casual word; also means the stubbed-out butt": "palabra informal de cada día; también significa la colilla apagada",
  "Everyday colloquial spelling of nichts": "Grafía coloquial cotidiana de nichts",
  "Everyday connection method (slang 'schreib mir')": "Manera cotidiana de mantener el contacto (argot 'schreib mir')",
  "Everyday criticism, medium weight; fine in casual talk about colleagues or exes.": "Crítica cotidiana de peso medio; vale en una charla informal sobre compañeros o ex.",
  "Everyday office and friend request; rüberschicken (send over) is the casual variant.": "Petición cotidiana en la oficina y entre amigos; rüberschicken (mandar) es la variante informal.",
  "Everyday slang (Bock haben)": "Argot cotidiano (Bock haben)",
  "Everyday slang (spendieren = to treat)": "Argot cotidiano (spendieren = invitar)",
  "Facharzt = specialist; colloquially also \"einen Termin ausmachen\"": "Facharzt = médico especialista; coloquialmente también 'einen Termin ausmachen'",
  "Falschparken = illegal/incorrect parking": "Falschparken = aparcar mal o donde no se debe",
  "Family": "Familia",
  "Famous last words — friends will quote it back at you for months.": "Últimas palabras célebres — tus amigos te lo repetirán durante meses.",
  "Farewell": "Despedida",
  "Feeling": "Sentimiento",
  "feiern = to celebrate, colloquially 'to love something'; very current usage.": "feiern = celebrar, coloquialmente 'flipar con algo'; uso muy actual.",
  "fett = huge (colloquial intensifier); standard dev talk, not rude.": "fett = enorme (intensificador coloquial); jerga dev habitual, no es grosero.",
  "Finding help": "Buscar ayuda",
  "Fixed casual set expression; already short, so no further clipping.": "Expresión fija informal; ya es corta, así que no se recorta más.",
  "flach and steil around dahinter — the swimming-pool warning as a geometry lesson.": "flach y steil en torno a dahinter — la advertencia de la piscina como clase de geometría.",
  "Flight status update": "Estado del vuelo",
  "Flirting": "Ligar",
  "Formal": "Formal",
  "Frustrated, to friends. 'schon wieder' carries the job-hunt fatigue.": "Con frustración, entre amigos. 'schon wieder' lleva el cansancio de buscar trabajo.",
  "geblitzt werden = to get caught by a speed camera — the standard colloquial verb for it": "geblitzt werden = que te pille un radar — el verbo coloquial estándar para eso",
  "Gen-Z": "Gen Z",
  "Genuine compliment between friends; on a date it's practically flirting.": "Cumplido de verdad entre amigos; en una cita es prácticamente coquetear.",
  "gereizt — irritable, like a nerve already touched. Fair warning to the room.": "gereizt — irritable, como un nervio ya tocado. Un aviso justo para toda la sala.",
  "gib — du-imperative of geben with vowel change; mal keeps it casual, not bossy.": "gib — imperativo de du de geben con cambio vocálico; mal lo mantiene informal, no mandón.",
  "Greeting": "Saludo",
  "Grufti = colloquial for goth (from Gruft = tomb/crypt)": "Grufti = coloquial para gótico (de Gruft = cripta, tumba)",
  "Gunsmith": "Armería",
  "Half-joking household rule for the unsortable. Colloquial, said with a shrug.": "Norma casera medio en broma para lo que no se puede clasificar. Coloquial, dicho encogiéndose de hombros.",
  "half-joking quitter's line; 'ich schwör' is casual spoken German": "frase medio en broma de quien lo deja; 'ich schwör' es alemán hablado informal",
  "idiomatic, informal": "idiomático, informal",
  "Im Alter von 30 = at the age of 30. As an exclamation, Alter! = dude! — very casual.": "Im Alter von 30 = a los 30 años. Como exclamación, Alter! = ¡tío! — muy informal.",
  "in casual speech often shortened to was: Hast du was gehört?": "en el habla informal se acorta a menudo a was: Hast du was gehört?",
  "In the moment": "En el momento",
  "Informal": "Informal",
  "Informal — friends only": "Informal — solo entre amigos",
  "Informal — the spoken contraction you'll usually hear": "Informal — la contracción hablada que se oye normalmente",
  "Informal — to strangers or staff say: Sprechen Sie Englisch?": "Informal — a desconocidos o al personal se dice: Sprechen Sie Englisch?",
  "Informal and rude: jemandem den Stinkefinger zeigen.": "Informal y grosero: jemandem den Stinkefinger zeigen.",
  "Informal and warm, mostly southern. 'Grüß Gott' is its formal, Bavarian and Austrian cousin.": "Informal y cálido, sobre todo en el sur. 'Grüß Gott' es su primo formal, bávaro y austriaco.",
  "Informal imperative of separable 'aufheben': 'Heb ... auf'; the full written form is 'Hebe'.": "Imperativo informal del separable 'aufheben': 'Heb ... auf'; la forma escrita completa es 'Hebe'.",
  "informal loan from English; das Okay – the go-ahead": "préstamo informal del inglés; das Okay – el visto bueno",
  "Informal reply — with Sie say: Und Ihnen?": "Respuesta informal — con Sie se dice: Und Ihnen?",
  "Informal term for a friend": "Término informal para un amigo",
  "informal, e.g. eine brenzlige Situation": "informal, p. ej. eine brenzlige Situation",
  "informal; the standard German way to say someone drifted off into conspiracy land": "informal; la forma alemana estándar de decir que alguien se ha ido al mundo de las conspiraciones",
  "Introducing": "Presentarse",
  "justifying one more — works for cigarettes and beers alike; very casual": "para justificar uno más — vale igual para cigarrillos que para cervezas; muy informal",
  "kicken — casual football. der Bolzplatz — the scuffed pitch every neighbourhood has.": "kicken — fútbol informal. der Bolzplatz — el campillo pelado que tiene cada barrio.",
  "klamm — damp, and colloquially short of cash. Honest without being dramatic.": "klamm — húmedo, y coloquialmente sin blanca. Honesto sin ser dramático.",
  "klingen — sounding. The honest warning given to every violin household's neighbours.": "klingen — sonar. La advertencia honesta a los vecinos de toda casa con violín.",
  "knapp bei Kasse — tight at the till. The honest sentence that friends answer with einladen.": "knapp bei Kasse — justo de caja. La frase honesta a la que los amigos responden con einladen.",
  "Knast = colloquial for jail/prison": "Knast = coloquial para cárcel, trena",
  "Komm doch mal vorbei! — the casual open invitation.": "Komm doch mal vorbei! — la invitación abierta e informal.",
  "Leaving": "Irse",
  "Loadout": "Equipamiento",
  "Logisch! is also a casual \"obviously\"": "Logisch! es también un 'obvio' informal",
  "Making a move": "Dar el primer paso",
  "Making plans": "Hacer planes",
  "medium insult — banter-safe among close friends with the right tone": "insulto medio — vale como broma entre amigos cercanos con el tono adecuado",
  "medium-strong — banter only with thick-skinned close friends": "de fuerza media-alta — solo en broma con amigos cercanos de piel dura",
  "Meta": "Meta",
  "Opinion": "Opinión",
  "Ordering food": "Pedir comida",
  "Plans": "Planes",
  "Position callout": "Aviso de posición",
  "Reacting": "Reaccionar",
  "Reassuring": "Tranquilizar",
  "Relationship status": "Estado sentimental",
  "Reporting a problem": "Informar de un problema",
  "Request": "Petición",
  "Routine": "Rutina",
  "Scheduling": "Programar",
  "Seasons": "Estaciones",
  "Slang": "Argot",
  "Status callout": "Aviso de estado",
  "Strong agreement": "Acuerdo rotundo",
  "Surprise": "Sorpresa",
  "Symptom": "Síntoma",
  "Team play": "Juego en equipo",
  "Telling time": "Decir la hora",
  "Texting": "Mensajes",
  "Time comment": "Comentario sobre la hora",
  "Typical reply": "Respuesta típica",
  "Unlocks": "Desbloqueos",
  "Urgent": "Urgente",
  "Very common leisure activity": "Actividad de ocio muy común",
  "Weather": "El tiempo",
  "Written German too": "También en alemán escrito",
};
