/**
 * The usage notes in Portuguese.
 *
 * Keyed by the English note exactly as the card carries it. A note missing
 * from here shows its English, so this file is filled in batches without any
 * card ever going blank — see usageNotes.ts for how it is loaded and why it
 * is not part of the interface tables.
 *
 * Fourteen thousand notes exist. This holds the ones translated so far, and
 * check-usage-notes prints how far along each language is on every build.
 */
export const USE_PT: Record<string, string> = {
  "'doppelt' — double. 'Menge' is a quantity, and colloquially 'a lot'.": "'doppelt' — duplo. 'Menge' é uma quantidade e, coloquialmente, 'muito'.",
  "'draufschauen' — to look at it. Colloquial and separable.": "'draufschauen' — dar uma olhada. Coloquial e separável.",
  "'durch sein' — colloquially done for: soaked, worn out, finished.": "'durch sein' — coloquialmente acabado: encharcado, gasto, no fim.",
  "'eigentlich' — the casual opener for a serious adult conversation.": "'eigentlich' — a abertura descontraída de uma conversa séria entre adultos.",
  "'Elfer' is the casual clip everyone uses in speech": "'Elfer' é a forma curta descontraída que todos usam na fala",
  "'ewig' — eternally, used casually for 'ages'. 'laden' for loading.": "'ewig' — eternamente, em tom descontraído 'uma eternidade'. 'laden' para carregar.",
  "'gar nicht erst' — not even starting. Avoiding the problem entirely.": "'gar nicht erst' — nem sequer começar. Evitar o problema por completo.",
  "'gläubig' — devout. Said plainly, this ends no friendships in Germany.": "'gläubig' — crente, praticante. Dito com naturalidade, na Alemanha não acaba com amizades.",
  "'schlapp' (colloquial) = run-down, drained; 'kaum' = barely.": "'schlapp' (coloquial) = abatido, esgotado; 'kaum' = mal, quase não.",
  "A colloquial fixed expression. It is not sexual in this use.": "Uma expressão fixa coloquial. Neste uso não tem sentido sexual.",
  "A common use of sammeln among friends, at work or in a family.": "Um uso comum de sammeln entre amigos, no trabalho ou em família.",
  "A direct warning that a condition or necessary step cannot be skipped.": "Um aviso direto: uma condição ou um passo necessário não pode ser saltado.",
  "A serious accusation, not casual criticism.": "Uma acusação grave, não uma crítica passageira.",
  "A standing offer between partners or close friends; warm, no drama.": "Um oferecimento sempre válido entre parceiros ou amigos próximos; caloroso, sem drama.",
  "A very common informal way to check whether a day suits someone.": "Uma forma informal muito comum de perguntar se um dia serve a alguém.",
  "Afterwards": "Depois",
  "Agreeing": "Concordar",
  "also colloquially \"incredibly\": unwahrscheinlich gut": "coloquialmente também 'incrivelmente': unwahrscheinlich gut",
  "also colloquially \"massively\": tierisch gut": "coloquialmente também 'para caramba': tierisch gut",
  "always plural": "sempre no plural",
  "Asking for the bill": "Pedir a conta",
  "At the till": "Na caixa",
  "auslaufen — leaking out. 'hinüber sein' — colloquially beyond saving.": "auslaufen — vazar. 'hinüber sein' — coloquialmente, sem salvação.",
  "Banter": "Brincadeira",
  "beraten — advising. 'einen' — the colloquial accusative of man.": "beraten — aconselhar. 'einen' — o acusativo coloquial de man.",
  "Blunt insult, literally a full fencepost. Friends-only register.": "Insulto direto, literalmente um poste de cerca inteiro. Só entre amigos.",
  "bumming a cigarette; casual, smoker-to-smoker only": "pedir um cigarro emprestado; descontraído, só de fumador para fumador",
  "Buying time": "Ganhar tempo",
  "Casual": "Descontraído",
  "Casual — Ding literally means 'thing'": "Descontraído — Ding significa literalmente 'coisa'",
  "Casual — literally 'now we have the salad'": "Descontraído — literalmente 'agora temos a salada'",
  "Casual — literally 'that's not my beer'": "Descontraído — literalmente 'isso não é a minha cerveja'",
  "Casual — literally 'you had pig'": "Descontraído — literalmente 'tiveste porco'",
  "Casual agreement": "Concordância descontraída",
  "Casual check-in mid-explanation.": "Verificação descontraída a meio de uma explicação.",
  "casual clipping of 'Prominenter' — everyday word": "forma curta descontraída de 'Prominenter' — palavra do dia a dia",
  "Casual complaint, one hour in. Someone packed too much Brotzeit.": "Queixa descontraída ao fim de uma hora. Alguém levou Brotzeit a mais.",
  "casual compliment; stehen + dative = to suit someone": "elogio descontraído; stehen + dativo = ficar bem a alguém",
  "Casual date invite (better than formal 'Möchten Sie...')": "Convite para um encontro em tom descontraído (melhor do que o formal 'Möchten Sie...')",
  "casual Denglisch — 'Ich hab gecodet' is completely normal among devs": "denglisch descontraído — 'Ich hab gecodet' é perfeitamente normal entre programadores",
  "Casual directive": "Instrução descontraída",
  "Casual everyday goodbye — used everywhere in Germany": "Despedida descontraída do dia a dia — usada em toda a Alemanha",
  "Casual everyday reassurance": "Frase de tranquilização descontraída do dia a dia",
  "Casual for playing video games; in money contexts it means to gamble.": "Descontraído para jogar videojogos; quando envolve dinheiro, significa apostar.",
  "Casual goodbye — borrowed from Italian, extremely popular in Germany": "Despedida descontraída — vinda do italiano, muito popular na Alemanha",
  "casual gym slang for lifting weights; 'pumpen gehen'": "calão descontraído de ginásio para levantar pesos; 'pumpen gehen'",
  "Casual invite": "Convite descontraído",
  "casual loanword; einkaufen is the German verb": "estrangeirismo descontraído; einkaufen é o verbo alemão",
  "Casual opener": "Abertura de conversa descontraída",
  "Casual opener for close friends": "Abertura descontraída entre amigos próximos",
  "Casual opinion": "Opinião descontraída",
  "Casual positive update": "Novidade positiva em tom descontraído",
  "Casual reminiscing; 'was los sein' = something happening.": "Recordações em tom descontraído; 'was los sein' = estar a acontecer algo.",
  "Casual reply": "Resposta descontraída",
  "Casual request": "Pedido descontraído",
  "Casual request to repeat": "Pedido descontraído para repetir",
  "Casual self-intro": "Apresentação pessoal descontraída",
  "Casual slang command": "Ordem em calão descontraído",
  "Casual slang farewell": "Despedida em calão descontraído",
  "casual spoken; from sich fertig machen = sich zurechtmachen": "fala descontraída; de sich fertig machen = arranjar-se",
  "casual spoken; the machen-lassen pattern for anything done at a salon": "fala descontraída; o padrão machen-lassen para tudo o que se faz num salão",
  "casual, admiring; 'definiert' = lean and cut, more technical": "descontraído e admirativo; 'definiert' = seco e definido, mais técnico",
  "Casual, teasing — literally 'do you have tomatoes on your eyes?'": "Descontraído e trocista — literalmente 'tens tomates nos olhos?'",
  "Casual, to companions. Famous last words on any hike.": "Descontraído, aos companheiros. As famosas últimas palavras de qualquer caminhada.",
  "Casual, wry — literally 'life is no pony farm'": "Descontraído e irónico — literalmente 'a vida não é uma quinta de póneis'",
  "casual, younger speakers; Hautpflege is the more formal word": "descontraído, falantes mais jovens; Hautpflege é a palavra mais formal",
  "casual; 'platt' = wiped out, works for any exhaustion": "descontraído; 'platt' = de rastos, serve para qualquer cansaço",
  "casual; 'Proteinshake' works too": "descontraído; 'Proteinshake' também serve",
  "casual; 'sich etwas ziehen' = to pull a muscle": "descontraído; 'sich etwas ziehen' = distender um músculo",
  "Casual; ackern makes the work sound tiring or relentless.": "Descontraído; ackern faz o trabalho soar cansativo e implacável.",
  "Casual; adults admit it with a grin": "Descontraído; os adultos admitem-no com um sorriso",
  "casual; literally also to plough a field": "descontraído; literalmente também lavrar um campo",
  "casual; the question everyone asks": "descontraído; a pergunta que toda a gente faz",
  "casual; the standard (optimistic) answer": "descontraído; a resposta habitual (otimista)",
  "Casual; the way adults confess it with a grin.": "Descontraído; a forma como os adultos o confessam com um sorriso.",
  "casual: kicken gehen = to go and play football": "descontraído: kicken gehen = ir jogar à bola",
  "Casual. 'Sich etwas holen' = to catch/get something (sunburn, a cold).": "Descontraído. 'Sich etwas holen' = apanhar alguma coisa (escaldão, constipação).",
  "casually clipped to 'der Elfer'": "encurtado coloquialmente para 'der Elfer'",
  "Chores": "Tarefas domésticas",
  "close friends only — sharing a cigarette or vape": "só entre amigos próximos — partilhar um cigarro ou um vaper",
  "coden is casual Denglisch; completely normal in the du-form dev crowd.": "coden é denglisch descontraído; perfeitamente normal no meio dev que se trata por tu.",
  "Colloquial (Kopfnuss = headbutt/noogie)": "Coloquial (Kopfnuss = cabeçada ou cascudo)",
  "Colloquial and strong; verbal or psychological cruelty": "Coloquial e forte; crueldade verbal ou psicológica",
  "Colloquial but harmless — safe with colleagues and family.": "Coloquial mas inofensivo — seguro com colegas e família.",
  "Colloquial but serious; 'zu dritt' = three of them together.": "Coloquial mas sério; 'zu dritt' = os três juntos.",
  "Colloquial combo of Ja + Nein": "Mistura coloquial de Ja + Nein",
  "colloquial intensifier: mächtig stolz = mighty proud": "intensificador coloquial: mächtig stolz = orgulhosíssimo",
  "Colloquial shortcut": "Atalho coloquial",
  "colloquial, what children do in sand; graben is neutral": "coloquial, o que as crianças fazem na areia; graben é neutro",
  "colloquial; invariable: ein super Film": "coloquial; invariável: ein super Film",
  "colloquially also snappy, punchy (UI, prose, deadlines)": "coloquialmente também ágil, incisivo (interfaces, textos, prazos)",
  "colloquially shortened to 'das Gespräch'": "encurtado coloquialmente para 'das Gespräch'",
  "common and informal; can describe a person, idea or situation": "comum e informal; pode descrever uma pessoa, uma ideia ou uma situação",
  "Common complaint": "Queixa comum",
  "Common slang reaction": "Reação comum em calão",
  "Common slang reaction to bad news — mies = lousy, shabby": "Reação comum em calão a más notícias — mies = mau, reles",
  "Confirming": "Confirmar",
  "Consent": "Consentimento",
  "Consent — always check": "Consentimento — pergunta sempre",
  "das Bügeleisen — the iron. The warning every household repeats.": "das Bügeleisen — o ferro de engomar. O aviso que se repete em todas as casas.",
  "das Halbjahreszeugnis — the February report. The early warning system.": "das Halbjahreszeugnis — a pauta de fevereiro. O sistema de alerta precoce.",
  "Dating": "Encontros",
  "der Strafzettel, colloquially das Knöllchen = parking ticket": "der Strafzettel, coloquialmente das Knöllchen = multa de estacionamento",
  "Desire": "Desejo",
  "die Lawine — the avalanche. The warning is not decorative.": "die Lawine — a avalanche. O aviso não é decorativo.",
  "eh = anyway / in any case (colloquial 'ohnehin')": "eh = de qualquer forma / em todo o caso (coloquial por 'ohnehin')",
  "Emergency": "Emergência",
  "Emphasis": "Ênfase",
  "Emphatic casual yes": "Sim descontraído e enfático",
  "Enemy info": "Info do inimigo",
  "Enthusiastic yes": "Sim entusiasmado",
  "Essential": "Essencial",
  "everyday casual word; also means the stubbed-out butt": "palavra descontraída do dia a dia; também significa a beata apagada",
  "Everyday colloquial spelling of nichts": "Grafia coloquial do dia a dia de nichts",
  "Everyday connection method (slang 'schreib mir')": "Forma do dia a dia de manter o contacto (calão 'schreib mir')",
  "Everyday slang (Bock haben)": "Calão do dia a dia (Bock haben)",
  "Everyday slang (spendieren = to treat)": "Calão do dia a dia (spendieren = pagar, oferecer)",
  "Facharzt = specialist; colloquially also \"einen Termin ausmachen\"": "Facharzt = médico especialista; coloquialmente também 'einen Termin ausmachen'",
  "Falschparken = illegal/incorrect parking": "Falschparken = estacionar mal ou onde não se deve",
  "Family": "Família",
  "Famous last words — friends will quote it back at you for months.": "Famosas últimas palavras — os amigos vão citá-las durante meses.",
  "Farewell": "Despedida",
  "Feeling": "Sentimento",
  "fett = huge (colloquial intensifier); standard dev talk, not rude.": "fett = enorme (intensificador coloquial); jargão dev normal, não é grosseiro.",
  "Finding help": "Encontrar ajuda",
  "Fixed casual set expression; already short, so no further clipping.": "Expressão fixa descontraída; já é curta, por isso não se encurta mais.",
  "Flight status update": "Estado do voo",
  "Flirting": "Namoriscar",
  "Formal": "Formal",
  "Frustrated, to friends. 'schon wieder' carries the job-hunt fatigue.": "Com frustração, entre amigos. 'schon wieder' carrega o cansaço da procura de emprego.",
  "Gen-Z": "Gen Z",
  "Greeting": "Cumprimento",
  "Grufti = colloquial for goth (from Gruft = tomb/crypt)": "Grufti = coloquial para gótico (de Gruft = cripta, jazigo)",
  "Gunsmith": "Armeiro",
  "half-joking quitter's line; 'ich schwör' is casual spoken German": "frase meio a brincar de quem desiste; 'ich schwör' é alemão falado descontraído",
  "idiomatic, informal": "idiomático, informal",
  "in casual speech often shortened to was: Hast du was gehört?": "na fala descontraída encurta-se muitas vezes para was: Hast du was gehört?",
  "In the moment": "No momento",
  "Informal": "Informal",
  "Informal — friends only": "Informal — só entre amigos",
  "Informal — the spoken contraction you'll usually hear": "Informal — a contração falada que se ouve normalmente",
  "Informal — to strangers or staff say: Sprechen Sie Englisch?": "Informal — a desconhecidos ou a funcionários diz-se: Sprechen Sie Englisch?",
  "Informal and rude: jemandem den Stinkefinger zeigen.": "Informal e grosseiro: jemandem den Stinkefinger zeigen.",
  "informal loan from English; das Okay – the go-ahead": "estrangeirismo informal do inglês; das Okay – a luz verde",
  "Informal reply — with Sie say: Und Ihnen?": "Resposta informal — com Sie diz-se: Und Ihnen?",
  "Informal term for a friend": "Termo informal para um amigo",
  "informal, e.g. eine brenzlige Situation": "informal, p. ex. eine brenzlige Situation",
  "Introducing": "Apresentar-se",
  "Knast = colloquial for jail/prison": "Knast = coloquial para prisão, cadeia",
  "Komm doch mal vorbei! — the casual open invitation.": "Komm doch mal vorbei! — o convite aberto e descontraído.",
  "Leaving": "Ir embora",
  "Loadout": "Equipamento",
  "Logisch! is also a casual \"obviously\"": "Logisch! é também um 'claro' descontraído",
  "Making a move": "Dar o primeiro passo",
  "Making plans": "Fazer planos",
  "medium insult — banter-safe among close friends with the right tone": "insulto médio — aceitável como brincadeira entre amigos próximos, com o tom certo",
  "medium-strong — banter only with thick-skinned close friends": "médio-forte — só a brincar com amigos próximos de pele grossa",
  "Meta": "Meta",
  "Opinion": "Opinião",
  "Ordering food": "Pedir comida",
  "Plans": "Planos",
  "Position callout": "Aviso de posição",
  "Reacting": "Reagir",
  "Reassuring": "Tranquilizar",
  "Relationship status": "Estado da relação",
  "Reporting a problem": "Comunicar um problema",
  "Request": "Pedido",
  "Routine": "Rotina",
  "Scheduling": "Marcar",
  "Seasons": "Estações",
  "Slang": "Calão",
  "Status callout": "Aviso de estado",
  "Strong agreement": "Concordância forte",
  "Surprise": "Surpresa",
  "Symptom": "Sintoma",
  "Team play": "Jogo em equipa",
  "Telling time": "Dizer as horas",
  "Texting": "Mensagens",
  "Time comment": "Comentário sobre a hora",
  "Typical reply": "Resposta típica",
  "Unlocks": "Desbloqueios",
  "Urgent": "Urgente",
  "Very common leisure activity": "Atividade de lazer muito comum",
  "Weather": "Tempo",
  "Written German too": "Também no alemão escrito",
};
