/**
 * The usage notes in French.
 *
 * Keyed by the English note exactly as the card carries it. A note missing
 * from here shows its English, so this file is filled in batches without any
 * card ever going blank — see usageNotes.ts for how it is loaded and why it
 * is not part of the interface tables.
 *
 * Fourteen thousand notes exist. This holds the ones translated so far, and
 * check-usage-notes prints how far along each language is on every build.
 */
export const USE_FR: Record<string, string> = {
  "'abschleppen' — to tow. Colloquially it also means pulling someone in a bar.": "'abschleppen' — remorquer. Familièrement, cela veut aussi dire lever quelqu'un dans un bar.",
  "'angesagt sein' — forecast, announced. Also slang for what's currently trendy.": "'angesagt sein' — annoncé, prévu. En argot aussi : ce qui est tendance en ce moment.",
  "'auf etwas stehen' — to be into something. Informal, current, and used constantly.": "'auf etwas stehen' — être fan de quelque chose. Informel, actuel, employé sans arrêt.",
  "'bedeuten' for meaning. 'Was heißt das?' is the more casual version and just as correct.": "'bedeuten' pour le sens. 'Was heißt das?' est la version plus décontractée, tout aussi correcte.",
  "'Das Match' — loan for a full competitive game; 'ist Schluss' = are we done. Casual.": "'Das Match' — emprunt pour une partie de compétition entière ; 'ist Schluss' = c'est terminé. Décontracté.",
  "'davon' avoids repeating the product name after pointing or asking a question about it.": "'davon' évite de répéter le nom du produit après l'avoir montré ou après avoir posé une question dessus.",
  "'davon' refers to an amount of the thing already being discussed and avoids repeating its name.": "'davon' renvoie à une quantité de la chose déjà évoquée et évite d'en répéter le nom.",
  "'Der Hammer' = the standard casual superlative for events. Informal, all ages under about 50.": "'Der Hammer' = le superlatif décontracté habituel pour un événement. Informel, chez les moins de 50 ans environ.",
  "'Der Ping' — English loan, no alternative. 'übel' is youth slang for 'terrible'.": "'Der Ping' — emprunt à l'anglais, sans équivalent. 'übel' est de l'argot des jeunes pour 'atroce'.",
  "'doppelt' — double. 'Menge' is a quantity, and colloquially 'a lot'.": "'doppelt' — double. 'Menge' est une quantité, et familièrement 'beaucoup'.",
  "'dran sein' — to be next in turn. Compact, informal and used constantly.": "'dran sein' — être le prochain à passer. Compact, informel, employé sans arrêt.",
  "'draufschauen' — to look at it. Colloquial and separable.": "'draufschauen' — y jeter un œil. Familier et à particule séparable.",
  "'Du hast einen guten Musikgeschmack' is a real compliment between friends or on a date.": "'Du hast einen guten Musikgeschmack' est un vrai compliment entre amis ou lors d'un rendez-vous.",
  "'durch sein' — colloquially done for: soaked, worn out, finished.": "'durch sein' — familièrement fichu : trempé, usé, fini.",
  "'eigentlich' — the casual opener for a serious adult conversation.": "'eigentlich' — l'entrée en matière décontractée d'une conversation sérieuse entre adultes.",
  "'Elfer' is the casual clip everyone uses in speech": "'Elfer' est l'abréviation décontractée que tout le monde emploie à l'oral",
  "'ewig' — eternally, used casually for 'ages'. 'laden' for loading.": "'ewig' — éternellement, employé de façon décontractée pour 'une éternité'. 'laden' pour le chargement.",
  "'frei Schnauze' — literally free snout: no recipe, pure instinct. Wonderfully casual.": "'frei Schnauze' — littéralement museau libre : pas de recette, rien que l'instinct. Merveilleusement décontracté.",
  "'gar nicht erst' — not even starting. Avoiding the problem entirely.": "'gar nicht erst' — ne même pas commencer. Éviter complètement le problème.",
  "'glatt' — slippery with ice. The winter warning Germans text each other.": "'glatt' — verglacé, glissant. L'avertissement d'hiver que les Allemands s'envoient par texto.",
  "'gläubig' — devout. Said plainly, this ends no friendships in Germany.": "'gläubig' — croyant, pratiquant. Dit simplement, cela ne brise aucune amitié en Allemagne.",
  "'gucken' is the casual everyday verb (north/central); the south says 'schauen'": "'gucken' est le verbe décontracté du quotidien (nord et centre) ; le sud dit 'schauen'",
  "'halbe-halbe' is common informal German for dividing something into two equal parts.": "'halbe-halbe' est de l'allemand informel courant pour partager quelque chose en deux parts égales.",
  "'hinkriegen' — to manage or pull something off. Informal, warm and extremely common.": "'hinkriegen' — arriver à faire quelque chose, y parvenir. Informel, chaleureux et extrêmement courant.",
  "'jeder zahlt seins' — the German default among friends. No awkwardness; it's the system.": "'jeder zahlt seins' — la règle par défaut entre amis en Allemagne. Rien de gênant : c'est le système.",
  "'Jetzt reicht's' is the short version, and the last warning before a row.": "'Jetzt reicht's' est la version courte, et le dernier avertissement avant la dispute.",
  "'Kein Thema' — not a topic: it doesn't even need discussing. Friendship in two words.": "'Kein Thema' — pas un sujet : il n'y a même pas à en discuter. L'amitié en deux mots.",
  "'mal' makes the command sound casual; use 'in die Ecke' when directing light into it.": "'mal' rend l'ordre décontracté ; on emploie 'in die Ecke' quand on y dirige la lumière.",
  "'mal' softens the imperative into a casual request; masculine object is 'deinen Benutzernamen'.": "'mal' adoucit l'impératif en demande décontractée ; l'objet masculin est 'deinen Benutzernamen'.",
  "'mal' turns an offer into something casual. Two seconds, no commitment.": "'mal' rend l'offre décontractée. Deux secondes, sans engagement.",
  "'mitnehmen' is separable; in the informal imperative, 'mit' lands at the end.": "'mitnehmen' est à particule séparable ; à l'impératif informel, 'mit' se retrouve à la fin.",
  "'Pass auf!' is the fastest warning; separable 'aufpassen' becomes 'pass ... auf'.": "'Pass auf!' est l'avertissement le plus rapide ; le séparable 'aufpassen' devient 'pass ... auf'.",
  "'rausfliegen' — from the fuse pack, here about a back. Colloquial and instantly understood.": "'rausfliegen' — venu du lot sur les fusibles, ici pour un dos. Familier et compris immédiatement.",
  "'schauen' or 'gucken' — gucken is more casual. No preposition before the platform.": "'schauen' ou 'gucken' — gucken est plus décontracté. Pas de préposition devant la plateforme.",
  "'schlapp' (colloquial) = run-down, drained; 'kaum' = barely.": "'schlapp' (familier) = à plat, vidé ; 'kaum' = à peine.",
  "'sicherheitshalber' explains that you are checking to avoid an unnecessary mistake.": "'sicherheitshalber' explique qu'on vérifie pour éviter une erreur inutile.",
  "'sportlich' — sporty, and also 'smart-casual' about clothes. Both are common.": "'sportlich' — sportif, et aussi 'smart casual' pour les vêtements. Les deux sont courants.",
  "'total' as an intensifier is thoroughly spoken German and slightly informal.": "'total' comme intensificateur relève pleinement de l'allemand parlé et reste légèrement informel.",
  "'unterschiedlich' — differing. Germans use it constantly to avoid overgeneralising.": "'unterschiedlich' — variable, divers. Les Allemands l'emploient sans arrêt pour éviter de généraliser.",
  "'was trinken gehen' — the standard invitation. Casual, open-ended, no commitment implied.": "'was trinken gehen' — l'invitation standard. Décontractée, ouverte, sans engagement.",
  "'wegmachen' colloquially for putting something aside. 'mal' softens the announcement.": "'wegmachen' familièrement pour ranger quelque chose de côté. 'mal' adoucit l'annonce.",
  "'Wie hoch' for amounts of money. A completely normal question between German friends.": "'Wie hoch' pour les sommes d'argent. Une question tout à fait normale entre amis allemands.",
  "'wieder drauf haben' — colloquial and compact. Bike chains come off constantly.": "'wieder drauf haben' — familier et compact. Les chaînes de vélo déraillent sans arrêt.",
  "'Wofür' is the normal neutral form; 'für was' is regional or very casual.": "'Wofür' est la forme neutre normale ; 'für was' est régional ou très décontracté.",
  "'Zeit mitbringen' — the honest warning. Open hours mean open-ended waiting.": "'Zeit mitbringen' — l'avertissement honnête. Des horaires sans rendez-vous, c'est une attente sans fin.",
  "A casual purpose question when someone has an object, tool, file or unusual plan.": "Une question décontractée sur le but, quand quelqu'un a un objet, un outil, un fichier ou un projet inhabituel.",
  "A colloquial fixed expression. It is not sexual in this use.": "Une expression figée familière. Elle n'a rien de sexuel dans cet emploi.",
  "A common informal response to disappointing news or an annoying problem.": "Une réaction informelle courante à une nouvelle décevante ou à un problème agaçant.",
  "A common use of sammeln among friends, at work or in a family.": "Un emploi courant de sammeln entre amis, au travail ou en famille.",
  "A considerate response to bad news when a casual reaction would feel too light.": "Une réponse pleine d'égards à une mauvaise nouvelle, quand une réaction décontractée paraîtrait trop légère.",
  "A direct warning that a condition or necessary step cannot be skipped.": "Un avertissement direct : une condition ou une étape nécessaire ne peut pas être sautée.",
  "A natural follow-up after meeting two friends. 'seid ihr' addresses both people together.": "Une relance naturelle après avoir croisé deux amis. 'seid ihr' s'adresse aux deux à la fois.",
  "A normal informal request for a very short wait. Add 'bitte' when you want it to sound softer.": "Une demande informelle normale pour patienter très brièvement. Ajoutez 'bitte' pour l'adoucir.",
  "A practical check that helps the group avoid stopping again once the task has begun.": "Une vérification pratique qui évite au groupe de devoir s'arrêter à nouveau une fois lancé.",
  "A serious accusation, not casual criticism.": "Une accusation grave, pas une critique en passant.",
  "A standard informal request. The favour itself normally follows immediately.": "Une demande informelle standard. Le service demandé suit normalement tout de suite.",
  "A standard Monday small-talk question with friends, classmates and colleagues you know.": "La question de small talk du lundi, entre amis, camarades de classe et collègues que l'on connaît.",
  "A standing offer between partners or close friends; warm, no drama.": "Une proposition toujours valable entre partenaires ou amis proches ; chaleureuse, sans drame.",
  "A very common informal way to check whether a day suits someone.": "Une manière informelle très courante de demander si un jour convient à quelqu'un.",
  "abgefahren — driven off, worn. Also slang for 'amazing'; the tyre meaning is older.": "abgefahren — usé jusqu'à la corde. En argot aussi 'génial' ; le sens lié au pneu est plus ancien.",
  "Achtung! is the warning word; die Ampel = the traffic light, always feminine.": "Achtung! est le mot d'avertissement ; die Ampel = le feu tricolore, toujours féminin.",
  "Afterwards": "Ensuite",
  "Agreeing": "Approuver",
  "Allotment neighbours — advisors, rivals and friends across one fence. Mostly all three.": "Voisins de jardin ouvrier — conseillers, rivaux et amis de part et d'autre d'une clôture. Le plus souvent les trois.",
  "also colloquially \"incredibly\": unwahrscheinlich gut": "familièrement aussi 'incroyablement' : unwahrscheinlich gut",
  "also colloquially \"massively\": tierisch gut": "familièrement aussi 'vachement' : tierisch gut",
  "always plural": "toujours au pluriel",
  "An informal reaction to a plan failing, something breaking or another everyday setback.": "Une réaction informelle quand un plan échoue, que quelque chose casse ou qu'un contretemps du quotidien survient.",
  "Asking for the bill": "Demander l'addition",
  "At the table, informal. One guest: 'Greif zu!' Signals the eating may begin.": "À table, informel. Pour un seul invité : 'Greif zu!' Cela signale qu'on peut commencer à manger.",
  "At the till": "À la caisse",
  "aufblasen — inflating. 'Hilf mir mal' — the casual recruiting of bystanders.": "aufblasen — gonfler. 'Hilf mir mal' — la façon décontractée d'enrôler ceux qui passent.",
  "aufdrängen — pressing something on someone. The warning before every market stroll.": "aufdrängen — imposer quelque chose à quelqu'un. L'avertissement avant chaque flânerie au marché.",
  "aufziehen — a storm pulling up. denn delivers the warning in plain word order.": "aufziehen — un orage qui se lève. denn livre l'avertissement dans un ordre des mots tout simple.",
  "auslaufen — leaking out. 'hinüber sein' — colloquially beyond saving.": "auslaufen — fuir, s'écouler. 'hinüber sein' — familièrement, fichu.",
  "Banter": "Vannes",
  "beraten — advising. 'einen' — the colloquial accusative of man.": "beraten — conseiller. 'einen' — l'accusatif familier de man.",
  "Between friends: Kannst du mir zehn Euro borgen? Standard German prefers leihen.": "Entre amis : Kannst du mir zehn Euro borgen? L'allemand standard préfère leihen.",
  "Blunt but completely normal between partners and friends — German directness in action": "Franc mais tout à fait normal entre partenaires et amis — la franchise allemande à l'œuvre",
  "Blunt insult, literally a full fencepost. Friends-only register.": "Insulte brutale, littéralement un piquet de clôture entier. À réserver aux amis.",
  "borgen — the casual borrow-lend verb. die Leiter migrates between households like a shared pet.": "borgen — le verbe décontracté pour prêter et emprunter. die Leiter migre d'un foyer à l'autre comme un animal en garde partagée.",
  "bumming a cigarette; casual, smoker-to-smoker only": "taxer une cigarette ; décontracté, entre fumeurs seulement",
  "Buying time": "Gagner du temps",
  "Casual": "Décontracté",
  "Casual — Ding literally means 'thing'": "Décontracté — Ding signifie littéralement 'chose'",
  "Casual — literally 'now we have the salad'": "Décontracté — littéralement 'maintenant on a la salade'",
  "Casual — literally 'that's not my beer'": "Décontracté — littéralement 'ce n'est pas ma bière'",
  "Casual — literally 'you had pig'": "Décontracté — littéralement 'tu as eu du cochon'",
  "Casual agreement": "Accord décontracté",
  "Casual and dramatic; often frustration rather than literal loss of control.": "Décontracté et dramatique ; souvent de la frustration plutôt qu'une vraie perte de contrôle.",
  "Casual check-in mid-explanation.": "Petite vérification décontractée en pleine explication.",
  "casual clipping of 'Prominenter' — everyday word": "abréviation décontractée de 'Prominenter' — mot de tous les jours",
  "Casual complaint, one hour in. Someone packed too much Brotzeit.": "Plainte décontractée au bout d'une heure. Quelqu'un a emporté trop de Brotzeit.",
  "casual compliment; stehen + dative = to suit someone": "compliment décontracté ; stehen + datif = aller bien à quelqu'un",
  "Casual date invite (better than formal 'Möchten Sie...')": "Invitation à un rendez-vous, ton décontracté (mieux que le formel 'Möchten Sie...')",
  "Casual dating vocabulary with friends. The verb is fully germanized: ghosten, geghostet.": "Vocabulaire de rencontres décontracté entre amis. Le verbe est entièrement germanisé : ghosten, geghostet.",
  "casual Denglisch — 'Ich hab gecodet' is completely normal among devs": "denglisch décontracté — 'Ich hab gecodet' est tout à fait normal chez les développeurs",
  "Casual directive": "Consigne décontractée",
  "Casual everyday goodbye — used everywhere in Germany": "Au revoir décontracté du quotidien — employé partout en Allemagne",
  "Casual everyday reassurance": "Petite phrase rassurante et décontractée du quotidien",
  "Casual favour between friends (du). 'drüberschauen' = give it a quick once-over.": "Petit service décontracté entre amis (du). 'drüberschauen' = y jeter un coup d'œil rapide.",
  "Casual for playing video games; in money contexts it means to gamble.": "Décontracté pour jouer aux jeux vidéo ; avec de l'argent, cela signifie parier.",
  "Casual goodbye — borrowed from Italian, extremely popular in Germany": "Au revoir décontracté — emprunté à l'italien, très répandu en Allemagne",
  "casual gym slang for lifting weights; 'pumpen gehen'": "argot décontracté de salle de sport pour soulever de la fonte ; 'pumpen gehen'",
  "Casual imperative 'Investier' is common spoken German; full written form is 'Investiere'.": "L'impératif décontracté 'Investier' est courant à l'oral ; la forme écrite complète est 'Investiere'.",
  "Casual imperative 'Setz' is short for 'Setze'; 'am' contracts dative 'an dem'.": "L'impératif décontracté 'Setz' abrège 'Setze' ; 'am' contracte le datif 'an dem'.",
  "Casual invite": "Invitation décontractée",
  "Casual kitchen-table economics; sich lohnen = to be worth it — very high-frequency verb": "Économie de coin de table, ton décontracté ; sich lohnen = en valoir la peine — verbe très fréquent",
  "casual loanword; einkaufen is the German verb": "emprunt décontracté ; einkaufen est le verbe allemand",
  "Casual opener": "Entrée en matière décontractée",
  "Casual opener for close friends": "Entrée en matière décontractée entre amis proches",
  "Casual opinion": "Avis exprimé de façon décontractée",
  "Casual positive update": "Bonne nouvelle donnée sur un ton décontracté",
  "Casual register inside student life; durcharbeiten = work through without a break.": "Registre décontracté de la vie étudiante ; durcharbeiten = travailler sans faire de pause.",
  "Casual reminiscing; 'was los sein' = something happening.": "Souvenirs évoqués sur un ton décontracté ; 'was los sein' = il se passe quelque chose.",
  "Casual reply": "Réponse décontractée",
  "Casual request": "Demande décontractée",
  "Casual request to repeat": "Demande décontractée de répéter",
  "Casual self-intro": "Présentation de soi décontractée",
  "Casual slang command": "Ordre en argot décontracté",
  "Casual slang farewell": "Au revoir en argot décontracté",
  "Casual spoken imperative 'Markier' is common; the tool follows dative 'mit einem Bleistift'.": "L'impératif oral décontracté 'Markier' est courant ; l'outil suit au datif : 'mit einem Bleistift'.",
  "casual spoken; from sich fertig machen = sich zurechtmachen": "oral décontracté ; de sich fertig machen = se préparer, s'apprêter",
  "casual spoken; the machen-lassen pattern for anything done at a salon": "oral décontracté ; la tournure machen-lassen pour tout ce qui se fait chez le coiffeur",
  "casual, admiring; 'definiert' = lean and cut, more technical": "décontracté et admiratif ; 'definiert' = sec et dessiné, plus technique",
  "Casual, enthusiastic. 'Der Wahnsinn' is the go-to superlative among friends.": "Décontracté, enthousiaste. 'Der Wahnsinn' est le superlatif de référence entre amis.",
  "casual, everyday; der Lidstrich is the German word, Eyeliner is what people say": "décontracté, quotidien ; der Lidstrich est le mot allemand, mais on dit Eyeliner",
  "Casual, relieved-triumphant, to friends. 'überstehen' = to survive something unpleasant.": "Décontracté, soulagé et triomphant, entre amis. 'überstehen' = survivre à quelque chose de désagréable.",
  "Casual, teasing — literally 'do you have tomatoes on your eyes?'": "Décontracté et taquin — littéralement 'tu as des tomates sur les yeux ?'",
  "Casual, to companions. Famous last words on any hike.": "Décontracté, à ses compagnons. La phrase fatidique de toute randonnée.",
  "Casual, to one person (du) — group: Lasst uns anfangen; formal: Fangen wir an": "Décontracté, à une seule personne (du) — au groupe : Lasst uns anfangen ; formel : Fangen wir an",
  "Casual, universal. The standard excuse to step outside — nobody questions frische Luft.": "Décontracté, universel. L'excuse standard pour sortir — personne ne discute la frische Luft.",
  "Casual, wry — literally 'life is no pony farm'": "Décontracté et pince-sans-rire — littéralement 'la vie n'est pas un poney-club'",
  "casual, younger speakers; Hautpflege is the more formal word": "décontracté, plutôt chez les jeunes ; Hautpflege est le mot plus formel",
  "Casual; 'die Pause' is the break, 'der Pausenhof' the yard it happens on.": "Décontracté ; 'die Pause' est la récréation, 'der Pausenhof' la cour où elle se passe.",
  "casual; 'platt' = wiped out, works for any exhaustion": "décontracté ; 'platt' = lessivé, valable pour toute forme d'épuisement",
  "casual; 'Proteinshake' works too": "décontracté ; 'Proteinshake' fonctionne aussi",
  "casual; 'pumpen gehen' marks you as a weights person, not a treadmill person": "décontracté ; 'pumpen gehen' vous classe du côté de la fonte, pas du tapis de course",
  "casual; 'sich etwas ziehen' = to pull a muscle": "décontracté ; 'sich etwas ziehen' = se faire un claquage",
  "Casual; ackern makes the work sound tiring or relentless.": "Décontracté ; ackern fait sonner le travail comme épuisant et sans répit.",
  "Casual; adults admit it with a grin": "Décontracté ; les adultes l'avouent avec un sourire en coin",
  "casual; literally also to plough a field": "décontracté ; littéralement aussi labourer un champ",
  "casual; stechen lassen (literally 'have it pricked') is the idiomatic verb for tattoos": "décontracté ; stechen lassen (littéralement 'se faire piquer') est le verbe idiomatique pour les tatouages",
  "casual; the question everyone asks": "décontracté ; la question que tout le monde pose",
  "casual; the standard (optimistic) answer": "décontracté ; la réponse habituelle (optimiste)",
  "Casual; the way adults confess it with a grin.": "Décontracté ; la façon dont les adultes l'avouent avec un sourire.",
  "casual: kicken gehen = to go and play football": "décontracté : kicken gehen = aller jouer au foot",
  "Casual. 'Baden gehen' = swim outdoors (lake, sea); 'schwimmen gehen' leans towards the pool.": "Décontracté. 'Baden gehen' = se baigner dehors (lac, mer) ; 'schwimmen gehen' penche vers la piscine.",
  "Casual. 'Eine Runde drehen' = do a loop; works for walks, bike rides or a quick drive.": "Décontracté. 'Eine Runde drehen' = faire un tour ; vaut pour la marche, le vélo ou un petit tour en voiture.",
  "Casual. 'Sich etwas holen' = to catch/get something (sunburn, a cold).": "Décontracté. 'Sich etwas holen' = attraper quelque chose (coup de soleil, rhume).",
  "casually clipped to 'der Elfer'": "abrégé familièrement en 'der Elfer'",
  "Chores": "Tâches ménagères",
  "close friends only — sharing a cigarette or vape": "entre amis proches seulement — partager une cigarette ou une vapoteuse",
  "Coarse and common among friends. It can sound confrontational when said angrily.": "Grossier et courant entre amis. Dit avec colère, cela peut sonner comme une provocation.",
  "Coarse-casual — 'forget it, who cares'. Banter-safe among friends; not for formal company.": "Grossier-décontracté — 'laisse tomber, on s'en fiche'. Passe en plaisanterie entre amis ; pas en compagnie formelle.",
  "coden is casual Denglisch; completely normal in the du-form dev crowd.": "coden est du denglisch décontracté ; tout à fait normal dans le milieu dev qui se tutoie.",
  "Colloquial (Kopfnuss = headbutt/noogie)": "Familier (Kopfnuss = coup de tête ou pichenette sur le crâne)",
  "Colloquial and strong; covers verbal and psychological cruelty, not just physical.": "Familier et fort ; couvre la cruauté verbale et psychologique, pas seulement physique.",
  "Colloquial and strong; verbal or psychological cruelty": "Familier et fort ; cruauté verbale ou psychologique",
  "colloquial anglicism (Duden-listed); marketing and social media register": "anglicisme familier (répertorié dans le Duden) ; registre du marketing et des réseaux sociaux",
  "Colloquial but harmless — safe with colleagues and family.": "Familier mais anodin — sans risque avec les collègues et la famille.",
  "Colloquial but serious; 'zu dritt' = three of them together.": "Familier mais grave ; 'zu dritt' = à trois.",
  "Colloquial combo of Ja + Nein": "Mot-valise familier de Ja + Nein",
  "colloquial intensifier: mächtig stolz = mighty proud": "intensificateur familier : mächtig stolz = drôlement fier",
  "Colloquial short form of herauskommen; also used of films, products or models being released.": "Forme courte familière de herauskommen ; s'emploie aussi pour la sortie de films, produits ou modèles.",
  "Colloquial shortcut": "Raccourci familier",
  "Colloquial, mild — gasped mid-laughter or typed in chats. Friends, family, relaxed colleagues.": "Familier, doux — lâché en plein rire ou tapé dans un chat. Amis, famille, collègues détendus.",
  "colloquial, what children do in sand; graben is neutral": "familier, ce que les enfants font dans le sable ; graben est neutre",
  "Colloquial; 'sich prügeln' is physical, much stronger than 'sich streiten'.": "Familier ; 'sich prügeln' est physique, bien plus fort que 'sich streiten'.",
  "colloquial; invariable: ein super Film": "familier ; invariable : ein super Film",
  "colloquially also snappy, punchy (UI, prose, deadlines)": "familièrement aussi vif, percutant (interfaces, textes, délais)",
  "colloquially shortened to 'das Gespräch'": "abrégé familièrement en 'das Gespräch'",
  "common and informal; can describe a person, idea or situation": "courant et informel ; peut décrire une personne, une idée ou une situation",
  "Common complaint": "Plainte courante",
  "Common slang reaction": "Réaction courante en argot",
  "Common slang reaction to bad news — mies = lousy, shabby": "Réaction argotique courante à une mauvaise nouvelle — mies = nul, minable",
  "Confirming": "Confirmer",
  "Consent": "Consentement",
  "Consent — always check": "Consentement — toujours demander",
  "Conversational geopolitics with an opinion baked in — fine among friends, spicier at work": "Géopolitique de conversation, avec une opinion incluse — ça passe entre amis, plus délicat au travail",
  "dark humour among friends; 'Echsenmenschen' is the go-to absurd-conspiracy reference": "humour noir entre amis ; 'Echsenmenschen' est la référence type aux complots absurdes",
  "das Band — the conveyor. Braking on it is the one real mistake to avoid.": "das Band — le tapis roulant. Freiner dessus est la seule vraie erreur à éviter.",
  "das Bügeleisen — the iron. The warning every household repeats.": "das Bügeleisen — le fer à repasser. L'avertissement que répète chaque foyer.",
  "das Halbjahreszeugnis — the February report. The early warning system.": "das Halbjahreszeugnis — le bulletin de février. Le système d'alerte précoce.",
  "Das hängt davon ab = it depends. Casually, mit Freunden abhängen = to hang out.": "Das hängt davon ab = ça dépend. De façon décontractée, mit Freunden abhängen = traîner avec des amis.",
  "das Profil — the tread. 'ist runter' — worn away; casual passive Germany runs on.": "das Profil — la sculpture du pneu. 'ist runter' — usée ; le passif décontracté sur lequel roule l'Allemagne.",
  "das Rücklicht — the rear light. 'nur noch schwach' — the warning phase before darkness.": "das Rücklicht — le feu arrière. 'nur noch schwach' — la phase d'avertissement avant le noir complet.",
  "das Teil — the casual word for any piece of clothing. The rule that prevents the pink wash.": "das Teil — le mot décontracté pour n'importe quel vêtement. La règle qui évite la lessive rose.",
  "das Wartezimmer — from the doctor pack, considerably louder. Cats sit high; dogs make friends.": "das Wartezimmer — venu du lot sur le médecin, nettement plus bruyant. Les chats sont perchés ; les chiens se font des amis.",
  "Dating": "Rencontres",
  "Deliberately vague — it lets both sides keep it casual. 'was' here is short for 'etwas'.": "Volontairement vague — cela permet aux deux parties de rester décontractées. 'was' est ici l'abrégé de 'etwas'.",
  "der Aszendent — the follow-up question that separates casual from committed.": "der Aszendent — la question de relance qui sépare les curieux des convaincus.",
  "der Helferkreis — the informal volunteer group, common in refugee and neighbourhood support.": "der Helferkreis — le groupe de bénévoles informel, courant dans l'aide aux réfugiés et l'entraide de quartier.",
  "der Platten — the flat tyre, colloquial and universal. The commute's classic opening line.": "der Platten — la crevaison, familier et universel. La réplique d'ouverture classique des trajets quotidiens.",
  "der Strafzettel, colloquially das Knöllchen = parking ticket": "der Strafzettel, familièrement das Knöllchen = contravention de stationnement",
  "Desire": "Envie",
  "die Abmahnung — the warning shot, at work or over copyright. Serious, not final.": "die Abmahnung — le coup de semonce, au travail ou en matière de droit d'auteur. Sérieux, mais pas définitif.",
  "die Abmahnung — the written warning. Serious, but far from a dismissal.": "die Abmahnung — l'avertissement écrit. Sérieux, mais loin d'un licenciement.",
  "die Hausnummer — colloquial for a rough figure. More with a role change.": "die Hausnummer — familier pour un ordre de grandeur. Davantage si le poste change.",
  "die Jugendfeuerwehr — where most volunteers begin. Knots, hoses and friendships.": "die Jugendfeuerwehr — là où commencent la plupart des volontaires. Des nœuds, des tuyaux et des amitiés.",
  "die Kantine — the subsidised lunch. The invitation that builds actual friendships.": "die Kantine — le déjeuner subventionné. L'invitation qui crée de vraies amitiés.",
  "die Lawine — the avalanche. The warning is not decorative.": "die Lawine — l'avalanche. L'avertissement n'est pas décoratif.",
  "Direct and neutral: 'Ich bin schwanger.' Colloquially, 'schwanger von ihm' names the father.": "Direct et neutre : 'Ich bin schwanger.' Familièrement, 'schwanger von ihm' nomme le père.",
  "düngen = to fertilize; der Dünger = fertilizer. Du register — said between family/friends": "düngen = fertiliser ; der Dünger = l'engrais. Registre du du — entre famille et amis",
  "eh = anyway / in any case (colloquial 'ohnehin')": "eh = de toute façon / en tout cas (familier pour 'ohnehin')",
  "eine Runde schmeißen — literally throwing a round. Casual, generous, slightly theatrical.": "eine Runde schmeißen — littéralement lancer une tournée. Décontracté, généreux, un peu théâtral.",
  "Emergency": "Urgence",
  "Emphasis": "Insistance",
  "Emphatic casual yes": "Oui décontracté et appuyé",
  "Encouragement between friends or from a partner — the compliment learners most want to hear.": "Encouragement entre amis ou de la part d'un partenaire — le compliment que les apprenants rêvent d'entendre.",
  "Enemy info": "Info ennemi",
  "English loan, fully naturalized and plural; 'doch' makes it dismissive — casual register": "emprunt à l'anglais, pleinement naturalisé et au pluriel ; 'doch' le rend dédaigneux — registre décontracté",
  "Enthusiastic yes": "Oui enthousiaste",
  "Essential": "Essentiel",
  "everyday casual word; also means the stubbed-out butt": "mot décontracté du quotidien ; désigne aussi le mégot écrasé",
  "Everyday colloquial spelling of nichts": "Orthographe familière courante de nichts",
  "Everyday connection method (slang 'schreib mir')": "Moyen de rester en contact au quotidien (argot 'schreib mir')",
  "Everyday criticism, medium weight; fine in casual talk about colleagues or exes.": "Critique du quotidien, de poids moyen ; ça passe dans une conversation décontractée sur des collègues ou des ex.",
  "Everyday office and friend request; rüberschicken (send over) is the casual variant.": "Demande quotidienne au bureau et entre amis ; rüberschicken (faire passer) est la variante décontractée.",
  "Everyday slang (Bock haben)": "Argot du quotidien (Bock haben)",
  "Everyday slang (spendieren = to treat)": "Argot du quotidien (spendieren = offrir, payer sa tournée)",
  "Facharzt = specialist; colloquially also \"einen Termin ausmachen\"": "Facharzt = médecin spécialiste ; familièrement aussi 'einen Termin ausmachen'",
  "Falschparken = illegal/incorrect parking": "Falschparken = stationnement illicite ou mal fait",
  "Family": "Famille",
  "Famous last words — friends will quote it back at you for months.": "Phrase fatidique — tes amis te la ressortiront pendant des mois.",
  "Farewell": "Au revoir",
  "Feeling": "Sentiment",
  "feiern = to celebrate, colloquially 'to love something'; very current usage.": "feiern = faire la fête, familièrement 'adorer quelque chose' ; usage très actuel.",
  "fett = huge (colloquial intensifier); standard dev talk, not rude.": "fett = énorme (intensificateur familier) ; jargon dev courant, pas grossier.",
  "Finding help": "Trouver de l'aide",
  "Fixed casual set expression; already short, so no further clipping.": "Expression figée décontractée ; déjà courte, donc pas d'abréviation supplémentaire.",
  "flach and steil around dahinter — the swimming-pool warning as a geometry lesson.": "flach et steil autour de dahinter — l'avertissement de la piscine sous forme de leçon de géométrie.",
  "Flight status update": "Statut du vol",
  "Flirting": "Draguer",
  "Formal": "Formel",
  "Frustrated, to friends. 'schon wieder' carries the job-hunt fatigue.": "Agacé, entre amis. 'schon wieder' porte toute la lassitude de la recherche d'emploi.",
  "geblitzt werden = to get caught by a speed camera — the standard colloquial verb for it": "geblitzt werden = se faire flasher par un radar — le verbe familier standard pour cela",
  "Gen-Z": "Gen Z",
  "Genuine compliment between friends; on a date it's practically flirting.": "Vrai compliment entre amis ; lors d'un rendez-vous, c'est pratiquement du flirt.",
  "gereizt — irritable, like a nerve already touched. Fair warning to the room.": "gereizt — à cran, comme un nerf déjà touché. Un avertissement loyal à toute la pièce.",
  "gib — du-imperative of geben with vowel change; mal keeps it casual, not bossy.": "gib — impératif en du de geben avec alternance vocalique ; mal garde le ton décontracté, pas autoritaire.",
  "Greeting": "Salutation",
  "Grufti = colloquial for goth (from Gruft = tomb/crypt)": "Grufti = familier pour gothique (de Gruft = caveau, crypte)",
  "Gunsmith": "Armurier",
  "Half-joking household rule for the unsortable. Colloquial, said with a shrug.": "Règle domestique à moitié pour rire, pour tout ce qui ne se trie pas. Familier, dit avec un haussement d'épaules.",
  "half-joking quitter's line; 'ich schwör' is casual spoken German": "réplique à moitié sérieuse de celui qui abandonne ; 'ich schwör' est de l'allemand parlé décontracté",
  "idiomatic, informal": "idiomatique, informel",
  "Im Alter von 30 = at the age of 30. As an exclamation, Alter! = dude! — very casual.": "Im Alter von 30 = à l'âge de 30 ans. En exclamation, Alter! = mec ! — très décontracté.",
  "in casual speech often shortened to was: Hast du was gehört?": "à l'oral décontracté, souvent abrégé en was : Hast du was gehört?",
  "In the moment": "Sur le moment",
  "Informal": "Informel",
  "Informal — friends only": "Informel — entre amis seulement",
  "Informal — the spoken contraction you'll usually hear": "Informel — la contraction orale qu'on entend le plus souvent",
  "Informal — to strangers or staff say: Sprechen Sie Englisch?": "Informel — à des inconnus ou au personnel, dites : Sprechen Sie Englisch?",
  "Informal and rude: jemandem den Stinkefinger zeigen.": "Informel et grossier : jemandem den Stinkefinger zeigen.",
  "Informal and warm, mostly southern. 'Grüß Gott' is its formal, Bavarian and Austrian cousin.": "Informel et chaleureux, surtout dans le sud. 'Grüß Gott' en est le cousin formel, bavarois et autrichien.",
  "Informal imperative of separable 'aufheben': 'Heb ... auf'; the full written form is 'Hebe'.": "Impératif informel du séparable 'aufheben' : 'Heb ... auf' ; la forme écrite complète est 'Hebe'.",
  "informal loan from English; das Okay – the go-ahead": "emprunt informel à l'anglais ; das Okay – le feu vert",
  "Informal reply — with Sie say: Und Ihnen?": "Réponse informelle — avec Sie, on dit : Und Ihnen?",
  "Informal term for a friend": "Terme informel pour un ami",
  "informal, e.g. eine brenzlige Situation": "informel, p. ex. eine brenzlige Situation",
  "informal; the standard German way to say someone drifted off into conspiracy land": "informel ; la manière allemande standard de dire que quelqu'un a dérivé vers les complots",
  "Introducing": "Se présenter",
  "justifying one more — works for cigarettes and beers alike; very casual": "pour justifier la suivante — vaut aussi bien pour les cigarettes que pour les bières ; très décontracté",
  "kicken — casual football. der Bolzplatz — the scuffed pitch every neighbourhood has.": "kicken — le foot décontracté. der Bolzplatz — le terrain pelé que possède chaque quartier.",
  "klamm — damp, and colloquially short of cash. Honest without being dramatic.": "klamm — humide, et familièrement à court d'argent. Honnête sans être dramatique.",
  "klingen — sounding. The honest warning given to every violin household's neighbours.": "klingen — sonner. L'avertissement honnête adressé aux voisins de toute maison à violon.",
  "knapp bei Kasse — tight at the till. The honest sentence that friends answer with einladen.": "knapp bei Kasse — à court à la caisse. La phrase honnête à laquelle les amis répondent par einladen.",
  "knapp bei Kasse sein = to be short of money; casual register, said among friends and family": "knapp bei Kasse sein = être à court d'argent ; registre décontracté, entre amis et en famille",
  "Knast = colloquial for jail/prison": "Knast = familier pour prison, taule",
  "Komm doch mal vorbei! — the casual open invitation.": "Komm doch mal vorbei! — l'invitation ouverte et décontractée.",
  "Leaving": "Partir",
  "Level 2, medium-mild — like English 'damn'; fine among adults, avoid formal settings": "Niveau 2, moyen-doux — comme le 'damn' anglais ; ça passe entre adultes, à éviter dans un cadre formel",
  "Loadout": "Équipement",
  "Logisch! is also a casual \"obviously\"": "Logisch! est aussi un 'évidemment' décontracté",
  "Making a move": "Faire le premier pas",
  "Making plans": "Faire des projets",
  "medium insult — banter-safe among close friends with the right tone": "insulte moyenne — passe en plaisanterie entre amis proches, avec le bon ton",
  "medium-strong — banter only with thick-skinned close friends": "assez fort — à réserver aux plaisanteries entre amis proches qui ont le cuir épais",
  "Messaging — informal (du); in formal calls: Ich schreibe Ihnen eine Nachricht": "Écrire des messages — informel (du) ; en contexte formel : Ich schreibe Ihnen eine Nachricht",
  "Meta": "Méta",
  "mild-medium — often affectionate banter among friends": "doux à moyen — souvent une taquinerie affectueuse entre amis",
  "mithelfen — pitching in. The morning-after miracle that separates friends from guests.": "mithelfen — donner un coup de main. Le miracle du lendemain matin qui sépare les amis des invités.",
  "mocking the classic 'Spiegel-Poser', a fixture of every gym; casual, said behind their back": "moqueur envers le classique 'Spiegel-Poser', présent dans toute salle de sport ; décontracté, dit dans son dos",
  "mocking, informal; the Aluhut is THE German ridicule image for conspiracists": "moqueur, informel ; l'Aluhut est LE symbole allemand de la moquerie envers les complotistes",
  "nachfragen — following up. The sentence that saves the friendship.": "nachfragen — relancer. La phrase qui sauve l'amitié.",
  "neu laden = to reload — neu as an adverb before the verb; einfach shrugs it casual.": "neu laden = recharger — neu en adverbe devant le verbe ; einfach donne le ton décontracté.",
  "Neutral opener that signals something is on your mind; works with friends and family.": "Entrée en matière neutre qui signale qu'on a quelque chose sur le cœur ; convient aux amis et à la famille.",
  "neutral small talk; works with anyone — casually dropped article is typical": "small talk neutre ; convient à tout le monde — l'article qu'on laisse tomber est typique",
  "neutral word; among friends it's almost always 'die Kippe'": "mot neutre ; entre amis, c'est presque toujours 'die Kippe'",
  "Neutral-casual; 'Abi' is what everyone says — the full 'Abitur' sounds formal.": "Neutre-décontracté ; tout le monde dit 'Abi' — le complet 'Abitur' fait formel.",
  "Neutral-casual; 'kriegen' is the spoken form of 'bekommen'.": "Neutre-décontracté ; 'kriegen' est la forme orale de 'bekommen'.",
  "Neutral-colloquial; 'zuschlagen' = to throw a punch, to strike.": "Neutre-familier ; 'zuschlagen' = donner un coup, frapper.",
  "Neutral, common — disbelief that hovers between amused and appalled. Safe with anyone informal.": "Neutre, courant — une incrédulité entre amusement et effroi. Sans risque avec n'importe qui, en registre informel.",
  "Neutral, to whoever planned the route. 'Die Tour' is the casual word for a planned hike.": "Neutre, à celui qui a préparé l'itinéraire. 'Die Tour' est le mot décontracté pour une randonnée planifiée.",
  "oder so = or something / or whatever (casual suggestions)": "oder so = ou un truc comme ça (suggestions décontractées)",
  "Opinion": "Opinion",
  "Ordering food": "Commander à manger",
  "Plans": "Projets",
  "Platform warning before train doors close": "Avertissement sur le quai avant la fermeture des portes du train",
  "pleite — from bankruptcy, used casually. 'gerade' makes it temporary.": "pleite — venu de la faillite, employé familièrement. 'gerade' le rend temporaire.",
  "plural 'Jungs' = guys, lads (colloquial)": "pluriel 'Jungs' = les gars, les mecs (familier)",
  "polite check with friends before lighting up; expected around non-smokers": "petite vérification polie auprès des amis avant d'allumer une cigarette ; attendue en présence de non-fumeurs",
  "polite warning shot before or instead of details; 'heikel' = delicate/tricky": "coup de semonce poli avant ou à la place des détails ; 'heikel' = délicat, épineux",
  "polite-casual at the salon; was = etwas in spoken German": "poli et décontracté au salon ; was = etwas à l'oral en allemand",
  "Position callout": "Annonce de position",
  "Post-breakup confession to close friends; serious and vulnerable, no banter register.": "Confidence après une rupture, à des amis proches ; sérieuse et vulnérable, pas de registre badin.",
  "Reacting": "Réagir",
  "Reassuring": "Rassurer",
  "Relationship status": "Statut relationnel",
  "Reporting a problem": "Signaler un problème",
  "Request": "Demande",
  "resigned, informal; standard line among worried friends of a Schwurbler": "résigné, informel ; la réplique standard entre amis inquiets d'un Schwurbler",
  "resigned; extremely common among friends and family of someone who's gone down the hole": "résigné ; extrêmement courant chez les amis et la famille de quelqu'un qui a plongé",
  "Retail-investor bravado among friends; 'nachkaufen' = to buy more of what you already hold": "bravade de petit porteur entre amis ; 'nachkaufen' = racheter davantage de ce qu'on détient déjà",
  "Routine": "Routine",
  "Said while handing over the Mitbringsel at the door, informal.": "Dit en tendant le Mitbringsel sur le pas de la porte, informel.",
  "Scheduling": "Planification",
  "schlauchen — sapping your energy like a hose. Colloquial and exactly right.": "schlauchen — pomper l'énergie comme un tuyau. Familier et parfaitement juste.",
  "schreiben = to write / spell (informal)": "schreiben = écrire / orthographier (informel)",
  "Seasons": "Saisons",
  "self-deprecating joke; 'ich schwör' is casual spoken German": "blague d'autodérision ; 'ich schwör' est de l'allemand parlé décontracté",
  "sich etwas freihalten — keeping a day open. The advance reservation of friendship.": "sich etwas freihalten — se garder une journée libre. La réservation anticipée de l'amitié.",
  "sich hinlegen — putting yourself down. 'mal' makes it casual, not dramatic.": "sich hinlegen — s'allonger. 'mal' rend la chose décontractée, pas dramatique.",
  "Slang": "Argot",
  "Slang — the English loan stays English; ein deutsches Bad is a bathroom": "Argot — l'emprunt anglais reste anglais ; ein deutsches Bad est une salle de bains",
  "Slang (voll = really/very)": "Argot (voll = vraiment, très)",
  "Slang expression of enthusiasm": "Expression d'enthousiasme en argot",
  "spiegelglatt — mirror-smooth. The radio traffic warning word.": "spiegelglatt — lisse comme un miroir. Le mot d'avertissement de l'info-trafic à la radio.",
  "standard match-day question among friends, colleagues, in the Kneipe": "la question standard les jours de match, entre amis, collègues, au Kneipe",
  "Standard term in news and casual talk alike; can get heated between generations.": "Terme standard aussi bien dans l'info que dans la conversation décontractée ; peut s'échauffer entre générations.",
  "Standard third-person relationship analysis among friends; casual armchair-psychology weight.": "L'analyse de couple à la troisième personne entre amis ; psychologie de comptoir, ton décontracté.",
  "Status callout": "Annonce d'état",
  "Strong agreement": "Accord appuyé",
  "stronger and less casual than widerlich finden": "plus fort et moins décontracté que widerlich finden",
  "Surprise": "Surprise",
  "Symptom": "Symptôme",
  "talking about quitting with friends or partner": "parler d'arrêter, avec des amis ou son partenaire",
  "tanken — refuelling. Driving on the warning light is called auf Reserve fahren.": "tanken — faire le plein. Rouler avec le voyant allumé s'appelle auf Reserve fahren.",
  "Team play": "Jeu d'équipe",
  "Teasing between partners or friends; 'etwa' adds the playful gotcha tone.": "Taquinerie entre partenaires ou amis ; 'etwa' apporte le ton badin du je-t'y-prends.",
  "Telling time": "Dire l'heure",
  "Texting": "Textos",
  "The Anprobe-zu-Hause strategy: order both, keep one, return the other; casual du-register": "La stratégie Anprobe-zu-Hause : commander les deux, en garder un, renvoyer l'autre ; registre du, décontracté",
  "The casual imperative is 'Misch'; 'die Karten mischen' is the normal phrase for shuffling.": "L'impératif décontracté est 'Misch' ; 'die Karten mischen' est la tournure normale pour battre les cartes.",
  "The casual tier. Beste Grüße, Viele Grüße, VG: the ladder descends with familiarity.": "Le cran décontracté. Beste Grüße, Viele Grüße, VG : l'échelle descend à mesure qu'on se connaît.",
  "the casual word for Rad fahren": "le mot décontracté pour Rad fahren",
  "The classic couple question. 'Sich (Dativ) etwas holen' is the casual verb for getting a pet.": "La question classique du couple. 'Sich (Dativ) etwas holen' est le verbe décontracté pour prendre un animal.",
  "The default Grußformel — never wrong, never exciting. MfG in casual shorthand.": "La Grußformel par défaut — jamais fausse, jamais palpitante. En abrégé décontracté : MfG.",
  "The dramatic version for partners and close friends — du-form territory, carries real weight": "La version dramatique pour les partenaires et les amis proches — territoire du du, avec un vrai poids",
  "The embarrassment-avoidance rule. Half of all lost keys are in the other jacket.": "La règle anti-embarras. La moitié des clés perdues sont dans l'autre veste.",
  "The first question every friend asks. Casual, expected, and everyone wants the full story.": "La première question que pose chaque ami. Décontractée, attendue, et tout le monde veut toute l'histoire.",
  "The flare-up warning. Move it to the side; never pour water on.": "L'avertissement contre l'embrasement. Écartez-la ; ne jamais verser d'eau dessus.",
  "The German ID card — der Perso in casual speech.": "La carte d'identité allemande — der Perso à l'oral décontracté.",
  "THE gym-bro question; casual, between guys who lift": "LA question des habitués de la salle ; décontractée, entre gens qui soulèvent de la fonte",
  "The hike itself; casually also 'die Tour'.": "La randonnée elle-même ; de façon décontractée, aussi 'die Tour'.",
  "The honest cost warning. Under a hundred euros, most people simply pay.": "L'avertissement honnête sur le prix. En dessous de cent euros, la plupart des gens paient sans discuter.",
  "The honest warning, issued once and remembered forever by flatmates.": "L'avertissement honnête, prononcé une fois et retenu à jamais par les colocataires.",
  "The host's standard warm goodbye at the door, informal.": "Le au revoir chaleureux standard de l'hôte sur le pas de la porte, informel.",
  "the key de-escalation and warmth line in mixed-belief couples and friendships; sincere register": "la phrase clé pour désamorcer et réchauffer, dans les couples et amitiés aux croyances différentes ; registre sincère",
  "The late-summer warning. Cover your drink — the wasp finds it anyway.": "L'avertissement de fin d'été. Couvrez votre verre — la guêpe le trouvera quand même.",
  "the modern word for conspiracy-rambling; informal and very common now": "le mot moderne pour le délire complotiste ; informel et très courant aujourd'hui",
  "The most common casual check-in — short for Wie geht es?": "La prise de nouvelles décontractée la plus courante — abrégé de Wie geht es?",
  "The order that avoids regret. Half a percent matters less than one good extra.": "L'ordre qui évite les regrets. Un demi-point compte moins qu'une bonne option en plus.",
  "The permission that keeps friendships alive through a separation.": "La permission qui maintient les amitiés en vie à travers une séparation.",
  "The promise that keeps friendships": "La promesse qui préserve les amitiés",
  "The proud line — drop it casually among friends and watch the questions start.": "La phrase fière — glissez-la l'air de rien entre amis et regardez les questions arriver.",
  "The quiet ending of many friendships, described without accusation.": "La fin discrète de bien des amitiés, décrite sans reproche.",
  "The reciprocity ledger of friendship — informal, unwritten, never forgotten.": "Le grand livre de la réciprocité amicale — informel, non écrit, jamais oublié.",
  "The refusal that protects the friendship by naming the rule, not the person.": "Le refus qui protège l'amitié en nommant la règle plutôt que la personne.",
  "The sentence that softens hard truths between friends.": "La phrase qui adoucit les vérités dures entre amis.",
  "The sequence that avoids visible edges. Professionals call it 'vorschneiden'.": "La séquence qui évite les démarcations visibles. Les professionnels appellent cela 'vorschneiden'.",
  "The so makes the question casual — 'what do you do, generally?' The small-talk classic.": "Le so rend la question décontractée — 'tu fais quoi, en gros ?' Le classique du small talk.",
  "The solemn one — anniversaries, vows, letters. Partner only; too big for casual goodbyes.": "La formule solennelle — anniversaires, vœux, lettres. Réservée au partenaire ; trop grande pour un au revoir décontracté.",
  "The spoken du-command is 'Klick'; a more formal warning is 'Klicken Sie nicht auf den Link'.": "L'ordre oral en du est 'Klick' ; un avertissement plus formel serait 'Klicken Sie nicht auf den Link'.",
  "The standard closing courtesy among friends. Expected, and noticed if forgotten.": "La politesse de clôture standard entre amis. Attendue, et remarquée si on l'oublie.",
  "The standard sigh after any pay-rise or salary talk; casual, universal": "Le soupir standard après toute négociation ou augmentation de salaire ; décontracté, universel",
  "the standard verb; coden is its casual twin": "le verbe standard ; coden en est le jumeau décontracté",
  "The standard way to promise a return invitation at the door, informal.": "La façon standard de promettre une invitation en retour sur le pas de la porte, informel.",
  "the standard word; casually 'die Muckibude' or just 'das Gym'": "le mot standard ; de façon décontractée 'die Muckibude' ou simplement 'das Gym'",
  "The stylist asks this at the end; reinmachen is casual spoken German": "Le coiffeur pose cette question à la fin ; reinmachen est de l'allemand parlé décontracté",
  "the universal leg-day complaint; casual": "la plainte universelle du jour des jambes ; décontractée",
  "The warning against illegal puppy trade. Cheap, sick, and it funds more of it.": "L'avertissement contre le trafic illégal de chiots. Pas cher, malade, et cela finance la suite.",
  "The written warning from an employer or lawyer — one step before consequences.": "L'avertissement écrit d'un employeur ou d'un avocat — une étape avant les conséquences.",
  "Time comment": "Remarque sur l'heure",
  "To friends or your partner right after trying a new word. Invites a gentle correction.": "À des amis ou à son partenaire juste après avoir essayé un mot nouveau. Invite à une correction douce.",
  "Two words that stop a small hand. 'Vorsicht' works alone as a warning.": "Deux mots qui arrêtent une petite main. 'Vorsicht' fonctionne seul comme avertissement.",
  "Typical reply": "Réponse typique",
  "überweisen + dative person — sending money person-to-person. How friends settle up in Germany.": "überweisen + personne au datif — envoyer de l'argent de personne à personne. C'est ainsi que les amis règlent leurs comptes en Allemagne.",
  "um einen Gefallen bitten — the formal opening of informal help. Germans appreciate the framing.": "um einen Gefallen bitten — l'ouverture formelle d'une aide informelle. Les Allemands apprécient ce cadrage.",
  "Unlocks": "Déblocages",
  "Urgent": "Urgent",
  "Urgent warning": "Avertissement urgent",
  "verschreien — jinxing by saying. The warning shouted across German offices daily.": "verschreien — porter la poisse en le disant. L'avertissement crié chaque jour dans les bureaux allemands.",
  "verstoßen gegen + Akkusativ; mit etwas rechnen müssen is the standard warning of consequences.": "verstoßen gegen + accusatif ; mit etwas rechnen müssen est l'avertissement standard des conséquences.",
  "Very casual slang for friends": "Argot très décontracté pour parler d'amis",
  "very casual, said just before a penalty; 'der' instead of 'er' is typical fan speech": "très décontracté, dit juste avant un penalty ; 'der' au lieu de 'er' est typique du parler des supporters",
  "Very casual: 'ne' = 'eine', 'probier mal' softens it. With friends, not in writing.": "Très décontracté : 'ne' = 'eine', 'probier mal' adoucit. Entre amis, pas à l'écrit.",
  "Very common (informal alternative to 'Die Rechnung bitte')": "Très courant (alternative informelle à 'Die Rechnung bitte')",
  "Very common casual slang": "Argot décontracté très courant",
  "Very common colloquial verb for losing your temper": "Verbe familier très courant pour dire qu'on perd son sang-froid",
  "Very common colloquial; about losing your temper, not going crazy.": "Très courant en registre familier ; il s'agit de perdre son calme, pas de devenir fou.",
  "Very common leisure activity": "Loisir très courant",
  "Very common, casual — Bock = desire/appetite": "Très courant, décontracté — Bock = l'envie",
  "Very common, casual — literally 'that's sausage to me'": "Très courant, décontracté — littéralement 'ça m'est saucisse'",
  "Very common, direct — friends or real annoyance": "Très courant, direct — entre amis ou en cas d'agacement réel",
  "Vorsicht + statement — the standard kitchen warning shape.": "Vorsicht + phrase — la forme standard de l'avertissement en cuisine.",
  "Vulgar-casual: Willst du mich verarschen? = are you kidding me?": "Vulgaire-décontracté : Willst du mich verarschen? = tu te fous de moi ?",
  "Vulgar-ish (from Arsch = arse). Fine among friends, avoid with strangers or at work.": "Plutôt vulgaire (de Arsch, le cul). Ça passe entre amis, à éviter avec des inconnus ou au travail.",
  "Warm casual goodbye — informal (du), friends only": "Au revoir chaleureux et décontracté — informel (du), entre amis seulement",
  "warm compliment for partner or close friends; stronger than 'gut'": "compliment chaleureux pour un partenaire ou des amis proches ; plus fort que 'gut'",
  "Warm compliment, safe in any casual context.": "Compliment chaleureux, sans risque dans tout contexte décontracté.",
  "Warm door greeting to friends (ihr). One person: 'Komm rein!'; formal: 'Kommen Sie rein!'": "Accueil chaleureux à la porte pour des amis (ihr). Une seule personne : 'Komm rein!' ; formel : 'Kommen Sie rein!'",
  "Warm du-form for friends and family. Softer and more personal than the formal Beileid formulas.": "Forme en du, chaleureuse, pour les amis et la famille. Plus douce et plus personnelle que les formules de condoléances officielles.",
  "Warm goodbye — informal (du), friends only": "Au revoir chaleureux — informel (du), entre amis seulement",
  "Warning": "Avertissement",
  "Weather": "Météo",
  "What you ask the neighbours during an outage; weg sein = to be gone (very common colloquial)": "Ce qu'on demande aux voisins pendant une panne ; weg sein = être coupé (très courant en registre familier)",
  "Written German too": "Aussi à l'écrit",
  "zunächst and bislang bracket the timeline; es das geblieben — das stands for harmlos.": "zunächst et bislang encadrent la chronologie ; es das geblieben — das renvoie à harmlos.",
  "zurückzahlen — paying back. The clause that keeps the friendship intact.": "zurückzahlen — rembourser. La proposition qui laisse l'amitié intacte.",
};
