/**
 * The usage notes in German.
 *
 * Keyed by the English note exactly as the card carries it. A note missing
 * from here shows its English, so this file is filled in batches without any
 * card ever going blank — see usageNotes.ts for how it is loaded and why it
 * is not part of the interface tables.
 *
 * Fourteen thousand notes exist. This holds the ones translated so far, and
 * check-usage-notes prints how far along each language is on every build.
 */
export const USE_DE: Record<string, string> = {
  "'abschleppen' — to tow. Colloquially it also means pulling someone in a bar.": "'abschleppen' — wegschleppen. Umgangssprachlich heißt es auch, jemanden in einer Bar aufzureißen.",
  "'angesagt sein' — forecast, announced. Also slang for what's currently trendy.": "'angesagt sein' — vorhergesagt, angekündigt. Im Slang auch: gerade im Trend.",
  "'auf den Cent genau' is the fixed phrase — a virtue in a shop, a friendship-killer at a table. 'abrechnen' is the verb for settling up, and this is the polite way to call off over-precise splitting.": "'auf den Cent genau' ist die feste Wendung — im Laden eine Tugend, am Tisch ein Freundschaftskiller. 'abrechnen' ist das Verb fürs Begleichen einer Rechnung, und so sagt man höflich, dass man nicht centgenau teilen muss.",
  "'auf etwas stehen' — to be into something. Informal, current, and used constantly.": "'auf etwas stehen' — etwas mögen. Informell, aktuell und ständig im Gebrauch.",
  "'Auf etwas stehen' = to be into something. Informal fan talk; works for genres, bands, and people.": "'Auf etwas stehen' = etwas mögen. Informelles Fan-Gerede; passt für Genres, Bands und Menschen.",
  "'auf jemanden aufpassen' covers cats, kids and luggage alike. Plain present tense is how favours get asked between friends — no 'könntest du bitte' needed.": "'auf jemanden aufpassen' gilt für Katzen, Kinder und Gepäck gleichermaßen. Im schlichten Präsens bittet man unter Freunden um Gefallen — kein 'könntest du bitte' nötig.",
  "'aufgewacht sein' as conspiracist self-description; comprehension only — hearing this is a warning sign": "'aufgewacht sein' als Selbstbeschreibung von Verschwörungsgläubigen; nur zum Verstehen — wer das sagt, ist ein Warnzeichen",
  "'bedeuten' for meaning. 'Was heißt das?' is the more casual version and just as correct.": "'bedeuten' für die Bedeutung. 'Was heißt das?' ist die lockerere Fassung und genauso richtig.",
  "'bei jemandem was offen haben' = to have something outstanding with someone — friendly and vague, so you avoid the heavy word 'Schulden'. Works in both directions: 'Du hast noch was bei mir offen.'": "'bei jemandem was offen haben' = bei jemandem etwas offenstehen haben — freundlich und vage, damit man das schwere Wort 'Schulden' vermeidet. Funktioniert in beide Richtungen: 'Du hast noch was bei mir offen.'",
  "'Bei uns' = in my country/family. 'Riesenthema' (giant topic) is casual and vivid — good for explaining your own culture.": "'Bei uns' = in meinem Land oder meiner Familie. 'Riesenthema' ist locker und anschaulich — gut, um die eigene Kultur zu erklären.",
  "'blank sein' = to have literally nothing left — a notch below 'pleite' and very casual. Friends and family only; never to a colleague or a landlord.": "'blank sein' = buchstäblich nichts mehr haben — eine Stufe unter 'pleite' und sehr locker. Nur bei Freunden und Familie; nie gegenüber Kollegen oder Vermietern.",
  "'borgen' — to lend informally between friends; 'leihen' works too. The dative person comes first: borgst du MIR.": "'borgen' — unter Freunden informell leihen; 'leihen' geht auch. Die Person im Dativ kommt zuerst: borgst du MIR.",
  "'Das Match' — loan for a full competitive game; 'ist Schluss' = are we done. Casual.": "'Das Match' — Lehnwort für ein ganzes Wettkampfspiel; 'ist Schluss' = ist Feierabend. Locker.",
  "'davon' avoids repeating the product name after pointing or asking a question about it.": "'davon' erspart es, den Produktnamen zu wiederholen, nachdem man darauf gezeigt oder danach gefragt hat.",
  "'davon' refers to an amount of the thing already being discussed and avoids repeating its name.": "'davon' bezieht sich auf eine Menge der schon besprochenen Sache und erspart die Wiederholung des Namens.",
  "'Der Hammer' = the standard casual superlative for events. Informal, all ages under about 50.": "'Der Hammer' = der übliche lockere Superlativ für Ereignisse. Informell, alle Altersgruppen unter etwa 50.",
  "'Der Ping' — English loan, no alternative. 'übel' is youth slang for 'terrible'.": "'Der Ping' — englisches Lehnwort ohne Alternative. 'übel' ist Jugendslang für 'schrecklich'.",
  "'dir' means you are choosing it for yourself; 'Such was aus' also works. 'aus' moves to the end. This is the warm, informal way to offer someone a choice.": "'dir' heißt, dass du für dich selbst wählst; 'Such was aus' geht auch. 'aus' rutscht ans Ende. So bietet man jemandem warm und informell eine Wahl an.",
  "'doch mal' turns the instruction into a casual suggestion. 'anrufen' splits around the person being called.": "'doch mal' macht aus der Anweisung einen lockeren Vorschlag. 'anrufen' trennt sich um die angerufene Person herum.",
  "'doppelt' — double. 'Menge' is a quantity, and colloquially 'a lot'.": "'doppelt' — zweifach. 'Menge' ist eine Quantität und umgangssprachlich 'viel'.",
  "'dran sein' — to be next in turn. Compact, informal and used constantly.": "'dran sein' — als Nächster an der Reihe sein. Knapp, informell und ständig im Gebrauch.",
  "'dran' (= daran) is the ultra-casual kitchen way to say 'onto it'; how home cooks actually talk, never written in recipes.": "'dran' (= daran) ist die ganz lockere Küchenform für 'daran'; so reden Hobbyköche wirklich, in Rezepten steht es nie.",
  "'draufschauen' — to look at it. Colloquial and separable.": "'draufschauen' — einen Blick darauf werfen. Umgangssprachlich und trennbar.",
  "'drücken' is the everyday word for hugging — warmer and more casual than 'umarmen'. Also in goodbyes and texts: 'Ich drück dich!' = hugs!": "'drücken' ist das Alltagswort fürs Umarmen — wärmer und lockerer als 'umarmen'. Auch beim Abschied und in Nachrichten: 'Ich drück dich!'",
  "'Du hast einen guten Musikgeschmack' is a real compliment between friends or on a date.": "'Du hast einen guten Musikgeschmack' ist ein echtes Kompliment unter Freunden oder beim Date.",
  "'durch sein' — colloquially done for: soaked, worn out, finished.": "'durch sein' — umgangssprachlich erledigt: durchnässt, abgenutzt, am Ende.",
  "'duzen' — to address someone as du. THE sentence for crossing from formal to informal. Traditionally the older person or the senior one offers it.": "'duzen' — jemanden mit du ansprechen. DER Satz für den Wechsel vom Sie zum Du. Traditionell bietet ihn die ältere oder ranghöhere Person an.",
  "'eigentlich' — the casual opener for a serious adult conversation.": "'eigentlich' — der lockere Einstieg in ein ernstes Gespräch unter Erwachsenen.",
  "'ein schlechtes Gewissen haben' = to feel guilty. The second cancellation needs this sentence; the third needs it plus a concrete new date attached, or the friendship quietly cools.": "'ein schlechtes Gewissen haben' = sich schuldig fühlen. Bei der zweiten Absage braucht es diesen Satz; bei der dritten dazu einen konkreten neuen Termin, sonst kühlt die Freundschaft still ab.",
  "'einschlafen' means to fall asleep, but about a habit, a group chat or a friendship it means it quietly died — no decision, no announcement. The gentlest way to admit you stopped going.": "'einschlafen' heißt eigentlich in den Schlaf fallen, bei einer Gewohnheit, einem Gruppenchat oder einer Freundschaft aber: sie ist still eingegangen — ohne Entscheidung, ohne Ankündigung. Die sanfteste Art zuzugeben, dass man nicht mehr hingeht.",
  "'Elfer' is the casual clip everyone uses in speech": "'Elfer' ist die lockere Kurzform, die alle sprechen",
  "'Er ist trocken' is THE standard, respectful phrase for a recovering alcoholic who no longer drinks — not slang, not euphemism.": "'Er ist trocken' ist DIE übliche, respektvolle Wendung für einen trockenen Alkoholiker, der nicht mehr trinkt — kein Slang, kein Beschönigen.",
  "'etwas aufrechnen' = to offset one thing against another, and between friends it's an accusation. This is the German way of saying the friendship is worth more than the four euros.": "'etwas aufrechnen' = eines gegen das andere verrechnen, und unter Freunden ist das ein Vorwurf. So sagt man auf Deutsch, dass die Freundschaft mehr wert ist als die vier Euro.",
  "'ewig' — eternally, used casually for 'ages'. 'laden' for loading.": "'ewig' — für immer, locker gebraucht für 'ewig lange'. 'laden' fürs Laden.",
  "'fertig sein' about a person means finished in the sense of nothing left in the tank. Blunt but affectionate between friends and flatmates — say it to your boss and it's simply an insult.": "'fertig sein' über eine Person heißt: der Tank ist leer. Direkt, aber liebevoll unter Freunden und Mitbewohnern — dem Chef gesagt ist es schlicht eine Beleidigung.",
  "'fies' is the mean-spirited one — sharper than 'gemein' and very spoken. Between friends it's often half-admiring after a brutal joke; said flat, with no smile, it's completely serious.": "'fies' ist das gehässige Wort — schärfer als 'gemein' und sehr gesprochen. Unter Freunden klingt es nach einem brutalen Witz oft halb bewundernd; tonlos und ohne Lächeln gesagt, ist es völlig ernst.",
  "'frei Schnauze' — literally free snout: no recipe, pure instinct. Wonderfully casual.": "'frei Schnauze' — wörtlich freie Schnauze: kein Rezept, reines Gefühl. Herrlich locker.",
  "'für Samstag' — booked for a day. A Transporter needs no lorry licence, which is why friends get asked.": "'für Samstag' — für einen Tag gebucht. Für einen Transporter braucht man keinen Lkw-Führerschein, deshalb fragt man Freunde.",
  "'gar nicht erst' — not even starting. Avoiding the problem entirely.": "'gar nicht erst' — erst gar nicht anfangen. Das Problem ganz vermeiden.",
  "'glatt' — slippery with ice. The winter warning Germans text each other.": "'glatt' — vereist und rutschig. Die Winterwarnung, die Deutsche einander schreiben.",
  "'gläubig' — devout. Said plainly, this ends no friendships in Germany.": "'gläubig' — fromm. Nüchtern gesagt beendet das in Deutschland keine Freundschaft.",
  "'gucken' is the casual everyday verb (north/central); the south says 'schauen'": "'gucken' ist das lockere Alltagsverb (Norden/Mitte); der Süden sagt 'schauen'",
  "'Hä?' — bafflement, rising tone. Rude to teachers, standard between friends. 'Sinn ergeben' — to make sense.": "'Hä?' — Verblüffung, steigender Ton. Gegenüber Lehrern unhöflich, unter Freunden normal. 'Sinn ergeben' — einleuchten.",
  "'halbe-halbe' is common informal German for dividing something into two equal parts.": "'halbe-halbe' ist geläufiges informelles Deutsch dafür, etwas in zwei gleiche Teile zu teilen.",
  "'hinkriegen' — to manage or pull something off. Informal, warm and extremely common.": "'hinkriegen' — etwas schaffen oder hinbekommen. Informell, warm und äußerst geläufig.",
  "'Ich meinte damit, dass ...' states the intended meaning directly and avoids an unnecessarily heavy sentence frame.": "'Ich meinte damit, dass ...' nennt die gemeinte Bedeutung direkt und vermeidet einen unnötig schwerfälligen Satzbau.",
  "'in einfach' is colloquial and slightly jokey — asking for simpler words, not slower speech. Germans find it charming from a learner; 'Leichte Sprache' even exists as an official concept.": "'in einfach' ist umgangssprachlich und leicht scherzhaft — man bittet um einfachere Wörter, nicht um langsameres Sprechen. Von Lernenden finden Deutsche das charmant; 'Leichte Sprache' gibt es sogar als amtliches Konzept.",
  "'jeder zahlt seins' — the German default among friends. No awkwardness; it's the system.": "'jeder zahlt seins' — der deutsche Normalfall unter Freunden. Nichts Peinliches daran; so läuft es.",
  "'jemandem etwas abkaufen' = to buy someone's story. Warm rather than confrontational between close friends, because it proves you've been paying attention — but presumptuous to an acquaintance.": "'jemandem etwas abkaufen' = jemandem die Geschichte glauben. Unter engen Freunden eher warm als konfrontativ, weil es zeigt, dass man aufgepasst hat — bei Bekannten aber anmaßend.",
  "'jemanden anstecken' = to pass your bug on. 'bloß' in a command is the urgent flavour — said with an arm held out, it's half genuine warning, half joke.": "'jemanden anstecken' = jemanden mit seinem Infekt anstecken. 'bloß' im Befehl gibt die dringliche Note — mit ausgestrecktem Arm gesagt ist es halb echte Warnung, halb Scherz.",
  "'jemanden unter Druck setzen' is the standard phrase for creating pressure; urgency is a common warning sign.": "'jemanden unter Druck setzen' ist die übliche Wendung dafür, Druck aufzubauen; Eile ist ein häufiges Warnzeichen.",
  "'jemanden vollquatschen' = to talk at someone non-stop. The standard climbdown once the rant runs out of steam. Casual, friends only.": "'jemanden vollquatschen' = jemanden ohne Pause zutexten. Der übliche Rückzug, wenn der Redeschwall verebbt. Locker, nur unter Freunden.",
  "'jemanden von der Seite anmachen' = to start on someone unprovoked, on the street or on the train. Street-level slang, not office German.": "'jemanden von der Seite anmachen' = jemanden grundlos anpöbeln, auf der Straße oder in der Bahn. Straßenslang, kein Bürodeutsch.",
  "'Jetzt reicht's' is the short version, and the last warning before a row.": "'Jetzt reicht's' ist die Kurzfassung — und die letzte Warnung vor dem Streit.",
  "'Keep your ears stiff' — parting encouragement to someone facing a hard stretch. Warm, informal, and said at doors.": "'Halt die Ohren steif' — Ermutigung zum Abschied, wenn jemandem eine harte Zeit bevorsteht. Herzlich, informell, an der Tür gesagt.",
  "'kein ... mehr' means there is none left. 'Klopapier' is the ordinary informal word used at home.": "'kein ... mehr' heißt, dass nichts übrig ist. 'Klopapier' ist das gewöhnliche informelle Wort zu Hause.",
  "'Kein Thema' — not a topic: it doesn't even need discussing. Friendship in two words.": "'Kein Thema' — wörtlich kein Gesprächsgegenstand: darüber muss man gar nicht reden. Freundschaft in zwei Wörtern.",
  "'knapp' covers anything in short supply — time, money, a train connection. Here it's the warning shot before you either turn up breathless or cancel.": "'knapp' passt auf alles, was fehlt — Zeit, Geld, ein Zuganschluss. Hier ist es der Warnschuss, bevor man entweder atemlos ankommt oder absagt.",
  "'Land unter' comes from coastal flood warnings and means properly overwhelmed. Casual — for colleagues, not for clients.": "'Land unter' stammt aus Sturmflutwarnungen an der Küste und heißt richtig überfordert. Locker — für Kollegen, nicht für Kunden.",
  "'laufen' is the verb for films showing — 'Der läuft noch' = it's still on. The 'denn ... so' pair turns it into a casual browse instead of a demand.": "'laufen' ist das Verb für Filme im Programm — 'Der läuft noch' = er ist noch im Kino. Das Paar 'denn ... so' macht daraus ein lockeres Stöbern statt einer Forderung.",
  "'mal' makes the command sound casual; use 'in die Ecke' when directing light into it.": "'mal' lässt die Aufforderung locker klingen; 'in die Ecke' nimmt man, wenn man Licht hineinlenkt.",
  "'mal' softens the imperative into a casual request; masculine object is 'deinen Benutzernamen'.": "'mal' macht aus dem Imperativ eine lockere Bitte; das maskuline Objekt heißt 'deinen Benutzernamen'.",
  "'mal' turns an offer into something casual. Two seconds, no commitment.": "'mal' macht aus dem Angebot etwas Lockeres. Zwei Sekunden, keine Verpflichtung.",
  "'Man sieht sich' — literally one sees oneself — is the standard casual sign-off when no date is fixed.": "'Man sieht sich' — wörtlich man sieht sich — ist der übliche lockere Abschied, wenn kein Termin feststeht.",
  "'mitnehmen' is separable; in the informal imperative, 'mit' lands at the end.": "'mitnehmen' ist trennbar; im informellen Imperativ landet 'mit' am Ende.",
  "'Nie im Leben' = never in a million years; 'legit' is borrowed straight from English gaming slang. The standard disbelief formula.": "'Nie im Leben' = niemals im Leben; 'legit' ist direkt aus dem englischen Gaming-Slang entlehnt. Die übliche Formel für Unglauben.",
  "'Pass auf!' is the fastest warning; separable 'aufpassen' becomes 'pass ... auf'.": "'Pass auf!' ist die schnellste Warnung; das trennbare 'aufpassen' wird zu 'pass ... auf'.",
  "'rauf und runter' = over and over — how Germans confess an obsession with a song or a show ('Die Serie hab ich rauf und runter geguckt'). Casual, affectionate, no negative edge at all.": "'rauf und runter' = immer wieder — so gestehen Deutsche eine Obsession für ein Lied oder eine Serie ('Die Serie hab ich rauf und runter geguckt'). Locker, liebevoll, ohne jeden negativen Beiklang.",
  "'rausfliegen' — from the fuse pack, here about a back. Colloquial and instantly understood.": "'rausfliegen' — aus dem Sicherungs-Paket, hier über einen Rücken. Umgangssprachlich und sofort verstanden.",
  "'rumhängen' (from 'herumhängen') = to hang about doing nothing. Casual and slightly teenage — perfect between friends and partners, odd in front of your boss.": "'rumhängen' (von 'herumhängen') = untätig herumsitzen. Locker und leicht jugendlich — perfekt unter Freunden und Partnern, vor dem Chef seltsam.",
  "'schauen' or 'gucken' — gucken is more casual. No preposition before the platform.": "'schauen' oder 'gucken' — gucken ist lockerer. Vor der Plattform steht keine Präposition.",
  "'schlapp' (colloquial) = run-down, drained; 'kaum' = barely.": "'schlapp' (umgangssprachlich) = kraftlos, ausgelaugt; 'kaum' = fast gar nicht.",
  "'schwurbeln' is the current word for conspiracy-rambling; informal, everywhere since the pandemic": "'schwurbeln' ist das aktuelle Wort fürs Verschwörungsgeschwurbel; informell, seit der Pandemie überall",
  "'sich aufs Ohr hauen' — literally to throw yourself onto your ear. Casual and a bit blokey, for friends and flatmates; 'ein Nickerchen machen' is the neutral way to describe the same twenty minutes.": "'sich aufs Ohr hauen' — wörtlich sich aufs Ohr werfen. Locker und ein bisschen kumpelhaft, für Freunde und Mitbewohner; 'ein Nickerchen machen' beschreibt dieselben zwanzig Minuten neutral.",
  "'Sich ein Haustier anschaffen' = to get a pet. Affectionate casual slang: 'das Fellbaby' (fur baby).": "'Sich ein Haustier anschaffen' = sich ein Haustier zulegen. Liebevoller lockerer Slang: 'das Fellbaby'.",
  "'sich etwas kaputt machen' = to wreck a body part — casual, slightly dramatic, used for backs and knees above all. 'Unkraut jäten' = to weed.": "'sich etwas kaputt machen' = sich ein Körperteil ruinieren — locker, leicht dramatisch, vor allem für Rücken und Knie. 'Unkraut jäten' = Unkraut entfernen.",
  "'Sich etwas ziehen' = to download, distinctly casual register; the standard buddy advice before a risky purchase.": "'Sich etwas ziehen' = herunterladen, deutlich lockeres Register; der übliche Kumpel-Rat vor einem riskanten Kauf.",
  "'sich etwas ziehen' is slang for downloading; more neutral: 'runterladen' or the loan verb 'downloaden' — all three are common.": "'sich etwas ziehen' ist Slang fürs Herunterladen; neutraler: 'runterladen' oder das Lehnverb 'downloaden' — alle drei sind geläufig.",
  "'sich irren' — the dignified admission, equally at home in a meeting and in the kitchen. Blunter and more colloquial: 'Ich lag komplett falsch.' Never 'Ich war falsch' — that isn't German.": "'sich irren' — das würdevolle Eingeständnis, in der Besprechung wie in der Küche zu Hause. Direkter und umgangssprachlicher: 'Ich lag komplett falsch.' Niemals 'Ich war falsch' — das ist kein Deutsch.",
  "'sich reinsteigern' = to spiral into something; informal, the natural way to describe the rabbit-hole process": "'sich reinsteigern' = sich in etwas hineinsteigern; informell, die natürliche Art, den Abwärtssog zu beschreiben",
  "'sicherheitshalber' explains that you are checking to avoid an unnecessary mistake.": "'sicherheitshalber' erklärt, dass man nachschaut, um einen unnötigen Fehler zu vermeiden.",
  "'spinnen' — literally to spin — is the everyday verb for being crazy. Between friends it is affectionate; at a stranger it is an insult.": "'spinnen' — wörtlich Garn spinnen — ist das Alltagsverb für Verrücktsein. Unter Freunden liebevoll; einem Fremden gegenüber eine Beleidigung.",
  "'sportlich' — sporty, and also 'smart-casual' about clothes. Both are common.": "'sportlich' — sportlich, bei Kleidung auch leger-elegant. Beides ist geläufig.",
  "'Strafzettel' — penalty slip. Also 'Knöllchen' colloquially, which sounds far too sweet for what it is.": "'Strafzettel' — der Zettel mit der Strafe. Umgangssprachlich auch 'Knöllchen', was viel zu niedlich klingt.",
  "'total' as an intensifier is thoroughly spoken German and slightly informal.": "'total' als Verstärker ist durch und durch gesprochenes Deutsch und leicht informell.",
  "'unbedingt' + colloquial 'was' (for etwas) = maximum urgency, zero formality. Best-friend register; the standard wind-up before gossip.": "'unbedingt' + umgangssprachliches 'was' (für etwas) = höchste Dringlichkeit, null Förmlichkeit. Register der besten Freunde; der übliche Anlauf vor dem Tratsch.",
  "'unterschiedlich' — differing. Germans use it constantly to avoid overgeneralising.": "'unterschiedlich' — verschieden. Deutsche gebrauchen es ständig, um nicht zu verallgemeinern.",
  "'Voll der/die X' is casual youth-speak amplification; pure banter register among friends and in voice chat.": "'Voll der/die X' ist lockere Jugendsprache zur Verstärkung; reines Spaßregister unter Freunden und im Voicechat.",
  "'voll' is THE everyday intensifier under about 40 — voll gut, voll nervig, voll teuer. Casual but harmless; drop it for the grown-up version: 'Das ist ziemlich langweilig.'": "'voll' ist DER Alltagsverstärker unter etwa 40 — voll gut, voll nervig, voll teuer. Locker, aber harmlos; für die erwachsene Fassung lässt man es weg: 'Das ist ziemlich langweilig.'",
  "'was trinken gehen' — the standard invitation. Casual, open-ended, no commitment implied.": "'was trinken gehen' — die Standardeinladung. Locker, offen, ohne jede Verpflichtung.",
  "'wegmachen' colloquially for putting something aside. 'mal' softens the announcement.": "'wegmachen' umgangssprachlich dafür, etwas wegzuräumen. 'mal' macht die Ankündigung weicher.",
  "'Wie hoch' for amounts of money. A completely normal question between German friends.": "'Wie hoch' für Geldbeträge. Eine völlig normale Frage unter deutschen Freunden.",
  "'wieder drauf haben' — colloquial and compact. Bike chains come off constantly.": "'wieder drauf haben' — umgangssprachlich und knapp. Fahrradketten springen ständig ab.",
  "'Wofür' is the normal neutral form; 'für was' is regional or very casual.": "'Wofür' ist die normale neutrale Form; 'für was' ist regional oder sehr locker.",
  "'Zeit mitbringen' — the honest warning. Open hours mean open-ended waiting.": "'Zeit mitbringen' — die ehrliche Warnung. Offene Sprechzeiten bedeuten offenes Warten.",
  "'zurückrufen' is separable: ich rufe dich zurück. 'mitten in was' (= in etwas) is casual spoken German; at work the same excuse is 'Ich bin gerade in einem Termin.'": "'zurückrufen' ist trennbar: ich rufe dich zurück. 'mitten in was' (= in etwas) ist lockeres gesprochenes Deutsch; im Job lautet dieselbe Ausrede 'Ich bin gerade in einem Termin.'",
  "'Zuschlagen' = to strike when a deal appears — THE verb for sale purchases, gaming or otherwise. Casual bragging register.": "'Zuschlagen' = zugreifen, wenn ein Angebot auftaucht — DAS Verb für Schnäppchenkäufe, ob beim Gaming oder sonstwo. Lockeres Angeberregister.",
  "\"Kiste\" is a crate or box, and colloquially any old thing. Say this before you sign for anything that looks tampered with.": "'Kiste' ist ein Behälter aus Holz oder Pappe und umgangssprachlich irgendein Ding. Sag das, bevor du etwas quittierst, das aufgebrochen aussieht.",
  "18+ conversational — the standard casual way to ask about turn-ons ('stehen auf + Akk'). Between partners or in open flirting, never at work.": "Gespräch ab 18 — die übliche lockere Art, nach Vorlieben zu fragen ('stehen auf + Akkusativ'). Unter Partnern oder beim offenen Flirt, nie bei der Arbeit.",
  "A broad casual check-in about life, work or whatever is currently going on. The situation decides how wide the answer should be.": "Eine weite, lockere Nachfrage zu Leben, Arbeit oder was gerade ansteht. Die Situation entscheidet, wie ausführlich die Antwort ausfällt.",
  "A broad casual question about someone's work, studies or life. It usually asks more than what they are doing this exact second.": "Eine weite, lockere Frage nach Arbeit, Studium oder Leben. Sie zielt meist auf mehr als das, was jemand in dieser Sekunde tut.",
  "A broad catch-up question about someone's current life. 'zurzeit' means these days or at present, and 'so' keeps the question casual.": "Eine weite Frage zum aktuellen Leben. 'zurzeit' heißt derzeit, und 'so' hält die Frage locker.",
  "A casual event or venue question. 'mit wem' asks which person or group someone came with or is spending time with.": "Eine lockere Frage auf einer Veranstaltung oder in einem Lokal. 'mit wem' fragt, mit welcher Person oder Gruppe jemand da ist oder Zeit verbringt.",
  "A casual first-meeting question about whether someone comes from the local area. It is less broad than asking which country or city they come from.": "Eine lockere Frage beim ersten Treffen, ob jemand aus der Gegend kommt. Sie ist enger gefasst als die Frage nach Land oder Stadt.",
  "A casual purpose question when someone has an object, tool, file or unusual plan.": "Eine lockere Frage nach dem Zweck, wenn jemand einen Gegenstand, ein Werkzeug, eine Datei oder einen ungewöhnlichen Plan hat.",
  "A casual question about an object when you do not know or do not need its exact name. 'Ding' is everyday but vague.": "Eine lockere Frage nach einem Gegenstand, wenn man den genauen Namen nicht kennt oder nicht braucht. 'Ding' ist alltäglich, aber vage.",
  "A colloquial fixed expression. It is not sexual in this use.": "Eine feste umgangssprachliche Wendung. In dieser Verwendung nicht sexuell gemeint.",
  "A common getting-to-know-you question when either work or study could fit. Avoid it if the setting makes the answer obvious.": "Eine geläufige Kennenlernfrage, wenn Arbeit oder Studium beide passen könnten. Lass sie weg, wenn die Situation die Antwort ohnehin verrät.",
  "A common informal reassurance. It literally mentions your head, but the meaning is not to worry.": "Eine geläufige informelle Beruhigung. Wörtlich ist vom Kopf die Rede, gemeint ist: mach dir keine Sorgen.",
  "A common informal response to disappointing news or an annoying problem.": "Eine geläufige informelle Reaktion auf enttäuschende Nachrichten oder ein ärgerliches Problem.",
  "A common shortened suggestion to avoid deciding too early. A complete version is 'Warten wir erst mal ab'.": "Ein geläufiger Kurzvorschlag, um nicht zu früh zu entscheiden. Vollständig heißt es 'Warten wir erst mal ab'.",
  "A common use of sammeln among friends, at work or in a family.": "Eine geläufige Verwendung von sammeln unter Freunden, bei der Arbeit oder in der Familie.",
  "A considerate response to bad news when a casual reaction would feel too light.": "Eine rücksichtsvolle Antwort auf schlechte Nachrichten, wenn eine lockere Reaktion zu leicht wirken würde.",
  "A direct informal question about ability. English keeps the main verb in its plain form after 'can': 'Can you do...?', never 'Can you to do...?'.": "Eine direkte informelle Frage nach dem Können. Im Englischen bleibt das Hauptverb nach 'can' in der Grundform: 'Can you do...?', nie 'Can you to do...?'.",
  "A direct warning that a condition or necessary step cannot be skipped.": "Eine deutliche Warnung, dass eine Bedingung oder ein nötiger Schritt nicht übersprungen werden kann.",
  "A natural follow-up after meeting two friends. 'seid ihr' addresses both people together.": "Eine natürliche Anschlussfrage, wenn man zwei Freunde trifft. 'seid ihr' spricht beide zusammen an.",
  "A natural urgent warning. German can use this short phrase without a verb when the danger is obvious.": "Eine natürliche dringende Warnung. Das Deutsche kommt bei offensichtlicher Gefahr ohne Verb aus.",
  "A natural warning to an animal gulping food. The situation supplies the missing verb, so German keeps it short.": "Eine natürliche Warnung an ein Tier, das sein Futter hinunterschlingt. Die Situation liefert das fehlende Verb, deshalb bleibt das Deutsche kurz.",
  "A normal informal request for a very short wait. Add 'bitte' when you want it to sound softer.": "Eine normale informelle Bitte um ganz kurzes Warten. Mit 'bitte' klingt sie weicher.",
  "A practical check that helps the group avoid stopping again once the task has begun.": "Eine praktische Rückfrage, damit die Gruppe nicht noch einmal anhalten muss, wenn es losgegangen ist.",
  "A safety warning in frost, snow or freezing rain. 'glatt' does not always mean icy, so slippery is the broad translation.": "Eine Sicherheitswarnung bei Frost, Schnee oder Eisregen. 'glatt' heißt nicht immer vereist, deshalb ist rutschig die weite Übersetzung.",
  "A serious accusation, not casual criticism.": "Ein schwerer Vorwurf, keine beiläufige Kritik.",
  "A shade more emotional than 'keine Lust' — this is about your state, not the activity. Warning: between partners at night it means exactly what it means in English.": "Eine Spur emotionaler als 'keine Lust' — hier geht es um deinen Zustand, nicht um die Tätigkeit. Achtung: unter Partnern am Abend heißt es genau das, was es im Englischen heißt.",
  "A short warning after treatment or when a pet worries a sore spot. The object is obvious, so German leaves it out.": "Eine kurze Warnung nach einer Behandlung oder wenn ein Tier an einer wunden Stelle herumknabbert. Das Objekt ist offensichtlich, deshalb lässt das Deutsche es weg.",
  "A shortened vulgar dismissal. It can be joking only between very close friends with the right tone; otherwise it is an insult.": "Eine verkürzte derbe Abfuhr. Als Scherz geht sie nur unter sehr engen Freunden im richtigen Ton; sonst ist es eine Beleidigung.",
  "A standard informal request. The favour itself normally follows immediately.": "Eine übliche informelle Bitte. Der eigentliche Gefallen folgt normalerweise sofort.",
  "A standard Monday small-talk question with friends, classmates and colleagues you know.": "Die übliche Montags-Small-Talk-Frage unter Freunden, Mitschülern und bekannten Kollegen.",
  "A standing offer between partners or close friends; warm, no drama.": "Ein Angebot, das immer gilt — unter Partnern oder engen Freunden; warm, ohne Drama.",
  "A very common casual follow-up when the first topic is finished and you want the conversation to continue.": "Eine sehr geläufige lockere Anschlussfrage, wenn das erste Thema erledigt ist und das Gespräch weitergehen soll.",
  "A very common informal way to check whether a day suits someone.": "Eine sehr geläufige informelle Art zu fragen, ob ein Tag jemandem passt.",
  "abgefahren — driven off, worn. Also slang for 'amazing'; the tyre meaning is older.": "abgefahren — abgenutzt, heruntergefahren. Im Slang auch 'irre gut'; die Reifenbedeutung ist älter.",
  "Achtung! is the warning word; die Ampel = the traffic light, always feminine.": "Achtung! ist das Warnwort; die Ampel = die Verkehrsampel, immer feminin.",
  "Affectionate or dry, harmless — literally 'fun bird'. Said fondly, or deadpan when the joke was bad. Safe with anyone informal.": "Liebevoll oder trocken, harmlos — wörtlich 'Spaßvogel'. Herzlich gesagt oder tonlos, wenn der Witz schlecht war. Bei jedem informellen Gegenüber unbedenklich.",
  "Affectionate teasing, harmless — partner, kids, close friends. Almost never stings; it implies fond exasperation, not stupidity.": "Liebevolle Neckerei, harmlos — Partner, Kinder, enge Freunde. Es trifft fast nie; es meint zärtliche Entnervtheit, nicht Dummheit.",
  "Affectionate, harmless — for someone talking nonsense or clowning around. Partner, friends, kids. Warm, never a real insult.": "Liebevoll, harmlos — für jemanden, der Unsinn redet oder herumalbert. Partner, Freunde, Kinder. Warm, nie eine echte Beleidigung.",
  "Afterwards": "Danach",
  "Agreeing": "Zustimmen",
  "Allotment neighbours — advisors, rivals and friends across one fence. Mostly all three.": "Nachbarn in der Kleingartenanlage — Ratgeber, Rivalen und Freunde über einen Zaun hinweg. Meist alles drei.",
  "Almost always plural; singular das Beziehungsproblem. Neutral, the word you use confiding in friends.": "Fast immer im Plural; Singular das Beziehungsproblem. Neutral, das Wort, mit dem man sich Freunden anvertraut.",
  "also colloquially \"incredibly\": unwahrscheinlich gut": "umgangssprachlich auch 'unglaublich': unwahrscheinlich gut",
  "also colloquially \"massively\": tierisch gut": "umgangssprachlich auch 'enorm': tierisch gut",
  "always plural": "immer Plural",
  "Among friends, immediately after the news. 'Mal' softens it into eager excitement, not a command.": "Unter Freunden, sofort nach der Nachricht. 'Mal' macht daraus gespannte Vorfreude statt eines Befehls.",
  "An informal reaction to a plan failing, something breaking or another everyday setback.": "Eine informelle Reaktion darauf, dass ein Plan scheitert, etwas kaputtgeht oder der Alltag dazwischenkommt.",
  "Anglicism, under-40 casual; scrollen is fully naturalized for everyone, doomscrollen still youth-flavoured": "Anglizismus, locker unter 40; scrollen ist bei allen voll eingebürgert, doomscrollen klingt noch jugendlich",
  "ANGRY — the final rung before consequences, and everyone hears it that way. Adults use it on each other too, where it lands as a real threat rather than a warning.": "WÜTEND — die letzte Stufe vor den Konsequenzen, und so hört es auch jeder. Erwachsene sagen es auch zueinander, wo es eher als echte Drohung ankommt denn als Warnung.",
  "Ask two or more people for the story of how they first met. It can be about friends, a couple or colleagues.": "Frag zwei oder mehr Leute nach der Geschichte ihres ersten Kennenlernens. Es kann um Freunde, ein Paar oder Kollegen gehen.",
  "Asking for the bill": "Nach der Rechnung fragen",
  "At the table, informal. One guest: 'Greif zu!' Signals the eating may begin.": "Am Tisch, informell. Bei einem Gast: 'Greif zu!' Es signalisiert, dass gegessen werden darf.",
  "At the till": "An der Kasse",
  "aufblasen — inflating. 'Hilf mir mal' — the casual recruiting of bystanders.": "aufblasen — aufpumpen. 'Hilf mir mal' — das lockere Einspannen von Umstehenden.",
  "aufdrängen — pressing something on someone. The warning before every market stroll.": "aufdrängen — jemandem etwas aufnötigen. Die Warnung vor jedem Marktbummel.",
  "aufziehen — a storm pulling up. denn delivers the warning in plain word order.": "aufziehen — ein Gewitter zieht herauf. denn bringt die Warnung in schlichter Wortstellung.",
  "Aus der Kirche austreten = to formally leave the church. Casually, mal austreten = to nip to the loo.": "Aus der Kirche austreten = die Mitgliedschaft in der Kirche förmlich beenden. Locker heißt mal austreten: kurz aufs Klo gehen.",
  "auslaufen — leaking out. 'hinüber sein' — colloquially beyond saving.": "auslaufen — herauslaufen. 'hinüber sein' — umgangssprachlich nicht mehr zu retten.",
  "ausstrecken splits in the imperative; mal softens the order to a casual prompt. German uses die, not 'your', with body parts.": "ausstrecken trennt sich im Imperativ; mal macht aus dem Befehl eine lockere Aufforderung. Bei Körperteilen nimmt das Deutsche die, nicht 'deine'.",
  "Banter": "Geplänkel",
  "beim Umzug = with the move. Moving house with friends (and pizza afterwards) is completely standard in Germany.": "beim Umzug = beim Wohnungswechsel. Mit Freunden umzuziehen (und danach Pizza) ist in Deutschland völlig üblich.",
  "beraten — advising. 'einen' — the colloquial accusative of man.": "beraten — Rat geben. 'einen' — der umgangssprachliche Akkusativ von man.",
  "Between friends: Kannst du mir zehn Euro borgen? Standard German prefers leihen.": "Unter Freunden: Kannst du mir zehn Euro borgen? Das Standarddeutsch bevorzugt leihen.",
  "Blunt but completely normal between partners and friends — German directness in action": "Direkt, aber unter Partnern und Freunden völlig normal — deutsche Direktheit in Aktion",
  "Blunt but standard dismissal of a politician. Strong opinion, casual delivery — fine between partners and friends. '...von ihr' for her.": "Direkt, aber die übliche Abfuhr für einen Politiker. Starke Meinung, lockerer Ton — unter Partnern und Freunden okay. '...von ihr' für sie.",
  "Blunt insult, literally a full fencepost. Friends-only register.": "Derbe Beleidigung, wörtlich ein ganzer Zaunpfosten. Nur unter Freunden.",
  "Blunt self-criticism that admits your behaviour was bad. It can sound sincere among friends, but use a cleaner apology at work.": "Direkte Selbstkritik, die einräumt, dass das eigene Verhalten schlecht war. Unter Freunden kann sie aufrichtig klingen, bei der Arbeit nimm eine sauberere Entschuldigung.",
  "borgen — the casual borrow-lend verb. die Leiter migrates between households like a shared pet.": "borgen — das lockere Verb fürs Leihen. Die Leiter wandert zwischen Haushalten wie ein geteiltes Haustier.",
  "Both a literal on-set announcement and a warning that everything from now on is Content; läuft = runs, the standard verb for recording devices.": "Zugleich die wörtliche Ansage am Set und die Warnung, dass ab jetzt alles Content ist; läuft = ist in Betrieb, das übliche Verb für Aufnahmegeräte.",
  "bumming a cigarette; casual, smoker-to-smoker only": "eine Zigarette schnorren; locker, nur von Raucher zu Raucher",
  "Buying time": "Zeit gewinnen",
  "Careful — between two people who might be dating, this IS the small confession, one step below 'Ich hab dich lieb'. Between friends it's plain and warm. Tone and timing carry the whole meaning.": "Vorsicht — zwischen zwei Menschen, die sich vielleicht daten, IST das das kleine Geständnis, eine Stufe unter 'Ich hab dich lieb'. Unter Freunden ist es schlicht und warm. Ton und Zeitpunkt tragen die ganze Bedeutung.",
  "Casual": "Locker",
  "Casual — and ambiguous by design: 'zocken' means both gambling and video gaming. Among under-40s the default reading is gaming; in a casino context it's gambling.": "Locker — und mit Absicht doppeldeutig: 'zocken' heißt sowohl glücksspielen als auch Videospiele spielen. Unter 40 versteht man standardmäßig das Zocken am Bildschirm; im Casino ist es Glücksspiel.",
  "Casual — Ding literally means 'thing'": "Locker — Ding heißt wörtlich 'Sache'",
  "Casual — literally 'now we have the salad'": "Locker — wörtlich 'jetzt haben wir den Salat'",
  "Casual — literally 'that's not my beer'": "Locker — wörtlich 'das ist nicht mein Bier'",
  "Casual — literally 'you had pig'": "Locker — wörtlich 'du hast Schwein gehabt'",
  "Casual agreement": "Lockere Zustimmung",
  "Casual and dramatic; often frustration rather than literal loss of control.": "Locker und dramatisch; meist Frust statt echtem Kontrollverlust.",
  "casual between friends; the English loans (Foundation, Concealer) are standard in German — French keeps 'fond de teint'": "locker unter Freunden; die englischen Lehnwörter (Foundation, Concealer) sind im Deutschen Standard — das Französische behält 'fond de teint'",
  "Casual check-in mid-explanation.": "Lockere Rückfrage mitten in einer Erklärung.",
  "casual clipping of 'Prominenter' — everyday word": "lockere Kurzform von 'Prominenter' — Alltagswort",
  "Casual complaint, one hour in. Someone packed too much Brotzeit.": "Lockere Beschwerde nach einer Stunde. Jemand hat zu viel Brotzeit eingepackt.",
  "casual compliment; stehen + dative = to suit someone": "lockeres Kompliment; stehen + Dativ = jemandem gut zu Gesicht stehen",
  "Casual criticism, mild to sharp depending on tone — from amused head-shake about a friend to genuine warning about a date.": "Lockere Kritik, je nach Ton mild bis scharf — vom amüsierten Kopfschütteln über einen Freund bis zur ernsten Warnung vor einem Date.",
  "Casual date invite (better than formal 'Möchten Sie...')": "Lockere Verabredung (besser als das förmliche 'Möchten Sie...')",
  "Casual dating vocabulary with friends. The verb is fully germanized: ghosten, geghostet.": "Lockerer Dating-Wortschatz unter Freunden. Das Verb ist voll eingedeutscht: ghosten, geghostet.",
  "Casual dating-discourse talk, mostly among friends dissecting someone's behaviour. Anglicism, feminine in German: die Red Flag (French keeps it masculine: un red flag).": "Lockeres Dating-Gerede, meist unter Freunden, die jemandes Verhalten sezieren. Anglizismus, im Deutschen feminin: die Red Flag (im Französischen bleibt es maskulin: un red flag).",
  "casual Denglisch — 'Ich hab gecodet' is completely normal among devs": "lockeres Denglisch — 'Ich hab gecodet' ist unter Entwicklern völlig normal",
  "Casual directive": "Lockere Aufforderung",
  "Casual everyday goodbye — used everywhere in Germany": "Lockerer Alltagsabschied — überall in Deutschland üblich",
  "Casual everyday reassurance": "Lockere Beruhigung im Alltag",
  "Casual favour between friends (du). 'drüberschauen' = give it a quick once-over.": "Lockerer Gefallen unter Freunden (du). 'drüberschauen' = kurz drüberlesen.",
  "Casual for playing video games; in money contexts it means to gamble.": "Locker fürs Computerspielen; beim Geld heißt es glücksspielen.",
  "Casual goodbye — borrowed from Italian, extremely popular in Germany": "Lockerer Abschied — aus dem Italienischen entlehnt, in Deutschland sehr beliebt",
  "casual gym slang for lifting weights; 'pumpen gehen'": "lockerer Gym-Slang fürs Gewichtheben; 'pumpen gehen'",
  "Casual idiom, literally 'sponge over it' (wiping the slate): declares a small quarrel officially closed. Friends and partners, minor stuff only — don't 'Schwamm drüber' a real hurt.": "Lockere Redewendung, wörtlich 'Schwamm drüber' (den Schwamm über die Tafel ziehen): erklärt einen kleinen Streit für offiziell beendet. Freunde und Partner, nur bei Kleinigkeiten — über eine echte Verletzung wischt man nicht.",
  "Casual imperative 'Investier' is common spoken German; full written form is 'Investiere'.": "Der lockere Imperativ 'Investier' ist geläufiges gesprochenes Deutsch; die volle Schriftform lautet 'Investiere'.",
  "Casual imperative 'Markier' is common in voice chat; after 'damit', 'verlaufen' goes to the end.": "Der lockere Imperativ 'Markier' ist im Voicechat geläufig; nach 'damit' rutscht 'verlaufen' ans Ende.",
  "Casual imperative 'Setz' is short for 'Setze'; 'am' contracts dative 'an dem'.": "Der lockere Imperativ 'Setz' ist die Kurzform von 'Setze'; 'am' zieht den Dativ 'an dem' zusammen.",
  "Casual imperative of separable 'hinzufügen' is 'Füg ... hinzu'; the person being added is accusative 'mich'.": "Der lockere Imperativ des trennbaren 'hinzufügen' lautet 'Füg ... hinzu'; die hinzugefügte Person steht im Akkusativ: 'mich'.",
  "Casual invite": "Lockere Einladung",
  "Casual kitchen-table economics; sich lohnen = to be worth it — very high-frequency verb": "Lockere Küchentisch-Ökonomie; sich lohnen = sich rentieren — ein sehr häufiges Verb",
  "casual loanword; einkaufen is the German verb": "lockeres Lehnwort; einkaufen ist das deutsche Verb",
  "Casual media criticism among friends; sich aufregen über = to get worked up about — essential B1 verb": "Lockere Medienkritik unter Freunden; sich aufregen über = sich über etwas ereifern — ein unverzichtbares B1-Verb",
  "casual money-vent to friends, du-register — the one informal line in this pack; the bank formally calls it 'Dispositionskredit'": "lockeres Geldgejammer unter Freunden, Du-Register — die eine informelle Zeile in diesem Paket; die Bank nennt es förmlich 'Dispositionskredit'",
  "Casual opener": "Lockerer Gesprächseinstieg",
  "Casual opener for close friends": "Lockerer Einstieg unter engen Freunden",
  "Casual opinion": "Lockere Meinungsäußerung",
  "Casual pointing-at-things question with friends — how learners actually acquire everyday nouns. 'das Ding' = thingy.": "Lockere Zeigefrage unter Freunden — so eignen sich Lernende Alltagswörter wirklich an. 'das Ding' = Dingsda.",
  "Casual positive update": "Lockere gute Nachricht zwischendurch",
  "Casual pub folklore — 'angeblich' (supposedly) does the honest work here. It's a myth: the Konterbier only postpones the hangover, and needing one regularly is a recognised warning sign.": "Lockere Kneipenfolklore — 'angeblich' leistet hier die ehrliche Arbeit. Es ist ein Mythos: Das Konterbier verschiebt den Kater nur, und wer regelmäßig eins braucht, hat ein anerkanntes Warnzeichen.",
  "Casual register inside student life; durcharbeiten = work through without a break.": "Lockeres Register aus dem Studentenleben; durcharbeiten = ohne Unterbrechung weiterarbeiten.",
  "Casual reminiscing; 'was los sein' = something happening.": "Lockeres Schwelgen in Erinnerungen; 'was los sein' = es ist etwas los.",
  "Casual reply": "Lockere Antwort",
  "Casual request": "Lockere Bitte",
  "Casual request to repeat": "Lockere Bitte um Wiederholung",
  "Casual self-intro": "Lockere Vorstellung der eigenen Person",
  "Casual slang command": "Lockere Slang-Aufforderung",
  "Casual slang farewell": "Lockerer Slang-Abschied",
  "Casual speech drops the prefix: you 'schieben' a plan with a friend, you 'verschieben' a Termin with a doctor or a client. 'auf' + accusative for the new date.": "In lockerer Rede fällt die Vorsilbe weg: einen Plan mit einem Freund 'schiebt' man, einen Termin beim Arzt oder Kunden 'verschiebt' man. 'auf' + Akkusativ für den neuen Termin.",
  "Casual spoken imperative 'Markier' is common; the tool follows dative 'mit einem Bleistift'.": "Der lockere gesprochene Imperativ 'Markier' ist geläufig; das Werkzeug folgt im Dativ 'mit einem Bleistift'.",
  "Casual spoken; 'ich wechsel' instead of textbook 'ich wechsle' is normal in speech. 'Die Klasse' is standard, no English loan here.": "Locker gesprochen; 'ich wechsel' statt des Lehrbuch-'ich wechsle' ist in der Rede normal. 'Die Klasse' ist Standard, hier kein englisches Lehnwort.",
  "casual spoken; from sich fertig machen = sich zurechtmachen": "lockere gesprochene Sprache; von sich fertig machen = sich zurechtmachen",
  "casual spoken; the machen-lassen pattern for anything done at a salon": "lockere gesprochene Sprache; das machen-lassen-Muster für alles, was im Salon gemacht wird",
  "casual, admiring; 'definiert' = lean and cut, more technical": "locker und bewundernd; 'definiert' = schlank und muskulös, eher fachlich",
  "Casual, concerned — 'die Spielothek' (slot arcade) sits several rungs below 'das Casino' in register and respectability; the sentence itself signals worry.": "Locker und besorgt — 'die Spielothek' (Spielhalle) steht in Register und Ansehen mehrere Stufen unter 'das Casino'; der Satz selbst signalisiert Sorge.",
  "Casual, enthusiastic. 'Der Wahnsinn' is the go-to superlative among friends.": "Locker und begeistert. 'Der Wahnsinn' ist der Standard-Superlativ unter Freunden.",
  "casual, everyday; der Lidstrich is the German word, Eyeliner is what people say": "locker, alltäglich; der Lidstrich ist das deutsche Wort, Eyeliner sagen die Leute",
  "Casual, exasperated. Standard lakeside-evening lament; 'fressen' (animal eating) makes it vivid.": "Locker und entnervt. Die übliche Klage am Seeufer am Abend; 'fressen' (Tiere fressen) macht es anschaulich.",
  "Casual, mild — amused disbelief among friends and family. Friendly in tone, but too blunt for strangers or superiors.": "Locker, mild — amüsierter Unglaube unter Freunden und Familie. Freundlich im Ton, aber zu direkt für Fremde oder Vorgesetzte.",
  "Casual, mild — the adjective version, interchangeable with 'einen Kater haben'. Fine in any informal setting.": "Locker, mild — die Adjektivfassung, austauschbar mit 'einen Kater haben'. In jedem informellen Rahmen okay.",
  "Casual, mild — the standard morning-after sentence among friends and relaxed colleagues. 'fett' intensifies it.": "Locker, mild — der übliche Satz am Morgen danach unter Freunden und entspannten Kollegen. 'fett' verstärkt ihn.",
  "Casual, mild — the standard verdict on a Flachwitz. Said with a groan and half a smile; friends and colleagues.": "Locker, mild — das übliche Urteil über einen Flachwitz. Mit einem Stöhnen und einem halben Lächeln gesagt; Freunde und Kollegen.",
  "Casual, playful — everyday micro-betting between friends. 'die Wette' = the bet; the structure was immortalized by the TV show 'Wetten, dass..?'.": "Locker, verspielt — die alltägliche kleine Wette unter Freunden. 'die Wette' = der Einsatz auf einen Ausgang; die Struktur hat die Fernsehshow 'Wetten, dass..?' unsterblich gemacht.",
  "Casual, relieved-triumphant, to friends. 'überstehen' = to survive something unpleasant.": "Locker, erleichtert-triumphierend, unter Freunden. 'überstehen' = etwas Unangenehmes durchstehen.",
  "Casual, relieved. 'Kriegen' is the everyday spoken 'bekommen'. Rare Bahn stories have happy endings — savour them.": "Locker, erleichtert. 'Kriegen' ist das alltägliche gesprochene 'bekommen'. Selten gehen Bahngeschichten gut aus — genieß sie.",
  "Casual, teasing — literally 'do you have tomatoes on your eyes?'": "Locker und neckend — wörtlich 'hast du Tomaten auf den Augen?'",
  "Casual, to companions. Famous last words on any hike.": "Locker, an die Begleitung. Berühmte letzte Worte auf jeder Wanderung.",
  "Casual, to friends/partner. 'An den See fahren' is the German summer ritual — pack the Picknick.": "Locker, an Freunde oder den Partner. 'An den See fahren' ist das deutsche Sommerritual — pack das Picknick ein.",
  "Casual, to one person (du) — group: Lasst uns anfangen; formal: Fangen wir an": "Locker, an eine Person (du) — Gruppe: Lasst uns anfangen; förmlich: Fangen wir an",
  "Casual, universal. The standard excuse to step outside — nobody questions frische Luft.": "Locker, überall verständlich. Die Standardausrede, um nach draußen zu gehen — frische Luft hinterfragt niemand.",
  "Casual, wry — literally 'life is no pony farm'": "Locker und trocken — wörtlich 'das Leben ist kein Ponyhof'",
  "casual, younger speakers; Hautpflege is the more formal word": "locker, eher jüngere Sprecher; Hautpflege ist das förmlichere Wort",
  "Casual; 'die Pause' is the break, 'der Pausenhof' the yard it happens on.": "Locker; 'die Pause' ist die Unterbrechung, 'der Pausenhof' der Hof, auf dem sie stattfindet.",
  "casual; 'platt' = wiped out, works for any exhaustion": "locker; 'platt' = völlig fertig, passt für jede Erschöpfung",
  "casual; 'Proteinshake' works too": "locker; 'Proteinshake' geht auch",
  "casual; 'pumpen gehen' marks you as a weights person, not a treadmill person": "locker; 'pumpen gehen' weist dich als Hantel-Typ aus, nicht als Laufband-Typ",
  "casual; 'sich etwas ziehen' = to pull a muscle": "locker; 'sich etwas ziehen' = sich einen Muskel zerren",
  "Casual; ackern makes the work sound tiring or relentless.": "Locker; ackern lässt die Arbeit anstrengend und unerbittlich klingen.",
  "Casual; adults admit it with a grin": "Locker; Erwachsene geben es grinsend zu",
  "casual; literally also to plough a field": "locker; wörtlich auch einen Acker pflügen",
  "casual; stechen lassen (literally 'have it pricked') is the idiomatic verb for tattoos": "locker; stechen lassen — wörtlich mit der Nadel stechen lassen — ist das idiomatische Verb für Tattoos",
  "casual; the question everyone asks": "locker; die Frage, die alle stellen",
  "casual; the standard (optimistic) answer": "locker; die übliche (optimistische) Antwort",
  "Casual; the way adults confess it with a grin.": "Locker; so gestehen Erwachsene es grinsend.",
  "casual: kicken gehen = to go and play football": "locker: kicken gehen = Fußball spielen gehen",
  "Casual. 'Baden gehen' = swim outdoors (lake, sea); 'schwimmen gehen' leans towards the pool.": "Locker. 'Baden gehen' = draußen schwimmen (See, Meer); 'schwimmen gehen' zielt eher aufs Schwimmbad.",
  "Casual. 'Eine Runde drehen' = do a loop; works for walks, bike rides or a quick drive.": "Locker. 'Eine Runde drehen' = eine Runde machen; passt für Spaziergänge, Radtouren oder eine kurze Fahrt.",
  "Casual. 'Sich etwas holen' = to catch/get something (sunburn, a cold).": "Locker. 'Sich etwas holen' = sich etwas zuziehen (Sonnenbrand, Erkältung).",
  "casually clipped to 'der Elfer'": "umgangssprachlich verkürzt zu 'der Elfer'",
  "Chores": "Hausarbeit",
  "close friends only — sharing a cigarette or vape": "nur unter engen Freunden — eine Zigarette oder Vape teilen",
  "Coarse — stronger than 'das ist mir egal'. Friends only; rude if said to a teacher, boss, or official.": "Derb — stärker als 'das ist mir egal'. Nur unter Freunden; gegenüber Lehrern, Chefs oder Beamten unhöflich.",
  "Coarse and common among friends. It can sound confrontational when said angrily.": "Derb und unter Freunden geläufig. Wütend gesagt kann es konfrontativ klingen.",
  "Coarse-casual — 'forget it, who cares'. Banter-safe among friends; not for formal company.": "Derb-locker — 'vergiss es, wen kümmert's'. Unter Freunden als Spaß okay; nicht in förmlicher Runde.",
  "coden is casual Denglisch; completely normal in the du-form dev crowd.": "coden ist lockeres Denglisch; in der Du-Entwicklerszene völlig normal.",
  "Colloquial (Kopfnuss = headbutt/noogie)": "Umgangssprachlich (Kopfnuss = Stoß mit dem Kopf bzw. Klaps auf den Kopf)",
  "Colloquial and strong; covers verbal and psychological cruelty, not just physical.": "Umgangssprachlich und heftig; meint verbale und seelische Grausamkeit, nicht nur körperliche.",
  "Colloquial and strong; verbal or psychological cruelty": "Umgangssprachlich und heftig; verbale oder seelische Grausamkeit",
  "colloquial and very common; 'Funkstille' is the go-to image for a communication freeze in families": "umgangssprachlich und sehr geläufig; 'Funkstille' ist das Standardbild für abgebrochene Kommunikation in Familien",
  "colloquial anglicism (Duden-listed); marketing and social media register": "umgangssprachlicher Anglizismus (im Duden verzeichnet); Register aus Marketing und sozialen Medien",
  "Colloquial but harmless — safe with colleagues and family.": "Umgangssprachlich, aber harmlos — bei Kollegen und Familie unbedenklich.",
  "Colloquial but harmless — the polite cousin of 'verarschen'. Safe with colleagues, in-laws, anyone informal.": "Umgangssprachlich, aber harmlos — der höfliche Verwandte von 'verarschen'. Bei Kollegen, Schwiegereltern, allen informell unbedenklich.",
  "Colloquial but serious; 'zu dritt' = three of them together.": "Umgangssprachlich, aber ernst; 'zu dritt' = drei zusammen.",
  "Colloquial combo of Ja + Nein": "Umgangssprachliche Mischung aus Ja + Nein",
  "Colloquial fixed expression meaning that someone loses their nerve or retreats. It is not sexual in this use.": "Feste umgangssprachliche Wendung dafür, dass jemand den Mut verliert oder einen Rückzieher macht. In dieser Verwendung nicht sexuell gemeint.",
  "Colloquial idiom, mild — groaning at a joke everyone has heard a hundred times. Friends and casual colleagues.": "Umgangssprachliche Redewendung, mild — das Stöhnen über einen Witz, den alle schon hundertmal gehört haben. Freunde und lockere Kollegen.",
  "colloquial intensifier: mächtig stolz = mighty proud": "umgangssprachlicher Verstärker: mächtig stolz = sehr stolz",
  "Colloquial short form of herauskommen; also used of films, products or models being released.": "Umgangssprachliche Kurzform von herauskommen; auch für Filme, Produkte oder Modelle, die erscheinen.",
  "Colloquial shortcut": "Umgangssprachliche Kurzform",
  "Colloquial, mild — casual settings with friends, family, relaxed colleagues. Often typed in chats too.": "Umgangssprachlich, mild — lockere Runden mit Freunden, Familie, entspannten Kollegen. Wird auch oft in Chats getippt.",
  "Colloquial, mild — gasped mid-laughter or typed in chats. Friends, family, relaxed colleagues.": "Umgangssprachlich, mild — mitten im Lachen hervorgestoßen oder in den Chat getippt. Freunde, Familie, entspannte Kollegen.",
  "colloquial, what children do in sand; graben is neutral": "umgangssprachlich, was Kinder im Sand tun; graben ist neutral",
  "Colloquial; 'sich prügeln' is physical, much stronger than 'sich streiten'.": "Umgangssprachlich; 'sich prügeln' ist körperlich und viel stärker als 'sich streiten'.",
  "colloquial; invariable: ein super Film": "umgangssprachlich; unveränderlich: ein super Film",
  "colloquially also snappy, punchy (UI, prose, deadlines)": "umgangssprachlich auch knackig, prägnant (Oberflächen, Texte, Fristen)",
  "colloquially shortened to 'das Gespräch'": "umgangssprachlich verkürzt zu 'das Gespräch'",
  "Colloquially, Der Hammer! means amazing or awesome — the literal tool is the primary card meaning.": "Umgangssprachlich heißt Der Hammer! so viel wie großartig — die eigentliche Kartenbedeutung ist das Werkzeug.",
  "common and informal; can describe a person, idea or situation": "geläufig und informell; kann eine Person, eine Idee oder eine Situation beschreiben",
  "Common complaint": "Häufige Beschwerde",
  "Common slang reaction": "Häufige Slang-Reaktion",
  "Common slang reaction to bad news — mies = lousy, shabby": "Häufige Slang-Reaktion auf schlechte Nachrichten — mies = übel, schäbig",
  "Confirming": "Bestätigen",
  "Consent": "Einverständnis",
  "Consent — always check": "Einverständnis — immer nachfragen",
  "Conversational geopolitics with an opinion baked in — fine among friends, spicier at work": "Geopolitik im Gespräch, mit eingebauter Meinung — unter Freunden okay, bei der Arbeit heikler",
  "dark humour among friends; 'Echsenmenschen' is the go-to absurd-conspiracy reference": "schwarzer Humor unter Freunden; 'Echsenmenschen' ist der Standardverweis auf absurde Verschwörungen",
  "das Band — the conveyor. Braking on it is the one real mistake to avoid.": "das Band — das Förderband. Darauf zu bremsen ist der eine Fehler, den man vermeiden sollte.",
  "das Bügeleisen — the iron. The warning every household repeats.": "das Bügeleisen — das Gerät zum Bügeln. Die Warnung, die in jedem Haushalt fällt.",
  "das Halbjahreszeugnis — the February report. The early warning system.": "das Halbjahreszeugnis — das Zeugnis im Februar. Das Frühwarnsystem.",
  "Das hängt davon ab = it depends. Casually, mit Freunden abhängen = to hang out.": "Das hängt davon ab = es kommt darauf an. Locker heißt mit Freunden abhängen: mit Freunden rumhängen.",
  "das Profil — the tread. 'ist runter' — worn away; casual passive Germany runs on.": "das Profil — das Reifenprofil. 'ist runter' — abgefahren; das lockere Passiv, mit dem Deutschland fährt.",
  "das Rücklicht — the rear light. 'nur noch schwach' — the warning phase before darkness.": "das Rücklicht — die hintere Leuchte. 'nur noch schwach' — die Warnphase vor der Dunkelheit.",
  "das Spritgeld — the fuel share. Simple beats fair-to-the-cent; friendships prefer round numbers.": "das Spritgeld — der Benzinanteil. Einfach schlägt centgenau; Freundschaften mögen runde Zahlen.",
  "das Teil — the casual word for any piece of clothing. The rule that prevents the pink wash.": "das Teil — das lockere Wort für jedes Kleidungsstück. Die Regel, die die rosa Wäsche verhindert.",
  "das Wartezimmer — from the doctor pack, considerably louder. Cats sit high; dogs make friends.": "das Wartezimmer — aus dem Arzt-Paket, deutlich lauter. Katzen sitzen oben; Hunde schließen Freundschaften.",
  "Dating": "Dating",
  "Deadpan sarcasm, mild — the everyday ironic groan at bad news. Universal: friends, family, muttered at work.": "Trockener Sarkasmus, mild — das alltägliche ironische Stöhnen über schlechte Nachrichten. Überall: Freunde, Familie, bei der Arbeit gemurmelt.",
  "Deliberately vague — it lets both sides keep it casual. 'was' here is short for 'etwas'.": "Bewusst vage — beide Seiten können es locker halten. 'was' steht hier kurz für 'etwas'.",
  "Denglish gym slang, completely standard between lifters; more formal: 'Kannst du mir Hilfestellung geben?'": "Denglischer Gym-Slang, unter Kraftsportlern völlig üblich; förmlicher: 'Kannst du mir Hilfestellung geben?'",
  "der Aszendent — the follow-up question that separates casual from committed.": "der Aszendent — die Nachfrage, die Gelegenheitsinteresse von echtem Ernst trennt.",
  "der Helferkreis — the informal volunteer group, common in refugee and neighbourhood support.": "der Helferkreis — die informelle Freiwilligengruppe, verbreitet in der Flüchtlings- und Nachbarschaftshilfe.",
  "der Platten — the flat tyre, colloquial and universal. The commute's classic opening line.": "der Platten — der platte Reifen, umgangssprachlich und überall verstanden. Der Klassiker als Einstieg auf dem Arbeitsweg.",
  "der Strafzettel, colloquially das Knöllchen = parking ticket": "der Strafzettel, umgangssprachlich das Knöllchen = Strafzettel fürs Parken",
  "Desire": "Wunsch",
  "die Abmahnung — the warning shot, at work or over copyright. Serious, not final.": "die Abmahnung — der Warnschuss, im Job oder beim Urheberrecht. Ernst, aber nicht endgültig.",
  "die Abmahnung — the written warning. Serious, but far from a dismissal.": "die Abmahnung — die schriftliche Verwarnung. Ernst, aber weit entfernt von einer Kündigung.",
  "die Hausnummer — colloquial for a rough figure. More with a role change.": "die Hausnummer — umgangssprachlich für einen ungefähren Betrag. Mehr, wenn sich die Rolle ändert.",
  "die Jugendfeuerwehr — where most volunteers begin. Knots, hoses and friendships.": "die Jugendfeuerwehr — wo die meisten Freiwilligen anfangen. Knoten, Schläuche und Freundschaften.",
  "die Kantine — the subsidised lunch. The invitation that builds actual friendships.": "die Kantine — das bezuschusste Mittagessen. Die Einladung, aus der echte Freundschaften werden.",
  "die Lawine — the avalanche. The warning is not decorative.": "die Lawine — der Schneeabgang. Die Warnung ist keine Zierde.",
  "Direct and neutral: 'Ich bin schwanger.' Colloquially, 'schwanger von ihm' names the father.": "Direkt und neutral: 'Ich bin schwanger.' Umgangssprachlich nennt 'schwanger von ihm' den Vater.",
  "drohen with a thing as subject = to loom/threaten to occur: Dehydrierung droht. sonst carries the warning.": "drohen mit einer Sache als Subjekt = bevorstehen: Dehydrierung droht. sonst trägt die Warnung.",
  "du-form for friends and partners. With strangers or officials: 'Können Sie das bitte wiederholen?'": "Du-Form für Freunde und Partner. Bei Fremden oder Behörden: 'Können Sie das bitte wiederholen?'",
  "düngen = to fertilize; der Dünger = fertilizer. Du register — said between family/friends": "düngen = Nährstoffe ausbringen; der Dünger = das Düngemittel. Du-Register — unter Familie und Freunden gesagt",
  "eh = anyway / in any case (colloquial 'ohnehin')": "eh = sowieso / in jedem Fall (umgangssprachlich für 'ohnehin')",
  "eine Runde schmeißen — literally throwing a round. Casual, generous, slightly theatrical.": "eine Runde schmeißen — wörtlich eine Runde werfen. Locker, großzügig, ein bisschen theatralisch.",
  "Emergency": "Notfall",
  "Emphasis": "Betonung",
  "Emphatic casual yes": "Nachdrückliches, lockeres Ja",
  "Encouragement between friends or from a partner — the compliment learners most want to hear.": "Ermutigung unter Freunden oder vom Partner — das Kompliment, das Lernende am liebsten hören.",
  "Enemy info": "Gegnerinfo",
  "English loan, fully naturalized and plural; 'doch' makes it dismissive — casual register": "englisches Lehnwort, voll eingebürgert und im Plural; 'doch' macht es abwertend — lockeres Register",
  "Enthusiastic yes": "Begeistertes Ja",
  "Essential": "Unverzichtbar",
  "everyday casual word; also means the stubbed-out butt": "lockeres Alltagswort; bedeutet auch den ausgedrückten Stummel",
  "Everyday colloquial spelling of nichts": "Alltägliche umgangssprachliche Schreibweise von nichts",
  "Everyday connection method (slang 'schreib mir')": "Alltäglicher Weg, in Kontakt zu bleiben (Slang 'schreib mir')",
  "Everyday criticism, medium weight; fine in casual talk about colleagues or exes.": "Alltagskritik von mittlerem Gewicht; im lockeren Gespräch über Kollegen oder Ex-Partner in Ordnung.",
  "Everyday office and friend request; rüberschicken (send over) is the casual variant.": "Alltagsbitte im Büro und unter Freunden; rüberschicken ist die lockere Variante.",
  "Everyday slang (Bock haben)": "Alltagsslang (Bock haben)",
  "Everyday slang (spendieren = to treat)": "Alltäglicher Slang (spendieren = einladen, ausgeben)",
  "Excited announcement to friends and family. Once the context is clear, everyone just says 'Gespräch'.": "Aufgeregte Ankündigung an Freunde und Familie. Sobald der Zusammenhang klar ist, sagen alle nur noch 'Gespräch'.",
  "Extremely common in speech as a hedge: Das ist quasi dasselbe. Latin by origin, fully casual in use.": "Äußerst geläufig in der gesprochenen Sprache als Abschwächung: Das ist quasi dasselbe. Lateinischen Ursprungs, im Gebrauch völlig locker.",
  "Facharzt = specialist; colloquially also \"einen Termin ausmachen\"": "Facharzt = Spezialist; umgangssprachlich auch 'einen Termin ausmachen'",
  "Falschparken = illegal/incorrect parking": "Falschparken = verbotenes oder falsches Parken",
  "Family": "Familie",
  "Famous last words — friends will quote it back at you for months.": "Berühmte letzte Worte — Freunde zitieren dich damit noch monatelang.",
  "Farewell": "Abschied",
  "Feeling": "Gefühl",
  "feiern = to celebrate, colloquially 'to love something'; very current usage.": "feiern = ein Fest begehen, umgangssprachlich auch 'etwas großartig finden'; sehr aktueller Gebrauch.",
  "fett = huge (colloquial intensifier); standard dev talk, not rude.": "fett = riesig (umgangssprachlicher Verstärker); normaler Entwickler-Jargon, nicht unhöflich.",
  "Finding help": "Hilfe finden",
  "firm but civil pushback; the 'doch längst' signals mild exasperation — fine with family, friends, colleagues": "bestimmter, aber höflicher Widerspruch; das 'doch längst' zeigt leichte Entnervtheit — bei Familie, Freunden, Kollegen okay",
  "Fixed casual set expression; already short, so no further clipping.": "Feste, lockere Wendung; schon kurz, also keine weitere Verkürzung.",
  "flach and steil around dahinter — the swimming-pool warning as a geometry lesson.": "flach und steil rund um dahinter — die Schwimmbadwarnung als Geometriestunde.",
  "Flight status update": "Flugstatus",
  "Flirting": "Flirten",
  "Formal": "Förmlich",
  "Frustrated, to friends. 'schon wieder' carries the job-hunt fatigue.": "Frustriert, unter Freunden. 'schon wieder' trägt den Frust der Jobsuche.",
  "geblitzt werden = to get caught by a speed camera — the standard colloquial verb for it": "geblitzt werden = von einem Blitzer erwischt werden — das übliche umgangssprachliche Verb dafür",
  "Gen-Z": "Gen Z",
  "Genuine compliment between friends; on a date it's practically flirting.": "Echtes Kompliment unter Freunden; beim Date ist es praktisch Flirten.",
  "gereizt — irritable, like a nerve already touched. Fair warning to the room.": "gereizt — reizbar, wie ein schon berührter Nerv. Eine faire Warnung an alle im Raum.",
  "gib — du-imperative of geben with vowel change; mal keeps it casual, not bossy.": "gib — du-Imperativ von geben mit Vokalwechsel; mal hält es locker statt befehlend.",
  "Greeting": "Begrüßung",
  "Grufti = colloquial for goth (from Gruft = tomb/crypt)": "Grufti = umgangssprachlich für Gothic-Anhänger (von Gruft = Grabgewölbe)",
  "Gunsmith": "Waffenschmied",
  "Half-joking household rule for the unsortable. Colloquial, said with a shrug.": "Halb im Scherz gemeinte Haushaltsregel für alles Unsortierbare. Umgangssprachlich, mit einem Schulterzucken gesagt.",
  "half-joking quitter's line; 'ich schwör' is casual spoken German": "halb im Scherz gemeinter Aufhör-Spruch; 'ich schwör' ist lockeres gesprochenes Deutsch",
  "hol mal = casual imperative; note 'das Licht geht nicht' would mean the lamp itself is broken, not a power cut": "hol mal = lockerer Imperativ; Achtung: 'das Licht geht nicht' hieße, die Lampe selbst ist kaputt, nicht der Strom weg",
  "Hopeful repair language. 'Hinkriegen' is colloquial and warm — much more natural than 'reparieren'.": "Hoffnungsvolle Reparatursprache. 'Hinkriegen' ist umgangssprachlich und warm — viel natürlicher als 'reparieren'.",
  "How you confess a current obsession. 'Auf Dauerschleife' = on endless loop; casual, very common.": "So gesteht man eine aktuelle Obsession. 'Auf Dauerschleife' = in Endlosschleife; locker, sehr geläufig.",
  "idiomatic, informal": "idiomatisch, informell",
  "Im Alter von 30 = at the age of 30. As an exclamation, Alter! = dude! — very casual.": "Im Alter von 30 = mit 30 Jahren. Als Ausruf heißt Alter! so viel wie 'Mann!' — sehr locker.",
  "in casual speech often shortened to was: Hast du was gehört?": "in lockerer Rede oft zu was verkürzt: Hast du was gehört?",
  "In the moment": "Im Moment",
  "Informal": "Informell",
  "Informal — friends only": "Informell — nur unter Freunden",
  "Informal — the spoken contraction you'll usually hear": "Informell — die gesprochene Verkürzung, die man meist hört",
  "Informal — to strangers or staff say: Sprechen Sie Englisch?": "Informell — zu Fremden oder Personal sagt man: Sprechen Sie Englisch?",
  "Informal and rude: jemandem den Stinkefinger zeigen.": "Informell und unhöflich: jemandem den Stinkefinger zeigen.",
  "Informal and warm, mostly southern. 'Grüß Gott' is its formal, Bavarian and Austrian cousin.": "Informell und herzlich, vor allem im Süden. 'Grüß Gott' ist der förmliche bayerisch-österreichische Verwandte.",
  "Informal imperative of separable 'ablehnen' is 'Lehn ... ab'; after 'wenn', 'kennst' goes to the end.": "Der informelle Imperativ des trennbaren 'ablehnen' lautet 'Lehn ... ab'; nach 'wenn' rutscht 'kennst' ans Ende.",
  "Informal imperative of separable 'aufheben': 'Heb ... auf'; the full written form is 'Hebe'.": "Informeller Imperativ des trennbaren 'aufheben': 'Heb ... auf'; die volle Schriftform lautet 'Hebe'.",
  "informal loan from English; das Okay – the go-ahead": "informelles Lehnwort aus dem Englischen; das Okay – die Zustimmung",
  "Informal reply — with Sie say: Und Ihnen?": "Informelle Antwort — mit Sie sagt man: Und Ihnen?",
  "Informal term for a friend": "Informelles Wort für einen Freund",
  "informal, e.g. eine brenzlige Situation": "informell, z. B. eine brenzlige Situation",
  "informal; the standard German way to say someone drifted off into conspiracy land": "informell; die übliche deutsche Art zu sagen, dass jemand in Verschwörungsgefilde abgedriftet ist",
  "Introducing": "Vorstellen",
  "justifying one more — works for cigarettes and beers alike; very casual": "die Rechtfertigung für noch eine — passt für Zigaretten wie für Bier; sehr locker",
  "kicken — casual football. der Bolzplatz — the scuffed pitch every neighbourhood has.": "kicken — Fußball ohne großen Rahmen. Der Bolzplatz — der abgewetzte Platz, den jedes Viertel hat.",
  "klamm — damp, and colloquially short of cash. Honest without being dramatic.": "klamm — feucht, umgangssprachlich auch knapp bei Kasse. Ehrlich, ohne dramatisch zu werden.",
  "klingen — sounding. The honest warning given to every violin household's neighbours.": "klingen — tönen. Die ehrliche Warnung an die Nachbarn jedes Geigenhaushalts.",
  "knapp bei Kasse — tight at the till. The honest sentence that friends answer with einladen.": "knapp bei Kasse — knapp an der Kasse. Der ehrliche Satz, auf den Freunde mit einladen antworten.",
  "knapp bei Kasse sein = to be short of money; casual register, said among friends and family": "knapp bei Kasse sein = wenig Geld haben; lockeres Register, unter Freunden und Familie gesagt",
  "Knast = colloquial for jail/prison": "Knast = umgangssprachlich für Gefängnis",
  "Komm doch mal vorbei! — the casual open invitation.": "Komm doch mal vorbei! — die lockere, offene Einladung.",
  "Krankmeldung (colloquial) is what people say; the official document is the Krankschreibung / AU-Bescheinigung": "Krankmeldung (umgangssprachlich) sagen die Leute; das amtliche Dokument heißt Krankschreibung bzw. AU-Bescheinigung",
  "Ladder level 4, STRONG — for genuine anger or shock. Friends only; heads will turn if you shout it in public.": "Stufe 4 der Leiter, STARK — für echten Zorn oder Schreck. Nur unter Freunden; in der Öffentlichkeit gerufen dreht sich alles um.",
  "Leaving": "Gehen",
  "Level 2, medium-mild — like English 'damn'; fine among adults, avoid formal settings": "Stufe 2, mittel bis mild — wie das englische 'damn'; unter Erwachsenen okay, förmliche Anlässe meiden",
  "Loadout": "Ausrüstung",
  "Logisch! is also a casual \"obviously\"": "Logisch! ist auch ein lockeres 'na klar'",
  "Making a move": "Den ersten Schritt machen",
  "Making plans": "Pläne machen",
  "medium insult — banter-safe among close friends with the right tone": "mittelschwere Beleidigung — unter engen Freunden im richtigen Ton als Spaß okay",
  "medium-strong — banter only with thick-skinned close friends": "mittelstark — nur als Spaß unter engen Freunden mit dickem Fell",
  "Messaging — informal (du); in formal calls: Ich schreibe Ihnen eine Nachricht": "Nachrichten schreiben — informell (du); förmlich: Ich schreibe Ihnen eine Nachricht",
  "Meta": "Meta",
  "MILD-MEDIUM — dismissive ('you're not right in the head') rather than aggressive. Banter-safe among friends.": "MILD BIS MITTEL — abwertend ('du bist nicht ganz richtig im Kopf') statt aggressiv. Unter Freunden als Spaß okay.",
  "MILD-MEDIUM — often affectionate among friends and family ('you silly thing'). Still rude to strangers.": "MILD BIS MITTEL — unter Freunden und Familie oft liebevoll ('du Dummerchen'). Fremden gegenüber trotzdem unhöflich.",
  "mild-medium — often affectionate banter among friends": "mild bis mittel — oft liebevolle Neckerei unter Freunden",
  "mithelfen — pitching in. The morning-after miracle that separates friends from guests.": "mithelfen — mit anpacken. Das Wunder am Morgen danach, das Freunde von Gästen trennt.",
  "mocking the classic 'Spiegel-Poser', a fixture of every gym; casual, said behind their back": "spöttisch über den klassischen 'Spiegel-Poser', den es in jedem Gym gibt; locker, hinter seinem Rücken gesagt",
  "mocking, informal; the Aluhut is THE German ridicule image for conspiracists": "spöttisch, informell; der Aluhut ist DAS deutsche Spottbild für Verschwörungsgläubige",
  "nachfragen — following up. The sentence that saves the friendship.": "nachfragen — noch einmal nachhaken. Der Satz, der die Freundschaft rettet.",
  "neu laden = to reload — neu as an adverb before the verb; einfach shrugs it casual.": "neu laden = erneut laden — neu steht als Adverb vor dem Verb; einfach macht es beiläufig locker.",
  "Neutral opener that signals something is on your mind; works with friends and family.": "Neutraler Einstieg, der signalisiert, dass einen etwas beschäftigt; passt für Freunde und Familie.",
  "neutral small talk; works with anyone — casually dropped article is typical": "neutraler Small Talk; passt bei jedem — der locker weggelassene Artikel ist typisch",
  "neutral word; among friends it's almost always 'die Kippe'": "neutrales Wort; unter Freunden heißt es fast immer 'die Kippe'",
  "Neutral-casual; 'Abi' is what everyone says — the full 'Abitur' sounds formal.": "Neutral-locker; alle sagen 'Abi' — das volle 'Abitur' klingt förmlich.",
  "Neutral-casual; 'kriegen' is the spoken form of 'bekommen'.": "Neutral-locker; 'kriegen' ist die gesprochene Form von 'bekommen'.",
  "Neutral-colloquial; 'zuschlagen' = to throw a punch, to strike.": "Neutral-umgangssprachlich; 'zuschlagen' = einen Schlag ausführen, zuhauen.",
  "Neutral, casual — a no-fuss way to not drink without explaining yourself. No justification expected.": "Neutral, locker — eine unaufgeregte Art, nicht zu trinken, ohne sich zu erklären. Eine Begründung erwartet niemand.",
  "Neutral, casual 'hab'. The standard sequel to Verspätung — deliver it with weary resignation, not anger.": "Neutral, lockeres 'hab'. Die übliche Fortsetzung von Verspätung — mit müder Resignation vorbringen, nicht wütend.",
  "Neutral, common — disbelief that hovers between amused and appalled. Safe with anyone informal.": "Neutral, geläufig — Unglaube irgendwo zwischen amüsiert und entsetzt. Bei jedem informellen Gegenüber unbedenklich.",
  "Neutral, friendly — the standard joke opener among friends, family and colleagues. 'den' refers to der Witz.": "Neutral, freundlich — der übliche Witz-Einstieg unter Freunden, Familie und Kollegen. 'den' bezieht sich auf der Witz.",
  "Neutral, to friends/family/partner. THE suggestion — a leisurely loop, especially Sunday afternoon.": "Neutral, an Freunde, Familie oder Partner. DER Vorschlag — eine gemütliche Runde, besonders am Sonntagnachmittag.",
  "Neutral, to whoever planned the route. 'Die Tour' is the casual word for a planned hike.": "Neutral, an denjenigen, der die Route geplant hat. 'Die Tour' ist das lockere Wort für eine geplante Wanderung.",
  "Noun phrase + und + consequence — a conditional without wenn; landen in = to end up in, informal and vivid.": "Nominalphrase + und + Folge — ein Bedingungssatz ohne wenn; landen in = irgendwo enden, informell und anschaulich.",
  "oder so = or something / or whatever (casual suggestions)": "oder so = oder etwas in der Art (lockere Vorschläge)",
  "Opinion": "Meinung",
  "Ordering food": "Essen bestellen",
  "Plans": "Pläne",
  "Platform warning before train doors close": "Bahnsteigwarnung, bevor sich die Zugtüren schließen",
  "Players say Wishlist even though Steam's German UI says Wunschliste; 'schon ewig' = for ages. Neutral-casual.": "Spieler sagen Wishlist, obwohl Steams deutsche Oberfläche Wunschliste anzeigt; 'schon ewig' = seit einer Ewigkeit. Neutral-locker.",
  "Playful defensiveness, mild — said with mock indignation when friends laugh at your mishap. Casual settings.": "Spielerisch verteidigend, mild — mit gespielter Empörung gesagt, wenn Freunde über dein Missgeschick lachen. Lockere Runden.",
  "pleite — from bankruptcy, used casually. 'gerade' makes it temporary.": "pleite — vom Bankrott, locker gebraucht. 'gerade' macht es vorübergehend.",
  "plural 'Jungs' = guys, lads (colloquial)": "Plural 'Jungs' = Jungen, Kerle (umgangssprachlich)",
  "polite check with friends before lighting up; expected around non-smokers": "höfliche Rückfrage bei Freunden, bevor man sich eine ansteckt; bei Nichtrauchern erwartet",
  "polite warning shot before or instead of details; 'heikel' = delicate/tricky": "höflicher Warnschuss vor oder statt der Einzelheiten; 'heikel' = delikat, schwierig",
  "polite-casual at the salon; was = etwas in spoken German": "höflich-locker im Salon; was = etwas im gesprochenen Deutsch",
  "Position callout": "Positionsansage",
  "Post-breakup confession to close friends; serious and vulnerable, no banter register.": "Geständnis nach einer Trennung an enge Freunde; ernst und verletzlich, kein Spaßregister.",
  "Reacting": "Reagieren",
  "Reassuring": "Beruhigen",
  "Relationship status": "Beziehungsstatus",
  "Reporting a problem": "Ein Problem melden",
  "Request": "Bitte",
  "resigned, informal; standard line among worried friends of a Schwurbler": "resigniert, informell; der Standardsatz unter besorgten Freunden eines Schwurblers",
  "resigned; extremely common among friends and family of someone who's gone down the hole": "resigniert; äußerst verbreitet unter Freunden und Familie von jemandem, der abgerutscht ist",
  "Retail-investor bravado among friends; 'nachkaufen' = to buy more of what you already hold": "Kleinanleger-Bravour unter Freunden; 'nachkaufen' = mehr von dem kaufen, was man schon hält",
  "Routine": "Routine",
  "Said while handing over the Mitbringsel at the door, informal.": "Gesagt, während man an der Tür das Mitbringsel überreicht, informell.",
  "Say this when someone is about to see mutual friends or family. To several listeners, use 'Grüßt'.": "Sag das, wenn jemand gleich gemeinsame Freunde oder Familie trifft. Bei mehreren Zuhörern nimm 'Grüßt'.",
  "Scheduling": "Termine",
  "schlauchen — sapping your energy like a hose. Colloquial and exactly right.": "schlauchen — die Kraft absaugen wie ein Schlauch. Umgangssprachlich und genau richtig.",
  "schreiben = to write / spell (informal)": "schreiben = schreiben bzw. buchstabieren (informell)",
  "Seasons": "Jahreszeiten",
  "self-deprecating joke; 'ich schwör' is casual spoken German": "selbstironischer Witz; 'ich schwör' ist lockeres gesprochenes Deutsch",
  "separable: 'Ich probier mal was aus.' Casual speech clips it to 'probieren': 'Ich probier mal ne andere Waffe'": "trennbar: 'Ich probier mal was aus.' In lockerer Rede verkürzt zu 'probieren': 'Ich probier mal ne andere Waffe'",
  "sich befassen mit = to engage with; the je/desto frame around a negation — avoidance measured in growth.": "sich befassen mit = sich mit etwas auseinandersetzen; das je/desto-Gerüst um eine Verneinung — Vermeidung, in Zuwachs gemessen.",
  "sich etwas freihalten — keeping a day open. The advance reservation of friendship.": "sich etwas freihalten — einen Tag frei lassen. Die Vorabreservierung der Freundschaft.",
  "sich hinlegen — putting yourself down. 'mal' makes it casual, not dramatic.": "sich hinlegen — sich zum Ausruhen niederlegen. 'mal' macht es locker, nicht dramatisch.",
  "sich kurzschließen = to quickly sync (colloquial workplace); aneinander vorbeiarbeiten is a set idiom.": "sich kurzschließen = sich schnell abstimmen (umgangssprachlich im Job); aneinander vorbeiarbeiten ist eine feste Wendung.",
  "Slang": "Slang",
  "Slang — the English loan stays English; ein deutsches Bad is a bathroom": "Slang — das englische Lehnwort bleibt englisch; ein deutsches Bad ist ein Badezimmer",
  "Slang (voll = really/very)": "Slang (voll = echt, sehr)",
  "Slang expression of enthusiasm": "Slang-Ausdruck der Begeisterung",
  "Small-talk staple with international friends and colleagues; expect Germans to argue about their own answer.": "Ein Small-Talk-Klassiker mit internationalen Freunden und Kollegen; rechne damit, dass Deutsche über ihre eigene Antwort streiten.",
  "Some platforms add friends through masculine 'der Freundescode'; accusative is 'deinen Freundescode'.": "Manche Plattformen fügen Freunde über das maskuline 'der Freundescode' hinzu; im Akkusativ 'deinen Freundescode'.",
  "spiegelglatt — mirror-smooth. The radio traffic warning word.": "spiegelglatt — glatt wie ein Spiegel. Das Warnwort im Verkehrsfunk.",
  "spoken clip of 'Dispositionskredit'; 'im Dispo sein' = to be overdrawn — casual, everyone says it": "gesprochene Kurzform von 'Dispositionskredit'; 'im Dispo sein' = im Minus sein — locker, alle sagen es",
  "standard match-day question among friends, colleagues, in the Kneipe": "die Standardfrage am Spieltag unter Freunden, Kollegen, in der Kneipe",
  "Standard term in news and casual talk alike; can get heated between generations.": "Standardbegriff in Nachrichten wie im lockeren Gespräch; zwischen Generationen kann es hitzig werden.",
  "Standard third-person relationship analysis among friends; casual armchair-psychology weight.": "Die übliche Beziehungsanalyse über Dritte unter Freunden; lockere Küchenpsychologie.",
  "Status callout": "Statusansage",
  "Strong agreement": "Starke Zustimmung",
  "stronger and less casual than widerlich finden": "stärker und weniger locker als widerlich finden",
  "Surprise": "Überraschung",
  "Symptom": "Symptom",
  "talking about quitting with friends or partner": "übers Aufhören sprechen, mit Freunden oder dem Partner",
  "tanken — refuelling. Driving on the warning light is called auf Reserve fahren.": "tanken — Kraftstoff nachfüllen. Mit der Warnleuchte weiterzufahren heißt auf Reserve fahren.",
  "Team play": "Teamspiel",
  "Teasing between partners or friends; 'etwa' adds the playful gotcha tone.": "Neckerei unter Partnern oder Freunden; 'etwa' bringt den spielerischen Ertappt-Ton.",
  "Telling time": "Uhrzeit sagen",
  "Texting": "Chatten",
  "The 'gerade' matters — asking about the current obsession, not the all-time answer. Casual, du-form.": "Das 'gerade' zählt — gefragt ist die aktuelle Obsession, nicht die Antwort aller Zeiten. Locker, Du-Form.",
  "The Anprobe-zu-Hause strategy: order both, keep one, return the other; casual du-register": "Die Anprobe-zu-Hause-Strategie: beide bestellen, eins behalten, das andere zurückschicken; lockeres Du-Register",
  "The barber will ask you this; colloquially you'll also hear 'Wie viel Millimeter an den Seiten?'": "Das fragt dich der Friseur; umgangssprachlich hörst du auch 'Wie viel Millimeter an den Seiten?'",
  "The casual imperative is 'Misch'; 'die Karten mischen' is the normal phrase for shuffling.": "Der lockere Imperativ lautet 'Misch'; 'die Karten mischen' ist die normale Wendung fürs Mischen.",
  "The casual tier. Beste Grüße, Viele Grüße, VG: the ladder descends with familiarity.": "Die lockere Stufe. Beste Grüße, Viele Grüße, VG: Die Leiter steigt mit der Vertrautheit herab.",
  "the casual word for Rad fahren": "das lockere Wort für Rad fahren",
  "The classic couple question. 'Sich (Dativ) etwas holen' is the casual verb for getting a pet.": "Die klassische Paarfrage. 'Sich (Dativ) etwas holen' ist das lockere Verb dafür, sich ein Haustier zuzulegen.",
  "The classic no-fault breakup explanation — sad but blame-free. What people tell friends afterwards.": "Die klassische Trennungserklärung ohne Schuldzuweisung — traurig, aber vorwurfsfrei. Was man Freunden hinterher erzählt.",
  "THE dating-scene diagnosis of the decade; said casually but half-seriously about anyone who won't commit.": "DIE Dating-Diagnose des Jahrzehnts; locker, aber halb ernst gesagt über jeden, der sich nicht festlegen will.",
  "The default Grußformel — never wrong, never exciting. MfG in casual shorthand.": "Die Standard-Grußformel — nie falsch, nie aufregend. Locker abgekürzt: MfG.",
  "The dramatic version for partners and close friends — du-form territory, carries real weight": "Die dramatische Fassung für Partner und enge Freunde — Du-Gebiet, mit echtem Gewicht",
  "The embarrassment-avoidance rule. Half of all lost keys are in the other jacket.": "Die Regel gegen peinliche Momente. Die Hälfte aller verlorenen Schlüssel steckt in der anderen Jacke.",
  "The excited announcement to friends and family. 'Einen Antrag machen' is the standard idiom for proposing.": "Die aufgeregte Ankündigung an Freunde und Familie. 'Einen Antrag machen' ist die übliche Wendung für einen Heiratsantrag.",
  "The first question every friend asks. Casual, expected, and everyone wants the full story.": "Die erste Frage, die jeder Freund stellt. Locker, erwartet, und alle wollen die ganze Geschichte.",
  "The flare-up warning. Move it to the side; never pour water on.": "Die Warnung vor der Stichflamme. Zur Seite ziehen; niemals Wasser darauf gießen.",
  "The German ID card — der Perso in casual speech.": "Der deutsche Personalausweis — in lockerer Rede der Perso.",
  "THE gym-bro question; casual, between guys who lift": "DIE Gym-Bro-Frage; locker, unter Leuten, die Gewichte stemmen",
  "The hedge 'eher' is key — Germans rarely self-label without it. Safe self-description among friends.": "Die Abschwächung 'eher' ist entscheidend — Deutsche etikettieren sich selten ohne sie. Eine unbedenkliche Selbstbeschreibung unter Freunden.",
  "The hike itself; casually also 'die Tour'.": "Die Wanderung selbst; locker auch 'die Tour'.",
  "The honest cost warning. Under a hundred euros, most people simply pay.": "Die ehrliche Kostenwarnung. Unter hundert Euro zahlen die meisten einfach.",
  "The honest warning, issued once and remembered forever by flatmates.": "Die ehrliche Warnung, einmal ausgesprochen und von Mitbewohnern für immer behalten.",
  "The host's standard warm goodbye at the door, informal.": "Der übliche herzliche Abschied des Gastgebers an der Tür, informell.",
  "the key de-escalation and warmth line in mixed-belief couples and friendships; sincere register": "der zentrale Satz für Deeskalation und Wärme in Paaren und Freundschaften mit unterschiedlichem Glauben; aufrichtiges Register",
  "The late-summer warning. Cover your drink — the wasp finds it anyway.": "Die Warnung im Spätsommer. Deck dein Getränk ab — die Wespe findet es trotzdem.",
  "the modern word for conspiracy-rambling; informal and very common now": "das moderne Wort fürs Verschwörungsgeschwurbel; informell und inzwischen sehr verbreitet",
  "The most common casual check-in — short for Wie geht es?": "Die geläufigste lockere Nachfrage — Kurzform von Wie geht es?",
  "The order that avoids regret. Half a percent matters less than one good extra.": "Die Reihenfolge, die Reue erspart. Ein halbes Prozent zählt weniger als ein gutes Extra.",
  "The permission that keeps friendships alive through a separation.": "Die Erlaubnis, die Freundschaften durch eine Trennung hindurch am Leben hält.",
  "The positive mirror. 'Etwas/nichts/viel von jemandem halten' is THE casual pattern for rating people.": "Das positive Spiegelbild. 'Etwas/nichts/viel von jemandem halten' ist DAS lockere Muster, um Menschen einzuschätzen.",
  "The promise that keeps friendships": "Das Versprechen, das Freundschaften erhält",
  "The proud line — drop it casually among friends and watch the questions start.": "Der stolze Satz — beiläufig unter Freunden fallen lassen und zusehen, wie die Fragen anfangen.",
  "The quiet ending of many friendships, described without accusation.": "Das leise Ende vieler Freundschaften, beschrieben ohne Vorwurf.",
  "The reciprocity ledger of friendship — informal, unwritten, never forgotten.": "Das Gegenseitigkeitskonto der Freundschaft — informell, ungeschrieben, nie vergessen.",
  "The refusal that protects the friendship by naming the rule, not the person.": "Die Absage, die die Freundschaft schützt, weil sie die Regel nennt und nicht die Person.",
  "The sentence that softens hard truths between friends.": "Der Satz, der harte Wahrheiten unter Freunden abfedert.",
  "The sequence that avoids visible edges. Professionals call it 'vorschneiden'.": "Die Reihenfolge, die sichtbare Kanten vermeidet. Profis nennen das 'vorschneiden'.",
  "The so makes the question casual — 'what do you do, generally?' The small-talk classic.": "Das so macht die Frage locker — 'was machst du so?' Der Small-Talk-Klassiker.",
  "The solemn one — anniversaries, vows, letters. Partner only; too big for casual goodbyes.": "Die feierliche Formel — Jahrestage, Gelübde, Briefe. Nur für den Partner; zu groß für lockere Abschiede.",
  "The spoken du-command is 'Klick'; a more formal warning is 'Klicken Sie nicht auf den Link'.": "Der gesprochene Du-Befehl lautet 'Klick'; förmlicher warnt man: 'Klicken Sie nicht auf den Link'.",
  "The standard closing courtesy among friends. Expected, and noticed if forgotten.": "Die übliche Abschiedshöflichkeit unter Freunden. Erwartet — und es fällt auf, wenn sie fehlt.",
  "The standard earworm complaint, informal. Often followed by singing it and infecting everyone else.": "Die übliche Ohrwurm-Klage, informell. Oft folgt darauf, dass man ihn singt und alle anderen ansteckt.",
  "The standard sigh after any pay-rise or salary talk; casual, universal": "Der Standardseufzer nach jedem Gehaltsgespräch oder jeder Erhöhung; locker, überall verstanden",
  "the standard verb; coden is its casual twin": "das übliche Verb; coden ist sein lockerer Zwilling",
  "The standard warm reply you WILL hear — 'echt' makes it casual and sincere. Just say 'Danke!', don't argue.": "Die übliche herzliche Antwort, die du GARANTIERT hörst — 'echt' macht sie locker und ehrlich. Sag einfach 'Danke!', widersprich nicht.",
  "the standard way to disclose a serious rift; neutral register, works with friends and colleagues alike": "die übliche Art, einen ernsten Bruch mitzuteilen; neutrales Register, passt bei Freunden wie bei Kollegen",
  "The standard way to promise a return invitation at the door, informal.": "Die übliche Art, an der Tür eine Gegeneinladung zu versprechen, informell.",
  "the standard word; casually 'die Muckibude' or just 'das Gym'": "das übliche Wort; locker 'die Muckibude' oder einfach 'das Gym'",
  "The stylist asks this at the end; reinmachen is casual spoken German": "Das fragt der Friseur zum Schluss; reinmachen ist lockeres gesprochenes Deutsch",
  "the universal leg-day complaint; casual": "die universelle Klage nach dem Beintraining; locker",
  "The warning against illegal puppy trade. Cheap, sick, and it funds more of it.": "Die Warnung vor dem illegalen Welpenhandel. Billig, krank — und es finanziert weiteren.",
  "The written warning from an employer or lawyer — one step before consequences.": "Die schriftliche Abmahnung von Arbeitgeber oder Anwalt — einen Schritt vor den Konsequenzen.",
  "This impersonal passive is a playful way to announce an unavoidable routine without repeatedly saying 'you'.": "Dieses unpersönliche Passiv ist eine spielerische Art, eine unvermeidliche Routine anzukündigen, ohne ständig 'du' zu sagen.",
  "Time comment": "Bemerkung zur Zeit",
  "To friends or your partner right after trying a new word. Invites a gentle correction.": "An Freunde oder den Partner, gleich nachdem man ein neues Wort ausprobiert hat. Lädt zu einer sanften Korrektur ein.",
  "Two words that stop a small hand. 'Vorsicht' works alone as a warning.": "Zwei Wörter, die eine kleine Hand aufhalten. 'Vorsicht' funktioniert allein als Warnung.",
  "Typical reply": "Typische Antwort",
  "überweisen + dative person — sending money person-to-person. How friends settle up in Germany.": "überweisen + Person im Dativ — Geld von Mensch zu Mensch schicken. So gleichen Freunde in Deutschland aus.",
  "um einen Gefallen bitten — the formal opening of informal help. Germans appreciate the framing.": "um einen Gefallen bitten — die förmliche Eröffnung informeller Hilfe. Deutsche schätzen diesen Rahmen.",
  "Unlocks": "Freischaltungen",
  "Urgent": "Dringend",
  "Urgent warning": "Dringende Warnung",
  "verschreien — jinxing by saying. The warning shouted across German offices daily.": "verschreien — durch Aussprechen heraufbeschwören. Die Warnung, die täglich durch deutsche Büros ruft.",
  "verschwitzen — sweating an appointment away: forgetting it entirely. Casual, honest, forgivable once.": "verschwitzen — einen Termin wegschwitzen: ihn völlig vergessen. Locker, ehrlich, einmal verzeihlich.",
  "verstoßen gegen + Akkusativ; mit etwas rechnen müssen is the standard warning of consequences.": "verstoßen gegen + Akkusativ; mit etwas rechnen müssen ist die übliche Warnung vor Konsequenzen.",
  "Very casual slang for friends": "Sehr lockerer Slang für Freunde",
  "very casual, said just before a penalty; 'der' instead of 'er' is typical fan speech": "sehr locker, kurz vor einem Elfmeter gesagt; 'der' statt 'er' ist typische Fansprache",
  "Very casual: 'ne' = 'eine', 'probier mal' softens it. With friends, not in writing.": "Sehr locker: 'ne' = 'eine', 'probier mal' macht es weicher. Unter Freunden, nicht schriftlich.",
  "Very common (informal alternative to 'Die Rechnung bitte')": "Sehr geläufig (informelle Alternative zu 'Die Rechnung bitte')",
  "Very common casual slang": "Sehr geläufiger lockerer Slang",
  "Very common colloquial verb for losing your temper": "Sehr geläufiges umgangssprachliches Verb dafür, die Beherrschung zu verlieren",
  "Very common colloquial; about losing your temper, not going crazy.": "Sehr geläufig umgangssprachlich; es geht ums Ausrasten, nicht ums Verrücktwerden.",
  "Very common leisure activity": "Sehr verbreitete Freizeitbeschäftigung",
  "Very common, casual — Bock = desire/appetite": "Sehr geläufig, locker — Bock = Lust",
  "Very common, casual — literally 'that's sausage to me'": "Sehr geläufig, locker — wörtlich 'das ist mir Wurst'",
  "Very common, direct — friends or real annoyance": "Sehr geläufig, direkt — unter Freunden oder bei echtem Ärger",
  "vorbeischauen — looking past: the casual visit. 'auf einen Kaffee' — the unit of neighbourliness.": "vorbeischauen — kurz vorbeisehen: der lockere Besuch. 'auf einen Kaffee' — die Maßeinheit der Nachbarschaftlichkeit.",
  "Vorsicht + statement — the standard kitchen warning shape.": "Vorsicht + Aussage — die übliche Form der Küchenwarnung.",
  "Vulgar-casual: Willst du mich verarschen? = are you kidding me?": "Derb-locker: Willst du mich verarschen? = willst du mich veräppeln?",
  "Vulgar-ish (from Arsch = arse). Fine among friends, avoid with strangers or at work.": "Eher derb (von Arsch). Unter Freunden okay, bei Fremden oder auf der Arbeit vermeiden.",
  "Warm casual goodbye — informal (du), friends only": "Herzlicher, lockerer Abschied — informell (du), nur unter Freunden",
  "warm compliment for partner or close friends; stronger than 'gut'": "herzliches Kompliment für Partner oder enge Freunde; stärker als 'gut'",
  "Warm compliment, safe in any casual context.": "Herzliches Kompliment, in jedem lockeren Rahmen unbedenklich.",
  "Warm door greeting to friends (ihr). One person: 'Komm rein!'; formal: 'Kommen Sie rein!'": "Herzliche Begrüßung an der Tür für Freunde (ihr). Eine Person: 'Komm rein!'; förmlich: 'Kommen Sie rein!'",
  "Warm du-form for friends and family. Softer and more personal than the formal Beileid formulas.": "Herzliche Du-Form für Freunde und Familie. Sanfter und persönlicher als die förmlichen Beileidsformeln.",
  "Warm goodbye — informal (du), friends only": "Herzlicher Abschied — informell (du), nur unter Freunden",
  "Warm toast among friends, couples, teams celebrating something together. Follows or replaces 'Prost'.": "Herzlicher Trinkspruch unter Freunden, Paaren, Teams, die gemeinsam etwas feiern. Folgt auf 'Prost' oder ersetzt es.",
  "Warm, casual encouragement before a challenge. 'You've got this' is the most natural English equivalent.": "Herzliche, lockere Ermutigung vor einer Herausforderung. Am nächsten kommt dem das englische 'You've got this'.",
  "Warning": "Warnung",
  "Weather": "Wetter",
  "What you ask the neighbours during an outage; weg sein = to be gone (very common colloquial)": "Was man bei einem Stromausfall die Nachbarn fragt; weg sein = ausgefallen (sehr geläufig umgangssprachlich)",
  "What your investment earns; 'Rendite abwerfen' = to yield a return, colloquially also 'Rendite machen'": "Was deine Anlage einbringt; 'Rendite abwerfen' = Ertrag bringen, umgangssprachlich auch 'Rendite machen'",
  "Written German too": "Auch im Schriftdeutsch",
  "youth slang from 'suchten' (die Sucht = addiction): hat durchgesuchtet; 'binge-watchen' also works": "Jugendslang von 'suchten' (die Sucht = Abhängigkeit): hat durchgesuchtet; 'binge-watchen' geht auch",
  "zunächst and bislang bracket the timeline; es das geblieben — das stands for harmlos.": "zunächst und bislang rahmen den Zeitverlauf; es das geblieben — das steht für harmlos.",
  "zurückzahlen — paying back. The clause that keeps the friendship intact.": "zurückzahlen — zurückgeben. Der Nebensatz, der die Freundschaft heil lässt.",
};
