import type { CountryTimelineEvent } from "@/lib/countryStudies";

/**
 * La linea del tempo del corso «Vivere in Italia».
 *
 * Costruita sul modello britannico, tedesco, francese e polacco, con la
 * stessa regola che vale lì: un periodo appartiene al suo ULTIMO anno, non
 * al primo. Il fascismo sta al 1945 e non al 1922 — altrimenti la linea si
 * leggerebbe come se un'epoca finisse prima di cominciare.
 *
 * Sei epoche, perché la storia d'Italia si spezza proprio in questi punti:
 * l'eredità romana e i Comuni, il Rinascimento degli Stati italiani, il
 * Risorgimento fino a Roma capitale, l'Italia liberale fino alla marcia su
 * Roma, il ventennio con la guerra, e la Repubblica. I nomi sono quelli con
 * cui l'Italia divide la propria storia, senza periodizzazioni prese altrove.
 */

type ItEra =
  | "roma-medioevo"
  | "rinascimento"
  | "risorgimento"
  | "italia-liberale"
  | "fascismo-guerra"
  | "repubblica";

export const IT_ERA_LABELS: Record<ItEra, string> = {
  "roma-medioevo": "Roma e il Medioevo",
  rinascimento: "Rinascimento e Stati italiani",
  risorgimento: "Risorgimento e Unità d'Italia",
  "italia-liberale": "L'Italia liberale",
  "fascismo-guerra": "Fascismo e guerra",
  repubblica: "La Repubblica",
};

export const IT_ERA_ORDER: ItEra[] = [
  "roma-medioevo",
  "rinascimento",
  "risorgimento",
  "italia-liberale",
  "fascismo-guerra",
  "repubblica",
];

const event = (
  id: string,
  year: number,
  displayYear: string,
  era: ItEra,
  title: string,
  summary: string,
  detail: string,
  tags: string[],
  category = "Storia"
): CountryTimelineEvent => ({ id, year, displayYear, era, title, summary, detail, tags, category });

export const IT_TIMELINE: CountryTimelineEvent[] = [
  event(
    "caduta-impero",
    476,
    "476",
    "roma-medioevo",
    "Fine dell'Impero romano d'Occidente",
    "La deposizione di Romolo Augustolo chiude un'epoca e ne apre una lunghissima.",
    "Nel 476 Odoacre depone l'ultimo imperatore d'Occidente, Romolo Augustolo. La penisola non tornerà a essere un solo Stato per quasi millequattrocento anni: è la frattura da cui nasce l'Italia dei mille poteri, dei ducati, dei Comuni e dei regni stranieri.",
    ["476", "Romolo Augustolo", "Odoacre", "impero"],
  ),
  event(
    "comuni",
    1176,
    "1176",
    "roma-medioevo",
    "La Lega Lombarda a Legnano",
    "Le città del Nord battono l'imperatore e si tengono le loro libertà.",
    "A Legnano i Comuni riuniti nella Lega Lombarda sconfiggono Federico Barbarossa. La pace di Costanza del 1183 riconosce alle città il diritto di governarsi da sé. È l'atto di nascita politico dei Comuni, un modello di autogoverno urbano che in Europa non ha eguali per densità.",
    ["1176", "Legnano", "Lega Lombarda", "Barbarossa", "Comuni"],
    "Ordinamento",
  ),
  event(
    "lorenzo",
    1492,
    "1492",
    "rinascimento",
    "Morte di Lorenzo il Magnifico",
    "Con lui finisce l'equilibrio fra gli Stati italiani.",
    "Lorenzo de' Medici muore nel 1492, l'anno in cui Colombo attraversa l'Atlantico. Due anni dopo Carlo VIII di Francia scende in Italia e comincia mezzo secolo di guerre combattute in casa da eserciti stranieri. Il Rinascimento raggiunge il suo culmine artistico mentre la penisola perde ogni autonomia politica.",
    ["1492", "Lorenzo de' Medici", "Firenze", "Rinascimento"],
    "Cultura",
  ),
  event(
    "unita",
    1861,
    "17 marzo 1861",
    "risorgimento",
    "Proclamazione del Regno d'Italia",
    "Vittorio Emanuele II diventa re d'Italia: la penisola torna uno Stato solo.",
    "Il 17 marzo 1861 il primo Parlamento italiano proclama il Regno d'Italia. Mancano ancora il Veneto, che arriverà nel 1866, e Roma, che sarà presa nel 1870. La capitale è Torino, poi Firenze, e solo alla fine Roma: l'Italia unita nasce spostando il proprio centro tre volte in dieci anni.",
    ["1861", "Vittorio Emanuele II", "Regno d'Italia", "Torino"],
    "Ordinamento",
  ),
  event(
    "roma-capitale",
    1870,
    "20 settembre 1870",
    "risorgimento",
    "Presa di Roma",
    "La breccia di Porta Pia chiude il Risorgimento e apre la questione romana.",
    "I bersaglieri entrano a Roma attraverso una breccia aperta presso Porta Pia. Lo Stato pontificio finisce e Roma diventa capitale l'anno successivo. Il papa si dichiara prigioniero in Vaticano: il rapporto fra Stato e Chiesa resterà irrisolto fino ai Patti Lateranensi del 1929.",
    ["1870", "Porta Pia", "Roma capitale", "questione romana"],
  ),
  event(
    "marcia-su-roma",
    1922,
    "28 ottobre 1922",
    "italia-liberale",
    "Marcia su Roma",
    "Il re incarica Mussolini invece di firmare lo stato d'assedio.",
    "Le squadre fasciste convergono su Roma e Vittorio Emanuele III rifiuta di firmare il decreto di stato d'assedio che l'esercito avrebbe eseguito. Il 30 ottobre incarica Mussolini di formare il governo. Il passaggio avviene formalmente dentro le regole dello Statuto albertino: è così che finisce l'Italia liberale.",
    ["1922", "Mussolini", "Vittorio Emanuele III", "fascismo"],
    "Ordinamento",
  ),
  event(
    "liberazione",
    1945,
    "25 aprile 1945",
    "fascismo-guerra",
    "Liberazione",
    "L'insurrezione delle città del Nord chiude vent'anni di dittatura e due di occupazione.",
    "Il Comitato di liberazione nazionale alta Italia proclama l'insurrezione generale. Milano e Torino sono liberate prima dell'arrivo degli Alleati. Il 25 aprile è oggi festa nazionale: ricorda la Resistenza, non la firma della resa, che avverrà pochi giorni dopo.",
    ["1945", "Resistenza", "25 aprile", "CLN"],
  ),
  event(
    "referendum-1946",
    1946,
    "2 giugno 1946",
    "repubblica",
    "Referendum istituzionale",
    "Gli italiani scelgono la repubblica, e per la prima volta votano anche le donne.",
    "Con il referendum del 2 e 3 giugno 1946 la repubblica prevale sulla monarchia. Lo stesso giorno viene eletta l'Assemblea costituente. È la prima consultazione a suffragio davvero universale della storia italiana: le donne votano per la prima volta a livello nazionale.",
    ["1946", "referendum", "repubblica", "suffragio femminile"],
    "Ordinamento",
  ),
  event(
    "costituzione",
    1948,
    "1º gennaio 1948",
    "repubblica",
    "Entra in vigore la Costituzione",
    "Centotrentanove articoli scritti da un'assemblea di forze politiche opposte.",
    "La Costituzione approvata il 22 dicembre 1947 entra in vigore il 1º gennaio 1948. È rigida: si modifica solo con la procedura aggravata dell'articolo 138, e la forma repubblicana non è modificabile affatto. Regge da allora senza essere mai riscritta.",
    ["1948", "Costituzione", "Assemblea costituente"],
    "Ordinamento",
  ),
  event(
    "trattati-roma",
    1957,
    "25 marzo 1957",
    "repubblica",
    "Trattati di Roma",
    "L'Italia è fra i sei paesi che fondano la Comunità economica europea.",
    "In Campidoglio i rappresentanti di Italia, Francia, Germania, Belgio, Paesi Bassi e Lussemburgo firmano i trattati che istituiscono la CEE e l'Euratom. L'Italia non entra nell'Europa comunitaria: la fonda, e lo fa nella propria capitale.",
    ["1957", "CEE", "Trattati di Roma", "Europa"],
    "L'Italia nel mondo",
  ),
  event(
    "fondazione-roma", -753, "753 a.C.", "roma-medioevo",
    "Fondazione di Roma",
    "La data che la tradizione assegna alla nascita della città.",
    "Il 21 aprile del 753 avanti Cristo è la data tradizionale, fissata dagli storici antichi e non da un documento. Gli scavi mostrano insediamenti sul Palatino più antichi ancora. La data conta comunque: i romani datavano gli anni a partire da lì, e il 21 aprile è tuttora il compleanno di Roma.",
    ["753 a.C.", "Roma", "Palatino", "21 aprile"],
  ),
  event(
    "augusto", -27, "27 a.C.", "roma-medioevo",
    "Ottaviano diventa Augusto",
    "Finisce la repubblica romana e comincia l'impero.",
    "Il senato conferisce a Ottaviano il titolo di Augusto. Formalmente la repubblica resta in piedi, con i suoi magistrati e le sue assemblee; nei fatti il potere è concentrato in una sola persona. È il modello che l'Europa chiamerà impero per i quindici secoli successivi.",
    ["27 a.C.", "Augusto", "impero", "repubblica romana"],
    "Ordinamento",
  ),
  event(
    "editto-milano", 313, "313", "roma-medioevo",
    "Editto di Milano",
    "Costantino concede libertà di culto ai cristiani.",
    "L'editto pone fine alle persecuzioni e apre la strada al cristianesimo come religione dell'impero. Per l'Italia significa l'inizio del ruolo di Roma come centro religioso, che le resterà quando avrà perso ogni altro potere.",
    ["313", "Costantino", "cristianesimo", "Milano"],
    "Società",
  ),
  event(
    "carlo-magno", 774, "774", "roma-medioevo",
    "Carlo Magno sconfigge i Longobardi",
    "Il regno longobardo finisce e il papa acquista un protettore franco.",
    "Carlo Magno prende Pavia e assume la corona del regno longobardo. La donazione delle terre al papa consolida il nucleo dello Stato della Chiesa, che taglierà l'Italia in due fino al 1870. Nel giorno di Natale dell'800 sarà incoronato imperatore a Roma.",
    ["774", "Carlo Magno", "Longobardi", "Pavia"],
  ),
  event(
    "bologna", 1088, "1088", "roma-medioevo",
    "Nasce l'Università di Bologna",
    "La più antica università del mondo occidentale ancora in attività.",
    "Bologna nasce come corporazione di studenti che assumono i propri maestri — il contrario del modello odierno. Vi si studia soprattutto diritto, e da lì il diritto romano torna a circolare in tutta Europa. La parola università significava in origine proprio corporazione.",
    ["1088", "Bologna", "università", "diritto"],
    "Cultura",
  ),
  event(
    "regno-sicilia", 1130, "1130", "roma-medioevo",
    "Nasce il Regno di Sicilia",
    "I Normanni fondano al Sud il primo Stato accentrato d'Europa.",
    "Ruggero II unisce Sicilia e Italia meridionale in un regno con un'amministrazione centrale, un catasto e una burocrazia stabile, quando il resto d'Europa è ancora feudale. Palermo è una capitale in cui convivono latino, greco e arabo.",
    ["1130", "Ruggero II", "Normanni", "Palermo"],
    "Ordinamento",
  ),
  event(
    "pace-lodi", 1454, "1454", "rinascimento",
    "Pace di Lodi",
    "Cinque Stati italiani si riconoscono un equilibrio che dura quarant'anni.",
    "Milano, Venezia, Firenze, lo Stato della Chiesa e il Regno di Napoli chiudono decenni di guerre. Nessuno può prevalere, e la diplomazia sostituisce le armi: nascono in questo periodo le ambasciate permanenti, un'invenzione italiana che l'Europa adotterà per intera.",
    ["1454", "pace di Lodi", "equilibrio", "diplomazia"],
    "Ordinamento",
  ),
  event(
    "carlo-viii", 1494, "1494", "rinascimento",
    "Carlo VIII scende in Italia",
    "Cominciano le guerre d'Italia, combattute in casa da eserciti stranieri.",
    "L'equilibrio di Lodi si rivela fragile davanti a uno Stato nazionale capace di schierare un esercito grande. Per sessantacinque anni la penisola è il campo su cui Francia e Spagna decidono chi comanda in Europa.",
    ["1494", "Carlo VIII", "guerre d'Italia"],
  ),
  event(
    "principe", 1513, "1513", "rinascimento",
    "Machiavelli scrive Il Principe",
    "La politica viene osservata per come funziona, non per come dovrebbe essere.",
    "Scritto in esilio dopo il ritorno dei Medici a Firenze, il libro separa l'analisi del potere dalla morale. Sarà letto come un manuale di cinismo e come il primo testo di scienza politica: entrambe le letture hanno seguito.",
    ["1513", "Machiavelli", "Il Principe", "Firenze"],
    "Cultura",
  ),
  event(
    "sacco-roma", 1527, "1527", "rinascimento",
    "Sacco di Roma",
    "I lanzichenecchi imperiali saccheggiano la città per mesi.",
    "Le truppe di Carlo V, rimaste senza paga, prendono Roma e la devastano. Gli storici prendono questa data come la fine del Rinascimento come stagione fiduciosa: dopo il 1527 la cultura italiana cambia tono, e l'Italia politica non conta più.",
    ["1527", "sacco di Roma", "Carlo V", "lanzichenecchi"],
  ),
  event(
    "cateau-cambresis", 1559, "1559", "rinascimento",
    "Pace di Cateau-Cambrésis",
    "Le guerre d'Italia finiscono e la Spagna resta padrona della penisola.",
    "Milano, Napoli, Sicilia e Sardegna passano sotto la corona spagnola, che vi resterà un secolo e mezzo prima di cedere il posto all'Austria. L'Italia esce dalla politica europea come soggetto e vi rientra come territorio.",
    ["1559", "Cateau-Cambrésis", "Spagna"],
    "Ordinamento",
  ),
  event(
    "galileo", 1633, "1633", "rinascimento",
    "Processo a Galileo",
    "Il fondatore del metodo sperimentale è costretto ad abiurare.",
    "Galileo aveva sostenuto con osservazioni al telescopio che la Terra gira intorno al Sole. Il processo lo costringe all'abiura e agli arresti domiciliari fino alla morte. Resta uno dei momenti in cui la scienza europea e l'autorità religiosa si scontrano più direttamente.",
    ["1633", "Galileo", "metodo sperimentale", "abiura"],
    "Cultura",
  ),
  event(
    "tricolore", 1797, "7 gennaio 1797", "risorgimento",
    "Nasce il tricolore",
    "La Repubblica Cispadana adotta a Reggio Emilia la bandiera verde, bianca e rossa.",
    "È la prima volta che i tre colori diventano il vessillo di uno Stato italiano. La repubblica durerà pochi mesi, la bandiera oltre due secoli. Il 7 gennaio è oggi la Festa del Tricolore.",
    ["1797", "tricolore", "Reggio Emilia", "Repubblica Cispadana"],
    "Simboli",
  ),
  event(
    "vienna", 1815, "1815", "risorgimento",
    "Congresso di Vienna",
    "Le potenze rimettono in Italia i sovrani che Napoleone aveva cacciato.",
    "L'Austria torna in Lombardia e Veneto, i Borbone a Napoli, il papa a Roma, i Savoia in Piemonte. La restaurazione dei troni non cancella però l'idea di un'Italia possibile, che le società segrete continueranno a far circolare.",
    ["1815", "congresso di Vienna", "restaurazione", "Austria"],
    "Ordinamento",
  ),
  event(
    "giovine-italia", 1831, "1831", "risorgimento",
    "Mazzini fonda la Giovine Italia",
    "Il Risorgimento acquista un programma: una repubblica unitaria fatta dal popolo.",
    "Dall'esilio a Marsiglia, Giuseppe Mazzini organizza un movimento che punta all'insurrezione popolare invece che alle trattative fra sovrani. Le sue rivolte falliscono quasi tutte, ma formano la generazione che farà l'Unità.",
    ["1831", "Mazzini", "Giovine Italia", "repubblica"],
  ),
  event(
    "statuto-albertino", 1848, "4 marzo 1848", "risorgimento",
    "Statuto albertino",
    "Il Regno di Sardegna ha una costituzione, che sarà quella d'Italia fino al 1948.",
    "Carlo Alberto la concede nell'anno delle rivoluzioni europee. È flessibile, cioè modificabile con legge ordinaria: per questo il fascismo poté svuotarla senza mai violarla formalmente, e per questo i costituenti del 1947 vollero una costituzione rigida.",
    ["1848", "Statuto albertino", "Carlo Alberto", "costituzione"],
    "Ordinamento",
  ),
  event(
    "mille", 1860, "11 maggio 1860", "risorgimento",
    "Spedizione dei Mille",
    "Garibaldi sbarca a Marsala e in pochi mesi conquista il Sud.",
    "Mille volontari partiti da Quarto sbarcano in Sicilia e battono un esercito assai più numeroso. A Teano Garibaldi consegna il regno conquistato a Vittorio Emanuele II: un repubblicano che regala un regno a un re, uno dei gesti più discussi della storia italiana.",
    ["1860", "Garibaldi", "Marsala", "Teano", "Mille"],
  ),
  event(
    "veneto", 1866, "1866", "risorgimento",
    "Il Veneto entra nel Regno",
    "La terza guerra d'indipendenza aggiunge Venezia all'Italia unita.",
    "L'Italia combatte a fianco della Prussia contro l'Austria e perde le proprie battaglie, a Custoza e a Lissa, ma ottiene il Veneto grazie alle vittorie prussiane. Trento e Trieste resteranno austriache fino al 1918.",
    ["1866", "Veneto", "Austria", "Prussia"],
  ),
  event(
    "triplice", 1882, "1882", "italia-liberale",
    "Triplice alleanza",
    "L'Italia si lega a Germania e Austria-Ungheria, cioè al proprio antico avversario.",
    "L'alleanza dura oltre trent'anni ed è difensiva. Nel 1914 l'Italia la considera non applicabile perché l'Austria ha attaccato per prima, e nel 1915 entra in guerra dall'altra parte: una svolta che il paese discuterà a lungo.",
    ["1882", "Triplice alleanza", "Germania", "Austria-Ungheria"],
    "L'Italia nel mondo",
  ),
  event(
    "suffragio-1912", 1912, "1912", "italia-liberale",
    "Suffragio universale maschile",
    "Il corpo elettorale passa da tre a otto milioni e mezzo di persone.",
    "La riforma di Giolitti estende il voto a quasi tutti gli uomini adulti, compresi gli analfabeti sopra i trent'anni. Le donne dovranno aspettare ancora trentaquattro anni, fino al referendum del 1946.",
    ["1912", "Giolitti", "suffragio", "voto"],
    "Ordinamento",
  ),
  event(
    "entrata-1915", 1915, "24 maggio 1915", "italia-liberale",
    "L'Italia entra nella Grande guerra",
    "Il patto di Londra firmato in segreto porta il paese in guerra contro i suoi alleati.",
    "Il governo e il re decidono l'intervento mentre la maggioranza del Parlamento è neutralista. Il paese si spacca fra interventisti e neutralisti, e la frattura non si richiuderà: molte delle tensioni del dopoguerra nascono qui.",
    ["1915", "patto di Londra", "interventisti", "Grande guerra"],
  ),
  event(
    "caporetto", 1917, "24 ottobre 1917", "italia-liberale",
    "Caporetto",
    "La rotta sull'Isonzo porta il fronte fino al Piave.",
    "L'offensiva austro-tedesca sfonda le linee italiane e l'esercito arretra di cento chilometri, con centinaia di migliaia fra prigionieri e sbandati. Il nome è entrato nella lingua comune come sinonimo di disfatta.",
    ["1917", "Caporetto", "Isonzo", "Piave"],
  ),
  event(
    "vittorio-veneto", 1918, "4 novembre 1918", "italia-liberale",
    "Vittorio Veneto e l'armistizio",
    "La guerra finisce con circa seicentomila morti italiani.",
    "L'offensiva finale porta all'armistizio di Villa Giusti. L'Italia ottiene Trento, Trieste, l'Alto Adige e l'Istria, ma non tutto ciò che il patto di Londra le aveva promesso: nasce la formula della vittoria mutilata. Il 4 novembre è oggi il Giorno dell'Unità nazionale.",
    ["1918", "Vittorio Veneto", "armistizio", "vittoria mutilata"],
  ),
  event(
    "fasci", 1919, "23 marzo 1919", "italia-liberale",
    "Nascono i Fasci di combattimento",
    "In un paese scosso da scioperi e violenza politica nasce il movimento fascista.",
    "Fondati a Milano in piazza San Sepolcro, i Fasci si presentano come forza d'ordine contro le occupazioni di fabbriche e le agitazioni contadine, e vengono tollerati da industriali, proprietari terrieri e apparati dello Stato.",
    ["1919", "Fasci di combattimento", "Milano", "fascismo"],
  ),
  event(
    "matteotti", 1924, "10 giugno 1924", "fascismo-guerra",
    "Delitto Matteotti",
    "Il deputato che aveva denunciato i brogli viene rapito e ucciso.",
    "Giacomo Matteotti aveva contestato in aula la validità delle elezioni. La sua morte apre la crisi più grave del regime nascente, che Mussolini supera nel gennaio 1925 assumendosene pubblicamente la responsabilità politica.",
    ["1924", "Matteotti", "brogli", "regime"],
    "Ordinamento",
  ),
  event(
    "leggi-fascistissime", 1926, "1925–1926", "fascismo-guerra",
    "Le leggi fascistissime",
    "Sciolti i partiti, soppressa la stampa libera, istituito il Tribunale speciale.",
    "In due anni lo Stato liberale viene smontato con leggi ordinarie, senza che lo Statuto albertino sia mai abrogato. È la dimostrazione pratica di che cosa significhi una costituzione flessibile, e la ragione della rigidità di quella del 1948.",
    ["1926", "leggi fascistissime", "Tribunale speciale", "partiti"],
    "Ordinamento",
  ),
  event(
    "patti-lateranensi", 1929, "11 febbraio 1929", "fascismo-guerra",
    "Patti Lateranensi",
    "Si chiude la questione romana aperta nel 1870 e nasce lo Stato della Città del Vaticano.",
    "L'accordo con la Santa Sede riconosce la sovranità del papa su un territorio minuscolo e regola i rapporti fra Stato e Chiesa. I Patti sono richiamati dall'articolo 7 della Costituzione repubblicana e sono stati rivisti nel 1984.",
    ["1929", "Patti Lateranensi", "Vaticano", "questione romana"],
    "Ordinamento",
  ),
  event(
    "etiopia", 1935, "1935–1936", "fascismo-guerra",
    "Guerra d'Etiopia",
    "L'invasione porta le sanzioni internazionali e spinge l'Italia verso la Germania.",
    "L'aggressione all'Etiopia viola gli impegni presi nella Società delle Nazioni, che risponde con sanzioni economiche. L'isolamento avvicina l'Italia alla Germania: l'asse Roma-Berlino è dell'anno successivo.",
    ["1935", "Etiopia", "sanzioni", "Società delle Nazioni"],
    "L'Italia nel mondo",
  ),
  event(
    "leggi-razziali", 1938, "1938", "fascismo-guerra",
    "Le leggi razziali",
    "Gli ebrei italiani sono esclusi da scuole, professioni e vita pubblica.",
    "I provvedimenti colpiscono una comunità presente in Italia da duemila anni e integrata nella vita del paese. Preparano il terreno alle deportazioni che comincieranno dopo l'occupazione tedesca del 1943. Il Giorno della Memoria, il 27 gennaio, ricorda anche questo.",
    ["1938", "leggi razziali", "persecuzione", "Shoah"],
    "Società",
  ),
  event(
    "entrata-1940", 1940, "10 giugno 1940", "fascismo-guerra",
    "L'Italia entra nella Seconda guerra mondiale",
    "Il paese entra in guerra impreparato, contando su un conflitto già deciso.",
    "La dichiarazione arriva quando la Francia è quasi sconfitta, nella convinzione che la guerra finirà in poche settimane. Seguono tre anni di sconfitte in Grecia, in Africa e in Russia.",
    ["1940", "Seconda guerra mondiale", "Mussolini"],
  ),
  event(
    "otto-settembre", 1943, "8 settembre 1943", "fascismo-guerra",
    "L'armistizio e la divisione del paese",
    "L'esercito si dissolve, i tedeschi occupano il centro-nord, l'Italia si spacca in due.",
    "Il 25 luglio Mussolini era stato messo in minoranza e arrestato. L'8 settembre viene annunciato l'armistizio, ma senza ordini chiari all'esercito, che si sfalda. Nasce al Nord la Repubblica sociale italiana e comincia una guerra che è anche civile.",
    ["1943", "armistizio", "8 settembre", "Repubblica sociale"],
  ),
  event(
    "statuto-lavoratori", 1970, "1970", "repubblica",
    "Statuto dei lavoratori e prime regioni ordinarie",
    "I diritti sindacali entrano in fabbrica e le regioni previste dal 1948 nascono davvero.",
    "La legge 300 porta nei luoghi di lavoro le libertà costituzionali e vieta il licenziamento senza giusta causa nelle imprese maggiori. Nello stesso anno si tengono le prime elezioni nelle quindici regioni a statuto ordinario, previste dalla Costituzione ventidue anni prima.",
    ["1970", "Statuto dei lavoratori", "regioni", "sindacati"],
    "Società",
  ),
  event(
    "moro", 1978, "16 marzo – 9 maggio 1978", "repubblica",
    "Il rapimento e l'uccisione di Aldo Moro",
    "Cinquantacinque giorni che segnano il culmine degli anni di piombo.",
    "Le Brigate rosse rapiscono il presidente della Democrazia cristiana in via Fani uccidendo i cinque uomini della scorta, e lo assassinano dopo cinquantacinque giorni. Il 9 maggio è oggi il Giorno della memoria delle vittime del terrorismo.",
    ["1978", "Aldo Moro", "Brigate rosse", "anni di piombo"],
  ),
  event(
    "bologna", 1980, "2 agosto 1980", "repubblica",
    "Strage alla stazione di Bologna",
    "Una bomba nella sala d'aspetto uccide ottantacinque persone.",
    "È la strage più grave dell'Italia repubblicana. L'orologio della stazione è fermo sull'ora dell'esplosione, e ogni 2 agosto la città si ferma con lui. I processi hanno accertato la matrice neofascista.",
    ["1980", "Bologna", "strage", "2 agosto"],
    "Società",
  ),
  event(
    "mani-pulite", 1992, "1992–1994", "repubblica",
    "Mani pulite e le stragi di mafia",
    "Il sistema dei partiti nato nel dopoguerra si dissolve in due anni.",
    "L'inchiesta milanese rivela un finanziamento illecito diffuso e i partiti di governo si sciolgono quasi tutti: è la fine della Prima Repubblica. Nello stesso 1992 le stragi di Capaci e via d'Amelio uccidono i giudici Giovanni Falcone e Paolo Borsellino.",
    ["1992", "Mani pulite", "Falcone", "Borsellino", "Prima Repubblica"],
    "Ordinamento",
  ),
  event(
    "euro", 2002, "1º gennaio 2002", "repubblica",
    "Arrivano le banconote in euro",
    "La lira esce dalle tasche degli italiani dopo centoquarant'anni.",
    "L'euro esisteva come moneta di conto dal 1999; dal 2002 circolano banconote e monete. La lira era nata con il Regno d'Italia nel 1862, e la sostituzione è il cambiamento quotidiano più visibile dell'integrazione europea.",
    ["2002", "euro", "lira", "Unione europea"],
    "L'Italia nel mondo",
  ),
];
