/**
 * Which meaning a word card is teaching, in two or three words.
 *
 * A spoken word arrives without context. Listen says "weiter", the card reads
 * "further, additional", and a learner who was thinking of "carry on" has no
 * way to tell whether they were wrong or whether the card simply means the
 * other one. Most of these cards already carry a `use` note, but that note is
 * a paragraph: it explains the word after the fact, and by then the voice has
 * moved on to the next item.
 *
 * So each entry here is a glance-sized anchor, shown beside the translation:
 * the word, what it means, and a short phrase naming the meaning in play.
 * "weiter · further information" settles in a second what a paragraph settles
 * in ten.
 *
 * Only words are tagged, never sentences — a sentence is its own context and
 * needs no help. And only words that genuinely carry more than one meaning:
 * either they are reviewed in canonicalWordSenses.ts, or the packs claim them
 * with two different senses. check-word-sense-tags.cjs holds that set and this
 * table to each other, so a newly ambiguous word cannot ship untagged.
 *
 * A tag is an example of the sense in use, not a second gloss. Where a card
 * honestly teaches two meanings at once (das Rezept), the tag names both
 * worlds rather than picking a winner the card itself does not pick.
 */

/** Article and reflexive pronoun stripped, so "die Rechnung" and "sich melden" find their entry. */
const tagKey = (value: string) => String(value ?? "")
  .trim()
  .toLocaleLowerCase("de-DE")
  .replace(/^(der|die|das)\s+/, "")
  .replace(/^sich\s+/, "")
  .trim();

const WORD_SENSE_TAGS: Record<string, string> = {
  morgen: "not the morning",
  lernen: "learning something new",
  rechnung: "the restaurant bill",
  kochen: "cooking a meal",
  glauben: "I think so",
  nachricht: "a text message",
  runde: "a game round",
  hammer: "the actual tool",
  abhängen: "it depends on",
  alter: "your age in years",
  feierabend: "after-work time",
  vollpfosten: "a blunt insult",
  korb: "a shopping basket",
  griff: "a door handle",
  reichweite: "how far it reaches",
  zustimmung: "agreeing to something",
  grenze: "a country border",
  einräumen: "loading the dishwasher",
  nachvollziehen: "seeing their reasoning",
  überspitzt: "put pointedly",
  rückblickend: "looking back now",
  vorwurf: "blaming someone",
  auswirkung: "the knock-on effect",
  überweisung: "a bank transfer",
  beschwerde: "a formal complaint",
  rezept: "cooking or medicine",
  rückmeldung: "a quick reply",
  vorschlag: "making a suggestion",
  absprache: "agreed in advance",
  zunehmen: "putting on weight",
  belegen: "taking a course",
  abgabefrist: "the hand-in date",
  vertreten: "covering for someone",
  entkräften: "refuting an argument",
  forschungsstand: "what research says",
  mist: "a mild expletive",
  verarschen: "winding someone up",
  vertragen: "food agreeing with you",
  wahl: "choosing between options",
  heikel: "a touchy subject",
  verarbeiten: "processing an experience",
  abhängigkeit: "depending on something",
  hinterfragen: "probing a claim",
  aufwärmen: "food or muscles",
  schminken: "doing your make-up",
  anstoßen: "a toast together",
  kater: "the morning after",
  nüchtern: "not drunk",
  trocken: "sober in recovery",
  zocken: "playing video games",
  gymnasium: "a secondary school",
  note: "a school grade",
  zeugnis: "a school report",
  widerlegen: "proving it wrong",
  antrag: "an official application",
  trauzeuge: "at a wedding",
  anpassen: "tweaking a setting",
  einladen: "inviting someone along",
  melden: "dropping someone a line",
  erstatten: "money paid back",
  austreten: "leaving the church",
  drehen: "turning something round",
  aufhören: "stopping an activity",
  schneiden: "cutting or chopping",
  anbraten: "browning meat first",
  braten: "pan or oven",
  abschmecken: "salt and pepper",
  sperren: "blocking a card",
  anzeige: "placing an advert",
  fundbüro: "lost and found",
  ausfallen: "the lesson is off",
  kostenvoranschlag: "a written quote",
  folge: "cause and effect",
  gemeinde: "a local parish",
  übung: "practice makes perfect",
  wiederholen: "going over again",
  elfmeter: "in football",
  verlängerung: "a deadline extended",
  see: "an inland lake",
  anschluss: "a connecting train",
  durchschlafen: "all night through",
  ausschlafen: "a weekend lie-in",
  schulden: "money you owe",
  trauerfeier: "the ceremony itself",
  ohrwurm: "a song stuck",
  anlage: "a plant or installation",
  mitbringsel: "flowers or wine",
  passen: "it fits me",
  stehen: "standing in place",
  sitzen: "sitting in place",
  kassenbon: "the till slip",
  anschreiben: "with a job application",
  kündigen: "handing in notice",
  arbeitszeugnis: "a job reference",
  zusage: "the yes you get",
  absage: "the no you get",
  nachliefern: "sent on later",
  ablaufen: "an ID expiring",
  garderobe: "where coats go",
  deshalb: "giving the reason",
  infolgedessen: "formal written German",
  trotzdem: "thanks anyway",
  allerdings: "softening a contrast",
  gang: "the walkway itself",
  abbauen: "taking something down",
  fertigkeit: "a trainable skill",
  aufladen: "charging a phone",
  ablehnen: "turning an offer down",
  zufall: "by pure chance",
  erinnern: "remembering something yourself",
  übertreiben: "overdoing it",
  feld: "a farmer's field",
  sicherung: "the fuse box",
  einpacken: "wrapping a present",
  buntwäsche: "the colours load",
  futter: "food for animals",
  leine: "the dog's lead",
  kratzen: "an itchy jumper",
  gleich: "any second now",
  bescheid: "an official letter",
  weg: "on the way",
  erledigen: "sorting something out",
  abschließen: "bringing to an end",
  ungefähr: "about ten minutes",
  entwerten: "stamping before travel",
  beschwerden: "aches and pains",
  abgeben: "handing something in",
  reichen: "enough to go round",
  steckdose: "in the wall",
  überlegen: "considering an option",
  erinnerung: "a memory kept",
  anfangen: "just getting started",
  zusammenhang: "in connection with",
  begründen: "saying why",
  meistens: "most of the time",
  ausleihen: "a library book",
  übrig: "any left over",
  auswahl: "a wide range",
  rund: "circular in shape",
  aufteilen: "splitting things up",
  übernehmen: "covering the costs",
  schaffen: "getting it done",
  stand: "the current state",
  verlauf: "your browser history",
  änderung: "a change made",
  abschlag: "a monthly part-payment",
  nachzahlung: "what you still owe",
  borgen: "between friends",
  schwein: "the farm animal",
  azubi: "in an apprenticeship",
  abkürzung: "a shorter route",
  ansatz: "how you start",
  nacken: "where it aches",
  aufklaren: "the weather only",
  beitrag: "a membership fee",
  durchhalten: "hang in there",
  deckel: "on a pot",
  läuse: "in the hair",
  nachweis: "written proof",
  absichern: "covering yourself",
  personalausweis: "the German ID",
  widerspruch: "a formal objection",
  anzahlung: "paid up front",
  umstellen: "changing a system",
  chip: "the trolley token",
  vorsatz: "New Year resolutions",
  kurzfristig: "with little warning",
  verlegen: "moving an appointment",
  zuschlag: "an extra fee",
  waschprogramm: "on the machine",
  liege: "by the pool",
  leerung: "emptying the postbox",
  störung: "a network outage",
  verzichten: "giving something up",
  überreden: "talking someone round",
  begründung: "the reason stated",
  befund: "a test result",
  anmeldung: "signing up somewhere",
  zettel: "a written note",
  einwerfen: "posting a letter",
  rollator: "a walking frame",
  abspann: "at the end",
  mittagsschlaf: "after lunch",
  station: "a stop en route",
  bund: "radishes or herbs",
  bestehen: "passing an exam",
  stimmen: "being correct",
  anprobe: "trying clothes on",
  abstieg: "the way down",
  aufstieg: "the climb up",
  notdienst: "out of hours",
  einstellen: "setting the heating",
  quote: "a required share",
  tipp: "a good tip",
  sitzenbleiben: "held back a year",
  mitgefühl: "feeling for someone",
  profil: "an online account",
  untertitel: "subtitles when watching",
  abmahnung: "a written warning",
  gericht: "in court",
  vertretung: "a stand-in teacher",
  filiale: "a shop branch",
  rate: "paid monthly",
  winterdienst: "gritting and snow-clearing",
  wadenwickel: "a fever remedy",
  krankmelden: "phoning work sick",
  ausfall: "something not happening",
  gutachten: "a commissioned assessment",
  aufnahme: "an audio recording",
  stundenlohn: "per hour worked",
  übergang: "moving between two",
  regional: "local produce",
  haltung: "your body posture",
  leistung: "what you achieve",
  punkt: "a dot or score",
  anwendung: "a software program",
  träger: "a dress strap",
  stimme: "your speaking voice",
  fordern: "demanding, not asking",
  spielraum: "room to manoeuvre",
  kündigung: "handing in notice",
  bewusstsein: "being conscious",
  vorläufig: "for now only",
  überzeugen: "convincing with reasons",
  bus: "the everyday vehicle",
  strecke: "the way there",
  knapp: "only just enough",
  schuld: "at fault yourself",
  ausgehen: "out for the evening",
  hervorheben: "singling something out",
  umfang: "the full extent",
  ziel: "what you aim for",
  geringfügig: "hardly worth mentioning",
  aufschlussreich: "told you a lot",
  verhältnismäßig: "comparatively speaking",
  pauschal: "one flat price",
  sachlich: "sticking to facts",
  einordnen: "making sense of",
  gegenüberstellen: "side by side",
  reichlich: "more than enough",
  rücksichtslos: "without regard",
  gelassen: "taking it calmly",
  ausführen: "carrying out a plan",
  kritisieren: "finding fault",
  priorisieren: "ranking by importance",
  einführen: "bringing something in",
  beibehalten: "sticking with it",
  gefährden: "putting at risk",
  nachlassen: "easing off gradually",
  verzögerung: "running late",
  vorbeugen: "prevention before cure",
  feststellen: "noticing a fact",
  ermitteln: "working it out",
  eingehen: "engaging with it",
  ankommen: "arriving somewhere",
  vornehmen: "resolving to do",
  prozess: "a series of steps",
  regelung: "how something is handled",
  literatur: "books and writing",
  bewertung: "a review score",
  kurs: "a class you take",
  kommentar: "a remark made",
  kritik: "criticism voiced",
  schwül: "heavy humid air",
  einschränken: "cutting back on",
  vorstellung: "a mental picture",
  milliarde: "a thousand million",
};

/** The tag for a word, or nothing when the word carries only one meaning. */
export function wordSenseTagFor(lookup: string): string | undefined {
  return WORD_SENSE_TAGS[tagKey(lookup)];
}

export const SENSE_TAGGED_WORDS = Object.freeze(Object.keys(WORD_SENSE_TAGS));
