import type { CountryTimelineEvent } from "@/lib/countryStudies";

/**
 * Oś czasu kursu „Życie w Polsce”.
 *
 * Zbudowana według wzoru brytyjskiego, niemieckiego i francuskiego, razem z
 * regułą, która tam obowiązuje: okres należy do swojego OSTATNIEGO roku, nie
 * pierwszego. II Rzeczpospolita stoi przy 1939, a nie przy 1918 — inaczej oś
 * czytałaby się tak, jakby kończyła się, zanim się zaczęła.
 *
 * Sześć epok, bo historia Polski łamie się właśnie w tych miejscach: początki
 * państwa, unia z Litwą i Rzeczpospolita Obojga Narodów, rozbiory, dwudziestolecie
 * międzywojenne, wojna wraz z PRL, i III Rzeczpospolita. Nazwy są polskie —
 * tak, jak Polska sama dzieli swoją historię, bez nakładania podziałów obcych.
 */

type PlEra =
  | "poczatki"
  | "jagiellonowie"
  | "rozbiory"
  | "druga-rp"
  | "wojna-prl"
  | "trzecia-rp";

export const PL_ERA_LABELS: Record<PlEra, string> = {
  poczatki: "Początki państwa polskiego",
  jagiellonowie: "Jagiellonowie i Rzeczpospolita Obojga Narodów",
  rozbiory: "Rozbiory i walka o niepodległość",
  "druga-rp": "II Rzeczpospolita",
  "wojna-prl": "Wojna, okupacja i PRL",
  "trzecia-rp": "III Rzeczpospolita",
};

export const PL_ERA_ORDER: PlEra[] = [
  "poczatki",
  "jagiellonowie",
  "rozbiory",
  "druga-rp",
  "wojna-prl",
  "trzecia-rp",
];

const event = (
  id: string,
  year: number,
  displayYear: string,
  era: PlEra,
  title: string,
  summary: string,
  detail: string,
  tags: string[],
  category = "Historia"
): CountryTimelineEvent => ({ id, year, displayYear, era, title, summary, detail, tags, category });

export const PL_TIMELINE: CountryTimelineEvent[] = [
  event(
    "chrzest",
    966,
    "966",
    "poczatki",
    "Chrzest Polski",
    "Mieszko I przyjmuje chrzest i wprowadza swoje państwo w krąg zachodniej Europy.",
    "Mieszko I, książę Polan, przyjmuje chrzest w 966 roku. Decyzja jest polityczna tak samo jak religijna: chrześcijański władca przestaje być dla sąsiadów celem misji zbrojnej, a państwo zyskuje pismo, kalendarz i sieć kontaktów z resztą łacińskiej Europy. Datę tę przyjmuje się za początek państwa polskiego.",
    ["Mieszko I", "chrzest", "966", "Polanie"],
  ),
  event(
    "konstytucja-3-maja",
    1791,
    "3 maja 1791",
    "jagiellonowie",
    "Konstytucja 3 maja",
    "Pierwsza w Europie i druga na świecie nowoczesna konstytucja spisana.",
    "Sejm Czteroletni uchwala Ustawę Rządową, znaną jako Konstytucja 3 maja. Znosi wolną elekcję i liberum veto, wzmacnia władzę wykonawczą i bierze mieszczan pod ochronę prawa. Powstaje jako próba ratowania państwa — cztery lata później Rzeczpospolita znika z mapy. Dzień 3 maja jest dziś świętem państwowym.",
    ["1791", "Sejm Czteroletni", "liberum veto", "święto"],
    "Ustrój",
  ),
  event(
    "niepodleglosc",
    1918,
    "11 listopada 1918",
    "rozbiory",
    "Odzyskanie niepodległości",
    "Po 123 latach rozbiorów Polska wraca na mapę Europy.",
    "11 listopada 1918 roku Rada Regencyjna przekazuje Józefowi Piłsudskiemu władzę wojskową. Data zamyka 123 lata, w których państwa polskiego nie było, i otwiera II Rzeczpospolitą. Jest dziś Narodowym Świętem Niepodległości.",
    ["1918", "Piłsudski", "11 listopada", "święto"],
  ),
  event(
    "wybory-1989",
    1989,
    "4 czerwca 1989",
    "wojna-prl",
    "Wybory czerwcowe",
    "Częściowo wolne wybory kończą rządy jednej partii.",
    "W wyborach 4 czerwca 1989 roku Solidarność zdobywa wszystkie mandaty, o które wolno jej było się ubiegać w Sejmie, i 99 na 100 miejsc w Senacie. Wynik jest tak jednoznaczny, że dotychczasowa władza traci podstawę do rządzenia. Rok później Polska ma pierwszego od dziesięcioleci prezydenta wybranego w wyborach powszechnych.",
    ["1989", "Solidarność", "wybory", "PRL"],
    "Ustrój",
  ),
  event(
    "unia-europejska",
    2004,
    "1 maja 2004",
    "trzecia-rp",
    "Wejście do Unii Europejskiej",
    "Polska wstępuje do Unii razem z dziewięcioma innymi państwami.",
    "1 maja 2004 roku Polska staje się członkiem Unii Europejskiej — po referendum, w którym za opowiedziało się ponad trzy czwarte głosujących. Wcześniej, w 1999 roku, kraj wszedł do NATO. Obie decyzje wyznaczają miejsce Polski w Europie po 1989 roku.",
    ["2004", "Unia Europejska", "NATO", "referendum"],
    "Polska w świecie",
  ),
  event(
    "zjazd-gnieznienski", 1000, "1000", "poczatki",
    "Zjazd gnieźnieński",
    "Cesarz Otton III przyjeżdża do Gniezna i uznaje pozycję Bolesława Chrobrego.",
    "Cesarz przybywa do grobu świętego Wojciecha i spotyka się z Bolesławem Chrobrym. Powstaje samodzielna metropolia kościelna w Gnieźnie — dowód, że młode państwo nie jest już terenem misyjnym, lecz partnerem. Zjazd bywa nazywany pierwszym polskim sukcesem dyplomatycznym.",
    ["1000", "Otton III", "Gniezno", "święty Wojciech"],
  ),
  event(
    "koronacja-chrobrego", 1025, "1025", "poczatki",
    "Koronacja Bolesława Chrobrego",
    "Pierwszy król Polski wkłada koronę na kilka miesięcy przed śmiercią.",
    "Bolesław Chrobry koronuje się w 1025 roku, po latach starań o zgodę papieża i cesarza. Umiera tego samego roku. Koronacja domyka dzieło Mieszka I: państwo ma odtąd nie tylko granice i chrzest, ale i królewski tytuł.",
    ["1025", "Bolesław Chrobry", "koronacja", "Piastowie"],
    "Ustrój",
  ),
  event(
    "rozbicie-dzielnicowe", 1138, "1138", "poczatki",
    "Testament Krzywoustego",
    "Podział państwa między synów zaczyna dwieście lat rozbicia dzielnicowego.",
    "Bolesław Krzywousty dzieli państwo między synów, żeby uniknąć wojny o władzę. Skutek jest odwrotny: dzielnice usamodzielniają się, a książęta walczą ze sobą. Scalenie zajmie blisko dwieście lat i uda się dopiero Władysławowi Łokietkowi.",
    ["1138", "Krzywousty", "rozbicie dzielnicowe"],
  ),
  event(
    "lokietek", 1320, "1320", "poczatki",
    "Koronacja Władysława Łokietka",
    "Po rozbiciu dzielnicowym kraj znów ma jednego króla.",
    "Władysław Łokietek koronuje się w Krakowie — nie w Gnieźnie, co przypieczętowuje przeniesienie ośrodka władzy na południe. Zjednoczenie jest niepełne: Śląsk i Pomorze Gdańskie pozostają poza granicami.",
    ["1320", "Łokietek", "zjednoczenie", "Kraków"],
    "Ustrój",
  ),
  event(
    "kazimierz-wielki", 1370, "1333–1370", "poczatki",
    "Panowanie Kazimierza Wielkiego",
    "Ostatni Piast rozbudowuje państwo, prawo i miasta.",
    "Kazimierz Wielki porządkuje prawo, buduje zamki i mury miejskie, zakłada w 1364 roku uniwersytet w Krakowie i przyjmuje Żydów wypędzanych z Europy Zachodniej. Powiedzenie o Polsce drewnianej i murowanej pochodzi z późniejszych kronik, ale oddaje skalę zmian.",
    ["Kazimierz Wielki", "1364", "uniwersytet", "Piastowie"],
  ),
  event(
    "unia-krewo", 1385, "1385", "jagiellonowie",
    "Unia w Krewie",
    "Litwa i Polska łączą się przez małżeństwo Jagiełły i Jadwigi.",
    "Wielki książę litewski Jagiełło przyjmuje chrzest, żeni się z królową Jadwigą i zostaje królem Polski. Litwa — ostatnie pogańskie państwo Europy — wchodzi w krąg chrześcijaństwa. Zaczyna się dynastia Jagiellonów i związek trwający czterysta lat.",
    ["1385", "Jagiełło", "Jadwiga", "unia"],
    "Ustrój",
  ),
  event(
    "grunwald", 1410, "15 lipca 1410", "jagiellonowie",
    "Bitwa pod Grunwaldem",
    "Wojska polsko-litewskie rozbijają armię zakonu krzyżackiego.",
    "Jedna z największych bitew średniowiecznej Europy. Zakon traci wielkiego mistrza i większość dowódców. Zwycięstwo nie przynosi od razu ziem, ale łamie potęgę państwa krzyżackiego i na stulecia wchodzi do zbiorowej pamięci.",
    ["1410", "Grunwald", "Krzyżacy", "Jagiełło"],
  ),
  event(
    "pokoj-torunski", 1466, "1466", "jagiellonowie",
    "Drugi pokój toruński",
    "Polska odzyskuje Pomorze Gdańskie i dostęp do morza.",
    "Po trzynastoletniej wojnie zakon krzyżacki oddaje Pomorze Gdańskie z Gdańskiem i Malborkiem, a resztę ziem zatrzymuje jako lenno Polski. Kraj zyskuje wybrzeże i ujście Wisły — a wraz z nimi handel zbożem, na którym oprze się gospodarka następnych stuleci.",
    ["1466", "Toruń", "Pomorze", "Gdańsk"],
    "Polska w świecie",
  ),
  event(
    "hold-pruski", 1525, "1525", "jagiellonowie",
    "Hołd pruski",
    "Ostatni wielki mistrz krzyżacki składa hołd królowi Polski.",
    "Albrecht Hohenzollern przekształca państwo zakonne w świeckie Prusy Książęce i klęka na krakowskim rynku przed Zygmuntem Starym. Scenę utrwalił trzy i pół wieku później Jan Matejko — obraz stał się jednym z najbardziej znanych w polskim malarstwie.",
    ["1525", "hołd pruski", "Zygmunt Stary", "Matejko"],
    "Polska w świecie",
  ),
  event(
    "unia-lubelska", 1569, "1569", "jagiellonowie",
    "Unia lubelska",
    "Powstaje Rzeczpospolita Obojga Narodów.",
    "Polska i Litwa tworzą jedno państwo ze wspólnym sejmem, wspólną monetą i wspólnie wybieranym królem. Powierzchnią jest wtedy jednym z największych państw Europy. Odrębne pozostają wojsko, skarb i prawo obu części.",
    ["1569", "Lublin", "Rzeczpospolita Obojga Narodów"],
    "Ustrój",
  ),
  event(
    "konfederacja-warszawska", 1573, "1573", "jagiellonowie",
    "Konfederacja warszawska",
    "Szlachta zapisuje pokój między wyznaniami w czasie wojen religijnych Europy.",
    "W roku, gdy Europa Zachodnia toczy wojny religijne, sejm konwokacyjny gwarantuje szlachcie różnych wyznań pokój i równe prawa. Dokument uchodzi za jeden z pierwszych aktów tolerancji religijnej na kontynencie. Wtedy też odbywa się pierwsza wolna elekcja.",
    ["1573", "tolerancja", "wolna elekcja", "wyznania"],
    "Ustrój",
  ),
  event(
    "stolica-warszawa", 1596, "1596", "jagiellonowie",
    "Przeniesienie dworu do Warszawy",
    "Zygmunt III Waza przenosi rezydencję z Krakowa.",
    "Po pożarze Wawelu i wobec unii z Litwą dwór przenosi się do położonej centralnie Warszawy. Kraków pozostaje miejscem koronacji i pochówku królów jeszcze przez dwa stulecia, ale ośrodkiem władzy jest odtąd Warszawa.",
    ["1596", "Warszawa", "Zygmunt III Waza", "stolica"],
    "Ustrój",
  ),
  event(
    "potop", 1660, "1655–1660", "jagiellonowie",
    "Potop szwedzki",
    "Szwedzki najazd niszczy kraj i zostaje odparty.",
    "Wojska szwedzkie zajmują większość Rzeczypospolitej. Punktem zwrotnym staje się obrona Jasnej Góry. Kraj zostaje odzyskany, ale wychodzi z wojny wyludniony i zniszczony — straty demograficzne bywa się porównuje z tymi z II wojny światowej.",
    ["1655", "potop", "Szwedzi", "Jasna Góra"],
  ),
  event(
    "wieden", 1683, "12 września 1683", "jagiellonowie",
    "Odsiecz wiedeńska",
    "Jan III Sobieski rozbija armię turecką pod Wiedniem.",
    "Husaria Jana III Sobieskiego przesądza o wyniku bitwy, która zatrzymuje ekspansję osmańską w Europie Środkowej. To ostatnie wielkie zwycięstwo Rzeczypospolitej; wewnętrznie państwo jest już osłabione liberum veto i walkami magnatów.",
    ["1683", "Sobieski", "Wiedeń", "husaria"],
  ),
  event(
    "pierwszy-rozbior", 1772, "1772", "rozbiory",
    "Pierwszy rozbiór",
    "Rosja, Prusy i Austria zabierają blisko jedną trzecią terytorium.",
    "Trzy sąsiednie mocarstwa dokonują podziału bez wojny, a sejm zostaje zmuszony do jego zatwierdzenia. Wstrząs uruchamia reformy: powstaje Komisja Edukacji Narodowej, pierwsze w Europie ministerstwo oświaty.",
    ["1772", "rozbiór", "Komisja Edukacji Narodowej"],
  ),
  event(
    "konstytucja-1791", 1791, "3 maja 1791", "rozbiory",
    "Konstytucja 3 maja",
    "Pierwsza w Europie nowoczesna konstytucja spisana.",
    "Sejm Czteroletni uchwala Ustawę Rządową. Znosi liberum veto i wolną elekcję, wzmacnia rząd, bierze mieszczan i chłopów pod ochronę prawa. Obowiązuje czternaście miesięcy — sąsiedzi widzą w reformie zagrożenie i wkraczają zbrojnie.",
    ["1791", "3 maja", "Sejm Czteroletni", "święto"],
    "Ustrój",
  ),
  event(
    "insurekcja", 1794, "1794", "rozbiory",
    "Insurekcja kościuszkowska",
    "Ostatnia próba obrony Rzeczypospolitej przed rozbiorem.",
    "Tadeusz Kościuszko, weteran wojny o niepodległość Stanów Zjednoczonych, ogłasza powstanie na krakowskim rynku. Uniwersał połaniecki obiecuje chłopom wolność osobistą. Powstanie upada, a rok później następuje trzeci rozbiór.",
    ["1794", "Kościuszko", "insurekcja", "Racławice"],
  ),
  event(
    "trzeci-rozbior", 1795, "1795", "rozbiory",
    "Trzeci rozbiór",
    "Państwo polskie znika z mapy Europy na 123 lata.",
    "Rosja, Prusy i Austria dzielą resztę Rzeczypospolitej. Król abdykuje. Przez ponad sto lat polskość trwa w języku, kulturze i kościele, a kolejne pokolenia próbują odzyskać państwo powstaniami albo pracą u podstaw.",
    ["1795", "rozbiór", "123 lata"],
  ),
  event(
    "powstanie-listopadowe", 1831, "1830–1831", "rozbiory",
    "Powstanie listopadowe",
    "Zryw przeciw Rosji kończy się klęską i Wielką Emigracją.",
    "Powstanie zaczyna się w Warszawie w listopadzie 1830 roku i trwa niespełna rok. Po klęsce tysiące ludzi wyjeżdża na Zachód — wśród nich Chopin i Mickiewicz. Wtedy też, 7 lutego 1831 roku, sejm ustala biel i czerwień jako barwy narodowe.",
    ["1830", "powstanie listopadowe", "Wielka Emigracja", "barwy"],
  ),
  event(
    "powstanie-styczniowe", 1864, "1863–1864", "rozbiory",
    "Powstanie styczniowe",
    "Najdłuższe powstanie kończy się represjami i zmianą myślenia.",
    "Walka partyzancka trwa kilkanaście miesięcy na rozległym terenie. Po klęsce przychodzą konfiskaty, zsyłki na Sybir i nasilona rusyfikacja. Część działaczy odchodzi wtedy od zbrojnych zrywów na rzecz pracy organicznej: szkół, spółdzielni i czytelni.",
    ["1863", "powstanie styczniowe", "Sybir", "praca organiczna"],
  ),
  event(
    "nobel-curie", 1903, "1903", "rozbiory",
    "Pierwszy Nobel Marii Skłodowskiej-Curie",
    "Polska uczona zdobywa nagrodę w czasie, gdy jej kraju nie ma na mapie.",
    "Nagroda z fizyki w 1903 roku, druga — z chemii — w 1911. Jako pierwsza osoba w historii otrzymuje Nobla dwukrotnie i jako pierwsza kobieta w ogóle. Nazwę odkrytego pierwiastka, polonu, wybrała na cześć nieistniejącej wtedy ojczyzny.",
    ["1903", "Skłodowska-Curie", "Nobel", "polon"],
    "Kultura i nauka",
  ),
  event(
    "powstanie-wielkopolskie", 1919, "1918–1919", "druga-rp",
    "Powstanie wielkopolskie",
    "Jedno z niewielu polskich powstań zakończonych zwycięstwem.",
    "Zryw wybucha w Poznaniu w grudniu 1918 roku i przynosi kontrolę nad Wielkopolską, potwierdzoną potem traktatem wersalskim. W polskiej pamięci zajmuje osobne miejsce właśnie dlatego, że się powiódł.",
    ["1918", "Poznań", "powstanie wielkopolskie"],
  ),
  event(
    "powstania-slaskie", 1921, "1919–1921", "druga-rp",
    "Powstania śląskie",
    "Trzy zrywy i plebiscyt rozstrzygają o Górnym Śląsku.",
    "Po plebiscycie, w którym głosy rozłożyły się blisko, trzy kolejne powstania doprowadzają do podziału Górnego Śląska. Polsce przypada mniejsza, ale uprzemysłowiona część regionu — kopalnie i huty, na których oprze się gospodarka międzywojnia.",
    ["1921", "Śląsk", "plebiscyt", "powstania śląskie"],
  ),
  event(
    "bitwa-warszawska", 1920, "sierpień 1920", "druga-rp",
    "Bitwa Warszawska",
    "Kontrofensywa zatrzymuje ofensywę bolszewicką na zachód.",
    "Po odwrocie znad Kijowa Armia Czerwona podchodzi pod Warszawę. Manewr znad Wieprza rozbija jej skrzydło i odwraca losy wojny. Bitwę nazywa się cudem nad Wisłą; 15 sierpnia jest dziś Świętem Wojska Polskiego.",
    ["1920", "Bitwa Warszawska", "cud nad Wisłą", "15 sierpnia"],
  ),
  event(
    "konstytucja-marcowa", 1921, "17 marca 1921", "druga-rp",
    "Konstytucja marcowa",
    "Młode państwo dostaje ustrój republiki parlamentarnej.",
    "Konstytucja daje szeroką władzę sejmowi i słabą prezydentowi — wzorem jest Francja. Ustrój okaże się chwiejny: rządy zmieniają się często, a w 1926 roku Piłsudski przeprowadza zamach majowy.",
    ["1921", "konstytucja marcowa", "parlamentaryzm"],
    "Ustrój",
  ),
  event(
    "reforma-grabskiego", 1924, "1924", "druga-rp",
    "Reforma Grabskiego i złoty",
    "Cztery waluty i hiperinflacja ustępują jednemu pieniądzowi.",
    "Władysław Grabski przeprowadza reformę walutową i skarbową: powstaje Bank Polski i nowa waluta — złoty. To jeden z warunków scalenia trzech odziedziczonych po zaborcach gospodarek w jedną.",
    ["1924", "Grabski", "złoty", "Bank Polski"],
    "Gospodarka",
  ),
  event(
    "gdynia", 1926, "od 1926", "druga-rp",
    "Budowa portu w Gdyni",
    "Państwo buduje od podstaw własny port nad Bałtykiem.",
    "Gdańsk jest Wolnym Miastem i nie podlega Polsce, więc kraj stawia własny port w rybackiej wsi. W ciągu dekady Gdynia staje się jednym z najnowocześniejszych portów Bałtyku i symbolem gospodarczych ambicji międzywojnia.",
    ["1926", "Gdynia", "port", "Bałtyk"],
    "Gospodarka",
  ),
  event(
    "zamach-majowy", 1926, "maj 1926", "druga-rp",
    "Zamach majowy",
    "Piłsudski przejmuje władzę siłą; zaczyna się sanacja.",
    "Po trzech dniach walk w Warszawie władzę przejmuje obóz Piłsudskiego. Formalnie republika trwa, ale rola parlamentu maleje, a opozycja bywa więziona. Okres ten nazywa się sanacją, czyli uzdrowieniem.",
    ["1926", "zamach majowy", "Piłsudski", "sanacja"],
    "Ustrój",
  ),
  event(
    "wrzesien-1939", 1939, "1 i 17 września 1939", "wojna-prl",
    "Napaść Niemiec i ZSRR",
    "Dwa ataki w niecały miesiąc dzielą państwo między okupantów.",
    "1 września Niemcy atakują od zachodu, zaczynając II wojnę światową ostrzałem Westerplatte. 17 września od wschodu wkracza Związek Radziecki, wykonując tajny protokół paktu Ribbentrop–Mołotow. Rząd przenosi się za granicę; walka trwa dalej poza krajem i w podziemiu.",
    ["1939", "Westerplatte", "Ribbentrop-Mołotow", "wrzesień"],
  ),
  event(
    "katyn", 1940, "wiosna 1940", "wojna-prl",
    "Zbrodnia katyńska",
    "NKWD morduje blisko 22 tysiące polskich oficerów i urzędników.",
    "Jeńców z obozów w Kozielsku, Starobielsku i Ostaszkowie rozstrzeliwuje się w Katyniu, Charkowie i Twerze. Przez pół wieku ZSRR obarczał odpowiedzialnością Niemcy; przyznanie się nastąpiło dopiero w 1990 roku.",
    ["1940", "Katyń", "NKWD", "oficerowie"],
  ),
  event(
    "getto", 1943, "kwiecień 1943", "wojna-prl",
    "Powstanie w getcie warszawskim",
    "Zryw podjęty bez szans na zwycięstwo, by zginąć z bronią w ręku.",
    "Po wywiezieniu do Treblinki blisko trzystu tysięcy mieszkańców getta pozostali podejmują walkę. Opór trwa blisko miesiąc, a dzielnicę Niemcy palą dom po domu. To pierwsze miejskie powstanie w okupowanej Europie.",
    ["1943", "getto", "Warszawa", "Zagłada"],
  ),
  event(
    "monte-cassino", 1944, "maj 1944", "wojna-prl",
    "Zdobycie Monte Cassino",
    "Żołnierze generała Andersa otwierają aliantom drogę na Rzym.",
    "Po czterech nieudanych szturmach klasztor zdobywa 2 Korpus Polski. Żołnierze przeszli wcześniej z sowieckich łagrów przez Bliski Wschód. Bitwa jest jednym z najbardziej znanych polskich epizodów wojny na Zachodzie.",
    ["1944", "Monte Cassino", "Anders", "2 Korpus"],
  ),
  event(
    "powstanie-warszawskie", 1944, "1 sierpnia 1944", "wojna-prl",
    "Powstanie Warszawskie",
    "63 dni walki, po których miasto zostaje celowo zburzone.",
    "Armia Krajowa podejmuje walkę o Warszawę, licząc na rychłe wejście frontu. Front zatrzymuje się na Wiśle. Po kapitulacji ludność zostaje wypędzona, a miasto systematycznie wysadzone. Zginęło około 180 tysięcy cywilów.",
    ["1944", "Powstanie Warszawskie", "Armia Krajowa", "1 sierpnia"],
  ),
  event(
    "granice-1945", 1945, "1945", "wojna-prl",
    "Nowe granice i przesiedlenia",
    "Państwo przesuwa się na zachód, miliony ludzi zmieniają miejsce.",
    "Konferencje w Jałcie i Poczdamie przesuwają Polskę na zachód: kraj traci Kresy Wschodnie, zyskuje ziemie nad Odrą i Bałtykiem. Miliony ludzi zostają przesiedlone w obie strony. Kraj po raz pierwszy w historii jest niemal jednolity narodowościowo.",
    ["1945", "Jałta", "Poczdam", "przesiedlenia"],
    "Polska w świecie",
  ),
  event(
    "poznan-1956", 1956, "czerwiec 1956", "wojna-prl",
    "Poznański Czerwiec",
    "Pierwszy masowy protest robotniczy w PRL, stłumiony wojskiem.",
    "Robotnicy Zakładów Cegielskiego wychodzą na ulice, żądając chleba i wolności. Protest tłumią czołgi; giną dziesiątki osób, wśród nich trzynastoletni chłopiec. Wstrząs przyspiesza polityczną odwilż jesienią tego samego roku.",
    ["1956", "Poznań", "protest", "odwilż"],
  ),
  event(
    "grudzien-1970", 1970, "grudzień 1970", "wojna-prl",
    "Grudzień na Wybrzeżu",
    "Strajki przeciw podwyżkom cen kończą się strzałami do robotników.",
    "Podwyżka cen żywności tuż przed świętami wywołuje strajki w Gdańsku, Gdyni, Szczecinie i Elblągu. Wojsko otwiera ogień; giną dziesiątki ludzi. Władzę traci Władysław Gomułka, obejmuje ją Edward Gierek.",
    ["1970", "Wybrzeże", "Gdynia", "strajki"],
  ),
  event(
    "papiez", 1978, "16 października 1978", "wojna-prl",
    "Wybór Karola Wojtyły na papieża",
    "Pierwszy od czterystu pięćdziesięciu lat papież spoza Włoch pochodzi z Polski.",
    "Wybór kardynała z Krakowa i jego pielgrzymka do kraju rok później gromadzą miliony ludzi. Dla wielu badaczy jest to jeden z warunków tego, co wydarzyło się w sierpniu 1980 roku.",
    ["1978", "Jan Paweł II", "Wojtyła", "pielgrzymka"],
    "Kultura i nauka",
  ),
  event(
    "solidarnosc", 1980, "sierpień 1980", "wojna-prl",
    "Porozumienia sierpniowe i Solidarność",
    "Powstaje pierwszy niezależny związek zawodowy w bloku wschodnim.",
    "Strajk w Stoczni Gdańskiej rozlewa się na cały kraj i kończy porozumieniem z władzą. Powstaje NSZZ „Solidarność” z Lechem Wałęsą na czele — w szczycie blisko dziesięć milionów członków, w kraju liczącym trzydzieści sześć milionów mieszkańców.",
    ["1980", "Solidarność", "Wałęsa", "stocznia"],
    "Ustrój",
  ),
  event(
    "stan-wojenny", 1981, "13 grudnia 1981", "wojna-prl",
    "Stan wojenny",
    "Wojsko przejmuje kontrolę, Solidarność zostaje zdelegalizowana.",
    "Generał Jaruzelski ogłasza stan wojenny w niedzielny poranek. Tysiące działaczy trafia do ośrodków internowania, łączność telefoniczna zostaje wyłączona, na ulicach stają czołgi. Związek działa dalej w podziemiu przez kolejne osiem lat.",
    ["1981", "stan wojenny", "Jaruzelski", "internowania"],
  ),
  event(
    "okragly-stol", 1989, "luty–kwiecień 1989", "wojna-prl",
    "Okrągły Stół",
    "Władza i opozycja uzgadniają częściowo wolne wybory.",
    "Rozmowy trwają dwa miesiące i kończą się porozumieniem: 35 procent miejsc w Sejmie w wolnych wyborach, Senat w całości wolny, Solidarność znów legalna. To model przemiany bez rozlewu krwi, powtórzony potem w innych krajach regionu.",
    ["1989", "Okrągły Stół", "negocjacje"],
    "Ustrój",
  ),
  event(
    "mazowiecki", 1989, "wrzesień 1989", "trzecia-rp",
    "Rząd Tadeusza Mazowieckiego",
    "Pierwszy niekomunistyczny premier w bloku wschodnim od czterdziestu lat.",
    "Po wyborach czerwcowych Sejm powołuje rząd Tadeusza Mazowieckiego. W ciągu kilku miesięcy zapadają decyzje o przejściu do gospodarki rynkowej, a jesienią następnego roku odbywają się pierwsze powszechne wybory prezydenckie.",
    ["1989", "Mazowiecki", "rząd", "przemiana"],
    "Ustrój",
  ),
  event(
    "balcerowicz", 1990, "1990", "trzecia-rp",
    "Plan Balcerowicza",
    "Gospodarka planowana ustępuje rynkowej w ciągu kilku miesięcy.",
    "Pakiet ustaw uwalnia ceny, otwiera handel zagraniczny i zbija hiperinflację. Cena jest wysoka: część zakładów upada, rośnie bezrobocie. Znikają jednak kolejki i puste półki, a prywatne firmy powstają masowo.",
    ["1990", "Balcerowicz", "reformy", "rynek"],
    "Gospodarka",
  ),
  event(
    "samorzad-1990", 1990, "maj 1990", "trzecia-rp",
    "Pierwsze wolne wybory samorządowe",
    "Odradza się gmina jako wspólnota decydująca o sobie.",
    "Po czterdziestu latach centralnego zarządzania gmina znów sama wybiera władze i dysponuje własnym budżetem. Reforma uchodzi za jedną z najbardziej udanych przemian tego okresu; powiaty i województwa wrócą dziewięć lat później.",
    ["1990", "samorząd", "gmina", "wybory"],
    "Ustrój",
  ),
  event(
    "konstytucja-1997", 1997, "2 kwietnia 1997", "trzecia-rp",
    "Konstytucja Rzeczypospolitej Polskiej",
    "Nowa ustawa zasadnicza zastępuje poprawianą konstytucję z 1952 roku.",
    "Zgromadzenie Narodowe uchwala Konstytucję, a obywatele potwierdzają ją w referendum. Dokument zapisuje podział władz, szeroki katalog wolności i prawa oraz konstruktywne wotum nieufności. Obowiązuje do dziś.",
    ["1997", "Konstytucja", "referendum"],
    "Ustrój",
  ),
  event(
    "nato", 1999, "12 marca 1999", "trzecia-rp",
    "Wejście do NATO",
    "Polska wstępuje do sojuszu razem z Czechami i Węgrami.",
    "Osiem lat po rozwiązaniu Układu Warszawskiego kraj wchodzi do zachodniego sojuszu obronnego. Tego samego roku reforma administracyjna zmniejsza liczbę województw z 49 do 16 i przywraca powiaty.",
    ["1999", "NATO", "sojusz", "reforma"],
    "Polska w świecie",
  ),
  event(
    "schengen", 2007, "21 grudnia 2007", "trzecia-rp",
    "Wejście do strefy Schengen",
    "Kontrole na granicach wewnętrznych Unii znikają.",
    "Trzy lata po wejściu do Unii przestają działać kontrole na granicach z Niemcami, Czechami, Słowacją i Litwą. Granica wschodnia staje się tym samym zewnętrzną granicą strefy.",
    ["2007", "Schengen", "granice"],
    "Polska w świecie",
  ),
  event(
    "smolensk", 2010, "10 kwietnia 2010", "trzecia-rp",
    "Katastrofa smoleńska",
    "Ginie prezydent i 95 innych osób lecących na obchody rocznicy Katynia.",
    "Samolot z delegacją państwową rozbija się przy podejściu do lądowania pod Smoleńskiem. Wśród ofiar są prezydent Lech Kaczyński z małżonką, dowódcy wojskowi, posłowie i rodziny katyńskie. Obowiązki prezydenta przejmuje Marszałek Sejmu.",
    ["2010", "Smoleńsk", "katastrofa", "Katyń"],
  ),
  event(
    "uchodzcy-2022", 2022, "od lutego 2022", "trzecia-rp",
    "Pomoc uchodźcom z Ukrainy",
    "Największy ruch ludności w regionie od czasów II wojny światowej.",
    "Po pełnoskalowej agresji Rosji na Ukrainę granicę przekraczają miliony osób. Kilkaset tysięcy zostaje na dłużej; dzieci trafiają do polskich szkół, dorośli na rynek pracy. Pomoc organizują w pierwszych tygodniach głównie zwykli ludzie i samorządy.",
    ["2022", "Ukraina", "uchodźcy", "pomoc"],
    "Polska w świecie",
  ),
];
