import type { Course } from "@/lib/courses";

/**
 * Życie w Polsce.
 *
 * Czwarty kurs w dziale Country studies, zbudowany według tego samego wzoru
 * co Life in the UK, Leben in Deutschland i Vivre en France: te same typy
 * bloków, ten sam kształt lekcji, ta sama budowa quizu. Zmienia się treść —
 * i język, bo każdy z tych kursów jest napisany w języku swojego kraju.
 *
 * NIE MA POLSKIEGO EGZAMINU OBYWATELSKIEGO. Tamte trzy kursy odwzorowują
 * istniejące egzaminy państwowe. Polska takiego egzaminu nie ma: przy
 * uznaniu za obywatela polskiego wymagany jest certyfikat znajomości języka
 * polskiego na poziomie B1, czyli egzamin JĘZYKOWY, nie wiedzy o kraju.
 * Test wiedzy obywatelskiej był w 2025 roku proponowany, ale nie wszedł w
 * życie. Ten kurs zatem niczego nie odwzorowuje i do niczego nie przygotowuje
 * — liczby w polu `exam` są liczbami tego kursu, a nie żadnego państwa.
 *
 * DLATEGO INNY DOBÓR TREŚCI. Pozostałe kursy pytają "co może paść na
 * egzaminie". Ten pyta "co warto wiedzieć, żeby rozumieć Polskę": historia,
 * ustrój, regiony, święta, codzienność, kultura. Szerokość zamiast gęstości
 * egzaminacyjnej.
 *
 * PIĘĆ ROZDZIAŁÓW:
 *   1. Symbole i wartości Rzeczypospolitej
 *   2. Ustrój i instytucje
 *   3. Historia Polski
 *   4. Geografia, gospodarka i Polska w świecie
 *   5. Społeczeństwo i życie codzienne
 *
 * ŹRÓDŁA są publiczne: Konstytucja Rzeczypospolitej Polskiej, strony Sejmu,
 * Senatu i Kancelarii Prezydenta, gov.pl, Główny Urząd Statystyczny oraz
 * podstawa programowa przedmiotu "wiedza o społeczeństwie" i portal
 * zpe.gov.pl. Przejęte są fakty — daty, instytucje, liczby. Sformułowania,
 * pytania i wyjaśnienia są pisane tutaj; żaden katalog nie jest przepisywany.
 */
export const zycieWPolsceCourse: Course = {
  id: "zycie-w-polsce",
  kind: "citizenship",
  name: "Poland – Land and Culture",
  tagline: "Historia, ustrój i codzienność — jak działa ten kraj.",
  icon: "🇵🇱",
  available: true,
  lessons: [
    // ══ Rozdział 1: Symbole i wartości Rzeczypospolitej ═══════════════════
    {
      id: "pl-symbole",
      title: "Symbole narodowe",
      section: "Symbole i wartości Rzeczypospolitej",
      badge: "lekcja 1",
      blocks: [
        { type: "callout", variant: "why", text: "Dlaczego od tego zaczynamy: symbole widuje się codziennie — na urzędzie, na paszporcie, na koszulce reprezentacji — więc są najłatwiejszym wejściem w resztę." },
        { type: "h3", text: "Godło" },
        { type: "p", text: "Godłem Polski jest **orzeł biały** w złotej koronie, ze złotym dziobem i szponami, na **czerwonym** tle. Opisuje go **artykuł 28 Konstytucji**. Korona wróciła na głowę orła w **1990 roku**; w czasach PRL orzeł jej nie miał." },
        { type: "h3", text: "Flaga i barwy" },
        { type: "p", text: "Flaga ma dwa poziome pasy: **biały u góry, czerwony u dołu**. Kolejność nie jest dowolna — biel jest zawsze nad czerwienią. **2 maja** obchodzi się Dzień Flagi Rzeczypospolitej Polskiej." },
        { type: "h3", text: "Hymn" },
        { type: "cards", items: [
          { h4: "Mazurek Dąbrowskiego", p: "Hymn państwowy, powstały w 1797 roku we Włoszech, w Legionach Polskich. Słowa napisał Józef Wybicki." },
          { h4: "Pierwsze słowa", p: "„Jeszcze Polska nie zginęła, kiedy my żyjemy” — zdanie napisane wtedy, gdy państwa polskiego na mapie nie było." },
        ] },
        { type: "quiz",
          q: "Który kolor znajduje się na fladze Polski u góry?",
          options: [
            { text: "Czerwony", correct: false },
            { text: "Biały", correct: true },
            { text: "Kolejność jest dowolna", correct: false },
            { text: "Złoty", correct: false },
          ],
          explanation: "Biały pas jest zawsze na górze, czerwony na dole. Odwrócona flaga to flaga Indonezji lub Monako." },
        { type: "h3", text: "Barwy i ich użycie" },
        { type: "p", text: "Flagi używa się w dni świąt państwowych, na budynkach urzędów i podczas uroczystości. Wersję z **godłem** na białym pasie stosują polskie statki i placówki dyplomatyczne — nie wywiesza się jej na balkonie." },
        { type: "h3", text: "Skąd wzięły się barwy" },
        { type: "p", text: "Biel od orła, czerwień od pola herbowego. Ustalono je oficjalnie **7 lutego 1831 roku**, w czasie powstania listopadowego — barwy narodowe są więc młodsze niż sam herb o kilkaset lat." },
        { type: "quiz",
          q: "Kto napisał słowa hymnu Polski?",
          options: [
            { text: "Adam Mickiewicz", correct: false },
            { text: "Józef Wybicki", correct: true },
            { text: "Fryderyk Chopin", correct: false },
            { text: "Juliusz Słowacki", correct: false },
          ],
          explanation: "Józef Wybicki, w 1797 roku we Włoszech. Mickiewicz i Słowacki to poeci romantyczni, Chopin kompozytor." },      ],
    },
    {
      id: "pl-konstytucja",
      title: "Konstytucja i wartości ustrojowe",
      section: "Symbole i wartości Rzeczypospolitej",
      badge: "lekcja 2",
      blocks: [
        { type: "h3", text: "Konstytucja z 1997 roku" },
        { type: "p", text: "Obowiązująca **Konstytucja Rzeczypospolitej Polskiej** została uchwalona **2 kwietnia 1997 roku** i przyjęta w referendum. Jest najwyższym prawem w państwie: żadna ustawa nie może być z nią sprzeczna." },
        { type: "h3", text: "Zasady ustrojowe" },
        { type: "cards", items: [
          { h4: "Republika", p: "Polska jest republiką — głowę państwa się wybiera, a nie dziedziczy." },
          { h4: "Państwo prawa", p: "Organy władzy działają na podstawie i w granicach prawa, nie poza nim." },
          { h4: "Podział władz", p: "Ustawodawcza, wykonawcza i sądownicza są rozdzielone i wzajemnie się równoważą." },
        ] },
        { type: "callout", variant: "warn", text: "Konstytucja to nie zbiór życzeń: sprzeczną z nią ustawę może uchylić **Trybunał Konstytucyjny**." },
        { type: "quiz",
          q: "W którym roku uchwalono obowiązującą Konstytucję RP?",
          options: [
            { text: "1989", correct: false },
            { text: "1997", correct: true },
            { text: "2004", correct: false },
            { text: "1952", correct: false },
          ],
          explanation: "2 kwietnia 1997 roku, potwierdzona w referendum. 1989 to rok wyborów czerwcowych, 2004 to wejście do Unii Europejskiej." },
        { type: "h3", text: "Jak zmienić Konstytucję" },
        { type: "p", text: "Zmiana wymaga większości **2/3** w Sejmie i bezwzględnej w Senacie. Jeśli dotyczy rozdziałów o ustroju, wolnościach albo o samej procedurze zmiany, można zażądać jeszcze **referendum**." },
        { type: "h3", text: "Poprzednie konstytucje" },
        { type: "cards", items: [
          { h4: "3 maja 1791", p: "Pierwsza w Europie, obowiązywała czternaście miesięcy." },
          { h4: "Marcowa 1921", p: "Republika parlamentarna II Rzeczypospolitej." },
          { h4: "Kwietniowa 1935", p: "Wzmocniła prezydenta kosztem parlamentu." },
          { h4: "Z 1952", p: "Konstytucja PRL, zmieniana wielokrotnie, obowiązywała do 1997 roku." },
        ] },
        { type: "quiz",
          q: "Jakiej większości w Sejmie wymaga zmiana Konstytucji?",
          options: [
            { text: "Zwykłej", correct: false },
            { text: "Bezwzględnej", correct: false },
            { text: "Dwóch trzecich", correct: true },
            { text: "Jednomyślności", correct: false },
          ],
          explanation: "Dwóch trzecich w Sejmie i bezwzględnej w Senacie — próg wyraźnie wyższy niż przy zwykłej ustawie." },      ],
    },
    {
      id: "pl-prawa",
      title: "Prawa i wolności",
      section: "Symbole i wartości Rzeczypospolitej",
      badge: "lekcja 3",
      blocks: [
        { type: "callout", variant: "why", text: "Rozdział II Konstytucji jest najdłuższy w całym dokumencie. To nie przypadek: państwo, które przez pół wieku ograniczało wolności, spisało je potem wyjątkowo dokładnie." },
        { type: "h3", text: "Wolności osobiste" },
        { type: "p", text: "Każdemu przysługuje **prawo do życia**, **nietykalność osobista** i **wolność sumienia**. Nikogo nie wolno zatrzymać bez podstawy prawnej, a zatrzymanego trzeba w ciągu **48 godzin** przekazać sądowi — inaczej musi zostać zwolniony." },
        { type: "p", text: "Obowiązuje **domniemanie niewinności**: dopóki sąd nie orzeknie prawomocnie, człowiek jest niewinny. Kara może spotkać tylko za czyn, który był zabroniony **w chwili popełnienia**." },
        { type: "h3", text: "Wolności polityczne" },
        { type: "cards", items: [
          { h4: "Wolność słowa", p: "Wolno wyrażać poglądy i rozpowszechniać informacje. Cenzura prewencyjna jest zakazana." },
          { h4: "Zgromadzenia", p: "Wolno organizować pokojowe zgromadzenia i w nich uczestniczyć." },
          { h4: "Zrzeszanie się", p: "Wolno tworzyć partie, związki zawodowe i stowarzyszenia." },
          { h4: "Petycje", p: "Każdy może kierować wnioski i skargi do organów władzy publicznej." },
        ] },
        { type: "h3", text: "Prawa socjalne" },
        { type: "p", text: "Konstytucja mówi też o **prawie do nauki** — obowiązkowej i bezpłatnej w szkołach publicznych do 18. roku życia — o **ochronie zdrowia** i o **prawie do zabezpieczenia społecznego** na starość, w chorobie i przy bezrobociu." },
        { type: "h3", text: "Kto broni tych praw" },
        { type: "p", text: "**Rzecznik Praw Obywatelskich** stoi na straży wolności i praw człowieka. Można się do niego zwrócić bezpłatnie, także pisemnie. Osobno działa **Rzecznik Praw Dziecka**." },
        { type: "callout", variant: "warn", text: "Wolności nie są nieograniczone. Ograniczyć je może tylko **ustawa** i tylko wtedy, gdy jest to konieczne dla bezpieczeństwa, porządku publicznego, zdrowia albo wolności innych osób. Nigdy nie wolno naruszyć **istoty** danej wolności." },
        { type: "quiz",
          q: "W ciągu ilu godzin zatrzymany musi zostać przekazany sądowi?",
          options: [
            { text: "24 godzin", correct: false },
            { text: "48 godzin", correct: true },
            { text: "72 godzin", correct: false },
            { text: "Nie ma takiego terminu", correct: false },
          ],
          explanation: "48 godzin. Sąd ma potem 24 godziny na decyzję o tymczasowym aresztowaniu — razem najwyżej 72." },
        { type: "h3", text: "Skarga konstytucyjna" },
        { type: "p", text: "Kto uważa, że jego wolność naruszył **przepis**, a nie sam wyrok, może po wyczerpaniu drogi sądowej złożyć **skargę konstytucyjną** do Trybunału Konstytucyjnego. Skargę sporządza adwokat albo radca prawny." },
        { type: "h3", text: "Ochrona danych" },
        { type: "p", text: "Od 2018 roku obowiązuje europejskie rozporządzenie **RODO**. Każdy ma prawo wiedzieć, jakie dane o nim zebrano, żądać ich poprawienia i — w wielu wypadkach — usunięcia. Nadzoruje to **Prezes Urzędu Ochrony Danych Osobowych**." },
        { type: "quiz",
          q: "Do kogo można się zwrócić bezpłatnie, gdy urząd narusza prawa obywatela?",
          options: [
            { text: "Do Rzecznika Praw Obywatelskich", correct: true },
            { text: "Do wojewody", correct: false },
            { text: "Do Prezydenta", correct: false },
            { text: "Do Najwyższej Izby Kontroli", correct: false },
          ],
          explanation: "Rzecznik Praw Obywatelskich stoi na straży wolności i praw; wniosek jest wolny od opłat." },      ],
    },
    {
      id: "pl-obowiazki",
      title: "Obowiązki obywatela",
      section: "Symbole i wartości Rzeczypospolitej",
      badge: "lekcja 4",
      blocks: [
        { type: "h3", text: "Wierność i troska o dobro wspólne" },
        { type: "p", text: "Konstytucja wymienia obowiązki krótko, w kilku artykułach. Pierwszy z nich to **wierność Rzeczypospolitej** i troska o **dobro wspólne** — sformułowanie ogólne, ale to z niego wynikają pozostałe." },
        { type: "h3", text: "Obowiązki konkretne" },
        { type: "cards", items: [
          { h4: "Przestrzeganie prawa", p: "Obowiązuje każdego, kto znajduje się pod władzą Rzeczypospolitej — także cudzoziemca." },
          { h4: "Ciężary publiczne", p: "Podatki i inne świadczenia nakłada wyłącznie ustawa, nie rozporządzenie." },
          { h4: "Obrona ojczyzny", p: "Obowiązek obywateli polskich. Kto ze względu na przekonania nie może pełnić służby wojskowej, może zostać skierowany do służby zastępczej." },
          { h4: "Dbałość o środowisko", p: "Kto pogarsza stan środowiska, odpowiada za to." },
        ] },
        { type: "h3", text: "Obowiązek szkolny" },
        { type: "p", text: "Nauka jest **obowiązkowa do 18. roku życia**. Odpowiadają za to rodzice albo opiekunowie; szkoła publiczna jest bezpłatna." },
        { type: "callout", variant: "warn", text: "Obowiązkowa zasadnicza służba wojskowa została w Polsce **zawieszona w 2009 roku**. Obowiązek obrony pozostał w Konstytucji, ale pobór w czasie pokoju się nie odbywa." },
        { type: "quiz",
          q: "Do którego roku życia trwa w Polsce obowiązek nauki?",
          options: [
            { text: "Do 15. roku życia", correct: false },
            { text: "Do 16. roku życia", correct: false },
            { text: "Do 18. roku życia", correct: true },
            { text: "Do ukończenia szkoły średniej", correct: false },
          ],
          explanation: "Do 18. roku życia. Obowiązek szkolny — nauka w szkole podstawowej — kończy się wcześniej, ale obowiązek nauki trwa dłużej." },
        { type: "h3", text: "Podatki w praktyce" },
        { type: "p", text: "Zeznanie roczne **PIT** składa się do **30 kwietnia** za rok poprzedni. Można to zrobić przez internet; urząd skarbowy przygotowuje wstępnie wypełnione zeznanie, które wystarczy sprawdzić i zatwierdzić." },
        { type: "h3", text: "Udział w wyborach" },
        { type: "callout", variant: "warn", text: "Głosowanie jest **prawem, nie obowiązkiem** — nie ma kary za nieoddanie głosu. Prawo wybierania przysługuje od 18. roku życia, także obywatelom mieszkającym za granicą, w obwodach przy placówkach dyplomatycznych." },
        { type: "quiz",
          q: "Do kiedy składa się roczne zeznanie podatkowe PIT?",
          options: [
            { text: "Do 31 stycznia", correct: false },
            { text: "Do 30 kwietnia", correct: true },
            { text: "Do 30 czerwca", correct: false },
            { text: "Do 31 grudnia", correct: false },
          ],
          explanation: "Do 30 kwietnia za rok poprzedni." },      ],
    },
    // ══ Rozdział 2: Ustrój i instytucje ═══════════════════════════════════
    {
      id: "pl-sejm-senat",
      title: "Sejm i Senat",
      section: "Ustrój i instytucje",
      badge: "lekcja 5",
      blocks: [
        { type: "callout", variant: "why", text: "Dwie izby, dwie różne liczby i dwie różne role. Mylenie ich to najczęstsza pomyłka w rozmowie o polskiej polityce." },
        { type: "h3", text: "Dwie izby parlamentu" },
        { type: "cards", items: [
          { h4: "Sejm", p: "460 posłów, wybieranych na 4 lata. Izba pierwsza: to tutaj powstają i zapadają rozstrzygnięcia." },
          { h4: "Senat", p: "100 senatorów, również na 4 lata. Izba druga: poprawia, odrzuca albo przyjmuje ustawy Sejmu." },
        ] },
        { type: "h3", text: "Kto może kandydować" },
        { type: "p", text: "Posłem może zostać obywatel, który ukończył **21 lat**; senatorem — **30 lat**. Głosować wolno od **18. roku życia**. Mandatu poselskiego nie można łączyć z senatorskim." },
        { type: "h3", text: "Jak powstaje ustawa" },
        { type: "p", text: "Projekt trafia do Sejmu, który czyta go i głosuje. Przyjęty projekt idzie do **Senatu**: ten ma **30 dni**, żeby go przyjąć, odrzucić albo poprawić. Poprawki i odrzucenie Sejm może **odrzucić bezwzględną większością**. Na końcu ustawę podpisuje **Prezydent**." },
        { type: "callout", variant: "warn", text: "Inicjatywę ustawodawczą mają posłowie, Senat, Prezydent, Rada Ministrów — a także **100 tysięcy obywateli**, którzy złożą podpisy pod projektem." },
        { type: "h3", text: "Zgromadzenie Narodowe" },
        { type: "p", text: "Sejm i Senat obradujące wspólnie tworzą **Zgromadzenie Narodowe**. Zbiera się rzadko: żeby odebrać przysięgę od Prezydenta, uznać go za trwale niezdolnego do sprawowania urzędu albo postawić przed Trybunałem Stanu." },
        { type: "quiz",
          q: "Ilu posłów zasiada w Sejmie?",
          options: [
            { text: "100", correct: false },
            { text: "230", correct: false },
            { text: "460", correct: true },
            { text: "560", correct: false },
          ],
          explanation: "460 posłów. 100 to liczba senatorów; razem obie izby liczą 560 osób." },
        { type: "h3", text: "Jak się głosuje" },
        { type: "p", text: "Do Sejmu wybiera się **proporcjonalnie**, z list w okręgach; mandaty dzieli się metodą **d'Hondta**, a partia musi przekroczyć próg **5 procent** (koalicja 8). Do Senatu głosuje się **większościowo**: w każdym ze stu okręgów wygrywa jeden kandydat." },
        { type: "h3", text: "Immunitet" },
        { type: "p", text: "Posła ani senatora nie można pociągnąć do odpowiedzialności karnej bez zgody własnej izby. Immunitet chroni mandat, a nie osobę: izba może go **uchylić**." },
        { type: "quiz",
          q: "Ilu senatorów liczy Senat?",
          options: [
            { text: "100", correct: true },
            { text: "230", correct: false },
            { text: "460", correct: false },
            { text: "560", correct: false },
          ],
          explanation: "100 senatorów, po jednym z każdego okręgu. 460 to liczba posłów." },      ],
    },
    {
      id: "pl-prezydent",
      title: "Prezydent",
      section: "Ustrój i instytucje",
      badge: "lekcja 6",
      blocks: [
        { type: "h3", text: "Wybór i kadencja" },
        { type: "p", text: "Prezydenta wybierają obywatele w **wyborach powszechnych**, na **5 lat**, najwyżej **dwa razy**. Kandydat musi mieć ukończone **35 lat** i zebrać **100 tysięcy podpisów**. Wygrywa ten, kto uzyska ponad połowę głosów; jeśli nikt nie uzyska, po dwóch tygodniach odbywa się **druga tura** między dwoma najlepszymi." },
        { type: "h3", text: "Co Prezydent może" },
        { type: "cards", items: [
          { h4: "Podpisać albo nie", p: "Ustawę podpisuje w ciągu 21 dni. Może ją zawetować albo skierować do Trybunału Konstytucyjnego." },
          { h4: "Weto", p: "Weto Sejm odrzuca większością 3/5 głosów. Ustawy skierowanej do Trybunału zawetować już nie można." },
          { h4: "Powołania", p: "Powołuje Prezesa Rady Ministrów, sędziów na wniosek Krajowej Rady Sądownictwa i ratyfikuje umowy międzynarodowe." },
          { h4: "Zwierzchnictwo", p: "Jest najwyższym zwierzchnikiem Sił Zbrojnych; w czasie pokoju sprawuje je przez Ministra Obrony Narodowej." },
        ] },
        { type: "h3", text: "Kontrasygnata" },
        { type: "p", text: "Większość aktów urzędowych Prezydenta wymaga **podpisu Prezesa Rady Ministrów**, który bierze za nie odpowiedzialność przed Sejmem. Konstytucja wylicza jednak **prerogatywy** — akty, których kontrasygnata nie dotyczy, na przykład prawo łaski, zarządzenie wyborów czy nadanie obywatelstwa." },
        { type: "callout", variant: "warn", text: "Prezydent nie kieruje rządem. Politykę bieżącą prowadzi **Rada Ministrów**; Prezydent reprezentuje państwo i stoi na straży Konstytucji." },
        { type: "quiz",
          q: "Na ile lat wybiera się Prezydenta Rzeczypospolitej?",
          options: [
            { text: "4 lata", correct: false },
            { text: "5 lat", correct: true },
            { text: "6 lat", correct: false },
            { text: "7 lat", correct: false },
          ],
          explanation: "5 lat, najwyżej dwie kadencje. 4 lata trwa kadencja Sejmu i Senatu." },
        { type: "h3", text: "Gdy Prezydenta zabraknie" },
        { type: "p", text: "Jeśli Prezydent nie może sprawować urzędu, zastępuje go **Marszałek Sejmu**, a gdyby i on nie mógł — Marszałek Senatu. Tak stało się w kwietniu 2010 roku po katastrofie smoleńskiej." },
        { type: "h3", text: "Rezydencja i przysięga" },
        { type: "p", text: "Siedzibą Prezydenta jest **Pałac Prezydencki** w Warszawie. Urząd obejmuje po złożeniu przysięgi przed **Zgromadzeniem Narodowym**." },
        { type: "quiz",
          q: "Jaką większością Sejm odrzuca weto Prezydenta?",
          options: [
            { text: "Zwykłą", correct: false },
            { text: "Bezwzględną", correct: false },
            { text: "Trzech piątych", correct: true },
            { text: "Dwóch trzecich", correct: false },
          ],
          explanation: "Trzech piątych głosów. Dwie trzecie potrzebne są do zmiany Konstytucji." },      ],
    },
    {
      id: "pl-rzad",
      title: "Rada Ministrów",
      section: "Ustrój i instytucje",
      badge: "lekcja 7",
      blocks: [
        { type: "h3", text: "Kto rządzi na co dzień" },
        { type: "p", text: "**Rada Ministrów** — czyli rząd — prowadzi politykę wewnętrzną i zagraniczną państwa. Na jej czele stoi **Prezes Rady Ministrów**, w mowie potocznej premier. W skład wchodzą ministrowie kierujący działami administracji." },
        { type: "h3", text: "Jak powstaje rząd" },
        { type: "p", text: "Prezydent desygnuje premiera, ten proponuje skład rządu, a Sejm udziela mu **wotum zaufania** bezwzględną większością. Gdy się nie uda, inicjatywę przejmuje Sejm — Konstytucja przewiduje **trzy kolejne kroki**, żeby państwo nie zostało bez rządu." },
        { type: "h3", text: "Jak rząd upada" },
        { type: "callout", variant: "warn", text: "**Konstruktywne wotum nieufności**: Sejm może odwołać rząd tylko wtedy, gdy jednocześnie wskaże nowego premiera. Nie da się obalić rządu, nie mając następcy — to zabezpieczenie wzięte z niemieckiej Ustawy Zasadniczej." },
        { type: "h3", text: "Kto pilnuje rządu" },
        { type: "cards", items: [
          { h4: "Sejm", p: "Uchwala budżet, pyta w interpelacjach, odwołuje ministrów." },
          { h4: "Najwyższa Izba Kontroli", p: "Bada wydatki państwa i podlega Sejmowi, nie rządowi." },
          { h4: "Trybunał Stanu", p: "Sądzi najwyższych urzędników za naruszenie Konstytucji lub ustawy." },
        ] },
        { type: "quiz",
          q: "Czego wymaga konstruktywne wotum nieufności?",
          options: [
            { text: "Zgody Prezydenta", correct: false },
            { text: "Jednoczesnego wskazania nowego premiera", correct: true },
            { text: "Rozwiązania Sejmu", correct: false },
            { text: "Większości 2/3 głosów", correct: false },
          ],
          explanation: "Sejm musi wskazać następcę. Bez tego wniosek jest bezskuteczny — państwo nie zostaje bez rządu." },
        { type: "h3", text: "Budżet" },
        { type: "p", text: "Rada Ministrów przygotowuje **ustawę budżetową** i przedkłada ją Sejmowi. Jeśli parlament nie uchwali jej w ciągu **czterech miesięcy**, Prezydent może skrócić kadencję Sejmu." },
        { type: "h3", text: "Ministerstwa" },
        { type: "p", text: "Każdy minister kieruje **działem administracji rządowej** — finansami, zdrowiem, edukacją, obroną. Podział działów określa ustawa, a nie sam premier; liczba ministerstw bywa różna w kolejnych rządach." },
        { type: "quiz",
          q: "Kto przygotowuje projekt ustawy budżetowej?",
          options: [
            { text: "Sejm", correct: false },
            { text: "Rada Ministrów", correct: true },
            { text: "Prezydent", correct: false },
            { text: "Narodowy Bank Polski", correct: false },
          ],
          explanation: "Rada Ministrów. Sejm budżet uchwala, ale sam go nie pisze." },      ],
    },
    {
      id: "pl-sady",
      title: "Sądy i Trybunały",
      section: "Ustrój i instytucje",
      badge: "lekcja 8",
      blocks: [
        { type: "h3", text: "Trzy szczeble sądów" },
        { type: "p", text: "Sprawy zaczynają się w **sądzie rejonowym**, odwołania trafiają do **okręgowego**, a dalej do **apelacyjnego**. Na szczycie stoi **Sąd Najwyższy**, który czuwa nad jednolitością orzecznictwa — nie rozpatruje spraw od początku." },
        { type: "h3", text: "Sądy administracyjne" },
        { type: "p", text: "Osobną drogą idą spory z urzędami. Skargę na decyzję rozpatruje **wojewódzki sąd administracyjny**, a skargę kasacyjną — **Naczelny Sąd Administracyjny**." },
        { type: "h3", text: "Dwa trybunały" },
        { type: "cards", items: [
          { h4: "Trybunał Konstytucyjny", p: "Orzeka, czy ustawa jest zgodna z Konstytucją. Może to zbadać na skargę konstytucyjną obywatela." },
          { h4: "Trybunał Stanu", p: "Sądzi Prezydenta, premiera i ministrów za delikty konstytucyjne — nie za zwykłe przestępstwa." },
        ] },
        { type: "h3", text: "Zasady procesu" },
        { type: "p", text: "Postępowanie jest **dwuinstancyjne**: od wyroku przysługuje odwołanie. Rozprawy są **jawne**, a wyrok ogłasza się publicznie. Sędziowie są **niezawiśli** i podlegają tylko Konstytucji oraz ustawom." },
        { type: "callout", variant: "warn", text: "Sądy powszechne rozstrzygają spory między ludźmi i sądzą przestępstwa. **Trybunał Konstytucyjny nie jest sądem odwoławczym** — nie zmieni wyroku w sprawie, przygląda się przepisowi." },
        { type: "quiz",
          q: "Który organ orzeka o zgodności ustawy z Konstytucją?",
          options: [
            { text: "Sąd Najwyższy", correct: false },
            { text: "Naczelny Sąd Administracyjny", correct: false },
            { text: "Trybunał Konstytucyjny", correct: true },
            { text: "Trybunał Stanu", correct: false },
          ],
          explanation: "Trybunał Konstytucyjny. Sąd Najwyższy czuwa nad orzecznictwem sądów, Trybunał Stanu sądzi urzędników." },
        { type: "h3", text: "Ława przysięgłych? Nie tutaj" },
        { type: "p", text: "Polska nie ma ławy przysięgłych. W części spraw obok sędziego zawodowego orzekają **ławnicy** — obywatele wybierani przez rady gmin, którzy mają przy wyrokowaniu taki sam głos jak sędzia." },
        { type: "h3", text: "Prokuratura i adwokatura" },
        { type: "cards", items: [
          { h4: "Prokurator", p: "Prowadzi postępowanie przygotowawcze i oskarża przed sądem." },
          { h4: "Adwokat i radca prawny", p: "Bronią i reprezentują. Kto nie ma środków, może dostać obrońcę z urzędu." },
          { h4: "Komornik", p: "Wykonuje prawomocne orzeczenia sądu, gdy dłużnik ich nie wypełnia." },
        ] },
        { type: "quiz",
          q: "Kto orzeka w polskim sądzie obok sędziego zawodowego w części spraw?",
          options: [
            { text: "Ława przysięgłych", correct: false },
            { text: "Ławnicy", correct: true },
            { text: "Prokurator", correct: false },
            { text: "Wojewoda", correct: false },
          ],
          explanation: "Ławnicy, wybierani przez rady gmin. Ławy przysięgłych w Polsce nie ma." },      ],
    },
    {
      id: "pl-samorzad",
      title: "Samorząd terytorialny",
      section: "Ustrój i instytucje",
      badge: "lekcja 9",
      blocks: [
        { type: "h3", text: "Trzy szczeble" },
        { type: "p", text: "Polska dzieli się na **16 województw**, te na **powiaty**, a powiaty na **gminy**. Gmina jest szczeblem podstawowym: to ona odpowiada za sprawy, których nie zastrzeżono dla innych." },
        { type: "h3", text: "Kto czym kieruje" },
        { type: "cards", items: [
          { h4: "Gmina", p: "Rada gminy i wójt, w mieście burmistrz albo prezydent miasta. Szkoły podstawowe, drogi lokalne, woda, śmieci." },
          { h4: "Powiat", p: "Rada powiatu i starosta. Szpitale powiatowe, szkoły średnie, prawa jazdy, rejestracja pojazdów." },
          { h4: "Województwo", p: "Sejmik i marszałek. Rozwój regionu, drogi wojewódzkie, fundusze europejskie." },
        ] },
        { type: "h3", text: "Wojewoda a marszałek" },
        { type: "callout", variant: "warn", text: "W województwie są **dwie** władze i łatwo je pomylić. **Marszałka** wybiera sejmik — to samorząd. **Wojewodę** powołuje premier — to przedstawiciel rządu w terenie, który nadzoruje legalność działań samorządu." },
        { type: "h3", text: "Wybory samorządowe" },
        { type: "p", text: "Radnych, wójtów, burmistrzów i prezydentów miast wybiera się co **5 lat**. Mieszkańcy mogą też odwołać wójta albo radę w **referendum lokalnym**." },
        { type: "quiz",
          q: "Kto powołuje wojewodę?",
          options: [
            { text: "Sejmik województwa", correct: false },
            { text: "Prezes Rady Ministrów", correct: true },
            { text: "Prezydent Rzeczypospolitej", correct: false },
            { text: "Mieszkańcy w wyborach", correct: false },
          ],
          explanation: "Premier. Wojewoda reprezentuje rząd; marszałka wybiera sejmik i to on kieruje samorządem województwa." },
        { type: "h3", text: "Skąd samorząd bierze pieniądze" },
        { type: "p", text: "Gminy mają **dochody własne** — podatek od nieruchomości, opłaty lokalne — oraz **udział w podatkach** PIT i CIT. Do tego dochodzą subwencje i dotacje z budżetu państwa, między innymi oświatowa." },
        { type: "h3", text: "Sołectwa i dzielnice" },
        { type: "p", text: "Wewnątrz gminy działają jednostki pomocnicze: na wsi **sołectwa** z sołtysem, w mieście **dzielnice** albo **osiedla**. Część gmin oddaje mieszkańcom do rozdysponowania **budżet obywatelski**." },
        { type: "quiz",
          q: "Który szczebel samorządu odpowiada za szkoły podstawowe?",
          options: [
            { text: "Gmina", correct: true },
            { text: "Powiat", correct: false },
            { text: "Województwo", correct: false },
            { text: "Państwo", correct: false },
          ],
          explanation: "Gmina. Powiat prowadzi szkoły średnie, województwo zajmuje się rozwojem regionu." },      ],
    },
    // ══ Rozdział 3: Historia Polski ═══════════════════════════════════════
    {
      id: "pl-poczatki",
      title: "Od Mieszka I do Rzeczypospolitej Obojga Narodów",
      section: "Historia Polski",
      badge: "lekcja 10",
      blocks: [
        { type: "callout", variant: "why", text: "Sześćset lat w jednej lekcji — nie po to, żeby je zapamiętać, tylko żeby wiedzieć, skąd biorą się nazwy, które wracają później: Piastowie, Jagiellonowie, Rzeczpospolita." },
        { type: "h3", text: "Chrzest i pierwsze państwo" },
        { type: "p", text: "**Mieszko I** przyjmuje chrzest w **966 roku**. Jego syn **Bolesław Chrobry** koronuje się w **1025** na pierwszego króla Polski. Dynastia nazywa się **Piastami** i rządzi do 1370 roku." },
        { type: "h3", text: "Rozbicie i zjednoczenie" },
        { type: "p", text: "Po śmierci Bolesława Krzywoustego w 1138 roku kraj rozpada się na dzielnice na blisko dwieście lat. Scala go dopiero **Władysław Łokietek**, a jego syn **Kazimierz Wielki** (1333–1370) rozbudowuje państwo — powiada się o nim, że „zastał Polskę drewnianą, a zostawił murowaną”. W **1364** zakłada uniwersytet w Krakowie." },
        { type: "h3", text: "Unia z Litwą" },
        { type: "cards", items: [
          { h4: "1385 — unia w Krewie", p: "Wielki książę litewski Jagiełło żeni się z królową Jadwigą, przyjmuje chrzest i zostaje królem Polski." },
          { h4: "1410 — Grunwald", p: "Wojska polsko-litewskie pokonują zakon krzyżacki w jednej z największych bitew średniowiecznej Europy." },
          { h4: "1569 — unia lubelska", p: "Polska i Litwa tworzą jedno państwo: Rzeczpospolitą Obojga Narodów, ze wspólnym sejmem i wspólnym królem." },
        ] },
        { type: "h3", text: "Szlachecka republika" },
        { type: "p", text: "Rzeczpospolita jest monarchią, ale króla **wybiera szlachta** w wolnej elekcji. Sejm decyduje o podatkach i wojnie. Zasada **liberum veto** pozwala jednemu posłowi zerwać obrady — z czasem paraliżuje państwo." },
        { type: "quiz",
          q: "W którym roku odbyła się bitwa pod Grunwaldem?",
          options: [
            { text: "1385", correct: false },
            { text: "1410", correct: true },
            { text: "1569", correct: false },
            { text: "1683", correct: false },
          ],
          explanation: "1410. 1385 to unia w Krewie, 1569 unia lubelska, 1683 odsiecz wiedeńska." },
        { type: "h3", text: "Gniezno i Kraków" },
        { type: "p", text: "Pierwszą stolicą było **Gniezno**, gdzie w **1000 roku** cesarz Otton III spotkał się z Bolesławem Chrobrym. Od XI wieku ośrodkiem władzy stał się **Kraków**, na Wawelu koronowano królów aż do XVIII wieku." },
        { type: "h3", text: "Złoty wiek" },
        { type: "p", text: "XVI stulecie nazywa się **złotym wiekiem**: rozkwitają nauka i literatura, **Mikołaj Kopernik** ogłasza teorię heliocentryczną, a **Jan Kochanowski** pisze po polsku zamiast po łacinie." },
        { type: "quiz",
          q: "Który uniwersytet założono w Krakowie w 1364 roku?",
          options: [
            { text: "Uniwersytet Warszawski", correct: false },
            { text: "Uniwersytet Jagielloński", correct: true },
            { text: "Uniwersytet Wrocławski", correct: false },
            { text: "Politechnika Gdańska", correct: false },
          ],
          explanation: "Uniwersytet Jagielloński, jedna z najstarszych uczelni Europy. Uniwersytet Warszawski powstał w 1816 roku." },      ],
    },
    {
      id: "pl-rozbiory",
      title: "Rozbiory i walka o niepodległość",
      section: "Historia Polski",
      badge: "lekcja 11",
      blocks: [
        { type: "h3", text: "Trzy rozbiory" },
        { type: "p", text: "Osłabioną Rzeczpospolitą dzielą między siebie **Rosja, Prusy i Austria**: w **1772**, **1793** i **1795** roku. Po trzecim rozbiorze państwo polskie **znika z mapy na 123 lata**." },
        { type: "h3", text: "Próba ratunku" },
        { type: "p", text: "Cztery lata przed końcem Sejm Czteroletni uchwala **Konstytucję 3 maja 1791** — pierwszą w Europie i drugą na świecie nowoczesną konstytucję spisaną. Znosi liberum veto i wolną elekcję. Sąsiedzi widzą w niej zagrożenie i wkraczają zbrojnie." },
        { type: "h3", text: "Powstania" },
        { type: "cards", items: [
          { h4: "1794 — insurekcja kościuszkowska", p: "Tadeusz Kościuszko prowadzi ostatnią próbę obrony Rzeczypospolitej. Po klęsce następuje trzeci rozbiór." },
          { h4: "1830 — powstanie listopadowe", p: "Wybucha w Warszawie przeciw Rosji. Po klęsce tysiące ludzi emigruje na Zachód." },
          { h4: "1863 — powstanie styczniowe", p: "Największe i najdłuższe. Po nim represje: rusyfikacja, konfiskaty, zsyłki na Sybir." },
        ] },
        { type: "h3", text: "Naród bez państwa" },
        { type: "p", text: "Przez sto dwadzieścia trzy lata polskość trwa w kulturze: w wierszach **Mickiewicza** i **Słowackiego**, w muzyce **Chopina**, w malarstwie **Matejki**. W 1903 roku **Maria Skłodowska-Curie** dostaje Nagrodę Nobla — pierwszą z dwóch." },
        { type: "quiz",
          q: "Ile lat Polski nie było na mapie Europy?",
          options: [
            { text: "50 lat", correct: false },
            { text: "99 lat", correct: false },
            { text: "123 lata", correct: true },
            { text: "150 lat", correct: false },
          ],
          explanation: "123 lata — od trzeciego rozbioru w 1795 do odzyskania niepodległości w 1918." },
        { type: "h3", text: "Trzej zaborcy, trzy porządki" },
        { type: "cards", items: [
          { h4: "Zabór rosyjski", p: "Największy. Po powstaniach nasilona rusyfikacja i zsyłki." },
          { h4: "Zabór pruski", p: "Silna germanizacja, ale i lepsza gospodarka oraz powszechna szkoła." },
          { h4: "Zabór austriacki", p: "Galicja, uboga, lecz od 1867 roku z autonomią: polskie szkoły i sejm we Lwowie." },
        ] },
        { type: "h3", text: "Praca zamiast powstania" },
        { type: "p", text: "Po klęsce 1863 roku część działaczy odchodzi od zbrojnych zrywów na rzecz **pracy organicznej**: zakładania szkół, spółdzielni i czytelni. Spór między walką a pracą u podstaw przewija się przez cały wiek XIX." },
        { type: "quiz",
          q: "Które powstanie wybuchło w 1863 roku?",
          options: [
            { text: "Listopadowe", correct: false },
            { text: "Styczniowe", correct: true },
            { text: "Warszawskie", correct: false },
            { text: "Wielkopolskie", correct: false },
          ],
          explanation: "Styczniowe. Listopadowe to 1830, wielkopolskie 1918, warszawskie 1944." },      ],
    },
    {
      id: "pl-druga-rp",
      title: "II Rzeczpospolita",
      section: "Historia Polski",
      badge: "lekcja 12",
      blocks: [
        { type: "h3", text: "11 listopada 1918" },
        { type: "p", text: "Gdy trzy zaborcze mocarstwa przegrywają albo rozpadają się w I wojnie światowej, Polska wraca. **11 listopada 1918** Rada Regencyjna przekazuje **Józefowi Piłsudskiemu** władzę wojskową. Dzień ten jest dziś **Narodowym Świętem Niepodległości**." },
        { type: "h3", text: "Granice trzeba było wywalczyć" },
        { type: "p", text: "Kształt państwa ustala się w walkach i plebiscytach: powstanie wielkopolskie, trzy powstania śląskie, wojna z Rosją bolszewicką. **Bitwa Warszawska w sierpniu 1920** zatrzymuje ofensywę na zachód — nazywa się ją „cudem nad Wisłą”." },
        { type: "h3", text: "Państwo od zera" },
        { type: "cards", items: [
          { h4: "Jedna waluta", p: "Trzy systemy prawne, trzy koleje, cztery waluty. W 1924 roku reforma Grabskiego wprowadza złotego." },
          { h4: "Gdynia", p: "Port budowany od podstaw od 1926 roku daje krajowi własne wyjście na Bałtyk." },
          { h4: "Konstytucja marcowa", p: "1921 — republika parlamentarna. W 1935 zastępuje ją kwietniowa, wzmacniająca prezydenta." },
        ] },
        { type: "h3", text: "Kraj wielu narodów" },
        { type: "p", text: "W II Rzeczypospolitej mieszkają Polacy, Ukraińcy, Żydzi, Białorusini, Niemcy i Litwini. Około **jednej trzeciej** mieszkańców to mniejszości narodowe — więcej niż dziś." },
        { type: "quiz",
          q: "Jak nazywa się bitwa z sierpnia 1920 roku, która zatrzymała ofensywę bolszewicką?",
          options: [
            { text: "Bitwa pod Grunwaldem", correct: false },
            { text: "Bitwa Warszawska", correct: true },
            { text: "Bitwa pod Wiedniem", correct: false },
            { text: "Bitwa nad Bzurą", correct: false },
          ],
          explanation: "Bitwa Warszawska, zwana cudem nad Wisłą. Bzura to wrzesień 1939, Wiedeń 1683, Grunwald 1410." },
        { type: "h3", text: "Zamach majowy" },
        { type: "p", text: "W **maju 1926** Piłsudski przeprowadza zamach stanu. Zaczyna się okres **sanacji** — rządów obozu piłsudczykowskiego, w których rola parlamentu maleje. Piłsudski umiera w 1935 roku." },
        { type: "h3", text: "Kultura międzywojnia" },
        { type: "p", text: "Dwudziestolecie to czas **Tuwima**, **Witkacego** i **Gombrowicza**, kabaretu warszawskiego i pierwszego polskiego radia. W 1924 roku powstaje Polskie Radio, a filmy kręci się w Warszawie i Wilnie." },
        { type: "quiz",
          q: "Kto przeprowadził zamach majowy w 1926 roku?",
          options: [
            { text: "Roman Dmowski", correct: false },
            { text: "Józef Piłsudski", correct: true },
            { text: "Ignacy Paderewski", correct: false },
            { text: "Wincenty Witos", correct: false },
          ],
          explanation: "Józef Piłsudski. Dmowski był jego głównym przeciwnikiem politycznym, Paderewski pianistą i premierem w 1919 roku." },      ],
    },
    {
      id: "pl-wojna",
      title: "II wojna światowa i okupacja",
      section: "Historia Polski",
      badge: "lekcja 13",
      blocks: [
        { type: "callout", variant: "why", text: "Sześć lat, które zmieniły granice, ludność i krajobraz kraju bardziej niż cokolwiek wcześniej. Bez nich nie da się zrozumieć ani dzisiejszej mapy, ani dzisiejszych świąt." },
        { type: "h3", text: "Wrzesień 1939" },
        { type: "p", text: "**1 września 1939** Niemcy atakują Polskę — wojna zaczyna się od ostrzału **Westerplatte**. **17 września** od wschodu wkracza Związek Radziecki, wykonując tajny protokół paktu Ribbentrop–Mołotow. Państwo zostaje podzielone między dwóch okupantów." },
        { type: "h3", text: "Okupacja" },
        { type: "p", text: "Niemcy prowadzą na ziemiach polskich **Zagładę**: w obozach, z których największym był **Auschwitz-Birkenau**, ginie około trzech milionów polskich Żydów. Sowieci wywożą setki tysięcy ludzi na wschód, a wiosną 1940 mordują w **Katyniu** i innych miejscach blisko 22 tysiące polskich oficerów." },
        { type: "h3", text: "Państwo Podziemne" },
        { type: "cards", items: [
          { h4: "Armia Krajowa", p: "Największa podziemna armia okupowanej Europy, podległa rządowi w Londynie." },
          { h4: "Tajne nauczanie", p: "Szkoły i uniwersytety działały w mieszkaniach, mimo kary śmierci za nauczanie." },
          { h4: "Powstanie w getcie", p: "Kwiecień 1943: zryw skazany z góry, podjęty, by zginąć z bronią w ręku." },
          { h4: "Powstanie Warszawskie", p: "1 sierpnia 1944, 63 dni walki. Miasto zostaje po nim celowo zburzone." },
        ] },
        { type: "h3", text: "Bilans" },
        { type: "p", text: "Polska traci około **6 milionów** obywateli — blisko jedną piątą ludności. Granice przesuwają się na zachód: kraj traci Kresy Wschodnie, zyskuje ziemie nad Odrą i Bałtykiem. Miliony ludzi zostają przesiedlone." },
        { type: "quiz",
          q: "Którego dnia rozpoczęła się II wojna światowa atakiem na Polskę?",
          options: [
            { text: "17 września 1939", correct: false },
            { text: "1 września 1939", correct: true },
            { text: "1 sierpnia 1944", correct: false },
            { text: "8 maja 1945", correct: false },
          ],
          explanation: "1 września 1939. 17 września to wkroczenie ZSRR, 1 sierpnia 1944 to Powstanie Warszawskie, 8 maja 1945 to koniec wojny w Europie." },
        { type: "h3", text: "Polacy poza krajem" },
        { type: "p", text: "Rząd przeniósł się do **Londynu**. Polscy lotnicy walczyli w bitwie o Anglię — najskuteczniejszy był **dywizjon 303**. Żołnierze generała Andersa przeszli przez Bliski Wschód do Włoch i w 1944 roku zdobyli **Monte Cassino**." },
        { type: "h3", text: "Ci, którzy ratowali" },
        { type: "p", text: "Za pomoc Żydom groziła w okupowanej Polsce **kara śmierci**, także dla całej rodziny. Mimo to działała **Żegota** — Rada Pomocy Żydom. Polacy stanowią najliczniejszą grupę wśród odznaczonych tytułem **Sprawiedliwy wśród Narodów Świata**." },
        { type: "quiz",
          q: "Jak nazywał się polski dywizjon myśliwski, który wsławił się w bitwie o Anglię?",
          options: [
            { text: "Dywizjon 300", correct: false },
            { text: "Dywizjon 303", correct: true },
            { text: "Dywizjon 316", correct: false },
            { text: "Dywizjon 1", correct: false },
          ],
          explanation: "Dywizjon 303 imienia Tadeusza Kościuszki, jeden z najskuteczniejszych w całej bitwie." },      ],
    },
    {
      id: "pl-prl",
      title: "PRL i Solidarność",
      section: "Historia Polski",
      badge: "lekcja 14",
      blocks: [
        { type: "h3", text: "Polska Rzeczpospolita Ludowa" },
        { type: "p", text: "Po wojnie Polska znajduje się w strefie wpływów Związku Radzieckiego. Władzę sprawuje jedna partia — **PZPR**. Gospodarka jest planowana centralnie, prywatny przemysł znacjonalizowany, granica zachodnia potwierdzona dopiero układami z lat 1970 i 1990." },
        { type: "h3", text: "Bunty" },
        { type: "cards", items: [
          { h4: "1956 — Poznań", p: "Robotniczy protest stłumiony wojskiem; zapoczątkował odwilż." },
          { h4: "1968 — Marzec", p: "Protesty studenckie i antysemicka kampania, po której kraj opuszcza kilkanaście tysięcy osób." },
          { h4: "1970 — Wybrzeże", p: "Strajki przeciw podwyżkom cen, stłumione strzałami do robotników." },
          { h4: "1976 — Radom i Ursus", p: "Kolejne strajki; powstaje Komitet Obrony Robotników." },
        ] },
        { type: "h3", text: "Solidarność" },
        { type: "p", text: "W **sierpniu 1980** strajk w Stoczni Gdańskiej kończy się **porozumieniami sierpniowymi**. Powstaje **NSZZ „Solidarność”** — pierwszy niezależny związek zawodowy w bloku wschodnim, z **Lechem Wałęsą** na czele. W szczytowym momencie liczy blisko dziesięć milionów członków." },
        { type: "h3", text: "Stan wojenny" },
        { type: "p", text: "**13 grudnia 1981** generał Wojciech Jaruzelski wprowadza **stan wojenny**. Solidarność zostaje zdelegalizowana, tysiące działaczy internowanych. Związek działa dalej w podziemiu." },
        { type: "callout", variant: "warn", text: "Wybór **Karola Wojtyły** na papieża w **1978** i jego pielgrzymka do Polski rok później są dla wielu badaczy jednym z warunków tego, co stało się w 1980 roku." },
        { type: "quiz",
          q: "W którym roku wprowadzono w Polsce stan wojenny?",
          options: [
            { text: "1970", correct: false },
            { text: "1976", correct: false },
            { text: "1981", correct: true },
            { text: "1989", correct: false },
          ],
          explanation: "13 grudnia 1981 roku. 1980 to powstanie Solidarności, 1989 to wybory czerwcowe." },
        { type: "h3", text: "Życie codzienne w PRL" },
        { type: "p", text: "Gospodarka niedoboru oznaczała **kolejki** i **kartki** na mięso, cukier czy buty. Mieszkania przydzielała spółdzielnia, a na samochód czekało się latami. Paszport trzymał urząd i trzeba było o niego prosić." },
        { type: "h3", text: "Kultura mimo cenzury" },
        { type: "p", text: "Mimo cenzury powstawały film, teatr i muzyka, które znano poza krajem: szkoła filmowa w Łodzi, plakat polski, jazz. Obok tego działał **drugi obieg** — książki drukowane i kolportowane nielegalnie." },
        { type: "quiz",
          q: "W którym roku powstała Solidarność?",
          options: [
            { text: "1976", correct: false },
            { text: "1980", correct: true },
            { text: "1981", correct: false },
            { text: "1989", correct: false },
          ],
          explanation: "W sierpniu 1980 roku, po strajku w Stoczni Gdańskiej. W 1981 wprowadzono stan wojenny." },      ],
    },
    {
      id: "pl-trzecia-rp",
      title: "1989 i III Rzeczpospolita",
      section: "Historia Polski",
      badge: "lekcja 15",
      blocks: [
        { type: "h3", text: "Okrągły Stół" },
        { type: "p", text: "Wiosną **1989** władza i opozycja siadają do rozmów przy **Okrągłym Stole**. Ustalają częściowo wolne wybory: o 35 procent miejsc w Sejmie wolno ubiegać się każdemu, Senat jest wolny w całości." },
        { type: "h3", text: "4 czerwca 1989" },
        { type: "p", text: "Solidarność zdobywa **wszystkie** mandaty, o które mogła się ubiegać w Sejmie, i **99 na 100** miejsc w Senacie. We wrześniu **Tadeusz Mazowiecki** zostaje pierwszym od czterdziestu lat niekomunistycznym premierem w bloku wschodnim." },
        { type: "h3", text: "Przemiany lat dziewięćdziesiątych" },
        { type: "cards", items: [
          { h4: "Gospodarka", p: "Plan Balcerowicza otwiera rynek. Ceny rosną, przedsiębiorstwa upadają, ale półki pustoszeć przestają." },
          { h4: "Samorząd", p: "1990: pierwsze wolne wybory samorządowe i odrodzenie gmin." },
          { h4: "Konstytucja", p: "1997: nowa ustawa zasadnicza zastępuje poprawianą konstytucję z 1952 roku." },
          { h4: "Reforma administracyjna", p: "1999: 49 województw zastąpiono 16, przywrócono powiaty." },
        ] },
        { type: "h3", text: "Miejsce w Europie" },
        { type: "p", text: "W **1999** Polska wstępuje do **NATO**, w **2004** do **Unii Europejskiej** — po referendum, w którym za opowiedziało się ponad trzy czwarte głosujących. Od **2007** należy do strefy Schengen; waluty euro nie przyjęła." },
        { type: "quiz",
          q: "W którym roku Polska wstąpiła do Unii Europejskiej?",
          options: [
            { text: "1989", correct: false },
            { text: "1999", correct: false },
            { text: "2004", correct: true },
            { text: "2007", correct: false },
          ],
          explanation: "1 maja 2004. 1999 to wejście do NATO, 2007 to strefa Schengen." },
        { type: "h3", text: "Prezydenci III Rzeczypospolitej" },
        { type: "p", text: "Pierwszym prezydentem wybranym w wyborach powszechnych został w **1990 roku Lech Wałęsa**. Po nim urząd sprawowali kolejno Aleksander Kwaśniewski, Lech Kaczyński, Bronisław Komorowski i Andrzej Duda." },
        { type: "h3", text: "Katastrofa smoleńska" },
        { type: "p", text: "**10 kwietnia 2010** w katastrofie samolotu pod Smoleńskiem zginęło 96 osób, w tym prezydent **Lech Kaczyński** z małżonką oraz wielu przedstawicieli władz. Delegacja leciała na obchody rocznicy zbrodni katyńskiej." },
        { type: "quiz",
          q: "Kto był pierwszym prezydentem wybranym w wyborach powszechnych po 1989 roku?",
          options: [
            { text: "Wojciech Jaruzelski", correct: false },
            { text: "Lech Wałęsa", correct: true },
            { text: "Aleksander Kwaśniewski", correct: false },
            { text: "Tadeusz Mazowiecki", correct: false },
          ],
          explanation: "Lech Wałęsa, w 1990 roku. Jaruzelskiego wybrało Zgromadzenie Narodowe w 1989, Mazowiecki był premierem." },      ],
    },
    // ══ Rozdział 4: Geografia, gospodarka i Polska w świecie ══════════════
    {
      id: "pl-geografia",
      title: "Geografia i regiony",
      section: "Geografia, gospodarka i Polska w świecie",
      badge: "lekcja 16",
      blocks: [
        { type: "h3", text: "Położenie i sąsiedzi" },
        { type: "p", text: "Polska leży w Europie Środkowej i graniczy z **siedmioma** państwami: Niemcami, Czechami, Słowacją, Ukrainą, Białorusią, Litwą i Rosją (obwód kaliningradzki). Od północy ma dostęp do **Morza Bałtyckiego**." },
        { type: "h3", text: "Ukształtowanie terenu" },
        { type: "p", text: "Kraj opada z południa na północ: **góry** na granicy południowej, **wyżyny** w środku, **niziny** na północy, **pojezierza** i wybrzeże. Najwyższy szczyt to **Rysy** w Tatrach — **2499 m n.p.m.** Powierzchnia kraju to około **312 700 km²**." },
        { type: "h3", text: "Rzeki i jeziora" },
        { type: "cards", items: [
          { h4: "Wisła", p: "Najdłuższa rzeka, 1047 km. Płynie z gór na północ, przez Kraków i Warszawę, do Bałtyku pod Gdańskiem." },
          { h4: "Odra", p: "Druga co do długości, na znacznym odcinku granica z Niemcami." },
          { h4: "Mazury", p: "Kraina tysiąca jezior na północnym wschodzie; największe z nich to Śniardwy." },
          { h4: "Puszcza Białowieska", p: "Ostatni fragment pierwotnej puszczy niżowej Europy, wpisany na listę UNESCO. Żyją tu żubry." },
        ] },
        { type: "h3", text: "Krainy historyczne" },
        { type: "p", text: "Poza podziałem administracyjnym mówi się o krainach: **Mazowsze** wokół Warszawy, **Małopolska** wokół Krakowa, **Wielkopolska** wokół Poznania, **Śląsk** na południowym zachodzie, **Pomorze** nad morzem, **Mazury** i **Podlasie** na wschodzie." },
        { type: "quiz",
          q: "Jak nazywa się najwyższy szczyt Polski?",
          options: [
            { text: "Śnieżka", correct: false },
            { text: "Rysy", correct: true },
            { text: "Giewont", correct: false },
            { text: "Babia Góra", correct: false },
          ],
          explanation: "Rysy w Tatrach, 2499 m. Śnieżka to najwyższy szczyt Karkonoszy, Giewont jest niższy i leży nad Zakopanem." },
        { type: "h3", text: "Klimat" },
        { type: "p", text: "Klimat jest **umiarkowany przejściowy**: między morskim z zachodu a kontynentalnym ze wschodu. Dlatego pogoda bywa zmienna, a zimy raz łagodne, raz mroźne. Występują wszystkie **cztery pory roku**." },
        { type: "h3", text: "Parki narodowe" },
        { type: "p", text: "Jest ich **23**. Najstarsze to Białowieski i Pieniński, najwyżej położony — **Tatrzański**. Nad morzem leży Słowiński z ruchomymi wydmami, które przesuwają się o kilka metrów rocznie." },
        { type: "quiz",
          q: "Która rzeka jest najdłuższa w Polsce?",
          options: [
            { text: "Odra", correct: false },
            { text: "Warta", correct: false },
            { text: "Wisła", correct: true },
            { text: "Bug", correct: false },
          ],
          explanation: "Wisła, 1047 km. Odra jest druga, Warta jest dopływem Odry." },      ],
    },
    {
      id: "pl-miasta",
      title: "Podział administracyjny i miasta",
      section: "Geografia, gospodarka i Polska w świecie",
      badge: "lekcja 17",
      blocks: [
        { type: "h3", text: "Szesnaście województw" },
        { type: "p", text: "Od reformy z **1999 roku** kraj dzieli się na **16 województw**. Wcześniej było ich 49. Każde ma stolicę — a dwa z nich mają po dwie: w kujawsko-pomorskim sejmik obraduje w Toruniu, a wojewoda urzęduje w Bydgoszczy; w lubuskim podobnie dzielą się Zielona Góra i Gorzów Wielkopolski." },
        { type: "h3", text: "Największe miasta" },
        { type: "cards", items: [
          { h4: "Warszawa", p: "Stolica od 1596 roku, około 1,8 miliona mieszkańców. Siedziba Sejmu, Senatu, Prezydenta i rządu." },
          { h4: "Kraków", p: "Dawna stolica i miejsce koronacji królów. Uniwersytet Jagielloński działa od 1364 roku." },
          { h4: "Łódź, Wrocław, Poznań", p: "Kolejne co do wielkości. Wrocław leży nad Odrą, Poznań nad Wartą." },
          { h4: "Gdańsk", p: "Główny port, miasto porozumień sierpniowych i początku Solidarności." },
        ] },
        { type: "h3", text: "Ludność" },
        { type: "p", text: "W Polsce mieszka około **37–38 milionów** osób. Kraj jest dziś **jednolity narodowościowo** — inaczej niż przed wojną, gdy jedną trzecią mieszkańców stanowiły mniejszości. Uznanych mniejszości narodowych i etnicznych jest **dziewięć i cztery**, a językiem regionalnym jest **kaszubski**." },
        { type: "callout", variant: "warn", text: "Stolicą Polski nie zawsze była Warszawa. Najpierw było **Gniezno**, potem przez pół tysiąclecia **Kraków**; przeniesienie dworu do Warszawy nastąpiło za Zygmunta III Wazy pod koniec XVI wieku." },
        { type: "quiz",
          q: "Ile województw ma Polska?",
          options: [
            { text: "12", correct: false },
            { text: "16", correct: true },
            { text: "24", correct: false },
            { text: "49", correct: false },
          ],
          explanation: "16 od reformy z 1999 roku. Wcześniej było 49." },
        { type: "h3", text: "Zabytki na liście UNESCO" },
        { type: "cards", items: [
          { h4: "Kraków", p: "Historyczne centrum, wpisane w 1978 roku wśród pierwszych obiektów na świecie." },
          { h4: "Wieliczka", p: "Kopalnia soli czynna od średniowiecza, z kaplicami wykutymi w solnej skale." },
          { h4: "Warszawa", p: "Starówka odbudowana po wojnie — wpisana właśnie za tę odbudowę." },
          { h4: "Auschwitz-Birkenau", p: "Miejsce pamięci, zachowane jako świadectwo." },
        ] },
        { type: "h3", text: "Miasta wojewódzkie" },
        { type: "p", text: "Stolicami województw są między innymi Warszawa, Kraków, Łódź, Wrocław, Poznań, Gdańsk, Szczecin, Lublin, Białystok, Katowice, Rzeszów, Kielce, Olsztyn i Opole." },
        { type: "quiz",
          q: "Które miasto było stolicą Polski przed Warszawą?",
          options: [
            { text: "Gdańsk", correct: false },
            { text: "Poznań", correct: false },
            { text: "Kraków", correct: true },
            { text: "Wrocław", correct: false },
          ],
          explanation: "Kraków, przez blisko pięćset lat. Jeszcze wcześniej stolicą było Gniezno." },      ],
    },
    {
      id: "pl-gospodarka",
      title: "Gospodarka i praca",
      section: "Geografia, gospodarka i Polska w świecie",
      badge: "lekcja 18",
      blocks: [
        { type: "h3", text: "Waluta" },
        { type: "p", text: "Walutą jest **złoty (PLN)**, dzielony na 100 groszy. Polska należy do Unii Europejskiej, ale **nie przyjęła euro** — zobowiązała się do tego w traktacie akcesyjnym, bez wyznaczonej daty. Pieniądz emituje **Narodowy Bank Polski**." },
        { type: "h3", text: "Praca" },
        { type: "cards", items: [
          { h4: "Umowa o pracę", p: "Daje urlop, ochronę przed zwolnieniem i składki. Obok niej działają umowy zlecenia i o dzieło." },
          { h4: "Płaca minimalna", p: "Ustalana co roku rozporządzeniem Rady Ministrów, obowiązuje wszystkich pracowników." },
          { h4: "Czas pracy", p: "Zasadniczo 8 godzin dziennie i 40 tygodniowo, przeciętnie w przyjętym okresie rozliczeniowym." },
          { h4: "Urlop", p: "20 dni przy stażu poniżej 10 lat, 26 dni powyżej. Nauka wlicza się do stażu." },
        ] },
        { type: "h3", text: "Podatki i składki" },
        { type: "p", text: "Podatek dochodowy od osób fizycznych (**PIT**) jest progresywny. Do tego dochodzą składki na **ZUS** — emerytalna, rentowa, chorobowa i wypadkowa — oraz składka zdrowotna na **NFZ**. Podstawowa stawka **VAT** wynosi 23 procent, na żywność i książki jest niższa." },
        { type: "h3", text: "Czym Polska żyje" },
        { type: "p", text: "Gospodarka opiera się na przemyśle, usługach i rolnictwie. Kraj jest dużym producentem żywności, mebli, sprzętu AGD i części samochodowych, a od lat dziewięćdziesiątych rośnie w nim sektor informatyczny i usług dla biznesu." },
        { type: "quiz",
          q: "Jaka jest waluta Polski?",
          options: [
            { text: "Euro", correct: false },
            { text: "Korona", correct: false },
            { text: "Złoty", correct: true },
            { text: "Marka", correct: false },
          ],
          explanation: "Złoty, dzielony na 100 groszy. Polska jest w Unii Europejskiej, ale euro nie przyjęła." },
        { type: "h3", text: "Zakładanie działalności" },
        { type: "p", text: "Jednoosobową działalność gospodarczą rejestruje się w **CEIDG** — bezpłatnie i przez internet. Spółki wpisuje się do **KRS**. Do rozliczeń potrzebny jest numer **NIP**, a przy zatrudnianiu zgłoszenie do ZUS." },
        { type: "h3", text: "Emerytura" },
        { type: "p", text: "Wiek emerytalny wynosi **60 lat dla kobiet** i **65 lat dla mężczyzn**. Wysokość świadczenia zależy od sumy odprowadzonych składek i przewidywanej długości życia — im dłużej się pracuje, tym wyższa emerytura." },
        { type: "quiz",
          q: "Gdzie rejestruje się jednoosobową działalność gospodarczą?",
          options: [
            { text: "W CEIDG", correct: true },
            { text: "W KRS", correct: false },
            { text: "W ZUS", correct: false },
            { text: "W urzędzie wojewódzkim", correct: false },
          ],
          explanation: "W CEIDG, bezpłatnie i przez internet. KRS jest rejestrem spółek." },      ],
    },
    {
      id: "pl-swiat",
      title: "Polska w Unii Europejskiej i NATO",
      section: "Geografia, gospodarka i Polska w świecie",
      badge: "lekcja 19",
      blocks: [
        { type: "h3", text: "Dwie daty" },
        { type: "p", text: "**1999** — wejście do **NATO**, razem z Czechami i Węgrami. **2004** — wejście do **Unii Europejskiej**, razem z dziewięcioma innymi państwami, po referendum, w którym wzięło udział blisko 59 procent uprawnionych, a za opowiedziało się ponad trzy czwarte głosujących." },
        { type: "h3", text: "Co daje członkostwo w Unii" },
        { type: "cards", items: [
          { h4: "Swoboda przemieszczania", p: "Wolno mieszkać, pracować i studiować w każdym państwie członkowskim." },
          { h4: "Schengen", p: "Od 2007 roku granice wewnętrzne przekracza się bez kontroli." },
          { h4: "Fundusze", p: "Polska jest jednym z największych odbiorców funduszy spójności — drogi, koleje, oczyszczalnie." },
          { h4: "Parlament Europejski", p: "Polacy wybierają swoich posłów co pięć lat, w wyborach bezpośrednich." },
        ] },
        { type: "h3", text: "Sąsiedztwo i bezpieczeństwo" },
        { type: "p", text: "Polska graniczy z **Ukrainą, Białorusią i Rosją**, więc granica wschodnia kraju jest zarazem zewnętrzną granicą Unii Europejskiej i NATO. Współpracuje też w formatach regionalnych — **Grupa Wyszehradzka** z Czechami, Słowacją i Węgrami oraz **Trójkąt Weimarski** z Niemcami i Francją." },
        { type: "h3", text: "Polacy poza krajem" },
        { type: "p", text: "**Polonia** — Polacy i osoby polskiego pochodzenia mieszkające za granicą — liczy według szacunków kilkanaście do dwudziestu milionów osób. Największe skupiska są w Stanach Zjednoczonych, Niemczech i Wielkiej Brytanii." },
        { type: "quiz",
          q: "W którym roku Polska wstąpiła do NATO?",
          options: [
            { text: "1989", correct: false },
            { text: "1999", correct: true },
            { text: "2004", correct: false },
            { text: "2007", correct: false },
          ],
          explanation: "1999, pięć lat przed wejściem do Unii Europejskiej. 2007 to strefa Schengen." },
        { type: "h3", text: "Prawo europejskie" },
        { type: "p", text: "Prawo Unii Europejskiej obowiązuje w Polsce bezpośrednio, a **Trybunał Sprawiedliwości Unii Europejskiej** w Luksemburgu czuwa nad jego stosowaniem. Osobno działa **Europejski Trybunał Praw Człowieka** w Strasburgu, do którego można złożyć skargę po wyczerpaniu drogi krajowej." },
        { type: "h3", text: "Pomoc dla Ukrainy" },
        { type: "p", text: "Po pełnoskalowej agresji Rosji na Ukrainę w **2022 roku** przez Polskę przeszły miliony uchodźców, a kilkaset tysięcy zostało na dłużej. Był to największy ruch ludności w tej części Europy od czasu II wojny światowej." },
        { type: "quiz",
          q: "Który trybunał rozpatruje skargi na naruszenie praw człowieka po wyczerpaniu drogi krajowej?",
          options: [
            { text: "Trybunał Konstytucyjny", correct: false },
            { text: "Europejski Trybunał Praw Człowieka w Strasburgu", correct: true },
            { text: "Trybunał Stanu", correct: false },
            { text: "Sąd Najwyższy", correct: false },
          ],
          explanation: "Trybunał w Strasburgu. Ten w Luksemburgu zajmuje się prawem Unii, a nie skargami indywidualnymi tego rodzaju." },      ],
    },
    // ══ Rozdział 5: Społeczeństwo i życie codzienne ═══════════════════════
    {
      id: "pl-religia",
      title: "Religia i tradycje",
      section: "Społeczeństwo i życie codzienne",
      badge: "lekcja 20",
      blocks: [
        { type: "h3", text: "Kościół i państwo" },
        { type: "p", text: "Konstytucja zapewnia **wolność sumienia i wyznania**, a państwo jest **bezstronne** w sprawach przekonań religijnych. Nie ma religii państwowej. Stosunki z Kościołem katolickim reguluje **konkordat** ze Stolicą Apostolską z 1993 roku." },
        { type: "h3", text: "Kto w co wierzy" },
        { type: "p", text: "Zdecydowana większość mieszkańców deklaruje wyznanie **rzymskokatolickie**, choć udział praktykujących od lat maleje, zwłaszcza w miastach i wśród młodych. Obecne są też **prawosławie** — najliczniej na Podlasiu — oraz protestantyzm, judaizm i islam, ten ostatni między innymi wśród **Tatarów polskich**, osiadłych tu od stuleci." },
        { type: "h3", text: "Jan Paweł II" },
        { type: "p", text: "Wybór **Karola Wojtyły** na papieża w **1978 roku** i jego pielgrzymki do kraju miały znaczenie wykraczające poza religię: dla wielu badaczy są jednym z warunków tego, co wydarzyło się w 1980 roku." },
        { type: "callout", variant: "warn", text: "Religia w szkole publicznej jest **nieobowiązkowa**. Rodzice albo pełnoletni uczniowie decydują, czy dziecko chodzi na religię, na etykę, czy na żadne z nich." },
        { type: "quiz",
          q: "Jaki jest stosunek państwa polskiego do wyznań według Konstytucji?",
          options: [
            { text: "Katolicyzm jest religią państwową", correct: false },
            { text: "Państwo jest bezstronne w sprawach przekonań religijnych", correct: true },
            { text: "Wyznawanie religii jest zakazane", correct: false },
            { text: "Religię wybiera wojewoda", correct: false },
          ],
          explanation: "Państwo jest bezstronne, a każdemu przysługuje wolność sumienia i wyznania. Religii państwowej nie ma." },
        { type: "h3", text: "Miejsca pielgrzymek" },
        { type: "p", text: "Najważniejszym jest **Jasna Góra** w Częstochowie z obrazem Matki Boskiej Częstochowskiej. Sierpniowe piesze pielgrzymki idą tam z całego kraju, niektóre po kilkanaście dni." },
        { type: "h3", text: "Mniejszości wyznaniowe" },
        { type: "p", text: "Prawosławni najliczniej mieszkają na **Podlasiu**, ewangelicy na **Śląsku Cieszyńskim**. Meczety Tatarów polskich w **Kruszynianach** i **Bohonikach** stoją tam od stuleci." },
        { type: "quiz",
          q: "Gdzie znajduje się najważniejsze sanktuarium pielgrzymkowe w Polsce?",
          options: [
            { text: "W Krakowie", correct: false },
            { text: "W Częstochowie", correct: true },
            { text: "W Gnieźnie", correct: false },
            { text: "W Licheniu", correct: false },
          ],
          explanation: "Jasna Góra w Częstochowie. Gniezno jest siedzibą prymasa, ale nie głównym miejscem pielgrzymek." },      ],
    },
    {
      id: "pl-swieta",
      title: "Święta i kalendarz",
      section: "Społeczeństwo i życie codzienne",
      badge: "lekcja 21",
      blocks: [
        { type: "callout", variant: "why", text: "Trzy daty wracają najczęściej i najłatwiej je pomylić: 3 maja, 11 listopada i 1 sierpnia. Pierwsza to konstytucja, druga niepodległość, trzecia powstanie." },
        { type: "h3", text: "Święta państwowe" },
        { type: "cards", items: [
          { h4: "3 maja", p: "Święto Konstytucji 3 Maja — rocznica ustawy z 1791 roku. Dzień wolny od pracy." },
          { h4: "11 listopada", p: "Narodowe Święto Niepodległości — rocznica roku 1918. Dzień wolny od pracy." },
          { h4: "1 sierpnia", p: "Godzina „W”: o 17.00 syreny w Warszawie upamiętniają Powstanie Warszawskie. Dniem wolnym nie jest." },
        ] },
        { type: "h3", text: "Święta kościelne wolne od pracy" },
        { type: "p", text: "Wolne są między innymi **Wielkanoc** z poniedziałkiem wielkanocnym, **Boże Ciało**, **15 sierpnia** (Wniebowzięcie, zarazem Święto Wojska Polskiego), **1 listopada** (Wszystkich Świętych) oraz **25 i 26 grudnia**." },
        { type: "h3", text: "Zwyczaje" },
        { type: "cards", items: [
          { h4: "Wigilia", p: "24 grudnia: dwanaście potraw, opłatek, wolne miejsce przy stole, kolacja po pierwszej gwiazdce." },
          { h4: "Śmigus-dyngus", p: "Poniedziałek wielkanocny, gdy polewa się wodą — zwyczaj starszy niż chrześcijaństwo." },
          { h4: "Andrzejki", p: "Wieczór 29 listopada, wróżby z wosku lanego przez ucho od klucza." },
          { h4: "Imieniny", p: "Bywają obchodzone chętniej niż urodziny, zwłaszcza przez starsze pokolenia." },
        ] },
        { type: "quiz",
          q: "Co upamiętnia święto 3 maja?",
          options: [
            { text: "Odzyskanie niepodległości", correct: false },
            { text: "Uchwalenie Konstytucji 3 maja 1791 roku", correct: true },
            { text: "Wybuch Powstania Warszawskiego", correct: false },
            { text: "Wejście do Unii Europejskiej", correct: false },
          ],
          explanation: "Konstytucję z 1791 roku. Niepodległość to 11 listopada, Powstanie Warszawskie to 1 sierpnia." },
        { type: "h3", text: "Wszystkich Świętych" },
        { type: "p", text: "**1 listopada** miliony ludzi jadą na groby bliskich i stawiają znicze. Cmentarze świecą wtedy przez całą noc — to jeden z najbardziej rozpoznawalnych obrazów polskiego roku." },
        { type: "h3", text: "Rok szkolny i wakacje" },
        { type: "p", text: "Rok szkolny zaczyna się **1 września** i kończy w drugiej połowie czerwca. Wakacje trwają lipiec i sierpień, ferie zimowe dwa tygodnie, w różnych terminach zależnie od województwa." },
        { type: "quiz",
          q: "Co upamiętnia 11 listopada?",
          options: [
            { text: "Uchwalenie Konstytucji", correct: false },
            { text: "Odzyskanie niepodległości w 1918 roku", correct: true },
            { text: "Wybuch Powstania Warszawskiego", correct: false },
            { text: "Wejście do NATO", correct: false },
          ],
          explanation: "Odzyskanie niepodległości. Konstytucja to 3 maja, Powstanie Warszawskie 1 sierpnia." },      ],
    },
    {
      id: "pl-edukacja",
      title: "Edukacja i zdrowie",
      section: "Społeczeństwo i życie codzienne",
      badge: "lekcja 22",
      blocks: [
        { type: "h3", text: "Droga przez szkołę" },
        { type: "p", text: "Dzieci zaczynają od **rocznego przygotowania przedszkolnego** w wieku sześciu lat, potem idzie **ośmioletnia szkoła podstawowa**. Kończy ją **egzamin ósmoklasisty**. Dalej wybiera się **liceum** (4 lata), **technikum** (5 lat) albo **szkołę branżową**." },
        { type: "h3", text: "Matura i studia" },
        { type: "p", text: "**Matura** otwiera drogę na studia; wyniki decydują o przyjęciu na uczelnię. Studia dzielą się na **licencjackie**, **magisterskie** i **doktoranckie**. Studia dzienne na uczelniach publicznych są **bezpłatne**." },
        { type: "h3", text: "Ochrona zdrowia" },
        { type: "cards", items: [
          { h4: "NFZ", p: "Narodowy Fundusz Zdrowia finansuje leczenie ze składek. Ubezpieczony leczy się bezpłatnie." },
          { h4: "Lekarz rodzinny", p: "Pierwszy kontakt; kieruje do specjalisty i prowadzi dokumentację." },
          { h4: "Numer 112", p: "Jeden numer alarmowy do pogotowia, straży i policji, w całej Unii Europejskiej." },
          { h4: "PESEL", p: "Jedenastocyfrowy numer identyfikacyjny; potrzebny u lekarza, w urzędzie i w banku." },
        ] },
        { type: "callout", variant: "warn", text: "Numer **PESEL** zawiera datę urodzenia i płeć: przedostatnia cyfra parzysta oznacza kobietę, nieparzysta mężczyznę." },
        { type: "quiz",
          q: "Ile lat trwa w Polsce szkoła podstawowa?",
          options: [
            { text: "6 lat", correct: false },
            { text: "8 lat", correct: true },
            { text: "9 lat", correct: false },
            { text: "12 lat", correct: false },
          ],
          explanation: "Osiem lat, zakończone egzaminem ósmoklasisty. Liceum trwa cztery lata, technikum pięć." },
        { type: "h3", text: "Uczelnie" },
        { type: "p", text: "Najstarszą uczelnią jest **Uniwersytet Jagielloński** (1364), największą **Uniwersytet Warszawski**. Obok uniwersytetów działają politechniki, uczelnie medyczne, ekonomiczne i artystyczne, a także szkoły prywatne." },
        { type: "h3", text: "Apteki i leki" },
        { type: "p", text: "Leki na receptę wydaje apteka po okazaniu **e-recepty** — kodu przychodzącego SMS-em albo widocznego w aplikacji. Część leków jest refundowana, czyli tańsza dzięki dopłacie NFZ." },
        { type: "quiz",
          q: "Jaki jest numer alarmowy obowiązujący w Polsce i całej Unii Europejskiej?",
          options: [
            { text: "997", correct: false },
            { text: "998", correct: false },
            { text: "112", correct: true },
            { text: "999", correct: false },
          ],
          explanation: "112. Dawne numery 997, 998 i 999 nadal działają, ale 112 łączy ze wszystkimi służbami." },      ],
    },
    {
      id: "pl-codziennosc",
      title: "Codzienność, media i kultura",
      section: "Społeczeństwo i życie codzienne",
      badge: "lekcja 23",
      blocks: [
        { type: "h3", text: "Załatwianie spraw" },
        { type: "p", text: "Sprawy urzędowe załatwia się w **urzędzie gminy** albo **miasta**, a coraz częściej przez internet: **profil zaufany** i aplikacja **mObywatel** zastępują wizytę i papierowy dowód. Meldunek zgłasza się w urzędzie miejsca zamieszkania." },
        { type: "h3", text: "Życie codzienne" },
        { type: "cards", items: [
          { h4: "Zakupy w niedziele", p: "Handel w niedziele jest ograniczony ustawą; otwarte pozostają między innymi piekarnie, stacje paliw i sklepy prowadzone przez właściciela." },
          { h4: "Transport", p: "PKP prowadzi koleje dalekobieżne, w miastach jeżdżą tramwaje i autobusy, bilet kasuje się przy wejściu." },
          { h4: "Kuchnia", p: "Pierogi, bigos, żurek, rosół, kotlet schabowy; obiad bywa jedzony wcześniej niż w Europie Zachodniej." },
          { h4: "Powitanie", p: "„Dzień dobry” do wszystkich, „cześć” do znajomych. Do osoby starszej mówi się „pan” albo „pani”." },
        ] },
        { type: "h3", text: "Media" },
        { type: "p", text: "Działają media **publiczne** — Telewizja Polska i Polskie Radio, finansowane z abonamentu i budżetu — oraz liczne prywatne stacje, gazety i portale. Nad rynkiem czuwa **Krajowa Rada Radiofonii i Telewizji**, wymieniona w Konstytucji." },
        { type: "h3", text: "Kultura" },
        { type: "p", text: "Polska ma pięcioro noblistów literackich: **Sienkiewicza**, **Reymonta**, **Miłosza**, **Szymborską** i **Tokarczuk**. W muzyce najbardziej znany jest **Chopin**, któremu poświęcony jest konkurs pianistyczny odbywający się w Warszawie co pięć lat." },
        { type: "quiz",
          q: "Jak nazywa się aplikacja, w której można nosić dokumenty w telefonie?",
          options: [
            { text: "ePUAP", correct: false },
            { text: "mObywatel", correct: true },
            { text: "PESEL", correct: false },
            { text: "mBank", correct: false },
          ],
          explanation: "mObywatel. PESEL to numer identyfikacyjny, a nie aplikacja." },
        { type: "h3", text: "Mieszkanie" },
        { type: "p", text: "Większość ludzi mieszka **we własnym** mieszkaniu lub domu — udział własności jest jednym z najwyższych w Europie. Przy najmie podpisuje się umowę i zwykle wpłaca kaucję; opłaty za wodę i ogrzewanie często idą osobno, do wspólnoty albo spółdzielni." },
        { type: "h3", text: "Sport" },
        { type: "p", text: "Najpopularniejsze są **piłka nożna** i **siatkówka**; reprezentacja siatkarzy należy do najlepszych na świecie. Zimą kraj ogląda **skoki narciarskie**, a raz w roku ulicami miast biegną tysiące uczestników maratonów." },
        { type: "quiz",
          q: "Ile osób z Polski otrzymało literacką Nagrodę Nobla?",
          options: [
            { text: "Dwie", correct: false },
            { text: "Trzy", correct: false },
            { text: "Pięć", correct: true },
            { text: "Siedem", correct: false },
          ],
          explanation: "Pięć: Sienkiewicz, Reymont, Miłosz, Szymborska i Tokarczuk." },      ],
    },
  ],
};
