/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src\micheonTheme.ts
 * Command: astryx theme build src\micheonTheme.ts
 * Generated: 2026-07-23T11:40:13.471Z
 */

// Generated by astryx theme build
export {};

declare module '@astryxdesign/core/Badge' {
  interface BadgeVariantMap {
    'gray': true;
  }
}
