/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src\micheonTheme.ts
 * Command: astryx theme build src\micheonTheme.ts
 * Generated: 2026-07-23T11:40:13.473Z
 */

/// <reference path="./micheon.variants.d.ts" />
import type { DefinedTheme } from '@astryxdesign/core/theme';
export declare const micheonTheme: DefinedTheme;
